### ISSUE TITLE
Variable names from included function prototypes lost in bndb

### ISSUE THREAD

**Issue by nshp** [Vector35/binaryninja-api#1000]
If I write an include file for binja to type imported functions, it applies the names from those function prototypes to argument variables. If I save and re-open the bndb, those names disappear.

**Comment by joshwatson** [comment]
CONGRATULATIONS ON ISSUE NUMBER 1000

**Comment by nshp** [comment]
Oh, it looks like argument types are lost too.
Interestingly, I think I can see them for an instant after visiting the function for the first time ... then they disappear.

**Comment by bpotchik** [comment]
Fixed in 1.1.1539-dev.
