### ISSUE TITLE
lifting error at PPC call instruction

### ISSUE THREAD

**Issue by lwerdna** [Vector35/binaryninja-api#1002]
at 6e46c the `bl generate_v3` gets lifted to a SET_REG instead of a CALL

additionally, this causes the following block at 6e478 to be missing in the IL view

[libcrypto.so.1.1.zip](https://github.com/Vector35/binaryninja-api/files/1864307/libcrypto.so.1.1.zip)

**Comment by rssor** [comment]
Fixed in build 1.1.1155-dev.
