### ISSUE TITLE
Non-standard Stack Parameters

### ISSUE THREAD

**Issue by resrever** [Vector35/binaryninja-api#1003]
When a nonstandard register is used as a parameter, an "@ register" is shown in the parameter list.  When the nonstandard parameter is on the stack, no indicator is shown.  It would be nice to have some way of seeing a non-standard stack parameter on the UI.  For example, showing "@ [rsp+0xc].d" for arg2 in the attached example
![screenshot from 2018-04-03 11-22-35](https://user-images.githubusercontent.com/29237040/38259381-d9403cba-3732-11e8-9e0a-67a8a840f7ef.png)
.
It looks like all the type information is available programatically, just not cosmetically.

**Comment by plafosse** [comment]
We actually have support for this, but its just a display bug that we're not showing it in the function header.

**Comment by plafosse** [comment]
closing in favor of this: https://github.com/Vector35/binaryninja-api/issues/3340
