### ISSUE TITLE
incorrect SignedValueRange

### ISSUE THREAD

**Issue by lucasduffey** [Vector35/binaryninja-api#1007]
**OS:** Ubuntu 16 LTS
**binja dev:** 1.1.1160-dev

binary: http://pwnable.kr/bin/rsa_calculator

0x400e82 address in `RSA_encrypt` function

possible values for rdx aren't working properly for `movsxd rdx, eax"

After the instruction is executed mouseover for rdx is: `SignedValueRange [ 0 to -1 : 1]` but in gdb the actual value was 5. In MLIL the rdx_3 at 0x400e97 was `SignedValueRange [ 0 to -1 : 1]`

**Comment by bpotchik** [comment]
Fixed in build 1.1.1173-dev.
