### ISSUE TITLE
Export as Assembly

### ISSUE THREAD

**Issue by PeterBortas** [Vector35/binaryninja-api#1011]
The ability to export the contents of a linear assembler view as a text file would be good. As is currently it's not even possible to select all and copy it.

(As discussed in Slack, opening this so it's not forgotten about as UI rewrites are done)

**Comment by plafosse** [comment]
Changed to to reflect the underlying issue #91

**Comment by psifertex** [comment]
More information / duplicate in #2502

**Comment by lwerdna** [comment]
awaiting merge

https://github.com/Vector35/binaryninja/commit/0950b3aa58de1118e8cf4ba544b6e530fe81290c

**Comment by lwerdna** [comment]
merged at https://github.com/Vector35/binaryninja/commit/6463302278675c438c70e1ad0532795c25a863bc
