### ISSUE TITLE
Error creating view of type Mach-O: invalid format

### ISSUE THREAD

**Issue by jespinhara** [Vector35/binaryninja-api#1014]
Binary Ninja Version: 1.1.1142, 32782455
Platform: Windows 10 (10.0)

Guys, I'm trying to load some dylibs using the latest release but I'm getting the _Error creating view of type Mach-O: invalid format_ error.
However, using the Version 1.0.776, Build ID 6573250f or any version before the 1.1.*, everything went well.

I'm attaching one dylib but I have others, let me know if required.

Regards.
[dylib.zip](https://github.com/Vector35/binaryninja-api/files/1897815/dylib.zip)

**Comment by rssor** [comment]
Oops, sorry about that! Fixed in build 1.1.1166-dev.

**Comment by jespinhara** [comment]
No worries mate. Thanks!
