### ISSUE TITLE
BasicBlock.__iter__ incorrect behavior

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#1015]
`BasicBlock.__iter__` returns data for the current disassembly based on the following:
```python
while idx < end:
    data = self.view.read(idx, 16)
    inst_info = self.arch.get_instruction_info(data, idx)
    inst_text = self.arch.get_instruction_text(data, idx)

    yield inst_text
    idx += inst_info.length
```

However, this is an incorrect assumption for architectures that have a larger max instruction size than 16. This should be changed to `data = self.view.read(idx, self.arch.max_instr_length)`

**Comment by psifertex** [comment]
Fixed on latest dev.
