### ISSUE TITLE
Can't type `*` into Hex View

### ISSUE THREAD

**Issue by toolCHAINZ** [Vector35/binaryninja-api#1018]
When I open a new file in Hex View and click in the ascii area, I can't type the `*` character (`0x2a`). Entering in the hex code on the binary side works, of course, but that's annoying.

I've seen this on Mac and Windows (both QWERTY, in case that matters).

**Comment by psifertex** [comment]
This is intended -- `*` in that context is "Follow pointer". If the address under your cursor is a pointer, it will follow it.

I'm closing this for now -- once we have user customizable keystrokes you'll be able to remove this mapping yourself if you prefer, but in the meantime this is by design.

**Comment by psifertex** [comment]
Oh wait, I misunderstood the request. I see what you mean. Yeah, agreed in the ascii side it should probably work.

**Comment by D0ntPanic** [comment]
Fixed in build 1457
