### ISSUE TITLE
Not show field of struct in ARM (ldr)

### ISSUE THREAD

**Issue by saruman9** [Vector35/binaryninja-api#1019]
In ARM executable BinaryNinja not show fields of structure:

![init_enc_key](https://user-images.githubusercontent.com/4244396/38872344-af77dfb2-425b-11e8-8453-4b958048d1cb.png)
![pointer](https://user-images.githubusercontent.com/4244396/38872009-ed314696-425a-11e8-924d-46e788a0ab5a.png)
![struct_pointer](https://user-images.githubusercontent.com/4244396/38872050-03168764-425b-11e8-8b22-e7f519338e0b.png)
![struct](https://user-images.githubusercontent.com/4244396/38872053-0553ead0-425b-11e8-87ac-ef302b4d438f.png)

It should look like this:

```
00016744    ldr r5, [r4] {enc_key}
00016748    ldr r3, [r5, #0x8] {enc_key.field_8}
0001674c    blx r3
00016750    str r0, [r5, #0x14] {enc_key.field_14}
```

**Comment by rssor** [comment]
In the MLIL view is the type of the variable backed by `r5` a `struct enc_struct*`? Are the field accesses not annotated in all views or just the assembly view?

**Comment by saruman9** [comment]
> In the MLIL view is the type of the variable backed by `r5` a `struct enc_struct*`?

Yes. And field of structure shown in MLIL view as:

```
@ 00016744    struct enc_struct* r5_1 = [enc_key].d
@ 00016748    int32_t r3_1 = [r5_1 + 8].d
```
So the field accesses not annotated in all views.

**Comment by rssor** [comment]
It's not showing the name in that instance because the field at offset 8 has a size of 1 byte and the access is 4 bytes. Switching it to a 32 bit type should get the annotations you want.

**Comment by saruman9** [comment]
Oh, my mistake. I used IDA before and it don't care about size of access. Thank you.
