### ISSUE TITLE
missing __hash__ method for MediumLevelILFunction

### ISSUE THREAD

**Issue by quickcoldthought** [Vector35/binaryninja-api#1020]
MediumLevelILBasicBlock has a \_\_hash\_\_ method which assumes that self.il_function which is of type MediumLevelILFunction has implemented a \_\_hash\_\_ method

I took a stab at this with the following implementation, but something else might make more sense?
```
	def __hash__(self):
		if self.source_function is not None:
			return hash(self.source_function)
		else:
			return hash(self.current_address)
```

**Comment by quickcoldthought** [comment]
On slack, @joshwatson mentioned a potential fix:
"When generating _binaryninjacore.py, if you automatically added a `__hash__` method to all of the ctypes classes that was just `return hash(ctypes.addressof(self.contents))`, then in all of the python API classes, you could add a `__hash__` method that was just `return hash(self.handle)` and be done with it"

**Comment by plafosse** [comment]
This was fixed somewhat recently.
