### ISSUE TITLE
Support of `fastcall` calling convention for ARM architecture

### ISSUE THREAD

**Issue by saruman9** [Vector35/binaryninja-api#1021]
BN does not support `fastcall` calling convention for ARM architecture.
```
>>> list(Architecture['armv7'].calling_conventions)
['cdecl', 'linux-syscall']
```

**Comment by rssor** [comment]
`cdecl` is probably the calling convention you want it to be using (and is already the default). The semantics of that calling convention probably exactly match what you're used to seeing labeled as `fastcall`.

**Comment by saruman9** [comment]
So `cdecl` in Binary Ninja indicates, that arguments passes in core registers (`r0`-`r3`) and on the stack?
Additional question: Binary Ninja can set comments for passing arguments of callee in caller function?

**Comment by joshwatson** [comment]
Use MLIL view and you’ll see the arguments in the call. Conversely, you could pretty easily write a callback to comment stuff for you

**Comment by rssor** [comment]
Correct:
```
>>> Architecture['armv7'].calling_conventions['cdecl'].int_arg_regs
['r0', 'r1', 'r2', 'r3']
```
For argument comments, the closest we do automatically at the moment is the 'Show call parameter names' option in the MLIL views:
![screen shot 2018-04-19 at 16 39 41](https://user-images.githubusercontent.com/34997787/39017232-b20d5b80-43f0-11e8-9c29-64808f3e85b6.png)
