### ISSUE TITLE
No xrefs to element of array in memory

### ISSUE THREAD

**Issue by saruman9** [Vector35/binaryninja-api#1029]
Issue in the title.
Array in memory:
![array](https://user-images.githubusercontent.com/4244396/39175584-62a27dc0-47b3-11e8-97ed-26841a4e7e24.png)

Get xref to element:
```
>>> bv.get_code_refs(current_function.get_reg_value_after(0x41203020, "r4").value)
[]
```

![xref](https://user-images.githubusercontent.com/4244396/39175549-5411df08-47b3-11e8-8c07-26dba8e4bc2a.png)

**Comment by plafosse** [comment]
We believe this issue was fixed a bit ago. We'll try to verify this is fixed unless you can try to verify the fix yourself.

**Comment by jeffli678** [comment]
I verify this is fixed
