### ISSUE TITLE
Ability to adjust number of parameters passed to variadic function at call site.

### ISSUE THREAD

**Issue by bdemick** [Vector35/binaryninja-api#1031]
Manually updating the types for variadic functions on x86_64 results in incorrect analysis and population of the function prototype. It appears that the register args are missed and only the ones that spill to the stack are populated properly. See attached binary with two custom variadic functions. Note that there are also floating point args at play here, and I know that's not supported quite yet. Not sure if this is potentially affecting the analysis.

[vtest_x64.zip](https://github.com/Vector35/binaryninja-api/files/1948549/vtest_x64.zip)

**Comment by psifertex** [comment]
This is now complete as of build 2002 or so! Right-click at the call site and choose `Override Call Type`
