### ISSUE TITLE
MIPS lw alias incorrectly disassembled

### ISSUE THREAD

**Issue by micro500** [Vector35/binaryninja-api#1033]
I have a 2 opcode sequence that BN converts into a single lw alias instruction:
```
3c02800e 8c42c52c
````

BN disassembles it to:
```
3c02800e… lw      $v0, 0x800ec52c
```

If I am not mistaken those individual opcodes should be:
```
lui $v0,0x800e 
lw $v0,-15060($v0)
```
which would result in a load from 0x800dc52c, not 0x800ec52c.

It seems that in this case BN adds the value in the second opcode as an unsigned 16bit instead of a signed 16 bit.

Binary Ninja Version: 1.1.1184-dev Personal, 44b71efd
Platform: Windows 10 (10.0)

**Comment by rssor** [comment]
Fixed in build 1.1.1086-dev (the build after next).
