### ISSUE TITLE
Analysis hang + unbounded memory consumption

### ISSUE THREAD

**Issue by nshp** [Vector35/binaryninja-api#1035]
Looks like http://cyberjes.us/py3.so hangs analysis and slowly consumes all of the memory. Seems like it gets stuck building some infinite rbtree? Debug output shows it slowly stepping through "Indirect branch at 0xf00 has 118 targets" repeatedly.
Testing on Linux with no plugins.

**Comment by bpotchik** [comment]
Py_FatalError and PyThread_exit_thread are automatically tagged as __noreturn now. You can also update the settings file to lower the max-function-size used for analysis. The default max-function-size is 65536.

   "analysis" :
   {
      "max-function-size" : 65536
   }

Fixed in build 1.1.1190-dev.
