### ISSUE TITLE
libarch_powerpc.so causing failure to start binaryninja on Ubuntu 18.04

### ISSUE THREAD

**Issue by camjjack** [Vector35/binaryninja-api#1036]
Installing on a base Ubuntu 18.04 I was presented with the following error when attempting to start binaryninja:

`./binaryninja -d -e
Using ca bundle: /etc/ssl/certs/ca-certificates.crt
: CommandLine Error: Option 'asm-instrumentation' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options`

This is a fatal error and binaryninja does not start.

Upon investigation I discovered that the error was with libarch_powerpc.so. By removing this file from the plugin directory I was able to get binaryninja to start without error.

**Comment by rssor** [comment]
Fixed in build 1.1.1231-dev.
