### ISSUE TITLE
NEON vector instructions not disassembling in Thumb2

### ISSUE THREAD

**Issue by zznop** [Vector35/binaryninja-api#1037]
Binary Ninja Version: 1.1.1198-dev, 2ae75bba
Platform: Windows 10 (10.0) & Ubuntu (16.04)

### BN Disassembly/bug

![bn-output](https://user-images.githubusercontent.com/14361933/39755704-dcdf6b52-5294-11e8-8a6a-58395e046b86.PNG)

The missing data from 2180-2181 is `c0 ef`

### IDA Disassembly

![ida-output](https://user-images.githubusercontent.com/14361933/39755715-e85cf576-5294-11e8-885c-dc8723b4aa6f.PNG)

Let me know if you need more information. This example is best case. I've seen other instances where it completely screws up analysis and it interprets everything after the NEON instructions as data and I have to manually make a second function starting at the next thumb/ARM instruction it can disassemble.

**Comment by negasora** [comment]
Sorry for the delayed response, just about done adding support for NEON vector instructions.

**Comment by zznop** [comment]
Awesome! Please let me know when the build is up on dev and I'll re-analyze/test. I'm hoping this will solve issues I'm having with linear sweep on these thumb binaries as well.

**Comment by negasora** [comment]
Changes are up in dev!

**Comment by zznop** [comment]
![image](https://user-images.githubusercontent.com/14361933/42033130-d6c5611c-7aa9-11e8-8236-e8ab2368b844.png)

:thumbsup:
