### ISSUE TITLE
Popping stack register breaks stack analysis

### ISSUE THREAD

**Issue by DatBrick** [Vector35/binaryninja-api#1038]
Binary Ninja Version: 1.1.1198-dev, 2ae75bba
Platform: Windows 10 (10.0)

Stack analysis breaks after popping the stack register (`rsp = pop`), even though the stack offset is known afterwards.

![image](https://user-images.githubusercontent.com/6098371/39824476-53031c76-53a7-11e8-995c-472b4715837d.png)

![image](https://user-images.githubusercontent.com/6098371/39824494-5acfaf14-53a7-11e8-8e0e-8ae013b54455.png)

```
>>> current_llil[2].get_reg_value('rsp')
<stack frame offset 0x0>
>>> current_llil[3].get_reg_value('rsp')
<stack frame offset 0x0>
>>> current_llil[4].get_reg_value('rsp')
<stack frame offset -0x100>
>>> current_llil[5].get_reg_value('rsp')
<stack frame offset -0x108>
>>> current_llil[6].get_reg_value('rsp')
<stack frame offset 0x0>

>>> current_llil[1].get_reg_value_after('rax')
<const 0xa>
>>> current_llil[7].get_reg_value_after('rax')
<undetermined>
```

**Comment by psifertex** [comment]
Unfortunately this would require resolving the stack _through_ the stack and isn't a feature we plan to implement any time soon. It's a limitation of our current design that this isn't possible and we don't have any intention to change that particular implementation.

That said, bug #281 will be the one you'll want to keep an eye out on since that particular feature will definitely be implemented and would be the right work-around for situations like this.

**Comment by DatBrick** [comment]
Apologies in advance if i'm misunderstanding you, but I did a bit more testing and it appears the problem actually just happens whenver you write the stack pointer to the stack then then read it back, even if done indirectly.
That may be what you meant by `resolving the stack through the stack`, but since `get_reg_value` still shows the correct value, not undetermined, I'm a bit unsure how you would inform the dataflow of something it appears to already know?

Works:
![image](https://user-images.githubusercontent.com/6098371/39877099-e5fc392a-546c-11e8-851a-72700777f2f5.png)
![image](https://user-images.githubusercontent.com/6098371/39877103-ede5b198-546c-11e8-8046-0e4e75e13f27.png)

```
>>> current_llil[2].get_reg_value('rax').offset
-8L
```

Doesn't Work:
![image](https://user-images.githubusercontent.com/6098371/39877197-33ff50b2-546d-11e8-93ed-1acba2128de9.png)
![image](https://user-images.githubusercontent.com/6098371/39877206-3b0e8e40-546d-11e8-81b0-82585762c4bb.png)


```
>>> current_llil[4].get_reg_value('rax').offset
-8L
```
