### ISSUE TITLE
BackgroundTaskThread progress is not visible in the UI or console

### ISSUE THREAD

**Issue by Rami114** [Vector35/binaryninja-api#1039]
When implementing a plugin as a BackgroundTaskThread you can set the progress string with the aim of indicating progress status to the user in the UI and/or the console. However, no output is visible on either UI or console when setting this string during the running of the thread. 

Whilst this doesn't prevent the plugin from running the task in the background, it is hard to know if long-running tasks are completed. Current workaround is to explicitly log progress to the console.

**Comment by rssor** [comment]
Fixed in build 1.1.1202-dev.

Background tasks that can be cancelled will now display progress text just like non-cancellable tasks.
