### ISSUE TITLE
MLIL should handle member fields that are also structures or arrays

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#1040]
I’ll edit to provide examples if necessary later, but MLIL shows dereferences of internal structures and arrays as generic offsets from the main structure, rather than resolving them as their fields or the index of an array. This makes it hard to use more complicated structures in MLIL

**Comment by psifertex** [comment]
@rssor has a partial fix that might help with this -- he'll reach out to you directly to talk about it

**Comment by psifertex** [comment]
@rssor finished this several weeks ago, not sure build number. :-P
