### ISSUE TITLE
coredump during plugin init with 3 plugins after upgrade to Ubuntu 18.04

### ISSUE THREAD

**Issue by ChuckFoo** [Vector35/binaryninja-api#1042]
Hi.

I've been using the latest stable Binary Ninja (1.1.1142) under Ubuntu, and after upgrading from Ubuntu 16.04 to 18.04, the next time I ran Binary Ninja it started segfaulting at startup.  Running it under gdb I discovered that this was in CorePluginInit(), so I hid my plugins directory and sure enough it started up okay.  So then I started replacing my plugins one by one, and I discovered that three of them appeared to trigger different coredumps at startup: liil, binja-msdn, and binja_arch_ref.  I have a few other plugins enabled too, but these were the three that seemed to be triggering the crashes when I put them back in.

The variants of the crash messages I've seen are:

free(): corrupted unsorted chunks
Aborted (core dumped)

malloc(): memory corruption
Aborted (core dumped)

free(): invalid pointer
Aborted (core dumped)

Segmentation fault (core dumped)

They happened with liil in my plugins dir, just restarting binary ninja over and over, actually.  Since I'm seeing references to threads in various places, I'm assuming that some level of multithreading is happening and race conditions leading to the variations in how it dies...  I also verified that these crashes happen if liil is the ONLY plugin in my plugins dir as well.

And running valgrind on it shows a lot of potential sketchy things happening (some subset of which might possibly be due to how python is doing somethings under the covers, I suppose), both with and without loading any plugins at all.

I'll try and get more targeted & specific info (from valgrind and stack trace trimmed down from gdb) and post it here in a little bit, but I wanted to get this initial report out there in case anyone else is seeing something similar.

Chuck

**Comment by nbanmp** [comment]
I had similar crashes with the angr plugin example.

I noticed that opening up binary ninja normally (without plugins), then opening the script console (View->Script Console) and typing "import tempfile" or "import angr" would crash it.

I am on Arch Linux.

**Comment by ChuckFoo** [comment]
I just verified that a clean install of Ubuntu 18.04 in a VirtualBox (5.2.12) VM, with a clean install of Binary Ninja 1.1.1142, and only the liil plugin causes the above crashing, and the same steps in a clean 16.04 VM did not.

So between that and @nbanmp having similar issues under Arch Linux, I'm assuming that this should be easily reproducible. But if not, let me know what additional info I can procure to help diagnose...

**Comment by ChuckFoo** [comment]
Just noticed #1032 which is probably the same underlying issue as this one.

**Comment by ChuckFoo** [comment]
I also verified that the crash happens in the current dev channel version (1.1.1208-dev)

**Comment by aagallag** [comment]
I am still encountering this issue with version: `1.1.1228-dev`.

**Comment by bpotchik** [comment]
Fixed in build 1.1.1229-dev. Proxy support has been added as well.
