### ISSUE TITLE
MIPS ORI immediate value displayed as signed

### ISSUE THREAD

**Issue by micro500** [Vector35/binaryninja-api#1045]
In an ORI instruction such as
```
34018000   ori     $at, $zero, -0x8000
```
the immediate value is displayed as a signed hexadecimal value, but the MIPS instruction actually treats it as an unsigned value. If I right click the value, Display As -> Unsigned Hexadecimal, the value changes to 0xFFFF8000 which is still incorrect.

Is there any way to have it display the correct value of 0x8000 without the negative sign?

Binary Ninja Version: 1.1.1207-dev Personal, 3981ce6e
Platform: Windows 10 (10.0)

**Comment by rssor** [comment]
Fixed in build 1.1.1208-dev.
