### ISSUE TITLE
Binary Ninja fails to disassemble x86 setalc opcode (0xd6)

### ISSUE THREAD

**Issue by peperunas** [Vector35/binaryninja-api#1049]
It seems that Binja doesn't recognize the x86 opcode `setalc` (`0xd6`).

![image](https://user-images.githubusercontent.com/6033387/40582055-9bb00be4-611e-11e8-96db-9cb968acc860.png)

**Comment by KyleMiles** [comment]
Resolved in 1.1.1287-dev.
