### ISSUE TITLE
PUSH/RET analysis

### ISSUE THREAD

**Issue by nshp** [Vector35/binaryninja-api#1052]
I see some tailcalls which compiled to a `push addr; ret` sequence, which is making binja a bit confused at the moment.

**Comment by nshp** [comment]
The more I look at this, the less I'm sure it should even be treated as a tailcall. Here's a constructed example: http://cyberjes.us/pushret

In the real-world case, the "real" tail of the function is also doing some extra stack cleanup, so binja is completely missing that for its stack resolution at the moment.

**Comment by plafosse** [comment]
We should be able to recognize push/ret as a jump to help higher levels of analysis.

**Comment by bpotchik** [comment]
Fixed in `3.6.4601-dev`.

I've added some initial support for this.
![Screen Shot 2023-10-27 at 12 02 30 PM](https://github.com/Vector35/binaryninja-api/assets/29309548/e0d76292-c7b1-4ca1-9d71-7f46c3b40421)
