### ISSUE TITLE
Display Issues in Linear View

### ISSUE THREAD

**Issue by toolCHAINZ** [Vector35/binaryninja-api#1053]
I mentioned this in the slack, just throwing it up here for good measure.

## Description
I've been running into some odd display behavior in the linear view. It usually occurs when viewing data in or near large arrays.

Bytes that should be contained within the array type will sometimes get rendered outside of the array. This is often triggered by resizing the array, or attempting to create data in the vicinity of a large array.

Additionally, scrolling past a large array will sometimes cause the scroll to "jump" to the beginning or end of the array. I've not tried reproducing that in a contained example yet. If I do, I'll attach another example to this issue.

## How to Reproduce

I've attached a BNDB which demonstrates this behavior. Go to `24860` in Linear Disassembly View and attempt to create data there. This should trigger some bytes from the array starting at `24950` to render following the array.

[weird_behavior.bndb.zip](https://github.com/Vector35/binaryninja-api/files/2063490/weird_behavior.bndb.zip)

**Comment by bpotchik** [comment]
Fixed in 1.1.1458-dev.
