### ISSUE TITLE
Add a Symbol reference to the DataVariable class

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#1056]
Renaming a global data variable is convoluted at the moment, and not very clear from the documentation. It would make sense to add a reference to a `DataVariable`'s `Symbol` object (or `None`) so that users can more easily name and rename them.

**Comment by Vhex** [comment]
I'm running into this issue right now trying to do this through the API.  Does someone have an example of the convoluted method until this gets resolved?

**Comment by joshwatson** [comment]
Use `BinaryView.define_user_symbol`

**Comment by plafosse** [comment]
Added in 2.4.2969
You can now do: 

```python
bv.get_data_var_at(here).name = "foo"
```
or 
```python
bv.get_data_var_at(here).symbol = my_symbol
```
