### ISSUE TITLE
Follow Pointer in hex view

### ISSUE THREAD

**Issue by gynophage** [Vector35/binaryninja-api#106]
Follow pointer does not work in hex view.

I'm not really sure if it should in the long run, but while you don't handle jump tables or a linear sweep of the binary, I'm spending a lot of time flipping function pointer tables by hand to go to address and create function.

**Comment by psifertex** [comment]
The menu is broken, but the hotkey still works. Put in a very small temporary fix to at least show the correct hotkey, but still need to fix the menu.

**Comment by psifertex** [comment]
This is still not possible in hex view, but it is possible in linear view with the `o` hotkey.

**Comment by D0ntPanic** [comment]
Fixed in dev
