### ISSUE TITLE
Disassembly of missing x86 instructions yields '??'

### ISSUE THREAD

**Issue by janfrancu** [Vector35/binaryninja-api#1064]
On the current dev version (1.1.1228), missing x86 instructions are not ignored (as on release version) but partially included in the output. See pictures below for comparison.
![avx_dev](https://user-images.githubusercontent.com/34743109/41410708-a03f532a-6fda-11e8-984e-25fef7e527c2.png)
![avx_stable](https://user-images.githubusercontent.com/34743109/41410709-a05b1240-6fda-11e8-8d03-e322da1a3385.png)

Note that on dev it breaks the iteration of `bv.instructions`, as the `None` returned from `arch.get_instruction_info` does not have the length property.
Here are few hashes and corresponding addresses (can be found in VT database) with unknown instructions:
58af924e90c5a8f95e663d63b4058a2d963bc9b88463bff699e431961eca8222 - 0x555947
e69c4abcc4d2f130e66560fc27829b4fe62a2b1f66933790a3060bd7f4fcd878 - 0x30015815

**Comment by rssor** [comment]
Resolved in build 1.1.1254-dev.
