### ISSUE TITLE
ArchitectureHooks are not transparent

### ISSUE THREAD

**Issue by 0x1F9F1** [Vector35/binaryninja-api#1065]
Binary Ninja Version: 1.1.1228-dev, e7118f14
Platform: Windows 10 (10.0)

Currently ArchitectureHooks are visible when checking the arch of a Function/BinaryView/etc.  Apparently `the arch hook shouldn’t be visible to anything but itself and the core so things like highlights should be made with the base arch handle`, and this is causing a lot of the API's which take an architecture to not function correctly.

```
>>> type(current_function.arch)
<class 'binja-obfu.obfu_hook.ObfuArchHook'>
>>> type(current_function.arch.base_arch)
<class 'binaryninja.architecture.CoreArchitecture'>
```

**Comment by rssor** [comment]
Should be resolved in `1.1.1494-dev`.
