### ISSUE TITLE
u hotkey does not undefine

### ISSUE THREAD

**Issue by Oldetymer** [Vector35/binaryninja-api#1067]
Binary Ninja Version: 1.1.1230-dev, bc547651
Platform: macOS High Sierra (10.13)

The 'u' hotkey is listed on the "Getting Started Guide" at https://docs.binary.ninja/getting-started/index.html as the hotkey to undefine a symbol. However in testing. Pressing u on analysis defined function does nothing. Pressing u on user defined function does nothing. Pressing u on user defined data does nothing. Pressing u on analysis defined data does nothing

**Comment by joshwatson** [comment]
It's for undefining a symbol, not variables. Rename something (i.e. create a symbol) with `n` and then highlight it and press `u`.

**Comment by Oldetymer** [comment]
Undefine is then a terrible name for this then, as it doesn't undefine anything. Unname would be more accurate.

**Comment by joshwatson** [comment]
It undefines the symbol

**Comment by Oldetymer** [comment]
But the symbol, the address with the data at it still exists, just without a name

**Comment by psifertex** [comment]
I've committed a small documentation fix to the explanation that hopefully makes the intended usage more clear. Not going to kick off a dedicated build just for a documentation improvement, but should be in the next dev release.
