### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by dnutiu** [Vector35/binaryninja-api#1077]
Binary Ninja Version: 1.1.1142 Personal, 32782455
Platform: Windows 7 SP 1 (6.1)

I didn't find any proxy settings in Binary Ninja Personal thus I cannot connect to the update server:

"
Unable to clone repository from https://github.com/vector35/community-plugins.git to C:\Users\xxxx\AppData\Roaming\Binary Ninja\repositories\default
Git error 2: failed to send request: The operation timed out
Unable to clone repository from https://github.com/vector35/official-plugins.git to C:\Users\xxxx\AppData\Roaming\Binary Ninja\repositories\official
Error fetching channel list: Couldn't connect to server
Error fetching channel list: Couldn't connect to server
"

**Comment by bpotchik** [comment]
Proxy settings are supported on the latest dev. 
You will have to disable your proxy to update or copy an updated binary ninja from a location not behind a proxy.

**Comment by bpotchik** [comment]
Support added in dev build `1.1.1229-dev`. This build comes proxy support for receiving updates/changlog as well. Proxies will be picked up and used automatically if they are defined as environment variables such as `<protocol>_proxy`. If no proxy environment variables are set, then in a Windows environment proxy settings are obtained from the registry’s Internet Settings section, and in a Mac OS X environment proxy information is retrieved from the OS X System Configuration Framework. You can also manually specify a proxy in the `settings.json` file by adding a section `"download-client"` with a setting of `"https-proxy" : "https://<host>:<port>"`.
