### ISSUE TITLE
Seems like get_incoming_var_for_parameter_var() returns an incorrectly typed variable

### ISSUE THREAD

**Issue by irwincong** [Vector35/binaryninja-api#1079]
```python
>>> current_mlil.ssa_form[0].vars_read
[<ssa <var int64_t* arg1> version 0>]
>>> ssa_var = current_mlil.ssa_form[0].vars_read[0]
>>> main_func = bv.get_function_at(bv.symbols['main'].address)
>>> cc = current_function.calling_convention
>>> in_var = cc.get_incoming_var_for_parameter_var(ssa_var.var, main_func)
>>> in_var
<var int32_t rdi>
```
Callee function:
![image](https://user-images.githubusercontent.com/6097024/42479172-9a7b4050-83a5-11e8-8591-8034441b4ea4.png)
![image](https://user-images.githubusercontent.com/6097024/42479190-ae8fd678-83a5-11e8-9499-775acee05669.png)

This prevents me from doing something like the following while doing an inter-procedural backward slice:
```python
in_var = cc.get_incoming_var_for_parameter_var(ssa_var.var, caller)
in_var_ssa_ver = mlil_inst.get_ssa_var_version(in_var)
in_var_ssa = bn.mediumlevelil.SSAVariable(in_var, in_var_ssa_ver)
```
and have to resort to something like:
`in_var_ssa = mlil_inst.params[tracking_idx].src`
where `tracking_idx` was retrieved by:
```python
    def _get_func_arg_idx(self, ssa_var):
        """Determines if the SSA variable is a function argument"""
        params = ssa_var.var.function.parameter_vars
        for idx in range(len(params)):
            if params[idx] == ssa_var.var:
                return idx
        return None
```

**Comment by psifertex** [comment]
Just a follow up to let you know we're sorry this one didn't get responded to earlier. Can you confirm if this is still an issue and we can look into it more closely?

**Comment by irwincong** [comment]
> Just a follow up to let you know we're sorry this one didn't get responded to earlier. Can you confirm if this is still an issue and we can look into it more closely?

Closing seems to work in BinaryNinja 1.1.1470.

```python
>>> cc = current_function.calling_convention
>>> caller = bv.get_functions_containing(0x4004be)[0]
>>> cc = caller.calling_convention
```

```python
>>> ssa_var = current_mlil.ssa_form[0].vars_read[0]
>>> ssa_var
<ssa <var int64_t* arg1> version 0>
```

```python
>>> in_var = cc.get_incoming_var_for_parameter_var(ssa_var.var, caller)
>>> in_var
<var int32_t rdi>
>>> caller.get_low_level_il_at(0x4004be).medium_level_il
<il: 0x4005e0(rdi)>
>>> mlil_inst = caller.get_low_level_il_at(0x4004be).medium_level_il
>>> in_var_ssa_ver = mlil_inst.get_ssa_var_version(in_var)
>>> in_var_ssa = binaryninja.mediumlevelil.SSAVariable(in_var, in_var_ssa_ver)
>>> in_var_ssa
<ssa <var int32_t rdi> version 1>
```
![image](https://user-images.githubusercontent.com/6097024/52977580-ba4bfb80-339b-11e9-9a8e-687c37f31d6e.png)

![image](https://user-images.githubusercontent.com/6097024/52977564-ae603980-339b-11e9-9285-6fe0448c6f95.png)
