### ISSUE TITLE
Goto address has no discoverability

### ISSUE THREAD

**Issue by gynophage** [Vector35/binaryninja-api#108]
Go To Address seems to only be available through the "G" key. There doesn't seem to be a context menu or menu option that even shows this functionality exists - you just have to know to hit g.

**Comment by psifertex** [comment]
Added to the right-click menu in dev for both hex and disassembly view. I suspect we'll likely re-vamp all the navigation options into a new menu and it will go there as well, but this is a reasonable stopgap.
