### ISSUE TITLE
Wrong disassembly

### ISSUE THREAD

**Issue by bulzika** [Vector35/binaryninja-api#1081]
Instead of disassembling the following bytes 
`a2 00 00 ff ff ff 7f 00 00` as `mov byte ptr [0x7FFFFFFF0000], al`
bninja only consumes the bytes
`a2 00 00 ff ff ff` and disassembles them as `mov byte [0xffff0000], al`, followed by `??`.

Binary Ninja Version: 1.1.1259 Personal, f51163e8
Platform: Windows 10 (10.0)

**Comment by plafosse** [comment]
@KyleMiles is currently working on a big refactor to our x86_64 disassembler, which will hopefully fix this issue. #193

**Comment by KyleMiles** [comment]
Resolved in 1.1.1287-dev.
