### ISSUE TITLE
Demo x86 Wrong disassembly/analysis

### ISSUE THREAD

**Issue by chq-matteo** [Vector35/binaryninja-api#1082]
The demo version does not recognize some symbols in this binary from a ctf

Analysis log
```
Bundled types for platform linux-x86 loaded
Added linux-x86 entry point at 0x5d0
ELF parsing took 0,001 seconds
Analysis update took 0,063 seconds
Analysis update took 0,028 seconds
```

Task babysandbox
https://scoreboard.meepwn.team/task
[bin.zip](https://github.com/Vector35/binaryninja-api/files/2196083/bin.zip)

![main](https://user-images.githubusercontent.com/6654800/42738149-29a5cb14-887f-11e8-9c0d-7a262fb57bad.png)
![screenshot from 2018-07-15 22-33-24](https://user-images.githubusercontent.com/6654800/42738150-2bd24c3c-887f-11e8-82d8-b13552e0a884.png)
![screenshot from 2018-07-15 22-33-34](https://user-images.githubusercontent.com/6654800/42738152-2d24883e-887f-11e8-985c-fece40459276.png)
![screenshot from 2018-07-15 22-33-40](https://user-images.githubusercontent.com/6654800/42738153-2e6ae774-887f-11e8-8e08-6e319a134757.png)

Let me know if it does work in the full version

**Comment by chq-matteo** [comment]
Version 1.1.1259 demo Build ID f51163e8

**Comment by plafosse** [comment]
This issue was fixed when we added relocation back in September 2018.
