### ISSUE TITLE
PE forwarded export support missing

### ISSUE THREAD

**Issue by quoscient** [Vector35/binaryninja-api#1088]
Binary Ninja Version: 1.1.1259, f51163e8
Platform: Ubuntu 18.04 LTS

Opening a windows dll with forwarded exports causes binaryninja to go haywire. It seems that it attempts to disassemble the exported functions; as these are actually just forwarded to other dlls there is a large block of mostly ascii characters (which disassembles just too good). Probably you just try it yourself, I'll send you a sample by mail.
^lb

**Comment by bpotchik** [comment]
Fixed in 1.1.1446-dev.
