### ISSUE TITLE
Bad License Expiration Date Formatting in the UI

### ISSUE THREAD

**Issue by ltfish** [Vector35/binaryninja-api#1090]
On some language versions of Windows, timezone names contain non-ASCII characters, which cannot be displayed correctly as part of the "valid until" date in the About dialog.

![bn_about](https://user-images.githubusercontent.com/5071575/43046116-515caa10-8df7-11e8-873c-a3f9be35e9e1.png)

**Comment by bpotchik** [comment]
Fixed in 2.1.2318-dev.
