### ISSUE TITLE
Failed header parsing does not close the FileMetadata

### ISSUE THREAD

**Issue by janfrancu** [Vector35/binaryninja-api#1092]
In the case of some PE-files the format is recognized, however the header cannot be correctly parsed. One example of this is (VirusTotal hash `d7e56505e1081c9818b7d742fb155deb52f322a33b58854444de6d283adb0fa6`), which prints the `Failed to parse PE headers: read out of bounds` error in the UI log. Using the API's `bn.binaryview.BinaryViewType['PE'].open(filename)` or `bn.binaryview.BinaryViewType.get_view_of_file(filename)` returns None and the underlying BV's FileMetadata cannot be closed manually using the bv.file.close() nor is closed automatically as it is probably assumed that the file will be worked on later, as is the case of UI, which returns the `Raw` view with the `FileMetadata` handle reference. However this is an issue when these binaries are to be skipped in batch processing, as the underlying file handle leaks memory.

Additionally the `bn.binaryview.BinaryViewType.get_view_of_file(filename)` throws an exception as by default it tries to run the analysis of a NoneType. This can be easily mitigated using an if condition on the result of `cls[available.name].open(filename)`.

```
if update_analysis and bv != None:
    bv.update_analysis_and_wait()
return bv
```

One solution to the file closing problem would be to return the raw view instead of None, when the parsing is unsuccessful. However this change would have a huge impact, as the documentation clearly states, that `get_view_of_file returns the first available, non-Raw BinaryView available.` and as such is an entry-point for many scripts written on API.

Using BN ver. 1.1.1259.

I would like to use this issue as a starting point for a discussion about the API's BinaryView creation, which is in comparison with the UI slightly confusing and less verbose.

**Comment by KyleMiles** [comment]
Fixed in 1.3.2059-dev (ad37832dd4ffa112b10b523a151d3fa9b86b6c9d).
