### ISSUE TITLE
User types are broken.

### ISSUE THREAD

**Issue by gynophage** [Vector35/binaryninja-api#1096]
![image](https://user-images.githubusercontent.com/3688488/43376412-a7294106-9388-11e8-894b-b193c98ce29b.png)

The file appears to be loaded by binaryninja.

**Comment by plafosse** [comment]
This should be fixed with #1193

**Comment by plafosse** [comment]
I don't think this issue should have been closed.

**Comment by CouleeApps** [comment]
This seems like it has since been fixed:
<img width="671" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/711973/71ea3933-bfcc-4ecf-b73f-664b9d098eaa">
