### ISSUE TITLE
CFG disappears when resizing blocks

### ISSUE THREAD

**Issue by enjhnsn2** [Vector35/binaryninja-api#1100]
When creating a comment (or deleting a comment) that would result in a block in the cfg having to resize, the cfg vanishes entirely. It is fixed by going to another function and coming back. The puzzling part is this only happens 20-30 % percent of the time, so it make take a few attempts to recreate. This is Version 1.1.1259 Personal Mac.
Thank you for your time.
![screen shot 2018-08-04 at 4 33 09 pm](https://user-images.githubusercontent.com/26125281/43680279-e3b2a66e-9804-11e8-9def-0fa9818e4adb.png)

**Comment by D0ntPanic** [comment]
This bug should be fixed in build 1477. Please reopen if it is still happening.
