### ISSUE TITLE
LLIL Documentation out of date

### ISSUE THREAD

**Issue by qwerty01** [Vector35/binaryninja-api#1102]
I was going through the LLIL documentation and noticed the following snippet:

```
>>> for block in current_function.low_level_il:
...  for instr in block:
...   if instr.operation == LowLevelILOperation.LLIL_SET_REG and instr.dest== 'rdx':
...    print instr.address, instr.instr_index, instr
... 
```

It seems registers used to be stored as strings, but they are now stored via `ILRegister`. When the code is run, the following error occurs on the current version of BinaryNinja:
```
Traceback (most recent call last):
  File "<console>", line 3, in <module>
  File "lowlevelil.py", line 62, in __eq__
    return self.info == other.info
AttributeError: 'str' object has no attribute 'info'
```

I propose 2 potential fixes:
- Change documentation to `instr.dest.name == 'rdx'`
- Change `ILRegister`'s `__eq__` function to support comparisons to a string

**Comment by psifertex** [comment]
I forgot to update the bug, but this was fixed for the offline documentation a little while ago. Online docs will be updated shortly as well.
