### ISSUE TITLE
get_possible_reg_values doesn't mark subregister as `entry` when the full register is

### ISSUE THREAD

**Issue by noobdoesre** [Vector35/binaryninja-api#1104]
Binary Ninja Version: 1.1.1259, f51163e8
Platform: Windows 10 (10.0)

![screenshot_1](https://user-images.githubusercontent.com/8819310/43785666-806d05e6-9a6f-11e8-8800-bfe862770525.png)

This function receives arguments in rcx, rdx, though only ecx and dx are used. 
Upon querying possible values of ecx I got unexpected output:
```
>>> current_function.low_level_il[3].get_possible_reg_values('rcx')

<entry rcx>

>>> current_function.low_level_il[3].get_possible_reg_values('ecx')

<unsigned ranges: [<range: 0x0 to 0xffffffff>]>
```
Expected that ecx will be reported as `entry` too.

**Comment by noobdoesre** [comment]
Also, because of `r8d = ecx` possible value of `r8` is also a range (but should be an entry):
```
current_function.low_level_il[9].get_possible_reg_values('r8')
<unsigned ranges: [<range: 0x0 to 0xffffffff>]>
```

**Comment by plafosse** [comment]
I think we fixed this issue. Any chance you could retry this and or provide a binary exercising the issue?

**Comment by plafosse** [comment]
Closing this issue as theres been no change in >20 days and I believe this issue is fixed.
