### ISSUE TITLE
Provide an API to check if executing in the Main Thread context

### ISSUE THREAD

**Issue by gaasedelen** [Vector35/binaryninja-api#1106]
It would be useful to include an in-box API to check whether the current execution context is actually the main thread (eg, the UI thread). 

```
binaryninja.is_main_thread()
```

Driving Qt UI in threaded applications is pretty tricky to do correctly, especially from the perspective of a plugin where we have no control over the main application (IDA/BN). Almost exclusively, it is in the best interest of plugin authors to offload the execution of routines that touch Qt/UI elements back to the main (UI) thread.

Usage might be something like this (I generally use decorators though). 

```python
def func():
    # does qt stuff ...

if binaryninja.is_main_thread():
    func()
else:
    binaryninja.execute_on_main_thread(func)
```

IDA provides an API for this:

```
idaapi.is_main_thread()
```

Personally, I most generally use this API in function decorators to ensure thread correctness, or pass off function execution as needed.

**Comment by gaasedelen** [comment]
This is basically what I do already, I have a utility function that I use for both BN & IDA:

```python
def is_mainthread():
    """
    Return a bool indicating main thread execution.
    """
    return isinstance(threading.current_thread(), threading._MainThread)
```

I was just thinking about the average plugin writer, where having it in box might seem less shady 😬

**Comment by plafosse** [comment]
Your if statement is unnecessary, it already checks if its the main thread in the core. Just call `execute_on_main_thread` if you think you might be called from a different thread. 

We will create an is_mainthread api though.

**Comment by D0ntPanic** [comment]
The is_main_thread API was added alongside the UI API update on dev.
