### ISSUE TITLE
Allow grouping of registered plugin actions into submenus

### ISSUE THREAD

**Issue by gaasedelen** [Vector35/binaryninja-api#1107]
When registering a plugin, there should be some way to group registered actions into sub-menus. This will help cut down on clutter, espescially if you plan to gate all plugins within the `Tools` dropdown menu.

eg: 
```
Tools --> Lighthouse --> Load Code Coverage
Tools --> Lighthouse --> Load Coverage Batch
Tools --> Lighthouse --> Open Coverage Overview
```

IDA does this via slashes, so perhaps binja could do something similar:

```python
PluginCommand.register("Tools/Lighthouse/Load Code Covereage", ...)
```

More broadly, IDA is actually great by allowing plugin developers to insert menu actions in any of their main dropdowns, not just a plugin cage.

**Comment by plafosse** [comment]
Added in v 1.1.1427 . Use backslashes rather than fwd slashes though.

**Comment by gaasedelen** [comment]
Thanks! Confirming this now works as expected: 

![image](https://user-images.githubusercontent.com/9522648/49339941-2e7dcb00-f607-11e8-8fb2-f5f4f131af97.png)
