### ISSUE TITLE
An API to access the original filename (executable) to generate the BNDB

### ISSUE THREAD

**Issue by gaasedelen** [Vector35/binaryninja-api#1108]
There is currently no way (with, or without a BV) to get the name of the file / executabe that was used to generate the BNDB.

IDA has an equivalent for this:

```
idaapi.get_root_filename()
```

This one is important, and the information is apparently already in the BNDB. Hopefully it should be relatively easy to add.

**Comment by KyleMiles** [comment]
Is `bv.file.filename` not sufficient for this?

**Comment by gaasedelen** [comment]
No, that returns the BNDB name (at least when loading from a database).

**Comment by joshwatson** [comment]
fixed in 1.1.1297-dev

**Comment by bpotchik** [comment]
Thanks Josh!
