### ISSUE TITLE
An API to check if a BNDB is open in the Binary Ninja UI

### ISSUE THREAD

**Issue by gaasedelen** [Vector35/binaryninja-api#1109]
It would be beneficial if there was a stateless API that a plugin could use to check if a database is currently open in the UI.

```
binaryninja.has_database_open()
```

By database, I mean BNDB/Executable/Sessison/Tab or whatever you call a UI session internally.

**Comment by dropk1ck** [comment]
This is more-or-less what I'm looking for with #1126 as well.

**Comment by joshwatson** [comment]
Implement a ScriptingProvider and you can get this information

**Comment by joshwatson** [comment]
Though actually you can probably get it directly from the PythonScriptingInstance

**Comment by gaasedelen** [comment]
IIRC, the ScriptingProvider is unusable from python because it doesn't get registered properly. 

Hijacking the PythonScriptingInstance is the workaround I use to deal with the lack of UI/state API's until an official solution is available. By snooping on the living instance, you can track BV lifetimes, and build your own layer of signals (bv opened, bv closed, view changed, binja closing, etc).

The crux of my custom signals class implementation is based on this:

```python
def _snoop(obj, name, value):
    """
    Used to snoop on some basic BN UI interaction.
    """

    # save the property to the scripting instance as it normally expects
    obj.__dict__[name] = value

    # now you are free to do whatever ...
    print obj, name, value
    
    #...

# install listener onto the BN console / python interpreter
PythonScriptingInstance.InterpreterThread.__setattr__ = _snoop
```

Good luck.

**Comment by joshwatson** [comment]
Rather than doing that, you could just hijack the set_* calls in the scriptinginstance and just issue callbacks from there to your own thing

**Comment by plafosse** [comment]
We have some apis that haven't been merged yet which will fix this.
