### ISSUE TITLE
Promote BNIsUIEnabled() from the BN core API

### ISSUE THREAD

**Issue by gaasedelen** [Vector35/binaryninja-api#1110]
The following API should be promoted from the BN core, and documented appropriately as it is useful for checking if Binary Ninja is running headlessly. 

```
binaryninja.core.BNIsUIEnabled()
```

Plugins that make exclusive use of UI have no business running in a headless context. Other plugins with UI components may use this API to optionally load in a headless / compute-only mode, sans their Qt/UI parts.

**Comment by bpotchik** [comment]
Exposed as binaryninja.core_ui_enabled. Will close when included in the next build.

**Comment by bpotchik** [comment]
Fixed in build 1.1.1278-dev.
