### ISSUE TITLE
Easy way to check if a given address falls within a function

### ISSUE THREAD

**Issue by gaasedelen** [Vector35/binaryninja-api#1113]
Loosely related to the previous issue (#1112) , it might be nice (and more performant in some cases) to provide an API or shorthand to check if an address falls within a function.

eg:

```python
if address in func:
    do_something()
```

or maybe

```python
if func.contains(address):
    do_something()
```

Ideally, this would be lower cost to use than calling `bv.get_functions_containing(...)` or `bv.get_function_at(...)`, in certain scenarios.

**Comment by plafosse** [comment]
This feature is addressed in 2.4.3000
