### ISSUE TITLE
Read-access to theme attribute definitions through the API

### ISSUE THREAD

**Issue by gaasedelen** [Vector35/binaryninja-api#1114]
This is really more of a luxury, but it would be nice if going forward there was some way to retrieve more details about the current theme (and its colors) through the API. 

```python
binaryninja.get_theme_attribute("graphNodeDarkColor") # --> (74, 74, 74, 255)
```

On the dev branch, it is possible to retrieve the theme `palette` definitions via a `QtGui.QPalette` obect, but the higher level mappings within `theme-colors` (from the theme file definitions) is not available.

This is important for plugins who wish to be cognizant of the existing theme, or even make use of it themselves. This is an API that I would be using, at least.

**Comment by plafosse** [comment]
The UI is the only component that understands this it will likely have to wait until GUI plugins are fully supported. This would be queried directly through the UI.

**Comment by plafosse** [comment]
This is dependent on #305

**Comment by D0ntPanic** [comment]
This is provided as `binaryninjaui.getThemeColor` in the new UI API that is currently on dev.
