### ISSUE TITLE
Provide failure notifications on gated BinaryDataNotifications

### ISSUE THREAD

**Issue by gaasedelen** [Vector35/binaryninja-api#1115]
One of the issues IDA struggles with (in regard to events) is that some of their 'gated' event notifications may fail without notification. BN also seems to suffer from this.

By 'gated' events mean an event callback that happens _before_ a certain piece of information is modified in the database, and an event callback that happens _after_ it is modified.

For example, in BinaryDataNotifications we have:

```
BEFORE - function_update_requested
AFTER  - function_updated
```

As a plugin developer, I may want to hook `function_update_requested` to capture some information prior to this object being modified. My hooks then may change their logic to wait for a `function_updated` event to come through. 

But in failure cases, the `function_updated` event may never get fired off. As a result, my logic is now stuck in a state waiting for an event that may never come (or recieve a completely different one later).

If these gated events cannot complete, you should send out a notification as such:

```
FAILURE - function_update_canceled
```

In slack, rss noted that _`this might be worth a ticket, my recollection of that path makes that seem like it wouldn't be hard to add'_. Filing this so it doesn't get lost.

**Comment by plafosse** [comment]
We believe this would be best implemented as an analysis pass, #471 which we plan but is not done yet. I'm going to close as a dupe.
