### ISSUE TITLE
Incomplete Jump Table Cases

### ISSUE THREAD

**Issue by bdrodes** [Vector35/binaryninja-api#1119]
Below is an example where binja correctly finds all jump table targets, but does not identify all cases when accessing a jump table through an llil instruction's possible values (e.g., `current_llil[32].dest.possible_values`). The image below is a read out of end of the jump table's data var. It appears that the possible_values include the last two target reference cases, and all other cases are ignored. 

```
>>> current_llil[32].dest.possible_values
<table: [0x5e] -> 0x17fc0, [0x5a] -> 0x17fc4>
```

<img width="271" alt="image" src="https://user-images.githubusercontent.com/7384532/44055428-59ef0e16-9f13-11e8-9443-b35fa9716268.png">

**Comment by bpotchik** [comment]
Fixed in build 1.1.1279-dev.
