### ISSUE TITLE
Converting raw bytes to offset fails

### ISSUE THREAD

**Issue by bkerler** [Vector35/binaryninja-api#1122]
Having function or ascii pointers (vtable) outside of the analysed area (raw bytes) and pressing 'o' will not convert the bytes to a pointer to a function or ascii. Pressing '4' will just change the type to int_t but also doesn't convert.

![text](https://user-images.githubusercontent.com/6317772/44301875-f2a44b80-a31e-11e8-8d8a-d280b024a9ca.png)
![pointers](https://user-images.githubusercontent.com/6317772/44301878-f637d280-a31e-11e8-8be4-16d273956142.png)

Expected result would be to press 'o' and it would be converted to a pointer to a string (ascii@08019420).

**Comment by bkerler** [comment]
This only happens in the latest demo version. Personal version however seems to have the correct behaviour.

**Comment by plafosse** [comment]
Do you know which versions the demo was and the personal version were that you were testing with?

**Comment by plafosse** [comment]
We're going to assume this issue is fix, as we've not heard back.
