### ISSUE TITLE
Missing PowerPC instructions

### ISSUE THREAD

**Issue by Leseratte10** [Vector35/binaryninja-api#1123]
I have just bought Binary Ninja to analyze some PowerPC Binaries (for the PowerPC Broadway / 750CL), and, as I have already been told on Slack, some instructions (especially those related to floating point stuff) aren't disassembled correctly (it displays "??" as instruction and the function ends). 

Is it possible to add those missing instructions in a future version? If yes, what information would be needed for that? Would it be enough to get the byte code and the textual representation for each non-detected instruction?

**Comment by gynophage** [comment]
While I'm sure V35 would be interested in adding these instructions at some point, if the wait becomes unbearable, you can implement them yourself in a plugin.

https://github.com/Vector35/binaryninja-api/blob/dev/examples/x86_extension/src/x86_extension.cpp is the example for extending the existing x86 architecture.

You can also do it in python:

https://github.com/Vector35/binaryninja-api/blob/dev/python/examples/arch_hook.py

See https://github.com/Vector35/binaryninja-api/blob/dev/python/examples/nes.py for a reasonable example of how defining instructions/LLIL for them works on a simple arch.

**Comment by psifertex** [comment]
I'm going to close this issue since we already have an open issue for PPC instruction set completeness. If you can add the instructions that are missing as a comment to #798, I will update the original table to include those so we can track them as not disassembled.

**Comment by Leseratte10** [comment]
@psifertex the instructions still haven't been added to the table in #798 - is there any estimate when at least disassembly for those will be added to the function disassembles correctly? I was unable to add those in an own hook, but maybe I just did something wrong ...

**Comment by psifertex** [comment]
Unfortunately we don't have an ETA for those fixes yet. 

If there's a technical problem blocking CPU extensions that would be a higher priority fix and we'd want to get that working. Did you ask in #api-help on the slack yet about why the extension wasn't working?

**Comment by Leseratte10** [comment]
Actually, I don't remember anymore. But I do remember that there is indeed a bug in the ArchitectureHook system that prevents me from using global_regs correctly: #1149 

I'll try the CPU code extensions again on the weekend to see if there was a specific problem or if I just wasn't able to get it to work.

**Comment by psifertex** [comment]
Ahh, actually talking it over internally @rssor reminded me about it. Yes, that's the right bug. We can take a look at our road map and see about slipping a fix in, but we've got several higher priority issues right now unfortunately.
