### ISSUE TITLE
Feature request: Notification to plugins on analysis tab close

### ISSUE THREAD

**Issue by dropk1ck** [Vector35/binaryninja-api#1126]
There does not seem to be a way for a plugin to detect when a tab is closed.

The use case here would be for something like revsync (https://github.com/lunixbochs/revsync), which starts long-running threads to sync analysis between binja <-> other tools.  The threads don't know when to 'die' since there seems to be no way to tell when the user closes the tab.  We could add some sort of menu item to explicitly 'stop' the plugin, but that kind of sucks and won't always end well when users forget to do it.

I don't imagine revsync is the only plugin that will ever have this issue, so I figured I'd put in a feature request.  Also if I've completely missed some part of the api that solves this, please let me know.  Thanks.

**Comment by plafosse** [comment]
I believe this issue was solved when we released 1.2 which included our UI plugins. Here is an example of how to do this. https://github.com/Vector35/binaryninja-api/blob/c0ddbf0c76d3f1bb7a2b2024f749afc8b9482575/python/examples/ui_notifications.py#L1
