### ISSUE TITLE
Feature Request : Copy text from current view (llil, mlil and disasm view)

### ISSUE THREAD

**Issue by bkerler** [Vector35/binaryninja-api#1128]
I'd like to see a feature where you can select multilines using Ctrl + Cursor and then copy the lines out into the clipboard :)

Example : In Disassembler view, select multiple lines or press Ctrl-A to select all lines in the current block and then press Ctrl-C to copy the text into the clipboard (for graphical view, llil and mlil pseudo-code)

Currently, this is only possible using python console, which is a bit inconvient if I need to copy out stuff fast.

Example code for llil for current block :
```
for bb in current_llil.basic_blocks:
  for instruction in bb:
    print instruction
```

**Comment by plafosse** [comment]
Duplicate of these: #91 #373
