### ISSUE TITLE
MLIL lift for PPC using a constant instead of stack var for function argument

### ISSUE THREAD

**Issue by kleusc8** [Vector35/binaryninja-api#1129]
I noticed this while working with a PPC binary. Looks like it may be a leftover from r3 being used for the malloc call.

Original assembly:
![screen shot 2018-08-22 at 12 05 41 pm](https://user-images.githubusercontent.com/11539105/44475719-c5e48280-a603-11e8-9386-69f34adb4f39.png)

MLIL:
![screen shot 2018-08-22 at 12 07 02 pm](https://user-images.githubusercontent.com/11539105/44475802-fb896b80-a603-11e8-998c-a1166a26a710.png)

**Comment by plafosse** [comment]
Any chance you can upload a screenshot of LLIL too?

**Comment by kleusc8** [comment]
Sure thing! 
![screen shot 2018-08-22 at 12 38 01 pm](https://user-images.githubusercontent.com/11539105/44477324-4dcc8b80-a608-11e8-9acd-805463b45350.png)

**Comment by joshwatson** [comment]
What's the function prototype for `malloc@GOT`? It looks like it thinks it doesn't modify `r3`, which is causing the dataflow issue

**Comment by kleusc8** [comment]
void*  malloc@GOT(uint32_t n)

![screen shot 2018-08-22 at 12 43 12 pm](https://user-images.githubusercontent.com/11539105/44477551-04307080-a609-11e8-92e1-36ec364eff89.png)

**Comment by kleusc8** [comment]
Nevermind, it's due to the fact that I changed it's type to a function rather than a function pointer...which screwed up the dataflow analysis. I'm sorry!
