### ISSUE TITLE
Wrong MLIL lifting on MIPS

### ISSUE THREAD

**Issue by Arcnor** [Vector35/binaryninja-api#1132]
I hope this is a real bug and not just some misunderstanding on my part :).

I have the following MIPS code:
<img width="336" alt="bug0" src="https://user-images.githubusercontent.com/28616/44585117-98a7f800-a7ee-11e8-983c-cd34b7381658.PNG">

0x80065046 looks like this:

<img width="225" alt="bug1" src="https://user-images.githubusercontent.com/28616/44585154-ba08e400-a7ee-11e8-842f-93dcf4dfad67.PNG">

(not sure why there is no reference to this memory address, some other bug?)

Then MLIL looks like this:

<img width="397" alt="bug2" src="https://user-images.githubusercontent.com/28616/44585186-d147d180-a7ee-11e8-8e68-40250be7c085.PNG">

As you can see, it simplified the `$v0 == $v1` comparison into `false`, which is completely wrong at runtime, because that memory address can (and will) change, obviously. Not sure if the lack of reference to that memory address (there is no `data_XXXX` field) has something to do with it.

**Comment by Arcnor** [comment]
I manually created a field on that address and it didn't solve the problem, so I'm guessing this is really a bug, but happy to be proven wrong :).

**Comment by bpotchik** [comment]
What are the segment/section permissions for 0x80065046?

**Comment by Arcnor** [comment]
Right, I knew I was missing something. The segment 0x80010000-0x80069800 is being set as `r-x`, which is not completely correct. Is there a way for me to manually change that?

**Comment by bpotchik** [comment]
You can right click in the UI from linear view at the top of the file. You can also use the API in the python console. There may be a bug here actually.

**Comment by Arcnor** [comment]
I'll check the API then, I don't see any entry in the popup menu when right clicking on the top of the linear view (I guess you mean where it specifies the segments and sections)

**Comment by bpotchik** [comment]
Yeah, the UI can modify section semantics, not the segment semantics. I imagine there are not sections defined. You could probably try `bv.add_user_section("<section_name>", <section_start_address>, <section_size>, SectionSemantics.ReadWriteDataSectionSemantics)`

**Comment by Arcnor** [comment]
Ok, that was a bit confusing, but I managed to change that section (yes, there were sections defined, matching 1:1 with the segments). When I changed that section to be writable, BN marked it as such and reanalyzed my whole target, but sadly the same behavior continues.

**Comment by Arcnor** [comment]
So after re-creating the code segment manually and assigning write permissions to it, this worked as expected, so I think this can be closed, unless you still think there is a bug somewhere @bpotchik ?

**Comment by bpotchik** [comment]
Missed that this issue has been resolved.
