### ISSUE TITLE
XRefs list loses focus/results

### ISSUE THREAD

**Issue by Arcnor** [Vector35/binaryninja-api#1133]
This is a very small bug, but highly annoying when doing some exploration on my targets.

1. I hover some function/field/whatever
2. I double click on some of the Xrefs
3. I continue up/down the list, opening each one of them
4. Suddenly/randomly, the Xref window loses focus, and the results are gone

I can of course click on my function/field/whatever again then check the Xref list, but now I don't know where on the list I was in, unless I go and search them (manually, since the Xref list also doesn't support filtering)

**Comment by yuv422** [comment]
I think highlighting the selected xref in the list would help with this too. I often loose my place when scanning through a long xref list which contains mainly unknown functions.

**Comment by bpotchik** [comment]
Fixed in 1.1.1458-dev.
