### ISSUE TITLE
Garbled text bug

### ISSUE THREAD

**Issue by Arcnor** [Vector35/binaryninja-api#1135]
Today I started getting garbled text in some of my functions (others look ok):

<img width="342" alt="binary_ninja" src="https://user-images.githubusercontent.com/28616/44634209-ec2a6980-a9d9-11e8-8d39-c5c018dfb931.png">

The data section looks like:

<img width="1001" alt="binary_ninja" src="https://user-images.githubusercontent.com/28616/44634215-019f9380-a9da-11e8-8cab-edf8b1d0bacd.png">

I've then changed the definition of that variable to "char[4]" and everything shows fine again. Nothing else worked (reanalysis, closing/opening BN, etc). I have other "strings" defined as `void` (like this one was) and it doesn't happen to those, so I'm not sure what the problem is.

**Comment by negasora** [comment]
This is most likely due to a bug in the Unicode parsing I added. If this is a binary that you can send me, send it in a slack message to negasora, please.

**Comment by negasora** [comment]
pushed a fix in 1.1.1303-dev

**Comment by negasora** [comment]
The minimum string length for showing an annotation is 4, unless it's explicitly defined as a character*/wchar16*/wchar32*

**Comment by Arcnor** [comment]
Found another place where this is probably breaking:

<img width="626" alt="bn" src="https://user-images.githubusercontent.com/28616/44783918-345ead00-abcf-11e8-9c6c-c30e5d3e45ee.png">

`data_800594c0` is a `void*[]` symbol, there should be no text preview here. I checked with stable and it's correctly showing nothing.

**Comment by Arcnor** [comment]
Found yet another:

<img width="866" alt="bn" src="https://user-images.githubusercontent.com/28616/44843490-c7f5b380-ac8b-11e8-8bed-1f483f2bbbb1.png">
<img width="981" alt="bn" src="https://user-images.githubusercontent.com/28616/44843517-d774fc80-ac8b-11e8-8692-78d665b77d9a.png">

**Comment by psifertex** [comment]
Indeed. @negasora I'm re-opening this one.

**Comment by Arcnor** [comment]
This seems to have been fixed at some point, at least for the 2 cases I found above, I'll close this for now, and I'll add a comment again if I see another instance of it happening.

**Comment by psifertex** [comment]
Yup, sorry about that, fix got checked in on the 6th but we missed marking it here.
