### ISSUE TITLE
tbb instruction has insufficient sanity(bounds) checking

### ISSUE THREAD

**Issue by atlas0fd00m** [Vector35/binaryninja-api#1138]
![image](https://user-images.githubusercontent.com/9836679/44807757-61439d80-ab98-11e8-8343-53369921fa2b.png)

**Comment by atlas0fd00m** [comment]
for context, that's the second instruction in an interrupt service routine.  
the first instruction is simply "bhi 0x1c52"

**Comment by atlas0fd00m** [comment]
for that matter, the functionality is broken.  that's a tbb with a base-register of PC, meaning that the case 0 byte offset and the case 1 byte offset are being used as actual code for case 0.  (0407)

**Comment by psifertex** [comment]
I don't know much about that instruction so apologies if this is a dumb question. Is the issue that the instruction encoding itself is not properly bound? Or the dataflow on the values leading up to it are not picking up what should be the proper limit? What does the IL look like leading up to that instruction?

**Comment by atlas0fd00m** [comment]
TBB and TBH are branch-table instructions, providing a base register and an indent offset register.  they both use the base register to find the start of an offset table.  each entry in the offset table is 1- or 2-bytes in size, for TBB and TBH respectively.  the value in the table entry (shifted left 1) is added to PC (with the stupid pipelining offset) as the next instruction for a particular switch case.

looking into it further, the function start was misidentified (my fault), so the analysis might be expecting sometime additional.  there should still be some sanity checks, since most often the jmp table runs into the first entry.

in case my description is difficult to understand, here's from the ARM:
"Table Branch Byte causes a PC-relative forward branch using a table of single byte offsets. A base register provides a pointer to the table, and a second register supplies an index into the table. The branch length is twice the value of the byte returned from the table.
Table Branch Halfword causes a PC-relative forward branch using a table of single halfword offsets. A base register provides a pointer to the table, and a second register supplies an index into the table. The branch length is twice the value of the halfword returned from the table."

**Comment by psifertex** [comment]
Sorry for leaving this languishing for so long. Looking back over it, I don't think we can restrict the IL any more than we already are. We do specify that the argument is a byte index which should limit the range as much as the instruction itself allows and assuming the dataflow is working properly we'll be able to constrain it to the actual size of the jump table. If it does crop up again you should be able to use https://api.binary.ninja/binaryninja.function-module.html?highlight=user_indirect#binaryninja.function.Function.set_user_indirect_branches to set the proper number of entries/targets.

**Comment by psifertex** [comment]
One other note to add that another solution (when it's finished) is #281

**Comment by bpotchik** [comment]
@atlas0fd00m Would you happen to have this binary floating around?

**Comment by atlas0fd00m** [comment]
sorry, not sharable. :(

thanks for your continued commitment to quality :)

@

**Comment by bpotchik** [comment]
@atlas0fd00m, no problem. I think this jump table may be better constrained with 1.1.1793-dev build. If you get a chance let me know if it works better....thanks!
