### ISSUE TITLE
smart demangler

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#114]
Add a smart symbol demangler that is type-information aware and does type propagation based on the demangling results.

**Comment by Grazfather** [comment]
For Just curious: For which languages? Just C++ or will Swift and such work. Rust would be nice..

**Comment by alexandernst** [comment]
Adding to what @Grazfather said. Are you willing to create some sort of "demangler API" that people willing to contribute could use to write demanglers for other languages?

**Comment by plafosse** [comment]
This issue is tracking only GNUv3/MSVS C++(11).  MSVS demangler is finished, we are still working on the GNUv3 demangler.  If there are particular languages you want demanglers for please create issues for them.

Demanglers as plugins is a good idea, I'll add a issue tracker for that.

**Comment by plafosse** [comment]
fixed in dev
