### ISSUE TITLE
Add CodeWarrior Name Demangling

### ISSUE THREAD

**Issue by Leseratte10** [Vector35/binaryninja-api#1141]
Binary Ninja doesn't support demangling functions mangled by the CodeWarrior compiler. I've seen the workaround in #467 with the script to manually demangle those, but that only fixes function names, not the parameter types. 

Could support for CodeWarrior demangling (as in this script: https://gist.github.com/jackoalan/a4035651f6b870136da5 ) be added to Binary Ninja?

**Comment by plafosse** [comment]
Thanks for filing an issue. You can set the type as well though you'd first have to recover the type from the mangled name, which isn't always a very easy thing to do. You can set the function's type by assigning the `current_function.function_type` property. It's unlikely that we'll get to this soon.

**Comment by plafosse** [comment]
We're unlikely to add first class support for this though we'd like to add demangler plugin support #467
