### ISSUE TITLE
Table without Table?

### ISSUE THREAD

**Issue by bdrodes** [Vector35/binaryninja-api#1153]
In the example below, I'm expecting to find a jump table at LLIL[2] but none exists. Instead, there is just a constant. 

```
>>> current_llil[2].dest.possible_values
<const ptr 0x3e5>
>>> current_llil[2].dest.possible_values.table
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'PossibleValueSet' object has no attribute 'table'
```
![image](https://user-images.githubusercontent.com/7384532/46023364-7ab20980-c0b2-11e8-9d7e-fcfe3566bf97.png)
![image 1](https://user-images.githubusercontent.com/7384532/46023391-8a315280-c0b2-11e8-8bcc-cb8a9df50f4b.png)
![image 2](https://user-images.githubusercontent.com/7384532/46023449-aaf9a800-c0b2-11e8-903c-aec769d3899d.png)

**Comment by plafosse** [comment]
A ConstPtr doesn't have a table attribute. Only LookUpTable's do.
