### ISSUE TITLE
`CodeRelativeAddressTokens` not represented in IRs.

### ISSUE THREAD

**Issue by KyleMiles** [Vector35/binaryninja-api#1154]
Unable to tell whether a `ConstPointer` was generated from `pc+const` or just `const`.

Important for deriving relation between different sections of code/data.

Optimally, would propagate the `CodeRelativeAddressTokens` text tokens to something like `CodeRelativePointer` in IRs.

**Comment by plafosse** [comment]
The IL is designed to abstract away the need for such things. Our analysis wasn't designed to ever do this. I've got to mark this as "Won't fix"
