### ISSUE TITLE
Suppress warnings when max-function-size is set to 0

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#1157]
If the settings contain `analysis.max-function-size` or a `BinaryView` sets `self.max_function_size_for_analysis` to `0`, it's probably okay to assume that the user explicitly doesn't want analysis beyond disassembly to ever run. In this case, the warning at the top of the graph view and the warnings in the log can be suppressed.

**Comment by bpotchik** [comment]
Fixed in build 1.1.1369-dev.
