### ISSUE TITLE
Searching for a substring in the strings window highlights the wrong result.

### ISSUE THREAD

**Issue by freetink3r** [Vector35/binaryninja-api#1159]
If you search for "rintf" in the strings window, the line *following* the correct result is the one that is highlighted instead of the correct line that contains "rintf".

**Comment by psifertex** [comment]
When you say "search" do you mean you're using CMD-F or you're using the filtering by just typing when the window is focused?

**Comment by psifertex** [comment]
I assume it's ctl-f or cmd-f but I can't seem to reproduce that here. Can you share a binary that demonstrates it or maybe record a quick screen cap showing it?

**Comment by freetink3r** [comment]
Yes, the problem only appears when using cmd-f and searching for a substring (i.e., "rintf" instead of "printf"
