### ISSUE TITLE
Suspected umlaut issue during setup

### ISSUE THREAD

**Issue by gitsoft** [Vector35/binaryninja-api#1161]
**Behaviour**
I installed Binary Ninja on Windows 10 Pro. After the setup had completed I got stuck on the step where you provide Binary Ninja with the license.txt file. It show the error message "_Failed to overwrite outdated license file_". 

**Handling of license.dat**
I noticed something strange. The setup had put the license.dat file here
C:\Users\Bj�rn\AppData\Roaming\Binary Ninja\

but %APPDATA%\Binary Ninja\ on my machine points to this folder:
C:\Users\Björn\AppData\Roaming\Binary Ninja\

**Theory**
The license verification fails because it checks for license.dat in another folder then were the setup had placed it. The root cause for this issue relates to how the setup handles my username, which contains the swedish letter ö.

**Details**
I have a lot of installations on my machine but Binary ninja is the only application that have placed anything under C:\Users\Bj�rn\AppData\Roaming so I guess it created an entirely new app data folder where the swedish letter Ö was replaced with a �.

**Steps to reproduce**
I'm on windows 10 Pro (x64) with all the latest updates, so I guess this bug/behaviour can be recreated by creating a user with å, ä or ö in the name and then running the Binary ninja setup and then provide the license.dat file?

**Workaround**
Manually move license.dat to the correct folder and start Binary ninja again.

**Comment by plafosse** [comment]
This is fixed as of v1.1.1344
