### ISSUE TITLE
binaryninja.binaryveiw.Section.align is broken in most recent dev

### ISSUE THREAD

**Issue by KyleMiles** [Vector35/binaryninja-api#1166]
I think @plafosse is already working on this and that it ties in to #1165, so I am adding it here just in case it wasn't noticed but mostly to track this specific issue.

Code affected:
    github.com/Vector35/binaryninja-api/blob/dev/python/binaryview.py#L579

Problem:
    The funciton `_binaryninjacore.BNSectionAlign` no longer exists.

**Comment by KyleMiles** [comment]
Looks like `BNSectionAlign` was changed to `BNSectionGetAlign`, though changing that locally causes a segmentation fault when calling `BNSectionGetAlign`.

**Comment by plafosse** [comment]
This was fixed in v1.1.1357
