### ISSUE TITLE
bv.get_sections_at broken in most recent dev build (1.1.1354-dev)

### ISSUE THREAD

**Issue by BrenanHornseth** [Vector35/binaryninja-api#1167]
This is probably related to #1166 and #1165 but I wanted to report it to be sure. I am seeing a crash with the following code on x86_64 (sample file provided though I imagine other binaries have the same issue) for binary ninja version 1.1.1354-dev

```
import binaryninja as bn
bv = bn.BinaryViewType['ELF'].open("vtable_no_rtti")

bv.get_sections_at(4194872)
bv.get_sections_at(4194872)
bv.get_sections_at(4194872)
```

A single call to `get_sections_at()` seems to work OK. But multiple calls causes a crash.

**Comment by plafosse** [comment]
This was fixed in v1.1.1357
