### ISSUE TITLE
GUI Doesn't Play Nicely with matplotlib on OS X

### ISSUE THREAD

**Issue by ehennenfent** [Vector35/binaryninja-api#1168]
When a plugin calls `show` on a matplotlib graph, Binary Ninja reopens any child windows (context menus, open file dialogs, etc) that have previously been clicked on, as described [on Slack on Oct 9 '18](https://binaryninja.slack.com/archives/C0CV88A83/p1539120469000100).

The following plugin is sufficient to reproduce the issue on OS X. I haven't tried it on other platforms. Note that this must be run from the plugins folder, as pasting it into the script console causes Binary Ninja to crash. 

```
from binaryninja.plugin import PluginCommand
import matplotlib.pyplot as plt

def do_the_thing(*args):
    plt.plot(1,1)
    plt.show()

PluginCommand.register_for_function("Bug out the GUI", "What it says", do_the_thing)
```

**Comment by psifertex** [comment]
So this is just a really bad implementation in matplotlib and not really something we can or will fix. Specifically:

https://github.com/matplotlib/matplotlib/blob/5e20d9baaed6f997a6ab73ea25add24177a82117/src/_macosx.m#L2358

Their `macosx` backend specifically enumerates all windows and shows them. They'll never play nice working embedded with that code.
