### ISSUE TITLE
Python API doesn't support function type comparison

### ISSUE THREAD

**Issue by jollheef** [Vector35/binaryninja-api#1169]
Binary Ninja Version: 1.1.1344, c25b2ebb
Platform: macOS 10.14

    >>> foo
    <type: int64_t (char const* a, char const* b, uint32_t c, char const* d) __noreturn>
    >>> bar
    <type: int64_t (char const* a, char const* b, uint32_t c, char const* d) __noreturn>
    >>> foo == bar
    False

**Comment by joshwatson** [comment]
`Type.__eq__` is currently checking if it is the exact same `Type` object in the core, not whether its members are the same:
```python
	def __eq__(self, value):
		if not isinstance(value, Type):
			return False
		return ctypes.addressof(self.handle.contents) == ctypes.addressof(value.handle.contents)
```
This is closer to `===` in Javascript than `==`. If you want `==`, you need to iterate over the function parameters, compare them, and then compare return type and any other member fields that are set that you might care about being equal.

**Comment by jollheef** [comment]
Oh, lol.

Sorry, I missed that you're not from Vector35.

**Comment by joshwatson** [comment]
lol I get that a lot 😜

**Comment by plafosse** [comment]
In general the type system didn't support proper comparison of types. It does as of v1.1.1365

**Comment by jollheef** [comment]
> It does as of v1.1.1365

I updated to version 1.1.1365-dev (Build ID a9f0b478) and tried to compare function types:

```
>>> foo.function_type
<type: int64_t (int64_t* arg1)>
>>> bar.function_type
<type: int64_t (int64_t* arg1)>
>>> foo.function_type == bar.function_type
False
```

Still doesn't work. What am I doing wrong?
