### ISSUE TITLE
copy/paste not working

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#117]
There's no way to select chunks of disassembly (or IL), nor do the copy/paste menu choices work.

**Comment by gynophage** [comment]
Potentially related - in hex view, when the hex side is selected, Command+C inputs 0xc. Command+v pastes the contents of the clipboard.

If you select a range, Command+C works as expected.

**Comment by D0ntPanic** [comment]
Fixed in dev (multiselect is not done, see #91)
