### ISSUE TITLE
[BUG] Class names not showing in UI function list

### ISSUE THREAD

**Issue by sizzop** [Vector35/binaryninja-api#1170]
After updating to most recent -dev release recently, I no longer see the class names in the function list. I am seeing functions listed as "::SomeFunction" (without the class) as opposed to "SomeClass::SomeFunction".

I verified this is not an issue with the .pdb by opening a new binary in binja, having it download the associated PDB from Microsoft symbol server, observing the issue, then opening the same binary in IDA and manually selecting the same PDB file to load. The symbols were displayed properly there.

Also the issue seems to be isolated to the UI as I can access the full class+method name via the Python console.

I'm on v. 1.1.1357-dev on macOS.

**Comment by plafosse** [comment]
Fixed as of v1.1.1365
