### ISSUE TITLE
Storing BinaryView Metadata does not cause prompt for database save

### ISSUE THREAD

**Issue by bpotchik** [Vector35/binaryninja-api#1174]
BinaryView metatdata is not saved in the database and the UI does not prompt to save the database if there have been no file and/or analysis changes. This can result in loss of binaryview metadata.

Note: Manually saving the database does save metadata.

Steps to reproduce.
1). Open existing bndb in UI.
2). Store Metadata in BinaryView.
3). Close the view.

**Comment by psifertex** [comment]
Current fix marks the file as modified, not the analysis.

**Comment by jonpalmisc** [comment]
Fixed again in build 2864.
