### ISSUE TITLE
Custom modules imported from script console are missing binja globals

### ISSUE THREAD

**Issue by freetink3r** [Vector35/binaryninja-api#1178]
When I import a custom module from the plugin directory, that module does not have access to the binja globals, such as bv.

To reproduce, create a trivial module file in the plugin folder. At the top of the module file, print(bv). Then from the scripting console in binja, import the module. You wil get a NameError exception with the message "name 'bv' is not defined".

Perhaps this is as designed, but I thought I'd report it in case the module should have access to the same globals that are exposed in the interactive console.

**Comment by plafosse** [comment]
This is working as designed. Those globals are not intended to work from within a plugins context. Within the plugin console the currently open tab and currently viewed function allows the UI to inform the API what the context is. Plugins have to create or register for receiving the context they desire to operate on.
