### ISSUE TITLE
Advanced Settings Freezes

### ISSUE THREAD

**Issue by resrever** [Vector35/binaryninja-api#1184]
Binary Ninja Version: 1.1.1376-dev, 6060fe26
Platform: Fedora 28 (Workstation Edition)

When I open Advanced Settings, Binary Ninja freezes and mostly doesn't respond to UI interactions.  If I click the X to close binja, it doesn't close for about 30 seconds.  If I scroll the Advanced Settings window, nothing happens for about 30 seconds, and then further UI interactions do not go through and I have to kill -9 the process.

**Comment by bpotchik** [comment]
This was the result of an invalid theme name in the user file and improper validation.
Fixed in 1.1.1379-dev.
