### ISSUE TITLE
[Bug] Cannot change function return type to `void`

### ISSUE THREAD

**Issue by Arcnor** [Vector35/binaryninja-api#1195]
I've tried changing a function return type to `void`, using both the UI and the API, because BN has mistakenly identified the function as returning a value (even when the only usage of it doesn't use the value at all, and BN correctly discovers that the function returns nothing in that context).

After changing the function type, BN runs the analysis very quickly but nothing changes at all.

**Comment by D0ntPanic** [comment]
Fixed in build 1806
