### ISSUE TITLE
[Bug] Xref in function that doesn't contain the xref address, because of tailcall analysis

### ISSUE THREAD

**Issue by Vasco-jofra** [Vector35/binaryninja-api#1196]
As seen in the image below, there are two xrefs of printf for the address 0x2340f  (but for different functions, meaning binary ninja thinks the functions overlap) but in the graph view that address doesn't seem to belong to one of the functions.

![image](https://user-images.githubusercontent.com/11303847/47950856-b1502f00-df50-11e8-8868-487993111bd4.png)

As Josh mentioned on slack, the cause of the problem seems to be that xrefs are being saved prior to tail call analysis. The second xref is in the function that the first one jumps into.

If you want a reproducer ask me on slack `@jofra`.

**Comment by bpotchik** [comment]
Fixed in 1.1.1604-dev.
