### ISSUE TITLE
About current_address

### ISSUE THREAD

**Issue by F1r** [Vector35/binaryninja-api#1198]
How can I set var current_address from a plugin?
I can set it or read it from Embedded python terminal.
Thanks very much!

**Comment by psifertex** [comment]
Binaryview.navigate
https://api.binary.ninja/binaryninja.binaryview-module.html#binaryninja.binaryview.BinaryView.navigate

For API help questions, please consider joining our Slack (slack.binary.ninja and #api-help specifically) or using one of our other support mechanisms instead of filing bugs.
