### ISSUE TITLE
Transform parameters cause errors in log

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#1199]
I'm guessing these views on the parameters are actually Raw BinaryViews, and so that's why it's popping an error message in the log saying it needs a default architecture?

![image](https://user-images.githubusercontent.com/5834130/47980770-076ec080-e07e-11e8-93f2-77c7410aeb54.png)

**Comment by bpotchik** [comment]
Fixed in 1.1.1440-dev.
