### ISSUE TITLE
linux_setup.sh bad path to logo.png

### ISSUE THREAD

**Issue by jar3dp** [Vector35/binaryninja-api#1203]
Binary Ninja Version: 1.1.1344 Personal, c25b2ebb
Platform: Ubuntu 18.04.1 LTS

The linux_setup.sh script seems to have a bad path. It fails to stat the logo.png file. I changed the following to make it work:

PNG="${BNPATH}/docs/images/logo.png"

to

PNG="${BNPATH}/docs/img/logo.png"

Thanks

**Comment by bpotchik** [comment]
Fixed on dev.
