### ISSUE TITLE
Unable to initialize Python API

### ISSUE THREAD

**Issue by WinMin** [Vector35/binaryninja-api#1205]
![image](https://user-images.githubusercontent.com/18380453/48970469-7751e480-f047-11e8-8202-2cfd51975f6e.png)

how 2 sovle it in macos

**Comment by plafosse** [comment]
This usually happens when the python API is somehow failing to load. Launch Binary Ninja from the command line and you should see some python errors show up in the console.

**Comment by joshwatson** [comment]
You’ve probably got homebrew python, which causes issues. Point your settings.json to the path of your homebrew install and it will work fine

**Comment by psifertex** [comment]
If I'm not mistaken I believe this was solved in slack -- settings.json wasn't in the proper folder to override and specify an appropriate python. See: https://docs.binary.ninja/getting-started.html#directories and https://docs.binary.ninja/getting-started.html#settings
