### ISSUE TITLE
python can't import binaryninja

### ISSUE THREAD

**Issue by orangepirate** [Vector35/binaryninja-api#1207]
hi, i don't know why i can't import binaryninja in python(2.7). it always shows  'no module named binaryninja'.  And i've tried lots of method, but all was failed.  i don't know where to get binaryninja module...could you help me ...

**Comment by rmspeers** [comment]
What platform are you on? Windows, Mac, Linux? What is your install path?

**Comment by joshwatson** [comment]
This is the kind of question you should ask on the slack; the github issues are for bug reports and feature requests

**Comment by psifertex** [comment]
Yeah, I'm going to close this one out. 

From the twitter conversation, you were using the demo build which is definitely not compatible with headless mode like that.
