### ISSUE TITLE
type propagation

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#121]
The backend now understands some types for various platforms and libraries, but it needs to propagate those symbols. Likewise for when users will be able to manually assign types, they should also be propagated.

**Comment by D0ntPanic** [comment]
A baseline implementation of type propagation is ready as of dev build 864. Future improvements to type propagation should take place in new issues, some of which are already referenced by this issue.

**Comment by D0ntPanic** [comment]
Issues #772 and #773 were added for some of the remaining improvements to type propagation
