### ISSUE TITLE
Segmentation Fault in BinaryNinja::BinaryView::ParseExpression

### ISSUE THREAD

**Issue by bitbane** [Vector35/binaryninja-api#1214]
I'm getting a segmentation fault in BinaryNinja::BinaryView::ParseExpression when using the binaryninja-offsetview plugin (https://github.com/tchebb/binaryninja-offsetview). It looks like there is a null-pointer derefence right at the beginning of that function according to the attached core dump.

The segfault happens right after entering the new base address.

[core.binaryninja.1000.f62b601922f047809f79fcbf03446d5c.14453.1544208498000000.gz](https://github.com/Vector35/binaryninja-api/files/2658456/core.binaryninja.1000.f62b601922f047809f79fcbf03446d5c.14453.1544208498000000.gz)

**Comment by plafosse** [comment]
I have confirmed the crash and have a local fix, but it will be a bit before I get it committed. A quick fix for this would be to change the interaction.get_address_input to data.get_address_input

**Comment by plafosse** [comment]
Fixed in v1.1.1453
