### ISSUE TITLE
empty strings or types are indistinguishable from each other

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#1215]
Linear view has a nice `Type: __` header at the top to differentiate from other views, and an empty hex view has the address offset, but Types and Strings just show empty windows (if someone hits a hotkey to select one and doesn't realize what they did)

A very small header at the top with "Strings" or "Types" would help disambiguate since the view menu on the bottom right is a bit subtle.

**Comment by bpotchik** [comment]
The tab title was updated a while back which contains the view name which would be "Strings" or "Types".

**Comment by plafosse** [comment]
A simple "No Types Defined" or "No Strings Defined" would be a good option

**Comment by CouleeApps** [comment]
With the advent of the sidebar, and the updated type browser (doesn't just look like an empty box when there are no types) this is no longer an issue.
