### ISSUE TITLE
Feature Request: Graph Overview

### ISSUE THREAD

**Issue by Cryptogenic** [Vector35/binaryninja-api#1217]
The graph disassembly view is great but it lacks a graph overview window. I think a graph overview window would be a great addition, especially for those who use graph view while reversing very large/complex functions. Not only does it help with seeing the overall flow of the function, but it can also be used to quickly navigate large functions by clicking/dragging inside the overview.

Here's an example:
![](https://i.imgur.com/sMTHydZ.png)

**Comment by psifertex** [comment]
This was implemented a few weeks ago. Switch to the dev branch and look in the lower left by the xrefs tab for the new mini graph view. 

Thanks for the prototype though, always helpful in big reports to show what you mean!
