### ISSUE TITLE
Analyzing functions is too slow

### ISSUE THREAD

**Issue by bulzika** [Vector35/binaryninja-api#1218]
This is an issue when analyzing big binaries (for example vmlinux). Even though I have the database of the previous analyzes saved, after opening it BN still takes couple of hours to analyze all functions (which are already found/defined).
This wouldn't be a problem itself, but because of the analyzes, I cannot modify, for example, function signatures. Being able to, at least, manually stop the analyzes would fix the issue for me.
Also, saving the database of the binary file takes too much time. And closing the windows doesn't stop it until it is done saving.

Binary Ninja Version: 1.1.1344 Personal, c25b2ebb
Platform: Windows 10 (10.0)

**Comment by plafosse** [comment]
As of version 1.1.1813 thee Personal edition has analysis caching. This greatly speeds loads from the database.
