### ISSUE TITLE
ARM elf GOT table thumb2 functions references missing

### ISSUE THREAD

**Issue by sprout42** [Vector35/binaryninja-api#1219]
I'm looking at an ARM elf library:
```
$ file libthing.so
libthing.so: ELF 32-bit LSB shared object ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /path/to/interpreter, stripped
```
And the thumb2 functions referenced by the GOT table are missing.

This is the version I am using:
Version 1.1.1443-dev (Build ID 464b1bc7)

**Comment by plafosse** [comment]
Any chance you can share this binary?

**Comment by sprout42** [comment]
Sorry about they super long delay for this response, I'm afraid I can't.  I'm pretty sure the library is missing some of the "strictly not necessary, but usually there" section information.  If there is something specific that I can look up in regards to the ELF structure for the library let me know and I swear I won't take as long to answer next time

**Comment by sprout42** [comment]
So this is a library that for some reason has mixed ARM and Thumb2 functions.  For ARM functions that are exported by this library the GOT table looks something like...
```
00abcd0 int32_t (* const armfunction1()@GOT)() = armfunction1()
00abcd4 int32_t (* const armfunction2()@GOT)() = armfunction2()
```
Where `armfunction1()` and `armfunction2()` are correctly linked to the offset that the function implementation is located at.

Thumb2 functions look something like
```
00abcd8 int32_t (* const thumbfunction1()@GOT)() = 0x650001
00abcda int32_t (* const thumbfunction2()@GOT)() = 0x651001
```
Where in this case `thumbfunction1()` is located @ 0x650000 and `thumbfunction2()` is located at `0x651000` (the extra 1 indication this is a jump to a thumb function.

**Comment by bpotchik** [comment]
I believe this has been fixed a while back. If it's not, please reopen.
