### ISSUE TITLE
Custom keybinding UI

### ISSUE THREAD

**Issue by D0ntPanic** [Vector35/binaryninja-api#1225]
Need to add a UI to be able to reassign hotkeys from within the interface. Currently you must edit a json file and reload the UI to assign custom hotkeys.

**Comment by psifertex** [comment]
Related: automatically show hotkeys when they're mapped in the relevant File / Context menus.

**Comment by CouleeApps** [comment]
Added in build 1.1.1571. Can be found under the Edit menu. Shortcut to bring up the UI is ctrl+shift+b (or cmd+shift+b for macOS).
