### ISSUE TITLE
Tools Menu and Command Palette should focus on the main ViewFrame

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#1228]
The Tools menu and Command Palette both currently determine which commands are valid based on the ViewFrame that is in focus, which means that if you do something like invoke `Log` from the Command Palette and then immediately press Cmd+P again to run a plugin, you won't be able to find the plugin in the palette because the Log frame is currently in focus and plugins aren't valid for that frame. Similarly, all of the plugins under the Tools menu are disabled as well.

**Comment by plafosse** [comment]
Acknowledged and fix is likely incoming today.

**Comment by D0ntPanic** [comment]
Fixed in build 1466
