### ISSUE TITLE
Confusing tooltip

### ISSUE THREAD

**Issue by artemdinaburg** [Vector35/binaryninja-api#123]
I am not sure how to interpret `reads incoming rdi from rbx`. There is a `mov rbx, rdi` early in the basic block, but the instruction reads memory pointed to by `rbx+0x154`, which the tooltip isn't telling me. Also, the tooltips are a really cool feature!

![image](https://cloud.githubusercontent.com/assets/1051838/12837215/522f8256-cb8e-11e5-81a5-769ce0974fd8.png)

**Comment by plafosse** [comment]
could you post what the LLIL view looks like?

**Comment by psifertex** [comment]
Don't have a long term fix yet for this. The short summary is that "reads incoming" is a hint for "the value came from this other place". Which, if rdi is the first argument to the function, should really be aliased to the first argument of the function. So this specific instance will be made more clear when we have stack locals and function arguments and variables implemented. 

That said, we could still probably think about other ways of phrasing it though--you're right, the "incoming" bit is a bit odd.

**Comment by artemdinaburg** [comment]
![image](https://cloud.githubusercontent.com/assets/1051838/12837336/ba1a4102-cb8f-11e5-8785-4622cae55789.png)
LLIL, if you are still interested.

**Comment by plafosse** [comment]
We have no plan for design for how to change this. If more concrete suggestions are available they will be entertained.
