### ISSUE TITLE
Support macOS 10.11.6 El Capitan

### ISSUE THREAD

**Issue by upiter** [Vector35/binaryninja-api#1230]
# Create dev package supporting macOS `10.11.6` (El Capitan)

## Info

After updating Binary Ninja to latest dev version `1.1.1461-dev`, I get this error:

> Sorry, "Binary Ninja" can not be run on this version of macOS. Qt requires macOS 10.12.0 or later, you have macOS 10.11.6.

I'm using macOS 10.11.6 (El Capitan) for research and it's very important for me to use Binary Ninja on it.

## How to reproduce
Run:
```
$ /Applications/Binary\ Ninja.app/Contents/MacOS/binaryninja
```
Output on macOS 10.11.6:
```
Sorry, "Binary Ninja" can not be run on this version of macOS. Qt requires macOS 10.12.0 or later, you have macOS 10.11.6.
```

## Details
Binary Ninja Version: `1.1.1461-dev` Personal
Platform: macOS `10.11.6` (El Capitan)

Last tested working version: `1.1.1344` (2018-10-05)

**Comment by psifertex** [comment]
Unfortunately older versions of QT contain bugs that negatively impact the user experience and we don't want to be constantly back-porting individual fixes (which isn't even possible in some instances) so we're not going to maintain backward compatibility with 10.11.x. Other options you might consider though are running in a Linux VM or another machine and using X-forwarding if it's critical to have the UI displayed  in the older version of MacOS. 

You can also use the built-in version switcher in preferences to switch back to previous builds that use older QT libraries.

**Comment by upiter** [comment]
> older versions of QT

I have qt version `5.12.0` installed via [brew](https://brewformulas.org/Qt) and I have no issues to build apps which are compatible with macOS `10.11.6`.
May be there are some fixes that are incompatible with 10.11.6, but I don't know about that.

> You can also use the built-in version switcher in preferences to switch back to previous builds that use older QT libraries.

I can't open Preferences when I can't run app itself, so I need to manually reinstall older version.

**Comment by upiter** [comment]
May be you explicitly define `QMAKE_MACOSX_DEPLOYMENT_TARGET` to not support `10.11`?

**Comment by psifertex** [comment]
If a commercial license you can use the version switcher example plugin as opposed to manually downgrading first, but yeah, obviously the UI won't work, sorry. 

https://github.com/Vector35/binaryninja-api/tree/dev/python/examples 

I'll double check, but i don't believe we've modified that environment variable.
