### ISSUE TITLE
Loop-based dataflow bug

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#1233]
You can find the binary [here](https://github.com/joshwatson/f-ing-around-with-binaryninja/blob/master/ep3-vm-arch/vm1.bndb)

The binary has a loop in it, where a stack variable is moved into a register, incremented, and then put back into the stack variable. The dataflow believes that this stack variable has a value range of `[0, 3]`, which is not correct. You can see the instructions `0x402308` through `0x40230e` below:

![image](https://user-images.githubusercontent.com/5834130/50721503-5d0f1b80-1075-11e9-9ba4-82a0d9c91c74.png)
and the resulting MLIL:
![image](https://user-images.githubusercontent.com/5834130/50721518-9778b880-1075-11e9-87cf-8a421953f3b3.png)
The stack variable is optimized away, and replaced with a constant at `0x402325`.

**Comment by plafosse** [comment]
We've been able to repro this bug and have a fix for it.

**Comment by rssor** [comment]
Fixed in build 1.1.1487
