### ISSUE TITLE
Ability to track references of variables

### ISSUE THREAD

**Issue by bambu** [Vector35/binaryninja-api#1236]
It would be nice to have an api function to see when a variable is referenced. Currently the closest thing would be `current_mlil.get_var_uses()`. This function does not find any variables that are referenced. 

```python
>>> current_mlil[1]
<il: r3_1 = &var_94>
>>> current_mlil[1].src
<il: &var_94>
>>> current_mlil.get_var_uses(current_mlil[1].src.src)
[]
```

Request would be for either `get_var_uses()` to show the referenced variable or to create a new function that just finds references.

**Comment by joshwatson** [comment]
Bumping this because it's really been causing me some issues lately. I really need either these references to show up in `get_var_uses` or a new `get_var_refs` that provides a list of these.

**Comment by sheadovas** [comment]
Up, binja needs this feature (and many other basic stuff).

Binja for now is just a nice-looking, paid(sic!) platform for writing plugins (sorry, but most of the coolest features of binja are actually written by community) :/

**Comment by joshwatson** [comment]
Not really a fair criticism given that “the coolest features” wouldn’t be possible without the api that drives them....which is kinda the core of Binary Ninja

**Comment by plafosse** [comment]
FWIW This is now available on HLIL `vars_address_taken`

**Comment by plafosse** [comment]
I'm leaving this issue open until I get the one done on MLIL

**Comment by plafosse** [comment]
I don't remember when but `vars_address_taken` was added to MLIL too.
