### ISSUE TITLE
Text searching of IL views

### ISSUE THREAD

**Issue by yuv422** [Vector35/binaryninja-api#1238]
I tried searching for text that contained [ ] characters and no matches were returned.

eg. 

I searched for "[actors]" which resulted in no matches but searching for "actors" returned results.

![image](https://user-images.githubusercontent.com/11899359/50862247-4c510380-13ef-11e9-840a-fee7f3ccea2a.png)

**Comment by plafosse** [comment]
So this issue is actually because we don't do text searching on IL views at all. I'm going to change the text of this ticket to reflect the underlying issue.

**Comment by plafosse** [comment]
We will also want this to be configurable:
- Specify which IL views should be searched
- Specify "search current function only"

**Comment by plafosse** [comment]
Closing in favor of #1969
