### ISSUE TITLE
Instruction tooltips could have a 1-sentence explanation of the instruction

### ISSUE THREAD

**Issue by ianklatzco** [Vector35/binaryninja-api#1239]
I'm learning some ARM and googling for "what is x instruction" constantly is a pain. It would be cool if hovering over a given instruction had a short explanation or name, eg:

![image](https://user-images.githubusercontent.com/1487413/50887492-25231380-13a8-11e9-8134-3e2fa53d455b.png)

would show "Load Register Byte" on the first line.

A friend worked on [this related plugin](https://github.com/nccgroup/binja_explain_instruction), but it's a little bit more heavy-handed than what I've suggested.

Would this be doable with just the API? (ie could I implement it myself)?

**Comment by plafosse** [comment]
Thanks for the feature request.

**Comment by plafosse** [comment]
We're unlikely to implement this.
