### ISSUE TITLE
Double-clicking on an edge should take you to the destination block

### ISSUE THREAD

**Issue by artemdinaburg** [Vector35/binaryninja-api#124]
Double clicking on an edge emanating from one block to another distant block should take you do the distant block. 

My major use case is exploring control flow. When I see a `je` and need to follow the true branch, I have to follow the little green line through a lot of code. I want to just double click the green line and go to the destination of the true branch.

**Comment by psifertex** [comment]
Yes! We've discussed this a lot internally actually but apparently never filed a bug for it. Thanks for mentioning it.

**Comment by D0ntPanic** [comment]
Implemented in dev
