### ISSUE TITLE
program crash when using floating python console with interactive usage

### ISSUE THREAD

**Issue by codingsnippets** [Vector35/binaryninja-api#1240]
Binary Ninja Version: 1.1.1344 Personal, c25b2ebb
Platform: Ubuntu 18.04.1 LTS

To reproduce problem:
View -> Script Console 
```
>>> help() 
>>> # works fine
>>> modules
>>> # loading a few packages, then application crash
```

**Comment by psifertex** [comment]
Does this still happen with the latest dev branch?

**Comment by codingsnippets** [comment]
yes, just tried using:
Binary Ninja Version: 1.1.1462-dev Personal, 7fd03575
Same behavior.

**Comment by plafosse** [comment]
Thanks for reporting the issue, we've been able to reproduce the issue.

**Comment by fuzyll** [comment]
This doesn't repro for me on 3.0.3321-dev. I suspect it's been fixed for awhile, since the original report is over 3 years old. Closing this now.
