### ISSUE TITLE
Can not open arm linux .ko file

### ISSUE THREAD

**Issue by tridentsx** [Vector35/binaryninja-api#1241]
Binary Ninja Version: 1.1.1344 Personal, c25b2ebb
Platform: Windows 10 (10.0)

Opened a new ticket since old was closed, I have attacvhed an example arm .ko file that fails to load.

[ext3.zip](https://github.com/Vector35/binaryninja-api/files/2749815/ext3.zip)

**Comment by plafosse** [comment]
@tridentsx unfortunately these changes haven't made it into the Stable build yet. You'll need to switch to the development build > v1.1.1345 This can be done using the version switcher in the preferences menu option.
