### ISSUE TITLE
If MLIL splits instruction at given address into several, comments are displayed at every split

### ISSUE THREAD

**Issue by Maykeye** [Vector35/binaryninja-api#1243]
Binary Ninja Version: 1.1.1462-dev Personal, 7fd03575
Platform: Windows 10 (10.0)

If I add a comment (by pressing ; key) to address which contains instruction like `sbb` or `cmp` which in mlil is split into several subinstructions, my comment gets repeated near every MLIL instruction:

![image](https://user-images.githubusercontent.com/13607441/51089516-cfc87700-1798-11e9-8e9f-cf4c0d687383.png)

(Binary is from https://crackmes.one/crackme/5c1d6f5f33c5d41e58e005f5 )

**Comment by psifertex** [comment]
Also related to the fact that highlighting between the different views isn't distinct. Highlights and comments should optionally be associated with a specific instruction and not a function/address combination.

**Comment by rssor** [comment]
Fixed in build 1.1.1487 -- a basic block will no longer display a comment more than once. Comments can still be duplicated when lifted into multiple IL blocks, once for each IL basic block that it occurs in.
