### ISSUE TITLE
If a local variable type changed to bigger one, an aliased variable disappear from declarations, but exists in MLIL

### ISSUE THREAD

**Issue by Maykeye** [Vector35/binaryninja-api#1245]
Binary Ninja Version: 1.1.1462-dev Personal, 7fd03575
Platform: Windows 10 (10.0)

![image](https://user-images.githubusercontent.com/13607441/51133536-711a0080-185f-11e9-87f8-cf6c1aad4c0c.png)

Here the function clears 28 bytes starting (from var_47) in the buffer using `rep stos.d` and 1 byte (var_48) with  a single byte by `mov`. 

Since it's two different assignments, BN thinks that it's different variables (pictured on the left)
But since it all looks like a single buffer, I want to change type of `var_48` from `char` to `char[0x20]`. 

Doing this removes var_47 from list of variables (as it's now part of var_48), but MLIL code still displays var_47(I expected &var_48+1)  (right part of the picture - var_47 is gone)

If I try to rename var_47 before changing the type of var_48 (e.g. to "buf_48[1]", after changing the type, name is changed back to var_47 and I can't re`n`ame it anymore.

(Executable: https://crackmes.one/crackme/5c38a2f133c5d475210bc581)

**Comment by plafosse** [comment]
This issue was fixed I believe in 2.3
