### ISSUE TITLE
no MIPS16 support

### ISSUE THREAD

**Issue by dzonerzy** [Vector35/binaryninja-api#1246]
I tried to reverse a mips binary in IDA and in BinaryNinja, the last one was unable to recognize a lot of functions

**Comment by dzonerzy** [comment]
Wrong binary here's the correct one 

[gl_cgi.zip](https://github.com/Vector35/binaryninja-api/files/2761257/gl_cgi.zip)

**Comment by psifertex** [comment]
RE: the conversation in slack, this appears to be a MIPS16 binary which we don't have support for. Going to close this issue for now as we don't track future architectures here. If you're interested in what it would take to implement  MIPS16 support yourself, suggest you join the #api-help channel in the slack as there are several folks in there who have implemented architecture plugins. Thanks for the sample, if we do add MIPS16 support we'll take a look at this again.
