### ISSUE TITLE
AnalysisCompletionEvents are triggering immediately

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#1248]
Using `BinaryView.add_analysis_completion_event` or instantiating a new `AnalysisCompletionEvent` object is triggering analysis for some reason lately, which then in turn fires off the completion event immediately; as such, they're kind of useless at the moment.

**Comment by plafosse** [comment]
This problem only presents itself in the python console. Binary Ninja updates after every type you submit python in the console. If you do need one you can add it in a function.
