### ISSUE TITLE
Big endian ARM not supported

### ISSUE THREAD

**Issue by gynophage** [Vector35/binaryninja-api#125]
New -> C source -> {code} -> armeb, platform none.

Hit p.
Choose armv7.
Weep.

**Comment by psifertex** [comment]
Thanks for the report -- it's actually a subset of the broader issue that our endianness support in general is lacking. I've renamed the bug accordingly, we'll track progress on the bigger issue here.

**Comment by D0ntPanic** [comment]
Choosing the endianness is now possible if the disassembler supports it, but not all architectures support disassembly in both formats.  It is implemented in MIPS.

**Comment by plafosse** [comment]
Fixed in dev
