### ISSUE TITLE
Add pseudosymbols to BinaryView.parse_expression

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#1250]
It would be really nice to be able to reference things like the base address of a BinaryView in `BinaryView.parse_expression` (and by extension, the "Go to" dialog); something like `$start + 0x1000` being resolved to `bv.start + 0x1000` would be really cool. Other things like being able to reference segments and sections (something like `$section(.text)` or the like), or just the ability to reference any BinaryView properties directly by name would be very nice.

**Comment by plafosse** [comment]
Yeah I started implementing something like this but then stopped when it got to be too much work. I'd definitely like to do something like this in the future. It might even be cool if you could define your own pseudosymbols, though I'd probably call them automatic variables or something like that.

**Comment by joshwatson** [comment]
At the very least I'd just like to be able to reference the base address of the view so I don't have to calculate it myself if all I have is an offset for the "Go to" dialog

**Comment by plafosse** [comment]
Added `$start` and `$end` in v1.1.1762 section names are also supported, as of earlier versions.
