### ISSUE TITLE
Relocation APIs using xrange

### ISSUE THREAD

**Issue by alexmullins** [Vector35/binaryninja-api#1251]
Currently on v1.1.1472-dev.

Was messing around with the relocation APIs and got an error about the use of xrange:

`Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/binaryview.py", line 1252, in relocation_ranges
    for i in xrange(0, count.value):
NameError: name 'xrange' is not defined`

I searched through the codebase and found that BinaryView.relocation_ranges[_at] and Segment.relocation_ranges[_at] are still using xrange and they break while using python3.

**Comment by plafosse** [comment]
Thanks, I've fixed this issue, since its not critical it will go out when we update api submodule again.

**Comment by plafosse** [comment]
Fixed in 1.1.1473
