### ISSUE TITLE
Instruction `endbr64` gets disassembled as a `nop`

### ISSUE THREAD

**Issue by erhlee-bird** [Vector35/binaryninja-api#1256]
Context
===
```
$ clang --version
clang version 7.0.1 (tags/RELEASE_701/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

```C
int main() {
    return 0;
}
```

```
$ clang lol.c
```

```
$ objdump -d a.out
...

00000000000011a0 <__libc_csu_fini>:
    11a0:	f3 0f 1e fa          	endbr64 
    11a4:	c3                   	retq   

Disassembly of section .fini:

00000000000011a8 <_fini>:
    11a8:	f3 0f 1e fa          	endbr64 
    11ac:	48 83 ec 08          	sub    $0x8,%rsp
    11b0:	48 83 c4 08          	add    $0x8,%rsp
    11b4:	c3                   	retq   
```

The endbr64 instruction is being lifted as a nop.

<img width="490" alt="binja_endbr64" src="https://user-images.githubusercontent.com/633268/51704397-f8e1d680-1fe6-11e9-981d-24c696fe58f0.png">

I'm using 1.1.1.481-dev.

Similar issues in other tools
===
- https://github.com/aquynh/capstone/issues/1129
- https://github.com/radare/radare2/issues/10113

Cheers!

**Comment by psifertex** [comment]
Thanks for the report -- XED supports it we just need to enable their CET option and should get it for free. Should be fairly easy to fix.

**Comment by jeffli678** [comment]
fixed in 2305
