### ISSUE TITLE
Incorrect x86 rep movs lifting

### ISSUE THREAD

**Issue by 0x1F9F1** [Vector35/binaryninja-api#1262]
Binary Ninja Version: 1.1.1486-dev, 747f0dfa
Platform: Windows 10 (10.0)

`rep movsw`, `rep movsd` and `rep movsq` are all lifted the same as `rep movsb` (only copying 1 byte at a time)

**Comment by KyleMiles** [comment]
Fixed in 1.1.1722-dev.
