### ISSUE TITLE
Convert value ranges with same start/end

### ISSUE THREAD

**Issue by 0x1F9F1** [Vector35/binaryninja-api#1264]
Binary Ninja Version: 1.1.1491-dev, dad47d9e
Platform: Windows 10 (10.0)

Sometimes you can end up with a value range that has the same start and end. It would be great if these were converted into constants. E.G

```
0 | rax = rcx
1 | rax = rax & 0x3
2 | rax = rax u>> 2
3 | <return> jump(pop)
```

```
>>> current_llil[2].src.possible_values
<unsigned ranges: [<range: 0x0 to 0x0>]>
```

**Comment by plafosse** [comment]
I believe these are simplified now.
