### ISSUE TITLE
Crash When Redefining Type

### ISSUE THREAD

**Issue by ericevenchick** [Vector35/binaryninja-api#1265]
Steps to Reproduce:
1. Create a struct type in the Types window:
```
struct crash
{
    uint8_t data[8];
};
```
2. Use Change Type in Linear Disassembly window to assign data the newly created type
3. Go back to types pane and undefine the type
4. Create a new type with the same name:
```
struct crash
{
    uint32_t data;
    uint8_t data2[4];
};
```
5. Return to the location of the data in Linear Disassembly, double click to update the type info.

This crashes binja and also results in a database that will crash binja when viewing the data assigned to the redefined type. 

Binary Ninja Version: 1.1.1492-dev, 3c53180b
Platform: macOS Sierra (10.12)

**Comment by plafosse** [comment]
I've confirmed the issue. My guess is that we have a stale reference to the old structure hanging around.

**Comment by jeffli678** [comment]
This is no longer crashing as in stable 2.0. Also we will support direct type redefinition in type view.
