### ISSUE TITLE
“Error initializing database: Data too large” when saving Analysis Database for a large binary

### ISSUE THREAD

**Issue by Ouroboros** [Vector35/binaryninja-api#1267]
Binary Ninja Version: 1.1.1470
Platform: macOS 10.14.3, 32G RAM

When loading a large binary (about 81MB) with Binary Ninja, it takes about 18GB of RAM. Furthermore, saving Analysis Database for this binary ends on the following error:

![8f075d3e350b84f3a2dff3362984cbd7](https://user-images.githubusercontent.com/1687847/52134556-798a7d80-264c-11e9-9715-f15481a20974.jpg)

Any idea how to successfully save the database?
I can provide/upload the binary if you need.

**Comment by plafosse** [comment]
Unfortunately this is a known issue that I guess we don't already have a bug for. Large files fail to save due to some considerations SQLite's maximum size limitations. There is a SQLite feature that exists we're just currently not using it.

**Comment by Ouroboros** [comment]
Hi. Thanks for your response. Is there any ETA for the fix?

**Comment by KyleMiles** [comment]
Fixed as of 1.1.1745-dev.
