### ISSUE TITLE
Switch over to CFFI for PyPy support

### ISSUE THREAD

**Issue by mattz0rt** [Vector35/binaryninja-api#1269]
This is more of a feature request, but we would love to be able to use PyPy with binja since our analysis runs can take significant amounts of time. Unfortunately since the python API uses ctypes PyPy is unable to run without function import issues, e.g.
```
  File "/home/user/binaryninja/python/binaryninja/binaryview.py", line 2374, in get_function_at
    plat = self.platform
  File "/home/user/binaryninja/python/binaryninja/binaryview.py", line 995, in platform
    return binaryninja.platform.Platform(self.arch, handle=plat)
  File "/home/user/binaryninja/python/binaryninja/binaryview.py", line 980, in arch
    return binaryninja.architecture.CoreArchitecture._from_cache(handle=arch)
  File "/home/user/binaryninja/python/binaryninja/architecture.py", line 2274, in _from_cache
    return _architecture_cache.get(ctypes.addressof(handle.contents)) or cls(handle)
  File "/home/user/binaryninja/python/binaryninja/architecture.py", line 2078, in __init__
    info = core.BNGetArchitectureRegisterInfo(self.handle, regs[i])
  File "/opt/pypy2-v6.0.0-linux64/lib_pypy/_ctypes/function.py", line 351, in __call__
    funcptr = self._getfuncptr(argtypes, self._restype_, thisarg)
  File "/opt/pypy2-v6.0.0-linux64/lib_pypy/_ctypes/function.py", line 419, in _getfuncptr
    ptr = self._getfuncptr_fromaddress(argtypes, restype)
  File "/opt/pypy2-v6.0.0-linux64/lib_pypy/_ctypes/function.py", line 410, in _getfuncptr_fromaddress
    return _ffi.FuncPtr.fromaddr(address, '', ffiargs, ffires, self._flags_)
SystemError: not supported by libffi
```
Switching over to cffi shouldn't be too much work since it's just repackaging the interface, but it should amount to large speed increase via pypy that would give a significant boost to our development pace (and hopefully for others as well). Thanks for considering!

**Comment by psifertex** [comment]
Thanks for the suggestion. One minor issue is that right now we have no dependencies outside the standard library on MacOS and Linux (on Windows we ship our own runtime anyway so it's less of a concern as we can ship whatever dependencies we need) so it makes the standard use case a bit more complicated and means the setup process there is potentially more complicated. 

For long-running high performance applications we highly recommend using the C++ API directly. Python is great for many small plugins and for prototyping things but if performance is an issue, the ultimate suggestion is going to be using a different set of bindings. 

If you prefer Rust over C/C++, there's a set of rust bindings in development that we can give you access to as well which would be another good alternative. 

Leaving this open for now but it's unlikely Vector35 will be working on it any time soon unfortunately. Of course, the API itself is open source so it's possible someone else could take a stab at it.

**Comment by mattz0rt** [comment]
Thanks Jordan for the response. In terms of using other bindings it's definitely a tradeoff in terms of reducing runtime via C++/Rust vs development speed via python, but we'll talk it over internally to see what makes the most sense.

**Comment by mattz0rt** [comment]
Hey @psifertex, I'm considering tackling this issue. Would it be possible to get access to the header file for binary ninja's core library? It would be a lot easier than reverse engineering it from _binaryninjacore.py

**Comment by joshwatson** [comment]
The header is in the repo

**Comment by mattz0rt** [comment]
Doh, thanks @joshwatson

**Comment by plafosse** [comment]
Sorry we're not going to try to do this any time soon.

**Comment by psifertex** [comment]
One other minor suggestion -- while it currently is still very much in need of being fully fleshed out, the Rust API might be another option with a better trade-off between speed of development and performance depending on your needs.
