### ISSUE TITLE
Mismatch between MediumLevelILOperation operands and MediumLevelILOperation.ILOperations

### ISSUE THREAD

**Issue by Vasco-jofra** [Vector35/binaryninja-api#1275]
In the `MediumLevelILInstruction` class, MLIL_SET_VAR_SSA_FIELD is defined as `MediumLevelILOperation.MLIL_SET_VAR_SSA_FIELD: [("prev", "var_ssa_dest_and_src"), ("offset", "int"), ("src", "expr")]`, but an instruction of that type has 4 operands (image below) and not 3.

![image](https://user-images.githubusercontent.com/11303847/52527370-8730aa80-2cbf-11e9-9864-8e0d7146a929.png)

While it isn't really a bug, it prevents the easy use of `MediumLevelILOperation.ILOperations` in cases like:
```
# Snippet from the plugin 'bnil-graph' by @withzombies 
for i, o in enumerate(il.operands):
    edge_label = il.ILOperations[il.operation][i][0]
```

This fails because `il.operands` is a list with 4 elements, but there are only 3 corresponding fields in  `il.ILOperations[il.operation]`, resulting in a `IndexError: list index out of range`.

**Comment by psifertex** [comment]
Unfortunately this is not possible to be changed at the moment and is due to a core design decision for how the SSA_variables need to be identified.
