### ISSUE TITLE
Right-clicking on an address, the hex view can cover the right-click menu

### ISSUE THREAD

**Issue by devtty1er** [Vector35/binaryninja-api#1280]
Binary Ninja Version: 1.1.1507-dev, c38cb24e
Platform: macOS 10.14

Possibly related to #174

![Example](https://imgur.com/download/CGX1Ylp)

**Comment by psifertex** [comment]
Not an actual fix, but this can be mitigated in build 1511 where you now have the `ui.manualTooltip` advanced preference that prevents tooltips from showing up at all unless `<ctrl>` is held down.

**Comment by bpotchik** [comment]
Fixed in build 1.1.1522-dev.
