### ISSUE TITLE
Feature Request: Advanced search options

### ISSUE THREAD

**Issue by monosource** [Vector35/binaryninja-api#1282]
I've been looking through the issues believing that I will find one similar to this, but I haven't managed to do so. If there is one or if this feature is planned, I apologize in advance.

One thing that I (and hopefully many people in the community) find useful is the ability to do pattern-based searches (fuzzy search/regular expressions).

A few examples/use cases:

1. Searching for a sequence of bytes in which some are fixed and some may change i.e. `\xde\xad\x??\xef`
2. Searching for instructions in which one of the operands can change i.e. `mov al, ??`
3. Searching for entire sequences of instructions in which some parts/instructions may change (can be applied to disassembly, LLIL, MLIL and so on)
```
sub rsp, ??
[1]               // exactly one instruction
pop rdi
[3-5]             // between 3 to 5 instructions
xor ??, rdi
```
I have been cobbling together a very hackish plugin which searches through all instruction ranges using Python's `re` module with `re.MULTILINE`, but it can only search through functions which are defined as such (it can't search through arbitrary data which might turn out to be code).

Of course, one approach (for scenario 3) would be to disassemble all sequence of bytes for all offsets and see if matches the search criteria, but that would be awfully slow. A smarter/harder approach would be to somehow assemble a search query into a sequence of bytes with wildcards/regexp and reduce use cases 2/3 to use case 1. (i.e. `mov al, ??` -> `\xb0\x??`)

**Comment by psifertex** [comment]
We've definitely had this on our roadmap as a planned feature, but I don't see an existing issue for it, so thanks for filing it. 

There's a couple of different related features. For example, an LLIL based ROP gadget finder would abstract away a lot of specific instruction semantics and let you describe effects you wanted.That's probably actually a better solution than just a partial text match on the disassemble unless you've got a use case you think that wouldn't cover?

**Comment by monosource** [comment]
I believe LLIL-based searching would cover pretty much everything (excepting a few exotic instructions which aren't lifted yet).

Still, there's the issue of "functions" which aren't defined as such at the time of searching (seen as arbitrary bytes in the `.text.` section, for instance, if there are no xrefs to them).

**Comment by psifertex** [comment]
Right, that's a different issue which we've taken to calling "code preview" internally which would let you create unaffiliated code and search it. In the meantime, best work-around is a plugin using the assembler and `find_next` APIs.

**Comment by plafosse** [comment]
Closing in favor of #1969
