### ISSUE TITLE
Unexpected type inference - Raw binary vs BNDB

### ISSUE THREAD

**Issue by jackaaron** [Vector35/binaryninja-api#1285]
Binary Ninja version: 1.1.1470 (release), build a3b48b43
Platform: Linux (ubuntu 18.04)

Types may be incorrectly inferred  - even after forcing reanalysis. Behavior varies depending on whether the binary or bndb is being analyzed.

example binary: `libtiff.so.5.4.0` [libtiff.zip](https://github.com/Vector35/binaryninja-api/files/2906929/libtiff.zip), https://gitlab.com/libtiff/libtiff/-/archive/v4.0.10/libtiff-v4.0.10.tar.gz

open binary in Binja GUI, in python console: 

```
bv.update_analysis_and_wait()
TIFFRGBAImageBegin_func = bv.get_function_at(bv.symbols['TIFFRGBAImageBegin'].address)
print TIFFRGBAImageBegin_func.get_low_level_il_at(0x25956).medium_level_il.ssa_form
bv.reanalyze()
bv.update_analysis_and_wait()
TIFFRGBAImageBegin_func = bv.get_function_at(bv.symbols['TIFFRGBAImageBegin'].address)
print TIFFRGBAImageBegin_func.get_low_level_il_at(0x25956).medium_level_il.ssa_form
```
results should be the same for each print: 
```
esi#1 = arg2#0
esi#1 = arg2#0
```

write bndb
```
bv.create_database(bv.file.filename + '.bndb')
```
open saved bndb in Binja GUI, repeat same steps as above, results will be different:
```
esi#1 = arg1#0
esi#1 = arg1#0
```

**Comment by KyleMiles** [comment]
This has been resolved at some point.  It appears to have been before the release of 1.3.
