### ISSUE TITLE
BNGetMediumLevelILExprText returns False for MLIL_CALL_OUTPUT_SSA output operand

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#1286]
This results in `<il: invalid>` when trying to print `current_mlil[96].ssa_form.output`
```
>>> current_mlil[96].ssa_form.operands[0].operation
<MediumLevelILOperation.MLIL_CALL_OUTPUT_SSA: 122>
>>> current_mlil[96].ssa_form.operands[0].operands
[57, [<ssa <var int64_t rax_28> version 44>]]
>>> tokens = ctypes.POINTER(core.BNInstructionTextToken)()
>>> count = ctypes.c_ulonglong()
>>> core.BNGetMediumLevelILExprText(current_mlil.ssa_form.handle, bv.arch.handle, current_mlil[96].ssa_form.operands[0].expr_index, tokens, count)
False
```
Unsure if this is a python3 issue or an overarching issue

**Comment by plafosse** [comment]
MLIL_CALL_OUTPUT_SSA is not a valid top level expression unfortunately, this API could use some improvements.

**Comment by plafosse** [comment]
As of 2.4.2969 MLIL_CALL_OUTPUT_SSA is now a valid top level expression in the python API and can be accessed normally like all the other instructions.
