### ISSUE TITLE
MediumLevelILFunction.llil and MediumLevelILInstruction.llil don't match for Mapped MLIL

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#1288]
For Mapped MLIL, `MediumLevelILFunction.llil` returns the corresponding LLIL `LowLevelILFunction` object, but `MediumLevelILInstruction.llil` returns the corresponding LLIL SSA `LowLevelILInstruction` object. This can be confusing for a user that would expect `current_llil.mmlil.llil == current_llil[1].mmlil.llil.function` to hold true.

**Comment by plafosse** [comment]
Changing this would break a lot of plugins. You can always use `.non_ssa` to get the non-ssa form.
