### ISSUE TITLE
Python DataRenderer seems totally broken

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#1289]
The example `DataRenderer` subclass in the docs appears to crash BinaryView as soon as you start scrolling through Linear View.

**Comment by plafosse** [comment]
I tried to repro this but was unable to. Any chance you can come up with more complete repro steps and verify you're starting from default configuration.

**Comment by joshwatson** [comment]
Rusty fixed this in 1.1.1542-dev I believe!
