### ISSUE TITLE
get_next_data_var_after return type

### ISSUE THREAD

**Issue by devtty1er** [Vector35/binaryninja-api#1294]
Binary Ninja Version: 1.1.1540-dev, c51ae7c5
Platform: macOS 10.14

The example usage seems a bit roundabout:
```
>>> hex(bv.get_next_data_var_after(0x10000000))
'0x1000003cL'
>>> bv.get_data_var_at(0x1000003c)
<var 0x1000003c: int32_t>
```

I would expect:
```
>>> bv.get_next_data_var_after(0x10000000)
<var 0x1000003c: int32_t>
```

**Comment by bpotchik** [comment]
Fixed in 1.1.1613-dev. The API for data variables was cleaned up to have `_start` similar to the other relevant APIs. A convenience method was added to python for returning DataVariable objects.
