### ISSUE TITLE
Add more PDB options in Advanced Settings

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#1296]
I'd really like to be able to choose what information is applied from a PDB. For example, if a PDB has a lot of types, this essentially locks up Binary Ninja for a long time because they're apparently all applied on the main thread (this is a separate issue that should also probably be addressed). So, I'd really like to be able to choose in the Advanced Settings to only apply function symbols from the PDB and ignore types.

**Comment by psifertex** [comment]
Updated #695 to include making them options since it describes some more specific features we plan to add. If there's missing options on that issue, please add a comment and we'll updat eit
