### ISSUE TITLE
interface to display binary properties

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#13]
_From @psifertex on May 29, 2015 21:30_

Mappings, executable pages, ASLR, etc. 

_Copied from original issue: Vector35/binaryninja#38_

**Comment by plafosse** [comment]
Mappings and executable pages are displayed at the top of linear view, ASLR info could be done by a plugin if needed I'm going to mark this as closed.

**Comment by joshwatson** [comment]
Is it possible for a plugin to add information to the top of linear view?

**Comment by plafosse** [comment]
Nope. Any particular use case? Internally we call these "SummaryLines"

**Comment by joshwatson** [comment]
Your comment about "ASLR info could b done by a plugin" made me think that it would be nice if we could add things to the SummaryLines like that, or other information gleaned from headers that might be interesting. As an example, if it were possible to create my own SummaryLines, I'd probably churn out a quick plugin to pretty print most information in the PE headers
