### ISSUE TITLE
Preview window for branches displays hex view

### ISSUE THREAD

**Issue by gynophage** [Vector35/binaryninja-api#130]
The floating window when you hover over a jump instruction in Disassembly view is a hex view, unlike when you hover over a call, which is a disassembly view.

**Comment by plafosse** [comment]
Same problem for LLIL and LIL views.

**Comment by bpotchik** [comment]
Fixed in build 1.1.1113-dev.

**Comment by jeffli678** [comment]
I believe we are having a regression on this

**Comment by bpotchik** [comment]
Fixed in `2.3.2662`.
