### ISSUE TITLE
[Python console] empty command is stored in command history

### ISSUE THREAD

**Issue by Vasco-jofra** [Vector35/binaryninja-api#1301]
In the python console if you press <ENTER> without any input, an empty command gets stored in the history. Afterwards when you press <ARROW_UP> you get the empty command instead of the last real command you executed.

It's a really minor issue but sometimes I press <ENTER> just to get some space between commands and expect the last command to appear when I press <ARROW_UP>.

**Comment by psifertex** [comment]
Fixed in builds >= 1676.
