### ISSUE TITLE
OSX Full screen shortcut

### ISSUE THREAD

**Issue by soen-vanned** [Vector35/binaryninja-api#1304]
Most applications in OSX have Control+Command+F tied to full screen, while Binary Ninja just has a dropdown for "Enter Full screen". Would it be possible to get that keybinding tied to entering and exiting full screen?

**Comment by psifertex** [comment]
That's implemented via QT so it's slightly different than our normal keybinding system unfortunately. The good news is that for MacOS in particular the generic menu keybindings will work just fine. So if you go to settings/keyboard/shortcuts/app shortcuts you can create a mapping there. 

I recommend making one for "Exit Full Screen" too if you do that so the same hotkey toggles.

**Comment by psifertex** [comment]
Actually scratch that -- it's not QT but rather a MacOS feature I think.

**Comment by soen-vanned** [comment]
Right on, thanks!
