### ISSUE TITLE
allow easy selection -> new file

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#1305]
New feature allowing an existing selection to be easily be opened in a new file.

Possible UI implementations (in my current order of preference but still brainstorming):

File / New Tab from Selection
Using the `selection` menu on the bottom bar
Edit / Copy selection to new tab

**Comment by plafosse** [comment]
Seems like it would make a good snippit ;)

**Comment by psifertex** [comment]
Done: https://gist.github.com/psifertex/6fbc7532f536775194edd26290892ef7#file-new_file_from_selection-py
