### ISSUE TITLE
Infinite loop when opening malware sample

### ISSUE THREAD

**Issue by richardmss** [Vector35/binaryninja-api#1306]
Binary Ninja Version: 1.1.1555, 1d59e7dc
Platform: Ubuntu 18.10

Malicious sample attached in archive causes and infinite loop when opening in binaryninja. Password is "infected".
[sample.zip](https://github.com/Vector35/binaryninja-api/files/2999670/sample.zip)

**Comment by bpotchik** [comment]
Fixed in build 1.1.1567-dev.
