### ISSUE TITLE
Edit Current Line with large block width

### ISSUE THREAD

**Issue by anthok** [Vector35/binaryninja-api#1307]
When in graph view and a disassembly block is wide enough, while trying to "Patch -> Edit Current Line" it re-centers the line to where it is not viewable. There is also no way to move your view while in Edit Line without leaving Edit mode.

Test Case was in ARM32 below
![Bug Gif](https://i.imgur.com/DyCEfhZ.gif)

**Comment by psifertex** [comment]
Fixed in 1574.
