### ISSUE TITLE
Can't use Binary Ninja if undocked tab is last window closed

### ISSUE THREAD

**Issue by holmesmr** [Vector35/binaryninja-api#1308]
Running Binary Ninja 1.1.1555 on Windows 10 x64.

I had a file open and popped out the Python console into it's own modal window. I closed the project view later on forgetting the Python console was still open. After closing the Python console Binary Ninja closed, but then on any future attempts the main window no longer appeared on startup, nor when manually opening any files by dragging them onto the shortcut or opening previous projects from the application's jumplist.

**Comment by holmesmr** [comment]
(as a note, I have fixed this situation by deleting the `0_geometry` and `0_state` registry keys in `HKCU\Software\ Vector 35\Binary Ninja\ui\mainwindow`)

**Comment by bpotchik** [comment]
You can also pass the -w command line option to reset the window state, which will also remove the settings from the registry. Does this issue still happen for you with the latest dev version which is 1567? I was not able to repro this issue yet.

**Comment by holmesmr** [comment]
It looks like in 1567 closing the main window also closes these types of windows, which eliminates the issue.

**Comment by bpotchik** [comment]
Great, thanks for checking on that! Closing this issue.
