### ISSUE TITLE
truncated choices in binaryninja.interaction.get_choice_input on macOS

### ISSUE THREAD

**Issue by melomac** [Vector35/binaryninja-api#1311]
It is unclear if the issue affects other platform.

Here you have an example of the issue:
<img width="757" alt="example" src="https://user-images.githubusercontent.com/1131386/55239700-8801a980-5237-11e9-8d55-0ff42b9d17fa.png">

And here you have an example of the expected behavior (i.e. with a 15-space padding):
<img width="843" alt="example_with_padding" src="https://user-images.githubusercontent.com/1131386/55239698-8801a980-5237-11e9-848a-f73907d45ee7.png">

**Comment by plafosse** [comment]
This API is intentionally restrictive. It doesn't know the sizes of the font which it will be rendered with. To get more configurability we recommend using a UI plugin instead.
