### ISSUE TITLE
Something really funky is happening when reading certain addresses in devbuild 1583

### ISSUE THREAD

**Issue by 404d** [Vector35/binaryninja-api#1319]
1582 on the left and 1583 on the right. Notice how the addresses are suddenly in the 0x20000000 range instead of 0x10000000.

This occurs both for freshly loaded binaries and existing "healthy" BNDBs

![Skjermbilde 2019-04-05 kl  00 10 10](https://user-images.githubusercontent.com/451886/55592203-0975a200-5738-11e9-9221-5d8357f3c3ae.png)

Reproducable on both Linux and OS X. File's straight from SysWOW64 in a Windows 10 install, but I've seen this in multiple other DLLs.

[ieframe.dll.zip](https://github.com/Vector35/binaryninja-api/files/3045710/ieframe.dll.zip)

**Comment by bpotchik** [comment]
Thanks for reporting. I just fixed several bugs related to relocations and this was an oversight in the PE relocation handler.

Fixed in 1.1.1584-dev.
