### ISSUE TITLE
cross platform PE/PDB symbol support

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#132]
Remove debughelp dependency for windows, and add support for linux and OS X to handle the symbols as well.  https://github.com/Microsoft/microsoft-pdb

**Comment by willglynn** [comment]
I wrote a [cross-platform `pdb` library](https://github.com/willglynn/pdb) in Rust. It has permissive licensing, and being Rust, it could be readily packaged into a C library and statically linked into Binary Ninja or anything else.

`cargo run --example pdb_symbols /path/to/something.pdb` produces tab-delimited output like:

    segment offset  kind    name
    1       6ee680  function        ??_H@YAXPEAX_K1P6APEAX0@Z@Z
    1       b00278  function        ??_L@YAXPEAX_K1P6AX0@Z2@Z
    1       b002e8  function        ??_M@YAXPEAX_K1P6AX0@Z@Z
    1       b1ed78  function        _purecall
    1       b003b8  function        ??2@YAPEAX_K@Z
    1       b003f4  function        ??3@YAXPEAX@Z
    1       b003fc  function        ??3@YAXPEAX_K@Z
    1       b00404  function        ??_U@YAPEAX_K@Z
    1       b003fc  function        ??_V@YAXPEAX@Z
    1       b0040c  function        ??_V@YAXPEAX_K@Z
    1       b006a4  function        atexit
    1       b1f4b4  function        __RTtypeid
    …

It's also quite fast. Processing a 176 MB `.pdb` for an 18 MB `.exe`:

    $ time target/release/examples/pdb_symbols /path/to/something.pdb | wc -l
       57682

    real	0m0.113s
    user	0m0.070s
    sys	0m0.098s

**Comment by lucasduffey** [comment]
@willglynn: you could write a plugin? There will be a plugin store in v1.2 release. Examples are at https://github.com/Vector35/binaryninja-plugins/tree/master/plugins.

**Comment by willglynn** [comment]
@lucasduffey: true, but I have zero familiarity with the plugin API and limited familiarity with Python. PDB support in Binary Ninja is not a pressing enough concern for me to build a plugin at this time.

I needed a cross-platform PDB library for other reasons, and I didn't find one, so I wrote one myself. I then whipped up a [tiny `pdb_symbols` example](https://github.com/willglynn/pdb/blob/master/examples/pdb_symbols.rs), made its output easy to parse, and mentioned it here. It shouldn't be hard for someone who's already familiar with the plugin API to wrap that example into something useful, even without touching Rust at all.

Having said that, Binary Ninja already knows how to find symbols for ELF and Mach-O binaries without a plugin; I kind of think it should be able to find symbols using PDBs too. I don't care _how_, but I think it should have that feature. The licensing on my library permits companies like Vector 35 to directly integrate it into their products if they so choose, so I wanted to point that out too.

**Comment by willglynn** [comment]
Another thought. PDBs contain excruciatingly detailed information about the target program:

* You get class/struct layouts, with sizes and offsets and names and types of each member variable.
* You get enumerations with all the names and values listed out for you.
* You get constants and globals listed with names, types and values.
* You get vtable layouts, down to information about offsetting the `this` pointer for multiply-inherited child classes.
* You get function information: positions, names, and types of parameters, and the type of the return value.
* You get offsets, names, and types of local variables in each stack frame.
* You get information about which functions were inlined into which other functions in the compiled executable, and specifically where each occurred.

It's definitely worth figuring out which information you want and how to integrate it into the host program. `cargo run --example pdb_symbols` is just a toy. Granted, it's a useful toy that provides a feature not currently offered by Binary Ninja – but it's a toy compared to what could be built using the information in the PDBs.

**Comment by plafosse** [comment]
@willglynn very cool do you pull out all of the above detail from the PDB or just symbol information?

**Comment by willglynn** [comment]
@plafosse All but the last two bullet points are available in my library right now.

**Comment by psifertex** [comment]
@willglynn Thanks much for that example library. @plafosse has implemented an initial pass of PDB parsing available as a built in plugin. Going to close this as complete though we'll be opening some new specific bugs to track other features that aren't yet implemented that we'd like to implement.
