### ISSUE TITLE
Not all XREFs are shown (and some are invalid)

### ISSUE THREAD

**Issue by sheadovas** [Vector35/binaryninja-api#1321]
Binary Ninja Version: 1.1.1555 Personal, 1d59e7dc
Platform: macOS 10.14

This issue occurred during analysis binary *magic* from  [Flare-On 2018](http://flare-on.com/files/Flare-On5_Challenges.zip) challenges.

## Steps to reproduce

1. Download above sample and open it in Binja.
2. Seek into `0x403a1a`, click on variable.
3. Xrefs table is showing nothing

![1](https://user-images.githubusercontent.com/5824063/55877623-d2214e00-5b9a-11e9-92b9-c8c3b34d81f8.png)
 
4. Go to: `0x403a41`
5. The same variable is showing xrefs(!)...

![2](https://user-images.githubusercontent.com/5824063/55877898-8327e880-5b9b-11e9-8033-506b60603fd6.png)

6. (...) but to invalid location - see highlighted line - (at least I don't understand how this variable refers to this jump)

![3](https://user-images.githubusercontent.com/5824063/55877775-3b08c600-5b9b-11e9-9c18-a86ce99148ed.png)

## Expected behavior

xrefs table is showing __all__ xrefs to local variables inside function.

**Comment by bpotchik** [comment]
What you are seeing are code cross references to the instruction you have selected, even in the case where you select a data variable token on the instruction line. For now, data variable cross references are incomplete and on our list to add. Although incomplete, if you select a variable, other uses of it are highlighted and visible in the mini graph.

**Comment by plafosse** [comment]
What I think you're looking for is #234 I'm going to close this as a dupe.
