### ISSUE TITLE
Seg Fault Loading with Architecture Plugin

### ISSUE THREAD

**Issue by rmspeers** [Vector35/binaryninja-api#1324]
When I run an analysis using the Xtensa LE plugin (grabbed from https://github.com/allanlw/binja-xtensa), on the file (a sample is included in the attached ZIP: [esp32-example.zip](https://github.com/Vector35/binaryninja-api/files/3074780/esp32-example.zip)), the analysis makes good progress but when allowed to continue to run, at some point, reliably, it will seg fault and crash all of Binja.

Even if the processor has some issue, it shouldn't result in a full core crash.

```
...
Invalid hexstr
Invalid hexstr
Invalid hexstr
Invalid hexstr
Invalid hexstr
Invalid hexstr
Segmentation fault: 11
```

**Comment by D0ntPanic** [comment]
This crash was caused by the plugin emitting invalid IL. A warning is generated instead of crashing in build 1650.
