### ISSUE TITLE
HOME and END key don't work in Linear or Graph view

### ISSUE THREAD

**Issue by melomac** [Vector35/binaryninja-api#1325]
The HOME and END keys are not scrolling to respectively the top and the bottom of the Linear view.

At the time of this writing, it is also not possible to list available views for an offset, like bv.start or bv.end so, unfortunately, it isn't possible to implement reliably these keys in a plugin 😟

If this is a blocker for some users, I could totally settle for Ctrl + HOME or END, just like the Raw Hex view 🙏

**Comment by plafosse** [comment]
This is going to be done while we're adding multi-select and keyboard navigation to LinearView. #91

**Comment by plafosse** [comment]
Control home and control end do go to the beginning and end of linear view and graph view now.
