### ISSUE TITLE
Imported functions do not show up if they do not have a PLT entry

### ISSUE THREAD

**Issue by resrever** [Vector35/binaryninja-api#1331]
The "Functions" pane shows PLT entries, but not GOT entries.  On binaries that skip a PLT and directly call GOT entries (such as the MIPS binary I am currently looking at), the imported functions do not appear in the "Functions" pane.  This makes it difficult to quickly navigate the binary to find vulnerabilities.

**Comment by psifertex** [comment]
Is this true for the triage plugin as well? That's the basis for the code that we have a separate issue tracking integration of a symbols list into where the functions list is now that is already slated for 1.2.

**Comment by plafosse** [comment]
This is fixed in 1.1.1772
