### ISSUE TITLE
Broken x86 enter disassembly

### ISSUE THREAD

**Issue by 0x1F9F1** [Vector35/binaryninja-api#1333]
Binary Ninja Version: 1.1.1611-dev, a7cd9923
Platform: Manjaro Linux

The second operand of `enter` is printed as a char.

![image](https://user-images.githubusercontent.com/6098371/56565764-03414b80-65a9-11e9-8af8-40e6fb646120.png)

**Comment by KyleMiles** [comment]
Resolved in 1.1.1711-dev.
