### ISSUE TITLE
CLR application notification/support

### ISSUE THREAD

**Issue by gynophage** [Vector35/binaryninja-api#134]
Apps built against the .NET CLR mostly load (as they're valid PE's), but then obviously fail at being disassembled.

**Comment by psifertex** [comment]
Leaving this here: https://en.wikipedia.org/wiki/Portable_Executable#.NET.2C_metadata.2C_and_the_PE_format

**Comment by psifertex** [comment]
Unfortunately this is not a priority and we're closing this as won't fix.
