### ISSUE TITLE
notifyOffsetChanged ambiguous offset

### ISSUE THREAD

**Issue by sraboy** [Vector35/binaryninja-api#1345]
When my widget's `notifyOffsetChanged` function is called, all I get is an `offset`. If a user has more than one tab open, there's no way to tell which `BinaryView` that `offset` belongs to.

If the intent is for the widget to track the `BinaryView` itself, the `notifyViewChanged` function segfaults on `view_frame.getCurrentWidget().getData()` with an invalid pointer (or am I misusing that?).

**Comment by joshwatson** [comment]
```python
self.current_view_frame.actionContext().binaryView
```

**Comment by sraboy** [comment]
Thank you, that should work for me. I'll give it a try once I'm back at my desk.

I feel like `offset` on its own isn't enough though. If multiple views is a first-class feature, and can be implemented by third parties, there's no telling what that offset might refer to, or if the view has changed again before the plugin has gotten around to processing the event. Just my $0.02.

**Comment by bpotchik** [comment]
Yes the intent is to stash a reference to the BinaryView in your dock widget. You will want to use something like ```			view = view_frame.getCurrentViewInterface()
			self.data = view.getData()``` in your `notifyViewChanged` method. Make sure you don't combine the statements as the temporary object is necessary.

**Comment by bpotchik** [comment]
Here is the example plugin posted in slack.
`from binaryninja import log
from binaryninjaui import DockHandler, DockContextHandler, UIActionHandler
from PySide2 import QtCore
from PySide2.QtCore import Qt
from PySide2.QtWidgets import QApplication, QHBoxLayout, QVBoxLayout, QLabel, QWidget

instance_id = 0
class HelloDockWidget(QWidget, DockContextHandler):
	def __init__(self, parent, name):
		global instance_id
		QWidget.__init__(self, parent)
		DockContextHandler.__init__(self, self, name)
		self.actionHandler = UIActionHandler()
		self.actionHandler.setupActionHandler(self)
		offset_layout = QHBoxLayout()
		offset_layout.addWidget(QLabel("Offset: "))
		self.offset = QLabel(hex(0))
		offset_layout.addWidget(self.offset)
		offset_layout.setAlignment(QtCore.Qt.AlignCenter)
		datatype_layout = QHBoxLayout()
		datatype_layout.addWidget(QLabel("Data Type: "))
		self.datatype = QLabel("")
		datatype_layout.addWidget(self.datatype)
		datatype_layout.setAlignment(QtCore.Qt.AlignCenter)
		layout = QVBoxLayout()
		title = QLabel(name, self)
		title.setAlignment(QtCore.Qt.AlignCenter)
		instance = QLabel("Instance: " + str(instance_id), self)
		instance.setAlignment(QtCore.Qt.AlignCenter)
		layout.addStretch()
		layout.addWidget(title)
		layout.addWidget(instance)
		layout.addLayout(datatype_layout)
		layout.addLayout(offset_layout)
		layout.addStretch()
		self.setLayout(layout)
		instance_id += 1
		self.data = None

	def notifyOffsetChanged(self, offset):
		self.offset.setText(hex(offset))

	def shouldBeVisible(self, view_frame):
		if view_frame is None:
			return False
		else:
			return True

	def notifyViewChanged(self, view_frame):
		if view_frame is None:
			self.datatype.setText("None")
			self.data = None
		else:
			self.datatype.setText(view_frame.getCurrentDataType())
			view = view_frame.getCurrentViewInterface()
			self.data = view.getData()


	def contextMenuEvent(self, event):
		self.m_contextMenuManager.show(self.m_menu, self.actionHandler)

	@staticmethod
	def create_widget(name, parent, data = None):
		return HelloDockWidget(parent, name)

def addStaticDockWidget():
	mw = QApplication.allWidgets()[0].window()
	dock_handler = mw.findChild(DockHandler, '__DockHandler')
	dock_widget = HelloDockWidget.create_widget("HelloDockWidget (Static Dock)", dock_handler.parent())
	dock_handler.addDockWidget(dock_widget, Qt.BottomDockWidgetArea, Qt.Horizontal, True)

def addDynamicDockWidget():
	mw = QApplication.allWidgets()[0].window()
	dock_handler = mw.findChild(DockHandler, '__DockHandler')
	dock_handler.addDockWidget("HelloDockWidget (Dynamic Dock)", HelloDockWidget.create_widget, Qt.BottomDockWidgetArea, Qt.Horizontal, True)

addStaticDockWidget()
addDynamicDockWidget()
`

**Comment by sraboy** [comment]
Looking forward to this all going stable and digging through the docs. Appreciate the examples!
