### ISSUE TITLE
Error while saving database snapshot

### ISSUE THREAD

**Issue by bmuessig** [Vector35/binaryninja-api#1347]
When trying to save via `File > Save`, this error is displayed:

> Error while saving database snapshot: cannot rollback - no transaction is active

Trying to save the analysis database via `File > Save Analysis Database` yields this error:

> Error while saving database snapshot: cannot start a transaction within a transaction

Binary Ninja Version: 1.1.1555 Personal, 1d59e7dc
Platform: Windows 8.1 Pro (6.3)

**Comment by bmuessig** [comment]
I am not sure what additional info could be useful to you or how to dump the state of Binary Ninja so that you can analyze it.

**Comment by plafosse** [comment]
Can you provide some additional information. Was this trying to save an existing BNDB? Was this a raw binary? Could you possibility have been saving to some protected directory?

**Comment by psifertex** [comment]
Going to close this one out as we don't have enough information on it. If you have it happen again or can provide more information about it, please re-open it.
