### ISSUE TITLE
"Display As" floating point

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#1349]
There is no way to change the display type of the following to be its floating point representation:
![image](https://user-images.githubusercontent.com/5834130/57975715-8cb72400-7983-11e9-9c87-10eac76c1c34.png)

However, if I set the type of a `DataVariable` to `double`, it automatically changes the display in linear view (though it really should display at least a single digit of the decimal point side), so the functionality is there somewhere...
![image](https://user-images.githubusercontent.com/5834130/57975736-00593100-7984-11e9-8ea6-15cc807a5bfd.png)

**Comment by meme** [comment]
As a stop-gap, is it possible to achieve this functionality (i.e.: adding custom "Display As" members) with a plug-in?

**Comment by jeffli678** [comment]
fixed in dev 2306
