### ISSUE TITLE
DataVariable.code_refs does not match bv.get_code_refs(DataVariable.address)

### ISSUE THREAD

**Issue by irwincong** [Vector35/binaryninja-api#1354]
On BinaryNinja v1.1.1555 (latest stable as of this writing)
```python
>>> bv.get_code_refs(bv.get_data_var_at(0x80560e0).address)
[<ref: x86@0x8052ab5>, <ref: x86@0x8048f85>, <ref: x86@0x8048f8b>, <ref: x86@0x80529dd>, <ref: x86@0x8052a3d>, <ref: x86@0x8052a0d>, <ref: x86@0x8052959>, <ref: x86@0x805296f>, <ref: x86@0x8052975>, <ref: x86@0x805299f>, <ref: x86@0x8052a6d>]

>>> bv.get_data_var_at(0x80560e0).code_refs
[]
```

[fsck.tar.gz](https://github.com/Vector35/binaryninja-api/files/3214228/fsck.tar.gz)

**Comment by psifertex** [comment]
Ahh, I'm not sure which fix improved this, but this is actually fixed on the latest dev, that's why I was unable to repro it. Simple update to the latest dev branch in your preferences and this should no longer be an issue.
