### ISSUE TITLE
Renaming functions will not update displayed prototype text anymore

### ISSUE THREAD

**Issue by bmuessig** [Vector35/binaryninja-api#1356]
Binary Ninja Version: 1.1.1689 Personal, 856ac082
Platform: Ubuntu 18.04.2 LTS

When renaming functions / changing types in the disassembly graph, the prototype displayed at the top is not updated to the new type and name anymore. Switching to another view and returning to the previous one will update the information. This used to work fine in 1555 and even after restarting BN this problem persists. This is related to the closed issue #683.

**Comment by bpotchik** [comment]
Fixed in 1.1.1742-dev.
