### ISSUE TITLE
Run linear-sweep until completion

### ISSUE THREAD

**Issue by valour01** [Vector35/binaryninja-api#1359]
[test_bin.zip](https://github.com/Vector35/binaryninja-api/files/3255494/test_bin.zip)
This is the test case I provided. I noticed that much bytes are not disassembled by Binary Ninja. I am pretty sure, these bytes are not inline data but code. However, it seems that ninja would treat so many bytes as data and won't disassemble them.
![image](https://user-images.githubusercontent.com/5527468/58930268-358bbe80-878d-11e9-8627-9778ca9a67a0.png)

**Comment by plafosse** [comment]
This particular binary seems to be mixed arm and thumb, which is probably the trickiest of binaries we have to deal with. This is a binary that can benefit from manually re-running linear sweep, potentially 5 times, we plan on our updating our algorithm to eventually do this automatically, until no additional functions are found, for now though it is a manual process: 
![Screen Shot 2019-06-05 at 11 03 20 AM](https://user-images.githubusercontent.com/10556585/58969133-3587c080-8785-11e9-828d-db0805b6e46c.png)

**Comment by bpotchik** [comment]
Fixed in 1.1.1746-dev.
