### ISSUE TITLE
Downgrade "feature"

### ISSUE THREAD

**Issue by gynophage** [Vector35/binaryninja-api#136]
It might be nice to be able to downgrade versions of binary ninja.

A situation where an update breaks a vital plugin or munges the .bndb format, being able to roll back until the issue can be resolved would be nice.

**Comment by psifertex** [comment]
There is a plugin [in dev](/vector35/binaryninja-api/tree/dev/python/examples/version-switcher.py), leaving open until the UI supports it as well.

**Comment by bpotchik** [comment]
Fixed in build 1.1.1121-dev.
