### ISSUE TITLE
Imported functions marked as __noreturn 

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#1361]
This is an issue I've noticed with really old mac binaries that have imported functions done via an RWX jump table that is filled in with `jmp` instructions at load time. In the binary, the jmp table is filled with `hlt` instructions that are overwritten before use. Binja notices the `hlt`s and marks all the imported functions as `__noreturn`, causing the rest of the analysis to stop after any imported function. 

Sample binary to reproduce: https://download.panic.com/transmit/Transmit%203/Transmit%203.7.zip

**Comment by CouleeApps** [comment]
Hmm upon further note this might only be for Fat Mach-O files. Extracting the i386 slice and analyzing it directly seemed to work fine.

**Comment by bpotchik** [comment]
This would be a result of relocations being broken with the original FatMacho BinaryViewType. This issue is resolved with the new Universal BinaryViewType which landed a while back in `2.1.2295-dev`
