### ISSUE TITLE
inline editing for does-not-return instructions fails to populate with existing instruction

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#1363]
See attached photo. Any instruction that ends analysis (such as int3, hlt) is a bit awkward to update as the line being selected is the text "{ Does not return }" which doesn't contain any instructions. 

Also more obvious when multi-selecting a chunk of instructions, any "does not return" instructions will not show up in the edit box. 

![Screen Shot 2019-06-10 at 6 05 30 PM](https://user-images.githubusercontent.com/140215/59230083-5d728c00-8baa-11e9-8fd2-e124b147c057.png)
![Screen Shot 2019-06-10 at 5 59 18 PM](https://user-images.githubusercontent.com/140215/59230085-5d728c00-8baa-11e9-88d2-ae4c8671bc02.png)

**Comment by jeffli678** [comment]
fixed in dev 2.1.2474

**Comment by jeffli678** [comment]
also the indention is fixed
