### ISSUE TITLE
Inconsistency when clicking on function name in the header

### ISSUE THREAD

**Issue by bambu** [Vector35/binaryninja-api#1370]
It is not possible to rename / change types when going to a function, clicking on the header (without clicking anywhere in the disassembly) and hitting `N` or `Y`. However, clicking in any basic block in the disassembly and then clicking on the function name in the header works. Note: it also does not work when initially clicking outside of a basic block either

**Comment by bpotchik** [comment]
Fixed in 1.1.1742-dev.
