### ISSUE TITLE
Incorrect function return type leads to incorrect SSA variable assignment

### ISSUE THREAD

**Issue by quend** [Vector35/binaryninja-api#1372]
In this case free() returns a tuple forcing binja to assign r0_11 at this instruction even though its not assigned here.

![image](https://user-images.githubusercontent.com/1381003/59518165-1b3f9800-8e93-11e9-91e8-337539112572.png)

**Comment by plafosse** [comment]
This is likely a undecidable problem, because we don't currently have type libraries. But this will still show up in cases of calls to external functions which we can't analyze.  If fixing the prototype doesn't eliminate the incorrect return types, then this is a bug we need to deal with.
