### ISSUE TITLE
Linear View needs horizontal scrolling

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#1373]
Long lines are cut off in linear view (and in views that subclass the linear view). Needs to be able to horizontally scroll to see the rest of the line.
![image](https://user-images.githubusercontent.com/5834130/59529511-13352780-8e96-11e9-9b5b-669bd2c226ba.png)

**Comment by plafosse** [comment]
Our solution here isn't going to be horizontal scrolling, but rather fixing the places where we don't line wrap properly.

**Comment by plafosse** [comment]
This was actually added back in v01.02.01950
