### ISSUE TITLE
Can't handle symlink on windows when updating Binary Ninja

### ISSUE THREAD

**Issue by NyaMisty** [Vector35/binaryninja-api#1374]
Binary Ninja Version: 1.1.1731-dev, 796e57e1 (1.1.1541 before update)
Platform: Windows 10 (10.0)

I installed a plugin via symlink, and Binary Ninja told me "Can't remove (Binary Ninja installing dir)\(symlink name)\XXX" while updating.
Seems that it's doing a simple path concatenation without checking whether it's a symlink.

**Comment by joshwatson** [comment]
You’re using the wrong plugin directory

**Comment by NyaMisty** [comment]
Oh I got it, I should use the plugin folder under %APPDATA%.
Thanks! I'll close this issue now.

**Comment by psifertex** [comment]
Yup! Thanks Josh for clarifying. The list of directories for each platform is in: https://docs.binary.ninja/getting-started.html#directories
