### ISSUE TITLE
Please Track Exported Symbols

### ISSUE THREAD

**Issue by clubbingbabyseals** [Vector35/binaryninja-api#1377]
Binary Ninja Version: 1.1.1689, 856ac082
Platform: macOS Mojave (10.14)

Can you please track exported symbols and expose that information?

perhaps make it easier to access via an iterator (both imported and exported) functions

**Comment by joshwatson** [comment]
They’re in the triage view. You can iterate over them based on the SymbolType

**Comment by plafosse** [comment]
This is a duplicate of: #69
