### ISSUE TITLE
String truncation is inconsistent

### ISSUE THREAD

**Issue by gynophage** [Vector35/binaryninja-api#138]
Auto-commented string references are inconsistently commented.

![truncation](https://cloud.githubusercontent.com/assets/3688488/12924263/3900d00e-cf27-11e5-9715-1764dbe318c1.PNG)

There is an ellipsis there, despite the next character being a NULL. On shorter strings that are NULL terminated ("\n\nEASTER EGG\n\n"), there is no ellipsis.

![easteregg](https://cloud.githubusercontent.com/assets/3688488/12924370/aa242a10-cf27-11e5-9a1f-905ba9e01f45.PNG)

**Comment by plafosse** [comment]
Fixed in dev
