### ISSUE TITLE
Debugger UI and Interface

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#1384]

**Comment by lwerdna** [comment]
The debugger exists currently as a plugin at [https://github.com/vector35/debugger](https://github.com/vector35/debugger).

It supports x86 and x64 architectures on Windows, Linux, and MacOS, and arm and aarch64 architectures when connected to a remote gdb stub.

With the plugin installed, you have programmatic/API access to debuggers starting with `import debugger` and `state = debugger.get(bv)`. Please see the code and markdown files in the debugger repository.
