### ISSUE TITLE
annotations have wrong addresses associated

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#1386]
See offset `0x201068` in the attached bndb. If you double click the string reference, you'll be taken to `0`, and likewise if you click the string the xrefs will be incorrect, showing a number of locations where a null argument is passed to functions. 

![Screen Shot 2019-07-03 at 5 16 24 PM](https://user-images.githubusercontent.com/140215/60625954-43962480-9db7-11e9-9466-4fc5a45fa5aa.png)

[rand2.bndb.zip](https://github.com/Vector35/binaryninja-api/files/3356868/rand2.bndb.zip)

**Comment by jeffli678** [comment]
This is fixed before stable 2.2
