### ISSUE TITLE
plugin manager 2.0 additional enhancements

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#1389]
Now that we have the 2.0 plugin manager shipped on dev, wanted to track some additional ideas for improving it. This issue may be closed before some or all of these are implemented, this is just being used as a brainstorming list:

- [x] Show category for each plugin
- [x] Hide "Installation" tab if content is empty
- [x] Document or add UI elements for the custom tags you can use to search
- [ ] ~Include author's github profile photo~
- [x] highlight clickable links (user profile, github project page) with 🔗 or otherwise indicate they're clickable
- [x] license name doesn't show up as a hyperlink when it is clickable (doesn't really matter since it's not an external link)
- [ ] ~highlight plugins that are available for update or provide facility for periodic automatic-update of plugins~ (including showing release notes if they exist) (Removing this in favor of #2199 / #3177)
- [x] Search in the plugins list should prioritize plugin names when possible

**Comment by psifertex** [comment]
Documentation added to: https://docs.binary.ninja/guide/plugins.html#plugin-manager-searching

**Comment by OvertimeRSB** [comment]
Include buildscripts for different package managers on different platforms automatically if a needed dependency is missing.

**Comment by psifertex** [comment]
Most of these were done some time ago, but I finished up the prioritized search and added the category in builds >= 3610
