### ISSUE TITLE
Documentation/Tutorials

### ISSUE THREAD

**Issue by CryptXor** [Vector35/binaryninja-api#139]
Are there plans to write a document similar to that "Unofficial IDA Pro Book" for BinaryNinja?
I would be happy to do that or contribute to it!
:smile: :+1:

**Comment by psifertex** [comment]
We're definitely planning on releasing updated documentation in the app itself and the website. We'll wait until we have a much bigger user base before we worry about a book. :-)

**Comment by psifertex** [comment]
https://docs.binary.ninja/
https://api.binary.ninja/

Offline versions are also now included as well.
