### ISSUE TITLE
Change Version While Update Download in Progress

### ISSUE THREAD

**Issue by sraboy** [Vector35/binaryninja-api#1398]
It seems that if a download is in progress, no change to the channel or version is accepted and no error or warning is shown to the user. After restarting, the version installed and selected in prefs is the one from the update that was downloading. Tested on 1.1.1779-dev and 1.1.1689.

Context:

I have BInja set to auto-update so when I opened Binja 1.1.1155 it automatically checked for an update and started the download. I edited the prefs to switch to a dev build, but got an error dialog saying "A check for an update is already in progress". When I hit OK, both the error and preferences dialogs closed.

When I re-open the prefs, it showed the dev channel selected but not the version I chose. I set the version again (the original update was still downloading) and hit OK. I didn't get the error this time but when I re-opened the prefs, it still didn't change the version.

Once I restarted Binja, the update was installed and "Update channel" had reverted to release and the version reflected the stable one that was just installed.

I went through the process again on 1.1.1689 to switch to dev. I never saw the error but if I changed it back to another version while the download was going, it just silently ignores/fails.

All tested on macOS with the versions specified.

**Comment by bpotchik** [comment]
Fixed in 1.1.1786-dev.
