### ISSUE TITLE
C Compiler "IntelliSense"

### ISSUE THREAD

**Issue by CryptXor** [Vector35/binaryninja-api#140]
Might be worthwhile to add "convenience" functions to the C Compiler.
Perhaps load a simple template on startup?
When "{" is typed; automatically add "}"

Just things like that.

**Comment by psifertex** [comment]
This would be nice -- a related feature we've been thinking about is that it would be good if discovered symbols in the binary are usable in the C (and assembly for that matter) with associated completion capability.

That said, this is pretty low on the priority list for features.

**Comment by CryptXor** [comment]
That would be even better. Add a true intellisense then :+1:

**Comment by plafosse** [comment]
I also wanted to do this for the assembler too, its quite easy to get a list of valid mnemonics, registers and addressing modes.

**Comment by psifertex** [comment]
Depends on #31 as we plan to integrate monaco (https://microsoft.github.io/monaco-editor/)

**Comment by psifertex** [comment]
We're closing this entirely in favor of #31. When we implement that we'll get this for free and we have no plans to implement it independently of 31.
