### ISSUE TITLE
Segmentation fault in BNFreeSymbol () from libbinaryninjacore.so.1

### ISSUE THREAD

**Issue by ATorNinja** [Vector35/binaryninja-api#1400]
Binary Ninja Version: 1.1.1779-dev, 53787b86
Platform: Ubuntu 16.04.6 LTS
crash when pressing 'a' at 0x115a0(string)
[init.zip](https://github.com/Vector35/binaryninja-api/files/3405701/init.zip)

**Comment by plafosse** [comment]
Fixed in 1.1.1780
