### ISSUE TITLE
windows virtualenvs have getusersitepackages but it returns system path, not virtualenv

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#1401]
From fish on slack:

weird problem with Python virtualenv on Windows: it has `site.getusersitepackages()`, but calling `getusersitepackages()` will return the system-wide user site-packages directory, not the one used for virtualenv. this makes `install_api.py` ignore the current virtualenv.
a possible solution:
```
def runs_in_venv():
    import sys
    if hasattr(sys, "real_prefix") or (hasattr(sys, "base_prefix") and sys.base_prefix != sys.prefix):
        return True
    return False

if runs_in_venv(): #fall back to sysconfig.get_path()
```

**Comment by ltfish** [comment]
Here is a list of environments that I tested in:

- Windows 10, Python 3.7, virtualenv.
- Ubuntu 18.04, Python 3.7, virtualenv.

Ref: https://stackoverflow.com/questions/1871549/determine-if-python-is-running-inside-virtualenv the first post *and* related discussions gave a thorough solution to support all combinations of different versions of Python and virtualenvs.

**Comment by psifertex** [comment]
This was fixed (poorly) with an older commit then fixed with a [PR](https://github.com/Vector35/binaryninja-api/commit/1b5e7f7bb4876694aed7f21bb620db926f5f91aa) from a few weeks ago and we missed closing it previously.
