### ISSUE TITLE
Undo doesn't always trigger a linear view update.

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#1402]
Repo steps:

1. Go to the entry point `_start`
1. Right click `Undefine Current Function`
1. `Undo`

Behavior:
 The function is created but the linear view doesn't update

**Comment by lucasduffey** [comment]
Also when you define a function it will create variable references visible in linear view. When you undefine the function those references remain.

**Comment by plafosse** [comment]
This was fixed with the 2.0 fix
