### ISSUE TITLE
Can't create a reference to a Platform

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#1405]
Any situation in which you save a copy of a Platform object results in the following exception on exit during headless mode:
```
Exception ignored in: <function Platform.__del__ at 0x1115c49d8>
Traceback (most recent call last):
  File "/Applications/Binary Ninja.app/Contents/Resources/python/binaryninja/platform.py", line 117, in __del__
AttributeError: 'NoneType' object has no attribute 'BNFreePlatform'
```

Referencing a platform as `Platform['xxx']` every single time it's needed gets rid of this error. However, I feel like I should be able to do something like `plt = Platform['xxx']` and then do stuff with `plt` without it throwing that exception on exit.

**Comment by 3pidemix** [comment]
I'm getting the same error in headless just opening a bndb:

`bv = BinaryViewType.get_view_of_file(sys.argv[1])`

    Exception ignored in: <function Platform.__del__ at 0x10b45e680>
    Traceback (most recent call last):
      File "/Applications/Binary Ninja.app/Contents/Resources/python/binaryninja/platform.py", line 
    117, in __del__
    AttributeError: 'NoneType' object has no attribute 'BNFreePlatform'

Similar to the above, just happens when the script is exiting.

**Comment by plafosse** [comment]
This is simply an issue of the how python is cleaning things up at the end `core` goes out of scope before `del` is called. This only happens when the python is shutting down and thus its harmless. We've gotten around this issue by checking if `core is None` in all of our destructors.
