### ISSUE TITLE
COFF (.obj) support

### ISSUE THREAD

**Issue by stong** [Vector35/binaryninja-api#1410]
If we support Linux object files (.o) along with ELF, we should also support Windows object files (.obj) along with PE.

**Comment by ccarpenter04** [comment]
I would be thrilled to see this be supported.

**Comment by psifertex** [comment]
We're in the process of open sourcing our lifters. If you're interested in potentially filing a PR to add support (I haven't looked into how much work it is, but it might not be much), I can prioritize that process higher.

**Comment by ccarpenter04** [comment]
Yeah I would be interested in doing so in the near future, could you please send me the contributor agreement?

**Comment by psifertex** [comment]
It's the same one if you've ever pushed to this repo: You can see it here: https://gist.github.com/psifertex/a207c2e070f4e342554dc011e920b341

Once you submit a PR to the repo, the bot will ask you to sign it if you haven't already, but I think it even tracks if you've already signed it on a sister-repo and will remember it though I might be mis-remembering.

**Comment by galenbwill** [comment]
since `.lib` files are archives of `.obj` files, going to track them over on #2085

**Comment by galenbwill** [comment]
MVP complete -- still needs to parse symbol and debug information sections to get type signatures for functions, but that's a separate enhancement
