### ISSUE TITLE
copying text from the first line of a section treats the copy as a line copy instead

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#1418]
Selecting text from the first line of a section will fail to copy just the intended bytes and will instead copy lines of text. For example:

![first-line-copy](https://user-images.githubusercontent.com/140215/62252038-9a474c00-b3bf-11e9-9454-766a8eea7670.gif)

Produces:

```
__stub_helper (PURE_CODE) section ended  {0x1000045e8-0x1000048f0}

1000048f0                                                  24 46 72 65 65 42 53 44 3a 20 73 72 63 2f 62 69                  $FreeBSD: src/bi
```

**Comment by jeffli678** [comment]
I cannot reproduce this right now. It is fixed before stable 2.0.
