### ISSUE TITLE
TokenizedTextView not rendering correctly

### ISSUE THREAD

**Issue by D0ntPanic** [Vector35/binaryninja-api#1420]
The `linear_mlil.py` example no longer renders correctly after the tags feature was added:

![Screen Shot 2019-08-06 at 6 23 16 PM](https://user-images.githubusercontent.com/7007406/62581486-61075400-b877-11e9-9108-ab03360b9acd.png)

It appears to be related to the new `width` field on tokens not being handled properly when using tokens from Python.

**Comment by plafosse** [comment]
Fixed in 1.1.1832
