### ISSUE TITLE
"Display As" for data variables in Linear Disassembly

### ISSUE THREAD

**Issue by meme** [Vector35/binaryninja-api#1428]
In structures defined in the "Linear Disassembly" view, there is no option to change the display type of defined values. It would make sense to enable the same "Display As" available in the graph view for structure fields. 

https://github.com/Vector35/binaryninja-api/issues/1349#issuecomment-520244474

**Comment by plafosse** [comment]
Currently the actual metadata that is required to keep track of an integer's display type state is attached to the function object itself. We need to add the ability to track this bit of metadata on data variables in linear view.

**Comment by bmuessig** [comment]
I support that feature request, as I use BN a lot for RE-ing file formats and being able to e.g. quickly view signed numbers in decimal would help a lot. It would also help if individual variables could be displayed as little or big endian individually.

**Comment by jeffli678** [comment]
pushed to dev in 2.1.2403
