### ISSUE TITLE
Context menu for many selected bytes in "Linear Disassembly" view

### ISSUE THREAD

**Issue by meme** [Vector35/binaryninja-api#1429]
In the "Hex Editor" view, it is possible to select many bytes then right-click for a context menu for options on said bytes. In the "Linear Disassembly" view, you may select many bytes but a right-click acts as a left-click and deselects all the bytes (single bytes have a context menu). It should instead open a context menu to allow for operations on the selected bytes, such as "Copy As", etc. (i.e.: same functionality as the "Hex Editor" view)

**Comment by plafosse** [comment]
Fixed in 1.1.1843

**Comment by meme** [comment]
Thank you, works great. Is there a reason "Copy As" and friends are not available in the menu?

**Comment by plafosse** [comment]
No its just something we didn't add to that view yet. Its something we should create an issue for.

**Comment by jeffli678** [comment]
Also several items should be hidden in the multiple-bytes context menu. They just work for a single byte and its confusing what it actually does when activated on a range of bytes.
