### ISSUE TITLE
Progress text of BackgroundTaskThreads that raise exception persists

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#1431]
If a BackgroundTaskThread raises an exception, the progress text in the status bar sticks around. Additionally, it does not look like any other BackgroundTaskThread can change the progress text afterwards.

**Comment by plafosse** [comment]
Do you have an example of this?

**Comment by joshwatson** [comment]
```
class MyBackgroundTask(BackgroundTaskThread):
    def run(self):
        for i in range(10, 0, -1):
            self.progress = f"{i}..."
            raise Exception("Test")
```

You'll see that the progress text sticks around. If you try a different background task after this, the progress text will not change.
