### ISSUE TITLE
Add tooltip to tags

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#1432]
When a line has multiple tags, you can't visually identify which tags are on that line:
![image](https://user-images.githubusercontent.com/5834130/63030244-dde19180-be66-11e9-9e7e-55c4c061b483.png)
It would be nice if the use could mouse over it, or double click it or something, to display all of the tag icons associated with a given line.

**Comment by psifertex** [comment]
We're allowed to upvote things, right? 'cause I totally am on this one. 😛

**Comment by psifertex** [comment]
This is implemented as of 1.2.1992. Also shows the data field from tags.
