### ISSUE TITLE
Incorrect jump table values

### ISSUE THREAD

**Issue by rakuy0** [Vector35/binaryninja-api#1434]
Example binary: vdir from coreutils, compiled with llvm 9.0 at optimization level O1 and debug enabled:
[vdir.zip](https://github.com/Vector35/binaryninja-api/files/3521239/vdir.zip)

![image](https://user-images.githubusercontent.com/45212823/63360854-1a1c6280-c33d-11e9-853d-bcf7b0891996.png)

![image](https://user-images.githubusercontent.com/45212823/63358439-07a02a00-c339-11e9-9843-5282394461db.png)
`jump_table_8059b78`, referenced by function parse_ls_color (the reference is at virtual address 0x804b00a), should have a total of 6 cases that it references (as noted from both the cmp at virtual address 0x804b001 as well as the outer switch case here: https://github.com/coreutils/coreutils/blob/master/src/ls.c#L2542). Right now both the above picture and the function graph only reference 4 total cases. It looks like the unparsed data at virtual address 0x8059b84, as well as `jump_table_8059b88`, should all be merged into one jump table to rule them all at `jump_table_8059b78`?

For three virtual addresses that should be referenced by `jump_table_8059b78` but aren't, 0x0804b210 gets recognized as the default case (despite not being referenced in the jump table?), 0x804b17c gets sectioned off into its own function that nobody has xrefs to, and 0x804b043 doesn't seem to be recognized as code at all.

**Comment by bpotchik** [comment]
Thanks. I have a fix for this and will push an update shortly.
![Screen Shot 2019-08-20 at 5 00 20 PM](https://user-images.githubusercontent.com/29309548/63384081-2370f380-c36c-11e9-9180-3ce8d642fad0.png)

**Comment by bpotchik** [comment]
Fixed in 1.1.1846-dev.
