### ISSUE TITLE
Unnamed Functions can't be found by bv.get_symbols_at

### ISSUE THREAD

**Issue by KyleMiles** [Vector35/binaryninja-api#1436]
Test case: current_function.symbol == bv.get_symbol_at(current_function.start) should be true, for functions that we assign names (sub_x), it is false.

![image](https://user-images.githubusercontent.com/7171118/63470357-731df080-c43a-11e9-9b91-cb3a26ddb11a.png)

bv.get_symbols_by_name also returns an empty list, and bv.get_symbol_by_raw_name returns none.

**Comment by plafosse** [comment]
This isn't a bug, its actually an intended feature. Though I agree it can be confusing. BinaryNinja doesn't create symbol objects for every Function and DataVariable object, and rather creates an ephemeral symbol whenever it is requested.
