### ISSUE TITLE
UI elements that subclass BinaryDataNotification don't expose those methods to Python

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#1443]
UI elements such as `LinearView` and `HexEditor` subclass `BinaryDataNotification` in order to update whenever the user performs most actions; however, if one of these classes are instantiated from Python, their notifications cannot be registered with a `BinaryView` because their `BinaryDataNotification` methods are not exposed in the Python. This prevents these views from being capable of automatically refresh as expected.

**Comment by plafosse** [comment]
In python you can create a helper class that registers a notification, as in pyside it's not really possible to subclass this.
