### ISSUE TITLE
Auto symbols overriding user symbols under certain conditions

### ISSUE THREAD

**Issue by PistonMiner** [Vector35/binaryninja-api#1445]
Under certain conditions, auto symbols will supercede user symbols, and not the other way around. This seems to be related to using namespaces.

E.g.:
```>>> bv.define_user_symbol(Symbol(SymbolType.ExternalSymbol, 0x81234567, "EXT_user_symbol", namespace = "namespace_user"))
>>> bv.get_symbol_at(0x81234567)
<SymbolType.ExternalSymbol: "EXT_user_symbol" @ 0x81234567>
>>> bv.get_symbol_at(0x81234567).auto
False
>>> bv.define_auto_symbol(Symbol(SymbolType.ExternalSymbol, 0x81234567, "EXT_auto_symbol"))
>>> bv.get_symbol_at(0x81234567).auto
True
>>> bv.get_symbol_at(0x81234567)
<SymbolType.ExternalSymbol: "EXT_auto_symbol" @ 0x81234567>
>>> bv.undefine_auto_symbol(bv.get_symbol_at(0x81234567))
>>> bv.get_symbol_at(0x81234567)
<SymbolType.ExternalSymbol: "EXT_user_symbol" @ 0x81234567>
>>> bv.get_symbol_at(0x81234567).auto
False
```

**Comment by plafosse** [comment]
One question why are you trying to define an ExternalSymbol? There are very limited uses for users doing this.

**Comment by plafosse** [comment]
This issue will be fixed in v1.1.1893

**Comment by PistonMiner** [comment]
Awesome, thanks!

This is running on a custom BinaryView; the platform I'm working with has custom "relocatable modules" that link either with a main module that is always loaded at fixed addresses or other relocatable modules.
Right now I'm resolving these relocations during BinaryView load and then patch the data with the resolved relocations (which then point outside the BinaryView to the right addresses or placeholder addresses if it's a relocation against another relocatable module) and then tagging the referenced external symbols with ExternalSymbol.

**Comment by plafosse** [comment]
Ok cool, sounds like you're using the External Symbols correctly :)
