### ISSUE TITLE
GOT problems (?) with certain ppc32 dialects

### ISSUE THREAD

**Issue by eShuttleworth** [Vector35/binaryninja-api#1446]
Analyzing some linux-ppc32 ELFs yields a large number of errors of the form 
`Call target 0x10011e54 does not appear to be code in instruction at 0x1000114c`

Looking closer, it appears to be related to binary ninja not recognizing the uninstantiated GOT?

[example](https://github.com/Vector35/binaryninja-api/files/3618434/cksum.gz)

**Comment by psifertex** [comment]
What version of BN are you running on? I can't reproduce this on a recent dev, 1881.
