### ISSUE TITLE
Implement write-lock to prevent accidental binary modifications during UI usage

### ISSUE THREAD

**Issue by johnwatsonoklahoma** [Vector35/binaryninja-api#1449]
Sometimes pressing keys (like 'g' for 'Go to') doesn't do the supposed action (when cursor is in specific UI location like right pane with ascii symbols in Hex view) and instead a piece of binary is rewritten with key value. I would like a write-lock to be present to prevent that kind of issues.

**Comment by bpotchik** [comment]
Similar to #2107 

An initial version of this is available in `2.2.2627-dev`. It is called 'Write Traction' and the goal is to prevent accidental modifications to a binary via cut/paste actions in views, and accidental modification in hexview. There is a corresponding action in the command palette which allows one to toggle the lock as well as an interactive lock glyph in the lower right status bar.

**Comment by bpotchik** [comment]
Latest version of this feature is in `2.2.2629-dev`. It's now called 'File Contents Write Lock'.
