### ISSUE TITLE
Bug report: Crash when the RAM is insufficient

### ISSUE THREAD

**Issue by jeffli678** [Vector35/binaryninja-api#1450]
I have an XPS 9570 with 16GB RAM and i7-8750H (6 cores, 12 thread). The Binary Ninja is configured with 11 parallel analysis threads. I find the BN crashes when analyzing big binaries, e.g., those ~50MB ones from iOS. I monitored the memory usage and find the RAM is insufficient for BN. I tested with the same version of BN and the same binary on a PC with 32GB memory, and it worked. It seems ~20GB RAM should be fine. 

I understand the amount of RAM is the root cause. However, 16GB is not too bad, right? I think BN should, at least, not crash. Maybe it can defer certain analysis or stop several analysis threads to allow other ones to work well. Crashing is time-wasting and sometimes I lose my progress. 

Nevertheless, is there any configurations I can tweak to avoid the crash? Maybe limiting the number of parallel analysis threads? Or limiting the max memory usage?

**Comment by psifertex** [comment]
The most important option for tuning memory usage is `analysis.limits.cacheSize`. MediumLevelIL is the most expensive analysis to cache so tuning that to a smaller number can help with overall memory usage. 

Related, you can turn on "basic" or "control-flow only" analysis modes which do a faster/lighter analysis that you can then specify individual functions you want analyzed in-depth afterward. Use the "open with options" menu and select "analysis.mode".

Another option is to enable an OS memory cache file. 

Unfortunately, validating all allocations isn't actually possible so those are the best options above.
