### ISSUE TITLE
Conflicting license messages in Log and About page

### ISSUE THREAD

**Issue by lurkermike** [Vector35/binaryninja-api#1459]
Binary Ninja Version: 1.2.1913-dev, 36a4cab6
Platform: Windows 10 (10.0)

When I initially installed Binary Ninja, I used a license that soon after expired.  I renewed my license, but Binary Ninja still shows that the support expired in the log when the application starts, however, on the "About" page, the support information is correct.

I looked for a way to reset my license but couldn't find anything, so I figured I'd raise a bug.

![bn](https://user-images.githubusercontent.com/292972/66188558-6517de00-e63c-11e9-87b3-50aad3f648fd.png)

**Comment by bpotchik** [comment]
This has been fixed in 1.2.1915-dev.
