### ISSUE TITLE
Improve CPU utilization by improving internal function batching

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#1469]
Currently our core analysis doesn't always make full use of all available cores. This is due to a design decision that may be able to be improved upon. Currently functions get batched for analysis as such all the functions in that batch must complete analysis prior to starting the next batch. This means batch processing time is gated on the longest running function for analysis. 

If you're attempting to maximize cpu utilization for batch processing we recommend setting the max worker thread count to something small (5 or so) and then use a tool such as gnu parallel, to simultaneously analyze many binaries at once.

The current batch size is 1024, so your binary has to be fairly large (or you machine has to have a *lot* of cores) to be hit by this edge case.

**Comment by D0ntPanic** [comment]
Analysis batch size is no longer limited as of early June 2020
