### ISSUE TITLE
some PDB lookups fail

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#1472]
On a recent win10 x64, open `c:\windows\system32\mfc100u.dll` then use the `Tools`/`PDB`/`Load` menu and notice the URL: 

Attempting to download PDB from https://msdl.microsoft.com/download/symbols//mfc100u.amd64.pdb/17D43C3863AC4000BA5CD2DF937C16A81/mfc100u.amd64.pdb 

The correct URL has a an extra `7` on the end of the hash, so there's an off-by-one in at least some PDB files.

**Comment by plafosse** [comment]
Fixed in 1.2.1936
