### ISSUE TITLE
BN_DISABLE_USER_PLUGINS Does not disable user plugins

### ISSUE THREAD

**Issue by mothran** [Vector35/binaryninja-api#1475]
When setting the BN_DISABLE_USER_PLUGINS environment variable on my system (arch linux) I still see my user plugins being loaded from ~/.binaryninja/plugins/.

Example:

I have a plugin called "binja-types" installed at: ~/.binaryninja/plugins/binja-types

Then I run:
`BN_DISABLE_USER_PLUGINS=1 binaryninja`

And in the log window I still see:

`Loaded python3 plugin 'binja-types'`

This happens both with the UI and headless.

**Comment by psifertex** [comment]
Fixed in builds >= 1991.
