### ISSUE TITLE
Function types from typelibrary don't populate ImportedFunctionSymbol on Linux platforms

### ISSUE THREAD

**Issue by mothran** [Vector35/binaryninja-api#1479]
If a typelibrary is registered with a platform at plugin init, those types will be propagated to the ExternalSymbol and ImportAddressSymbol symbol functions but not the ImportedFunctionSymbol functions (In a Linux ELF file).  This means that if the binary calls the PLT stub the type definitions will not correctly be populated in the MLIL.

Example code to replicate the issue:
https://github.com/mothran/binja-typelibs/

Using the following binary:
[libfb.so.gz](https://github.com/Vector35/binaryninja-api/files/3748401/libfb.so.gz)

Install the plugin and then open the above binary, navigating to "memset" will show the incorrect types but "memset@GOT" will have a populated function type.

I had to implement a fixup in the plugin here to work around the issue:
https://github.com/mothran/binja-typelibs/commit/38bc3490f544b32778582014fce0e225e39911b1

BinaryNinja version: 1.2.1928-dev

**Comment by plafosse** [comment]
This was fixed in build number 2183
