### ISSUE TITLE
Smart go-to-address

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#148]
We can greatly enhance our current go-to-address feature.

- [x] Full expression parsing "base_address + 10 \* elementSize"
- [x]  Symbol auto-complete
- [x] Preview - Show what they will navigate to as soon as the complete the address
- [ ] Show if its in a data section or code section

**Comment by shane-runsafe** [comment]
Bumping to request the ability to specify section names as well.

**Comment by plafosse** [comment]
Yeah really this should be a feature of the Expression Parser.

**Comment by plafosse** [comment]
FYI Section names can be specified in the Expression Parser now

**Comment by psifertex** [comment]
Considering this one closed as of Fixed in v1.1.1590. Instead of showing the section in the preview, we allow you specify the section in the address
