### ISSUE TITLE
Rename instances of `macos` to `darwin`

### ISSUE THREAD

**Issue by Maximus-** [Vector35/binaryninja-api#1480]
Rename instances of macos to darwin inside of Binary Ninja. This will make it more clear for future feature support for iOS kernel / dyld cache / other XNU related platforms that arent explicitly macos. :)

**Comment by joshwatson** [comment]
Those platforms are specifically macOS. Other platforms will be added when they’re explicitly supported

**Comment by plafosse** [comment]
When we add specific support for iOS/iPadOS, we will add then as additional platforms.
