### ISSUE TITLE
Nested lists in bv.symbols dictionary 

### ISSUE THREAD

**Issue by janfrancu** [Vector35/binaryninja-api#1482]
Given a binary with more than 2 symbols with the same name but different namespace, `bv.symbols` contains nested lists. 
Example: 
```python
[[<SymbolType.ImportAddressSymbol: "C_GetSlotList@IAT" @ 0x46a868>, <SymbolType.ImportAddressSymbol: "C_GetSlotList@IAT" @ 0x46a878>], <SymbolType.ImportAddressSymbol: "C_GetSlotList@IAT" @ 0x46a888>]
```
in `ed69be0aff27e961789f1879e32c9a2c7bb7c124b4a7f0b4f967365a4a5b0e7c`, which can be found on VirusTotal.

This is most likely related to previously fixed [issue](https://github.com/Vector35/binaryninja-api/issues/1185) in this [commit](https://github.com/Vector35/binaryninja-api/commit/515381255191f35845e8c57059842741fcc652cd). 

One check at [binaryview.py#L1529](https://github.com/Vector35/binaryninja-api/blob/dev/python/binaryview.py#L1529) for `isinstance` or something along these lines solves the issue.
```python
if sym.raw_name in result:
    _sym = result[sym.raw_name]
    if isinstance(_sym, list):
    	_sym.append(sym)
        result[sym.raw_name] = _sym
    else:
        result[sym.raw_name] = [_sym, sym]
else:
    result[sym.raw_name] = sym
```

**Comment by bpotchik** [comment]
Duplicate symbol support now exists.

Fixed in 2.3.2731-dev.
