### ISSUE TITLE
Thumb2 Function Pointer Creation

### ISSUE THREAD

**Issue by 3pidemix** [Vector35/binaryninja-api#1489]
Working in a Thumb2 database, function pointers don't easily resolve to their respective functions with the `p` key. The only workaround I have found is to set the data to a generic function pointer type and mask out the Thumb2 bit via patching, which isn't ideal.

![1_start](https://user-images.githubusercontent.com/45530187/69482028-4fc16380-0de4-11ea-9942-b41d76a0459c.png)
**Starting data - bytes are within code section**

![2_fptr](https://user-images.githubusercontent.com/45530187/69482029-52bc5400-0de4-11ea-80cf-b2fcac8fe69d.png)
**After applying generic function pointer type to data**

![3_patched](https://user-images.githubusercontent.com/45530187/69482030-551eae00-0de4-11ea-9767-12bbc2bb8227.png)
**After patching data to mask Thumb2 bit**

**Comment by negasora** [comment]
I can't repro this on latest dev, can you share the binary?

**Comment by negasora** [comment]
Fixed in 1.2.1984-dev
