### ISSUE TITLE
C Compiler Inline ASM

### ISSUE THREAD

**Issue by CryptXor** [Vector35/binaryninja-api#149]
Does the C Compiler support inline ASM? I have tried using the `asm()` directive (unix gcc) and binja crashes as a result :/

**Comment by plafosse** [comment]
We don't have plans to support inline assembly in scc. But it shouldn't crash. Marking this as a bug.

**Comment by plafosse** [comment]
We're not going to support this. Its a bit too much work for very little benefit, eventually we may support linking with external asm files.
