### ISSUE TITLE
Invalid Xrefs and Annotations

### ISSUE THREAD

**Issue by 3pidemix** [Vector35/binaryninja-api#1493]
I'm seeing an odd issue with ARM Thumb2 binaries. Constant values that happen to match an address in a code section seem to be treated as addresses regardless of their usage. This causes xrefs to show up on all addresses where that constant is used. This function exhibits the behavior (constant pool for the function follows):

![start](https://user-images.githubusercontent.com/45530187/70017363-e6aebe00-1550-11ea-8381-19b746f7466b.png)

    000001ec  int32_t data_1ec = 0x80000
    000001f0  int32_t data_1f0 = 0x20008000
    000001f4  int32_t data_1f4 = 0x0
    000001f8  int32_t data_1f8 = 0x959
    000001fc  int32_t data_1fc = 0x20000c00
    00000200  int32_t data_200 = 0x20000f0c
    00000204  int32_t data_204 = 0x1cfd

As you can see at 0x1ae, the value 0 (the symbol **__isr_vector** also refers to address 0) is moved into r1, and the subsequent mov instructions get annotations for this symbol, which happens anywhere that the constant 0 is propagated in the binary.

Another oddity within this function is that the call target of the false block from the first comparison appears to resolve to **__isr_vector**, while the value reported for r3 is undetermined:

![undetermined](https://user-images.githubusercontent.com/45530187/70017844-422d7b80-1552-11ea-85fb-3e346c9e7192.png)

![start_mlil](https://user-images.githubusercontent.com/45530187/70018360-dd732080-1553-11ea-8d13-75e3852e8386.png)

The MLIL appears to be correct except for the **__isr_vector** call. At any rate, the most troubling thing for me is the invalid xrefs. I can supply some binaries if needed.

**Version 1.2.1966-dev (Build ID 26ce81fc)**

**Comment by plafosse** [comment]
This is us trying to detect which things are pointers. HLIL won't show this at all at this point. If you rebase to something not zero it will not show up.
