### ISSUE TITLE
shipping type libraries

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#1495]
List of type libraries currently included versus those that are planned: 

First Wave: 
- [x] ws2_32.dll (32-bit)
- [x] kernel32.dll (partial) (32-bit)
- [x] libc.so.6 (linux x86_64)
- [x] libgcc_s.so.1 (linux x86_64)
- [x] libm.so.6 (linux x86_64)
- [x] libpthread.so.0 (linux x86_64)

Linux type libraries
- [x] ld (linux aarch64/armv7/armv7eb/i386/mips/mipsel/ppc32/thumb2/thumb2eb/x86_64)
- [x] libc (linux aarch64/armv7/armv7eb/i386/mips/mipsel/ppc32/thumb2/thumb2eb/x86_64)
- [ ] libdl (linux aarch64/arm/i386/mipsel/x86_64)
- [x] libgcc_s (linux aarch64/armv7/i386/mips/mipsel/x86_64)
- [x] libm (linux aarch64/armv7/armv7eb/i386/mips/mipsel/ppc32/thumb2/thumb2eb/x86_64)
- [x] libmemusage (linux x86_64)
- [ ] libmvec (linux x86_64)
- [x] libpthread (linux aarch64/armv7/armv7eb/i386/mips/mipsel/ppc32/thumb2/thumb2eb/x86_64)
- [x] librt (linux aarch64/arm/i386/mipsel/x86_64)
- [x] libstdc++ (linux aarch64/armv7/i386/mipsel/x86_64)
- [ ] libutil (linux aarch64/arm/i386/mipsel/x86_64)

Windows Wave (x86/amd64)
- [x] activeds.dll
- [x] advapi32.dll
- [x] comctl32.dll
- [x] crypt32.dll
- [x] dsprop.dll
- [x] gdi32.dll
- [x] GdiPlus.dll
- [x] imm32.dll
- [x] kernel32.dll
- [x] KernelBase.dll
- [x] msacm32.dll
- [x] msvcrt.dll
- [x] netapi32.dll
- [x] ntdll.dll
- [x] ntdsapi.dll
- [x] ole32.dll
- [x] oleaut32.dll
- [x] psapi.dll
- [x] secur32.dll
- [x] shell32.dll
- [x] shlwapi.dll 
- [x] user32.dll
- [x] usp10.dll
- [x] version.dll
- [x] wininet.dll
- [x] winmm.dll
- [x] wintrust.dll
- [x] ws2_32.dll
- [x] wtsapi32.dll

**Comment by psifertex** [comment]
Unfortunately we discovered a bug that means we'll have to hold off on the next batch of libraries until shortly after 1.3 ships. Will still be coming shortly.

**Comment by tekwizz123** [comment]
Quick question, but any reason some of these will only have partial support?

**Comment by rssor** [comment]
It boiled down mostly to when we’d have the tooling in place to make it easier to work with some of the platform specific types on the generation side of things, but until then at least shipping all the stuff that can still be done in the mean time.

Long term is for them to all be fully supported, the things that are listed as partial right now are temporary measures.

**Comment by lwerdna** [comment]
updating the linux list by inspecting <Application>/Contents/Resources/typelib/ install directory on macos:

[x] ld (linux aarch64/armv7/armv7eb/i386/mips/mipsel/ppc32/thumb2/thumb2eb/x86_64):

```
typelib/aarch64/ld-linux-aarch64.so.1.bntl
typelib/armv7/ld-linuxv7.so.3.bntl
typelib/armv7/ld-linuxv7eb.so.3.bntl
typelib/mips/ld.so.1.bntl
typelib/mips/ldel.so.1.bntl
typelib/ppc/ld32.so.1.bntl
typelib/thumb2/ld-linux.so.3.bntl
typelib/thumb2/ld-linuxeb.so.3.bntl
typelib/x86/ld-linux.so.2.bntl
typelib/x86_64/ld-linux-x86-64.so.2.bntl
typelib/x86_64/ld-linux-x86-64.so.2_linux-x86_64.bntl
```

[x] libc (linux aarch64/armv7/armv7eb/i386/mips/mipsel/ppc32/thumb2/thumb2eb/x86_64):

```
typelib/aarch64/libc.so.6.bntl
typelib/armv7/libcv7.so.6.bntl
typelib/armv7/libcv7eb.so.6.bntl
typelib/mips/libc.so.6.bntl
typelib/mips/libcel.so.6.bntl
typelib/ppc/libc32.so.6.bntl
typelib/thumb2/libc.so.6.bntl
typelib/thumb2/libceb.so.6.bntl
typelib/x86/libc.so.6.bntl
typelib/x86_64/libc.so.6.bntl
```

[ ] libdl (linux aarch64/arm/i386/mipsel/x86_64) - MISSING X86_64:

```
typelib/aarch64/libdl.so.2.bntl
typelib/armv7/libdl.so.2.bntl
typelib/mips/libdlel.so.2.bntl
typelib/x86/libdl.so.2.bntl
```

[x] libgcc_s (linux aarch64/armv7/i386/mips/mipsel/x86_64):

```
typelib/aarch64/libgcc_s.so.1.bntl
typelib/armv7/libgcc_sv7.so.1.bntl
typelib/mips/libgcc_s.so.1.bntl
typelib/mips/libgcc_sel.so.1.bntl
typelib/x86/libgcc_s.so.1.bntl
typelib/x86_64/libgcc_s.so.1.bntl
typelib/x86_64/libgcc_s.so.1_linux-x86_64.bntl
```

[x] libm (linux aarch64/armv7/armv7eb/i386/mips/mipsel/ppc32/thumb2/thumb2eb/x86_64):

```
typelib/aarch64/libm.so.6.bntl
typelib/armv7/libmv7.so.6.bntl
typelib/armv7/libmv7eb.so.6.bntl
typelib/mips/libm.so.6.bntl
typelib/mips/libmel.so.6.bntl
typelib/ppc/libm32.so.6.bntl
typelib/thumb2/libm.so.6.bntl
typelib/thumb2/libmeb.so.6.bntl
typelib/x86/libm.so.6.bntl
typelib/x86_64/libm.so.6.bntl
typelib/x86_64/libm.so.6_linux-x86_64.bntl
```

[x] libmemusage (linux x86_64):

```
typelib/x86_64/libmemusage.so.bntl
```

[ ] libmvec (linux x86_64) - MISSING

[x] libpthread (linux aarch64/armv7/armv7eb/i386/mips/mipsel/ppc32/thumb2/thumb2eb/x86_64)

```
typelib/aarch64/libpthread.so.0.bntl
typelib/armv7/libpthreadv7.so.0.bntl
typelib/armv7/libpthreadv7eb.so.0.bntl
typelib/mips/libpthread.so.0.bntl
typelib/mips/libpthreadel.so.0.bntl
typelib/ppc/libpthread32.so.0.bntl
typelib/thumb2/libpthread.so.0.bntl
typelib/thumb2/libpthreadeb.so.0.bntl
typelib/x86/libpthread.so.0.bntl
typelib/x86_64/libpthread.so.0.bntl
typelib/x86_64/libpthread.so.0_linux-x86_64.bntl
```

[x] librt (linux aarch64/arm/i386/mipsel/x86_64):

```
typelib/aarch64/librt.so.1.bntl
typelib/armv7/librt.so.1.bntl
typelib/mips/librtel.so.1.bntl
typelib/x86/librt.so.1.bntl
typelib/x86_64/librt.so.1.bntl
```

[x] libstdc++ (linux aarch64/armv7/i386/mipsel/x86_64)

```
typelib/aarch64/libstdc++.so.6.bntl
typelib/armv7/libstdc++v7.so.6.bntl
typelib/mips/libstdc++el.so.6.bntl
typelib/x86/libstdc++.so.6.bntl
typelib/x86_64/libstdc++.so.6.bntl
```

[ ] libutil (linux aarch64/arm/i386/mipsel/x86_64) - MISSING X86_64:

```
typelib/aarch64/libutil.so.1.bntl
typelib/armv7/libutil.so.1.bntl
typelib/mips/libutilel.so.1.bntl
typelib/x86/libutil.so.1.bntl
```
