### ISSUE TITLE
Crash on launch due to Python Openssl

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#1497]

**Comment by psifertex** [comment]
We believe we have a fix landed on latest stable.

Users experiencing this issue should try the following:

temporarily replace your settings.json in `%APPDATA%\Binary Ninja\` with the following:
```
{
    "downloadClient" :
    {
        "providerName" : "QtDownloadProvider"
    },
    "python" :
    {
        "interpreter" : "INVALID"
    }
}
```
Next, launch Binary Ninja and update to any development build greater than 1978.

**Comment by psifertex** [comment]
Closing this issue as resolved as we haven't had any other issues since build 1978.
