### ISSUE TITLE
Demo doesn't run on Windows 7

### ISSUE THREAD

**Issue by soutzis** [Vector35/binaryninja-api#1499]
I have installed the demo on my VM (VirtualBox):
-Microsoft Windows 7 Enterprise (32-bit)
-Version 6.1.7601 Service Pack 1 Build 7601
-Installed on default location (tried installing for everyone and just for me)

When I try to run BinaryNinja I get the error:
*The Version of this file is not combatible with the version of Windows you're running. [...]*

Am I doing something wrong?

**Comment by psifertex** [comment]
Binary Ninja is 64bit only. Windows 7 is not supported officially either though if you are running a 64bit build with the latest updates I believe it does run the last time we checked.  More information on supported platforms is available at:

http://faq.binary.ninja/en/what-platforms-does-binary-ninja-run-on-66GRPbTBKdZuCqjqc

**Comment by soutzis** [comment]
I assumed it did, because at the [demo download page](https://binary.ninja/demo/), under limitations of demo version it clearly states:

Only works with **x86**, x86_64, and ARMv7

**Comment by psifertex** [comment]
Those are the architectures the demo analyzes, not runs on. We can clarify that language though, thanks for pointing that out.

**Comment by soutzis** [comment]
Oh, I see now. Thanks for your quick replies!
