### ISSUE TITLE
Support for more x86 extensions

### ISSUE THREAD

**Issue by wontonSlim** [Vector35/binaryninja-api#150]
Many x86 instructions cause the disassembly engine to break.
I did a diff of the instruction table in arch_x86.dll and the one in nasm 2.11
I cleaned it up a little and posted it here: 
[diff_insns.txt](https://github.com/Vector35/binaryninja-docs/files/129823/diff_insns.txt)

Examples of some instructions that stop dissassembly are:

```
aesenc xmm1,xmm3
xend
bzhi eax, [eax], ebx
rpu_read
vpandq zmm1,zmm2,zmm3
rdrand eax
```

There are some other weirdnesses going on with some of these instructions.
for example, BN supports the finit instruction which is what fninit assembles to but using BN to assemble an finit instruction generates both fwait and finit instructions.

**Comment by plafosse** [comment]
Closing this in favor of a more specific issue: #193
