### ISSUE TITLE
API for prioritizes user-requested function

### ISSUE THREAD

**Issue by honghai0924** [Vector35/binaryninja-api#1501]
I've known that in GUI, the analysis prioritizes user-requested function. 
Is there an API for that feature?  For example, when i'd like to analyze function foo, I can use some api to put foo on top of the analysis queue. Does function.reanalyze() do that?

BTW, what's the meaning of 'request_advanced_analysis_data()' ? 
Thanks a lot.

**Comment by psifertex** [comment]
Sorry for the delay on this. You'll want to use the following API:

https://api.binary.ninja/binaryninja.function-module.html#binaryninja.function.Function.request_advanced_analysis_data
