### ISSUE TITLE
Complete system call information in Linux platform types

### ISSUE THREAD

**Issue by meme** [Vector35/binaryninja-api#1507]
As the Linux syscall ABI is somewhat stable, it would make sense to fill out the entire `/types/platform/linux-*.c` platform files with their respective system call numbers and parameters, as it seems like it was started:

```c
/* linux-x86_64.c */
void sys_exit(int status) __noreturn __syscall(60);
void sys_exit_group(int status) __noreturn __syscall(231);
```

but never completed with the entire system call table.

**Comment by meme** [comment]
For anyone else interested in the table for AArch64, I have generated the system call table information for Linux 5.1.8: https://github.com/meme/dotfilez/blob/master/.binaryninja/types/platform/linux-aarch64.c

**Comment by plafosse** [comment]
This was fixed in build number 2467
