### ISSUE TITLE
Form to edit existing types in C-like form tries to create instead of edit

### ISSUE THREAD

**Issue by lks128** [Vector35/binaryninja-api#1509]
Binary Ninja Version: 1.2.1988-dev Personal, 638f19bd
Platform: macOS 10.15

Dear support,

I am facing the following issue with the process of editing existing structure in C-like form.

The workflow goes as follows:

1. focus on the structure

<img width="230" alt="Screenshot 2020-01-12 at 18 09 47" src="https://user-images.githubusercontent.com/120235/72221815-beaa7580-3566-11ea-9956-cd4540687771.png">

2. click Y to open editor dialog window

<img width="646" alt="Screenshot 2020-01-12 at 18 10 32" src="https://user-images.githubusercontent.com/120235/72221828-d8e45380-3566-11ea-898c-01f1f7f2ce0e.png">

As you may already have noticed the action button says "Create" instead of expected "Edit/Update". Pressing create is also trying to create a new structure instead of updating the existing one hence shows an error message.

<img width="532" alt="Screenshot 2020-01-12 at 18 14 17" src="https://user-images.githubusercontent.com/120235/72221881-5c05a980-3567-11ea-831a-3a09d71b6c4d.png">

Expectations:
- Y opens an "Edit" dialog window
- After finishing the dialog the sturcture is updated

Best regards,
Andris

**Comment by jeffli678** [comment]
close in favor of #1665. It will be fixed soon.
