### ISSUE TITLE
Document type library format

### ISSUE THREAD

**Issue by rollsafe** [Vector35/binaryninja-api#1513]
We should document the file format for type libraries. Here's a quick specification in case anyone is working with these.

First four bytes: magic 'BNTL' (42 4E 54 4C)
Next four bytes: If compressed, `uncompressed size`; otherwise, `0x80000000 | (size)`
Remaining bytes: If compressed, lzf compressed JSON; otherwise, uncompressed JSON

**Note that this isn't a formal specification. The file format may change without notice. This is just for any users who happen to be playing with this on their own.**

**Comment by negasora** [comment]
Users are only intended to interact with type libraries via the api, so this is more or less a wontfix
