### ISSUE TITLE
`s` hotkey might be triggering in unintended locations

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#1514]
xmppwocky reported that `s` produced odd results when called NOT from one of the locations expected in the new Smart Structure workflow.

**Comment by XMPPwocky** [comment]
So some of this is user error- me misunderstanding what 's' was supposed to do- but:

`299 @ 000b945e  uint32_t edi_126 = zx.d([esi_43 + 2].w)`

My understanding (now corrected) was that pressing "s" on "esi_43" would do three things: first, prompt for a type name and struct size and generate a struct from that; second, set the type of `esi_43` to a pointer to the new struct; third, add a 2-byte-wide member to the new struct, at offset 0x2.

But the actual behavior here is confusing - the prompt for a type name and struct size does appear, and a struct *is* defined with that name and size. And `esi_43`'s type *is* set to a pointer to struct... but the wrong struct! Specifically, regardless of the name used, `esi_43` ends up as `struct struct_1 *esi_43`.  This struct does not appear in the Types view, and does not seem to have a size. The API indicates that the actual type of `esi_43` is a pointer to a NamedTypeReference("struct_1") (and struct_1 is not a defined type).

So something's funky here.

**Comment by jeffli678** [comment]
I cannot reproduce this. I suggest it closed after we find when it is fixed

**Comment by jeffli678** [comment]
this is fixed sometime between stable 2.1 and 2.1.2371-dev
