### ISSUE TITLE
environment variable override for user folder

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#1518]
Plugin testing or even just testing multiple settings would benefit from a user-configurable [user folder](https://docs.binary.ninja/getting-started.html#user-folder). The `BN_USER_FOLDER` environment variable would allow for specifying different plugins and settings and be used in similar situations to [`BN_DISABLE_USER_PLUGINS `](https://docs.binary.ninja/guide/plugins.html#troubleshooting)

**Comment by plafosse** [comment]
Added in 2.4.3003
