### ISSUE TITLE
upgrading to latest stable makes token highlighting only be line highlighting 

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#1521]
As reported in slack, upgrading to the latest stable from previous stable caused previous BNDBs (but not fresh ones) to highlight only the line that contained a token rather than the token itself. 

![5B2E2E82-A439-4C83-BA72-B4A7D9051187](https://user-images.githubusercontent.com/140215/74035074-96f0d680-4987-11ea-980f-da60d1ff9cf5.jpeg)

**Comment by jeffli678** [comment]
I did not upgrade from the last stable, I upgraded from a dev version 1921.

**Comment by psifertex** [comment]
For what it's worth, 1921 was the latest stable before the most recent. 

https://binary.ninja/changelog/

**Comment by jeffli678** [comment]
Well, I am 100% percent sure I am using a dev rather than a stable. Then it must NOT be 1921. Sorry I cannot remember the exact version.

**Comment by jeffli678** [comment]
I believe this is already fixed. I downloaded the two old versions of binja and cannot reproduce it; I tested the particular database file that is having issues, and it works correctly on latest versions of binja.
