### ISSUE TITLE
Undefining function causing crash upon database reopen

### ISSUE THREAD

**Issue by 3pidemix** [Vector35/binaryninja-api#1523]
Getting a SIGSEGV accessing address 0. Occurs after undefining some bad functions, saving, and attempting to reopen the saved database.

Happens repeatably with multiple binaries. Can supply via Slack.

Version 1.3.2022-dev (Build ID c24b6acb)
macOS Catalina
Thumb2 binaries

**Comment by negasora** [comment]
Fixed in 1.3.2023-dev
