### ISSUE TITLE
annotating a function does not cause the function to become a user-function

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#1526]
This could result int he loss of information and also makes it currently impossible to tell the difference between functions that were automatically discovered and those that had user information applied.

**Comment by plafosse** [comment]
Repro steps:

1. Go to a function (a child) which is only called by one other function (the parent) and the child was discovered through recursive disassembly i.e. `current_function.auto == True`.
2. Modify the child function in some way. Change a variable name, make a comment, etc.
3. Undefine the parent function
4. This undefines the child function and causing data loss.
