### ISSUE TITLE
ephemeral highlights

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#1532]
Need the ability to make highlights and and comments

**Comment by negasora** [comment]
can the highlight part of this be closed?

https://api.binary.ninja/binaryninja.function-module.html#binaryninja.function.Function.set_auto_instr_highlight
https://api.binary.ninja/binaryninja.basicblock-module.html#binaryninja.basicblock.BasicBlock.set_auto_highlight

**Comment by negasora** [comment]
Highlights done a while ago. Split to https://github.com/Vector35/binaryninja-api/issues/2972
