### ISSUE TITLE
Font improperly scaling on home page on 4k monitors

### ISSUE THREAD

**Issue by hydra45** [Vector35/binaryninja-api#1535]
Binary Nina Version 1.3.2041-dev Build ID 7d256b28
Platform: Windows Version 10.0.18362 Build 18362

![](https://i.imgur.com/kT4zyic.png)

The font on the right side of the screen is basically unreadable because it's too small. There seems to be an issue with the scaling of the characters. When I tested on Linux Ubuntu 19.10, and the font was  pretty small there as well, although not nearly to the degree of the windows version.

**Comment by plafosse** [comment]
We will be moving to Qt6 and changing this view away from a QWebEngineView which will fix this problem.
