### ISSUE TITLE
Add a setting to increase the witdh of the hex values in the linear assembly view

### ISSUE THREAD

**Issue by janbbeck** [Vector35/binaryninja-api#1538]
The hex values column is too narrow to display some opcodes. I increased all the values under UI in settings, but none seems to affect this.
![Screenshot from 2020-02-24 06-05-16](https://user-images.githubusercontent.com/11450961/75129866-4e9e1c00-56dc-11ea-9ba0-f640a3f8bbbe.png)

**Comment by jeffli678** [comment]
Implemented in dev 2.1.2317. You can use "Expand long Opcode" in the disassembly options to show all opcode bytes.
