### ISSUE TITLE
PE file header "Load_Configuration_Directory_Table" isn't fully parsed , missing CFG structures

### ISSUE THREAD

**Issue by rohitwas** [Vector35/binaryninja-api#1542]
When analyzing PE files compiled with CFG,  Binary Ninja doesn't recognize and parse the full CFG structure within the  `Load_Configuration_Directory_Table` 
https://docs.microsoft.com/en-us/windows/win32/debug/pe-format#the-load-configuration-structure-image-only
It misses information about the CFG function table which is a list of RVA offsets to all the functions within the binary that are marked as valid CFG calls. 

BN could automatically mark all these offsets as valid cross refs to the corresponding functions

**Incomplete Load_Configuration_Directory_Table**
<img width="895" alt="load_config_dir_table" src="https://user-images.githubusercontent.com/12820186/75592958-986a6780-5a38-11ea-977f-60c832de0e93.png">

**CFG RVA offset table**
<img width="776" alt="CFG_table_rva_offsets" src="https://user-images.githubusercontent.com/12820186/75592980-a7e9b080-5a38-11ea-879b-79c6477d8fa0.png">

**Comment by rohitwas** [comment]
It seems that BN does recognize the CFG structures in **certain** PE files (example below) like jscript.dll but for some other files the analyzer does not parse it. 
<img width="721" alt="jscript" src="https://user-images.githubusercontent.com/12820186/75615891-9965cc80-5afe-11ea-9156-8968e28996f2.png">

**Comment by psifertex** [comment]
Apologies if you already shared it on slack and I've forgotten, but do you have an example you can share where it fails to parse?

**Comment by rohitwas** [comment]
@psifertex here is the example dll file- 
[jscript9.dll.zip](https://github.com/Vector35/binaryninja-api/files/4276813/jscript9.dll.zip)

**Comment by rohitwas** [comment]
according to the header, **0x10008f38** should be the CFG table but BN identifies the region around it as code and creates a function as can be seen below-
![misidentified-CFG-table](https://user-images.githubusercontent.com/12820186/75700425-e49aef00-5c66-11ea-93cc-fc01264ba50f.png)

**Comment by psifertex** [comment]
Thanks! That's helpful. Yeah, if the original parsing isn't correct the linear sweep will try to fill in the gaps (sometimes erroneously). Appreciate the test case.

**Comment by bpotchik** [comment]
Fixed in 2.1.2321-dev.
