### ISSUE TITLE
Anlaysis not completing and Python Console freezing

### ISSUE THREAD

**Issue by stvn1337** [Vector35/binaryninja-api#1543]
**_BinaryNinja 1.3.2047-dev.Personal Build ID 3fd9b7f9_**

<p>When disassembling :</p>

> EssentialPIM.exe (newest version)

<p>
analysis is constantly freezing and never completes on its own. </p><p>
By using bv.analysis_info, and navigating to the current function, you can sometimes get analysis to resume. </p><p>
However, after multiple times of doing this, the Python Console never reponds to the last bv.analysis_info command and simply freezes and becomes unusable.</p>

<p> I have tried 9 times over the course of 2 days to analyze this binary. </p>

**Comment by bpotchik** [comment]
This binary appears to analysis fine with `2.1.2459-dev`. It took around 90 minutes on Personal, and half the time with Commercial.
