### ISSUE TITLE
Publish API documentation for UI plugins

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#1544]

**Comment by gaasedelen** [comment]
As an external developer, it is very hard to find any information about the Binary Ninja UI apis or what they do. Google literally turns up nothing for any of the UI API's:

![image](https://user-images.githubusercontent.com/9522648/76144006-fce58200-6049-11ea-8d55-6e7b6d240799.png)

... and there is no information or references to these new APIs in the official binary ninja online docs.

The best resources at the moment are apparently the UI headers found in the github repo, but even these provide no information on what the API's actually do: https://github.com/Vector35/binaryninja-api/tree/dev/ui

If a direct google search isn't even able to find these headers, then how is anyone else?!?

**Comment by psifertex** [comment]
This is now available at https://api.binary.ninja/cpp (which is linked in recent builds) though we still need better organization to the documentation and it should be available offline. That will be tracked in 2046.
