### ISSUE TITLE
Relocation of PE is incomplete

### ISSUE THREAD

**Issue by jeffli678** [Vector35/binaryninja-api#1548]
The relocation of PE handles the addresses of code correctly. But it misses (seems all?) relocations to the global variables. For the following simple code, 

```
#include <iostream>

int a = 1;
int* p = &a;

int main()
{
    std::cout << "Hello World!\n";
	std::cout << a << std::endl;
	std::cout << p << std::endl;
}
```

Before relocation, everything works fine. 
![binaryninja_OyyVsuXfpk](https://user-images.githubusercontent.com/3380590/76380660-56251c80-638e-11ea-84cc-9a73076ee462.png)

After relocation, all references to globals are missing, 
![binaryninja_YtV0dsZSku](https://user-images.githubusercontent.com/3380590/76380686-6b9a4680-638e-11ea-9cde-30dab0513c8c.png)

Maybe you missed something when working with the relocation table?

**Comment by bpotchik** [comment]
Thanks for reporting this!

Fixed in 1.3.2074-dev.
