### ISSUE TITLE
Make accessible function signature properties

### ISSUE THREAD

**Issue by gaasedelen** [Vector35/binaryninja-api#1549]
Overview
---
Today I was trying to retrieve and update a function signature through the API and it is kind of non-trivial compared to IDA's API.

For example, using the API I could not find a way to get the fully qualified function signature string as shown at the top of each function (or if you press `Y`):

![image](https://user-images.githubusercontent.com/9522648/76426576-a0ec6780-6381-11ea-8d54-65ecaa2826b3.png)

The closest thing is `str(current_function.function_type)` but it does not include the function name:

```python
>>> str(current_function.function_type)
'int64_t (int64_t arg1, int64_t arg2, char* arg3)'
```

Suggestion
---

I think that the fully-qualified function signature string should be made available as a property off the `Function` object. Please consider something like the following:

```python
>>> current_function.type_string
'int64_t sub_232c0(int64_t arg1, int64_t arg2, char* arg3) __noreturn`

>>> current_function.type_string = 'int64_t sub_232c0(int64_t arg1, int64_t arg2, char* arg3)`
```

This is what I have to do currently: 

```python

# lol probably not portable for all sigs?!?
type_string = (' %s(' % current_function.name).join(str(current_function.function_type))
new_type_string = type_string.replace("__noreturn", "")
new_type = bv.parse_type_string(new_type_string)
current_function.function_type = new_type
```

PS: I had a hard time finding the `parse_type_string` function. It might also be helpful to update the `Type` module docs to reference it, or have an alias for it.

**Comment by psifertex** [comment]
- I've added parse_type_string along with a few others to the `class Type`  docstring 
- made the function_type setter also take a string
- changed the repr on the function itself to return the full prototype with name.
