### ISSUE TITLE
Create and ship more signature libraries

### ISSUE THREAD

**Issue by stong** [Vector35/binaryninja-api#1551]
Here's a list of the current signature libraries we have available:

Linux:
 - Ubuntu libc: x86, x86_64, arm32, arm64 (all versions)
 - Ubuntu libgcc: x86, x86_64, arm32, arm64 (all versions)

For the sake of size, we can't ship every sig lib by default. Here's what we're currently shipping:
 - Ubuntu libc, x86, x86_64 (18.04 and 16.04)
 - Ubuntu libgcc, x86, x86_64 (18.04 and 16.04)

In the future, we would like to have these:

Windows:
 - msvcrt: x86, x86_64

Unfortunately, we can't generate Windows signature libraries right now as we don't don't support COFF relocations yet (ref #1410 #1376 #1956).

**Comment by rollsafe** [comment]
Please suggest and vote on which signature libraries you'd like to see in the future.

**Comment by kongo86** [comment]
Windows Def!

**Comment by psifertex** [comment]
Windows doesn't need signature libraries, I don't think anyone staticly compiles user32.dll into their applications, do they?  You're talking about type libraries which is over here: https://github.com/Vector35/binaryninja-api/issues/1495

Good news is that's actively being worked. :-)

**Comment by joshwatson** [comment]
msvcrt and related dlls can be statically linked

**Comment by plafosse** [comment]
Added in 3.3
