### ISSUE TITLE
Register Architecture based on Machine Type and ELF Class (32/64 Bit)

### ISSUE THREAD

**Issue by f0rki** [Vector35/binaryninja-api#1553]
We recently released our [RISC-V architecture plugin](https://github.com/uni-due-syssec/bn-riscv/) and we tried to implement both 32-bit and 64-bit support. However, we had trouble getting both to work at the same time. 

The issue seems to be that currently there is only one ELF `e_machine` type for RISC-V (243 or 0xf3). Other architectures such as ARM or x86 have different `e_machine` types for 32/64 bit. So currently, we cannot register both the 64 and 32 bit RISC-V Architecture classes at the same time.

It would be nice to be able to register an Architecture also based on the ELF class (`e_class`, which is either `ELFCLASS32=1` or `ELFCLASS64=2`). Maybe even something like the `is_valid` parameter for the `PluginCommand.register` function that would allow a even more flexible selection?

Would this be possible? Is there a better workaround for this? (I know you can currently manually change the architecture in the open with options menu, but this is kind of cumbersome.)

**Comment by dragonmux** [comment]
Seconding this as we just smacked straight into this hard with the bn-riscv plugin trying to work with a RISC-V 32-bit binary - it's making the experience complete misery. Can't even automate the un-screwing-up of having asked for a 32-bit disassembly and getting a 64-bit disassembly (very broken).

**Comment by D0ntPanic** [comment]
You can now do this by placing the ELF class in the upper 16 bits of the architecture to be registered. If the upper 16 bits are zero, the ELF class is ignored. This is used in the official MIPS and RISC-V plugins, like the following:

```C++
		#define ARCH_ID_MIPS32 ((EI_CLASS_32<<16)|EM_MIPS) /* 0x10008 */
		#define ARCH_ID_MIPS64 ((EI_CLASS_64<<16)|EM_MIPS) /* 0x20008 */
		BinaryViewType::RegisterArchitecture("ELF", ARCH_ID_MIPS64, BigEndian, mips64eb);
		BinaryViewType::RegisterArchitecture("ELF", ARCH_ID_MIPS32, LittleEndian, mipsel);
		BinaryViewType::RegisterArchitecture("ELF", ARCH_ID_MIPS32, BigEndian, mipseb);
```
