### ISSUE TITLE
Non-determinism in returned lists and iterations of function xrefs

### ISSUE THREAD

**Issue by quend** [Vector35/binaryninja-api#1554]
Goal: to get a consistently ordered list of functions, x-refs, phi node elements, etc which we can iterate over deterministically 

Will add an example shortly #

**Comment by joshwatson** [comment]
Pretty sure this is due to prolific usage of `std::unordered_map` for storing things for performance reasons

**Comment by quend** [comment]
Yeah I'm not sure its possible to fix but would be handy for API usability

**Comment by psifertex** [comment]
I just added `__lt__` to `class Function` and `class ReferenceSource` so you can just `.sort()` or `sorted(list)` on them. 

I think most of the other common classes should have it too, but let me know if you find any other missing ones.
