### ISSUE TITLE
DWARF symbols in PE executables

### ISSUE THREAD

**Issue by resrever** [Vector35/binaryninja-api#1555]
mingw produces PE executables with embedded DWARF symbols.  Could BinaryNinja parse these automatically?  One workaround is to use cv2pdb to convert the symbols to a separate .pdb file, then manually select the .pdb for loading, but I would prefer to automate for scripting purposes.

**Comment by plafosse** [comment]
Dependent on #151

**Comment by plafosse** [comment]
Dependent on #2000

**Comment by psifertex** [comment]
We have improved dwarf import support and could use more test files. Do you have a specific file we could use for our test corpus?

**Comment by amyspark** [comment]
@psifertex Here go some files generated with MSYS2 CLANG64: [substrate.zip](https://github.com/Vector35/binaryninja-api/files/12502436/substrate.zip)

I and @dragonmux can generate more from our projects with all of the MSYS2 compilers; let us know and we'll send them your way.

**Comment by negasora** [comment]
Those example files load with debug info properly in `4.1.5747`, this was likely done a while ago
