### ISSUE TITLE
UI plugins are loaded even in headless

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#1556]
UI-only plugins may be loaded even in headless, though it's not normally observable without capturing logging information. Simple test case:

```
import binaryninja
binaryninja.log_to_stdout(binaryninja.LogLevel.WarningLog)
bv = binaryninja.BinaryViewType.get_view_of_file('/bin/ls')
```

produces:
```
Plugin module '/Applications/Binary Ninja-dev.app/Contents/Resources/python/binaryninja/../../../MacOS/plugins/libtriage.dylib' failed to load
dlerror() reports: dlopen(/Applications/Binary Ninja-dev.app/Contents/Resources/python/binaryninja/../../../MacOS/plugins/libtriage.dylib, 5): Library not loaded: @rpath/QtWidgets.framework/Versions/5/QtWidgets
  Referenced from: /Applications/Binary Ninja-dev.app/Contents/MacOS/plugins/libtriage.dylib
  Reason: image not found
list index out of range
Could not initialize UI, using headless mode only
```

**Comment by psifertex** [comment]
It's worth pointing out a very lazy but temporary fix to at least not get the message is to just re-order the log so that it happens after the core is initialized:

```python
import binaryninja
bv = binaryninja.BinaryViewType.get_view_of_file('/bin/ls')
binaryninja.log_to_stdout(binaryninja.LogLevel.WarningLog)
```

**Comment by melomac** [comment]
May be outputing those `dlopen` error messages to `stderr` would address a few user concerns? The workaround isn't practical in my context.

**Comment by melomac** [comment]
Seems like it is now fixed.

**Comment by jeffli678** [comment]
The reason is we do cannot distinguish a UI plugin from a core plugin until we dlopen it and see whether it exports CorePluginInit() or UIPluginInit(). But UI plugins are likely to already fail when we dlopen it, since they could import qt libs that are not present in headless

**Comment by plafosse** [comment]
This was fixed a while ago. Closing for now.
