### ISSUE TITLE
Stack usage graph opened by unresolved stack usage warning has overlapping nodes

### ISSUE THREAD

**Issue by shinmai** [Vector35/binaryninja-api#1558]
Binary Ninja Version: 1.3.2071-dev Personal,  5ac479f
Platform: Windows 10 Version 1909

Opening the stack usage graph from the "This function has unresolved stack usage" warning often results in a graph view that has overlapping nodes at the top of the graph as [illustrated in this screenshot](https://i.imgur.com/EJriYUi.png). Often when this happens, errors about nodes not being present in the layout data and not being processed are output to the log (also in the screenshot), but not always.

**Comment by plafosse** [comment]
Is there any chance you can share the binary?

**Comment by plafosse** [comment]
We believe this issue is fixed.
