### ISSUE TITLE
separate log_window output by BV

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#1564]
Sometimes a shared log window for multiple binaryviews is convenient and helpful. However with lots of open views it's more of an annoyance. We should optionally be able to pin the log window to just the output from the focused view.

**Comment by bpotchik** [comment]
Just open the binaryview in another window.

**Comment by gamozolabs** [comment]
Running into this pretty bad, can't reasonably use a script on multiple binja windows during dev as using it on one database scrolls the log of the other.

**Comment by plafosse** [comment]
Fixed in 3.1
