### ISSUE TITLE
UI: Single function linear view

### ISSUE THREAD

**Issue by withzombies** [Vector35/binaryninja-api#1569]
I'd like to be able to view a single function in linear view. It's really distracting to see neighboring functions, when most the time I'm unconcerned with them. I spend a lot of time on individual functions and it's best to keep distractions to a minimum.

**Comment by toolCHAINZ** [comment]
Also nice to be able to "scroll all the way up/down" in a function context and not an entire-binary context.

**Comment by psifertex** [comment]
Yeah, that would come for free with this new view. Home/End already function that way in the graph views.

**Comment by D0ntPanic** [comment]
Added in build 3177.

Single function view is now part of linear view as an option. You can find it in the options menu. If you navigate to data, linear view will show data for the entire binary with the functions collapsed. In this mode, double clicking a function will navigate to that function in single function view.
