### ISSUE TITLE
UI: Comment spacing

### ISSUE THREAD

**Issue by withzombies** [Vector35/binaryninja-api#1572]
```
080489f4  int32_t var_15 = 0x32494234
08048a00  int32_t edx  // comment
```

When marking up functions, I like to add a lot of comments and focus on those. It'd be nice if I could specify a minimum comment indentation, to pull comments out of the noise.

```
080489f4  int32_t var_15 = 0x32494234
08048a00  int32_t edx                                   // comment
```

Also, it'd be nice if comments were colored differently than string references.

**Comment by negasora** [comment]
Added in `4.1.5242-dev` with the `ui.view.common.minimumCommentSpacing` setting
