### ISSUE TITLE
Stray LLIL subtraction on compare

### ISSUE THREAD

**Issue by qwerty01** [Vector35/binaryninja-api#1576]
Binary Ninja Version: 2.0.2097-dev, 451aae39
Platform: Windows 10 Version 1903

Binary: [emojidb.zip](https://github.com/Vector35/binaryninja-api/files/4497203/emojidb.zip) from plaidctf 2020

Address: 0xa65

Disassembly:
![image](https://user-images.githubusercontent.com/1034539/79645107-49f56180-817b-11ea-88cc-e667eeb35ad3.png)

LLIL:
![image](https://user-images.githubusercontent.com/1034539/79645115-54aff680-817b-11ea-8e9e-4d6c934b67aa.png)

HLIL:
![image](https://user-images.githubusercontent.com/1034539/79645202-d2740200-817b-11ea-9a66-dbb777e54d3a.png)

It looks like LLIL correctly identifies the compare instruction, but it also emits a stray subtract for the same instruction, which is propagated all the way up to HLIL and isn't removed by the dead code heuristic.

**Comment by plafosse** [comment]
Fixed in 2.3
