### ISSUE TITLE
Tooltips from graph view need to be replicated in linear view

### ISSUE THREAD

**Issue by toolCHAINZ** [Vector35/binaryninja-api#1579]
Graph IL and assembly views allow for hovering over registers/IL variables to see the associated `PossibleValueSet`. It would be really nice to have this in linear views as well, especially now that there's linear IL views.

**Comment by psifertex** [comment]
Updating the title since there's a number of other tooltips that aren't shown in linear as well and we'd like to bring them all over.

**Comment by CouleeApps** [comment]
This has been done as of 2.4.3101-dev
