### ISSUE TITLE
binary ninja 2.0 can not analyse switch jump table correctly!

### ISSUE THREAD

**Issue by lyciumlee** [Vector35/binaryninja-api#1580]
![image](https://user-images.githubusercontent.com/29589768/79680595-eedb7180-8243-11ea-9677-a0e44b1f9b1a.png)
there is supposed a switch table.

**Comment by plafosse** [comment]
Could you possibly share this binary?

**Comment by breakingdevil** [comment]
[lelfei_fix.exe.zip](https://github.com/Vector35/binaryninja-api/files/4513584/lelfei_fix.exe.zip)

**Comment by breakingdevil** [comment]
IDA can identify switch table correctly.

**Comment by bpotchik** [comment]
Are you sure the image came from that binary? or did you rebase? I was not able to find the raw bytes or the code from the image in the file provided...

**Comment by breakingdevil** [comment]
the big function is at 0x401630.I update the bn,now it can identify the switch jump table, but i maybe crash.because the function is too big.

**Comment by psifertex** [comment]
Just to follow up -- can you please double check the binary that you're having trouble with and make sure you shared the right one? The screenshot you showed is at 0x400a50, but in the binary you included, there's nothing at that address! See:

![Screen Shot 2020-04-25 at 11 06 10 PM](https://user-images.githubusercontent.com/140215/80296464-81e74080-8749-11ea-8309-4746f2fe9eb7.png)

There also have been several bug-fixes to the 2.0 beta over the last week so if you can make sure you're on the latest dev and try again, please let us know if you're still experiencing any problems.

**Comment by plafosse** [comment]
As we've not gotten a binary which demonstrates this issue we can not fix. Please reopen if you have a binary you can share or additional details.
