### ISSUE TITLE
Clean up HLIL partial variable access

### ISSUE THREAD

**Issue by D0ntPanic** [Vector35/binaryninja-api#1589]
It is very common, especially in 64-bit or RISC binaries, to get a lot of extra zero extend and partial access operations, like these:

![HLIL partial access](https://user-images.githubusercontent.com/7007406/79794896-105e5b00-8321-11ea-99d4-29b2c8637a5a.png)

The analysis needs to be able to pick up on the actual size of access of larger registers and eliminate these if they are accessed as a smaller size. This will clean up the decompiled output considerably.

**Comment by D0ntPanic** [comment]
Build 2453 optimizes cases where only the lower bits of a register are used. This will take place automatically in many cases and give the correct size to the variable according to its access patterns. This means that the occurrence of `zx` and `sx` IL instructions should be reduced, especially for RISC architectures.

There are some restrictions to the optimization that may make it not take place automatically. One of these is return values. The analysis can't yet be sure of the uses of the return value elsewhere in the program, so it does not currently optimize the size of return values. Setting the return type in the UI or through the API to a smaller size will take effect and propagate throughout the function.

If Binary Ninja makes an incorrect optimization somewhere, you can set the variable to a larger type and it will inhibit the optimization from taking place.

Small access size should work well on most RISC architectures. For x86, 8-bit and 16-bit writes may not optimize cleanly in all cases. This will also be true of any architecture that partially writes registers, leaving the upper part of the register unchanged.

**Comment by nshp** [comment]
Just FYI, I still see unnecessary zero-extending for properly typed function parameters:

I have a function (I manually set the type):
`int func(int arg1, char mode)`

And the callsite shows:
`r6 = func(constant, mode: zx.d(*gMode))`

Where `gMode` is also defined as a `char`.
