### ISSUE TITLE
HLIL has code that should probably be removed

### ISSUE THREAD

**Issue by Vasco-jofra** [Vector35/binaryninja-api#1594]
`temp0_1`

![comments](https://user-images.githubusercontent.com/11303847/79875431-904bfa00-83e1-11ea-8a68-088180be8204.png)

The subtraction (caused by the cmp) seems irrelevant.

![random_sub](https://user-images.githubusercontent.com/11303847/79875427-8e823680-83e1-11ea-951b-28d3262350e5.png)

**Comment by D0ntPanic** [comment]
Fixed in build 2636
