### ISSUE TITLE
Elf object files

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#16]
_From @D0ntPanic on May 26, 2015 5:13_

Should add support for disassembling .o files.  On Linux they are ELF files, and Binary Ninja recognizes them as such.  However, as they have no load program headers, the ELF file appears empty.  Should allow disassembly of the functions inside of it.

This probably should be considered lower priority.

_Copied from original issue: Vector35/binaryninja#35_

**Comment by erhlee-bird** [comment]
Hey @psifertex, I know this is lower on the priority list, but do you have any idea when this issue might be revisited?

Thanks!

**Comment by psifertex** [comment]
@erhlee-bird Sorry for the very long delay in responding, missed this comment earlier. Unfortunately, no ETA on this still.

**Comment by erhlee-bird** [comment]
No worries! Thanks for the update guys

**Comment by plafosse** [comment]
Support added in added as of v1.1.1345
