### ISSUE TITLE
automatically navigate to main

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#1600]
For binaries where main is defined and identified, navigate there on startup rather than staying at the entry-point

**Comment by galenbwill** [comment]
Implement automatic navigation to `main` function when opening a new binary:

- [ ] 1. Settings should include a list of symbol names to search for.
- [ ] 2. Only function symbols should be allowed.
- [ ] 3. Settings should have an "enable" checkbox (checked by default).

**Comment by galenbwill** [comment]
Implemented in dev build 3377.
