### ISSUE TITLE
Missing BNCustomArchitecture callback for BNGetArchitectureRegisterByName

### ISSUE THREAD

**Issue by nshp** [Vector35/binaryninja-api#1603]
Unless BNGetArchitectureRegisterByName is internally implemented in terms of the other callbacks, I believe there should be an extra:

```c
uint32_t (*getRegisterByName)(void* ctxt, const char* name)
```
in BNCustomArchitecture

**Comment by rssor** [comment]
This is actually implemented internally in terms of cached names/register IDs, so is not a bug. If there's a chance that this is the XY problem, there is a limitation with Python extensions adding registers mentioned in #963, so if you're seeing a failure to look up registers by name as a result of trying to do that, that's what you're running into. Feel to to re-open if I've misunderstood.
