### ISSUE TITLE
Search and apply standard enum constants.

### ISSUE THREAD

**Issue by bool101** [Vector35/binaryninja-api#1608]
One of the features I frequently use in IDA is to change constant values to known enum members. I usually end up using search feature to find standard enum constants with the 'm' hotkey. It results in more readable code. These values are pulled in from type libraries. It would be nice to see a similar feature in BinaryNinja.

**Comment by plafosse** [comment]
Thanks, we agree that is a needed feature. We had to put some underlying analysis in place before we could make this happen. There is already an issue tracking this: #1216

**Comment by psifertex** [comment]
Sorry, that's my bad, I forgot about the existing issue and asked him to file this one. :-)
