### ISSUE TITLE
Support MachO local relocations

### ISSUE THREAD

**Issue by meme** [Vector35/binaryninja-api#1610]
In seemingly really, really old linker configurations, the MachO produced will use the local relocation table for relocations which is stored in the `__LINKEDIT` segment (which is referenced in the `DYNSYM` MachO load command).

Additionally it appears that when `.dylib`s contain the local relocation section they will also report themselves as non-PIE which is as far as I can tell INCORRECT because they can observably be relocated by the macOS linker using the local relocations section.

As well, Binary Ninja should type these relocations and display them in the linear view.

**Comment by lwerdna** [comment]
Could you attach or link to a small MachO with the properties you describe?

**Comment by meme** [comment]
If you just set your SDK to be really old, you can build for yourself: 

```c
// sample.c
#include <stdint.h>
#include <stdlib.h>
#include <time.h>

// You _probably_ don't have these old crt1.o binaries.
uint64_t X asm("dyld_stub_binding_helper") = 0;

uint64_t SERIAL = 0xdeadbeef;

void transmogrify(uint64_t v) {
    srand(time(NULL));
    SERIAL ^= v & rand();
}
```

```sh
$ clang -shared -undefined dynamic_lookup -arch i386 -Wl,-macos_version_min,10.4 sample.c
```

(should also build an x86_64 variant with `-arch x86_64` as they have a different set of relocations)

You can confirm that you've built a binary with the old relocation model using `otool` (modern binaries should have **no output**):
```
$ otool -v -r a.out
a.out:
Local relocation information 9 entries
address  pcrel length extern type    scattered symbolnum/value
00000f4c False long   False  VANILLA False     6 (__DATA,__la_symbol_ptr)
00000f52 False long   False  VANILLA False     6 (__DATA,__la_symbol_ptr)
00000f58 False long   False  VANILLA False     6 (__DATA,__la_symbol_ptr)
00000f5d False long   False  VANILLA False     6 (__DATA,__la_symbol_ptr)
00000f69 False long   False  VANILLA False     6 (__DATA,__la_symbol_ptr)
00000f75 False long   False  VANILLA False     6 (__DATA,__la_symbol_ptr)
00001000 False long   False  VANILLA False     3 (__TEXT,__stub_helper)
00001004 False long   False  VANILLA False     3 (__TEXT,__stub_helper)
00001008 False long   False  VANILLA False     3 (__TEXT,__stub_helper)
```

---

And to see that the "bug" is present:

```
>>> bv.perform_is_relocatable()
False
```

Binary Ninja will report that the executable is not relocatable (even though it is) and you will not be able to rebase it.

---

To resolve this, Binary Ninja should support local relocations and external relocations in the LC_DYSYMTAB command and parse both scattered and non-scattered relocations. If you have any questions about this antiquated relocation format, I've had to hack together my own simple linker for some analysis and the `dyld` linker source is a good ground truth (but I'm also happy to answer questions if I can).

**Comment by meme** [comment]
Also see: https://github.com/Vector35/binaryninja-api/issues/1609 (as these new changes should be reflected in the MachO types).

**Comment by lwerdna** [comment]
[sample_x64.zip](https://github.com/Vector35/binaryninja-api/files/6276143/sample_x64.zip)

@meme do you know what the address field in these relocations refer to exactly?

```
$ otool -v -r ./sample_x64
./sample_x64:
Local relocation information 3 entries
address  pcrel length extern type    scattered symbolnum/value
00000000 False quad   False  UNSIGND False     3 (__TEXT,__stub_helper)
00000008 False quad   False  UNSIGND False     3 (__TEXT,__stub_helper)
00000010 False quad   False  UNSIGND False     3 (__TEXT,__stub_helper)
```

As offsets into the first segment's .vmaddr=0 field, 0, 8, and 10 are still in the header. As offsets into the first segment's first loaded data (section __text) at 0xEF0 the 0 is at the `0EF0: 55 push rbp` and 8 is at the `0EF8: xor eax, eax` so that can't be right. Where do these things point?

It's interesting `llvm-readobj -r --expand-relocs ./sample_x64` doesn't display any of these.

Here's some wide output of a tool to display the `struct relocation_info`:

```
                                                                           struct relocation_info(dysymtab)
00002000 00 00 00 00                                      ....               r_address: 0x0
00002000             03 00 00 06                              ....           r_symbolnum: 0x3 section "__TEXT/__stub_helper"
                                                                             r_pcrel: 0
                                                                             r_length: 4 bytes (2)
                                                                             r_extern: 0
                                                                             r_type: X86_64_RELOC_UNSIGNED (0)
                                                                           struct relocation_info(dysymtab)
00002000                         08 00 00 00                      ....       r_address: 0x8
00002000                                     03 00 00 06              ....   r_symbolnum: 0x3 section "__TEXT/__stub_helper"
                                                                             r_pcrel: 0
                                                                             r_length: 4 bytes (2)
                                                                             r_extern: 0
                                                                             r_type: X86_64_RELOC_UNSIGNED (0)
                                                                           struct relocation_info(dysymtab)
00002010 10 00 00 00                                      ....               r_address: 0x10
00002010             03 00 00 06                              ....           r_symbolnum: 0x3 section "__TEXT/__stub_helper"
                                                                             r_pcrel: 0
                                                                             r_length: 4 bytes (2)
                                                                             r_extern: 0
                                                                             r_type: X86_64_RELOC_UNSIGNED (0)
```

**Comment by meme** [comment]
The `r_address` points into the first writeable section. In the example it is `__DATA`. So the calculation is `base_address + data_address + r_address`. The `r_address` can also have tags, so make sure to check if the scattered bit is set (for scattered relocations: `& R_SCATTERED != 0`)

**Comment by lwerdna** [comment]
@meme Ah the first _writeable_ section, thanks. Would you mind double checking, for the 64-bit attachment, that Binary Ninja is not applying the relocations?

I'm going to blab out loud here, so if I go wrong, the exact place can be identified:

Those three `r_address` locations point to PLT entries:

```
__DATA/__la_symbol_ptr:
1000: 0F4C
1008: 0F58
1010: 0F64
```

and those values are initially the addresses of instructions that jump through the PLT:

```
__TEXT/__stub_helper:
0F4C: lea	r11, qword ptr [rip + 0xad]; jmp dyld_stub_binding_helper
0F58: lea	r11, qword ptr [rip + 0xa9]; jmp dyld_stub_binding_helper
0F64: lea	r11, qword ptr [rip + 0xa5]; jmp dyld_stub_binding_helper
```

but after relocations (and in Binary Ninja) they're changed to:

```
__DATA/__la_symbol_ptr:
1000: 3000 ; extern _rand
1008: 3008 ; extern _srand
1010: 3010 ; extern _time
```

This all seems correct, and disassembly of `transmogrify()` correctly shows the calls to rand, srand, and time. Is it just that the return from `perform_is_relocatable()` is wrong?

**Comment by meme** [comment]
This looks right. I was able to analyze the binary but I want to be able to rebase it in BN which was not possible because it didn't detect it as relocatable. So if it is not too much work, ideally I could open the binaries I have with local relocations and rebase them (and have BN detect that they are PIE)

**Comment by lwerdna** [comment]
@meme could you update to latest dev and try to rebase now? Note that `bv.perform_is_relocatable()` isn't meant to be called directly (and will show false), try the property `bv.relocatable` instead, which should return true now. Rebasing works on this end now, please confirm.

[sample_x86.zip](https://github.com/Vector35/binaryninja-api/files/6282997/sample_x86.zip)

**Comment by meme** [comment]
Thanks for your help, it works as expected on latest now :smile:

**Comment by lwerdna** [comment]
Great, thanks for creating the issue and following up! See you on the next issue :P
