### ISSUE TITLE
Intrinsics and global register issues

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#1611]
I have been attempting to work around some non-lifted arm64 instructions and add intrinsics for them and have run into some problems.

## Problem

Because unlifted instructions are counted as nops in HLIL, dataflow going into them is can be optimized away via dead store removal.

MLIL:
```
_start():
   0 @ 00010004  int64_t x0 = 0x30c50830
   1 @ 00010008  unimplemented  {msr sctlr_el3, x0}
```

HLIL:
```
_start():
   0 @ 00010008  unimplemented  {msr sctlr_el3, x0} // what is x0?
```

## Adding Intrinsics

The solution to these particular unlifted instructions seems to be intrinsics via an architecture extension. I implemented this and it worked fine for simple instructions without arguments (ISB, WFI, etc), but on instructions that affect dataflow I ran into problems.

First, both of the "good" solutions I can think of require adding registers to the architecture for the MSRs themselves. I added all the MSRs as global registers in my extension.

I implemented two intrinstics, `_ReadStatusRegister` and `_WriteStatusRegister`, corresponding to `MRS` and `MSR` (x64 analogs would be `RDMSR` and `WRMSR`). There are two obvious ways to try to lift these, and both seem to have problems.

### msr_reg = Intrinsic(input_reg)

I originally lifted `_WriteStatusRegister` as `msr_reg = intrinsic(input_reg)`. This solves my initial problem of the input value being removed, however immediately introduced a second problem! The HLIL with this implemented looks like:

```
_start():
   0 @ 00010008  _WriteStatusReg(0x30c50830)
```

So now my input value _is_ used, but the _output_ value gets removed for the same reason. Wups.

### Intrinsic(msr_reg, input_reg)

Ok, so my second idea was to make both the msr_reg and the input_reg inputs to my intrinsic and have it clobber nothing. I implemented this, and it again solved my problem while immediately introducing a new one. Because these registers were used before they were written to my function signature and HLIL changed to this:

```
int64_t _start(uint32_t arg1 @ SCTLR_EL3, ...)

   0 @ 00010008  _WriteStatusReg(arg1, 0x30c50830)
```

Which obviously not great either.

## Solutions?

I can see a few ways to solve this:
1. Global registers are always considered used, so don't get removed as dead stores (fixes my first attempt)
2. Global registers are excluded from argument lists (fixes second attempt)
3. I could add an intrinsic pair per MSR (one for read, one for write) and hardcode the MSR register name into the intrinsic name. This is kinda ugly.
4. I could try to exclude the MSRs from the calling convention?
5. Something else I didn't think of?

At this point Im unsure what the best way forward is. Happy to provide input binaries, my code, etc.

**Comment by yrp604** [comment]
Add on: even with the first solution (`msr_reg = Intrinsic(input_reg`) the argument list still becomes an issue when you have functions that do `x0 = _ReadStatusRegister(msr_reg)` without writing it first. So it looks like with my current attempt I would need at least global regs excluded from arguments lists for either solution to work.

**Comment by D0ntPanic** [comment]
There were two issues here. First is that adding global registers from an architecture hook did not work. The core caches the global register list early and does not update it, so adding a global register had no effect. The analysis never adds global registers as parameters, but the core did not realize that the new registers were global. This has been fixed.

Second, there needed to be two types of global registers. One of the most common uses of global registers is to account for module data pointers that are global between functions. These are important for the analysis to track as it is critical to the computation of pointers in some position independent binaries. These values also should be eliminated in the higher levels of IL, as they are not important once the pointers have been resolved.

To support use cases such as MSRs, a new "system register" list has been added to the API. You should add your MSR registers to the system register list, and these will never be eliminated as dead code. In the future, HLIL may choose to display these writes differently (as they currently appear to be a local variable, which may be confusing).

Added in build 2114

**Comment by yrp604** [comment]
Switched things over, fixed some other bugs on my end and things look good so far! Thanks!
