### ISSUE TITLE
Parameters annotations/lable missing in linear view

### ISSUE THREAD

**Issue by oeyvindb** [Vector35/binaryninja-api#1616]
Function paramenter annotations is missing in linear view, but they exist in graph view

**Linear view:**
<img width="567" alt="Skjermbilde 2020-04-27 kl  21 47 05" src="https://user-images.githubusercontent.com/10116900/80414651-a79f5180-88d1-11ea-9fa9-36eca5cee470.png">

**Graph view:**
<img width="1025" alt="Skjermbilde 2020-04-27 kl  21 46 20" src="https://user-images.githubusercontent.com/10116900/80414695-b38b1380-88d1-11ea-9c56-e8d1ceea3619.png">

**Comment by negasora** [comment]
Fixed in 2.0.2112-dev
