### ISSUE TITLE
Bold text in menus on windows renders poorly (Dark Theme)

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#162]
<img width="265" alt="screen shot 2016-02-21 at 12 00 55 pm" src="https://cloud.githubusercontent.com/assets/10556585/13204012/d4367a28-d892-11e5-853f-95a233f682c1.png">

**Comment by bpotchik** [comment]
This has been fixed for the dark theme in build 1.1.1294-dev.
