### ISSUE TITLE
Incorrect HLIL breaking out of a while loop

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#1622]
2.0.2115-dev Personal

I have a function which is checking if a 0x100 byte buffer is null. Note that this function can return either zero (ins 4) or one (ins 9)

MLIL function:
```
   0 @ 00001ba0  ii = 0
   1 @ 00001ba0  goto 2 @ 0x1ba4

   2 @ 00001ba4  x2_1 = zx.q([arg1 + (ii << 2)].d)
   3 @ 00001ba8  if (x2_1.w2 != 0) then 4 @ 0x1bc0 else 6 @ 0x1bac

   4 @ 00001bc0  r = 0
   5 @ 00001bc4  goto 8 @ 0x1bbc

   6 @ 00001bac  ii = ii + 1
   7 @ 00001bb4  if (ii != 0x40) then 2 @ 0x1ba4 else 9 @ 0x1bb8

   8 @ 00001bbc  return r

   9 @ 00001bb8  r = 1
  10 @ 00001bb8  goto 8 @ 0x1bbc
```

HLIL:
```
00001ba0  int64_t ii = 0
00001bc0  int64_t r
00001bc0  do
00001bc0      if (*(arg1 + (ii << 2)) != 0)
00001bc0          r = 0
00001bc4          break
00001bac      ii = ii + 1
00001bac  while (ii != 0x40)
00001bb8  r = 1
00001bbc  return r
```

The HLIL version of the function has the return 0 path folded into the return 1 path.

This binary can be downloaded from http://static.sstic.org/challenge2019/challenge_SSTIC_2019-virtual_phone.tar.gz and found inside rom.bin @ offset 00001ba0.

**Comment by D0ntPanic** [comment]
Fixed in build 2117.
Same issue as #1581 but for do while loops.
