### ISSUE TITLE
Minor Feature request: re display/copy physical address in file

### ISSUE THREAD

**Issue by CunningLogic** [Vector35/binaryninja-api#1624]
Could we perhaps get an option in the ui to display the physical address of instructions, or maybe a right click option to "Copying physical address in file" like we can with  right click copy address?

**Comment by psifertex** [comment]
This was solved with a snippet: https://gist.github.com/psifertex/6fbc7532f536775194edd26290892ef7#file-clipboard-py

Though note that you'll want to uncomment that example (which I think you already did)
