### ISSUE TITLE
Docs: get_instruction_low_level_il gets more data than documented

### ISSUE THREAD

**Issue by nshp** [Vector35/binaryninja-api#1630]
https://github.com/Vector35/binaryninja-api/blob/6f863df807afdd111017a92cfc15c6f6a0d79310/python/architecture.py#L1503

I don't believe this is true. Maybe `BN_MAX_INSTRUCTION_LENGTH`? Maybe up to the end of the basic block? But definitely greater than Architecture.max_instruction_length

**Comment by plafosse** [comment]
Its only guaranteed to be up to max_instruction_length, but it is in fact as you guessed it up to the end of the basic block.

**Comment by psifertex** [comment]
Need to investigate all other APIs that claim to return max_instruction_length and validate them as well.

**Comment by psifertex** [comment]
Other APIs clarified and validated.
