### ISSUE TITLE
Invalid Symbol Types when using C++ based executables

### ISSUE THREAD

**Issue by masl123** [Vector35/binaryninja-api#1632]
**Description of the Problem:**
When trying to change the type of a symbol (a function)  in the UI that has been automatically created or created by python, it will sometimes fail because symbol names are checked differently.

**Example:**
One example of this happening is when the keyword "class" is used as part of the type.
1. Open the binaryninja.exe using File-->Open
2. wait for the autoanalysis to complete
3. open one of the symbols in the "Graph view" or "Linear View" that has a class as a parameter
e.g. "int64_t  MiniGraph::mousePressEvent(**class** QMouseEvent* arg1)"
4. try to change the type using the "Change Type..." Option in the context menu when selecting the symbol name or use the shortcut 'Y'
5. e.g. change the name of the parameter
e.g. "int64_t  MiniGraph::mousePressEvent(class QMouseEvent* **arg2**)"
6. Not a valid type anymore.... :(

**Info:**
Binary Ninja Version: 2.0.2111-dev Personal, 5466385d
Platform: Windows 10 Version 1803

**Comment by crand6** [comment]
Will also throw in another example of `int64_t  std::ostream::operator<<(int32_t arg1)`

**Comment by CouleeApps** [comment]
Type names with <> and :: are now allowed via string escaping. See https://github.com/Vector35/binaryninja-api/issues/2427#issuecomment-1042327994 for details.

Going to leave this open for now, as the original issue was reporting an error with `class` keywords, which is still present.

**Comment by CouleeApps** [comment]
Class keywords are now handled with the new clang type parser.
