### ISSUE TITLE
Cannot create empty structs using the "Create Types" dialog

### ISSUE THREAD

**Issue by masl123** [Vector35/binaryninja-api#1633]
**Description of the Problem:**
You cannot create empty structs using the "Create Types" dialog. Although you can create them using the "Create New Structure..." dialog.

**Example:**
1. Open some executable using File-->Open
2. wait for the autoanalysis to complete
3. Open the Types View
4. open the "Create Types" dialog using the "Create New Types..." option from the context menu when clicking on an empty space of the Type View. 
5. enter the following into the dialog: 
```
struct empty
{

};
```
6. try to click on create
7. this leads to an error message

**Info:**
Binary Ninja Version: 2.0.2111-dev Personal, 5466385d
Platform: Windows 10 Version 1803

**Comment by CouleeApps** [comment]
Empty structures are now allowed as of 3.0.3413-dev (both clang and core parsers).
