### ISSUE TITLE
String parameters don't inline in some HLIL functions

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#1635]
If a function is folded into another function call as a parameter, or into an if expression, parameters of that call that are strings will not inline if you press `a` while highlighting that parameter:
![image](https://user-images.githubusercontent.com/5834130/80824530-79e92f80-8b93-11ea-82f3-7baf5a95e9b8.png)

**Comment by D0ntPanic** [comment]
Fixed in build 2124
