### ISSUE TITLE
Feature request: Highlight current code block in linear HLIL

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#1636]
It would be really nice to have a slight highlight on the current block of code in linear HLIL so it's obvious to the user where the current indentation ends

**Comment by psifertex** [comment]
Following the cursor specifically? Or for all indentation levels separately highlighted?

**Comment by joshwatson** [comment]
Yeah, following the cursor, basically like this, but lighter for the instructions in the same block that aren't specifically being highlighted by the cursor:
![image](https://user-images.githubusercontent.com/5834130/80828890-eb78ac00-8b9a-11ea-979a-35306b8f6cc7.png)

**Comment by petterroea** [comment]
I was about to request this myself. Another possibility that could work for me would be to have the "cursor" not stop showing itself when you move it vertically. Just anything that would give me a practical way of measuring indentation without using a physical ruler :straight_ruler: 

![binja_issue](https://user-images.githubusercontent.com/725557/95891671-b3020e80-0d85-11eb-9f4a-851d91e695ab.png)
Screenshot of the "cursor" in question, which stays visible if moved horizontally, but not vertically.

**Comment by psifertex** [comment]
`Show Indentation Guides` will help you, it's a setting in recent dev builds

**Comment by psifertex** [comment]
<img width="901" alt="Screen Shot 2020-10-13 at 1 06 08 PM" src="https://user-images.githubusercontent.com/140215/95892676-dd87a380-0d54-11eb-8893-5162abaff02e.png">

**Comment by petterroea** [comment]
Nice, this solves the issue for me

**Comment by psifertex** [comment]
Actually, come to think of it, we might just be able to close this issue entirely now as it's a relatively nice solution to the request. @joshwatson do you think there's still value in the highlight as well? 

We've been debating enabling the indentation guide by default as well.

**Comment by negasora** [comment]
This is on dev, and will be enabled by default in the next build
