### ISSUE TITLE
Clearing "recently opened files"

### ISSUE THREAD

**Issue by gynophage** [Vector35/binaryninja-api#164]
It would be neat if we could remove entries from recently opened files, or clear the list all together.

**Comment by psifertex** [comment]
implemented a menu item to clear the list for builds >= 1094 but this is only a temporary fix as it still needs to properly clear any existing new file tabs. Will close this bug when that is completed.

**Comment by bpotchik** [comment]
Fixed in build 1.1.1127-dev.
