### ISSUE TITLE
Navigation to function while in strings/types view

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#1646]
Currently, when you double-click a function or cross reference in the strings/types view it doesn't switch your view back to a linear/graph view. Rather it tries to navigate within that view.

**Comment by negasora** [comment]
This seems fixed as of 2.1.2273-dev

**Comment by negasora** [comment]
Actually, xrefs work, symbol list doesn't

**Comment by jeffli678** [comment]
@negasora I tested it and I think it is also fixed on symbol list. Free feel to test it again and poke me

**Comment by jeffli678** [comment]
it is already fixed a while ago. Though I cannot find an exact version number
