### ISSUE TITLE
MLIL pointers into the middle of a structure 

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#1649]
Discussion here: #1641

**Comment by enedil** [comment]
I'm not adding much to the discussion, but I'd really like to see this bug solved. This affects lots of my work, is really annoying and I'm not aware of any viable workaround (apart from checking LLIL/disasm each time I'm not sure). So that's a bump from me.

**Comment by psifertex** [comment]
If you're on the latest dev you can at least use the reflection menu (from the view menu or command palette) to always show the other ILs side by side. I realize that's not a complete fix, just a suggestion to at least make the workaround easier.

**Comment by D0ntPanic** [comment]
Fixed in build 2610
