### ISSUE TITLE
Enhance Comments in HLIL

### ISSUE THREAD

**Issue by Martyx00** [Vector35/binaryninja-api#1652]
Just few tips on how to enhance experience with comments.

1.  Comments on lines with same addresses but two different instructions would be more readable if they would show only on the first line.

2. Since with HLIL, Linear view is now much more popular compared to graph view, it would be good to have function comments visible above function header.

**Comment by plafosse** [comment]
Dependent on this: #2371

**Comment by CouleeApps** [comment]
Both of these are fixed in 2.4.2900-dev:
1. Comments with multiple lines for one address will now show at most once per basic block. In HLIL-Linear this corresponds to showing only once at the first line with that address.
2. Function comments are now visible above function headers.
