### ISSUE TITLE
HLIL Doesn't Currently Retrieve `this` pointer

### ISSUE THREAD

**Issue by tekwizz123** [Vector35/binaryninja-api#1656]
Atm if one loads up binaries such as win32kfull.sys and attempts to decompile a function with a `this` pointer in its function defininition, such as `ESTROBJ::ptlBaseLineAdjustSet`, the definition in Binary Ninja will be as though the invisible `this` pointer never existed. This makes it incredibly annoying to correct HLIL output that uses the `this` pointer in its code. This can be seen in the image below.

![binary ninja failing to find hidden this pointer](https://user-images.githubusercontent.com/2746189/81533130-404ebc00-932b-11ea-91c5-fa57302b4478.PNG)

On the contrary, programs like Relyze are able to recognize that this function has a hidden `this` parameter from the PDB information:

![relyze showing this pointer](https://user-images.githubusercontent.com/2746189/81533453-da166900-932b-11ea-9518-3a3f6f99658e.PNG)

**Comment by plafosse** [comment]
This is dependent on this issue #604

**Comment by CouleeApps** [comment]
PDBs now properly annotate `this` parameters and thiscall functions, so combining the fixing of #604 with the new PDB loader in 3.1.3715-dev, this is now fixed.
