### ISSUE TITLE
Python HLIL instruction should implement lt, le, gt, ge

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#1659]
LLIL: https://github.com/Vector35/binaryninja-api/blob/dev/python/lowlevelil.py#L942-L960
MLIL: https://github.com/Vector35/binaryninja-api/blob/dev/python/mediumlevelil.py#L375-L394
HLIL: n/a

This breaks @withzombies's bnil graph here: https://github.com/withzombies/bnil-graph/blob/master/__init__.py#L202 because HLIL instructions are not sortable. I'd PR it, but as far as I can tell it's a literal copy/paste of your own code to fix it.

**Comment by withzombies** [comment]
Lol i just came here to file this issue. I agree, it breaks my graph plugin.

**Comment by yrp604** [comment]
630824de49fcde2f61701ac2019834bda079a341 closes this, unless I've missed something?

**Comment by negasora** [comment]
Thanks, it does (added in 2.1.2289-dev)
