### ISSUE TITLE
HLIL invalidly simplifies unsigned comparisons

### ISSUE THREAD

**Issue by PistonMiner** [Vector35/binaryninja-api#1662]
This PPC assembly
```
addi    r0, r3, -0x12
cmplwi  r0, 0x1
ble     0x8006e5b4
```

incorrectly ends up as the following HLIL:
```
r3_2 u> 0x13
```

The offending transformation obtained through `Function.request_debug_report("high_level_il")` appears to be:
https://i.imgur.com/OaUd9Ts.png to https://i.imgur.com/GtX5tsi.png

**Comment by D0ntPanic** [comment]
This optimization should have been done only on equality comparisons. Fixed in build 2145.
