### ISSUE TITLE
Attempting to Alter an Already Defined Type in Binary Ninja Can Lead to "Error *type* is already defined!"

### ISSUE THREAD

**Issue by tekwizz123** [Vector35/binaryninja-api#1665]
When attempting to edit types within Binary Ninja, there appears to be several errors at the moment. One of the most confusing though is a an error that sometimes occurs when trying to add new fields in to an already existing type. Doing so sometimes succeeds, but in other cases, particularly cases where structures have an "_" in their name, we sometimes tend to get this instead:

![trying to edit the fields](https://user-images.githubusercontent.com/2746189/81895056-efcb9e80-9576-11ea-99e5-f833b7a228b6.PNG)

The only way to get around this is to then go ahead and "Set Structure Size", followed by right clicking one of the bytes and selecting "Create Field at Cursor". Result of doing this can be seen below:

![part 2 of structure modification issues](https://user-images.githubusercontent.com/2746189/81895140-33260d00-9577-11ea-910f-b5394d5c0e85.PNG)

Any way we could get this fixed or at least have an option to forcibly overwrite a type as a workaround to solve these issues?

**Comment by jeffli678** [comment]
fix in dev 2.1.2372
