### ISSUE TITLE
Not Possible to Use Some Types in The Type Database for Function Definitions

### ISSUE THREAD

**Issue by tekwizz123** [Vector35/binaryninja-api#1666]
Attempting to define new types in the type database and then use them in the function prototype sometimes fails, as can be seen in the following screenshot.

Note that this is fine:

![function prototype definition issue part 1](https://user-images.githubusercontent.com/2746189/81895492-ea228880-9577-11ea-8a63-628d95d74056.PNG)

However this is not for some odd reason:

![function prototype definition issue part 2](https://user-images.githubusercontent.com/2746189/81895506-f4dd1d80-9577-11ea-9d20-1868d6d46b32.PNG)

And yet if we look at the type database, `POINTL` clearly is a type definition for `tagPOINT` which worked in the first example:

![function prototype defintition issue part 3](https://user-images.githubusercontent.com/2746189/81895540-0f16fb80-9578-11ea-8cc2-f2ae6c95697e.PNG)

This is likely going to confuse a lot of people who expect this functionality to allow one to set an argument to any predefined type within the database.

**Comment by psifertex** [comment]
Can you please try this instead? I don't believe that second example is valid C syntax:
```void ESTROBJ::ptlBaseLineAdjustSet(POINTL* pPOINTL)```

**Comment by tekwizz123** [comment]
@psifertex Shouldn't the two be equivalent considering they are both pointing to the same type definition?

**Comment by tekwizz123** [comment]
@psifertex Also your solution did work. That being said I'm confused why the earlier definition of `struct tagPOINT*` still worked and why when lifting from the PDB the definition was `void  ESTROBJ::ptlBaseLineAdjustSet(struct _POINTL& arg1)` which was still allowed. Would have thought those should have errored out if it was invalid C syntax like you are suggesting? Or am I missing the mark here?

**Comment by psifertex** [comment]
Honestly, I'm not great with type systems, we were doing our weekly bug scrub and others on the team mentioned it as soon as they saw the bug. So take what I'm about to say with a grain of salt because I'm trying to translate what I remember them saying. :-)

The short summary is that a typedef is only useful for creating aliases or other names for types. So you use it when /defining/ a type, but not when you'd want to apply a type to a variable. You'd apply it using the type that was the result of the typedef, or the original type that the typedef created the alias for.

**Comment by tekwizz123** [comment]
@psifertex Thanks for explaining this :) I see where you are coming from from your perspective, however often times I see cases like `typedef _INTERNAL_STRUCT EXTERNAL_REF` in header files and in C code, after which `EXTERNAL_REF` would then be used in PDB files and in headers.

Whilst in theory your approach would make sense, it doesn't take into account that `typedef`'s by their very nature are meant to be used when defining types for variables, at least when it comes to Windows (I don't know if the situation is different for other operating systems so forgive me if this is not the case and I'm misunderstanding things because of that.

Do appreciate you giving me insight into the thought pattern and I can see why you guys might of decided to take this approach originally; just think it doesn't quite work in practice due to the reasons I mentioned above. Another reason I think this doesn't make sense though is that it prohibits naming flexibility, which is primarily why people like Microsoft use `typedef`'s as shown above: to allow naming types with external names vs internal, which are then used when defining new types so as to not require releasing the details of the internal structures.

Sorry if thats a long winded explanation and feel free to ask for clarification if you need any, but hopefully that helps explain my thoughts here a bit more.
