### ISSUE TITLE
`show_plain_text_report()` contents is truncated at `<E`

### ISSUE THREAD

**Issue by melomac** [Vector35/binaryninja-api#1668]
Only in Binary Ninja user interface, CLI / API is as expected. Confirmed in Binary Ninja 1.3-stable and 2.0-dev.

Steps to reproduce:

1. In Binary Ninja console, enter the following command:

```
>>> binaryninja.show_plain_text_report("","ONE<EOTTWO")
```

2. In the new plain text view, read:

```
ONE
```

**Comment by psifertex** [comment]
Thanks for the report, the issue was plaintext content was still being put into an html view inside of <pre> tags so html characters would still be parsed as such. This is resolved in build 2149 which uses text/plain to prevent any parsing.
