### ISSUE TITLE
hlil.dest.value returns <unavailable>

### ISSUE THREAD

**Issue by CunningLogic** [Vector35/binaryninja-api#1670]
mlil.dest.value returns the address of a call, but hlil.dest.value returns <unavailable>

Work around here for me was to use hlil.dest.constant.

Version 2.0.2144-dev (Build ID f704503e)

**Comment by D0ntPanic** [comment]
Caused by #1683

**Comment by D0ntPanic** [comment]
Fixed in build 2242
