### ISSUE TITLE
No Current Way to Seperate Type Library by both Architecture and OS

### ISSUE THREAD

**Issue by tekwizz123** [Vector35/binaryninja-api#1672]
At the moment the type library is mainly contained in the .c files located at `C:\Program Files\Vector35\BinaryNinja\types`, assuming that you installed the software on Windows for all users. The problem is that these files are named on a per OS basis, example `windows.c`, `linux.c`, `macos.c`, `cpp.c`, `python.c`, etc.

This sounds great at first but consider this: a lot of types and structures will change depending on the OS version and the architecture. For example from Windows 7 to Windows 10, a lot of the internal kernel structures changed, and even for mostly static structures, there will be some changes such as pointers getting upgraded from 32 bits to 64 bits.

I would like to propose that the current type system be reconsidered to take this into account, along with issues of being able to reload types as needed, to allow for more flexibility with regards to changes across operating system versions and architectures to ensure that Binary Ninja appropriately handles these changes and can produce appropriate IL representations of the code, particularly for HLIL

**Comment by plafosse** [comment]
the `linux.c` is only the types that are shared between all architectures. There is a `linux_<arch>.c` for each of the supported architectures, which is the only way we disambiguate platforms at the moment.
