### ISSUE TITLE
Font style setting not saved

### ISSUE THREAD

**Issue by melomac** [Vector35/binaryninja-api#1675]
On macOS at least, when using a custom font style, the Font style isn't stored in preferences and doesn't persist.

Steps to reproduce:
- go to Settings
- go to Font Name setting
- press the _Select..._ button
- select a Font name **and** a Font style, ex: Menlo Bold 🤷‍♂️
→ only the Font name is stored

**Comment by jeffli678** [comment]
fixed in dev #2251
