### ISSUE TITLE
File specific view size

### ISSUE THREAD

**Issue by michalmalik** [Vector35/binaryninja-api#1677]
Binary Ninja Version: 2.0.2153-dev Personal, b5661dc1
Platform: Windows 10 Version 1909

When I have multiple files open, I want to have a different size of e.g. the Cross References view for each file. At the moment, when you resize the view in one file tab, it changes for all of the files, which I find quite bothersome.

Would it be possible to have file specific view size? Maybe as a setting?

Thanks!

**Comment by plafosse** [comment]
It's a little hard to know if people will want it the way you describe it or the way it currently exists. We do have plans to implement "workspaces" at some point. I think this kind of feature would work well with workspaces.

**Comment by plafosse** [comment]
This will be fixed by #2217

**Comment by psifertex** [comment]
Complete since dev builds >= 2.4.3051
