### ISSUE TITLE
"show variable types at top of function" has some broken behavior

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#1681]
You can only enable/disable `Show Variables Types` / `At top of Function` in HLIL Linear.

However, the setting changes the display for all other views including assembly.

Also, even when that setting is disabled, other IL views continue to show variables up top. If you enable it, you'll actually get two copies of the list.

**Comment by D0ntPanic** [comment]
Double variable lists are fixed in build 2156. Other workflows will be explored at a later time.

**Comment by psifertex** [comment]
bug resolved some time ago, see #1900 for the feature request
