### ISSUE TITLE
Crash when viewing references on macOS with Windows kernel driver

### ISSUE THREAD

**Issue by iangcarroll** [Vector35/binaryninja-api#1684]
1. Load the attached Windows kernel driver into Binary Ninja (Riot's anti-cheat driver).
2. Click from linear HLIL view of `_start` to `sub_1400117dc` (called inside `_start`).
3. Click on `sub_1404ea813`, called by `sub_1400117dc`, and click the first reference for it in the Code References pane.
4. EXC_BAD_ACCESS (trace included in ZIP)

[Archive.zip](https://github.com/Vector35/binaryninja-api/files/4653657/Archive.zip)

**Comment by iangcarroll** [comment]
(2.0.2158-dev on macOS 10.15.4)

**Comment by psifertex** [comment]
Thanks for the repro. Crashing bugs with repros are usually fixed very quickly and we're in the middle of testing for the stable release for tomorrow so it's good timing, we're working to get this taken care of ASAP.

**Comment by D0ntPanic** [comment]
Will be fixed in 2.0 stable. Note that the navigation will not work as expected due to #1685
