### ISSUE TITLE
HLIL not being explicit about restore from globals at function end

### ISSUE THREAD

**Issue by dfraze** [Vector35/binaryninja-api#1689]
![image](https://user-images.githubusercontent.com/12348497/82486954-a4038280-9aab-11ea-98ba-dd404c64968e.png)
![image](https://user-images.githubusercontent.com/12348497/82486987-b2ea3500-9aab-11ea-8285-2974152f2f8f.png)
[service.zip](https://github.com/Vector35/binaryninja-api/files/4658804/service.zip)

Because this is an interrupt handler, seeing the registers reloaded in important. It's also small, but the HLIL view has no way of showing that $at is saved into 0xa0180000, but loaded from 0xa0180008.

**Comment by dfraze** [comment]
(Load as MIPSEL, base address 0xbfc00000)

**Comment by huntergregal** [comment]
i could not figure out how to add segments after analyzing the ROM on this challenge either. Not related to this issue.. but related to this service..

**Comment by plafosse** [comment]
This may have improved somewhat due to the DCE changes. You can now prevent elimination of variables at least.

**Comment by psifertex** [comment]
<img width="1430" alt="Screen Shot 2021-04-14 at 10 02 41 PM" src="https://user-images.githubusercontent.com/140215/114803252-23a5da00-9d6d-11eb-85b3-01c9e5a68cf8.png">

Solved with the improved DCE.
