### ISSUE TITLE
HLIL MIPSEL calling convention (???) error

### ISSUE THREAD

**Issue by dfraze** [Vector35/binaryninja-api#1690]
![image](https://user-images.githubusercontent.com/12348497/82487353-428fe380-9aac-11ea-850a-47f056e1e0e1.png)
![image](https://user-images.githubusercontent.com/12348497/82487445-58050d80-9aac-11ea-8217-014d34cd8d94.png)
[service.zip](https://github.com/Vector35/binaryninja-api/files/4658823/service.zip)
(load MIPSEL, load at 0xbfc00000. bv.add_user_segment(start=0xa0180000, length=0x10a0, data_offset=0x4fdc, data_length=0x10a0, flags=5)

I don't the the return of fprintf is being used in the call to the next fprintf.

**Comment by plafosse** [comment]
This no longer happens if the fprintf function's type is set correctly
<img width="170" alt="image" src="https://github.com/user-attachments/assets/6bc1b98b-379c-4aac-919a-0fe61ff5587f">
