### ISSUE TITLE
Enable "Make Struct" Key Binding in Linear View

### ISSUE THREAD

**Issue by toolCHAINZ** [Vector35/binaryninja-api#1693]
Graph view has a very useful key binding for automatically creating a structure based on memory accesses. However, the keybinding does not work in linear view.

Now that I'm spending more time in linear view because of HLIL, it would be nice to be able to use this hotkey directly from linear view rather than having to switch to graph and back.

**Comment by ccarpenter04** [comment]
I think this would be an excellent addition as well to keep the keybinds consistent.

**Comment by D0ntPanic** [comment]
Fixed in build 2245
