### ISSUE TITLE
XOR transform behavior differs b/w linear and hex view

### ISSUE THREAD

**Issue by copsNroppers** [Vector35/binaryninja-api#1695]
I noticed that when I highlight a region of bytes in the hex view and run an XOR via right click->Transform->XOR, it works correctly, but when I do the same operation in linear view via Edit->Transform->XOR, it does not work on the same region or range of bytes as expected. This is reproducible in Version 2.0.2165-dev (Build ID 49e50f83) on Linux by opening a new blank file, inserting "FF FF FF FF 00 00 00 00", and running an XOR with key "FF FF FF FF" against the first four bytes. This zeroes all four selected bytes as expected in the hex editor, but in the linear disassembly view, this only zeroes the fourth selected byte. I suspect this issue has something to do with the position of the cursor rather than the highlighted region in the case of linear view.

I did notice that transforms are not available via right click in linear view (hence having to go through edit)--is it intentional to still have this functionality available in linear?

**Comment by D0ntPanic** [comment]
Fixed in build 2249
