### ISSUE TITLE
Add hotkey for individual tag types

### ISSUE THREAD

**Issue by k3an3** [Vector35/binaryninja-api#1699]
It would be nice to have the ability to quickly add a certain type of tag to a selected line. Currently, my workflow is:

1. Use custom keyboard shortcut for "add tag"
2. Click on the tag type I want
3. Click select

When I need to do this many times across a binary, it becomes too much clicking, and I stop bothering to change the tag type at all.

It would be nice to be able to map hotkeys to individual tag types, or at least one default tag type to mark things to check out later.

**Comment by psifertex** [comment]
Thanks, this is something we'll consider for the main product. In the meantime, here's a trivial way to get that exact effect using the Snippets editor: 

1. Install Snippet Editor from the plugin manager
2. Add the following snippet, adjusting as necessary (note that the data field could be an empty string if you didn't want to put anything in):
```
if bv and here:
	counter = len(bv.data_tags)
	tt = bv.tag_types["Crashes"]
	if current_function:
		tag = current_function.create_tag(tt, "Data #%d" % counter)
		current_function.add_user_address_tag(here, tag)
	else:
		tag = bv.create_tag(tt, "Data #%d" % counter)
		bv.add_user_data_tag(here, tag)
```
3. Add whatever hotkey you want, and save.

**Comment by psifertex** [comment]
Have you had a chance to try it out? Did that workflow work for you?

**Comment by k3an3** [comment]
Yes, I just tried it out. That seems to be the exact behavior I am looking for, and will suffice.

**Comment by psifertex** [comment]
Closing this as the existing work-around produces the desired result, we may or may not implement this as a core feature this there are many other similar bits of functionality where a hotkey-bound snippet is probably a reasonable answer.
