### ISSUE TITLE
Manually add cross references.

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#170]
We should provide a way to manually add cross-references to things like indirect calls.

**Comment by rollsafe** [comment]
Basic functionality has been merged into dev. You can access it using the python bindings `func.add_user_xref(source, target)` and `func.remove_user_xref(source, target)`. If you try to add a xref with a source outside the function, it won't do anything. Gui integration inbound as well.

**Comment by rollsafe** [comment]
Working on this now. The api will probably look like `bv.add_user_data_ref` and `bv.remove_user_data_ref`, and `bv.get_data_refs` would return both user and auto references. User data and code references should be serialized to the database.

**Comment by rollsafe** [comment]
This feature was added in build 1705. For manual code refs, you can use `current_function.add_user_code_ref(here, here+4)`, with optional architecture you can specify, For data refs, you can use `bv.add_user_data_ref(here, here+4)`. The functions to remove them are `remove_user_code_ref` and `remove_user_data_ref`. :)
