### ISSUE TITLE
Overridden call type not always consulted when doing dead store elimination for registers

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#1709]
Relevant disassembly:
![image](https://user-images.githubusercontent.com/8716677/82872208-8d17c280-9ee7-11ea-9c99-5793e4473fd4.png)

Notably `x1` is set to `sp + 0x48` at `10b0`, and is the second argument to `printf`. At this point, `printf` type at `10c0` is `uint64_t  printf@2da0(char* arg1, ...)`.

This turns into expected LLIL:
![image](https://user-images.githubusercontent.com/8716677/82872641-2a72f680-9ee8-11ea-8574-9f4f3bb6fb8c.png)

MLIL initially is as expected, as `printf`s type signature is wrong for this call site:
![image](https://user-images.githubusercontent.com/8716677/82872728-47a7c500-9ee8-11ea-9184-74156167c675.png)

Now, while the string in the screenshots is truncated, it has a single positional paramter of `char *` from a `%s`. If I override the call site's type to account for this, the MLIL turns into this:
![image](https://user-images.githubusercontent.com/8716677/82872913-8fc6e780-9ee8-11ea-83f0-99ec7789e9ca.png)

For some reason it is pulling `x1` from the previous call, not the initialization that happens immediately prior.

If I remove the override and globally change `printf`'s call type to `const char *fmt, char *` I get the expected result:
![image](https://user-images.githubusercontent.com/8716677/82873124-e2080880-9ee8-11ea-9e53-61c41fb56fe9.png)

Happy to provide binaries or bndb's if needed.

**Comment by rssor** [comment]
Fixed last week in 2.2.2649-dev.
