### ISSUE TITLE
Add the ability to toggle a function's '__pure' status

### ISSUE THREAD

**Issue by SiD3W4y** [Vector35/binaryninja-api#1712]
I have a weird behavior on a PSP Game (MIPS). A call that is present in the assembly, LLIL and MLIL view is absent from the HLIL view. This doesn't happen with all calls but only those jumping to a stub (trampoline) section. Which is correctly detected as code by binary ninja.

Assembly:
![Assembly view](https://i.ibb.co/j5kq99K/2020-05-26-600x432-scrot.png)

LLIL:
![LLIL view](https://i.ibb.co/7XhwD7n/2020-05-26-481x174-scrot.png)

MLIL:
![MLIL view](https://i.ibb.co/CPL9W5n/2020-05-26-442x131-scrot.png)

HLIL:
![HLIL view](https://i.ibb.co/yFcqpRW/2020-05-26-666x108-scrot.png)

I can share the binary privately if needed.

**Comment by SiD3W4y** [comment]
The issue may be that the stub (import) is defined as a simple return.

![Stub Code](https://i.ibb.co/wKgNbCH/2020-05-26-377x117-scrot.png)

**Comment by plafosse** [comment]
Yup this is a feature not a bug :) pure functions like this can be eliminated safely. Is there a reason that this could be considered unsafe?

**Comment by SiD3W4y** [comment]
In this binary the stubs (like sceIoOpen) are part of the dynamic linking process. At runtime they are patched and replaced by trampolines to other module functions. Here binary ninja is removing all the calls to these imports which is pretty troublesome for reverse-engineering.

Is there a way to prevent the optimization ?

**Comment by rssor** [comment]
A test case binary would be pretty useful here, especially if it’s a result of missing relocations that would give us an opportunity to skip the stub and directly point it towards an extern, since BinaryViews are generally responsible setting up a post-dynamic linker environment to help with analysis for pretty much the reasons seen here.

Could you send an example binary to the support email or to one of us on slack? (@rss or @peter)

I don’t think there’s currently a trivial way to prevent the optimization at the moment, but that’s certainly something worth adding.

**Comment by SiD3W4y** [comment]
Thank you, I sent the binary to @plafosse on Slack.

**Comment by rssor** [comment]
As a temporary workaround, does replacing the nop instruction with a random syscall instruction suppress the behavior?

**Comment by SiD3W4y** [comment]
Yes it does seem to prevent the optimization.

**Comment by plafosse** [comment]
To solve this issue we'll need to expose the ability to change a function's pure status, and perhaps add a setting which will not inline pure functions.

**Comment by w1282** [comment]
Mentioning here for others that run into this issue before it can be toggled on a function-by-function basis, pure call elimination can be disabled across the entire binary by disabling `analysis.hlil.pureCallElimination` in settings

**Comment by CouleeApps** [comment]
This is now done in 3.5.4377-dev via the `Function.is_pure` member or the Pure button in the Edit Function Properties dialog.
