### ISSUE TITLE
Add section name on Linear/Byte view

### ISSUE THREAD

**Issue by niculastefan** [Vector35/binaryninja-api#1713]
It would be great if the "Byte Overview" or "Linear Dissasembly" view would support the option to see the section name as well near the address. Attaching a screenshot as reference. Thanks!

![binja](https://user-images.githubusercontent.com/19197579/82910704-a1090600-9f73-11ea-964f-581e00fb9c8c.png)

**Comment by psifertex** [comment]
Thanks for the mockup.

**Comment by jonpalmisc** [comment]
Fixed by #3128 in builds ≥3435.
