### ISSUE TITLE
HLIL does not invert multiplication in switch statements

### ISSUE THREAD

**Issue by nshp** [Vector35/binaryninja-api#1718]
The thumb2 `tbb` instruction is lifted with a multiplication, and @D0ntPanic said the HLIL passes just don't handle multiplication at the moment, resulting in e.g. `tbb [pc, r0]` becoming:
```
switch (2 * zx.d(*(jump_table_f00 + r0)))
    case 0xe
        ...
    case 0x12
        ...
```

**Comment by D0ntPanic** [comment]
Fixed in build 2298
