### ISSUE TITLE
merge incoming edges in control flow graph(UI)

### ISSUE THREAD

**Issue by yufengzjj** [Vector35/binaryninja-api#1719]
when there is too many incoming edges in one basic block it looks really inconvenient:

<img width="395" alt="9D33D722-D9F8-4249-9D93-3F33E6222534" src="https://user-images.githubusercontent.com/7138035/82987114-99a43400-a029-11ea-973e-388d95906b1b.png">

while IDA merges edges look like:

<img width="229" alt="7D05CA8F-16CA-4117-8EF7-3E3E50A3411F" src="https://user-images.githubusercontent.com/7138035/82987247-cfe1b380-a029-11ea-810a-4b7bc2aa3b4b.png">

**Comment by psifertex** [comment]
This is one specific example of a class of improvements we're tracking under #58 

This is a good specific one though, so while I'm closing it, it will show up as a reference on the other ticket which will track when we next work on improving the graph layout and edge routing, thanks!
