### ISSUE TITLE
Open functions in tabs

### ISSUE THREAD

**Issue by pgoodman** [Vector35/binaryninja-api#172]
I'd like to be able to treat functions as logical documents, and have multiple functions opened in multiple tabs, ideally with the ability to drag tabs in such a way that you can show multiple functions open at one time split into panes on the same screen. If you double click on a function name/address that's already open in a tab, then the active tab should switch to that function's tab. You could be able to Ctrl-click on a function to open in a tab (like in browsers), or right click "open function in new tab", also like browsers.

**Comment by psifertex** [comment]
You can already have multiple tabs open for multiple functions--it's just cumbersome (View/Split to New Tab, then navigate).

The open function in a new tab like a browser is definitely something we've been planning. 

The other suggestion about smart focusing of existing tabs is a really good one though. 

We need better flexibility in terms of UI layout that would probably encompass this and a few other changes, but that will probably come after we fix some of the more pressing core RE functionality.

**Comment by plafosse** [comment]
Closing this as it is document by these issues #225 and #219
