### ISSUE TITLE
Highlight matching parens in HLIL expressions

### ISSUE THREAD

**Issue by nshp** [Vector35/binaryninja-api#1730]
HLIL expressions are complicated enough now that either rainbow parenthesis or highlighting matching pairs on click would be helpful.

**Comment by psifertex** [comment]
Yes, a UI plugin could technically do it. But at this point that's basically true of _any_ UI change if you're willing to write enough code and this deserves to be built-in I think.

**Comment by CouleeApps** [comment]
This is added in 3.5.4291-dev
