### ISSUE TITLE
Type.int(size).with_confidence fails with TypeError

### ISSUE THREAD

**Issue by XMPPwocky** [Vector35/binaryninja-api#1731]
On 2170-dev,

```Type.int(arch.default_int_size).with_confidence(0)```

fails with

```
File "/home/user/binaryninja/plugins/../python/binaryninja/types.py", line 878, in with_confidence
    return Type(handle = core.BNNewTypeReference(self._handle), platform = self._platform, confidence = confidence)
  File "/home/user/binaryninja/plugins/../python/binaryninja/_binaryninjacore.py", line 13305, in BNNewTypeReference
    result = _BNNewTypeReference(*args)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: expected LP_BNType instance instead of LP_BNTypeBuilder
```

This breaks at least one plugin ( https://github.com/whitequark/binja_itanium_cxx_abi ). Looks like recent changes to make type objects immutable are the culprit (and Type.with_confidence needs to be updated to check self._mutable)?

**Comment by psifertex** [comment]
Thanks for finding this and the suggestion. Should be fixed in builds > 2199.
