### ISSUE TITLE
Copy occasionally fails

### ISSUE THREAD

**Issue by CunningLogic** [Vector35/binaryninja-api#1732]
Ubuntu 19.10, happens when copying addres via ctl shit A or right click copy.

Failes ~50% of the time outputs this:

jcase@HackPad:~/VirtualMachines$ binja
QXcbClipboard::setMimeData: Cannot set X11 selection owner
QXcbClipboard::setMimeData: Cannot set X11 selection owner
QXcbClipboard::setMimeData: Cannot set X11 selection owner
QXcbClipboard::setMimeData: Cannot set X11 selection owner
QXcbClipboard::setMimeData: Cannot set X11 selection owner

Similar issues:
https://github.com/qtile/qtile/issues/1542

**Comment by psifertex** [comment]
Just to confirm -- has this issue persisted in the last few days? We've upgraded QT versions and we suspect there's a QT bug that is the root clause so we're hoping the upgrade might have fixed it.

**Comment by psifertex** [comment]
Resolved and also believe new QT should prevent a recurrence. Closing for now.
