### ISSUE TITLE
Symbols view doesn't update when renaming a function with an existing symbol.

### ISSUE THREAD

**Issue by iamausertoo** [Vector35/binaryninja-api#1742]
1. Rename a function with the name of an existing symbol.
2. Select "Yes" when asked if you want to override the existing symbol.
3. The function is renamed, but the function whose symbol was taken is not updated in the symbols view.  Whereas, the linear view correctly reverts to "sub_HEXADDR".

**Comment by plafosse** [comment]
I think this was fixed with the recent support for duplicate symbols
