### ISSUE TITLE
SSL Certificate Verify Failed

### ISSUE THREAD

**Issue by soen-vanned** [Vector35/binaryninja-api#1746]
I'm trying to update BN this morning and am getting the following in my logs:
`<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>`

**Comment by psifertex** [comment]
What OS and what version of python are you using? You can probably work-around it by switching the download provider setting in settings to use QT but I'd be curious what configuration is causing this.

**Comment by soen-vanned** [comment]
I was using Python 2.7.16 on OSX, swapping over to 3.8 solved the issue. I wonder why 2.7 just stopped working? I also swapped between 2 & 3 on Windows & Linux, they seem to not have the same SSL errors...must have been something wrong with my OSX Python 2.7.

**Comment by psifertex** [comment]
Did you by chance happen to brew install a 2.7? That's been known to cause trouble in the past.

**Comment by psifertex** [comment]
In the meantime, I'm going to close this one out since there's not only a workaround but we're moving away from 2.7 and 3.0 is about to be the default and shipped with MacOS.

**Comment by soen-vanned** [comment]
I think it was a brew problem, yeah. Thank's for helping me! :)
