### ISSUE TITLE
Additional Fat Mach-O Arch Support

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#1747]
Re #1654: Some newer cpu subtypes are not supported yet:

- [x] CPU_SUBTYPE_X86_64_H
- [x] Potentially more, see `<mach/machine.h>`

**Comment by bpotchik** [comment]
Fixed in 2.1.2295-dev. There is a new Universal BinaryViewType. New architecture subtypes should generally be handled now without any required changes as long as the base architecture is available.
