### ISSUE TITLE
Function Prototype Correction

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#1748]
From @3pidemix:

I'm noticing several functions in a Thumb2 binary that I'm working with have function prototypes that aren't correct. It's simple enough to change the type of the function accordingly, but this does not change the calling code to reflect the new prototype. In many cases different call sites show different prototypes as well. Here's one example:

```
debounce_rd:
int32_t r0 = [debounce].d
int32_t r2 = [data_20000e54].d
int32_t r0_1 = r0 | r2
int32_t r2_1 = [data_20000e58].d
int32_t r2_2 = r2_1 | r0_1
int32_t r0_2 = [data_20000e5c].d
int32_t r0_3 = r0_2 | r2_2
return r0_3
```

This function clearly takes no arguments, but for its two call sites, we have:
```
r0_2 = debounce_rd(r0_1, r1_4, r2_4, r3_5, __saved_r3)
```
and
```
r0_11, r1_5 = debounce_rd(r0_11, r1_5, r2_4)
```
This is after setting the prototype to int32_t debounce_rd(void). I would expect that explicitly setting this (which does of course trigger an analysis update) would fix the call site as well. As it stands now, it breaks some def-use/use-def analysis that I'm doing, which isn't ideal.

1. Why don't the call sites update?
1. What causes a relatively simple function like this to be mistyped? May be related to #1456 
1. What can I do to fix it? I have yet to find any analysis settings that make a difference.

**Comment by plafosse** [comment]
We believe this was fixed in: 2.3.2711
