### ISSUE TITLE
Auto-analyzed function parameter is missing name (and type?)

### ISSUE THREAD

**Issue by nshp** [Vector35/binaryninja-api#1750]
Repro binary (Thumb2 ELF): http://cyberjes.us/missing-type.o
The third parameter to this function somehow has no name or type?
`current_function.parameter_vars[2].type is None and current_function.parameter_vars[2].name == ''`
The UI shows it as just a plain `int32_t` with no name.

There should also only be 2 parameters here, not sure where 3 and 4 even come from.

**Comment by fuzyll** [comment]
Was passing through while searching for a different issue and thought I'd try to repro.

This still repros on 3.0 stable (open with options and choose Thumb2, then hit 'p' on the second byte in the `repro` section to make the function). There is a slight difference from the above in that `current_function.parameter_vars[2].name` returns `r2` now, but the UI still doesn't show it.

**Comment by CouleeApps** [comment]
Does not repro on 3.6-dev. Closing this for now.
