### ISSUE TITLE
Error initializing database: Data too large

### ISSUE THREAD

**Issue by verylazyguy** [Vector35/binaryninja-api#1752]
After running an analysis plugin and creating hundreds of types, adding user code refs, altering function arguments, etc.  This error occurs and there doesn't seem to be a workaround to save the database. This is an especially big problem when the analysis takes hours to run

![Screen Shot 2020-06-05 at 7 38 29 AM](https://user-images.githubusercontent.com/4371276/83878444-2f1a8480-a70a-11ea-8476-842c1f85926c.png)

**Comment by negasora** [comment]
Fixed in 2.0.2218-dev

**Comment by negasora** [comment]
The issue of snapshots being too large was fixed, but this bug can still be triggered if the analysis cache is too large

**Comment by negasora** [comment]
Fixed in 2.0.2225-dev
