### ISSUE TITLE
Ship Python 3

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#1761]
We currently default to Python 3 where it exists, but we need to ship pre-built Python 3 packages for MacOS and Windows and then all platforms will be Py3.

**Comment by D0ntPanic** [comment]
Python 3.8.3 is now bundled with Binary Ninja on Windows and Mac. On Linux, it now defaults to the system Python 3 interpreter.

Python 2 support for the API has not yet been dropped, but will be deprecated soon. You can select Python 2 from using the Python Interpreter setting.

If you require additional packages for your plugins, it is best to switch Python interpreters in the settings and install the packages into the selected interpreter using a package manager such as pip.

**Comment by D0ntPanic** [comment]
As of build 2214, we now bundle Python 3.8.3 on Windows and Mac. On Linux, we default to the system Python 3. Python 2 support in the API will be deprecated soon, but will continue to work in the near term.

If you need to install additional packages into the bundled Python, it is recommended that you instead install the official Python 3 and switch the Python interpreter in the Binary Ninja settings. This will allow you to install any Python dependencies you need.
