### ISSUE TITLE
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.

### ISSUE THREAD

**Issue by oscper** [Vector35/binaryninja-api#1762]
I am trying to install a program called Binary Ninja which I installed from binary.ninja. However, when I try to run the package, I get the following error:

`qt.qpa.xcb: could not connect to display 127.0.0.1:0.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

Aborted`

I run the following commands but still I get the same problem:
apt-get install qt5-default
ldd /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
sudo apt-get install libxcb-xinerama0

Any ideas as to what could be the problem?

**Comment by jeffli678** [comment]
Hi oscper, I am not entirely sure, but it could be that libqxcb.so is
missing executable permissions. Locate the libqxcb.so in the
binaryninja_installation_path/qt/platforms. Try run `chmod +x libqxcb.so`
and see if that helps.

**Comment by psifertex** [comment]
What distro are you running? You definitely don't want to try installing other QT libs, we should be providing everything you need. Note that workarounds for some unsupported linux distributions are described here: 

https://docs.binary.ninja/guide/troubleshooting.html#platforms

**Comment by psifertex** [comment]
If you're running ubuntu it's possible that the error is actually right and you do just need to reinstall too.

**Comment by oscper** [comment]
Thanks for the reply.
I am running Kali Linux 2019. And running the "chmod +x libqxcb.so" command doesn't help either. As for reinstalling the application, you just run the binary file and it executes it, there is no installation involved.

**Comment by negasora** [comment]
Have you tried the solution given in https://github.com/Vector35/binaryninja-api/discussions/1753

**Comment by psifertex** [comment]
To clarify, I recently tested with kali and it worked out of the box with no tweaks. Make sure you're logging in as the kali user and not root.

**Comment by plafosse** [comment]
We fixed the permissions on the zip package that we distribute, this is no longer an issue.

**Comment by sanjeevmossae** [comment]
> Thanks for the reply. I am running Kali Linux 2019. And running the "chmod +x libqxcb.so" command doesn't help either. As for reinstalling the application, you just run the binary file and it executes it, there is no installation involved.

Hi. Were you able to solve the problem ?

**Comment by psifertex** [comment]
Reinstalling means getting a fresh download link in case a file was corrupted. As long as your suppor is active you can do that with https://binary.ninja/recover/
