### ISSUE TITLE
Improve tooltips for structure members

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#1767]
It would be super useful to see type and offset in a tooltip when mousing over a structure member.

Additionally, it would also be really cool if double clicking on a structure member would navigate to the type/field in the Types view.

**Comment by OvertimeRSB** [comment]
I like that idea quite a bit and it feels like an important detail is missing now that I imagined having one there and... well, it's not...

**Comment by jeffli678** [comment]
the type xref branch will send you to the type view when you double click. It will land on dev before 2.3

**Comment by psifertex** [comment]
Also, probably the same thing for variables would be great. Knowing storage/offset/etc.

**Comment by negasora** [comment]
Added in `3.6.4734-dev`
