### ISSUE TITLE
linear view selection when on a non-full line fails on some selections

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#1768]
It depends on how in-sit the line is, but any partial linear view hex line will not allow for selection of all bytes. 

![screenflow](https://user-images.githubusercontent.com/140215/84713023-0e3b0600-af38-11ea-8d24-ff3a7f4d6a72.gif)

It looks like a display-issue only. Using `here` or `current_selection` will produce the expected values for whatever was clicked or selected.

**Comment by D0ntPanic** [comment]
Fixed in build 2249
