### ISSUE TITLE
more confusing/inconsistant tooltips

### ISSUE THREAD

**Issue by I-am-Batman** [Vector35/binaryninja-api#177]
1) all tooltips for mov instructions of the form `[esp+displacement], imm` in a particular function say "Reads stack frame offset -0x3c from esp". If 0x3c is referring to the displacement from esp, the value is wrong, and it should be a write to that location rather than a read. If I'm misunderstanding the tooltip entirely, the language is ambiguous. The value 0x3c seems related to the size of the stack frame, as if referring to current esp as the value of esp upon function entry minus a displacement. 

![image](https://cloud.githubusercontent.com/assets/9060943/13374740/4e0ef308-dd5b-11e5-9dc4-947947d4aa99.png)

2) similar instructions (same opcode, different operands) in a different function have a completely different tooltip:
![image](https://cloud.githubusercontent.com/assets/9060943/13374848/2940df52-dd5e-11e5-9949-e85a4c765ef5.png)

3) more confusion/inconsistency 

This tooltip makes perfect sense. I would expect the next tooltip to look very similar...
![image](https://cloud.githubusercontent.com/assets/9060943/13374927/3118ce40-dd60-11e5-9813-a1565b05d136.png)

...but instead of being like the last one, it's very confusing. It seems like the words "stack frame offset -0xc" just need to be removed:
![image](https://cloud.githubusercontent.com/assets/9060943/13374934/6b0a8940-dd60-11e5-9047-d042fbb28b4e.png)

**Comment by plafosse** [comment]
Would it be possible for you to share the binary for this? Or would it be possible to post what the LLIL looks like? Those tool tips are generated from the il, so if the IL is messed up that would explain the issue.

**Comment by I-am-Batman** [comment]
Here's the binary. [bufbomb.zip](https://github.com/Vector35/binaryninja-docs/files/155767/bufbomb.zip)

The stack pivot I showed in item 3) above is at 0x8048fdf. The IL looks normal to me. 

It's almost like it's trying to track the value "stack frame offset -0x3c" being moved between registers, starting in esp (once the function prologue is complete), then to eax, then the edx

**Comment by plafosse** [comment]
Since we already have an issue tracking this #123 I'm going to close this one.
