### ISSUE TITLE
terminate called after throwing an instance of 'BinaryNinjaCore::DatabaseException'

### ISSUE THREAD

**Issue by janbbeck** [Vector35/binaryninja-api#1774]
Even with the latest build, I still get an error reminisent of #1496 
```
terminate called after throwing an instance of 'BinaryNinjaCore::DatabaseException'
  what():  Data too large
Aborted (core dumped)
```
to reproduce:
- turn off tailcall options
- analyze executable
- save bndb

I am using linux
The file is too big to post here, Peter has a copy from the Slack chat (ch34.zip). Or let me know where to post it.

**Comment by negasora** [comment]
Fixed in 2.0.2225-dev
