### ISSUE TITLE
Redundant HLIL goto's in graph view

### ISSUE THREAD

**Issue by toshipiazza** [Vector35/binaryninja-api#1777]
In HLIL graph view you can often see basic blocks with only a single goto:

<p align="center">
    <img src="https://user-images.githubusercontent.com/6254422/85084320-f972a280-b1c3-11ea-8388-6954027e5a9f.png"/>
</p>

Although necessary for linear view, this is somewhat distracting in graph view and perhaps should be collapsed.

**Comment by psifertex** [comment]
Unfortunately this is not something we can resolve. This is required because we want to maintain consistency between the AST and Block based HLIL. If you wanted to resolve this it would require a new view.
