### ISSUE TITLE
Strings will not inline in flat MIPS binary

### ISSUE THREAD

**Issue by nshp** [Vector35/binaryninja-api#1779]
Not sure if this is architecture-specific, or if it's because I loaded the thing as a RWX segment, but I cannot get strings to inline. This is a minimal repro bndb: http://cyberjes.us/test.bndb

I used the open-with-options to set the base segment flags to 7 instead of 5 (as in RWX, 0b111, right?)

**Comment by psifertex** [comment]
This is expected behavior for RWX segments. If you create additional sections with read-only or make the specific variables `const` they will inline properly.

**Comment by nshp** [comment]
Note in the bndb the strings _are_ in a ReadOnly section, it's the segment that is RWX. If I carve out more specific segments from the file and make sure the strings are in a read-only segment, they'll inline. I expected the section flags to override the segment flags in this case.

**Comment by psifertex** [comment]
Hmm, that should. Does marking them as `const`?

**Comment by nshp** [comment]
Nope, marking const and reanalyzing doesn't change anything. Tried again with 2243-dev.

**Comment by HeranGa0** [comment]
Fixed in the build #2229
