### ISSUE TITLE
lack of judgement whether c is None in binaryview.get_ascii_string_at()

### ISSUE THREAD

**Issue by wxywang89** [Vector35/binaryninja-api#1782]
In binaryview.get_ascii_string_at(), there is no judgement whether 'c' is None after 'c = br.read8()'. This will make analysis crash in some cases.

Attachment contains the test binary, and crash happens in the code below.

import binaryninja
bv = binaryninja.BinaryViewType.get_view_of_file('curl-7_21_0-aosp-clang-Os-arm')
bv.get_ascii_string_at(0x 25234) // crash!

Thank you.

[curl-7_21_0-aosp-clang-Os-arm.zip](https://github.com/Vector35/binaryninja-api/files/4811749/curl-7_21_0-aosp-clang-Os-arm.zip)

**Comment by psifertex** [comment]
Looks like this is a python exception, not a crash per-se, but something we should still fix, thanks for the report. 

```Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Applications/Binary Ninja-dev.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/binaryview.py", line 4214, in get_ascii_string_at
    while c > 0 and c <= 0x7f:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

**Comment by jeffli678** [comment]
This is already fixed by Heran
