### ISSUE TITLE
Unexpected view jump when selecting bytes

### ISSUE THREAD

**Issue by toolCHAINZ** [Vector35/binaryninja-api#1786]
I have a large binary blob that I want to select a lot of bytes from (on the order of several megabytes). To do this, I would like to:

* Click the start address (or end address)
* Scroll to the end (or start)
* Press <kbd>Shift</kbd>
* Click the appropriate address

However, pressing Shift snaps the view back to the original address I selected. 

If I change the order to the following it works:

* Click the start address (or end address)
* Press <kbd>Shift</kbd>
* Scroll to the end (or start)
* Click the appropriate address

But it's kind of annoying to have to hold <kbd>Shift</kbd> down while I try to find the end of what I'm looking at. It would be nice if pressing shift didn't reset the view.

**Comment by D0ntPanic** [comment]
Fixed in build 2249
