### ISSUE TITLE
SCC does void* math incorrectly.

### ISSUE THREAD

**Issue by toomanybananas** [Vector35/binaryninja-api#1788]
```
int main(void* a1)
{
	void* a = a1;
	a += 4;
	return (int)a;
}
```

When compiling the C program above with SCC, the add in line 3 is generated as `add <whatever>, 0` (instead of `add <whatever>, 4`, which GCC does). I tested this with x86, x64, and arm so I'm assuming this is a problem for all architectures.

**Comment by D0ntPanic** [comment]
Fixed in build 2249
