### ISSUE TITLE
HLIL confusing/incorrect if statement conditions

### ISSUE THREAD

**Issue by 0x1F9F1** [Vector35/binaryninja-api#1789]
Binary Ninja Version: 2.0.2246-dev, c6d9b1cc
Platform: Windows 10 Version 1903

```
call 0x1234
test eax, eax
je .1 

call 0x5678
test eax, eax
je .2

.1:
call 0xDEADBEEF

.2:
ret
```
Becomes:
```
int32_t eax
if (0x1234() != 0)
    eax = 0x5678()
if (0x1234() == 0 || (0x1234() != 0 && eax != 0))
    eax = 0xdeadbeef()
return eax
```

Which is quite confusing, and incorrect as it shows 0x1234 being called 3 times.

**Comment by D0ntPanic** [comment]
The incorrect duplication of calls is fixed in build 2320
