### ISSUE TITLE
Changing return type to float doesn't work properly.

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#1790]
Repro steps:

1. Click the return type hit y
2. type float hit enter
3. repeat steps 1 and 2
4. Hit Ctrl+Z

Steps 2,3 don't change the type. Step 4 (rather hilariously) does change the type.

[floatRepro.bndb.zip](https://github.com/Vector35/binaryninja-api/files/4847952/floatRepro.bndb.zip)

**Comment by jeffli678** [comment]
It seems, what is actually broken is that we cannot change the return type of a function. Regardless of its new return type. 

Also, Ctrl+Z seems not working on my end.

**Comment by plafosse** [comment]
Fixed in 2.1.2450
