### ISSUE TITLE
add UI for parsing source files into the type view

### ISSUE THREAD

**Issue by Invincible-World** [Vector35/binaryninja-api#1796]
Just like IDA pro, you can use the JNI type

**Comment by psifertex** [comment]
You can do that with the following API: https://api.binary.ninja/binaryninja.platform-module.html#binaryninja.platform.Platform.parse_types_from_source_file

That said, we should add a UI element for it to make it easier to find, so I'm editing your title to make this issue now track that.

**Comment by Invincible-World** [comment]
I made a mistake while using it








------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jordan"<notifications@github.com&gt;; 
发送时间: 2020年7月2日(星期四) 凌晨2:19
收件人: "Vector35/binaryninja-api"<binaryninja-api@noreply.github.com&gt;; 
抄送: "四大皆空"<1967064046@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Vector35/binaryninja-api] How to import C header file (#1796)





 
You can do that with the following API: https://api.binary.ninja/binaryninja.platform-module.html#binaryninja.platform.Platform.parse_types_from_source_file
 
That said, we should add a UI element for it to make it easier to find, so I'm editing your title to make this issue now track that.

**Comment by psifertex** [comment]
Can you be more specific? Is it not working for you? How does it fail if not?

**Comment by CouleeApps** [comment]
This was done with the release of 3.3 (Import Header File)
