### ISSUE TITLE
Search cannot be canceled

### ISSUE THREAD

**Issue by nshp** [Vector35/binaryninja-api#1799]
I think I've seen this mentioned before, but didn't find an issue tracking it.

Search, as in Edit>Find / Ctrl+F, has a cancel button which only briefly closes the progress window and does not cancel the search.

**Comment by psifertex** [comment]
There's #1639 but obviously different. I thought there was one too, thanks for filing.

**Comment by D0ntPanic** [comment]
Fixed in build 2255
