### ISSUE TITLE
"Display as" menu displays the wrong values

### ISSUE THREAD

**Issue by nshp** [Vector35/binaryninja-api#1801]
In linear HLIL, the "Display as" context submenu will list options like "Signed Decimal (4294967241)" and "Signed Hexadecimal (0xffffffc9)". This is a 32bit architecture and those are 32bit register values, so those should definitely be 55 and -0x37. The conversion in the disassembly view when I choose one of those options is correct.

Related, I have also recently seen that menu display entirely the wrong values, like showing all 0s when I select a non-0 value, but I don't have an example in front of me at the moment.

**Comment by jeffli678** [comment]
I do not fully understand this; need a discussion on it

**Comment by nshp** [comment]
Fixed with the recent display-as changes (confirmed in 2.1.2403-dev)
