### ISSUE TITLE
Ability to remove old snapshots from BNDB

### ISSUE THREAD

**Issue by ExpHP** [Vector35/binaryninja-api#1802]
Every time I save my databases, they grow bigger; and I'm not saving undo data!

Tested on Version 2.0.2258-dev Personal (Build ID b2474e41).

Here's a minimal reproduction:

* In binary ninja, open `C:\Windows\System32\notepad.exe`.  Wait for analysis to finish.
* File >> Save Clean Analysis Database.  The resulting bndb is 1488 kb.
* Close the tab for `notepad.exe`.
* Open the bndb.
* File >> Save Clean Analysis Database.  The bndb is now 2227 kb.
* Close the tab and open the bndb again.
* File >> Save Clean Analysis Database.  The bndb is now 2297 kb.
* Close the tab and open the bndb again.
* File >> Save Clean Analysis Database.  The bndb is now 2363 kb.
* Close the tab and open the bndb again.
* File >> Save Clean Analysis Database.  The bndb is now 2430 kb.

On stable it's even worse.  I have a database that was growing by 6MB on every save, and is now 1.13 GB large.  Now that I switched to dev, it's growing in much smaller increments (0.3 MB each save), but... I mean, it's still growing instead of shrinking, and I assume most of that 1.13 GB is effectively trash.

**Comment by jeffli678** [comment]
You can use this as a temporary workaround: https://github.com/jeffli678/shrink-binaryninja-db.

Please be advised that this is NOT a Vector35 project. Please use it as your own risk.

**Comment by ExpHP** [comment]
Huh, so from the description there, it sounds almost like this is by design?  Seems kind of odd! 😅 

Sure enough, the tool dropped that 1.133 GB down to 23.818 MB, and nothing seems to have been lost.  (since it was only adding ~6MB on each save, I assume the other 17 MB comes from stuff in the other tables)

**Comment by negasora** [comment]
Clean saves are, as of now, just a way to remove undo data from BNDBs. They still create another snapshot.
The ability to trim a database via the ui/api is on my shorter term to-do list

**Comment by negasora** [comment]
Added to "Save With Options" in 2.1.2266-dev
