### ISSUE TITLE
Conditional branches are lifted into LLIL tailcall

### ISSUE THREAD

**Issue by resrever** [Vector35/binaryninja-api#1803]
Conditional branches have two outgoing edges, and if one of those edges is a function then binja lifts it into a single-edge tailcall.

![image](https://user-images.githubusercontent.com/29237040/87059075-e0637d00-c1d6-11ea-8535-46524e1a4390.png)
![image](https://user-images.githubusercontent.com/29237040/87059133-f07b5c80-c1d6-11ea-8dda-9d42dff7d254.png)

**Comment by resrever** [comment]
Offset 0x8116:
[VGAuthService.zip](https://github.com/Vector35/binaryninja-api/files/4897979/VGAuthService.zip)

**Comment by bpotchik** [comment]
Closed after some discussion. Just needed a second set of eyes.
