### ISSUE TITLE
Add Generators to the API

### ISSUE THREAD

**Issue by KyleMiles** [Vector35/binaryninja-api#1805]
API's such as `bv.functions` and `bv.get_symbols()` return lists, which for large binaries could be undesirable.

From a Python perspective, this would be pretty easy to fix; Using [`bv.get_symbols()`](https://github.com/Vector35/binaryninja-api/blob/8abb6547d7fdb8b4148b60c5427201a664febb89/python/binaryview.py#L3467-L3494) as an example, there simply needs to be `yield` statement added in the for loop, and a `finally` to clean up the core reference.

Since this would break a lot of plugins, this should be added as a separate API which the current ones could wrap.

**Comment by jeffli678** [comment]
We might create a generator that can also be sliced. And if it is being sliced, we print a warning message that this is sub-optimal and in the future it will be disabled.

**Comment by plafosse** [comment]
Done as of 2.4.2969 Though there are some additional pre 3.0 things we'd like to add which will improve utility and backward compatibility with older versions and allow for indexing.
