### ISSUE TITLE
Undoing the addition of comments from a loaded database leaves the comment, instead of removing it

### ISSUE THREAD

**Issue by bpotchik** [Vector35/binaryninja-api#1807]

**Comment by negasora** [comment]
Additionally,
1. comment on the first instruction in a basic block
2. comment on the basic block itself
3. save a database
4. load the database
5. undo twice (this is already broken, as the instruction comment doesn't get undone)
6. redo twice

will result in the first instruction comment being wrong

**Comment by bpotchik** [comment]
The undo code related to comments is using the BinaryView comment API instead of the regular Function comment API. This results in the inability to change/modify a comment once it's saved in the BinaryView.

**Comment by negasora** [comment]
Fixed for comments created in versions >= 2.1.2277-dev
