### ISSUE TITLE
Segfault when loading a DLL: "Failed to import: LONG".

### ISSUE THREAD

**Issue by Rvrzng** [Vector35/binaryninja-api#1814]
Hello,

i have found that with the latest update (**version 2.1.2269-dev Personal**) i can't load a DLL with Binary Ninja on Arch Linux anymore which was possible 1-2 days ago. Every time I try, binary ninja crashes.

The [logfile.txt](https://github.com/Vector35/binaryninja-api/files/4927384/logfile.txt) contains the following error at the end:
> Failed to import: LONG

I also added the [backtrace.txt](https://github.com/Vector35/binaryninja-api/files/4927554/backtrace.txt).

**Comment by psifertex** [comment]
Thanks -- is it all DLLs or just a particular one that's crashing? Any chance you can share the binary?

**Comment by Rvrzng** [comment]
I did a little testing, it seems it affects all x32 DLLs and no specific one. I have also randomly downloaded two dlls for testing.
[Hello World DLLs](https://github.com/carterjones/hello-world-dll/releases)

The x64 DLL works, but with the x32 DLL Binary Ninja crashed again, like all the others I tested.

**Comment by psifertex** [comment]
Thanks. That's very helpful, should be more than enough to fix it.

**Comment by psifertex** [comment]
Hmm, I can't reproduce it on the latest dev with 32bit dlls I'm trying here. Have you by chance created any user-type libraries?

**Comment by psifertex** [comment]
I tried on MacOS and Linux so I don't think there's any platform differences. Wondering about plugins / type libraries. If you just temporarily do:
```
$ mov ~/.binaryninja ~/.binaryninja-old
$ mkdir ~/.binaryninja
$ cp ~/.binaryninja-old/license.dat ~/.binaryninja/
```
and try again, what happens?

**Comment by Rvrzng** [comment]
>Hmm, I can't reproduce it on the latest dev with 32bit dlls I'm trying here. Have you by chance created any user-type libraries?

Nope.

> and try again, what happens?

I tried again after work, same problem. After that I executed the commands as you described above, now I have **version 2.1.2263 Personal** instead of **version 2.1.2269 Personal**, but now all x32 DLLs work again. I'm a bit surprised now, so I guess it was because of the version? But why do I suddenly have version 2.1.2263?

**Comment by Rvrzng** [comment]
Now I changed from release build back to dev build version 2269 and everything seems to work again, just to be on the safe side I tested 2270 and it also works. Really weird. 

Sorry, I think you can close this issue then, still wondering what happened..

**Comment by psifertex** [comment]
Very strange. Maybe a corrupted file during download somehow? I'll close for now, but if it crops up again please let us know!
