### ISSUE TITLE
Remain in the same view after rebasing and splitting to a new tab/window

### ISSUE THREAD

**Issue by jeffli678** [Vector35/binaryninja-api#1816]
We should remain in the same view and on the same address after these operations. 

Currently, we will go to the default view after splitting to a new tab/window. For rebasing, we are pretty close, but if we are on a LLIL view, we will get to the disassembly view.

**Comment by jeffli678** [comment]
Closed in favor of #1954

**Comment by bpotchik** [comment]
Fixed in 2.2.2515-dev. See #2068
