### ISSUE TITLE
Mach-O Objective-C Symbol Support

### ISSUE THREAD

**Issue by fuomag9** [Vector35/binaryninja-api#1817]
Does anyone know if you can get mach-o binaries function names from the binary or eventually import them? Ghidra/hopper/ida have them

**Comment by fuomag9** [comment]
According to Peter on slack this is a bug 
![image](https://user-images.githubusercontent.com/1580624/87669087-a281ce00-c76d-11ea-9516-e0d6bc5eece3.png)

**Comment by jeffli678** [comment]
Yeah I also encounter this from time to time.

**Comment by fuomag9** [comment]
> Yeah I also encounter this from time to time.

My mach-o binaries come from .ipa all the time, I've never had symbol tables parsed in binary ninja unfortunately

**Comment by jeffli678** [comment]
Exactly, ipa files are problematic. I might look into this.

**Comment by bpotchik** [comment]
I just found and fixed a bug related to parsing the dynamic table. Related bug is #1862. Unsure if it fixes the issue encountered here. If you are able to check please report back. Thanks!

The other fix is in 2.1.2319-dev.

**Comment by fuomag9** [comment]
> I just found and fixed a bug related to parsing the dynamic table. Related bug is #1862. Unsure if it fixes the issue encountered here. If you are able to check please report back. Thanks!
> 
> The other fix is in 2.1.2319-dev.

I'm on Version 2.1.2319-dev Personal (Build ID 7d13301) and unfortunately the issue is still present, hopper can correctly display the classes names and functions, meanwhile binary ninja just calls them by their address. :(

**Comment by bpotchik** [comment]
@hubert3 would you happen to have a binary you can share? You can DM me on slack if you like. Thanks!

**Comment by fuomag9** [comment]
Sample binary [here ](https://drive.google.com/file/d/1WDr6j9T4oU5igaDctpuL0AoiFQyuwPME/view?usp=sharing)(The main Zoom binary inside the .ipa is the one to analyze)
I'd have uploaded it here but it's too heavy for github

**Comment by bpotchik** [comment]
This requires some extra objective c analysis which we do not currently have built into the core Mach-O loader. You can potentially use https://github.com/trailofbits/ObjCGraphView to apply the proper analysis in the mean time.

You can track #362, #419, and #420 for native objective c support in the future.
