### ISSUE TITLE
Python console takes some action to sync with binaryview

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#1819]
Version 2.1.2269-dev Personal (Build ID 26eb7189), Windows 10

Repro steps:
- Open a binja python console
- Open a binary, get some address of something in .data, in my case that is 0x403098
- Close the binaryview
- Open the binary again, don't navigate anywhere
- In the console, attempt to navigate via `here = <your address>`, e.g. `here = 0x403098`. You should see the following error:
Address 0x403098 is not valid for the current view
- Hit 'g' and paste your address. The address is clearly valid.
- Now `here = 0x403098` works

```
>>> here = 0x403098
Address 0x403098 is not valid for the current view
>>> here = 0x403098
>>> here
0x403098
```

It seems if you navigate around a bit without going to the address directly it will also cause it to sync up and start working.

**Comment by bpotchik** [comment]
This appears to be fixed. Tested on `2.2.2614-dev`.
