### ISSUE TITLE
Plugin manager does not follow the network proxy set in BinaryNinja Settings

### ISSUE THREAD

**Issue by jeffli678** [Vector35/binaryninja-api#1825]
I verified it directly reaches out to GitHub to fetch plugin status and subsequently download the plugins

**Comment by CouleeApps** [comment]
This may not be possible if we use QWebEngine: https://bugreports.qt.io/browse/QTBUG-66601 The Qt6 views look like they use our custom TextBrowser class which goes through DownloadProvider and follows the proxy setting.

**Comment by CouleeApps** [comment]
Likewise with #2078 this should be fixed by the qt6 transition.
