### ISSUE TITLE
PE incorrect handling of dummy/padding relocation

### ISSUE THREAD

**Issue by 0x1F9F1** [Vector35/binaryninja-api#1826]
Binary Ninja Version: 2.1.2269-dev, 26eb7189
Platform: Windows 10 Version 1903

Not too sure of the specifics, but the dummy/padding relocation seen at the end of some relocation blocks isn't being ignored.

![image](https://user-images.githubusercontent.com/6098371/87844681-73777380-c8b7-11ea-86e9-ca1d46b4f421.png)

```
>>> bv.relocation_ranges_at(0x00658000)
[(6651904, 6651908)]
```

CFF Explorer:
![image](https://user-images.githubusercontent.com/6098371/87844744-4ecfcb80-c8b8-11ea-9561-2657249ad6e2.png)

**Comment by bpotchik** [comment]
Fixed in 2.1.2275-dev.
