### ISSUE TITLE
Allow to select a Range of bytes by specifying the start and size

### ISSUE THREAD

**Issue by jeffli678** [Vector35/binaryninja-api#1827]
In hex view, currently we can only select a range of bytes by mouse dragging. However, it is quite often that we know the start and size of the range. It would be nice if we can make the selection by specifying the range.

**Comment by xusheng6** [comment]
Added via https://github.com/Vector35/binaryninja-api/commit/015314d34d073a8ebbd958edf8150a81381f12c2, should be available in dev 4.1.5260
