### ISSUE TITLE
Double-clicking a comment to edit it

### ISSUE THREAD

**Issue by jeffli678** [Vector35/binaryninja-api#1845]
It is a UI improvement: We should show the editing dialog when a comment is double-clicked.

**Comment by plafosse** [comment]
If there is an address in the comment and the address is double clicked on we should navigate to that address.

**Comment by jeffli678** [comment]
To achieve the goal, we need to tweak the comment annotation generation logic so that addresses are emitted as another token. So we can double-click it to navigate that address

**Comment by jeffli678** [comment]
implemented

**Comment by jeffli678** [comment]
This also addresses https://github.com/Vector35/binaryninja-api/issues/1502
