### ISSUE TITLE
Make the string literals copyable

### ISSUE THREAD

**Issue by jeffli678** [Vector35/binaryninja-api#1846]
Currently, we cannot select (so cannot copy) the inlined string literals, which is sometimes inconvenient. 

As a note, it should copy the complete (long) version of the string if it is too long and we put `...` into the display. 

![Screenshot from 2020-07-22 12-24-00](https://user-images.githubusercontent.com/3380590/88134064-40661480-cc16-11ea-8643-3578a7c6733c.png)

**Comment by jeffli678** [comment]
related to: https://github.com/Vector35/binaryninja-api/issues/1846

**Comment by plafosse** [comment]
Fixed in 3.5.4347
