### ISSUE TITLE
Error when running export_svg.py

### ISSUE THREAD

**Issue by TheHackerDev** [Vector35/binaryninja-api#1853]
I get the following error in my Binary Ninja log when running the `export_svg.py` plugin provided in the `python/examples` folder:

```
Traceback (most recent call last):
  File "C:\Software\Binary Ninja\plugins\..\python\binaryninja\plugin.py", line 172, in _function_action
    action(view_obj, func_obj)
  File "C:\Users\Me\AppData\Roaming\Binary Ninja\plugins\export_svg.py", line 46, in save_svg
    outputfile = outputfile.replace('/', '\\')
TypeError: a bytes-like object is required, not 'str'
```

The error occurs right after I click the `save` button in the Windows Explorer window that pops up when I run the plugin.

Running Windows 10 x64, using Python 3.

**Comment by psifertex** [comment]
Should be resolved whenever the next stable goes out or you can download it manually now: https://github.com/Vector35/binaryninja-api/blob/dev/python/examples/export_svg.py

As an added bonus, it now supports IL forms of graphs. :-) 

Note, that it is also ONLY supports Python3 for now. Slowly starting to remove Py2 compatibility where it hurts testing as was the case with some of the edge-cases around file system operation on windows in particular.
