### ISSUE TITLE
the size of ellipsis (...) is wrongly calculated

### ISSUE THREAD

**Issue by jeffli678** [Vector35/binaryninja-api#1854]
![Screenshot from 2020-07-28 16-08-00](https://user-images.githubusercontent.com/3380590/88642062-934a3b00-d0f2-11ea-9b4e-55acb026a9a3.png)

The ... occupies the size of one char in the display, however, it is actually three bytes wide. So the display gets some problems here.

**Comment by plafosse** [comment]
Related to this bug: #1234

**Comment by negasora** [comment]
Fixed in 2.1.2317-dev
