### ISSUE TITLE
Wrong alignment of disassembly with long instructions

### ISSUE THREAD

**Issue by Tomfox91** [Vector35/binaryninja-api#1855]
Binary Ninja Version: 2.1.2263, 4d2bf25a
Platform: macOS 10.15

When an instruction is longer than 8-9 bytes, this happens (see screenshot). The instruction is visually misaligned with the other instructions (see top and bottom instructions).

<img width="537" alt="image" src="https://user-images.githubusercontent.com/2546080/88654095-2ec8b500-d0cd-11ea-8278-8904f0feba9e.png">

I assume this is due to a ellipsis character `…` being used instead of three dots `...`.

**Comment by jeffli678** [comment]
Thanks for the report! Closing in favor of https://github.com/Vector35/binaryninja-api/issues/1854
