### ISSUE TITLE
A ".var" of an HLIL_VAR object not correct in some cases

### ISSUE THREAD

**Issue by Martyx00** [Vector35/binaryninja-api#1864]
Under unknown specific circumstances the ".var" attribute of the HLIL_VAR object does not map to correct variable as shown below. I would love to provide more details, but I have not found any pattern in why this happens.

<img width="290" alt="image" src="https://user-images.githubusercontent.com/20481897/89156133-79817b80-d56a-11ea-8585-0d171a3452d8.png">

**Comment by plafosse** [comment]
Could you provide a binary which displays this issue?

**Comment by Martyx00** [comment]
Sure, the binary can be found [here](https://drive.google.com/file/d/10tJdwaCPngFnQXyKnCEXxqF3cTaV5JVQ/view?usp=sharing).
This issue occurs in function `_xmlNodeListGetRawString` on the instruction `rax_2, arg3 = _xmlStrncat(_xmlStrcat(rax_6, *(rbx_1 + 0x10), rdx), &var_32, 1)` (7th from the bottom of the function in HLIL).
I have tested this with the latest development build of BinaryNinja (2323).

**Comment by psifertex** [comment]
We believe we've fixed these with the recent HLIL improvements that landed on dev last week. Please let us know if you run into any more instances.
