### ISSUE TITLE
HLIL reference of instance field (&x->y)

### ISSUE THREAD

**Issue by sum-catnip** [Vector35/binaryninja-api#1866]
im seeing a couple of instances where an offset is added to a pointer variable (known type):
`self + 0x378`
the type of self does have a field at offset 0x378 but binary ninja doesnt show it because its not getting dereferenced. the code is getting the address of a field of the instance.

id expect to see something like this: `&self->fieldname`

disassembled it looks like this:
`lea rsi, [rdi+0x378]`

**Comment by plafosse** [comment]
Closing in favor of #1649
