### ISSUE TITLE
Offer a convenient way to set variable names from the API

### ISSUE THREAD

**Issue by jeffli678** [Vector35/binaryninja-api#1871]
Currently, there is no way to easily rename a variable from the Python API. The reason is that symbols are separate from variables. However, it is still worthy to create a helper function to allow a variable to be renamed.

**Comment by xavierholt** [comment]
I second this one - it'd be very nice to have!  Ideally the `name` attribute would be settable like it is for functions, but right now attempts to set it are silently ignored:

```
>>> main
<func: x86_64@0x4012c3>
>>> main.name
'main'
>>> main.name = 'blah'
>>> main.name
'blah'
>>> main.vars[0]
<var char** var_18>
>>> main.vars[0].name
'var_18'
>>> main.vars[0].name = 'bob'
>>> main.vars[0].name
'var_18'
```

**Comment by verylazyguy** [comment]
```main.create_user_var(main.vars[0], main.vars[0].type, 'bob')``` works

**Comment by psifertex** [comment]
A setter would be much better.

**Comment by jeffli678** [comment]
addressed by https://github.com/Vector35/binaryninja-api/pull/1923. Thanks xavierholt!
