### ISSUE TITLE
Saving and reloading a bndb corrupts segment mappings when a user segment precedes an auto segment

### ISSUE THREAD

**Issue by tchebb** [Vector35/binaryninja-api#1872]
Binary Ninja Version: 2.1.2322-dev Personal, 38f36d9a
Platform: Arch Linux

At some point between 1.1.1338-dev and 2.1.2263, Binary Ninja started corrupting databases with a specific segment layout on save, causing them to produce an incorrect map when reloaded. I know the issue happens on save because I can open a database saved with 1.1.1338-dev in 2.1.2263 and not see any corruption until I resave it with 2.1.2263. I have confirmed that this bug is still present in the latest development build 2.1.2322-dev.

Please see my repository [here](https://github.com/tchebb/binaryninja-versionbug), which contains a minimal repro of the bug as well as a README with a full description of when/how it manifests.

**Comment by bpotchik** [comment]
Thanks for reporting. This issue is fixed in 2.1.2394-dev.

Note that rebasing is performed in relation to the lowest addressed auto segment.
