### ISSUE TITLE
UI - blocks in HLIL graph overflow

### ISSUE THREAD

**Issue by enedil** [Vector35/binaryninja-api#1874]
Binary Ninja Version: 2.1.2263 Personal, 4d2bf25a
Platform: Fedora 32 (Workstation Edition)

As in title, HLIL massively overflows:

![Zrzut ekranu z 2020-08-06 22-00-28](https://user-images.githubusercontent.com/5454648/89576991-512aa300-d830-11ea-853b-a22a267ca893.png)

Sample:

Load at address 0x60484, architecture: aarch64, platform linux-aarch64.
[fun.zip](https://github.com/Vector35/binaryninja-api/files/5037718/fun.zip)

**Comment by psifertex** [comment]
This looks to be resolved though it's possible I"m not loading the file correctly so feel free to re-open if that's not the case and provide more explicit information. Here's my open-with options I'm using:
<img width="1046" alt="Screen Shot 2021-04-21 at 2 42 53 PM" src="https://user-images.githubusercontent.com/140215/115604875-dc10d800-a2af-11eb-936f-06f71e80fb46.png">
