### ISSUE TITLE
PE Header Parsing Bug

### ISSUE THREAD

**Issue by MaorNr** [Vector35/binaryninja-api#1875]
I have been analyzing some malware sample and noticed that the disassembly at the **entry point** is not the same across my debugger and binary ninja!

https://ibb.co/TBCyz73

binary ninja read the section data from file offset 0x10 ( file offset) whilst the windows loader starts from file offset 0x0.
Hence I think that problem is that binary ninja ignores the FileAlignment field in the PE header!

link to the sample ( be cautious): https://gofile.io/d/NWHRcD

**Comment by KyleMiles** [comment]
Yeah we're not handling the sections of that binary well at all:
![image](https://user-images.githubusercontent.com/7171118/89715366-475d8880-d973-11ea-92ce-645977c72c54.png)

Though I will say that the disassembly itself isn't the problem, just the entry point identification.

Should change the name of this issue to reflect that.

**Comment by MaorNr** [comment]
> Yeah we're not handling the sections of that binary well at all:
> 
> ![image](https://user-images.githubusercontent.com/7171118/89715366-475d8880-d973-11ea-92ce-645977c72c54.png)
> 
> 
> 
> Though I will say that the disassembly itself isn't the problem, just the entry point identification.
> 
> 
> 
> Should change the name of this issue to reflect that.

The raw pointer of the section is 0x10 and it should be rounded to 0 as the FileAlignment is 0x200.

I will change the title ofcourse.

**Comment by bpotchik** [comment]
Fixed in 2.1.2325-dev.

**Comment by bpotchik** [comment]
Also added a warning about this in 2.1.2326-dev.
