### ISSUE TITLE
Type View enhancements

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#1883]
There are a lot of things that could be done to enhance the current type view. This is an overall issue, concerning a list of items that may need to change to support a better type workflow. We will create individual tickets for some or all of these items as we commit to actually doing them.

- [x] Improve search. "CMD+F" isn't very discoverable, as its unlike the other windows like Strings.
- [x] Add filtering
- [ ] ~Perhaps add a sidebar with just definitions.~
- [x] Collapse definitions into a single line.
- [x] Add visual distinction between, auto and user-defined types.

**Comment by plafosse** [comment]
Side-by-side view of types and code will be part of the 3.0 enhancements #2217

**Comment by negasora** [comment]
finished as of 2.3.2794-dev
