### ISSUE TITLE
Create auto struct

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#1886]
We should create a hotkey "create auto struct"  This would analyze the current function's access pattern for the currently selected pointer and then suggest a structure. It could just pop up a windows with a C definition in it for the user to modify and then accept/reject

**Comment by larkwiot** [comment]
Definitely could use this feature--it's one of the main things I miss coming from Ghidra.

**Comment by ccarpenter04** [comment]
I really miss this feature when using BinaryNinja after using Ghidra for a while.

**Comment by jeffli678** [comment]
Implemented in dev 2.3.2827
