### ISSUE TITLE
Split HLIL Variables

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#1887]
Need the ability to merge and split different HLIL variables, and a UI for doing so.

**Comment by withzombies** [comment]
You can currently name several HLIL variables the same name. This is nice but a proper variable merging hides duplicate assignments, resulting in much cleaner HLIL output.

**Comment by D0ntPanic** [comment]
Added in build 3678

Variables that have multiple definitions can be manually split into multiple variables by clicking on the variable at a definition site and selecting "Split Variable at Definition" from the context menu.

Warning:
Binary Ninja automatically splits all variables that the analysis determines to be safely splittable. Splitting a variable manually can cause IL and decompilation to be incorrect. There are some patterns where variables can be safely split semantically but analysis cannot determine that it is safe, and this feature is provided to allow variable splitting to be performed in these cases.

Manually split variables will initially provide the selected definition as a separate variable, and all other definitions will be automatically resolved into one or more other variables. If some of the definitions should have been included as part of the same variable, use "Merge Variables..." from the context menu after splitting to select which of the other definitions should be merged.
