### ISSUE TITLE
Try to keep the same type of token selected when navigating tokens with up/down 

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#1891]
If a token is selected and 'up' or 'down' is hit it puts the cursor back in lines selection mode. This makes 'down', 'y', 'down', 'y'  workflow much more difficult it becomes 'down', 'right', 'right', 'right', 'y', 'down', 'right', 'right', 'right', 'y'

**Comment by negasora** [comment]
Added in 2.1.2329-dev
