### ISSUE TITLE
Crash if window is closed while popup menu is open

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#19]
_From @D0ntPanic on May 18, 2015 6:33_

1. Open any popup menu (the highlight menu and right click menu in the disassembly were tried)
2. On a Mac, used Cmd+W to close the current window while the popup menu is still showing

This crashes because the parent of the menu is deleted while it is still visible.

_Copied from original issue: Vector35/binaryninja#32_

**Comment by D0ntPanic** [comment]
Fixed in dev
