### ISSUE TITLE
closing the last tab (if it's settings) closes BN instead of going back to the new tab widget

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#1905]
If closing the last tab is a BV, a new tab widget will be created. If the last tab was settings, the entire window will close instead. The behavior should be consistent.

**Comment by bpotchik** [comment]
It's not just settings. There are 5 other tab types that behave exactly the same way.

**Comment by jeffli678** [comment]
fixed in dev 2.1.2389
