### ISSUE TITLE
Recursion depth error when trying to iterate HLIL instructions

### ISSUE THREAD

**Issue by iamausertoo** [Vector35/binaryninja-api#1906]
With the attached binary, in subroutine `sub_11e0`, if you try to iterate over the HLIL instructions:
```
list(current_function.hlil.instructions)
```

you get:
```
RecursionError: maximum recursion depth exceeded while calling a Python object
```

[dict_rfc5777.so.gz](https://github.com/Vector35/binaryninja-api/files/5076856/dict_rfc5777.so.gz)

**Comment by KyleMiles** [comment]
One workaround is to simply
```
import sys
sys.setrecursionlimit(X)
```
Where `X` is something about 1000, which is the default.

**Comment by negasora** [comment]
This doesn't repro as of 2.4.2977-dev (it's probably been fixed for a while)
