### ISSUE TITLE
Notify the user when variable creation fails due to non-coherent pointer values.

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#1907]
Not sure this is the best title. In this screenshot variable creation starts failing at `10077` because binja cannot get a coherent view of `sp` from both incoming branches.

![image](https://user-images.githubusercontent.com/8716677/90303737-64a7c080-de65-11ea-854e-92e9775098ef.png)

I _think_ I'd like to be notified here via log entry or similar, however this is a situation I've only knowingly encountered in my own code. I'm not sure how noisy this would be in your common cases, so if this is a dumb idea feel free to deep six it.

**Comment by rssor** [comment]
Some additional context: in the case where this happens in functions with calls in them, this will actually result in a warning about unresolved stack usage at the top along with a UI for fixing it up manually. In the absence of calls it looks like this warning isn't issued (and even if it was wouldn't be actionable).

**Comment by CouleeApps** [comment]
This has been done in 2.4.2902 with two features:
1. Tags are placed on blocks whose stack pointer has multiple valid values on incoming edges that fail to merge:
![image](https://user-images.githubusercontent.com/711973/125378786-5ad05b00-e35d-11eb-994c-bfeb9aa32805.png)
These can be enabled under the "Unresolved Stack Pointer Value" tag type.

2. In LLIL with `ui.debugMode` enabled, you can enable `Show Stack Pointer Usage` to get annotations on how instructions affect the stack pointer. 
![image](https://user-images.githubusercontent.com/711973/125378917-94a16180-e35d-11eb-99eb-232b8db1fa30.png)

Hopefully the combination of these two features should assist in both manually analyzing binaries with anti-reversing stack manipulation and lifting ILs with complicated stack semantics.
