### ISSUE TITLE
Incomplete register highlighting

### ISSUE THREAD

**Issue by jeffli678** [Vector35/binaryninja-api#1912]
When we select the register rcx, the register ch is not highlighted as a result. Though cl and various other related registers are properly highlighted. 

![Screenshot from 2020-08-18 21-14-18](https://user-images.githubusercontent.com/3380590/90517317-d0589900-e197-11ea-8bdf-520e06604cb5.png)

related to: https://github.com/Vector35/binaryninja-api/issues/321

**Comment by KyleMiles** [comment]
This seems to have been hiding for a while...before 2.0 at least.
Selecting ax properly selects al and ah, but eax and rax don't prop to ah.

**Comment by jeffli678** [comment]
fixed in dev 2.1.2360
