### ISSUE TITLE
SettingsView lacking horizontal scrollbar

### ISSUE THREAD

**Issue by ccarpenter04** [Vector35/binaryninja-api#1915]
Could a horizontal scrollbar please be added to the settings page? I know I can expand it by shrinking the left setting categories view or by expanding BN horizontally but it would be useful for reading the descriptions if there was a scrollbar.

![Display](https://i.gyazo.com/2a702bc18f6f0587497438b132d6668e.png)

**Comment by bpotchik** [comment]
That's strange the text should freely reflow based on the width. Which platform is this?

**Comment by ccarpenter04** [comment]
https://i.gyazo.com/e6ebecf052bfb150f4ec0a7996f2a322.png

If you would prefer to have it flow instead of adding a scrollbar then this example shows several elements that should resize or be moved onto the next line such as the identifier and the combobox.

**Comment by bpotchik** [comment]
Fixed in `2.2.2616-dev`.
