### ISSUE TITLE
The Symbols view needs a horizontal scrollbar

### ISSUE THREAD

**Issue by ccarpenter04** [Vector35/binaryninja-api#1916]
I'm well aware that I could resize the view however that's somewhat inconvenient and when you load a C++ binary with debug symbols included the amount of characters (and thus width) rapidly increases. And then if you factor in parameter arguments, namespaces, etc... well it gets really hard to view the latter end of symbols.

**Comment by negasora** [comment]
Added in 2.1.2346-dev

**Comment by ccarpenter04** [comment]
That was fast, thanks @negasora !
