### ISSUE TITLE
Custom Directed Graph by hiding basic blocks

### ISSUE THREAD

**Issue by afjoseph** [Vector35/binaryninja-api#1919]
Hey. Thanks for the great API!

I'm well-aware that it is possible to highlight specific blocks in graph view. I'm looking for a way to "isolate" specific blocks, possibly in a new view, without destroying the graph view.

The process will be as follows:
* Make a dialog that takes a bunch of addresses (doable now)
* Binja would highlight the blocks (doable now)
* Binja would either "hide" all other blocks for that function, or transfer the highlighted blocks to another view for easier viewing, while retaining the control flow fo the highlighted blocks.

Let me know if this is doable. What I reached so far is to color the other blocks differently, which doesn't look great TBH

**Comment by afjoseph** [comment]
Found exactly what I was looking for here: https://api.binary.ninja/binaryninja.flowgraph-module.html#binaryninja.flowgraph.FlowGraph

Much obliged :D

**Comment by psifertex** [comment]
@afjoseph So I think this is primarily a documentation issue. I've just pushed a change to the pydoc for the basic_block property to clarify that setting the basic_block property of a FlowGraphNode is NOT going to cause that node to necessarily take on the lines of text from the original block to appear in the `flowgraphnode`. This property is used to associate the two which is used for some of the rendering but you'll want to set the `.lines` property based on the lines / tokens from the basic block. Here's an example that will be closer to what you want:

```
graph = FlowGraph()
node_a = FlowGraphNode(graph)
node_a.basic_block = current_function.basic_blocks[0]
node_a.lines = [x[0] for x in current_function.basic_blocks[0]]
node_b = FlowGraphNode(graph)
node_b.basic_block = current_function.basic_blocks[1]
node_b.lines = [x[0] for x in current_function.basic_blocks[1]]
graph.append(node_a)
graph.append(node_b)
node_a.add_outgoing_edge(BranchType.UnconditionalBranch, node_b)
show_graph_report("Custom Graph", graph)
```

**Comment by psifertex** [comment]
So I think the API as shown above is the intended solution -- I don't think we plan to add any native UI workflow to enable this, but you're welcome to build a user-plugin that could do it if you like. Let me know if you have any issues with the sample above! I will note that it currently is very simplified and doesn't use the disassemblysettings to objects to control whether the address or bytes are shown unlike the other views, but it could be expanded to do that if desired.

**Comment by afjoseph** [comment]
Many thanks, @psifertex! This is exactly what I wanted!
