### ISSUE TITLE
thumb2 auto-patching

### ISSUE THREAD

**Issue by pr0me** [Vector35/binaryninja-api#1922]
Hey,

is it correct that the auto-patching API functions (e.g., convert_to_nop, invert_branch) are not implemented for thumb2? 
If so, I guess contributing here is not an option as this architecture plugin seems to be part of the closed source code base, or am I missing something?

Thanks

**Comment by lwerdna** [comment]
They're implemented, but they're in a weird path (in the thumb2_disasm folder):

`ConvertToNop()`:
https://github.com/Vector35/arch-armv7/blob/f99d8b97caf0dc645469ebe4e050448d2b241bc1/thumb2_disasm/arch_thumb2.cpp#L1573

`InvertBranch()`:
https://github.com/Vector35/arch-armv7/blob/f99d8b97caf0dc645469ebe4e050448d2b241bc1/thumb2_disasm/arch_thumb2.cpp#L1607
