### ISSUE TITLE
change out asmx86/nasm for intel XED

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#193]
XED seems to be a much better choice for assembler/disassembler than asm68/nasm. Doing this depends on the license available for XED

**Comment by plafosse** [comment]
Due to licensing constraints we can not use this as a part of the core product.

**Comment by plafosse** [comment]
Reopening this since they now have a reasonable license :)

**Comment by KyleMiles** [comment]
Resolved in 1.1.1287-dev.
