### ISSUE TITLE
PDP-endian (or custom endianness) support in core API

### ISSUE THREAD

**Issue by turbocool3r** [Vector35/binaryninja-api#1934]
There is currently no support for PDP endianness in BN. It would be nice to either have it as a variant of the BNEndianness enum or have a special BNEndianness variant which requires BN to use BNCustomArchitecture callbacks to decode integers. The latter approach could also be applied to floats to support exotic float encodings.

**Comment by plafosse** [comment]
This issue would be solved by #1977
