### ISSUE TITLE
Automatically calculate the size array when defining an array in linear view

### ISSUE THREAD

**Issue by jeffli678** [Vector35/binaryninja-api#1937]
since we know the size of the array element, and the length of the selection, it is possible to calculate the size of the array automatically. The user simply need to select a range of bytes, specify a type like `struct Elf64_Sym[]`, and we will take care of the array size calculation. When the selection size is not precisely divisible by the member size, skip several bytes at the end and give a warning.

Also, there should be the ability to increase/decrease the size of an array easier. Maybe by pressing `+/-` while selecting the integer token that displays the array size.  

P.S.: consider shift + `+/-` to grow/shrink the array backwards

**Comment by jeffli678** [comment]
merged in dev 2.1.2385

**Comment by jeffli678** [comment]
Oh, shift + +/- to grow/shrink the array backwards not implemented yet

**Comment by xusheng6** [comment]
I am gonna close this issue because the title no longer reflects the intention
