### ISSUE TITLE
Incomplete wide strings in .NET binaries

### ISSUE THREAD

**Issue by uafio** [Vector35/binaryninja-api#1945]
Wide strings found in .NET binaries are incomplete. Sometimes the first letter is missing, sometimes the ending letter.

```Python
>>> bv.get_string_at(0x411308).value
'&Cance'
>>> bv.get_string_at(0x411308).raw
b'&\x00C\x00a\x00n\x00c\x00e\x00'
```

**Comment by negasora** [comment]
I'm not seeing this in any binaries I have, can you share one that shows this behavior? You can post it here or message me in slack.

**Comment by negasora** [comment]
Closing since I haven't found a sample of this happening - I'm assuming it was fixed when unicode handling got refactored.
