### ISSUE TITLE
Possible improvements for undo

### ISSUE THREAD

**Issue by jeffli678** [Vector35/binaryninja-api#1946]
1. Disable the undo/redo menu when there is no further actions to undo/redo
2. Give a brief description about the next available undo/redo action
3. Show a list of undo actions, and allow the user to undo several actions at once
~~4. Be able to undo a rebase~~

**Comment by ccarpenter04** [comment]
It's as if you read my mind. #1 and #3 don't matter much to me but #2 would improve my user experience significantly.

**Comment by psifertex** [comment]
For #3, it’s admittedly a tiny bit awkward, but you can get the same info by saving the .bndb and using Tools / Collaboration / Merge Tool to get a list of changes as a workaround.

**Comment by negasora** [comment]
3 will be solved by https://github.com/Vector35/binaryninja-api/issues/2070

1 and 2 are added in `3.1.3552-dev`
