### ISSUE TITLE
Two functions at the same address will only show up in the symbol list once

### ISSUE THREAD

**Issue by jeffli678** [Vector35/binaryninja-api#1948]
We can have two functions starting at the same address as long as they have different architectures. However, only one of them will show up in the symbol list. 

Also, it would be convenient to annotate the functions with an arch different from the default one. So we can disambiguate between them.

**Comment by plafosse** [comment]
This is actually quite difficult to do. If you're in this scenario you can just switch to linear view and scroll around.
