### ISSUE TITLE
Export/Import all/selected types to a .h file

### ISSUE THREAD

**Issue by jeffli678** [Vector35/binaryninja-api#1949]
It would be nice to be able to export all/selected types to a .h file, so I can 1). reuse them in a C program; 2).  reuse it in another .bndb. 

For exporting selected types, do not forget to walk the dependencies and export all related ones.

And for usage case 2) mentioned above, we might develop a better way to reuse types, but it is good for now.

**Comment by CouleeApps** [comment]
"Import all types from an h file" is now implemented and will be in dev 3.2.3853, closing this and making a new issue dedicated to "export all types"
