### ISSUE TITLE
Allow Control Over Reanalysis When Loading from a Database

### ISSUE THREAD

**Issue by verylazyguy** [Vector35/binaryninja-api#1950]
opening large bndb's is rough enough but if you have to reanalyze upon opening it is slow (and usually unnecessary)

If the log would print which version the bndb was saved with or if there were a setting to _not_ reanalyze when opening a bndb it would be a huge QoL improvement

**Comment by bpotchik** [comment]
We now save the product version string (in addition to the build ID) to help identify product versions used to save old BNDBs.

A new setting `analysis.database.suppressReanalysis` has also been added which allows the user to control whether analysis should be performed. Be warned that suppressing analysis may leave stale analysis results, which will update the next time the function is analyzed.

**Comment by bpotchik** [comment]
Fixed in 2.1.2413-dev.
