### ISSUE TITLE
Incorrect function signature for GetModuleFileNameW

### ISSUE THREAD

**Issue by SlidyBat** [Vector35/binaryninja-api#1951]
Binja seems to mistakenly think that `GetModuleFileNameW` has the following signature:
![image](https://user-images.githubusercontent.com/25954912/92248248-bb0b9a80-ef0b-11ea-8eba-3e21c9e866ff.png)

However, the correct signature is `DWORD GetModuleFileNameW(HMODULE hModule, LPWSTR lpFilename, DWORD nSize);` ([docs](https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-getmodulefilenamew)).

I'm guessing this error is from using the signature for [GetModuleFileNameEx](https://docs.microsoft.com/en-us/windows/win32/api/psapi/nf-psapi-getmodulefilenameexw) function, which has that extra `hProcess` param.

**Comment by xusheng6** [comment]
This is already fixed before 3.2.3946-dev (Build ID a5936bc8)

```
>>> bv.import_library_object('GetModuleFileNameW')
<type: immutable:FunctionTypeClass 'uint32_t __stdcall(HINSTANCE hModule, char* lpFilename, uint32_t nSize)'>
```
