### ISSUE TITLE
Cannot select first/last byte leftwards on a line in Linear view

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#1953]
macOS 10.15 / BN 2.1.2371-dev

Attempting to select all bytes in one line of the hex dump of Linear view works only when dragging from left to right. When dragging from right to left, the first and last byte are not included.

1. Open Linear view
2. Scroll to a region of hex dump
3. Click on the last byte (the `00` part not the `.` part)
4. Drag leftwards to the first byte

Dragging right to left:
![image](https://user-images.githubusercontent.com/711973/92285632-c8586300-eed2-11ea-94ee-7da29c22bd04.png)

And for reference, dragging left to right:
![image](https://user-images.githubusercontent.com/711973/92285655-d312f800-eed2-11ea-93f7-2606207dc7bf.png)

**Comment by jeffli678** [comment]
I already submitted PR for it! Hopefully it will be ready soon

**Comment by jeffli678** [comment]
This is fixed in dev 2.1.2424. Along with various improvements to linear view and hex editor
