### ISSUE TITLE
Possible improvements related to "Split to New Tab"

### ISSUE THREAD

**Issue by jeffli678** [Vector35/binaryninja-api#1954]
1. When we press shift and click a view type (e.g., Linear, Hex, etc), split to a new tab and navigate to the selected view
2. For symbols/variables that we can double-click and navigate to, add a context menu that "split to new tab and view"
3. Remain in the same view after rebasing and splitting to a new tab/window #1816

**Comment by bpotchik** [comment]
Fixed in `2.2.2515-dev`. See #2068
