### ISSUE TITLE
Binary ninja fails to parse symbol tables in kotlin/native binary

### ISSUE THREAD

**Issue by fuomag9** [Vector35/binaryninja-api#1956]
Similarly to #1817, Binary ninja fails to parse the symbols table for a kotlin/native binary, meanwhile ida can do that correctly (ghidra too!)

![1](https://user-images.githubusercontent.com/1580624/92314383-430aa680-efd7-11ea-9fb1-aca19b6da873.png)
![2](https://user-images.githubusercontent.com/1580624/92314402-603f7500-efd7-11ea-91a3-9995f7876d80.png)

I've attached the binary
[untitled.zip](https://github.com/Vector35/binaryninja-api/files/5178725/untitled.zip)

**Comment by bpotchik** [comment]
Added some initial COFF symbol table support.

Fixed in 2.1.2384-dev.
