### ISSUE TITLE
Showing Xrefs of a function when it is selected in the symbol list

### ISSUE THREAD

**Issue by jeffli678** [Vector35/binaryninja-api#1958]
This is a tentative feature suggestion: sometimes I wish to see the xrefs to a function without actually showing it. Showing xrefs for functions in the symbol list solves this problem. I am not sure if it will raise any other issues though. Anyway we are already showing xrefs when a function pointer is selected in the graph view.

**Comment by negasora** [comment]
This was implemented a long time ago
