### ISSUE TITLE
Allow scrolling past graph edges

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#196]
It's currently impossible to always center the view of a function given that the rendered space is limited to the edge of the graph nodes. Adding some buffer would allow better usability for people trying to center their view on code near the edges of the overall layout.

**Comment by ColdHeat** [comment]
Perhaps you can allow this in config similar to how Sublime Text does it: 
http://blog.matthewrathbone.com/2012/03/18/scrolling-past-the-end-of-a-file-in-sublime-text-2.html

**Comment by CouleeApps** [comment]
This has been implemented as of 2.3.2704-dev. See the `ui.view.graph.padding` setting in the options to enable it.
