### ISSUE TITLE
Improve python binding init behavior

### ISSUE THREAD

**Issue by rssor** [Vector35/binaryninja-api#1964]
In order to support python plugins when the core is loaded as a library by another application, the python bindings need to know in order to suppress behaviors like creating log listeners by default.

This will allow headless python scripts to use stderr for log messages automatically, as people keep getting tripped up by not realizing it has to be done manually. However, we must *never* do this in any other scenario (running under the UI, part of another headless application, etc.).

**Comment by bpotchik** [comment]
Fixed in 2.1.2396-dev.
