### ISSUE TITLE
Add advanced analysis iterator

### ISSUE THREAD

**Issue by 0x1F9F1** [Vector35/binaryninja-api#1967]
Binary Ninja Version: 2.1.2388-dev, ab5036c7
Platform: Windows 10 Version 1903

When iterating through a list of functions, you often have to wait for each function to be reanalyzed if accessing the analysis/IL, which can be quite slow. Instead it would be great if there was an iterator that requested the analysis data of each function ahead of time, something like:
```py
class FunctionAnalysisIterator:
    def __init__(self, view, preload_limit = 32):
        self.view = view
        self.func_iter = iter(self.view)
        self.func_queue = deque()
        self.preload_limit = preload_limit

    def __iter__(self):
        while True:
            while len(self.func_queue) < self.preload_limit:
                try:
                    self.func_queue.append(AdvancedFunctionAnalysisDataRequestor(next(self.func_iter)))
                except StopIteration:
                    break
            if not self.func_queue:
                break
            func = self.func_queue.popleft()
            yield func.function
```
Depending on the usage i've found this is often 2-3x faster than regular iteration

**Comment by plafosse** [comment]
Thanks for this suggestion, this has been added as of 2.4.3016 With helper methods off of BinaryView `mlil_functions` and `hlil_functions`
