### ISSUE TITLE
BinaryDataNotification.type_defined type parameter bug

### ISSUE THREAD

**Issue by hanssl** [Vector35/binaryninja-api#1968]
The type parameter for the type_defined() notification has extra data when the type is 'bool'.

Normal case:
type, name = bv.parse_type_string("int foo")
registered_name = bv.define_type(Type.generate_auto_type_id("source", name), name, type)
type_defined notification: str(name): 'foo' str(type): 'int32_t'

Failure case:
type, name = bv.parse_type_string("bool foo")
registered_name = bv.define_type(Type.generate_auto_type_id("source", name), name, type)
type_defined notification: str(name): 'foo' str(type): 'bool foo'

The problem is that string of  the type field includes the name when the type is 'bool'. Therefore, any code that makes use of the type field fails because there is extra data.

![Screenshot from 2020-09-10 13-29-02](https://user-images.githubusercontent.com/649957/92791296-caef0880-f369-11ea-98e6-00d218914824.png)

![Screenshot from 2020-09-10 13-31-28](https://user-images.githubusercontent.com/649957/92791497-f70a8980-f369-11ea-9bf8-1f97e12332dc.png)

**Comment by negasora** [comment]
This seems fixed as of 2.4.2977-dev

Script I used to check:
```python
from binaryninja import open_view, Type, BinaryDataNotification

class Notifs(BinaryDataNotification):
    def type_defined(self, view, name, type):
        print(f"view: {view}, name: {name}, type: {type}")

n = Notifs()

with open_view('/bin/true') as bv:
    bv.register_notification(n)
    type, name = bv.parse_type_string("bool foo")
    registered_name = bv.define_type(Type.generate_auto_type_id("source", name), name, type)
```
