### ISSUE TITLE
Search Enhancements

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#1969]
Currently search is very limited as you can only find and find-next. We should add the ability to display all search results in a window.

**Comment by plafosse** [comment]
- [ ] Display persistent search results in separate window
- [ ] Improve speed of text and constant search
- [ ] Allow text search of IL views.
- [ ] Current function search
- [ ] Range based search
- [ ] Regex search (perhaps)
- [ ] Navigate to current active view graph-view/linear-view/LLIL/MLIL/HLIL/etc

**Comment by ccarpenter04** [comment]
Regex support should be considered an essential part of this in my opinion

**Comment by jeffli678** [comment]
Most of the proposed improvement is implemented and merged into dev 2.3.2757.

Some comments on this:

1. We currently do not implement `Improve speed of text and constant search`, but I feel the speed is good enough
2. We do not implement regex search in the core, but the filtering in the UI does support regex filtering. So one can set up a looser search criteria, and then filter it in the search result widget.

When we get back to work on this (along with other improvements to search), a new issue will be created. So closing this.
