### ISSUE TITLE
Searching symbols window causes UI to hang

### ISSUE THREAD

**Issue by KyleMiles** [Vector35/binaryninja-api#1979]
Possibly related to #1876 and #1006.

Searching in the symbols window of a binary with a lot of symbols (I'm working on one with ~100k symbols) causes the entire UI to hang on each keystroke until the list narrows down significantly... To the point where scripting the search in the python console is faster.

Assigning this to @bpotchik since you seem to have handled the previous related bugs.

**Comment by plafosse** [comment]
Fixed in 2.1.2408
