### ISSUE TITLE
Resizing the Python console causes UI to hang

### ISSUE THREAD

**Issue by KyleMiles** [Vector35/binaryninja-api#1980]
Any action that causes the Python console to resize while there's a lot of scroll-back causes the whole UI to hang (and often cause the desired action to fail).

I vote for added a configurable max scroll-back, though it seems like there might be an issue with resizing/rendering off-screen text.

**Comment by negasora** [comment]
9c6be1b6e18c0f8c75e1eb5911ce1206e1a1d7b5 migrates the ScriptingConsoleOutput to QPlainTextEdit instead of QTextEdit - it gives a huge performance improvement for insert/draw so this should be fixed
