### ISSUE TITLE
ARMv7 ldrd lifts to SET_REG_SPLIT

### ISSUE THREAD

**Issue by nshp** [Vector35/binaryninja-api#1983]
GCC seems to really like generating `ldrd`, pairing accesses to sequential 32-bit struct members. Binja lifts `ldrd` as a `LLIL_SET_REG_SPLIT`. With a properly typed struct, the HLIL then looks like: `r2:r3 = some_ptr->:0x30.15.__offset(0x4).q` rather than simply `r2 = some_ptr->field_34; r3 = some_ptr->field_38;`.
Should that just always be lifted to two separate loads?

**Comment by plafosse** [comment]
Is this still the case? If it is can you provide an example?

**Comment by nshp** [comment]
Vector35/arch-armv7#44 includes a fix for this.

**Comment by fuzyll** [comment]
Is this now resolved? The PR referred to 2 years ago has been merged, wondering if maybe we just forgot to close this.

**Comment by fuzyll** [comment]
I'm assuming this is now resolved and closing the issue. Please reopen if I'm mistaken.
