### ISSUE TITLE
Clear the log

### ISSUE THREAD

**Issue by 0xchase** [Vector35/binaryninja-api#1984]
It would be useful to be able to clear the log. My apologies if there is already a way to do this, but I couldn't find it.

**Comment by psifertex** [comment]
Right-click and "clear log"?

**Comment by 0xchase** [comment]
@psifertex No I want to do it from the API

**Comment by psifertex** [comment]
Ahh, you'll want to use the action system for that. It's a bit more complicated than I'd like, but something like:

```
from binaryninjaui import UIActionHandler, DockHandler
def triggerAction():
    UIActionHandler().actionHandlerFromWidget(DockHandler.getActiveDockHandler().parent()).executeAction("Clear Log")

execute_on_main_thread_and_wait(triggerAction)
```
Note that the `execute_on_main_thread_and_wait` is important. You want to execute UI actions on the main thread or risk corruption/crashing.
