### ISSUE TITLE
Show/hide tag types does not work if an instruction has multiple tags

### ISSUE THREAD

**Issue by hanssl** [Vector35/binaryninja-api#1992]
Binary Ninja Version: 2.1.2263, 4d2bf25a
Platform: Ubuntu 20.04.1 LTS

Problem: if an instruction has multiple tags and the user toggles show/hide for one of those tags then the GUI does no update on the instruction with multiple tags.

Steps to reproduce:
1. Add a tag (e.g. Bugs) to an instruction
2. Add another tag (e.g. Crashes) to the same instruction
3. Go to the Tags -> Tag Types view and toggle 'Show' for one of the tags.
4. Observe that the tags rendered with that instruction do not change.

- Other instructions that have either of the tags (and only that tag) do update in step #3.

**Comment by CouleeApps** [comment]
Fixed in 2.3.2820-dev
