### ISSUE TITLE
Type Parser: Cannot declare pointer to array

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#1999]
Pointers to arrays ane of the less common types, but still valid C.

Test cases:
* `bv.parse_types_from_string("char (*test)[10];")` Should return a variable of type `Type.pointer(bv.arch, Type.array(Type.char(), 10))`
* `bv.parse_type_string("char (*)[10]")` Should return type `Type.pointer(bv.arch, Type.array(Type.char(), 10))`

**Comment by plafosse** [comment]
These work as of 2.3.2760
