### ISSUE TITLE
option to display mangled symbols

### ISSUE THREAD

**Issue by crowell** [Vector35/binaryninja-api#200]
it's great that the default is to demangle symbols, but it would be nice to be able to view the mangled C++ symbols also. Some sort of toggle to do that would be appreciated.

**Comment by plafosse** [comment]
Just FYI, you can view mangled C++ names by hovering over them in the functions list window. This isn't ideal since you may want to sort by them or copy them. Some kind of toggle would be good.

**Comment by plafosse** [comment]
Ref #126

**Comment by plafosse** [comment]
Added in 1.1.1827
