### ISSUE TITLE
Integrate debug info into the core

### ISSUE THREAD

**Issue by KyleMiles** [Vector35/binaryninja-api#2000]
Currently DWARF is imported from (an official plugin)[https://github.com/Vector35/dwarf_import], but what we could do a lot more with that debug info if we supported it in the core.

**Comment by psifertex** [comment]
Suggested features:

 - [ ] Automatic parsing without an explicit action
 - [ ] Use it for function creation prior to the normal function identification sweep? 
 - [ ] Others?

**Comment by KyleMiles** [comment]
DebugInfo API added in 2.4.2898-dev.  DWARF port yet to come.
