### ISSUE TITLE
API to modify ILs

### ISSUE THREAD

**Issue by honghai0924** [Vector35/binaryninja-api#2001]
Hi,
I've been working with Binary Ninja ILs. I have to say BNIL is very helpful when analyzing binaries. But sometimes the ILs generated by Binary Ninja are not well optimized.
For example, when I analyze some binary (arch:mips32), the `$v1_2#3` in MLIL 115 is a condition flag in the following picture apparently, and I'd like to replace the condition in MLIL 117 from `$v1_2#3 != 0` to `$v1_1#2 u< 8`.
![image](https://user-images.githubusercontent.com/5728515/94125379-d887b080-fe88-11ea-9216-ef00ad9128fe.png)

So here's the question: If I'd like to write an MLIL optimizer to handle situations like this, is there any API can help?
By the way, thank you for creating this great binary analysis tool. It helps a lot.

**Comment by psifertex** [comment]
Yup, this is an oft requested feature that we are tracking in  #1606.
