### ISSUE TITLE
search performance regression

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#2011]
It looks like we might have experienced a performance regression in the constant search and text search options after the linear view refactor before the 2.0 stable. 

As reported by a customer support chat, version 1.3.2015 exhibits significantly improved search performance. I'll update this when some metrics when I get a chance to generate them as well as potentially a commit-hash.

**Comment by plafosse** [comment]
We haven't heard anyone complaining about this recently. Please comment and we can reopen if you run into something.
