### ISSUE TITLE
PWD not parsed correctly linux setup script

### ISSUE THREAD

**Issue by TheREK3R** [Vector35/binaryninja-api#2014]
Context: I am running debian 10

When placed in the following dir structure

pwd = /home/u/Documents/Binary Ninja/binaryninja

The linux setup script at pwd/scripts/linuxscriptname fails because it can't handle the space in the Binary Ninja dir name.

**Comment by psifertex** [comment]
Thanks for the report. I've updated the script which you can grab here but I'm not going to trigger a dedicated build just for this. You can grab it from git directly and manually check it out in the meantime: https://github.com/Vector35/binaryninja-api/blob/dev/scripts/linux-setup.sh

Whenever the next dev build goes out it'll include this fix.
