### ISSUE TITLE
strings longer than 128 chars not fully searchable in strings list

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#2022]
Using the filtered view to search the strings list for part of a string past 128 chars will fail (but the UI shows the strings in 256 byte chunks)

For example, paste:
```aaaabaaacaaadaaaeaaafaaagaaahaaaiaaajaaakaaalaaamaaanaaaoaaapaaaqaaaraaasaaataaauaaavaaawaaaxaaayaaazaabbaabcaabdaabeaabfaabgaabhaabiaabjaabkaablaabmaabnaaboaabpaabqaabraabsaabtaabuaabvaabwaabxaabyaabzaacbaaccaacdaaceaacfaacgaachaaciaacjaackaaclaacmaacnaacoaacpaacqaacraacsaactaacuaacvaacwaacxaacyaaczaadbaadcaaddaadeaadfaadgaadhaadiaadjaadkaadlaadmaadnaadoaadpaadqaadraadsaadtaaduaadvaadwaadxaadyaadzaaebaaecaaedaaeeaaefaaegaaehaaeiaaejaaekaaelaaemaaenaaeoaaepaaeqaaeraaesaaetaaeuaaevaaewaaexaaeyaaezaafbaafcaaf``` into a new empty file, then try to search for the substring `laab` (which occurs at offset 142) and it will fail.

**Comment by negasora** [comment]
Fixed in 2.2.2583-dev
