### ISSUE TITLE
MIPS branch delay bug

### ISSUE THREAD

**Issue by evanpjensen** [Vector35/binaryninja-api#203]
If the target of a branch is the next instruction the disassembler displays the next instruction branching to itself and halts disassembly. 

![mips_bug](https://cloud.githubusercontent.com/assets/2665132/13964207/024d2e48-f03f-11e5-95a4-859459fecdd1.PNG)
[branch_delay_slot_bug_mips32.bin.zip](https://github.com/Vector35/binaryninja-docs/files/184770/branch_delay_slot_bug_mips32.bin.zip)

**Comment by rssor** [comment]
Fixed in build 1.1.1169-dev.
