### ISSUE TITLE
Handle calling conventions that return values on the stack

### ISSUE THREAD

**Issue by multun** [Vector35/binaryninja-api#2032]
The Golang calling convention stores all return values on the stack, and it doesn't seem like having no register for returning values is allowed:
```
  File "/nix/store/s4ic9x82sajnk6z45s45hg6zr829ly5k-binaryninja-dev-2.1.2403-dev/opt/binaryninja-dev/plugins/../python/binaryninja/callingconvention.py", line 273, in _get_int_return_reg
    return self.arch.regs[self.__class__.int_return_reg].index
```

**Comment by psifertex** [comment]
https://go.googlesource.com/go/+/refs/heads/dev.regabi/src/cmd/compile/internal-abi.md

**Comment by plafosse** [comment]
Closing in favor of this: https://github.com/Vector35/binaryninja-api/issues/3340
