### ISSUE TITLE
Some plugin menu ui options are unresponsive

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#2037]
2480-dev Personal Windows 10

Some work great, note that the menu option is highlighted:

![image](https://user-images.githubusercontent.com/8716677/96352938-7c294280-107c-11eb-9aa1-54113900597e.png)

![image](https://user-images.githubusercontent.com/8716677/96352948-8e0ae580-107c-11eb-872b-dad84287db88.png)

Others do not work (the mouse is removed from the screen shot, but in all instances its in the spot which should cause the menu option to be selected):

![image](https://user-images.githubusercontent.com/8716677/96352959-a549d300-107c-11eb-8de6-51a1c2c96faa.png)

![image](https://user-images.githubusercontent.com/8716677/96352973-c7435580-107c-11eb-9be6-28b21b073bb5.png)

![image](https://user-images.githubusercontent.com/8716677/96352976-cf02fa00-107c-11eb-83f1-a12ebf959467.png)

In all cases, clicking on these menu entries does nothing, however I can still access their functionality via the command palette as a workaround.

**Comment by yrp604** [comment]
I am an idiot, I didn't have a selected binary view. Sorry -_-

**Comment by psifertex** [comment]
It's fine, makes our closed bug ratio better. 🤪
