### ISSUE TITLE
Default window size is too small for Plugin Manager

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#2049]
The default window size for binja is 800x600, which is apparently small enough that the Plugin Manager cannot fit both its sidebar and content panels. Trying to resize the sidebar will cause the split view to glitch back and forth since neither view has enough space.

Looks like it needs about 820px horizontal for everything to fit.

**Comment by plafosse** [comment]
Fixed in 2.3 dev
