### ISSUE TITLE
Maintain Select Focus Across Views

### ISSUE THREAD

**Issue by utkonos** [Vector35/binaryninja-api#2054]
If a location has been selected in one view and the user changes views, the new view should be centered on the same selected location.

Example of ideal behavior:

Select bytes from an opcode in the Disassembly Graph View.
![image](https://user-images.githubusercontent.com/2775739/96911911-84fc8880-146f-11eb-80eb-6fc6cb0c9f60.png)

When switching to the Linear Disassembly view, those same bytes should be highlighted and the new view should be centered on those bytes. Same behavior should occur with the Hex Editor view.

As it is now, the user must remember to copy the address of the selection, then use the goto address feature ("G") after switching over to the new view.

**Comment by psifertex** [comment]
So if you're using the latest stable or latest dev, the view /should/ remain centered. Between linear view and graph view selections should be maintained (if you're switching via `space` this should already work).

The current bugs are:
 - switching via the bottom-right view switch does not maintain selection
- switching to hex view doesn't sync to the same address/selection at all

**Comment by bpotchik** [comment]
Fixed in `2.2.2614-dev`.
