### ISSUE TITLE
Back button on 5-button Mouse Broken for Types View

### ISSUE THREAD

**Issue by zackorndorff** [Vector35/binaryninja-api#2064]
For navigating back/forward, I use the back/forward buttons on my 5-button mouse. (They work more places than you'd think)

They work great in most of Binary Ninja, however, to back out of the Types view, it requires me to double tap the back button, rather than just clicking it as in everywhere else, which is a bit jarring when I want to pop over and look at a struct definition.

I know this is a bit of an esoteric feature, but I use it a lot.

This repros on what was the latest dev at the start of the weekend, v2.2.2489-dev (Build ID ed1c5c3f). Let me know if you need anything else!

**Comment by KyleMiles** [comment]
Honestly surprised this isn't a duplicate; #337, #828, and #1988 are all tangentially related.

This isn't just a mouse input error; the back button and escape both don't well for changing views either in the case of: open a new binary, change the view, and then hitting any form of "back" doesn't work.

To get the behavior described above by @zackorndorff (the double click thing) you need to navigate away from the entrypoint...but then hitting escape/the back button brings you to the entrypoint, not where you were.  Double clicking back on the mouse isn't reliable, whereas escape/the back button seems to be more so.

**Comment by bpotchik** [comment]
The original title was actually perfect, and points to the exact bug.

**Comment by bpotchik** [comment]
Fixed in `2.2.2615-dev`.

**Comment by zackorndorff** [comment]
Just tested, I can confirm it's fixed, thanks Brian!

**Comment by bpotchik** [comment]
Excellent! Sorry about the delay in getting this fixed 😅
