### ISSUE TITLE
patching in linear view with "never branch" (or NOP) patches the wrong location/number of bytes

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#2065]
Note that as a temporary work-around, simply switching to graph-view at the same location will work.

Before and after.

<img width="752" alt="Screen Shot 2020-10-26 at 3 56 54 PM" src="https://user-images.githubusercontent.com/140215/97221964-015ed680-17a4-11eb-86ab-3ecbeae79ff2.png">
<img width="752" alt="Screen Shot 2020-10-26 at 3 57 01 PM" src="https://user-images.githubusercontent.com/140215/97221975-04f25d80-17a4-11eb-833e-e453393621e7.png">

**Comment by jeffli678** [comment]
fixed in dev 2.2.2497
