### ISSUE TITLE
Add Keybindings support for Patch->NOP and Patch->Never Branch on the same shortcut

### ISSUE THREAD

**Issue by themrrobert** [Vector35/binaryninja-api#2067]
Can we please add support for these 2 functions to be bound on the same shortcut?

I like Ctrl+Q, but unfortunately, I can't bind both to the same shortcut, even though (as far as a I can tell) there's never a time when both Patch->NOP and Patch->Never Branch are available, so the shortcut shouldn't be ambiguous.

If I'm just doing it wrong, that would be nice to know, too haha :)

Thanks guys!

**Comment by psifertex** [comment]
This is resolved on builds >=2500 or >=2501, I forget which. Thanks Glenn!
