### ISSUE TITLE
Improved View Location Preservation When Duplicating Existing Views in the UI (Split to New Tab/Window, Rebasing, etc.)

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#2068]
Windows 10 2491-dev Personal

This is a minor UX enhancement.

Right now, split to new tab:
- Opens a new tab focused on _start
- Focuses on that new tab
- Your previous tab is moved one to the right of the new, _start focused tab

This is could be better in two ways:
- the new tab should have the same view as the tab youre splitting, essentially I should get a copy of my current view. E.g. if I split a types window, I should get a second types tab, not _start
- that new tab should _not_ be in focus, so I retain my navigation history in the current focused view

**Comment by bpotchik** [comment]
Fixed in `2.2.2515-dev`.
