### ISSUE TITLE
allow user-defined custom themes

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#207]
What it says on the label. Likely will be implemented following #126.

**Comment by plafosse** [comment]
Added in version 1.1.1235. Theme files are json files stored in the <userDirectory>/themes/. Examples of which can be found here: https://github.com/Vector35/binaryninja-api/tree/dev/themes. Themes files can be refreshed by pressing `Ctrl/Cmd+Shift+r`

This is currently only the code for parsing, refreshing, and serializing theme files. Future
