### ISSUE TITLE
"Edit Function" UI

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#2071]
Have a dialog (or dockwidget) that can edit all the various properties of a Function. Currently there are a bunch of attributes that can only be accessed through python, eg clobbered registers, and without a full read of the documentation you could easily never know about these attributes.

I mocked up a super basic ui about this a few weeks ago: https://github.com/CouleeApps/bn_function_view

**Comment by CouleeApps** [comment]
Reference of the various properties to show: https://github.com/CouleeApps/bn_function_view/blob/master/__init__.py#L14

**Comment by jonpalmisc** [comment]
Now available in 2.3.2810.
