### ISSUE TITLE
API enhancement: function iterators, block interators, etc

### ISSUE THREAD

**Issue by withzombies** [Vector35/binaryninja-api#208]
I'd like to be able to do this:
```
for block in func:
    for insn in block:
        print insn
```
It'd also be convenient if I could do this:
```
for block in func:
   for il_block in block.il_blocks:
       for llil_insn in il_block:
             print llil_insn
```
and this:
```
for il_block in func.low_level_il_basic_blocks:
    for llil_insn in il_block:
        print llil_insn
```

Additionally, it'd be nice if I could query the previous and subsequent instruction addresses, something like:
```
func.get_instructions_before(addr)
func.get_instructions_after(addr)
func.get_llil_instrucitons_before(addr)
func.get_llil_instructions_after(addr)
```
and BasicBlock variants:
```
block.get_instructions_before(addr)
block.get_instructions_after(addr)
block.get_llil_instrucitons_before(addr)
block.get_llil_instructions_after(addr)
```
Each would return a list of previous instructions.

**Comment by plafosse** [comment]
Is this not acceptable for your third request?
```>>> for func in bv.functions:
...  for il in func.low_level_il:
...   print il```

**Comment by withzombies** [comment]
No, blocks intrinsically describe control flow, a stream of IL instructions has to be further parsed to determine control flow.

Those first few requests are all enhancements that correlate blocks more directly and explicitly to instructions (or llil instructions).

**Comment by plafosse** [comment]
These are covered by your pull request correct?

**Comment by withzombies** [comment]
Yes
