### ISSUE TITLE
IL does not support certain Intel SIMD and SSE instructions

### ISSUE THREAD

**Issue by soen-vanned** [Vector35/binaryninja-api#209]
![assembly](https://cloud.githubusercontent.com/assets/1918848/14150616/e44ead24-f677-11e5-9e3b-787954af4b3e.png)
![il_view](https://cloud.githubusercontent.com/assets/1918848/14150615/e44c4dd6-f677-11e5-902f-b3608a57afbc.png)

**Comment by KyleMiles** [comment]
Closing in favor of #1362.
