### ISSUE TITLE
Python Autocomplete is Slow in Large Files

### ISSUE THREAD

**Issue by toolCHAINZ** [Vector35/binaryninja-api#2090]
# Steps

Get or make a large file (e.g. `dd if=/dev/zero bs=1000000 count=500 of=test.bin`).

Open the file in Binja. Open the python console and type `bv.` followed by a <kdb>Tab</kbd> to trigger autocompletion. The UI will freeze for several seconds, until the autocomplete prompt appears.

This gets noticeably slower on very large files (> 1Gb).

**Comment by psifertex** [comment]
Is some sort of analysis still running? I'm not able to reproduce this locally with either a commercial build or personal build on a few different builds I tried.

Which version are you on?

**Comment by toolCHAINZ** [comment]
Nope, no analysis running.

I'm running commercial, 2.2.2487 on macOS

**Comment by psifertex** [comment]
Just tried that exact setup on the exact file using `dd` you suggested above and can't reproduce any issues. Can you make sure you don't have any plugins enabled that might be causing the behavior? I'm wondering if maybe an over-zealous python BinaryView is being loaded which is slowing things up.

Also, I tried both opening in mapped view and raw view (can just switch the tab in open-with-options when it comes up) and that didn't have any effect. I'm assuming you're not making any changes there?

**Comment by toolCHAINZ** [comment]
Plugins seems pretty plausible. I took a sample in macOS and in the main thread I see:
* BNScriptingInstanceCompleteInput
  * ....... BNGetBinaryViewtypesForData
    * ......... python calling malloc a lot

I'll try disabling all my view plugins and see if that fixes it, thanks!

And correct, I'm just opening as raw.

**Comment by toolCHAINZ** [comment]
Ok, I disabled all plugins except for a custom python architecture (which doesn't define any views and I'm not using in this image). The behavior is a bit different now. For the following anecdotes I'm using a 1.2G raw view.

The *first* time I autocomplete, it takes a few seconds to pop up (during which time the UI is frozen).
On subsequent autocompletes it seems to keep slowing down. I ran several trials (autocomplete on `bv`, back to back), and timed out how long it took for the menu to appear and the UI to unfreeze. These are rough times captured on my phone's stopwatch.

| Time to Unfreeze     | 
| ----------- | 
| 5.92s     | 
| 9.68s     | 
| 14.75s     | 
| 23.16s     | 
| 38.95s |
| 54.72s |
| 54.25s |

Took a sample during one of these and I no longer see `BNGetBianryViewTypesForData`, so there definitely was something going on with a plugin like you suggested, but I feel like there's still something weird happening. Now the time is spent in a "wider" tree of python eval calls.

**Comment by 0x1F9F1** [comment]
Seems like the autocompleter evaluates every `@property` when querying a type https://github.com/Vector35/binaryninja-api/blob/dev/python/bncompleter.py#L202. Perhaps `inspect.getattr_static` can be used to avoid that now that Python 2 isn't supported?
```
>>> getattr(bv, 'available_view_types')
[<view type: 'Raw'>, <view type: 'PE'>]
>>> inspect.getattr_static(bv, 'available_view_types')
<property object at 0x00000236B93FA6D8>
```

**Comment by psifertex** [comment]
@toolCHAINZ Can you test that change locally in the bncompleter.py and see if it fixes your issue? It's definitely not a bad change either way.

**Comment by psifertex** [comment]
I just thought of one other potential difference -- what version of python are you using? I'm using a homebrew 3.8.5 currently.

**Comment by toolCHAINZ** [comment]
Yeah, I'll try that out tonight or tomorrow and let you know.

I am using the same python.

**Comment by 0x1F9F1** [comment]
FWIW I could repro this using the https://github.com/toolCHAINZ/hexfiles plugin, since all of those views try and read the whole BinaryView and decode it to utf8 in is_valid_for_data. Using getattr_static fixed the autocomplete perf for that.

**Comment by toolCHAINZ** [comment]
@0x1F9F1 out of curiosity, do you see the incrementally slower behavior without `hexfiles` installed or is that still just me? Agreed, `hexfiles` was the likely culprit for the View stuff, haha

**Comment by psifertex** [comment]
I've pushed that to API, not sure when the next dev will go out, but this is a worthwhile change regardless. If you confirm that change fixes your generic slowdown @toolCHAINZ, please close the issue.

Thanks @0x1F9F1 for the suggestion!

**Comment by toolCHAINZ** [comment]
Tried this in 2513-dev and it is indeed fixed!
