### ISSUE TITLE
incorrect address calculation in PDB parsing

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#2095]
Some of the PDB parsing is producing an incorrect address resulting in many errors like: 

![image](https://user-images.githubusercontent.com/140215/98166801-fdbf0400-1eb5-11eb-911a-0e48b5317660.png)

**Comment by CouleeApps** [comment]
Related: #1660

**Comment by plafosse** [comment]
Fixed in 2.2.2517
