### ISSUE TITLE
PDBs not overwriting function recognizer functions

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#2096]
Functions that begin with `j_` are named during auto analysis when they are simple jump wrappers around other functions. Currently the PDB parser is not checking whether existing symbols are AUTO type or not resulting in these functions not being properly renamed when the PDB information is loaded. 

![image](https://user-images.githubusercontent.com/140215/98166917-365edd80-1eb6-11eb-8d71-a651668c7166.png)

For a reproduction, see attached sample at offset 0x140004c0a after loading the PDB.

[sample.zip](https://github.com/Vector35/binaryninja-api/files/5490463/sample.zip)

**Comment by plafosse** [comment]
Fixed 2.2.2517
