### ISSUE TITLE
Incorrect types after applying PDB

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#2097]
Unsure whether these two issues are related or not, might need to split them after further investigation, but the following symbols/types are incorrect after applying the PDBs.

In the sample attached to #2096 , at offset 0x1400fd913, `memcpy` has no arguments.

In 
[32bit-sample-with-pdb.zip](https://github.com/Vector35/binaryninja-api/files/5490478/32bit-sample-with-pdb.zip)
at offset, 0x4f8679, the function is named `new[]` in Stable 2263, but `delete[]` in `2487`.

**Comment by plafosse** [comment]
Fixed in 2.2.2517
