### ISSUE TITLE
Navigation Is Broken

### ISSUE THREAD

**Issue by cnSchwarzer** [Vector35/binaryninja-api#2100]
Binary Ninja Version: 2.2.2487 Personal, e0eb0a77
Platform: Windows 10 Version 2004

1.Click on the symbol i want to jump to
![image](https://user-images.githubusercontent.com/29846655/98334368-a6e43680-203d-11eb-9970-76b5d0e134db.png)
![image](https://user-images.githubusercontent.com/29846655/98334410-bf545100-203d-11eb-91c2-8d9245c5583e.png)

2.Use 'Navigate Back' feature of the Binary Ninja
![image](https://user-images.githubusercontent.com/29846655/98334433-cbd8a980-203d-11eb-93df-7dc4655dbb35.png)

It seems moved to a correct position, but the following function is not correct, which means it is not navigated to where i came from.

**Comment by cnSchwarzer** [comment]
What's more, the main function is manually created by myself, meanwhile the functions created by the analyzer seems to work just fine, only user created has this problem.

**Comment by plafosse** [comment]
Any chance you can share this binary?

**Comment by bpotchik** [comment]
This should be fixed in `2.2.2614-dev`.
