### ISSUE TITLE
HTTPS Proxy won't work

### ISSUE THREAD

**Issue by cnSchwarzer** [Vector35/binaryninja-api#2101]
Binary Ninja Version: 2.2.2513-dev Personal, bd410b74
Platform: Windows 10 Version 2004

1. Open Settings
2. Search Proxy
3. Set HTTPS Proxy to https://127.0.0.1:10809 (In my case)
4. Restart BN
5. Pop this error.

Error fetching version list: [4] A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision. (Unsupported proxy 'https://127.0.0.1:10809', libcurl is built without the HTTPS-proxy support.)

**Comment by psifertex** [comment]
What is your download provider setting currently set to? Quickest work around is probably to try a different one of those.

**Comment by jeffli678** [comment]
Just a quick verification that you are actually running a https proxy on localhost. Since most likely people would run a plain http proxy on the localhost

**Comment by cnSchwarzer** [comment]
> Just a quick verification that you are actually running a https proxy on localhost. Since most likely people would run a plain http proxy on the localhost

> What is your download provider setting currently set to? Quickest work around is probably to try a different one of those.

Yes, i am running a https proxy. Simply change the setting to 'http://127.0.0.1:10809' will work

**Comment by negasora** [comment]
The `curl` rust crate does not support https proxies yet. The workaround for this is selecting a download provider other than `CoreDownloadProvider` in settings. Closing since there's an easy workaround and it's a missing feature in a library.
