### ISSUE TITLE
Create index/cross reference for constant values

### ISSUE THREAD

**Issue by jeffli678** [Vector35/binaryninja-api#2104]
The motivation is certain magic constant values are indicators of the crypto algorithms used. If we can find them easily, then we can identify crypto functions faster. Although we can search for it, it is more convenient if we can directly emit a list of values (along with its address) that is worth checking out. We also need a UI to present the list to the user.

Another use case is to find access to a particular member within a struct. 

We do need a way to efficiently store the index/mapping to make it possible

**Comment by plafosse** [comment]
There are a lot of issues that would need to be overcome to index these, this is something we're unlikely to ever get around to.
