### ISSUE TITLE
Feature request: read-only mode

### ISSUE THREAD

**Issue by jeffli678** [Vector35/binaryninja-api#2107]
Be able to mark the BianryView as read-only. Also, there should be a way to toggle between read-only/writable mode. Probably a lock (or something) in the UI

**Comment by bpotchik** [comment]
Similar to #1449 

An initial version of this is available in `2.2.2627-dev`. It is called 'Write Traction' and the goal is to prevent accidental modifications to a binary via cut/paste actions in views, and accidental modification in hexview. There is a corresponding action in the command palette which allows one to toggle the lock as well as an interactive lock glyph in the lower right status bar.

**Comment by bpotchik** [comment]
Latest version of this feature is in `2.2.2629-dev`. It's now called 'File Contents Write Lock'.
