### ISSUE TITLE
Better support for array indexing in MLIL and HLIL

### ISSUE THREAD

**Issue by jeffli678** [Vector35/binaryninja-api#2111]
![image4](https://user-images.githubusercontent.com/3380590/98432390-a0ff5b80-20f8-11eb-891d-7ebd0761114e.png)

We already do a decent job for array indexing when the index is a constant. However, we need to identify accesses when the index is variable.

**Comment by jeffli678** [comment]
potentially related to: https://github.com/Vector35/binaryninja-api/issues/1888

**Comment by plafosse** [comment]
Closing in favor of #2161
