### ISSUE TITLE
Collision resolution in Re(n)ame Symbol dialog

### ISSUE THREAD

**Issue by amtal** [Vector35/binaryninja-api#2116]
Currently, manually adding a duplicate symbol name follows `bv.define_user_symbol` behavior plus a Yes/No dialog pop-up to confirm the overwrite.

This adds keystrokes to some manual re-naming workflows, such as:
- Renaming the Nth instance of slightly-differently-vectorized memcpy/memclr while exploring around in an embedded image.
- Marking a bunch of related library functions stuff like `web_handler??__crypto?__???` in the hopes that you'll see them used again in a different context where they make more sense.
- Stumbling across an un-referenced table of function pointers and naming them something related with a number suffix, until you can figure out what calls it.

None of these workflows scale, but they'll always crop up during initial analysis. The obvious solution is automatically adding an incrementing suffix, but since these are often very preliminary names something section and address-based might be better. 

Integrating the names into the initial auto-complete dialog rather than as a surprise pop-up *after* the user hits Enter may also speed markup.

**Comment by bpotchik** [comment]
Duplicate symbol support now exists. There is no longer a warning dialog about creating duplicate. We may show a dup message in the rename dialog in a future build.

Fixed in `2.3.2731-dev`.
