### ISSUE TITLE
Adjust number of parameters passed to variadic function at call site, on ABIs where variadic functions are special

### ISSUE THREAD

**Issue by comex** [Vector35/binaryninja-api#2121]
This is a followup from #1031 ("Ability to adjust number of parameters passed to variadic function at call site."), which was closed with a note that you can now use "Override Call Type".

I assume the suggestion is that if you have, say, a call to `printf` with two int arguments, you can override the type for that call to `void printf(const char *, int, int)`.  That works on most ABIs, where variadic functions are called the same way as a normal function with the same argument types.  But some ABIs make variadic functions special; for instance, on Apple arm64, variadic arguments are forced to be passed on the stack rather than in registers.  [Attached example binary.](https://github.com/Vector35/binaryninja-api/files/5519489/test.zip)

Is there a way to make "Override Call Type" work for variadic functions on those ABIs?  If not, this issue is a request for one.

**Comment by nshp** [comment]
You can define custom calling conventions via the API, and the "override call type" will let you choose a calling convention as well. Perhaps add a `__va_stack` calling convention for variadic functions on Apple arm64, then define your printf as `int printf(const char *, ...) __va_stack`?

**Comment by comex** [comment]
That could work.  Ideally this functionality would be built in, though.  And there's a bit of a semantic mismatch.  A variadic function doesn't force *all* function arguments to the stack, only the variadic arguments.  For example, the format argument to printf is still passed in a register.  So I suppose there would have to be a whole set of calling conventions depending on the number of fixed arguments – `__va_stack_1`, `__va_stack_2`, etc. – unless there's some way to parameterize calling conventions.

**Comment by rssor** [comment]
Thank you for the test case.

As of build 2.3.2834-dev calling conventions have a new callback `areArgumentRegistersUsedForVarArgs`. The new `apple-arm64` calling convention is also added to take advantage of it.

In addition to working with simple cases like `int printf(char* fmt, ...)`, call type overrides at particular call sites will now, in the variadic case, intelligently look at the original call type to see at which point the overridden type needs to transition to stack parameters while still preserving the ability to provide extra type information at individual call sites to variadic functions.
