### ISSUE TITLE
This program is used to create viruses, worms or other malware. 

### ISSUE THREAD

**Issue by ColdHeat** [Vector35/binaryninja-api#213]
![image](https://cloud.githubusercontent.com/assets/166333/14231834/3d584962-f960-11e5-90f3-a26197ffd2bd.png)

**Comment by plafosse** [comment]
This is prebuilt clang binaries that are being flagged.  Microsoft wrote a very bad windows defender signature. We have temporarily fixed this by removing the executables from the windows build, and purging previous windows versions so someone can't accidentally get this error.  We have notified Microsoft and the original providers of the binaries that these files are being flagged incorrectly.  I will keep this issue alive until we have a solution.

**Comment by psifertex** [comment]
Those binaries are removed from the program.
