### ISSUE TITLE
Can't search symbols list by mangled name

### ISSUE THREAD

**Issue by KyleMiles** [Vector35/binaryninja-api#2130]
It _feels_ like a bug to be able to right-click the symbols list, "Show Mangled Names" and then not be able to search by what's being displayed.

**Comment by cxnder** [comment]
![image](https://user-images.githubusercontent.com/55725881/186409994-b7aabde5-622c-4245-b288-97ea6273c949.png)
This appears to have been fixed in a previous build

**Comment by plafosse** [comment]
Confirmed.
