### ISSUE TITLE
Disassembly text does not show variable name when it should

### ISSUE THREAD

**Issue by jeffli678** [Vector35/binaryninja-api#2133]
![Screenshot from 2020-11-19 21-47-43](https://user-images.githubusercontent.com/3380590/99682947-c3ab5000-2aba-11eb-9d41-ec17966e4e24.png)
![Screenshot from 2020-11-19 21-47-49](https://user-images.githubusercontent.com/3380590/99682950-c4dc7d00-2aba-11eb-9377-0e6e06f0cb0d.png)

we should display `0x403370` as `input`, in the disassembly at `0x4010cf`. Especially, we handle `target` correctly. the binary is here: 
[keygenme.zip](https://github.com/Vector35/binaryninja-api/files/5567598/keygenme.zip)

**Comment by psifertex** [comment]
This was fixed by #209 some time ago.
