### ISSUE TITLE
Add option for viewing IL for function cross references

### ISSUE THREAD

**Issue by toolCHAINZ** [Vector35/binaryninja-api#2135]
It would be nice to be able to view IL for a function call in the cross reference list.

What I currently see:

![img1](https://user-images.githubusercontent.com/27028960/99694606-9cbd3180-2a5a-11eb-9902-c02e3f0e300d.png)

What I would like to have the option to see:

![img2](https://user-images.githubusercontent.com/27028960/99694629-a3e43f80-2a5a-11eb-9437-68ab7af610c4.png)

**Comment by jeffli678** [comment]
interesting request, did you Photoshop that screenshot btw?

**Comment by toolCHAINZ** [comment]
Haha, yeah I did (I also messed it up and used the wrong xref, so the screenshot doesn't quite make sense, but I only realized that after I posted). Figured a picture communicated what I wanted succinctly.

**Comment by toolCHAINZ** [comment]
It looks like this got implemented at some point! Closing this issue.
