### ISSUE TITLE
Confusing HLIL for function pointer call

### ISSUE THREAD

**Issue by SlidyBat** [Vector35/binaryninja-api#2139]
For the following HLIL:
![image](https://user-images.githubusercontent.com/25954912/99859729-0bc69180-2be5-11eb-9e97-c0fa5cb43412.png)
You would think what is happening is a function at `0x400` is being called, and the result of that is added to `data_40f0`.

However, what is actually happening is `(*data_40f0 + 0x400)()` -- `0x400` is added to `data_40f0`, and the result is called as a function.
This can be seen from the assembly:
![image](https://user-images.githubusercontent.com/25954912/99859833-6233d000-2be5-11eb-85be-76f80ae8d28c.png)

The binary with this issue is attached.
[main.zip](https://github.com/Vector35/binaryninja-api/files/5576633/main.zip)

**Comment by D0ntPanic** [comment]
Fixed in build 2656
