### ISSUE TITLE
Functions returning pointers to structures do not have their offsets named

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#2140]
Windows 10 2545-dev Personal

Apologies if this is a dupe -- I looked for similar issues but might be using different terms for things. It looks like functions that return pointers to structs do not have their offsets named.

```C
#include <stdio.h>
#include <stdint.h>

struct A {
    uint32_t x;
    uint32_t y;
};

struct A AAAA[4];

struct A* idx(int ii) {
    return &AAAA[ii];
}

int main(void) {
    idx(0)->x = 0x41;
    idx(0)->y = 0x42;

    printf("%#x %#x\n", idx(0)->x, idx(0)->y);
}
```

Disassembling this in binja, even with appropriately type annotating everything gives me:
```
int64_t main()

140001026  idx(0)->:0.d = 0x41
140001033  idx(0)->:4.d = 0x42
140001064  printf(data_14001d000, zx.q(idx(0)->:0.d), zx.q(idx(0)->:4.d))  {"%#x %#x\n"}
14000106f  return 0
```

This is with the type `struct A*  idx(int32_t arg1)`. Ideally I'd see `idx(0)->x` and `idx(0)->y` in the hlil output.

**Comment by D0ntPanic** [comment]
Fixed in build 2650
