### ISSUE TITLE
Binja crash - seg fault after toggling between two bndb tabs

### ISSUE THREAD

**Issue by hanssl** [Vector35/binaryninja-api#2146]
Binary Ninja Version: 2.2.2549-dev, 920769a4
Platform: Ubuntu 20.04.1 LTS

Binja randomly crashes when the user (or plugin) moves focus between two (or more) tabs.

Steps to reproduce:
1. Open at least 2 bndb tabs in binja
2. Launch the attached sample_plugin
3. Observe the crash after a count of ~40.
* If you are having trouble reproducing the crash, toggle to a new window (e.g. a web browser and then back to binja).

Note: I run binja while logging to a file. The log file does not have any information about the crash. The console that I launch binja from reports a
[sample_plugin.zip](https://github.com/Vector35/binaryninja-api/files/5592922/sample_plugin.zip)
 Segmentation fault.

**Comment by psifertex** [comment]
Can you show the results of the stack at the moment of the crash? We have symbols we can sync it to.

**Comment by bpotchik** [comment]
Thanks for the excellent repro plugin! I was able to repro after 352 cycles.

**Comment by psifertex** [comment]
Unfortunately, this looks like a QT bug and we're currently blocking on being able to upgrade due to some Visual Studio incompatibilities. In the meantime, if you really want to work-around this if we can identify which change in QT caused it you could back-port the patch and replace the version of QT we ship with as described at: https://docs.binary.ninja/about/open-source.html#building-qt

That said, our current plan is to wait for a version of QT that resolves both this issue and the VS incompatibilities.

**Comment by hanssl** [comment]
Ouch: Waiting for QT to release a patch could be an indeterminate delay.

I have witnessed the bug with only a few tabs (<5) and a few toggles (<5).  I used in infinite loop in the sample plugin to make sure you could reproduce the issue.

If you will identify a version of pyside2 that does not have the issue I will be glad to try it, hopefully an older version still implements the UI that our plugin(s) code is built on.

**Comment by hanssl** [comment]
This may be a long shot, but you might want to check your QT code for thread issues.  I recently fixed a bug in my plugin code where I was using a progress bar that crashed after a number of updates.  The fix was that I had to switch to using Signals and Slots instead of callbacks.

**Comment by hanssl** [comment]
@bpotchik @psifertex   Has there been any change on this bug?  Is there a chance for a work around?

**Comment by bpotchik** [comment]
Looking at your script, it looks like you need to make sure that any actions you invoke through the action system need to run on the main thread. Update the line of your script which calls trigger_action to the following, and I believe your crash should go away.
`execute_on_main_thread_and_wait(lambda : trigger_action("Next Tab"))`

**Comment by hanssl** [comment]
@bpotchik Your suggestion to modify the crash script does mask the issue.

However, the sample_plugin scrip (using trigger_action) is just to illustrate the issue.  My users are reporting this crash from human interactions (i.e. a human RE has multiple tabs open in binja, after manually toggling between a few tabs then binja crashes).  Their interactions are basic functions in binja.

**Comment by bpotchik** [comment]
If you have a plugin active that is invoking any actions through the action system that run as a result of switching tabs, that can potentially crash as well if not run on the main thread. I imagine this crash only happens with some plugin active?

**Comment by hanssl** [comment]
Yes, we started seeing the crashes after using a feature of one of our plugins.  The plugin has a table of bndbs that when the user double clicks one of them then the plugin loads that bndb into binja and navigates to the desired address with:
`    def open_bndb_in_new_tab(self, file_path: str, fid: str, address: int):
        try:
            mainthread.execute_on_main_thread_and_wait(
                lambda: UIContext.allContexts()[0].openFilename(file_path)
            )

            # navigate to the target function.  Use a new thread so that we can wait on analysis to complete without hanging the gui
            self.navigate_to_address_thread = threading.Thread(
                target=self._navigate_to_target_address_thread,
                args=(fid, address,),
            )
            self.navigate_to_address_thread.start()

        except:
            print("Something went wrong when we tried to open the bndb in a new tab")

    def _navigate_to_target_address_thread(self, fid: str, address: int):

        try:
            bv = self.get_current_bv()# note: race-condition: the current bv may not be the one we are aiming for...Very likely though as the open_bndb_in_new_tab thread just completed...

            cur_fid = getFileId.get_file_id_from_bv_original_filename(bv)

            if cur_fid != fid:
                print(f"The current fid '{cur_fid}' != target fid: '{fid}' so we can't navigate to address: {address}")
            else:
                # wait until the analysis is complete
                while bv.analysis_info.state != AnalysisState.IdleState:
                    print("waiting for analysis to complete -> then navigate to address")
                    time.sleep(0.5)

                print(f"navigate to address: {address} fid: '{fid}'")
                mainthread.execute_on_main_thread(
                    lambda: bv.navigate(bv.file.view, int(address, base=16))
                )
        except:
            print(
                "Something went wrong when we tried to navigate to the target address"
            )

    def get_current_bv(self) -> BinaryView:
        dock = DockHandler.getActiveDockHandler()
        if not dock:
            print(
                f"Could not get DockHandler.  Vector 35 Snippets plugin says this should not happen."
            )
            return None, None, None
        else:

            view_frame = dock.getViewFrame()
            if not view_frame:
                # no open views
                return None, None, None
            else:
                view_interface = view_frame.getCurrentViewInterface()
                bv = view_interface.getData()

                return bv
`
Now the user has 2 or more bndbs open in binja.  The bug usually occurs minutes later as the user manually switches between open bndb tabs.

**Comment by bpotchik** [comment]
Yes I see. The navigation action needs to occur on the main thread. That code is creating a new thread.

**Comment by hanssl** [comment]
I create a new thread so that I can wait in case there is any analysis (e.g. from a new version of binja) but then I do the bv.navigate action inside a execute_on_main_thread() block.

**Comment by bpotchik** [comment]
Oh I see that now. The formatting was a little strange on first glance. What happens if you change the execute_on_main_thread call to a execute_on_main_thread_and_wait?

**Comment by hanssl** [comment]
I changed my code to use execute_on_main_thread_and_wait for the bv.navigate step.  I don't see any change in behavior but the bug is difficult to reproduce.

The crashes do not appear to be related to the open/navigate steps as they usually happen minutes later when the user is manually switching between tabs or closing a tab.

How would the execute_on_main_thread_and_wait version of the navigate step relate to the crash?

**Comment by hanssl** [comment]
I can confirm that the bug persists after changing to the execute_on_main_thread_and_wait block for the bv.navigate step.  I have reproduced the bug several times in the last hour.

**Comment by bpotchik** [comment]
It's been a while since the original post which was 2.2.2549-dev. Does this still occur on the latest dev (2.2.2576?)

Is there a chance this crash is being produced by a specific binary which is able to trigger this edge case? And if so can you share the binary? (Can also DM to me on slack)

**Comment by hanssl** [comment]
I tested the stable and dev branch.  Crash persists on both. 

I don't think the crash is related to any specific binary.  I will try to put together a binary set that I can share.

**Comment by bpotchik** [comment]
Also if you have a different plugin to try and repro that could help. The `sample_plugin.zip` provided above does not crash for me anymore after updating with the 'and_wait' version of the API.

**Comment by bpotchik** [comment]
I believe this may have been fixed in `2.2.2644-dev`. I am unable to repro this issue anymore. If you are able to repro on the latest dev please reopen this issue.
