### ISSUE TITLE
Better support for editting structures with unknown bytes

### ISSUE THREAD

**Issue by jeffli678** [Vector35/binaryninja-api#2149]
![Screenshot from 2020-11-26 11-39-22](https://user-images.githubusercontent.com/3380590/100306420-4ada5580-2fde-11eb-814f-5f31506d6a39.png)

Currently, when we edit a packed structure, all the padding bytes will vanish. 

Also, it would be nice if we can directly toggle whether a structure is packed or not.

**Comment by psifertex** [comment]
Not really related to packed or not since the issue will exist in regular structures as well. Need to extend our type parser to support an offset keyword or some sort of padding type that we can represent in the C representation that will then round-trip.

**Comment by CouleeApps** [comment]
This was fixed back in 3.1 with the addition of the Clang type parser.
