### ISSUE TITLE
Updating a type definition is not immediately reflected in HLIL

### ISSUE THREAD

**Issue by jeffli678** [Vector35/binaryninja-api#2150]
Assume I work on two tabs, one displays the type view, one displaying the HLIL. If I update the type definition, e.g., changing a type field name, it is not immediately reflected in the HLIL. Forcing binja to regenerate the HLILs, e.g., reanalyzeing the current function fixes the problem.

**Comment by plafosse** [comment]
Do you have a repro?

**Comment by xusheng6** [comment]
There is already fixed as of BN 3.4
