### ISSUE TITLE
Binaryninja-api version check on plugin load

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#2155]
When developing architecture plugins, it's common to update binja but not rebuild your plugin. While this usually works, if binaryninja-api has been updated as part of this update, the plugin will have been built against an outdated binaryninja-api repo and can fail in strange and mysterious ways that are annoying to debug. The request here is to warn and/or fail to load a plugin that is built against a binaryninja-api repo that doesn't match the current running binja version.

**Comment by D0ntPanic** [comment]
Native plugins are now bound to an ABI versioning system in both the core and the UI.

For core plugins, the `BN_DECLARE_CORE_ABI_VERSION` macro must be included in the plugin source.
For UI plugins, the `BN_DECLARE_UI_ABI_VERSION` macro must be included in the plugin source.

If these are not included, the plugin will fail to load (and show an error reminding that these are required).

On future updates that break binary compatibility, plugins that have not been updated will be prevented from loading, and an error describing this will be generated on startup.

Plugins that have the new ABI version attached will still load in the 2.2 stable. Future stable versions will require the ABI version.

Updates that add functionality but do not break existing binary compatibility will not prevent older plugins from loading, as there is a concept of a minimum compatible ABI version. Plugins that are compiled for newer versions of Binary Ninja will not load in older versions, as it is not possible to verify compatibility in this case. To maximize compatibility when distributing pre-built native plugins, build on the minimum supported API version.

Added in build 2624.
