### ISSUE TITLE
Add a disassembly-only option for large functions

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#2156]
I should be able to at least look at very large functions without binja attempting to lift them. Right now my options are keep it collapsed and force analysis. I'd prefer to keep those, and add a third 'disassembly only' option which skips lifting (or does minimal lifting, e.g. LLIL but no MLIL/HLIL, etc).

**Comment by bpotchik** [comment]
You should already be able to do this. Right click in the function and select `Disable Current Function Analysis". For a general settings see the `analysis.limits` related settings.
