### ISSUE TITLE
Support jumping to file offset

### ISSUE THREAD

**Issue by landaire** [Vector35/binaryninja-api#2157]
A feature I frequently use in IDA is the `Jump > Jump to file offset...` for scenarios where I may search in my hex editor for some data in the binary then jump to it in the disassembler. I cannot figure out any way to do this in Binary Ninja. `g` is used for addresses, which doesn't appear to always map correctly.

For example in my hex editor I searched for the binary sequence `90 0F 10 00 0F 11 04 10` which yielded a result at `0x5FB40F`. Trying to use the python console with `here = current_view.start + 0x5FB40F` brought me to a location with instructions that did not match the byte sequence I searched for above. I then used the text search feature to search for the same hex string which yielded a result at `0x005fc00f`. My guess is this has something do with RVA vs mapped VAs.

**Comment by psifertex** [comment]
1. Install the Snippets plugin from the plugin manager
2. Bind https://gist.github.com/psifertex/6fbc7532f536775194edd26290892ef7#file-navigate_to_offset to a hotkey

**Comment by psifertex** [comment]
I'm gonna close this issue since it should solve your problem with the above snippet but if not, feel free to re-open1

**Comment by landaire** [comment]
I believe that does the trick. Thank you!

**Comment by psifertex** [comment]
Reopening since we do want to implement this without requiring a snippet.

**Comment by kristopax** [comment]
Fixed in 2.3.2685-dev
