### ISSUE TITLE
UIDF: Handle more than definition sites

### ISSUE THREAD

**Issue by nshp** [Vector35/binaryninja-api#2160]
This might really be multiple issues, but:
- Make the "set user variable value" option available on variables regardless of context. Use the SSA form to find the definition site automatically.
- Allow setting UIDF directly on function parameters, which have no normal definition site
- Allow setting UIDF on global registers, e.g. to set or override the global pointer value within a function

**Comment by fuzyll** [comment]
We believe this should now be fixed in builds >= 3.6.4614-dev (assuming no one unintentionally sabotages the CI system this time 🙃). If not, or if you find any issues with the fix, please let us know.
