### ISSUE TITLE
Suboptimal decompiler output with array of structs

### ISSUE THREAD

**Issue by comex** [Vector35/binaryninja-api#2161]
[Test case](https://github.com/Vector35/binaryninja-api/files/5617848/bnquirk.zip)

In the test case, the function `_main` first initializes r12 to point to a global array of structs:
```
100003f51  4c8d25b8400000     lea     r12, [rel _a_list]
```
Then, in a loop, it gets two fields from the nth entry and ORs them together:
```
100003f5f  410fb704dc         movzx   eax, word [r12+rbx*8]
100003f64  450fb76cdc02       movzx   r13d, word [r12+rbx*8+0x2]
100003f6a  4909c5             or      r13, rax
```

Binary Ninja (2.2.2551-dev) decompiles this as:

```
100003f76      rax_2 = _asdf(0, zx.q(*((rbx << 3) + 0x100008012)) | zx.q(*(_a_list + (rbx << 3))), &var_38)
```

where `0x100008012` points to `_a_list + 2`.

This is suboptimal in two ways:

1. Displaying the raw number `0x100008012` instead of `_a_list + 2` is unhelpful.
    
    -> If I manually create a struct with appropriate fields and mark `_a_list` as a variable of that struct type, `0x100008012` changes to `_a_list.field_2`, which is better, but isn't it missing an `&`?  Regardless, BN should show the symbol without needing this.

2. Ideally the decompiler would merge the duplicate instances of `r12+rbx*8` and end up with something like:
    ```
    entry = _a_list + (rbx << 3)
    … *entry | *(entry + 2) …
    ```

**Comment by ccarpenter04** [comment]
I've heard that this is  being worked on, will we be seeing it in dev builds anytime soon?

**Comment by plafosse** [comment]
Very soon, the feature is being tested currently

**Comment by ccarpenter04** [comment]
Awesome, thanks for the update @plafosse , I definitely won't miss https://i.gyazo.com/7a9bb5aca7ddcd47d8efeede3205ead5.png

**Comment by D0ntPanic** [comment]
Array resolution support has been added in build 2760. HLIL output will now include array references from array and pointer types. Accesses to global structure members have been improved as well.

After defining a structure and applying the structure to the global array in the given example, the output is now like this:
```
100003f76      rax_2 = _asdf(0, zx.q((*_a_list)[rbx].field_2) | zx.q((*_a_list)[rbx].field_0), &var_38)
```

The need to dereference global addresses may be improved at a later date.
