### ISSUE TITLE
Offer a way to create new variables for MLIL/HLIL in the UI

### ISSUE THREAD

**Issue by landaire** [Vector35/binaryninja-api#2163]
[Dicussion post for more context here](https://github.com/Vector35/binaryninja-api/discussions/2158).

It seems like this should be possible with a snippet by modifying `current_function.vars` although I have not ventured down this path. Offering a way to do this in the UI would be a huge UX improvement for producing more readable and semantically-correct HLIL.

**Comment by plafosse** [comment]
Closing in favor of #1887
