### ISSUE TITLE
UI Callback for changing address (with / without navigating)

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#2166]
Currently, plugins can register for a callback when the user navigates, but this doesn't apply when they use the UI to change address without navigating. DockWidgets can register for offset change notifications, but there is no general callback for that.

Proposed solution: add another callback to UIContextNotification

**Comment by CouleeApps** [comment]
As of 2.2.2555 this is now OnAddressChanged() on UIContextNotification

**Comment by psifertex** [comment]
Also worth mentioning this example script demonstrates that API: python/examples/ui_notifications.py
