### ISSUE TITLE
Cannot select aarch64 slice in universal binary

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#2169]
When trying to load a universal (fat mach-o) binary, selecting the aarch64 slice does not actually affect which slice is loaded.

BN Version: 2.2.2557-dev

Repro steps:
1. Open libbinaryninjacore.1.dylib in binja
2. On the Open with Options menu, change to the arm64 slice
3. Press Open
4. Observe that binja loads the x86_64 slice

Expected beahvior: Binja loads the arm64 slice

**Comment by CouleeApps** [comment]
Looks like binja always just loads the first slice of the binary, regardless of arch

**Comment by bpotchik** [comment]
Fixed in `2.2.2560-dev`
