### ISSUE TITLE
Copying from the About dialog actually copies from open view

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#2170]
Makes it dificult to copy build ids...

BN Version: 2.2.2557-dev

Repro steps:
1. Open any file
2. Highlight some text in linear view
3. Open the about page
4. Highlight the binja version text
5. Copy

Expected behavior: Binja version is copied

Actual behavior: Lines from linear view are copied

**Comment by jeffli678** [comment]
I cannot reproduce this. But it does remind me of a similar issue: https://github.com/Vector35/binaryninja-api/issues/2075

**Comment by psifertex** [comment]
Right-click copy works. CMD/CTRL-C does not.

**Comment by psifertex** [comment]
This has been resolved and a duplicate ticket filed accidentally.
