### ISSUE TITLE
Mach-O: arm64e slices are listed as arm64 (not e)

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#2171]
This seems to be due to Apple using a different format for the cpu subtype than usual. `CPU_SUBTYPE_ARM64E` is defined as `((cpu_subtype_t) 2)` in machine.h, but binaries actually use `0x80000002` which includes one bit for `CPU_SUBTYPE_LIB64` (`0x800000000`). Since we don't expect that extra subtype flag, we fallback to assuming arm64e binaries are regular arm64 and display the wrong arch.

Possible fix 1: Add extra cpu subtype options with the `CPU_SUBTYPE_LIB64` flags

Possible fix 2: Strip `CPU_SUBTYPE_MASK` flags from subtype when checking list

**Comment by bpotchik** [comment]
Fixed in `2.2.2560-dev`
