### ISSUE TITLE
Binja crashes after bad BinaryDataNotification.tag_added addr

### ISSUE THREAD

**Issue by hanssl** [Vector35/binaryninja-api#2174]
Binary Ninja Version: 2.2.2487, e0eb0a77
Platform: Ubuntu 20.04.1 LTS

Crash: after toggling visibility of function tag

Steps to reproduce:
1. Open any bndb
2. Right click any function and launch the "Binja crash demo" (attached)
3. Observe that binja crashes after a count of ~22-100.

Problems:
1. When a function tag is created create_user_function_tag() then the BinaryDataNotification.tag_added parameters are wrong
	- addr is 0: therefore to get the location of the tag we have to de-reference the func ptr.
	- after de-referencing the func ptr a few times then binja crashes
	
	* no stack trace or help from the binja log file...

[sample_plugin.zip](https://github.com/Vector35/binaryninja-api/files/5639778/sample_plugin.zip)

**Comment by bpotchik** [comment]
Thanks for the example plugins to repro. Also you can use `"Binja crash demo\\Tabs"` to register a plugin if you would like the action in a menu (Since you're finding so many crashes 👍)

**Comment by CouleeApps** [comment]
Binja is crashing because the Function(handle=...) constructor doesn't increment the refcount (with core.BNNewFunctionReference) of the Function, but it does decrement when destroyed. The real underlying bug here is that the python api is giving you a LP_BNFunction instead of a real Function object.

**Comment by CouleeApps** [comment]
This was fixed in 2.2.2565
