### ISSUE TITLE
Strange error message

### ISSUE THREAD

**Issue by houseofwealth** [Vector35/binaryninja-api#2175]
Hello, I have recently started seeing a strange error message I haven't seen before when I run a Python script on Binary Ninja:

```
bv = binja.BinaryViewType['PE'].open(sys.argv[1])      #argv[1] is the name of the executable
bv.update_analysis_and_wait()

```
The analysis seems to proceed, but I get an error message:
`Failed to parse load configuration directory: encountered invalid offset
`
There's not much to go on in this error message and I'm not sure what its trying to say (should there be an "or" between "parse" and "load"?). Any ideas? (I also find that the further analysis that I do seems to miss quite a few jump targets and return targets, but I'm wondering if that has to with this error message

thanks
PS I am attaching the executable on which I ran it (its the 32 bit version of WIndows "finger")
[finger32.zip](https://github.com/Vector35/binaryninja-api/files/5639786/finger32.zip)

**Comment by bpotchik** [comment]
The error message is correct, although Load Configuration Directory could be emphasized as it is an entry in the PE file. There was also a bug here while parsing, although it would not affect your analysis.

Fixed in `2.2.2562-dev`.

**Comment by houseofwealth** [comment]
I'm sorry, I don't understand what the resolution of this problem is. Are you saying there's a problem with the executable, or a problem with Binary Ninja that has been fixed, or that it's not a problem that I need to worry about?
thanks

**Comment by bpotchik** [comment]
I fixed the size/field detection of the Load Configuration Table in Binary Ninja. If you switch to linear view you can look at address `0x1001138` to see the structure. There are several versions of this structure, where each new version adds some new fields.

There is no problem with the executable. Thanks for reporting the error!
