### ISSUE TITLE
Bin

### ISSUE THREAD

**Issue by houseofwealth** [Vector35/binaryninja-api#2177]
I have the following code to get the return targets of retn instructions:
```
def get_ninja_block_disasm(startEA,endEA, retnTargets):
    text = ""
    try:
        #get_basic_blocks_at returns the bbs at an addr - more than one b/c of overlap?
        bbs = bv.get_basic_blocks_at(startEA)   
        if len(bbs) > 1:
            print("***WARNING: possible overlapping basic blocks at " + str(startEA))
        block = bbs[0]
        bb_textlines = block.get_disassembly_text()
        for instr in bb_textlines:
            text += "0x"+format(instr.address,'08x') +":"+str(instr) +"\n"
            if str(instr).startswith("ret") :
                callers = bv.get_callers(startEA)
    ...
```

The problem is that sometimes callers is empty for some "retn" instructions. In the enclosed finger.exe example, retn at 0x1001581, or retn at 0x10015aa, even though when I open the file in Binary NInja they have perfectly good looking call instructions, etc (eg the retn at 0x1001581 is the end of a subroutine starting at 0x10014c6 that is called at 0x010016e5). I have a similar problem with jump instructions that jump to subroutines, where `block.outgoing_edges` returns empty (eg. `jmp     sub_1001ba8 `at 0x1001841)

thanks!
[finger32.zip](https://github.com/Vector35/binaryninja-api/files/5645185/finger32.zip)

**Comment by plafosse** [comment]
``get_callers`` returns a list of callers to the provided address. If you'd like to find callers to the current function that the "ret" is in I'd suggest you use ``block.function.callers``. 

Concerning the ``block.outgoing_edges`` This API only provides intra-procedural edges.  ``jump`` instructions end a basic block and thus do not have intra-procedural edges. If you would like to know which functions the current function calls you can get this on the function object using the ``callees`` property.

**Comment by psifertex** [comment]
Also, for questions about API usage I recommend joining the slack https://slack.binary.ninja/ which has a dedicated #api-help channel, or filing a discussion as opposed to a bug report. 

https://github.com/Vector35/binaryninja-api/discussions
