### ISSUE TITLE
Copy paste fails on instruction bytes with unknown instructions

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#2178]
If an instruction cannot be decoded, I cannot copy/paste the bytes out of graph view into another disassembler. In the attached recording, I am using control-c on the bytes at 000039a8 to no effect.

![copy-paste-unk-ins](https://user-images.githubusercontent.com/8716677/101269218-6998c480-3721-11eb-901b-47895cefe193.gif)

Image is attached, loaded at address zero in the screen recording.

[rom.bin.txt](https://github.com/Vector35/binaryninja-api/files/5648153/rom.bin.txt)

**Comment by xusheng6** [comment]
Similar to https://github.com/Vector35/binaryninja-api/issues/5189

**Comment by xusheng6** [comment]
Fixed in dev 4.1.4972, along with #5189
