### ISSUE TITLE
Binary Ninja API should yell if you don't have a license

### ISSUE THREAD

**Issue by gynophage** [Vector35/binaryninja-api#218]
If you've got the binary ninja stuff installed, but license not in place, and you import binaryninja and do things, it doesn't error, it just doesn't work.

Did this on a headless Linux install, was very confusing until strace showed me failing a license load. Perhaps you should throw an exception for this?

**Comment by psifertex** [comment]
Fixed in dev, should be in the next beta. Still possible to import without warning because of some internal dependencies, but any attempt to use anything in it will throw a RuntimeException with a warning about the license.
