### ISSUE TITLE
HLIL should use type information for jumps when available

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#2186]
HLIL optimization opportunity when jumping to a function pointer with type information.

```
int32_t io_size(struct io_entity_t* handle, uint64_t* length)

0e00b404  int32_t (* size)(struct io_entity_t* entity, uint64_t* length) = handle->dev_handle->funcs->size
0e00b414  if (size == 0)
0e00b414      return 0xffffffed
0e00b40c  jump(size)
```

This would be easier to follow if the parameters were listed as arguments to the jump, e.g.:
```
[...]
0e00b40c  jump(size, entity: handle, length: length)
```

Corresponding source is [here](https://github.com/ARM-software/arm-trusted-firmware/blob/eeb77da64684424ef275330e3e15d8350ecc1b07/drivers/io/io_storage.c#L251-L265)

**Comment by plafosse** [comment]
Seems more like an indirect tailcall. Perhaps we can actually improve tailcall resolution and then it just gets shown as
```
return size(entity: handle,  length:length)
```

**Comment by bpotchik** [comment]
Looks like a typed, unresolved tailcall would be needed.

**Comment by yrp604** [comment]
Yeah I’m not too particular about how these parameters might be displayed, the suggestion was mostly to expose the info somehow. Your example looks great and definitely does that 👍

**Comment by plafosse** [comment]
marking as a duplicate of: https://github.com/Vector35/binaryninja-api/issues/2186
