### ISSUE TITLE
View menu and the options in the bottom right should maintain address

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#2187]
We currently have two distinct ways of switching to views (such as the hex editor) and it's not immediately clear that they do different things. One is to use the "View in..." action . This will maintain the address currently selected if using a view that has BV offsets.

The second is to use the View / $view or options in the bottom right and that currently does NOT create a navigation event, nor does it stay on the current address.

We should instead try to navigate to the same address (if applicable -- the types view for example does not have bv offsets, but graph, linear, and strings should all have real offsets) when using the other menus for a more consistent experience and optionally have another fallback method such as an action item that can switch without maintaining the address.

**Comment by bpotchik** [comment]
This has been fixed for a while.
