### ISSUE TITLE
Find text ignores intrinsics

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#2192]
2575-dev Personal Win10

I have a linear hlil function:
```
int64_t vbar_el1[4]() __noreturn

0e203200  uint32_t daifclr = _WriteStatusReg(4)
0e203240  void esr_el1
0e203240  if (zx.q((_ReadStatusReg(esr_el1) u>> 0x1a) & 0x3f) != 0x25)
0e203240      return wfi_loop() __tailcall
0e2022d0  uint64_t __saved_x0
0e2022d0  void far_el1
0e2022d0  if (sub_e200e84(&__saved_x0, _ReadStatusReg(far_el1)) != 0)
0e2022d0      return wfi_loop() __tailcall
0e20229c  int0_t elr_el1
0e20229c  uint32_t elr_el1_1 = _WriteStatusReg(_ReadStatusReg(elr_el1) + 4)
0e2022cc  _eret()
0e2022cc  trap(0)
```

c-f for 'WriteStatus', 'eret', or 'ReadStatus' all fail. c-f for 'daifclr' works.

**Comment by psifertex** [comment]
The root cause is that find text doesn't really work at all in IL views except accidentally where it aligns with addresses from assembly views. This is described in the bulleted list in #1969 but the good news is we plan to work on that for 2.3
