### ISSUE TITLE
show outdated plugins in status bar

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#2199]
If plugins have updates that can be installed we should have a visual indicator in the status bar that either triggers updates or opens the plugin manager.

**Comment by bambu** [comment]
Adding to this, it would be nice if the plugins showed last time it was updated

**Comment by psifertex** [comment]
Would you want when the version in the plugin repository was last updated or a check that just sees the last activity on the repository itself which might not align with versions in the plugin manager?

**Comment by psifertex** [comment]
I guess I never replied previously, but plugins _do_ now show when they were last updated as of several years ago. Still need to add better notification of outdated plugins.

**Comment by ElykDeer** [comment]
Closing in favor of #2200.
