### ISSUE TITLE
Font sizes on Windows 10 are very large

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#2201]
The font sizes used on Windows 10 are all over the place. Here's an example from the Plugin Manager:

![image](https://user-images.githubusercontent.com/607452/102452700-c9884880-4008-11eb-8ff8-42dba0f73a4a.png)

Fonts elsewhere in the UI are also wacky sizes as well (e.g. the buttons on the main tab when you launch the application have text twice the size of the "Decompiler is here!" section's body text). Adjusting the font size in the settings menu doesn't seem to have an effect. I suspected it had something to do with display scaling (mine's set to 150% in Windows Settings), but when I changed it, this text was still huge relative to the other text.

This is from a fresh install on Windows 10, v2.2.2487, which should be current stable. I can also confirm that v2.2.2579-dev has the same behavior.

**Comment by VelocityRa** [comment]
Same here.
I'm using Binary Ninja on Windows 10, a 4k monitor with 150% scaling.
Even if I reduce the font size in Binja's settings, UI elements are still too large.

**Comment by psifertex** [comment]
Hmm, I can't reproduce this in a VM at least on a 4k display at 150% scaling. Can you try with the various QT DPI settings to see if they impact it? 

https://doc.qt.io/qt-5/highdpi.html#microsoft-windows

**Comment by fuzyll** [comment]
I launched Binja from PowerShell with all 3 DPI awareness settings and there's no change from the screenshot attached at the top level.

**Comment by psifertex** [comment]
Thanks. Must be something else. What resolution are you running at? Is this native or in a VM?

**Comment by fuzyll** [comment]
Oh, sorry, should've provided that up-front: Native at both 3840x2160 (4k) and 3840x2400. Binary Ninja looks this way on every Windows computer I've ever installed it on, including both work and personal computers, plus computers my co-workers use. If you guys somehow still can't replicate the problem, let me know and I'll bring a computer by the office.

**Comment by psifertex** [comment]
After some more testing we got this reproducing just fine and have a temporary work-around for anyone else experiencing similar issues:

1) Right-click on your Binary Ninja startup shortcut and choose properties
2) Under "compatibility" enable the last HiDPI option and set it to "System (Enhanced)"
3) Then, enable the HiDPI setting on Binary Ninja under font anti-aliasing

This should fix the relative font sizes and still produce clean renderings. 

Going to leave this issue open to track the issue which we'll revisit post moving to QT6 which has a number of HiDPI changes associated with it.

**Comment by ranweiler** [comment]
@psifertex, your workaround _kind of_ works for me, in that all the relative sizes look right. However, rendering is still fuzzy in the way that, say, the Hyper-V Manager's panes are fuzzy on my 4K display. Is that what we should expect for the workaround, or should I dig in a bit more? Anything version-specific to be aware of?

It seems like the real fix will be the QT upgrade, so I'm not worrying about this too much. I just want to make sure I'm getting the best rendering I can with the current implementation.

**Comment by psifertex** [comment]
Nope, not aware of anything else that might impact it, pretty sure the long-term fix is wait for QT. 

Or run an X server and run the linux version under WSL which is actually a surprisingly not-terrible experience (though to be fair, I haven't tested it specifically for DPI/scaling issues just in general it's been very usable in the past)

**Comment by fuzyll** [comment]
I believe that the underlying issues causing this have now been resolved as of builds >= 3.5.4425-dev. There are still situations where font sizes aren't ideal, but I believe those to be issues specific to certain UIs and affecting all platforms equally.

It took me almost 3 years, but my master plan to get hired so I could fix Windows font rendering is nearly complete! 😛
