### ISSUE TITLE
Calling view.get_code_refs fails on MIPS binaries

### ISSUE THREAD

**Issue by jvinnedge-novetta** [Vector35/binaryninja-api#2202]
Calling `view.get_code_refs()` on a MIPS binary fails to find xrefs, even when they exist. This problem does not appear on other architectures (ie ARM, x64, etc) so I assume it's a bug? I've attached a MIPS binary that can be used to reproduce the behavior. I'm running BinaryNinja 2.2.2487.

Here's some output that shows the issue:

```console
>>> import binaryninja
>>> v = binaryninja.BinaryViewType.get_view_of_file('libwrite4_mipsel.so')
>>> v
<BinaryView: 'libwrite4_mipsel.so', len 0x110b8>
>>> s = v.get_symbol_by_raw_name('read')
<SymbolType.ExternalSymbol: "read" @ 0x110ac>
>>> hex(s.address)
'0x110ac'
>>> v.get_code_refs(s.address)
[]
```

As a possible work around, I discovered that it works on MIPS if you call `view.get_code_refs(view.get_data_refs(sym.address)[0])`:

```console
>>> v.get_data_refs(s.address)
[69720]
>>> v.get_code_refs(v.get_data_refs(s.address)[0])
[<ref: mipsel32@0x950>, <ref: mipsel32@0x958>]
>>> 
```

The above pattern did not work on ARM or x64.

Apologies if this is not a bug; the difference in behavior from other architectures leads me to think that it might be.

[libwrite4_mipsel.so.zip](https://github.com/Vector35/binaryninja-api/files/5731317/libwrite4_mipsel.so.zip)

EDIT: Updated to add that this behavior was not in the previous stable version. Calling `view.get_code_refs(sym.address)` on a MIPS binary worked as expected.

**Comment by psifertex** [comment]
At first glance, this might just be an issue of getting the wrong symbol. The following code works for me:

```
for sym in filter(lambda x: "read" in x.name, bv.get_symbols()):
  print(bv.get_code_refs(sym.address))
```

The issue is that there are two symbols. One is the PLT entry, one is the GOT entry. I suspect this change came either as the result of some improved ELF/MIPS parsing or some other fix that resulted in this (apparent) regression. 

Let me know if that fixes the issue for you or not.

**Comment by psifertex** [comment]
Err, not PLT/GOT, but rather one is the external reference which is in a faked address space to provide references to (in this case a data reference since presumable the loader would be writing the actual address of read from libc into that location.)

**Comment by jvinnedge-novetta** [comment]
Makes sense. I did notice that the data references were in the faked externs section, which then tied back to the GOT entry.

I'm fine with either the solution I posted or the one you posted. It was just interesting to me that it only happened in ELF/MIPS and not other platforms. 

Seems like it might be more of a documentation issue than anything maybe?

Thanks for the quick response!

**Comment by psifertex** [comment]
No worries, happy to help. Hope you have a Happy Holidays and pleasant New Year.
