### ISSUE TITLE
Child type changes are not propagated to parent type

### ISSUE THREAD

**Issue by jeffli678** [Vector35/binaryninja-api#2203]
Given the following structures A and B:

![Screenshot from 2020-12-23 13-15-23](https://user-images.githubusercontent.com/3380590/102962060-f9f84700-4520-11eb-95a3-d5994dc488fd.png)

If we redefine structure B and add a new field, the display of structure A screws up:

![Screenshot from 2020-12-23 13-16-35](https://user-images.githubusercontent.com/3380590/102962134-1a280600-4521-11eb-9b97-074eafd2b9a9.png)

**Comment by jeffli678** [comment]
The cause of this is that the size of B becomes larger, and `char* a3` overlaps with it

**Comment by ccarpenter04** [comment]
This can be quite frustrating when dealing with types that use multiple inheritance

**Comment by jeffli678** [comment]
A related feature would be allowing the user to manually specify the offset of a member in a strutcture

**Comment by jeffli678** [comment]
Also related to https://github.com/Vector35/binaryninja-api/issues/2149

**Comment by plafosse** [comment]
This is intended behavior we dont' think that structure fields should ever be moved around without direct user input. It would be nice though if you could automatically/optionally overwrite the structure members as the contained structure is expanded.
