### ISSUE TITLE
Tags not working in some IL views

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#2204]
Win10 2584-dev Personal

Tags do not display in HLIL when created from HLIL (they do display at the disassembly view however). It's not clear if this is a bug or a feature request, but I had already made the gif and I didn't want it to go to waste =p

![tagfail](https://user-images.githubusercontent.com/8716677/102978452-63dd0600-44b9-11eb-8807-48258bb46c83.gif)

**Comment by yrp604** [comment]
This also happens leaving comments:
![commentfail](https://user-images.githubusercontent.com/8716677/103144862-6623a800-46e5-11eb-956f-799d8f26ce0e.gif)

**Comment by CouleeApps** [comment]
There are two bugs here:
- Tags/comments on addresses before the first visible line of HLIL
- Tags/comments on the functions directly (`current_function.comment = 'Wow this field is not settable through the ui'`)

Both of these fail to appear at all.

**Comment by CouleeApps** [comment]
Both of those bugs mentioned should be fixed in 2.4.2900-dev.
