### ISSUE TITLE
Make UI consMake built-in variables read-only or warn on changes

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#2206]
Because the UI scripting CI some has a few helpful objects automatically created, if the user writes a script that happens to use those variable names the results will be unexpected. `bv` being a good example. 

We should either make the variable not writable so an exception is triggered, or detect modifications and log_error to the user.

**Comment by jeffli678** [comment]
I believe some variables, including `bv`, is indeed write-protected. Attempting to write to `bv` gives me:

```
Setting variable "bv" will have no affect as it is automatically controlled by the ScriptingProvider.
```

**Comment by psifertex** [comment]
Ahh, yeah, I just saw that myself. I think the issue is it's a log_warn which is less noticeable when it should be a log_error.
