### ISSUE TITLE
Stack variable lifetimes

### ISSUE THREAD

**Issue by pgoodman** [Vector35/binaryninja-api#221]
It would be interesting if you could introduce a kind of lifetime annotation. For example, you mark an instruction to say that at this point, the lifetime of `var_X` ends, so appearances of `var_X` after the marked end-of-lifetime would be automatically renamed to `var_Y`.

**Comment by withzombies** [comment]
This would be useful for when two or more functions are inlined into the same caller or when the developer explicitly sub-scopes their code in a function.

```
void func()
{
	int var;
	{
		char *var2;
		// code here
	}
	
	{
		int var3;
		// code here
	}
}```

In this example, var2 and var 3 would occupy the same stack slot and IDA would treat them as a single type. It's quite frustrating, generally I deal with it by marking it as a union `union { char *var2; int var3; } v23;`

**Comment by plafosse** [comment]
This was actually fixed with the introduction of MLIL.
