### ISSUE TITLE
Don't show lexical control flow statements in graph view

### ISSUE THREAD

**Issue by whitequark** [Vector35/binaryninja-api#2211]
The `break`s here add, as far as I can tell, nothing:
![Screenshot_20210102_134642](https://user-images.githubusercontent.com/54771/103458521-f1fa8d00-4d00-11eb-8294-1916c98ca04f.png)

Conversely, on architectures that do have a `break` instruction, it's very easy to forget about the exact disassembler mode, mistake it for an instruction, and get really confused for a while. Doubly so when showing a screenshot of BN to someone not familiar with it.

**Comment by plafosse** [comment]
Though these may seem unnecessary they do show where loop exits are and can be very helpful. It also provides a way to link to the other ILs.

**Comment by whitequark** [comment]
Well that's a pretty obnoxious response.
