### ISSUE TITLE
Symbol simulation bug

### ISSUE THREAD

**Issue by sttacckz** [Vector35/binaryninja-api#2212]
Binary Ninja Version: 2.2.2487 Personal, e0eb0a77
Platform: macOS 10.16
ios app 
cpu:aarch64

103ee53e4  ff4300d1   sub     sp, sp, #0x10
103ee53e8  28bf9b52   mov     w8, #0xddf9
103ee53ec  08edae72   movk    w8, #0x7768, lsl #0x10  {0x7768ddf9}
103ee53f0  49098052   mov     w9, #0x4a
103ee53f4  e90b00b9   str     w9, [sp, #0x8 {var_8}]  {0x4a}
103ee53f8  690c8052   mov     w9, #0x63
103ee53fc  e90700b9   str     w9, [sp, #0x4 {var_c}]  {0x63}
103ee5400  e90b40b9   ldr     w9, [sp, #0x8 {var_8}]  {0x4a}
103ee5404  ea0740b9   ldr     w10, [sp, #0x4 {var_c}]  {0x63}
103ee5408  eb030032   orr     w11, wzr, #0x1
103ee540c  292d091b   madd    w9, w9, w9, w11  {0x1565}
103ee5410  ab248952   mov     w11, #0x4925
103ee5414  4b92a472   movk    w11, #0x2492, lsl #0x10  {0x24924925}
103ee5418  2b7dab9b   umull   x11, w9, w11
103ee541c  6bfd60d3   lsr     x11, x11, #0x20  {0x0}   **//x11= 0x30e**

**Comment by psifertex** [comment]
We currently do not handle double precision floating point in our dataflow system. The data you're seeing is the result of the umull instruction being unlifted. If you try again on the latest dev you'll see that the value isn't wrong but instead is marked as "undefined". This is the expected correct behavior with the current dataflow system unless we eventually enhance it to handle floating point will be how it will remian.

**Comment by psifertex** [comment]
To clarify, it now shows as undefined because the lifting has been corrected for that instruction along with many other recent enhancements to the armv7 and aarch64 lifting and disassembly.
