### ISSUE TITLE
Enabling Tail Call Translation Analysis Breaks For Embedded Functions

### ISSUE THREAD

**Issue by sabastiaan** [Vector35/binaryninja-api#2213]
**Tail Call Translation Analysis Breaks For Embedded Functions**
When enabling the Tail Call Translation, results obtained by accessing properties of `bv.Function` once a fall through function has been identified inside said function.
However it seems that every function embedded in another gets marked as such.

**To Reproduce**

1. Open any x64 binary with Tail Call Translation option enabled
2. Go to any identified function which has multiple instructions (__lib_c_init works), this will be referred to as the parent function
3. print out total bytes of the parent function `current_function.total_bytes`
4. create a function inside the parent function, let this function be called the child function
5. print out total bytes of the parent function, which should now show total bytes as parent.total_bytes - child.total_bytes

**Expected behavior**
The outcome should not change

**Screenshots**
![Screenshot from 2021-01-04 01-47-52](https://user-images.githubusercontent.com/5167125/103492969-e9a07000-4e2e-11eb-966c-64dd03cd3f8b.png)
No UI actions have been taken for this screen shot

**Desktop (please complete the following information):**

- OS: Ubuntu Linux
- Version 20.04
- Version 2.2.2587-dev

**Additional context**

Disabling the setting solves this problem

It also has the effect that once the child function is deleted, the bytes get marked as un-analyzed and not part of the parent function anymore 
But not 100% sure how to  reproduce this always

**Comment by plafosse** [comment]
As we understand this ticket this is intended behavior.

**Comment by sabastiaan** [comment]
I would feel that this behavior could lead to a lot of nasty situations. 
So this works if we assume all starting points of instructions are aligned, however this is not the case for variable length instruction encoded ISA's like x86-64

So currently it is possible to create a function at an offset that is unaligned with the instruction stream of an analyzed function like. 
![broken_tailcall1](https://user-images.githubusercontent.com/5167125/104031244-c67a1580-51cc-11eb-911a-ce0b2286eb6a.png)

Currently the new function gets disregarded and has no effect on the analysis of the parent function because it is on an un-aligned offset. This is inconsistent with the behavior shown in the first post of this issue. 
Even if we would reduce it down to "if the child function executes a sequence of instructions that the parent does, they get strictly attributed to the child and not the parent", then you will still have really un-intuitive behavior because the unaligned child function might converge to with the parent instruction stream in just 1 byte.  

Even if you decide to also let unaligned functions have effect on the parent instruction, then you only run into situations where total bytes are incorrect due to parts of instruction bytes not getting counted anymore.

 i.e if we have `f1`  that is only `41 5f c3`, and lets would create an extra user function `f2` at starts one byte into `f1`. Here `41 5f` and `5f` are a valid instruction,
Then `f2` would have total length 2 (`5f c3`), but `f1` would now have only length of 1, which is clearly not the case.

So either you end up with inconsistent behavior in analysis, or you end up with invalid analysis.

**Comment by bpotchik** [comment]
The second example output looks correct and intentional. The second example does not create a child function. In Binary Ninja overlapping functions are allowed and when doing so you can end up with separate and distinct analysis contexts. In second case I see 2 distinct functions. If the two functions happened to converge later in the instruction stream there there could potentially be new tailcall functions created, or shared basic blocks in the case of a shared epilogue.
