### ISSUE TITLE
UI enhancements

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#2217]
- [x] Main window refactor
- [x] SIdebar (ala VS Code sidebar which includes the new search capabilities from #1969 )
- [x] Being able to show strings/types besides the main views (similar to re
- [x] #2216

**Comment by stonedreamforest** [comment]
you can refer to the floating window design of windbg, it is highly customizable, any window can be moved to the position you want,

**Comment by psifertex** [comment]
We've talked about approaches like that, but I don't like that model actually. It's /too/ customizable and it's hard to get layouts looking good without an annoying amount of tweaking in my experience. Then on every new machine you have to do it all over. 

We are aiming for something a bit more opinionated such as Visual Studio's layout with a sidebar and some additional panes.

**Comment by stonedreamforest** [comment]
Some styles can be predefined, and users can adjust them at will according to their needs.  Visual studio can also adjust the position of the window at will

**Comment by psifertex** [comment]
Also need to solve #2574 with this

**Comment by D0ntPanic** [comment]
All major features of the UI refactor are now in build 3164
