### ISSUE TITLE
arm64 frame pointer tracking

### ISSUE THREAD

**Issue by withzombies** [Vector35/binaryninja-api#222]
It seems the arm64 frame pointer (x29) isn't marked properly as a frame pointer during stack variable recovery.

<img width="462" alt="screen shot 2016-04-11 at 10 27 40 am" src="https://cloud.githubusercontent.com/assets/4872355/14432327/a61d36ce-ffd7-11e5-86c2-9402400ac933.png">
<img width="458" alt="screen shot 2016-04-11 at 10 27 51 am" src="https://cloud.githubusercontent.com/assets/4872355/14432331/a82aeb14-ffd7-11e5-8df5-4908cdc3c173.png">

It also seems to get confused, on the first line it marks `x29` as `var_10` and that propagates throughout the program, but it really should be marked as something like `&var_10`.

**Comment by withzombies** [comment]
[example.arm64.zip](https://github.com/Vector35/binaryninja-api/files/213292/example.arm64.zip)

**Comment by plafosse** [comment]
This issue here is that we were not lifting the ldur/stur instruction variants. These have been added in dev.
