### ISSUE TITLE
allow calling conventions to opt-out of herustic detection

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#2230]
Certain calling conventions, (such as linux-syscall) are almost never found in "wild" code but are rather niche. When combined with some other circumstances this allows calling conventions to be heuristically guessed when they shouldn't be: 

See, eg: https://twitter.com/XMPPwocky/status/1345107559607275520

One short-term improvement to this is to explicitly exclude linux-syscall from heuristic detection. This feature will add an additional property for calling conventions to allow them to opt out and will explicitly opt-out linux-syscall. 

The convention will still work for type libraries and may be manually applied but should not be heuristically detected.

**Comment by CouleeApps** [comment]
This is done as of 2.2.2607
