### ISSUE TITLE
Constructing Platforms from python causes null deref

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#2231]
Repro case: `p=Platform(arch=Architecture['x86'])`

Seems to be because `self.__class__.name` is None on https://github.com/Vector35/binaryninja-api/blob/dev/python/platform.py#L104

Not sure what the intended behavior for this constructor should be. Possbly instead return `arch.standalone_platform` ?

**Comment by plafosse** [comment]
Platforms shouldn't be created like this. That interface is intended for subclasses of `Platform`. I've added some asserts in the python to prevent this and some checks in the core so we don't crash. And yes you should be using `arch.standalone_platform` Fixed in 2.4.3028
