### ISSUE TITLE
Defining a structure on the stack does not work unless it is done twice

### ISSUE THREAD

**Issue by jeffli678** [Vector35/binaryninja-api#2234]
If I define a variable that has a structure type, it will not work until I do the same thing twice. This is a regression, though the real problem is related to the actively developed dead-code elimination. 

When I define `var_58` to be type B for the first time, I get this:

![Screenshot from 2021-01-19 09-00-40](https://user-images.githubusercontent.com/3380590/104975153-d8fa1780-5a34-11eb-9041-07ea33f875b8.png)

When I define it a second time, it now works:

![Screenshot from 2021-01-19 09-01-43](https://user-images.githubusercontent.com/3380590/104975200-f7f8a980-5a34-11eb-9695-cdc26cc7d27e.png)

Structure B is defined as:

```
struct B
{
    char b1;
    uint64_t b2;
    bool b3;
};
```

And the assembly snippet is:

```
mov byte [rbp-0x50], 0x61
mov qword [rbp-0x48], 0x12345678
mov byte [rbp-0x40], 0x0
```

**Comment by ccarpenter04** [comment]
Great work debugging the issue effectively

**Comment by D0ntPanic** [comment]
Fixed in build 2646
