### ISSUE TITLE
Skipping analysis. Exceeds analysis.limits.maxFunctionUpdateCount

### ISSUE THREAD

**Issue by zackorndorff** [Vector35/binaryninja-api#2243]
I received the following log message `Skipping analysis for function at 0x1800c3b60 : Exceeds 'analysis.limits.maxFunctionUpdateCount'. If possible, please report this issue.`, so I'm reporting as the message requests.

Binary in question is Binja's own `cryptoplugin.dll`, as I was goofing around with the UI and happened to pick that binary to open up. Specifically, it's `Version 2.2.2615-dev (Build ID 5739b738)`, file sha256 `2D7A0BEAE0FAC3A5665238D79D75A135D5F981DE3EAA8A7AB9038CF89683C3B7`

System in question has `analysis.limits.maxFunctionUpdateCount` set to 100, which appears to be the default.

If I force analysis on that function, it does seem to loop for a long time, perhaps infinitely.

I'm only reporting this because the log message asked me to, I have no actual need to reverse the set of default transforms or whatever's implemented there :joy:

**Comment by bpotchik** [comment]
Fixed in `2.2.2616-dev`.
