### ISSUE TITLE
cleanup right-click menu

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#2246]
The current right-click menu in graph and linear view is far too easily cluttered and needs some re-organization.

**Comment by ccarpenter04** [comment]
I would like to see this happen.

**Comment by psifertex** [comment]
Good, it'll be coming in build 2620 and later so you should have it soon (though I'm currently fighting some unrelated build-server issues right now, so it might take a few builds for it finally goes live)

**Comment by bpotchik** [comment]
I think this still needs some work.
