### ISSUE TITLE
confusing behavior on updating function type

### ISSUE THREAD

**Issue by 3vilWind** [Vector35/binaryninja-api#2248]
It prints [rc_testcase.zip](https://github.com/Vector35/binaryninja-api/files/5882410/rc_testcase.zip) which looks like a race
```
int32_t main(int32_t arg1, char** arg2, char** arg3)
int32_t main()
```

**Comment by psifertex** [comment]
This is exactly expected behavior. You're making an analysis change in a background thread. If you would like to block after updating analysis, you'll need to use: https://api.binary.ninja/binaryninja.binaryview-module.html#binaryninja.binaryview.BinaryView.update_analysis_and_wait
