### ISSUE TITLE
Undoing function calling convention that causes platform load does not unload the platform

### ISSUE THREAD

**Issue by cryptwhoa** [Vector35/binaryninja-api#2251]
I used "Make Function at This Address" to make a windows-thumb2 function for the first time in a .bndb, which automatically added a bunch of Microsoft types to my types window.

When I undid the windows-thumb2 function, the Microsoft types stayed behind, and I couldn't delete them.

Using undo here should remove all of the new Microsoft types that got added.

**Comment by plafosse** [comment]
Our solution here will be to not show items in the types view which aren't currently being used. Closing in favor of #1883
