### ISSUE TITLE
String not detected as a string

### ISSUE THREAD

**Issue by Ayrx** [Vector35/binaryninja-api#2255]
I have a BNDB with the following string that isn't detected as a string:

![image](https://user-images.githubusercontent.com/1937160/106701615-e660f580-6621-11eb-9ad3-ce5f663395c5.png)

```
>>> bv.get_string_at(0x981324)
```

It does sound similar to #1298 but setting the `partial` flag to either `True` or `False` does nothing to change the results of the API.

The BNDB is too large to attach in this issue but I have uploaded it here: https://drive.google.com/file/d/1rroZJoN_GhqgALi1s08MfXciv-GZuHbo/view?usp=sharing

Version 2.2.2487 Personal (Build ID e0eb0a77)

**Comment by psifertex** [comment]
Short strings are intentionally excluded from auto discovery and you can either use this alternate API: https://api.binary.ninja/binaryninja.binaryview-module.html#binaryninja.binaryview.BinaryView.get_ascii_string_at

or change the minimum string length setting: https://docs.binary.ninja/getting-started.html#settings if you want short strings to appear in the strings list

**Comment by psifertex** [comment]
Thanks for the clear bug report, I'm going to close this but feel free to reopen or let me know if I have misunderstood!

**Comment by Ayrx** [comment]
Thanks for the quick reply!

With the default "Minimum String Length" setting of 4, both `get_ascii_string_at` and `get_string_at` returns `None`.

```
>>> bv.get_ascii_string_at(0x981324)
>>> bv.get_string_at(0x981324)
```

My use case is in an extension where I know that a specific pointer is a null terminated string. I would expect there to be an API to just do the "dumb" thing and read bytes till a null terminator. If that is supposed to be `get_ascii_string_at`, it would appear to be bugged at the moment. 

My current hacky workaround is the following function:

```
def read_string(bv, addr):
    ret = bv.get_string_at(addr)
    if ret:
        return str(ret)

    ret = b""
    cur = 0
    while True:
        b = bv.read(addr + cur, 1)
        ret += b
        cur += 1

        if b == b"\00":
            break

    return ret.decode()
```

**Comment by Ayrx** [comment]
And of course I should have looked at the docs for `get_ascii_string_at` before replying 😂 

Specifying the `min_length` param works:

```
>>> bv.get_ascii_string_at(0x981324, 1)
<StringType.AsciiString: 0x981324, len 0x3>
```

**Comment by 0xdevalias** [comment]
See also:

- https://github.com/Vector35/binaryninja-api/issues/5547
