### ISSUE TITLE
Feature Request: Function or structure level comment

### ISSUE THREAD

**Issue by Ayrx** [Vector35/binaryninja-api#2256]
It would be very useful to have the ability to set a comment at a function or structure level and have it show up in all of the Binary Ninja views. Similar to the idea of Ghidra's "Plate Comment" shown in the following screenshot:

![image](https://user-images.githubusercontent.com/1937160/106726428-52a12080-6645-11eb-9a49-7dd6800f3e3e.png)

(image taken from: https://byte.how/posts/what-are-you-telling-me-ghidra/)

**Comment by plafosse** [comment]
We do have function level comments, though they can't be set via the ui currently. 
``current_function.comment = "ASDFASDF"``

Additionally it seems like these function comments don't currently show up in HLIL.

**Comment by psifertex** [comment]
Here's a [snippet](https://gist.github.com/psifertex/6fbc7532f536775194edd26290892ef7#file-function_comment-py) you can use with the snippet manager (installable via the plugin manager) to bind to a hotkey if you want.
