### ISSUE TITLE
PDB Plugin - Applying PDB incorrectly types function symbols from the PDB

### ISSUE THREAD

**Issue by marpie** [Vector35/binaryninja-api#2277]
If using the default settings on the "Symbols" dock, most of the functions disappear after applying a PDB. It seems that the symbols are typed incorrectly.

## Steps to Reproduce

- Load `C:\Windows\System32\reset.exe`
- Apply PDB (from Symbol Server)
- Try to locate `main` in the *Symbols* dock

![image](https://user-images.githubusercontent.com/703785/108622070-b5acf880-7436-11eb-9823-df4286b111b2.png)

Binary Ninja Version: 2.2.2654-dev,  bb1563b
Platform: Windows 10 Version 2004

**Comment by bpotchik** [comment]
Duplicate symbol support now exists.

Fixed in 2.3.2731-dev.
