### ISSUE TITLE
List invalid/non-member struct accesses

### ISSUE THREAD

**Issue by nshp** [Vector35/binaryninja-api#2279]
Not sure what the UI for this would look like. Maybe show as a filterable property of type xrefs?

I want to quickly see all references to a given struct which are _not_ either the base of the structure or a defined member offset+size. Any time Binja shows its `struct.__offset(x).y`, I want to know in a quick overview.

**Comment by psifertex** [comment]
Tag class?

**Comment by nshp** [comment]
I had that thought as well, but that seems a bit more awkward. I don't want to see "every invalid struct access in the entire binary," I want "every invalid access to struct Foo in the entire binary."

**Comment by jeffli678** [comment]
implemented in dev 2.3.2785. Follow-up work is likely to improve it.
