### ISSUE TITLE
"Create function at symbol" does not refresh symbol name on undo

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#228]
Given an instruction like `call dword [0x40feb5]`, if `0x40feb5` is selected and `Create function at symbol (P)` is run on it, a function `sub_40feb5` is added to the function list, and all instances of `0x40feb5` in the assembly are changed to the symbol `sub_40feb5` (i.e. the previous call instruction becomes `call dword [sub_40feb5]`, as one would expect. However, when undoing this command, `sub_40feb5` is properly removed from the functions list, but the original instruction does not revert back to its original form, and remains as `call dword [sub_40feb5]`.

It looks like switching to a new function and then going back, or even just double clicking on the current function refreshes the symbol name, so it's not a major or incredibly inconvenient bug, just something I noticed.

**Comment by psifertex** [comment]
This is a specific instance of #102, closing as a dupe.
