### ISSUE TITLE
Xref Max Items Warning

### ISSUE THREAD

**Issue by bpotchik** [Vector35/binaryninja-api#2287]
Can we move this warning to some kind of informational message/label/widget inside the Xref pane?
<img width="991" alt="Screen Shot 2021-02-28 at 8 44 46 AM" src="https://user-images.githubusercontent.com/29309548/109421402-2c9d4080-79a5-11eb-95b6-fefae444787c.png">

**Comment by psifertex** [comment]
Suggestions for this:

1) Make the limit of 1000 configurable via user-setting with a default of 1000
2) Don't make a log_warn but instead just add an extra item at the end of the xref list that mentions that more items exist but aren't shown as the list truncates.

**Comment by jeffli678** [comment]
That’s exactly the plan! I will do it once I get search enhancement done.
