### ISSUE TITLE
Python API leads to Crashes

### ISSUE THREAD

**Issue by itsacoderepo** [Vector35/binaryninja-api#229]
My system is an x64 Arch.

Using the python API i get (more or less random) crashes: 
$ python2 bininfo.py 
['__doc__', '__init__', '__module__', 'index']
Speicherzugriffsfehler (Speicherabzug geschrieben)
$ python2 bininfo.py 
['__doc__', '__init__', '__module__', 'index']
Speicherzugriffsfehler (Speicherabzug geschrieben)

Sometimes ( and other..):
$ python2 bininfo.py 
['__doc__', '__init__', '__module__', 'index']
*** Error in `python2': free(): invalid pointer: 0x00007f23080094f0 ***
======= Backtrace: =========
/usr/lib/libc.so.6(+0x6f364)[0x7f2315e9f364]

This is the python script:

```
#!/usr/bin/env python
import sys, binaryninja, time
bintype="ELF"
target = "/bin/ls"
bv = binaryninja.BinaryViewType[bintype].open(target)
bv.update_analysis()
print dir(binaryninja.LowLevelILExpr(target))

```

I have more crashes (ATM 28) if you need more info

$ coredumpctl list
So 2016-04-17 17:07:02 CEST   17970  1000  1000  11 * /usr/bin/python2.7
So 2016-04-17 17:07:03 CEST   17988  1000  1000  11 * /usr/bin/python2.7
So 2016-04-17 17:07:40 CEST   18093  1000  1000  11 * /usr/bin/python2.7
So 2016-04-17 17:07:40 CEST   18103  1000  1000  11 * /usr/bin/python2.7

$ coredumpctl gdb 18093
           PID: 18093 (python2)
           UID: 1000 (nope)
           GID: 1000 (nope)
        Signal: 11 (SEGV)
     Timestamp: So 2016-04-17 17:07:40 CEST (4min 43s ago)
  Command Line: python2 bininfo.py
    Executable: /usr/bin/python2.7
 Control Group: /
         Slice: -.slice
       Boot ID: 166a8b82451c42098133bcc683633830
    Machine ID: f2d6555e417e4c3cbfef6f994e7db83a
      Hostname: nope
      Coredump: /var/lib/systemd/coredump/core.python2.1000.166a8b82451c42098133bcc683633830.18093.1460905660000000000000.lz4
       Message: Process 18093 (python2) of user 1000 dumped core.
                
                Stack trace of thread 18096:
                #0  0x00007f50500050a0 n/a (n/a)

[...] (gdb stuff)
warning: core file may not match specified executable file.
[New LWP 18096]
[New LWP 18094]
[New LWP 18093]
[New LWP 18095]

warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `python2 bininfo.py'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f50500050a0 in ?? ()
[Current thread is 1 (Thread 0x7f5057ca7700 (LWP 18096))]
> bt
#0  0x00007f50500050a0 in ?? ()
#1  0x00007f505b6ee474 in std::function<void ()>::function(std::function<void ()> const&) () from ~/binaryninja/python/binaryninja/../../libbinaryninjacore.so.1
#2  0x00007f505b70be43 in ?? () from ~/binaryninja/python/binaryninja/../../libbinaryninjacore.so.1
#3  0x00007f505b6ee474 in std::function<void ()>::function(std::function<void ()> const&) () from ~/binaryninja/python/binaryninja/../../libbinaryninjacore.so.1
#4  0x00007f505b6ecef9 in ?? () from ~/binaryninja/python/binaryninja/../../libbinaryninjacore.so.1
#5  0x00007f505b3c6c40 in std::(anonymous namespace)::execute_native_thread_routine (__p=<optimized out>) at /build/gcc-multilib/src/gcc-5-20160209/libstdc++-v3/src/c++11/thread.cc:84
#6  0x00007f505eee8424 in start_thread () from /usr/lib/libpthread.so.0
#7  0x00007f505ec27cbd in clone () from /usr/lib/libc.so.6

>i r
rax            0x7f50500050a0	139982916309152
rbx            0x7f50480008c0	139982782073024
rcx            0x7f5048000020	139982782070816
rdx            0x2	2
rsi            0x7f5050005070	139982916309104
rdi            0x7f50480008c0	139982782073024
rbp            0x7f5050005070	0x7f5050005070
rsp            0x7f5057ca6e28	0x7f5057ca6e28
r8             0x7f50480008e0	139982782073056
r9             0x30	48
r10            0x1	1
r11            0x1	1
r12            0x7f5050005070	139982916309104
r13            0x7f5057ca6e90	139983046995600
r14            0x3	3
r15            0x55888ea650d0	94044997177552
rip            0x7f50500050a0	0x7f50500050a0
eflags         0x10206	[ PF IF RF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0

$ coredumpctl gdb 17919 
           PID: 17919 (python2)
           UID: 1000 (nope)
           GID: 1000 (nope)
        Signal: 11 (SEGV)
     Timestamp: So 2016-04-17 17:07:00 CEST (14min ago)
  Command Line: python2 bininfo.py
    Executable: /usr/bin/python2.7
 Control Group: /
         Slice: -.slice
       Boot ID: 166a8b82451c42098133bcc683633830
    Machine ID: f2d6555e417e4c3cbfef6f994e7db83a
      Hostname: nope
      Coredump: /var/lib/systemd/coredump/core.python2.1000.166a8b82451c42098133bcc683633830.17919.1460905620000000000000.lz4
       Message: Process 17919 (python2) of user 1000 dumped core.
                
                Stack trace of thread 17922:
                #0  0x00007fe471782e51 n/a (libbinaryninjacore.so.1)
                #1  0x00007fe471765474 _ZNSt8functionIFvvEEC2ERKS1_ (libbinaryninjacore.so.1)
                #2  0x00007fe471763ef9 n/a (libbinaryninjacore.so.1)
                #3  0x00007fe47143dc40 execute_native_thread_routine (libstdc++.so.6)
                #4  0x00007fe474f5f424 start_thread (libpthread.so.0)
                #5  0x00007fe474c9ecbd __clone (libc.so.6)
                
                Stack trace of thread 17921:
                #0  0x00007fe474c2c45b _int_free (libc.so.6)
                #1  0x00007fe471777253 n/a (libbinaryninjacore.so.1)
                #2  0x00007fe471777247 n/a (libbinaryninjacore.so.1)
                #3  0x00007fe471777247 n/a (libbinaryninjacore.so.1)
                #4  0x00007fe471777247 n/a (libbinaryninjacore.so.1)
                #5  0x00007fe471777247 n/a (libbinaryninjacore.so.1)
                #6  0x00007fe47176d0fa n/a (libbinaryninjacore.so.1)
                #7  0x00007fe4717752c4 n/a (libbinaryninjacore.so.1)
                #8  0x00007fe471769a31 n/a (libbinaryninjacore.so.1)
                #9  0x00007fe471782c97 n/a (libbinaryninjacore.so.1)
                #10 0x00007fe471763f64 n/a (libbinaryninjacore.so.1)
                #11 0x00007fe47143dc40 execute_native_thread_routine (libstdc++.so.6)
                #12 0x00007fe474f5f424 start_thread (libpthread.so.0)
                #13 0x00007fe474c9ecbd __clone (libc.so.6)
                
                Stack trace of thread 17920:
                #0  0x00007fe474f67e4c __lll_lock_wait (libpthread.so.0)
                #1  0x00007fe474f61ab5 pthread_mutex_lock (libpthread.so.0)
                #2  0x00007fe471763cdd n/a (libbinaryninjacore.so.1)
                #3  0x00007fe47143dc40 execute_native_thread_routine (libstdc++.so.6)
                #4  0x00007fe474f5f424 start_thread (libpthread.so.0)
                #5  0x00007fe474c9ecbd __clone (libc.so.6)
                
                Stack trace of thread 17919:
                #0  0x00007fe47370ffa0 n/a (libk5crypto.so.3)

Reading symbols from /usr/bin/python2.7...(no debugging symbols found)...done.

warning: core file may not match specified executable file.
[New LWP 17922]
[New LWP 17921]
[New LWP 17920]
[New LWP 17919]

warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `python2 bininfo.py'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fe471782e51 in ?? () from ~/binaryninja/python/binaryninja/../../libbinaryninjacore.so.1
[Current thread is 1 (Thread 0x7fe46dd1e700 (LWP 17922))]

> bt
#0  0x00007fe471782e51 in ?? () from ~/binaryninja/python/binaryninja/../../libbinaryninjacore.so.1
#1  0x00007fe471765474 in std::function<void ()>::function(std::function<void ()> const&) () from ~/binaryninja/python/binaryninja/../../libbinaryninjacore.so.1
#2  0x00007fe471763ef9 in ?? () from ~/binaryninja/python/binaryninja/../../libbinaryninjacore.so.1
#3  0x00007fe47143dc40 in std::(anonymous namespace)::execute_native_thread_routine (__p=<optimized out>) at /build/gcc-multilib/src/gcc-5-20160209/libstdc++-v3/src/c++11/thread.cc:84
#4  0x00007fe474f5f424 in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007fe474c9ecbd in clone () from /usr/lib/libc.so.6
> i r
rax            0x0	0
rbx            0x7fe46dd1dea0	140619071741600
rcx            0x7fe464000020	140618906992672
rdx            0x556900000007	93909459927047
rsi            0x7fe468009500	140618974139648
rdi            0x7fe4640008c0	140618906994880
rbp            0x7fe4640008c0	0x7fe4640008c0
rsp            0x7fe46dd1de50	0x7fe46dd1de50
r8             0x7fe4640008e0	140618906994912
r9             0x30	48
r10            0x1	1
r11            0x1	1
r12            0x7fe468009500	140618974139648
r13            0x7fe46dd1de90	140619071741584
r14            0x3	3
r15            0x5569d40e40d0	93913017630928
rip            0x7fe471782e51	0x7fe471782e51
eflags         0x10202	[ IF RF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0

**Comment by itsacoderepo** [comment]
Even with a (suggested) sleep, one das only needs a larger binary:

```
[...]
$ python2 bininfo.py 
['__doc__', '__init__', '__module__', 'index']
Speicherzugriffsfehler (Speicherabzug geschrieben)
$ python2 bininfo.py 
['__doc__', '__init__', '__module__', 'index']
$ python2 bininfo.py 
['__doc__', '__init__', '__module__', 'index']
$ cat bininfo.py 
#!/usr/bin/env python
import sys, binaryninja, time
bintype="ELF"

target = "~/binaryninja/binaryninja"
bv = binaryninja.BinaryViewType[bintype].open(target)
bv.update_analysis()
time.sleep(1)
print dir(binaryninja.LowLevelILExpr(target))
```

**Comment by psifertex** [comment]
Yeah, the sleep needs to be larger than 1s for larger binaries. The sleep is very temporary until we have the proper blocking call implemented. 

As for the crash, I'll look into it, though arch isn't one of the platforms we plan to officially support.

**Comment by psifertex** [comment]
We can reproduce the crash just fine on other operating systems, looks like a race condition when the analysis is in some specific state apparently. Will let you know when we resolve it.

Once we do have the blocking update call it shouldn't crash like that, but we'll look into the crash regardless since it might be possible to trigger via some other asynchronous behavior even once we have that.

**Comment by iambrosie** [comment]
Hi,
I'm running Ubuntu 14.04.4 LTS here, and experience the same issue with the Python API.

**Comment by plafosse** [comment]
Fixed
