### ISSUE TITLE
Lingering Python2 reference in linux-setup.sh

### ISSUE THREAD

**Issue by jeffalau** [Vector35/binaryninja-api#2290]
```
if [[ -x "`which python`" ]]
then
 	python -V >/dev/null 2>&1 && ${SUDO}python "${BNPATH}/scripts/install_api.py" ${ROOT} ${SILENT}
fi
```

Because this snippet is still executed, it causes an error when `core_version()` is called in install_api.py. Recommend removing snippet.

There error I get is:
```
Traceback (most recent call last):
  File "/home/user/Downloads/binaryninja/scripts/install_api.py", line 68, in <module>
    while not validate_path(api_path):
  File "/home/user/Downloads/binaryninja/scripts/install_api.py", line 60, in validate_path
    print("Found Binary Ninja core version: {}".format(core_version()))
TypeError: 'str' object is not callable
```

**Comment by psifertex** [comment]
Thanks. Removed whenever the next dev build comes out. (Not going to trigger a new build since you can just grab it directly if you need it: https://github.com/Vector35/binaryninja-api/blob/dev/scripts/linux-setup.sh )

**Comment by Frankenstein-bit** [comment]
> Thanks. Removed whenever the next dev build comes out. (Not going to trigger a new build since you can just grab it directly if you need it: https://github.com/Vector35/binaryninja-api/blob/dev/scripts/linux-setup.sh )

hi,i meet the same error on windows,how should i do

**Comment by psifertex** [comment]
Just manually create a PTH file that points to your install location. That's essentially all this script does. 

https://stackoverflow.com/a/700394

**Comment by psifertex** [comment]
Also to be clear, you shouldn't be running the linux setup on windows. I assume you meant you got that error running the install api script which is what my answer above is about.
