### ISSUE TITLE
Allow Overriding Platform Load Setting for ELF, Mach-O, and PE Files

### ISSUE THREAD

**Issue by nshp** [Vector35/binaryninja-api#2291]
e.g. I want to override just the Platform for an ELF. "Open With Options" says it (and most other load options) are read-only.

Just realized I can do `bv.platform = Platform['x']` for that case after the fact, but then I have to fix up every function's calling convention. It doesn't look like it's quite all the way applied my change.

**Comment by bpotchik** [comment]
Added in `2666-dev`.
