### ISSUE TITLE
python callback for update analysis and wait call that blocks

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#230]
Looking through the bugs I just realized we don't have an issue for this already though we've mentioned it a few times and plan on resolving it. 

There is currently no reliable way to script up the python API on large binaries for calls that require analysis without long sleeps after calling `update_analysis`. This is due to the 

This is due to the mult-threaded nature of the analysis.

The proper fix is a blocking call or a callback upon completion of analysis so the rest of the plugin can continue.

**Comment by psifertex** [comment]
blocking on #272

**Comment by D0ntPanic** [comment]
Fixed in dev with the `update_analysis_and_wait` API.
