### ISSUE TITLE
Broken argument detection

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#2307]
Win 10 Personal 2673-dev

I see the following argument list when analyzing a bndb. I'd add more context to the title, but I have no idea what happening here.

```
int64_t* smc_entry_path(int32_t arg1, char* arg2, int64_t arg3, int64_t arg4, int64_t arg5, int64_t arg6, int64_t* arg7, int32_t arg8, void arg9 @ )

void arg9
void 
int32_t arg1  {Register x0}
int64_t* x0  {Register x0}
int64_t* x0_2  {Register x0}
char* arg2  {Register x1}
int64_t arg3  {Register x2}
int64_t arg4  {Register x3}
int64_t arg5  {Register x4}
int64_t arg6  {Register x5}
int64_t* arg7  {Register x6}
int32_t arg8  {Register x7}
int64_t* x8  {Register x8}

smc_entry_path:
0e032014  e903002a   mov     w9, w0
...
```

Notably arg9 lives nowhere, and there is a mysterious void under it. bndb is attached.

[id3-cleaner - Copy.zip](https://github.com/Vector35/binaryninja-api/files/6106138/id3-cleaner.-.Copy.zip)

**Comment by D0ntPanic** [comment]
This is not an analysis or core bug. This is a bug in the architecture plugin.

See https://github.com/Vector35/arch-arm64/issues/80 for the actual issue here.
