### ISSUE TITLE
Limits of analysis doesn't work

### ISSUE THREAD

**Issue by MGYN** [Vector35/binaryninja-api#2309]
From [#908](https://github.com/Vector35/binaryninja-api/issues/908), you had added the new options to limit the analysis. But we test that it doesn't work as wished.

Such as **analysis.limits.maxFunctionAnalysisTime**，we set the time arbitrarily and test the results, but we got lots of functions with analysis more than **0.00002**, the code shows:
`bv = BinaryViewType.get_view_of_file_with_options(bndb_file_path, update_analysis=True,
options={"analysis.limits.maxFunctionAnalysisTime":0.00002})
    for func in   ##bv.functions:
        print(func.analysis_performance_info.values())`
and the partial results is that:

> dict_values([0.00223859])
dict_values([0.001841212])
dict_values([0.007671538])
dict_values([0.001371252])
dict_values([0.004085607])
dict_values([0.008869185])
dict_values([0.003579045])
dict_values([0.00389014])

and we got the same numbers of functions(**4897**) and total analysis time(**73s**) with the analysis without limits.

Such as **analysis.limits.maxFunctionSize**，we set the size arbitrarily and test the results, but we got lots of functions with size more than **30**, the code shows:
`    bv = BinaryViewType.get_view_of_file_with_options(bndb_file_path, update_analysis=True,
options={"analysis.limits.maxFunctionSize":30})
    for func in bv.functions:
        print(func.analysis_skipped)
        print(func.total_bytes)`
and the partial results is that:

> False
30
True
34
False
26
True
96
False
30

and we got more numbers of functions(**5860**) and less total analysis time(**17s**) with the analysis without limits.

But when we got the **disassembly_text** of each basic block, we found there is a great difference between limited analysis and unlimited analysis, and the function name is odd and lots **disassembly_text** of the block is meaningless or wrong compared with the correct disassembly text.
and some functions name like this:

> sub_1f17c4
sub_1f17d4
sub_1f17f4
sub_1f1804
sub_1f1824
sub_1f1844
sub_1f1af4
sub_1f1c84
sub_1f1ca4
sub_1f1cc4
sub_1f1ce4
sub_1f1d04

We aim to analyze a mass of ".so" files in apps and get the disassembly text of every block. Because we've run into situations where analysis takes up a lot of time and we want to jump these files or only jump the timeout function and get correct disassembly text, so we try to add some limits during analysis. Some files with the size of **2M** take up more than **2000** seconds and some are **7M** only take up **300** seconds. So we can't know in advance which ones will take more time from the size of the file without analysis. 

We tried some timeout monitoring like _eventlet_ and _signal_ in python, but it doesn't work until the analysis is done. And the added options in [#908](https://github.com/Vector35/binaryninja-api/issues/908) seem doesn't work as wishes.
Are there any good methods? Or is there something wrong with my implementation?
If so, please give an example to guide me on what to do, thanks!

**Comment by bpotchik** [comment]
Please have a look at the`analysis.mode` setting.


![Screen Shot 2021-03-11 at 7 48 09 AM](https://user-images.githubusercontent.com/29309548/110789674-24af8d00-823e-11eb-97ab-bad07b6072fb.png)

Please keep in mind that a setting like `analysis.limits.maxFunctionAnalysisTime` is a best effort type of limit. Analysis of a function that exceeds that limit will be halted, once the analysis reaches the next checkpoint. The analysis time for a function with a time limit will be n (limit) + ε (some small additional time).

As far as for the size. The rational is very similar. The maxFunctionSize limit is used to limit the size of a function that Binary Ninja will analyze and decompile. For example, I set a limit to 30 bytes, and main is 44 bytes the following output would be realized:

```
>>> current_function.total_bytes
44
>>> current_function.analysis_skip_reason
<AnalysisSkipReason.ExceedFunctionSizeSkipReason: 2>
```

**Comment by MGYN** [comment]
Thanks! It is very useful, and I want to try some other limits. But I can't find the detailed description of each limit as you showed above in [Python API](https://api.binary.ninja/binaryninja.settings-module.html). Such as the optional parameters of **analysis.mode**. So where can I get it including the other limits?

**Comment by bpotchik** [comment]
Open SettingsView in the UI. You can open it via menu or Cmd or Ctrl +.

The Settings are also documented online in the getting started guide.

**Comment by plafosse** [comment]
This issue seems to be resolved.
