### ISSUE TITLE
Copy doesn't work from floating Python console

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#2310]
If python console is floating copy "CMD+C" or Right Click->"Copy" doesn't work. Work around is to dock the console and then copy will work.

**Comment by kristopax** [comment]
I just tested this issue out to confirm its behavior.  I can copy from the command line of the python console.  I cannot copy from the console output though. Just FYI (edited)

**Comment by fuzyll** [comment]
After 3.0, I don't even think it's possible to pop the Python Console out into a separate window now? At least, I just tried to do it a bunch of different ways and none of them worked. So, problem fixed! :tada: _Monkey's paw curls..._
