### ISSUE TITLE
double clicking an enum value should take you to the enumeration 

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#2312]
<img width="536" alt="Screen Shot 2021-03-11 at 3 49 52 PM" src="https://user-images.githubusercontent.com/140215/110853261-6c0b3d00-8281-11eb-9c9b-844cc141ba06.png">

Double clicking "grey" should take me to:
<img width="490" alt="Screen Shot 2021-03-11 at 3 50 23 PM" src="https://user-images.githubusercontent.com/140215/110853326-7f1e0d00-8281-11eb-8734-85c2901e2e05.png">

**Comment by plafosse** [comment]
Fixed in 3.4.4294
