### ISSUE TITLE
Give auto-analysis progress somewhere

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#232]
Loading a larger binary (xnu kernel for example) pegs my cpu. This makes sense, as it's a good amount of code. However, it would be nice if I could see a status somewhere (i.e. 400/87219 functions, 25%, 100k/10mb, etc) or at least an indication that work was happening, other than my fans spinning more.

**Comment by psifertex** [comment]
blocking on #272

**Comment by D0ntPanic** [comment]
Implemented in dev
