### ISSUE TITLE
MLIL → HLIL lifting drops conditional call to __noreturn function on ARMv7

### ISSUE THREAD

**Issue by tchebb** [Vector35/binaryninja-api#2320]
Minimal repro, save as `main.s`:
```
.global _start
_start:
    bl maybe_call_spin

  1:
    @ Not needed for repro, just spin so the function ends.
    b 1b

.global maybe_call_spin
maybe_call_spin:
    cmp r0, #0
    moveq r0, #1
    @ This call gets dropped in HLIL.
    bleq spin
mov pc, lr

.global spin
spin:
    b spin
```
Compile:
```
$ arm-none-eabi-gcc -nostdlib -o main main.s
```
Open `main` in Binary Ninja (I'm testing with version 2.3.2679-dev), view MLIL:
![MLIL](https://user-images.githubusercontent.com/1082640/111084997-a841d600-84eb-11eb-8677-13804ba47316.png)
Then view HLIL:
![HLIL](https://user-images.githubusercontent.com/1082640/111085007-aed04d80-84eb-11eb-8d75-0167eb37403d.png)

Observe that the conditional call to `spin()` inside `maybe_call_spin()` has completely disappeared!

This may be related to Vector35/arch-armv7@3e9f6c2fc7d732994efcc85bd710df45b30af0e2, as I previously reported a bug in Slack for which that commit was a fix and remember seeing this behavior show up right after.

**Comment by tchebb** [comment]
After playing around a bit more, turns out the `moveq r0, #1` before the problematic call is unnecessary as well. I'd initially thought this was some sort of issue with the ARMv7 conditional coalescing, but now I think what's happening is that HLIL is eliding `spin()` because it has no side effects and doesn't return a result that gets used. However, the fact that it doesn't return is itself a side effect and so needs to be preserved.

**Comment by D0ntPanic** [comment]
Fixed in build 2688
