### ISSUE TITLE
Function pointer xref not showing up

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#2323]
Win10  2682

![image](https://user-images.githubusercontent.com/8716677/111556257-57c6b480-8747-11eb-9122-155b87b2eb55.png)

![image](https://user-images.githubusercontent.com/8716677/111556322-82b10880-8747-11eb-9610-dfcc9b693239.png)

Screenshots are from the same bndb. I can click on the function in the struct and go to it, but the xrefs are empty. I'd expect an xref for each struct element that references the function.

**Comment by jeffli678** [comment]
I investigated this bug but I failed to reproduce it. I would appreciate it if one can provide a binary that can reproduce this issue. 

Labeling it as "Can't reproduce" simply mean we have some difficulties reproducing it and need more input. We believe the bug does happen on the user end.

**Comment by yrp604** [comment]
[id3-cleaner - Copy.zip](https://github.com/Vector35/binaryninja-api/files/6226162/id3-cleaner.-.Copy.zip)

Sure, attached the bndb. You can get the relevant addresses/functions from the screenshots. Feel free to drop me a line on slack if you still have trouble.

**Comment by jeffli678** [comment]
repro confirmed. I will troubleshoot it and fix it

**Comment by jeffli678** [comment]
The issue is related to the field that has type `uint8_t`. Its probably something related to padding
