### ISSUE TITLE
Display and provide UI for creation of Function-level comments.

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#2325]
Function objects can have comments. These however aren't shown in HLIL and there is no way to actually set a function comment via the UI.

**Comment by ptechofficial** [comment]
Hey, i am a beginner at open source contributions. What am i supposed to work on?

**Comment by plafosse** [comment]
This would be a great question for the discussions section: https://github.com/Vector35/binaryninja-api/discussions/new

**Comment by CouleeApps** [comment]
This can now be accomplished by setting a function on the line with the function header in 2.4.2900-dev.
