### ISSUE TITLE
Display the width of enums / document enum width parsing

### ISSUE THREAD

**Issue by multun** [Vector35/binaryninja-api#2326]
The type view doesn't show the width of enums. Setting the width of an enum from the GUI also isn't documented.

For example, the `enum e_type` ELF type has a width of 16 bits, but this isn't shown anywhere. After much trying, I found out that you can set the size of enums using a C++ like syntax:

```c++
enum test : int16_t { 
    VAL
};
```

Because of the missing pretty print, the UI only shows this once the type has been parsed:

```c++
enum test { 
    VAL
};
```

I really wish it were documented somewhere, and displayed: I only found this feature because I got lucky, and copy pasting types doesn't work because of this missing annotation (structures don't have the intended size anymore)

**Comment by negasora** [comment]
Added in 2.3.2692-dev
