### ISSUE TITLE
Download provider: 'PythonDownloadProvider' not available!

### ISSUE THREAD

**Issue by 0x00fy** [Vector35/binaryninja-api#2327]
Please help me. im using 2.3 version of Binary Ninja. When the binary ninja is opened, I get the following error:

Failed to find suitable libpython! Specified python library does not exist: 
Download provider: 'PythonDownloadProvider' not available!Download provider: 'PythonDownloadProvider' not available!

My os : Linux 0x00fy 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
(LİNUX MİNT 20.1)

**Comment by bpotchik** [comment]
Open up Settings View and either reset the setting (right click), or select a new compatible interpreter.

**Comment by 0x00fy** [comment]
> Open up Settings View and either reset the setting (right click), or select a new compatible interpreter.
> 
> <img alt="Screen Shot 2021-03-20 at 11 22 32 AM" width="696" src="https://user-images.githubusercontent.com/29309548/111875158-ba4dc980-896e-11eb-9997-be29169c4799.png">

Thank you sir Successfully Running Now.
