### ISSUE TITLE
Database corruption on 2.3.2660

### ISSUE THREAD

**Issue by multun** [Vector35/binaryninja-api#2329]
```
Error while reading snapshot from database: Exception while parsing json.
Persistent analysis data may be incomplete
```

This error has occurred multiple times while working on the same file. Each time, most of the analysis work was lost 

Here's the corrupted database :
[corrupted.zip](https://github.com/Vector35/binaryninja-api/files/6189349/corrupted.zip)

**Comment by negasora** [comment]
Thanks for the report, there will be a fix out soon with 2.3.2691-dev. You can switch to the dev channel via `Edit > Preferences > Update Channel`
