### ISSUE TITLE
Freeze when navigating and quitting with unfinished auto-analysis

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#233]
If you load up larger binary (again, xnu kernel), let the auto-analysis run for a while, then start clicking around, some functions will fail to display ('Loading...' forever). I notice that before this happens the cpu usage dips, then spikes back up, and it usually seems to be more time related than activity related. Once you get 'Loading...', even navigating back to functions you've previously view wont work (you still get 'Loading...', but the xrefs do update/change).

Once you're in the dreaded 'Loading...' state, quitting the application will just hang, requiring you to kill the process.

**Comment by psifertex** [comment]
blocking on #272

**Comment by D0ntPanic** [comment]
Fixed in dev
