### ISSUE TITLE
Placeholder text is incorrectly colored (nearly invisible) under Qt 6

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/binaryninja-api#2331]
Notice the "Search Settings..." text appears to be missing since it is almost the same color as the field background.

### Before (Qt 5)
![qt5](https://user-images.githubusercontent.com/41548458/112187825-d0f75900-8bd8-11eb-9de0-382014ddba45.png)

### After (Qt 6)
![qt6](https://user-images.githubusercontent.com/41548458/112188094-14ea5e00-8bd9-11eb-86f8-75e825c06445.png)

**Comment by jonpalmisc** [comment]
Update: Seems to affect dark themes and not light ones - my own light theme as well as the default light & solarized light themes are not affected.

**Comment by jonpalmisc** [comment]
Update 2: This seems to affect all placeholder text, and can also be observed in the snippets plugin description field.

**Comment by jeffli678** [comment]
This seems more like a Qt bug to me, though we can use `QPalette::PlaceholderText` to explicitly specify the color of tool tip texts. Also, the color of these buttons in the xref widget is also buggy:

![Screenshot from 2021-04-01 12-08-07](https://user-images.githubusercontent.com/3380590/113242191-f116ce80-92e2-11eb-9d4d-8e93b2f656de.png)

**Comment by jonpalmisc** [comment]
Fixed in build 2865.
