### ISSUE TITLE
Plugin manager "enable/disable" flow is broken

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/binaryninja-api#2334]
## Summary

The enable/disable button text does not stay in sync with the plugin's enabled/disabled state. Furthermore, once you accidentally disable the plugin due to the misleading text, you cannot re-enable it. I'm unsure whether this is a Qt 6 issue, but I'm pretty sure this hasn't always happened.

## Steps to reproduce

1. Open the plugin manager and find an uninstalled plugin
2. Install it (the plugin should be automatically enabled)
3. Despite being enabled, notice that the enable/disable button still says "Enable" (see first screenshot)
4. Click the (incorrect) "Enable" button, notice that this disables the plugin
5. Click the (incorrect) "Enable" button again, notice that this does not enable the plugin. The log will say "plugin already installed"; see third screenshot.

![step-2](https://user-images.githubusercontent.com/41548458/112508598-15642f80-8d66-11eb-865f-4ecefb5457e1.png)
![step-3](https://user-images.githubusercontent.com/41548458/112508869-51979000-8d66-11eb-824a-0b4fbb59a770.png)
![step-4](https://user-images.githubusercontent.com/41548458/112509223-a5a27480-8d66-11eb-8cb5-00dabb7b68a7.png)

## System & build info

Binary Ninja 2.3.2695-qt6, 8f2ca998 on Ubuntu 20.04.2 LTS (also reproduced on Windows Qt 6 branch)

**Comment by plafosse** [comment]
Fixed in 2.3.2763
