### ISSUE TITLE
Error installing colorama for Debugger plugin. Windows 10 x64 20H2

### ISSUE THREAD

**Issue by macjohnmcc** [Vector35/binaryninja-api#2336]
Binary Ninja Version: 2.3.2698-dev Personal, 5fbc89db
Platform: Windows 10 Version 2009

When I tried to install the debugger plugin it told me I needed colorama and I told it to install it. The debugger plugin remains disabled and I saw a red X and 7 displayed in the status bar so I clicked it and saw this:

`Loaded UI plugin triage
Exception ignored on calling ctypes callback function: <bound method PythonScriptingProvider._install_modules of <binaryninja.scriptingprovider.PythonScriptingProvider object at 0x0000026389CB9850>>
Traceback (most recent call last):
  File "C:\Program Files\Vector35\BinaryNinja\plugins\..\python\binaryninja\scriptingprovider.py", line 918, in _install_modules
    python_bin, status = self._get_executable_for_libpython(python_lib, python_bin_override)
  File "C:\Program Files\Vector35\BinaryNinja\plugins\..\python\binaryninja\scriptingprovider.py", line 904, in _get_executable_for_libpython
    python_bin = Path(get_install_directory()) / "plugins\\python\\python.exe"
NameError: name 'get_install_directory' is not defined
Successfully installed plugin: Debugger
Loaded python3 plugin 'Vector35_debugger'
Successfully disabled: Debugger
`

**Comment by psifertex** [comment]
Replied via email as well, but putting the answer here for others:

Are you using the latest dev? The latest dev will actually install the dependencies for you automatically. Check your update channel. https://docs.binary.ninja/getting-started.html#updates

The other issue is probably that the python that Binary Ninja is using is not the one you pip installed the dependencies to. You can check that by checking your settings (CMD/CTL + , ) and searching for "python" to see the python interpreter (or this exact setting name: https://docs.binary.ninja/getting-started.html#python.interpreter). Just change to the python version that matches where you installed the dependency.

**Comment by psifertex** [comment]
Oh, nevermind, reading your message more closely it looks like you are running a development build since stable can't auto-install dependencies. That said, the advice about switching to the python that you manually installed the dependency for is still valid, but it should automatically install the dependency for you. Let me double check on a windows VM to see if I can replicate that error.

**Comment by psifertex** [comment]
Ahh, found the culprit. Thanks for reporting this! New build is underway and should be live in a few hours on the update server. Builds 2699 and above should work on windows to automatically install the dependency for you.
