### ISSUE TITLE
Error trying to enable debug plugin -- colorama install failure (plugin manager)

### ISSUE THREAD

**Issue by macjohnmcc** [Vector35/binaryninja-api#2337]
Binary Ninja Version: 2.3.2700-dev Personal, 2cb0d17c
Platform: Windows 10 Version 2009

Loaded native plugin pythonplugin
Loaded UI plugin triage
Running pip ['C:\\Program Files\\Vector35\\BinaryNinja\\plugins\\python\\python.exe', '-m', 'pip', '--isolated', '--disable-pip-version-check', 'install', '--verbose', 'colorama']
Error while attempting to install requirements Command '['C:\\Program Files\\Vector35\\BinaryNinja\\plugins\\python\\python.exe', '-m', 'pip', '--isolated', '--disable-pip-version-check', 'install', '--verbose', 'colorama']' returned non-zero exit status 120.
Failed to install plugin dependencies:
colorama

Check the log for more details

I ran the following command line after the fact:

c:\Program Files\Vector35\BinaryNinja\plugins\python>python.exe -m pip --isolated --disable-pip-version-check install --verbose colorama

And it claimed to install colorama successfully. Not sure how to check the log to see why it failed with the plugin manager.

The plugin manager still indicates that colorama is not installed and will not enable the debugger plugin.

**Comment by psifertex** [comment]
Did you try the other suggestion from #2336 and check the version of python that Binary Ninja is pointing at? What version of python are your settings currently pointing at? Using the built-in python this process appears to work fine on 2700 for me in a test VM.

**Comment by macjohnmcc** [comment]
After manually configuring for c:\python39 and manually installing requests and colorama I can now enable the debugger. If I eventually get a commercial license to use for the company can I just install all of this on my own computer to get all of the required packages then zip up something to copy to the computer in the sandbox since it won't have access to package repositories?
On 3/28/2021 7:29:44 PM, Jordan ***@***.***> wrote:
Did you try the other suggestion from #2336 [https://github.com/Vector35/binaryninja-api/issues/2336] and check the version of python that Binary Ninja is pointing at? What version of python are your settings currently pointing at? Using the built-in python this process appears to work fine on 2700 for me in a test VM.

**Comment by psifertex** [comment]
I think I followed up via email but just in case I didn't following up here as well. I've enabled better error reporting on the latest dev as of a few days ago so if you try this process again I'd like to see if you get more information about why pip failed. I'm suspicious there's some permission issue but hard to say without the additional debugging information.

For your question about offline installs, I've created this discussion question and I'll answer it over there: https://github.com/Vector35/binaryninja-api/discussions/2345

**Comment by macjohnmcc** [comment]
Here is the log where I tried to load the plugin (debugger) manually copying the plugins from the host computer where I had tested it before trying to get it installed in an offline environment. I have given up on doing this myself at this point I have spent too much time on it already and need to find a working solution to present to the people where I work.
On 3/31/2021 8:42:02 AM, Jordan ***@***.***> wrote:
I think I followed up via email but just in case I didn't following up here as well. I've enabled better error reporting on the latest dev as of a few days ago so if you try this process again I'd like to see if you get more information about why pip failed. I'm suspicious there's some permission issue but hard to say without the additional debugging information.
For your question about offline installs, I've created this discussion question and I'll answer it over there: #2345 [https://github.com/Vector35/binaryninja-api/discussions/2345]

**Comment by psifertex** [comment]
FYI, I updated the discussion at #2345 with a much longer explanation about migrating plugins and their python dependencies to an offline machine. 

Hopefully that helps explain the process. The main trick is if you're copying plugins installed via the plugin manager online to an offline machine you want to put them into your `$USER_FOLDER/plugins`, NOT back into a `repository/` subfolder. 

Also, I think you tried to add an attachment to the email but I don't think GitHub will work like that when using the email interface. If you can come directly to this GitHub issue and upload the attachment that way, that would be appreciated so we can see the debug log. Or email it to binaryninja at vector35 · com.

**Comment by psifertex** [comment]
Also, GitHub is a bit high latency, if you're interested we have a slack channel that it might be easier to have a more interactive discussion on to help you solve issues faster: https://slack.binary.ninja/

**Comment by plafosse** [comment]
Fixed in 2.3.2763
