### ISSUE TITLE
Outgoing Data Reference whose target is code is wrongly rendered as hex dump

### ISSUE THREAD

**Issue by jeffli678** [Vector35/binaryninja-api#2347]
![Screenshot from 2021-04-01 11-02-59](https://user-images.githubusercontent.com/3380590/113237779-0f2c0100-92da-11eb-8423-c9342b05efac.png)

We render all data references as if the target is a data variable. However, according to the definition, a data xref is a xref whose source is from data. So outgoing data references can have their targets being code. And in this case, we fail to render it in the best way we can.

Note, in some cases, such data refs appear to be rendered correctly. However, that is only an illusion. It is because there happens to be a auto data var at the same address of the function start. If there is no such data var (as in the case of the screenshot), or the target of the xref is in the middle of a function, then the preview line will be wrong. 

Related to https://github.com/Vector35/binaryninja-api/issues/2323

**Comment by emesare** [comment]
Seems to have been fixed at some point.

Showing the function name:
<img width="1268" alt="image" src="https://github.com/user-attachments/assets/f1fc0a90-3695-46a0-bd57-432f0237a9ba">

Showing the HLIL of the outgoing ref target:
<img width="1268" alt="image" src="https://github.com/user-attachments/assets/367c9d57-f065-4999-92d3-b409eaf157f1">
