### ISSUE TITLE
Reorder the tags tabs

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#2351]
This is the tags view by default:

![image](https://user-images.githubusercontent.com/8716677/113465387-6ae4b000-93e8-11eb-870f-ab85c5d7549f.png)

From other comments: bookmarks are meant to be programmatically used via the keyboard for navigation. Tags are meant to be interacted with via the UI. However, the default display puts tags an extra click away, opting to show the bookmark type which should _not_ be used via the UI (in the common workflow).

The request here is to have the 'Tags' bookmark be the selected one by default instead of 'Bookmarks'. Yes, this is an incredibly minor thing.

**Comment by psifertex** [comment]
Minor, but thanks for filing it -- I've been meaning to do this for a while.

**Comment by psifertex** [comment]
Fixed in build 2728 and above.
