### ISSUE TITLE
Unable to create new structure in filtered Type View

### ISSUE THREAD

**Issue by inspier** [Vector35/binaryninja-api#2356]
I am currently unable to create a new structure without specifying the size in the filtered types view set to only User Types. Doing so results in the application crashing.

Build: v2.3.2731-dev
Build ID: ee7f8d75

**Comment by negasora** [comment]
I can't reproduce this on 2.3.2738-dev

**Comment by negasora** [comment]
Fixed in 2.3.2741-dev
