### ISSUE TITLE
More magic python console variables

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#2364]
It would be nice to have additional variables auto-defined in the scripting console for ease of interacting with IL and UI. Here's a list of nice potential additions:

- [ ] current_{l,m,h}lil_instruction: get the actual LowLevelILInstruction/etc class for current selection
- [ ] current_{l,m,h}lil_instruction_index: like current_address for IL views
- [ ] current_{l,m,h}lil_basic_block: like current_basic_block for IL views
- [ ] current_instruction: like the {l,m,h} version except using the specific IL type
- [ ] current_view_frame: ViewFrame of current tab
- [ ] current_context: UIContext of current window

**Comment by plafosse** [comment]
current_token
current_data_var
current_type
current_section, current_segment
current_file_offset

**Comment by plafosse** [comment]
current_comment

**Comment by psifertex** [comment]
Current_index could be the index of the current view's selected instruction index? Though this does potentially get a bit confusing as how current_function always returns the native function so maybe current[hlm]lil_index is more straight forward?

**Comment by jeffli678** [comment]
Maybe also a `current_var` that is the current variable

**Comment by xusheng6** [comment]
Added in dev 3.1.3598
