### ISSUE TITLE
Function.call_sites are not consistent

### ISSUE THREAD

**Issue by hanssl** [Vector35/binaryninja-api#2368]
Binary Ninja Version: 2.3.2660, 88f343c3
Platform: Ubuntu 20.04.2 LTS

I am getting different results for Function.call_sites depending on whether I open a .bndb from the gui or a headless call.

Steps to reproduce:
1. Load a saved bndb in the binja gui.  
2. Navigate to a function (funcX) that calls other functions (with at least one call to an IAT entry).
3. get the current_function.call_sites
4. Load the same bndb as step 1 in a headless api client
5. Get funcX (bv.get_function_at(<target addr>)
6. get the funcX.call_sites.
7. Note: that the call sites in step 6 do not include the IAT entries.  Only the subroutines are included.

Other observations:
I switched to the latest dev branch for binja and observed a small change in behavior.
8. Since the binja instance changed then when I open the saved bndb there is some auto analysis that occurs.
9. If I let the auto analysis to run in step 5 then step 6 gives me the correct call_sites (including the IAT entries).
10. However, if I open the saved bndb in the binja GUI, save the bndb, then open the saved/updated bndb with my headless client then I see the bug again (no IAT entries in call_sites).

**Comment by plafosse** [comment]
We attempted to repro this but were unable to. Could you share a binary?

**Comment by hanssl** [comment]
[reproduceBugFiles.zip](https://github.com/Vector35/binaryninja-api/files/6319928/reproduceBugFiles.zip)

Here is a calc.exe test that reproduces the issue.

The headless client (file included) will find 7 call_sites.  If I open the same calc.bndb file, then the function at 0x401913 has 12 call sites (current_function.call_sites).

**Comment by hanssl** [comment]
My concern with this issue is that it makes me question what other things my plugins are not finding because they do not get all the data that the GUI does.

**Comment by negasora** [comment]
Everything in the gui goes through the same apis that headless operation uses

**Comment by psifertex** [comment]
If there's a difference in opening a file in a headless script and the python console in the UI it's due to how you're opening the file in the console. Are you using open_with_options?

**Comment by hanssl** [comment]
Here is the headless code:

# open a bndb
    bv = BinaryViewType.get_view_of_file(filename)
    bv.update_analysis_and_wait()

    # lookup the target function
    func = bv.get_function_at(target_addr)

    call_sites = func.call_sites
    print(f"call_sites({len(func.call_sites)}): {func.call_sites}")

The update_analysis_and_wait() is optional.  The results are the same.

**Comment by hanssl** [comment]
I did not find the function 'open_with_options' in the docs.  I tried to call it from a BinaryView but received the error:

AttributeError: type object 'BinaryView' has no attribute 'open_with_options'

**Comment by hanssl** [comment]
Found it: get_view_of_file_with_options

That fixes the problem.

**Comment by psifertex** [comment]
Excellent, glad to hear it. Sorry, was typing the API off the top of my head. Usually I'd link to the docs, glad you found it.
