### ISSUE TITLE
Mappings between assembly to HLIL aren't complete.

### ISSUE THREAD

**Issue by inaryart** [Vector35/binaryninja-api#2371]
The code block in the reflection view (hlil) does not correctly correspond to the code block in the main view (disassembly)

![YjFDw75QZJ](https://user-images.githubusercontent.com/51652878/114571309-250dce80-9ca9-11eb-8e1e-37271fb875f6.gif)

**Comment by bpotchik** [comment]
The mappings to/from HLIL are incomplete at the moment. We will finish these up at some point. Until then, mappings up to MLIL should be fairly complete.
