### ISSUE TITLE
disabled plugins cannot be re-enabled

### ISSUE THREAD

**Issue by macjohnmcc** [Vector35/binaryninja-api#2375]
Binary Ninja Version: 2.3.2743-dev Personal, 8ff681fd
Platform: Windows 10 Version 2009

This was working before but for some reason now the debugger shows disabled and when I go to enable it says it needs to install "colorama" then when I allow it to attempt to install it the log shows:

Running pip ['c:/Python39/Python.exe', '-m', 'pip', '--isolated', '--disable-pip-version-check', 'install', '--verbose', 'colorama']
Plugin is already installed.

And the plugin still shows disabled. Even after restarting the plugin is not enabled.
<img width="935" alt="2021-04-15_10-52-25" src="https://user-images.githubusercontent.com/17675231/114899693-cc3d5380-9dd8-11eb-8620-8ac05ddd2efd.png">

**Comment by psifertex** [comment]
Yeah, there's a bug on current dev where once a plugin is disabled it cannot be re-enabled using the UI. Recommend just uninstalling and then re-installing and it should enable then if dependencies are met. I thought we had a bug for this already but I don't see it, so we'll use this, thanks for filing.

**Comment by jonpalmisc** [comment]
This is the issue you're looking for @psifertex
https://github.com/Vector35/binaryninja-api/issues/2334

**Comment by psifertex** [comment]
Ahh, good catch, thanks. I thought there was one.

**Comment by macjohnmcc** [comment]
no problem. Happy to be a guinea pig 
On 4/15/2021 11:12:12 AM, Jordan ***@***.***> wrote:
Yeah, there's a bug on current dev where once a plugin is disabled it cannot be re-enabled using the UI. Recommend just uninstalling and then re-installing and it should enable then if dependencies are met. I thought we had a bug for this already but I don't see it, so we'll use this, thanks for filing.
