### ISSUE TITLE
Crash clicking locals in linear view

### ISSUE THREAD

**Issue by terorie** [Vector35/binaryninja-api#2392]
**Describe the bug**

I just bought Binary Ninja Personal and loaded my first binary. When clicking on certain locals in the linear view, the program immediately crashes.

**To Reproduce**

I don't know how to reproduce this issue. I can share the `.bndb` file.

**Expected behavior**

The program doesn't crash.

**Screenshots**

See screenshot: Clicking on the cyan text at `0x18012f41f` (`...ReferenceController`) immediately crashes the program.

![grafik](https://user-images.githubusercontent.com/21371810/115999932-51511580-a5ee-11eb-8d90-7bbdfe5dc4c2.png)

**Context:**
 - OS: Windows 10
 - Binary NInja Version 2.3.2660 Personal

**Additional context**

The log file contains nothing useful. The last few lines are

```
0x18012fbf0: Function analysis took 0.020 seconds
0x18012fe70: Function analysis started
0x18012fe70: Function analysis took 0.001 seconds
0x18012feb0: Function analysis started
0x18012feb0: Function analysis took 0.001 seconds
0x18012fed0: Function analysis started
0x18012fed0: Function analysis took 0.066 seconds
```

**Comment by terorie** [comment]
This is what Windows Event Viewer logs. Looks like a null pointer dereference.

```
Faulting application name: binaryninja.exe, version: 0.0.0.0, time stamp: 0x6036e2d4
Faulting module name: binaryninjacore.dll, version: 0.0.0.0, time stamp: 0x6036e287
Exception code: 0xc0000005
Fault offset: 0x00000000000f92f3
Faulting process id: 0x1644
Faulting application start time: 0x01d739e9c4380adc
Faulting application path: C:\Program Files\Vector35\BinaryNinja\binaryninja.exe
Faulting module path: C:\Program Files\Vector35\BinaryNinja\binaryninjacore.dll
Report Id: d063a786-f239-4e8b-8be2-a84b441905cc
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by bpotchik** [comment]
Are you using the stable or latest dev version? You can change channels in Edit...Preferences....Update Channel to try the latest version.

**Comment by bpotchik** [comment]
Oh yeah looks like you're on stable. The latest dev build is `2762-dev`

**Comment by terorie** [comment]
@bpotchik Thanks for the tip. `2762-dev` does not crash :tada:
