### ISSUE TITLE
Mach-O: Failed to parse symbol table when loading Hopper

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#2394]
**Describe the bug**
Trying to reverse the binary for Hopper causes the log to print the error "Failed to parse symbol table!" and the large majority of symbols to not load. This might be caused by their obfuscation, or binja's mach-o symbol table parser is missing a feature they use. Loading Hopper into Hopper resolves their symbol table, so I'd wager it's probably our parser. 

**To Reproduce**
1. Download the latest version of Hopper (4.7.4 as of this issue)
2. Open `Hopper Disassembler.app/Contents/MacOS/Hopper Disassembler v4` in binja
3. Observe broken symbol table which contains only _start, exports, and symbols found by linear sweep/dataflow.
4. (Optionally if you have a license for Hopper) Load Hopper into Hopper and notice the symbol table with many named symbols

**Expected behavior**
Expected the symbol table to load at least some of the symbols. 

**Screenshots**
![image](https://user-images.githubusercontent.com/711973/116012024-0b984b00-a5f6-11eb-9274-e7c5da0c5b7c.png)
![image](https://user-images.githubusercontent.com/711973/116012094-76498680-a5f6-11eb-9728-9b04270be3b1.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 10.15.7
 - Binja Version: 2.3.2760-qt6

**Comment by cxnder** [comment]
This is lack of export trie parsing, which is relevant in stripped binaries with many libraries. 

Resolved in builds >= 3.3.4028
