### ISSUE TITLE
Intermittent SEC_E_MESSAGE_ALTERED error on out-of-support Windows versions

### ISSUE THREAD

**Issue by amtal** [Vector35/binaryninja-api#2397]
Very infrequently on an older Windows system the following error pops up during Binary Ninja start-up:
`Error fetching version list: [35] SSL connect error (schannel: next InitializeSecurityContext failed: SEC_E_MESSAGE_ALTERED (0x8009030F) - The message or signature supplied for verification has been altered)`

Quick search turns up curl/curl#5488 with comments [referencing other schannel users bumping into it](https://github.com/curl/curl/issues/5488#issuecomment-636301280) as well as a [workaround](https://github.com/curl/curl/issues/5488#issuecomment-638301064).

**To Reproduce** Best way to hit it is to keybind "Restart Binary Ninja" then trial-and-error your way through plugin development. Seen from a Windows 7 build 7601 with probably <1% occurrence.

**Expected behavior** TLS error messages should come from amusing sources, like wifi hotspots trying to deliver advertisements into the binja start page. A malfunctioning curl-schannel turducken is dull and does not bring joy.

**Comment by plafosse** [comment]
We only support Windows 10.
