### ISSUE TITLE
Synchronized navigation of split views.

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#24]

**Comment by D0ntPanic** [comment]
1.0.278 beta adds simultaneous editing in a new tab or window. Split views in a single window will be added later.

**Comment by plafosse** [comment]
Just to add to Rusty's comment. In the current implementation navigation is not synced but editing is. So edits from one window appear in the other. But scrolling in one window does not effect the others. Window synchronization is reserved for later.

**Comment by plafosse** [comment]
Blocked on #305

**Comment by kciredor** [comment]
Would love to see this feature implemented, as it would be useful to have side-by-side views of assembly and HLIL!

**Comment by stonedreamforest** [comment]
+1

**Comment by psifertex** [comment]
For what it's worth, the only way to have those +1 actually count is to use the thumbs up icon on the original issue. That's how they get sorted in the bug list when we sort by "most 👍"

**Comment by bpotchik** [comment]
A preview version of synchronized views is now available in `2.2.2546-dev`. It's currently in a dock widget and can be activated by choosing 'Show Reflection' from the command palette, or the View menu. The view is currently limited to graph view, however cycling to all other IL views is supported. At the moment, synchronization is one way.

**Comment by yrp604** [comment]
The reflection is primarily useful for sanity checking what I'm looking at in the main view -- e.g. hlil to dasm. For this reason it might make sense to have the IL carousel cycle both the main view and the split view? If main view is dasm and the reflection is LLIL, hitting I would progress the main view to LLIL and the reflection to MLIL.

I haven't fully thought this out, but my normal workflow is HLIL in the main view with dasm in the reflection. However, when I drop down to dasm in the main view, I then result in dasm with reflected dasm which seems wasteful.

**Comment by psifertex** [comment]
Sometimes I like to leave asm on the right and cycle between the ILs on the left. So I'm not sure that's a good universal default. Certainly it should be optional if we did enable it. 

That said, could probably use a snippet and remap the hotkeys though it might require some UIContext juggling I think.

**Comment by bpotchik** [comment]
Locking the step between ILs among views is an interesting idea. Addition

**Comment by bpotchik** [comment]
Build `2.2.2569-dev` gets some additional settings for Reflection View. There is also a right-click context menu available from the function header portion of the reflection window.

![Screen Shot 2020-12-08 at 3 49 31 PM](https://user-images.githubusercontent.com/29309548/101540029-64c85080-396d-11eb-9e78-30b6cf340a61.png)

**Comment by psifertex** [comment]
This issue is closed after the testing period for the reflection feature. To enable this, use the `View` / `Native Docks` / `Show Reflection` or `Show Reflection` from the command-palette. 

We have some additional enhancements we plan to make to it tracked in #2216 and #2217 but we believe reflection solves the majority of the functionality requested by users voting for this issue.
