### ISSUE TITLE
Incorrect function parameter variables 

### ISSUE THREAD

**Issue by kumarak** [Vector35/binaryninja-api#2400]
**Describe the bug**

Binary ninja identifies the function parameter variables incorrectly and the register assignment does not follow ABI. I have seen it with most of the Linux Binutils binaries both x86 and arm architectures. 

The screenshot attached shows the register assignment which does not follow the calling convention. 

**Screenshots 1**
![Screen Shot 2021-04-26 at 12 18 29 PM](https://user-images.githubusercontent.com/1365912/116117193-f79e2900-a689-11eb-82b7-3e1e5820352d.png)

**Screenshots 2**
![Screen Shot 2021-04-26 at 12 20 35 PM](https://user-images.githubusercontent.com/1365912/116117216-fc62dd00-a689-11eb-93e6-26d7ab6eebe4.png)

**Screenshots 3**
![Screen Shot 2021-04-26 at 12 21 06 PM](https://user-images.githubusercontent.com/1365912/116117237-fff66400-a689-11eb-9e69-62a9df4d5505.png)

**Comment by KyleMiles** [comment]
Can you by chance share that binary and possibly expand on what you're describing?

Did we by chance file the same bug nearly simultaneously? Check #2399

**Comment by kumarak** [comment]
It seems the same issue. The function type identified is incorrect and the register allocated also does not follow the calling convention. I have attached another screen shot with the test binary. 

This is `thumb2` binary and I see the main function has two additional parameter of register type, backed by `q1` and `q2` registers.  


![Screen Shot 2021-04-26 at 9 38 23 PM](https://user-images.githubusercontent.com/1365912/116173802-37413100-a6db-11eb-874a-4be428ce34b5.png)
 
[test_binary.tar.gz](https://github.com/Vector35/binaryninja-api/files/6381380/test_binary.tar.gz)

**Comment by psifertex** [comment]
Already linked to #2399, closing for now, but thanks for the nice additional test!
