### ISSUE TITLE
Inlined suffix strings now displayed as array accesses

### ISSUE THREAD

**Issue by nshp** [Vector35/binaryninja-api#2402]
Now that HLIL has killer array access detection, my only complaint is that inlined C-strings which are suffixes of larger strings display like `&(*"Some long unrelated log message\n"[0x1f])` rather than `"\n"`, like they used to.
I think there should be an exception for inlined constant strings.

**Comment by bpotchik** [comment]
Fixed in `3.2.3795-dev`.
