### ISSUE TITLE
the lack of propagating the function type when called indirectly

### ISSUE THREAD

**Issue by 3vilWind** [Vector35/binaryninja-api#2404]
**Describe the bug**
Function type is not propagated when called indirectly, Maybe it is intended behavior, but is there a way to automatically (or via api) set the function type?

**To Reproduce**
1. Load [test_case.zip](https://github.com/Vector35/binaryninja-api/files/6385454/test_case.zip) binary
2. Load types from [header.zip](https://github.com/Vector35/binaryninja-api/files/6385462/header.zip)
3. Go to main function
4. Change type of rbx var to "EFI_SYSTEM_TABLE*"
5. See incorrect type of LocateProtocol function call, it has invalid args count and types, also it doesn't propagate type of return value

**Expected behavior**
LocateProtocol function call should have correct type (with 3 arguments with correct types and correct return value type)

**Screenshots**
![before](https://user-images.githubusercontent.com/29675029/116262194-00bdf180-a781-11eb-8841-5a13f9085a89.PNG)
![after](https://user-images.githubusercontent.com/29675029/116262214-04517880-a781-11eb-8e99-f560a8cc4e59.PNG)

**Desktop:**
Platform: Windows 10 Version 2004

**Additional context**
Binary Ninja Version: 2.3.2763-dev Personal, 426a99ac

**Comment by rssor** [comment]
It should be possible to manually apply a function type at a call site using call type overrides (right click on a call site), although it does look like it should have automatically stored off and used the call type override here.

**Comment by rssor** [comment]
Fixed in 2.3.2770-dev. It was not following typedefs when evaluating types used in indirect call target expressions.
