### ISSUE TITLE
Can't filter symbol list with "g" as first letter

### ISSUE THREAD

**Issue by negasora** [Vector35/binaryninja-api#2411]
It pulls up the goto dialog, and that's not very cool.

It probably happens with other ui hotkeys too.

**Comment by CouleeApps** [comment]
This can be fixed by doing #2414

**Comment by negasora** [comment]
probably related to #1533

**Comment by negasora** [comment]
Probably will be fixed by #2217

**Comment by plafosse** [comment]
Fixed as of the sidebar refactor 2.4.2921
