### ISSUE TITLE
Double click on __offset(N) should navigate to type in type view

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#2412]
Navigate to type view offset on double click of structure offset tokens.

![image](https://user-images.githubusercontent.com/10556585/116884109-5b79a200-abf4-11eb-883d-a3b4cb21cbdd.png)

**Comment by jeffli678** [comment]
It should also support pressing N to rename, and pressing 1, 2, 4, 8 to create new structure member
