### ISSUE TITLE
Update tab title when switching views

### ISSUE THREAD

**Issue by bambu** [Vector35/binaryninja-api#242]
Pulling up the strings view, then going to an xref does not update the tab title to reflect the current view. The tab title will continue to say that it is in the strings view. The same problem can be observed by going from disassembler to hex view by pressing `h`.

**Comment by psifertex** [comment]
Same thing happens when switching views with a hotkey (for example `h` to switch to hex view will leave `Disassembly` up top when it should switch away)

**Comment by bpotchik** [comment]
Fixed in 1.1.11460-dev.
