### ISSUE TITLE
Exported symbols can break things

### ISSUE THREAD

**Issue by dfraze** [Vector35/binaryninja-api#2423]
Heres a library that calls an internal function (this function is also exported for other binaries to call). We're interested in the GenerateMenu method of BBSUserEdit

![image](https://user-images.githubusercontent.com/12348497/116898231-21180100-ac04-11eb-9638-8db2a0563570.png)

So, let's double click it.

![image](https://user-images.githubusercontent.com/12348497/116898359-486ece00-ac04-11eb-8f80-308bd6d5670a.png)

Hmm. Not really what I was expecting. Ok, let's double click the target of the tailcall.

![image](https://user-images.githubusercontent.com/12348497/116898438-5fadbb80-ac04-11eb-88ec-5b742dab6751.png)

...ok...now each of these just brings us right back here.

Checking the symbol table:

![image](https://user-images.githubusercontent.com/12348497/116898527-7a803000-ac04-11eb-8d6f-b6b87fddfbd7.png)

And of course, clicking on the white symbol name...

![image](https://user-images.githubusercontent.com/12348497/116898576-8d930000-ac04-11eb-8a13-c936d7e1e19d.png)

I would expect to be able to get to the implementation of this function without having to search the symbol table. Ideally, also without going through the got/plt.

Binary is attached. BBSUserEdit::DoAction starts at 0x3540.

[libBBSUserEdit.zip](https://github.com/Vector35/binaryninja-api/files/6415927/libBBSUserEdit.zip)

**Comment by bpotchik** [comment]
Fixed  in `2.3.2782-dev`.
