### ISSUE TITLE
HLIL hides important things sometimes

### ISSUE THREAD

**Issue by dfraze** [Vector35/binaryninja-api#2425]
I don't have a great suggestion as to how to fix this, but, sometimes when programs do weird things, HLIL hides this.

Looks simple enough:
![image](https://user-images.githubusercontent.com/12348497/116899287-60931d00-ac05-11eb-9e4e-7982de2a783e.png)

...but this zeroes almost every register before that jump.
![image](https://user-images.githubusercontent.com/12348497/116899393-7c96be80-ac05-11eb-98f9-9a0e7658811b.png)

I don't know that I would expect it to become high level IL instructions, but I feel like some signifier that this may be interesting to look at in another IL might be nice.

**Comment by plafosse** [comment]
I don't know that we can really do anything about this. The HLIL_JUMP operation should clue you in that something really weird is happening.
