### ISSUE TITLE
Types can't round trip

### ISSUE THREAD

**Issue by dfraze** [Vector35/binaryninja-api#2427]
This function got its signature from the binary.

![image](https://user-images.githubusercontent.com/12348497/116902085-b87f5300-ac08-11eb-86a9-83796b37feeb.png)

If I edit the type (even just typing a space and then deleting that space), I cannot save my changes.

![image](https://user-images.githubusercontent.com/12348497/116902427-1ad85380-ac09-11eb-9a90-f7f71dbefa83.png)

[libBBSUserEdit.zip](https://github.com/Vector35/binaryninja-api/files/6416081/libBBSUserEdit.zip)

**Comment by yrp604** [comment]
Related: #1658 #2298

**Comment by psifertex** [comment]
Also #2585 and #1632

**Comment by CouleeApps** [comment]
As of 3.0.3260, you will be able to put arbitrary characters into function/symbol/type names. The UI should automatically escape them in the various edit dialogs, but if you are defining them yourself, use the following backtick syntax, e.g:

    bool `ExampleClass::operator=`(struct ExampleClass* this)
    `vector<int>` someVectorFunction(const `vector<int>`& input)
    struct `vector<int>` {
        int* m_start;
        int* m_end;
        int* m_bufEnd;
    }
