### ISSUE TITLE
incorrect behavior in c parser with forward declaration

### ISSUE THREAD

**Issue by 3vilWind** [Vector35/binaryninja-api#2431]
**Describe the bug**
Incorrect parsing forward declaration structs

**To Reproduce**
1. [test_case.zip](https://github.com/Vector35/binaryninja-api/files/6420840/test_case.zip)
2. Open any binary (eg. helloworld)
3. Import types from test_case.h by "Create New Types..." button
4. See unexpected __offset(0x8) field

**Expected behavior**
__offset (0x8) field does not exist 

**Screenshots**
![image](https://user-images.githubusercontent.com/29675029/116998137-70366280-ace6-11eb-91af-3ac5c64f6eca.png)

**Additional context**
Binary Ninja Version: 2.3.2787-dev Personal, 2e6e0ce9

**Comment by jeffli678** [comment]
The `__offset(0x8)` keyword means the next field starts at 0x8, which is smaller than the address that is already occupied by the last member, in this case 0x18. 

This looks bizarre since on the one hand, it seems we know the size of `LIST_ENTRY` so we can correct calculate the end of it, i.e., 0x18. On the other hand, the reason we put `Action` at offset 0x8 is we think the size of `LIST_ENTRY` is 0. There must be something wrong in the type parser, or the surrounding code.

**Comment by CouleeApps** [comment]
Forward declared structure types are now handled and resolved upon parsing, as of 3.0.3413-dev (both clang and core parsers).

**Comment by wrffrz** [comment]
There appears to be a regression related to this issue. 3.0.3457-dev correctly parses these definitions:

typedef struct _LIST_ENTRY LIST_ENTRY;

struct _LIST_ENTRY {
  LIST_ENTRY *ForwardLink;
  LIST_ENTRY *BackwardLink;
};

However, 3.0.3459-dev and the latest build from today (3.1.3470-dev) both fail with this error:

error: <unknown>: sources.hpp:1: error: type '_LIST_ENTRY' is not defined

**Comment by psifertex** [comment]
Which type parser setting are you using?

**Comment by wrffrz** [comment]
I hadn't changed that setting, but it looks like the default in 3.0.3457-dev was ClangTypeParser and starting with 3.0.3459-dev. the default is CoreTypeParser again.

It works correctly with ClangTypeParser.

**Comment by psifertex** [comment]
We switched it back just for the stable as there were some unintended side effects and are switching it right back to clang post 3.1 stable so it naturally may result in a little confusion, but in short if what you want isn't working in one, manually change to the other! Sorry about that!

**Comment by wrffrz** [comment]
No worries, it didn't occur to me to go look for that setting until you mentioned it since it had been working great for my use case with the new type parser.  Thanks!
