### ISSUE TITLE
Analysis propagate the underlying typedef type instead of itself

### ISSUE THREAD

**Issue by 3vilWind** [Vector35/binaryninja-api#2433]
**Describe the bug**
Analysis propagate the underlying type of NamedTypeReference instead of itself

**To Reproduce**
1. [test_case.zip](https://github.com/Vector35/binaryninja-api/files/6421567/test_case.zip)
2. Open test_case binary
3. Import types from test_case.h
4. Go to "f" function and set argument type to "Test*"
5. The use of this parameter is propagated as "_Test *"
6. It would be nice if it will propagate the original type "Test*" instead of "_Test*"

**Expected behavior**
Analysis propagate the original type

**Screenshots**
![image](https://user-images.githubusercontent.com/29675029/117014836-ded0eb80-acf9-11eb-827d-d631b5c1968b.png)

**Additional context**
Binary Ninja Version: 2.3.2787-dev Personal, 2e6e0ce9

**Comment by CouleeApps** [comment]
This was fixed with the fix for #2428 in 2.3.2819-dev
![image](https://user-images.githubusercontent.com/711973/119409735-c0855c80-bcb5-11eb-88a2-eaad30c536b4.png)
