### ISSUE TITLE
Variables View

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#2445]
Likely a different widget than #220 due to including non-stack variables like register/flag vars.

It would be great to have a widget where all of the variables in the current function can be inspected/modified. Specific features include:
- See all the variables in the function
- Edit their names
- Edit their types
- Use dataflow to display their value at the current address
- Use UIDF to edit their values
- Highlight live variables at the current address
- Highlight variables whose value is modified at the current address
- Optionally sort live variables above nonlive
- Show additional context eg global pointer

**Comment by jonpalmisc** [comment]
Available in build 2919
