### ISSUE TITLE
PDBs download and cache a 404

### ISSUE THREAD

**Issue by gamozolabs** [Vector35/binaryninja-api#2449]
When trying to load my PDB for a maplestory executable it attempts to hit the symbol server, and ends up saving a file in `~/.binaryninja/symbols/MapleStory.pdb/ED1CF4F0DE3B436E8817A2423ABA88231/MapleStory.pdb`. However, the contents of this file are a 404.

```
pleb@gamey ~/.binaryninja/symbols/MapleStory.pdb/ED1CF4F0DE3B436E8817A2423ABA88231 $ cat MapleStory.pdb 
{"type":"https://tools.ietf.org/html/rfc7231#section-6.5.4","title":"Not Found","status":404,"traceId":"0HM8JR5R8JU4L:000043E6"}
```

Unfortunately, this then leads to Binja seeing it as not an MSF 7.0 file.

![image](https://user-images.githubusercontent.com/13505090/117738418-d3296d00-b1b0-11eb-8603-50812507c9a8.png)

I had a file called `MapleStory95.pdb` in the same directory as the file on accident, renaming it to `MapleStory.pdb` fixed it in terms of Binja finding it. It would potentially be nice if Binja printed the name of the file it was attempting to open locally, eg "Binja is attempting to load: /home/pleb/foobar.pdb", as it would help debug file naming issues. That being said, that's just a nice to have.

-B

**Comment by CouleeApps** [comment]
This should be fixed in 3.0.3295-dev.
