### ISSUE TITLE
Jump Table entries offset by -1

### ISSUE THREAD

**Issue by Nordwald** [Vector35/binaryninja-api#2455]
**Describe the bug**
The jump table entries exported from MLIL seem to be off by -1. Somehow, it is shown correctly in HLIL.

**To Reproduce**
Consider the following sample with non-sequential switch cases:
```C
int test7()
{
    int week;
    printf("Enter week number(1-7): ");
    scanf("%d", &week);
    
    switch(week)
    {
        case 1: 
            printf("Monday");
            break;
        case 12: 
            printf("Tuesday");
            break;
        case 34: 
            printf("Wednesday");
            break;
        case 40: 
            printf("Thursday");
            break;
        case 500: 
            printf("Friday");
            break;
        case 6: 
            printf("Saturday");
            break;
        case 9: 
            printf("Sunday");
            break;
        default: 
            printf("Invalid input! Please enter week number between 1-7.");
    }
    return 0;
}
```
[test_switch.zip](https://github.com/Vector35/binaryninja-api/files/6493180/test_switch.zip)

The corresponding CFG in MLIL looks like this:
![switch_problem](https://user-images.githubusercontent.com/683685/118474614-8c38fb80-b70b-11eb-9391-518ba1821ff1.png)

The jump-table is the following (marked entries default), which is wrong because Case 0 should be default and Case1 should be Monday. All cases are subtracted by 1. Case 0 would never be reached.
![wrong-switch_jumptable](https://user-images.githubusercontent.com/683685/118474719-a8d53380-b70b-11eb-87cb-96453e1b4e59.png)

However, in the HLIL the cases are correct:
![wrong_switch_HL](https://user-images.githubusercontent.com/683685/118474839-ce623d00-b70b-11eb-96f5-cd4a7df25152.png)

Cross validation with IDA and Ghidra showed that this seems to be binaryninja specific. If this is intened behavior, we would like to know how to get the correct cases from the jump table.

**Expected behavior**
A correct jumptable as utilized in HLIL.

**Comment by plafosse** [comment]
The jump_table DataVariable object is simply an array showing index-value pairs. To get the jump table mapping you can query the dataflow of the `eax_1` variable using the `possible_values` api.

**Comment by Nordwald** [comment]
That is basically what we are doing at this point - but the values are the same.

```python
branch.dest.get_possible_values()
```
> <table: [0x0] -> 0x804960c, [0xb] -> 0x804961e, [0x21] -> 0x8049630, [0x27] -> 0x8049642, [0x5] -> 0x8049666, [0x8] -> 0x8049678, [0x1, 0x2, 0x3, 0x4, 0x6, 0x7, 0x9, 0xa, 0xc, 0xd, 0xe, 0xf, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f, 0x20, 0x22, 0x23, 0x24, 0x25, 0x26] -> 0x804968a>
```python
possible_values.lookup_table_value(possible_values.table, possible_values.mapping)
```
> <table: [0x0] -> 0x804960c, [0xb] -> 0x804961e, [0x21] -> 0x8049630, [0x27] -> 0x8049642, [0x5] -> 0x8049666, [0x8] -> 0x8049678, [0x1, 0x2, 0x3, 0x4, 0x6, 0x7, 0x9, 0xa, 0xc, 0xd, 0xe, 0xf, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f, 0x20, 0x22, 0x23, 0x24, 0x25, 0x26] -> 0x804968a>
```python
branch.get_ssa_var_possible_values(branch.dest.operands[0])
```
<table: [0x0] -> 0x804960c, [0xb] -> 0x804961e, [0x21] -> 0x8049630, [0x27] -> 0x8049642, [0x5] -> 0x8049666, [0x8] -> 0x8049678, [0x1, 0x2, 0x3, 0x4, 0x6, 0x7, 0x9, 0xa, 0xc, 0xd, 0xe, 0xf, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f, 0x20, 0x22, 0x23, 0x24, 0x25, 0x26] -> 0x804968a>
