### ISSUE TITLE
Scripting Console: Pressing Up on wrapped single-line text should not cycle history

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#2467]
If you type a long line of text in the scripting console entry, it will wrap to a new line. In this case, pressing Up (to edit an earlier part of the same text) actually navigates backwards in history and deletes your current entry. 

Expected behavior: pressing Up on wrapped text moves the cursor to the previous "line", unless the cursor was on the first "line" already.

As an interesting aside: pressing Down does nothing, as there is no history after the current selection, but does not move the cursor down either.

OS: macOS 10.15.17
BN: 2.3.2812-dev

**Comment by negasora** [comment]
Fixed in 2.3.2817-dev
