### ISSUE TITLE
Segfault in type parser for variadic args

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#2469]
Repro steps:
1. Open the following binary: [repro2.zip](https://github.com/Vector35/binaryninja-api/files/6525127/repro2.zip)
2. Click _malloc()
3. Edit Type to `int64_t  _malloc(...)`
4. Note segv upon typing the third dot

A quick stacktrace looks like this happens in the type parser

OS: macOS 10.15.7
BN Version: 2.3.2812-dev

**Comment by negasora** [comment]
Fixed in 2.3.2816-dev
