### ISSUE TITLE
OS-level "Open in Binary Ninja" Context Menu Option

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#248]
A context menu option, added on install, that says "Analyze with Binary Ninja" or "Open in Binary Ninja" would be very convenient.

**Comment by CryptXor** [comment]
```bat
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\*\shell\Analyze with Binary Ninja\command]
@="\”D:\\Applications\\binaryninja\binaryninja.exe\” \"%1\""
"Icon"="\”D:\\Applications\\binaryninja\binaryninja.exe\”"
```

**Comment by CryptXor** [comment]
Or if you only want it to show when you hold shift + right click:

```bat
Windows Registry Editor Version 5.00
[HKEY_CLASSES_ROOT\*\shell\Analyze with Binary Ninja]
@="Analyze with Binary Ninja"
"Icon"="\”D:\\Applications\\binaryninja\\binaryninja.exe\”"
"Extended"=""

[HKEY_CLASSES_ROOT\*\shell\Analyze with Binary Ninja\command]
@="\”D:\\Applications\\binaryninja\\binaryninja.exe\” \"%1\""
```

**Comment by CryptXor** [comment]
Or if you only want it on .exe files for example, change xxxx_ROOT\*\shell to xxxx_ROOT\exefile\shell

Go exploring in ```HKEY_CLASSES_ROOT\*``` for key names, you want the ones which are appended with -file.
e.g: exefile, dllfile, giffile, docxfile and NOT .exe, .dll, .gif, .docx

**Comment by plafosse** [comment]
Thanks CryptXor for figuring out how to do this on Windows... Now just tell me how to do it on Mac and Linux :)

**Comment by psifertex** [comment]
Decided to close this as wont fix as we're unlikely to implement this. Users that are interested can manually set up similar workflows if they want for themselves.
