### ISSUE TITLE
C++ documentation should be available offline

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#2483]
Currently the C++ documentation is only available online, it should be bundled and included for offline viewing as well.

**Comment by psifertex** [comment]
available in builds >= 6329.

Dev C++ docs will also be live on https://dev-api.binary.ninja/cpp/ when that build is finished.

**Comment by xusheng6** [comment]
This does not work on Windows. The `BinaryNinja\api-docs\cpp` folder does not exists

**Comment by xusheng6** [comment]
This appears to be fixed in 4.2.6434-dev (3d47b1b8). Should we close it as fixed? Or we still want it to be kept opened for other reasons? @psifertex

**Comment by psifertex** [comment]
Nope, good to close. @negasora fixed it.
