### ISSUE TITLE
have to hit up twice for single-line history entries in scripting console

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#2485]
**Describe the bug**
navigating multi-line history was improved to require an extra "UP" key for line-wrapped lines (matching previous multi-line behavior) but was accidentally applied to single-line history entries as well. This means you have to hit up twice for every single history entry in the scripting console, regardless if multi-line or not. This behavior should only apply to multi-line or line-wrapped, not single line.

**Comment by negasora** [comment]
fixed in 2.3.2837-dev
