### ISSUE TITLE
Plugin Manager: Dialog button ordering

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#2491]
Extremely tiny UI gripe: the plugin manager dialogs have their "Accept" button on different sides depending on the dialog:

![image](https://user-images.githubusercontent.com/711973/120424677-e1dfeb80-c33a-11eb-8bac-caaf27f75d71.png)
![image](https://user-images.githubusercontent.com/711973/120424687-e60c0900-c33a-11eb-856f-f02cd4cdb425.png)

**Comment by galenbwill** [comment]
The second dialog is a standard QMessageBox so we don't control the order of the buttons. The community plug-in dialog is custom, so we do. Easy to fix the custom one, but I'm not sure if the QMessageBox button order is the same on all platforms.

**Comment by negasora** [comment]
Fixed in 2.4.2924-dev
