### ISSUE TITLE
High Level IL (SSA Form) is available when Debug mode is disabled in LinearView

### ISSUE THREAD

**Issue by Ayrx** [Vector35/binaryninja-api#2495]
**Describe the bug**
High Level IL (SSA Form) is available in the selection menu when Debug mode is disabled. Seems like a tiny inconsistency with the rest of the SSA IL's that are only available when Debug mode is enabled.
 
**Screenshots**

![image](https://user-images.githubusercontent.com/1937160/120804718-90707000-c577-11eb-8217-8930f87058ba.png)

**Desktop:**
 - OS: MacOS 112.3

**Comment by psifertex** [comment]
Hmm, i can't reproduce this. What version of BN are you on? Were you in HLIL SSA when you either enabled or disabled that setting?

**Comment by Ayrx** [comment]
Binary Ninja version 2.4.2846.

Behaviour seems consistent no matter which mode I was on when changing the setting. I also tried restarting Binary Ninja after disabling Debug mode but the menu item is still there.

**Comment by psifertex** [comment]
Looks like this only occurs in Linear View, not Graph View.
