### ISSUE TITLE
Latest version of BN - invalid type handling

### ISSUE THREAD

**Issue by kotee4ko** [Vector35/binaryninja-api#2497]
Working with linux kernel object, simple smoke-test:
[!img](https://i.ibb.co/5KJDYXK/image.png)

**Comment by psifertex** [comment]
I don't understand the issue. Is there a function prototype for _copy_from_user that you expect to be backward propagated that isn't? 

What does `y` show when you press it while _copy_from_user is selected? 

Can you be more explicit about what you expect to see that you don't?

**Comment by psifertex** [comment]
*ping* Without more clarification we're going to close this issue as it's not clear enough what the specific issue or requested fix is.

**Comment by plafosse** [comment]
Closing this issue as it seems abandoned
