### ISSUE TITLE
collapse memory views

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#25]
_From @psifertex on May 5, 2015 21:21_

For large sections of unused memory in the loaded module, collapse them down to not take up so much room. 

_Copied from original issue: Vector35/binaryninja#28_

**Comment by D0ntPanic** [comment]
Implemented in dev

**Comment by ligix** [comment]
> _From [@psifertex](https://github.com/psifertex) on May 5, 2015 21:21_
> 
> For large sections of unused memory in the loaded module, collapse them down to not take up so much room.
> 
> _Copied from original issue: Vector35/binaryninja#28_

How do I expand them? I do want to use them :/
