### ISSUE TITLE
Enhancement request: Peephole optimizer

### ISSUE THREAD

**Issue by j1my3p1x** [Vector35/binaryninja-api#250]
Things like VMProtect, _some_ malware, and a lot of security critical components in just about anything rely on obfuscation for security. In some cases, it means creating tons of useless or redundant code, which would be annoying, and potentially impossible, to optimize away, but oftentimes it is just one function that is heavily "mutated" into using many times more instructions than necessary in order to make code hard to keep track of, annoying and confusing to read, and overall a much longer process than what should be necessary. Security through obscurity is one of the biggest annoyances to me, and probably a lot of other security researchers too. In order to reduce the complexity of mutated code, a peephole optimizer would be _incredibly_ useful. 

Here's an example of what I mean: http://theory.stanford.edu/~sbansal/pubs/osdi08_html/index.html
http://theory.stanford.edu/~aiken/publications/papers/asplos06.pdf
https://github.com/jnraber/VirtualDeobfuscator <-- only uses peephole optimization in one stage, but still
https://media.blackhat.com/us-13/US-13-Raber-Virtual-Deobfuscator-A-DARPA-Cyber-Fast-Track-Funded-Effort-Slides.pdf <-- a presentation about VirtualDeobfuscator, which is the thing in the GitHub link right above this. 

Binary ninja looks like it'll end up being a huge time saver for me with its focus on quick productivity with the IL translation and great UI. But the IL translation  I'm hoping that something like this can get implemented because that would singlehandedly manage to clean up what is by far my largest bottleneck.

Two completely random question while I'm here, if that's okay:
1) Is there a way to tip the devs? I don't have much on my PayPal right now, but I'd still like to give something.

2) Is there a way to import and/or export symbols?

Thanks.

**Comment by psifertex** [comment]
We absolutely plan on integrating optimizations into our IL analysis. We've been internally calling it our "optimized IL" where we will lift once more (gotta get in shape!) from one of our current ILs into another IL that optimizes out opaque predicates among other things.

We're actually pretty close to doing a lot of that now though we're primarily relying on our static data flow. There's also already some optimization in place (consider we translate from `xor reg, reg` into `reg=0` when you move from Lifted IL to Low Level IL in the options view.

So, yeah, definitely something we're looking into and have indeed already started. Will keep this bug open to track other similar suggestions.

As to 1) nope, not yet, but really appreciate it! Best things you can do for us now until we release the product is:

- submit bug reports/ideas like this one
- write plugins to scratch some itch you've got and publish it (at some point we plan on having a plugin repository available right from within the app)
- writeup CTF challenges, crackmes, whatever you're doing that you can share into a blog post showing off binary ninja features that were helpful
- tell others!

2) Not in the UI -- we do plan a refactor of the names list that might include that, but no ETA on it. You can pretty easily do it in the API though:
```
import binaryninja
fn = binaryninja.BinaryView['Mach-O'].open('/bin/ls')
fn.update_analysis() #Sleep here if not running interactively, 'cause but #230
print fn.symbols
```
To set them, use the `define_auto_symbol`  or `define_user_symbol` functions (https://github.com/Vector35/binaryninja-api/blob/master/python/__init__.py#L1362 and

**Comment by j1my3p1x** [comment]
Wow, you guys have seriously thought of everything. Thanks for the response! How do you guys think it will fare on stuff like VMProtect mutation? 

1) Sure, I'd be glad to! Writing plugins sounds like some fun. Will the plugin API ever open to more languages? Radare's support for Lua (and I think LuaJIT, so then maybe FFI too), IDA and Radare's combined support for JS, etc., are mindblowing, although I admittedly haven't tried using Radare's API. I can imagine that with the API and API docs still under way, that'd be a very low priority addition, but if it is on the road map then sweet.

I'll definitely be telling others about binaryninja!

2) Huh, that's pretty cool, thanks. I absolutely suck with Python, but binaryninja may get me to overcome my laziness and start trying to learn.

**Comment by psifertex** [comment]
Virtualization protections are a totally different beast that requires a very different approach. Some of the individual obfuscation techniques we can help on, but reversing a custom VM will pretty much always be hard, though it's a field I haven't followed closely so there may be more generic techniques these days. 

For language bindings, pretty much everything can call C libraries so it'd be certainly possible to add other language support, but it definitely won't be a priority of ours for a while.

**Comment by j1my3p1x** [comment]
VMP mutation is actually different from VMP virtualization. It's a really confusing naming scheme, but VMP mutation essentially just turns machine code into spaghetti with tons of redundant code to avoid major performance hits. On the other hand, virtualization is based around implementing an entirely virtual machine for your software to run on, sacrificing performance for complexity. VMP mutation ends up getting used a lot more often as a result, which is _really_ annoying. 

And that's good to hear. :+1:

**Comment by psifertex** [comment]
Closing this one out as we aren't pre-planning to include any specific optimizations. Rather, as we are implementing the HLIL (which is currently in development) we are implementing the appropriate data dependence graphs and implementations as needed.
