### ISSUE TITLE
migrate kaitai and snippets out of the api repo

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#2500]
Kaitai and Snippets both exist in this repo ([1](https://github.com/Vector35/binaryninja-api/tree/dev/python/examples/snippets),[2](https://github.com/Vector35/binaryninja-api/tree/dev/python/examples/kaitai)) and in their own repos ([1](https://github.com/Vector35/snippets),[2](https://github.com/Vector35/kaitai)). This is problematic and has caused many mis-syncs and we should simply submodule or just link to them. They are also available in the plugin manager now as well so could probably even be removed.

**Comment by jeffli678** [comment]
Done in 13ff200ba134b8704f37eca99c42b70dab0d17dc
