### ISSUE TITLE
Redundant condition in decompilation

### ISSUE THREAD

**Issue by comex** [Vector35/binaryninja-api#2504]
**Binary Ninja Version**
Version 2.3.2811-dev (Build ID 86f5afe6)

**Describe the bug**
For certain input, the HLIL view shows:
```
if (arg1 != 0 || (arg1 == 0 && arg2 s>= 1))
```
But `arg1 == 0` is redundant here.  It could be written as just
```
if (arg1 != 0 || arg2 s>= 1)
```

**To Reproduce**
- [Demonstration binary](https://github.com/Vector35/binaryninja-api/files/6633760/test.o.zip)
Compiled from this assembly:
```asm
    cmp x0, #0
    b.ne 2f
    cmp x1, #1
    b.lt 3f
2:
    str xzr, [x3]
3:
    ret
```

**Version and Platform (required):**
 - Binary Ninja: Version 2.3.2811-dev (Build ID 86f5afe6)
 - OS: macOS
 - Version 11.4

**Comment by xusheng6** [comment]
The same behavior can be observed in https://github.com/Vector35/binaryninja-api/issues/4251, e.g., at 0xd6f in the attached binary

**Comment by negasora** [comment]
This was fixed, likely a long time ago
![image](https://github.com/Vector35/binaryninja-api/assets/3020965/840934e8-70ba-4aa6-9582-deb279975fcd)
