### ISSUE TITLE
Log window refactor

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#2508]
- [ ] tagged log messages with support for filtering
 - [ ] possibly allow colors per type/tag
 - [ ] might address #1564

**Comment by galenbwill** [comment]
also: searching/filtering the log based on text (or regex, even)

**Comment by plafosse** [comment]
I wanted to add some more detail to this issue. The logging window could have a lot of nice improvements.  Prerequisite to these improvements is a refactor of the backend code  #2837 

I imagine 1 search/filter field and 2 comboboxes with checkboxes in them for each entry.

- The search box would allow for text-based searching/filtering and perhaps regular expression matching.
- The first combobox would contain the file/system scope. For example you could select system scope to see things that Binary Ninja is doing unrelated to a specific binary like fetching updates or plugin load status. Alternatively you could select a single or a set of open BinaryViews allowing you to see logs only related to a particular view.
- The second combobox would allow you to select a subset of loggers.

**Comment by yrp604** [comment]
the ability to select text and copy/paste it would also be a nice improvement.

**Comment by psifertex** [comment]
To clarify -- copy is already possible in the log window, it's just line-based. The requested feature enhancement here would be for sub-line selection.

**Comment by plafosse** [comment]
Fixed in 3.0.3297
