### ISSUE TITLE
The edit function dialog should open for the right-clicked function rather than the parent

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/binaryninja-api#2510]
Right-clicking on a function token in linear/graph view and selecting "Edit Function Properties..." should open the edit function dialog for the function that was right-clicked instead of the parent function currently focused. I believe this is the natural, expected behavior in this instance, and was caught off guard when it didn't work that way.

**Comment by jeffli678** [comment]
You can checkout how we implement change types in linear view, which works as you suggested

**Comment by negasora** [comment]
Fixed in 2.4.2922-dev
