### ISSUE TITLE
Right-click -> Copy in Symbols view does not work as expected

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/binaryninja-api#2516]
Selecting a symbol in the symbols list then right-clicking and choosing copy does not copy the symbols name. It should.

Additionally, it should copy whichever form of the symbol name is currently shown - demangled or mangled.

Running 2.4.2871 on macOS at time of reporting.

**Comment by galenbwill** [comment]
In lieu of select-all & copy, i have wanted a "copy all" action, that would copy all the currently visible symbols (in their current form)

**Comment by plafosse** [comment]
Duplicate of #1918
