### ISSUE TITLE
Calling conventions in function types aren't parsed properly

### ISSUE THREAD

**Issue by negasora** [Vector35/binaryninja-api#2518]
1. Set calling convention with `Edit function properties` dialog
2. Try editing function with `y`
3. It no parse :(

**Comment by CouleeApps** [comment]
Does this happen with any specific calling conventions? I can't reproduce with thiscall / stdcall / fastcall / linux-syscall / regparm (which shows up as `__fastcall`?) / cdecl

**Comment by yrp604** [comment]
if regparm shows up as fastcall, then https://github.com/Vector35/binaryninja-api/issues/1741 has regressed.

**Comment by CouleeApps** [comment]
Clang supports __convention("name") parsing now, and I'm pretty sure the core one did too? Regardless, as of 3.0.3413-dev clang will do this.
