### ISSUE TITLE
Plugin Development menu

### ISSUE THREAD

**Issue by CryptXor** [Vector35/binaryninja-api#252]
I hate to be a total tool, but where exactly is the Plugin Development Menu?

**Comment by psifertex** [comment]
No, it's a good question -- right now none of the menus work on it, so we've commented out. We have a number of menu items that aren't functional that we just removed instead of leaving them dead in the meantime.

**Comment by CryptXor** [comment]
Right - That makes me feel a whole lot better! :laughing:

**Comment by psifertex** [comment]
Changed the wording to "mode" to make that more clear.
