### ISSUE TITLE
Rust Linking Issues for Windows and Headless

### ISSUE THREAD

**Issue by WittsEnd2** [Vector35/binaryninja-api#2521]
**Binary Ninja Version**  - Latest Dev API

**Bug Description**
For the Rust API, whenever I try to create a Headless build (or any build on Windows), there are linking issues. Specifically, it cannot link to any function from the C API This is whenever I tell Cargo that a dependency is Binary Ninja via Git or Locally. 

A Linux plugin doesn't have these linking issues. 

**To Reproduce**
1. Give Binary Ninja as a dependency in Cargo. 
2. Use one of the examples from the Binary Ninja repository for testing. 
3. `cargo build`

**Expected behavior**
Compile a binary (for headless and windows plugin) 

**Version and Platform (required):**
 - Binary Ninja: Dev 2.4.2487 (if tested in stable, please also test the development channel via the "update channel" option)
 - OS: Ubuntu Linux and Windows
 - Version Ubuntu 20.04, Windows 10 2021 H2 Update

**Comment by KyleMiles** [comment]
If `Lots of linking issues.` is your expected behaviour, it sounds like this is closed.

What version/channel of cargo are you using?

**Comment by jrozner** [comment]
I'm experiencing this as well on both macos and windows. Using rust nightly through cargo (up to date as of yesterday). Using up to date dev binary ninja and up to date dev branch of binaryninja-api for the rust crate.

**Comment by WittsEnd2** [comment]
Whoops, my bad! The expected behavior is to compile haha. 

I am using:
```
Cargo: 1.5.4 - Nightly 
Rustc: 1.5.5 - Nightly
```

**Comment by KyleMiles** [comment]
I'm still confirming this, but I think this is a regression in cargo.

Everything works on my Mac on 1.53.0-nightly, and everything was working on Linux for me before I updated nightly (not sure from what version).  Seems like it's no longer propagating the linker arguments from binaryninjacore-sys.

**Comment by KyleMiles** [comment]
Sure enough, if I run `rustup install nightly-2021-04-24` and then `rustup run nightly-2021-04-24 cargo run` on the `basic_script` example, everything works again.

I'll see if there's a provided workaround from Rust.

**Comment by KyleMiles** [comment]
Unfortunately it seems that we were relying on a bug, and that any ability for a crate to provide linking dependencies for crates that import it is an intended anti-pattern: see rust-lang/cargo#9554.

The only solution at the moment seems to make all dependants include their own build.rs until rpath has better first-class support.  I'll push a rust/examples/template.
