### ISSUE TITLE
settings sub-sections should be delineated

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#2523]
**Is your feature request related to a problem? Please describe.**
There are sub-sections in settings such as:

![Screen Shot 2021-06-23 at 10 14 41 AM](https://user-images.githubusercontent.com/140215/123112604-d3ea2b80-d40b-11eb-8156-1962eb616af4.png)

**Describe the solution you'd like**
The right-menu should also have those settings broken up into more organized sub-sections. Right now only the top-level sections are delineated:

![Screen Shot 2021-06-23 at 10 16 23 AM](https://user-images.githubusercontent.com/140215/123112997-32afa500-d40c-11eb-8977-1d45161175c8.png)

**Comment by bpotchik** [comment]
Added in `2.4. 2967-dev`.
