### ISSUE TITLE
Odd cycles between phi nodes

### ISSUE THREAD

**Issue by wipawel** [Vector35/binaryninja-api#2527]
Binary Ninja Version: 2.4.2875-dev, adb7c635
Platform: macOS 10.15

When analyzing several non-trivial binaries in MLIL SSA, I noticed an oddly looking cycles between phi nodes.

Here is an example:
![image](https://user-images.githubusercontent.com/5213897/123231750-c8186b00-d4d8-11eb-837b-fea4025cfac8.png)

We can see two types of cycles:
* var#1 = phi(var#2, var#1, var#3) - "self" cycle
* var#3 = phi(var#2, var#4) <-> var#4 = phi(var#3, var#4, var#5) - "between phi nodes" cycle

Is there a rational explanation for this situation, or is it a bug? I could not explain this from looking at the binary in LLIL SSA nor disassembly.

**Comment by nshp** [comment]
Unless I misunderstand the question, this is exactly one of the expected features of phi nodes. Phi nodes “merge” data flows together. A dataflow cycle created by phi nodes suggests that a variable is being altered in a loop. Your basic for-loop counter, for example:

```
for (i=0;i < 4;i++);
```
```
i#1 = 0
loop:
i#2 = phi(i#1, i#3)
i#3 = i#2 + 1
if (i#3 < 4) goto loop
```
Here, the phi node is there to let you know that the value of i#2 is *either* i#1 or i#3, and that creates a cycles because, well, there is a cycle in that flow.

**Comment by wipawel** [comment]
> Unless I misunderstand the question, this is exactly one of the expected features of phi nodes. Phi nodes “merge” data flows together. A dataflow cycle created by phi nodes suggests that a variable is being altered in a loop. Your basic for-loop counter, for example:
> 
> ```
> for (i=0;i < 4;i++);
> ```
> 
> ```
> i#1 = 0
> loop:
> i#2 = phi(i#1, i#3)
> i#3 = i#2 + 1
> if (i#3 < 4) goto loop
> ```
> 
> Here, the phi node is there to let you know that the value of i#2 is _either_ i#1 or i#3, and that creates a cycle because, well, there is a cycle in that flow.

Yes, the above example is a loop cycle and I understand it. There is no odd phi cycle in it.

But, in the example I provided you can see there is just one SSA def of `arg9#4` and at the same time it contains a use of the very same variable and version. Kinda chicken-egg problem.
How should I interpret this?

In the other example I provided there are two phi nodes which constitute variable definitions and both of them also use the defined variables as input. Thus, neither the variable def nor use, appear anywhere else but in the phi node cycle.

**Comment by rssor** [comment]
Are there any edges back to the first basic block in the function? I'm curious about how the instruction at index 0 is a phi statement in the first place unless there's a back edge there.

Otherwise they look valid, even the instruction with index 52. If you consider a block that ends in a jumptable dispatch that potentially comes back to itself, you could have a phi providing its own input.

**Comment by wipawel** [comment]
> Are there any edges back to the first basic block in the function? I'm curious about how the instruction at index 0 is a phi statement in the first place unless there's a back edge there.
> 
> Otherwise they look valid, even the instruction with index 52. If you consider a block that ends in a jumptable dispatch that potentially comes back to itself, you could have a phi providing its own input.

The first basic block was the beginning of a function without any back edges.

**Comment by rssor** [comment]
If the function starts with phi nodes despite there not being other edges to the first basic block in the function that would be a pretty severe bug that I’d be very interested in repros for. 

The only situations I’ve ever seen graphs like the one you posted with instruction 0 being a phi node is where a function is tailcall recursive where we’ll wind up just turning the `jmp(function_start)` into a `goto(function_start)` which causes the edge back into the entry block (thinking about it now, it probably makes more sense to unconditionally translate those into tailcalls to prevent them from ever contributing edges).

For the rest of it though, those cycles can be expected where loops are present.

**Comment by rssor** [comment]
Closing as without a repro as near as I can tell this is working with intended, as phi cycles can be expected. As described there could be a bug relating to the phi instructions at the function entry point but I need more information to track that down.
