### ISSUE TITLE
Plugin Manager lets you click buttons with no plugin selected

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#2528]
BN 2.4.2875-dev
macOS 10.15.7

**Describe the bug**
If you set your HTTP proxy to `https://127.0.0.1` and don't have a proxy running, the plugin manager will not be able to pull updates. This means your plugin list will be empty. It should disable the update/enable/install buttons in this case, but they are enabled and you can click them to crash BN.

**To Reproduce**
1. Set network proxy to `https://127.0.0.1`
2. Go to plugin manager
3. Click Uninstall/Reinstall/one of them is blank

**Expected behavior**
These buttons should not be clickable

**Screenshots**
![image](https://user-images.githubusercontent.com/711973/123337969-084a0e80-d516-11eb-8c8f-fc3bed764f63.png)

**Comment by negasora** [comment]
Fixed in 2.4.2924-dev
