### ISSUE TITLE
"expected LP_BNPlatform instance instead of LP_BNArchitecture"

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#253]
I've noticed that several `BinaryView` member functions take an `arch` parameter, but when they make a call to the underlying C, an exception is thrown because an instance of `LP_BNPlatform` is actually expected. In a script I was working on, I encountered the following exception:

```
Traceback (most recent call last):
  File "../binaryninja-api/python/examples/add_symbols.py", line 71, in <module>
    added_function = bv.get_function_at(bv.arch, function_addr)
  File "/Applications/Binary Ninja.app/Contents/Resources/python/binaryninja/__init__.py", line 1259, in get_function_at
    func = core.BNGetAnalysisFunction(self.handle, arch.handle, addr)
  File "/Applications/Binary Ninja.app/Contents/Resources/python/binaryninja/_binaryninjacore.py", line 2247, in BNGetAnalysisFunction
    result = _BNGetAnalysisFunction(*args)
ctypes.ArgumentError: argument 2: <type 'exceptions.TypeError'>: expected LP_BNPlatform instance instead of LP_BNArchitecture
```

As you can see, I pass in `bv.arch` to the function, and then `BinaryView.get_function_at` passes `arch.handle` into `BNGetAnalysisFunction` ... but that function actually wants an `LP_BNPlatform` instance. Modifying my code to pass in `bv.platform` instead fixes the exception (though I can't get it to return anything except `None`, so maybe there is something else going on there).

I'm not sure how much of the API does this, but I did also notice that `BinaryView.create_user_function` also produces this exception when `bv.arch` is passed in.

**Comment by psifertex** [comment]
You're right in changing it to `bv.platform`, that is the correct thing to do. If you're not getting back something after that, there's a different unrelated bug. I've fixed both `get_function_at` and `create_user_function` in dev, and I don't see any other obvious ones. Thanks for catching that.

**Comment by plafosse** [comment]
Fixed in dev
