### ISSUE TITLE
headless and UI have inconsistent results in default usage

### ISSUE THREAD

**Issue by hanssl** [Vector35/binaryninja-api#2530]
Binary Ninja Version: 2.4.2883-dev, dda4ac45
Platform: Ubuntu 20.04.2 LTS

I was checking on an old bug (https://github.com/Vector35/binaryninja-api/issues/2368) and found that the current version of binja (stable and dev) have made this issue worse.  In my previous report I was able to get all 12 call_sites if I opened the bndb with 'get_view_of_file_with_options'.  In the current binja versions I only get 7 call_sites no matter how I open the bndb headless.

Steps to reproduce:
1. Extract the attached binary (calc.exe) and headless script to a folder.
2. Install QT (e.g. PySide6).
3. Run the script.
4. Observe that the call with the binary finds all 12 call_sites.  The bndb only finds 7 call_sites in the function that starts at 0x401913.
5. Open the binary or bndb with the binja gui, navigate to 0x401913 and observe that len(current_function.call_sites) is 12.

How can I open a bndb and find all the call sites like the GUI or original analysis does?

[binjaBug.zip](https://github.com/Vector35/binaryninja-api/files/6729080/binjaBug.zip)

**Comment by hanssl** [comment]
Updated script: 

import sys
import os

from binaryninja import BinaryViewType, BinaryView
from PySide6.QtWidgets import QApplication

def get_callsite_count(bv: BinaryView, target_addr: int):
    # lookup the target function
    func = bv.get_function_at(target_addr)

    call_sites = func.call_sites
    print(f"name: {func.name} call_sites.len: {len(func.call_sites)}")
    print(f"call_sites: {func.call_sites}")

if __name__ == "__main__":
    app = QApplication(sys.argv)

    bin_filename = "./calc.exe"
    bndb_filename = "./calc.bndb"
    target_addr = 0x401913

    # open a binary
    bv = BinaryViewType.get_view_of_file_with_options(bin_filename) # finds 12 call_sites
    get_callsite_count(bv, target_addr)
    bv.create_database(bndb_filename)

    # open a bndb
    bv = BinaryViewType.get_view_of_file_with_options(bndb_filename) # finds 7 call_sites
    bv.update_analysis_and_wait()
    get_callsite_count(bv, target_addr)

    os.remove(bndb_filename)

    print("done")

**Comment by hanssl** [comment]
Updated script.

[__init__.zip](https://github.com/Vector35/binaryninja-api/files/6729144/__init__.zip)

**Comment by psifertex** [comment]
I don't see a function at `0x401913` at all. Are you sure that address is right? Maybe you mean `get_functions_containing`?

**Comment by hanssl** [comment]
![Screenshot from 2021-06-28 14-39-35](https://user-images.githubusercontent.com/649957/123701179-bc9daa80-d81e-11eb-9947-f8173b99b9d7.png)

**Comment by psifertex** [comment]
Are you sure that's the `calc.exe` you uploaded? I want to make sure we're working with the right file and when I open the binary provided, I see this at that offset:

![Screen Shot 2021-06-28 at 4 44 16 PM](https://user-images.githubusercontent.com/140215/123701622-165aa080-d830-11eb-91ba-3e80f93a1035.png)

**Comment by psifertex** [comment]
```>>> Transform['RawHex'].encode(Transform['SHA256'].encode(bv.file.raw.read(0, len(bv.file.raw))))
b'b183bd6414c5123465075d76d2413c999d569492fb543acbc29690b4b745bdf2'
```

**Comment by hanssl** [comment]
That is the correct file.  Switch to HLIL and you will see the same as my screen capture.

**Comment by psifertex** [comment]
D'oh, sorry about that, I had a changed tailcall analysis setting.

**Comment by psifertex** [comment]
So there's two slightly different issues here. The first is that callees are not serialize to the BNDB. I filed #2531 to track that specific issue, though there's also the broader issue of why the UI and headless behave differently -- which is what I'm going to edit this bug to track. I believe the proper API should be `open_view` but we might have some discussion internally about where the proper place for the "behave the same as the UI" API is, but regardless, such a thing should exist and we'll track that here.

**Comment by psifertex** [comment]
We've done some more testing and there is actually only one bug here, tracked in #2531. The reason it works at all in the UI currently is because of a funny property -- you're looking at the functions in the UI linear view! This causes the IL to be generated which is actually what triggers the re-analsis and the correct data. So the good news is that there's no unexpected difference between the UI and headless and it's instead just an issue with the call references not being serialized/deserialized correctly in the first place. It just happens to be that the UI gets it right anyway for other unrelated reasons.
