### ISSUE TITLE
Uninformative HLIL Warnings: Maximum Complexity and Maximum Reduction Iterations

### ISSUE THREAD

**Issue by KyleMiles** [Vector35/binaryninja-api#2541]
The following errors are uninformative:
```
Function at 0x... has HLIL condition that exceeds maximum reduction iterations, condition not optimized (step 508)
Function at 0x... has HLIL condition that exceeds maximum complexity, omitting condition
```

The main problem with them is that I do not know how they affect me, if at all.  Since they're warnings, I presume they do, but the warning provides me with no indication other than the **first address of the function** where they occur.

If these warnings indicate something I should take action on or otherwise be aware of, then I propose the following:
- [x] Add an instruction address to the warning
- [x] Add a setting for the maximum complexity
- [x] Add a setting for the maximum reduction iterations

If these warnings don't affect me, then they should probably be demoted to LogDebugs.

**Comment by WhatTheFuzz** [comment]
I just came across both of these warning messages and I am confused on how to go about resolving them. I really like the solutions that Kyle mentioned above. Just adding 2¢.

**Comment by bpotchik** [comment]
Settings were added in `3.0.3445-dev`. See #3079

The instruction address is added as well, where possible, in build `3.1.3579-dev'.
