### ISSUE TITLE
HLIL SSA Generation Bug

### ISSUE THREAD

**Issue by KyleMiles** [Vector35/binaryninja-api#2542]
There are two problems in the picture below:

1. All the instructions in that middle block having the same instruction index
2. The last line of the same block being incomplete

![image](https://user-images.githubusercontent.com/7171118/124859318-afe72800-df7d-11eb-9c9e-a94c08344578.png)

The binary is [bash](https://github.com/Vector35/binaryninja-api/files/6781311/bash.zip), in the function `maybe_make_restricted`/0x32148.

**Comment by plafosse** [comment]
I think you're just reading it wrong. These aren't separate instructions its a single instruction with many phi instructions in the `condition_phi` property. Here's what it looks like all on a single line:
`'while (rcx_1#2 = ϕ(rcx_1#1, rcx_1#3)\nrsi_1#2 = ϕ(rsi_1#1, rsi_1#3)\nrdi#2 = ϕ(rdi#1, rdi#3)\ntemp1_1#1 = ϕ(temp1_1#0, temp1_1#2)\ntemp2_1#1 = ϕ(temp2_1#0, temp2_1#2)\nc_1#2 = ϕ(c_1#1, c_1#3)\nz_1#2 = ϕ(z_1#1, z_1#3)\n, rcx_1#2 != 0)'`

**Comment by KyleMiles** [comment]
Oh weird, you're right.  We should probably add some indentation to the front of those line continuations?
