### ISSUE TITLE
Ability to click on bracket on HLIL

### ISSUE THREAD

**Issue by elbiazo** [Vector35/binaryninja-api#2549]
**Is your feature request related to a problem? Please describe.**
Is it frustrating when you are reversing really big function and you don't really know where the end of bracket is.
![image](https://user-images.githubusercontent.com/23147879/125324776-38632100-e30e-11eb-9dbe-b75ff5cff3ac.png)

**Describe the solution you'd like**
It would be nice if you can click on beginning of the bracket to see where end of the bracket is located at. Kind of like vscode 
![image](https://user-images.githubusercontent.com/23147879/125324926-5fb9ee00-e30e-11eb-9de7-df49ebfe98b0.png)
Ghidra also have feature where you can click on the beginning of bracket to follow the end of the bracket.
![image](https://user-images.githubusercontent.com/23147879/125325021-79f3cc00-e30e-11eb-9ba5-05df68626ac3.png)

It would be also pretty sweet if there was an right click option to highlight all the code in between bracket.

**Describe alternatives you've considered**
Current method is to use comments or write a code to highlight addresses using the API.

**Comment by psifertex** [comment]
Highlighting is unfortunately not likely to happen too soon as it is dependent on #1940 which requires a decent refactor of both the highlight system and/or how ILs are generated and serialized. 

You could have a small gist which could implement an approximation using the native instructions at the appropriate addresses and "get_instruction_at" but it would be lossy and have some over and under-approximation. Let me know if you're interested in that and I can throw something together. 

That said, the ability to more easily highlight and or navigate braces/code blocks is a good idea and worth leaving this issue open for.

**Comment by plafosse** [comment]
Though this isn't exactly the same the solution we come up with will likely suffice for both: #1730
