### ISSUE TITLE
Show endianness (and maybe other things) in Triage view

### ISSUE THREAD

**Issue by endeav0r** [Vector35/binaryninja-api#2556]
**Is your feature request related to a problem? Please describe.**
I am very lazy. Instead of figuring out the endianness of my binaries/bndbs (and perhaps other simple properties), I would like to just open Triage view in Binary Ninja and see this information.

**Describe the solution you'd like**
Display the endianness of the binary in the Triage view.

**Describe alternatives you've considered**
Spending 30 seconds to look at the binary, which I will be doing after posting this issue.

**Additional context**
Super convenience feature. I was just surprised this wasn't automatically the case.

**Comment by jeffli678** [comment]
added in dev 2.4.3012
