### ISSUE TITLE
Allow more expressive function parameter/return locations

### ISSUE THREAD

**Issue by nshp** [Vector35/binaryninja-api#2560]
**Is your feature request related to a problem? Please describe.**
Greater-than-register sized parameters and return types are split between multiple registers (or even spilled over to the stack). For example:

```c
uint64_t sub_foo(uint64_t x, uint64_t y);
```

Compiled for ARMv7, this will take `x` from `r0:r1` and `y` from `r2:r3`, and it will return in `r0:r1`. Binja is currently unable to express this - the best it can do is split `x` and `y` into multiple parameters, like `sub_foo(uint32_t x_1, uint32_t x_2, uint32_t y_1, uint32_t y_2)`.

**Describe the solution you'd like**
Calling conventions should be able to specify what happens to greater-than-register sized values. The function type parser should also allow specifying concatenated storages, e.g. `uint64_t sub_foo(uint64_t x @ r0:r1)`.

**Comment by xusheng6** [comment]
Related to https://github.com/Vector35/binaryninja-api/issues/1003

**Comment by plafosse** [comment]
Closing in favor of this: https://github.com/Vector35/binaryninja-api/issues/3340
