### ISSUE TITLE
Remember previous values in input boxes

### ISSUE THREAD

**Issue by gsingh93** [Vector35/binaryninja-api#258]
IDA stores the values you've previously typed into input boxes in a context-aware way. For example, if I type `g`, the IDA input box remembers all of the previous addresses I've typed so I can reuse them. If I type `n`, IDA knows the previous names I've typed. It would be nice if Binary Ninja had this feature.

**Comment by plafosse** [comment]
This was added awhile ago, and is in the last stable.
