### ISSUE TITLE
Highlight Block does not propagate to HLIL

### ISSUE THREAD

**Issue by gaasedelen** [Vector35/binaryninja-api#2584]
**Binary Ninja Version**

2.4.2921-dev

**Describe the bug**

No block-based highlights propagate to the HLIL view. 

**To Reproduce**

1. Highlight all the blocks in a function
2. View the HLIL for the function
3. None of the HLIL is highlighted in the function

**Expected behavior**

If I highlight blocks of instructions, I would expect these highlights to propagate to the HLIL. At least, in the same manner that individual instruction highlights currently propagate

**Screenshots**

This GIF demonstrates the issue:

![highlight_binja_blocks](https://user-images.githubusercontent.com/9522648/128755193-9d0ee82d-c818-453e-8984-243bc480020c.gif)

**Version and Platform (required):**
 - Binary Ninja: Dev 2.4.2921
 - OS: Windows
 - Version: Windows 8.1 (x64)

**Additional context**

N/A

**Comment by elbiazo** [comment]
Not sure if this is true but is this issue the reason why Lighthouse isn't working on HLIL?

**Comment by gaasedelen** [comment]
> Not sure if this is true but is this issue the reason why Lighthouse isn't working on HLIL?

Yes.

Lighthouse does block-based highlighting in Binja because it is significantly faster to highlight thousands of blocks rather than millions of individual instructions. That said, Lighthouse is still much slower in Binja than IDA.

While it would be nice for this issue to be fixed, the ideal solution for Lighthouse would be a rendering callback that plugins could use from Binary Ninja to decide whether or not an instruction should be highlighted as it comes into view.

**Comment by psifertex** [comment]
We don't plan to solve this particular issue as the way that HLIL does transformations make highlighting in this way problematic. We do however plan to solve the callback-based solution which we're tracking in #2587 and are putting on the G release.
