### ISSUE TITLE
Error parsing specified type

### ISSUE THREAD

**Issue by syjzwjj** [Vector35/binaryninja-api#2585]
Binary Ninja Version: 2.4.2846, df7c027e
Platform: macOS 11.1

When I want to add some arguments to a function, it shows "Error parsing specified type". I didn't change anything. How to solve this problem? Thanks!

![image](https://user-images.githubusercontent.com/3119309/128803721-949c0e60-4e42-45a2-b40d-627c188276b9.png)

**Comment by jeffli678** [comment]
I do not know the exact cause, since the actual type is not included in the screenshot. However, there is an known issue that sometimes types do not round trip, e.g., type emitted by Binary Ninja cannot be parsed by itself.

**Comment by plafosse** [comment]
Could you please provide more information there could be a lot of different ways for parsing to fail. With out additional information we'll have to close this issue.

**Comment by syjzwjj** [comment]
Hi, this issue comes to when I analysis a windows system dll (dwmcore.dll) with microsoft symbol. 
You can try to change this function below:
`int32_t  CCubeMapRenderingEffect::UpdateSwapChains(class CDrawingContext* arg1, class TMilRect_<float,struct MilRectF,struct MilPointAndSizeF,struct RectUniqueness::NotNeeded> const& arg2)`

**Comment by syjzwjj** [comment]
[dwmcore-10.0.18362.387.dll.zip](https://github.com/Vector35/binaryninja-api/files/6979961/dwmcore-10.0.18362.387.dll.zip)
this is the attachment dll

**Comment by CouleeApps** [comment]
Type names with <> are now allowed via string escaping. See https://github.com/Vector35/binaryninja-api/issues/2427#issuecomment-1042327994 for details.
