### ISSUE TITLE
Implement stack model for tracking data flow through the stack

### ISSUE THREAD

**Issue by gsingh93** [Vector35/binaryninja-api#259]
Only `__libc_start_main` and `_start` are identified for this binary: https://github.com/ctfs/write-ups-2016/blob/master/boston-key-party-2016/pwn/cookbook-6/58056c425dc617b65f94a8b558a4699fedf4a9fb.tgz

**Comment by gsingh93** [comment]
Looks like the function prologs are a little different, I bet that's the issue:
```
lea     ecx, [esp+4]
and     esp, 0FFFFFFF0h
push    dword ptr [ecx-4]
push    ebp
mov     ebp, esp
```

**Comment by plafosse** [comment]
This is due to our missing stack model, which is being actively worked on. We do not look for common function prologs to determine where functions starts.  I thought we had a issue that was tracking stack model.  I am going to rename this issue as it is part of a larger fix.

**Comment by D0ntPanic** [comment]
Implemented in development
