### ISSUE TITLE
Crash when modify structure field

### ISSUE THREAD

**Issue by grokeus** [Vector35/binaryninja-api#2590]
**Binary Ninja Version**
2.4.2943-dev

**Describe the bug**
Binary Ninja often crash while modifying field of structure. It seems that only fields which is assigned some global symbols are affected (originally I faced bug while working with vtables, in attached repro binary affected field is function pointer)

**To Reproduce**
1. Open attached binary
2. Goto `main` function
3. create auto struct at `rax` variable
4. press `create members at accessed offsets`
5. change name or type  of `field_0`
6. BN crashed

Also we can create type by hand and after we set type for `rax` variable if we try to change type/rename first field we also will see a crash

**Expected behavior**
We should be able successfully change type/name of the field

**Version and Platform (required):**
 - Binary Ninja: Dev 2.4.2943-dev
 - OS: Windows
 - Version: 10.0.19041.1052

**Additional context**
It seem that heap is somehow corrupted 

[crash.zip](https://github.com/Vector35/binaryninja-api/files/6981263/crash.zip)

**Comment by jeffli678** [comment]
Crash confirmed. Will investigate.
