### ISSUE TITLE
more than one disassembly view for the same binary file

### ISSUE THREAD

**Issue by nitrogar** [Vector35/binaryninja-api#2592]
**Is your feature request related to a problem? Please describe.**
it is hard to analyze a function with a lot of inner function calls or jumps with just one disassembly view 
**Describe the solution you'd like**
if there is more than one disassembly view side by side or detachable to have each in different monitor 
i can right-click on an address and choose something like "follow in disassembly view number x"
**Describe alternatives you've considered**
the only alternative is to open multiple binary ninja instances each in different monitor and sync between them manually
**Additional context**
i faced this problem with packed files where there is a lot of jumps and it is hard for me to keep the context of a original function if i need to switch back and forth in different locations

**Comment by jeffli678** [comment]
There is a "Windows -> Split to New Window" that will open the file in a different Binary Ninja window, which you can then move to a different monitor. Does it help?

**Comment by nitrogar** [comment]
unfortunately no, because that is what I meant by opening multiple instances of binary ninja. what I proposed was to add the ability to sync between them so for example I want to select a function in the first binary view and the disassembly of that function appears in the second view automatically .

**Comment by bpotchik** [comment]
You can use Reflection View to get something close to this. For now Reflection view is limited to graph view, however the views are sync'd and you can configure how they sync in terms of src IL view type to target IL view type.

**Comment by bpotchik** [comment]
The next version of Binary Ninja will support sync'd side by side linear views.

**Comment by nitrogar** [comment]
well it is more than syncing the current address it is about controlling the address of the second(or more) views from the primary one.

**Comment by D0ntPanic** [comment]
You can now split panes using the icon in the upper right to get as many disassembly views as you desire in build 3164. In addition, alt double click or double middle click to navigate will navigate in a different side-by-side pane, leaving the source pane in the existing location. The logic for this is it navigates in the pane with the next highest sync group number, or opens a new pane if everything is the same sync group.
