### ISSUE TITLE
RegisterBinaryViewInitialAnalysisCompletionEvent and RegisterBinaryViewFinalizationEvent called twice

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#2598]
**Binary Ninja Version**
2.4.2954-dev

**Describe the bug**
When registering a callback with `BinaryViewType::RegisterBinaryViewInitialAnalysisCompletionEvent` or `BinaryViewType::RegisterBinaryViewFinalizationEvent`, the callback is called multiple times instead of once.

**To Reproduce**
```
	BINARYNINJAPLUGIN bool CorePluginInit()
	{
            auto completionEvent = [](BinaryView* view) {
                LogInfo("completionEvent");
            };

            BinaryViewType::RegisterBinaryViewFinalizationEvent(completionEvent);
            // or
            // BinaryViewType::RegisterBinaryViewInitialAnalysisCompletionEvent(completionEvent);
        }
```

**Expected behavior**
"completionEvent" should only appear in the log once.

**Screenshots**
![image](https://user-images.githubusercontent.com/5834130/130366658-ba9cb856-7abb-42f0-a875-f1bf03fca746.png)

**Version and Platform (required):**
 - Binary Ninja: Dev 2.4.2954-dev
 - OS: MacOS
 - Version 11.4

**Comment by jeffli678** [comment]
I believe this is the desired behavior. The callback is called once on each BinaryView that gets finalized (or whose initial analysis has finished). Typically, there will be two views, i.e., the raw view and the actual BinaryView (e.g., ELF, PE, etc) that is useful. It is the callback writer's responsibility to filter out the unwanted views and do nothing for it.

I am closing this issue for now. Feel free to re-open it if the callback is triggered multiple times even on the same binary view
