### ISSUE TITLE
Binary blob rebase not possible without an architecture

### ISSUE THREAD

**Issue by 3331** [Vector35/binaryninja-api#2600]
This seems like a thing that should be possible out of the box, as loading a binary blob that has been dumped is quite common for some people and from whatever has been dumped usually looks better when loaded at the correct base address, so you can easily follow pointers etc.

Edit: Image Base Address seems to fail when not selecting any arch upon load, otherwise selecting an arch makes it possible to load binary blob at desired address.

**Comment by bpotchik** [comment]
You can now load and rebase binary blobs without specifying an architecture.

Fixed in `3.0.3219-dev`.
