### ISSUE TITLE
Inconsistent `notifyViewChanged` behavior

### ISSUE THREAD

**Issue by KyleMiles** [Vector35/binaryninja-api#2607]
I've observed that `notifyViewChanged` is sometimes triggered when changing between IL's, which could allow a UI plugin to react to the currently displayed IL.

This works in the case where:
1. Open a binary view
2. Press `g`, navigate to a function
3. Cycle between ILs in any fashion

However, `notifyViewChanged` is not triggered when:
1. Open a binary view
2. (Optional) Navigate to a function through the symbols list
3. Cycle between ILs in any fashion

I suspect that one or the other of these should be considered a bug, since the behavior is inconsistent, but I'm not sure which.  I hope that it's the latter, lest there's a better way to track changes to the currently displayed IL.

**Comment by bpotchik** [comment]
Fixed in `2.4.2983-dev`.
