### ISSUE TITLE
Right click release notes, left click "Recent" label ==> crash

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#2610]
**Binary Ninja Version**
2.4.2958-dev

**To Reproduce**
1. Open a new tab
2. Right click on the text of the release notes panel
3. Left click the "Recent" label above the recent files
4. Crash

**Expected behavior**
I expected this to not crash.

**Version and Platform (required):**
 - Binary Ninja: Dev 2.4.2958
 - OS: macOS
 - Version 10.15.7

**Additional context**
Here's a log:
[binaryninja_2021-08-31-183029_MacBook-Pro.txt](https://github.com/Vector35/binaryninja-api/files/7087111/binaryninja_2021-08-31-183029_MacBook-Pro.txt)

**Comment by jeffli678** [comment]
I have ran into this crash as well, though I did not get a consistent repro
