### ISSUE TITLE
Display As character on enum in types sidebar causes segfault

### ISSUE THREAD

**Issue by galenbwill** [Vector35/binaryninja-api#2618]
**Binary Ninja Version**
Commercial

**Describe the bug**
Executing the `Display As - Character Constant` action on an enum member in the types sidebar view causes a segfault.

**To Reproduce**
1. Go to types view
2. Select an enum member
3. Open command palette or right-click on the member and select `Display As - Character Constant`
4. See binja crash

**Expected behavior**
The enum member should be displayed as a character. Also, binja should not crash.

**Crash Log Excerpt**
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libbinaryninjaui.1.dylib      	0x0000000107e8d06d 0x107b4b000 + 3416173
1   libbinaryninjaui.1.dylib      	0x0000000107e07a90 View::displayAs(UIActionContext const&, BNIntegerDisplayType) + 96
2   libbinaryninjaui.1.dylib      	0x0000000107b6f816 UIActionHandler::executeAction(QString const&) + 198

**Version and Platform (required):**
 - Binary Ninja: Dev 2.4.2968-dev
 - OS: macOS
 - Version 11.4

**Comment by jeffli678** [comment]
It does not have to be in the sidebar -- doing the same thing from the TypesView gets the same result
