### ISSUE TITLE
Type propagation should change display type of bitwise operations to hex

### ISSUE THREAD

**Issue by aschmitz** [Vector35/binaryninja-api#262]
I have a 32-bit MIPS instruction of `30 63 ff 00`, which binja disassembles as `andi $v1, $v1, -0x100`. In theory, this is equivalent to `andi $v1, $v1, 0xff00`, which would likely be more readable as a bitwise mask.

Would it make more sense to display values for bitwise operations with immediate values as their unsigned version instead? I can't think of many situations where and/or/xor'ing with a negative value is more understandable than the unsigned value.

**Comment by plafosse** [comment]
The display type can now be change by the user. Rather than close I'm going to modify to reflect the real way we will fix this issue.

**Comment by bpotchik** [comment]
This has been fixed for a while now.
