### ISSUE TITLE
sidebar notifyOffsetChanged function does not update offset on graph view

### ISSUE THREAD

**Issue by elbiazo** [Vector35/binaryninja-api#2621]
**Describe the bug**
notifyOffsetChanged function does not update offset on graph view. It does update on linear view for **sidebar** only. It does work as its suppose to on dockwidget.

**To Reproduce**
Load sidebarhello.py example 
https://github.com/Vector35/binaryninja-api/blob/dev/python/examples/hellosidebar.py

1. In linear view: offset works fine
![image](https://user-images.githubusercontent.com/23147879/132797209-63ef9913-fc5e-4be4-b033-6d3cd3c3c1d5.png)

2. In graph view: offset does not get updated.
![image](https://user-images.githubusercontent.com/23147879/132797182-1b00c3a5-a425-496e-8f41-531de530902a.png)

**Version and Platform (required):**
 - Binary Ninja: 2.4.2975-dev
 - OS: Ubuntu Linux
 - Version 20.04

**Comment by negasora** [comment]
Fixed in 2.4.2978-dev
