### ISSUE TITLE
Binary ninja softlock when open Edit function property

### ISSUE THREAD

**Issue by acheron2302** [Vector35/binaryninja-api#2623]
**Binary Ninja Version**
Binary Ninja Dev Version 2.4.2975

**Describe the bug**
The 

**To Reproduce**
1. Open a binary file
2. While it is analysing the binary, go to a function
3. Right click open the Edit function property
4. Now the program is softlock, u can't do anything with the program.

Video:
https://vimeo.com/601796827

Error photo on terminal:
![image](https://user-images.githubusercontent.com/45268078/132851580-26a1b9a1-955b-4bf7-8ad7-91dcfd432221.png)

**Version and Platform (required):**
 - Binary Ninja: Dev 2.4.2975
 - OS: Arch Linux x86_64
 - Version: 5.11.15-arch1-2

**Comment by jonpalmisc** [comment]
Hi,

I'm not able to reproduce this hangup (nor the Qt errors in the console) on macOS under the latest dev build. I don't currently have access to a Linux machine, so I'm unable to test on Linux at the moment.

Any additional information as well as a test binary/BNDB would be helpful in the meantime.

**Comment by negasora** [comment]
It's possible that this is specifically a Personal problem (Personal version, not throwing shade :P)

**Comment by jonpalmisc** [comment]
I still can't reproduce this on either Binary Ninja nor Binary Ninja Personal. Are you still encountering this issue @acheron2302?

**Comment by fuzyll** [comment]
Going to close this as we can't reproduce it and it's been over a month with no response from the original reporter. If we've got a way to reproduce this, we're more than happy to re-open the ticket and address it. Just let us know.
