### ISSUE TITLE
Visually differentiate tag headings in tag list view

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#2624]
**Is your feature request related to a problem? Please describe.**
When scrolling the tag list, the tag type headers look like broken tags, not actual headers.

**Describe the solution you'd like**
Some sort of visual indicator to suggest that this is not actually tag, outside of the arrow and icon. Different background color, border, whatever.

**Describe alternatives you've considered**
None

**Additional context**
See an example of the tag heading as it is currently. Make it pop pls.

![image](https://user-images.githubusercontent.com/8716677/132934224-7a02675a-0cdb-4a02-83db-879d0fa5c9a1.png)

**Comment by CouleeApps** [comment]
Done as of 2.4.3005-dev
