### ISSUE TITLE
MIPS `andi` immediate value gets sign-extended

### ISSUE THREAD

**Issue by aschmitz** [Vector35/binaryninja-api#263]
This may be an LLIR lifting issue, or it may be a disassembling issue:

I have a 32-bit MIPS instruction of `30 63 ff 00`, which binja disassembles as `andi $v1, $v1, -0x100`, which is correct if the `-0x100` is a signed 16-bit value, but not a signed 32-bit value: the immediate value referenced here is `0xff00`.

When displaying the LLIR for that operation, I get `$v1 = $v1 & 0xffffff00`, which is not what the instruction is actually doing: it should be `$v1 = $v1 & 0xff00`.

(Note that this may apply to other operations with immediate values, I haven't checked.)

**Comment by psifertex** [comment]
Should be fix.
