### ISSUE TITLE
Opening a new window causes menu items to be duplicated

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#2630]
**Binary Ninja Version**
2.4.2967-dev

**Describe the bug**
Every time you open a new window (cmd+shift+N), the Preferences and Check for Updates menu items are duplicated.

**To Reproduce**
1. Open binja
2. Open a new window
3. Do that a bunch of times

**Expected behavior**
The menu items are not duplicated

**Screenshots**
<img width="243" alt="image" src="https://user-images.githubusercontent.com/711973/133010558-eb73b854-b79f-4992-8dd9-dabbeb26fd33.png">

**Version and Platform (required):**
 - Binary Ninja: Dev 2.4.2967-dev
 - OS: macOS
 - Version 10.15.7

**Comment by plafosse** [comment]
Workaround added in 3.6.4823

**Comment by plafosse** [comment]
This is actually not fixed

**Comment by bpotchik** [comment]
Fixed in `4.0.4832-dev`.
