### ISSUE TITLE
Template simplification isn't being applied to parameters of data variables

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#2631]
![image](https://user-images.githubusercontent.com/10556585/133102776-0cf90eb0-9e2d-4d8e-acee-c6573f337ba5.png)

In some cases c++ template simplification isn't being applied as it should. 

@KyleMiles likely knows the most about this issue.

**Comment by KyleMiles** [comment]
Looks like the `class` keyword is messing with it, though there are some other oddities in that screenshot, such as ostream and that second line not simplifying.  Can you share the binary/copy out those strings?

**Comment by KyleMiles** [comment]
So the actual issue here is that simplification isn't being applied to the names of types.  The data symbols themselves are being simplified, but I'm not yet sure how types from typelibraries are getting through to the demangler.

**Comment by plafosse** [comment]
Fixed in 2.4.3081
