### ISSUE TITLE
Cancelling on "would you like to save" when restarting still spawns a new binja

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#2633]
**Binary Ninja Version**
2.4.2967-dev

**Describe the bug**
When you restart binja with unsaved changes, the "would you like to save" dialog has a cancel button. Pressing it will cancel quitting but a new binja will still spawn and now you have two.

**To Reproduce**
1. Open any binary
2. Make some changes
3. Command palette -> Restart Binary Ninja
4. Click Cancel

**Expected behavior**
I expected the restart to cancel and not spawn a second binja.

**Version and Platform (required):**
 - Binary Ninja: Dev 2.4.2967-dev
 - OS: macOS
 - Version 10.15.7

**Additional details**
Bonus: if you press Cancel on the restart dialog, you will no longer be able to use Restart.

**Comment by jeffli678** [comment]
Fixed in dev 2.4.2986
