### ISSUE TITLE
support MIPS t9 register

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#264]
We currently do not propagate dataflow from writable data sections, but MIPS requires a special case because the way their global pointer works (`$GP` / `t9`).

**Comment by endeav0r** [comment]
Sometimes MIPS functions (PIC) tend to set a lot of things relative to $t9, which should be equal to the address of the function when called. While this issue (#264) will help identify a lot of functions initially, https://github.com/Vector35/binaryninja-api/issues/281 will also allow people to write plugins to perform further analysis and do more automated code discovery.

**Comment by DexterHaslem** [comment]
strongly agree, both these issues addressed would be a huge jump for MIPS usability

**Comment by psifertex** [comment]
Yeah, we agree that this is a pretty big issue for MIPS disassembly. Once the refactor is complete we expect it to get fixed relatively soon after.

**Comment by D0ntPanic** [comment]
Using #260 for this as it is more descriptive of the issue.
