### ISSUE TITLE
`RegisterInfo` is no longer hashable

### ISSUE THREAD

**Issue by tetsuo-cpp** [Vector35/binaryninja-api#2642]
**Binary Ninja Version**
2.4.2981-dev

**Describe the bug**
As of [this commit](https://github.com/Vector35/binaryninja-api/commit/920da93a153ff0e6cff405c76f6d5175a9cbcfa4), `RegisterInfo` is no longer hashable due to being annotated with `@dataclass(frozen=False)`.

We've been using structures like `Set[RegisterInfo]` and `Dict[RegisterInfo, ...]` in our plugin which is no longer possible. I wanted to check whether this was intentional and if so, when we'd expect Binary Ninja to be writing to `RegisterInfo` objects.

**To Reproduce**
1. Write code in a plugin that uses `Set[RegisterInfo]`
2. Observe the runtime error when trying to insert into it

**Version and Platform (required):**
 - Binary Ninja: Dev 2.4.2981
 - OS: MacOS
 - Version: Big Sur 11.6

**Comment by plafosse** [comment]
Ah thanks for pointing that out. This is because I set it to be mutable. This was in error. I can have a fix for this today hopefully.

**Comment by plafosse** [comment]
Will be fixed in >= 2.4.2988
