### ISSUE TITLE
type library regressions on x64 libc

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#2647]
Latest type library changes appear to have cause a regression for a number of functions:

Here's a selection of ones after a quick look through /bin/ls:
```
00023dc0  off64_t (* const lseek)(int32_t fd, int64_t __arg2, int32_t whence) = lseek
00023ee0  char* (* const setlocale)(int32_t category, char const* locale, int64_t arg3, int64_t arg4, uint64_t arg5, ssize_t arg6, int32_t category, int32_t category) = setlocale
00023ef0  int32_t (* const statx)(int32_t fd, int64_t __arg2, int32_t flags, uint32_t mask) = statx
```

**Comment by lwerdna** [comment]
The three issues mentioned are corrected [here](https://github.com/Vector35/typelib-jsons/commits/main/x86_64/libc.so.6.json
). @psifertex Is there a more exhaustive list of functions have have regressed?

**Comment by psifertex** [comment]
Nope, I just happened to notice /bin/ls had a regression when comparing stable and eyeballed to find those. I don't have a more rigorous method for identifying others.
