### ISSUE TITLE
set_user_indirect_branches() will not propagate analysis from predecessor blocks

### ISSUE THREAD

**Issue by duk-37** [Vector35/binaryninja-api#2648]
**Binary Ninja Version**
Version 2.4.2997-dev (Build ID 45fa7f79)

**Describe the bug**
When using set_user_indirect_branches(), the function will not propagate analysis from predecessor blocks. Instead, it will describe all incoming registers as EntryValues.

**To Reproduce**
Target assembly:
```
mov ecx, 4
lea rax, [rip + 2]
push rax
retn

mov eax, ecx
retn
```

Python script:
```
valid_values = {
    RegisterValueType.ConstantPointerValue,
    RegisterValueType.ConstantValue,
    RegisterValueType.ImportedAddressValue,
    RegisterValueType.InSetOfValues,
    RegisterValueType.LookupTableValue,
    RegisterValueType.SignedRangeValue,
    RegisterValueType.UnsignedRangeValue
}

for cf in bv.functions:
    set_values = {}
    changed = True
    while changed:
        changed = False
        for (data, addr) in cf.instructions:
            if (data[0].text == 'retn'):
                if addr not in set_values:
                    set_values[addr] = {}
                target_values = set_values[addr]
                cv = cf.get_reg_value_after(addr, "rsp")
                cs = cf.get_stack_contents_after(addr, cv, 8)
                if (cs.type in valid_values and cs not in target_values):
                    target_values[cs] = True
                    cf.set_user_indirect_branches(
                        addr, branches=[[cf.arch, cs]])
                    changed = True
                    bv.update_analysis_and_wait()
```

**Expected behavior**
`ecx` should be a ConstantValue in the second basic block.

**Screenshots**
![image](https://user-images.githubusercontent.com/74797529/134059876-7b6bf808-b745-4647-823f-7a631d069f26.png)

**Platform:**
 - OS: Windows 10
 - Version: 21H1 (Build 19043)

**Comment by D0ntPanic** [comment]
This is no longer happening as of the latest stable. However, this method of continuing analysis will not work properly. The IL will end after the first `retn` and not finish analysis of the rest of the code. You will need to use the workflow API or an architecture hook to prevent `retn` from emitting an IL return.
