### ISSUE TITLE
Comments on basic blocks

### ISSUE THREAD

**Issue by Xiaogrill** [Vector35/binaryninja-api#265]
The ability to put comments directly on basic blocks in disassembly view, instead of putting the comment on an address, would help my workflow.
You already have implemented this functionality for the "Show IL basic block register state" option.

**Comment by psifertex** [comment]
We've decided to start being a bit more selective as to what features we're planning on implementing. This feature request has unfortunately fallen below the threshold of what we plan to implement so we're going to close it out.
