### ISSUE TITLE
Remember screen position across launches

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#2651]
**Is your feature request related to a problem? Please describe.**
Every time I launch binja it position itself slightly off screen (up and to the left):
![image](https://user-images.githubusercontent.com/8716677/134105871-7ea45613-d7c3-4c9a-819d-e411bdc63fba.png)

**Describe the solution you'd like**
Binja should remember its screen position and size between launches and load where it was closed from.

**Describe alternatives you've considered**
None, this is what notepad.exe does, and notepad.exe is the worlds only perfect program.

**Additional context**

**Comment by yrp604** [comment]
This is fixed as of 3004?

**Comment by yrp604** [comment]
Back as of 3032, perhaps earlier.

**Comment by psifertex** [comment]
We aren't touching the code around this so it's likely either QT related (though only the very most recent dev and the one before it have moved to QT 6.1.3) 

I suspect it's just a subtle trigger or something environmental contributing to when it shows up. I'll see if I can reproduce it this time as well later today.

**Comment by yrp604** [comment]
Nope
