### ISSUE TITLE
TypeLibrary fails to import some base types

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#2652]
**Binary Ninja Version**
2.4.3001-dev

**Describe the bug**
When loading certain binaries, a bunch of warnings related to type libraries failing to load are printed. I'm not sure what the underlying bug is, but the warnings are consistent.

The warnings look like:
```
TypeLibrary: failed to import type '_Unwind_Reason_Code'; referenced but not present in library 'libstdc++_x86_64.so.6'
TypeLibrary: failed to import type '_Unwind_Exception_Class'; referenced but not present in library 'libstdc++_x86_64.so.6'
TypeLibrary: failed to import type '_Unwind_Exception'; referenced but not present in library 'libstdc++_x86_64.so.6'
TypeLibrary: failed to import type '_Unwind_Context'; referenced but not present in library 'libstdc++_x86_64.so.6'
TypeLibrary: failed to import type '_Unwind_Reason_Code'; referenced but not present in library 'libstdc++_x86_64.so.6'
TypeLibrary: failed to import type '_Unwind_Exception_Class'; referenced but not present in library 'libstdc++_x86_64.so.6'
...
```

**To Reproduce**
1. Extract the binary from https://github.com/Vector35/BinaryTestCases/blob/master/test_corpus/unicodestrings.zip
2. Open in binja
3. Observe console log

**Expected behavior**
I expected there to not be warnings about type libraries failing to load

**Screenshots**
![image](https://user-images.githubusercontent.com/711973/134447675-0b7c76d2-af7b-4cbb-90f7-899578f9908d.png)

**Version and Platform (required):**
 - Binary Ninja: Dev 2.4.3001
 - OS: Ubuntu
 - Version 20.04

**Additional context**
This also happens with other libraries, eg I've seen a lot of warnings about `size_t` in other files

**Comment by plafosse** [comment]
Fixed in 2.5.3201
