### ISSUE TITLE
Type system support for structs ending in zero-sized arrays

### ISSUE THREAD

**Issue by jkalez** [Vector35/binaryninja-api#2654]
Binary Ninja Version: 2.4.2993-dev, 479483ef
Platform: Ubuntu 20.04.3 LTS

The type system does not allow creating a structure which ends with a zero-sized arrays.  For example, I'd like to create a structure that looks like the following (32-bit integers, pointers, etc.):

```c
struct mystruct {
  int tag;
  int length;
  uint8_t value[0];
};
```

This structure should be 8 bytes in size.  Instead, the output in the types window after creating this structure is the following:
```c
struct mystruct
{
    int32_t tag;
    int32_t length;
    uint8_t* value;
};
```

The types window also specifies this as a 12-byte structure (which is correct for the structure that was created, but not for the one I'm trying to create).

Please add support for structures which end with a zero-sized array, as these are common for variable-sized structures in C.

**Comment by plafosse** [comment]
This issue with the parser producing the wrong output was fixed last night. The issue where we infer the type of items past the end of the structure still needs to be done.
![image](https://user-images.githubusercontent.com/10556585/134703834-63819e44-24a3-49d7-bff1-9258faf16bed.png)

**Comment by plafosse** [comment]
Closing this in favor of: #2655
