### ISSUE TITLE
Substring offset display in HLIL

### ISSUE THREAD

**Issue by k3an3** [Vector35/binaryninja-api#2657]
**Binary Ninja Version**
2.4.2846

**Describe the bug**
Certain compilers may use a substring into a larger string for frequently reused strings, e.g. format string specifiers. The result is that the HLIL output looks like this:

```
fprintf(r0_2, &(*"nvram set foobarfoo=%d")[0x14], getpid())
```

The substring being passed to the function here is simply `%d`, and that's all the HLIL needs to show. The output shown is hard to parse visually, since I need to determine what is being referenced here by counting into the string myself. May be unrelated, but vulnerability-finding plugins such as VulnFanatic and Format String Finder are falsely marking every single invocation like this as a user-controlled format string vulnerability.

The disassembler shows the data a little better:

```
add     r1, pc, r1  {data_6171c[0x14], "%d"}
```

**To Reproduce**
1. Likely requires a binary with particular compilation options/features. Can't provide an example binary at this time.

**Expected behavior**
I would expect HLIL output to look like:

```
fprintf(r0_2, "%d", getpid())
```

**Version and Platform (required):**
 - Binary Ninja: 2.4.2846 (stable)
 - OS: Debian 12

**Comment by nshp** [comment]
Dupe of #2402 ?

**Comment by psifertex** [comment]
Indeed.
