### ISSUE TITLE
loading gamelogic.dll from PwnAdventure3 with the PDB causes a crash in dev

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#2659]
**Binary Ninja Version**
As early as dev 3000, as late as 3013, all crash

**Describe the bug**
Crash.

(See #2656 )

**To Reproduce**
1. Open dll
2. Load PDB
3. Crash.

**Expected behavior**
Not crashing

**Version and Platform (required):**
- Tried on both MacOS and Windows of various dev builds. 

**Additional context**
Regression from stable.
[gamelogic.zip](https://github.com/Vector35/binaryninja-api/files/7239701/gamelogic.zip)

**Comment by CouleeApps** [comment]
Version bisect finds: not crashing in 2.4.2930-dev, crashing in 2.4.2934-dev

**Comment by plafosse** [comment]
Fixed in 2.4.3041
