### ISSUE TITLE
PIE/PIC Support

### ISSUE THREAD

**Issue by soen-vanned** [Vector35/binaryninja-api#266]
Take the following non-pie binary disassembly:
![noPie](https://cloud.githubusercontent.com/assets/1918848/15716483/77f08c2e-27f0-11e6-9b21-46b4172172c7.png)

and the same binary compiled with pie:
![withPIE](https://cloud.githubusercontent.com/assets/1918848/15716512/929371e0-27f0-11e6-8582-a403dfcef26d.png)

I'm compiling using gcc -m32 -pie

Included are both
[binaries.zip](https://github.com/Vector35/binaryninja-api/files/293851/binaries.zip)

**Comment by psifertex** [comment]
same issue as #5

**Comment by plafosse** [comment]
PIC/PIE support has existed for some time now, though we do have some problems with this binary now because the PIE binary is compiled with relocations which we don't currently support. Follow #5 if you're interested in the progress of this issue.
