### ISSUE TITLE
BasicBlock._buildStartCache() Uses Default Architecture for Instruction Length

### ISSUE THREAD

**Issue by kristopax** [Vector35/binaryninja-api#2660]
Tested on Binary Ninja version 2.4.2846

**Bug Description**
In the BN Python API, BasicBlock._builtStartCache() uses the default architecture (from the binary view) when getting the instruction length (and starts) for each instruction in the basic block as follows:

`length = self.view.get_instruction_length(start)
`

Since the API here does not supply an architecture to the call to `get_instruction_length`, the default architecture of the binary is used.  For ARM binaries individual functions can have a different architecture than the default architecture (e.g. armv7 versus thumb-2), this leads to incorrect cached instructions.

**Steps to reproduce the behavior**
1. Go to 0x2a64 (__gmon_start__()) in the attached BNDB
2. In the Python Console, enter the following

`bb = current_function.basic_blocks[0]`
`print([insn for insn in bb])`
`print(bb.instruction_count)`
`print([insn for insn in bb])`

3. Each call to `print([insn for insn in bb])` produces a different result

**Expected behavior**
Each call to `print([insn for insn in bb])` should produce the same correct result, which should cache the instructions associated with the architecture of the function to which the basic blocks belong.

**Version and Platform (required):**
 - Binary Ninja: 2.4.2846 (though I believe this occurs in any recent version)
 - OS: macOS

**Proposed solution**
Provide the basic block architecture to the `get_instruction_length` api as follows:

`length = self.view.get_instruction_length(start, self._arch)`

**Screenshot Showing the Bug**
![Screen Shot 2021-09-28 at 9 55 12 AM](https://user-images.githubusercontent.com/79866371/135101171-368deb23-9ed9-42f3-80c3-36fc6b6da2bb.png) 

**Binary**
[fb1f194159d362f236d511d155426b4af8672c2c.bndb.txt](https://github.com/Vector35/binaryninja-api/files/7244683/fb1f194159d362f236d511d155426b4af8672c2c.bndb.txt)

**Comment by plafosse** [comment]
Fixed in 2.4.3016
