### ISSUE TITLE
Argument not populated to extern call in linux kernel module

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#2661]
**Binary Ninja Version**
3013

**Describe the bug**
I have a kernel module that calls `kfree` via call to `.extern`. This extern is applied the type `void kfree(void *objp)`. However, a particular kfree in this binary does not populate a the single paramter once that type is applied. If I override the call type, then it does work. It's not clear to me why this particular kfree should require an override.

**To Reproduce**
1. Go to 00017cf0
2. Click on kfree, hit 'y' to set it's type and give it the type `void kfree(void *objp)`
3. Look at call to kfree
4. See the lack of argument
5. Override the call site
6. See the argument show up

**Expected behavior**
I expect function arguments to be populated once the types are defined or an error that notifies me as to the reason they cannot be populated.

**Version and Platform (required):**
 - Binary Ninja: Dev 2.4.3013
 - OS: Windows
 - Version 21h1

**Additional context**
Binary is provided privately

**Comment by rssor** [comment]
Should be fixed in 2.4.3040-dev.
