### ISSUE TITLE
HighLevelILFunction.vars does not contain all variables

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#2662]
**Binary Ninja Version**
3017

**Describe the bug**
A variable that I can interact with is missing from the Variables pane

**To Reproduce**
1. Go to 00400988
2. Click on the stack based variable that gets passed to fgets, change its type to `uint8_t[0x20]`
3. Select the variables pane
4. See the missing variable

**Expected behavior**
I see all variables in the current function in the variable pane

**Screenshots**
![image](https://user-images.githubusercontent.com/8716677/135213801-4b410f68-e85b-4867-ad38-7c1cf5efd2ae.png)

**Version and Platform (required):**
 - Binary Ninja: Dev 2.4.3017
 - OS: Windows
 - Version 2-h1

**Additional context**
[chall.txt](https://github.com/Vector35/binaryninja-api/files/7249342/chall.txt)

**Comment by negasora** [comment]
It looks like this is a bug with HLIL losing variables, switching to any other IL shows the variable in the pane.

![image](https://user-images.githubusercontent.com/3020965/135916853-e8ca4b4e-6186-4016-baf8-b82e3c2e362c.png)

**Comment by KyleMiles** [comment]
Resolved in 2.4.3106-dev.

**Comment by KyleMiles** [comment]
Those aliased variables will be accessed through `HighLevelILFunction.aliased_vars`, seeing as they're a distinct thing we now expose.
