### ISSUE TITLE
"File Modified" confirmation dialog does not properly tab between options

### ISSUE THREAD

**Issue by Vasco-jofra** [Vector35/binaryninja-api#2664]
**Binary Ninja Version**
Binary Ninja 2.4.3021-dev

**Describe the bug**
The dialog box `File Modified` that appears when you close binary ninja does not tab between options correctly. It tabs between `Cancel` -> `Save` -> `Save` and `Close without saving` at the same time. If you click `Enter` on the last one, you get prompted to choose `Save File Contents or Database`, meaning the `Save` option was selected.

Before, I used to do `Ctrl+P -> Restart Binary Ninja -> Enter`, and it would restart without saving. Now I have to click on the `Close without saving` option with the mouse.

**To Reproduce**
1. `Ctrl+P` -> Restart Binary Ninja
2. Tab between options 
3. See that `Close without saving` cannot be selected

**Expected behavior**
Tabbing between options works as before and you can select `Close Without Saving` using only the keyboard.

**Screenshots**
Both options selected simultaneously:
![image](https://user-images.githubusercontent.com/11303847/135450474-1bfca999-7bfd-49d8-ad14-494b139c06ae.png)

**Version and Platform (required):**
 - Binary Ninja: 2.4.3021-dev
 - Ubuntu Linux
 - Version: 20.04

**Comment by fuzyll** [comment]
This was fixed in 3.0 and we missed closing it somehow. Thanks for the report!
