### ISSUE TITLE
task bar icon blank on windows 10

### ISSUE THREAD

**Issue by soen-vanned** [Vector35/binaryninja-api#267]
![binja_icon](https://cloud.githubusercontent.com/assets/1918848/15716869/5cc3548e-27f2-11e6-9673-818575b31d72.PNG)

This is before and during binary ninja execution

**Comment by pawlos** [comment]
I think this is also related so I added it here so this also can be verified: 
- binary ninja icon is also when the icon is snapped to Windows 10 menu.
![image](https://cloud.githubusercontent.com/assets/1296768/16068634/a264d3c0-32c7-11e6-86b0-71f487c9eb15.png)

**Comment by plafosse** [comment]
Fixed
