### ISSUE TITLE
Rendering diagonal lines

### ISSUE THREAD

**Issue by alexmullins** [Vector35/binaryninja-api#2675]
**Binary Ninja Version 2.4.3041 Personal (latest dev)**

I'm seeing a diagonal line rendered in the stack view. At first I thought I had a scratch on my screen. I took a screenshot of what it looks like. This is with the /usr/libexec/taskgated binary open on the _start function. The line stays in the same spot when the stack view is scrolled. 

<img width="279" alt="Screen Shot 2021-10-04 at 9 48 55 PM" src="https://user-images.githubusercontent.com/174546/135952962-99d84435-25ec-48bc-a00e-22b731a8445d.png">

(Edit: I'm using a MacBook Pro on MacOS 10.15.7)

**Comment by D0ntPanic** [comment]
Fixed in build 3064
