### ISSUE TITLE
Externs do not populate the change type ui dialog with their type

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#2680]
3043

**Describe the bug**
When changing the type of an extern, the provided default is the last thing typed _not_ any existing type information

**To Reproduce**
1. Go to 00000179
2. Select kfree, hit 'y' to give it a type. type should be `void kfree(void *p)`
3. Double click kfree, observe that the type is set in the extern section
3. Go to 00000143
4. Select kmem_cache_alloc_trace, give it a type. This can be anything, you're just doing this to clear the suggested text history. I used `int kmem_cache_alloc_trace(int*, int, int)`
5. Go back to 00000179
6. Select kfree, hit 'y'
7. Observe the type you set does not populate the dialog box

**Expected behavior**
If an extern has a type, I expect it to populate the change type dialog box

**Version and Platform (required):**
 - Binary Ninja: Dev 2.4.3043
 - OS: Windows
 - Version 11
 
[kernote.ko.txt](https://github.com/Vector35/binaryninja-api/files/7301543/kernote.ko.txt)

**Comment by plafosse** [comment]
Fixed in 2.4.3060
