### ISSUE TITLE
il_function has .ssa_vars which is invalid for that form

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#2681]
Looks like the 3.0 refactor added .ssa_vars to regular mlil functions and llil functions even though it should only be applied to the ssa form.

It should have some subset of these changes made:

1) be removed from the non-ssa form
2) automatically do the lookup through the ssa form
3) throw an exception when called on an invalid function type as opposed to returning an empty list

**Comment by KyleMiles** [comment]
Resolved in 2.4.3106-dev.
