### ISSUE TITLE
Folder View for Symbols (Components)

### ISSUE THREAD

**Issue by elbiazo** [Vector35/binaryninja-api#2693]
**Is your feature request related to a problem? Please describe.**
When reversing large binaries, I often try to group certain functions together so that I can focus on small sets of functions.

**Describe the solution you'd like**
It would be nice if you can create a tabs just like how it is in tags for symbols
![image](https://user-images.githubusercontent.com/23147879/136985492-db22865f-4b18-4b3a-80f3-7428460f3630.png)

Similar to Ida 7.5 and Ghidra folder structure:
https://hex-rays.com/products/ida/news/7_5/
https://mobile.twitter.com/rolfrolles/status/1283157239147008000

**Describe alternatives you've considered**
Currently I either tag or name them similarly so i can filter them.

**Comment by cxnder** [comment]
Resolved in builds >= 3.4.4089. 

Currently, the new Symbols UI is gated behind an option in settings (ui.components.enabled), and off by default. It's currently experimental and may have bugs. Try it out! Feedback and bug reports are appreciated. 

Build 3.4.4089 added the new Symbols sidebar widget.

This widget replaces the old one, and allows:

- Creating, organizing, and managing Folders
- Displaying Addresses, Segments, Function/Datavariable sizes in neighboring columns
- Built-in Scripts to automatically sort items into Folders
- More options to edit attributes of functions/DataVariables directly from the sidebar.

Along with several other improvements.

**Comment by psifertex** [comment]
Thanks to @cxnder this is now on dev in an experimental capacity. To enable it, use the setting 
`ui.components.enabled`

**Comment by elbiazo** [comment]
@cxnder this looks awesome! i also love that its really easy to script it. One question though. Is there a way to automatically run a script when any of the symbols get changed? for example, it would be cool if i define some function as Foo::bar, it would automatically put it on Foo folder by running the script user defined.

**Comment by cxnder** [comment]
We're working on a better way of showing off examples. What you requested could be done by setting up a BinaryDataNotification handler and moving corresponding functions/vars when symbols are added/updated/removed
