### ISSUE TITLE
need improvements to primary versus secondary highlighting on reflection view

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#2696]
<img width="1532" alt="Screen Shot 2021-10-12 at 7 48 55 PM" src="https://user-images.githubusercontent.com/140215/137043850-bb29bcee-fd15-4d04-a86b-72190cb34105.png">

Note that 118a and 1192 are supposedly different highlight colors but it's very subtle.

Once again in dark theme which is a little better, but not great if they aren't contiguous: 

<img width="1515" alt="Screen Shot 2021-10-12 at 7 50 24 PM" src="https://user-images.githubusercontent.com/140215/137043935-b1236869-f7d7-4993-acaf-e64ee42f45cc.png">

**Comment by yrp604** [comment]
More general dup of #2506, feel free to close mine.

**Comment by psifertex** [comment]
Nope, definitely a dupe.
