### ISSUE TITLE
Find All doesn't find all in IL Views

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#2700]
**Binary Ninja Version**
2.4 Stable 

**Describe the bug**
Find all code doesn't wait for IL functions to be populated prior to searching their contents as can be seen by searching for 'Loading' on any sufficiently large binary

![image](https://user-images.githubusercontent.com/10556585/137390638-b0441317-ac7d-4833-9b6d-0933746c16e8.png)

**To Reproduce**
1. CMD+F
2. Type 'Loading'
3. Click 'Find all'
4. Click 'Find'

**Expected behavior**
Find all should generate all IL to be searched.

**Comment by xusheng6** [comment]
Fixed in https://github.com/Vector35/binaryninja/commit/7bbcb062ba2669768c3518fafa1503a7bf2d71ad. Credit goes to @plafosse
