### ISSUE TITLE
PDB Plugin should be prevented from running twice

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#2701]
PDB Plugin can be run many times. The PDB plugin should add some bit of metadata to prevent it from being run twice. All it does is take a long time to do nothing if you run it twice. It seemed to lock up the UI too, which is probably a separate bug.

**Comment by CouleeApps** [comment]
There is now a cancel button to speed up PDB parsing in the event you apply it twice. I'm going to leave that ability in, in case someone finds a private PDB and wants to load it over top of analysis that has already used a public PDB with less information.
