### ISSUE TITLE
Double Clicking a Type name in TypesView while a filter is selected does nothing

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#2704]
**Binary Ninja Version**
2.4 dev

**Describe the bug**
If you have a filter applied in TypesView and you double click a type which doesn't match the current filter nothing occurs.

**To Reproduce**
1. Click on Types side bar
2. Apply a filter which shows a type and references a different type which doesn't match the filter
3. Double click that type
4. No navigation will occur

**Expected behavior**
On double click I would expect it to clear the filter before attempting to navigate. Maybe we could search the current filter first and then if its not found clear the filter and try again? That might make it a little less intuitive though.

**Comment by negasora** [comment]
Fixed in 2.4.3070-dev
