### ISSUE TITLE
Cancelling a FindNext action does not cancel

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#2706]
3068-dev

**Describe the bug**
Hitting cancel on a FindNext action does not stop the search

**To Reproduce**
1. Get a large binary and search for something
2. After you find something, hit find next
3. Hit cancel as it processes
4. See bug

**Expected behavior**
Cancel stops the search

**Screenshots**
![please-stop-searching](https://user-images.githubusercontent.com/8716677/137395259-129a07c3-e390-41ef-9a96-835a918349b8.gif)

**Version and Platform (required):**
 - Binary Ninja: 3068
 - OS: Windows
 - Version 11

**Comment by xusheng6** [comment]
It is verified this is fixed after the above mentioned perf issue is fixed
