### ISSUE TITLE
Display Best-Guess IL in XRefs

### ISSUE THREAD

**Issue by KyleMiles** [Vector35/binaryninja-api#2715]
This could be considered a low-effort, early version of #1617.

With the recent improvement of mappings between ILs, I think it would be useful to add a toggle to display the current IL for the given address of each cross reference.  If the IL for the function the cross reference is pointing to isn't available, we could fall back on disassembly and/or queue the function analysis in the background.

**Comment by plafosse** [comment]
Added in 3.1.3625
