### ISSUE TITLE
iOS Type Libraries

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#2736]
If we can generate macOS type libraries, we can likely generate iOS ones easily too. Here's a shortlist of iOS type libraries we may want:

- libSystem.dylib
- dyld
- libc++abi.dylib
- Foundation.framework
- Kernel.framework
- IOKit.framework

**Comment by 0cyn** [comment]
Resolved in **dev builds >= 4.1.5601**
