### ISSUE TITLE
Support Python 3.10 in UIPlugins 

### ISSUE THREAD

**Issue by XVilka** [Vector35/binaryninja-api#2740]
After a recent update to Fedora 35, where Python 3.10 is the default Python version, BInary Ninja shows me:
```
Python 3.10 is unsupported by PySide. UI plugins have been disabled. To enable UI plugins, select a Python Interpreter in Settings between version 3.5 and 3.9
```

2.4.3081-dev Personal (Build ID e6569ee9)

Would be nice to have a support for it, now it's somewhat mainstream.

**Comment by thanasisk** [comment]
Can you please prioritize this or at the very least suggest a workaround?

**Comment by psifertex** [comment]
There are no known work-arounds because QT for Python (PySide) requires QT 6.2 which made some other changes which are impacting our builds. I can look into it again but no promises on schedule. In the meantime, simply installing an older python or using one of the supported linux platforms is the best work-around.

**Comment by thanasisk** [comment]
@psifertex thanks for getting back to us and for the quick reply. I understand that downgrading the system python might not be a trivial exercise and can lead to unexpected bugs. Is there a way to use a `virtualenv` with BN?

**Comment by thanasisk** [comment]
`Failed to import python plugin: official/Vector35_sigkit: No module named 'flatbuffers'`
`Failed to load plugin: Vector35_sigkit`
are side effects as well - just as an FYI

**Comment by psifertex** [comment]
Yup, see the following setting:
<img width="1130" alt="Screen Shot 2021-11-28 at 3 36 23 PM" src="https://user-images.githubusercontent.com/140215/143785044-d8c170c8-381b-47b9-8fbb-529be3f6d11a.png">

**Comment by psifertex** [comment]
I guess that is a better work-around I should have thought about. 😉

**Comment by psifertex** [comment]
Also, the flatbuffers issue isn't 3.10 specific--when you switch python versions or interpreters (even to an identical version) you're not going to have the same python dependencies installed. The quick fix is that you need to run `python -m pip install flatbuffers` (or equivalent for whatever missing packages) after switching versions in the new runtime.

**Comment by thanasisk** [comment]
For those that want to implement the `virtualenv` workaround, I wrote some instructions: https://akostopoulos.blog/2021/12/07/fixing-python-3-10-incompatibilities-in-binary-ninja/

**Comment by D0ntPanic** [comment]
Fixed in dev build 3401

**Comment by plafosse** [comment]
Correction Fixed in dev build 3355
