### ISSUE TITLE
Xref widget always shows outgoing xref icon in table mode

### ISSUE THREAD

**Issue by lwerdna** [Vector35/binaryninja-api#2745]
**Binary Ninja Version**
2.4.2846

**Describe the bug**
Cross reference icon changes depending on whether the cross references view is in table form or not.

**To Reproduce**
1. Open a binary and select a function with cross references.
2. In the cross references widget, right click and select "View as table"

**Expected behavior**
The icon should stay the same.

**Screenshots**

![xref_default](https://user-images.githubusercontent.com/474191/139482175-30e4e18e-5610-4c63-a55e-d58e3c1f461d.png)

![xref_table](https://user-images.githubusercontent.com/474191/139482188-8e41d60f-5045-4d8b-9e01-9ac909429861.png)

**Version and Platform (required):**
 - Binary Ninja: Dev 2.4.2846
 - OS: MacOS 11.4 Big Sur

**Additional context**

We should clearly define what the icon means. In default (non-table) form, the tail of the arrow is leaving a box, so one might think the box is the source of the cross reference, and the arrow points to the destination. However, due to rendering positioning in the widget, the head of the arrow is drawn next to the address of the cross reference, so it looks as if it's pointing toward the source.

**Comment by xusheng6** [comment]
The real issue is the table mode always displays the icon for outgoing xref
