### ISSUE TITLE
Implement PEP-0561 - py.typed

### ISSUE THREAD

**Issue by justdaniel-gh** [Vector35/binaryninja-api#2747]
Could you add the `py.typed` file to the top-level python API directory? This will help tools like `mypy` run properly.

See: https://www.python.org/dev/peps/pep-0561/#toc-entry-5

**Comment by justdaniel-gh** [comment]
Along the same lines... some `# type: ignore` lines contain additional trailing comments that do not meet PEP 484 recommendations (missing `#` before the trailing comment).

See: https://www.python.org/dev/peps/pep-0484/#type-comments

Fix: `sed -i 's/# type: ignore \(.*\)/# type: ignore # \1/' binaryninja/python/binaryninja/*.py`

**Comment by psifertex** [comment]
Thanks for pointing that out, I've added the `py.typed` file and made those changes. Thanks for making it easy. :-)
