### ISSUE TITLE
Armv7 BE8 support does not properly handle references to global strings

### ISSUE THREAD

**Issue by jkalez** [Vector35/binaryninja-api#2749]
**Binary Ninja Version**
2.4.3090-dev

**Describe the bug**
Armv7 BE8 binaries do not properly handle references to global strings, and likely other global data.

**To Reproduce**
1. Load the attached libssl_armv7be8.so binary
2. Open the SSL_SESSION_print function in HLIL
3. Observe that calls to `BIO_puts` do not have their strings populated in the arguments
4. Repeat the same steps with the attacked libssl_x64.so binary and observe that in the same location, strings are populated in the arguments

**Expected behavior**
I expect the behavior we get in the Armv7 BE8 version (incorrect) to be the same as x64 (correct)

**Screenshots**
![armv7be8](https://user-images.githubusercontent.com/91279640/139858994-765309b4-3100-4d19-9974-06ed92296dd1.png)
![x64](https://user-images.githubusercontent.com/91279640/139858995-7083c6f2-5805-4379-9fb5-a85b0cafdedb.png)

**Version and Platform (required):**
 - Binary Ninja: 2.4.3090-dev
 - OS: Ubuntu
 - Version 20.04

**Files**
[binja_libssl.tar.gz](https://github.com/Vector35/binaryninja-api/files/7461129/binja_libssl.tar.gz)
Both libraries included in the tarball

**Comment by plafosse** [comment]
Thanks for the detailed report and test case this helped us quickly narrow down the issue. Fixed in 2.4.3100
