### ISSUE TITLE
show imported libraries in Triage Summary

### ISSUE THREAD

**Issue by loverics** [Vector35/binaryninja-api#2765]
I wish that I could see a list of imported libraries in Triage Summary. It would keep me from switching to an external program to get this info. I'm sure I can do this with the api in the python console but I would much prefer it was available in the Triage Summary. 

Near term solution:  

I'd like to see the list of imported libraries to the left of `Imports`. I'd like to be able to select a library to filter the imports shown.

![triage_summary_libraries](https://user-images.githubusercontent.com/18367903/142454933-4c73ca74-5cf3-4d65-8808-08e3d48d4375.png)

Stretch goal:

The main reason I ask for the above is that I want to open the library for a given imported symbol in binja without going to external utils to find the library of interest. With that goal in mind I'd like to:

1. Configure a Triage view setting for a library search directory
2. Allow the user to open a selected library in binja from Triage view

Alternative solution:

My current solution is to open a terminal use `rabin2` to get the imported libraries for the binary I currently have open in binja. Then I go back to binja and open the library I want to examine.

``` bash
$ rabin2 -l usr/bin/diagTool
[Linked libraries]
libcutil.so
libos.so
libcmm.so
libxml.so
libpthread.so.0
librt.so.0
libgdpr.so
libc.so.0

8 libraries
```

**Comment by plafosse** [comment]
On top of linear view you can see the list of libraries. It would be nice to see in the triage view too. Additionally you can get this in the python console using `bv.libraries`

**Comment by xusheng6** [comment]
This is now tracked by https://github.com/Vector35/binaryninja-api/issues/3266
