### ISSUE TITLE
C++ api circular include problem

### ISSUE THREAD

**Issue by hanssl** [Vector35/binaryninja-api#2769]
Binary Ninja Version: 2.4.2846, df7c027e
Platform: Ubuntu 20.04.3 LTS

I pulled the C++ api code and tried to build the examples.  I get pages of undefined references during the link stage.

I created a test to simplify the issue.  
1. I copied the /example/bin-info example to the main binaryninja-api directory
2. I added 'add_subdirectory(bin-info)' to /binaryninja-api/CMakeLists.txt so that this exe would be built regardless of DBN_API_BUILD_EXAMPLES setting.
3. I trimmed the /binaryninja-api/bin-info/src/bin-info.cpp file to include a min set of code that would compile and link (file attached).
4. NOTE: if you un-comment line 44 'new FileMetadata();' then the linker explodes with pages of undefined BinaryNinja references.

**Comment by hanssl** [comment]
[bin-info.cpp.txt](https://github.com/Vector35/binaryninja-api/files/7627232/bin-info.cpp.txt)

**Comment by hanssl** [comment]
I found that the problem is with the stable branch (v. 2.4.2846 df7c027e).  If I switch Binaryninja to the dev branch then the C++ api examples build and link.

**Comment by psifertex** [comment]
iirc this is expected -- there are several fixes to the API and example build process since stable.

**Comment by psifertex** [comment]
This should have been closed a while ago, sorry for leaving it open.
