### ISSUE TITLE
C++ api examples x86_extension missing files

### ISSUE THREAD

**Issue by hanssl** [Vector35/binaryninja-api#2770]
The file /binaryninja-api/examples/x86_extension/CMakeLists.txt includes tries to add the files src/asmx86/asmx86.c and src/asmx86/asmx86.h but the /binaryninja-api/examples/x86_extension/src/asmx86 directory is empty.

The project will not build.

**Comment by nshp** [comment]
asmx86 is a git submodule. Run `git submodule update --init --recursive` in the repo to fetch and check out submodules.

**Comment by hanssl** [comment]
my bad.
