### ISSUE TITLE
Section hints for symbol/name collisions

### ISSUE THREAD

**Issue by mechanicalnull** [Vector35/binaryninja-api#2776]
When I use the "Go to Address" functionality and type in the name of a function with multiple matching symbols, I'm presented with a dialog that asks me to select between ambiguous symbols, where the only clarifying information is the address for each. A similar conundrum occurs when a user searches in the symbol view for a symbol and finds multiple matches with the same name. 

While it's a minor issue, I feel like putting a hint next to each name with the name of the section containing the symbol would help users tell the difference between the options (in the times I've encountered this issue, it's just been the same symbol in multiple sections like `.plt`, `.got.plt`, and `.extern`). This would only need to be done in the case of symbol name collisions.

Typically the result I want is the first result, so I've thought maybe this isn't an issue and doesn't need to be fixed, but it seems like the attitude of "experienced users don't need this" is the wrong one to take when a solution seems fairly straightforward. Also, other variations on this issue might occur and maybe it would be helpful to know what section a symbol is in some of the related dialogs.

**Comment by psifertex** [comment]
added in builds >= 3612

<img width="245" alt="Screen Shot 2022-08-06 at 3 12 29 AM" src="https://user-images.githubusercontent.com/140215/183238719-593ac4de-3cc9-4b2d-a70b-c63d0c3bb4fa.png">
