### ISSUE TITLE
eax is incorrectly being marked as the constant 0

### ISSUE THREAD

**Issue by gsingh93** [Vector35/binaryninja-api#278]
The two screenshots below show the assembly and IL for a function where `eax` is being treated as the constant `0x0`, but it's clearly being modified.
<img width="936" alt="screen shot 2016-06-04 at 1 34 44 pm" src="https://cloud.githubusercontent.com/assets/1012677/15802043/1f4175f2-2a5c-11e6-84dc-eff026a38fe1.png">
<img width="897" alt="screen shot 2016-06-04 at 1 43 35 pm" src="https://cloud.githubusercontent.com/assets/1012677/15802042/1f408534-2a5c-11e6-99b5-c8fbcd51f3e0.png">

**Comment by plafosse** [comment]
Could you please provide a binary or verify that its bug still exists on the "dev" update channel?  The whole data flow system has been refactored and it is unlikely that this issue still exists.

**Comment by psifertex** [comment]
Marking this as closed unless you can re-test and verify whether it's still live.

**Comment by gsingh93** [comment]
Yup, this was fixed in dev. Thanks!
