### ISSUE TITLE
Allow wildcard syntax when searching for hex strings

### ISSUE THREAD

**Issue by duk-37** [Vector35/binaryninja-api#2787]
**Is your feature request related to a problem? Please describe.**
Scanning for sequences of bytes with wildcards should not require writing a plugin.

**Describe the solution you'd like**
Some sort of wildcard syntax for hex strings. i.e. `*` or `?` or `??`.
`??` could allow for matching nibbles inside bytes, yara-style.

**Describe alternatives you've considered**
Current plugins are outdated and plugins themselves would presumably be much slower than native integration.

**Comment by xusheng6** [comment]
Thanks for the report! Closed in favor of #2788.
