### ISSUE TITLE
HLIL if/do/while gutter highlights

### ISSUE THREAD

**Issue by withzombies** [Vector35/binaryninja-api#2790]
Please highlight the gutter for the selected control statement, to better understand what operations are included. IDEs have curly brace matching and highlighting with many different solutions but I think a small tweak will be a big improvement:

Before:
<img width="533" alt="before" src="https://user-images.githubusercontent.com/4872355/146623951-cdabde04-3dd7-4c5c-9929-673bb7caa0b2.png">

After example:
<img width="533" alt="after" src="https://user-images.githubusercontent.com/4872355/146623955-ef0eee23-8fca-4698-972d-6c6cc9ae2680.png">

**Comment by fuzyll** [comment]
As per the issue above that I just closed, we now also need to make sure this is done in Pseudo C view in addition to HLIL.

**Comment by CouleeApps** [comment]
This is implemented on versions >= 4.1.5240-dev:

<img width="414" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/711973/cb9e7213-d433-4351-9e86-a5892125940b">

**Comment by CouleeApps** [comment]
Good catch, that should be fixed on >= 4.1.5246
