### ISSUE TITLE
decompiler thinks arm64 `fcmp` doesn't affect condition flags

### ISSUE THREAD

**Issue by comex** [Vector35/binaryninja-api#2791]
**Binary Ninja Version**
Version 2.5.3129-dev (Build ID 9038e9f1)

**Describe the bug**
Binary Ninja seems to misunderstand how the arm64 instruction `fcmp` affects condition codes.

**To Reproduce**
Given this assembly:
```
    cmp x0, x1
    fcmp s0, s1
    bne L_not_equal
```
[(example binary here)](https://github.com/Vector35/binaryninja-api/files/7739898/test.zip):

the generated LLIR is
```
   0 @ 00003f9c  cond:0 = x0 != x1
   1 @ 00003fa0  s0 f- s1
   2 @ 00003fa4  if (cond:0) then 3 @ 0x3fb0 else 5 @ 0x3fa8

   3 @ 00003fb0  x0 = 1
   4 @ 00003fb4  <return> jump(x30)

   5 @ 00003fa8  x0 = 0
   6 @ 00003fac  <return> jump(x30)
```
This shows the branch depending on the `cmp` result.

**Expected behavior**
`fcmp` writes the same condition flags as `cmp` (i.e. PSTATE.{N,Z,C,V}).  So in this example, the `cmp` is useless, and the branch actually depends on the `fcmp` result.

**Version and Platform (required):**
 - Binary Ninja: Version 2.5.3129-dev (Build ID 9038e9f1)
 - OS: macOS
 - Version: 11.6

**Comment by yrp604** [comment]
This is a variant of: https://github.com/Vector35/arch-arm64/issues/84 -- the arm64 disassembler does not set `instr.setflags`.

Until it's fixed properly, this is a workaround in the arch-arm64 repo:
```
diff --git a/il.cpp b/il.cpp
index 4755af9..71c0132 100644
--- a/il.cpp
+++ b/il.cpp
@@ -1488,6 +1488,7 @@ bool GetLowLevelILForInstruction(
        break;
        case ARM64_FCMP:
        case ARM64_FCMPE:
+               instr.setflags = 1;
                il.AddInstruction(il.FloatSub(REGSZ_O(operand1), ILREG_O(operand1),
                    ReadILOperand(il, operand2, REGSZ_O(operand1)), SETFLAGS));
                break;
```

**Comment by lwerdna** [comment]
The problem is `CMP` has decode psuedo code:

```
integer d = UInt(Rd);
integer n = UInt(Rn);
integer m = UInt(Rm);
integer datasize = if sf == '1' then 64 else 32;
boolean sub_op = (op == '1');
boolean setflags = (S == '1');    <--- !!!!!!!!!!!!!HERE!!!!!!!!!!!!!!!!
ExtendType extend_type = DecodeRegExtend(option);       
integer shift = UInt(imm3);
if shift > 4 then UNDEFINED;
```

And `FCMP` has:

```
integer n = UInt(Rn);
integer m = UInt(Rm);   // ignored when opc<0> == '1'

integer datasize;
case ftype of
    when '00' datasize = 32;
    when '01' datasize = 64;
    when '10' UNDEFINED;
    when '11'
        if HaveFP16Ext() then
            datasize = 16;
        else
            UNDEFINED;

boolean signal_all_nans = (opc<1> == '1');
boolean cmp_with_zero = (opc<0> == '1');
```

So there is appears to be no way, based on decoding pseudo code alone, to tell that the instruction affects flags.

I'm near ready to call it a spec bug :(

Later, in the operational pseudo code, it has:

```
...
PSTATE.<N,Z,C,V> = FPCompare(operand1, operand2, signal_all_nans, FPCR[]);
...
```

I'm getting tempted to set setflags for any encoding matching `.*CMP.*`.

**Comment by lwerdna** [comment]
Please update to latest dev release for the fix 👍
