### ISSUE TITLE
Strings view does not load all strings sometimes

### ISSUE THREAD

**Issue by thisusernameistaken** [Vector35/binaryninja-api#2796]
**Binary Ninja Version**
2.4.3108-dev

**Describe the bug**
When loading a bndb saved for a larger binary (150mb+), only a few strings appear in the strings view or in bv.get_strings. The only way I've noticed to get them to appear is to reanalyze the entire binary, which can take a long time on these larger binaries, or press "a" on a string. Pressing "a" on a string seems to analyze around 2097000 byte chunks at a time, so to get all the strings to load, I have to constantly press "a" on a string a ton of times. After saving the bndb again with all the strings loaded and reopening the bndb, the strings are gone again and I have to repeat the process.

**To Reproduce**
1. Open a bndb of a large binary
2. View strings window and see only a fraction of the strings loaded
3. Press "a" on a string and see a chunk of strings added to the strings view, but not all of them

**Expected behavior**
When opening a bndb, all the strings in the binary should appear in the strings window

**Version and Platform (required):**
 - Binary Ninja: Dev 2.4.3108 
 - OS: Ubuntu Linux
 - Version  20.04

**Comment by plafosse** [comment]
thanks I think I have a fix for this issue. Hopefully it will be pushed out today.

**Comment by plafosse** [comment]
Fixed in 2.5.3190

**Comment by hanssl** [comment]
I am seeing this same bug on 3.0.3233 for small binaries.
