### ISSUE TITLE
Hex Templates

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#28]
_From @psifertex on May 5, 2015 14:9_

Definitely post-v1, gonna be a killer feature though.

_Copied from original issue: Vector35/binaryninja#16_

**Comment by psifertex** [comment]
We don't consider this feature complete yet, but it's made a lot of progress since it was first filed. See this example video showing how to use the type system to https://youtu.be/sCKiG_xdNSc

**Comment by plafosse** [comment]
Use Kaitai Plugin or Buy 010 instead :P
