### ISSUE TITLE
Decompiler should split stores that write to multiple struct fields

### ISSUE THREAD

**Issue by comex** [Vector35/binaryninja-api#2805]
**What is the feature you'd like to have?**
Suppose the compiler optimizes two stores to adjacent 32-bit values into a single 64-bit store instruction.  I would like Binary Ninja to split it back into multiple stores when applicable based on type information.  (Same applies to loads.)

For example, [this example binary](https://github.com/Vector35/binaryninja-api/files/7786430/str.zip) initially decompiles as:
```
00000000  void start(int64_t* arg1)
00000008      *arg1 = 0x4358000043c00000
```

I happen to know that the 64-bit constant 0x4358000043c00000 actually represents a pair of 32-bit floats, 384.0 and 216.0.  So I create a struct in the Types view:
```
struct point __packed
{
    float x;
    float y;
};
```

And I set the type of `arg1` to `struct point *`.

This just changes the decompiled output to:
```
00000000  void start(struct point* arg1)
00000008      arg1->__offset(0x0).q = 0x4358000043c00000
```
But I would like something more like
```
00000000  void start(struct point* arg1)
00000008      arg1->x = 384.0
00000008      arg1->y = 216.0
```
**Is your feature request related to a problem?**
It's difficult to make sense of these kinds of writes otherwise.

**Are any alternative solutions acceptable?**
Some way to mark individual instructions to be split (as opposed to determining it based on types) might also work, and might be more flexible in some cases (e.g. with unions), though it would be less convenient in the common case.

**Comment by fuzyll** [comment]
This should have been fixed in builds >= 3563. Please let us know if it's not.
