### ISSUE TITLE
arm64 `fcmp` doesn't work with many condition codes

### ISSUE THREAD

**Issue by comex** [Vector35/binaryninja-api#2808]
**Version and Platform (required):**
- Binary Ninja Version: Version 2.5.3140-dev (Build ID 532595b6)
- OS: macOS
- OS Version: 11.6

**Bug Description:**

[This binary](https://github.com/Vector35/binaryninja-api/files/7790320/fcmp.zip) demonstrates using all 14 ARM condition codes with `fcmp`.  Among these:
- `eq`, `ne`, `cs`, and `cc` look good.
- `ge`, `lt`, `gt`, and `le` are decompiled using `unimplemented`, e.g.:
  ```
  000000f0  int64_t test_ge(int32_t arg1 @ v0, int32_t arg2 @ v1)
  000000f0      int64_t x0 = 0
  000000f4      arg1 f- arg2
  000000f4      bool v = unimplemented  {fcmp s0, s1}
  000000f4      bool n = unimplemented  {fcmp s0, s1}
  000000f8      if (n == v)
  00000100          x0 = 1
  000000fc      return x0
  ```
  This is unfortunate, since those condition codes are very common.
- `ls` and its inverse `hi` are decompiled correctly but suboptimally.  For `ls`:
  ```
  000000d8  int64_t test_ls(float arg1 @ v0, float arg2 @ v1)
  000000d8      int64_t x0 = 0
  000000dc      arg1 - arg2
  000000e0      if (arg1 == arg2 || arg1 < arg2)
  000000e8          x0 = 1
  000000e4      return x0
  ```
  This could be `arg1 <= arg2`.

- `pl` is decompiled incorrectly:

  ```
  00000078  int64_t test_pl(int32_t arg1 @ v0, int32_t arg2 @ v1)
  00000078      int64_t x0 = 0
  00000080      if (arg1 f- arg2 s>= 0)
  00000088          x0 = 1
  00000084      return x0
  ```

  In reality it should be `not(arg1 < arg2)` (see below table), which is not the same as `arg1 - arg2 >= 0`.  For example, if one or both arguments is NaN, `not(arg1 < arg2)` is true, but `arg1 - arg2 >= 0` is false.

- `mi` is similarly oddly decompiled as `arg1 f- arg2 s< 0` when it should be `arg1 < arg2`.  I can't think of any cases within standard IEEE floating point where these expressions aren't equivalent, but under IEEE floating point with subnormals disabled (common in games), [there are pairs of floats](https://stackoverflow.com/a/54532647) `a`, `b` such that `a < b` but `a - b == 0.0`.

Here is the relevant table from the ARM manual:

<img width="819" alt="image" src="https://user-images.githubusercontent.com/47517/147696978-bd8616b1-e459-4cbd-bdaf-7db3e19bffda.png">

**Comment by rssor** [comment]
This looks like a result of us having not implemented semantic flag groups for arm. Fortunately the patch for this should wind up being pretty small.
