### ISSUE TITLE
User Informed Dataflow

### ISSUE THREAD

**Issue by withzombies** [Vector35/binaryninja-api#281]
It'd be nice if you could set register values to be used by the auto analysis. It'd be especially useful with odd calling conventions or LTO.

For example, this binary uses ebx-based addressing:

![4_49550685506635985](https://cloud.githubusercontent.com/assets/4872355/15806681/dd265f78-2b16-11e6-8f68-88051a6c7b56.png)

![4_49550685506635984](https://cloud.githubusercontent.com/assets/4872355/15806682/e1906a7c-2b16-11e6-86eb-40e5d867b576.png)

I could write a script to set ebx's value, then this should be calculated properly until binja has inter-procedural dataflow:
![4_49550685506635983](https://cloud.githubusercontent.com/assets/4872355/15806683/e3cd3248-2b16-11e6-9755-3f809020b180.png)

**Comment by withzombies** [comment]
Also, these features would be nice to evaluate some functions with.

For example, it'd be neat to make a bunch of "unit tests" that you can use to identify standard pure functions. Something like 10 strings of differing length passed as parameter 1 then checking the return value to see if the lengths come back and then making that function as strlen. You could do the same for a lot of simple c string functions.

**Comment by psifertex** [comment]
There's a chance this gets fixed as a part of #264 as referred to above, but not sure yet so leaving for a future milestone for now.

**Comment by chinmaydd** [comment]
This is now implemented and is a part of 2.1.2385-dev. More details on the same are available [here](https://binary.ninja/2020/09/10/user-informed-dataflow.html).
