### ISSUE TITLE
Copy/paste does on instruction bytes does not copy correct data

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#2810]
**Version and Platform (required):**
- Binary Ninja Version: 2.4.3145-dev (if version is stable, please also test the latest development build via the "Update Channel" option)
- OS: Windows
- OS Version: 11

**Bug Description:**
When you copy instruction bytes with 0 nibbles in them, some of them are removed.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Go to 18008483c
2. Click on the instruction bytes
3. Copy
4. Paste

**Expected Behavior:**
Copy/paste works consistently on any text binja displays

**Screenshots:**
![copy-paste-null](https://user-images.githubusercontent.com/8716677/147730228-94e818e9-092f-4e10-93e9-31e54c2af62e.gif)

**Additional Information:**
[ntdll.dll.txt](https://github.com/Vector35/binaryninja-api/files/7791882/ntdll.dll.txt)

**Comment by CouleeApps** [comment]
Looks like it's not extending the `00` byte when copying, and only copying `0`. Will be fixed on next dev.
