### ISSUE TITLE
Remove the secret Filter triangle

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#2819]
**Version and Platform (required):**
- Binary Ninja Version: 2.5.3149-dev
- OS: macOS 12.1

**Bug Description:**
The secret triangle behind "Filter" needs to go.

**Steps To Reproduce:**
Open the Cross References pane on the left, observe the extra triangle behind the word "Filter".

**Expected Behavior:**
There can only be one!

**Screenshots:**
<img width="117" alt="Screen Shot 2022-01-04 at 1 57 39 PM" src="https://user-images.githubusercontent.com/607452/148111692-11f108aa-2b4f-4317-9a41-37b41c03c985.png">

**Comment by jonpalmisc** [comment]
This appears to be a Qt bug after further testing. Obvious solution is to rewrite the entire UI using wxWidgets.

**Comment by bpotchik** [comment]
Fixed in `3.0.3250-dev`.
