### ISSUE TITLE
msvcrt!_CxxThrowException should be marked no return

### ISSUE THREAD

**Issue by withzombies** [Vector35/binaryninja-api#282]
<img width="1048" alt="screen shot 2016-06-05 at 5 50 37 pm" src="https://cloud.githubusercontent.com/assets/4872355/15808490/928b766c-2b46-11e6-8119-e97af677c3e3.png">

**Comment by psifertex** [comment]
You can add prototypes to `/Applications/Binary Ninja.app/Contents/Resources/types/windows.c` yourself to test, but we should probably add others.

Also, just adding a note that Peter made in slack that I agree with -- the UI should allow marking functions as no-return as well so it can at least be manually fixed up other instances.

**Comment by bpotchik** [comment]
Fixed 6 months ago.
