### ISSUE TITLE
QMessageBox doesn't show title on macOS

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#2822]
**Version and Platform (required):**
- Binary Ninja Version: 2.5.3150ish
- OS: macOS
- OS Version: 12.0.1

**Bug Description:**
Might not necessarily be our bug, but it likely impacts us in a number of places. On macOS, QMessageBox dialogs don't show their title text and could be missing relevant context.

Someone needs to take a close look at uses of QMessageBox and make sure nothing is being lost. Or, we should hack (patch?) Qt to display the title as expected.

**Steps To Reproduce:**
```
from PySide6.QtWidgets import QMessageBox
execute_on_main_thread_and_wait(lambda: QMessageBox.warning(None, "Title", "Text"))
```

**Expected Behavior:**
I expected the message box to show both its title and text.

**Screenshots:**
![image](https://user-images.githubusercontent.com/711973/148132083-2ff8ac49-739c-4e66-8b31-783c24ef91ad.png)

**Comment by CouleeApps** [comment]
Qt (and macOS HIG) claim this is intended behavior. Personally, that seems Kinda Dumb and like we might lose imporant contextual information in some dialogs. It would be pretty trivial to patch Qt itself to include titles, but supposedly there is a workaround with the power of C++ virtual functions:

```
msgBox.QDialog::setWindowTitle("My Title");
```

Whatever the case, someone should definitely make sure all the dialogs are actionable even without their title, or otherwise patch the title text back onto the dialogs somehow.

**Comment by psifertex** [comment]
Closing for now -- if specific popups are problematic we'll fix them as needed but since the primary dev platform is macos I'd argue that they're all fairly self-explanation.
