### ISSUE TITLE
`continue` statement wrongly optimized out during optimizations/lifting within a jump table

### ISSUE THREAD

**Issue by ek0** [Vector35/binaryninja-api#2824]
**Version and Platform (required):**
- Binary Ninja Version: Version 2.5.3163-dev Personal
- OS: Microsoft Windows 11
- OS Version: 21H2

**Bug Description:**
One of the jump table optimizations/lifting step removes the `continue` statement if the jump table is in a loop, and the case contains a `if()/else()` statement. Here is a snippet of the [original source code](https://gist.github.com/ek0/a7f9bf7805874ab33ec1211333c2d5a0#file-test_x86-cc-L231):
```cpp
uint32_t jtbl_test(uint32_t a)
{
    uint32_t b = a;
    uint32_t p = a;
    while(true)
    {
        switch (b)
        {
        // ...
        case 12:
            b = 13;
            if (a == 0)
                b = 13;
            else
                b = 14;
            p = b + a;
            continue;
        case 13:
        {
            b = 14;
            continue;
        }
        case 14:
        {
            b = 9876;
            //uint32_t c = 1;
            //c = b * 2;
            //uint64_t d = c / 3;
            if (a == 0)
                b = 123;
            else
                b = 12345;
            p = b + a;
            continue;
        }
        // ...
```
and here is the resulting HLIL for this snippet:
```cpp
// ...
    case 0xb
        int32_t var_18_1 = 0xd
        if (arg1 != 0)
        {
            var_18 = 0xe
        }
        else
        {
            var_18 = 0xd
        }
        uint32_t var_10_1 = var_18 + arg1
    case 0xc
        var_18 = 0xe
        continue
    case 0xd
        int32_t var_18_2 = 0x2694
        if (arg1 != 0)
        {
            var_18 = 0x3039
        }
        else
        {
            var_18 = 0x7b
        }
        uint32_t var_10_2 = var_18 + arg1
// ...
```
It seems to happen during the `Step 6` of the lifting, if I trust the `high_level_il` report. During the merging (?) of the `if/else` statement and the following `var_10_2 = var_18 + arg1`

**Steps To Reproduce:**
- Download the attached [adder.zip](https://github.com/Vector35/binaryninja-api/files/7830719/adder.zip) attached. This file includes the sample example and its PDB file. You can find the source code for the executable [here](https://gist.github.com/ek0/a7f9bf7805874ab33ec1211333c2d5a0).
- Open `adder.exe` in binary ninja
- Load the associated PDB
- Go to `jtbl_test`
- Open the HLIL view and look at `case 0xb` or `case 0xd`

**Expected Behavior:**
The HLIL should keep the `continue` statement. Otherwise one could think it is a fall through.

**Comment by D0ntPanic** [comment]
Fixed in build 3437
