### ISSUE TITLE
Sometimes FP arguments are not correctly used/propagated in the MLIL/HLIL function

### ISSUE THREAD

**Issue by ek0** [Vector35/binaryninja-api#2828]
**Version and Platform (required):**
- Version 2.5.3163-dev Personal
- OS: Microsoft Windows 11
- OS Version: 21H2

**Bug Description:**
FP arguments are usually passed through `xmm0,xmm1,xmm2,xmm3` for Windows executables. While the calling convention seems to reflect this, it is not always automatically detected by the analysis. Example: 
![image](https://user-images.githubusercontent.com/7302683/148694531-f9b52cd7-f94d-4102-9b16-a547da0302c6.png)

The HLIL shows `zmm0` as uninitialized and `arg1` seems to never be used, which is wrong.
Instead, it should look like this:
![image](https://user-images.githubusercontent.com/7302683/148694550-b2e329fb-dd9b-4eaf-a6b1-57274e2e2987.png)

A quick workaround is to manually change the function prototype. 

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Download [adder.zip](https://github.com/Vector35/binaryninja-api/files/7835601/adder.zip). Source code can be found [here](https://gist.github.com/ek0/a7f9bf7805874ab33ec1211333c2d5a0).
2. Open `adder.exe` in binary ninja and load the associated PDB.
3. Open any `test_f2i` or `test_f2i_smaller` functions in HLIL view. If you have [this](https://github.com/Vector35/arch-x86/pull/26) patch for `COMISD/UCOMISD` you can also look at `test_double_XXX` functions.

**Additional information**
I checked some other bigger functions, such as `cos` in `ntdll.dll`. It seems to work fine:
![image](https://user-images.githubusercontent.com/7302683/148694736-36813e25-9b1b-4677-ba10-b06446385c1c.png)
It is possible it is related to the function size or the way the argument registers are used in the function.

**Comment by plafosse** [comment]
This seems to have been fixed the last time we addressed calling convention issues. This is what you get out of the box now: 
<img width="420" alt="image" src="https://github.com/user-attachments/assets/786c11b9-e251-426a-a222-66dddbcef0a3">

**Comment by ConnorBP** [comment]
This issue is affecting me on the return arg. Floating point returns in xmm0 on function pointers with no function body within the same module are impossible to convince that they shouldn't be discarding the xmm0 during the translation from low to medium IL
