### ISSUE TITLE
HLIL variable values are incorrect when dealing with loops

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#2829]
**Version and Platform (required):**
- Binary Ninja Version: 2.5.3163-dev
- OS: Windows
- OS Version: 11

**Bug Description:**
HLIL dataflow in some contexts doesn't seem properly account for loops changing variable values

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Go to 0x04f7751
2. Click on the variable used to dispatch the switch statement
3. Hover and see the ConstantValue
4. Select the variables pane
5. Find the corresponding variable, see the difference

**Expected Behavior:**
HLIL dataflow values are accurate. In the above example, the HLIL dataflow value is correct at loop entry, but not for subsequent executions.

**Screenshots:**
![image](https://user-images.githubusercontent.com/8716677/148706227-a4f3eeea-b02c-4d24-8200-17d4c6c37552.png)

**Additional Information:**
binary can be provided on slack

**Comment by bpotchik** [comment]
See #2939, we have not added the ability to query variables in HLIL yet. The invalid queries have been fixed as of `3.0.3216-dev`.
