### ISSUE TITLE
Functions erroneously created overtop of  jump tables

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#2833]
**Version and Platform (required):**
- Binary Ninja Version: 3164-dev
- OS: Windows
- OS Version: 11

**Bug Description:**
In some arm64 binaries, functions are created over top of jump tables, despite having no code references to them.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open a recent xnu arm64 kernel
2. Click on tags
3. Search for 'udf', you should see a bunch of 'Opcode udf is unimplemented' in functions that start with 'jump_table_<addr>'
4. See error -- any 'udf' that occurs inside a jump table is likely not code.

**Expected Behavior:**
Functions should not be created here. Undefining these functions solve the problem immediately, but there are dozens if not hundreds of these and it's not clear why they are created.

**Screenshots:**
![image](https://user-images.githubusercontent.com/8716677/149042813-54349f8d-d91b-45e7-9731-f02cbd94db4c.png)

**Additional Information:**
Disabling linear sweep does not affect this, at least as far as I can tell.

**Comment by bpotchik** [comment]
These bad functions were coming from the LC_FUNCTION_STARTS section that gets processed. I've added some validation to this logic in the Mach-O loader to prevent obvious bad functions from being created.

Also, you can always open with options and deselect `loader.macho.processFunctionStarts`.

I've added lifting for the arm64 UDF instruction as well.

**Comment by bpotchik** [comment]
You can track #290 for better support of dyld shared and kernel cache images.

**Comment by bpotchik** [comment]
Fixed in `3.0.3249-dev`.
