### ISSUE TITLE
multiple close/save prompts after splitting window or popping out a pane

### ISSUE THREAD

**Issue by galenbwill** [Vector35/binaryninja-api#2834]
**Version and Platform (required):**
- Binary Ninja Version: 2.5.3165-dev
- OS: macOS
- OS Version: 12.1

**Bug Description:**

See subject

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open a binary
2. Name anything/change a byte
2. Click on minigraph in sidebar
3. Click minigraph popout button
4. Drag minigraph panel outside window so it opens in its own window
5. Close the new minigraph window

Proposed fix is to modify the detection of whether the database is dirty to check if another window with the same BNDB is already open

**Comment by D0ntPanic** [comment]
Fixed in build 3247
