### ISSUE TITLE
Logging system improvements

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#2837]
This issue is to document backend improvements to the logging system. The current logging system needs a bunch of improvements. I'd like a system much like python's logging library: https://docs.python.org/3/library/logging.html 

Users should be able to create different named loggers, register these loggers and look up loggers by name.
These loggers would function much like the existing log interface. I imagine code like this:

```python
from binaryninja.log import logger, get_logger
mylog = logger("My Logger") # <- this would create and register a logger called "My Logger"
assert mylog == get_logger("My Logger")
mylog.debug("Foobar")
mylog.disable()
```

Additionally I think these loggers should probably be registered against BinaryViews too. So something like:

```python
mylog = bv.logger("My Logger")
```

So you'd have _global_ and _view-centric_ logs. These backend changes would would then enable a host of new front end log improvements. You could for instance only view log output for your specific plugin or binary ninja component you're interested in.

**Comment by galenbwill** [comment]
…or filter and see only log for a particular binary view (to state the obvious)

**Comment by plafosse** [comment]
Added in 3.0.3297
