### ISSUE TITLE
Go to address relative to the base address of binary

### ISSUE THREAD

**Issue by dankope** [Vector35/binaryninja-api#2844]
**What is the feature you'd like to have?**
Have an option in the `Go to address` panel for going to an address relative to the base address of the binary.

**Is your feature request related to a problem?**
I have a relative virtual address which is `12D49`, the base address of the binary is `0x590000`, I want to use the `Go to address` panel to go to `0x5a2d49`, the option `Relative` in the panel is relative to the current cursors address, instead I want to have an option for the address I put into the textbox to be an offset from the binaries base address, **not my current cursors address**.

**Comment by joshwatson** [comment]
You can type `$start+12d49` to go to an address relative to the start of the binary.

**Comment by dankope** [comment]
Thanks @joshwatson!

**Comment by psifertex** [comment]
For some other nice shortcuts that you can use for that navigation box, checkout the docs on [parse_expression](https://api.binary.ninja/binaryninja.binaryview-module.html?highlight=parse_expression#binaryninja.binaryview.BinaryView.parse_expression)
