### ISSUE TITLE
Re-Open with Options causes universal binaries to forget arch

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#2845]
**Version and Platform (required):**
- Binary Ninja Version: 2.5.3176-dev
- OS: macOS
- OS Version: 12.0.1

**Bug Description:**
When you use Open with Options on a saved bndb of a universal binary, it forgets which architecture you selected and attempts to switch the bndb to the other arch. There is no option to pick an arch when opening the second time, so you cannot easily fix this or use Open with Options to change settings for any other reason.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open with Options /bin/ls on macOS 12.0.1 (here's a copy: [ls.zip](https://github.com/Vector35/binaryninja-api/files/7885633/ls.zip) )
2. Choose aarch64 as the architecture 
3. Continue opening the file
4. Save to a bndb anywhere
5. Close the bndb
6. On the new tab screen, right click the bndb you just created, and pick Open with Options
7. Notice the text "Updated load schema has been detected. Verify against old schema."
8. Notice the Mach-O load architecture is now x86_64

**Expected Behavior:**
I expected Open with Options to remember which arch I initially picked when creating a bndb.

**Screenshots:**
![image](https://user-images.githubusercontent.com/711973/149858358-e447315e-2e1a-49d1-8596-952fa96ca07b.png)

**Comment by bpotchik** [comment]
Fixed in `2.5.3179-dev`.
