### ISSUE TITLE
@deprecated decorators for python api

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#2846]
**What is the feature you'd like to have?**
A bunch of APIs are (or are soon to be) deprecated. It would be nice to have a consistent and easy way to mark them as such.

There are a few ways of doing this:
1. Handrolled deprecated decorator
2. This pip package: https://deprecation.readthedocs.io/en/latest/
3. Some other package?

**Comment by psifertex** [comment]
Added in https://github.com/Vector35/binaryninja-api/commit/bfeba3302e995fdba373603533fce54bf788adff
