### ISSUE TITLE
enhanced windows platform support

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#2849]
Windows has lots of data structures regularly accessed off of FS and GS -- we need to enhance our windows platform support to apply the appropriate data structures at those locations to improve analysis of some libraries

**Comment by fuzyll** [comment]
This is a duplicate of #1977, which we've earmarked for this next milestone anyway. Closing this in favor of that one.

**Comment by plafosse** [comment]
I don't believe this should have been closed. #1977 is a likely pre-requsite for this one.

**Comment by plafosse** [comment]
This is a duplicate of #1977 re-closing it 🤦
