### ISSUE TITLE
Stack View: Option to see variables as offset from esp

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#2866]
**What is the feature you'd like to have?**
I want the ability to switch stack view to show variables as offsets from the stack pointer at the current address, so that I can easily mentally map assembly to the variables I've defined.

**Is your feature request related to a problem?**
The stack view shows the stack frame offsets of all the variables relative to the stack pointer at the start of the function, but does nothing for variable offsets at an arbitrary point in the function after stack space has been reserved. This makes it difficult to find variables by referencing assembly, as they are named after their base offset, and that information is lost if you rename them.

I have a bunch of assembly and I want to see the stack layout around the variables I named, except I cannot easily find them.

E.g.: the variables I'm looking for here are accessed with [esp+0xf8], [esp+0xf0], [esp+0xe8], yet if I want to find them in the stack view I have to navigate to -0x260, -0x268, -0x270. There is not really a clear connection without trying to do the math on esp myself.
<img width="590" alt="image" src="https://user-images.githubusercontent.com/711973/150698259-89c796a5-874c-44ce-9276-8b26a033ad3c.png">

**Are any alternative solutions acceptable?**
Maybe adding esp offsets to the variable annotations when they are used? That seems like it will get very wordy very quickly.

**Comment by utkonos** [comment]
If this is implemented, can there be an option for the count being relative to the base pointer as well? Here is an example of a malware packer's decoding function and everything is relative to `ebp`. Therefore, the numbering in the Stack pane is off by one. Not quite as brain bending as your example that is relative to `esp` but still not ideal. So the UI doesn't get cluttered with different columns, have a new hamburger menu with a toggle that selects "default", "relative to base pointer", and "relative to stack pointer".

<img width="615" alt="image" src="https://user-images.githubusercontent.com/2775739/197324387-610f5c1c-64a1-40c7-a7d7-e7a7634d0307.png">

<img width="336" alt="image" src="https://user-images.githubusercontent.com/2775739/197324424-784ee113-148e-49e1-9017-3d661efb1168.png">

**Comment by CouleeApps** [comment]
Implemented in >= 4.1.5250-dev under the stack view context menu "Choose Base Register"

**Comment by utkonos** [comment]
@CouleeApps This feature should be very useful. I tried to articulate it a bit better in this discussion:
https://github.com/Vector35/binaryninja-api/discussions/5289

Do you think that the new feature would also basically satisfy this:
https://github.com/Vector35/binaryninja-api/issues/5297

I think being able to choose the base register handles 80% of the use case. I don't want to second guess the new implementation, but would the x64dbg stack distances via click still be something else to implement besides this?

**Comment by CouleeApps** [comment]
That is an interesting extension of this I had not considered! The implementation I just wrote only lets you base the offset on registers, but it should be pretty easily adaptable to any arbitrary offset value. I will look into that tomorrow and see how feasible it is, thanks for the heads-up!
