### ISSUE TITLE
add support for LC_DYLD_CHAINED_FIXUPS

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#2867]
https://github.com/xpcmdshell/bn-chained-fixups

**Comment by xpcmdshell** [comment]
If you need a reference for implementing this later, Siguza's code is more complete and may be more helpful:
https://github.com/Siguza/iometa/blob/master/src/macho.c

**Comment by psifertex** [comment]
Angr has a nice test case: https://github.com/angr/binaries/pull/80
