### ISSUE TITLE
SHL constant folding inaccurate

### ISSUE THREAD

**Issue by ek0** [Vector35/binaryninja-api#2868]
**Version and Platform (required):**
- Binary Ninja Version: Version 3.0.3208-dev Personal
- OS: Microsoft Windows 11
- OS Version: 21H2

**Bug Description:**
`SHL` constant folding gives inaccurate results.

**Steps To Reproduce:**
This is my current setup. In visual studio I have 2 files:
- main.cc
- funcs.asm

```cpp
// main.cc
#include <iostream>

extern "C" uint64_t test_shl_fold();

int main(int argc, char **argv)
{
    std::cout << std::hex << test_shl_fold() << std::endl;
}
```

```x86asm
test_shl_fold PROC
	stc
	mov rcx, 1
	shl rcx, 4
	mov rax, rcx
	ret
test_shl_fold ENDP
```

Running the file gives the result:
```
PS D:\codes\ConsoleApplication2\x64\Debug> .\adder.exe
10
```
In Binary Ninja HLIL view, we see:
![image](https://user-images.githubusercontent.com/7302683/150709720-54a92456-16fe-448d-a397-9aa72cd84bd8.png)

NOTE: The constants are just an example, I would assume the issue persists no matter the constant of the operation.

**Expected Behavior:**
The result of `mov rcx, 0x1; shl rcx, 0x4` should be `0x10` not `0x1`.

**Comment by plafosse** [comment]
I think this is incorrect. 🤔  Using your recent PR it shows `return 1` but on current dev it shows `return 0x10`
