### ISSUE TITLE
can't change base of constants

### ISSUE THREAD

**Issue by crowell** [Vector35/binaryninja-api#287]
when i have a thing like `mov eax, 0x41` i want to be able to change the base of the 0x41 to base 10, or to char or other stuff. 

if it's possible to do, it isn't discoverable currently.

**Comment by psifertex** [comment]
Correct, not currently possible. We plan to fix that, but I don't remember offhand whether it's slated for v1 or has another big tracking it. I'll double check tomorrow.

**Comment by D0ntPanic** [comment]
Implemented in dev
