### ISSUE TITLE
Save/restore layout for panes with default layouts

### ISSUE THREAD

**Issue by D0ntPanic** [Vector35/binaryninja-api#2872]
Every binary that is opened defaults to a single pane. With the split pane support and syncing features, many users are going to want a setup that involves multiple panes, possibly spanning multiple monitors. The save/restore layout feature that already exists is not pane aware and will not restore your pane layouts.

The save/restore layout feature should be extended to also save and restore the pane layout. There should also be a feature to save the current pane layout as the default layout so that it is used whenever a new binary is opened. This will greatly improve workflow when opening a binary, as currently you have to set up your preferred pane layout every time.

**Comment by kciredor** [comment]
Would be extra nice if this can be managed through settings, which persist to settings.json and can be moved around between instances.

Perhaps a couple of starting points like "Initial setup: 2-way horizontal split, left=graph asm, right=linear hlil".

**Comment by psifertex** [comment]
It's much morel likely if we implemented it that way that we would let you specify the name of a saved layout in the setting. Much easier than trying to specify some custom config.

**Comment by psifertex** [comment]
Resolved by @jonpalmisc in builds >= 3410
