### ISSUE TITLE
Closing the search results window while a search is in progress causes a crash

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/binaryninja-api#2873]
Steps to repro:

1. Start a search (preferably something that will take some time)
2. Close the search results window. (pane?)
3. Enjoy the segfault

**Comment by CouleeApps** [comment]
This happens because closing the search window doesn't actually cancel the search, but it does delete the widget. So the incoming search results all start going to a nullptr...

**Comment by CouleeApps** [comment]
This will be fixed in 3.0.3220
