### ISSUE TITLE
typelibs: _Unwind_Resume should be __noreturn

### ISSUE THREAD

**Issue by fabianfreyer** [Vector35/binaryninja-api#2876]
**Version and Platform (required):**
- Binary Ninja Version: Version 3.0.3219-dev (2022-01-26 00:56:21)
- OS: MacOS
- OS Version: 11

**Bug Description:**
The automatically detected type for the `_Unwind_Resume` function is not marked `__noreturn`.

**Steps To Reproduce:**
1. Open a C++ binary doing any exception handling.
The following C++ code produces a binary that has this:
```cpp
#include <iostream>

using namespace std;

void __attribute__ ((noinline)) inner() {
    cout << "throwing exception" << endl;
    throw new exception();
}

void __attribute__ ((noinline)) outer() {
    inner();
}

int main() {
    try {
        outer();
    }
    catch (...) {
        cout << "exception caught" << endl;
    }
}
```
2. Find `_Unwind_Resume` in the imports.
3. Observe that it is not marked `__noreturn`

**Expected Behavior:**
`_Unwind_Resume` should be marked `__noreturn`.

**Screenshots:**
![image](https://user-images.githubusercontent.com/3423837/151093902-e303164f-cb27-4829-86af-7bffe01fa513.png)

**Additional Information:**
* https://reviews.llvm.org/rGe0751234ef0df733032b777ed0d993a490121855
* [AMD64 ABI](https://www.uclibc.org/docs/psABI-x86_64.pdf) section 6.2.6, p98 (99 in the PDF), under "Transferring Control to a Landing Pad":
    > `_Unwind_Resume` will never return.

**Comment by fabianfreyer** [comment]
Ah, but that's not a real return! That's a "set return address, and use that to jump". `uw_install_context_1` returns `0`.

**Comment by lwerdna** [comment]
attached binary to reproduce issue

[repros.zip](https://github.com/Vector35/binaryninja-api/files/9355572/repros.zip)

**Comment by lwerdna** [comment]
Please wait a couple hours for a build to be pushed and then it should be available on dev update channel. It appears resolved in the repro binary, but let me know if it's not fully resolved on your end.

![unwind-resume](https://user-images.githubusercontent.com/474191/185020862-ca720a84-bc23-4b52-b5d4-fd7806a7d800.png)
