### ISSUE TITLE
Add the ability to move sidebar right

### ISSUE THREAD

**Issue by grokeus** [Vector35/binaryninja-api#2878]
**What is the feature you'd like to have?**
Now sidebar is always located at left part of the window. I think that ability to move it to the right part will be helpfull. 
Usually when we dealing with disassembly/LLIL/MLIL/HLIL view we have a lot of free space at the right part of the screen, which is often stay unused (well, for me, at least). 
![unused_space](https://user-images.githubusercontent.com/20337200/151114447-3f0f9b1a-11e9-47b1-a877-5fb2f387be6d.png)

Visual Code for example have this feature:
![изображение](https://user-images.githubusercontent.com/20337200/151114867-0dcc66c1-5ae6-472f-acf4-3615cd20a135.png)

Or maybe I just didn't noticed some existing setting for this in BN?

**Is your feature request related to a problem?**
No

**Comment by plafosse** [comment]
Closing this issue as its in the product and we have this issue still open which will be closed when the documentation is finished. https://github.com/orgs/Vector35/projects/15/views/18?pane=issue&itemId=49575628
