### ISSUE TITLE
qt.conf is questionably mode 600

### ISSUE THREAD

**Issue by justinsteven** [Vector35/binaryninja-api#288]
`qt.conf` is mode 600. Dropping the project in /opt and `chown`ing it to root makes it unable to be launched until the permissions on `qt.conf` are relaxed.

```
a09a6523feac% /opt/binaryninja/binaryninja 
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Reinstalling the application may fix this problem.
zsh: abort      /opt/binaryninja/binaryninja

a09a6523feac% ls -la /opt/binaryninja/qt.conf 
-rw------- 1 root root 21 May 17 14:15 /opt/binaryninja/qt.conf

a09a6523feac% sudo chmod 644 /opt/binaryninja/qt.conf 

a09a6523feac% /opt/binaryninja/binaryninja 
xkbcommon: ERROR: failed to add default include path /usr/share/X11/xkb
Qt: Failed to create XKB context!
Use QT_XKB_CONFIG_ROOT environmental variable to provide an additional search path, add ':' as separator to provide several search paths and/
or make sure that XKB configuration data directory contains recent enough contents, to update please see http://cgit.freedesktop.org/xkeyboard-config/ .

```

And then it launches fine.

(I'm running it in Docker if that explains the remaining errors that don't seem to be hurting anything)

Not sure how you plan to package it for release, but not being able to read `qt.conf` prevented me from launching the application.

**Comment by psifertex** [comment]
Fixed in dev. File is now `0644`. Note that I'm not sure the eventual plan for a linux installer many not necessarily install as root anyway, but it's easy enough to fix and no real harm in it.
