### ISSUE TITLE
Add Support for Segment Granular Rebasing Respecting Common Image Base

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#2882]
Repro steps
1. `echo -en "\x00\x00\x00\x00" > test.bin`
2. open test.bin
3. in the console type `bv.add_user_segment(0, 1, 0, 1, 5)`
4. Internal to BN  `Segment::Serialize` gets the wrong value for the `segment.m_start` after call to `NormalizeAddress`

This problem appears to be a serialization problem not a deserialization problem.

**Comment by bpotchik** [comment]
Currently there is a limitation that the first segment of a BinaryView must be an auto segment. Adding a user segment at or before the first auto segment is not supported. The issue reported above is a failure due to this limitation.

**Comment by fabianfreyer** [comment]
I think this is a duplicate of #2881, will close that in favor of this one.

**Comment by bpotchik** [comment]
Previously, normalized offsets were based on bv.start. Now normalized offsets are based on bv.image_base. This allows us to support adding 'user' segments and/or memory regions before the image base. Now, rebasing and save/load operations preserve the memory map correctly.

Fixed in 4.2.5758.
