### ISSUE TITLE
Screenshots in user docs need updating

### ISSUE THREAD

**Issue by galenbwill** [Vector35/binaryninja-api#2884]
The images in this list need updating because they are wrong. However, all images probably need to be recaptured to reflect the current 3.0 version.

- [x] https://github.com/Vector35/binaryninja-api/blob/dev/docs/img/status-bar.png
  - this image needs updating to reflect new status bar
- [x] https://github.com/Vector35/binaryninja-api/blob/dev/docs/img/view-choices.png
  - this image needs updating to show view chooser in the pane header
- [x] https://github.com/Vector35/binaryninja-api/blob/dev/docs/img/keybindings.png
  - this image has a weird hamburger icon on the bottom left, and doesn't show a sidebar, or any of the coloring to reflect modified keybindings
- [x] https://github.com/Vector35/binaryninja-api/blob/dev/docs/img/graphview.png
  - this image needs updating to reflect graph view signature header, at least
- [x] https://github.com/Vector35/binaryninja-api/blob/dev/docs/img/options.png
  - this image needs updating to reflect it's coming from the hamburger button
- [x] https://github.com/Vector35/binaryninja-api/blob/dev/docs/img/cross-reference-tree.png
  - this image needs updating to show the cross references pane **tree view** in the sidebar (would also be nice to select a reference that actually shows off that it's a tree view, and make sure the reference shows arrows going in both directions)
- [x] https://github.com/Vector35/binaryninja-api/blob/dev/docs/img/cross-reference-table.png
  - this image needs updating to show the cross references pane **table view** in the sidebar
- [x] https://github.com/Vector35/binaryninja-api/blob/dev/docs/img/functionlist.png
  - this image needs to be replaced to show the Symbols pane instead of the defunct "Functions List"
- [x] https://github.com/Vector35/binaryninja-api/blob/dev/docs/img/pseudo-c.png [does not exist yet]
  - need a new image showing HLIL and Pseudo C side by side (I'll leave a placeholder in the [`docs/getting-started.md`](https://github.com/Vector35/binaryninja-api/blob/dev/docs/getting-started.md#pseudo-c)
- [x] https://github.com/Vector35/binaryninja-api/blob/dev/docs/img/tiling-panes.png [does not exist yet]
  - need a new image showing tiling view panes with most of the following, with their views synced:
    - Hex view
    - Disassembly view
    - LLIL view
    - MLIL view
    - HLIL view
    - Pseudo-C view
    - Pinned cross references
    - and make sure the feature map is visible!
- [x] https://github.com/Vector35/binaryninja-api/blob/dev/docs/img/sidebar.png [does not exist yet]
  - need a new image showing off the sidebar
- [x] https://github.com/Vector35/binaryninja-api/blob/dev/docs/img/hex.png
  - need a new image showing the current status bar (including the lock button and excluding the menus) and the pane header with the view menus and buttons
 - [x] https://github.com/Vector35/binaryninja-api/blob/dev/docs/img/console-split-and-tabbed.png [does not exist yet]
  - need a new image showing the Log and Script console views in both split and tabbed arrangements

**Comment by psifertex** [comment]
updated the ones I checked and added `pseudoc.png` from the blog.

I'm not totally sure about having a single image showing all panes sync'ed, not sure that's necessary?
