### ISSUE TITLE
Graph View Reverts to Linear View

### ISSUE THREAD

**Issue by iamausertoo** [Vector35/binaryninja-api#2888]
**Version and Platform (required):**
- Binary Ninja Version: 3.0
- OS: macOS

**Bug Description:**
When skimming a binary using the feature map, the graph view changes to linear view, probably because the address isn't contained in a function? Seems like it should just show a blank view. This is especially the case when graph view is a secondary split view. I want linear and graph side-by-side and then skim using the feature map. Can't do it because graph view keeps changing to linear and I end up with two linear views.

**Steps to Repro:**
If you toggle graph/linear view using the spacebar then the view will stay on the selected view.  However, if you select disassembly graph from the drop-down menus instead, then the above behavior can be observed.

**Comment by bpotchik** [comment]
Fixed in `3.0.3234-dev`.
