### ISSUE TITLE
SIGSEGV when analysing bash (+interaction)

### ISSUE THREAD

**Issue by cornejo** [Vector35/binaryninja-api#289]
I've got a repeatable crash when analysing /bin/bash and interacting with the UI.

Steps to reproduce:
- Load bash
- While it's analysing double click on the first function call (sub_41db90)
- Then double click on the jump to main (__libc_start_main@PLT)
- Type 'c's (I do 5) to overwrite data in the region. I've tried with other characters ('a') and it also seems to crash.
- Wait for crash

sha1sum bash 
a6cabb20a54bba91d925d8d97d079ffc6437c6d8  bash

gdb -args ./binaryninja 
GNU gdb (Ubuntu 7.11-0ubuntu1) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./binaryninja...(no debugging symbols found)...done.
(gdb) run
Starting program: /home/ejcorne/Downloads/binaryninja/binaryninja/binaryninja 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe82e2700 (LWP 13199)]
[New Thread 0x7fffdd951700 (LWP 13200)]
[New Thread 0x7fffdd150700 (LWP 13201)]
[New Thread 0x7fffd7822700 (LWP 13205)]
[New Thread 0x7fffd7021700 (LWP 13206)]
[New Thread 0x7fffd6820700 (LWP 13207)]
[New Thread 0x7fffd601f700 (LWP 13208)]
[New Thread 0x7fffd581e700 (LWP 13209)]
[New Thread 0x7fffd501d700 (LWP 13210)]
[New Thread 0x7fffd481c700 (LWP 13211)]
Data flow for function at 0x47f8e0 did not terminate
Data flow for function at 0x47f7f0 did not terminate
Data flow for function at 0x47f430 did not terminate
Data flow for function at 0x48e320 did not terminate

Thread 6 "binaryninja" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd7021700 (LWP 13206)]
0x00007ffff79f194d in ?? () from /home/ejcorne/Downloads/binaryninja/binaryninja/libbinaryninjacore.so.1
(gdb) bt
#0  0x00007ffff79f194d in ?? () from /home/ejcorne/Downloads/binaryninja/binaryninja/libbinaryninjacore.so.1
#1  0x00007ffff79f234d in ?? () from /home/ejcorne/Downloads/binaryninja/binaryninja/libbinaryninjacore.so.1
#2  0x00007ffff7a0e3cc in ?? () from /home/ejcorne/Downloads/binaryninja/binaryninja/libbinaryninjacore.so.1
#3  0x00007ffff7a139c6 in ?? () from /home/ejcorne/Downloads/binaryninja/binaryninja/libbinaryninjacore.so.1
#4  0x00007ffff79e3fb4 in ?? () from /home/ejcorne/Downloads/binaryninja/binaryninja/libbinaryninjacore.so.1
#5  0x00007ffff5bdec70 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff4db96fa in start_thread (arg=0x7fffd7021700) at pthread_create.c:333
#7  0x00007ffff5344b5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) info shared
From                To                  Syms Read   Shared Object Library
0x00007ffff7dd7ac0  0x00007ffff7df5640  Yes         /lib64/ld-linux-x86-64.so.2
0x00007ffff79a7740  0x00007ffff7b59acf  Yes (*)     /home/ejcorne/Downloads/binaryninja/binaryninja/libbinaryninjacore.so.1
0x00007ffff725c5b0  0x00007ffff75ebee0  Yes (*)     /home/ejcorne/Downloads/binaryninja/binaryninja/libQt5Widgets.so.5
0x00007ffff69e7600  0x00007ffff6e068bc  Yes (*)     /home/ejcorne/Downloads/binaryninja/binaryninja/libQt5Gui.so.5
0x00007ffff65ef350  0x00007ffff66cb954  Yes (*)     /home/ejcorne/Downloads/binaryninja/binaryninja/libQt5Network.so.5
0x00007ffff5f23f20  0x00007ffff61f3a38  Yes (*)     /home/ejcorne/Downloads/binaryninja/binaryninja/libQt5Core.so.5
0x00007ffff5bafd20  0x00007ffff5c5bcb9  Yes (*)     /usr/lib/x86_64-linux-gnu/libstdc++.so.6
0x00007ffff5822600  0x00007ffff5893d0a  Yes         /lib/x86_64-linux-gnu/libm.so.6
0x00007ffff5609a70  0x00007ffff56198b5  Yes (*)     /lib/x86_64-linux-gnu/libgcc_s.so.1
0x00007ffff525d8b0  0x00007ffff53b0334  Yes         /lib/x86_64-linux-gnu/libc.so.6
0x00007ffff4fd8e70  0x00007ffff5023b13  Yes (*)     /usr/lib/x86_64-linux-gnu/libcurl.so.4
0x00007ffff4db7a70  0x00007ffff4dc4ab1  Yes         /lib/x86_64-linux-gnu/libpthread.so.0
0x00007ffff4b69f00  0x00007ffff4b9a8f6  Yes (*)     /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
0x00007ffff495d680  0x00007ffff495d7fa  Yes (*)     /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0
0x00007ffff4757100  0x00007ffff475a1df  Yes         /lib/x86_64-linux-gnu/librt.so.1
0x00007ffff445e7f0  0x00007ffff44d5789  Yes (*)     /lib/x86_64-linux-gnu/libglib-2.0.so.0
0x00007ffff4235590  0x00007ffff423f39f  Yes (*)     /usr/lib/x86_64-linux-gnu/libXext.so.6
0x00007ffff3f10870  0x00007ffff3f982e4  Yes (*)     /usr/lib/x86_64-linux-gnu/libX11.so.6
0x00007ffff3c95770  0x00007ffff3c9999b  Yes (*)     /usr/lib/nvidia-361/libGL.so.1
0x00007ffff3a50df0  0x00007ffff3a61870  Yes (*)     /lib/x86_64-linux-gnu/libz.so.1
0x00007ffff3674a50  0x00007ffff37c82a8  Yes (*)     /home/ejcorne/Downloads/binaryninja/binaryninja/libicui18n.so.56
0x00007ffff32555b0  0x00007ffff332e114  Yes (*)     /home/ejcorne/Downloads/binaryninja/binaryninja/libicuuc.so.56
                                        Yes (*)     /home/ejcorne/Downloads/binaryninja/binaryninja/libicudata.so.56
0x00007ffff1616da0  0x00007ffff161798e  Yes         /lib/x86_64-linux-gnu/libdl.so.2
0x00007ffff13e5b70  0x00007ffff13ea246  Yes (*)     /usr/lib/x86_64-linux-gnu/libidn.so.11
0x00007ffff11cba80  0x00007ffff11da9c3  Yes (*)     /usr/lib/x86_64-linux-gnu/librtmp.so.1
0x00007ffff0f73fc0  0x00007ffff0faccf8  Yes (*)     /lib/x86_64-linux-gnu/libssl.so.1.0.0
0x00007ffff0b67f00  0x00007ffff0c9ce1f  Yes (*)     /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
0x00007ffff08c4470  0x00007ffff08f3889  Yes (*)     /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2
0x00007ffff06ac9e0  0x00007ffff06b3caa  Yes (*)     /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2
0x00007ffff04657f0  0x00007ffff0496d62  Yes (*)     /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2
0x00007ffff02527f0  0x00007ffff025709c  Yes (*)     /usr/lib/x86_64-linux-gnu/libffi.so.6
0x00007fffeffe2530  0x00007ffff0031623  Yes (*)     /lib/x86_64-linux-gnu/libpcre.so.3
0x00007fffefdc86b0  0x00007fffefdd71a5  Yes (*)     /usr/lib/x86_64-linux-gnu/libxcb.so.1
0x00007fffefb909f0  0x00007fffefb9b652  Yes (*)     /usr/lib/nvidia-361/libGLX.so.0
0x00007fffef8d0c20  0x00007fffef8f1f51  Yes (*)     /usr/lib/nvidia-361/libGLdispatch.so.0
0x00007fffef5992c0  0x00007fffef663b94  Yes (*)     /usr/lib/x86_64-linux-gnu/libgnutls.so.30
0x00007fffef347590  0x00007fffef354e1f  Yes (*)     /usr/lib/x86_64-linux-gnu/libhogweed.so.4
0x00007fffef112e60  0x00007fffef12f59f  Yes (*)     /usr/lib/x86_64-linux-gnu/libnettle.so.6
0x00007fffeee943c0  0x00007fffeeef2668  Yes (*)     /usr/lib/x86_64-linux-gnu/libgmp.so.10
0x00007fffeebd9b10  0x00007fffeec32d57  Yes (*)     /usr/lib/x86_64-linux-gnu/libkrb5.so.3
0x00007fffee98df90  0x00007fffee9a8eae  Yes (*)     /usr/lib/x86_64-linux-gnu/libk5crypto.so.3
0x00007fffee787440  0x00007fffee788003  Yes (*)     /lib/x86_64-linux-gnu/libcom_err.so.2
0x00007fffee57d6d0  0x00007fffee5827cb  Yes (*)     /usr/lib/x86_64-linux-gnu/libkrb5support.so.0
0x00007fffee363990  0x00007fffee373398  Yes         /lib/x86_64-linux-gnu/libresolv.so.2
0x00007fffee147940  0x00007fffee1586f3  Yes (*)     /usr/lib/x86_64-linux-gnu/libsasl2.so.2
0x00007fffedf119a0  0x00007fffedf369e8  Yes (*)     /usr/lib/x86_64-linux-gnu/libgssapi.so.3
0x00007fffedd00e50  0x00007fffedd01acc  Yes (*)     /usr/lib/x86_64-linux-gnu/libXau.so.6
0x00007fffedafb1d0  0x00007fffedafcb38  Yes (*)     /usr/lib/x86_64-linux-gnu/libXdmcp.so.6
0x00007fffed8a6470  0x00007fffed8d4dd7  Yes (*)     /usr/lib/x86_64-linux-gnu/libp11-kit.so.0
0x00007fffed6849e0  0x00007fffed68fd1b  Yes (*)     /usr/lib/x86_64-linux-gnu/libtasn1.so.6
0x00007fffed47f2c0  0x00007fffed47fee4  Yes (*)     /lib/x86_64-linux-gnu/libkeyutils.so.1
0x00007fffed277a70  0x00007fffed27abdc  Yes (*)     /usr/lib/x86_64-linux-gnu/libheimntlm.so.0
0x00007fffed007280  0x00007fffed04fb02  Yes (*)     /usr/lib/x86_64-linux-gnu/libkrb5.so.26
0x00007fffecd62a00  0x00007fffecdca65c  Yes (*)     /usr/lib/x86_64-linux-gnu/libasn1.so.8
0x00007fffecb1c770  0x00007fffecb38fae  Yes (*)     /usr/lib/x86_64-linux-gnu/libhcrypto.so.4
0x00007fffec904ed0  0x00007fffec9105b9  Yes (*)     /usr/lib/x86_64-linux-gnu/libroken.so.18
0x00007fffec6d7ea0  0x00007fffec6d9792  Yes (*)     /usr/lib/x86_64-linux-gnu/libwind.so.0
---Type <return> to continue, or q <return> to quit---
0x00007fffec4ca8c0  0x00007fffec4d1ff4  Yes (*)     /usr/lib/x86_64-linux-gnu/libheimbase.so.1
0x00007fffec28e020  0x00007fffec2b3a6c  Yes (*)     /usr/lib/x86_64-linux-gnu/libhx509.so.5
0x00007fffebfb3040  0x00007fffec053990  Yes (*)     /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
0x00007fffebd70b40  0x00007fffebd767e7  Yes         /lib/x86_64-linux-gnu/libcrypt.so.1
0x00007fffeb147220  0x00007fffeb14761c  Yes (*)     /home/ejcorne/Downloads/binaryninja/binaryninja/qt/platforms/libqxcb.so
0x00007fffeaf09d10  0x00007fffeaf28d5a  Yes (*)     /usr/lib/x86_64-linux-gnu/libfontconfig.so.1
0x00007fffeac66c60  0x00007fffeacd6212  Yes (*)     /usr/lib/x86_64-linux-gnu/libfreetype.so.6
0x00007fffea9ef680  0x00007fffeaa40474  Yes (*)     /home/ejcorne/Downloads/binaryninja/binaryninja/qt/platforms/../../libQt5DBus.so.5
0x00007fffea7d1ad0  0x00007fffea7d79e5  Yes (*)     /usr/lib/x86_64-linux-gnu/libXrender.so.1
0x00007fffea5cd6d0  0x00007fffea5cea04  Yes (*)     /usr/lib/nvidia-361/libEGL.so.1
0x00007fffea2bb9d0  0x00007fffea36b218  Yes (*)     /home/ejcorne/Downloads/binaryninja/binaryninja/qt/platforms/../../libQt5XcbQpa.so.5
0x00007fffea04eb40  0x00007fffea066c19  Yes (*)     /lib/x86_64-linux-gnu/libexpat.so.1
0x00007fffe9e29a70  0x00007fffe9e42373  Yes (*)     /lib/x86_64-linux-gnu/libpng12.so.0
0x00007fffe9be4460  0x00007fffe9c0f1e4  Yes (*)     /lib/x86_64-linux-gnu/libdbus-1.so.3
0x00007fffe99d85e0  0x00007fffe99d86fb  Yes (*)     /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1
0x00007fffe97ca1a0  0x00007fffe97d46f7  Yes (*)     /usr/lib/x86_64-linux-gnu/libXi.so.6
0x00007fffe95c1bc0  0x00007fffe95c5ade  Yes (*)     /usr/lib/x86_64-linux-gnu/libSM.so.6
0x00007fffe93aa6b0  0x00007fffe93b771a  Yes (*)     /usr/lib/x86_64-linux-gnu/libICE.so.6
0x00007ffff7f41810  0x00007ffff7f98b4f  Yes (*)     /lib/x86_64-linux-gnu/libsystemd.so.0
0x00007fffe91a2510  0x00007fffe91a3bb1  Yes (*)     /lib/x86_64-linux-gnu/libuuid.so.1
0x00007fffe8f84ab0  0x00007fffe8f9729b  Yes (*)     /lib/x86_64-linux-gnu/libselinux.so.1
0x00007fffe8d5f0d0  0x00007fffe8d7324d  Yes (*)     /lib/x86_64-linux-gnu/liblzma.so.5
0x00007fffe8a84d00  0x00007fffe8b25648  Yes (*)     /lib/x86_64-linux-gnu/libgcrypt.so.20
0x00007fffe886a8d0  0x00007fffe8873db9  Yes (*)     /lib/x86_64-linux-gnu/libgpg-error.so.0
0x00007fffe858c520  0x00007fffe8615318  Yes (*)     /usr/lib/nvidia-361/libEGL_nvidia.so.0
0x00007fffe82e62f0  0x00007fffe834c7b8  Yes (*)     /usr/lib/nvidia-361/libnvidia-glsi.so.361.42
0x00007fffe78da420  0x00007fffe78dee20  Yes (*)     /usr/lib/x86_64-linux-gnu/libXcursor.so.1
0x00007fffe76d3530  0x00007fffe76d5756  Yes (*)     /usr/lib/x86_64-linux-gnu/libXfixes.so.3
0x00007fffe70f0f80  0x00007fffe7349fae  Yes (*)     /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
0x00007fffe6def950  0x00007fffe6e4671b  Yes (*)     /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
0x00007fffe6bcf170  0x00007fffe6bd0075  Yes (*)     /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0
0x00007fffe69c5980  0x00007fffe69ca746  Yes (*)     /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0
0x00007fffe67a6780  0x00007fffe67b2bc3  Yes (*)     /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0
0x00007fffe6499c40  0x00007fffe655b897  Yes (*)     /usr/lib/x86_64-linux-gnu/libcairo.so.2
0x00007fffe626c0b0  0x00007fffe627ea29  Yes (*)     /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0
0x00007fffe5f13880  0x00007fffe5fe6d9b  Yes (*)     /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
0x00007fffe5ccf1f0  0x00007fffe5cd787d  Yes (*)     /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0
0x00007fffe5a88ff0  0x00007fffe5aa8396  Yes (*)     /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0
0x00007fffe5879af0  0x00007fffe587a3ec  Yes (*)     /usr/lib/x86_64-linux-gnu/libXinerama.so.1
0x00007fffe566fc70  0x00007fffe5675a82  Yes (*)     /usr/lib/x86_64-linux-gnu/libXrandr.so.2
0x00007fffe546bc40  0x00007fffe546c618  Yes (*)     /usr/lib/x86_64-linux-gnu/libXcomposite.so.1
0x00007fffe5268b90  0x00007fffe526949b  Yes (*)     /usr/lib/x86_64-linux-gnu/libXdamage.so.1
0x00007fffe4fc9be0  0x00007fffe504eb30  Yes (*)     /usr/lib/x86_64-linux-gnu/libpixman-1.so.0
0x00007fffe4dbcdb0  0x00007fffe4dbd8c3  Yes (*)     /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0
0x00007fffe4bb5460  0x00007fffe4bb88da  Yes (*)     /usr/lib/x86_64-linux-gnu/libxcb-render.so.0
0x00007fffe495a6a0  0x00007fffe4995639  Yes (*)     /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0
0x00007fffe474cb90  0x00007fffe4750455  Yes (*)     /usr/lib/x86_64-linux-gnu/libthai.so.0
0x00007fffe45284b0  0x00007fffe4543765  Yes (*)     /usr/lib/x86_64-linux-gnu/libgraphite2.so.3
0x00007fffe431f130  0x00007fffe43225bd  Yes (*)     /usr/lib/x86_64-linux-gnu/libdatrie.so.1
0x00007fffe40f2710  0x00007fffe41171f4  Yes (*)     /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/engines/libmurrine.so
0x00007fffdfdf74e0  0x00007fffdfdfc71d  Yes (*)     /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/engines/libpixmap.so
0x00007fffdfb72da0  0x00007fffdfba6b2f  Yes (*)     /home/ejcorne/Downloads/binaryninja/binaryninja/plugins/libplatform_windows.so
0x00007fffdf8d3230  0x00007fffdf919cef  Yes (*)     /home/ejcorne/Downloads/binaryninja/binaryninja/plugins/libarch_armv7.so
0x00007fffdf62db50  0x00007fffdf66f74f  Yes (*)     /home/ejcorne/Downloads/binaryninja/binaryninja/plugins/libarch_x86.so
0x00007fffdf379460  0x00007fffdf3c943f  Yes (*)     /home/ejcorne/Downloads/binaryninja/binaryninja/plugins/libarch_powerpc.so
0x00007fffdf0f0da0  0x00007fffdf124b5f  Yes (*)     /home/ejcorne/Downloads/binaryninja/binaryninja/plugins/libplatform_freebsd.so
0x00007fffdee69e70  0x00007fffdee9e51f  Yes (*)     /home/ejcorne/Downloads/binaryninja/binaryninja/plugins/libplatform_linux.so
0x00007fffdec2e1d0  0x00007fffdec2f125  Yes (*)     /home/ejcorne/Downloads/binaryninja/binaryninja/plugins/libpythonplugin.so
0x00007fffdea222b0  0x00007fffdea28616  Yes (*)     /home/ejcorne/Downloads/binaryninja/binaryninja/plugins/libcryptoplugin.so
---Type <return> to continue, or q <return> to quit---
0x00007fffde7c6520  0x00007fffde7fd20f  Yes (*)     /home/ejcorne/Downloads/binaryninja/binaryninja/plugins/libarch_mips.so
0x00007fffde51d590  0x00007fffde5642ef  Yes (*)     /home/ejcorne/Downloads/binaryninja/binaryninja/plugins/libarch_arm64.so
0x00007fffde28bd40  0x00007fffde2bfaef  Yes (*)     /home/ejcorne/Downloads/binaryninja/binaryninja/plugins/libplatform_mac.so
0x00007fffddd15540  0x00007fffddeb6750  Yes (*)     /usr/lib/x86_64-linux-gnu/libpython2.7.so.1
0x00007fffddac3e60  0x00007fffddac4705  Yes         /lib/x86_64-linux-gnu/libutil.so.1
0x00007fffdc6682d0  0x00007fffdc66dbf1  Yes         /lib/x86_64-linux-gnu/libnss_compat.so.2
0x00007fffdc451ff0  0x00007fffdc45f1e1  Yes         /lib/x86_64-linux-gnu/libnsl.so.1
0x00007fffdc2440b0  0x00007fffdc24a8ce  Yes         /lib/x86_64-linux-gnu/libnss_nis.so.2
0x00007fffdc0321b0  0x00007fffdc0382a1  Yes         /lib/x86_64-linux-gnu/libnss_files.so.2
(*): Shared library is missing debugging information.
(gdb) info registers
rax            0xc16bc0	12676032
rbx            0x0	0
rcx            0x3396	13206
rdx            0x0	0
rsi            0x0	0
rdi            0x7fffcc94a2c0	140736625681088
rbp            0x7fffd7020d80	0x7fffd7020d80
rsp            0x7fffd7020bc0	0x7fffd7020bc0
r8             0x7fffcc94a2d8	140736625681112
r9             0x0	0
r10            0x1	1
r11            0x6f3df0	7290352
r12            0x7fffcc94a2c0	140736625681088
r13            0x7fffd7020e50	140736800624208
r14            0x7fffd70219c0	140736800627136
r15            0xdd6e50	14511696
rip            0x7ffff79f194d	0x7ffff79f194d
eflags         0x10206	[ PF IF RF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0
(gdb)

**Comment by psifertex** [comment]
Sorry for missing this before, this was a race condition that's been fixed for some time now. Thanks for the report.
