### ISSUE TITLE
Reduced memory utilization

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#2893]
Binary Ninja can be over eager consuming memory. There are a number of things we can do to improve the situation.

**Comment by Ethan-ks** [comment]
This is a great goal to work towards, and I wanted to add a bit of detail for situations I've found where this has been a problem. On large binaries (embedded firmware/RTOS images), particularly those with a very large number of functions, memory usage quickly grows as analysis continues and more functions are defined and analyzed.

For example, I was working on analyzing a large hypervisor RTOS firmware binary, which included over 500,000 functions. Even with auto-linear sweep and signature matching disabled, and analysis set to controlFlow only, memory usage will continue to grow as new functions are defined (and analysis cascades down called functions etc.) until eventually Binary Ninja is OOM killed by the kernel after consuming ~20GB of memory.

**Comment by fuzyll** [comment]
This has been improved considerably, see the blog post for more information: https://binary.ninja/2022/03/24/memory-usage-and-performance-optimizations.html.

There's always more to be done, but we're currently pretty happy with the improvements that have been made.
