### ISSUE TITLE
Split Views Revert to Linear View when Renaming Tags

### ISSUE THREAD

**Issue by iamausertoo** [Vector35/binaryninja-api#2897]
**Version and Platform (required):**
- Binary Ninja Version: 3.0
- OS: macOS

**Bug Description:**
Views revert to Linear view when tags are edited.

**Steps To Reproduce:**
1. Create a couple of split views.
2. Change to something other than Linear/Graph
3. Edit tag text
4. Some of the views change to Linear

**Expected Behavior:**
Views should not change when editing tags.

**Comment by bpotchik** [comment]
So assuming you're editing the tag name from the side bar. If you use 'enter' to accept the new name, it's causing a navigation event, which navigates the currently focused pane to the tag, potentially taking you away from Strings view for example.

Fixed in `3.0.3238-dev`.
