### ISSUE TITLE
support for dyld shared cache

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#290]
See: http://iphonedevwiki.net/index.php/Dyld_shared_cache for more info.

**Comment by cornejo** [comment]
If you need to get copies of a dyld_shared_cache_<arch> file then you can follow the steps here (http://newosxbook.com/articles/OTA.html) to extract one for yourself from one of the updates here (https://www.theiphonewiki.com/wiki/OTA_Updates)

Note that the files taken from actual phones are a) encrypted (I believe?) and b) have some form of ASLR pre-applied to them.

**Comment by psifertex** [comment]
Blocking on #133

**Comment by brinlyau** [comment]
Apple OSS'ed their latest version of dyld, plus you could probably look at how the Ghidra loader works. https://github.com/apple-oss-distributions/dyld

**Comment by psifertex** [comment]
Thanks -- we've got some other references for this too I thought I posted on this issue but it must have been a different one. I did at least tag this for 3.3 which is when we expect to be working on it again.

**Comment by cxnder** [comment]
https://github.com/cxnder/bn-dyldsharedcache

here you go

**Comment by 0cyn** [comment]
Resolved in **dev builds >= 4.2.6279**

We've shipped a preview 'alpha version' of our SharedCache processing plugin which you can start to work with now 🎉 

It currently has first class support for iOS 11-17, partial support for iOS 18 (missing objc selector optimizations)
It has partial support for macOS x86_64 and arm64e caches as well. 

It should be usable for RE in all cases. 

Support for other arches/formats, misc features, and bugs (which _will_ exist) will be tracked in separate issues, and we look forward to feedback as we continue working on this.

**Comment by psifertex** [comment]
For future reference, the current version is here: https://github.com/Vector35/binaryninja-api/tree/dev/view/sharedcache
