### ISSUE TITLE
BinaryView plugin does not set endianness

### ISSUE THREAD

**Issue by mblsha** [Vector35/binaryninja-api#2900]
**Version and Platform (required):**
- Binary Ninja Version: 3.0.3233
- OS: macOS
- OS Version: 11.6 (Build 20G165)

**Bug Description:**
Please provide a clear and concise description of what happened.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Install https://github.com/zznop/bn-genesis + https://github.com/wrigjl/binaryninja-m68k
2. Open a Sega Genesis ROM (or patch bn-genesis to open arbitrary binary file)
3. Open Python Console

```
>>> bv.arch
<arch: M68000>
>>> bv.endianness
<Endianness.LittleEndian: 0>
```

**Expected Behavior:**
Expect bv.endianness to match bv.arch.endianness:
```
>>> bv.arch.endianness
<Endianness.BigEndian: 1>
```

**Additional Information:**
Opening binaries without bn-genesis and selecting M68000 architecture directly sets bv.endianness to the correct value.

**Comment by psifertex** [comment]
This seems like it should be filed on https://github.com/zznop/bn-genesis no?

**Comment by mblsha** [comment]
But how a plugin author is supposed to fix this? I wasn't able to find other BinaryView plugins that use a BigEndian architecture.

This is all that plugin does to set the architecture:
https://github.com/zznop/bn-genesis/blob/master/genesis/loader.py#L14

And this issue could be similar to #645.

**Comment by psifertex** [comment]
By implementing this method:

https://api.binary.ninja/binaryninja.binaryview-module.html#binaryninja.binaryview.BinaryView.perform_get_default_endianness

**Comment by mblsha** [comment]
Thanks Jordan! This fixes the issue when I put it into my own plugin.
