### ISSUE TITLE
Headless install silent logic backwards?

### ISSUE THREAD

**Issue by rchildre3** [Vector35/binaryninja-api#2908]
**Version and Platform (required):**
- Binary Ninja Version: 3.0.3233 Headless
- OS: Ubuntu Linux
- OS Version: 18.04

**Bug Description:**
`linux-setup.sh` silent mode flag is set in the when `$USERINTERACTIVE` is set to true.  This seems backwards?

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. `download_headless.py`
2. unzip
3. `linux-setup.sh`

**Expected Behavior:**
Silent mode correctly exits when passed through to the python installer script

**Comment by psifertex** [comment]
Resolved in the next dev build or you can pull directly now.
