### ISSUE TITLE
Import From IDB

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#2918]
Add the ability to import IDA Databases into Binary Ninja

**Comment by psifertex** [comment]
Only a limited beta with some limitations -- reopening as this needs some more work.

**Comment by rbran** [comment]
The https://github.com/Vector35/binaryninja-api/pull/5884 implement a IDB/TIL data type parser.

**Comment by emesare** [comment]
Merged with https://github.com/Vector35/binaryninja-api/commit/fe0d4ae2c3baa26fca84a9a8cb9670955bdfea12, on dev with >4.2.6013-dev
