### ISSUE TITLE
binja crash

### ISSUE THREAD

**Issue by hanssl** [Vector35/binaryninja-api#2921]
Binary Ninja Version: 3.0.3233, e250d0a3
Platform: Ubuntu 20.04.3 LTS

This binary will crash all versions of binaryninja.  It gets to Analyze stage 3 and seg faults (about 10s).

Grab the Windows Vista (second option) version of wab32.dll from here: https://www.exefiles.com/en/dll/wab32-dll/

![Screenshot from 2022-02-02 13-08-49](https://user-images.githubusercontent.com/649957/152229619-d9fa12dd-a4a8-4afb-90a4-cfac4dd42961.png)

**Comment by plafosse** [comment]
Thank you for the report. We've been able to reproduce and root cause the issue.
