### ISSUE TITLE
SEH Prologue and Epilogue Functions

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#2922]
We need to gracefully handle the SEH prologue and epilogue with workflows. This is really critical to Windows support.

**Comment by ccarpenter04** [comment]
Has this been figured out or are you still looking into different solutions?

**Comment by D0ntPanic** [comment]
SEH prologue and epilogue functions are now inlined directly into the functions that call them. This fixes stack variable resolution for functions that use SEH.

Added in build 3949
