### ISSUE TITLE
Name demanging returns unexpected results

### ISSUE THREAD

**Issue by joehendrix** [Vector35/binaryninja-api#293]
I ran into a couple issues with the attached binary with respect to names.

The name demangling gives unexpected names (e.g., a function named “f” became “float”, and a function named “h” became “unsigned char”).

The function at address 0x400158 is named "sub_400158".  However, there is a symbol for _exit.

[hello_world_ubuntu_64_lts_12_04_diet.zip](https://github.com/Vector35/binaryninja-api/files/303448/hello_world_ubuntu_64_lts_12_04_diet.zip)

**Comment by psifertex** [comment]
This is a helpful test case, but we've already got #114 tracking a ground-up name demangler we've been working on so I'm going to close this one. Thanks for the report.
