### ISSUE TITLE
Broken shadow painting behind command palette affects linear view header box

### ISSUE THREAD

**Issue by galenbwill** [Vector35/binaryninja-api#2933]
**Version and Platform (required):**
- Binary Ninja Version: since forever, according to rusty
- OS: macOS
- OS Version: `¯\_(ツ)_/¯`

**Bug Description:**

**Steps To Reproduce:**

1. scroll to the top of the binary so the Linear View header is visible
2. open the command palette, observe black bars:
![image](https://user-images.githubusercontent.com/12259536/152620129-934d08b5-da61-4438-b274-cc045ea581f8.png)
3. close the command palette, observe black bars are still there:
![image](https://user-images.githubusercontent.com/12259536/152620142-d97af4b4-7dba-4f14-9ccd-d9bc514a4ad4.png)
4. click in the offending space in the header, observe the header gets repainted (scrolling also works):
![image](https://user-images.githubusercontent.com/12259536/152620159-b51ba063-c385-43d2-9679-2ff93dc008d6.png)

**Additional Information:**
Note that it happens upon both opening and closing the palette -- scrolling while the palette is open will clear the bars, but closing the palette will make them appear again.

**Comment by op2786** [comment]
I guess this also is related. Notice the shadow in feature map.

![shadow](https://user-images.githubusercontent.com/109607896/182800005-2a07a098-8cb6-4c43-b73c-d4e967d1eeb4.PNG)

**Comment by CouleeApps** [comment]
This was happening because it drew the rect in the repainted region, which was just the region covered by command palette (and its shadow), so the painting assumed that the rect only extended that far. Fixed as of 3.2.3799.
