### ISSUE TITLE
"Reset all user settings" should have a confirmation dialog

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#2936]
**What is the feature you'd like to have?**
Resetting all settings is a potentially hazardous action, and should have a confirmation prompt. With how easy it is to right click and release (which activates the selected item), you can lose all of your configuration in potentially one click.

**Is your feature request related to a problem?**
It should not be this easy to lose data / configurations.

**Are any alternative solutions acceptable?**
Not that I can think of.

**Comment by cxnder** [comment]
This was resolved in builds >=3.0.3360 (almost 4 months ago, woops)
