### ISSUE TITLE
License file and update dir doesn't follow env variables

### ISSUE THREAD

**Issue by BonusPlay** [Vector35/binaryninja-api#2938]
Setting `BN_USER_DIRECTORY` does work, but binja still looks for license file in `~/.binaryninja/license.dat` instead of `$BN_USER_DIRECTORY/license.dat`. This can be worked arouns by providing license file contents in `BN_LICENSE` env var. However, binja still creates `~/.binaryninja/update/<sha256>/manifest` disregarding `BN_USER_DIRECTORY`.

Binary Ninja Version: 3.0.3233 Personal, e250d0a3
Platform: Arch Linux

**Comment by psifertex** [comment]
Thanks for the report -- working on these now, agree those should follow the environment variable convention.

**Comment by psifertex** [comment]
Fixed in builds >= 3300
