### ISSUE TITLE
Problem when hovering over call

### ISSUE THREAD

**Issue by AV-IO** [Vector35/binaryninja-api#294]
When hovering over a call the preview shown does not stretch to show the full width of the layout. This is not an issue by itself, however to scroll right and left you have to hold the alt key. The problem arises when you attempt to scroll right or left more than once. If you press alt, scroll, release alt, (then optionally scroll or zoom the preview window), and then scroll left or right again, as soon as the alt key is released the preview window disappears and resets.

This is a definite problem when you want to quickly scroll through a larger call. Example    [image](https://i.imgur.com/8zbOGGk.png).

Version: 1.0.295
OS: Windows 10

**Comment by plafosse** [comment]
This could be nice to some may not like this behavior.  I'm going to mark this as won't fix, but it should be possible to do as a plugin in v1.2.
