### ISSUE TITLE
bv.functions return type different for headless

### ISSUE THREAD

**Issue by hanssl** [Vector35/binaryninja-api#2943]
Binary Ninja Version: 3.0.3233, e250d0a3
Platform: Ubuntu 20.04.3 LTS

Steps to reproduce:
1. open a binary with binaryninja
2. from the gui python console type: type(bv.functions) -> <class 'binaryninja.binaryview.FunctionList'>
3. save the bndb to disk
4. Use a headless script to open the bndb with bn.open_view()
5. from the headless script run 'print(f"type(bv.functions): {type(functions)}")' -> outputs type(bv.functions): <class 'tuple'>

Shouldn't the gui and headless script have the same return type for bv.functions?

**Comment by CouleeApps** [comment]
Cannot reproduce on a fresh install. Your `type(functions)` is not defined... does this still happen if you do `print(f"type(bv.functions): {type(bv.functions)}")` ?
<img width="604" alt="image" src="https://user-images.githubusercontent.com/711973/152881495-e3d0d464-3c78-4043-8d47-7281d86c00e0.png">

**Comment by hanssl** [comment]
Oops. My bad.
