### ISSUE TITLE
Type annotation `binaryninja.types.ParamsType` in API is incorrect

### ISSUE THREAD

**Issue by holmesmr** [Vector35/binaryninja-api#2946]
**Version and Platform (required):**
- Binary Ninja Version: 3.0.3233
- OS: macOS
- OS Version: 12.2

**Bug Description:**
The API documentation and type annotations document that `ParamsType` (for specifying the type of parameters for a function) can be tuples of `(Type, str)`.

`FunctionBuilder._to_core_struct(params)` expects tuples of `(str, Type)`, and this is the only place this type is actually used:
https://github.com/Vector35/binaryninja-api/blob/4ee98c21c517e40a31d5eb51ef4cee9fe8b4bb7e/python/types.py#L968-L977

A PR is open (#2906) to fix the type declaration (as reordering the tuple would break API compat with anything using the expected order).

**Steps To Reproduce:**
1. Attempt to create a function type through the API with the ordering `(Type, str)` as specified by `ParamsType`
2. Get a stacktrace.

**Expected Behavior:**
Documented and actual behaviour should match.

**Screenshots:**
n/a

**Additional Information:**
n/a

**Comment by psifertex** [comment]
PR was merged -- thanks very much!
