### ISSUE TITLE
Support Kext Mach-O files

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#295]
The view at the bottom right displays both 'Raw' and 'Mach-O', but won't actually let you select Mach-O. Binary Ninja then becomes the worlds most complex hex editor.

**Comment by pwmoore** [comment]
I can confirm that this happens with OS X kernels and iOS kernelcaches as well. Normal Mach-O binaries open fine, but not kexts or kernels.

**Comment by b3ntx** [comment]
This and #461 are very similar. I suspect much of the same code would address both issues.

**Comment by plafosse** [comment]
Fixed in dev build >= 806
