### ISSUE TITLE
Pseudo-C view not listed in IL carousel options

### ISSUE THREAD

**Issue by computerality** [Vector35/binaryninja-api#2958]
**What is the feature you'd like to have?**
Hitting i to alternate views currently doesn't include Pseudo-C since it isn't in the default carousel or even in list of carousel options as of 3.0.3233. Would be nice to be able to add it and have it included by default.

**Is your feature request related to a problem?**
na

**Are any alternative solutions acceptable?**
idk

**Additional Information:**
n/a

**Comment by psifertex** [comment]
Will be available in dev builds > 3254, good catch.
