### ISSUE TITLE
Incorrect uses of `binaryninja.types.EnumMembersType` in API type annotations

### ISSUE THREAD

**Issue by holmesmr** [Vector35/binaryninja-api#2965]
**Version and Platform (required):**
- Binary Ninja Version: 3.0.3233
- OS: macOS
- OS Version: 12.2

**Bug Description:**
The definition of `EnumMembersType` at https://github.com/Vector35/binaryninja-api/blob/ece59d9114f566a0f364cf8c56d555b70952f70b/python/types.py#L46 includes `List[]` wrapping around all `Union[]` variants. However, its use in https://github.com/Vector35/binaryninja-api/blob/ece59d9114f566a0f364cf8c56d555b70952f70b/python/types.py#L647-L652 wraps the type in a `List[]` as well.

The builder method it calls also has this same annotation: https://github.com/Vector35/binaryninja-api/blob/ece59d9114f566a0f364cf8c56d555b70952f70b/python/types.py#L1237-L1242

as well as the builder's protected method for actually adding the enum members:
https://github.com/Vector35/binaryninja-api/blob/ece59d9114f566a0f364cf8c56d555b70952f70b/python/types.py#L1290-L1305

but this code clearly expects items in `members` to be `Union[Tuple[str, int], str, 'EnumerationMember']`. These annotations should all be `Option[EnumMembersType]`/`EnumMembersType` instead.

**Steps To Reproduce:**
1. Create an enumeration type in the BN GUI console or headless mode following the type annotations in the docs for `Type.enumeration()`, e.g. `Type.enumeration(width=1, members=[[("foo", 1)]])`
2. Get a stacktrace:
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/types.py", line 1702, in enumeration
    return EnumerationType.create(members, width, arch, sign)
  File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/types.py", line 1983, in create
    EnumerationBuilder._add_members(builder, members)
  File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/types.py", line 1209, in _add_members
    core.BNAddEnumerationBuilderMember(enum_builder_handle, name)
UnboundLocalError: local variable 'name' referenced before assignment
```

**Expected Behavior:**
Documented and actual behaviour should match.

**Screenshots:**
n/a

**Additional Information:**
n/a

**Comment by plafosse** [comment]
Just fixed in dev should be in the next release > 3.0.3321
