### ISSUE TITLE
Support context menu with copy options in strings view

### ISSUE THREAD

**Issue by D0ntPanic** [Vector35/binaryninja-api#297]
In strings view, right clicking currently does nothing.  It should bring up a context menu with options to copy or copy with a transform (built-in or custom).

**Comment by galenbwill** [comment]
Just noting that double-right clicking jumps to the string in linear view (which also seems like unexpected UX behavior)

**Comment by galenbwill** [comment]
Would also like to have an option to toggle sorting by address or by string

**Comment by cxnder** [comment]
Resolved in builds >= 3.1.3616
