### ISSUE TITLE
Jump tables sometimes only recognize one case.

### ISSUE THREAD

**Issue by Hypersonic** [Vector35/binaryninja-api#298]
In the attached binary, compiled under `Apple LLVM version 7.3.0 (clang-703.0.29)` under `-O0` for `x86_64-apple-darwin15.3.0`, Binja only recognizes a single case (`case 5`) for the jump table, while it should recognize the other 16 cases as well.

Also attached is the C file that was compiled.

[switch.zip](https://github.com/Vector35/binaryninja-api/files/308082/switch.zip)

**Comment by plafosse** [comment]
This is intended behavior.  The provided example switches on a constant, thus only one case can ever be executed, we display only the one case that is executed.

**Comment by CryptXor** [comment]
Hypothetically, what about a switch which jumps on some sort of input? Since the input is unknown then all possible cases would be processed I assume?

**Comment by plafosse** [comment]
Yes those should show everything because we should the total range of values at the jump.
