### ISSUE TITLE
RepositoryManager.add_repository does not add plugins

### ISSUE THREAD

**Issue by lordidiot** [Vector35/binaryninja-api#2987]
**Version and Platform (required):**
- Binary Ninja Version: Version 3.0.3267-dev Personal (Build ID ef8dc2f8)
- OS: Ubuntu Linux
- OS Version: 20.04

**Bug Description:**
I'm trying to test a binary ninja plugin's metadata for the plugin manager to eventually add to the [community plugins repo](https://github.com/Vector35/community-plugins).
However, I cannot setup the plugin to work locally using the `pluginmanager` module in binary ninja.

Just in order to just test the API, I tried to load the vector35 repository using the `pluginmanager`, but it does not work. The `RepositoryManager.add_repository` function returns `True` but the plugins are not loaded properly.

More details below.

**Steps To Reproduce:**
I entered the following code into the Binary Ninja python console to try loading the vector35 community repository using the API.
```
>>> mgr = RepositoryManager()
>>> mgr.add_repository("https://raw.githubusercontent.com/Vector35/community-plugins/master/plugins.json", "test")
True
>>> mgr.repositories
[<community>, <official>, <test>]
>>> mgr.repositories[2].plugins
[]
```
Notice that `mgr.repositories[2].plugins` is not populated with the plugins like is expected.

**Expected Behavior:**
After running `add_repository` as done in the above code snippet, the manager should be able to load all the relevant plugins, to then be installed/enabled.

**Screenshots:**
If applicable, please add screenshots here to help explain your problem.

**Additional Information:**
In case it is relevant, the `~/.binaryninja/repositories/` directory is not updated either after the API call.
```
(manticore) ctf@ctf:~/.binaryninja/repositories
$ ll
total 16
drwxrwxr-x 4 ctf ctf 4096 Feb 24 14:55 ./
drwxrwxr-x 5 ctf ctf 4096 Feb 23 13:31 ../
drwxrwxr-x 3 ctf ctf 4096 Feb 23 12:37 community/
drwxrwxr-x 3 ctf ctf 4096 Feb 23 12:37 official/
```

**Comment by psifertex** [comment]
Thanks for catching this -- this is a bug caused by the directory for the repository not being created in the right order.

If you manually make the directory in that subfolder called "test" it will be a work-around until we can fix the code in the core.

**Comment by psifertex** [comment]
Another solution is that you can add your test repository to the "official" repository setting and that should also create it for you (and saves you from having to manually add it each time):
<img width="1213" alt="Screen Shot 2022-02-28 at 1 47 15 PM" src="https://user-images.githubusercontent.com/140215/156040736-6185a888-5f61-423d-98f1-11d233d9380c.png">

**Comment by KyleMiles** [comment]
You need to call `mgr.check_for_updates()` for it to fetch the metadata for added repositories. I'll add a note to the docs to that effect.
