### ISSUE TITLE
Improve plugin manager sort

### ISSUE THREAD

**Issue by mechanicalnull** [Vector35/binaryninja-api#2989]
**What is the feature you'd like to have?**
Please make the plugin manager's default sort something better than case-sensitive lexicographic order. Anything is better: sort by stars or other popularity metric, sort by official/unofficial, or even just case-insensitive lexicographic order.

**Is your feature request related to a problem?**
It's counter-intuitive as a user to find plugins starting with a letter at two places in the list (because some plugins start with a capital version of the letter and some with the lowercase).

**Are any alternative solutions acceptable?**
...

**Additional Information:**
N/A

**Comment by fuzyll** [comment]
Looks like we only sorted correctly in one location. This should now be case-insensitively sorted at all times in an upcoming `dev` build later today. Thanks for the report!
