### ISSUE TITLE
Display immediates in different formats

### ISSUE THREAD

**Issue by driest** [Vector35/binaryninja-api#299]
Sometimes, immediates are not just numbers. Eg. they can be ascii strings, like in this optimized strcpy implementation:
![strcpy](https://cloud.githubusercontent.com/assets/518927/15986669/6f2bc20a-300d-11e6-95f9-ef9122a9ceba.png)

It would be really useful to be able to right click on an immediate, and select which format will be displayed. Examples are:
* hex
* octal (think file permission flags etc.)
* decimal
* ascii
* symbolic names of enums

**Comment by psifertex** [comment]
Also, display as negative

**Comment by plafosse** [comment]
Fixed
