### ISSUE TITLE
ASM Block Splitting/Basic block definitions

### ISSUE THREAD

**Issue by mrphrazer** [Vector35/binaryninja-api#2999]
In general, strict basic block definitions terminate basic blocks after each control-flow transfer. To maintain readability, disassemblers don't split after direct/indirect calls. However, for conditional returns and other 'edge cases', binja deviates from other tools (IDA, Ghidra) on the assembly level, while it models it in the same way on the IL level.

For example, the following ARMv7 code has a conditional return ` bxeq    lr`, which doesn't terminate the basic block:

```
0000483c  14309fe5   ldr     r3, data_4858
00004840  14209fe5   ldr     r2, data_485c
00004844  03308fe0   add     r3, pc, r3
00004848  022093e7   ldr     r2, [r3, r2]  {__gmon_start__}
0000484c  000052e3   cmp     r2, #0
00004850  1eff2f01   bxeq    lr
00004854  dff5ffea   b       __gmon_start__
```

However, on IL level it looks as follows:

![image](https://user-images.githubusercontent.com/10834372/156588145-db12211b-dbb2-4692-9b28-7701e3b3e608.png)

It would be nice to make this splitting behavior on the assembly level (especially since it will also be done on the IL level) be more consistent or, at least, configurable (including strict basic block definitions). For starters, some documentation about the current design decisions (if this is intentional) might also help.

**Comment by bpotchik** [comment]
Fixed in `3.0.3275-dev`.
