### ISSUE TITLE
Missing x86/x64 instructions IL translations

### ISSUE THREAD

**Issue by driest** [Vector35/binaryninja-api#300]
The IL doesn't have all instructions implemented. Eg. the rep/scas family on x86 are unsupported.

**Comment by psifertex** [comment]
Renamed the bug since we have others tracking different architectures. Peter was going through all of them and documenting missing instructions, x86 is just a lot more work to track down all the extensions compared to most other architectures. We'll use this ticket though to track it when we flesh out the full list.

**Comment by psifertex** [comment]
Folding in #676 into this one:

Taking a crack at some of the known missing extensions as well while I'm here. Feel free to comment if I've missed one: 

- [ ] [BMI1](https://en.wikipedia.org/wiki/Bit_Manipulation_Instruction_Sets#BMI1_.28Bit_Manipulation_Instruction_Set_1.29)
- [ ] [BMI2](https://en.wikipedia.org/wiki/Bit_Manipulation_Instruction_Sets#BMI2_.28Bit_Manipulation_Instruction_Set_2.29)
- [ ] [TBM](https://en.wikipedia.org/wiki/Bit_Manipulation_Instruction_Sets#TBM_.28Trailing_Bit_Manipulation.29)
- [ ] [SVM EPT](https://www.tptp.cc/mirrors/siyobik.info/instruction/INVEPT.html)
- [ ] [CLMUL](https://en.wikipedia.org/wiki/CLMUL_instruction_set)
- [ ] [FMA](https://en.wikipedia.org/wiki/FMA_instruction_set)
- [ ]

**Comment by psifertex** [comment]
Also worth pointing out that we've been discussing internally switching to xed for disassembly which makes life much easier for keeping up with all the disassembly though doesn't necessarily do much for the lifting.

**Comment by KyleMiles** [comment]
Disassembly added in 1.1.1287-dev, lifting not.

**Comment by KyleMiles** [comment]
Closing this in favor of #1362.
