### ISSUE TITLE
Need hard error when applying non-pointer function type to variable

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#3004]
**EDIT:** Ignore this, see comment below.

**Version and Platform (required):**
- Binary Ninja Version: 3.0.3238-dev Enterprise
- OS: macOS
- OS Version: 12.2.1

**Bug Description:**
In the malware sample linked in [this discussion thread](https://github.com/Vector35/binaryninja-api/discussions/3003), the function call at 0x00402eff exhibits a whole bunch of odd behaviors. Here are my random notes from a Slack conversation about it:

* The function call is through a memory access (`call dword[ebp-0x30]`)
* HLIL says, initially, `int32_t eax_5 = eax_1(...)`, which is confusing, but not wrong (`eax` is moved into `ebp-0x30` earlier in the function)
* Re-typing the function is weird because it initially just shows as `void* eax_1` despite it showing as taking 3 arguments in the HLIL view
* Afterward, there is no change to the output whatsoever (aside from `eax_1` being renamed to `var_34_1`)
* There are clearly 5 arguments to the function, although one of them ("HTTP") is being pushed to an address instead of the stack which is kinda weird
* Hitting `y` on `var_34_1` shows the type as `int32_t var_34_1` and not the type I gave it before (function with 5 arguments)
* Changing the type to the same exact thing I had before just changes the variable name to `eax_1`, but this time, it shows the type correctly while the HLIL output still only shows 3 arguments despite the type now showing 5

**Steps To Reproduce:**
See above. The type I was trying to give to the function was `void* eax_1(LPCSTR, DWORD, LPCSTR, LPCSTR, DWORD)`.

**Expected Behavior:**
As mentioned above, I expected HLIL to show 5 arguments for the function after changing its prototype instead of continuing to show 3. I also didn't expect the type for the variable `eax_1` to continually be shown incorrectly throughout the process.

**Comment by fuzyll** [comment]
So, turns out I'm bad at computers at the type _should_ have been `void* (*eax_1)(LPCSTR, DWORD, LPCSTR, LPCSTR, DWORD)`. This works just fine if you don't do the wrong thing!

But: Shouldn't this be an error if you try to do this..? I can't think of an instance where applying a function type to a variable would be something you actually intend to do.

**Comment by CouleeApps** [comment]
Here's the dialog you will get for this as of 3.2.3801-dev: 
<img width="532" alt="image" src="https://user-images.githubusercontent.com/711973/197367543-cbb51d02-8548-485c-94ce-a8f54a1b6ea1.png">
