### ISSUE TITLE
Dataflow should track variables through registers

### ISSUE THREAD

**Issue by driest** [Vector35/binaryninja-api#301]
For example in the following picture, var_14 is tracked for memory reads, but not when moved around registers (eax, edx, edi):
![scasb_counter_flow](https://cloud.githubusercontent.com/assets/518927/15986705/15efcafe-300f-11e6-9ea7-4f2aa0f5d3f8.png)

**Comment by plafosse** [comment]
It does, in later version you can hover over the registers to see their values.
