### ISSUE TITLE
Improve decompiler output for PE binaries

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#3016]
**Version and Platform (required):**
- Binary Ninja Version: 3.0.3297-dev
- OS: Windows
- OS Version: 11

(Original reporter was, I believe, on Linux.)

**Bug Description:**
We really need to make our analysis a lot cleaner-looking for certain functions. Here's a user's side-by-side comparison of us and IDA for a really small binary:

![](https://i.imgur.com/SC5OHl0.png)

Some of these parts, marked in red, are extraneous and probably don't need to be a part of the decompiler output:

![](https://i.imgur.com/oSDv2Sm.png)

**Steps To Reproduce:**
The input binary was the following, compiled on Windows for x86:

![](https://i.imgur.com/IXb2vXu.png)

Just open that up and view the default results.

**Expected Behavior:**
Our output often looks pretty good, but this is a case where, for some reason, we output a lot of extraneous stuff that can slow down or confuse a user. I would have expected something closer to IDA's output without all of the marked lines from the second screenshot above. The user that reported this also expected this.

**Comment by psifertex** [comment]
The stack cookie check and init are a duplicate of [2250](https://github.com/Vector35/binaryninja-api/issues/2250) already and everything else as far as i can tell is basically either preference or already greyed out specifically as a low-confidence thing (which when we _didn't_ show people complained we were eliminating too many things!)

**Comment by lexika979** [comment]
Maybe making this an option that can be changed In the settings would be the best solution in general? That way everyone can have their output how they like it :)

**Comment by psifertex** [comment]
So...  some of the items you highlighted were specifically in the IDA view too. Like v5 = 10 / var_34=0xa

That would never be covered by such a setting, can you maybe clarify a bit more what the issue is there?

**Comment by fuzyll** [comment]
I think the main problems were:

1. Stack cookie stuff at the top/bottom (which is covered by #2250 and I just didn't see that before).
2. The `printf` function (`sub_401050` is missing varargs, which is a fairly quick manual fix, though possibly something we could deal with better)

I think it's fine if we close this in favor of #2250, I just wanted to make sure we had this documented somewhere since it was a nice, small test case. I wasn't able to find a ticket for anything related to varargs in a quick search, though, so maybe we should re-focus the ticket on that?

**Comment by lexika979** [comment]
Small thing I'd like to add:
It would be awesome to have a option where BN would place the string directly in the function call instead of showing the address to where the string is stored and placing the actual string in a comment, I'd say it helps with readability.

**Comment by psifertex** [comment]
It will do this if the function call has an argument that indicates it is a string. Alternatively, just hit `a` on the parameter.

**Comment by fuzyll** [comment]
I think all aspects of this ticket are now covered by:

1. #2250 (for the stack cookie stuff)
2. Our current work with types/type libraries (for the `printf` thing), which should hopefully be landing on `dev` in the next week or two 🤞 
3. #3026 (for some of the extra stuff that could be eliminated)

So, I'm closing this in favor of those. This issue should be linked to each so we have an extra test case, though. 👍
