### ISSUE TITLE
Show vtable function calls as normal function call

### ISSUE THREAD

**Issue by lexika979** [Vector35/binaryninja-api#3017]
**What is the feature you'd like to have?**
VTable function calls currently show up as the vtable ptr with a offset:
![lbWETnQ](https://user-images.githubusercontent.com/83946527/158711701-297b142c-9b31-4d69-9140-85801bfa0279.png)

Which looks rather dirty and prevents me from jumping into the function by clicking on it, or renaming the function globally. 

Implementing a feature to make these show up as actual function calls would fix all the issues explained above.

**Is your feature request related to a problem?**
No

**Are any alternative solutions acceptable?**
Finding the target function manually and creating a cross-reference to it may work, but is tedious and not a long-term solution.

**Additional Information:**
None

**Comment by CouleeApps** [comment]
There is a workaround for this in the meantime:

You can define a structure manually for the vtable, with function pointers to all relevant functions:
```
struct Foo_vtable
{
    void (*foo_func1)(Foo* this, int etc);
};
struct Foo
{
    Foo_vtable* vtable;
};
```

Then retype `this` to `Foo*` and HLIL should show `this->vtable->foo_func1(this, etc)`.

It's not perfect and it's not very automated, but you could probably write a script to create structures from RTTI information.

**Comment by fuzyll** [comment]
Hey @lexika979, the binary for this one is the one you had me run the plugin for you on, right? Do you mind if I attach it to this issue?

**Comment by lexika979** [comment]
Yep, you can attach it, no problem ^^

**Comment by lexika979** [comment]
> There is a workaround for this in the meantime:
> 
> You can define a structure manually for the vtable, with function pointers to all relevant functions:
> 
> ```
> struct Foo_vtable
> {
>     void (*foo_func1)(Foo* this, int etc);
> };
> struct Foo
> {
>     Foo_vtable* vtable;
> };
> ```
> 
> Then retype `this` to `Foo*` and HLIL should show `this->vtable->foo_func1(this, etc)`.
> 
> It's not perfect and it's not very automated, but you could probably write a script to create structures from RTTI information.

Would this enable me to jump into the function aswell?

**Comment by fuzyll** [comment]
> Yep, you can attach it, no problem ^^

Thanks!

This is the binary in question: [engine.zip](https://github.com/Vector35/binaryninja-api/files/8278162/engine.zip)

**Comment by CouleeApps** [comment]
> Would this enable me to jump into the function by clicking on it?

Double clicking the vtable functions on that would most likely bring you to the vtable type, since the actual function pointers are not known statically (that's the whole point of a vtable). If you annotated the various vtables in memory as `struct Foo_vtable` then you should be able to see all the data cross references to see the possible values for that function.

**Comment by ccarpenter04** [comment]
I'd be very grateful to see better handling of VTables and RTTI information in general.

**Comment by psifertex** [comment]
Instead of commenting, just upvote the original issue. That's how we often sort for priority.

**Comment by emesare** [comment]
With the addition of `__data_var_refs` (see: [C++ Types user docs](https://docs.binary.ninja/guide/cpp.html#defining-a-virtual-function-table)) this is effectively solved.

**Comment by fuzyll** [comment]
Yeah, I think I forgot to close this back when we got the new `vtable` stuff in that you linked to the docs for. Thanks for the reminder. 🙂 

Agreed entirely that we need to handle RTTI better, though, thanks for linking the issues. Your plugin was helpful the last time I needed to use it, but you're right that we should be handling this stuff in the core.
