### ISSUE TITLE
Annotations showing up incorrectly

### ISSUE THREAD

**Issue by driest** [Vector35/binaryninja-api#302]
In the following example, editing the annotation in line 7 changes the value of the immediate in line 1 (renamed to counter):
![counter](https://cloud.githubusercontent.com/assets/518927/15986725/a40d7ac0-300f-11e6-924f-6a088dbda2a4.png)

![counter_rename](https://cloud.githubusercontent.com/assets/518927/15986718/7cb19862-300f-11e6-8ed1-3d21e62b198a.png)

**Comment by psifertex** [comment]
This should be resolved with the new type system and type propagation. Sorry for the long lived issue.
