### ISSUE TITLE
No type information on line

### ISSUE THREAD

**Issue by lexika979** [Vector35/binaryninja-api#3023]
**Version and Platform (required):**
- Binary Ninja Version: 3.0.3233 Personal
- OS: Windows
- OS Version: 11

**Bug Description:**
"There is no type information on this line. Please report this bug!" shows up in the log when i try to change the type of a function.

**Steps To Reproduce:**
1) Download this bndb: https://drive.google.com/file/d/14bMzyTXkmZE2ruLTEKA1tYU8mx21WP37/view?usp=sharing
2) Open it in BN
3) Search for the function "C_BaseAnimating::SetupBones"
4) Click on the function definition and press Y or Right click -> Change type
5) You can now find the error in the log

**Expected Behavior:**
I expected to be able to change the type.

**Screenshots:**
![R8tc6KW](https://user-images.githubusercontent.com/83946527/158881045-1c4a10e8-c17a-4109-8c09-562b1359eaa5.gif)

**Additional Information:**
Happens in all forms of decompilation, including HLIL and Pseudo C.

**Comment by fuzyll** [comment]
Was able to reproduce this, but _only_ in linear view, on 3.0.3312-dev Enterprise.

In graph view, you can click the name of the function and hit 'y' and get the type modification window as you would expect. In linear view, it gives the "There is no type information on this line." error (when clicking on the name of the function, or any of the variables).

**Comment by xusheng6** [comment]
Fixed in dev 3.3.3391
