### ISSUE TITLE
PDB downloader checks file order wrong and has no support for ptr files

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#3025]
The current pdb plugin loads plugins in the wrong order (checks for cab first and then the raw pdb) and does not additionally check for the existance of `file.ptr` which can indicate the PDB is available via a UNC. We should fix the order and add at least some minimal support for detecting the ptr file format.

https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/symbol-storage-format

**Comment by psifertex** [comment]
Resolved in dev builds >= 3301. Note that PTR support currently only logs to the console. Depending on your OS, something adapted from https://gist.github.com/psifertex/6fbc7532f536775194edd26290892ef7#file-ptr_dl-py may prove useful to automatically downloading the PDB and saving it in the correct location.

**Comment by fuzyll** [comment]
@plafosse did some extra work on this:

1. There is a new command “PDB//Load From File” which will just prompt you with a dialog. All of the below stuff is rather hacky but it gets around some deficiencies in our plugin command system. These will likely be resolved when we convert the PDB plugin to a DebugInfo plugin.
2. “PDB//Load From File” has an as of yet undocumented feature. It will query the binaryview metadata for `PDB_USER_PATH` and if that exists it will open that instead.
3. If we encounter a PTR file we put the path of it into `PDB_PTR_PATH`

```
run_plugin_command("PDB//Load")
sleep(3) # wait for the pdb to be loaded or the metadata to be written
pdb_unc_path = bv.query_metadata("PDB_PTR_PATH")
pdb_local_path = map_unc_path_locally(pdb_unc_path)
bv.store_metadata("PDB_USER_PATH", pdb_local_path)
run_plugin_command("PDB//Load From File") # there is a special case here to attempt to open whatever is in the "PDB_USER_PATH" metadata. Normally this code just pops a file picker
```
