### ISSUE TITLE
Skipping analysis for function, Exceeds 'analysis.limits.maxFunctionUpdateCount'

### ISSUE THREAD

**Issue by lexika979** [Vector35/binaryninja-api#3036]
**Version and Platform (required):**
- Binary Ninja Version: 3.0.3298-dev
- OS: Windows
- OS Version: 10

**Bug Description:**
While Analysis of a binary was running i got the following warning:
![fZJJTLV](https://user-images.githubusercontent.com/83946527/159430918-282b4e7b-87d7-4bc1-bda4-c2bbed19be5b.png)

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Download [this](https://cdn.discordapp.com/attachments/937625265310433320/955728032323215410/client.dll) binary
2. Throw it in BN
3. Wait for the error to appear in the console

**Comment by bpotchik** [comment]
Fixed in `3.1.3677-dev`.
