### ISSUE TITLE
Navigation issues in Linear View when Prefer Disassembly Graph is set

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#3037]
**Version and Platform (required):**
- Binary Ninja Version: 3.0.3233 Personal
- OS: macOS
- OS Version: 11.6.4

**Bug Description:**
If I select an address in the Disassembly Graph view then copy that selected address then change the view to Linear Disassembly then hit "G" to Go to Address, then paste the address and hit enter, the view changes back to the Graph view before displaying the location. I can't figure out how to go to an address in Linear view. This seems to be either a regression, or the behavior has been changed and I don't know the new trick. Any hints?

**Steps To Reproduce:**
See text above and video below.

**Expected Behavior:**
The current view is retained.

**Screenshots:**

https://user-images.githubusercontent.com/607452/159506340-3b5d1c8c-488c-45d0-ba91-c72ab2607815.mp4

Example of focus across views bug:

**Additional Information:**
I have isolated which setting is causing the problem:
Settings > UI > view.graph > Prefer Disassembly Graph > Set

If I unset this, the view behavior is as expected. I have attached a video of what appears to be a bug when this setting is set.

**Comment by fuzyll** [comment]
The user that reported this provided a video and repro steps and everything, but I actually can't seem to reproduce this on any platform with 3.0 stable or latest dev. Going to close this one...happy to see it re-opened if someone can point me in the right direction on how to reproduce the behavior.

**Comment by bpotchik** [comment]
I can't repro either. Reporter should see if the bug still occurs on the latest version of dev.
