### ISSUE TITLE
Location is not preserved across views

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#3038]
**Version and Platform (required):**
- Binary Ninja Version: 3.0.3233 Personal
- OS: macOS
- OS Version: 11.6.4

**Bug Description:**
When I have a file open to the Disassembly Graph view and I have a particular address selected then change the view to Linear Disassembly, the location that appears is different than the one highlighted in the previous view.

**Steps To Reproduce:**
See text above and video below.

**Expected Behavior:**
The current location in the binary should be retained across view changes within a pane.

**Screenshots:**
https://user-images.githubusercontent.com/607452/159508377-12d1edef-299d-44d8-9eb9-c386ed7deac3.mp4

**Additional Information:**
All user settings were disabled when creating the video above.

**Comment by fuzyll** [comment]
Original issue was reported via email by a different user.

I can reproduce the issue by following the steps shown in the screenshot with 3.0.3280-dev Enterprise.

I cannot reproduce the behavior by using the spacebar or the Command Palette option "View in Linear Disassembly".

I suspect we just need to change the behavior of the drop-down to do whatever the Command Palette option is doing.

**Comment by bpotchik** [comment]
Fixed in `3.0.3315-dev`.
