### ISSUE TITLE
Programatically setting comments without clobbering existing comments 

### ISSUE THREAD

**Issue by Ayrx** [Vector35/binaryninja-api#3047]
The current API to set a function level comment is as follows:

```
current_function.comment = "hi"
```

When writing plugins to perform some analysis, it is sometimes nice to annotate items with comments. However, it would be nice to have an API that can allow plugins to do the following which is currently very difficult with strings:
1. Add comments without clobbering existing comments
2. Avoid annotating with the same comment if the analysis has been run before

The simplest way I can think of accomplishing this would be to change the `comment` type from a string to a list of strings. The UI can join the items in the list together with new lines in between for display.

**Comment by Ayrx** [comment]
Fair enough, but FWIW this would probably be a change to the type of the existing `comment` property and a change in the type signature of the `set_comment_at` method instead of an additional API.

**Comment by psifertex** [comment]
that's true, though the downside of that solution is it breaks old plugins.
