### ISSUE TITLE
GUI API for plugins

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#305]
Provide the ability for plugins to extend the current GUI, possible transitional step of some simple built-in dialogs before the extensible UI itself is refactored)

**Comment by psifertex** [comment]
Highlighting is probably a good one for this intermediate plugin UI functionality.

**Comment by soen-vanned** [comment]
This could be as simple as adding a python binding to the QtGui.QMainWindow object ;)

**Comment by D0ntPanic** [comment]
In dev, there are now APIs to easily ask for user input and filenames (including a simple form API to ask for multiple fields), and to show a text/markdown/HTML report of plugin results in a new tab. Full Qt bindings will be added for full UI support post v1.1

**Comment by lucasduffey** [comment]
something to think about: 

if the function window is modular a tree-base "class" function viewer would be possible. Could potentially make C++ and java-based languages easier.

**Comment by plafosse** [comment]
Added as of v1.1.556
