### ISSUE TITLE
Support PAC instructions when assembling aarch64

### ISSUE THREAD

**Issue by fabianfreyer** [Vector35/binaryninja-api#3055]
**Version and Platform (required):**
- Binary Ninja Version: 3.0.3331-dev
- OS: MacOS
- OS Version: 12.3

**Bug Description:**
The assembler doesn't support aarch64 PAC instructions

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Make a new binary
2. Open the Assemble dialog
3. Type in a PAC instruction, e.g. `paciza x13`
4. Click `Assemble`
5. Observe the following error message:
<img width="714" alt="image" src="https://user-images.githubusercontent.com/3423837/161649570-fb213a9a-b0af-4726-808e-7e04d3d08975.png">

**Expected Behavior:**
The instruction to be assembled and written to the BinaryView.

**Comment by galenbwill** [comment]
FYI, error message is not shown in the above screenshot

**Comment by fabianfreyer** [comment]
@galenbwill thanks! Fixed 👍

**Comment by fuzyll** [comment]
I _believe_ that error message means that we aren't invoking the assembler with the `pauth` extension enabled. It's not very clear from the LLVM documentation how we turn this on, but we may need to call `[LLVMCreateDisasmCPUFeatures](https://llvm.org/doxygen/group__LLVMCDisassembler.html#ga0ed319f9f853493c0b38e551ec2adfc5)` instead of `LLVMCreateDisasm` and specify it in the third argument?

**Comment by fabianfreyer** [comment]
It'd be really ideal if one could specify those features somehow (or the arch could?)

**Comment by lwerdna** [comment]
The fix is in the arm64 architecture repo: https://github.com/Vector35/arch-arm64/commit/9f5f827fe5a18760d39d4bd6da652f80468c26cb

BinaryNinja dev will have it at the next build.

**Comment by fabianfreyer** [comment]
Thanks! so as a user, I could set that using `.arch_extension`? That's good to know for the future :)

**Comment by lwerdna** [comment]
Yes, assembling this:

```
.arch_extension pauth
paciza x13
```

worked, and I almost suggested it as a workaround, but it's so much nicer not having to think about it.
