### ISSUE TITLE
BinaryNinja hangs when Python extension throws exception in is_valid

### ISSUE THREAD

**Issue by fabianfreyer** [Vector35/binaryninja-api#3056]
**Version and Platform (required):**
- Binary Ninja Version: 3.0.3111-dev
- OS: macOS
- OS Version: 12.3

**Bug Description:**
When a Python extension throws an exception in the `is_valid` callback of a `PluginCommand`, Binary Ninja will hang

**Steps To Reproduce:**
Create and install the following plugin:
```python
from binaryninja.plugin import PluginCommand

def action(bv):
    pass

def is_valid(bv):
    raise Exeption("test")

PluginCommand.register("foo", "bar", action, is_valid)
```

Observe Binary Ninja to hang when opening a BinaryView.

**Expected Behavior:**
Binary Ninja does not crash, and logs the exception data to the log window.

**Additional Information:**
The problem seems to be related to logging. The vscode debugger shows `is_valid` to be invoked over and over again, recursively.

**Comment by plafosse** [comment]
Fixed in latest dev
