### ISSUE TITLE
Closing a search pane during an ongoing search stops the search

### ISSUE THREAD

**Issue by MartijnB** [Vector35/binaryninja-api#3061]
**Version and Platform (required):**
- Binary Ninja Version: 3.3.3337-dev
- OS: Windows
- OS Version: 11

**Bug Description:**

When you start a second HLIL search while the first pane is still open, closing the first pane kills the second search.

**Steps To Reproduce:**

1. Start a HLIL (Text) search and wait until the results are ready. There is no need to find anything (actually, I had no results)
2. Start a new search without closing the results of the first search
3. Close the first search
4. The second search is stopped in the middle and doesn't continue

**Expected Behavior:**

First pane closes, second pane continues searching

**Screenshots:**

Start a second search while the first is still open:
![image](https://user-images.githubusercontent.com/506862/162561465-9897c606-3e3b-4a7e-8f57-9a60855134d5.png)

Close the results pane of the first search and the second search stops:

![image](https://user-images.githubusercontent.com/506862/162561501-fa63c640-efa4-4753-9123-c2a661154512.png)

If you close it and restart the search, everything works fine again. So likely the close pane action checks if there is an active search and stops it even though it doesn't correspond with the closed pane?

**Comment by xusheng6** [comment]
This is already fixed in dev 3.3.3338. Credit goes to Rusty.
