### ISSUE TITLE
Variables view provides inconsistent values

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#3066]
**Version and Platform (required):**
- Binary Ninja Version: 3338-dev
- OS: Windows
- OS Version: 11

**Bug Description:**
This is a very strange bug. In some situations, the variables view provides incorrect values for variables in a function. What makes it particularly weird is the specific values it provides. Right now it is the constant value 0x20 for all variables. In the past it's been addresses from the binaryninja process itself.

**Steps To Reproduce:**
These repro steps suck, sorry. It requires a Windows machine with virtual desktops (as in https://www.windowscentral.com/how-use-multiple-desktops-windows-10) set up, and at least two virtual desktops

Please provide all steps required to reproduce the behavior:
1. Open any binary and select the variables pane from the left
2. Click on the function name in the main area, e.g. 
![image](https://user-images.githubusercontent.com/8716677/162635996-f56551cd-ba76-4584-aaa3-b9076e075887.png)

4. Navigate away from this virtual desktop and back. I use the keyboard to do this quickly: Windows + Control + Left/Right
5. The values in the variables pane should immediate change on navigation back to the desktop with binja running.

**Expected Behavior:**
I expect the variables view to contain accurate values.

**Screenshots:**
Current bugged behavior:
![image](https://user-images.githubusercontent.com/8716677/162635837-7e53e91f-f326-4c3f-9554-31a1b175438a.png)

This is an old screenshot, but here is an example of addresses being leaked
![image](https://user-images.githubusercontent.com/8716677/162635788-5e417401-0794-4c84-9ab5-29dc31dfbf5b.png)
![image](https://user-images.githubusercontent.com/8716677/162635793-ce35f634-4ad2-4363-b33b-cb104f1f304b.png)

The second screenshot is windbg attached to binaryninja.exe

**Comment by yrp604** [comment]
Some more info, I can still repro as of 3414-dev. Requires linear view, also requires the selected line to not map well to the underlying IL? Im guessing, but for the example function, it triggers reliably when these lines are highlighted:
![image](https://user-images.githubusercontent.com/8716677/168200388-eb255640-6693-4b52-a19d-2a805a2e608d.png)

**Comment by jonpalmisc** [comment]
Potentially fixed in builds ≥3428. When you have some time, please report back if the issue persists.

**Comment by yrp604** [comment]
This doesn't seem to repro anymore :)
