### ISSUE TITLE
Annotations show up weird around conditional jumps

### ISSUE THREAD

**Issue by toomanybananas** [Vector35/binaryninja-api#307]
Like this:

![screenshot from 2016-06-15 20 53 05](https://cloud.githubusercontent.com/assets/694033/16102186/33bcb73e-333b-11e6-9dcd-7edfe108d261.png)

**Comment by psifertex** [comment]
Sorry for the super old notice on this, any chance you have this sample still around so we can test it on the latest build?

**Comment by psifertex** [comment]
So I think this isn't an issue with a conditional jump but rather an artifact of just having a symbol at the destination of the jmp. I'm not entirely sure that's a problem? Without a counter-example I'm going to assume that's the cause and it's closed. Feel free to re-open if that's not the case!
