### ISSUE TITLE
Adding overlapping segment may lead to segment truncation

### ISSUE THREAD

**Issue by fabianfreyer** [Vector35/binaryninja-api#3072]
**Version and Platform (required):**
- Binary Ninja Version: 3.0.3355-dev
- OS: macOS
- OS Version: 12.3.1
- CPU Architecture x64

**Bug Description:**
When adding a segment that overlaps an existing segment in such a way that it is completely contained within the existing segment, the existing segment is truncated to the start of the new segment, dropping the part _after_ the added segment.

**Steps To Reproduce:**
1. Create a new raw file: `echo -e AAAABBBBCCCC > raw.bin`
2. Open the new raw file in Binary Ninja
3. In the Mapped view, observe the full binary is shown:
    <img width="888" alt="image" src="https://user-images.githubusercontent.com/3423837/163816748-3d9339a6-58bf-43c3-9776-fc2e46bd828f.png">
4. Create a segment within the initial segment:
    ```
    bv.add_user_segment(4,4,4,4,7)
    ```
5. Observe the initial segment has been truncated up to the start of the segment, followed by the second segment. Data that was part of the initial segment but _after_ the added segment is no longer displayed.
    <img width="844" alt="image" src="https://user-images.githubusercontent.com/3423837/163817038-fee375b4-fe54-49ef-bd60-37d2a0314f83.png">

**Expected Behavior:**
The overlapped segment is split into (up to, depending on overlap) two sub-segments, like so:
<img width="884" alt="image" src="https://user-images.githubusercontent.com/3423837/163817541-8a15bc7c-be21-4a53-8c2a-babe5d285be0.png">

**Comment by plafosse** [comment]
Seems like a bug, our code is supposed to take this into account.

**Comment by plafosse** [comment]
Fixed in 3.3.4033
