### ISSUE TITLE
Error while installing debugger plugin

### ISSUE THREAD

**Issue by st1064870** [Vector35/binaryninja-api#3075]
Binary Ninja Version: 3.0.3233 Personal, e250d0a3
Platform: Arch Linux
OS version : Linux archlinux 5.17.3-arch1-1

I have set the Python path to Python 3.9 because I have also other Python versions installed.

Steps to reproduce (Not sure if this is reproducable)
1. Click the install plugin button on the official debugger plugin
2. Press ok in the appearing dialogs
3. Then this error appears:

Running pip ['/usr/bin/python3.9', '-m', 'pip', '--isolated', '--disable-pip-version-check', 'install', '--verbose', '--target', '~/.binaryninja/python39/site-packages', 'colorama']
Status 1 Failed to unzip temporary file ~/.binaryninja/repositories/official/plugins/d48f557d-c8f6-4463-80e1-f309cbf5346f.zip
Failed to install plugin:
Debugger
Check the log for more details

**Comment by xusheng6** [comment]
The Python debugger plugin is deprecated. And we will push a C++ debugger to the dev soon. If you still wish to install the Python debugger, you can manually install this: https://github.com/Vector35/deprecated_python_debugger.

**Comment by xusheng6** [comment]
We should update the official plugin info to point to the https://github.com/Vector35/deprecated_python_debugger. However, we are in the middle of the transition and it is not finished yet. Thanks for the report anyways!
