### ISSUE TITLE
Make maximum HLIL function complexity limit configurable

### ISSUE THREAD

**Issue by cr7pt0pl4gu3** [Vector35/binaryninja-api#3079]
**Version and Platform (required):**
- Binary Ninja Version: Version 3.0.3357-dev
- OS: MacOS
- OS Version: Monterey 12.3.1
- CPU Architecture M1

**Bug Description:**
Even when "Possible Value Set Function Complexity Limit" is set to 99, Binary Ninja still omits some of the functions.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Set "Possible Value Set Function Complexity Limit" in settings to 99
2. Load big binary into Binary Ninja
3. Observe log menu and notice the warning

**Expected Behavior:**
Function complexity of 99 or max should allow binary ninja to analyse all functions.

**Screenshots:**
![image](https://user-images.githubusercontent.com/43863412/164490608-63c2c044-6e9b-4391-91e5-2ca82efea0e3.png)

**Comment by psifertex** [comment]
Just following up that while there is an issue not being able to set that particular value above 99, that ultimately won't fix this particular issue. The HLIL complexity limits are not currently configurable.

**Comment by jonpalmisc** [comment]
To clarify, the setting in the screenshot is unrelated to the warnings in the screenshot. The former is a setting for the variables list sidebar item, and the latter is due to the (currently not-configurable) maximum HLIL function complexity. I have renamed this issue to reflect this.

**Comment by bpotchik** [comment]
This is already configurable on dev. See settings `analysis.hlil.maxConditionComplexity` and `analysis.hlil.maxIntermediateConditionComplexity`.

This setting is available in 3.0.3445-dev.
