### ISSUE TITLE
virtualenv path doesn't include .egg subdirectories

### ISSUE THREAD

**Issue by infinitesteps** [Vector35/binaryninja-api#3080]
**Version and Platform (required):**
- Binary Ninja Version: 3.0.3233 (Build ID e250d0a3)
- OS: Ubuntu 
- OS Version: 20.04.4 LTS
- CPU Architecture: x86_64

**Bug Description:**
The use of the `python.virtualenv` setting doesn't search *.egg library subdirectories. Therefore any modules installed as an egg aren't available to binary ninja plugins.

**Steps To Reproduce:**

1. Create python virtual environment outside of binary ninja

   ```
   $ cd /tmp/
   $ python3 -m venv scratch
   ```
2. Activate venv and install a module that uses an egg (ex. [chiken](https://hinty.io/ivictbor/create-an-egg-file-example/))

   ```
   $ . /tmp/scratch/bin/activate
   (scratch) $ python setup.py install  # the chiken setup.py file
   (scratch) $ ls /tmp/scratch/lib/python3.8/site-packages/chiken-0.1-py3.8.egg 
               /tmp/scratch/lib/python3.8/site-packages/chiken-0.1-py3.8.egg
   ```
3. Install another module using pip (numpy)

   ```
   (scratch) $ pip install numpy
   ```
4. Verify that both modules are available to venv running outside of bninja:

   ```
   >>> import chiken
   >>> chiken.__file__
       '/tmp/scratch/lib/python3.8/site-packages/chiken-0.1-py3.8.egg/chiken/__init__.py'
   >>> import numpy
   >>> numpy.__file__
       '/tmp/scratch/lib/python3.8/site-packages/numpy/__init__.py'

   ```

3. In bninja settings configure `python.binaryOverride` and `python.virtualenv` to point to new venv

   ```
	"python.binaryOverride" : "/tmp/scratch/bin/python",
	"python.interpreter" : "/usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0",
	"python.virtualenv" : "/tmp/scratch/lib/python3.8/site-packages"
   ```
4. In bninja python console repeat the verification step

   ```
   >>> import chiken
       Traceback (most recent call last):
         File "<console>", line 1, in <module>
       ModuleNotFoundError: No module named 'chiken'
   >>> import numpy
   >>> numpy.__file__
       '/tmp/scratch/lib/python3.8/site-packages/numpy/__init__.py'
   ```

**Expected Behavior:**
When configured to use a Python virtual environment, use the same library paths as the virtual environment.

**Comment by psifertex** [comment]
It looks like easy_install (and thus eggs since pip doesn't have support for eggs afaik) is deprecated. I _think_ you can manually work around this restriction by doing something like this in your script to work around it but I haven't tested it:

```
import os
pth = Settings().get_string("python.virtualenv")
with open(os.path.join(pth, "easy_install.pth", "r") as f:
  for line in f.readlines():
    sys.path.append(line)
```
