### ISSUE TITLE
Add support for R_AARCH64_MOVW_UABS_G* relocations

### ISSUE THREAD

**Issue by resrever** [Vector35/binaryninja-api#3089]
I'm analyzing some AARCH64 binaries that use a lot of R_AARCH64_MOVW_UABS_G* relocations to embed 64-bit offsets 16 bytes at a time over 4 assembly instructions.  For example:

`0035e670  090080d2   mov     x9, #0
0035e674  0900a0f2   movk    x9, #0, lsl #0x10
0035e678  0900c0f2   movk    x9, #0, lsl #0x20
0035e67c  0900e0f2   movk    x9, #0, lsl #0x30`

But the 4 immediates have the 64-bit value split over 4 operands.  Without these relocations, Binary Ninja cannot identify the correct register values.

There is a push request for Ghidra that addresses these relocations:
https://github.com/NationalSecurityAgency/ghidra/pull/3546/files
However, while that ghidra push request fixes the issue for sequences like above, that code ignores the actual relocation subtype, and assumes the shift offset in the target instruction matches the G0, G1, etc. relocation subtype.  A precise fix would get the shift value from the number after G.  From the ARM ELF reference manual:

Reloc Code | Name | Comment
287 R_AARCH64_MOVW_PREL_G0 - bits 15:0, check value fits in 16 bits
288 R_AARCH64_MOVW_PREL_G0_NC - bits 15:0, no check
280 R_AARCH64_MOVW_PREL_G1 - bits 31:16, check value fits in 32 bits
290 R_AARCH64_MOVW_PREL_G1_NC - bits 31:16, no check
291 R_AARCH64_MOVW_PREL_G2 - bits 47:32, check value fits in 48 bits
292 R_AARCH64_MOVW_PREL_G2_NC - bits 47:32, no check
293 R_AARCH64_MOVW_PREL_G3 - relocation address bits 63:48

The 16-bit value is assigned to the AARCH64 instruction operand bits 21:5

I also found this discussion informative:
https://stackoverflow.com/questions/38570495/aarch64-relocation-prefixes

**Comment by galenbwill** [comment]
Resolved by merge of https://github.com/Vector35/arch-arm64/pull/107

Fixed in `3.0.3366-dev`.

**Comment by galenbwill** [comment]
Fixed in `3.0.3366-dev`.

Resolved by merge of https://github.com/Vector35/arch-arm64/pull/107

**Comment by galenbwill** [comment]
Fixed in `3.0.3366-dev`.

Resolved by merge of https://github.com/Vector35/arch-arm64/pull/107
