### ISSUE TITLE
'Check for updates...' seen twice in File dropdown in OSX

### ISSUE THREAD

**Issue by jgrunzweig** [Vector35/binaryninja-api#309]
Latest version shows 'Check for updates...' twice in the File dropdown in OSX, as seen below.

<img width="233" alt="screen shot 2016-06-17 at 1 55 17 pm" src="https://cloud.githubusercontent.com/assets/492768/16159912/55b61cdc-3493-11e6-9fa0-b2f6de4d8079.png">

**Comment by psifertex** [comment]
Hmm, that's odd, never seen that one before. That's running the latest version?

**Comment by jgrunzweig** [comment]
Was a weird one-off that resulted from me upgrading versions of BinaryNinja. Corrected once the app was restarted afterwards.
