### ISSUE TITLE
Can't update on MacOS

### ISSUE THREAD

**Issue by Kharos102** [Vector35/binaryninja-api#3091]
Binary Ninja Version: 3.0.3364-dev Personal, 97d0df19
Platform: macOS 12.3

On both intel & M1 based macs, I can't change the update channel for binary ninja.

After opening the change update channel UI, the error "Unable to write to cache" appears in binary ninja's log output and prevents any changing of the update channel (and potentially, any updating).

<img width="679" alt="Screen Shot 2022-04-26 at 8 37 45 PM" src="https://user-images.githubusercontent.com/16039802/165435171-9e3d415e-3745-454c-a22e-b8a645c52c70.png">

**Comment by Kharos102** [comment]
Also note I installed this particular version of binary ninja through the recovery page on the website, and using the download link emailed to me.

**Comment by xusheng6** [comment]
I have run into a similar problem, when I installed BN in once account and tried to update it in another account. Is it relevant here?

**Comment by psifertex** [comment]
I have also run into this and the fix was:
```rm -rf ~/Library/Caches/Binary\ Ninja/update/*```
Unfortunately not sure what causes it.

**Comment by Kharos102** [comment]
I have not changed accounts, and that fix won't work as that folder path "~/Library/Caches/Binary\ Ninja" does not exist...

**Comment by psifertex** [comment]
We've identified the root bug and a fixed dev build should be out shortly (builds >= 3365 will have the fix included). Ironically, the work-around until then is to _create_ that folder instead of removing it, up to and including the "update" folder.  

Or just wait a bit and grab the latest dev. :-)

**Comment by Kharos102** [comment]
That fix (creating the path including the update folder) doesn't fix it for me.

But I'll just wait for an updated version to be available via the license recovery download link I guess

**Comment by psifertex** [comment]
Thanks for confirming! Appreciate you following up.
