### ISSUE TITLE
Incorrect display of some enum values after applying Windows type libraries

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#3093]
**Version and Platform (required):**
- Binary Ninja Version: Version 3.0.3365-dev Enterprise
- OS: macOS
- OS Version: 12.3.1
- CPU Architecture: M1

**Bug Description:**
There's an issue with the Windows type libraries where stuff sometimes looks a little weird with enums. For example, having defined `SetLastError()` as `void  SetLastError(enum WIN32_ERROR)` sometimes leads to stuff like `SetLastError(ERROR_INVALID_PARAMETERDNS_ERROR_RCODE_NO_ERROR)` being shown.

**Steps To Reproduce:**
For example, open `bfsvc.exe` and go to 0x140002f16.

**Expected Behavior:**
Only one of `ERROR_INVALID_PARAMETER` or `DNS_ERROR_RCODE_NO_ERROR` (in the example above) should be shown. Or, perhaps they should both be shown, but with a `|` between them? Not entirely certain.

**Additional Information:**

When 0 is one of the enumeration values, we might not handle it correctly. This also could be a tokenization issue. It shouldn't be an issue related to the type libraries themselves.

**Comment by Stolas** [comment]
[bfsvc.zip](https://github.com/Vector35/binaryninja-api/files/8575592/bfsvc.zip)

**Comment by plafosse** [comment]
Fixed in 3.0.3375
