### ISSUE TITLE
If PDB file can't be loaded, PDB loader prompts user for filename and waits indefinitely when running from headless scripts

### ISSUE THREAD

**Issue by wrffrz** [Vector35/binaryninja-api#3100]
**Version and Platform (required):**
- Binary Ninja Version: 3.0.3370-dev (Build ID 812dad)
- OS: Ubuntu Linux
- OS Version: 21.10
- CPU Architecture x64

**Bug Description:**
When using the PDB loader plugin in a headless script, if a PDB is not available locally and can't be downloaded from symbol server, the process prints out "Select PDB file: " and waits for input indefinitely instead of failing and reporting status to script.  When this happens while processing many files in a script using parallelization, the "Select PDB file:" prompt is lost in the rest of the analysis output and that process stalls until the user hits enter.  There's no indication which PDB file it had attempted to load or which file being analyzed had a missing PDB.

**Steps To Reproduce:**
Here's an example script that can be used to demonstrate this behavior if the symbol-server-list setting is cleared and not all required PDBs are available in the local symbol store:

```
#!/usr/bin/env python3
import os
os.environ["BN_DISABLE_USER_SETTINGS"] = "True"
os.environ["BN_DISABLE_USER_PLUGINS"] = "True"
os.environ["BN_DISABLE_REPOSITORY_PLUGINS"] = "True"
import binaryninja
import glob
import sys
from multiprocessing import Pool, cpu_count, set_start_method

def spawn(filename):
        binaryninja.set_worker_thread_count(1)
        with binaryninja.open_view(filename, update_analysis=False, options={"analysis.mode": "controlFlow", "analysis.linearSweep.autorun": False}) as bv:

                ctx = binaryninja.plugin.PluginCommandContext(bv);
                binaryninja.plugin.PluginCommand.get_valid_list(ctx)[r'PDB\Load'].execute(ctx)

                bv.update_analysis_and_wait()

                exported = bv.get_symbol_by_raw_name("ExportedSymbol")
                print(exported)
                nonexported = bv.get_symbol_by_raw_name("NonexportedSymbol")
                print(nonexported)

if __name__ == '__main__':
        set_start_method("spawn")
        processes = cpu_count()-1 if cpu_count() > 1 else 1
        pool = Pool(processes=processes)
        results = []
        if len(sys.argv) > 1:
                filenames = sys.argv[1:]
        else:
                filenames = glob.glob("/path/to/targets/**/*.exe", recursive=True)
        for filename in filenames:
                results.append(pool.apply_async(spawn, (filename,)))
        output = [result.get() for result in results]
        print(output)
```

**Expected Behavior:**
A failure to load a PDB shouldn't result in the process stalling and waiting for user input when running in a headless script.  Ideally, there would be a mechanism to provide status about if the PDB load succeeded or not to the running script, but that's just a nice-to-have.

**Screenshots:**
Here's an example of what the output looks like when it prompts for a filename after a failed PDB load:

> 2097554437155708683:1147784109806547036 Function warn] Skipping analysis for function at 0xHHHHHHHH : Exceeds 'analysis.limits.maxFunctionSize'
> [12506051600147864506:1849191497379587362 Function warn] Skipping analysis for function at 0xHHHHHHHH : Exceeds 'analysis.limits.maxFunctionSize'
> <FunctionSymbol: "ExportedSymbol" @ 0xHHHHHHHH>
> <DataSymbol: "NonexportedSymbol" @ 0xHHHHHHHH>
> <FunctionSymbol: "ExportedSymbol" @ 0xHHHHHHHH>
> <DataSymbol: "NonexportedSymbol" @ 0xHHHHHHHH>
> Select PDB file: [11556716973402249249:11003870014610074654 Function warn] Skipping analysis for function at 0xHHHHHHHH : Exceeds 'analysis.limits.maxFunctionSize'
> [6519155112955055706:5806481581183227552 Function warn] Skipping analysis for function at 0xHHHHHHHH : Exceeds 'analysis.limits.maxFunctionSize'

**Comment by psifertex** [comment]
So the short explanation here is there's really no core API system being exposed by the PDB plugin so it's a rather weak thing to be able to trigger it from the action manager.

We do plan on re-working the PDB plugin as a DebugInfo API at some point soon for 3.2, but here's a simple work-around you can use in the meantime in your plugin (basically, registering your own dummy interaction handler that overrides the methods to not block -- or you could provide the answer in your script if you want):

```python
#!/usr/bin/env python3
import os
os.environ["BN_DISABLE_USER_SETTINGS"] = "True"
os.environ["BN_DISABLE_USER_PLUGINS"] = "True"
os.environ["BN_DISABLE_REPOSITORY_PLUGINS"] = "True"
import binaryninja
import glob
import sys
from multiprocessing import Pool, cpu_count, set_start_method

class DummyHandler(binaryninja.InteractionHandler):
        def get_open_filename_input(self, prompt, ext):
                return False

def spawn(filename):
        binaryninja.set_worker_thread_count(1)
        dummy = DummyHandler()
        dummy.register()
        with binaryninja.open_view(filename, update_analysis=False, options={"analysis.mode": "controlFlow", "analysis.linearSweep.autorun": False}) as bv:

                ctx = binaryninja.plugin.PluginCommandContext(bv);
                binaryninja.plugin.PluginCommand.get_valid_list(ctx)[r'PDB\Load'].execute(ctx)

                bv.update_analysis_and_wait()

                for symbol in bv.symbols:
                        print(symbol)

if __name__ == '__main__':
        set_start_method("spawn")
        processes = cpu_count()-1 if cpu_count() > 1 else 1
        pool = Pool(processes=processes)
        results = []
        if len(sys.argv) > 1:
                filenames = sys.argv[1:]
        else:
                filenames = glob.glob("/path/to/targets/**/*.exe", recursive=True)
        for filename in filenames:
                results.append(pool.apply_async(spawn, (filename,)))
        output = [result.get() for result in results]
        print(output)
```
