### ISSUE TITLE
Double clicking function names no longer opens disassembly graph

### ISSUE THREAD

**Issue by bmuessig** [Vector35/binaryninja-api#3103]
In previous versions, I could open the disassembly graph for a function in linear view if I just double clicked on it.
This now no longer works. In very old versions, there used to be a context menu entry to open in disassembly graph.
I really hope this comes back, as it makes my experience worse, since my workflow is always interrupted switching views.

Binary Ninja Version: 3.0.3233 Personal, e250d0a3

**Comment by psifertex** [comment]
So you want the graph to be the default view of you navigate no matter what view you started in? Double clicking is (and always has been) the only way to navigate around any symbols. I don't actually remember older versions switching views as we would have considered that a bug. 

I don't know that we will ever implement this as I understand it in the core product but I can write a small plugin that every time you navigate if you changes locations it will automatically switch you to graph view if that's the behavior you are asking about.

**Comment by bmuessig** [comment]
What I would really like to have back is the context menu entry that just allows me to jump from linear view to graph view (or that switching the views would synchronize locations).

**Comment by bmuessig** [comment]
About how it worked previously:
![grafik](https://user-images.githubusercontent.com/2276327/166104973-e12eae50-0c12-4f5c-be78-91a33cce6dbe.png)

You could double click the header to jump to the matching graph view previously. This replaced the context menu entry that did the same thing in version 1.0.

**Comment by psifertex** [comment]
Oh! I understand. Just the header entry but not a function name in the listing itself. It's early for me still. Gotcha. Hmm, I would consider that. I honestly don't even remember that behavior. 😂 

Thanks for clarifying.

**Comment by psifertex** [comment]
You can also hit "space" to do the same thing but adding a context menu is definitely a good idea and  adding back double click header might be reasonable.

**Comment by psifertex** [comment]
After some discussion we're not planning on adding double click back as a way to switch graph/linear view. I suspect if we change it to anything, it would be the "edit function properties" dialog. Hopefully the `space` hotkey works for you, 

If you're interested in a context menu (besides the file / view/graph), let me know and I can re-open this to track that.

Alternatively, if you _really_ want the double click feature, it's possible to build a UI plugin that adds a click handler for the graph and flowgraph views and implements that behavior yourself but it would be a bit hacky and not officially supported.

**Comment by bmuessig** [comment]
I would be totally happy with a context menu version too :)

**Comment by bpotchik** [comment]
Perhaps this is fixed in `3.0.3390-dev`. If you navigate to linear view from graph view via data ref or feature map, you can scroll and double click a function header to navigate to that function in graph view. Before this behavior was present but you were required to double click the function name token. Now you can double click anywhere in the function header.

**Comment by bpotchik** [comment]
Also noteworthy, navigating to Linear/Graph view via the drop down selection in the top left pane did not used to change the graph/linear view preference. This changed around 3 months ago so that this preference is changed, similar to pressing the space bar.
