### ISSUE TITLE
Windows Type Libraries contain pointers to anonymous structures

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#3108]
**Version and Platform (required):**
- Binary Ninja Version: 3.0.3395-dev
- OS: macOS
- OS Version: 12.0.1
- CPU Architecture M1

**Bug Description:**
This issue is not about fixing the underlying bugs (see #3109), but just cleaning the type libraries that trigger them for a hotfix until we can actually address them.

The updated Windows type libraries (as of #2830) contain various types that are pointers-to-structures where the underlying structure is anonymous and contained within the pointer type. While this is constructable with our type system, certain operations do not handle them properly. 

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open this exe: [symupload.exe.zip](https://github.com/Vector35/binaryninja-api/files/8628507/symupload.exe.zip)
2. Open the types view
3. Search for `IUnknown`
4. Observe broken type

**Expected Behavior:**
I expected the typedef to point to a named structure with a full expanded definition in another type, ie
```
struct _IUnknown {
    ...
};
typedef struct _IUnknown* IUnknown;
```

**Screenshots:**
<img width="313" alt="image" src="https://user-images.githubusercontent.com/711973/166858944-e17bc267-50df-4eca-809f-72597f8305b3.png">

**Additional Information**
This is blocking the clang integration merge (#3007)

**Comment by plafosse** [comment]
Fixed in 3.0.3408
