### ISSUE TITLE
make binaryninja.Architecture more pythonic

### ISSUE THREAD

**Issue by gynophage** [Vector35/binaryninja-api#311]
To get a list of supported architectures for binjapython API, you read the list property of binaryninja.Architecture:

`binaryninja.Architecture.list`
`[<arch: aarch64>, <arch: armv7>, <arch: mips32>, <arch: powerpc>, <arch: x86>, <arch: x86_64>, <arch: 6502>]`

Can we support list() of architecture, or perhaps add an iterator? And other such pythonic things?

**Comment by plafosse** [comment]
Some of these are fixed, open bugs for specific issues.
