### ISSUE TITLE
Symbol issue with MIPS ELF's that use _GLOBAL_OFFSET_TABLE_ to set $gp

### ISSUE THREAD

**Issue by loverics** [Vector35/binaryninja-api#3112]
- Binary Ninja Version: 3.0.3395-dev (build id 4289927a)  
- OS: MacOS Monterey  
- OS Version: 12.3.1  
- CPU Architecture: x64  

**Bug Description:**  
I believe this to be a bug and I’ve seen it many times in MIPs elf’s.  

I have a httpd elf file from a MIPS based IoT device. binja isn’t finding all the symbols correctly (specifically `recv`). I think the cause is that `$gp` is being loaded from the global symbol `_GLOBAL_OFFSET_TABLE_` which is set to `0x0`.   

binja finds 3 symbols for recv:  
<ImportedFunctionSymbol: "recv" @ 0x503a70>  
<ImportAddressSymbol: "recv" @ 0x53f018>  
<ExternalSymbol: "recv" @ 0x54eeb0>  

The ImportedFunctionSymbol has 1 code reference which is shown as system but that seems wrong because of `_GLOBAL_OFFSET_TABLE_` isn’t correct. The ExternalSymbol has no code references.  

However, the ImportAddressSymbol recv is in the `.got`  and it has code references. But `get_callers` doesn’t return any callers.

**Steps To Reproduce:**
``` python
syms = bv.get_symbols_by_name('recv')
for sym in syms:
    print(sym)
    for call in bv.get_callers(sym.address):
        print(f'\tcaller: {call}')
```

```
<ImportedFunctionSymbol: "recv" @ 0x503a70>  
    code ref0 ... refN
<ImportAddressSymbol: "recv" @ 0x53f018> 
    [no output] 
<ExternalSymbol: "recv" @ 0x54eeb0>  
    code ref0 ... refN
```

**Expected Behavior:**
1. `get_callers` returns code references possibly for `ImportAddressSymbol` if the below doesn't fix the code references issue.
2. in Linear Disassembly View the `$gp` value needs to be correctly handled. Currently, `_GLOBAL_OFFSET_TABLE_` is used for `$gp` which is `0x0` I think it should be replaced by the address of the `.got`. As a result `$t9` will no longer be `0x0`.

**Screenshots:**
![image](https://user-images.githubusercontent.com/18367903/166991275-1fb4aab4-f864-402e-bd80-cb625ef61003.png)

![image](https://user-images.githubusercontent.com/18367903/166991417-18d3704f-56ac-4651-a85e-a1017f4592d5.png)

![image](https://user-images.githubusercontent.com/18367903/166991526-1cf84fed-f0b3-4ede-a742-ae1ef114e2f7.png)

![image](https://user-images.githubusercontent.com/18367903/166991688-5e6a0a95-92c8-4b6d-b1ba-a0eceb555b91.png)

![image](https://user-images.githubusercontent.com/18367903/166991810-d4ad873b-9bca-44bf-a26b-5cda4f7cae47.png)

![image](https://user-images.githubusercontent.com/18367903/166991944-6788b814-b039-4b42-935e-a6f8d581d5c4.png)

**Additional Info:**
[httpd.tar.gz](https://github.com/Vector35/binaryninja-api/files/8634538/httpd.tar.gz)

**Comment by psifertex** [comment]
Wow, yeah, that looks truly broken:
<img width="716" alt="Screen Shot 2022-05-05 at 5 41 05 PM" src="https://user-images.githubusercontent.com/140215/167030206-f5f75af0-a0e6-496f-bffa-260ba73248cb.png">

**Comment by psifertex** [comment]
Looks like the issue here is there's some weird extra leftover debug info that is basically a broken stub that doesn't get used. You'll want to use the ImportAddressSymbol to get the correct cross-refs:

```
# Iterate over xrefs to `recv`
recvSym = [x for x in  if x.type][0]
for sym in bv.get_symbols_by_name('recv'):
  if sym.type == SymbolType.ImportAddressSymbol:
    for xref in bv.get_code_refs(recvSym.address):
      # Do the thing zhu li
      pass
```
