### ISSUE TITLE
Windows "User Installs" don't get heap performance benefits

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#3116]
We opted into the Segment Heap (see: #2778) in order to get a significant performance boost on Windows. This was implemented by having the installer set the `FrontEndHeapDebugOptions` key during installation.

This works perfectly fine for *system* installs. For *user* installs, however, the Binary Ninja installer sets the registry key in `HKEY_CURRENT_USER` instead of `HKEY_LOCAL_MACHINE` because it doesn't have permissions to access HKLM.

It appears that the HKCU key is never checked (or possibly ignored?) by the loader, which means user installs of Binary Ninja do not get this performance benefit.

One workaround we could possibly add is an extra screen in the installer for user installs that says, "Click this button to install a registry key that gives performance benefits", and triggers UAC to add the HKLM key. That way, the user installer still doesn't require elevated privileges, but there's an easy option for user installs to get the registry key installed.

We could also just point people at this ticket and tell them to go set:

```
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\binaryninja.exe]
"FrontEndHeapDebugOptions"=dword:00000008
```

Ultimately, I feel this is a Windows bug (it really should check HKCU as well during load, unless there's a security concern I'm not aware of). But, it does affect users, and it's an unfortunate problem to have right before a "Performance"-focused release.

**Comment by D0ntPanic** [comment]
The new performance optimizations in 3.1 flip the situation around, and now the segment heap was measured at 68% slower analysis performance. We are instead disabling the segment heap.
