### ISSUE TITLE
Improper pane view switch in some conditions

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#3119]
**Version and Platform (required):**
- Latest dev Macos

**Bug Description:**
Panes can spuriously switch their view.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Split pane
2. Got to right pane and switch to graph view.
3. Left pane will some times switch to graph view too.

**Expected Behavior:**
Views should not be synchronized between panes, only addresses should be synchronized.

**Comment by fuzyll** [comment]
There's something probably related, but maybe different, going on in the ticket I just closed above (#3335) where the display name of the type of disassembly being shown is missing entirely when switching.

**Comment by bpotchik** [comment]
Fixed in `3.2.3819-dev`.
