### ISSUE TITLE
binaryninja.Architecture.assemble pairity

### ISSUE THREAD

**Issue by gynophage** [Vector35/binaryninja-api#312]
To assemble an instruction in binaryninja API, you call Architecture.assemble.

To disassemble an instruction in binaryninja API, you call Architecture.disassemble.

...I'm kidding. You call Architecture.get_instruction_text. Can we get a disassemble alias for get_instruction_text, so it's a bit more intuitive for plugin developers?

**Comment by plafosse** [comment]
The problem is that there is only one way to assemble and multiple ways to disassemble, do you just want the raw text of the disassembly or do you want the tokenized version. We have documentation now explaining the APIs so theres less confusion.
