### ISSUE TITLE
Feature Request: Configure truncation of names 

### ISSUE THREAD

**Issue by clubby789** [Vector35/binaryninja-api#3120]
**What is the feature you'd like to have?**
In all levels (disassembly up to Pseudo C) long names (such as those in Rust or C++) are truncated. I'd like to be able to force these names to be fully displayed, or have the max length before truncation be configurable.
e.g.  `<std::io::stdio::Stdin as std::io::Read>::read::hfa16b0e464caf3bf` is displayed as `<std::io::stdio::Stdin a...d::io::Read>::read::hfa16b0e464caf3bf(&var_7e8, &var_7d8, &var_828, 0x40)`

**Additional Information:**
![image](https://user-images.githubusercontent.com/13556931/167885238-a99d4e3c-b26b-4b7b-adac-3e2ed083ec9f.png)
Names are displayed like this in both Linear and Graph view

**Comment by jonpalmisc** [comment]
See the new "Maximum Symbol Name Length" setting available in builds ≥3441.
![image](https://user-images.githubusercontent.com/41548458/169042969-1b0db434-8122-43ff-88d3-1e2ef5153239.png)
