### ISSUE TITLE
Change type dialog does not default to existing type in linear view

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#3125]
**Version and Platform (required):**
- Binary Ninja Version: 3420-dev
- OS: Windows
- OS Version: 11
- CPU Architecture: x64

**Bug Description:**
When changing the type of a global variable in linear view, the dialog box populates with the last type used, not the current type.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Go to any global variable in linear view
2. Hit 'y' to change the type
3. See the type is not populated with the current value

**Expected Behavior:**
I expect the type dialog to populate with the current value

**Screenshots:**
![image](https://user-images.githubusercontent.com/8716677/168446116-5d7125c4-6018-4c25-ba48-02e6ecdca573.png)

**Comment by jonpalmisc** [comment]
Fixed in builds ≥3427.
