### ISSUE TITLE
XFG causes linear sweep analysis failures on Windows 11 binaries

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#3126]
**Version and Platform (required):**
- Binary Ninja Version: 2.4.3426
- OS: Windows
- OS Version: 11
- CPU Architecture [x64

**Bug Description:**
With the introduction of XFG, linear sweep create a erroneous functions on Windows 11+ system binaries.

**Steps To Reproduce:**
1. Open test.dll
2. Navigate to foo
3. See error

**Expected Behavior:**
There should not be a function created out of the 8 bytes immediately prior to foo.

**Screenshots:**
Before:
![xfg-before](https://user-images.githubusercontent.com/8716677/168487886-f4828aa5-8b91-44b8-b2d2-037baedf00da.png)

After manual fixup:
![xfg-after](https://user-images.githubusercontent.com/8716677/168487883-8297553b-9950-4d2b-921a-e2183c316179.png)

**Additional Information:**
XFG is a type based control flow integrity scheme, where before jumping to any exported or indirect target it will compare the type hash at the call site and the type hash of the destination and bail on error. XFG is enabled by default on Windows 11+ binaries, meaning for any exported or possible indirect call target, there will be an 8 byte hash immediately before the function. This hash is described in detail here: https://blog.quarkslab.com/how-the-msvc-compiler-generates-xfg-function-prototype-hashes.html

The test code in this case is:
```C
#include <Windows.h>
#include <stdio.h>

typedef struct _TEST
{
    DWORD a;
} TEST, *PTEST;

__declspec(dllexport) VOID foo(TEST t)
{
    printf("%d\n", t.a);
    return;
}
```

and it's compiled with `cl /LD /guard:xfg test.cc`.
[test.dll.txt](https://github.com/Vector35/binaryninja-api/files/8695640/test.dll.txt)

**Comment by plafosse** [comment]
Fixed in 3.1.3583
