### ISSUE TITLE
Bookmark/Tags context menu is inconsistent

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#3130]
**Version and Platform (required):**
- Binary Ninja Version: 2.4.3427
- OS: Windows
- OS Version: 11
- CPU Architecture: x64

**Bug Description:**
A bookmark is a subtype of tag, but the top level menu entry is "bookmark", inverting the relationship between the concepts.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Right click
2. See "Bookmark"
3. See error

**Expected Behavior:**
I expect Tags to be the top level entry with Bookmark as a subtype. Alternatively, because there are convenient key binds for bookmarks they could be removed and the entire menu could just be flattened into 'Add Tag'.

**Comment by jonpalmisc** [comment]
Will be fixed in builds ≥3436.
