### ISSUE TITLE
Parameter propagation through simple thunks fails

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#3133]
**Version and Platform (required):**
- Latest Dev

**Bug Description:**
In the included binary Binary Ninja fails to propagate parameters from the a thunk target to its parent:
![image](https://user-images.githubusercontent.com/10556585/169050976-ec156811-ab17-4496-a933-1f0148341ff3.png)

[test_staticlink.exe.zip](https://github.com/Vector35/binaryninja-api/files/8716643/test_staticlink.exe.zip)

**Work around**

The following quick and dirty script will manually propagate through these thunks.
```python
for func in bv.functions:
 if func.name.startswith("j_"):
  targets = bv.get_functions_by_name(func.name[2:])
  if len(targets) == 0:
    continue
  target = targets[0]
  func.function_type = target.function_type
```

**Comment by D0ntPanic** [comment]
Fixed in 3.4.4224
