### ISSUE TITLE
Triage View starts at address 0 and can cause crashes

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#3136]
**Version and Platform (required):**
- Binary Ninja Version: 3.0.3444
- OS: macOS
- OS Version: 12.0.1
- CPU Architecture M1

**Bug Description:**
When opening binaries with Triage view as the default, the current address starts at 0x0 and trying to change its display can cause crashes.

**Steps To Reproduce:**
1. Enable the settings triage.preferSummaryView and triage.preferSummaryViewForRaw
2. Open an exe
3. Observe current address (in status bar) is 0x0
4. Click current address status bar menu and switch to Segment Offset
5. Observe crash
6. BONUS: Crash persists because it saves your preference

**Expected Behavior:**
I expected multiple things:
- If I open triage view on a non-raw binary, it defaults the address to somewhere within the mapped binary. Probably bv.start
- Even if I'm not at an address in a mapped segment, the product should not crash

**Additional Information:**
I used ntoskrnl.exe as a test case, but this likely works with any binary file.

**Comment by negasora** [comment]
Fixed in 3.1.3553-dev
