### ISSUE TITLE
Add zoom-to-fit and zoom-to-mouse hotkeys

### ISSUE THREAD

**Issue by amtal** [Vector35/binaryninja-api#3138]
Large CFGs need a larger graph overview/minimap. Rather than wasting screen space on the overview, why not have two adjacent hotkeys: one zooms out the current graph view such that entire CFG is visible, the other zooms in to 100% at the mouse cursor.

The resulting workflow (zoom to fit to get a minimap-style overview, identify and mouseover area of interest, zoom to it) is a bit slower than glancing at a minimap then clicking/dragging around until you're roughly where you want. It should however be faster than bringing up the minimap, doing the navigation, then bringing back xrefs/whatever was in the minimap's place. 

It would be particularly useful in the presence of block highlighting plugins.
Animated zoom may or may not be needed to retain spatial awareness.
Oh, could mouse wheel zoom sensitivity also be a setting?

**Comment by plafosse** [comment]
"Zoom to Fit" and "Zoom to Cursor" implemented in 3.1.3635
