### ISSUE TITLE
Separate instruction token from padding token in x86

### ISSUE THREAD

**Issue by gynophage** [Vector35/binaryninja-api#314]
`binaryninja.Architecture["x86"].get_instruction_text("\x58", 0)`
`(['pop     ', 'eax'], 1L)`

Why are there so many spaces in the first element. I understand in the UI that you guys do formatting to line up the arguments, but why does it get returned in the get_instruction_text? Is there a way to just get the instruction name without calling strip() all the time?

**Comment by plafosse** [comment]
Fixed
