### ISSUE TITLE
Filtering symbol list with spaces is weird

### ISSUE THREAD

**Issue by negasora** [Vector35/binaryninja-api#3146]
The symbol list filter treats filter strings with spaces as multiple individual filters that get applied sequentially
eg. Filtering for `a g` will match `this is a string`

String filtering also behaves this way

**Comment by negasora** [comment]
This behavior should be in the docs somewhere if it's not already

**Comment by psifertex** [comment]
That's fair. Here's some text we can throw in https://docs.binary.ninja/getting-started.html#symbols-list

```Filter search boxes on items such as strings and lists work on a fuzzy match with each space-separated word being its own search term. This is convenient for, for example, searching for the first letter in multiple words. Or searching for an offset when the offset occurs as a substring in a larger string.```
