### ISSUE TITLE
Newly-created BNDBs do not save in place until close & restart

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/binaryninja-api#3148]
1. Open a binary
2. Use the "Save" action to save a database
3. Run the same "Save" action again
4. Notice you are prompted for a save location again rather than saving in-place

This will occur on every save attempt until the database is closed and reopened.

**Comment by xeysz** [comment]
I'm seeing this behavior as well on this configuration:

Binary Ninja Version: 3.1.3469 Personal, 93650e26
Platform: macOS 12.5

**Comment by bpotchik** [comment]
This appears to be fixed on the latest dev build and has probably been fixed for a while. Tried on `3.1.3605-dev`.
