### ISSUE TITLE
binaryninja.Architecture.get_instruction_* inconsistent error returns.

### ISSUE THREAD

**Issue by gynophage** [Vector35/binaryninja-api#315]
get_instruction_\* return inconsistent values on error cases.

x86, x86_64, mips32, and armv7 return '' on an invalid instruction.
powerpc returns "undef", unless it's not a multiple of 4. Invalid instruction lengths return None. This behavior is mirrored by mips32 and armv7.

**Comment by plafosse** [comment]
Since powerpc doesn't exist currently I'm marking this one as closed and we'll make sure powerpc returns the correct value. Right @lwerdna?
