### ISSUE TITLE
Remember the window position and size of Create Types / Change Type dialogs

### ISSUE THREAD

**Issue by alexrp** [Vector35/binaryninja-api#3159]
**What is the feature you'd like to have?**
Related to #3158, it would be great if these dialogs could also remember their window position and size. For any non-trivial type definition, I consistently find myself resizing the window.

**Are any alternative solutions acceptable?**
Resizing the window manually whenever I need to create/edit large type definitions.

**Comment by psifertex** [comment]
Added in builds >= 3610
