### ISSUE TITLE
Ability to unload (or avoid loading) type libraries

### ISSUE THREAD

**Issue by alexrp** [Vector35/binaryninja-api#3161]
**What is the feature you'd like to have?**
I'd like a way to unload type libraries, e.g.:

```python
for tl in bv.type_libraries:
    bv.remove_type_libraries(tl)
```

**Is your feature request related to a problem?**
There are a variety of issues with how Binary Ninja imports types from type libraries right now. For example, COM-related definitions are all kinds of wrong: Incorrect pointer levels, missing `this` parameters in vtables, no handling of vtable inheritance, etc...

I'm sure these issues will be addressed in time, but in the meantime, I need to be able to fill in the types myself without having to fight Binary Ninja because I'm stepping on its toes when I define a type that has a name found in a type library.

**Are any alternative solutions acceptable?**
An option to not load type libraries in the first place when loading the binary would also be sufficient.

**Comment by plafosse** [comment]
If you could provide a specific example of a type which is wrongly defined that would be very helpful.

**Comment by alexrp** [comment]
Is there any chance this might be addressed anytime soon? It'll of course take time to squash all the bugs associated with turning Win32 metadata into correct BN types, but I still find myself having to fight BN when it has incorrect/incomplete definitions for e.g. COM interfaces.

The Types view has a number of odd quirks when you try to edit/overwrite types coming from type libraries, and even when you manage to do so, you'll get strange warnings in the console at times because (I presume) BN gets confused when it expects to find a type in a type library but the user has overwritten it.

Even a super simple option to just disable loading of *all* type libraries when opening a binary would be a sufficient solution for me (I don't mind having to fill in Win32 types myself).

**Comment by psifertex** [comment]
We have a test branch in progress right now that loads them on-demand.  Adding a setting along with that change to not load should be trivial. I think our expectation for the original issue was a more granular ability to load only some. A simple on/off would be easy, thanks for letting us know again it's causing you an issue.   

I don't know the overall timeline on the feature branch, highlighting Josh here to ask. 

Cc: @negasora 

If it's not close we can just land a quick setting.

**Comment by alexrp** [comment]
Hey @negasora, just wanted to check in on the above?

**Comment by negasora** [comment]
It got batched in with a larger changeset, but should be getting merged today

**Comment by negasora** [comment]
The setting `platform.autoLoadTypeLibs` is added in 3.2.3880-dev
