### ISSUE TITLE
New tab page has rendering glitches

### ISSUE THREAD

**Issue by inaryart** [Vector35/binaryninja-api#3165]
**Version and Platform (required):**
see image

**Bug Description:**
Lines of text are messed up

**Steps To Reproduce:**
start demo

**Expected Behavior:**

**Screenshots:**
![image](https://user-images.githubusercontent.com/51652878/171770939-fd3e5023-992f-4899-b032-a84c64888ea0.png)

**Additional Information:**

**Comment by jonpalmisc** [comment]
Alternate (non-deterministic) repro steps:

1. Open fresh BN or new tab
2. Scroll slightly (for good luck? seems to help...)
3. File > Open with Options
4. Select and confirm file in system file picker
5. When the options dialog opens, click cancel
6. Observe overlapping recent files lists

**Comment by cxnder** [comment]
This also happens when non-deterministically but pretty reliably when refreshing the theme

**Comment by bpotchik** [comment]
Fixed in `3.1.3692-dev`.
