### ISSUE TITLE
Submenus should not be clickable

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/binaryninja-api#3199]
The "Copy As" submenu (and many others like it) can be clicked, which closes the menu and has no action. This shouldn't be possible, clicking on submenus should do nothing and keep the menu open.

![image](https://user-images.githubusercontent.com/41548458/173881527-50ca2206-ae28-43d6-ac57-32a3ceb908a7.png)

**Comment by jonpalmisc** [comment]
Briefly looked into this yesterday and didn't learn much about /why/ it happens, but can confirm that other Qt apps experience this, namely:
- Ableton Live 11
- IDA Pro
- Qt Creator/Designer/Linguist

This may just be a Qt thing but still needs more investigation.

**Comment by D0ntPanic** [comment]
Fixed in 3.6.4568
