### ISSUE TITLE
Unable to open linux kernel .o and .ko files

### ISSUE THREAD

**Issue by r3dey3** [Vector35/binaryninja-api#320]
Attempting to open an intermediate .o file or .ko module from the Linux kernel fails with:

Function entry point x86_64:0x0 is invalid

**Comment by psifertex** [comment]
Dupe of #63.

**Comment by tridentsx** [comment]
I am trying to open arm .ko files and the analyzer fails and I dont get any data in dissaessmbly view. Attached is a sample .ko file that is failing on the newly bought (today) binaryninja.


[ext3.zip](https://github.com/Vector35/binaryninja-api/files/2749803/ext3.zip)

**Comment by plafosse** [comment]
@tridentsx unfortunately these changes haven't made it into the Stable build yet. You'll need to switch to the development build > v1.1.1345 This can be done using the version switcher in the preferences menu option.
