### ISSUE TITLE
Collaboration with the debugger to add heap and stack view and edit with IL support.

### ISSUE THREAD

**Issue by st1064870** [Vector35/binaryninja-api#3202]
**What is the feature you'd like to have?**
I think it would be perfect to have IL support connected with the debugger to provide heap and stack view and edit. This could be implemented as two separate windows one for the "Stack Viewer/Editor" and one for the "Heap Viewer/Editor" with will sync with the level of IL view that is selected at each time. I have mentioned this also in the debugger issues but I mention it also here because the support for the heap and stack recognition/analysis/editing in my opinion should be added to the core itself and the debugger should only provide an interface/gui for this

**Comment by fuzyll** [comment]
Can you describe what you're looking for a little bit more? We already have a stack view that lets you view and edit types, and you can already do this with the debugger attached. In the memory view you can apply types as well. I'm just having a hard time understanding specifically what workflow you want us to support. Do you have an example you could walk me through?

**Comment by st1064870** [comment]
No I'm not talking about types. Imagine debugging a program and at some point I want to edit a stack byte and change its value *at runtime*. Theoretically, this can be done with the lldb using the `memory write` command. I was wondering if a ui could exist for such purpose to make such a process very simple. For me the ideal solution would be to adding a column with tracking the values of the stack variables in the Stack View and offer the user the ability to edit them. ![image](https://user-images.githubusercontent.com/61602820/175813663-fffe19d9-8828-4b5c-8e3c-d91c865c1e96.png)

**Comment by xusheng6** [comment]
Is this related? https://github.com/Vector35/debugger/issues/197#issuecomment-1166946394

**Comment by xusheng6** [comment]
We have not decided whether to show live value of the stack variables in the stack sidebar. Right now, I feel like using the linear view is a more straightforward approach. It is not very super convenient at the moment, but I will add some shortcut to make it easier to switch to the stack in linear view

**Comment by plafosse** [comment]
Closing in favor of https://github.com/Vector35/debugger/issues/197#issuecomment-1166946394
