### ISSUE TITLE
Ability to have two sidebars

### ISSUE THREAD

**Issue by alexrp** [Vector35/binaryninja-api#3204]
**What is the feature you'd like to have?**
It would be nice if there was a way to add an extra sidebar. Since I rarely use split panes, on my 21:9 monitor, a lot of screen real estate is wasted:

![image](https://user-images.githubusercontent.com/44076/174199180-d9c4cc38-2269-45ee-be41-52ea80bfca24.png)

It would be fantastic if there was a way to add an extra sidebar so e.g. I could have Symbols and Cross References on the left and Types on the right.

**Comment by psifertex** [comment]
Typed and Strings were left as full views in addition to sidebar panels so you can already do exactly this. Split the pane and then make the new pane be the type view. 

We explicitly do not want to add the additional complexity of dual sidebar and since there's an existing workflow that solves this issue, I'm going to close this as won't fix for now.

**Comment by alexrp** [comment]
@psifertex I've tried working with a Types pane for a bit, and as far as I can tell, there are two issues with this approach that make it not ideal:

* Double-clicking a type still navigates to it in the sidebar's Types view, even if I'm in the Symbols view. I'm reversing a binary with a vast amount of types, so I need the ability to quickly navigate to a relevant type. This issue alone effectively forces me to use the sidebar's Types view.
* There seems to be no way to temporarily hide the Types pane, meaning I'd have to close it and then later open a new pane and switch it to Types again. This is a relatively minor issue next to the previous one, though.

**Comment by psifertex** [comment]
The ability to navigate the appropriate view (pane or sidebar) based on what is open when clicking a type is a good one and should definitely be filed. I can reopen this issue and wedit the description and title or you can open a new one whichever you prefer. 

The second I'll have to think about.  Not sure the right solution. Could make a new action to open a particular view in a pane or re-open last closed pane maybe. 🤔
