### ISSUE TITLE
DWARF Import

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#3206]
We [started](https://github.com/Vector35/binaryninja-api/tree/dev/rust/examples/dwarfdump) to create a rust plugin that could use the DebugInfo APIs to parse dwarf information (indeed, it's what DebugInfo was designed for) but it was not completed. The [current plugin](https://github.com/Vector35/dwarf_import) has a number of limitations that would be eliminated by finishing this plugin.

**Comment by KyleMiles** [comment]
This is currently disabled by default. To enable the new plugin, enable the setting `corePlugins.dwarfImport`:
<img width="632" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/7171118/092e2147-8219-4af8-8b8f-53b8f8ebdff9">

**Comment by fuzyll** [comment]
Reopening this as I'm continuing to have crashes on a lot of things I'm putting through it and we were hoping to be able to have this turned on by default for the upcoming 3.5 release.

We can close this again once we've got unit tests committed and have run this across a reasonable corpus of inputs. I believe we'll also need some documentation for how to use this with #3643.

**Comment by KyleMiles** [comment]
Documentation exists [here](https://docs.binary.ninja/guide/debuginfo.html). I've now run this on all the debug files in the Debian corpus (~1TB of files), with no crashes. Parsed ~0.5B Types/Functions/Data Vars.

**Comment by psifertex** [comment]
I think the only remaining task should be the unit test and it's good to enable by default on dev and close.

**Comment by KyleMiles** [comment]
We talked about this over Slack, but just putting it here as well that there are unit test.

**Comment by KyleMiles** [comment]
The last thing holding this issue open is a round-trip unit test with our DWARF Export plugin, which is blocked by the issue just above, #4700.

**Comment by KyleMiles** [comment]
I worked around #4700 by shelling out to a subprocess. Would still be nice to fix that, but the round trip unit test is now in and I believe we can consider this issue closed.
