### ISSUE TITLE
Navigate to type in pane rather than sidebar if a pane is in the Types view

### ISSUE THREAD

**Issue by alexrp** [Vector35/binaryninja-api#3208]
Double-clicking a type still navigates to it in the sidebar's Types view, even if the Symbols view is currently open in the sidebar and a Types pane is open.

See comments in #3204 for more context.

**Comment by op2786** [comment]
I think this is fixed by #3579.

**Comment by psifertex** [comment]
Yeah, I think we missed this as a duplicate. Thanks for catching it. Feel free to re-open @alexrp if I've missed it.
