### ISSUE TITLE
Register Highlighting for 8 & 16 bit

### ISSUE THREAD

**Issue by osardar** [Vector35/binaryninja-api#321]
Might be a personal preference, but I believe R/EAX should be highlighted when either AX/AH/AL is selected.  Should also be true for the other GPRs.  Having it be the default, with an option to disable it might be the best solution here?  Thanks!

**Comment by shuffle2** [comment]
Yes, IDA supports the same, and allows processor module to define which registers should be related.

**Comment by KyleMiles** [comment]
Resolved in 1.1.1448-dev
