### ISSUE TITLE
Enum member names are not used in some bitwise operations

### ISSUE THREAD

**Issue by alexrp** [Vector35/binaryninja-api#3211]
**Version and Platform (required):**
- Binary Ninja Version: 3.1.3519-dev
- OS: Windows
- OS Version: 10.0.25136.1000
- CPU Architecture: x64

**Bug Description:**
BN currently handles simple assignments of flags fine:

![image](https://user-images.githubusercontent.com/44076/174466942-5c8a3f77-a475-41cb-8342-9c5f5a483196.png)

Enum member names are not used in checks, however:

![image](https://user-images.githubusercontent.com/44076/174466967-40e554ff-0ef1-4a3f-a97f-c8d34979c1ce.png)

Additionally, patterns like this are not handled:

![image](https://user-images.githubusercontent.com/44076/174467041-6c0ea82e-df4a-4e7d-9163-faa79af17336.png)

**Comment by psifertex** [comment]
On my phone so I don't have the issue number handy but I believe this is a duplicate of one already scheduled for this release.

**Comment by alexrp** [comment]
Ah, I missed that one when searching somehow. Closing this then.
