### ISSUE TITLE
Ability to toggle user changes in Binaryview

### ISSUE THREAD

**Issue by elbiazo** [Vector35/binaryninja-api#3214]
**What is the feature you'd like to have?**

I would like to see a way to differentiate user changed things that can effect the ILs.
It will be nice if I can toggle view (changed vs unchanged) as well as have some kind of special tag that cant be deleted

examples:
1. when you change uidf, it might effect graph view
2. If you patch some instruction, it might effect graph view

**Is your feature request related to a problem?**

It is a problem when you change things to a binary and eventually forget what you have done.

**Are any alternative solutions acceptable?**

Currently, what i do is tag the binary and take notes somewhere else. If I really need to see the original, i would just open a new bv.

**Comment by fuzyll** [comment]
Thanks for the feature request! I think #2070 should cover most of what you want from this. I'm going to close this ticket in favor of that one. If, when we have that implemented, your use-case is still not covered, let's revisit this in a new issue with more specifics.
