### ISSUE TITLE
Add an API for getting more specific version information

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#3215]
Needing to do something like `int(core_version()[4:][:4])` or `core_version().split(".")[1]` to get parts of version information feels bad. In particular, it would be great to have an API that lets you request the build number, since that's often the best way to alter functionality based on changes to the API or UI. But, being able to get major/minor and channel might be useful as well in other circumstances.

**Comment by verylazyguy** [comment]
like how python has 
```
>>> sys.version
'3.9.13 (main, May 24 2022, 21:28:12) \n[Clang 12.0.0 (clang-1200.0.32.29)]'
>>> sys.version_info
sys.version_info(major=3, minor=9, micro=13, releaselevel='final', serial=0)
```

**Comment by psifertex** [comment]
Exactly like that. I'm smelling a `core_version_info` property.

**Comment by negasora** [comment]
`core_version_info()` added in 3.1.3545-dev
