### ISSUE TITLE
Wrapper around machine code instructions

### ISSUE THREAD

**Issue by krx** [Vector35/binaryninja-api#322]
Right now when you iterate through a `BasicBlock`, the instructions are just the tuples returned by `Architecture.get_instruction_text`. Can we instead have an `Instruction` wrapper similar to `LowLevelILInstruction` that contains the instruction text, address, length, etc?

**Comment by svv232** [comment]
The DisassemblyTextLine also does not contain a size field. It feels a bit verbose to use `bv.get_instruction_length()` per address. I'm currently trying to pull instructions sequentially in byte form and I think it would be a huge improvement for the overall api if the user could get instruction size and instruction address from the same object.

**Comment by plafosse** [comment]
We have no plans to implement this. Soon we will be releasing our Architectures open source and we will consider this issue obviated.
