### ISSUE TITLE
Make creating selections easier

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/binaryninja-api#3221]
It is currently awkward to create large selections. Lots of scrolling is involved. An "extend selection" action which allows the user to define selection bound(s) would be useful.

Example workflow 1:

1. Navigate to the start of a section X
2. Run "extend selection", provide the address or name of the next section in the dialog
3. Selection now encompasses the entirety of section X

Example workflow 2:

1. Navigate to the start of section X
2. Run "extend selection", enter "+1024"
3. Selection grows by 1024 bytes

**Comment by xusheng6** [comment]
Duplicate of https://github.com/Vector35/binaryninja-api/issues/3260
