### ISSUE TITLE
Feature: Set value of global register

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#3223]
**What is the feature you'd like to have?**
On some architectures (eg PPC), certain registers are considered "Global" (eg r2) and are not considered by dataflow. There should be a way to set these registers to a constant value at the start of a function, considering they do not have variables created which you can use Set User Variable Value on.

**Is your feature request related to a problem?**
I wanted to reverse a PPC binary and my HLIL is full of `-1234(r2)` with no way to tell binja what r2 should be.

**Are any alternative solutions acceptable?**
Could do a more general approach of "set _any_ register to a PossibleValueSet at start of function"

**Additional Information:**
Binary available upon request

**Comment by fuzyll** [comment]
This was completed at some point between 4.1 and 4.2, although we currently only allow a single global register. Support for multiple is tracked now by #6096.
