### ISSUE TITLE
Creating data tags doesn't refresh current view

### ISSUE THREAD

**Issue by SensorLock** [Vector35/binaryninja-api#3228]
**Version and Platform (required):**
- Binary Ninja Version: 3.1.3478-dev, 3.0 (not a new issue)
- OS: Windows
- OS Version: 11
- CPU Architecture: x64

**Bug Description:**
I'm adding tags at addresses with bv.create_auto_data_tag, and if a tag is added to the function currently displayed in the UI it does not redraw to show the tags until the user clicks away and comes back to the function.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Execute python bv.create_auto_data_tag(0x1234, bv.tag_types['Bugs'], "foo"), using an address within the current function UI view. (I had a MLIL view open.)
2. Observe the view didn't change to show the bug icon.
3. Switch the view to a different function, then switch back.
4. Observe the bug icon present on the address now.

**Expected Behavior:**
Behavior should go directly from step 1 to 4 in the above sequence, or there should be an API to force a redraw.

**Additional Information:**
Affects user_data_tags as well.

**Comment by plafosse** [comment]
Tested in 4.2 and it seems to work fine now
