### ISSUE TITLE
Malformed IL causing flags analysis to fail

### ISSUE THREAD

**Issue by D0ntPanic** [Vector35/binaryninja-api#323]
Flags resolution is causing invalid IL to be emitted, which causes some conditionals that should be resolved to be invalid.

Test case was /bin/ls from Ubuntu 16.04

![screen shot 2016-06-30 at 8 37 56 pm](https://cloud.githubusercontent.com/assets/7007406/16508666/38572f62-3f03-11e6-9479-58a50c4a4a7c.png)

**Comment by psifertex** [comment]
Fixed either by the medium level IL push or some other push prior to now.
