### ISSUE TITLE
parsing 'const' seems to be broken when using clang parser

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#3231]
**Version and Platform (required):**
- Binary Ninja Version: 3.1 dev using clang parser

**Bug Description:**
Navigate to a char const array
<img width="440" alt="image" src="https://user-images.githubusercontent.com/10556585/177040110-39ca9569-47ed-4a22-ba1c-8e2b3fbf77e6.png">
hit `y`
<img width="426" alt="image" src="https://user-images.githubusercontent.com/10556585/177040122-b1f641a7-c478-4b99-bd84-e4717c75f03d.png">
hit `enter`
<img width="354" alt="image" src="https://user-images.githubusercontent.com/10556585/177040140-0a133c3b-1ee4-41b3-917f-73a0baa27a6d.png">

**Comment by CouleeApps** [comment]
This makes a const array of const chars, which prints weirdly (char const const [10]) but doesn't affect functionality or analysis-- it just looks weird.

**Comment by CouleeApps** [comment]
This will be fixed in dev >= 3.1.3723
