### ISSUE TITLE
`*` hotkey should suggest a size for the array based upon next DataVariable or end of Section/Segment

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#3254]
When you hit `*` hotkey on a variable it should look for the next DataVariable or end of Section/Segment and suggest an array size that would fill that region.

**Comment by galenbwill** [comment]
Suggested enhancements:
1. if user hits `*` on a thing of type `$type` (with no selection range) and there are a bunch of `$type` things following it, pre-populate the dialog with the range of those same-typed things (might also consider having it offer a "both ways" button so it would work even on a datavar in the middle of a sequence of them). Basically, act the same as if they'd hit `*` with all of the adjacent same-type datavars selected.
2. if a user enters a function name into the type field, use the type of that function for the element type, as if they had entered a function type

**Comment by psifertex** [comment]
Resolves in builds >= 5041
