### ISSUE TITLE
Action to expand selection.

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#3260]
Trying to expand a selection in linear view to a whole section/segment is tedious. It would be helpful if there were actions which could help:

Expand Selection\\To end/start of bv
Expand Selection\\To end/start of section
Expand Selection\\To end/start of segment
Expand Selection\\To end/start of function
Expand Selection\\N Bytes

**Comment by xusheng6** [comment]
Related to https://github.com/Vector35/binaryninja-api/issues/1827

**Comment by xusheng6** [comment]
Added via https://github.com/Vector35/binaryninja-api/commit/015314d34d073a8ebbd958edf8150a81381f12c2, should be available in dev 4.1.5260
