### ISSUE TITLE
Swapping system theme on macOS breaks application color scheme

### ISSUE THREAD

**Issue by cxnder** [Vector35/binaryninja-api#3265]
**Version and Platform (required):**
- Binary Ninja Version: 3.1
- OS: MacOS
- OS Version: >=10.14 (Mojave)
- CPU Architecture: *

**Bug Description:**
When swapping the system color theme (Dark -> Light or Light -> Dark), Qt tries to automatically swap color pallets for the program, but is only partially successful, resulting in a really strange, broken-looking BinaryNinja

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open BinaryNinja
2. Swap system theme in macOS' Settings panel

**Additional Info:**
Not reproducible on Windows 10 or 11 by swapping system theme.

**Comment by D0ntPanic** [comment]
No longer breaks when switching themes as of build 3567.

The theme will not be updated when changing system themes. See bug #1909 for the automatic switching feature.
