### ISSUE TITLE
Show contents of `bv.libraries` in TriageView

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#3266]
The contents of `bv.libraries` is shown at the top of linear view but not in Triage View.

**Comment by psifertex** [comment]
Maybe replace the imports with a tree view with that info?

**Comment by plafosse** [comment]
Added in 3.1.3713

@psifertex the information about which imports belong to which library explicitly doesn't exist so its not really possible.

**Comment by psifertex** [comment]
Note that this feature also implements whether or not each library has applied type information. This is visible in the UI based on the color of the entry on the import list.
