### ISSUE TITLE
Small negative numbers sometimes show up as large positive numbers when they shouldn't

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#3269]
Small negative numbers sometimes show up as large positive numbers sometimes:

At LLIL it looks correct:

![image](https://user-images.githubusercontent.com/10556585/178295464-716e0bc3-7e18-43b4-9e1b-4c8927d56a33.png)

But at HLIL its showing wrong:

![image](https://user-images.githubusercontent.com/10556585/178295052-56ba2f77-b494-46e8-818c-81d9c8227186.png)

**Comment by fuzyll** [comment]
Does anyone have specific test cases for this?

**Comment by CouleeApps** [comment]
Possibly related: https://github.com/Vector35/binaryninja-api/issues/2237

**Comment by plafosse** [comment]
I don't think this is happening anymore as of at least 4.0
