### ISSUE TITLE
Auto analysis edge cause allocating all of the memory

### ISSUE THREAD

**Issue by D0ntPanic** [Vector35/binaryninja-api#327]
There is an edge case that is causing very fast allocation of all of memory trying to analyze one function.  Closing the file does successfully abort the analysis and stop the allocations, but will cause the machine to run out of memory if left alone.

Test case:
[mem_exhaust.zip](https://github.com/Vector35/binaryninja-api/files/344842/mem_exhaust.zip)

**Comment by r3dey3** [comment]
I was able to reproduce this (or at least something similar) by loading a super simple program compiled statically with glibc on Ubuntu 15.10

**Comment by D0ntPanic** [comment]
Fixed in dev. These cases are caused by unusually large functions (in this case, over 20,000 basic blocks). We now avoid running data flow on these functions. Disassembly and IL viewing are still fully available, but jump table resolution will not occur inside these giant functions. We will increase the function size limits for the full analysis as we improve analysis performance.
