### ISSUE TITLE
get_var_uses sometimes doesn't detect variable uses

### ISSUE THREAD

**Issue by RLS-Rylan** [Vector35/binaryninja-api#3277]
**Version and Platform (required):**
- Binary Ninja Version: 3.1.3560-dev
- OS: MacOS
- OS Version: Monterey 12.3.1
- CPU Architecture x64

**Bug Description:**
`get_var_uses` fails to find any uses of `var_58` in the following code snippet
![Screen Shot 2022-07-13 at 1 32 17 PM](https://user-images.githubusercontent.com/100705943/178795297-5dd13b47-89ca-46e0-984c-5fb18c3e5436.png)

```python
>>> list(current_mlil.instructions)[3]
<mlil: rdi = &var_58>
>>> var_58 = list(current_mlil.instructions)[3].vars_read[0]
>>> var_58
<var void var_58>
>>> current_mlil.get_var_uses(var_58)
[]
```

Definitions and uses of other variables in the same binary can be found via this API, so this issue seems to be unique to this variable.

**Steps To Reproduce:**
1. Download and unzip [naughty_elf.zip](https://github.com/Vector35/binaryninja-api/files/9104698/naughty_elf.zip)
2. Open `printf_tests` in Binary Ninja
3. Run the following lines of code:
```python
>>> mlil_func = bv.get_functions_containing(0x826)[0]
>>> var = list(mlil_func.instructions)[3].vars_read[0]
>>> mlil_func.get_var_uses(var)
```

**Expected Behavior:**
`mlil_func.get_var_uses(var)` should return a list with two instructions which use `var_58` - `[rdi = &var_58, rdi_1 = &var_58]`

**Comment by RLS-Rylan** [comment]
Are there plans support querying for variable references in the future? 
I'm happy to put in a new ticket and label it as an enhancement if that will be easier to track.

**Comment by plafosse** [comment]
There is also `current_function.get_mlil_var_refs(var)` if you need to find out the where the variable is being referenced. Is there still some other API you need?

**Comment by RLS-Rylan** [comment]
I must have missed that function, thanks for pointing it out!

`current_function.get_mlil_var_refs` should work fine for my use case.
