### ISSUE TITLE
removed get_next_disassembly function

### ISSUE THREAD

**Issue by hyuunnn** [Vector35/binaryninja-api#3279]
![286D9740-D449-4A2A-83DE-4245E0D5DF4F](https://user-images.githubusercontent.com/15611739/179126336-a5efba40-6255-40ad-ac17-b8177d81dc65.png)

The example explains the function, but there is no implemented code.

![843B0019-19A2-497B-A55E-1A352F09832C](https://user-images.githubusercontent.com/15611739/179126968-f911ac66-0df3-4abd-a024-d0f44b2fae62.jpeg)

This is the function used in the Hyara plugin. (https://github.com/hyuunnn/Hyara/blob/master/hyara_lib/integration/bn_hyara/binaryninja_api.py)

**Comment by psifertex** [comment]
Apparently I closed #3279 but missed this one. Was resolved back in July.
