### ISSUE TITLE
Unable to load PDB with non matching GUID

### ISSUE THREAD

**Issue by Kaioru** [Vector35/binaryninja-api#3281]
**Version and Platform (required):**
- Binary Ninja Version: 3.1.3561-dev (if version is stable, please also test the latest development build via the "Update Channel" option)
- OS: MacOS
- OS Version: Monterey 12.4 (21F79)
- CPU Architecture: M1

** Also tested on a Windows 10 x64 machine.  **

**Bug Description:**
Unable to load PDB when executable is not compiled with /debug flags, or when GUID does not match between the PDB and .exe file.

**Steps To Reproduce:**
1. Load an .exe file not compiled with /debug 
2. Tools > Plugins > PDB > Load PDB is greyed out

**Additional Information:**
There was discussion on Slack on this topic and the consensus was to have this allowed and display a warning for the user.

**Comment by psifertex** [comment]
Thanks for the issue. I know this request has come up before but I don't see it as currently tracked. This should be resolved for the next stable release.

**Comment by CouleeApps** [comment]
This is resolved as of 3.1.3718-dev. The automatic PDB loader will check for matching guid + info in the exe, but if you manually choose to load a PDB it will warn you and allow you to load it anyway.
