### ISSUE TITLE
Triage View breaks `here = bv.start + offset`

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#3283]
**Version and Platform (required):**
- Binary Ninja Version: 3.1.3553-dev
- OS: macOS
- OS Version: 10.15.7
- CPU Architecture: x86

**Bug Description:**
When Triage view is set to open by default, you cannot use `here = bv.start + offset` to navigate (even if offset = 0)

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Enable `triage.preferSummaryView`
2. Open a binary
3. Enter in the console: `here = bv.start`
4. Observe "Address 0x10000000 is not valid for the current view"
5. Click address in text and observe how navigation totally works

**Expected Behavior:**
I expected `here = bv.start` to work in all cases

**Comment by xusheng6** [comment]
This happens to be fixed by 7c7ceb899dfd18138584cefc8b79221210cd2e29, in which I did a navigation on the viewFrame, rather than the binary

**Comment by CouleeApps** [comment]
Can confirm, this is fixed. Thanks!
