### ISSUE TITLE
"Navigate to main" should navigate to programmer's main

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#3288]
I think it would be better to navigate into main function which is written by programmer instead of compiler generated one. For example it would be better BN navigates to DllMain instead of _start for DLL's, and into main, WinMain for other binaries. It can also be applied to other binaries for other platforms.

**Comment by galenbwill** [comment]
The navigate-to-main feature is meant to be a very simple convenience. It is meant only to find symbols that exist without waiting for analysis to complete, and without triggering any analysis.

It will attempt to navigate to the symbols in the list specified in the `ui.firstNavigate.names` setting when first opening a binary, and only if the `ui.firstNavigate.enable` setting is turned on.

You can add to the list if you want to navigate to a specific symbol, or disable the feature entirely if you prefer.

Note, however, that there are some cases in which it will not work. Specifically, if the symbol is not defined and pointing to a function after the binary loader completes but before analysis, navigation will not occur. I believe this is actually the case for `WinMain`. From what I understand, however, `DllMain` should be the entry point for DLLs, and so Binary Ninja should already start there upon opening a DLL for the first time.

I'm going to close this as "won't fix", as it is outside the intended scope for this feature.

**Comment by alexrp** [comment]
> For example it would be better BN navigates to DllMain instead of _start for DLL's

These should effectively be the same thing, at least if `DllMain` is not exported (which it often isn't). For example, I know that `EasyHook64.dll` has a non-exported `DllMain`, so its symbol name is lost when compiled. BN correctly navigates to it and names it `_start`, however.

@galenbwill I think there's an argument to be made that when loading a DLL, BN should rename the entry point function (as found in the optional header) to `DllMain` and set its parameters/types accordingly to avoid this confusion.
