### ISSUE TITLE
Type signatures lost after PDB loaded

### ISSUE THREAD

**Issue by kevre91** [Vector35/binaryninja-api#3291]
BN is losing function prototypes after PDB is loaded. I'm using version 3.1.3469.

Before PDB loaded: 

![before](https://user-images.githubusercontent.com/109617473/179805996-fc283030-d740-4107-a290-9b380c4020c4.PNG)

After:
![after](https://user-images.githubusercontent.com/109617473/179806027-3807623b-59d2-4d09-839f-d5e3af16c280.PNG)

**Comment by psifertex** [comment]
Indeed. I _think_ we might already have this being tracked by another issue but it's definitely planned for our 3.2 release so I'm adjusting it to that for now and we'll sort if it's a specific duplicate as PDB improvements are high on our priority list right now.

**Comment by CouleeApps** [comment]
Resolved as of 3.1.3715-dev with the new PDB loader. Symbols that would be created with no types will no longer override existing symbols with types.
