### ISSUE TITLE
Support for blank lines in decompiler output

### ISSUE THREAD

**Issue by kevre91** [Vector35/binaryninja-api#3292]
I can make blank line by entering a comment with a new line and a space character. But it looks something like this in decompiler output:

```
//
//
```

Instead of this weird output, somehow we should be able to put a blank line between some code blocks. For example by CTRL+ENTER? Putting a blank line between some important code blocks makes reverse engineer's eyes more comfortable for understanding what happening in the code, especially in HLIL and Pseudo C view.

**Comment by fuzyll** [comment]
We don't have any plans to implement this at this time. Sorry!

**Comment by kevre91** [comment]
May I ask why? I think that would be a great loss for readability. Imagine that programmers in Vector35 wrote all of BN's code without a single new line. Readability of the output is as important as accurate output, in my humble opinion.

I want to politely insist on this feature. 

At least, what about making it hide double "/" character in empty comments? Because I can make an empty lines by entering a comment with two new line. But it looks ugly in the output.

**Comment by op2786** [comment]
+1

**Comment by psifertex** [comment]
The short summary is the level of effort to implement it given our current architecture versus the potential benefit doesn't justify the effort. We don't think it's a bad idea, just that implementing it currently is more effort than would make sense.

**Comment by kevre91** [comment]
In IDA they solve it like this, if you press ENTER in decompiler window, it puts a new line at current cursor position. But, this is not a new line actually, it is just a comment with only a new line character. So, If a press ENTER 5 times, it is a comment with 5 new line character on each line. But magic is this, IDA does not puts "//" before comment line, if it is a line with only new line character (\n). 

Let's say this is my comment:

```
test
test
(new line here)
test
```

IDA:

```
  // test
  // test

  // test
```

BN:

```
005511df      // test
005511df      // test
005511df      // 
005511df      // test
```

If I put space instead of new line:

IDA:

```
  // test
  // test
  // 
  // test
```

BN:
```
005511df      // test
005511df      // test
005511df      // 
005511df      // test

```

By pressing ENTER I simply put a comment with new line character. And IDA checks my comment line and it see that there is no real comment (only new line, not space, not any string etc..), so it does not puts "//" before that comment line. Therefore it imitates a new line between code blocks.

My question is, why BN can not do this? It already puts "//" in front of comments. Why it can not check comment line? If it is consist of only an empty new line character, then do not show "//" prefix for that comment line and voila, problem solved.

Was I succeed at explain what I mean @psifertex? But, if implementation also blocks on this, then okay, there is nothing to do right now.

**Comment by robert-yates** [comment]
i also agree this would be nice, and in my opinion an extremely simple solution is to just not output // for blank lines in comments.

**Comment by blue-devil** [comment]
Hello;
I think @kevre91 did explain in [this](https://github.com/Vector35/binaryninja-api/issues/3292#issuecomment-1203020125) reply beautifully.

As a reverser I highly need a readable+configurable decompiler output. You know how ghidra's decompile output sucks, on the contrary ida's decompile output meets a reverser's demands(But we know BN will take their place ;).

Like @robert-yates I also want to say that It would be really nice to add this small but helpful feature.

**Comment by CouleeApps** [comment]
Dev versions >= 3.6.4669 contain a setting for "rendering.hlil.newLinesAroundScopes" that will cause blank lines to be added around all if/else/while/for/switch blocks in HLIL and Pseudo-C. Hopefully this can alleviate some of the need for blank lines at arbitrary places.

![image](https://github.com/Vector35/binaryninja-api/assets/711973/537da766-dca8-4644-b35e-b9cad24e9a26)

**Comment by op2786** [comment]
@CouleeApps Thank you for your effort. I don't know OP's opinion but it does not as flexible as I need. It sometimes makes decompiler output more readible, sometimes it does vice versa. We need flexibility. Even when writing a code we loosen the code style when necessary, we should be able to do so in the decompiler output too.
