### ISSUE TITLE
Changing structures by `Y` fails 

### ISSUE THREAD

**Issue by kevre91** [Vector35/binaryninja-api#3294]
**Version and Platform (required):**
- Binary Ninja Version: 3.1.3469
- OS: Windows
- OS Version: 10
- CPU Architecture: x64

I could not edit structures by pressing `Y` in types window. It gives a syntax error if it has a `__packed` string in it.

![bug](https://user-images.githubusercontent.com/109617473/179819379-5a6b1f2f-b164-4bf9-97c2-94e67e0c6783.PNG)

I guess there is another bug, If I remove `__packed` string, this time it gives an error that stating "structure already defined". So, It does not update structure. 

I made another test, this time I've created a structure by pressing `S`, which named `test` with blank size field. Then I pressed `l` and make it unpacked. Afterwards I pressed `Y` and tried to add one `int32_t` field into structure. Like this:

```
struct test
{
    int32_t a1;
};
```

When I press Update button, it does not show any error code but structure in types windows does not changed, so there is no new field named `a1`.

**Comment by fuzyll** [comment]
If you're using 3.1 stable, could you try switching to the `clang` type parser and see if this fixes the issue? (It's in `Settings -> Analysis -> Types -> Type Parser`). Alternatively, you can update to the latest `dev` build where this is now the default.

I _believe_ this is not an issue in the new type parser, in which case we'll be closing this as `wontfix`. We didn't get the new `clang` type parser at an acceptable level before the 3.1 stable release to make it default, but it's definitely the future and we aren't putting any additional effort into the older "Core" type parser at this point.

**Comment by kevre91** [comment]
Switching type parser to `ClangTypeParser` fixed all of them.

**Comment by fuzyll** [comment]
Awesome, thanks! Sorry that we're in kind of a weird limbo state between the two right now, but we'll hopefully have the `clang` parser in really good shape by 3.2 when we switch to it as the default. In the meantime, like I said, you can always try the current `dev` builds if you encounter problems with the `clang` parser on stable.

Closing this now as `wontfix` since we'll hopefully be retiring the old "Core" parser shortly.
