### ISSUE TITLE
Show function prototype for imported functions on hovering

### ISSUE THREAD

**Issue by kevre91** [Vector35/binaryninja-api#3295]
BN shows function preview when hovering on function names. But when hovering on a function that is imported from another library, BN shows hex dump of the import table, I guess. 

Wouldn't be better if BN preview function prototype in this example?

![hover](https://user-images.githubusercontent.com/109617473/179824087-37f9ee9f-e942-4b61-a0ca-d1236df96007.png)

**Comment by plafosse** [comment]
Duplicate of: #1175
