### ISSUE TITLE
BN hangs when it fails to open a URL

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#3298]
In our documentation (https://docs.binary.ninja/guide/type.html#smart-structures-workflow), when I try to open the linked file using the URL: `binaryninja:http://captf.com/2011/gits/taped`, BN hangs. The link seems to be down and no longer valid. However, BN hangs after the failed attempt.

**Comment by psifertex** [comment]
I really need to get that domain up and working, but yeah, a hang is undesirable. Does it timeout eventually? Presumably it needs to be moved to a background thread.

**Comment by psifertex** [comment]
There's a mirror at: [taped](http://54.212.176.14/2011/gits/taped) but I don't control it so we shouldn't update the docs to that we should instead just find another file we can point to.
