### ISSUE TITLE
copy/paste/transform gui

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#33]
_From @psifertex on May 5, 2015 13:56_

Copy/paste/transform is already in gui, just needs the functionality written along with the few modal dialogs

_Copied from original issue: Vector35/binaryninja#10_

**Comment by plafosse** [comment]
This issues is mostly fixed. If people want to add custom transforms they can.

**Comment by galenbwill** [comment]
Sorry to beat a dead ~horse~ issue, but looks like this never got implemented:

- [ ] Unicode transforms

So there is no way to copy/transform as UTF-* from the UI.
