### ISSUE TITLE
MIPS disassembly not working as expected?

### ISSUE THREAD

**Issue by afreeborn** [Vector35/binaryninja-api#330]
I'm seeing different versions of the disassembly in objdump and Binja for a MIPS binary. Is this expected?

Binja:
main
![image](https://cloud.githubusercontent.com/assets/19598523/16606569/946744d2-42fe-11e6-9191-4bce868a71dd.png)

dat_shell
![image](https://cloud.githubusercontent.com/assets/19598523/16606582/b96c1280-42fe-11e6-8af6-39877a946a06.png)

----

objdump (buildroot mipsel version):
main (snippet)
![image](https://cloud.githubusercontent.com/assets/19598523/16606594/dc27e538-42fe-11e6-8a46-6a93f35a5249.png)

dat_shell
![image](https://cloud.githubusercontent.com/assets/19598523/16606606/f43a0c5a-42fe-11e6-968b-3871f87f6c74.png)

stack_bof_01
https://github.com/praetorian-inc/DVRF/blob/master/Pwnable%20Source/Intro/stack_bof_01.c
[stack_bof_01.zip](https://github.com/Vector35/binaryninja-api/files/348998/stack_bof_01.zip)
![image](https://cloud.githubusercontent.com/assets/19598523/16606665/664fd1b2-42ff-11e6-92b8-70db389112b3.png)

**Comment by plafosse** [comment]
Currently we only support big endian MIPS, support of LSB mips is forthcoming

**Comment by maycon** [comment]
Hello,

Any update for `mipsel`? I was excited when read "MIPS Suport" on the v1.1 announcement. But BinNinja still cannot recognize instructions like `bc1t`.

Cheers,
