### ISSUE TITLE
Indicator for wide strings in decompiler output

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#3301]
I think decompiler should indicate a sign about string assignations according to string type. 

![wide_indicator](https://user-images.githubusercontent.com/109607896/179927031-316cebd1-5d1a-4190-9a10-20e7efc898cc.PNG)

In this example "mytestname1234567" is actually a wide string. But I cannot directly understand it from decompiler output. When I hover on it, I can understand it is a wide string from hexdump. Putting a simple L prefix before string could make things better.

**Comment by plafosse** [comment]
Fixed in 3.5.4347
