### ISSUE TITLE
Support setting UIDF in HLIL/PseudoC

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#3306]
**Version and Platform (required):**
- Binary Ninja Version: 3.1.3567-dev
- OS: macOS
- OS Version: 12.0.1
- CPU Architecture: M1

**Bug Description:**
There is no open to Set User Variable Value in HLIL or Pseudo-C views-- you have to do it from MLIL. Considering how many people ignore the MLIL view, I'd bet that a number of users don't even realize this is a feature they can use. This issue is strictly less broad than #2160, and only needs to apply to HLIL_VAR_INIT statements.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open any binary
2. Switch to MLIL
3. Right click the definition site of a variable
4. Observe the ability to Set User Variable Value
5. Switch to HLIL
6. Right click the definition site of a variable
7. Observe the lack of ability to Set User Variable Value

**Expected Behavior:**
I expected this option to be available in HLIL.

**Additional Information:**
I'm on the fence whether this is a bug or feature

**Comment by xusheng6** [comment]
Related to https://github.com/Vector35/binaryninja-api/issues/4289

**Comment by fuzyll** [comment]
Thanks for the report! We believe this should now be fixed in builds >= 3.6.4614-dev.
