### ISSUE TITLE
Dialog for Copy As functionality

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#3309]
Having a dialog for Copy As functionality would make understanding what kind of data will be copied more easier. In this way user can see a preview of data that will be copied. In current situation I've a little bit strugge to understand what is going to be copy into clipboard.

**Comment by psifertex** [comment]
This is an anti-feature in my opinion. The whole point of the current system is each entry gets its own action in the action system which lets you bind each to a dedicated hotkey or trigger them directly through the command palette. 

You could add an additional dialog that also had the functionality you are requesting but that just muddles the UI and makes it even mor le confusing ti have different but related options that do the same thing. 

If you wanted to implement this yourself ada. Python plugin or snippet it would be quite easy but I don't think we have any plans to implement this as a first party feature.
