### ISSUE TITLE
Log highlighting sometimes highlights multiple lines

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#331]
I've noticed that sometimes if I select an error message, it will also select other output lines not part of that log message. In the attached image, you can see that a Python traceback is highlighted, as well as a `log_info` line beneath it. When I originally clicked on the traceback, it actually highlighted two `log_info` lines beneath it; clicking it again only highlighted the traceback message, but then the message beneath it became highlighted on its own with no interaction.

It seems to be easily reproducible, as I have noticed this behavior multiple times with error messages in the console.

<img width="1680" alt="screen shot 2016-07-07 at 12 12 25 pm" src="https://cloud.githubusercontent.com/assets/5834130/16660410/22a77472-443c-11e6-8094-4a5f3929408c.png">

**Comment by plafosse** [comment]
Thanks for the ticket. This is a know issue: #324

**Comment by bpotchik** [comment]
Fixed in build 1.1.1079-dev.
