### ISSUE TITLE
Ability to hide-show code blocks

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#3311]
It can save us from scrolling up and down several times for long code blocks in some functions. 

![vs](https://user-images.githubusercontent.com/109607896/180204031-197d67ef-19b9-4174-a860-dc5d170e224a.gif)

**Comment by fuzyll** [comment]
I believe this would be one of the things covered by #510, but the other issue doesn't mention it explicitly.

**Comment by jonpalmisc** [comment]
Added this to #510. Closing as duplicate.
