### ISSUE TITLE
Default database name should include file extension too

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#3312]
Some applications have a DLL which named same as it's main executable. Let's say I've a two file named **a.exe** and **a.dll** respectively. When I analyze **a.exe** and save a database for it, BN saves a database named **a.bndb**. Then when I try to open **a.dll** for analysis, BN asks me if I want to load database from disk for obvious reasons. I think this behaviour is prone to some annoying results.

**Comment by galenbwill** [comment]
fwiw, this is not entirely accurate: the Existing Database Detection looks for basename.ext.bndb as well as basename.bndb, though it does prefer basename.bndb first.

Note that if they both exist, it will ask about both of them if the user clicks No on the first prompt.

**Comment by negasora** [comment]
Fixed in `3.5.4373-dev`
