### ISSUE TITLE
Navigating back or forward does not highlight function in symbols window

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#3326]
**Version and Platform (required):**
- Binary Ninja Version: 3.1.3469
- OS: Windows
- OS Version: 11
- CPU Architecture x64

**Steps To Reproduce:**
1. Double click a function in symbols windows and see that it gets highlighted in green.
2. Double click on a function from decompiler window and see that the function is gets highlighted and focused in symbols window.
3. Now navigate back by pressing ESC and see that current function is not highlighted and focused.
4. You can also see that navigating forward results the same thing.

**Expected Behavior:**
I expect that current functions highlighted and focused in symbols windows when navigating back and forward.

**Comment by fuzyll** [comment]
I wasn't able to reproduce this on 3.1.3466 (stable) or on latest dev on macOS. I'll try it later today on Windows 11.

**Comment by op2786** [comment]
After navigating back to _start by pressing ESC it still highligts sub_401000.

There is another bug by the way. In the first startup, the first function bn focused which is _start in this example is not highlighed too.

![bug](https://user-images.githubusercontent.com/109607896/182307669-b09bb06b-b292-4167-8aff-6f843c358e9c.gif)

**Comment by fuzyll** [comment]
This repros for me on 3.1.3572-dev on Windows 11. @psifertex says it repros on macOS as well for both stable and dev, so I'm not sure what I was doing differently before.

**Comment by plafosse** [comment]
Oh heh I just created this same issue a few days ago #3350 The number of pane splits matters

**Comment by plafosse** [comment]
This is no longer an issue because the new Symbols sidebar doesn't show the current selection.
