### ISSUE TITLE
Better Discoverability for "Go To Address" and "Go to File Offset"

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#3327]
Both actions have no menu items and are hard to find. Although many people figure out the "Go To Address" by pressing "G", the muscle memory actually comes from our competitor. If they have not used it before using BN, then its hard to find. "Go to File Offset" is worse, that it can only be triggered by command palette, which is fairly low discoverability.

I suggest we add a "Go to" menu entry, and put the two actions as a submenu item. Besides, we can add many other ones, e.g., "Next Function/Data Variable/Section/Segment", etc.

**Comment by fuzyll** [comment]
"Go to Address" exists in the Edit menu (and lists the "G" hotkey next to it). They're also in the command palette.

We should maybe put "Go to File Offset" next to "Go to Address" in the Edit menu, though.

**Comment by psifertex** [comment]
`Go to Address` was already in the `Edit` menu. I've added `Go to File Offset` as well as of build 3586 and I don't think we have any plans to add them to the context menu.

**Comment by xusheng6** [comment]
Well, I am not reopening this issue at the moment, but I suggest that we add a `Go To` context menu that has "Go to address", "Go to file offset", "Go to next data var", "Go to next use of the variable", etc
