### ISSUE TITLE
Automatically show functions in the __mod_init_func section and name them as such in MACH-O binaries

### ISSUE THREAD

**Issue by shepgoba** [Vector35/binaryninja-api#3334]
Init funcs in MACH-O binaries are not named after being an init func or shown in the `__mod_init_func` section, as shown in the screenshots below.
![image](https://user-images.githubusercontent.com/25678143/181410307-37b67ac0-d15f-471f-b687-723431871e80.png)
![image](https://user-images.githubusercontent.com/25678143/181410409-69611138-0c5a-4be0-8443-ace43bf06497.png)

It would be nice if these were shown in the `__mod_init_func` section which could be jumped to, as well as being named similar to how they are in IDA. IDA names init funcs `InitFunc_<index>` so the first one is `InitFunc_0`, then `InitFunc_1`, then `InitFunc_2`, etc.

It seems like that would make sense because `sub_<address>` is a name that's understandably based on no information, so IMO we may as well populate function names with *something* that make sense. It doesn't need to copy IDA's naming scheme, although InitFunc does make the most sense.

What's interesting is when I load a shared library like one shown in those screenshots it jumps to sub_9b14, pointing to the fact that your analyzer knows what the constructors / init funcs are.

Regardless, thanks for your effort

**Comment by cxnder** [comment]
As of **Dev Builds >= 3.4.4159**, whenever there is no existing symbol, these functions will be named following "mod_init_func_{n}"
![image](https://user-images.githubusercontent.com/55725881/226675045-8872e9a6-c38d-4c60-8d33-cad754ce9569.png)
