### ISSUE TITLE
Changing Linear (while pseudo C is set) to Triage Summary then back to Linear back resets the view to Disassembly

### ISSUE THREAD

**Issue by XVilka** [Vector35/binaryninja-api#3335]
Binary Ninja Version: 3.1.3581-dev Personal, 67158f4e
Platform: macOS 12.3

When you have file opened with the view "Linear" and "Pseudo C" or "HLIL" representation, changing it to the "Triage Summary" then back to "Linear" resets the view to "Disassembly" as a default, and also prints the empty string instead of the name of the active representation mode. I think, for the better UX, it should preserve the last active representation when switching the modes back and forth.

<img width="1145" alt="Screen Shot 2022-07-29 at 17 43 35" src="https://user-images.githubusercontent.com/203261/181732804-9b6e59be-0e46-4761-832d-f2ca7a237dc3.png">

Note the empty name on the left pane where the switch happened and compare it to the right one where it didn't.

**Comment by fuzyll** [comment]
This should be covered by #3119. Closing in favor of that issue. Thanks!

**Comment by bpotchik** [comment]
This issue is different than #3119

**Comment by bpotchik** [comment]
Fixed in `3.1.3611-dev`.
