### ISSUE TITLE
Reopen all opened files automatically on restarts triggered by installing the update

### ISSUE THREAD

**Issue by XVilka** [Vector35/binaryninja-api#3336]
Binary Ninja Version: 3.1.3581-dev Personal, 67158f4e
Platform: macOS 12.3

I am on the "dev" channel and try to install update every morning, when it's available, and then pressing the "Restart" button after downloading is complete. The biggest issue that I have to reopen all files every time, from "Recent Files", especially since I often have multiple opened in different tabs. I propose the default behavior or an option, to reopen all these tabs again automatically if the restart was triggered by the update.

**Comment by psifertex** [comment]
That's a great suggestion and as we recently added the "restart and reopen" action it's trivial to implement. 

I've also updated the "restart" text when it appears after changing settings (such as python interpreter or theme) that require a restart as well to use that same method as it's almost certainly a better default. 

Will be live in builds >= 3582

**Comment by XVilka** [comment]
@psifertex thank you for the fix, but one minor thing remains - the order of tabs is not saved. After the restart tabs are located in a different order which in some scenarios can be confusing - e.g. when you have multiple versions of the same executable opened in different tabs and have the identical file name but a different absolute file path.

**Comment by psifertex** [comment]
Heh, looking at the code it looks like it was accidentally _always reversing_ the order. That's an easy fix. See #3360 which will be fixed in the next dev. Thanks for pointing that out.
