### ISSUE TITLE
Documentation for BinaryView.parse_type_string cut-off mid sentence.

### ISSUE THREAD

**Issue by cookiemon** [Vector35/binaryninja-api#3338]
The documentation for [BinaryView.parse_type_string](https://api.binary.ninja/binaryninja.binaryview-module.html?highlight=parse_type_string#binaryninja.binaryview.BinaryView.parse_type_string) is missing the latter half of the sentence. I assume it would describe that it allows references to types available in the bv.

![image](https://user-images.githubusercontent.com/4206862/182034279-649650d3-f82d-42b5-be3b-69cf7f480cf8.png)

**Comment by psifertex** [comment]
Thanks, will be fixed in the next dev build with https://github.com/Vector35/binaryninja-api/commit/522d8eb648bcf0f58d17d421e4f5967b251b0b70
