### ISSUE TITLE
Process the PE Exception Table (.pdata) to source additional function starts

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#335]
Use the .pdata list of functions to identify more functions on an initial PE load. 

https://msdn.microsoft.com/en-us/library/ft9x1kdx(v=vs.80).aspx
https://msdn.microsoft.com/en-us/library/windows/apps/ms253988(v=vs.80).aspx

**Comment by psifertex** [comment]
Updated URLs:
https://docs.microsoft.com/en-us/cpp/build/exception-handling-x64?redirectedfrom=MSDN&view=vs-2019
https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-runtime_function

**Comment by bpotchik** [comment]
Added in  2.1.2365-dev.
