### ISSUE TITLE
Clicking 'X' To Close Multiple Tabs Sequentially Seems Broken

### ISSUE THREAD

**Issue by bpotchik** [Vector35/binaryninja-api#3354]
Using the mouse to close tabs doesn't work in all cases.

**Comment by psifertex** [comment]
Small work-around: use the middle-click to close buttons which doesn't require precisely hitting the `X`.  Middle clicking anywhere closes a tab.

The `X` not working consistently is due to the tab width being calculated based on filename and therefore not always aligning from tab-to-tab.

**Comment by cxnder** [comment]
The issue isn't "tabs arent the same width", the X button literally just doesnt work if you dont move your mouse after clicking one.

Repro:
* cmd+N like 4 times from the new tab pane
* prepare your mouse /trackpad position so you can click without moving it a single pixel
* click and don't move the mouse, try to click the x again, the button will respond but the tab wont close

**Comment by bpotchik** [comment]
Fixed in `3.1.3703-dev`.
