### ISSUE TITLE
SettingsView Search Filter Bug When Pasting Search Text

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#3355]
Repro steps:
1) Search for "pdb" in the settings search
2) type "history" in another window and copy the text.
3) Paste "history" while selecting "pdb"
4) Search results are blank:
![Screen Shot 2022-08-03 at 7 34 27 PM](https://user-images.githubusercontent.com/140215/182730310-a6d6b904-816f-48aa-8da2-f15cc2fbbc07.png)

Here's what they should look like:
![Screen Shot 2022-08-03 at 7 35 29 PM](https://user-images.githubusercontent.com/140215/182730425-805ef99b-e8d1-41e6-b283-202d21c63227.png)

Presumably there's some race condition that appears to be trying to combine search filters so nothing matches?

**Comment by bpotchik** [comment]
Fixed in `3.1.3596-dev`.
