### ISSUE TITLE
Support for customizable block indent 

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#3357]
![indent](https://user-images.githubusercontent.com/109607896/182792453-c278beb7-4267-4103-b72e-fe70925ebdf2.PNG)

Line at 180038454 have 10 different indent. This is too much for reading code.  Same binary and same address have 3 indent in IDA and IDA uses 2 spaces for indent in default settings. I couldn't be able to find how to set it to 2 in BN. Support for doing so would be useful.

I guess this is also related to decompiler's choices but that is another story.

**Comment by jonpalmisc** [comment]
This is now configurable via the new "Tab Width" (`rendering.hlil.tabWidth`) setting in builds ≥3607. I'd also suggest checking out the "Indent HLIL Function Body" setting in the linear view options accessible from the hamburger menu (pictured below), which can knock off an additional level of indentation if you had it enabled beforehand.

![image](https://user-images.githubusercontent.com/41548458/183083979-821836ec-3edc-4b5a-bfac-1e4f568a0e9e.png)
