### ISSUE TITLE
scriptingprovider.py error

### ISSUE THREAD

**Issue by tykind** [Vector35/binaryninja-api#3359]
Binary Ninja Version: 3.1.3600-dev Personal, dfa1ae81
Platform: Windows 11 Version 2009

Hi, after installing this development update an error kept occurring. When trying to use python console and sometimes plugins even fail with errors leading to the scriptingprovider.py.

![image](https://user-images.githubusercontent.com/106443697/182949452-cafd6f34-e42a-4395-9337-fcfd2c44ecee.png)

**Comment by cxnder** [comment]
Thank you for the report, resolved in builds >= 3.1.3604
