### ISSUE TITLE
Always use backslashes on recent files on Windows.

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#336]
The Recently opened files on windows shows paths with forward slashes. Depending on how the files were opened (either by dragging the file onto the icon or opening with the open dialog).

![screen shot 2016-07-12 at 6 02 47 pm](https://cloud.githubusercontent.com/assets/10556585/16785259/20b4ff4a-485b-11e6-8e0d-64c33777f3aa.png)

**Comment by psifertex** [comment]
Fixed in 1090. Windows builds now canonicalize on backslashes.
