### ISSUE TITLE
Restart and Reopen Files Does Not Preserve Tab Order Or Separate Windows

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#3360]
restart and reopen reverses the list of tabs each time you use it instead of maintaining the current order

**Comment by psifertex** [comment]
Resolved in builds >= 3605

**Comment by bpotchik** [comment]
This is still broken.

**Comment by psifertex** [comment]
Order is correct now, even if tabs have been re-arranged. Also, currently collects from multiple separate windows but does not necessarily re-open in the same split windows but gathers all open tabs into one new window for now. 

builds >= 3650
