### ISSUE TITLE
Reanalyzing doesn't update PE Filesection virtual size

### ISSUE THREAD

**Issue by Q4LEX** [Vector35/binaryninja-api#3364]
Binary Ninja Version: 3.1.3469 Personal
Platform: Windows 11 Version 2009

Changing the virtual size of a section (in the section table) and then reanalyzing doesn't update the section size in the view.

For example:
Resizing the virtual size of the .text section to the raw size (providing virtual size < raw size), and then reanalyzing does not reveal the
zero padded bytes. Restarting the program and reanalyzing that way is required.

**Comment by fuzyll** [comment]
Are you editing the bytes in the original file and then hitting reanalyze? Reanalysis does not re-parse the underlying binary. Reanalysis re-analyzes all of the known functions. So, this isn't an expected workflow.

Or, are you doing something else?

**Comment by Q4LEX** [comment]
I am editing them in the inbuilt hex editor, the type display also updates.

**Comment by plafosse** [comment]
Binary Ninja has two different phases. Parse, and Analyze. Re-analysis doesn't effect the original parsing of the binary. To get this to work you'll have to write out the raw binary and re-open it. Changing the headers and expecting it to update Binary Ninja's representation is not a currently a supported workflow.
