### ISSUE TITLE
We need the ability to name snapshots

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#3367]
**What is the feature you'd like to have?**
We treat snapshots like `git` commits, but there is no way to add a name or description for them currently. This will be super useful to have in the product once #3358 has been completed.

**Is your feature request related to a problem?**
We need this in Enterprise for feature parity with Ghidra's collaboration.

**Comment by CouleeApps** [comment]
This has been implemented as of 3.2.3950-dev (Enterprise).
