### ISSUE TITLE
Back and forward too hasty

### ISSUE THREAD

**Issue by D0han** [Vector35/binaryninja-api#337]
Back and forward buttons on mouse are triggering changes on on-press and on-release, jumping 2 times per click.

**Comment by VelocityRa** [comment]
Bump.

**Comment by TactiFail** [comment]
Bumping as well.

**Comment by gosma** [comment]
This is annoying, but fortunately only happens on Windows for me.

**Comment by psifertex** [comment]
Fixed due to the switch to QT 5.10 (builds >= 1041)
