### ISSUE TITLE
Missing IL xrefs for imported function passed as argument in a tailcall

### ISSUE THREAD

**Issue by nshp** [Vector35/binaryninja-api#3382]
**Version and Platform (required):**
- Binary Ninja Version: 3.1.3626-dev

**Bug Description:**
Some xrefs to `strcmp` are missing the IL in the `ls` binary from my system.

**Steps To Reproduce:**
Open my `ls` binary, go to `strcmp`, look at the xrefs around 0x9544.

**Screenshots:**
![](https://cyberjes.us/noil.png)

**Binary:**
[https://cyberjes.us/ls-ilxrefs.elf](https://cyberjes.us/ls-ilxrefs.elf)

**Comment by plafosse** [comment]
Ah yes I think this one is specifically related to missing hlil mappings which @bpotchik has a fix for.

**Comment by bpotchik** [comment]
Fixed in `3.1.3638-dev`.
