### ISSUE TITLE
Improve discoverability of "keyword" search in Symbols search

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#3383]
For as long as it has existed the Symbols search has been keyword based i.e. you can search for "foo bar" to do sub searches.  We've noticed most people don't eve know about this great feature.

Suggest changing the default text to "Search symbols (keyword)" and adding a tool tip explaining how the search works.
In the future we'll add regex search and we can change the default text dynamically to "Search symbols (regex)"

**Comment by psifertex** [comment]
Resolved just by adding a tooltip, the keyword default text felt a bit too cramped. Resolved in builds > 4979
