### ISSUE TITLE
custom loading options

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#339]
We currently have no GUI way to load binaries/firmware or other data via custom mappings into address spaces with properties. We should have such.

**Comment by bpotchik** [comment]
This was added in 1.1.1856-dev. The UI is incomplete for this, however the underlying mechanism is in place. For now a mapping (segments/sections) can be provided via stringified json in the 'Open With Options' UI. This is also supported in headless.

**Comment by psifertex** [comment]
Note that #1698 is tracking the UI capability.
