### ISSUE TITLE
Documentation needed on how a Function's end is determined and how it can be changed.

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#3390]
Binary Ninja calculates a function's "end" differently than other products. Though we believe this to be a superior approach it can cause confusion when someone wants to end a function early.  The possible options should be explained somewhere and if possible the user should be notified.

**Comment by psifertex** [comment]
Will go in new `concepts` section
https://github.com/Vector35/binaryninja-api/blob/dev/docs/dev/concepts.md

**Comment by psifertex** [comment]
Added in concepts in builds > 4500
