### ISSUE TITLE
Open source BinaryViewTypes

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#3394]
We would like to at some point open source our BinaryViewType implementations for 

- [x] ELF 
- [x] Mach-O
- [x] PE
- [x] COFF

**Comment by xusheng6** [comment]
Currently blocked by https://github.com/Vector35/binaryninja-api/issues/3205

**Comment by D0ntPanic** [comment]
Done as of build 4020

**Comment by D0ntPanic** [comment]
The view implementations can be found here:

https://github.com/Vector35/view-elf
https://github.com/Vector35/view-macho
https://github.com/Vector35/view-pe
