### ISSUE TITLE
Cannot view log for BinaryViews opened in Python console

### ISSUE THREAD

**Issue by KyleMiles** [Vector35/binaryninja-api#3396]
It seems with how the log window is tied to the current view, you can't view the log for a bv you open from the Python console.

**Steps To Reproduce:**
1. Run `view = open_view("/bin/cat")` (or better, a binary that has errors)

If that binary view has errors, it'll bring up error indicators for `global`, and then be unable to show them/clear them.  This also causes #3074 to happen again; clearing the log does not clear the error indicator for the bv's whose errors cannot be viewed.

This is problematic for me debugging DebugInfo, though the workaround is to open the bv in its own tab and just do a `debug_view = bv`.

**Comment by plafosse** [comment]
The work around for this is to change your "Log Scope" to "All Tabs" This is available in the hamburger menu in the log window.
