### ISSUE TITLE
Deprecate unused `BinaryViewTypeArchitectureConstant` API

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#3398]
The `BNSetBinaryViewTypeArchitectureConstant` and `BNGetBinaryViewTypeArchitectureConstant` APIs are no longer used and should be both deprecated and defanged.

**Comment by xusheng6** [comment]
Done in https://github.com/Vector35/binaryninja-api/commit/ed820d2ab81470b3e5ac543d75211e87ff3bc738
