### ISSUE TITLE
linear IL views (all IL views should be supported in linear view)

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#340]
- [ ] IL support
- [ ]  LLIL support
~- [ ]  jumps need arrows on the side~ (tracked in #965)

**Comment by pgoodman** [comment]
Also suggest indenting basic blocks (this is similarish to arrows) in such a way that it is kind of like indented code. For example:
```
A
if (..) {
  B
} else {
  C
}
D```

Could become something like the following in the linear view: ```
A_blocks
  B_blocks
  C_blocks
D_blocks```

**Comment by withzombies** [comment]
Basic block labels that propagate to the branches as well.

For Example:
```
0x08041200   jnz 0x08041234
<snip>
0x08041234  xor eax, eax
```

Becomes:
```
0x08041200   jnz fail
<snip>
fail:
0x08041234  xor eax, eax
```

**Comment by plafosse** [comment]
withzombies there is already a feature request for basic block labels

**Comment by D0ntPanic** [comment]
Added in version 2.0
