### ISSUE TITLE
User documentation still has python2.7 in the example code

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#3400]
Probably not limited to:

 https://docs.binary.ninja/dev/bnil-llil.html#introduction-by-example

**Comment by xusheng6** [comment]
I browsed the user documentation, and there are only two places of py 2.7 code. Fixed in https://github.com/Vector35/binaryninja-api/commit/a835ef412023854fb434fe02444db4cd26021c9e
