### ISSUE TITLE
Explain the difference between an InstructionIndex and an ExpressionIndex

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#3403]
**Is this a general concept that needs to be documented or a specific API?**
Concept

An ExpressionIndex and an InstructionIndex are two similar but distinct concepts which need specific documentation.

**Comment by psifertex** [comment]
Added in https://github.com/Vector35/binaryninja-api/commit/4942700ca3387b64cc6443a80bac60b470588bb9#diff-cff90f37a570c71fac9989cd42c8198bbd46f473b765ec74229685bc8fa8b126R15-R18

**Comment by psifertex** [comment]
Probably could use better clarification from someone else but it's a good start and at least warns folks that are reading the dev docs.
