### ISSUE TITLE
Scrollbars clip into symbols list text

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#3406]
**Version and Platform (required):**
- Binary Ninja Version: 3.1.3615
- OS: macOS
- OS Version: 12.0.1
- CPU Architecture: M1

**Bug Description:**
The symbols list has side scrolling but assumes the scrollbar does not have any width, so the last 3 characters of symbol names are cut off.

**Steps To Reproduce:**
1. Open binary with long symbol names
2. Find long symbol in sidebar
3. Scroll right 
4. See lack of last few chars

**Expected Behavior:**
I expected to be able to scroll like 22px more

**Screenshots:**
<img width="305" alt="image" src="https://user-images.githubusercontent.com/711973/184989477-27431231-0fd4-4788-908b-c72d10d3dd8d.png">

**Additional Information:**
This likely applies to other views too. It used to happen to the Log though that might be fixed now.

**Comment by psifertex** [comment]
Resolved with the migration to the new Symbols widget
