### ISSUE TITLE
Feature request: Published Qt builds

### ISSUE THREAD

**Issue by bb010g** [Vector35/binaryninja-api#3407]
**What is the feature you'd like to have?**
When building UI plugins, a build of Qt 6 with Binary Ninja's patches is required. This build process is documented at <https://github.com/Vector35/binaryninja-api/blob/41d558e510b1e79f5b83834fcf99b1b2eec4961b/docs/about/open-source.md> and <https://github.com/Vector35/qt-build>, but if you're not modifying Qt, this is inconvenient and takes a while. If a build of Qt 6 with Binary Ninja's patches for each supported platform was published in a way that could be dropped into `CMAKE_PREFIX_PATH` to override system Qt, building UI plugins would become much simpler.

**Is your feature request related to a problem?**
I wanted to build <https://github.com/Vector35/debugger> in the process of writing & submitting patch that fixes <https://github.com/Vector35/debugger/issues/237>.

**Are any alternative solutions acceptable?**
I'm very glad that the existing Qt 6 build process exists, but it's still inconvenient and gets in the way of contributions. I would like to see the `libclang` that Vector35 uses for official builds documented. <https://wiki.qt.io/Building_Qt_6_from_Git> links to <https://download.qt.io/development_releases/prebuilt/libclang/>, but I don't know if the official builds use a libclang from there.

**Comment by xusheng6** [comment]
Available at https://github.com/Vector35/qt-artifacts/releases
