### ISSUE TITLE
Function not found in a Windows debug binary generated by MinGW

### ISSUE THREAD

**Issue by KrzaQ** [Vector35/binaryninja-api#341]
Function `make_foo` is only referenced in the code, never called. Nevertheless, when compiled in debug mode, it's detected on Linux or when compiled with cl.exe on Windows.

[testcase.tar.gz](https://github.com/Vector35/binaryninja-api/files/376031/testcase.tar.gz)

On Arch Linux, compiled with gcc 6.1.1 everything works exactly as expected. 
![2016-07-17_04-54-52](https://cloud.githubusercontent.com/assets/1174663/16898432/bf52edf6-4bda-11e6-96fe-7bb4bdea8662.png)

On Windows, with cl.exe (from Visual Studio 2013):
![2016-07-21_15-06-12](https://cloud.githubusercontent.com/assets/1174663/17023678/cbdc09d6-4f54-11e6-816f-da3543f7e11b.png)

On Windows, compiled with mingw-gcc 5.3.0 (bundled with Qt 5.7 for MinGW), I am getting this:
![2016-07-17_05-12-03](https://cloud.githubusercontent.com/assets/1174663/16898580/db6b2540-4bde-11e6-8f58-218ada39184d.png)

After pressing `H`:
![2016-07-17_05-12-51](https://cloud.githubusercontent.com/assets/1174663/16898581/e0dbaf54-4bde-11e6-9303-866990c94772.png)

And after pressing `P`, the function and many in its call tree are added to the list:
![2016-07-17_05-13-03](https://cloud.githubusercontent.com/assets/1174663/16898583/e376e6e8-4bde-11e6-8648-64709d626103.png)

I'm not 100% sure this constitutes a bug, but it definitely surprised me.

**Comment by psifertex** [comment]
Ahh, this is good information, thanks. 

First, a quick summary is that we don't scan looking for functions. We will automatically add functions exposed via symbols, and if the function is called from anywhere else, we should find it as well.

That said, there are symbols on the mingw binary so that's good to know, we should be able to fix that.

Any chance you could upload the mingw built binary as well?

**Comment by KrzaQ** [comment]
It's in `testcase.tar.gz` from the first post, `libtestlib_mingw.dll`. Sorry for the bad naming.

**Comment by psifertex** [comment]
Sorry for not closing this a while ago, this bug was fixed some time ago.
