### ISSUE TITLE
Incorrect function end address (and awkward search dialog ranges?)

### ISSUE THREAD

**Issue by ioncodes** [Vector35/binaryninja-api#3410]
**Version and Platform (required):**
- Binary Ninja 3.0.3247-dev
- OS: Windows
- OS Version: 11
- CPU Architecture: x64

**Bug Description:**
`current_function.high_address` seems to be wrong for certain functions. This has been tested with the `ntoskrnl.exe` function `NtQueryInformationThread`. I noticed this behavior while using the search dialog. Additionally, the search box seems to show the address `0x7fffff....`.

**Steps To Reproduce:**
1. Open `ntoskrnl.exe` in Binary Ninja
2. Load PDB info (this may be optional; haven't tested it without)
3. Go to `NtQueryInformationThread`
4. Enter `current_function.high_address` in Python Console

I cannot reproduce the `7ffff...` bug. Not sure what happened there.

**Expected Behavior:**
The address should reflect what I see in the graph view.

**Screenshots:**
![image](https://user-images.githubusercontent.com/18533297/185221143-d31727f4-c90e-4c54-b801-19f699139da6.png)

**Comment by psifertex** [comment]
After some investigation, this is behaving as intended as there is a basic block far away from the start by address.
