### ISSUE TITLE
Wrong Installation on Freshly installed Win 8.1 && proposed fix

### ISSUE THREAD

**Issue by Evilcry** [Vector35/binaryninja-api#342]
On a fresh-install not updated Windows 8.1, after installing, BN cannot start due to a missing DLL (that comes from the redistributable package). 

I've already seen this issue and it's caused by some missing update.

A way to solve the issue is to check if ucrtbase.dll exists; if not available then "force" the user to update by installing the following: https://support.microsoft.com/en-us/kb/2999226

**Comment by psifertex** [comment]
Given that the package is available through windows update we'll likely just mark this as won't fix for now. Sorry for the long time for a response.
