### ISSUE TITLE
Search not only for command but also for keybindings in "Keybinding" view

### ISSUE THREAD

**Issue by mostobriv** [Vector35/binaryninja-api#3422]
**What is the feature you'd like to have?**
Searching for specific key combinations, currently it's only possible to search by command name.

**Is your feature request related to a problem?**
nope

**Are any alternative solutions acceptable?**
Currently we can sort actions by keybinding and look up for what we need, but it's become harder and slower to search when number of keybinding is growing

**Comment by psifertex** [comment]
I've wanted this for a while too. I implemented it though we still don't have the ability to hit a button that would turn entered hotkeys into text yet, in builds >= 3642 you can now search hotkey text though you'll have to search for for it by entering (for example): `Ctrl+o` into the search field. Still faster than sorting/scrolling.
