### ISSUE TITLE
automatically apply debug information

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#3423]
It should be possible for DebugInfo APIs to automatically be detected and loaded when appropriate. Examples include: dwarf information, PDB information, etc. Might require some in-progress changes to workflows.

**Comment by KyleMiles** [comment]
This is fixed in builds >3.1.3729-dev.  Debug information is attempted to be loaded when opening a file, and you can adjust that behavior with the new load settings `load.debugInfoInternal` and `load.debugInfoExternal`.  See the Open with Options menu for more details.
