### ISSUE TITLE
Change Type dialog opens on different monitor

### ISSUE THREAD

**Issue by cxnder** [Vector35/binaryninja-api#3426]
**Version and Platform (required):**
- Binary Ninja Version: 3.1.3642
- OS: macos
- OS Version: 12.4
- CPU Architecture: *

**Bug Description:**
Change type dialog ignores the monitor BinaryNinja is currently on and instead opens on the primary monitor

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Have 2 monitors
2. Move binaryninja to the 2nd
3. Open the symbol rename dialog, observe it behaving properly
4. Open the Change Type dialog, observe it on the wrong monitor

**Comment by psifertex** [comment]
After much internal discussion we're going to just close this as WONTFIX. This is the cost of having a type dialog that remembers its location and is easily fixable by just moving the create type dialog once at which point it remembers its new location on the new monitor. Note that if you unplug a monitor the create type dialog will open on a new monitor instead.

**Comment by psifertex** [comment]
Minor clarification that I did push one change that resets the saved dialog information on restart of BN. This way the first time you launch BN if you've moved monitors the dialog will be on the "right" dialog. And if you prefer a layout where the dialog is on another monitor, you only have to move it once per restart.
