### ISSUE TITLE
High RAM usage when running for a long time

### ISSUE THREAD

**Issue by toomanybananas** [Vector35/binaryninja-api#343]
After running binja for about 2 weeks on my (Debian Linux 8 64-bit) the process uses about 14GB of RAM, even when no files are open.

**Comment by toomanybananas** [comment]
Further information: opening a moderately sized (600kb) statically-linked ELF file causes binja to allocate roughly 1GB of RAM, which is not freed when the file is closed.

I can't share this specific sample unfortunately but I will attempt to reproduce it.

**Comment by plafosse** [comment]
Can you validate this on the current dev build?

**Comment by plafosse** [comment]
Closing this since the question has been outstanding for a while and I can't seem to replicate it. Please reopen this bug if the issue is still present.
