### ISSUE TITLE
Support function stack pointer

### ISSUE THREAD

**Issue by inaryart** [Vector35/binaryninja-api#3434]
**What is the feature you'd like to have?**
When the stack offset is identified incorrectly, I can manually fix it myself

**Is your feature request related to a problem?**
na

**Are any alternative solutions acceptable?**
like ida
![image](https://user-images.githubusercontent.com/51652878/186831999-cb9b19d1-8497-437b-bcec-298372ea5503.png)

![image](https://user-images.githubusercontent.com/51652878/186832214-aae8fbbe-db4b-49c9-ad66-e1ed17dd049f.png)

**Additional Information:**
na

**Comment by CouleeApps** [comment]
Not quite what you're asking for, but there is "Show Stack Pointer Value" in Low Level IL mode (check the options dropdown in any view). From there, you can find any branches/calls that cause the stack pointer to become UndeterminedValue and clean them up.

**Comment by fuzyll** [comment]
We haven't received an update on this in over a week, so we're closing it now due to inactivity. We're more than happy to re-open it with more information. Thanks!
