### ISSUE TITLE
brackets pair highlight in pseudo-c code

### ISSUE THREAD

**Issue by nitrogar** [Vector35/binaryninja-api#3437]
**What is the feature you'd like to have?**
when clicking on an opening or closing characters like (),"",{},'',[] I would like the other pair to be highlighted. 
**Is your feature request related to a problem?**
yes without this feature reading the pseudo-c code is difficult 
**Are any alternative solutions acceptable?**
counting by hand :(

**Comment by psifertex** [comment]
Pretty sure this feature is tracked already between these two issues:
#2790 
#1730
