### ISSUE TITLE
the ability to search the pseudo-c code of the full program

### ISSUE THREAD

**Issue by nitrogar** [Vector35/binaryninja-api#3438]
**What is the feature you'd like to have?**
I would like to search for a pattern in the pseudo-c code of all defined functions 
**Is your feature request related to a problem?**
In case of analyzing firmware or video game I  would like to find all functions which have infinite loop "while(true)". Also in case of vulnerability research it is hard to write a general plugin that work in all cases it is better to have built in feature like project zero's [weggli](https://github.com/googleprojectzero/weggli) for real-time feedback and fine-tuning the search criteria 
**Are any alternative solutions acceptable?**
writing custom plugin to loop over all function and find the pattern but it is hard be generalized for all programs

**Comment by psifertex** [comment]
You can already search pseudo-c of the full program:
<img width="888" alt="Screen Shot 2022-08-26 at 3 21 50 PM" src="https://user-images.githubusercontent.com/140215/186976817-75ff0681-cfde-4860-9924-0f7a60544836.png">

Is there a reason that search doesn't work?

**Comment by nitrogar** [comment]
The feature I think of is sort of fuzzy search for example 
searching for "while( __var == 1)" , will find all while loops independent of the variable name inside the brackets
searching for 
`__var x = malloc(__value);`
`__var y = malloc(__value);`
`strcpy(x,y);`

will find any heap memory string copy even code exists between the search criteria like 
`char * buffer1 = malloc(100)`
`char * buffer2 = malloc(100)`
`if(buffer1){`
         `strcpy(buffer1,buffer2)`
`}`

**Comment by psifertex** [comment]
Ahh, gotcha. That is unfortunately not something on the roadmap at this point but the good news is you can actually use the BN Weggli plugin. I recommend using this PR which unfortunately hasn't been merged yet: https://github.com/googleprojectzero/weggli/pull/32

Another alternative that I've been working on for a while is a semgrep plugin though it's not quite complete yet, but keep an eye out in the plugin manager for that soon as well.
