### ISSUE TITLE
There are two different, conflicting ways to select text in Types view which can both be active at once.

### ISSUE THREAD

**Issue by 0cyn** [Vector35/binaryninja-api#3440]
**Version and Platform (required):**
- Binary Ninja Version: 3.1.3651
- OS: macOS
- OS Version:  *
- CPU Architecture: x64

**Bug Description:**
There are multiple ways to select text in the Types view, both of which can be active at once, causing very confusing behavior when trying to copy a type out of the view.

**Steps To Reproduce:**

1. Define a struct or enum
2. Create a selection by dragging your mouse from the closing bracket of the struct to the middle of the word "struct", and then release the left mouse button. 

**Expected Behavior:**
Token selection and "range of lines" selections should not be allowed to both be active at once.

**Screenshots:**
In this screenshot, the entire enum has been selected, but since the selection drag stopped over the struct name, only the token "SCTLR_VALS" will be copied via the "Copy" action.
![image](https://user-images.githubusercontent.com/55725881/187049382-a2fcc6ce-b97e-418a-9279-2513b9f767ce.png)

**Additional Info:** 
LinearView supports both of these selection types but properly does not allow them to both be active at once.

**Comment by CouleeApps** [comment]
This was addressed with the new types browser view as of 3.6.4615-dev
