### ISSUE TITLE
Cannot copy version number out of about window when a binary is open

### ISSUE THREAD

**Issue by saagarjha** [Vector35/binaryninja-api#3441]
**Version and Platform (required):**
- Binary Ninja Version: 3.1.3651-dev
- OS: macOS
- OS Version: 13.0 (22A5331f)
- CPU Architecture: Apple silicon

**Bug Description:**
If I open the about window and select the version number, then hit ⌘C, the version number doesn't get copied to my pasteboard. The Edit menu flashes, but it copies whatever code my cursor is on in the other window.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open a binary.
2. Open the about window.
3. Select the version number.
4. Hit ⌘C.

**Expected Behavior:**
The version number is in my clipboard.

**Comment by psifertex** [comment]
I've actually been meaning to change the text there to be click-to-copy instead for a while since that's even easier than having to separately copy. Resolved in builds >= 3653.
