### ISSUE TITLE
Cannot kill text from Python console

### ISSUE THREAD

**Issue by saagarjha** [Vector35/binaryninja-api#3442]
**Version and Platform (required):**
- Binary Ninja Version: 3.1.3651-dev
- OS: macOS
- OS Version: 13.0 (22A5331f)
- CPU Architecture: Apple silicon

**Bug Description:**
If I hit ⌃K in the console I expect text to be killed, but nothing happens.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Put your cursor into the Python console and type something.
2. Hit ⌃A to go to the beginning of the line.
3. Hit ⌃K.

**Expected Behavior:**
The text is added to the killed. (Try this in any other text field on macOS.)

**Comment by psifertex** [comment]
added in builds >= 3654

**Comment by psifertex** [comment]
Short summary is no, we don't have a unified UI input field so it would require a massive amount of copy/paste.

Re: implementing a kill buffer, it looks like _maybe_ QT might have [both of these features](https://doc.qt.io/qtcreator/creator-keyboard-shortcuts.html) that but just not bind it by default? It's not entirely clear to me though if those are just in QT creator or QT itself. Your best bet would probably be to get them enabled in QT proper by filing an issue with them to get them to match OS behavior on MacOS more closely and then we'd get it in all of our dialogs automatically.

**Comment by psifertex** [comment]
Looks like that's just one input field in QT Creator and not anything built into QT itself. I think an upstream patch is definitely the way to go for this. @jonpalmisc is also interested in this feature so there's a chance we take a look at supplying the patch ourselves to QT, but it's obviously pretty low priority.
