### ISSUE TITLE
Save reminder alert should put a focus ring on "Don't Save"

### ISSUE THREAD

**Issue by saagarjha** [Vector35/binaryninja-api#3443]
**Version and Platform (required):**
- Binary Ninja Version: 3.1.3651-dev
- OS: macOS
- OS Version: 13.0 (22A5331f)
- CPU Architecture: Apple silicon

**Bug Description:**
On macOS, it is typical for the "hey do you want to save before closing this" alert to have three options: "Save", "Don't Save", and "Cancel". With full keyboard access, the keyboard shortcuts for each of these is enter, space, and escape respectively. It would be nice for Binary Ninja to offer these too.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open a binary.
2. Try to close the window.

**Expected Behavior:**
There's a focus ring around "Don't save" that lets me select that option with the spacebar.

**Screenshots:**
<img width="532" alt="Screenshot 2022-08-27 at 19 32 36" src="https://user-images.githubusercontent.com/13786931/187054929-94636b42-3604-4055-9a69-764d0f270d8a.png">
(Focus is on the "Save" option, which means both enter and space select it)

**Additional Information:**
<img width="372" alt="Screenshot 2022-08-27 at 19 33 34" src="https://user-images.githubusercontent.com/13786931/187054947-2ee761a0-97b5-4e86-9aba-f5390d87a113.png">
(A more standard accelerator set, in this case from Hopper)

**Comment by psifertex** [comment]
Ohh boy, if only you knew the amount of internal discussion we've had around this particular topic. Far, for more than most would expect. 😉 

In short, the current behavior has been carefully chosen after lots of analysis of many different applications as well as the desire to remain as cross-platform as possible while still doing our best to follow local conventions and it is unlikely to change again soon.

That said -- if you want to select "don't save", use the CMD-D hotkey (CTRL-D on non-MacOS installs of BN). Believe it or not this actually used to be default hotkey across [all native apple apps](https://osxdaily.com/2011/08/15/return-the-dont-save-keyboard-shortcut-to-commandd-in-mac-os-x-lion/) and it happens to play nicely across other OS's once you get used to it.

**Comment by saagarjha** [comment]
Cool, that works for me.

**Comment by saagarjha** [comment]
Can we revisit this issue now that the dialog looks like this?
<img width="372" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/13786931/e618dc65-74d2-43ca-b979-78cae9a7cba4">
