### ISSUE TITLE
Horizontal scrolling acceleration in the functions list is different when searching

### ISSUE THREAD

**Issue by saagarjha** [Vector35/binaryninja-api#3444]
**Version and Platform (required):**
- Binary Ninja Version: 3.1.3651-dev
- OS: macOS
- OS Version: 13.0 (22A5331f)
- CPU Architecture: Apple silicon

**Bug Description:**
If you search for text in the function list and then scroll horizontally the acceleration is jarringly different.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open a binary.
2. Search for something in the function list.
3. Scroll horizontally, preferrably with a  high-quality trackpad.

**Expected Behavior:**
Scrolling is smooth and has momentum.

**Screenshots:**
Not a screenshot but a video.

https://user-images.githubusercontent.com/13786931/187055094-f07e86fb-493c-4bcf-b358-8d426344614c.mov

**Comment by psifertex** [comment]
I suspect this is a coincidence based on the number or type of of items on the list. In other words, the default QT horizontal scrolling is based on the number of items on the list or average line width, or some other property which changes when the filter is in place. 

Given that, I'm not really sure what we could/should do to change this behavior as it likely involves mucking around with QT internals that are better left alone and this is probably in the "WONTFIX" category of behavior. I'll leave it open for a bit and talk about it with some others on the team just to see if they have more ideas on the matter just in case.

**Comment by fuzyll** [comment]
We discussed this further and believe this is a Qt bug and not something we can fix easily. Hopefully this will be fixed in a future Qt release. Thanks for the report, though.
