### ISSUE TITLE
"Display As" does not work on array indices in the "Disassembly" view annotations 

### ISSUE THREAD

**Issue by cxnder** [Vector35/binaryninja-api#3446]
**Version and Platform:**
- Binary Ninja Version: 3.1.3656-dev 
- OS: macOS
- OS Version: 12.4
- CPU Architecture: x64 😔 

**Bug Description:**
Selecting the indices in these annotations and clicking "Display as", then selecting decimal does not update their representation in the annotations. It does update it for other IL levels. 
![image](https://user-images.githubusercontent.com/55725881/187154928-b803183b-ba7a-4b7b-af89-2df50f8e93b4.png)

**Steps To Reproduce:**

Open the following bndb, select any index annotation, click display as, select anything, and note it not updating in disasm, but working properly in other IL levels.

[report_disasm_display_as_fail.bndb.zip](https://github.com/Vector35/binaryninja-api/files/9442793/report_disasm_display_as_fail.bndb.zip)

**Expected Behavior:**
Preferrably it should respect the display setting. It's especially preferable in this example when the array in question is referring to an array of arm64 register states.

**Comment by fuzyll** [comment]
Reproduced this on both 3.1 stable and 3.1.3656-dev. In the screenshot above, changing the #0x78 works, but trying to change 0xf or 0x10 does not work. (This is what the ticket title means by 'annotations', which I did not fully understand at first.)

**Comment by cxnder** [comment]
Separate but related issue I'm tacking on to this:
`Display as` on array (not struct -> array, just array) doesn't work in disassembly, low, medium, but changing it in any of those modes affects it in HLIL

**Comment by cxnder** [comment]
Resolved in builds >= 3.1.3693
