### ISSUE TITLE
Analyzing Safari.framework crashes the app

### ISSUE THREAD

**Issue by saagarjha** [Vector35/binaryninja-api#3447]
**Version and Platform (required):**
- Binary Ninja Version: 3.1.3665-dev Personal (Build ID 9678ab70)
- OS: macOS
- OS Version: 13.0 (22A5331f)
- CPU Architecture: Apple silicon

**Bug Description:**
When analyzing the arm64e slice of Safari.framework from Safari Technology Preview Release 152 (LC_UUID: 60EE7A38-0A34-3B39-AC47-3C5B863B8B85), the app crashes. 

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open the binary.
2. Wait a little while while it analyzes.

**Expected Behavior:**
No crash while analyzing.

**Additional Information:**
[binaryninja-2022-08-31-032405.ips.txt](https://github.com/Vector35/binaryninja-api/files/9460723/binaryninja-2022-08-31-032405.ips.txt)
[Safari.zip](https://github.com/Vector35/binaryninja-api/files/9460737/Safari.zip)

**Comment by cxnder** [comment]
Thank you for the report, this should be resolved in builds >=3.1.3666
