### ISSUE TITLE
Sticky Linear Function Titlebar

### ISSUE THREAD

**Issue by toolCHAINZ** [Vector35/binaryninja-api#3453]
Apologies if this has already been requested (couldn't find it in a quick search).

It would be nice if the Function Title Bar in linear mode would "stick" to the top of the pane when it scrolls out of frame (in the spirit of this recent vscode addition: https://twitter.com/stefanjudis/status/1555466217774882818).

Graph view has something similar in that it has the function name/prototype permanently at the top of the pane.  Not sure of the difficulty of "sticky" elements in QT. Maybe as a simpler alternative, having that same graph view title bar in single function linear view would be nice.

**Comment by psifertex** [comment]
We've definitely talked about it a lot but I can't find the issue so it was either a comment on another issue or a checkbox that was maybe removed. Definitely would be nice.

**Comment by fuzyll** [comment]
This is related to issue #2988. Depending on what we do, the solution might resolve both tickets.

**Comment by psifertex** [comment]
Proposed before and after visuals.

Note that in the "after" the black boarder at the top/sides is not intended but the border at the bottom _is_ intended as it should differentiate in some subtle way from an actual function header at that exact line, but shouldn't be so distinct as to confuse the "current function" in case a smaller function lower on the screen is currently selected. 

![before-feature](https://user-images.githubusercontent.com/140215/188710500-684137c9-848d-40f1-b4e0-b6270a7420bc.png)
![after-feature](https://user-images.githubusercontent.com/140215/188710503-b831951a-b7af-4d91-a23c-b6bf64550c28.png)

**Comment by negasora** [comment]
Added in 3.2.3889-dev
