### ISSUE TITLE
Triage View: Import/export addresses should be green

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#3456]
**What is the feature you'd like to have?**
Make the import/export/entrypoint/base addresses all green, like everywhere else an address is shown in binja.

**Is your feature request related to a problem?**
UI inconsistency is always a problem :)

**Are any alternative solutions acceptable?**
Not really, it's just a standard thing

**Comment by xusheng6** [comment]
Added in 6afd790abeccc98e4319e392ed1f8d8dd78baa8f
