### ISSUE TITLE
Zooming in graph view in small functions gets the zoom stuck

### ISSUE THREAD

**Issue by ZetaTwo** [Vector35/binaryninja-api#3457]
**Version and Platform (required):**
- Binary Ninja Version: 3.1.3678-dev (Build ID 471db061)
- OS: Xubuntu Linux
- OS Version: 22.04.1
- CPU Architecture x64

**Bug Description:**
When in graph view, you can use CTRL+scroll (or CTRL++/CTRL+-) to zoom in and out but for some functions if I try to do this I can zoom in exactly 1 level and then I'm stuck there and can neither zoom in nor out. It seems to be happening specifically for small/simple functions. In the attached binary. The zooming works great for the function `f4` but not the function `f3`

[graph-zoom-bug.zip](https://github.com/Vector35/binaryninja-api/files/9485417/graph-zoom-bug.zip)

**Steps To Reproduce:**
1. Open the attached binary in Binary Ninja
2. Go to the function named `f3`
3. Press CTRL++
4. Try to press CTRL+-

**Expected Behavior:**
I expect to first zoom in and then zoom out again.

**Additional Information:**
Pressing `W` or `Z` to reset the zooms to one of those levels works but doesn't get rid of the issue, after zooming again you get stuck again.

**Comment by plafosse** [comment]
I've fixed this issue but as we're in the middle of a move the build won't be out for sometime yet. Hopefully today though 🤞

**Comment by plafosse** [comment]
Fixed in 3.1.3731
