### ISSUE TITLE
TypesView widget filters out types which are collapsed

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#3458]
**Version and Platform (required):**
- Binary Ninja Version: 3.1 latest

**Bug Description:**

https://user-images.githubusercontent.com/10556585/188640027-63c9e702-d5be-4ace-a514-24026aa53e5b.mov

**Expected Behavior:**
The collapse state shouldn't matter to the filter

**Comment by CouleeApps** [comment]
This is no longer an issue as the new types browser has a different means of filtering types. As of 3.6.4615
