### ISSUE TITLE
Type search should prioritize exact matches

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#3462]
**What is the feature you'd like to have?**
Imagine I have two types added to a bndb: FOO and BAR_FOO. If I search for FOO in the type view, I will see in order BAR_FOO, FOO. With two types this is not a problem, but for complex targets its not uncommon to have hundreds of matching types, especially when types are imported from pdb/dwarf.

The current logic seems to be alphabetical sorting of all substring matches. I'd propose exact match first, followed by the existing logic.

**Is your feature request related to a problem?**
If there are many types, finding a match even when you know the exact name is needlessly cumbersome.

**Are any alternative solutions acceptable?**
Sure

**Comment by CouleeApps** [comment]
As of >= 4.1.5248-dev this is now under the Setting `ui.view.types.exactMatchesFirst` "Filter Exact Matches on Top"
