### ISSUE TITLE
Inconsistent tagging in non-code areas

### ISSUE THREAD

**Issue by emesare** [Vector35/binaryninja-api#3469]
**Version and Platform (required):**
- Binary Ninja Version: 3.1.3701-dev
- OS: Windows 11
- OS Version: 21H2
- CPU Architecture: x64

**Bug Description:**
Removing a tag in a non-code (function) does not update the view, leaving the tag icon and the tooltip. Also adding a tag other than a `Bookmark` does not immediately update the view and the tag's icon only shows up after an update to the view (adding a comment, renaming a symbol, adding another tag).

**Steps To Reproduce:**
1. Go to any non-code section and place a tag/bookmark
2. Observe the icon not being placed in the case for non-bookmark tags
3. Go to Tags sidebar and delete the tag
4. Observe the view not updating and the tag still being present

**Expected Behavior:**
A tag in a non-code section should exhibit the same behavior and be immediately updated with the tag icon and in the case of deletion should be removed.

**Screenshots:**
No update when removing a tag.
![Screenshot 2022-09-15 184852](https://user-images.githubusercontent.com/35282038/190539019-02e76b8e-9c8b-4735-b2b1-914bc5ae68b5.jpeg)
No update when adding tag.
![Screenshot 2022-09-15 185004](https://user-images.githubusercontent.com/35282038/190539136-24308c59-5bfa-4413-bcc1-23f561f7904e.jpeg)

**Comment by psifertex** [comment]
Iirc we have an existing bug tracking this but will double check later. Does pressing space twice trigger an update and render the tag?

**Comment by dankope** [comment]
> Iirc we have an existing bug tracking this but will double check later.
Only one I could find that was similar was #3228

**Comment by galenbwill** [comment]
The existing issue #3228 specifically applies to creating tags via the API, whereas this issue is for data tags created via the UI.

**Comment by emesare** [comment]
Tested on **3.5.4299-dev** and it seems like this has been fixed, closing this as completed.
