### ISSUE TITLE
File offset is off by 0x1000 for ELF x86-64 binary

### ISSUE THREAD

**Issue by ZetaTwo** [Vector35/binaryninja-api#3470]
**Version and Platform (required):**
- Binary Ninja Version: 3.1.3703-dev (Build ID 2713759a)
- OS: Ubuntu Linux 
- OS Version: 22.04.01
- CPU Architecture x64

**Bug Description:**
Binary Ninja is off by 0x1000 in the file offset mapping in an ELF file. When looking at .data section of the attached binary, it claims that the variable `password1` has offset 0x3010 in the file but in reality it is at offset 0x2010 as shown in a hex editor such as 010 Editor.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open the attached ELF file
2. Change the display to show file offset instead of address

**Expected Behavior:**
I expect to see `0x2010 password1:` but I see `0x3010 password1:`

**Screenshots:**

![offset1](https://user-images.githubusercontent.com/870392/190877471-b542e23d-d4d0-436f-99a2-0f9b088c09b8.png)
![offset2](https://user-images.githubusercontent.com/870392/190877473-c1f44c66-81c3-44ff-912b-efaf0f0753f5.png)

**Additional Information:**
Binary with the issue: [offset-bug.zip](https://github.com/Vector35/binaryninja-api/files/9592668/offset-bug.zip)

**Comment by psifertex** [comment]
Resolved in builds >= 3749
