### ISSUE TITLE
Analysis of arm64e slice of dyld fails to discover any instructions

### ISSUE THREAD

**Issue by saagarjha** [Vector35/binaryninja-api#3471]
**Version and Platform (required):**
- Binary Ninja Version: 3.1.3703-dev Personal (Build ID 2713759a)
- OS: macOS
- OS Version: 13.0 (22A5342f)
- CPU Architecture: Apple silicon

**Bug Description:**
If I load the arm64e slice of dyld into Binary Ninja, it doesn't seem to recover any instructions.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open /usr/lib/dyld in Binary Ninja.
2. Select the arm64e slice and run the default analysis.

**Expected Behavior:**
Basic analysis works and instructions are detected.

**Screenshots:**
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/13786931/190879998-2bec16c2-bb50-4b85-8157-1478a1099dbb.png">

**Additional Information:**
[dyld.zip](https://github.com/Vector35/binaryninja-api/files/9592774/dyld.zip)

**Comment by bpotchik** [comment]
This is the same issue as [#3505](https://github.com/Vector35/binaryninja-api/issues/3505).

Fixed in `3.1.3747-dev`.
