### ISSUE TITLE
Note background does not scroll horizontally

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/binaryninja-api#3475]
1. Make a very narrow linear view pane and scroll to the "note" at the top
2. Scroll horizontally
3. Notice that the text scrolls but the "note" background does not, creating an overlap

<img width="499" alt="image" src="https://user-images.githubusercontent.com/41548458/191617729-af72d39b-5256-4b1d-bfe5-9bac92c2b68d.png">

**Comment by CouleeApps** [comment]
Now accounts for scrollbar offset as of 3.2.3799.
