### ISSUE TITLE
Tag labeling on new tag

### ISSUE THREAD

**Issue by elbiazo** [Vector35/binaryninja-api#3478]
**What is the feature you'd like to have?**

I would like extra dialog to add description whenever I make new tag.

**Is your feature request related to a problem?**

Current flow is really awkward in that whenever I make a tab, i would have to goto tag sidebar and label them. It does get pretty confusing when you have many bookmark and you cant really find them.

**Are any alternative solutions acceptable?**

Usually you can have tag sidebar open first then create new tag. then label it. i feel like its a lot of steps and messes with the re flow

**Comment by bpotchik** [comment]
This has been resolved. The dialog accepts the tag text.

<img width="250" alt="Screenshot 2024-11-24 at 11 23 44 PM" src="https://github.com/user-attachments/assets/76bfe5e3-f944-4ef3-8193-d3543dabe7b0">
