### ISSUE TITLE
Assigning structs to globals does not work

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#3492]
**Version and Platform (required):**
- Binary Ninja Version: 3708
- OS: Windows
- OS Version: 11
- CPU Architecture: x64

**Bug Description:**
Assigning structures to globals does not work

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open any binary
2. Create any struct
3. Go to .data
4. Change the type of any existing variable to the struct you just created
5. See error

**Expected Behavior:**
I expect the structure to show up in linear view

**Screenshots:**
![image](https://user-images.githubusercontent.com/8716677/193434658-b9e4c8ad-9adc-41a7-8a08-4ce3c197b761.png)

**Comment by CouleeApps** [comment]
What did you type exactly when you were giving the struct a type? Eg `test_struct` or `struct test_struct` or something else

**Comment by yrp604** [comment]
struct test_struct

**Comment by CouleeApps** [comment]
Does it work with just `test_struct`? I bet the declaration styled name makes a forward declared struct in the parser. If so I'll look at this on Monday cause I bet I know how to fix it.

**Comment by CouleeApps** [comment]
This will be fixed in dev >= 3.1.3723
