### ISSUE TITLE
BN hanging while loading of file with messed-up header

### ISSUE THREAD

**Issue by mostobriv** [Vector35/binaryninja-api#3498]
**Version and Platform (required):**
- Binary Ninja Version: 3.1.3172-dev
- OS: Windows
- OS Version: 10
- CPU Architecture: x86_64

**Bug Description:**
BN just hanging while trying to load the binary.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Just load attached binary in BN

**Expected Behavior:**
It finishes loading like IDA or GHIDRA do.

**Additional Information:**
This actually is an obfuscation, in this binary executing code lays inside of an elf header and some of header values are too big (for example number of section headers is 0xFFDA). But somehow IDA and GHIDRA manage to finish the loading pretty quickly, while BN cannot :(
[task3.zip](https://github.com/Vector35/binaryninja-api/files/9724557/task3.zip)

**Comment by plafosse** [comment]
Thanks for the report. I've fixed this bug and pushed the change, however we're in the process of moving so our build servers are down at the moment. When they come back up the next development build that comes out will contain a fix.
