### ISSUE TITLE
`BinaryNinja::OpenView` C++ API does not apply `files.universal.architecturePreference` option to load settings correctly

### ISSUE THREAD

**Issue by skr0x1c0** [Vector35/binaryninja-api#3500]
**Version and Platform (required):**
- Binary Ninja Version: 3.1.3469
- OS: MacOS
- OS Version: Ventura 13.0
- CPU Architecture: M1

**Bug Description:**
`files.universal.architecturePreference` load option is not applied correctly when C++ API function `BinaryNinja::OpenView` is used for opening universal binaries. 

https://github.com/Vector35/binaryninja-api/blob/309fc943fb48d9ce4f6f7c59f7d66bf0ca69eef1/binaryview.cpp#L4366-L4370

The value of `archEntry["loadSchema"]` is already a string containing serialized JSON value. Converting it again to JSON using `Json::writeString` will provide unexpected input to `loadSettings->DeserializeSchema`.

**Steps To Reproduce:**

Download the [test.zip](https://github.com/Vector35/binaryninja-api/files/9731201/test.zip) file and use the following c++ code to open the `test` binary using BinaryNinja C++ API.

``` 
#include <iostream>

#include <binaryninjaapi.h>
#include <binaryninjacore.h>
#include <lowlevelilinstruction.h>

using namespace BinaryNinja;


int main(int argc, char *argv[]) {
    SetBundledPluginDirectory(BNGetBundledPluginDirectory());
    InitPlugins(true);
    const char* path = "./test";
    Json::Value options;
    Json::Value archs;
    archs.append("arm64");
    options["files.universal.architecturePreference"] = archs;
    Ref<BinaryView> bv = OpenView(path, false, nullptr, options);
    std::cout << bv->GetDefaultArchitecture()->GetName() << "\n";
    return 0;
}
```

**Expected Behavior:**
The code should output "arm64" instead of "x86_64"

**Comment by bpotchik** [comment]
Fixed in `3.1.3763-dev`.
