### ISSUE TITLE
Memory leak when hitting Cancel on Open with Options

### ISSUE THREAD

**Issue by D0ntPanic** [Vector35/binaryninja-api#3501]
**Version and Platform (required):**
- Binary Ninja Version: 3.1.3736-dev
- OS: macOS
- OS Version: 12.6
- CPU Architecture: M1

**Bug Description:**
Starting to open a file with Open with Options, then cancelling it instead of going through with the load will leak a BinaryView object each time this is done. This can be verified by using the `get_memory_usage_info` function from the Python console.

**Comment by bpotchik** [comment]
Fixed in `3.1.3748-dev`.
