### ISSUE TITLE
Add setting for symbols view to hide "auto" names

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#3502]
**What is the feature you'd like to have?**
There needs to be an option in the hamburger menu for the symbols sidebar that hides "auto" names.

**Is your feature request related to a problem?**
This solves the problem where you're filtering for something, but "auto" names match your filter and you can't actually find what you're looking for.

**Are any alternative solutions acceptable?**
Being able to exclude matches when filtering would also be acceptable (and could also be implemented alongside this feature). Also, this might be obsoleted if regex filtering gets implemented first.

**Comment by plafosse** [comment]
I need a bit more clarification on this. When you say "auto" do you mean just things that start with "sub_" or "data_" or do you mean all symbols which come from the BinaryView as well "main"  "_start" etc I would assume the latter, so you could rather see "Just the things I've renamed"

**Comment by fuzyll** [comment]
Correct, this issue is about the latter. We want to just search things we've renamed.

My understanding is that manually renaming something gives it a "user" name instead of an "auto" name, but maybe I've got that wrong?

**Comment by bpotchik** [comment]
Fixed in `3.6.4664-dev`.
