### ISSUE TITLE
Some symbols are missing in database after save

### ISSUE THREAD

**Issue by lshagiev** [Vector35/binaryninja-api#3504]
Some symbols are missing in database after save, they are replaced with underscore symbol.

Binary Ninja Version: 3.1.3469 Personal and 3.1.3740-dev Personal
Platform: Windows 11 Version 2009

File:
[mach_kernel.zip](https://github.com/Vector35/binaryninja-api/files/9742157/mach_kernel.zip)

Steps to reproduce:
1) Open attached file for analysis
2) Wait until analysis is done
3) Save database
4) Close database
5) Open saved database

Symbols window during analysis
<img width="215" alt="image" src="https://user-images.githubusercontent.com/1954912/194769611-5e020696-4f1a-4d1b-9b95-d1891c7b9896.png">

Symbols window after you re-open database
<img width="211" alt="image" src="https://user-images.githubusercontent.com/1954912/194769557-51e56814-ce36-4c7e-ae3d-78d3e8eea8e9.png">

**Comment by fuzyll** [comment]
This reproed for me on a recent macOS dev build as well with the test file.

**Comment by D0ntPanic** [comment]
Fixed in build 3951
