### ISSUE TITLE
Opening fat Mach-O picks wrong architecture

### ISSUE THREAD

**Issue by comex** [Vector35/binaryninja-api#3505]
**Version and Platform (required):**
- Binary Ninja Version: 3.1.3740-dev
- OS: macOS
- OS Version: 12.5.1
- CPU Architecture: M1

**Bug Description:**
Possibly a dupe of #3500; I didn't investigate the cause.

If I try to open the arm64 slice of a Mach-O containing x86_64 and arm64 slices, it opens the x86_64 one and disassembles it as arm64.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. File -> Open; pick `libbinaryninjacore.1.dylib` from the same Binary Ninja version being run.
2. At the top of the resulting 'Open with Options' window, where it says "Universal binary detected. Select an object to load", switch from the default "Mach-O 64-bit executable x86_64" to "Mach-O 64-bit executable arm64".
3. Press Open without changing any other settings.
4. In the disassembly view, notice that `__macho_header` at the beginning of the file shows `CPU_TYPE_X86_64`, and all the function disassemblies are nonsense arm64 instructions, seemingly indicating that the wrong slice was opened.

**Additional Information:**

Something I noticed which is probably unrelated: At the bottom of the 'Open with Options' window is "* Note: Previously modified settings automatically applied for this file. <ins>Show modified settings</ins>."  But after clicking "Show modified settings", no settings are displayed (the list of settings goes blank).

**Comment by bpotchik** [comment]
As a temporary workaround, you can disable the `ui.files.restore.viewOptions` setting which obviates the bug I'll push a fix shortly and update.

**Comment by bpotchik** [comment]
Fixed in `3.1.3747-dev`.

Also, the `ui.files.restore.viewOptions` setting is now disabled by default.
