### ISSUE TITLE
Occasional crash when splitting to a new pane

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#3509]
I ran into an occasional crash on Windows when I split to a new pane. It can happen in various situations and I have not figured out what is in common yet. It is not restricted to a specific file. It happens like 2-3 time per 3-4 hours of use. So it's not very easy to reproduce.

**Comment by alureon** [comment]
I'm having this problem quite often on Linux and it's making it quite annoying to use binja.
I very briefly looked at the coredump and it seems that it's crashing in `libQt6Gui.so`.

**Comment by D0ntPanic** [comment]
This issue should be resolved as of build 3862. If it is not resolved, please let us know.
