### ISSUE TITLE
Function.set_comment_at fails when the target line is selected in UI

### ISSUE THREAD

**Issue by cxnder** [Vector35/binaryninja-api#3510]
**Version and Platform (required):**
- Binary Ninja Version: 3.1.3740-dev

**Bug Description:**
![image](https://user-images.githubusercontent.com/55725881/194926842-e4197018-84da-4b50-8543-27f65fd9d2dd.png)

`current_function.set_comment_at(here, 'text')` will always fail as a result.

**Steps To Reproduce:**
```
>>> here = 0x3d10
>>> current_function.set_comment_at(0x3d10, 'blah')
>>> current_function.comments
{}
>>> here = 0x3d11
>>> here = 0x3d11
>>> current_function.set_comment_at(0x3d10, 'blah')
>>> current_function.comments
{15632: 'blah'}
```

This also repros via manually selecting the relevant lines (instead of using `here =`

**Comment by fuzyll** [comment]
When I was searching for this, I apparently missed this issue. I've got another one open in #3682 that I'm going to close this in favor of.
