### ISSUE TITLE
Search in merge variables list

### ISSUE THREAD

**Issue by matthewfarrellex** [Vector35/binaryninja-api#3513]
Sometimes merge variables dialog have a lot of potentially unsound merges. Ability to search in them would be useful. 

Perhaps reducing the number of variables that can be merged somehow would also be a good solution.

**Comment by xusheng6** [comment]
Closing in favor of https://github.com/Vector35/binaryninja-api/issues/4896

**Comment by plafosse** [comment]
These features will all be present in 3.6.4772.

* Merge Variables Dialog now has a search
* Merge Variables now has suggested merges that are at the top of the list
* A new 'Merge Variables Here' option is available in the menu and hotkey '+' if you're in HLIL/Pseudo-C and you've selected the index of a variable-to-variable assignment.
