### ISSUE TITLE
Support for different address presentation in views

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#3517]
Currently (If I'm not wrong) we see address all time time.

Support for address presentation options like below list would be useful. I can currently change display format for address presentation in right bottom, but it does not affects views.

* segment:offset
* section:offset
* segment or section name:offset
* function offset

**Comment by yrp604** [comment]
Also module+offset please.

**Comment by CouleeApps** [comment]
This has been implemented as of 4.1.5224-dev
