### ISSUE TITLE
Creating user function with does not update linear disassembly view

### ISSUE THREAD

**Issue by kristopax** [Vector35/binaryninja-api#3518]
**Version and Platform (required):**
- Binary Ninja Version: 3.1.3745-dev
- OS: macOS
- OS Version: Monterey 12.0.1
- CPU Architecture: M1

**Bug Description:**
When creating a user function via the python bv.create_user_function API with analysis.linearSweep.autorun disabled, the Linear Disassembly view does not update to reflect the new function.  If you switch the view to Graph Disassembly and then back to Linear Disassembly, then the view is updated to reflect the new function.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open with options the attached binary (ex3_initiator), ensure imageBase=0x10000, and disable analysis.linearSweep.autorun
2. Switch view to Linear Disassembly
3. Navigate to 0x12e0c and verify that function is not defined
4. In the Python Console, enter the following : 

`bv.create_user_function(0x12e0c)`

5. Verify that the function is not updated in the Linear Disassembly view
6. Verify that the function is actually created by entering the following in the Python Console:

`bv.get_functions_at(0x12e0c)`

7. Switch view to Graph Disassembly view and verify that the function is present in the view. 
8. Switch view back to Linear Disassembly view and verify that the function is present in the view. 
9. Drop the mic and exit stage 

**Expected Behavior:**
After calling bv.create_user_function(0x12e0c), I expected the Linear Disassembly view to automatically update with the newly defined function.

**Screenshots:**
![create_user_function_bug_screeenshot](https://user-images.githubusercontent.com/79866371/195098676-0d23d034-d2cf-4b46-91fd-349c115cc94b.png)
[ex3_initiator.zip](https://github.com/Vector35/binaryninja-api/files/9756078/ex3_initiator.zip)

**Comment by bpotchik** [comment]
Fixed in `3.1.3750-dev`.
