### ISSUE TITLE
immediates are namable but shouldn't be

### ISSUE THREAD

**Issue by I-am-Batman** [Vector35/binaryninja-api#352]
An undo following renaming an immediate or defining it as a function does not display the change until view is changed and changed back (such as to a different function and back to the original one), or undoing to a change which properly causes the undoes to display. Video example. 
[uhoh.zip](https://github.com/Vector35/binaryninja-api/files/379911/uhoh.zip)

**Comment by psifertex** [comment]
There are some generic bugs we have in the undo refresh not working that is fixed in dev. 

The problem in this case though is actually that you're able to name the immediate constant value at all. Those aren't supposed to be namable so I'm going to rename this bug accordingly.

**Comment by D0ntPanic** [comment]
Fixed in dev
