### ISSUE TITLE
Renaming a structure duplicates it

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#3523]
**Version and Platform (required):**
- Binary Ninja Version: 3.1.3751-dev
- OS: Windows
- OS Version: 10
- CPU Architecture: x64

**Steps To Reproduce:**
1. Create a structure
2. Press Y and rename it 
3. See it gets duplicated and renamed

I can rename it with N, bug is in renaming it with Y.

**Screenshots:**
Before renaming:
![before_renaming](https://user-images.githubusercontent.com/109607896/195286330-f75b9d00-d11d-41d5-a705-1bf4574a1c53.PNG)

After renaming:
![after_renaming](https://user-images.githubusercontent.com/109607896/195286337-044f14b0-533d-4a93-9706-7aeadefcd028.PNG)

**Comment by CouleeApps** [comment]
This will be fixed as of 3.3.4010-dev. Now changing the name in the type definition editor will rename the type and then change its contents. This only happens as long as the new definition has only one type.
