### ISSUE TITLE
Cannot set the integer display type of an integer enum

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#3534]
We have made some improvements on enum type propagation and now we correctly render these integer enum as their name, rather than the hex value. E.g.,

```
100003e40      enum foobar var_28
100003e40      if (var_28 == foo3)
```

However, occasionally we wish to view the integer in other formats, even if the name is probably the most useful one. There is no way to do it since the `foo3` token is a `KeywordToken`, and we reject setting display type on such tokens.

**Comment by cxnder** [comment]
Resolved in builds >= 3.2.3974
