### ISSUE TITLE
Console Log - "Fold Lines Like This"

### ISSUE THREAD

**Issue by ccarpenter04** [Vector35/binaryninja-api#3537]
**What is the feature you'd like to have?**
In IntelliJ and other Jetbrain IDEs, they have an option to fold lines that match a certain pattern you define. This is useful when you need to run code with heavy debug logging enabled because it allows you to collapse many, sometimes most, lines that are being printed so you can focus on just the logging related to the problem you're working on. I'd like to have a similar feature in Binary Ninja so that I can enable debug logging and locate the logging I'm interested in much more easily and without the console buffer running out of space so quickly.

**Is your feature request related to a problem?**
Not a particular problem but it would make it much easier to locate debug information for the development team and it would make it easier to make comprehensive bug reports.

**Additional Information:**
IntelliJ allows highlighting a string, right clicking, and selecting Fold Lines like this. It brings up a dialog allowing you to tweak the conditions and regex and overall allows you to get debug information much more easily. I think it would be very beneficial. 

<img width="407" alt="image" src="https://user-images.githubusercontent.com/2475433/195745913-75ded15e-0140-4cbb-8de0-aecf3fabb185.png">

and it's representation when it has collapsed lines:

<img width="146" alt="image" src="https://user-images.githubusercontent.com/2475433/195746049-04b12d47-9a67-424c-97d3-d952d7e396f9.png">

**Comment by plafosse** [comment]
Though this would be a valuable feature our log does support filtering and categorizing and so we'll unlikely be implementing this request.
