### ISSUE TITLE
Rendering glitch (afterimage) in xref widget

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#3538]
https://user-images.githubusercontent.com/94503187/195772727-88e1b78e-93e1-4bac-8a04-fde52567f984.mov

As we can see from the attached recording, there is a weird glitch in xref widget, when the xref preview is wider than the widget's width. When I scroll to the right, we can see the xref count number is duplicated several times. When I hover my mouse over them, they would disappear. If I scroll back, the xref count number does not show up until I hover over the same position.

This is not a new bug -- it is introduced between the stable 3.0 and stable 3.1. During which time, we did no changes to the xref code. So I somehow think this is actually a Qt glitch.

**Comment by xusheng6** [comment]
related to #3466 . Issue #3466 actually shadows this issue that we cannot scroll the xref widget at all. once #3466 is fixed, the current issue becomes noticable

**Comment by D0ntPanic** [comment]
Fixed in 3.6.4570
