### ISSUE TITLE
Option for making cross-references dockable /dialog

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#3539]
Currently we have to keep the sidebar open if we want to see the cross-references. Most of the time I use 2 view (disassembly + HLIL/Pseudo-C). It's kind of annoying that the sidebar has to be open to see the cross-references.

I tried to dock cross-references into my disassembly view, but looks like it does not support it. But pinned cross-references can docked into views.

So, if we can dock cross-references into views just like pinned cross references, this could save us from opening sidebar. 

Another way in order to solve this would be making cross-references a dialog. Both can be good solutions to save us from having to open the sidebar.

**Comment by galenbwill** [comment]
Note that there are [default hotkeys](https://dev-docs.binary.ninja/guide/index.html#cross-reference-hotkeys) defined for the cross references pane:

* `x` - Focus the cross-references pane
* `[SHIFT] x` Create a new pinned cross-references pane
* `[OPTION/ALT] x` - Navigate to the next cross-reference
* `[OPTION/ALT-SHIFT] x` - Navigate to the previous cross-reference

The following are only available when the cross-references pane is in focus:

* `[CMD/CTRL] f` - Open the filter dialog
* `[ESC]` - Clear the search dialog
* `[CMD/CTRL] a` - Select all cross-references
* `[ARROW UP/DOWN]` - Select (but don't navigate) next/previous cross-reference
* `[ENTER]` - Navigate to the selected reference

**Comment by psifertex** [comment]
As of version 4.0.4911 , all panes now have the ability to be either floating windows or separate windows (right-click on the pane icon and select "floating" or "window"). We're also tracking #5987 for the ability to make it a true modal dialog, but for a pure windowed menu this is done!
