### ISSUE TITLE
Don't create data variables for addresses that are code

### ISSUE THREAD

**Issue by D0ntPanic** [Vector35/binaryninja-api#355]
If code takes an address of code, the analysis may create a data variable at that address.  Because it is in the middle of code, linear view won't even show this data variable, but it will be highlighted with a name.  Update the analysis to not create automatic data variables that refer to regions of known code.

**Comment by plafosse** [comment]
There has been some mitigation to this issue at some point in the past. Please let us know if you run into this issue.

**Comment by jeffli678** [comment]
I am still sometimes seeing data variables created  at the start of a function. In some cases, the start of the function is indirectly referenced, e.g., by _libc_start_main, so I think the data variable is fine. 

Also, this reminds me of another issue that we do not render data vars if they overlap with the code. I believe that needs to be fixed as well.
