### ISSUE TITLE
Show total/filtered item count in symbols, strings etc

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#3566]
Currently windows like Symbols and Strings does not shows how many items they have. Support for showing item count both in filtered non-filtered would be useful.

**Comment by op2786** [comment]
I think this is duplicate of #3415... I do not closing this because other issue does not include Strings window.

**Comment by psifertex** [comment]
I'm closing this and will edit the other to match. They're already linked just by virtue of referring to it so we won't miss the request for both. A test branch already exists for this feature hopefully it will get landed shortly after the next stable.
