### ISSUE TITLE
Tags and comments are duplicated on instructions that is exactly one-byte long

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#3568]
We are showing tags twice if the tag is added to an instruction that is one-byte long.

![Screen Shot 2022-10-20 at 4 51 18 PM](https://user-images.githubusercontent.com/94503187/196903100-f62191fd-42cf-4a23-85d8-753dc1eae1f7.png)

As I tested (not shown in the screenshot), this has nothing to do with the instruction being at the function start, only its length matters.

This is causing https://github.com/Vector35/debugger/issues/272.

**Comment by xusheng6** [comment]
![Screen Shot 2022-10-20 at 10 35 53 PM](https://user-images.githubusercontent.com/94503187/196978975-5de458da-e6df-4fd6-8bf4-74d081752cc3.png)

Comments are also duplicated, since they are processed by the same logic as tags

**Comment by psifertex** [comment]
This was a regression introduced between 2.4 and 3.0.
