### ISSUE TITLE
Update Channel not updated in 1.0.300

### ISSUE THREAD

**Issue by CryptoMonkey** [Vector35/binaryninja-api#357]
OSX 10.11.6
Binary Ninja 1.0.300, build ID c1c9e369

When you move from the beta version to the pre-release version (1.0.300), the update channel is not automatically reset to the "Latest Binary release" from "Private Beta" which makes auto-update immediately downgrade the application back to the beta.  

You have to shut off auto-update, install the new version, switch channels and then you can turn auto-update back on.

**Comment by psifertex** [comment]
Hmm, good point. We can force the new builds to switch channels but that would be annoying for later when we do have multiple channels the user wants to select from.

Not sure the best way to resolve it until then. We'll see if we can figure something out to make it a smoother process. Thanks for the report.

**Comment by psifertex** [comment]
We've adjusted the license config so this shouldn't be a problem going forward. Thanks for the report.
