### ISSUE TITLE
Variable name is missing in Pseudo C windows

### ISSUE THREAD

**Issue by ElvisBlue** [Vector35/binaryninja-api#3576]
**Version and Platform (required):**
- Binary Ninja Version: 3.2.3786-dev Personal (Build ID  85f1719)
- OS: Windows
- OS Version: Windows 10
- CPU Architecture: x64

**Bug Description:**
Variable name is missing in Pseudo C windows

**Steps To Reproduce:**
1. Load the binary in attachment to Binary Ninja
2. Goto function address "sub_11ba"

**Expected Behavior:**
Variable name should be show as HLIL Windows

**Screenshots:**
![image](https://user-images.githubusercontent.com/32590178/197131710-14378a01-fab7-4b20-a222-529d213f15ff.png)

[revme.zip](https://github.com/Vector35/binaryninja-api/files/9836409/revme.zip)

**Comment by CouleeApps** [comment]
Looks like the pseudo c renderer is missing a call to `HighLevelILFunction::GetVariableNameOrDefault`. Good find.

**Comment by CouleeApps** [comment]
This will be fixed in 3.2.3791
