### ISSUE TITLE
Go to element /structure in types pane instead of Types sidebar if there is one

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#3579]
Let's say I've 2 pane HLIL and Types (not sidebar) and sidebar is closed.  When I navigate in HLIL and double click on any structure elements or structure name, it reopens sidebar and navigates to element /structure in Types sidebar. 

I think there should be some kind of check, if there is a already opened types pane, then do not open Types sidebar and navigate to element /structure in types pane.

**Comment by CouleeApps** [comment]
Good idea for navigation. This will be done in 3.2.3790-dev.
