### ISSUE TITLE
implement MIPS pseudo instructions 

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#358]
Wikipedia has a list of the pseudo instructions implemented by the standard MIPS assembler that Binary Ninja should implement for disassembly: 

https://en.wikipedia.org/wiki/MIPS_instruction_set#Pseudo_instructions

**Comment by plafosse** [comment]
These are implemented and have been for some time. There was a recent bug fix that prevented them from working on MIPSEL.  I'll reopen this if there are some specific pseudo instructions missing.
