### ISSUE TITLE
Structure does not automatically expand when navigating into to its fields

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#3585]
* Binary Ninja Version: 3.2.3782-dev
* OS: Windows 10 x64

**Bug Description:**
When I double click on a field of structure that is collapsed in Types sidebar, Binary Ninja focuses on sturcture in Types sidebar but does not automatically expands the structure. So, it shows it like this:

![not_expanded](https://user-images.githubusercontent.com/109607896/197206397-27602a15-793f-4330-8995-f1f10643ef3d.PNG)

**Expected Behavior:**
I expect Binary Ninja to expand the structure automatically.

**Comment by CouleeApps** [comment]
Looks like the type was not marked as expanded properly. This will be fixed in 3.2.3789.
