### ISSUE TITLE
'displayIdentifiers' Doesn't Update in All Cases in Settings UI

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#3587]
* Binary Ninja Version: 3.2.3782-dev
* OS: Windows 10 x64

**Bug Description:**
See the GIF please. I don't know if this is intended but it looks suspicious.

**Screenshots:**
![Recording 2022-10-21 at 16 10 26](https://user-images.githubusercontent.com/109607896/197217451-817601a1-012a-477f-9884-272873e618d2.gif)

**Comment by bpotchik** [comment]
Fixed in `3.2.3789-dev`.
