### ISSUE TITLE
Line numbers and addresses are not highlighted when clicked in IL view

### ISSUE THREAD

**Issue by micro500** [Vector35/binaryninja-api#359]
![example](https://cloud.githubusercontent.com/assets/10532511/17153180/5a31c318-5349-11e6-9aad-09a87e9e270b.png)

In the example above I clicked on the "49" on line 55 and expected to see the "49" on line 49 to be highlighted, but it was not. The same thing happens if I click the address for line 49.

**Comment by plafosse** [comment]
Fixed in v1.1.1429
