### ISSUE TITLE
Allow renaming enum members with N key

### ISSUE THREAD

**Issue by zackorndorff** [Vector35/binaryninja-api#3594]
**What is the feature you'd like to have?**
Similar to how you can press N on the use of a struct member, it would be useful to be able to press N to rename an enum member from one of its uses

**Are any alternative solutions acceptable?**
The N hotkey does work in the Types view, which is usable enough as a substitute.

**Comment by plafosse** [comment]
Fixed in 3.4.4294

**Comment by plafosse** [comment]
Unfortunately there is a bug that causes this to be less useful. https://github.com/Vector35/binaryninja-api/issues/4341
