### ISSUE TITLE
Support collapsing long enums as members

### ISSUE THREAD

**Issue by zackorndorff** [Vector35/binaryninja-api#3595]
**What is the feature you'd like to have?**
In the Types view, long enums have a arrow so you can collapse them. However, if you make a struct with one member being the enum, it inlines the whole enum into that struct's definition, making it hard to read.

**Are any alternative solutions acceptable?**
Named enums could just show the name and then allow double click to find the definition, rather than displaying inline.

**Comment by negasora** [comment]
Not sure if I'm misunderstanding this, was the full definition of `test_enum` included in the definition of `test_struct`? 
I couldn't get it to show up in versions going back to `3.1.3771-dev`.
![image](https://user-images.githubusercontent.com/3020965/213023318-29bfa73c-7247-4711-b97a-797a77893910.png)

**Comment by zackorndorff** [comment]
I think I have to admit to a bit of PEBKAC here, sorry for the incomplete report. You're exactly correct, for some reason I inlined the enum definition while reversing it out.

Here's the screenshot:

<img width="343" alt="Screenshot 2023-01-17 at 7 37 29 PM" src="https://user-images.githubusercontent.com/14002032/213051899-d4605f08-ea7b-4dad-9bb1-49027bc8e1e3.png">

And here's the struct definition:

```c
struct parsed_input __packed
{
    char firstword[0x8];
    int64_t padding;
    char rest[0x1ff];
    __padding char _20F[1];
    int32_t rest_len;
    enum : uint32_t
    {
        REIN = 0x1,
        TYPE = 0x2,
        SIZE = 0x3,
        REST = 0x4,
        MLST = 0x5,
        STOU = 0x6,
        LIST = 0x7,
        RMDA = 0x8,
        EPRT = 0x9,
        FEAT = 0xa,
        QUEU = 0xb,
        STOR = 0xc,
        RMD = 0xd,
        CDUP = 0xe,
        PORT = 0xf,
        PASS = 0x10,
        APPE = 0x11,
        NLST = 0x12,
        FREE = 0x13,
        HELP = 0x14,
        VIEW = 0x15,
        QUIT = 0x16,
        MKD = 0x17,
        MLSD = 0x18,
        PASV = 0x19,
        PWD = 0x1a,
        RNTO = 0x1b,
        DELE = 0x1c,
        MODE = 0x1d,
        RETR = 0x1e,
        EXEC = 0x1f,
        CWD = 0x20,
        EPSV = 0x21,
        STRU = 0x22,
        USER = 0x23,
        RNFR = 0x24,
        SYST = 0x25,
        MDTM = 0x26
    } command_enum;
};
```

... notice a similarity?

If I replace that inline struct with a "normal" enum, it displays exactly as expected.

I reverted to the previous stable and verified this was true then, which was only ~20 builds away from the version I was using at the time, so I'm not sure what I was thinking with that struct definition.

This probably falls into the "WONTFIX, use a proper enum instead" category, unless you think it's worth handling anonymous enums specially. (Do the typelibs for any major platform use anonymous enums a lot?)

Thanks for taking a look!

**Comment by negasora** [comment]
Thanks for the report! Collapsing type members is tracked by https://github.com/Vector35/binaryninja-api/issues/3758 - closing in favor of that issue
