### ISSUE TITLE
Types sidebar missing horizontal scrollbar

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#3597]
- Binary Ninja Version: 3.2.3801-dev
- OS Version: Windows 10 x64

**Bug Description:**
Types sidebar missing horizontal scrollbar

**Comment by CouleeApps** [comment]
This has become a lot more annoying now that the C++ types add a bunch of horizontal noise to structure definitions. Almost none of the useful information about my type is visible without scrolling or expanding the sidebar, which makes the types sidebar basically unusable as a result.
![image](https://user-images.githubusercontent.com/711973/232600533-5d804922-b345-46b6-bda1-bc35dadf9652.png)

**Comment by D0ntPanic** [comment]
Fixed in 3.4.4246
