### ISSUE TITLE
Changing type of `void` variables are buggy

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#3599]
- Binary Ninja Version: 3.2.3801-dev
- OS: Windows 10 x64

**Bug Description:**

In this example code, when I try to change type of `var_250` it shows me a last type I typed on change type dialog. I expect it to show me `void var_250`. I can reproduce this with all variables that have type `void` (not void pointer).

```
void var_250
Ordinal_mfc140_1089(&var_250)
```

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open any binary
2. Find a variable that have type `void`
3. Press `Y` in order to change its type
4. See last type instead of void xxx

**Screenshot**

![Recording 2022-10-24 at 09 56 11](https://user-images.githubusercontent.com/109607896/197476154-9f719097-3f49-4639-afb4-15ec5756ab01.gif)

**Comment by negasora** [comment]
Fixed in 3.2.3836-dev
