### ISSUE TITLE
Wrong x86 Disassembly

### ISSUE THREAD

**Issue by bdarmofal** [Vector35/binaryninja-api#360]
BN's dissassembly parser incorrectly defines the instruction:
VMLAUNCH as consisting of the 2 opcode bytes: "0F 01" instead of "0F 01 C2"

This error destroys (by misalignment) the disassembly of all functions containing instructions that start with "0F 01" such as MWAIT, XGETBV, VMCALL, etc.

**Comment by bdarmofal** [comment]
Note: In addition to IDA, objdump disassembles these routines correctly

**Comment by psifertex** [comment]
Unfortunately, we have no support for kernel model disassembly right now for multiple other reasons as well. Even if we fix this particular flaw, there are some other problems you'll run into with hypervisor code as well (#17, #63, eg).

We definitely plan to better support ring 0 and ring -1 disassembly, but it's unfortunately not supported at this time.

**Comment by plafosse** [comment]
fixed in dev
