### ISSUE TITLE
Crash when creating /modifying a very big structure field

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#3600]
- Binary Ninja Version: 3.2.3801-dev
- OS: Windows 10 x64

**Bug Description:**
I guess this is very edge case one, but bug is a bug.

**Steps To Reproduce:**
1. Create new type like this
```c
struct crash_test {
    int64_t field_0[0x9999985d8a0000];
};
```
2. Now try to set `field_0` type into `int64_t field_0[1]` by pressing `Y` on it
3. See the crash

**Additional Information:**
Stack trace:
```
binaryninjacore!BNRegisterTransformType+0x35f66
binaryninjacore!BNRegisterTransformType+0x386e
binaryninjacore!BNRegisterTransformType+0xeffe
binaryninjacore!BNRegisterTransformType+0x240e3
binaryninjacore!BNRegisterTransformType+0x1a91d
binaryninjacore!BNTypeParserPreprocessSource+0x24a9
binaryninjacore!BNGetTypeLines+0xf1
```

**Comment by psifertex** [comment]
Given how unlikely this is to be triggered by accident, we're bumping this to the next release.

**Comment by galenbwill** [comment]
Should be fixed in builds >= 3971
