### ISSUE TITLE
Cross References Navigation with Keyboard

### ISSUE THREAD

**Issue by bpotchik** [Vector35/binaryninja-api#3606]
The workflow for trying to use the keyboard to scan through the xrefs list doesn’t seem optimal. Using the mouse with double clicking is the only way afaik to scan the surrounding code from an xref.

An improvement could be to:
1) When using the 'enter' key to trigger navigation in xrefs, keep focus on the current xrefs list item.
2) The tab key could be used to move focus into a View
3) Using arrow keys + some other modifier to trigger auto-navigation (again without losing focus).

**Comment by bpotchik** [comment]
This feature may also be applicable for other list item types like search results, strings, etc.

**Comment by bpotchik** [comment]
There are default keybindings for the desired behavior behind `alt+x` and `alt+shift+x`.

**Comment by psifertex** [comment]
The existing hotkeys mentioned above are the intended solution to the problem for now. We'll re-open this if we decide to re-visit it with another solution.
