### ISSUE TITLE
Empty tab title when creating new binary data

### ISSUE THREAD

**Issue by D0ntPanic** [Vector35/binaryninja-api#3607]
**Version and Platform (required):**
- Binary Ninja Version: 3.2.3810 (Build ID 5f5ac682)
- OS: macOS
- OS Version: 13.0
- CPU Architecture: M1

**Bug Description:**
Select "New Binary Data".

Observe the tab title (or lack thereof).

<img width="123" alt="Screenshot 2022-10-26 at 2 45 13 PM" src="https://user-images.githubusercontent.com/7007406/198134233-96b93487-7e56-4e93-9d63-1a400329b28c.png">

The dot is because it is modified.

**Comment by CouleeApps** [comment]
This was a bug in the debugger. It was fixed in https://github.com/Vector35/debugger/commit/8bac123569d9be9793afc0fe18afc8949f81c4f6
