### ISSUE TITLE
Filter count is backwards

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#3608]
**Version and Platform (required):**
- Binary Ninja Version: 3.2.3811
- OS: macOS
- OS Version: 12.6
- CPU Architecture: M1

**Bug Description:**
The count of items in the filter displays shows the total number of items removed, not the total remaining. This is too backwards for my primitive reversing brain to understand and I expected it to be the other way around.

**Steps To Reproduce:**
1. Find all on any query
2. In the results, open the filter and enter a filter
3. Observe the number goes up when the filter gets longer

**Expected Behavior:**
I expected the result number to go down when the filter became more specific and there were fewer results remaining.

**Screenshots:**
![image](https://user-images.githubusercontent.com/711973/198154089-a65e5f5a-0eb3-4baa-b3fd-e0827ee21655.png)

**Additional Information:**
This seems to also apply to cross references

**Comment by CouleeApps** [comment]
Fixed in 3.2.3830-dev

**Comment by CouleeApps** [comment]
Reopened in 3.2.3858-dev due to previous implementation causing #3660

**Comment by plafosse** [comment]
This was fixed at some point prior to 4.0
