### ISSUE TITLE
Cross References previews should be 'view' sensitive

### ISSUE THREAD

**Issue by galenbwill** [Vector35/binaryninja-api#3610]
**Version and Platform (required):**
- Binary Ninja Version: 3.2.3813 (stable and dev)
- OS: macOS
- OS Version: 12.6
- CPU Architecture: M1

**Bug Description:**
When a Pseudo C view is active, the Cross References pane shows no previews for local variables, neither Pseudo C nor disassembly.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open any binary
2. Switch to Pseudo C view (F5)
3. Select any local variable (stack, register, or parameter)
4. See no preview in the Cross References pane

**Expected Behavior:**
Pseudo C previews should be shown in the Cross References pane.

**Comment by rssor** [comment]
Implemented on dev as of last week, it makes a best effort attempt to find the corresponding IL instruction in the active view. Failure preserves the existing behavior of falling back to disassembly.
