### ISSUE TITLE
"Paste from Hex Dump" skips first byte

### ISSUE THREAD

**Issue by cxnder** [Vector35/binaryninja-api#3612]
**Version and Platform (required):**
- Binary Ninja Version: 3.2.3812
- OS: macOS x86-64
- OS Version: 12.4

**Bug Description:**
When 'Paste from hex dump'-ing the following string into a new BinaryView, it skips the first byte

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Cmd+N
2. "Paste from hex dump"
3. ```aa 01 02 03 04 05 06 07```

**Expected Behavior:**
It should not do that

**Comment by negasora** [comment]
`Hex Dump` expects something like the format given by xxd where the first chunk is an address
```
00000000: 6173 64                                  asd
```
The behavior you're looking for is `Paste From > Raw Hex`
