### ISSUE TITLE
Cross References Pane High CPU Utilization

### ISSUE THREAD

**Issue by bpotchik** [Vector35/binaryninja-api#3613]
The cross references view contains a race condition which keeps it from quiescing the painting logic.

**Steps To Reproduce:**
1. Open any binary
2. Let analysis finish
3. Observe CPU utilization
4. Adding additional panes and clicking around can start/stop the excessive painting.

For example, a layout like the following:
![Screen Shot 2022-10-28 at 9 04 16 AM](https://user-images.githubusercontent.com/29309548/198607243-f5f72093-2a37-4002-9b14-d88a9a22bc5a.png)

Produces anywhere from 7% to 12% CPU utilization.
<img width="339" alt="Screen Shot 2022-10-28 at 9 03 59 AM" src="https://user-images.githubusercontent.com/29309548/198608040-5b38d245-4983-408d-b1d2-32caf8ff3a92.png">

**Comment by plafosse** [comment]
Fixed in 4.0 Stable
