### ISSUE TITLE
Ability to cancel Checking for Updates

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#3615]
**Version and Platform (required):**
- Binary Ninja Version: 3.2.3814
- OS: macOS
- OS Version: 12.4
- CPU Architecture: M1

**Bug Description:**
While there is a button to disable _downloading_ an update, there's no way to disable the updater before it actually starts downloading.

**Steps To Reproduce:**
1. Open an outdated build with auto updates enabled
2. Watch status bar
3. Realize you can't cancel during "Checking for Updates"
4. Look away for 3 seconds and come back to "update downloaded" (optional)

**Expected Behavior:**
I expected to be able to cancel the updater in every phase of the process.

**Comment by D0ntPanic** [comment]
Added in build 3979
