### ISSUE TITLE
Add function level register reference view

### ISSUE THREAD

**Issue by inaryart** [Vector35/binaryninja-api#3618]
**What is the feature you'd like to have?**
Looking at the disassembly can help to quickly understand if the register has been modified. can display read and write properties for it.
when i click on the `rax` register
```
mov  rax ,1  // write
mov  al ,1  // write
mov rbx, rax // read
mov [rax+8], 1 // write with offset
```

**Is your feature request related to a problem?**
na

**Are any alternative solutions acceptable?**
na

**Additional Information:**
na

**Comment by psifertex** [comment]
Some of this information is already available. Simply hover over an instruction in disassembly and you can see a summary of what is done to all registers or memory. Here's a few examples:

<img width="729" alt="Screenshot 2023-01-02 at 2 26 23 PM" src="https://user-images.githubusercontent.com/140215/210271780-f0079091-4261-4261-a22e-2f36022480a9.png">

<img width="313" alt="Screenshot 2023-01-02 at 2 28 37 PM" src="https://user-images.githubusercontent.com/140215/210271923-626bae1c-b8c7-4957-a86f-c288b2aa4357.png">

We have no plans to implement this as a first-class feature, but you could definitely implement this as a plugin or a snippet. If you're interested in that, feel free to drop into the api-help channel on the [public slack](https://slack.binary.ninja/) and we can give you some suggestions.
