### ISSUE TITLE
Strings sidebar hides `\n` from strings

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#3621]
- Binary Ninja Version: 3.2.3814-dev
- OS: Windows 10 x64

**Bug Description:**
Looks like strings sidebar remove all `\n` from strings in order to show strings beautifully in views. But I think this can lead to not finding a string in some situations.

**Expected Behavior:**
I expect BN escapes `\n` instead of removing them.

**Screenshots:**
![escape_new_lines](https://user-images.githubusercontent.com/109607896/198966187-9443060c-663d-4549-abd0-0d2767649a4d.png)

**Comment by blue-devil** [comment]
I have replicate this issue on Binary Ninja macOs version too.

**Comment by cxnder** [comment]
Resolved in builds >= 3.2.3947
