### ISSUE TITLE
Looks like memory does not give back to OS after closing a database

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#3623]
- Binary Ninja Version: 3.2.3814-dev
- OS: Windows 10 x64

**Steps To Reproduce:**
1. Open Binary Ninja and note the RAM usage 
2. Open some binary in Binary Ninja and note the RAM usage 
3. Close the tab for opened binary and note the RAM usage
4. Compare noted RAM usages

**Screenshots:**
**Example 1**:
IDLE:
![ramidle](https://user-images.githubusercontent.com/109607896/199010112-e3b17eb5-09a3-4216-b9fc-5a6b7071a565.png)

Binary loaded:
![ram_binary_loaded](https://user-images.githubusercontent.com/109607896/199009261-5cc9f985-f3b2-4b68-bacf-57a658b66915.png)

Binary unloaded:
![ram_binary_unloaded](https://user-images.githubusercontent.com/109607896/199009300-8061ebc8-d669-4c6a-b678-cab0d7aad558.png)

**Example 2**:
IDLE:
![ramidle](https://user-images.githubusercontent.com/109607896/199010509-70fbeed1-1040-45d2-b9d1-cfc70b101a4f.png)

Binary loaded:
![ram_binary_loaded](https://user-images.githubusercontent.com/109607896/199010519-7783c44d-4dc9-4ed7-a6dd-f5c1c928f30e.png)

Binary unloaded:
![ram_binary_unloaded](https://user-images.githubusercontent.com/109607896/199010530-f788bb25-9b2b-4d70-abb5-b9be8299c54c.png)

**Comment by psifertex** [comment]
Some amount of resources are saved and to some degree I believe this is expected (but will double check with Rusty who last worked on memory utilization). 

The true test is if you continually re-open and close the same file (or multiple different files), does memory continue to grow each time and I don't believe that is the case at least it doesn't appear to be in the quick tests I just ran.
