### ISSUE TITLE
Unicode String support

### ISSUE THREAD

**Issue by bdarmofal** [Vector35/binaryninja-api#363]
ASCII strings referenced by LEA instructions are correctly printed as hints on the same line as the reference.  Unicode strings are not displayed due to the 0x00 high bytes found between letters for typical English strings.

Suggestions:
1) Detect use of Unicode strings and store accordingly
2) When Unicode strings are in use, switch to 2x null bytes for end of string detection

**Comment by negasora** [comment]
Added in 1.1.1300-dev.
