### ISSUE TITLE
Need getParentFunction() Method for Instructions

### ISSUE THREAD

**Issue by bdarmofal** [Vector35/binaryninja-api#364]
When writing Python plug-ins that act on individual instructions, getting a handle to the function that contains the selected instruction is not fun.

Add a getParentFunction() method to the instruction object or add a getFunctionContainingAddr( virtualAddress ) method.

**Comment by plafosse** [comment]
Though this sounds like an easy thing, since we support multiple overlapping basic blocks and functions it is not as simple as just getting the address of a function.  
If there is no overlapping basic blocks the following code works and isn't difficult
`bv.get_basic_blocks_at(address)[0].function`
