### ISSUE TITLE
Scripting console uses Unicode line seperators (e280a9 (utf8)) 

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#3646]
I notice that the Scripting Console, e.g., the Python console, uses Unicode line separator. The separator is not widely supported, and it causes the line separator to be missing when the console output is copied to other tools, e.g., VSCode. We should replace it with '\n` for better compatibility

**Comment by xusheng6** [comment]
This is probably due to Qt update -- iirc it works fine when I copy and paste the console output to other tools

**Comment by plafosse** [comment]
This has been resolved with a Qt update.
