### ISSUE TITLE
TypeView filter status gets cleared randomly. 

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#3647]
**Version and Platform (required):**
- Binary Ninja Version: 3.2

**Steps To Reproduce:**
1. Open a binary and click on types window
2. Click "Show system types"
3. Navigate around, open/close panes, etc
4. See filter setting get reset

**Comment by CouleeApps** [comment]
So I'm pretty sure the original bug here was an issue with pane splitting causing duplicate sidebar widgets to be created. As of recent versions the sidebar UI has been redone and this behavior no longer happens.
