### ISSUE TITLE
"File Modified, save before closing?" popup displays nothing as the filename on untitled files

### ISSUE THREAD

**Issue by cxnder** [Vector35/binaryninja-api#3650]
**Version and Platform (required):**
Binary Ninja Version: 3.2.3834, e88d9c23
Platform: macOS Monterey (12.4)

**Bug Description:**
"File Modified, save before closing?" popup displays nothing as the filename on untitled files

![image](https://user-images.githubusercontent.com/55725881/200976524-b1f520cd-d8f5-4a8e-9d1d-b4ebf892d777.png)

**Expected Behavior:**
Should probably display something similar to "Untitled File Modified", etc.

**Comment by psifertex** [comment]
Other than the fact that there's two spaces visible this actually strikes me as not a problem?

**Comment by cxnder** [comment]
Resolved in `4a95fe45`
