### ISSUE TITLE
Filtered Item Count on sidebar widgets can entirely cover text 

### ISSUE THREAD

**Issue by cxnder** [Vector35/binaryninja-api#3651]
**Version and Platform (required):**  
Binary Ninja Version: 3.2.3834, e88d9c23  
Platform: macOS Monterey (12.4)

**Bug Description:**
When the sidebar is thin, the filter count can entirely elide any text being typed in the filter box. This is a usability issue, especially when running multiple windows, where users may have to make sidebars as small as possible. 

Fixing the sidebar minimum width at a higher value would be annoying in the multiple-window setup, where it would force always hiding the sidebar or H-scrolling much more.

![image](https://user-images.githubusercontent.com/55725881/200977375-cea9e9a2-766b-4092-8c2b-2d619cd07f64.png)

**Expected Behavior:**
* A setting to disable this
and one of 
* Having the filter count be hidden at smaller widths
or
* Moving the filter somewhere else

**Comment by CouleeApps** [comment]
Through the power of gradients, your query is no longer covered, but instead covers the numbers.
![image](https://user-images.githubusercontent.com/711973/200978774-60379e24-b6f2-41cc-9ddb-6170c4014fa4.png)

Will be version 3.2.3837
