### ISSUE TITLE
Undefining a function does not clear it from UI

### ISSUE THREAD

**Issue by cxnder** [Vector35/binaryninja-api#3654]
**Version and Platform (required):**
Binary Ninja Version: 3.2.3834, e88d9c23
Platform: macOS Monterey (12.4)

**Steps To Reproduce:**
1. ⌘+N 
2. `00 01 02 03 04 05 06 07 08` -> Paste From Hex Dump
3. Swap to Linear View, define function at `0x0` as armv7
4. Undefine function

Symbol will disappear from sidebar.
Function will not disappear from Linear View
`current_function` will still hold a function object. Same with `current_basic_block`

Swap to Hex view and back to linear to actually have it be 'undefined'

**Expected Behavior:**
"Undefine function" should undefine functions in the UI.

**Comment by negasora** [comment]
This seems fixed some time before 3.2.3943-dev
