### ISSUE TITLE
Exception when calling `get_lines` on struct and enum types

### ISSUE THREAD

**Issue by waskyo** [Vector35/binaryninja-api#3672]
**Version and Platform (required):**
- Binary Ninja Version: 3.2.3857
- OS: Debian Linux
- OS Version: Unstable/sid
- CPU Architecture: host is x64, binary is armv7

**Bug Description:**
When calling `get_lines` on a struct or enum type the following exception happens:
```
Traceback (most recent call last):
  File "./types_print.py", line 174, in type_to_c
    lines = t.get_lines(bv, name)
  File "binaryninja/python/binaryninja/types.py", line 1867, in get_lines
    core_lines = core.BNGetTypeLines(self._handle, bv.handle, name, line_width, collapsed, escaping, count)
  File "binaryninja/python/binaryninja/_binaryninjacore.py", line 30759, in BNGetTypeLines
    result = _BNGetTypeLines(type, data, cstr(name), lineWidth, collapsed, escaping, count)
  File "binaryninja/python/binaryninja/_binaryninjacore.py", line 28, in cstr
    return var.encode("utf-8")
AttributeError: 'QualifiedName' object has no attribute 'encode'
```

I was able to "fix" the problem with this patch to `cstr`, but it doesn't seem very clean. Checking for `QualifiedName` is tough in this file as it can't import the `types` module:

```
def cstr(var: Optional[AnyStr]) -> Optional[bytes]:
    if var is None:
        return None
    if isinstance(var, bytes):
        return var
-   return var.encode('utf-8')
+  if isinstance(var, str):
+        return var.encode("utf-8")
+  return ("%s" % var).encode('utf-8')
```

**Steps To Reproduce:**
1. Define a struct or enum type, e.g.:
```
enum State : uint32_t
{
    IDLE = 0x0,
    EST = 0x1
};

struct ConnectionInfo
{
    enum State state;
    uint8_t num_packets;
    uint8_t recv_num_packets;
    uint8_t* data;
};
```
2. Call `get_lines` on that type.
3. Get exception

**Expected Behavior:**
To get the lines for the type instead of an exception.

**Comment by psifertex** [comment]
It looks like you're passing a QualifiedName into an API that [takes a str](https://api.binary.ninja/binaryninja.types-module.html?highlight=get_lines#binaryninja.types.Type.get_lines).

You should probably be calling [.escape()](https://api.binary.ninja/binaryninja.types-module.html#binaryninja.types.QualifiedName.escape) on the QualifiedName to get back out a `str` instead.

**Comment by psifertex** [comment]
Also, sorry for the delay in getting to this, this is NOT our expected turn-around time for reported issues.

**Comment by waskyo** [comment]
No worries, and thank you for pointing out the wrong API usage, I fixed the code and everything is good now.
