### ISSUE TITLE
Undo of "Undefine Current Function" loses variable names, types, comments, ...

### ISSUE THREAD

**Issue by cookiemon** [Vector35/binaryninja-api#3675]
**Version and Platform (required):**
- Binary Ninja Version: 3.2.3857-dev
- OS: Windows 10
- OS Version: Windows 10 21H2
- CPU Architecture: x64

**Bug Description:**
After an Undo of an "Undefine Current Function" all user-set, comments, variable names and parameter names and their respective types are lost.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Load any binary
2. Set the function type, add comments, change variable names, change variable types.
3. Right click function from last step -> Undefine Current Function
4. CTRL+Z

**Expected Behavior:**
After step 4 function should look like after step 2.

**Comment by fuzyll** [comment]
Thanks for the report! This should be fixed in builds >= 3.5.4417-dev. Please feel free to re-open the issue if you're still encountering the bug, but I tested it in a few different scenarios and couldn't get new build to fail again.
