### ISSUE TITLE
"Find All" pane should be able to have a smaller height before collapsing entirely

### ISSUE THREAD

**Issue by 0cyn** [Vector35/binaryninja-api#3678]
**Bug Description:**
The "Find All" pane's table for displaying found items has a locked minimum height. Trying to resize this pane any smaller will result in the entire pane being hidden. When displaying multiple "Find All" panes this impairs the usability of the disassembly pane.

**Expected Behavior:**
Resizing the pane to smaller sizes should resize the Find All table till it can only display one or two entries

**Screenshots:**
This is the minimum height for a "Find All" pane:
![image](https://user-images.githubusercontent.com/55725881/202369851-b9eaa3c7-ccc4-426e-88a4-37c6fcb5ecd8.png)

**Comment by fuzyll** [comment]
This appears to have been fixed prior to 3.6.4617-dev:

![image](https://github.com/Vector35/binaryninja-api/assets/607452/3132bc36-5c28-4bab-9cce-582c7790c901)

However, you will see in the above screenshot that Pinned Cross References *also* has the same problem.

In a weird twist of fate, it seems like code that was intended to address this problem may have created it by accidentally ensuring that the pane couldn't be made smaller than it was initially sized. I've removed this code, which now means Search Results, Pinned Cross References, and the Mini Graph can all be made quite small if necessary.

Builds >= 3.6.4621-dev should have the new behavior. I *believe*  I tested every widget that uses this codepath, but if anyone sees any unintended consequences, please let me know.
