### ISSUE TITLE
"Hide Comments" toggle in Linear View

### ISSUE THREAD

**Issue by cxnder** [Vector35/binaryninja-api#3680]
**What is the feature you'd like to have?**
A quick toggle to hide/show comments in linear view would be nice.

**Is your feature request related to a problem?**
Sometimes I want to quickly copy-paste heavily commented disassembly out of a program. I can script/keybind items to hide most of the non-compilable bits of disassembly, but comments cannot be hidden. Probably also useful at times for readability

**Comment by cxnder** [comment]
Duplicate of https://github.com/Vector35/binaryninja-api/issues/2771

**Comment by utkonos** [comment]
Here is a whole plugin that removes comments temporarily as well as other types of annotations.

"CleanShot"
https://gist.github.com/utkonos/195a58046ad89d83c9eb8f2da409034b
