### ISSUE TITLE
Comment APIs are fundamentally broken

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#3682]
**Version and Platform (required):**
- Binary Ninja Version: 3.2.3814
- OS: macOS
- OS Version: 12.6
- CPU Architecture: arm64

**Bug Description:**
The comment API is entirely broken:

```
>>> bv.set_comment_at(here, "lol")
>>> bv.get_comment_at(here)
''
```

To make matters worse, if you set a comment manually (e.g. "test") and do the following:

```
>>> bv.get_comment_at(here)
''
>>> bv.set_comment_at(here, "lol")
>>> bv.get_comment_at(here)
'test'
```

...it duplicates the "test" comment.

**Steps To Reproduce:**
See above.

**Expected Behavior:**
The thing we actually documented these APIs to do.

**Additional Information:**
After some preliminary review of the code, I believe something is mixing up "global" comments (which get/set are supposed to operate on) and "address" or "function" comments (which I believe the UI is setting). As far as I can tell, differences between types of comments have not been documented anywhere, so this should also probably be something we fix.

**Comment by fuzyll** [comment]
In 3.0.3233, this also behaves oddly. It does what it's supposed to (so, the 3.2 behavior is definitely a regression), but it actually adds _two_ "lol" comments.

<img width="317" alt="image" src="https://user-images.githubusercontent.com/607452/202759095-f2b51b8b-a62a-4aa4-9ece-590c442915ae.png">

In 3.1.3469, however, it worked correctly:

<img width="298" alt="image" src="https://user-images.githubusercontent.com/607452/202794904-a4c261e3-a2cc-4dab-89c0-d986372b4264.png">

Still haven't determined what the change was that altered the behavior, but I'm not sure if this has ever truly worked correctly.

**Comment by xusheng6** [comment]
The comment for "push ebx" being displayed twice is caused by #3568
