### ISSUE TITLE
Opening DVTInstrumentsAnalysisCore crashes Binary Ninja

### ISSUE THREAD

**Issue by saagarjha** [Vector35/binaryninja-api#3691]
**Version and Platform (required):**
- Binary Ninja Version: 3.2.3869 Personal (Build ID c87be5f8)
- OS: macOS
- OS Version: 13.1 (22C5050e)
- CPU Architecture: Apple silicon

**Bug Description:**
Disassembling DVTInstrumentsAnalysisCore (attached, but also available at /Applications/Xcode.app/Contents/SharedFrameworks/DVTInstrumentsAnalysisCore.framework/DVTInstrumentsAnalysisCore) crashes Binary Ninja.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open the file.

**Expected Behavior:**
No crash.

**Additional Information:**
[binaryninja-2022-11-21-230258.txt](https://github.com/Vector35/binaryninja-api/files/10064740/binaryninja-2022-11-21-230258.txt) ← this is actually an IPS file
[DVTInstrumentsAnalysisCore.zip](https://github.com/Vector35/binaryninja-api/files/10064744/DVTInstrumentsAnalysisCore.zip)

**Comment by cxnder** [comment]
Should be resolved in builds >= 3.2.3870

**Comment by saagarjha** [comment]
Thanks!
