### ISSUE TITLE
Linear view hangs after defining segment 

### ISSUE THREAD

**Issue by cxnder** [Vector35/binaryninja-api#3694]
**Version and Platform (required):**
- Binary Ninja Version: 3.2.3872
- OS: macOS

**Bug Description:**
Process hangs at 100% CPU after defining a segment with no data in a new binary.

**Steps To Reproduce:**
1. Create a new BinaryView
2. Define a new segment with: `Start = 0, Size = 0x100, Data Start = 0, Data Size = 0` and permissions `r-x`
3. Swap to Linear view if it is not already open to trigger the hang.

**Comment by negasora** [comment]
This is fixed as of `3.3.4003-dev`, but was probably fixed some time ago
