### ISSUE TITLE
Symbols discovered through debug information are marked as exported

### ISSUE THREAD

**Issue by Ben-Lichtman** [Vector35/binaryninja-api#3698]
**Version and Platform (required):**
3.2.3835-dev Personal (Build ID e414dfad)

**Bug Description:**
Binja 3.2 now scans PDBs for debug information and adds that information into the binary view.
This information may contain extra information not available in the original binary, including non-exported symbols.
When these non-exported symbols are found, they appear to be being treated as if they were exported, which makes them impossible to filter out of the symbol search on the side bar.

**Steps To Reproduce:**
***Preparation:***
- Find some system DLL which has an included PDB (ntdll.dll should work fine)
- Copy this to a new place to test on
***Repro***
- Open this DLL in binja
- right click on the symbol search and hide the exported functions
- You should see only a few functions (the ones with no associated debug information) - all the rest will be classified as exported
***Comparison***
- To demonstrate why this in incorrect, now patch the size of the PE_Data_Directory_Entry of the DLL to be zero - this should stop binja fetching debug information next time you open the DLL
- Re-open the patched DLL
- You will see far fewer named functions - most will be anonymous
- right click on the symbol search and hide the exported functions
- Now you will see that all the anonymous functions are marked as local (this is the correct behaviour)

**Expected Behavior:**
- Symbols loaded from PDBs may either be exported or local and should be classified as such

**Screenshots:**
Before patching:
![image](https://user-images.githubusercontent.com/15235153/204127122-cc37f980-b9b7-4e26-ab33-9edfffc7dbf1.png)
After patching:
![image](https://user-images.githubusercontent.com/15235153/204127143-bd25eb32-0583-4ff1-9fa6-b13051db22e0.png)

**Additional Information:**

**Comment by CouleeApps** [comment]
This was fixed in 3.2.3886-dev by @plafosse
