### ISSUE TITLE
Binja can not handle more than 100 sections

### ISSUE THREAD

**Issue by Ben-Lichtman** [Vector35/binaryninja-api#3699]
**Version and Platform (required):**
3.2.3835-dev Personal (Build ID e414dfad)
Windows 11

**Bug Description:**
If an ELF (in this case a coredump) contains more than 100 sections binja appears to just stop parsing them at 100

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
Create an ELF with more than 100 sections
load it into binja

**Expected Behavior:**
binja should parse out the number of sections listed in the elf header

**Screenshots:**
![image](https://user-images.githubusercontent.com/15235153/204127273-42f167a3-875c-4bd6-9f89-435448b9301f.png)

**Additional Information:**

**Comment by negasora** [comment]
Fixed in 3.2.3878-dev
