### ISSUE TITLE
ARM CLZ seems to cause invalid IL lifting

### ISSUE THREAD

**Issue by pjgat09** [Vector35/binaryninja-api#370]
![binja5](https://cloud.githubusercontent.com/assets/10532511/17272898/4e1ed108-5671-11e6-9b63-403652ab7ea9.png)
![binja6](https://cloud.githubusercontent.com/assets/10532511/17272897/4e1d8712-5671-11e6-8adb-151b5215d1f0.png)
At address 0x22b20 there is a CLZ instruction, followed by a few other instructions which can be seen in the linear view. When switching to the graph view the instructions at 0x22b24 and 0x22b28 are lost, and 0x22b20 incorrectly points to 0x22b3c.

**Comment by bpotchik** [comment]
![screen shot 2017-12-13 at 9 35 51 am](https://user-images.githubusercontent.com/29309548/33944111-1eeeeb7c-dfe9-11e7-9749-b56a44289e95.png)

From what I can tell, the count leading zeros looks to be fixed now.
