### ISSUE TITLE
some command-line arguments not loaded when multiple mach-o files are loaded

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#3707]
Command-line parsing of multiple elements appears buggy. To reproduce, simply:

```"/Applications/Binary Ninja.app/Contents/MacOS/binaryninja" /bin/ls /usr/bin/ditto /usr/bin/vim``` and notice only the second two files are actually opened. If you remove the last file, the first two are opened.

Appears to be related to the "open with options" dialog for mach-o universal files as doing the same operation on other file formats causes no issue.

**Comment by psifertex** [comment]
This was actually resolved by some other unrelated fixes a few weeks ago.

**Comment by bpotchik** [comment]
Restart should restart binja with the exact same command line that binja was originally started with.
Therefore, restart should reopen any files that were specified on the command line, not the current open files (which may have changed from the start)

A recent fix enforced this behavior.
