### ISSUE TITLE
Add /edit segment or section dialog title is wrong

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#3712]
- Binary Ninja Version: 3.2.3895, 6b1f21d2
- Platform: Windows 11, x64

Dialog title for add /edit section and add /edit segment is "Binary Ninja". I expect them titled according to their function.

![title_bug](https://user-images.githubusercontent.com/109607896/205296254-36ade1e1-c7a3-43c0-a931-1982bda62adc.png)

**Comment by psifertex** [comment]
Fixed in the next build greater than 3899 (not triggering a fresh build so it'll basically be whenever the next dev comes out)
