### ISSUE TITLE
Rust API could be more Rusty

### ISSUE THREAD

**Issue by dyslexicsteak** [Vector35/binaryninja-api#3714]
The Rust API is not as friendly or rusty as it could potentially be, one thing that stuck out to me as a large contributor to this is the need to call `headless::init()` then `headless::shutdown()`, the Rust type system is able to express this in a more concise and friendly manner: create a struct that represents a session, say `HeadlessSession`, and implement all initialisation within a `new` associated function (static method), then `impl Drop for HeadlessSession` and place shutdown behaviour in `drop` there. In this way, the lifetime of the session determines its validity in a way that the user is not required to remember anything, the user can drop it if they need to manually end a session or simply allow it to go out of scope normally.

Any configuration options can be placed as arguments to `new` with a `SessionConfig` struct, and any state that needs to be communicated can be placed behind getters on this struct, in this way, manipulations of the Binary Ninja instance can be consolidated into this struct, and the receiving of state information can be too.

**Comment by KyleMiles** [comment]
There are still plenty of things in the API that could be "more Rusty," but I'll leave those for more specific issues. :)

Let me know if this doesn't work like you were thinking it would. Not right now sure what other config options we'd want to provide.
