### ISSUE TITLE
Binja fails to change variable type or name

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#3717]
- Binary Ninja Version: 3.2.3895
- OS: Windows 11, x64

**Bug Description:**
I can not change `var_28`' type and name. Interestingly, binja shows me a dialog for changing type of the current function, not variable. When I try to change its name, nothing happens.

**Steps To Reproduce:**
1. Open attached binary
2. Go to function `sub_140001000`
3. Try to change type /name of variable `var_28`
4. See you're changing type for `sub_140001000`

**Expected Behavior:**
I expect it to let me change type /name of `var_28`.

**Additional Information:**
Binary: 
[ConsoleApplication1.zip](https://github.com/Vector35/binaryninja-api/files/10174315/ConsoleApplication1.zip)

**Comment by negasora** [comment]
`var_28` wasn't created in the function - so there's no `Variable` for the UI to reference

A workaround is to create a variable of any type at the offset in stack view, then editing works as expected

**Comment by negasora** [comment]
Here's a minimized example: [var_creation.zip](https://github.com/Vector35/binaryninja-api/files/10484143/var_creation.zip)

I think this might be the same root cause as https://github.com/Vector35/binaryninja-api/issues/3065

**Comment by bpotchik** [comment]
You can also cause a crash by clicking `var_28` and using `'t'`
