### ISSUE TITLE
Allow selection of BinaryViewType in open-with-options

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#3721]
Some embedded firmwares may have binaryviews that aren't easily fingerprintable but the user would like to optionally load them. The only options right now are to either register a view that [returns true](https://github.com/fluxchief/binaryninja_avr/issues/15) for all files which is obviously annoying, or to simply not return true which means the view is only available via the API to be manually applied but the user cannot select it.

**Comment by zznop** [comment]
Added new `is_force_loadable` method to `BinaryViewType` class in `4.2.6146-dev`. BinaryView's for raw formats can now be written to return `False` from `is_valid_for_data` (unconditionally) and `True` from `is_force_loadable`, which ensures the BV won't be auto-selected, but allows the user to select the view type in "Open with Options".
