### ISSUE TITLE
Deadlock when creating database in analysis completion event

### ISSUE THREAD

**Issue by negasora** [Vector35/binaryninja-api#3723]
Trying to create a database in an analysis completion callback will deadlock

Script to repro:
```python
import time
from binaryninja import open_view

db_saved = False
bv = open_view('/bin/true', update_analysis=False)

def analysis_complete():
    global db_saved
    print("COMPLETION EVENT")
    bv.create_database("testdatabase.bndb")
    db_saved = True
    print("EXITING COMPLETION EVENT")

bv.add_analysis_completion_event(analysis_complete)
bv.update_analysis()

while not db_saved:
    time.sleep(1)
```

Alternatively, if this behavior isn't supported, we need to document it

**Comment by bpotchik** [comment]
The thread that processes analysis callbacks holds the data lock for the binary view. Creating a database schedules the action on the main thread, which will try to grab the data lock, and block. So in short the operation is not supported. I'll update the docs.
