### ISSUE TITLE
Uncatchable crash when parsing strings for types

### ISSUE THREAD

**Issue by mahaloz** [Vector35/binaryninja-api#3727]
**Version and Platform (required):**
- Binary Ninja Version: 3.2.3814
- OS: Ubuntu
- OS Version: 22.04
- CPU Architecture  x64

**Bug Description:**
Crashes when parsing an empty string:
```
bv.parse_type_string("")
```

**Steps To Reproduce:**
1. Load a binary
2. In the Python console run this command: `bv.parse_type_string("")` 
3. You should've crashed. 

**Expected Behavior:**
Binary Ninja windows completely closes. You can't catch it with a Python try-catch

**Comment by CouleeApps** [comment]
Looks like this is a bug with the parser returning successfully since there was technically no syntax errors, but also not returning a type. This is being fixed so that any parse with no types will return an error for `parse_type_string` specifically, in dev version 3.2.3919
