### ISSUE TITLE
Keybinding for stack adjust graph view and update of adjust value display in unresolved stack view

### ISSUE THREAD

**Issue by 0x61616161** [Vector35/binaryninja-api#3734]
**Version and Platform (required):**
- Binary Ninja Version: Version 3.2.3913-dev
- OS: Windows
- OS Version: 10
- CPU Architecture x64

**Bug Description:**
There does not seem to be a way to enter the stack usage graph again after "fixing" it. However it seems that it might still be possible to adjust it in disassembly views, but getting back to the graph would be nice.

Also inside the graph view the adjust value does not update.
call    sub_423540  { Adjust by 0 }    -> change adjust via right click menu to 8
still shows adjust by 0, until the graph view is closed and opened again.

Tested on this years flare-on(9) challenge 5, function sub_404680.
When trying to fix the stack adjustments I made some errors, but it seems I adjusted everything, so the button to enter the graph view disappears, however I could not find any way to enter that view again.
(side note, in general it seems I have to test this sample more, did not get the function calls in that function to display proper parameter in HLIL at all)

**Expected Behavior:**
A keybinding / command palette option to enter the stack adjust graph view.
Update of the adjustments in the graph view, without the need to reopen them

I hope this is clear enough, the reopen of the view might be considered a feature, but the update of the Adjust value seems like a bug, so I hope it is fine to have this as one issue.

**Comment by plafosse** [comment]
The reason for this is that the stack adjustment graph removes nodes as they're resolved. BN doesn't see a broken stack adjustment it has literally nothing to display. It seems what you'd like is simply a graph of the stack adjustments and not the unresolved stack adjustments.  This can be seen in the low level il if you use the command "Show Stack Pointer Value"
<img width="252" alt="image" src="https://user-images.githubusercontent.com/10556585/217059720-f68a0975-484c-4eeb-9db8-5c626d29278e.png">
Which gives you the following annotations:
<img width="595" alt="image" src="https://user-images.githubusercontent.com/10556585/217059865-127b3e01-1723-4ae0-bc54-0a3ee938ebb4.png">
