### ISSUE TITLE
Builtin Outlining of Constant Expressions

### ISSUE THREAD

**Issue by bpotchik** [Vector35/binaryninja-api#3742]
It would be nice to have support for outlining common optimizations performed by compilers when dealing with constant strings and data. This covers well-known situations such as stack constructed strings, or zero initialization of data structures.

Some of the builtins that would be good to provide outlining for are `strcpy`, `strncpy`, `memset`, and `memcpy` to start.

**Comment by plafosse** [comment]
This feature is in but is disabled by default as its still in active development.  To enable this feature open settings and check:


![Image](https://user-images.githubusercontent.com/10556585/211588791-ddb59b17-2ac6-438b-aa22-79f76bca7fde.png)

**Comment by bpotchik** [comment]
Added support for handling type constraints in `3.4.4120-dev`. The feature is now enabled by default.

**Comment by bpotchik** [comment]
Support for outlining stack storage is in `3.4.4133-dev`.
