### ISSUE TITLE
Referencing unknown inner type error even if type is defined

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#3745]
- Binary Ninja Version: 3.2.3906-dev
- OS: Windows 11, x64

**Bug Description:**
I've a structure like this:
```
struct _test
{
    int32_t a;
};
```

and a typedef for it like this: `typedef struct _test test`.

Now, when I try to edit some variable /function prototype and set variable /parameter type to `test`, I get an error message like this:

`Referencing unknown inner type _test`

**Steps To Reproduce:**
1. Create a structure
2. Create a typedef for it
3. Change variable /parameter type to that typedef
4. See unknown inner type error in log

**Additional Information:**
Is reproduces for enums.

**Comment by CouleeApps** [comment]
Looks like imported typedef types were not properly marked as imported to the Clang plugin, so it was throwing a warning when trying to look it up. Will be fixed on dev 3.2.3924-dev.
