### ISSUE TITLE
"Create Array" crashes for void types

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#3747]
- Binary Ninja Version: 3.2.3928-dev
- OS: Windows 11, x64

**Bug Description:**
If we select some bytes that starts with a void typed variable and press `*` binary ninja crashes.

**Steps To Reproduce:**
1. Open a file
2. Find a void variable somewhere 
3. Select some bytes after it and press `*` in order to create an array
4. See the crash

**Comment by negasora** [comment]
Fixed in `3.2.3942-dev`
