### ISSUE TITLE
Create Array dialog fails to copy full type on function pointer types.

### ISSUE THREAD

**Issue by cxnder** [Vector35/binaryninja-api#3750]
**Bug Description:**
![image](https://user-images.githubusercontent.com/55725881/208546087-c42dbe46-3f33-4b47-a144-d032f524e29d.png)

**Steps To Reproduce:**
1. Find some random bytes
2. Set the type at the start to `void* (* )(void())`
3. Try to create an array w/ the dialog starting with the typed var

**Comment by jonpalmisc** [comment]
Should be fixed in builds ≥ 4046.
