### ISSUE TITLE
Combine operation (HLIL -> PseudoC) likely has bug

### ISSUE THREAD

**Issue by rvrecen** [Vector35/binaryninja-api#3751]
**Version and Platform (required):**
- Binary Ninja Version: [e.g. 3.2.4000-dev] (if version is stable, please also test the latest development build via the "Update Channel" option)
- OS: Windows
- OS Version: 11
- CPU Architecture: x64

**Bug Description:**

![image](https://user-images.githubusercontent.com/66631929/208775453-5ae1dbe3-9baf-4c38-8080-64c51d46a2c5.png)

There appears to be a bug in how HLIL lifts 64 bit operations on 32 bit binaries. The expected behavior would be COMBINE(arg2, arg1) as seen in LLIL and HLIL, but instead the Pseudo C reports COMBINE(arg1, arg1).

**Steps To Reproduce:**
I was not able to create a binary that did this, but any binary that does `div` in assembly would expect to do the similar behavior on a 32 bit binary.

**Comment by galenbwill** [comment]
Fixed in builds >= 3932
