### ISSUE TITLE
Strange behavior when creating tags/tag types in binaryview_finalized_event

### ISSUE THREAD

**Issue by verylazyguy** [Vector35/binaryninja-api#3752]
**Version and Platform (required):**
- Binary Ninja Version: 3.2.3826-dev
- OS: OSX
- OS Version: Catalina
- CPU Architecture amd64

**Bug Description:**
adding tag types in the callback provided to BinaryViewType.add_binaryview_finalized_event doesn’t work. It seems like it works but it doesn’t show up in the list of tag_types in the UI. To add to the confusion if you use that tag_type to create tags in a bv.add_analysis_completion_event callback, the tags will show up in the tags list but the type will still not show up in the tag_type list in the UI. Tags also don’t show up in the UI if they are added in the former callback

**Expected Behavior:**
Either the tags (& types) fail to be created at all _or_ more preferably everything is created like normal

**Comment by bpotchik** [comment]
Fixed in a prior version to `4.2.6245-dev`.
