### ISSUE TITLE
Binja hangs on auto-analysis, gobbles RAM

### ISSUE THREAD

**Issue by Douggem** [Vector35/binaryninja-api#3760]
**Version and Platform (required):**
- Binary Ninja Version: [e.g. 3.2.3944-dev] 
- OS: Windows
- CPU Architecture AMD64

**Bug Description:**
During initial auto-analysis, Binja gets stuck on a function and spins, consuming more and more RAM (I let it run for a few hours)

After rolling back to an older version (3.2.3932-dev) this behavior does not occur BUT the following output hits the Log window:
```
Skipping analysis for function at 0x1400be080 : Exceeds 'analysis.limits.maxFunctionUpdateCount'. If possible, please report this issue.
Analysis update took 97.592 seconds
Skipping analysis for function at 0x1400bdd80 : Exceeds 'analysis.limits.maxFunctionUpdateCount'. If possible, please report this issue.
Skipping analysis for function at 0x1400bcfc0 : Exceeds 'analysis.limits.maxFunctionUpdateCount'. If possible, please report this issue.
```

The binary is a video game server binary - DayZServer_x64.exe I have uploaded it here https://drive.google.com/file/d/1833KSDwVxT6BR7W7Ev-UC9_YHpG97R2D/view?usp=sharing in an encrypted zip with the password: "binja"

**Comment by bpotchik** [comment]
Thanks for reporting this!

Fixed in `3.2.3945-dev`.
