### ISSUE TITLE
Tab broken on text input for builds >= 3863 on MacOS

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#3763]
**Version and Platform (required):**
- Binary Ninja Version: 3.2.3946-dev
- OS: macOS
- OS Version: 12.4
- CPU Architecture: M1

**Bug Description:**
When I tried to press tab to indent a line in the Python Console, it instead switched focus to some other view and did not indent anything.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open the Python Console
2. Try to enter the following (type it out, don't paste it in, also press tab):
```
if True:
    print("test")
```
3. Observe pressing tab moves focus instead of indenting

**Expected Behavior:**
I expected tab to insert a tab character

**Additional Information:**
This is a regression since latest stable

**Comment by psifertex** [comment]
This is correlated with the move to QT 6.4.1 in build 3863. QT point releases have been introducing more bugs than they've been fixing lately... :-(

**Comment by negasora** [comment]
doesn't repro on linux :-)

**Comment by cxnder** [comment]
Or windows. Appears to be a macOS only Qt 6.4.1 bug. 

A mitigation for this that restores the old behavior will be available in builds _after_ 3.2.3947

**Comment by CouleeApps** [comment]
This also applies to Assemble Source, Compile C Source, Input New Type, Set Comment, and other dialogs that use QTextEdit (or subclasses).

**Comment by CouleeApps** [comment]
Filed with qt at https://bugreports.qt.io/browse/QTBUG-109754

**Comment by psifertex** [comment]
https://bugreports.qt.io/browse/QTBUG-109754

**Comment by CouleeApps** [comment]
Including the patch from https://codereview.qt-project.org/c/qt/qtbase/+/451686 via https://github.com/Vector35/qt-build/commit/4ca43d719c0780b4ee15650bdb4665e07730b66a fixes this bug for now. Fix will be present in the next dev that goes out after CI builds Qt, likely 3.2.3950
