### ISSUE TITLE
Inlining a trampoline terminates the caller with a tailcall

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#3764]
**Version and Platform (required):**
- Binary Ninja Version: 3.2.3949
- OS: macOS
- OS Version: 12.4
- CPU Architecture: M1

**Bug Description:**
Marking a trampoline function as inline causes the caller's lifting to end early, as if the caller did a tailcall jump to the trampoline's target. 

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open the following exe/pdb: [animals.zip](https://github.com/Vector35/binaryninja-api/files/10340035/animals.zip)
2. Navigate to 0x402553 (`Fly::buzz`)
3. Right click the call to j__printf, and Edit Function Properties
4. Enable Inline during Analysis
5. Observe lifting of `Fly::buzz` is now broken

**Expected Behavior:**
I expected the inlined call to j__printf to result in a call to _printf, not a tailcall

**Screenshots:**
HLIL (before)
<img width="440" alt="image" src="https://user-images.githubusercontent.com/711973/210448123-a32a963d-3e59-49e7-9f8b-99f5e65b7af7.png">

HLIL (after)
<img width="597" alt="image" src="https://user-images.githubusercontent.com/711973/210448162-e70a54f9-44f4-4d59-a35b-7741e1ce132a.png">

LLIL (before)
<img width="646" alt="image" src="https://user-images.githubusercontent.com/711973/210448313-9176bf00-d74c-42d5-8ef5-a443e29332c9.png">

LLIL (after)
<img width="655" alt="image" src="https://user-images.githubusercontent.com/711973/210448248-4099ed3a-2c9c-4fe8-9b3d-b033724cd6bc.png">

**Comment by D0ntPanic** [comment]
The ability to inline these functions from the UI has been disabled. The option will be reenabled when it is possible to inline them.

**Comment by D0ntPanic** [comment]
Inlining of functions that contain tail calls is now supported in build 3969. Note that in this particular example, inlining the call will cause suboptimal HLIL expression folding because of the additional control flow. This is a different bug and is currently unknown why it is the case, as the required optimizations are already implemented.

**Comment by D0ntPanic** [comment]
Decompiler output has been improved in these cases with build 3998. Some expressions that were no longer optimized after inlining are now optimized again.
