### ISSUE TITLE
Support for running Binary Ninja natively on Linux Arm64

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#3765]
We've started to receive some requests for an arm linux native version of BN. Adding a new architecture adds a significant amount of work to the build/update infrastructure as well as requires more work for each stable release so we're holding off for now. In the meantime, vote on this issue to indicate your interest. Also, mentioning arm64 in case GH search doesn't find it without it.

**Comment by WhatTheFuzz** [comment]
Just posting my use case here.

I like macOS (which has gone all-in on `arm64`) as my host, but I like doing security research/CTFing on Linux. Thus most of my work is done in Linux virtual machines. It's a PITA to move over executables from the guest over to the host, in order to use Binary Ninja, every time I want to look at something.

I actually love Binja so much I reverted back to an Intel Mac just do I can use it on my guest VMs. :smile:

**Comment by CunningLogic** [comment]
There are many notebooks with the Snapdragon X Elite will debut in mid-2024, which are by all accounts leaps and bounds above the "toy" arm notebooks we have seen the last couple years.

It might be worth reconsidering the priority of this. If the demand is not here yet, it will be shortly.

**Comment by WhatTheFuzz** [comment]
This has me so excited.

**Comment by fuzyll** [comment]
These builds and updates are now live on the `dev` branch and installers can be downloaded by using the [License/Installer Recovery](https://binary.ninja/recover/) process on our website. Just make sure to change the "Download type" to `dev` before you click "Send license" as we do not have any 4.0 stable builds available at this time.

In our limited testing, the arm64 build seems to work very well and we're not currently aware of any limitations or issues. But, we have not gone through a full release test process yet. So, it should be considered a "release candidate" until the 4.1 stable in a few months.

If I'm wrong and anyone encounters a problem, I highly encourage you to file issue to bring the problem to our attention so we can get it fixed.

**Comment by blue-devil** [comment]
Tested dev build on Arch GNU/Linux aarch64 and binja works like a charm. Thank you guys
