### ISSUE TITLE
Navigate to closing Bracket/Paren

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#3768]
Much like #1730 (Highlighting matching Brackets) we should be able to navigate to them as well with a keystroke.

**Comment by CouleeApps** [comment]
While this is not added in 3.5.4291, matching braces are highlighted and this can be easily implemented by searching for the other BraceToken with the same value.

**Comment by negasora** [comment]
Added in `4.1.5248-dev`
