### ISSUE TITLE
Negative Comparison (reg == -1) lifts as `(var == )` whenever `var` is an Enum and has no definition for the absolute value of the bit.

### ISSUE THREAD

**Issue by cxnder** [Vector35/binaryninja-api#3775]
**Version and Platform (required):**
- Binary Ninja Version: 3.2.3982
- OS: macOS

**Bug Description:**
![image](https://user-images.githubusercontent.com/55725881/211875114-d3778838-fa29-40e8-bec5-d0fb9c2b96c3.png)

This is not a recent regression due to recent enum changes, and has been here at least throughout the current stable.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Locate a cmp/cmn -> branch comparing against a negative number
2. Define the target variable to be of an enum type
3. Ensure the enum type does not have a value for 0 defined.

**Expected Behavior:**
Given that the enum is unsigned it should fall back to default integer rendering

Repro:
[empty_comp.bndb.zip](https://github.com/Vector35/binaryninja-api/files/10394630/empty_comp.bndb.zip)

**Comment by negasora** [comment]
Fixed in 3.3.4001-dev
