### ISSUE TITLE
`const` keyword does not work in type parser

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#3777]
Defining a variable with a `const` type no longer sets it as constant type.

Steps to repro:

1. Open any binary, create an integer at any place
2. Press 'Y' to change its type
3. add `const` to its type, and hit enter
4. observe the integer is not having a const type as expected

**Comment by plafosse** [comment]
Or repro using the API
```python
>>> bv.parse_type_string("const int")[0].const
BoolWithConfidence(value=False, confidence=255)
>>> bv.parse_type_string("int const")[0].const
BoolWithConfidence(value=False, confidence=255)
```

**Comment by ccarpenter04** [comment]
I noticed this as well, I know it's supposed to be release day but is there any chance it'll be fixed in time for 3.3?

**Comment by plafosse** [comment]
We are going to look into it today. No promises. 😊

**Comment by CouleeApps** [comment]
Interestingly, `int volatile` and `volatile int` work fine, just `const` is broken. I'm looking into this now.

**Comment by CouleeApps** [comment]
Looks like this was due to converting a `clang::QualType` to a `clang::CType*` and losing the `const` qualifier, only on typedef types. This will be fixed in the next build.
