### ISSUE TITLE
Hotkey for switching between IL and assembly not working

### ISSUE THREAD

**Issue by 0xbc** [Vector35/binaryninja-api#378]
In graph view, pushing the l key to switch between assembly and IL isn't working for me. I can successfully toggle them by clicking on "Options -> Assembly / Low Level IL" in the bottom RH corner.

Binary Ninja 1.0.307 (build ID f2ac3d81)
Windows 10 Pro x64 version 10.0.14393

**Comment by psifertex** [comment]
The hotkey is an I (EYE), not an l (ELL). 

The docs were actually wrong, sorry about that. Fixed in the latest build and online docs are being pushed now.
