### ISSUE TITLE
VariablesView offers no visual indication as to when it stops showing possible values due to large number of variables

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#3785]
**Version and Platform (required):**
- Binary Ninja Version: 3.2 dev

**Bug Description:**
VariablesView will query and display PossibleValueSet information for each variable. This can take too much time when the variables list is long so currently we don't query if there are more than some threshold number of variables. There are two solutions possible solutions.

A. Be more performant and perhaps add some caching. We can probably cache things as long as the variable list doesn't change, and we only refresh the list if the variable list has changed. Additionally we could probably only query for the variables that are on screen as another way to improve performance.

B. Add some visual indicator that variable values aren't being displayed as there are too many variables.

**Comment by negasora** [comment]
It's not the number of variables, but the "complexity" of the function. Users can change the complexity cutoff with `ui.view.variables.pvsComplexityLimit`. Though there should absolutely be some indication that this is happening

**Comment by yrp604** [comment]
There is a third option here I'd prefer that's kinda a combination of the two -- a button similar to the way you can force analysis on large functions. This would also serve as a visual indication that analysis hasnt happened. If caching is added on top of this, all the better.

**Comment by negasora** [comment]
Fixed in `3.6.4626-dev`
