### ISSUE TITLE
Analysis hangs on static binary

### ISSUE THREAD

**Issue by mossberg** [Vector35/binaryninja-api#380]
This binary causes binja to hang around analysis 291. It makes progress, but pretty slowly. Only compile flag was `-static`.

[bin.zip](https://github.com/Vector35/binaryninja-api/files/411472/bin.zip)

**Comment by psifertex** [comment]
So does it just run slowly or does it never finish at all? For me, it gets slower around the 300s and then picks back up and does eventually complete. We do have some cases where we know our dataflow can be much slower though we haven't tracked the specific bug down.

**Comment by mossberg** [comment]
Same for me, runs slow but does complete.

**Comment by lucasduffey** [comment]
OS: ubuntu 16.04
PwnAdventure3 linux binary - freezes analysis @ "analyzing (144/4629)"

**Comment by plafosse** [comment]
Fixed in dev
