### ISSUE TITLE
Headless BinaryView Loading broken in Rust API

### ISSUE THREAD

**Issue by toolCHAINZ** [Vector35/binaryninja-api#3811]
After the recent rust API refactor/cleanup, headless loading of binaries that are supported by non-raw `BinaryView`s broke. The `open_view` function and friends will load a `Raw` image even if there are `BinaryViewType`s that will parse an image.

After some quick triage and testing on my own fork, it seems to be because of the following line:

https://github.com/Vector35/binaryninja-api/blob/dev/rust/src/lib.rs#L234

Changing

```rust
if available_view.name().as_ref() == b"Raw"
```

to

```rust
if available_view.name().as_str() == "Raw"
```

seems to fix it. The issue seems to be that the `&[u8]` yielded by `as_ref` has an extra null termination character which causes the rust string comparison to fail.

**Comment by KyleMiles** [comment]
Resolved with #3816
