### ISSUE TITLE
Additional struct annotation types

### ISSUE THREAD

**Issue by rickmark** [Vector35/binaryninja-api#3813]
**What is the feature you'd like to have?**
A annotation to a struct allowing for the notation that a value is the file offset instead of a VM mapped address

**Is your feature request related to a problem?**
In order to navigate to file offsets, you must copy the value, calculate the vmaddress, and navigate to that vmaddr.  vmaddresses only require a double click

**Are any alternative solutions acceptable?**
Please provide a clear and concise description of any alternative solutions or features you've considered.

**Additional Information:**
Please add any other context or screenshots that would help us understand your feature request here.

An example struct, `addr` could be annotated `__vmaddr` or such (the default interpretation) and `offset` could be annotated `__fileoff` letting the UI know that double clicks must map to a vmaddr before navigate

<img width="579" alt="Screenshot 2023-01-19 at 3 37 53 PM" src="https://user-images.githubusercontent.com/125403/213586388-2cb010e7-c17a-4d6b-b617-c5f4f3c5bf44.png">

**Comment by rickmark** [comment]
Additionally,

`__size` as a binja extension specifying that the field is the full size of the struct allowing it to cover the full area of it.

The ability to specify arrays that are sized based on a value of the struct

```c
typedef struct some_element {
uint64_t value;
} some_element_t;

struct something {
  __size size_t size;
  size_t count;
  some_element_t elements[count];
};
```

**Comment by rickmark** [comment]
Another useful one

`__relative_to_section(_cstring)` `__relative_to_pc` to annotate an address that is relative to a section or from the program counter (PC)

**Comment by plafosse** [comment]
@CouleeApps 's correct I'm going to mark this as a dupe.
