### ISSUE TITLE
Changing type to fixed size char becomes array of uint8_t

### ISSUE THREAD

**Issue by rickmark** [Vector35/binaryninja-api#3814]
**Version and Platform (required):**
3.3.3996
- OS: macOS
- OS Version: 13.2
- CPU Architecture x64

**Bug Description:**
When changing the type of a variable to `char const [0x14]` the value of char is replaced with uint8_t making it show as a array of bytes instead of a fixed length C-String with null padding.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open a file that has a C-String of fixed size
2. (as an example one from a compiled binary defining a const `const char some_var[255] = "Some String!"`)
3. Find the variable in the constants
4. Select "Change Type"
5. Set the type to `const char [255]`
6. The value will be shown as an array of uint8_t[255]

**Expected Behavior:**
Display as a C-string and keep the char type

**Screenshots:**
Proper fixed length C-string from auto parsing:
<img width="595" alt="Screenshot 2023-01-19 at 4 12 27 PM" src="https://user-images.githubusercontent.com/125403/213589977-99d39cfd-9d67-4e91-bdbc-ef6f802539f7.png">

Improper display of a variable where type was set:
<img width="367" alt="Screenshot 2023-01-19 at 4 13 25 PM" src="https://user-images.githubusercontent.com/125403/213590043-4d9934a7-e57e-412a-bd98-66c62d493aa4.png">

**Additional Information:**
Please add any other context about the problem here.

**Comment by CouleeApps** [comment]
This was due to certain platforms defining `char` as an unsigned int, but binja only renders signed ints as `char`. Binja will now always parse `char` as a signed int when using the type dialog, but importing headers will respect the platform's wishes since Clang knows what is correct.

Fixed in 3.3.4005-dev.
