### ISSUE TITLE
undocumented macros

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#3818]
There's a number of undocumented macros like COMBINE, HIGH?, LOW?, etc, that need to be in a searchable part of the user documentation.

- [x] COMBINE
- [x] LOW / HIGH
- [x] ROR / ROL / RLC / RRC
- [x] TEST_BIT
- [x] FCMP_O / FCMP_UO

**Comment by CouleeApps** [comment]
* `COMBINE(a, b)` is equivalent to the IL split register `a:b` syntax, where `a` is the upper half and `b` is the lower half of a value. E.g., for 32-bit values a and b, `COMBINE(a, b)` is equivalent to the 64-bit value, `(a << 32) | b`
* `LOWx(a)` is the low x bits of larger value `a`. E.g., for 64-bit value `a`, `LOWD(a)` is the lower 32 bits of `a`, or `a & 0xFFFFFFFF`
* `HIGHx(a)` is the upper x bits of larger value `a`, shifted into a lower size value. E.g., for 64-bit value `a`, `HIGHD(a)` is the upper 32 bits of `a`, or `a >> 32`
* `ROR(a, b)`, `ROL(a, b)`, `RLC(a, b)`, `RRC(a, b)` are Rotate Right/Left and Rotate Right/Left with Carry value `a` by number of bits `b`
* `TEST_BIT(a, b)` is Test if Bit `b` is set in value `a`, equivalent to `(a & (1 << b)) == (1 << b)`
* `FCMP_O(a, b)` and `FCMP_UO(a, b)` are Floating Point Comparison Ordered/Unordered. They are tests comparing if two floating point values are ordered/unordered (ordered meaning less than or greater than).

**Comment by galenbwill** [comment]
Now the question is, **where** in the user docs should this helpful information be inserted?

**Comment by psifertex** [comment]
My vote is: https://docs.binary.ninja/dev/bnil-overview.html probably.

**Comment by psifertex** [comment]
Will be fixed in the next dev build.
