### ISSUE TITLE
Holding `I`/shortcut to cycle ILs should only activate once per keypress

### ISSUE THREAD

**Issue by cxnder** [Vector35/binaryninja-api#3820]
**Version and Platform (required):**
- Binary Ninja Version: 3.3 Stable
- OS: macOS

**Bug Description:**
Approximately half the time I hit this key, it processes the event far too many times, cycling me far further than I intended to go, skipping IL levels entirely, or sometimes cycling entirely around. I'm not sure whether this is an "all keybinds should be latched" thing, or just the IL one needs a latch.

**Comment by psifertex** [comment]
🦋⌨️

**Comment by cxnder** [comment]
Blocked by apple engiineering department
