### ISSUE TITLE
BinaryNinja fails to reliably recognize function arguments on inlined stub calls

### ISSUE THREAD

**Issue by cxnder** [Vector35/binaryninja-api#3821]
**Version and Platform (required):**
- Binary Ninja Version: 3.3.4007

**Bug Description:**
BinaryNinja fails to reliably recognize function arguments on inlined objc_stub calls
While the ObjC workflow is still able to resolve the dynamic calls through SSA, HLIL will fail to properly lift the x0/x1 registers into the function arguments at all on many of the calls. 

This reproduces with both core inlining and the `msgsend_stubs` branch of the Objective-C Workflow (which inlines them via workflow.)

**Steps To Reproduce:**
1. Open the ARM64 slice of the Attached binary with the standard Obj-C Workflow (not  `msgsend_stubs` branch)
2. Paste following into console:
```py
s = [f for f in bv.functions if f.start in range(bv.get_section_by_name('__objc_stubs').start, bv.get_section_by_name('__objc_stubs').end)]
for f in s:
    f.inline_during_analysis = True
```
3. Navigate anywhere in Binary, view inconsistent lifting

[Hexadecimal.zip](https://github.com/Vector35/binaryninja-api/files/10484398/Hexadecimal.zip)

**Comment by cxnder** [comment]
This appears to have actually been a race condition with the objc_workflow that should be resolved later via it's `arc_cleanup` branch.

**Comment by NyaMisty** [comment]
Hi can you elaborate more on the how your inlining work?
Are you using a different branch of objc_workflow?
Thanks!
