### ISSUE TITLE
Collapsing of code blocks

### ISSUE THREAD

**Issue by 0x61616161** [Vector35/binaryninja-api#3828]
**What is the feature you'd like to have?**
It would be great to be able to collapse code blocks on the IL level (maybe also groups of bbs). 
For example when a function is long and uses if/else and loops, it would be nice to be able to hide a loop or a branch, basically like the collapsing you get in IDEs.
(maybe the bb comment would be something different, like grouping blocks and collapsing them into a single block with a comment placeholder, but that would probably be hard to replicate on IL level, so would probably only be for bbs)

So the primary request would be the collapsing of branches / loops in functions on HLIL level.

**Is your feature request related to a problem?**
Not related to a problem ( if you don't consider long functions to be a problem)

**Are any alternative solutions acceptable?**
Keeping it as is works

**Additional Information:**
I hope it is clear enough, otherwise I can make some mockup.

**Comment by psifertex** [comment]
Yes, we want this too, it's one of our older issues at this point and tracked in #510

The good news is that it's already on our medium term roadmap now.
