### ISSUE TITLE
Variable Detection Flaw

### ISSUE THREAD

**Issue by mabbamOG** [Vector35/binaryninja-api#383]
In the [attached](https://github.com/Vector35/binaryninja-api/files/423202/crackme0x04.zip) elf x86 executable one of the binary-ninja assigned variables isn't being recognized.
Flaw is in the `check` function.
Switching to *Low Lever IL* option fixes the bug. Check the screens.

FLAW:
![screenshot_2016-08-14_12-40-41](https://cloud.githubusercontent.com/assets/19165952/17746825/4735a9ee-64b2-11e6-8187-856e74bf1b07.png)

WORKING:
![screenshot_2016-08-14_12-40-57](https://cloud.githubusercontent.com/assets/19165952/17746854/72fced4e-64b2-11e6-9c79-e06ee0bef8e2.png)

Source for binary executable [here](http://pof.eslack.org/tmp/IOLI-crackme.tar.gz). Look for a file named `crackme0x04` under `bin-linux` folder.
The linux binaryninja version i used is *1.0.7* (demo edition :grimacing:)

**Comment by D0ntPanic** [comment]
Fixed in dev

**Comment by ekse** [comment]
Thank you!
