### ISSUE TITLE
Builtin outlining for constant expressions does not work in older BNDBs

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#3835]
Binary Ninja Version: 3.3.3997-dev
Platform: Windows 11 22H2

I've a BNDB from BN version 3.2.3906, when I open it in 3.3.3997, seems like builtin outlining for constant expression feature does not work, I can't see the section `.synthetic_builtins`.

If I generate fresh BNDB from binary again in 3.3.3997, I can see that there is a section named `.synthetic_builtins`.

I expected that even if my BNDB is created with older version of BN, it will outline constant expressions.

**Comment by bpotchik** [comment]
I'm pretty sure this bug was fixed in the last stable release. If it is not fixed please feel free to reopen. Internal commit for reference: b17d6de.
