### ISSUE TITLE
Ability to save a section as a binary file

### ISSUE THREAD

**Issue by rickmark** [Vector35/binaryninja-api#3840]
**What is the feature you'd like to have?**
Right click on a section / segment and have a save dialog appear to write out the contents of that area

**Is your feature request related to a problem?**
<img width="277" alt="image" src="https://user-images.githubusercontent.com/125403/215179311-d0ea7daf-553f-4219-a2b1-e7495f575b1f.png">

**Are any alternative solutions acceptable?**
Please provide a clear and concise description of any alternative solutions or features you've considered.

**Additional Information:**
Please add any other context or screenshots that would help us understand your feature request here.

**Comment by plafosse** [comment]
As of Binary Ninja 4.2 you now have the ability to do this:
![image](https://github.com/user-attachments/assets/87f47b1c-bc80-43a4-a7f6-0bae43ef6c57)
