### ISSUE TITLE
UI in Linear View should show both the section/segment as well as the function

### ISSUE THREAD

**Issue by rickmark** [Vector35/binaryninja-api#3841]
**What is the feature you'd like to have?**
Today the top of the scroll view shows the section/segment info when in data, but is replaced when entering a procedure.  Since procedures can occur in multiple sections it would be useful if the header became two row showing both instead of replacing:

<img width="594" alt="image" src="https://user-images.githubusercontent.com/125403/215190831-770dc400-157d-4f70-9c48-c0f495502414.png">

<img width="844" alt="image" src="https://user-images.githubusercontent.com/125403/215190912-c6413601-75c7-4749-a444-4266302f1327.png">

**Is your feature request related to a problem?**
When in a procedure I cannot quickly know what section I am in while in linear view

**Are any alternative solutions acceptable?**
Please provide a clear and concise description of any alternative solutions or features you've considered.

**Additional Information:**
Please add any other context or screenshots that would help us understand your feature request here.

**Comment by galenbwill** [comment]
The address indicator in the status bar is a clickable menu, from which you can select "Display Format":
![image](https://user-images.githubusercontent.com/12259536/215197325-56a28b0a-45dd-407c-bd74-77ebcb1add06.png)
