### ISSUE TITLE
Add "Use current (statically analyzed) value as constant" feature

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#3844]
**What is the feature you'd like to have?**
A user that contacted us via our website would like to have a feature where you can turn a variable into a constant that matches the value it has obtained from constant propagation.

**Is your feature request related to a problem?**
"Some ELF may make const offset exported or mutable to confuse (as a mutable variable, I can manually apply const type to fix, but those exported variable/pointer cannot be resolved)"

**Are any alternative solutions acceptable?**
None were provided

**Comment by ccarpenter04** [comment]
I'd never even thought of that before but it would be a very nice touch for many situations I've been in during RE sessions.. The only thing I'd like is that it was a bidirectional action. So the ability to restore the original later on if I were to come back and want to see original statement for whatever reason. So essentially either have the original expressions stored in a the const representation type or list of Tuple<Expression, const, address> that could be used to restore it to it's original state.

**Comment by plafosse** [comment]
So the original suggestion is basically what "user informed data flow" does.  The current issues with user informed dataflow is that you can't do it on HLIL and you can only do it at SSA variable definition sites, which makes it a bit cumbersome to use. I'm going to close this in favor of this: https://github.com/Vector35/binaryninja-api/issues/1970 please reopen if there's something I missed.
