### ISSUE TITLE
In linear mode, double clicking address does not jump to correct line

### ISSUE THREAD

**Issue by polsab** [Vector35/binaryninja-api#385]
In linear mode, double clicking an address (from a jump instruction for example) will take you to the line “{ Does not return }”  if it exists ((e.g. blocks with calls to exit) before the target disassembly line, instead of the on disassembly line itself.

**Comment by plafosse** [comment]
I'm not able to repro this in dev, it could have been fixed in a recent build. Does this behavior still happen for you. If so can you please provide more detail?

**Comment by polsab** [comment]
Still happening. Here's an example:

![screen shot 2016-11-29 at 7 50 42 am](https://cloud.githubusercontent.com/assets/868708/20690956/aeb8414c-b608-11e6-93ad-a8c30c50034d.png)

Clicking on 0x400816 will take the cursor to the { Does not return } line, instead of address 0x400816.

**Comment by plafosse** [comment]
Ok its an issue related to linear view, thats the info I needed.

**Comment by plafosse** [comment]
Fixed in dev. Wasn't just a linear view thing.  Annotations like `{ Does not return }` were associated the following address.

**Comment by polsab** [comment]
Thanks!
