### ISSUE TITLE
Binary Ninja not opening on MacOS Ventura 13.1 M1

### ISSUE THREAD

**Issue by h0nus** [Vector35/binaryninja-api#3853]
**Version and Platform (required):**
- Binary Ninja Version: 3.3.4025-dev Personal, 5ab69587
- OS: Mac OS
- OS Version: 13.1 Ventura
- CPU Architecture: Apple M1

**Bug Description:**
Newer version of Binary Ninja won't open on my iMac 24" with M1 chip.
If I set it to use Rosetta, it will open but with a error screen box:
![image](https://user-images.githubusercontent.com/23401728/216126274-730e33d2-39e2-4edd-8e8f-c0e735652abb.png)

**Steps To Reproduce:**
1) Download from scratch DMG Installer
2) Install Binary Ninja
3) Open it
4) Error:
![image](https://user-images.githubusercontent.com/23401728/216125430-5e400115-f1ea-4697-8f11-2a96e0738d70.png)

Extra error from CLI:
![image](https://user-images.githubusercontent.com/23401728/216125611-ae5fe75b-79f1-417d-b955-59070e6f8000.png)

**Expected Behavior:**
I expect BinaryNinja to open

**Screenshots:**
Already sent

**Additional Information:**
I already tried to use the stable version, still not working and same issues
Log informations attached (dump from crash)

[log.txt](https://github.com/Vector35/binaryninja-api/files/10560055/log.txt)

**Comment by plafosse** [comment]
I believe you have the old Bindiff plugin. Please try to disable all plugins and launch again.

**Comment by h0nus** [comment]
Thanks for fast answer, 
strange because i used the latest installer available from bindiff official website, i will try again, but what about the issue without Rosetta, is it linked to plugins thing?

**Comment by plafosse** [comment]
So I think for whatever reason its not crashing but its still calling the old BNLog API which was changed in later versions of BinaryNinja.

**Comment by psifertex** [comment]
Here's quick steps to troubleshoot both settings and plugins: https://docs.binary.ninja/guide/troubleshooting.html#troubleshooting-plugins

That said -- I don't think the latest bindiff works with our latest stable. It sometimes can take a bit for the natural binexport release cycle to update and track the latest releases of Binary Ninja. The short explanation is you're better off just doing a local build yourself and that way you can have good support for dev or stable, whichever you're using.

**Comment by h0nus** [comment]
I found the issue, thanks to your messages guys
Apparently the issue was really BinDiff's plugin under `~/Library/Application\ Support/Binary Ninja`.
To resolve i completely deleted the folder `Binary Ninja` and now works.

Thanks guys you're awesome <3

**Comment by verylazyguy** [comment]
I feel like this issue comes up enough that maybe if binja crashes on startup before plugins are finished loading that it should automatically restart without plugins on next launch with a popup alerting the user as to why
