### ISSUE TITLE
Please restore sidebar customization

### ISSUE THREAD

**Issue by cryptwhoa** [Vector35/binaryninja-api#3855]
A ways back, before the new UI was introduced (maybe a year ago?), we were free to add/remove windows in the sidebar.  The most notable example was having the xref window and the minigraph window open and viewable at the same time, in separate little boxes.

However, the new UI introduced what I think the documentation refers to as "carousels".  There are now 2 boxes: one can only show xrefs OR the minigraph, one can show all the other windows but only one at a time (types, symbols, etc.).  The current UI makes it impossible to show both the xrefs and the minigraph at the same time in the sidebar, which really hampers my ability to reverse engineer.

I was able to use the tool much more effectively with the old UI.  I actually bought a large monitor specifically for being able to display a bunch of different things at the same time in Binary Ninja (back with the old UI); I used to have 3 boxes in the sidebar: one that always showed the minigraph, and the other 2 had groups of tabs I could toggle between, depending on what I needed in the moment.  Life was glorious.

In the meantime, I've been using hotkeys quite a bit to toggle between xref/minigraph windows, but it's not a great substitute for being able to see both at the same time.  I also only recently found out that it's possible to move the minigraph to the main window, but the shape of this window is awkward for the shapes of most functions, and also eats up a lot of valuable screen real estate in the main window.

The perfect solution (for me) would be going back to the old system, or at least providing the option to, which I guess looked a little uglier but I didn't really mind.  Another idea is letting users decide the options that each carousel can show; bonus points if a user can set the number carousels too.

**Comment by op2786** [comment]
Current design of the sidebar is very restrictive. For example, let's say I want to see symbols, debugger and tags at the same time, what do I do? We should be able to freely pin any of sidebar item induvidually like in IDA.

**Comment by psifertex** [comment]
Documentation [has been added](https://github.com/Vector35/binaryninja-api/commit/5956003ebafea9cc2788b6771d07372984a7b8bf) and the feature has been live for a few weeks!
