### ISSUE TITLE
DWARF Export

### ISSUE THREAD

**Issue by KyleMiles** [Vector35/binaryninja-api#3863]
It would be nice to export types, function starts/prototypes, data variables, etc to DWARF for interoperability with other tools.

**Comment by KyleMiles** [comment]
DWARF Export included by default in builds >3.4.4127-dev. Needs more testing while on dev to shake out the bugs.

**Comment by KyleMiles** [comment]
Reopening in lue of being able to test this feature.
GDB, Angr, and Ghirda all require debug link stuff to be set in the original binary. IDA fails silently to import our debug info, getting a debug log from them would be extremely helpful. The last way to test this would be to:
1. Take a binary with no debug link information in it
2. Mark it up in BN
3. Export dwarf
4. `objcopy --add-gnu-debuglink=exported.dwo source_binary`
5. Try again with the various tools, making sure to put the binary in the correct system folders/setting the import folders in that various setting areas.

**Comment by psifertex** [comment]
Only thing remaining on this is:
- [ ] Any one of IDA, Ghidra, LLDB, etc, able to import
- [ ] Unit tests
- [ ] Documentation

**Comment by KyleMiles** [comment]
Looks in to this a little more, and it seems like IDA and GDB both require the CRC in the original binary to match. So the path forward is going to have to include exporting a modified version of the original binary. It'd be nice if that new binary included the debug info, instead of export two separate files.

**Comment by KyleMiles** [comment]
3.6.4757-dev is now compatible with (at least) GDB and IDA. I tested GDB 9.2 (20.04) and IDA 8.1. The fix was easier than expected; I just needed to change the names of the sections containing the debug info.

To get a debug file generated in Binary Ninja to work with GDB, simply open your binary in GDB and then run `symbol-file <full-path-to-generated-file>`, as you might usually do for GDB.

To get a debug file generated in Binary Ninja to work with IDA, simply open your binary in IDA and then use [Edit -> Plugins -> Load DWARF File](https://hex-rays.com/blog/igors-tip-of-the-week-55-using-debug-symbols/), as you might usually do for IDA.

The longer note for anyone who's curious: gnu binutils' `file` and `dwarfdump` only appear to look for the `.debug_info` section to determine if a file has valid DWARF info. It appears that IDA and gdb follow that convention too, if not actually leverage the same code underneath. What delayed this fix, unfortunately, is that the `dwarfdump` I got on my Mac (probably through brew) follows spec and also looks for the DWO version of that section as well (`.debug_info.dwo`). The DWARF Export and Import plugins I've been working on support "properly formatted" DWOs in addition to these sort of fake non-dwo DWOs.  In fact, if you generate a "proper" DWO with gcc (using `-gsplit-dwarf `), then strip the original binary, you can't load that DWO in GDB. You actually need to use `objcopy --only-keep-debug main-split <file>` on a binary with debug info, which just pulls out the original debug sections and puts them in their own ELF file, to get a "DWO" that works with a stripped binary in GDB. But that's not a "proper DWO" because it wasn't generated with all the DWO-specific conventions from the DWARF spec, and it's instead what I've been calling a "non-dwo DWO" because it follows all the conventions of DWARF that gets stored in the original binary instead of the "proper" separate-file conventions. In the end though it doesn't matter because we support both, and we're now exporting files that follow the conventions most other tools seem to have settled on.
