### ISSUE TITLE
The "Installed" text is misplaced in the Plugins tab.

### ISSUE THREAD

**Issue by st1064870** [Vector35/binaryninja-api#3870]
**Version and Platform (required):**
- Binary Ninja Version: 3.3.4037-dev Personal (Build ID 6efab358)
- OS: Ubuntu Linux
- OS Version: 22.04
- CPU Architecture x64

**Bug Description:**
The "Installed" text is misplaced in the Plugins tab. This is a minor user interface bug.

![Screenshot from 2023-02-05 11-45-56](https://user-images.githubusercontent.com/61602820/216812208-cfd524d3-6583-4aff-a495-7447bca71301.png)

**Comment by psifertex** [comment]
This is only an issue when the font size is increased from the default and honestly I don't think we're going to bother to make a change here -- you can always make the side-bar wider manually if you need to see the title better but I don't think we want to do that automatically.
