### ISSUE TITLE
Ability to specify stack arguments layout

### ISSUE THREAD

**Issue by mostobriv** [Vector35/binaryninja-api#3875]
**What is the feature you'd like to have?**
To be able to specify layout of function arguments on stack, using function signature. Currently it's only possible with adding custom calling convention, but would be handy to make it same way as it can be done for registers.

**Additional Information:**
For example in IDA you can use syntax:
`@<^offset:size>`

**Comment by plafosse** [comment]
Yes additionally the UI needs to be updated so it can display these types of parameters as well.

**Comment by plafosse** [comment]
Closing in favor of this: https://github.com/Vector35/binaryninja-api/issues/3340
