### ISSUE TITLE
python console - binja closes when typing help() and then modules

### ISSUE THREAD

**Issue by lucasduffey** [Vector35/binaryninja-api#388]
OS: ubuntu 16.04 LTS

binja exits/crashes if you type in the python console:
help()
modules

**Comment by psifertex** [comment]
Can you please clarify? I do something similar in this screenshot and it works fine: http://docs.binary.ninja/getting-started/index.html#script-python-console

**Comment by Manouchehri** [comment]
What OS? `help()` works fine here on Windows 10.

**Comment by lucasduffey** [comment]
it says "No handlers could be found for logger OpenGL.tk" right before the crash.

It's very brief so that string may not be exactly the same

**Comment by lucasduffey** [comment]
it's ubuntu 16.04 LTS

**Comment by psifertex** [comment]
Closing as it was not reproducible and is likely another root cause, feel free to re-open if you can figure out a reliable test case.

**Comment by lucasduffey** [comment]
not a binary ninja problem - ran in normal python shell and had the same problem.
