### ISSUE TITLE
Opening Foundation causes Binary Ninja to rapidly consume unlimited amounts of memory

### ISSUE THREAD

**Issue by saagarjha** [Vector35/binaryninja-api#3885]
**Version and Platform (required):**
- Binary Ninja Version: 3.3.4051-dev Personal (Build ID f44963d9)
- OS: macOS
- OS Version: 13.2 (22D49)
- CPU Architecture: Apple silicon

**Bug Description:**
If I open Foundation Binary Ninja quickly uses massive amounts of memory.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open Foundation from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Foundation. Alternatively pick the one I have attached to this bug.

**Expected Behavior:**
The binary loads.

**Additional Information:**
[Foundation.zip](https://github.com/Vector35/binaryninja-api/files/10695155/Foundation.zip)

**Comment by 0cyn** [comment]
Resolved in development **builds >= 3.6.4596**
