### ISSUE TITLE
Plugin list in plugin manager does not follow application font size

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#3889]
![Screenshot 2023-02-13 at 11 23 38 AM](https://user-images.githubusercontent.com/94503187/218363377-0a09f14a-2d4d-4da3-ab01-0942dae3d46e.png)

I set the font to be very large and the plugin list font does not chagne

**Comment by xusheng6** [comment]
Note this is different from https://github.com/Vector35/binaryninja-api/issues/3891. Right now the Plugin list view ignores the font setting, even after restart.

**Comment by fuzyll** [comment]
Related to #2201.

**Comment by fuzyll** [comment]
Fixed in builds >= 3.3.4075-dev.
