### ISSUE TITLE
Crash when saving bndb

### ISSUE THREAD

**Issue by Moneyl** [Vector35/binaryninja-api#3894]
Binary Ninja Version: 3.3.4063-dev Personal, 6dbbe983
Platform: Windows 11 Version 22H2

One of my projects crashes when I try to save it. I emailed the bndb file to binaryninja@vector35.com. This crash happens on 3.3.3996 Personal as well. 

Steps to reproduce:
- Open the bndb file.
- Save with `Ctrl + S` or `File > Save`.
- Binja will crash mid-save. Any changes made since opening aren't saved.

I don't know when this problem started. The project saved fine initially. I realized there was a problem when I opened the project today and found my latest changes from yesterday were gone.

**Comment by negasora** [comment]
Looks like there's a 0 width enum created that's causing cascading failures in type deserialization. Did you create any funky types via the api?

**Comment by negasora** [comment]
Crash fixed in `3.3.4067-dev`

**Comment by Moneyl** [comment]
Thank you. I haven't used the API yet, so I don't know how that happened. I only recognize one enum in the project as one I added myself and it has `uint32_t` as its base. Are updates pushed nightly and/or with a delay? The highest version I see is `3.3.4065-dev Personal`.

**Comment by fuzyll** [comment]
Changes we make are pushed as soon as the build finishes and passes a battery of unit tests. In this specific case, it looks like we forgot to update a unit test and the build failed. But, there should be a build >= 4067 coming out in the next few hours that will contain the fix.
