### ISSUE TITLE
Disabling the view plugins in settings doesn't disable the view plugins

### ISSUE THREAD

**Issue by cxnder** [Vector35/binaryninja-api#3895]
**Version and Platform (required):**
- Binary Ninja Version: 3.3.4064
- Machine: macOS 13.0 M2

**Bug Description:**
When I disable the view plugins in settings they are not disabled.

**Steps To Reproduce:**
1. Disable a view plugin
2. Load a file that uses that view and note it is not disabled

**Expected Behavior:**
Setting to disable the view plugins should disable the view plugins.

**Screenshots:**
![image](https://user-images.githubusercontent.com/55725881/218647592-877bf72a-05de-41b2-a6f2-c12d8c1283cc.png)
![image](https://user-images.githubusercontent.com/55725881/218647693-307e01b4-d878-4563-a88a-2d342c919d9b.png)

**Additional Information:**
Can be worked around by just deleting the library from the current install.

**Comment by xusheng6** [comment]
This only affects Mach-O view, I tested ELF view and it works fine.
