### ISSUE TITLE
python plugins should be split from the UI thread

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#390]
Python plugins currently run on the same thread as the UI, they need to be run on a separate thread and also allow for viewing the status of running plugins as well as interrupting them when needed via api or user-feedback. 

Likely also need a progress bar so the plugin can indicate their status.

**Comment by lucasduffey** [comment]
BackgroundTaskThread example is in https://github.com/Vector35/binaryninja-api/blob/dev/python/examples/angr_plugin.py#L31

**Comment by psifertex** [comment]
Thanks for linking that here. We consider this issue resolved with the addition of the feature.
