### ISSUE TITLE
Problems opening a bndb after updating

### ISSUE THREAD

**Issue by Moneyl** [Vector35/binaryninja-api#3907]
Binary Ninja Version: 3.4.4078-dev Personal, 5afd2ed0
Platform: Windows 11 Version 22H2

I have a bndb for a particular exe that is having problems if I open it with a version of Binary Ninja newer than the version it was last analyzed & saved with. The steps I'm taking leading up to the problem:
1) Analyze the exe with `File > Open with Options...`. I set the PDB path here as well.
2) The exe analyzes without issue and I'm able to save the bndb without issues.
3) Update binja and try to open the bndb again. From here 1 of 2 things can happen:
    3a) The bndb fails to open. Binja keeps loading it indefinitely or crashes.
    3b) The bndb opens and Binja starts analyzing it automatically. Analysis gets stuck on one of the functions and Binja shows 100% cpu usage in task manager. I left it running for 30min and it was still stuck on the same function.

I'll send a bndb to binaryninja@vector35.com shortly. I created it with a version of Binja on the dev branch from yesterday. If you open it with one the dev versions from today, you should see 3a and/or 3b.

**Comment by plafosse** [comment]
Thank you for the report. This is a critical issue and we will try to address it immediately.

**Comment by bpotchik** [comment]
Fixed in `3.3.4079-dev`.
