### ISSUE TITLE
Use Python libraries from system

### ISSUE THREAD

**Issue by Manouchehri** [Vector35/binaryninja-api#391]
We should import Python libraries from the system for Binja to use (so I don't have to do `sys.path.append('C:\\python27-64\\lib\\site-packages')` all the time).

![image](https://cloud.githubusercontent.com/assets/7232674/17824147/58e9fa46-662e-11e6-82d5-ea404541c5f2.png)

**Comment by Manouchehri** [comment]
As a temporary fix, throw this in your plugins folder.

```python
import sys
sys.path.append('C:\\python27-64\\lib\\site-packages')  # Change to match your install folder.
```

**Comment by psifertex** [comment]
I'm going to mark this as closed won't fix for now though that could change. I'd rather not probe/search for existing libraries (since they could be in different locations, be different versions, etc). It's simpler to have your plugins work with your system the way you've done above so there's no guessing.

**Comment by Palantir555** [comment]
+1 for @Manouchehri 's idea. If you're not gonna import standard library paths, at least explicitly state in the GUI what needs to be done to fix the issue. I wasn't sure whether binja shipped with its own copy of python2.7 or what; pretty confusing. A simple `pip --version` will tell you where pip libraries are installed by default:

```
$ pip -V
pip 8.1.2 from /usr/local/lib/python2.7/site-packages (python 2.7)
```

**Comment by Manouchehri** [comment]
I'm no programmer, but I think identifying where the system's Python folder wouldn't be too difficult.

IDA has done this by default (on Windows at least) for awhile.

**Comment by Manouchehri** [comment]
@psifertex This behavior is still different across platforms..

**Comment by psifertex** [comment]
It is, because different platforms have different native pythons by default. Note that you can always use pip install via the console itself to ensure the dependencies are installed in the "right" Python. 

```import pip

pip.main(['install', package])```

**Comment by mrexodia** [comment]
These are the kind of hacks I use to automagically detect the python home. https://github.com/x64dbg/x64dbgpy/blob/v25/py.cpp#L626
