### ISSUE TITLE
Binary Ninja crashed, now crashing when re-opening database

### ISSUE THREAD

**Issue by FirehaK** [Vector35/binaryninja-api#3911]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4084-dev Personal, 6b32dfcc
- OS: MacOS
- OS Version: Ventura (13.0)
- CPU Architecture x64

**Bug Description:**
When double clicking on an address in the graph view to view a string and its surrounding contents, Binja crashed before loading that view. I had already saved the database by this point, so I attempted to reopen the bndb file which is resulting in a crash every time it loads.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open bndb file

**Expected Behavior:**
I expect Binary Ninja to load the bndb file. 

**Additional Information:**
Loading the original exe or other database files still works just fine.

I am happy to provide the ransomware sample as well if it will be useful.

[2ebf7598f3cd118a8c91bdc9c07aec5d2f45506c7b2c83baa4305c6bc8c91dc3.bndb.zip](https://github.com/Vector35/binaryninja-api/files/10772962/2ebf7598f3cd118a8c91bdc9c07aec5d2f45506c7b2c83baa4305c6bc8c91dc3.bndb.zip)

**Comment by FirehaK** [comment]
Immediately after submitting this issue, Binary Ninja happily loaded my database file, but is still (seemingly) randomly crashing. I'm attaching the crash logs from console.app.

[Binary Ninja crash logs.zip](https://github.com/Vector35/binaryninja-api/files/10772987/Binary.Ninja.crash.logs.zip)

**Comment by plafosse** [comment]
Fixed in 3.3.4088
