### ISSUE TITLE
Segfault in libbinaryninjaui's CrossReferenceTreeModel

### ISSUE THREAD

**Issue by SmoothHacker** [Vector35/binaryninja-api#3912]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4084-dev
- OS: MacOS Ventura
- OS Version: 13.2.1
- CPU Architecture: M1

**Bug Description:**
Binary Ninja's `libbinaryninjaui.1.dylib` segfaults in the `CrossReferenceTreeModel::parent(QModelIndex const&)` function.

**Steps To Reproduce:**
1. Open the `passme` binary
2. Go to the `_GLOBAL_OFFSET_TABLE_` at `0x804bff4`
3. Select the symbol and hit the `o` key to make it a pointer
4. Binary Ninja should segfault

**Expected Behavior:**
The `_GLOBAL_OFFSET_TABLE_` should have a pointer type and not segfault.

**Additional Information:**
I've attached an example binary and the macOS crash dump in [Archive.zip](https://github.com/Vector35/binaryninja-api/files/10775030/Archive.zip)

**Comment by plafosse** [comment]
Fixed in 3.3.4088
