### ISSUE TITLE
Show/hide column on new symbols UI should be one context menu

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/binaryninja-api#3920]
The current menu for showing or hiding columns in the new symbols UI looks like this:

<img width="364" alt="image" src="https://user-images.githubusercontent.com/41548458/220456931-76f7d8a8-4617-4b31-85b2-ee33a7a2c6a2.png">

I think it would make much more sense if there was simply a "Columns" submenu with checkable menu items for each column.

**Comment by psifertex** [comment]
Doesn't even need to be a sub-menu. A top section with enable/disable for the headers and then a bottom divider with "reset header" seems more than sufficient for now. The only other thing that make it require a submenu would be adding sorting to the context menu for the header too.
