### ISSUE TITLE
Parse PE rich header information

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#3932]
I frequently get this information via other tools, maybe BN would parse it for us in future versions.

https://github.com/dishather/richprint

**Comment by plafosse** [comment]
Additionally we should put this information in the BinaryView Metadata so it can be easily queried by the user if needed.

**Comment by plafosse** [comment]
This is done now and displayed in the linear view header
![image](https://github.com/user-attachments/assets/241abbec-c175-4524-8e27-4872cae56976)
