### ISSUE TITLE
Allow cut & paste in components 

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#3933]
I would like to cut & paste functions in symbols. 

For example I've created a "t123" folder, then put 5 function in it those starts with `test_`. After some reversing I've found 10 more functions that should named with `test_` prefix. Now I want to search `test_` and cut those functions and paste them into "t123" folder.

**Comment by bpotchik** [comment]
You can now accomplish this by using the context menu and using the "Move Selection to" action. There will be a list of existing target folders where you can move the selected items.

It's very unlikely that we will implement a Cut/Paste variant for this behavior.
