### ISSUE TITLE
Log window font is not monospaced correctly

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#3939]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4093-dev
- OS: macOS
- OS Version: 12.4
- CPU Architecture: M1

**Bug Description:**
The text in the log window does not have the same horizontal advance for all characters. This means that lines that were designed to line up in a monospaced grid do not actually line up.

**Steps To Reproduce:**
1. Open the python console and enter `print("M"*80+"A\n"+" "*80+"A")`
2. Observe the 'A's line up in the console
3. Now enter `log_info("M"*80+"A\n"+" "*80+"A")` and look at the log window
4. Observe the 'A's do not line up

**Expected Behavior:**
I expected the clearly monospace font to be monospaced.

**Screenshots:**
<img width="728" alt="why" src="https://user-images.githubusercontent.com/711973/221004478-daf711c7-db47-4038-b7dc-97613b728d8b.png">

**Additional Information:**
This is with default font settings

**Comment by CouleeApps** [comment]
Fixed in 3.5.4281-dev

**Comment by psifertex** [comment]
Duplicate of #1674
