### ISSUE TITLE
Cannot resize function view when viewing function with long name

### ISSUE THREAD

**Issue by sboesen** [Vector35/binaryninja-api#394]
When viewing a function with a long name, I cannot resize the function list larger than screenshot below.

<img width="1280" alt="screen shot 2016-08-19 at 10 31 01 pm" src="https://cloud.githubusercontent.com/assets/248703/17829215/badf2626-665c-11e6-9f11-3f8998f8fffa.png">

Navigating away to a function with shorter name allows me to resize:
<img width="1280" alt="screen shot 2016-08-19 at 10 31 38 pm" src="https://cloud.githubusercontent.com/assets/248703/17829216/bfe674f8-665c-11e6-80c6-ec436b9f8cb2.png">

**Comment by plafosse** [comment]
This is essentially a dup of #7
