### ISSUE TITLE
Incorrect lifting of SSE `mulsd` in x86

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#3940]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4093-dev
- OS: macOS
- OS Version: 13.2
- CPU Architecture: arm64

**Bug Description:**
In x86, we lift instructions like `mulsd   xmm0, qword [rel data_180072d90]` incorrectly. We say that the second argument is `fconvert.t`'d, but [that is not the case](https://www.felixcloutier.com/x86/mulsd#mulsd--128-bit-legacy-sse-version-). The source of the problem is `ReadFloatILOperand` in `arch-x86`, which doesn't seem to have the option to treat this operand as a 64-bit value.

**Expected Behavior:**
The `fconvert.t` should not be emitted.

**Screenshots:**
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/607452/221063608-93d33e66-fb4e-4894-98c6-8ff9004c0595.png">

**Comment by fuzyll** [comment]
Updating this at @lwerdna's request.

When I made the original issue, the problem was that the second operand _could_ be a 64-bit value (which, in the screenshot, it is). But, we were unconditionally treating it as a 10-byte value (the `.t` in `fconvert.t`).

Right now, on `dev`, this issue does not repro. It _looks_ like there's a second issue:

![image](https://github.com/Vector35/binaryninja-api/assets/607452/9ce4b6c5-121d-451e-95c4-4b778acffcac)

...because it does an `fconvert.s` of the resulting value. But, this should be because of the `cvtsd2ss`, which is correct.

As a result, I _believe_ this issue can be closed. If anyone disagrees or has other examples where this is still wrong, please update the ticket and we'll reopen it.

**Comment by lwerdna** [comment]
Thanks @fuzyll, I'll hit enter on my draft here since extra info can't hurt...
 
The fconvert llil doesn't come from `mulsd` instruction, but from the `cvt2sd2ss` instruction.

The `mulsd` instruction lifts to:

```
LLIL_SET_REG.q
	xmm0
	LLIL_FMUL.q
		LLIL_REG.q
			xmm0
		LLIL_LOAD.q
			LLIL_CONST.d(0x6DAF3)
				449267
```

The asm -> llil mapping is nice and one-to-one:

![mapping-llil](https://github.com/Vector35/binaryninja-api/assets/474191/cf30d6cf-b571-4ac1-87a6-c0ccf0f8fd15)

The asm -> to hlil mapping is many-to-one, and clicking the hlil highlights the contributing asm instructions to the left:

![mapping-hlil](https://github.com/Vector35/binaryninja-api/assets/474191/7179a5a7-a4c8-4e99-a0c1-c46e1205eaf5)

As Peter noted, that fact that a nice round number like .1 is being converted and displayed (versus high entropy digits), is evidence in favor of conversion occurring correctly.

**Comment by fuzyll** [comment]
For more context, I believe this commit is what fixed it: https://github.com/Vector35/arch-x86/commit/5b134ac7da45c009094faf654f613a9ecd11cae8.

**Comment by lwerdna** [comment]
Sorry to beat a dead horse, but the [llil transpiler](https://github.com/Vector35/llil_transpiler) just got some more floating point support, and we have the means to test if the lifting is correct. Using this C:

```C
float fp_convert_double_product_to_single(double a, double b)
{ return a * b; }
```

the compiler generates:

```
push	rbp
mov	rbp, rsp
movsd	qword ptr [rbp - 8], xmm0
movsd	qword ptr [rbp - 16], xmm1
movsd	xmm0, qword ptr [rbp - 8] ## xmm0 = mem[0],zero
mulsd	xmm0, qword ptr [rbp - 16]
cvtsd2ss	xmm0, xmm0
pop	rbp
ret
```

which contains the `mulsd`, `cvtsd2ss` combination. That lifts/transpiles to:

```C
PUSH_Q(REG64("rbp"));
SET_REG64("rbp", REG64("rsp"));
STORE64(ADD64(REG64("rbp"), -8), LOW_PART_Q(REG128("xmm0")));
STORE64(ADD64(REG64("rbp"), -16), LOW_PART_Q(REG128("xmm1")));
SET_REG128("xmm0", ZX_O(LOAD64(ADD64(REG64("rbp"), -8))));
SET_REG128_Q("xmm0", FMUL64_Q(REG128_Q("xmm0"), LOAD64(ADD64(REG64("rbp"), -16))));
SET_REG128_D("xmm0", FLOAT_CONV64_S(REG128_Q("xmm0")));
SET_REG64("rbp", POP_Q());
RET(POP_Q());
```

which, when executed, correctly computes and returns several floating point products in the test cases 👍.
