### ISSUE TITLE
Components view does not re-sort when you add/rename symbols

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#3942]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4093-dev
- OS: macOS
- OS Version: 12.4
- CPU Architecture: M1

**Bug Description:**
I renamed and created a bunch of symbols/data variables, but the components view did not show them in the right order until i manually toggled the sorting order back and forth.

**Steps To Reproduce:**
1. Enable new components UI
2. Open a binary
3. Create a couple symbols
4. Rename some of the symbols
5. Watch how they are not sorted properly

**Expected Behavior:**
I expected the sorting to update when I make changes

**Screenshots:**
<img width="713" alt="image" src="https://user-images.githubusercontent.com/711973/221064429-bb4f3928-76d3-4503-a158-350ba4a63335.png">

**Comment by cxnder** [comment]
Resolved in builds >= 3.4.4149
