### ISSUE TITLE
Structure field references to a function only display the structure name in xrefs

### ISSUE THREAD

**Issue by negasora** [Vector35/binaryninja-api#3943]
It should also show the field referencing it

Repro steps:
1. Open the bndb in [no_ref_fields.bndb.zip](https://github.com/Vector35/binaryninja-api/files/10819703/no_ref_fields.bndb.zip)
2. Click `sub_8`
3. Notice the xrefs pane doesn't show the field that references the function

**Comment by fuzyll** [comment]
I thought this was also related to #899 (and it still might be), but the function in question is actually referenced from the _second_ field of the struct (whereas that ticket is about problems surrounding the _first_ field of the struct). Still repros on latest stable (3.4), though.

**Comment by negasora** [comment]
Fixed in `4.2.5943-dev`
