### ISSUE TITLE
`BinaryView.lookup_imported_object_library` returns `Qualifiedname` despite the type hint says `str`

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#3947]
The type hint says the second return value is a `str`, https://github.com/Vector35/binaryninja-api/blob/1230d1edcf09fa825985c204b115241141332a91/python/binaryview.py#L7201-L7203

But we can see it is a `QualifiedName`:

```
>>> type(bv.lookup_imported_object_library(here)[1])
<class 'binaryninja.types.QualifiedName'>
```

Also evident from the code:

https://github.com/Vector35/binaryninja-api/blob/1230d1edcf09fa825985c204b115241141332a91/python/binaryview.py#L7222-L7224

**Comment by plafosse** [comment]
Fixed in 3.3.4123
