### ISSUE TITLE
Show full filename on tooltip when hovering on tab

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#3949]
**What is the feature you'd like to have?**
Show the full name of a file on a tooltip when you mouse over a tab.

**Is your feature request related to a problem?**
Having multiple, similarly-named files open is problematic because it's difficult to tell which is which.

**Are any alternative solutions acceptable?**
Fitting more text onto the tab somehow would also help, but would not solve the problem. Honestly not sure if there are any better alternatives here.

**Comment by negasora** [comment]
Added in `3.6.4735-dev`
