### ISSUE TITLE
Inconsistent search results via UI vs Headless on Windows 10

### ISSUE THREAD

**Issue by malre0x21** [Vector35/binaryninja-api#3954]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4097-dev
- OS: Windows 10 Enterprise
- OS Version: 1607
- CPU Architecture x64

**Bug Description:**
When doing a HLIL text search for `rcx_2 ^ arg5` in the UI i get the correct results however if i use the API directly (in the UI or completely headless) with the following params `bv.find_all_text(bv.start,bv.end, text="rcx_2 ^ arg5", flags=FindFlag.FindCaseInsensitive, graph_type=FunctionGraphType.HighLevelILFunctionGraph)` the search fails. When i do this on a Mac (same dev version of binja and same target binary) the search via both the UI and API returns the correct results. The screenshot is from my windows 10 instance with the failed API search.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
In the UI
1. Ctrl+F to open the find menu
2. Set the search for Text(HLIL)
3. Add search term in the search box
4. Place a check next to "Case Insensitive"
5. Place a check next to "Find all"
6. Press Find button

Steps via the API
bv.find_all_text(bv.start, bv.end, text="rcx_2 ^ arg5", flags=FindFlag.FindCaseInsensitive, graph_type=FunctionGraphType.HighLevelILFunctionGraph)

**Expected Behavior:**
The returned queue size should contain the same results when running the same search via the UI or API 

**Screenshots:**
![image](https://user-images.githubusercontent.com/103318403/221920563-146be17e-aa7b-435b-b1df-27d92ac965fc.png)

**Additional Information:**
- I was just playing around and turns out simply adding a ,  after the final param of graph_type will return the correct results on windows 10 from the UI
- Further testing running this completely headless from the windows terminal with and without a , after graph_type i still get incorrect results.

**Comment by xusheng6** [comment]
Thx for filing, I will have a look!

**Comment by vergil-SI** [comment]
I am experiencing this same issue on Linux between the UI search vs API search. The inconsistencies seem to be somewhat random when I use the API. I can do small insignificant things, like scroll through the project, and suddenly the API search will find different results. Re-opening or re-analyzing also seems to cause it to sometimes change its results dramatically. 3.4.4270-dev

**Comment by xusheng6** [comment]
I can reproduce this. This only happens on Windows. 

A sample that triggers this bug (warning: malware!):

[OllzGZn.zip](https://github.com/Vector35/binaryninja-api/files/12145509/OllzGZn.zip)
