### ISSUE TITLE
Enhancement: Any-case substring symbol search

### ISSUE THREAD

**Issue by FuzzySecurity** [Vector35/binaryninja-api#3957]
When you change the type of a variable, the search is case-sensitive and you have to enter text from the first character of the symbol name.

This doesn't work:
![image](https://user-images.githubusercontent.com/10997340/221944825-14459e38-e5ce-4365-b2cc-48ed9c9ca341.png)

This doesn't work:
![image](https://user-images.githubusercontent.com/10997340/221944871-a2e081f5-8c82-47a1-adb6-5438b99e77a3.png)

This works
![image](https://user-images.githubusercontent.com/10997340/221944922-067dd5a8-1193-46a6-96ff-f38d30d53c0c.png)

This should really be changed to any-case and do a substring match on all the symbols.

Binary Ninja Version: 3.4.4080-dev Personal, 842d9298

**Comment by psifertex** [comment]
Good suggestion -- added in builds >= 4098.

**Comment by psifertex** [comment]
Oh, to be clear, I made it case insensitive -- doing a substring match might have more performance implications for binaries with extremely large numbers of types so I want to do some more testing on that.

**Comment by psifertex** [comment]
After playing a bit with the substring matching there's enough unexpected behavior that I'm going to hold off implementing this for now. It's not clear in the long-run whether the better results will be surfaced more easily with or without the setting. Potentially we'll add it as an option but not sure. The actual line of code for subtring matches is trivial:
```
       m_combo->completer()->setFilterMode(Qt::MatchContains);
```
the real fix though would be implementing a new sorter that would match the substring also but sort the results to surface prefixed matches first but that's a bit more work.

**Comment by psifertex** [comment]
By "unexpected" I mean, "does the user get what they want when they type a small bit of text from their desired type". Not that it doesn't work as expected, just that it doesn't always produce better results given some common workflows.

**Comment by psifertex** [comment]
Yeah, it would definitely be off by default without that implementation I described above. Sure, I just added "ui.types.substring" into settings, it will be on dev builds >= 4111
