### ISSUE TITLE
Enhancement: The Windows type system needs TLC

### ISSUE THREAD

**Issue by FuzzySecurity** [Vector35/binaryninja-api#3959]
This is a big one for me. All know Windows types should be imported so it is easy to make arbitrary data types. This is just an example I tried by copying a struct from msdn but you get the idea. I encountered this while looking at a driver as well, it can be a big time sync to have to define these.

![image](https://user-images.githubusercontent.com/10997340/221949482-54fbd7d8-5a79-4776-9579-6045cdb51e29.png)

Binary Ninja Version: 3.4.4080-dev Personal, 842d9298

**Comment by fuzyll** [comment]
Closing in favor of #3836, which is a bit more broad and encompasses the full issue better.

We do actually define at least some of those types in a type library (possibly `msvcrt.dll`?). Not sure why it's not being loaded in your case, but we don't currently have a good way of pulling those types out manually right now. So, that's also a part of this issue (and is being worked on separately for an upcoming release).

Thanks for the report, though! Please feel free to 👍 the other issue so we can continue to track how many people are being affected and prioritize accordingly.
