### ISSUE TITLE
Alignment of padding bytes in types view /pane could be improved

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#3965]
Binary Ninja Version: 3.4.4090-dev 
Platform: Windows 11 Version 22H2

Looks like there is some weird alignment issues in both types view and pane. See the GIF please.

![padding_bytes](https://user-images.githubusercontent.com/109607896/222087832-747d55d6-3bbc-4a6c-b038-5c8e747b6a1e.gif)

**Comment by CouleeApps** [comment]
This does not appear to be an issue on the new types browser, available as of 3.6.4615-dev
