### ISSUE TITLE
Crash when 2 instruction sequence is encountered

### ISSUE THREAD

**Issue by D0ntPanic** [Vector35/binaryninja-api#3970]
If the following two instructions occur in the instruction steam, Binary Ninja will crash.

0fe0a0e1   mov     lr, pc
08f09de4   ldr     pc, [sp],  #0x8 {var_8}

To repro, just place the opcode bytes in a new file and make an armv7 function out of them.

**Comment by plafosse** [comment]
Crash is here: https://github.com/Vector35/arch-armv7/commit/72a728d061d3dcab83c67af9fb1094a028d19c30#diff-674748bfdb6938a89d14654f976e4a5058d3a0679dfaa5f56a3a0e549e14debfR1618
Because the instruction `tgtInstr` isn't verified to be an `LLIL_JUMP` so the

**Comment by bpotchik** [comment]
Fixed in `3.4.4158-dev`.
