### ISSUE TITLE
Inconsistency in jump table recovery depending on LDR, TBB/TBH

### ISSUE THREAD

**Issue by lwerdna** [Vector35/binaryninja-api#3971]
This is copied from slack:

> Hello, there's an issue with how switch cases are being resolved if the compiler chose to use the ldr instruction instead of tbb/tbh for the jump table. I've seen this a few times now on arm cortex-m3 compiled firmware, was taking a look at how the IL was being generated to see if it could be easily fixed, but I imagine you will track it down significantly faster

Screenshot:

![issue](https://user-images.githubusercontent.com/474191/212404522-64fd7fd1-c025-4eb7-9cdc-746c4b529682.png)

Repro binary:

[lpc1769_semaforo.axf.zip](https://github.com/Vector35/arch-armv7/files/10414868/lpc1769_semaforo.axf.zip)

> For that binary, you'll see it in SetSemaphore()

**Comment by bpotchik** [comment]
Fixed in `3.4.4195-dev`.
