### ISSUE TITLE
Wrong IL for MemAtomicCompareAndSwap instructions

### ISSUE THREAD

**Issue by skr0x1c0** [Vector35/binaryninja-api#3995]
Consider `CAS <Xs>, <Xt>, [<Xn|SP>{,#0}]` instruction. Apart from compare and swap, this instruction will also save the value loaded from memory to register `Xs`. Currently generated IL only implements the compare and swap part.

#### Example instruction

```
cas        x0,x1,[x2]
```

#### Generated IL

```
0 @ 0x0  if (x0 == [x2].q) then 1 else 3 @ 0x4
1 @ 0x0  [x2].q = x1
2 @ 0x0  goto 3 @ 0x4
3 @ 0x4  undefined
```

#### Expected IL

```
0 @ 0x0  temp0.q = [x2].q
1 @ 0x0  if (x0 == temp0.q) then 2 else 4
2 @ 0x0  [x2].q = x1
3 @ 0x0  goto 4
4 @ 0x0  x0 = temp0.q
```

**Comment by negasora** [comment]
Unsure how long ago this was fixed, but as of `4.0.5336` the lifting is correct: 
![image](https://github.com/Vector35/binaryninja-api/assets/3020965/2ad4a52d-cd63-47a7-94a3-0e8e440e245c)
