### ISSUE TITLE
Associate .bndb files with Binary Ninja

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#4]
_From @D0ntPanic on September 22, 2015 2:51_

Need to associate the database files with the application so that it will open the application and the database automatically when clicked in Finder/Explorer

_Copied from original issue: Vector35/binaryninja#50_

**Comment by plafosse** [comment]
Done for Windows and Mac in dev branch.

**Comment by plafosse** [comment]
Follow #224 for status of Linux
