### ISSUE TITLE
Remaining unlifted instructions from ARM64e DYLD

### ISSUE THREAD

**Issue by lwerdna** [Vector35/binaryninja-api#4000]
This is just a branch off of issue Vector35/binaryninja-api#4002 for the [DYLD binary](https://drive.google.com/file/d/1ChbTlzoOSTJ52q5xJ6bfr-4shXxVQq8Z/view?usp=sharing) (@brinlyau provided) in particular.

Current unlifted status:

```
       4            swpl [0x52168, 0x52370, 0x540d8, 0x54188]
       3         ldaddal [0x10368, 0x4c898, 0x557d4]
       2            uxtl [0x2ad98, 0x2b1b4]
       2              dc [0x52d40, 0x52d40]
       1             xtn [0x274a8]
       1           ucvtf [0x47988]
       1            ldxr [0x56e20]
       1            stxr [0x56e28]
```

**Comment by brinlyau** [comment]
These are all fixed in the latest master branch. Think you could pretty much close it now (or once it's in -dev)

**Comment by lwerdna** [comment]
As of cb41c34f the non-predicated UCVTF instructions are lifted to intrinsics.
