### ISSUE TITLE
Collaborative effort to add support for missing lifting support for certain instructions present in common platform binaries

### ISSUE THREAD

**Issue by brinlyau** [Vector35/binaryninja-api#4002]
Pasting a bunch of them here, so we can all take a stab and not duplicate work :) 

This is from [/usr/lib/dyld](https://drive.google.com/file/d/1ChbTlzoOSTJ52q5xJ6bfr-4shXxVQq8Z/view?usp=sharing)  on a ARM64e iOS device.

We lifted it!

**Comment by WZ-Tong** [comment]
For android arm64 lib, among all unimplemented instruction, `stlxr` is quite common (even if you compare it with `ldaxr` and other locked read/write instructions), it can just be represented as 2 `mov` operation (store value, set lock register, maybe add `WRITE_LOCKED (var)` wrapper in HLIL), I hope this instruction will be implemented soon.

**Comment by yrp604** [comment]
https://github.com/Vector35/arch-arm64/commit/2a8e100cdc489baf7669a3969cb6a1fcd0f247f6 is an example commit if you want to lift them yourself. Otherwise this is the relevant discussion for how they should be lifted: https://github.com/Vector35/arch-arm64/discussions/117
