### ISSUE TITLE
Broken register calculation in this version

### ISSUE THREAD

**Issue by Leseratte10** [Vector35/binaryninja-api#4018]
After Vector35/arch-ppc#2 I have to open another issue, I believe the version I compiled myself from this source code behaves differently (and wrong) from the version that's included with Binary Ninja. 

With the version in Binary Ninja I get this disassembly (correct): 
![Bildschirmfoto von 2021-02-13 21-30-02](https://user-images.githubusercontent.com/6040787/107860934-a7f9e080-6e42-11eb-9b3f-7b3fd7efd24f.png)

With the version I'm compiling myself (most recent commit on the dev branch, most recent version of capstone), I get this disassembly (wrong): 
![Bildschirmfoto von 2021-02-13 21-33-32](https://user-images.githubusercontent.com/6040787/107861004-33737180-6e43-11eb-9ab0-4c59c104e65a.png)

Now it thinks that "addi r0, r4" with the last two bytes being ff fa would result in 0x0000fffa in the register, but that's wrong. It should be 0xfffffffa (-6). This makes all the offset calculations wrong, like for the jump table. 

Could this be a bug in the capstone code?
Can someone tell me which exact version of capstone is used to compile the ppc-capstone in the current Binary Ninja, so I can try that as well to rule out a capstone bug?

**Comment by lwerdna** [comment]
We've resolved this by having Capstone as a submodule, fixed at a particular commit, [this one from Mar 5, 2017](https://github.com/capstone-engine/capstone/commit/bac2b3b2023d2d3ad76398c76d64ceb308a606cb).

```
$ git clone https://github.com/vector35/arch-ppc
$ cd arch-ppc
$ git submodule update --init --recursive
Submodule 'capstone' (https://github.com/capstone-engine/capstone.git) registered for path 'capstone'
Cloning into '/private/tmp/arch-ppc/capstone'...
Submodule path 'capstone': checked out 'bac2b3b2023d2d3ad76398c76d64ceb308a606cb'
```

I'll update arch-ppc's readme to mention this, and also there should be an upgrade to capstone 5 soon: https://github.com/capstone-engine/capstone/tree/5.0.
