### ISSUE TITLE
Error during analysis on Win64

### ISSUE THREAD

**Issue by RyanAiden** [Vector35/binaryninja-api#402]
If you load the attached program eventually Binary Ninja will become unresponsive and gradually starts consuming all your memory until you kill it.  

This was tested with the Personal license under Windows x64. 

[sublime_text.zip](https://github.com/Vector35/binaryninja-api/files/430817/sublime_text.zip)

**Comment by psifertex** [comment]
Fixed in dev.

**Comment by D0ntPanic** [comment]
This is still unreliable. Works with 3 worker threads (commercial), but endlessly analyzes with personal (1 worker).

**Comment by D0ntPanic** [comment]
Personal now correctly analyzes in dev
