### ISSUE TITLE
PPC: Fails to disassemble 'fcmpu' instruction

### ISSUE THREAD

**Issue by viclw** [Vector35/binaryninja-api#4020]
Per issue Vector35/binaryninja-api#4023 there should be support for disassembling the 'fcmpu' PPC instruction.  However, it is not supported in the latest Binary Ninja version (2.0.2243-dev).

To reproduce, please reference address 0x1000bd58 in the [ls.zip](https://github.com/Vector35/binaryninja-api/files/4832567/ls.zip) binary.

**Comment by lwerdna** [comment]
Fixed, just update to latest 👍 

![image](https://github.com/Vector35/binaryninja-api/assets/474191/d0ce221c-64c9-4515-a6e1-4b529e225a8c)
