### ISSUE TITLE
Lift the `int` instruction

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4026]
Looks like currently Binary Ninja does not lifts (I guess it is called lifting?) `int` instruction. It's a bit sad to see undefined in HLIL.

![int_lifting](https://user-images.githubusercontent.com/109607896/196897004-9587c1ca-073f-454c-9b28-2b80c01e8b1a.PNG)

**Comment by lwerdna** [comment]
Fixed at https://github.com/Vector35/arch-x86/commit/ce54c270537a36255608cd1f67df64f971558d0e, will be in dev soon.
