### ISSUE TITLE
Go to address in context menu ambiguous

### ISSUE THREAD

**Issue by Grazfather** [Vector35/binaryninja-api#404]
When I right click on an address, e.g. in `mov edx, dword [data_8ec1d8]`, it behaves the same as normal go to address (popping up the modal), as opposed to what I think most would expect: Go to the address under the cursor.

Yes you can double click to go to `data_8ec1d8`, so maybe there should either be an extra option in the context menu or even just add `...` to "Go to address" as in "Enter comment..." which suggests the modal.

**Comment by psifertex** [comment]
I don't think it's useful to replicate the double click functionality in the context menu, but don't mind adding an ellipsis for clarity. Fixed in dev.

**Comment by Grazfather** [comment]
WFM. ty.
