### ISSUE TITLE
Back and forward not working with mouse on OSX

### ISSUE THREAD

**Issue by Grazfather** [Vector35/binaryninja-api#405]
According to my event viewer, these mouse buttons are sending `COMMAND_L + BRACKET_RIGHT` and `COMMAND_L + BRACKET_LEFT`. This works in my web browser and I would expect it to work in binja.

**Comment by psifertex** [comment]
I unfortunately this is a QT bug. Our exact code for all platforms is: 

```
void ViewFrame::mousePressEvent(QMouseEvent* event)
{
	if (event->button() == Qt::BackButton)
		back();
	else if (event->button() == Qt::ForwardButton)
		forward();
	else
		QWidget::mousePressEvent(event);
}
```

**Comment by Grazfather** [comment]
Ah that sucks. Do you happen to know the keycode that should normally be sent? I had to do some custom mapping with Karabiner on OSX to get it to work in browser, I could maybe switch to this 'correct' one and have it work with QT.

What's funny is that iirc this same button mapping worked on IDA, which also uses QT. I don't have IDA on this mac though so I cannot check right now.

**Comment by psifertex** [comment]
I think the main problem is there's no "official" back/forward hotkey on OS X. So while Safari has a keystroke (which is what you've used above and incidentally I map on my mouse as well), mice with extended buttons don't actually issue those on OS X without tweaking.

**Comment by Grazfather** [comment]
So does it not work for you on OSX IDA? Could the command [/] be added to the keyboard event handler?

And then for curiosity's sake: Is there a keyboard mapping for it? I tried backspace/ctrl-enter (ida style) and -/+ (olly style) and neither work.

**Comment by psifertex** [comment]
So the workaround is to just add a hotkey navigation for `⌘-[` and `⌘-]` (or `^-[` and `^-]` on other platforms. Fixed in dev, and we're about to push to master soon.

**Comment by Grazfather** [comment]
Kick ass. Crushing through these. Appreciated!
