### ISSUE TITLE
Symbols and data variables for import functions overwritten by PDB parser with lower quality symbols/data vars

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#4051]
[kernel32-64.dll_.zip](https://github.com/Vector35/view-pe/files/10856827/kernel32-64.dll_.zip)

For the attached file, we can see the IAT table is not correctly processed, that the import symbols are not defined:

![Screenshot 2023-03-01 at 11 24 15 AM](https://user-images.githubusercontent.com/94503187/222037133-988a2e1e-839f-46e3-8ffa-43cd49300b58.png)

For comparison, a typical x64 file looks like this:

![Screenshot 2023-03-01 at 11 24 55 AM](https://user-images.githubusercontent.com/94503187/222037209-b4738895-bbec-403d-a7cb-9699561262a2.png)

**Comment by xusheng6** [comment]
This is also caused by the downloading a PDB. If I disable the PDB, then everything works fine.

**Comment by xusheng6** [comment]
Related to https://github.com/Vector35/binaryninja-api/issues/4050

**Comment by xusheng6** [comment]
The problem is that the PDB parser overwrites the import function symbols and the data var with information from the PDB (as illustrated in the first screenshot), but the info from PDB is having a lower quality than we already have (in the second screenshot).

**Comment by CouleeApps** [comment]
This has since been resolved (as of 3.4.4163), although note that type libraries for those functions still do not exist.

<img width="1081" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/711973/74a88920-54bb-4197-94b6-510b396a5436">
