### ISSUE TITLE
Crash on `Display As` changes inside plugin view

### ISSUE THREAD

**Issue by w1282** [Vector35/binaryninja-api#4055]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4101-dev, 5aa15539
- OS: windows
- OS Version: 10
- CPU Architecture: x86_64

**Bug Description:**
Attempting to `Display As > Anything` from within the bnil-graph plugin `Instruction Graph` view causes the application to crash.

**Steps To Reproduce:**
1. Install the `bnil-plugin`
2. Trigger the `Plugins > BNIL > Instruction Graph` view on something
3. Right click a constant and `Display As > Pointer` or something and observe the crash

**Expected Behavior:**
Either the value is altered to display appropriately, or the option to `Display As` is never presented in the context menu

**Comment by fuzyll** [comment]
I've tried to repro this and I...can't?

Just to be clear, you're using [this plugin](https://github.com/withzombies/bnil-graph), right?

These are the only options I see with that installed from the plugin manager on 3.4.4101-dev:

<img width="660" alt="image" src="https://user-images.githubusercontent.com/607452/222242161-b7df166c-75ef-46fc-8773-3c628070148c.png">

I've tried right-clicking a _lot_ of stuff, too. Am I doing something wrong?

**Comment by w1282** [comment]
![image](https://user-images.githubusercontent.com/24464219/222243149-5a4d112c-5638-4e83-9e8e-9db7c96bb7c2.png)

Interesting. Yes, that is the same plugin, but this is what I see.

**Comment by psifertex** [comment]
How are you installing the plugin? Via the plugin manager? Cloning directly into your plugin folder? If using the plugin manager, what version does it show?

**Comment by w1282** [comment]
> How are you installing the plugin?
Via plugin manager

> What version does it show?
1.3.0, Last Updated: 2021-06-07

> What type of file?
Raw firmware image
Also replicates under x86_64 ELF

**Comment by fuzyll** [comment]
Tried on Windows 11 with a PE file and still no dice.

![image](https://user-images.githubusercontent.com/607452/222322903-3cea7e74-4a25-413a-a204-1aa2b4e1f806.png)

I'll try some other binaries a bit later and see if I can repro.

**Comment by w1282** [comment]
https://binaryninja.slack.com/archives/C0CV88A83/p1677715869954879

^^ Reference to slack conversation where Jordan was able to reproduce

**Comment by xusheng6** [comment]
We fixed the issue by disabling `Display as` in the BNIL view. The display as would not function properly in views other than linear view or graph view anyways. After the fix, the `Display As` menu should only show up in the following two cases:

1. there is a valid function
2. a data variable is selected in the linear view

**Comment by fuzyll** [comment]
Fixed in 3.4.4105-dev
