### ISSUE TITLE
Install Python plugin dependencies on MacOS using bundled Python

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#4060]
We don't currently ship a python binary on macos as last time we attempted to we got some weird issues with signing. We need to spend the time to track these down.

The problem with not shipping the python binary is that it prevents us from being able to install plugin requirements via pip with default configuration.

**Comment by kristopax** [comment]
The ultimate issue here is that we are unable to install Python plugin package dependencies on MacOS using the bundled Python. The solution to this issue should enable that.

**Comment by kristopax** [comment]
During testing, the prior solution for this issue fails to handle the case when installing packages that employ setuptools/setup.py scripts.  A new solution needs to include the python executable as part of the bundled python on MacOS.

**Comment by kristopax** [comment]
This issue is linked to PR #4122, which has been merged and closed.  Therefore, this issue can be closed.
