### ISSUE TITLE
Change log is a bit harder to read after the new tab page cleanup

### ISSUE THREAD

**Issue by alexrp** [Vector35/binaryninja-api#4067]
Fairly minor gripe here, but the recent cleanup of the new tab page has (to my eyes at least) made it a bit harder to scan through the change log.

I think some extra spacing (or something) here would help:

![image](https://user-images.githubusercontent.com/44076/222803992-49ccbcb8-b22b-4df7-b3fd-1ce667fb70ff.png)

(Alternatively, it would probably be less of an issue if the version headers had a font color that contrasts more with the commit message color?)

(cc @fuzyll?)

**Comment by fuzyll** [comment]
There actually _was_ supposed to be a larger space there. But, that was the one part I couldn’t test before landing it on dev and I forgot to go check. I’ll take care of it on Monday, thanks for the issue!

**Comment by CouleeApps** [comment]
Added the <hr>s back (only the ones between the versions) in 3.4.4108-dev.
