### ISSUE TITLE
FR: Ability to extend from CoreArchitecture (for Python api)

### ISSUE THREAD

**Issue by WZ-Tong** [Vector35/binaryninja-api#4068]
**What is the feature you'd like to have?**
Extending from CoreArchitecture to build a new Architecture

**Is your feature request related to a problem?**
For some confused virtual machine protect, it converts code into "VM code" to execute. After figuring out it's mapping relation, it 's easy to use custom architecture support in binary ninja to build a function. But it's fussy to build a fresh new platform including Flags, register size, etc.
If it can be extended from CoreArchitecture and I'll have just to implement/override a few functions to build my own architecture.

**Are any alternative solutions acceptable?**
Maybe provide a template of major architectures, or maybe users already have related method, give some link in "CoreArchitecture" api page:
```python
>>> type(Architecture['aarch64'])
<class 'binaryninja.architecture.CoreArchitecture'>
```

**Comment by psifertex** [comment]
Good news, this is already possible. They're called architecture hooks: 

https://github.com/Vector35/binaryninja-api/blob/dev/python/examples/arch_hook.py

**Comment by WZ-Tong** [comment]
Maybe it's not the stuff with hooks.

Image there is a virtual machine protect re-interpret hex `000080d2` into `ret` instruction, while keeping other instructions same.

If I use hooks, this will cause other `mov x0,0` instructions in my bndb turned into `ret`

Currently my own solution is to build a fresh new `Arch['MyArm64']`, it's function is almost like a real aarch64, but will treat `000080d2` into `ret`. But in order to do this small change, I'll completely re-write an arch.

But if I can extend from `aarch64`, I'll just have to extend it, changing its name, overwrite function like `get_instruction_low_level_il`, `get_instruction_text` and easily solve this.

If I can do it with hook (such as adding a parameter called "hook in a copied/isolated arch"), it will work fine. Or if this will take a lot of effect because of the lift flow etc., it's OK to ignore my request since this usage happens seldomly. But this will be the unique advantage that binja have.

**Comment by psifertex** [comment]
The hook is exactly what you asked for. Your modification can change the lifting of a single instruction and pass the rest of the changes to the main architecture. How is what you're asking for different?

**Comment by psifertex** [comment]
Is the issue you want to only change _some_ instances of `mov x0, 0`? Whether you reimplement the entire architecture or have a hook you'd have the same problem, that's totally unrelated and probably requires a different solution.

**Comment by WZ-Tong** [comment]
> Is the issue you want to only change _some_ instances of `mov x0, 0`? Whether you reimplement the entire architecture or have a hook you'd have the same problem, that's totally unrelated and probably requires a different solution.

Right! Just change it in specific function, while keeping all others stays the same.

**Comment by psifertex** [comment]
But how do you know which function to apply it to? You have to have some analysis to even identify that is the right function in the first place. Architectures that do lifting happen too early in the process and have no state. 

The better fix is probably a workflow which can rewrite analysis later and is also already possible as well. See the example workflow in the API (note that workflows are really only doable in C++ because python has  performance limitations).

**Comment by WZ-Tong** [comment]
How to find mapping and start point is what reverse players need to do though, but it's my problem to make this complex.

Just get rid of the usage, based on these features:

1. I can 'load' (not really, but act like) multiple architectures at the same time by creating functions with other architectures
2. I want to convert some byte into a function with my architecture, while keeps others stay unchanged
3. My architecture has just a few changes to the default architecture

I will meet 2 problems:

1. If I use architecture hook, other normal functions will also behaves like my architecture
2. If I completely write all my architecture, I have to deal with other assemblies

My desired solution is the ability to extend from the default architecture like
```python
class MyArch(CoreArchitecture.AARM64)
    some override
```

rather than
```python
class MyArch(Architecture)
    full implements
```
