### ISSUE TITLE
Components view should keep current selection after sort/filter

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#4071]
If you filter and select a given filtered item then clear the filter the view should scroll to my selected item.
Similarly if I have a selected item and I sort it should select scroll to that selected item.

**Comment by cxnder** [comment]
Resolved in builds >= 3.4.4149

We will now conditionally autoscroll to the selected item:

When symbols are added: If the item was visible before they were added
When sorting/filtering changes: Always
When navigating (i.e. hitting Enter): Always
When you hit the up/down arrows to move selection: Always
