### ISSUE TITLE
Structure member cross references can become stale 

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#4080]
**Bug Description:**
Structure member cross references are not cleared by undoing the creation of a structure.

https://user-images.githubusercontent.com/10556585/223724605-26796d7f-4095-486a-af6f-bfd73cc1ae8a.mov

**Comment by xusheng6** [comment]
This issue can be triggered in a simpler way: just undefine the function that has the xref to the type field, and observe (in the type view or using Python) the type field xref still exists.
