### ISSUE TITLE
Don't lose focus when renaming parameter /variable /function etc.

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4081]
Binary Ninja Version: 3.4.4090-dev
Platform: Windows 11 Version 22H2

Looks like BN loses focus after renaming of parameter /variable /function. It should focus on the thing that we renaming after rename operation. It does not do so when changing type.

**Comment by plafosse** [comment]
Yes its annoying and its a really old bug marking as duplicate of  #1086
