### ISSUE TITLE
Truncate Folder Name In Children can extend the length of the name and cut off more of the symbol name than previously

### ISSUE THREAD

**Issue by ccarpenter04** [Vector35/binaryninja-api#4086]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4123

**Bug Description:**
In regards to the "eastl" library (EA:STL), the truncate folder name in children option in the new symbol view will result in it being "truncated" to "eas..." which is both an extra character in length and rendered more widely (assuming a monospaced font or a font with similar widths for most characters). This results in less of the actual function name (symbol name) being shown since it's wider, resulting in an additional character being cutoff in the end.

I would expect that the truncated naming would have less characters than the full name of the symbol.

**Screenshots:**
<img width="437" alt="image" src="https://user-images.githubusercontent.com/2475433/223791511-4855fc47-2f92-4e6a-9af0-e3ee3ea0f7fa.png">

**Comment by cxnder** [comment]
This should be resolved in dev **builds >= 3.4.4161**

It now uses a smaller ellipsis, and won't truncate names <= 3 characters
