### ISSUE TITLE
Using "Copy Name" on the new symbol view while "Show Mangled Names" is enabled results in the demangled name being copied

### ISSUE THREAD

**Issue by ccarpenter04** [Vector35/binaryninja-api#4087]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4123
- 
**Bug Description:**
In the new symbol view, if "Show Mangled Names" is selected and you right click a mangled name in the symbol view and right-click -> "Copy Name" it will copy the demangled name to your clipboard instead of the mangled name.

Since Show Mangled Names was selected (and mangled names were displayed in the view) I expected the copy name function to copy the mangled name instead of the demangled name.

**Comment by cxnder** [comment]
Resolved in dev builds >= 3.4.4161
