### ISSUE TITLE
A way for seeing entry points

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4088]
Currently I need to go to triage view in order to see exported functions -requires a lot of click- moreover that list does not have the entrypoint function. I really find `CTRL+E` feature of IDA very useful. Is it possible to consider implement something like that in BN?

**Comment by psifertex** [comment]
Not sure what we'll decide long-term, but you've got a few work-arounds I wanted to document:

https://gist.github.com/psifertex/6fbc7532f536775194edd26290892ef7#file-show_exports-py

Also, aside from #4089 (IE, using the old symbols view) you can use the "show only exports" action, or change the display settings to just see exports in the symbol list:

![Screenshot 2023-03-09 at 10 18 11 AM](https://user-images.githubusercontent.com/140215/224069142-af1da292-0720-4664-9ed5-d2a2ea8985fa.png)

**Comment by fuzyll** [comment]
Would #1700 solve this for you? If so, I'm going to close this as a duplicate and track having imports/exports in sidebar widgets there (or change Symbols view in a way that makes the option to show only exports within it more discoverable/easier to toggle).

**Comment by op2786** [comment]
I think it might solve it. Let's close this and wait for #1700 and see if it's work.

**Comment by CX330Blake** [comment]
I thinks it's solved now (5.3.8857-dev). I found that the entry functions will shown in Triage view, so that entry points like TLS callback can be easily found.

**Comment by psifertex** [comment]
Thanks for catching and closing. Yeah, Xusheng added support in https://github.com/Vector35/binaryninja-api/commit/845c1e5435fd49cf220e6df28934402904c121c0
