### ISSUE TITLE
"show only exports" is broken in new components view

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#4089]
Haven't looked at the root cause yet, but using the "show only exports" action with the components view results in an empty list. It looks like it changes the settings appropriately in terms of "show exported data vars" and "show exported functions" but nothing shows up. 

Using old symbols and a windows dll after that action:
![Screenshot 2023-03-09 at 10 18 11 AM](https://user-images.githubusercontent.com/140215/224069142-af1da292-0720-4664-9ed5-d2a2ea8985fa.png)

Using components/new symbols view:
![Screenshot 2023-03-09 at 10 18 54 AM](https://user-images.githubusercontent.com/140215/224069343-39990e40-6ca1-461d-baab-291897712244.png)

**Comment by cxnder** [comment]
Resolved in builds >= 3.4.4149
