### ISSUE TITLE
Pointers not being created from relocations, redux

### ISSUE THREAD

**Issue by comex** [Vector35/binaryninja-api#4098]
This is a followup to #3371, which I'm now finally getting around to responding to after several months.  I don't see a button to reopen it so I'm filing a new issue - this time with reproduction instructions :)

**Version and Platform (required):**
- Binary Ninja Version: 3.4.4137-dev (ebbd47c5)
- OS: macOS
- OS Version: 13.1 (22C65)
- CPU Architecture: M1

**Bug Description:**
When loading ELF files that were produced by [`nx2elf`](https://github.com/shuffle2/nx2elf), Binary Ninja does not create pointers corresponding to the relocations.

~`nx2elf` is an obscure tool so there may be something wrong with the ELF files.~  However, Binary Ninja does know about the relocations, as demonstrated using `bv.relocation_ranges_at`.

Update: `nx2elf` is probably a red herring, since the same thing happens with the the original ELF produced by GNU ld.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Load [this ELF file](https://github.com/Vector35/binaryninja-api/files/10949186/x.elf.zip) with default settings.  (Update: Or [this ELF file](https://github.com/Vector35/binaryninja-api/files/10949214/orig.elf.zip) which is the original, but I'm more interested in things working for the previous ELF, since it's more representative of my real use case.)
2. Go to e.g. 0x3c100, and note that there are lots of pointers that are not marked as such (see screenshot).
3. Set the cursor to any of those pointers, run `bv.relocation_ranges_at(here) == [(here, here + 8)]`, and note that it returns True.
4. The existence of relocations can be verified using readelf: `aarch64-none-elf-readelf -Dr x.elf`

**Expected Behavior:**
The pointers should be printed with the correct size, show up in xrefs, etc.

**Screenshots:**
<img width="992" alt="image" src="https://user-images.githubusercontent.com/47517/224505970-4fc2392a-d706-4f24-8c55-77505150b628.png">

**Comment by plafosse** [comment]
Ok this info helps a ton. So looking into this a bit this is a `R_AARCH64_RELATIVE` 

We don't define a pointer there because the architecture defines it as `pcRelative`: https://github.com/Vector35/arch-arm64/blob/master/arch_arm64.cpp#L3205

Our check on if we should make a pointer there or not is this:
```(view->IsOffsetCodeSemantics(address) || info.`pcRelative` || (info.size != reloc->GetArchitecture()->GetAddressSize()))```

I need to look into this a bit more to understand what needs to change. The other thing we should be able to do is make an integer DataVariable there if it is `pcRelative`

**Comment by comex** [comment]
I see.  I believe `R_AARCH64_RELATIVE` has the same semantics as `R_X86_64_RELATIVE` or `R_386_RELATIVE`, which, [in `arch-x86`](https://github.com/Vector35/arch-x86/blob/e0585ca54d72908d4da09c8ad41831aafd86b2b0/arch_x86.cpp#L4059), is assigned `pcRelative = false` but `baseRelative = true`.

To quote 'ELF for ARM64.pdf':
> R_AARCH64_RELATIVE represents a relative adjustment to the place based on the load address of the object relative to its original link address. All symbols defined in the same segment will have the same relative adjustment. [..] This relocation represents an optimization; it can be used to replace R_AARCH64_GLOB_DAT when the symbol resolves to the current dynamic shared object.

**Comment by plafosse** [comment]
Ok I pushed a fix to the arm64 repo that makes that change and it seems to now produce all those DataVariables.

I noticed though there is this weird .plt section 
![image](https://user-images.githubusercontent.com/10556585/224510261-6003780d-6914-460a-8aa6-9e7d404027fb.png)

which running `readelf -t` you can see

```
readelf: Warning: Size of section 10 is larger than the entire file!
  [10] .plt
       PROGBITS         00000000640cc8f6  0000000000000000  0
       0000000038043e29 0000000000000010  0                 16
       [0000000000000006]: ALLOC, EXEC
```

Any idea what is up with that? Did you modify the binary somehow?

**Comment by comex** [comment]
Yeah, probably nx2elf's fault.  Thanks for the fix!

**Comment by psifertex** [comment]
Note that I don't believe this has landed on dev yet so I'm going to reopen this for now so we can track it and we'll close when the updated arm architecture is on dev with the build number that resolves it. 

Folks are welcome to build the arch module themselves beforehand to test if they want but I wouldn't consider it closed until it's available in a release even if dev.

**Comment by plafosse** [comment]
Oh additionally in that commit I also put in a fix for the strange section. We now exclude sections which are outside the bounds of the BinaryView
