### ISSUE TITLE
Text-based/Disassembly search

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#41]
Need search / replace for both hex and disassembly (replace for disassembly requires #27)

**Comment by artemdinaburg** [comment]
The strings window also desperately needs a search option.

**Comment by D0ntPanic** [comment]
Search is implemented, but replace is not.  Also, implement text searching in linear view.

**Comment by plafosse** [comment]
Making this ticket specifically targeting finding of text in the current BinaryVIew

**Comment by plafosse** [comment]
Added in 1.1.1422
