### ISSUE TITLE
Support `readline` hotkeys in Python interpreter

### ISSUE THREAD

**Issue by Grazfather** [Vector35/binaryninja-api#410]
Ctrl-p and Ctrl-n for previous and next commands in the history should be supported instead of requiring the user use the arrow keys

Ctrl-u to delete line left, Ctrl-w to delete word left, etc

Ctrl a, e, and h, seem to work on OSX.

**Comment by psifertex** [comment]
The existing keys work as QT provides them for free in the input box. Command-history searching is a nice feature we would like to implement eventually.

**Comment by negasora** [comment]
Command history searching was added in 2.1.2351-dev
