### ISSUE TITLE
Dev build fails parsing imports

### ISSUE THREAD

**Issue by Kharos102** [Vector35/binaryninja-api#4101]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4144-dev, d9984bce
- OS: windows
- OS Version: 11
- CPU Architecture: x86_64

**Bug Description:**

Imports aren't parsed for x64 PE32+ files on HLIL view, tested by loading kernelbase.dll from system32

**Steps To Reproduce:**
Open the target and look at triage 

**Expected Behavior:**
HLIL view should show the imported function call

**Screenshots:**
![missing_import](https://user-images.githubusercontent.com/16039802/224933295-540f70bc-2682-4f0d-8a5a-d1688a5dd551.png)
![missing_import2](https://user-images.githubusercontent.com/16039802/224933308-06d436b6-27c7-4a5d-96cc-800a2acb6569.png)

**Additional Information:**
Doesn't occur on release branch

**Comment by CouleeApps** [comment]
This will be fixed as of 3.4.4161-dev. Now, symbols from the pdb parser come with type confidences and will not clobber the already applied import types with higher confidence.
