### ISSUE TITLE
Bad arm elf disassemble from unaligned addresses

### ISSUE THREAD

**Issue by sdlf** [Vector35/binaryninja-api#411]
My arm/thumb elf file has a symbol, JNI_OnLoad, that disassemble wrong in BN (while objdump and others gets i right). I assume BN is confused about the alignment.

readelf:
...
     8: 00000000     0 FUNC    GLOBAL DEFAULT  UND lrand48
     9: 00001611    96 FUNC    GLOBAL DEFAULT    7 JNI_OnLoad
    10: 00000000     0 FUNC    GLOBAL DEFAULT  UND memcpy
...

objdump:
00001610 <JNI_OnLoad>:
    1610:       b510            push    {r4, lr}
    1612:       4c13            ldr     r4, [pc, #76]   ; (1660 <JNI_OnLoad+0x50>)
    1614:       6803            ldr     r3, [r0, #0]
    1616:       b0a2            sub     sp, #136        ; 0x88

r2:
(fcn) sym.JNI_OnLoad 80
 DATA XREF from 0x000037d6 (unk)
0x00001610      push {r4, lr}
0x00001612      ldr r4, [pc, 0x4c]                         ; [0x1660:4]=0x5a6c
0x00001614      ldr r3, [r0]

BN get this wrong and thinks the function actually begins at 1611:

JNI_OnLoad:
00001611  b5134c03   movteq  r1, #0xc3b5
00001615  68a2b07c   ldcvc   p2, c10, [r0],  #0x1a0
00001619  44211c14   ldrne   r2, [r12],  #-0x144
0000161d  319b6910   rsbne   r9, r9, r1, lsr r11
00001621  4a984700   subeq   r9, r7, r10, asr  #0x10
00001625  2817d10f   svceq   #0xd11728

**Comment by sdlf** [comment]
or maybe it just does not detect thumb properly

**Comment by plafosse** [comment]
We do not currently support Thumb, this will be fixed when thumb is added.

**Comment by sdlf** [comment]
is that on the current todo list or more of a future thing? working with arm binaries without thumb support is, hmm, rather limited.
