### ISSUE TITLE
Show folders first option in components

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4123]
I believe that having an option for showing folders first would be useful in components especially when sorting items.

**Comment by cxnder** [comment]
It *should* already be doing this, as there's not really a logical way to sort them otherwise. Are you requesting an option to disable this behavior, or have you found a case where they aren't properly sorted first?

**Comment by op2786** [comment]
As you can see in the GIF, when I sort name column, folders get lost in the list. I want to be able to show them first even if I do sort alphabetically.

![Recording 2023-03-22 at 08 11 44](https://user-images.githubusercontent.com/109607896/226828064-693f1b0d-d031-4faf-9bad-9dd77c8181f2.gif)

**Comment by cxnder** [comment]
So sorting folders first is the intended behavior, and this should be resolved now as of dev **builds >= 3.4.4167**
