### ISSUE TITLE
Overly aggressive code elimination removes condition

### ISSUE THREAD

**Issue by ZetaTwo** [Vector35/binaryninja-api#4128]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4161-dev (307b0cbe)
- OS: Ubuntu Linux
- OS Version: 22.04
- CPU Architecture: x64

**Bug Description:**

Consider the four screenshots below from the same binary. The disassembly and LLIL is correct with six separate conditions on the argument (arg1 == "ABC123") but the MLIL, and therefore the HLIL only contain five conditions (arg1 == "ABC12").

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Have function with the disassembly shown in the first screenshot
2. View the HLIL

**Expected Behavior:**
I expect all six conditions to appear in the HLIL

**Screenshots:**

Correct disassembly:
![image](https://user-images.githubusercontent.com/870392/226750127-3f0ca287-d37f-4d7d-a8b6-fb217bb862e8.png)

Correct LLIL:
![image](https://user-images.githubusercontent.com/870392/226750188-436ead1e-5193-4b5d-9c64-25e38006fd45.png)

Incorrect MLIL:
![image](https://user-images.githubusercontent.com/870392/226750279-203ce1fd-e545-4d1e-acef-4028327ca7ca.png)

Incorrect HLIL:
![image](https://user-images.githubusercontent.com/870392/226750410-cab4ae8f-7c4c-42fd-aac9-f743c9b140f8.png)

**Additional Information**
The binary is attached: [binja-bug-dce.zip](https://github.com/Vector35/binaryninja-api/files/11034131/binja-bug-dce.zip)

**Comment by plafosse** [comment]
Looks like this issues is fixed in latest dev 
![image](https://user-images.githubusercontent.com/10556585/236919528-287e2cbc-a7b3-4c91-a5f6-5081d3ae8dfe.png)
