### ISSUE TITLE
Can not see created folder if it's created when filtering in components

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4133]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4151-dev 
- OS: Windows 11, x64

**Bug Description:**
I would like to be able to see created folder even if I do it when filtering. I guess it is because filter list does not updated after creating a folder. Because when I type one more letter it shows it. But it should do it without any interaction.

**Screenshots:**
![Recording 2023-03-22 at 12 33 47](https://user-images.githubusercontent.com/109607896/226892657-0df46e3e-b1a8-45ed-88b9-36f5d445ae5d.gif)

**Comment by cxnder** [comment]
Thank you so much for these bug reports (and the attached gifs!), they are incredibly helpful! This should be resolved as of **builds >= 3.4.4167**
