### ISSUE TITLE
Select strings without double quotes

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4134]
It is incredibly useful to use some function parameters as function names, especially for logging and GetProcAddress like functions. Currently BN selects strings with double quotes which makes it harder to copy function names from those kind of functions and use them as variable name. I need to do click & drag on the string in order to get rid of double quotes or I need to manually delete them. Which is very time consuming.

![Recording 2023-03-22 at 13 07 10](https://user-images.githubusercontent.com/109607896/226900411-63903e51-1822-41db-9dce-5da7787ac310.gif)

**Comment by plafosse** [comment]
Fixed in 3.5.4347
