### ISSUE TITLE
BN should be case sensitive when changing function prototypes

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4138]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4164-dev Personal, 93fb7583
- OS: Windows 11, x64

**Bug Description:**
In the GIF below, I wanted to overwrite return value of a function with `bool` (1 byte) which was `BOOL` (4 byte) before. But as you can see in the GIF, it thinks that this prototype is same as before and used old one instead. I think that this is because BN handles function prototypes case insensetive because it reproduces this for parameter names in function prototypes. You need to do this by pressing `Y` on function name in order to reproduce.

**Screenshots:**
![Recording 2023-03-23 at 09 28 24](https://user-images.githubusercontent.com/109607896/227146144-7a3c54c6-8389-495b-99bd-7b6bf29855d8.gif)

**Comment by jonpalmisc** [comment]
If you look closely, the combo box text is actually being changed back to the type string with all-caps "BOOL" before the accept button is pressed. This looks like a UI bug, not a core bug.

**Comment by alexrp** [comment]
This also happens for me just when pressing Y on the return type sometimes.

Can work around it by using backticks around `BOOL`.

**Comment by plafosse** [comment]
Fixed in 4.2.6384
