### ISSUE TITLE
Support for various windows interfaces in type libraries

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4139]
I was reversing a binary that uses `CoCreateInstance` and get `IWbemServices` interface. and looks like BN currently does not support that interfaces in type libraries. I also remember a binary that uses dbgeng backend which uses interfaces like `IDebugDataSpaces4`, `IDebugControl4` etc. which also lacks support in BN at the moment. I know I can create structures for them by myself but it is very time consuming therefore should be supported by default.

**Comment by op2786** [comment]
By the way, I was NOT be able to import those with import header file. VFT of these interfaces is all empty.

**Comment by plafosse** [comment]
This should be fixed in 3.6.4794
