### ISSUE TITLE
Option for saving database with extra privacy cleanup

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4141]
As far as I can understand BNDB's have some fields that can pose threat to ones privacy. For example I can see that the binary path is in it which have username and full path of binary, a very informative things. Also I guess there is username and email fields in snapshots which could also important in regards of privacy.

Can we please have an option in "Save Database With Options" dialog that anonymizes these kind of informations?

**Comment by psifertex** [comment]
We've come up with the following that we could consider in the future. I'm closing this and implementing just the original filename for now, but documenting the others just for awareness. The others are more nuanced and more likely to break intended functionality so would probably require something more powerful like a database explorer to selectively control what is/isn't saved (already possible through the API of course, just not in the UI):

- [x] Full File Path -- this is the one I'm closing for this issue with the new "Purge original path" option in the "save analysis database with options" UI. There's also a new `analysis.database.purgeOriginalFilenamePath` setting that can be enabled to always strip file paths
- [ ] Settings -- technically settings that are scoped to a view could contain information such as a local PDB server path, but that isn't the default and most folks aren't even aware of how to make such settings changes.
- [ ] [session_data](https://api.binary.ninja/binaryninja.binaryview-module.html#binaryninja.binaryview.BinaryView.session_data)
- [ ] [metadata](https://api.binary.ninja/binaryninja.binaryview-module.html#binaryninja.binaryview.BinaryView.store_metadata)

New setting ands ave option added in builds >= 4221.
