### ISSUE TITLE
More ergonomic way of retrieving an IL string operand

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#4144]
**What is the feature you'd like to have?**
I'd like to have an ergonomic API for retrieving the string referenced by the operand of an IL operation. This _may_ be as easy as just fixing the output of `str()` on an operand, but I'm not entirely sure as I'm not familiar with the implementation of these APIs.

**Is your feature request related to a problem?**
Given line 13 in MLIL in this screenshot:

<img width="1193" alt="image" src="https://user-images.githubusercontent.com/607452/227416807-c4ed1f48-05c4-4f40-a87f-05bd12e0f4ae.png">

...I want to get the string `'MS Word document scan in progress...\n'` out. The _only_ ways that I have been successful have been by doing:

```
bv.get_ascii_string_at(current_il_instruction.params[1].value.value).value
# or
bv.get_ascii_string_at(current_mlil[13].params[1].value.value).value
```
...with it selected (so that `current_il_instruction` refers to that one). If there's a better way right now, please feel free to close a pointer to the right API. But, other possible solutions I came up with like this one:

```
current_il_instruction.operands[2][1].__str__()
```

...don't actually get me the full string. They're truncated and return `'"MS Word document scan in progres…"'` instead.

**Are any alternative solutions acceptable?**
As mentioned above, if `str()` just worked on the operand, I think that would be fine? Otherwise, modifying `get_string_at()` and friends to be able to unpack the value I want would be my suggestion.

I would also accept just having explicit documentation on this as a way to close the issue. I feel like it's a common enough operation that we should at least try to make it more discoverable.

**Additional Information:**
This came up while trying to help another user with this problem tonight. Their issue was different and involved something that had been outlined, but the solution was similar.

**Comment by plafosse** [comment]
Seems like something to the effect of `instr.get_strings_referenced_by_instruction()` would be a nice convenience API.
