### ISSUE TITLE
Binary Ninja python is broken

### ISSUE THREAD

**Issue by ElvisBlue** [Vector35/binaryninja-api#4149]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4170-dev
- OS: Windows 10
- OS Version: 22H2
- CPU Architecture: x64

**Bug Description:**
All python features are broken. Look like binary ninja can't find python library.

**Steps To Reproduce:**
Go to update channel and update to binary ninja 3.4.4170-dev version

**Expected Behavior:**
Every feature related to python should work normally.

**Screenshots:**
![image](https://user-images.githubusercontent.com/32590178/227751319-98fea821-69f9-4a58-ac15-57c317833270.png)

**Additional Information:**
When I roll back to version 3.4.4167-dev everything work just fine

**Comment by negasora** [comment]
Do you have a python interpreter specified in settings?

**Comment by ElvisBlue** [comment]
I have python 3.8 installed by default (both x86 and x64). But version 3.4.4167-dev work fine with python 3.10 shipped with it so I think it could be new binary ninja dev load default python version on my computer instead of load python version shipped with it.

**Comment by psifertex** [comment]
We did some switching around shipping a 3.11 briefly on dev before downgrading it back to 3.10 due to some incompatibility and for some reason this is causing some folks to have to manually re-set their interpreter setting. Not sure why that's being caused but if you manually set it correctly either to blank so that it uses the built in interpreter or to your system python that should fix it?

**Comment by ElvisBlue** [comment]
I didn't know that I can set python interpreter with binary ninja. After set it manually to built in python interpreter it works just fine. Thank @psifertex

**Comment by psifertex** [comment]
You're welcome! We are still trying to figure out what causes this issue in the first place as you shouldn't _have_ to manually change that setting but at least the upside is you learned about this feature!

**Comment by kristopax** [comment]
This issue is fixed in 3.4.4173-dev.  Please update your BN to this version. You should be able to clear the python interpreter setting to the default (which uses the bundled Python version), restart BN, and carry on.

Thank you for reporting this issue.

**Comment by ElvisBlue** [comment]
Thank a lot @kristopax. Today I update my binary ninja to last dev version. Everything works fine.
