### ISSUE TITLE
arch-armv7 test.py mismatch for `bfi r0, r1, #2, #3` lifting

### ISSUE THREAD

**Issue by mblsha** [Vector35/binaryninja-api#4150]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4170-dev Personal (7b9a14df)
- OS: macOS
- OS Version: macOS Version 13.2.1 (Build 22D68)
- CPU Architecture: M1

**Bug Description:**
Please provide a clear and concise description of what happened.

**Steps To Reproduce:**
1. Run test.py for cases that check `bfi r0, r1, #2, #3` lifting, there's one for arm and another one for thumb2
2. expected (left) will mismatch actual (right), see screenshot

**Expected Behavior:**
Not sure whether it's tests that need to be updated or the lifter.

**Screenshots:**
<img width="556" alt="Screenshot 2023-03-26 at 13 55 17" src="https://user-images.githubusercontent.com/4909/227752691-b7078d19-f158-4561-b735-8a123c741c69.png">

**Additional Information:**
This PR seems to have changed the discrepancy:
https://github.com/Vector35/arch-armv7/commit/5bdcbef38b8da2f3b13f4ae80d2c5fd412aa53be

**Comment by lwerdna** [comment]
The expected/left side is wrong: it extracts source bits b2, b3, b4 by and-ing with 28.

The docs say the source bits are always from the little end, but the destination bits are specified by the `<lsbit>` field in the instruciton:

```
if ConditionPassed() then
    EncodingSpecificOperations();
    if msbit >= lsbit then
        R[d]<msbit:lsbit> = R[n]<(msbit-lsbit):0>;
        // Other bits of R[d] are unchanged
    else
        UNPREDICTABLE;
```

So getting the source bits like the actual/right side does it (and-ing with 7) is correct.

Fix is [here](https://github.com/Vector35/arch-armv7/commit/831af7681fc3e5b9315b2d55cf70ae9154a9ee41). Thank you for spotting this 👍
