### ISSUE TITLE
Recognize libc constructor and destructor arrays

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4153]
Today I encountered an example binary that uses constructor function for some black magic. When I found that constructor function, I noticed there there is no reference to it. I digged into it a bit and looks like it's because BN does not recognized constructor and destructor arrays.

As known `__libc_start_main` is responsible for initializing and calling programmer written main function which have a prototype like this:

```c
int __libc_start_main(int *(main) (int, char * *, char * *),
					  int argc,
					  char * * ubp_av,
					  void (*init) (void),
					  void (*fini) (void),
					  void (*rtld_fini) (void),
					  void (* stack_end));
```

`init` and `finit` are functions that responsible for calling constructors and destructors. This is what I saw when I look at `init` function and `.init_array`, `.finit_array` sections.

`init` function:
```c
void init()

0805633c  _init()
08056350  int32_t edi_1 = 0
08056373  do {
08056364    (*((edi_1 << 2) + 0x81a4efc))(arg_4, arg_8, arg_c)
0805636b    edi_1 = edi_1 + 1
0805636b  } while (edi_1 != 2)
```

Sections:
![Screenshot 2023-03-27 101702](https://user-images.githubusercontent.com/109607896/227882513-42c62b17-81c3-42e3-bcd6-7da8bba807c0.png)

#257 should have fixed this, but looks like it did not.

Interestingly, even if I defined functions in `.init_array` like below, it does not shows reference for `secret_init`.

```
.init_array section started  {0x81a4efc-0x81a4f04}
081a4efc  int32_t data_81a4efc = frame_dummy
081a4f00  int32_t data_81a4f00 = secret_init
```

Binary:
[break.zip](https://github.com/Vector35/binaryninja-api/files/11076472/break.zip)

**Comment by plafosse** [comment]
This will be fixed in 3.4.4192
