### ISSUE TITLE
LogListener class is missing from the Python API

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#4156]

**Comment by CouleeApps** [comment]
Implemented on a branch here: https://github.com/Vector35/binaryninja-api/tree/test_py_loglistener

Also a corresponding branch on the core repo addressing performance concerns

**Comment by plafosse** [comment]
This is a somewhat intentional omission due to the performance concerns of calling into python and having to take the GIL in the middle of analysis. @CouleeApps 's change does address the major concern  though and would probably be fine to integrate his code.

**Comment by xusheng6** [comment]
Related to https://github.com/mandiant/capa/issues/1413

**Comment by xusheng6** [comment]
I am not rushing to merge this since the capa issue can be mitigated using existing log infra: https://github.com/mandiant/capa/issues/1413#issuecomment-1507854165

**Comment by xusheng6** [comment]
Duplicate of https://github.com/Vector35/binaryninja-api/issues/2236
