### ISSUE TITLE
Renaming enumeration member does not reflected on the decompiler output

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4163]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4170-dev
- OS: Windows 11, x64

**Bug Description:**
When I rename a enumeration member, it does not reflected on the decompiler output.

**Steps To Reproduce:**
* Create an enumeration
* Use one of its member somewhere in the decompiler output
* Rename that enumeration member
* See the bug

**Expected Behavior:**
I expect it to reflect the changes to the decompiler output.

**Screenshots:**
![Recording 2023-03-29 at 10 28 12](https://user-images.githubusercontent.com/109607896/228474043-1c848830-01fa-4de4-afab-0bd75b8bd124.gif)

**Comment by 0cyn** [comment]
Resolved in **builds >= 4.0.4859**
