### ISSUE TITLE
Optimize `if 0 < variable` like if statements

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4165]
I've encountered a several interesting `if`s like this:

```c
if (0 u< NtHdrs->numberOfSections) {
```

```assembly
0041417f  33c0               xor     eax, eax  {0x0}
00414181  663b4106           cmp     ax, word [ecx+0x6 {COFF_Header::numberOfSections}]
00414185  0f838b000000       jae     0x414216
```

which looks ugly in the decompiler output. I would prefer 

```c
if (NtHdrs->numberOfSections) {
```

instead of first one. Could be related to #4137.

**Comment by plafosse** [comment]
We now do this by default in PseudoC

![image](https://github.com/user-attachments/assets/ded60e7d-39dd-4d87-bad1-5435b244cf33)

**Comment by plafosse** [comment]
Closing this in favor of https://github.com/Vector35/binaryninja-api/issues/4137
