### ISSUE TITLE
Crash when creating a stack variable in malformed offset

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4169]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4170-dev Personal, 7b9a14df
- OS: Windows 11, x64

**Bug Description:**
BN could crash if we create a stack variable in malformed offset.

**Steps To Reproduce:**
1. Open any binary
2. Go to stack sidebar
3. Create new stack variable and give offset as `-0x2c09999999`
4. See the crash

**Expected Behavior:**
Even if this is a rare case, it should not crash.

**Comment by plafosse** [comment]
My assumption here is memory exhaustion in `std::vector<StackViewLine> LineBuilder::buildFillLines(int64_t offset, int64_t nextOffset) const` Its trying to render all the fill lines into a vector. The existing code doesn't have any saftey checking to ensure that the offset isn't overly large.

**Comment by plafosse** [comment]
Will be fixed in 3.4.4190
