### ISSUE TITLE
Type editor does not append structure members to correct place when structure size manually set

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4181]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4189-dev
- OS: Windows 11, x64

**Bug Description:**
See the GIF please.

**Steps To Reproduce:**
1. Open types sidebar
2. Create a structure and give it a size in Create Structure dialog
3. Click end of the structure and press `4` in order to append a member in 4 byte size
4. See that member append in the beginning of the structure

**Expected Behavior:**
I expect it to append it to end of the structure

**Screenshots:**
![Recording 2023-04-04 at 13 30 15](https://user-images.githubusercontent.com/109607896/229778357-e2196ff9-0589-4ac2-8022-4a1788811942.gif)

**Comment by CouleeApps** [comment]
This is fixed in the new Type Browser, available as of 3.6.4615-dev
