### ISSUE TITLE
Add ability to merge two type definitions

### ISSUE THREAD

**Issue by kristopax** [Vector35/binaryninja-api#4184]
**What is the feature you'd like to have?**
I would like the ability to merge two type definitions. 

**Additional Information:**
This will enable Sidekick to work more fluidly.

**Comment by ccarpenter04** [comment]
Could you provide a couple examples of ways you'd like to see them merged? I can imagine a lot of conflict cases.

**Comment by CouleeApps** [comment]
Duplicate of #2594
