### ISSUE TITLE
Add ability to Expand All/Collapse All in the Components View

### ISSUE THREAD

**Issue by kristopax** [Vector35/binaryninja-api#4187]
**What is the feature you'd like to have?**
I would like the ability to expand all/collapse all items in the Components View.

**Is your feature request related to a problem?**
Currently, in order to identify the full structure in the Components View, the user must manually expand each item.

**Additional Information:**
This feature will enable Sidekick to work more fluidly.

**Comment by cxnder** [comment]
This should be very trivial to implement in a UI plugin once componenttree.h is moved to the public api repository.

**Comment by cxnder** [comment]
Resolved in **builds >= 3.4.4202**
