### ISSUE TITLE
Install new dependencies during plugin update

### ISSUE THREAD

**Issue by kristopax** [Vector35/binaryninja-api#4188]
**Version and Platform (required):**
- Binary Ninja Version: latest
- OS: MacOS
- OS Version: Monterey
- CPU Architecture: M1

**Bug Description:**
In the plugin manager, when updating a plugin that contains new dependencies, the update process does not install the new dependencies.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Install an old version of the Sidekick plugin
2. Install a new version of the Sidekick plugin that adds new packages
3. In the python console, enter "import <new_python_dependency"

**Expected Behavior:**
I expected during the update process that the new dependencies would be installed.

Currently, the only work around is to uninstall the plugin and re-install it.

**Comment by psifertex** [comment]
Resolved last week, not sure the exact build number.
