### ISSUE TITLE
Open Keyboard Shortcuts... doesnt work on windows

### ISSUE THREAD

**Issue by 0xFDFDFDFD** [Vector35/binaryninja-api#4190]
Platform: Windows 11 Version 22H2
The "Open Keyboard Shortcuts..." option doesn't work on windows. I assume it is because it is calling CreateFile on <%WhateverInstallPath%\Vector35\BinaryNinja\docs\guide\index.html#default-hotkeys> instead of calling the correct moniker (Maybe this would be file:///). if you click on open user guide the correct moniker will be called, i hope this helps to fix this bug.

**Comment by psifertex** [comment]
The only real fix we could come up with would be to refactor that section of the user guide into a totally separate file something which we decided wasn't worth the benefit of being able to directly link to it.
