### ISSUE TITLE
new symbols view filtered + arrow keys regression

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#4195]
**Version and Platform (required):**
- Binary Ninja Version: 4189

**Bug Description:**
On the previous symbol list, I could type a phrase in the search filter and use the arrow keys to select from the filtered list.

This is currently broken in the updated symbol view with components support. Arrows don't do anything that I'd expect.

**Comment by cxnder** [comment]
Resolved in **builds >= 3.4.4203**
