### ISSUE TITLE
new symbols view should navigate to currently selected function when it changes

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#4199]
Regression from the previous symbol list behavior.

**Comment by cxnder** [comment]
Resolved in **builds >= 3.4.4203** (I think, this issue is kind of unclear)

**Comment by psifertex** [comment]
I found a slight edge case where when it first loads the behavior isn't quite consistent. Oh! I think I see what it is. The current function is indeed the "highlighted" color (or whatever the color is that shows the current function), but because initial analysis can cause the function list to move/adjust, it can move the "selected" function off the pane and then when you click around in the same function it's already highlighted (but just not visible) so nothing is shown. 

The next time you leave that function and go elsewhere though, then it will update again and properly sync.

**Comment by cxnder** [comment]
that is due to `ViewFrame::setCurrentFunction(FunctionRef func)` presumably only being called when you enter a new function, and affects old Symbols UI as well.
