### ISSUE TITLE
missing symbols in components

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#4204]
Across a number of versions are different platforms some users are experiencing all symbols missing in components view. All functions are listed as sub_* for example instead of their actual name. Saving a BNDB and opening on another machine may result in all symbols being visible. See Josh for a repro, also reported by a customer on Ubuntu 22.04 and 23.10 but didn't reproduce on Jordan's 22.04 Stream VM so it's unclear what might be the root cause.

**Comment by cxnder** [comment]
Should be resolved in **builds >= 3.4.4230**
