### ISSUE TITLE
Show Imports option does not work if function is in a folder

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4207]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4212-dev
- OS: Windows 11, x64

**Bug Description:**
"Show Imports" option does not work if function is in a folder.

**Steps To Reproduce:**
Please see the GIF below.

**Expected Behavior:**
I expect it to hide /show imports even if it is in a folder.

**Screenshots:**

![Recording 2023-04-10 at 23 13 14](https://user-images.githubusercontent.com/109607896/230989648-85b06e5a-ff50-4d53-8297-cd27c97cdf64.gif)

**Comment by op2786** [comment]
Looks like other options like Show Functions -> Local does not work either in same situation.

**Comment by cxnder** [comment]
This is intentional behavior, and can be disabled by unchecking the Folders menu options "Always Show All Contained Data Variables" and "Always Show All Contained Functions"

![image](https://user-images.githubusercontent.com/55725881/231044794-26c56a4a-ffe4-4203-8670-ff8f5e0c5ce5.png)
