### ISSUE TITLE
New symbols UI scrolls sideways when searching

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#4208]
**Version and Platform (required):**
- Binary Ninja Version: 3.4 dev (eef3ec3)
- OS: macOS
- OS Version: 12.5
- CPU Architecture: M1

**Bug Description:**
When I search for text in the new symbols ui (components), the results all scroll to the left by about 30px.

**Steps To Reproduce:**
0. Enable components UI
1. Open binary
2. Click any symbol in the sidebar
3. Enter text in search bar
4. Observe L E F T

**Expected Behavior:**
I expected the view not to scroll unless i scrolled it.

**Screenshots:**
![image](https://user-images.githubusercontent.com/711973/230997083-fa30519f-8375-48ac-97a5-708791f40aa8.png)

**Additional Information:**
Tags view might be of assistance in solving this-- it does not have the same bug

**Comment by bpotchik** [comment]
I was unable to repro this in the newer than new symbols view. Please reopen if you encounter this again.
