### ISSUE TITLE
Freezing when trying to create 2 folder in components view

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4209]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4212-dev
- OS: Windows 11, x64

**Bug Description:**
When we try to create a second folder in components view, BN freeze. In the GIF below, I've demonstrated it a bit unnecessarily complex way. It could be reproduced by simply trying to create two folder that have at least one function with "New Folder With Selection" option.

**Steps To Reproduce:**
Please see the GIF below.

**Screenshots:**
![Recording 2023-04-10 at 23 45 50](https://user-images.githubusercontent.com/109607896/230997061-543f3b2d-ebda-440b-aa40-3cda187af1ac.gif)

**Comment by bpotchik** [comment]
Fixed in `3.6.4660-dev`.
