### ISSUE TITLE
When naming a symbol via type setting ('y'), you can overwrite an existing name without confirmation.

### ISSUE THREAD

**Issue by Hypersonic** [Vector35/binaryninja-api#421]
For instance, if you have a symbol named `x`, and another symbol named `data_1234`, and you go to set the type of `data_1234`, you can retype it to `int32_t x`.

This will rename `data_1234` to `x` without confirmation, as opposed to when renaming with the rename functionality, which prompts for confirmation.

**Comment by plafosse** [comment]
This is working as intended. You can always undo.
