### ISSUE TITLE
HLIL variable does not appear in function.hlil.vars list when only variable reference is address taken

### ISSUE THREAD

**Issue by kristopax** [Vector35/binaryninja-api#4224]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4173-dev
- OS: MacOS
- OS Version: Monterey
- CPU Architecture: M1

**Bug Description:**
Given an HLIL function, a variable defined in one of its HLIL instructions does not appear in the Function.hlil.vars list when the only reference to that variable is an address-taken type.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open the attached binary and switch to Linear High Level IL view
2. Navigate to 0x4094c with the "void var_98" instruction highlighted
3. In the Python console, enter and see the following:

```
>>> current_il_instruction.var
<var void var_98>
>>> current_il_instruction.var in current_function.hlil.vars
False
```

**Expected Behavior:**
I expected `current_il_instruction.var in current_function.hlil.vars` to return True.

**Screenshots:**
![image](https://user-images.githubusercontent.com/79866371/232213070-51cf4282-35e1-4f6e-9f45-dad498d915a4.png)

**Additional Information:**
In this case, it appears that var_98 is a stack variable used solely to refer to its address on the stack as a parameter to the __memcpy_chk function.  It seems that whenever the only reference to a variable is via address taken, it is not captured as one of the variables in the Function.hlil.vars list.  It seems the only way I can find these variables is to iterate through all the instructions of the HLIL function and capture the instruction vars into a set for the function.

[lighttpd.zip](https://github.com/Vector35/binaryninja-api/files/11239306/lighttpd.zip)

**Comment by D0ntPanic** [comment]
From the documentation on `HighLevelILFunction.vars`:

```
This gets just the HLIL variables - you may be interested in the union of `HighLevelIlFunction.source_function.parameter_vars` and `HighLevelIlFunction.aliased_vars` as well for all the variables used in the function
```

In this binary the variable referenced does appear in the `HighLevelILFunction.aliased_vars` list, so this is currently working as documented.
