### ISSUE TITLE
New symbols UI autoscrolls back to selection every 5 seconds

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#4225]
**Version and Platform (required):**
- Binary Ninja Version: 3.4 (based on 2763525)
- OS: macOS
- OS Version: 12.5
- CPU Architecture: M1

**Bug Description:**
When I've got a row selected in the new symbols ui (components), and try to scroll around to look at other functions, it jumps back to my selection after a few seconds of trying to read the other symbols. This basically makes it impossible to scan the symbols list as it keeps jumping around when I stop scrolling to actually read some text.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open a binary with a bunch of symbols
2. Double click one to navigate
3. Try to scroll around the symbols list to see the other symbols
4. Nope, Chuck Testa. You're back at your selection

**Expected Behavior:**
I expected the UI to not jump around when I'm not interacting with it (and the file is not analyzing either).

**Screenshots:**
Have a video: https://user-images.githubusercontent.com/711973/232265724-fc15bb24-11a0-4309-a61d-e312ad354eb3.mov

**Additional Information:**
Might be related to search queries? I tried clearing the query and it still did it, but I opened a different binary and it didn't reproduce.

**Comment by bpotchik** [comment]
Fixed in `3.6.4661-dev`.
