### ISSUE TITLE
nothing shown in the feature map

### ISSUE THREAD

**Issue by joelreymont** [Vector35/binaryninja-api#4229]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4228-dev
- OS: MacOS
- OS Version: 13.3.1
- CPU Architecture: M1 Max

**Bug Description:**
Entropy not displayed in the sidebar, although the entropy sidebar itself is displayed.

All I get is a black view.

**Steps To Reproduce:**
Just start.

![Screenshot 2023-04-17 at 07 20 10](https://user-images.githubusercontent.com/18791/232377152-8fee68f5-ace3-4705-a78b-a4ddda3e5330.png)

**Comment by psifertex** [comment]
One point of clarification is that the feature map doesn't show entropy. There _is_ a dedicated entropy via available via the "View" / "Triage Summary" menu option (or available from the second drop-down in the main pane) but the feature map shows [specific types](https://docs.binary.ninja/guide/index.html#feature-map) of analysis data. 

I suspect what is happening here is that the code is just a very very small amount of the overall address space. To fix that, try right-clicking the feature map and selecting "file-backed only mode" from the menu.

**Comment by joelreymont** [comment]
That's right, thank you @psifertex !
