### ISSUE TITLE
libcurl must be installed

### ISSUE THREAD

**Issue by h0ng10** [Vector35/binaryninja-api#423]
I tried to start binary ninja under Linux Mint 18, got following error message:

```
./binaryninja: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory
```
Solved it by installing libcurl3 via apt-get. Just to let you know

**Comment by psifertex** [comment]
Thanks for the comment, might help others using Mint. Yes, Linux mint is not an officially supported operating system and on unsupported Linux OS's this tends to be the most common problem, it's even mentioned in our troubleshooting guide at docs.binary.ninja. Once Ubuntu LTS moves to curl4 the situation should improve.
