### ISSUE TITLE
Building latest api with old bn release triggers large amount of `undefined reference to`

### ISSUE THREAD

**Issue by Learner0x5a** [Vector35/binaryninja-api#4231]
**Version and Platform (required):**
- Binary Ninja Version: [bn-release-3.1.3469-linux]
- OS: [Ubuntu]
- OS Version: [22.04]
- CPU Architecture: [x64]

**Bug Description:**
I'm building the latest binaryninja-api with an old bn (bn-release-3.1.3469-linux) in headless mode.
When I specify `cmake -S . -B build -DHEADLESS=ON`, everything is fine.
But there are a lot of `undefined reference to` when `-DBN_API_BUILD_EXAMPLES=ON` added.

**Steps To Reproduce:**
```bash
git clone https://github.com/Vector35/binaryninja-api.git
cd binaryninja-api
git submodule update --init --recursive
cmake -S . -B build -DHEADLESS=ON -DBN_API_BUILD_EXAMPLES=ON
cmake --build build -j24
```

**Expected Behavior:**
Expected to build with no error.

**Screenshots:**
![image](https://user-images.githubusercontent.com/21185907/232476657-cf5f5047-84d1-4fc2-8efd-ae5f7766003e.png)

**Comment by negasora** [comment]
Building the API with a mismatched version of the core is unsupported. Check `api_REVISION.txt` (in the base directory of your binja install) for the proper API version to use.

**Comment by Learner0x5a** [comment]
> Building the API with a mismatched version of the core is unsupported. Check `api_REVISION.txt` (in the base directory of your binja install) for the proper API version to use.

OK. Thank you!
