### ISSUE TITLE
Floating point calling convention is not applied when the called function is an extern one

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#4239]
For the following source code
```
#include <stdio.h>
#include <math.h>

int main(int argc, char** argv)
{
    double a = argc;
    double b = argc + 5;
    double c = pow(a, b);
    return 0;
}
```

compiled with `gcc -o floating_point_test floating_point_test.c -lm`, we can see the HLIL of `pow` is screwed up:

```
00001149  int32_t main(int32_t argc, char** argv, char** envp)

00001158      char** var_38 = argv
00001178      int64_t var_18 = float.d(argc + 5)
0000118f      pow(x: argc, y: argv)
00001199      int64_t var_10 = float.d(argc)
000011a3      return 0
```

The call to `pow` does not use the two doubles as its parameters. Instead, it uses `argc` and `argv`, which I believe happens to be the first two things in the calling convention if floating point convention is ignored. 

Binary: [floating_point_test.zip](https://github.com/Vector35/binaryninja-api/files/11271652/floating_point_test.zip)

However, if the `pow` function is a function inside of the binary, then everything works fine:

```
#include <stdio.h>
#include <math.h>

double sum(double a, double b)
{
    return a + b;
}

int main(int argc, char** argv)
{
    double a = argc;
    double b = argc + 5;
    double c = sum(a, b);
    return 0;
}
```

```
00001129  double sum(double arg1 @ zmm0, double arg2 @ zmm1)

00001150      return arg1 + arg2


00001151  int32_t main(int32_t argc, char** argv, char** envp)

00001160      char** var_38 = argv
000011a1      int64_t var_10 = sum(float.d(argc), float.d(argc + 5))
000011ab      return 0
```

P.S.: I noticed this while working with https://crackmes.one/crackme/641bb9a533c5d447bc761b6f, it triggers the same bug at 0x177c

```
sub_177c:
   0 @ 0000178b  int32_t var_10 = arg2.d
   1 @ 000017ae  pow(x: arg1, y: arg2)
   2 @ 000017be  return float.d(arg1.d)

```

**Comment by plafosse** [comment]
Fixed in 3.6.4705 
<img width="565" alt="image" src="https://github.com/user-attachments/assets/42dc9162-5b64-4c8a-8772-36277d67d059">
