### ISSUE TITLE
crashes trying to open certain powerpc binaries

### ISSUE THREAD

**Issue by verylazyguy** [Vector35/binaryninja-api#424]
[vmlinux-3.2.0-4-powerpc.zip](https://github.com/Vector35/binaryninja-api/files/437526/vmlinux-3.2.0-4-powerpc.zip)
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid

back trace looks like it might be the argument to a std::thread constructor

The kernel from the qcow2 at https://people.debian.org/~aurel32/qemu/powerpc/ makes it crash:  [vmlinux-3.2.0-4-powerpc.zip](https://github.com/Vector35/binaryninja-api/files/437527/vmlinux-3.2.0-4-powerpc.zip) (had to zip it because github)

**Comment by plafosse** [comment]
Sorry Greg :) we weren't supposed to have PPC in yet, I will test with your binaries before we officially add PPC support. Next Release will have PPC support removed, thanks for the test case.
