### ISSUE TITLE
UI: Unable to create symbol at a given address

### ISSUE THREAD

**Issue by joelreymont** [Vector35/binaryninja-api#4242]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4242-dev, 2e3a4286
- OS: macos
- OS Version: 13.3
- CPU Architecture: arm64

**Bug Description:**

I would like to create a symbol at a memory location so that I see `FETCH_CONFIG_END` instead of `0x13d3d0` BN is not letting me do this, though. Creating a variable at this address does not update the code either. 

Last but not least, there's no option to create a symbol when I navigate to the address.

**Screenshots:**
![Screenshot 2023-04-19 at 13 50 52](https://user-images.githubusercontent.com/18791/233055793-95a9f34f-57d2-4c00-9a80-be0512de8635.png)
![Screenshot 2023-04-19 at 13 51 10](https://user-images.githubusercontent.com/18791/233055799-1c139bec-6c81-4289-be5e-4b18947b1d5a.png)
![Screenshot 2023-04-19 at 13 52 06](https://user-images.githubusercontent.com/18791/233055802-f55dfb1f-4d9c-4864-bfcd-c177d7bc4ae0.png)
![Screenshot 2023-04-19 at 13 52 46](https://user-images.githubusercontent.com/18791/233055806-e8c4ec74-c612-4cd8-9bf4-3d910fb5e908.png)
![Screenshot 2023-04-19 at 13 53 33](https://user-images.githubusercontent.com/18791/233055807-9f5ea682-d2fd-406b-894f-cb691fe1ee17.png)

**Comment by plafosse** [comment]
Hit `y` to create a DataVariable at that location. Type `void`. Then you can name it with `N` 
![image](https://github.com/Vector35/binaryninja-api/assets/10556585/aaa9cef9-dffe-4818-bd0d-5543205289dd)
