### ISSUE TITLE
Missing data references

### ISSUE THREAD

**Issue by joelreymont** [Vector35/binaryninja-api#4243]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4242-dev, 2e3a4286
- OS: macos
- OS Version: 13.3
- CPU Architecture: arm64

**Bug Description:**

A function is referring to a memory address but the location is not being cross-referenced. The reference is indirect and the references appear as soon as I re-type the variable holding the base address as a pointer. 

Shouldn't BN be doing this for me automatically, though? I would have to have to go through each and every function to change types. 
![Screenshot 2023-04-19 at 14 18 36](https://user-images.githubusercontent.com/18791/233060897-3a7cce2a-b7b6-47b3-88e6-c52245b3361c.png)
![Screenshot 2023-04-19 at 14 24 36](https://user-images.githubusercontent.com/18791/233060904-df3ec710-0855-4658-9dc6-a97b439a6162.png)
![Screenshot 2023-04-19 at 14 24 21](https://user-images.githubusercontent.com/18791/233060909-00c88ef1-c99f-460d-b9b9-9b44dbbca97d.png)
![Screenshot 2023-04-19 at 14 22 26](https://user-images.githubusercontent.com/18791/233060910-432d2201-7332-4729-9284-9d044dae1b10.png)
![Screenshot 2023-04-19 at 14 22 04](https://user-images.githubusercontent.com/18791/233060916-a58a4dbb-b183-4466-9f75-41a73328e953.png)
![Screenshot 2023-04-19 at 14 20 31](https://user-images.githubusercontent.com/18791/233060917-5c4c3bd7-c48c-48b9-95ef-7db53c2cb612.png)
![Screenshot 2023-04-19 at 14 20 10](https://user-images.githubusercontent.com/18791/233060922-ec9c1f3e-11e2-4b0e-9cce-b55286ebfca8.png)
![Screenshot 2023-04-19 at 14 19 32](https://user-images.githubusercontent.com/18791/233060929-b9fed602-e829-4d4c-81fb-329824a6cd04.png)

**Additional Information:**

**Comment by joelreymont** [comment]
Related to the above. All of the ints here hold function pointers. BN has created the functions for me. Why hasn't BN adjusted these to be pointers, though?
![Screenshot 2023-04-19 at 14 34 40](https://user-images.githubusercontent.com/18791/233063346-aaec397c-903e-4741-aa55-0856a208822f.png)

**Comment by alexrp** [comment]
I think you might be running into the same thing I did in #3746.

**Comment by joelreymont** [comment]
V35 should search for "Encourage Salesman Prompt Delay" to find the database.

**Comment by plafosse** [comment]
This was complete in 3.5.4376 along with pointer sweep. There does still seem to be issue due to some missing lifting.
