### ISSUE TITLE
Create function shortcut is not creating code for the current architecture

### ISSUE THREAD

**Issue by joelreymont** [Vector35/binaryninja-api#4244]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4242-dev, 2e3a4286
- OS: macos
- OS Version: 13.3
- CPU Architecture: arm64

**Bug Description:**

I try to create a function using the `P` shortcut or picking `Default (thumb2) P` from the menu. This creates garbage.

Using the menu and _Make function at this address ––> thumb2 ––> thumb2_ works fine, though.

![Screenshot 2023-04-19 at 14 47 27](https://user-images.githubusercontent.com/18791/233066604-9d7eb2fc-6151-4490-b565-91cecb58aefe.png)
![Screenshot 2023-04-19 at 14 48 16](https://user-images.githubusercontent.com/18791/233066602-42752fc7-981e-487e-84b1-22d8b6afd834.png)
![Screenshot 2023-04-19 at 14 48 55](https://user-images.githubusercontent.com/18791/233066597-920b4d8d-0c2e-4a38-9f9a-5c260c582e4b.png)
![Screenshot 2023-04-19 at 14 51 12](https://user-images.githubusercontent.com/18791/233066586-2d4e3805-b381-41d9-a4d3-7fe870fc8a15.png)

**Comment by joelreymont** [comment]
V35 should search for "Encourage Salesman Prompt Delay" to find the database.

**Comment by joelreymont** [comment]
Apparently, it _is_ creating code for the current architecture. 

How do I change the current architecture of my database, though?

**Comment by plafosse** [comment]
If you'd like to create a thumb2 function you have to click on the address + 1. This or right clicking the address. Unfortunately Arm/Thumb is very difficult to work with.

**Comment by fuzyll** [comment]
Duplicate of #1177.

**Comment by psifertex** [comment]
Just a note that we've decided to re-open 1177 and plan to fix this as we now agree the current behavior is indeed a bug and we will fix it for the default case of using the UI when a default platform is set.
