### ISSUE TITLE
Issues link in bundled help docs goes to steakknife/unsign

### ISSUE THREAD

**Issue by mnem** [Vector35/binaryninja-api#425]
Version: 1.0.4 Personal (Build ID 27b0a2fe)
Platform: OSX 10.11.6

If you open the help documentation from the Help menu and then click on the Troubleshooting section, the link in "Have you searched known issues[issues]?" goes to https://github.com/steakknife/unsign.

**Comment by psifertex** [comment]
Yeah, this was a copy/pasta that was fixed in dev and online shortly after it was made, but it slipped in that build. We've got another build in testing now that resolves it.
