### ISSUE TITLE
Identical structure field names

### ISSUE THREAD

**Issue by joelreymont** [Vector35/binaryninja-api#4257]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4248-dev, c26685e2
- OS: macos
- OS Version: 13.3
- CPU Architecture: arm64

I understand this is a feature for function names. Should it be allowed for structure field names, though?
```
struct __data_var_refs drv_cfg_item_t __packed
{
    char* name;
    char field_4;
    char field_5;
    char field_6;
    char field_7;
    char field_8;
    char field_8;
    char field_8;
    char field_8;
};
```

I got here by re-typing 2 `int32_t` field names and then entering the type as `int8_t`, letting BN pick the field name for me.

**Comment by negasora** [comment]
This seems fixed, I can't repro by:
1. Selecting two `int32_t` struct members
2. Using `1` to automatically expand to 8 `uint8_t`s
