### ISSUE TITLE
Tags Sidebar Steals Focus

### ISSUE THREAD

**Issue by ElykDeer** [Vector35/binaryninja-api#4269]
The tags sidebar steals focus (when you create a tag) even when you have it closed.

https://user-images.githubusercontent.com/7171118/234714747-3429b5cd-5280-4e2b-aed4-53e93fba3286.mov

Note: When nothing is happening in the video I'm mashing my keyboard.

I believe that if we actually pop open the sidebar when tags are created, it would probably solve #3478, though not exactly as they requested.

**Comment by bpotchik** [comment]
This has been resolved. The dialog accepts the tag text and the tags list no longer steals focus.

<img width="250" alt="Screenshot 2024-11-24 at 11 23 44 PM" src="https://github.com/user-attachments/assets/110b9f09-0fe9-45f2-92cc-b4a84a5f036a">
