### ISSUE TITLE
Reset filters does not refresh symbol list in component view

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4270]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4262-dev 
- OS: windows 11, x64

**Bug Description:**
But it should. Because when I disable several options it hides a lot of symbol in the list. So when I reset filters, I did not be able to saw that symbols because list is not refreshed.

**Steps To Reproduce:**
* Disable Show Functions -> Local
* Disable Show Functions -> Exported
* Reset Filters
* See symbol list does not refreshed

![Recording 2023-04-27 at 09 58 06](https://user-images.githubusercontent.com/109607896/234797931-01622353-03c7-445d-9fd7-b8f29f90154e.gif)

**Comment by cxnder** [comment]
Resolved in **builds >= 3.5.4308**
