### ISSUE TITLE
Errors/warnings in log from binary that has since been closed cannot be dismissed

### ISSUE THREAD

**Issue by D0ntPanic** [Vector35/binaryninja-api#4272]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4265
- OS: macOS
- OS Version: 13.3.1
- CPU Architecture: M1

**Bug Description:**
If you open a binary that generates errors or warnings during analysis and have a different tab (like the Python console) open in the global area, then close the binary, it becomes impossible to dismiss the pending warnings and errors in the bottom right of the status bar. Clicking on them will open the log, but not clear the warnings or errors.

If more than one binary is done in this way, clicking on the warnings or errors will show a drop down menu with several options that all do nothing:

<img width="179" alt="Screenshot 2023-04-28 at 9 18 30 PM" src="https://user-images.githubusercontent.com/7007406/235276667-623be99c-d31d-4c90-9c56-852c5142c01e.png">

**Comment by plafosse** [comment]
This will be fixed in 4.2.6320
