### ISSUE TITLE
Armv7 SXTH instructions lifting is incorrect 

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#4278]
**Version and Platform (required):**
- Binary Ninja Version: 3.4

The implementation of ARM SXTH instruction is not correct and leads to incorrect dataflow:

https://github.com/Vector35/arch-armv7/blob/master/il.cpp#L4525

It is expecting get_register_size to return in bits but it actually returns bytes. Additionally it should be sign extending and it doesn't look like its doing that either. Finally there should probably be a condition that checks if the rotation value is 0 and omits it all together.

**Comment by lwerdna** [comment]
https://github.com/Vector35/arch-armv7/commit/da656878c3acf85715df53e6ae09dfb60d31024e

Example lift **before** change:

```
7100bfe6                        sxth    r0, r1, ror  #0

LLIL_SET_REG
	r0
	LLIL_ASR
		LLIL_LSL
			LLIL_REG
				r1
			LLIL_CONST.d(0xFFFFFFF4)
				4294967284
		LLIL_CONST.d(0x10)
			16
LLIL_UNDEF
```

Now **after** the change:

```
7100bfe6                        sxth    r0, r1, ror  #0

LLIL_SET_REG.d
	r0
	LLIL_SX.d
		LLIL_LOW_PART.w
			LLIL_REG.d
				r1
LLIL_UNDEF
```

If we add some rotation, it utilizes LLIL_ROR:

```
7104bfe6                        sxth    r0, r1, ror  #0x8

LLIL_SET_REG.d
	r0
	LLIL_SX.d
		LLIL_LOW_PART.w
			LLIL_ROR.d
				LLIL_REG.d
					r1
				LLIL_CONST.b(0x8)
					8
```

The thumb encodings didn't exhibit any problems.
