### ISSUE TITLE
Scrolling down in linear disassembly mode can cause infinite function loops

### ISSUE THREAD

**Issue by mnem** [Vector35/binaryninja-api#429]
Sometimes when I'm scrolling down in linear mode, a disassembled block scrolls onto the screen and then keeps duplicating as I scroll. I can scroll down forever, or I can scroll back up out of it. As soon as I drag the thumb to scroll, it fixes it. It happens when I scroll with a mouse gesture, clicking the down arrow or clicking beneath the thumb to page down.

I'm not sure that's a great explanation, so here's a screenshot where the `_start()` block is being repeated:

<img width="771" alt="screen shot 2016-08-26 at 21 16 28" src="https://cloud.githubusercontent.com/assets/33655/18019175/d7467686-6bd2-11e6-8fd9-fec77b51d92c.png">

I haven't observed the same thing happening when scrolling upwards.

In case it's related to some odd parsing of the binary I was viewing I've a attached it. It's an armv7 elf file.

[main.gz](https://github.com/Vector35/binaryninja-api/files/440079/main.gz)

**Comment by D0ntPanic** [comment]
Fixed in dev
