### ISSUE TITLE
it is not possible to mark an array const to cause control flow to propagate correctly.

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#4293]
**Version and Platform (required):**
- Binary Ninja Version: 4272-dev
- OS: windows
- OS Version: 22h2
- CPU Architecture:: x64

**Bug Description:**
I have 3 arrays:

```
void func1(void) { puts("func1"); }
void func2(void) { puts("func2"); }
void func3(void) { puts("func3"); }
void func4(void) { puts("func4"); }

const void* bar[] = { func1, func2 };
const void* baz[] = { func3, func4 };

void** foo[] = { bar, baz };

int main(void) {
  void (*fptr)(void) = (void (*)(void))foo[0][0];
  fptr();
}
```

I should be able to mark all as const to get r/o semantics from them and have main resolve as a call to `func1`

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Go to foo, bar, and baz and mark them as const
2. Go to main
3. See dataflow not be properly resolved

**Expected Behavior:**
I expect main to contain a resolved call to `func1`.

**Comment by psifertex** [comment]
Can you share the exact binary or BNDB? I just tested and couldn't recreate it. Simply marking the single `foo` as constant was enough to resolve it but I suspect I'm doing something different:

<img width="923" alt="Screenshot 2023-05-07 at 9 43 49 PM" src="https://user-images.githubusercontent.com/140215/236715943-a7dc0153-e3bf-48da-845f-b818ac5adb39.png">
<img width="377" alt="Screenshot 2023-05-07 at 9 44 00 PM" src="https://user-images.githubusercontent.com/140215/236715959-9e33ea33-9987-4717-8445-4cf1a4973063.png">

**Comment by yrp604** [comment]
Sure [array.txt](https://github.com/Vector35/binaryninja-api/files/11417092/array.txt). Rename to exe

**Comment by yrp604** [comment]
so this appears to be due to `const void** foo` vs `void** const foo`. What is further confusing here is `const void **` gets parsed to `void const**`.

**Comment by plafosse** [comment]
I was able to get it to be seen as r/o if I type `foo` as `void *const * const`
