### ISSUE TITLE
Variables are incorrectly named to std lib names

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#4294]
**Version and Platform (required):**
- Binary Ninja Version: 4272-dev
- OS: Windows
- OS Version: 22h2
- CPU Architecture: x64

**Bug Description:**
When creating the repro for #4293 binary ninja named my functions incorrectly. Specifically, I compiled:

```
void func1(void) { puts("func1"); }
void func2(void) { puts("func2"); }
void func3(void) { puts("func3"); }
void func4(void) { puts("func4"); }

const void* bar[] = { func1, func2 };
const void* baz[] = { func3, func4 };

void** foo[] = { bar, baz };

int main(void) {
  void (*fptr)(void) = (void (*)(void))foo[0][0];
  fptr();
}
```

And binary ninja recovered the names of func1-func4 incorrectly. In the snippet below, I've renamed foo, bar, and baz but left the discovered names for their corresponding functions.

```
14001b000  void const* bar[0x2] = 
14001b000  {
14001b000      [0x0] = std::_Error_objects<int32_t>::ystem_object::`local vftable'::
14001b008      [0x1] = std::fout::()
14001b010  }
14001b010  void const* baz[0x2] = 
14001b010  {
14001b010      [0x0] = std::ignore::()
14001b018      [0x1] = std::_Error_objects<int32_t>::ostream_object::`vector destructor iterator'::
14001b020  }
14001b020  void const** foo[0x2] = 
14001b020  {
14001b020      [0x0] = bar
14001b028      [0x1] = baz
14001b030  }
```

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Compile the code above in msvc
2. See the incorrect names once you open a binary

**Expected Behavior:**
I expect binary ninja to either correctly name things or not attempt to name them.

**Comment by plafosse** [comment]
As far as I can tell the DataVariable names aren't stored in the binary and the function names are due to bad function sigantures. https://github.com/Vector35/binaryninja-api/issues/3773
