### ISSUE TITLE
documentation - FunctionReturn isn't in docs

### ISSUE THREAD

**Issue by lucasduffey** [Vector35/binaryninja-api#430]
FunctionReturn isn't in api.binary.ninja - You can use this to indicate an instruction will return:

example, in "perform_get_instruction_info" for the DEX architecture:

`if instr in ["return-void", "return", "return-wide", "return-object"]:
        result.add_branch(FunctionReturn)`

**Comment by psifertex** [comment]
A small bug in the table prevented the relevant snippet of documentation from showing up, it's maybe not quite where it should be, but it is searchable at least now along with all the other branch types: 

http://api.binary.ninja/python.html?highlight=functionreturn#binaryninja.Architecture.perform_get_instruction_info
