### ISSUE TITLE
Missing Structure Field Assignments via `__builtin_memcpy` on Stack Vars

### ISSUE THREAD

**Issue by w1282** [Vector35/binaryninja-api#4301]
**What is the feature you'd like to have?**
When the destination of a call to `__builtin_memcpy` is a stack variable that has been typed with a structure, it would be nice for the `__builtin_memcpy` to be exploded into a series of structure field assignments, in a similar fashion to how non-stack variable static assignments are handled.

**Is your feature request related to a problem?**
There is a loss of clarity when a stack-local structure is initialized with default values and those get optimized into a single static assignment which gets translated into a `__builtin_memcpy` call. See below screenshot for example.

**Are any alternative solutions acceptable?**
None that I have considered.

**Additional Information:**
Please add any other context or screenshots that would help us understand your feature request here.
![sample](https://github.com/Vector35/binaryninja-api/assets/24464219/3bd11488-22e3-4cac-91f1-1f66e79a783d)

**Comment by bpotchik** [comment]
Fixed in `3.5.4292-dev`.
