### ISSUE TITLE
UIDF values do not display in variables view

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#4302]
**Version and Platform (required):**
- Binary Ninja Version: 4276-dev
- OS: Windows
- OS Version: 22h2
- CPU Architecture: x64

**Bug Description:**
After setting UIDF values, the new values are not reflected in the Variables view.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Set any value
2. Select the variables view
3. See error

**Expected Behavior:**
I expect the variables view to show me the dataflow state of variables, if available.

**Screenshots:**
Prior to UIDF:
![image](https://github.com/Vector35/binaryninja-api/assets/8716677/3e946192-2cf3-4428-b144-30b420530c2b)

After using UIDF @ 14:
![image](https://github.com/Vector35/binaryninja-api/assets/8716677/f9ed5287-ac23-41aa-859e-86a04d1a8939)

**Additional Information:**
Please add any other context about the problem here.

**Comment by negasora** [comment]
Fixed in `3.6.4627-dev`
