### ISSUE TITLE
Thumb2: RRX

### ISSUE THREAD

**Issue by joelreymont** [Vector35/binaryninja-api#4304]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4251-dev, 3f761e0a
- OS: macos
- OS Version: 13.3
- CPU Architecture: arm64

IDA Pro
```
ROM:00004B76                 MOV.W           R1, R1,RRX
```

BN
```
🚫000004b76  4fea3101   rrx     r1, r1
```

Why the difference?

**Comment by joelreymont** [comment]
V35 should search for "Encourage Salesman Prompt Delay" to find the database.

**Comment by fuzyll** [comment]
This instruction is a [preferred synonym for `MOV` instructions with shifted register operands](https://developer.arm.com/documentation/dui0473/m/arm-and-thumb-instructions/rrx). IDA isn't wrong - its output is what you'll find in the ARM manual. But, neither are we.
