### ISSUE TITLE
Naming variables can hide others

### ISSUE THREAD

**Issue by percontation** [Vector35/binaryninja-api#432]
Naming a variable can cause other variables to no longer be labeled in the disassembly (or IL) view.

![screen recording](https://cloud.githubusercontent.com/assets/563506/18033156/625940fc-6cd0-11e6-9409-c4e2dc095cac.gif)

(In the gif I'm hitting undo after each rename.)

[binary.zip](https://github.com/Vector35/binaryninja-api/files/441078/binary.zip)

Version 1.0.314

**Comment by plafosse** [comment]
This bug was fixed a while ago. Verified fixed on 1.1.1038
