### ISSUE TITLE
Crash on unplugging two monitors at the same time, OS X.

### ISSUE THREAD

**Issue by percontation** [Vector35/binaryninja-api#433]
Binary Ninja crashes when unplugging two external monitors at the same time from my laptop (2x Apple Monitor / Macbook Pro). Happens about 25% of the time when quickly detaching my monitor cables.

Assumedly this is a Qt bug; a brief check suggests it's unreported.

OS X crash log: [crash.txt](https://github.com/Vector35/binaryninja-api/files/441085/crash.txt)

**Comment by psifertex** [comment]
Sorry for the long delay, we were finally able to do a QT rev -- can you please confirm whether you still have this issue with builds >=1041?

**Comment by percontation** [comment]
Yep, fixed.

...apparently I sucked at googling before, pretty sure it was this https://bugreports.qt.io/browse/QTBUG-48275
