### ISSUE TITLE
SSA Form MLIL push handling

### ISSUE THREAD

**Issue by verd1c** [Vector35/binaryninja-api#4333]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4271
- OS: Windows
- OS Version: 11
- CPU Architecture: x64

**Bug Description:**

I have the following disassembly that moves a value from the first argument to rdx, and pushes that to the stack:

![image](https://github.com/Vector35/binaryninja-api/assets/38715146/86d17b05-cf7f-474a-934b-bd76dcca83b6)

In MLIL SSA form this looks like this:

![image](https://github.com/Vector35/binaryninja-api/assets/38715146/f2fa3225-89a2-4744-8e87-49ce857b1630)

Where line 6 and 7 seem to be the ones representing the push. I'm trying to do some data flow analysis and follow rdi through the function, and I am using the Function. However, when pointing at instruction 6 and trying to get the uses of the value it writes to (var_18#1), it seems to not find the &var_18, making it impossible to follow taint:

![image](https://github.com/Vector35/binaryninja-api/assets/38715146/b2cdaf35-63d5-473d-a935-ac8ea1cb521a)

Is there any way to overcome this and follow the push?

**Comment by plafosse** [comment]
For our purposes we don't assume _address taken_ as a use.  You can however this this information using the IL instruction apis `vars_read`, `vars_written` and `vars_address_taken`
