### ISSUE TITLE
Opening specific binary on version 3.5.4294-dev crashes

### ISSUE THREAD

**Issue by emesare** [Vector35/binaryninja-api#4350]
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4294-dev
- OS: Windows 11
- OS Version: 22H2
- CPU Architecture: x64

**Bug Description:**
Opening a specific binary crashes binary ninja.

**Steps To Reproduce:**
1. [Download binary](https://letsupload.cc/v25bE5t2zf/simple_exe)
2. Attempt to open the binary inside Binary Ninja
3. Crashes with `NullClassPtr`

**Expected Behavior:**
Expect binary to open and not crash Binary Ninja

**Additional Information:**
I bisected the dev versions and found that the crash was introduced in `3.5.4294-dev` (i.e. I don't experience this crash on `3.5.4293-dev`), [here was my crash dump](https://letsupload.cc/pb53Eft3zf/accessviolation_dmp) (generated with windbg).

**Comment by emesare** [comment]
> I was unable to repro this crash 3.5.4304. Could you possibly have a plugin installed causing this? Please disable your plugins and try to load the file again.

I have disabled every plugin (including debugger, objective-c). For clarification I have tested that Binary Ninja crashes from latest dev (3.5.4304 to 3.5.4294-dev), [here is the crash dump](https://letsupload.cc/v709F5taz3/accessviolation2_dmp) from the latest dev (3.5.4304).

**Comment by yrp604** [comment]
I hit this on a different binary and was able to repro it on this one by scrolling up/down very quickly in linear view.

**Comment by xusheng6** [comment]
Fixed by [390387c6aff9cc8370f0c0d9791b93179cb2a20a](https://github.com/Vector35/binaryninja/commit/390387c6aff9cc8370f0c0d9791b93179cb2a20a)
