### ISSUE TITLE
Disassembly type annotations are incorrect or missing

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#4352]
**Version and Platform (required):**
- Binary Ninja Version: 4299-dev
- OS: Windows
- OS Version: 11
- CPU Architecture: x64

**Bug Description:**
For some structure layouts, the type annotations in the disassembly are incorrect

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open the attached bndb
2. Switch to disassembly view
3. Look at instruction 12

**Expected Behavior:**
I expect to see `mov     eax, dword [rbx {struct_1::last}] `

There is a second bug as well. If you change type of struct_1::last to `int32_t`, the same move a 12 now has no type information associated with it.

**Screenshots:**
![image](https://github.com/Vector35/binaryninja-api/assets/8716677/dec177ca-1462-4892-990c-4831e4885893)

**Additional Information:**
MLIL and above do this properly, it is only the disassembly view that displays incorrect annotations

[binja-bad-disassembly-type.bndb.txt](https://github.com/Vector35/binaryninja-api/files/11579337/binja-bad-disassembly-type.bndb.txt)

**Comment by plafosse** [comment]
Fixed in 3.5.4324
