### ISSUE TITLE
Incorrect documentation for `Function.callees` in Python API 

### ISSUE THREAD

**Issue by comex** [Vector35/binaryninja-api#4356]
**Version and Platform (required):**
`binaryninja-api` 5e61fe0e0f4cb2e7747acc6f2cd73858d7bfe452

**Bug Description:**
From `python/function.py`:
```py
    @property
    def callee_addresses(self) -> List[int]:
        """
        ``callee_addressses`` returns a list of start addresses for functions that call this function.
        Does not point to the actual address where the call occurs, just the start of the function that contains the reference.

        :return: List of start addresess for Functions that call this function
        :rtype: list(int)
        """
```
This contains two copies of the text "functions that call this function", but that confuses callees with callers.  It should say "functions that this function calls".

Also, "addresess" is misspelled.

**Comment by plafosse** [comment]
Fixed in 3.5.4323
