### ISSUE TITLE
Enum flags are all rendering on top of one another

### ISSUE THREAD

**Issue by 0cyn** [Vector35/binaryninja-api#4360]
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4307
- OS: macOS
- OS Version: 13
- CPU Architecture: M1

**Bug Description:**
Enum flags render partially on top of one another

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open a Mach-O
2. Scroll to the top.

**Expected Behavior:**
Despite the decreased footprint of enums with several flags, these should probably be rendered spaced out

**Screenshots:**
![image](https://github.com/Vector35/binaryninja-api/assets/55725881/517e832f-34cd-48bf-9848-e16e24984af8)

**Comment by cxnder** [comment]
Resolved in **builds >= 3.5.4309**
