### ISSUE TITLE
Disassembly of small binary hangs

### ISSUE THREAD

**Issue by darkf** [Vector35/binaryninja-api#437]
I grabbed the demo and ran it on KiTTY (a 514kb binary) and let it disassemble. I forgot about it and left it running overnight (~12 hours) and it's still "disassembling", maxing out a core of my PC. 

Not a great demo for a commercial product, I'll be honest. :)

**Comment by plafosse** [comment]
Unfortunately this binary is packed with UPX which we don't currently support please follow issue #338 if you are interested in its resolution.  To work around this issue unpack the binary and reopen it. Though looking at the binary after unpacking we see a different bug which I will be filing separately.
