### ISSUE TITLE
`src` parameter of `__builtin_memcpy` should be typed as `void const*`

### ISSUE THREAD

**Issue by alexrp** [Vector35/binaryninja-api#4376]
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4311-dev Personal (ff27871c)
- OS: Windows
- OS Version: 10.0.25375.1
- CPU Architecture: x64

**Bug Description:**
Just a minor nitpick, in the synthetic `memcpy` builtin:

```c
7ff68b024000  extern void* __builtin_memcpy(void* dest, void* src, uint64_t n)
```

`src` should probably be typed as `void const*` to be consistent with the other builtins.

**Comment by bpotchik** [comment]
Fixed in 3.5.4357-dev.
