### ISSUE TITLE
IAT entries are not parsed correctly after unpacking UPX executables

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#438]

**Comment by jeffli678** [comment]
Do you still remember any details about this or happen to have an offending file? I think we parse the unpacked PE correctly. Btw is there anything special about the unpacked binary

**Comment by xusheng6** [comment]
This is fixed after we get the number of IAT entries based on the first all-zero struct, rather than the reported number. https://github.com/Vector35/view-pe/blob/d4116c805d1bf8b645ebbe9367e62c4de786e87e/peview.cpp#L1055-L1062.
