### ISSUE TITLE
Recovery of variable types in from DWARF

### ISSUE THREAD

**Issue by ltlly** [Vector35/binaryninja-api#4383]
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4315-dev Personal, 8ff26e7e
- OS: windows
- OS Version: 11
- CPU Architecture: x86_64

**Bug Description:**
The binary file contains DWARF information and decompiles well in IDA, but only limited information is recognized in BinaryNinja.
I already use "DWARF import"
This is my binary file
[Baby_Re.zip](https://github.com/Vector35/binaryninja-api/files/11649783/Baby_Re.zip)

![image](https://github.com/Vector35/binaryninja-api/assets/86669384/ccc76ccb-c8c7-4674-b359-7bf201f49662)

**Steps To Reproduce:**
decompiles the binary file
click F5

**Expected Behavior:**
Analysis as accurate as IDA

![image](https://github.com/Vector35/binaryninja-api/assets/86669384/e56933f4-8b33-44db-9308-23332f4fb8d0)

**Comment by KyleMiles** [comment]
Closing this in favor of #1555.
