### ISSUE TITLE
Remember selected log category across restarts

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/binaryninja-api#4389]
It would be helpful if there were a way to make the log category selection (`BinaryView.MachoView` in the picture below) stay selected across restarts.

<img width="594" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/41548458/d9b316e2-0956-4c70-b16f-3c0472b939a6">

This is particularly helpful when you are developing a new plugin and are frequently checking debug messages, etc., but don't care about the log output of anything else.

Right now, to test my changes to my plugin, I have to restart Binary Ninja, reopen a file, then re-select the log category. The first two steps are obviously necessary, but avoiding the last one would be a nice quality of life improvement.

**Comment by psifertex** [comment]
Re-opening a file is not required! 

Use the "restart and reopen files" action. 

Instead of only doing it on restart, I'll just make that filter sticky in general across both restarts and tabs.

Resolved in builds >= 3.5.4319

**Comment by plafosse** [comment]
The commit that added this caused a major UI performance regression and had to be reverted.

**Comment by fuzyll** [comment]
This should be fixed in builds >= 3.5.4352, but with better performance this time. Please comment on this issue if you notice performance issues again, or any other edge cases, with the new implementation.
