### ISSUE TITLE
Go to Address relative to image base

### ISSUE THREAD

**Issue by alexrp** [Vector35/binaryninja-api#4391]
**What is the feature you'd like to have?**
Today, Go to Address can either be absolute or relative to the current position. It would be nice if there was an option to go to an RVA (i.e. an offset relative to the image base).

**Are any alternative solutions acceptable?**
* Going to the image base and performing the relative go-to from there.
* Manually performing the image base + RVA addition in the go-to dialog.

**Comment by plafosse** [comment]
You can do this using the built in variables, The goto dialog accepts a full language that supports 

`$start` - Beginning of the BV
`$end` - End of the BV - 1
`$` - Current location
`[]` - Dereference operations

This is all documented here: https://api.binary.ninja/binaryninja.binaryview-module.html#binaryninja.binaryview.BinaryView.parse_expression
