### ISSUE TITLE
Linear Disassembly View Doesn't Show All Data

### ISSUE THREAD

**Issue by zachriggle** [Vector35/binaryninja-api#440]
Linear disassembly view attempts to intermix data and disassembled instructions.  It appears that it only shows data when there is a cross-reference to it.  For example, the ELF header shown here doesn't display the full "7fELF" while analysis is underway.

<img width="473" alt="screen shot 2016-08-30 at 6 04 21 pm" src="https://cloud.githubusercontent.com/assets/111640/18112446/7a497304-6edc-11e6-99ae-12cc933b11b5.png">

**Comment by plafosse** [comment]
I believe this issue was fixed, please reopen if you have a test case in the latest dev.
