### ISSUE TITLE
Enum representation shows 'foo | 0x10' instead of 'foo & ~0x10'

### ISSUE THREAD

**Issue by comex** [Vector35/binaryninja-api#4402]
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4325-dev (41782587)
- OS: macOS
- OS Version: 13.3 (22E252)
- CPU Architecture: arm64

**Bug Description:**
When Binary Ninja displays the value 0x23 as type `enum e : uint8_t { _0x33 = 0x33 }`, it shows `_0x33 | 0x10`, when it should be `_0x33 & ~0x10` or just `0x23`.

**Steps To Reproduce:**
1. Load [this file](https://github.com/Vector35/binaryninja-api/files/11715481/enum-test.txt) which just consists of the bytes `0x23 0x33`.
2. Create an enum: `enum e : uint8_t { _0x33 = 0x33 }`
3. Create a variable of type `enum e` for each byte.
4. Notice the display:
```
00000000  enum e data_0 = _0x33 | 0x10  // this is 0x23
00000001  enum e data_1 = _0x33  // this is 0x33
```

**Additional Information:**
Question: Is there some way to mark an enum as "not a bitfield" so Binary Ninja only uses named constants if there's an exact match?

**Comment by negasora** [comment]
Fixed in `3.5.4326-dev`
