### ISSUE TITLE
FR: Display string as "UTF-8"

### ISSUE THREAD

**Issue by WZ-Tong** [Vector35/binaryninja-api#4403]
**What is the feature you'd like to have?**
When a library contains strings of non-English words (in stack, in global variable `.bss`, etc), when convert them using key `a`, it transformed into python bytes representation (like `\xAB\xCD`), I want to add an option to "Display as" menu to transform them into UTF-8 string representation. (And possibly add an option that "If I press `a`, force to convert to UTF-8 string rather than python bytes" in settings)

**Comment by negasora** [comment]
Sorry, I misunderstood the issue. This should already be supported - do you have the relevant blocks in `analysis.unicode.blocks`?

**Comment by WZ-Tong** [comment]
Thanks, I just searched "utf-8" and see the checkbox, but missed the Unicode blocks option.

**Comment by psifertex** [comment]
Good point -- I just added "UTF" to the description of that setting to make it easier to find.
