### ISSUE TITLE
parse_expression API needs to use arch endianness

### ISSUE THREAD

**Issue by amtal** [Vector35/binaryninja-api#4404]
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4320-dev
- CPU Architecture: armv6

**Bug Description:** `[addr]` syntax does LE reads on BE arch

**Steps To Reproduce:** try dumping a command table from some BE net app fw

**Expected Behavior:** read 32bit words just like processor does, `bv.arch.endianness` is set correctly even in data region

**Additional Information:** please lift ARMV7_TEQ

**Comment by plafosse** [comment]
This will be fixed in 3.5. 4329
