### ISSUE TITLE
GUI viewport snaps to base address when editing distant array entries

### ISSUE THREAD

**Issue by amtal** [Vector35/binaryninja-api#4405]
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4320-dev going back into infinity
- OS: win10 19045
- CPU Architecture: 86_64

**Bug Description:** GUI viewport of arrays-of-structs snaps to base address of array when editing entry names 

**Steps To Reproduce:**
1. open something with a CLI implemented with arrays of structs containing `{char* name; handler}` or similar
2. create `cmd_struct cmd_table[123];` overtop that .rodata
3. scroll way down, try to rename `cmd_struct[120].handler` to match interesting name/id prior to RE
4. viewport snaps to show `cmd_struct[0]`

**Expected Behavior:** viewport stays on table entry with recently-renamed function to maintain flow

**Additional Information:** please lift ARMV7_TEQ

**Comment by CouleeApps** [comment]
This turned out to be an issue where LinearView didn't know that the arrays had a length, so it always went to the top. Should be fixed on 3.5.4471-dev
