### ISSUE TITLE
Wrap long lines in MLIL & HLIL

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/binaryninja-api#4409]
HLIL could really benefit from wrapping long lines. I know IDA does this, I believe Ghidra does as well.

For example, this is a real function ([created by real programmers](https://i.kym-cdn.com/photos/images/newsfeed/002/029/841/a26.png)):

![image](https://github.com/Vector35/binaryninja-api/assets/41548458/d05ba0e3-0f54-4cef-8d40-361857f27152)

The screenshot is rough as-is, but when the function name and argument names aren't redacted, it barely fits on my 34" ultrawide monitor.

**Comment by plafosse** [comment]
Duplicate of #2366
