### ISSUE TITLE
Incorrect Data Access X-Refs for PIE binaries

### ISSUE THREAD

**Issue by zachriggle** [Vector35/binaryninja-api#441]
If you load a PIE ELF binary into Binary Ninja, the base address is set to zero.

This causes erroneous cross-references to be generated for any constant value.

Screenshots are attached. 

<img width="459" alt="screen shot 2016-08-30 at 6 09 00 pm" src="https://cloud.githubusercontent.com/assets/111640/18112495/e0d4bba6-6edc-11e6-8e04-0bfb22c58607.png">
<img width="317" alt="screen shot 2016-08-30 at 6 08 54 pm" src="https://cloud.githubusercontent.com/assets/111640/18112498/e2fc5272-6edc-11e6-91b8-76ca2282bfc5.png">

**Comment by plafosse** [comment]
Fixed in dev and stable.
