### ISSUE TITLE
Rename type dialog has wrong prompt

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/binaryninja-api#4410]
When renaming a type, the prompt in the dialog is "enter member name", but should in theory be "enter type name".

<img width="420" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/41548458/da3fe562-f423-4f51-a32d-32d3e77057eb">

Observed on Binary Ninja 3.5.4328-dev.

**Comment by fuzyll** [comment]
This should be fixed in builds >= 3.5.4352 now.
