### ISSUE TITLE
Adding a segment does not resize feature map

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#4411]
**Version and Platform (required):**
- Binary Ninja Version: 3.5.{dev}
- OS: macOS
- OS Version: 12.5
- CPU Architecture: M1

**Bug Description:**
When I use the segments editor and add a segment to the file, the feature map does not update to show the added segment, even if "file-backed only mode" is disabled.

**Steps To Reproduce:**
1. Open a file
2. Observe feature map
3. Open memory maps panel
4. Add a segment at the start of the binary (addr 0 length 0x100000 data addr 0 data length 0)
5. Observe feature map does not update
6. Right-click feature map and enable File-Backed only mode
7. Right-click feature map and disable File-Backed only mode
8. Observe feature map has updated

**Expected Behavior:**
I expected feature map to update automatically

**Additional Information:**
Via Andrew :)

**Comment by bpotchik** [comment]
The Feature Map will now update for segment and/or memory map changes.

Fixed in `4.2.5758`.
