### ISSUE TITLE
Pip installed packages are not accessible using bundled python interpreter

### ISSUE THREAD

**Issue by reversing-dev** [Vector35/binaryninja-api#4413]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4271 Personal, b7fd028d
- OS: windows
- OS Version: 11
- CPU Architecture: x86_64

**Bug Description:**
When Binja is using bundled python interpreter, pip installed packages are not getting loaded because the sys.path doesn't contain paths to install_directory\\plugins\\python\\Lib\\site-packages

**Steps To Reproduce:**
Install Binja into c:\binja (select install for current user only and change the path)
Install any package using bundled interpreter 
`C:\binja\plugins\python>python -m pip install networkx`

**Expected Behavior:**
Binja should populate the sys.path with correct paths.

**Screenshots:**
![image](https://github.com/Vector35/binaryninja-api/assets/42991292/05c9bfd1-152e-47db-9bd4-de164a65441f)

**Additional Information:**

**Comment by xusheng6** [comment]
This is actually the expected behavior. If you wish the packages installed via pip to be available inside of BN, you can set `python.interpreter` to the python interpreter associated that the pip (typically the system one)

**Comment by reversing-dev** [comment]
But I don't have any other python interpreter. The pip is from Binja's python interpreter, so it should reflect the install?

**Comment by xusheng6** [comment]
@reversing-dev oh sorry I misread the issue. I am not sure if we support installing packages in this way. I will re-open the issue and let my colleagues follow-up with it.
