### ISSUE TITLE
Nitpick: Confusing language in "duplicate variable name" warning dialog

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/binaryninja-api#4415]
The word "chosen" seems weird here since the name I entered is the name I chose, but isn't the "chosen name". Doing `s/chosen/suggested` on all the text in the dialog makes more sense in my opinion, and makes it clear what actually happens for each option.

![image](https://github.com/Vector35/binaryninja-api/assets/41548458/10b61c3b-fe0e-48f0-8852-40385bfb3ebf)

Could also change "Use My Name" to "Use Duplicate Name" for even more clarity.

**Comment by fuzyll** [comment]
This should be fixed in builds >= 3.5.4353, which is making its way through CI now and should be live soon.
