### ISSUE TITLE
quick EFI_LOCATE_PROTOCOL text fix

### ISSUE THREAD

**Issue by HackingThings** [Vector35/binaryninja-api#4418]
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4332-dev, 90f160d9
- OS: windows
- OS Version: 11
- CPU Architecture: x86_64

**Bug Description:**

Current:
EFI_LOCATE_PROTOCOL LocalProtocol;

**Steps To Reproduce:**
Check struct EFI_BOOT_SERVICES type definition
 
**Expected Behavior:**

Expeted:
EFI_LOCATE_PROTOCOL LocateProtocol

**Screenshots:**

**Additional Information:**
https://uefi-d.dpldocs.info/uefi.spec.EFI_LOCATE_PROTOCOL.html

**Comment by D0ntPanic** [comment]
Fixed in 3.5.4333
