### ISSUE TITLE
Misaligned disassembly text when Show opcode bytes option is on 

### ISSUE THREAD

**Issue by polsab** [Vector35/binaryninja-api#442]
Minor nitpick. Happens when opcode bytes are more than 8 bytes long.

![unaligned](https://cloud.githubusercontent.com/assets/868708/18112531/f6d1536e-6f5a-11e6-8d37-298bc8c8a37e.png)

**Comment by psifertex** [comment]
This will be fixed when we do some other unicode bugfixes -- it's due to line length calculation deep in the core and a bit of work to fix.

**Comment by plafosse** [comment]
This was fixed a while ago. Verified as of 1.1.1038
