### ISSUE TITLE
Variable hover should show stack frame offset in hex

### ISSUE THREAD

**Issue by alexrp** [Vector35/binaryninja-api#4420]
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4335-dev Personal ( 3a1746b)
- OS: Windows
- OS Version: 10.0.25375.1
- CPU Architecture: x64

**Bug Description:**
Hovering over a variable shows the stack frame offset in decimal. This is pretty weird and seems unintentional since stack frame offsets everywhere else in the UI are in hexadecimal.

**Screenshots:**
![image](https://github.com/Vector35/binaryninja-api/assets/44076/121546a9-5a75-4928-9017-a0d1f556e31c)

**Comment by plafosse** [comment]
Should be fixed in 3.5.4340
