### ISSUE TITLE
`binaryninjacore.h` is not valid C, despite seemingly trying to be

### ISSUE THREAD

**Issue by alexrp** [Vector35/binaryninja-api#4422]
The header has some `__cplusplus` checks, so it seems like it's trying to be valid C. But it actually isn't:

```text
... snip ...
../../api\binaryninjacore.h(1026,3): error : must use 'enum' tag to refer to type 'BNRegisterValueType'
../../api\binaryninjacore.h(1064,3): error : must use 'struct' tag to refer to type 'BNType'
... snip ...
```

So what's the deal there? Is it actually meant to be consumable from a C project or only C++?

(For context, it's a lot easier to cross-compile C code than C++ code, so for my plugin, I would much prefer to compile it as C.)

**Comment by xusheng6** [comment]
I think the goal is to make a valid in C, though there could be some issues in it.

However, the binja API is not really meant to be used in C. The C++ API handles reference counting, among other things, so it is much easier to use.

Could you please explain how/why are you cross-compiling?

**Comment by CouleeApps** [comment]
I would not recommend targeting the core header directly in C. It's more like an intermediate FFI boundary layer and less like a proper API. As a result, (as you have noticed) it's not actually valid C code but instead C++ that is close enough to C that our toolchains and scripts can parse it. It's also prone to a decent amount of ABI breaking/churn and the lifetime/nullability semantics of a lot of the functions are not clearly documented (unless you consider the C++/Python source as documentation). You can likely cross-compile the C++ correctly with some effort, but writing a plugin in straight C does not sound like a better experience.

**Comment by alexrp** [comment]
> Could you please explain how/why are you cross-compiling?

I'm making a loader plugin for .NET plugins (see #3166 for some background). I intend to support all the same platforms that BN supports. So I'm cross-compiling for all of them.

**Comment by xusheng6** [comment]
Are you writing the disassembler from scratch?

Coincidentally, I was thining about writing a .net binary view and disassembler on top of these projects: https://github.com/malwarefrank/dnfile and https://github.com/mandiant/dncil. They are all Python projects so they skip the build problem

**Comment by xusheng6** [comment]
> Are you writing the disassembler from scratch?
> 
> Coincidentally, I was thining about writing a .net binary view and disassembler on top of these projects: https://github.com/malwarefrank/dnfile and https://github.com/mandiant/dncil. They are all Python projects so they skip the build problem

Oh sorry, I misread your messages

**Comment by CouleeApps** [comment]
I think you've picked the one valid case for using the C api... Offhand, the list of things needed to make this valid C include:
- Turn all the `struct BNFoo;` forward declarations into `typedef struct BNFoo BNFoo;` typedefs
- Turn all the `enum BNFoo {...};` declarations into `typedef enum BNFoo {...} BNFoo;` typedefs
- (Possibly) Convert all the `BNFoo();` functions to `BNFoo(void);`
- Look into whether the macro attributes cause any problems

Likely should be easy to do, just need to Poke It Until There Are No More Errors

**Comment by alexrp** [comment]
> Oh sorry, I misread your messages

No worries. 🙂 Loading .NET assemblies into a BV would be an interesting feature, but not what I'm tackling here. (Though it *would* be significantly easier if you could write the CIL BV in C# since you could use the super robust [System.Reflection.Metadata](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.metadata) APIs... 🤔)

**Comment by alexrp** [comment]
> Likely should be easy to do, just need to Poke It Until There Are No More Errors

If you're on board with this, I guess I can send a PR to make it happen. Seems like a fairly straightforward search/replace job.

**Comment by CouleeApps** [comment]
Yeah, assuming there are no breaking changes (why would there be?) I would definitely accept it if you PR'd it

**Comment by alexrp** [comment]
Do you build any of the example plugins in your CI? Seems like it would be straightforward to add a simple "hello world"-esque example plugin that's built as C to maintain the header's C-ness.

PS: While I have you here, any chance you have an answer to https://github.com/Vector35/binaryninja-api/discussions/3166#discussioncomment-6178816?

**Comment by CouleeApps** [comment]
One of the CI stages is building all of the examples, and (rather amusingly) one of them uses the C api directly, but from within a C++ file. So we may be able to change that to a C file and verify it still compiles. 

As for that discussion, let me see...
