### ISSUE TITLE
Wrong byte count when lifting movsb/stosb to intrinsics and __builtin_memcpy

### ISSUE THREAD

**Issue by reversing-dev** [Vector35/binaryninja-api#4424]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4271 Personal, b7fd028d
- OS: windows
- OS Version: 11
- CPU Architecture: x86_64

**Bug Description:**
When populating a stack string, the memcpy gets the wrong count value after lifting to LLIL (which propagates to higher IL)

**Steps To Reproduce:**
Open the exe file in Binja.
Go to address : 0x140001088  

**Expected Behavior:**
0x21 should be the count. 

**Screenshots:**
![image](https://github.com/Vector35/binaryninja-api/assets/42991292/a4444c48-8b9b-4407-8f28-cf67476ec214)
![image](https://github.com/Vector35/binaryninja-api/assets/42991292/fa144ff0-3e39-48ae-b4b8-39d1547444f5)

**Additional Information:**

[main.zip](https://github.com/Vector35/binaryninja-api/files/11792669/main.zip)

**Comment by bpotchik** [comment]
Fixed in `3.5.4357-dev`.
