### ISSUE TITLE
Can't update current address from a background thread

### ISSUE THREAD

**Issue by snare** [Vector35/binaryninja-api#444]
Updating the `here` global from a thread other than the main GUI/Python REPL thread predictably does not update the view. I'm sure this will be affected by changes for #390.

**Comment by snare** [comment]
The reason I'm trying to do this is I wrote a plugin that spins off a background thread to watch a debugger (using [Voltron](https://github.com/snare/voltron)) and synchronise the selected instruction with the instruction pointer in the debugger.

**Comment by joshwatson** [comment]
`here` is a global, so you need to use the `global` keyword if you intend to change it outside of the global scope. The following worked for me in the GUI:

```
import threading
def a():
    global here
    here = 0x401160

b = threading.Thread(target=a)
b.start()
```

**Comment by snare** [comment]
Huh, I'm not sure what's going on. I was declaring it as a global. Your example works, this example does not:

```
import threading
import time

def a():
    global here
    while True:
        time.sleep(1)
        here = 0x100000d9f

b = threading.Thread(target=a)
b.start()
```

**Comment by snare** [comment]
This method works:

import threading
import time

```
def a():
    while True:
        time.sleep(1)
        bv.file.navigate(bv.file.view, 0x100000ea4)

b = threading.Thread(target=a)
b.start()
```
