### ISSUE TITLE
Can't set cpp data structure to function parameter

### ISSUE THREAD

**Issue by elbiazo** [Vector35/binaryninja-api#4443]
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4356-dev, d3c66087
- OS: macos
- OS Version: 13.4
- CPU Architecture: x86_64

**Bug Description:**
Can't set cpp data structure to function parameter. Example, hit `y` on parameter you are trying to change. Then try to set it as cpp string like `class string* name`. Tried different combination like `class std::string * name`, but it seems to not work either. I can set that data type to structure but not parameters.

**Comment by elbiazo** [comment]
Also when i define structure I had to do class string*name; instead of class std::string *name; when it is defined like this below
<img width="478" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/23147879/4178b974-143a-4d35-a4f7-cf0559173a05">

**Comment by alexrp** [comment]
Should work if you escape `std::string` with backticks in the Change Type dialog.

**Comment by elbiazo** [comment]
thanks that was it.

**Comment by elbiazo** [comment]
One edge case is in struct manager. you can create a type as class string name; then it will ask you if you wana make that class string * name.
