### ISSUE TITLE
Indicator for blocks with no outgoing edges in graph view

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#4450]
**What is the feature you'd like to have?**
Some indication that a block contains a `return`/`noreturn` in the flow graph.

**Is your feature request related to a problem?**
In large functions that have multiple returns, it's very difficult to see the terminating blocks at a glance.

**Are any alternative solutions acceptable?**
Possibly.

**Comment by CouleeApps** [comment]
As of 3.6.4632, this style has changed to drawing a border around entry/exit nodes, instead of just a weird line in the text.
<img width="447" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/711973/31714a97-3873-4fe7-b3eb-ea786dbe85d7">
