### ISSUE TITLE
String tokens now display xrefs to 0

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#4454]
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4369-dev
- OS: macOS
- OS Version: 13.4.1
- CPU Architecture: ARM64

**Bug Description:**
After the recent string changes, selecting any string will now display all xrefs to the constant 0x0 in the cross references list.

**Steps To Reproduce:**
1. Click any string token
2. Observe that the cross references list has _a lot_ of cross-references, most of which have absolutely nothing to do with your string token.

**Expected Behavior:**
Only cross references to the actual string token that I have selected should be shown.

**Screenshots:**
![image](https://github.com/Vector35/binaryninja/assets/607452/185bd2b1-0ec2-4d5a-bf87-40646c75d172)

**Comment by plafosse** [comment]
Fixed in 3.5.4370
