### ISSUE TITLE
Wrong function in the sticky header on initial click

### ISSUE THREAD

**Issue by jonomango** [Vector35/binaryninja-api#4458]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4271 Personal, b7fd028d
- OS: windows
- OS Version: 10
- CPU Architecture: x86_64

**Bug Description:**
When double-clicking on a function, the initial function in the "sticky header" (not sure what to call this) is the wrong function. After scrolling, the function displayed will fix itself to the correct value.

**Steps To Reproduce:**
1. Double-click on any function, in any of the views.

**Expected Behavior:**
The UI should display the correct function.

**Screenshots:**
Before double clicking on `sub_407b40` (note that `sub_407b00` is properly shown):
![image](https://github.com/Vector35/binaryninja-api/assets/26609800/bf69280e-e7f1-48cb-83a2-081fae7f81a7)
After double clicking on `sub_407b40`:
![image](https://github.com/Vector35/binaryninja-api/assets/26609800/a22caf72-ca97-48fe-9779-7e0a4343107a)
After scrolling down then up again:
![image](https://github.com/Vector35/binaryninja-api/assets/26609800/dad5ba59-4bc4-4a91-944b-9d04051c8629)

**Comment by negasora** [comment]
Fixed in `3.5.4375-dev`
