### ISSUE TITLE
Sticky header function doesn't update correctly with arrow keys, only scrollbar.

### ISSUE THREAD

**Issue by jonomango** [Vector35/binaryninja-api#4459]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4271 Personal, b7fd028d
- OS: windows
- OS Version: 10
- CPU Architecture: x86_64

**Bug Description:**
When scrolling up and down with the arrow keys, the function in the sticky header of the UI doesn't update correctly. Only using the scrollbar/scrollwheel seems to get the correct results.

**Steps To Reproduce:**
1. Scroll up or down in any of the views with your up and down arrow keys.

**Expected Behavior:**
The UI should display the correct function.

**Screenshots:**
The wrong function is shown after scrolling up with the arrow keys:
![image](https://github.com/Vector35/binaryninja-api/assets/26609800/07df7b27-620b-411b-a462-9bf093e42dcf)

**Additional Information:**
The function in the sticky header will update occasionally when using the arrow keys, at what seems to be random intervals.

**Comment by negasora** [comment]
Fixed in `3.5.4375-dev`
