### ISSUE TITLE
Option to retain file extension on save

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/binaryninja-api#4461]
By default, if you open a file called `foo.bar`, then try to save a BNDB, the default name is `foo.bndb`. As you can see, Binary Ninja interprets the `.bar` as a file extension and then removes it, replacing it with `.bndb`.

Some common files use file extensions as "tags" rather than "extensions". For example, a directory might contain the following files:

```
foo.release
foo.debug
foo.asan
```

In this case, Binary Ninja would suggest the same database name, `foo.bndb` for all of these files.

It would be nice if there were a setting such that Binary Ninja would retain the original extension and just append the `.bndb` suffix, i.e. a "always append" setting. Such that the default-suggested name for these files would be `foo.release.bndb`, etc.

**Comment by fuzyll** [comment]
In my opinion, this shouldn't be an option, but should be default behavior. So, I'm considering this a duplicate of #3312.
