### ISSUE TITLE
Questionable comment placement near `else` block

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/binaryninja-api#4464]
I set a comment on the highlighted line in the picture below. The comment is placed in between the "else" and the braces. I would expect the comment to be placed inside of the braces, since I am trying to annotate the selected line in particular.

From what I can tell, this **only** happens with `else` blocks.

![image](https://github.com/Vector35/binaryninja-api/assets/41548458/5e618c52-def7-49be-9b96-acb9307c35a6)

Binary Ninja 3.5.4369-dev

**Comment by xusheng6** [comment]
Related to: #708

**Comment by 0xdevalias** [comment]
Possibly also:

- https://github.com/Vector35/binaryninja-api/issues/2728

**Comment by psifertex** [comment]
I actually don't think this particular issue is valid as described anymore. Testing works fine so it's either binary specific, or just a specific instance of #2728:
<img width="645" alt="Screenshot 2024-06-11 at 10 29 12" src="https://github.com/Vector35/binaryninja-api/assets/140215/23d59bf6-9b05-47ff-8330-13ddaf803c01">

**Comment by 0xdevalias** [comment]
> I actually don't think this particular issue is valid as described anymore.

@psifertex Your screenshot shows what looks like a *IL level view, whereas the original screenshot looks as though it might be a Pseudo C-view. Just want to confirm, have you tested that it still doesn't seem to apply in the Pseudo-C view as well before closing this?
