### ISSUE TITLE
New `.extern` section, apparently duplicate of `.synthetic_builtins`, has started appearing in older BNDBs

### ISSUE THREAD

**Issue by alexrp** [Vector35/binaryninja-api#4467]
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4375-dev Personal (30858726)
- OS: Windows
- OS Version: 10.0.25375.1
- CPU Architecture: x64

**Bug Description:**
Not sure if this is expected, but when opening older BNDBs in the latest BN build, a new `.extern` section has started appearing, seemingly a duplicate of `.synthetic_builtins`.

**Steps To Reproduce:**
Open an older BNDB (not sure how old) in the latest BN build. ~~Newly-created BNDBs don't have this `.extern` section.~~ They do, but not with the builtins.

**Expected Behavior:**
No `.extern` section.

**Screenshots:**
![image](https://github.com/Vector35/binaryninja-api/assets/44076/1e7f61c8-06bc-465a-89ad-da33cfad182b)

**Comment by alexrp** [comment]
Apparently this is a new synthetic section that's used for IAT entries? Still seems odd that it turned into this in an older BNDB. 🤔

**Comment by bpotchik** [comment]
This is probably fixed in `3.5.4507`. Please reference #4324 for steps to resolve and/or clean up the existing BNDB.
