### ISSUE TITLE
Some functions are marked as import thunks despite not being so

### ISSUE THREAD

**Issue by alexrp** [Vector35/binaryninja-api#4469]
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4377-dev Personal (24869472)
- OS: Windows
- OS Version: 10.0.25375.1
- CPU Architecture: x64

**Bug Description:**
Some functions are being marked as import thunks despite clearly doing more than that.

No amount of messing around with symbols and data vars in the API seems to make BN stop marking them as such.

**Steps To Reproduce:**
1. Open [this BNDB](https://drive.google.com/file/d/1mG7qAnWlI1MxKfoWPcHRgnIT16JAVo7F/view?usp=sharing).
2. Navigate to these functions: `Sleep`, `InitializeSListHead`, `RaiseException`, `SetUnhandledExceptionFilter`

**Expected Behavior:**
These 4 functions should not be marked as import thunks.

**Screenshots:**
![image](https://github.com/Vector35/binaryninja-api/assets/44076/1201a8be-08d8-4890-ac92-040e5d352fe3)
![image](https://github.com/Vector35/binaryninja-api/assets/44076/b277b6d0-9b68-4318-b0f8-cdd981da64e0)
![image](https://github.com/Vector35/binaryninja-api/assets/44076/9cf6a9f8-65b5-4a7a-abed-06f3868d399f)
![image](https://github.com/Vector35/binaryninja-api/assets/44076/87d3f71c-6df9-4112-894b-343cf3df681d)

**Comment by plafosse** [comment]
This I assume is one of our function recognizer being overly broad.

**Comment by plafosse** [comment]
Thanks for the report this should be fixed in 3.5.4391

**Comment by alexrp** [comment]
@plafosse maybe I'm missing something, but this doesn't appear to be fixed on my end. I updated to `3.5.4392-dev Personal (f9a3e2ad)` and navigated to the misidentified `InitializeSListHead`. I first undefined the function and then the `kernel32:InitializeSListHead` variable. Then I recreated the function, and it's once again identified as `InitializeSListHead` and marked as a library function. The same happens for `SetUnhandledExceptionFilter` and `Sleep`. It's a bit harder to tell with `RaiseException` because undefining it causes BN to consider it as an extension of `FOutputDeviceWindowsError::method_001` (`0x7ff69a9399d0`).

**Comment by plafosse** [comment]
For me it looks like this:
<img width="551" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/10556585/c5ade69e-3761-467b-a3c3-18994d803ffc">

Could you try re-opening the original binary?

**Comment by plafosse** [comment]
Also for SetUnhandledExceptionFilter all the calls to it seem to be un-named
<img width="620" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/10556585/3687d082-62b3-4c9b-8826-b9f838a81813">
Same with InitializeSListHead
<img width="567" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/10556585/3b3b159a-eca7-4cfa-99c6-8e3e2e09de35">
I really believe I fixed the underlying issue here as I had to update our unit tests to remove one of the false positives that was showing up.

**Comment by alexrp** [comment]
> Could you try re-opening the original binary?

Hmm, it does seem to work as it should when creating a new BNDB.

Is there any way to fix it for my existing BNDB? At this time, `Import From BNDB` doesn't carry over enough of my analysis progress for it to be a realistic option.

**Comment by alexrp** [comment]
> Is there any way to fix it for my existing BNDB?

After messing around with the API a bit, I managed to get rid of the stale `ImportedFunctionSymbol`s for good:

![image](https://github.com/Vector35/binaryninja-api/assets/44076/8b7c3241-05b1-4b32-a31d-658f0a9df188)

**Comment by plafosse** [comment]
ok great!
