### ISSUE TITLE
Remove opcodes from when editing assembly

### ISSUE THREAD

**Issue by bambu** [Vector35/binaryninja-api#447]
Editing a assembly with `E` when opcodes are displayed leaves the opcode as text that can be edited (the address disappears when in line edit mode). This opcode should not be displayed at all since editing the assembly text and not removing the opcodes fails with the following error. 

<img width="425" alt="screen shot 2016-08-31 at 9 33 36 pm" src="https://cloud.githubusercontent.com/assets/564972/18152277/ad8e9bae-6fc2-11e6-8262-2137894b7a1a.png">

**Comment by psifertex** [comment]
Fixed in dev.
