### ISSUE TITLE
Clicking Xref when in strings view does not take you to xref location

### ISSUE THREAD

**Issue by bambu** [Vector35/binaryninja-api#448]
Reproducing:
1. Go to strings view and select a string that has an Xref.
2. Double click on the Xref.

The expected behavior would be to view the graph that is previewed in the tool tip. What actually happens is that you are taken to a different position in the strings view.

**Comment by Manouchehri** [comment]
Yep, I can reproduce this as well. https://www.youtube.com/watch?v=rQA_Wx81yyc

**Comment by plafosse** [comment]
fixed in dev
