### ISSUE TITLE
Create Array "Item Count" Mishandles Unprefixed Hex Input

### ISSUE THREAD

**Issue by w1282** [Vector35/binaryninja-api#4480]
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4384-dev
- OS: Windows
- OS Version: 11
- CPU Architecture: x64

**Bug Description:**
When creating an array through the "Create Array" dialog, binary ninja attempts to prepopulate "Item Count" with a sane value based on the selected range and size of the initial type. This pre-populated value is presented as hex but parsed as decimal, resulting in an error when the value contains non-decimal characters and results in the wrong number of items in the array when the value contains only decimal values (e.g. 0x10 items selected results in an array of size 10, not 16).

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Create an `int32_t` type somewhere
2. Select that value and the following 15 integers worth of memory and trigger the 'Create Array' dialogue
3. Observe that the 'Item Count' has been prepopulated with "10"
4. 'Create' the array and observe that only 10 items have been added
5. Repeat with 15 items selected and observe that 'Create' fails when attempting to parse an Item Count of "f"

**Expected Behavior:**
The value is either always populated as decimal, or always populated as hex with the 0x prefix

**Comment by psifertex** [comment]
Resolved in builds > 4387
