### ISSUE TITLE
`analysis.types.paddingThreshold` is not respected

### ISSUE THREAD

**Issue by alexrp** [Vector35/binaryninja-api#4485]
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4387-dev Personal (71942341)
- OS: Windows
- OS Version: 10.0.25375.1
- CPU Architecture: x64

**Bug Description:**
Compilers sometimes like to generate weird code when initializing nested structures:

![image](https://github.com/Vector35/binaryninja-api/assets/44076/bafebccf-e06f-41e9-8847-dd7ff6ac08e0)

There's a separate argument to be made that BN should handle this better, but the more annoying issue for me here is the rendering of the types involved:

![image](https://github.com/Vector35/binaryninja-api/assets/44076/8332b63e-2461-498e-9318-00e475dede0f)
![image](https://github.com/Vector35/binaryninja-api/assets/44076/97398584-edc5-4582-a2b0-ba544c02efa3)

The fact that the whole `S1DataCacheBucket` structure is rendered this way makes it much harder to add fields at specific offsets by hand, which is particularly important in this case because of the weird offset pointers in the initialization code confusing BN's analysis.

**Steps To Reproduce:**
1. Grab [this BNDB](https://drive.google.com/file/d/1mLCLJDAw_iA4oyaZi6dnCFAuo1iDC4Ol/view?usp=sharing).
2. Navigate to `0x7ff69baff3a0`.

**Expected Behavior:**
There should be no `__padding` fields rendered in the Types view.

**Comment by xusheng6** [comment]
Our code is correct for this case

**Comment by alexrp** [comment]
> The problem is that you have somehow (maybe unknowingly) changed the value of `analysis.types.paddingThreshold` for the binary.

That was exactly it. Changing it on the `Resource` level fixed the issue.

It's strange though. I don't think I've ever used the `Resource` tab in the settings UI... not sure how that crept in there.
