### ISSUE TITLE
Calculate ELF PT_DYNAMIC p_offset from its p_vaddr

### ISSUE THREAD

**Issue by michalmalik** [Vector35/binaryninja-api#449]
Hi,

I am using the BinaryNinja demo version 1.0.14 (Build ID 4f54d53d). 

TL;DR: p_offset field of the PT_DYNAMIC segment in ELF files is irrelevant (it can have arbitrary values, the file will still run fine). The file offset of the PT_DYNAMIC segment should be calculated from its virtual address (p_vaddr). 

Sorry for the self-promotion, but I wrote about it here: http://michalmalik.github.io/elf-dynamic-segment-struggles if you are interested.

**Comment by plafosse** [comment]
Any chance you can share a binary that demonstrates this issue?

**Comment by bpotchik** [comment]
I believe this has been fixed for a while now.
