### ISSUE TITLE
Tags UI has various bugs and performance issues

### ISSUE THREAD

**Issue by alexrp** [Vector35/binaryninja-api#4490]
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4390-dev Personal (d58232bc)
- OS: Windows
- OS Version: 10.0.25375.1
- CPU Architecture: x64

**Bug Description:**
Lately, I've been running into various bugs and performance issues with the tags UI. They render it basically unusable until I restart BN.

1. Despite what's stated in #4208, I do sometimes have this sideways scrolling issue.
2. Sometimes when I try to change the names of tags, anything I type just immediately gets replaced with the original name (e.g. `New Tag`).
3. When clicking the address of a tag, BN sometimes just hangs for a while, and then it seems to be a coin toss whether it actually navigates there afterwards.

Unfortunately, these issues all seem very random in nature. The tags UI might work fine for 10-15 minutes and then suddenly break in any combination of the above ways.

In case it matters, it happens when I'm working on [this BNDB](https://drive.google.com/file/d/1mRX0JMkcleAZWVVl-DQcZICbllsVIibK/view?usp=sharing).

**Comment by alexrp** [comment]
Additionally, scrolling sideways with the scrollbar or mouse wheel just doesn't work; the view just snaps back to where it was immediately. This reproduces reliably.

**Comment by alexrp** [comment]
One way to trigger these issues seems to be to use `Add Tag...` while the sidebar is focused on anything other than the tags UI, confirming the tag type, and then switching to the tags UI to fill in the tag name.

**Comment by alexrp** [comment]
Updates:

* I can no longer reproduce the horizontal scrolling and renaming issues. But due to the random nature of those, this could just be luck. Not sure yet.
* The hang when navigating to a tag still exists and is by far the most disruptive issue with the tags UI for me.

**Comment by bpotchik** [comment]
Should be resolved for the most part in `4.3.6462-dev`. I've got another update coming after this which should improve things further. But as of right now, the UI shouldn't be blocking anymore.
