### ISSUE TITLE
Creating a tag by calling BinaryView.add_tag does not update the UI

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#4495]
If I add a tag by calling https://api.binary.ninja/binaryninja.binaryview-module.html#binaryninja.binaryview.BinaryView.add_tag, the tag is added correctly, but the UI is not updated and the tag is not displayed. Triggering a UI update fixes the problem.

Doing the same thing with https://api.binary.ninja/binaryninja.function-module.html#binaryninja.function.Function.add_tag works fine

**Comment by xusheng6** [comment]
I just tested that the problem only occurs when the address is part of a function. If it is on a data, the UI is also updated properly

**Comment by river-li** [comment]
The tags are displayed correctly now. Not sure when this got fixed.
