### ISSUE TITLE
binja enforce the usage of the return value, although it was discarded

### ISSUE THREAD

**Issue by nitrogar** [Vector35/binaryninja-api#4509]
**Version and Platform (required):**
- Binary Ninja Version: [e.g. 3.2.4000-dev] (if version is stable, please also test the latest development build via the "Update Channel" option)
- OS: manjaro

**Bug Description:**
while reversing windows x86 binary i noticed that, binja enforce the usage of return value as shown in the pictures below

![binja_fail](https://github.com/Vector35/binaryninja-api/assets/53944555/fcc64e54-bf12-4d46-b959-e22c2bdb73d8)
![binja_fail_2](https://github.com/Vector35/binaryninja-api/assets/53944555/c38a7db6-0a10-42ed-af2d-f81740af87e5)
![binja_fail3](https://github.com/Vector35/binaryninja-api/assets/53944555/350b26cb-5ba3-421a-85bb-2fe0463d2f94)

eax was discarded but binja enforce it which corrupt the rest of the analysis.

**Expected Behavior:**
after NOPing the function call, the analysis become correct as shown.
![binja_correct](https://github.com/Vector35/binaryninja-api/assets/53944555/6557e514-0e37-4f1f-b473-97ffcd4ffd6d)

**Additional Information:**
Sorry i cant provide the binary ;)

**Comment by xusheng6** [comment]
Related to https://github.com/Vector35/binaryninja-api/issues/4511.

The problem is BN thinks the function memcpy uses register `ebp` as its return value, which is wrong. Can you try unchekcing the `ebp` checkbox in the `Cloberred Registers` list in the `Edit Function Properties` dialog of the memcpy function?

**Comment by nitrogar** [comment]
thanks, after removing ebp from the clobbered registers the analysis was corrected.
