### ISSUE TITLE
clicking functions list items doesn't do anything in linearView

### ISSUE THREAD

**Issue by lucasduffey** [Vector35/binaryninja-api#451]
the first 40 functions work, but clicking anything after it while in linear view doesn't work. Nothing in the logs

I've only seen this in my Dex plugin. Doesn't apply to ELF or PE files

**channel:** release
**OS:** ubuntu 16.04 LTS

**Comment by lucasduffey** [comment]
this doesn't apply to ELF files

**Comment by psifertex** [comment]
Can you reproduce it in any of the built-in views? Sounds like a bug in the plugin otherwise...

**Comment by psifertex** [comment]
Can you maybe try with `binaryninja -d -e` and see if verbose debug logs include any useful info?

**Comment by lucasduffey** [comment]
nothing in the verbose debug logs

**Comment by psifertex** [comment]
Yeah, that is odd. I can't replicate it on any of the built-in views, and I even tried an NES rom and it worked fine so it's not related to it being a python architecture/view plugin pair. Don't have time to debug the dex stuff now unfortunately, maybe another comparison between the NES and yours would show something different?

**Comment by lucasduffey** [comment]
closing for now until I can find hard evidence it's binja's problem
