### ISSUE TITLE
Integer literals in MLIL+ occasionally lose their '0x' prefix

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/binaryninja-api#4517]
As you can see, the integer literals in HLIL on the left are missing the '0x' prefix that they have in the disassembly on the right.

Originally, I suspected that integer literals might be limited to 16 characters by the call to `sprintf` when formatting them, but that's not the case and you can see inside of the `if` statement in the screenshot that isn't the case.

Furthermore, it seems like changing the type of the `ptr` argument from `void*` causes the token inside of the call to `swift_bridgeObjectRelease` to render correctly, but not the other pictured tokens starting with `d0`.

<img width="1198" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/41548458/073a1aea-096f-4f7e-b3b3-b22ac37f17fc">

**Comment by xusheng6** [comment]
@jonpalmisc Could you please share a binary that reproduces this?

**Comment by jonpalmisc** [comment]
Here's the binary. Navigate to `1000071ac` and set the type for `_swift_bridgeObjectRelease` to `void _swift_bridgeObjectRelease(void *)`. You should then be able to observe the bug.

[lockdownmoded.not.a.txt](https://github.com/Vector35/binaryninja-api/files/12186139/lockdownmoded.not.a.txt)

**Comment by jonpalmisc** [comment]
You should also be able to observe this when changing the type of `x0_15` (set in each switch case) to `void *`.

**Comment by xusheng6** [comment]
I can reproduce this. This should be a relatively easy fix
