### ISSUE TITLE
Type library x86/libgcc_s.so.1.bntl reports an arch of MIPS

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#4522]
The `x86/libgcc_s.so.1.bntl ` reports an arch of MIPS. I believe this is a copy-paste error, since the file is identical to `mips32/libgcc_s.so.1.bntl`

**Comment by xusheng6** [comment]
I noticed this while working with the demo version. Demo version does not have MIPS arch, so when I open an Windows x86 file, I get this error message:

```
Unable to deserialize type library for arch 'mips32'
```

**Comment by plafosse** [comment]
Fixed in 4.1.5228
