### ISSUE TITLE
Can  i split python console to another window?

### ISSUE THREAD

**Issue by helloobaby** [Vector35/binaryninja-api#4523]
As title.
I think BinaryNinja plugin system is better than other static analyse tool, i hope it can work better

**Comment by xusheng6** [comment]
Not as I know if. But you can use the snippet plugin if you are writing a long script. https://github.com/Vector35/snippets

**Comment by helloobaby** [comment]
Good plugin

**Comment by psifertex** [comment]
For future reference, please use [Discussions](https://github.com/Vector35/binaryninja-api/discussions) instead of issues for questions. Thanks!
