### ISSUE TITLE
Signature matcher false positive

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#4526]
While working with this binary: https://crackmes.one/crackme/64a071de33c5d460c17f1f5f. The signature matcher thinks the function at the entry point is `??$get_epsilon_imp@OU?$policy@U?$promote_float@$0A@@policies@math@boost@@U?$promote_double@$0A@@234@Udefault_policy@234@U6234@U6234@U6234@U6234@U6234@U6234@U6234@U6234@U6234@U6234@@policies@math@boost@@@detail@policies@math@boost@@YAOAEBU?$bool_@$00@mpl@3@@Z` while it is not:

![Screenshot 2023-07-28 at 2 44 52 PM](https://github.com/Vector35/binaryninja-api/assets/94503187/91671201-bd79-45a0-8ff9-0dc180a2ff64)

**Comment by plafosse** [comment]
Closing as duplicate: https://github.com/Vector35/binaryninja-api/issues/3773
