### ISSUE TITLE
Analyzing hangs

### ISSUE THREAD

**Issue by cstoitner** [Vector35/binaryninja-api#453]
Binary Ninja takes forever to analyze the [attached file](https://github.com/Vector35/binaryninja-api/files/455395/DX_Module.zip). It gets stuck at "Analyzing 198/799" and the graph view is unusable, printing "Loading..." when switching to a different function. I have let it run for about an hour without progress.

Im using version 1.0.14 demo.

**Comment by plafosse** [comment]
I can confirm that this fails on the latest development build as well, thanks for the report

**Comment by D0ntPanic** [comment]
It appears to be trying to disassemble a large block of zeros as a function. There is a symbol for the address, so it is likely mistaking a data symbol for a function symbol. The latest dev build does not hang during analysis but does have some UI responsiveness issues when scrolling though the linear view.

**Comment by D0ntPanic** [comment]
Fixed in dev, there was an error in the PE parser
