### ISSUE TITLE
Cannot create, update, or delete components in new symbol view

### ISSUE THREAD

**Issue by BrokenR3C0RD** [Vector35/binaryninja-api#4538]
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4412-dev (have been experiencing this for a few weeks though, I've reproduced on 4271-stable and 4388-dev)
- OS: Arch Linux
- OS Version: Kernel 6.4.6-zen
- CPU Architecture: x64

**Bug Description:**
The new symbol view fails to reflect CUD operations on components. The list is only refreshed if the project is reloaded.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open a binary with the new symbol view enabled.
2. Right click on a function in the symbol view and try to create a component.
3. Note that nothing appears to happen

**Expected Behavior:**
A new component should be created, with the default name "Component", and the ability to rename before it is saved

**Additional Information:**
Sometimes components will randomly start working for a short period, but it always stops working after a certain period of time/certain numbers of changes to a binary.
I've tested this on a few different binaries, for a few different architectures, so I don't think this is isolated on my machine at least.

Thought my neofetch might be helpful to provide slightly more information on my configuration:
![image](https://github.com/Vector35/binaryninja-api/assets/7197791/b1181c96-e4a2-46eb-a9df-79c27a1ac5ec)

**Comment by bpotchik** [comment]
Fixed in `3.6.4660-dev`.
