### ISSUE TITLE
Add Setting for Line-Wrapping Comments

### ISSUE THREAD

**Issue by kristopax** [Vector35/binaryninja-api#4539]
**What is the feature you'd like to have?**
I would like to have a setting that sets the size for line-wrapping comments in both linear and graph view. The setting should have a sane default value. One of the values should be used to indicate when the user does not want line-wrapping.

**Is your feature request related to a problem?**
Currently, in linear view, comments are line-wrapped at the width of the view frame. When the user expands the window width to a very large size, very long comments will extend to the width of the window.  It would be nice to apply a comment line-wrap setting for better readability.

Also, graph view does not apply any line wrapping for comments.  Therefore, when a comment is very long, the width of the graph node in which the comment occurs becomes very large.

**Additional Information:**
Screen shot of linear view:
<img width="1321" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/79866371/4d2609b5-8522-4959-88b8-0b6a9035df61">

Screen shot of graph view:
<img width="1400" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/79866371/375d4d66-5eaf-4586-b2f4-f2c5ea9c36c4">

**Comment by xusheng6** [comment]
The settings is called `ui.view.common.commentWidth`

**Comment by kristopax** [comment]
The Settings UI does not allow the user to specify a commentWidth of any value other than 2 digits. For example, comment widths of 9 and 100 are not permitted.  At a minimum, I think we should allow the user to at least set 3 digits.

**Comment by xusheng6** [comment]
Also, currently there is no value to indicate no line-wrapping

**Comment by psifertex** [comment]
`ui.view.common.commentWidth` is the setting
