### ISSUE TITLE
"Create All Members For Structure" overrides inherited fields

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#4540]
*From another customer, via email.*

**Version and Platform (required):**
- Binary Ninja Version: 3.5.4409-dev Personal ( 4eafbd3)
- OS: macOS Version 13.4.1 (c) (Build 22F770820d)

**Bug Description:**
Not sure if it's an expected behavior. See the screenshots. I had a struct with `__base()` that is inheriting a bunch of fields, and I wanted to create the fields that don't already exist (the `__offset*` ones). Instead of only creating the fields for the `__offset*`, it also overrode the fields that already existed.

**Screenshots:**
<img width="1034" alt="Screenshot 2023-07-30 at 10 02 43" src="https://github.com/Vector35/binaryninja-api/assets/607452/11504171-f027-45cc-a655-fa88910c11df">

<img width="985" alt="Screenshot 2023-07-30 at 10 02 57" src="https://github.com/Vector35/binaryninja-api/assets/607452/8ffd510d-5668-4191-85c4-1f5cf92fda49">

**Comment by xusheng6** [comment]
[test_inherited_struct.bndb.zip](https://github.com/Vector35/binaryninja-api/files/12237892/test_inherited_struct.bndb.zip)

![Screenshot 2023-08-02 at 4 33 14 PM](https://github.com/Vector35/binaryninja-api/assets/94503187/c325058b-9abd-42b5-81bc-2b9e73ef4061)


![Screenshot 2023-08-02 at 4 32 11 PM](https://github.com/Vector35/binaryninja-api/assets/94503187/5e22ae7a-7625-4f07-82ad-592a7c1a398b)

I created a database that can be used to reproduce this issue. Press `S` on `var_38` and we can see all of the fields get redefined, including those inherited from the base class. 

![Screenshot 2023-08-02 at 4 32 27 PM](https://github.com/Vector35/binaryninja-api/assets/94503187/ee409909-e5fd-446b-9905-d48fb9ddf78c)
