### ISSUE TITLE
improved stack structure aliasing

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#4544]
This is believed to be a major component of many reports of Dead Code Elimination problems, remains to be seen once this fix is implemented how many other related issues are fixed.

**Comment by CouleeApps** [comment]
Relevant: #2219 #773 possibly #3049

**Comment by D0ntPanic** [comment]
Added in build 4469. Uses much more conservative constant propagation for stack variables when there is stack variable aliasing present. Dead code elimination should be much improved in functions with stack structures, though in some cases constant propagation through stack variables will no longer occur.
