### ISSUE TITLE
Add API for list of callers and called functions

### ISSUE THREAD

**Issue by D0ntPanic** [Vector35/binaryninja-api#456]
Need to add APIs to the function object to get the list of callers, and the list of functions called. This would assist in the construction of a function dependency graph. Also, it will allow us to automatically queue analysis in the priority queue for all functions that the function being viewed calls, which will significantly improve looking through a binary while it is still being analyzed (as calls to imports will be immediately resolved and displayed using the correct name).

**Comment by psifertex** [comment]
This is implemented as `.callees` and `.callers` on functions in the Python API and has core APIs on the BinaryView.
