### ISSUE TITLE
ARM64 assembler ignores address of assembled instruction.

### ISSUE THREAD

**Issue by lwerdna** [Vector35/binaryninja-api#4563]
**Version and Platform (required):**
3.5

**Bug Description:**
The assembler is ignore the address at which the assembling should occur.

**Steps To Reproduce:**
1. Run BinaryNinja
2. File -> New Binary Data
3. Enter bytes: 1f 20 03 d5 1f 20 03 d5 1f 20 03 d5 1f 20 03 d5 (four nop instructions)
4. Create aarch64 function at address 0 (hotkey "P")
5. With cursor at address 0, Edit -> Assemble, then "bl 0x1000" it emits encoding 0x00040094 
6. With cursor at address 4, Edit -> Assemble, then "bl 0x1000" it emits encoding 0x00040094 

![image](https://github.com/Vector35/binaryninja-api/assets/474191/771c8ab1-01ff-4a63-a0f3-9f4b8948f7b6)

**Expected Behavior:**
The assembled instruction is PC-relative, so it should not have the same encoding. The second instruction at address 4 should be encoded 0xff030094.

**Comment by lwerdna** [comment]
Thank you for the bug report. Unfortunately this is a limitation of LLVM which we are using for many of our assemblers.

The recommended workaround is to install and use the keypatch plugin from the plugin manager:

![Screen Shot 2023-08-20 at 4 58 17 PM](https://github.com/Vector35/binaryninja-api/assets/474191/a64f4e40-ee44-402d-ac33-cc913913b6f1)

![assemble-plugin](https://github.com/Vector35/binaryninja-api/assets/474191/8a1ab80d-a52a-4cfb-ad75-1e3981a33d0f)

In the future we will release a more official plugin.

**Comment by BrentDaMage** [comment]
Dude are you okay?

**Comment by psifertex** [comment]
We use public issues to relate the state of internal discussions on features and fixes quite frequently. It's not uncommon to see one Vector35 person post an issue and end up resolving it differently after we've talked about it in more detail internally. 

In this case I think Andrew was posting the issue on behalf of someone else originally who he is thanking which does sound a bit strange without that context. :-)

**Comment by lwerdna** [comment]
> Dude are you okay?

Hah while I do sometimes talk to myself, what's happening is someone will briefly report a problem on slack, and I'll promote it to an official github issue and give them the link so they can track its status. I assume they're reading it, or will read it when it's closed. So yes, as psifertex explained, this is an issue posted on behalf of someone else.
