### ISSUE TITLE
ARM64 R_AARCH64_CALL26 relocation breaks on rebase.

### ISSUE THREAD

**Issue by lwerdna** [Vector35/binaryninja-api#4565]
**Version and Platform (required):**
3.5

**Bug Description:**
When you rebase this binary, `main()`'s call to `myAdd()` is lost.

![image](https://github.com/Vector35/binaryninja-api/assets/474191/b532c6ac-a4d6-45d4-ae36-4b3a2775d039)

**Steps To Reproduce:**
Open this file:  [test.o.zip](https://github.com/Vector35/binaryninja-api/files/12354611/test.o.zip)

Observe `main()` is calling `myAdd()`:

```
00000048  eeffff97   bl      myAdd
```
Note this call is targetted by a relocation:

![image](https://github.com/Vector35/binaryninja-api/assets/474191/8133c54c-c96e-4de4-94d7-4f9a3d554b77)

Symbol index 6 holds the struct for `MyAdd()`. Now rebase the binary to 0x4000 and the call is destroyed:

![image](https://github.com/Vector35/binaryninja-api/assets/474191/c0953d95-7fa2-4d6d-b006-b0de98a93ead)

Looking at the hex view, those bytes that comprised the `bl` got destroyed:

![image](https://github.com/Vector35/binaryninja-api/assets/474191/50f5f0fb-1e7b-4615-a38a-83cc1f6497f4)

**Expected Behavior:**
The relocation should work correctly. The call should survive rebasing.

**Comment by bpotchik** [comment]
Fixed in `3.5.4489-dev`
