### ISSUE TITLE
View font does not fallback to default if missing

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/binaryninja-api#4566]
If you configure your view font to a font that isn't installed (or in my case, copy your settings to a new machine without the configured font), the view font becomes the default system font and comedy ensues. The font should fall back to the default mono font if the configured font is missing.

<img width="561" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/41548458/b4ff4c88-f4f6-4d59-9ebc-057660dc6bd1">

Binary Ninja 3.4.4271 (Stable)

**Comment by fuzyll** [comment]
Reopening this as it appears I _did_ introduce a problem where certain fonts can no longer be set as per the issue above.
