### ISSUE TITLE
View jumps around seemingly at random when renaming or changing type

### ISSUE THREAD

**Issue by alexrp** [Vector35/binaryninja-api#4567]
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4455-dev Personal (56505582)
- OS: Windows
- OS Version: 10.0.23521.1000
- CPU Architecture: x64

**Bug Description:**
On this particular BNDB, anytime I rename something or change the type of something, the view jumps to some seemingly random point.

This is *super disruptive*.

**Steps To Reproduce:**
1. Grab [this](https://drive.google.com/file/d/100NkO7AJTZQ35Rh5b7A8nJxBJ3lBovHI/view?usp=sharing).
2. Rename or change type on basically anything.

**Expected Behavior:**
No random jumping around.

**Comment by fuzyll** [comment]
Hey, thanks, one of our devs just noticed this as well in the context of making comments in a binary. Out of curiosity, what version were you on previously? Do you remember? Hoping this was recent and we can get a good bisect to figure it out quickly.

**Comment by alexrp** [comment]
Unfortunately I don't have an exact version. But I want to say this wasn't happening some 10-20 builds ago? 🤔

**Comment by CouleeApps** [comment]
Looks like this was caused by the linear view stuff I was working on yesterday as part of #4560. Should be fixed in the next build
