### ISSUE TITLE
Why this branch cannot be determined

### ISSUE THREAD

**Issue by helloobaby** [Vector35/binaryninja-api#4568]
![image](https://github.com/Vector35/binaryninja-api/assets/84119280/1d6f330c-2aef-49fd-9267-4f9225cf6202)
![image](https://github.com/Vector35/binaryninja-api/assets/84119280/5eb3d75d-86c9-4cfe-bd9a-e88814cb79ed)

In fact, all similar branches cannot be determined

**Comment by plafosse** [comment]
its difficult to tell without seeing the full function and the MLIL - SSA form
