### ISSUE TITLE
Using arrow key or tab key at the "Save" / "Don't Save" dialog always choose "Save"

### ISSUE THREAD

**Issue by lwerdna** [Vector35/binaryninja-api#4571]
**Version and Platform (required):**
3.5

**Bug Description:**
At the quit screen, if you arrow over or tab over to the "Don't Save" it will select both buttons and hitting enter will prompt you for a filename to save to.

![ui-bug-two-buttons-selected-on-quit](https://github.com/Vector35/binaryninja-api/assets/474191/5de8efa2-74fb-418f-aa01-53d2fdcf9d29)

**Steps To Reproduce:**
Open any binary, made an edit, then quit. At the "Save" / "Don't Save" dialog, arrow over or tab over to "Don't Save" and hit enter.

**Expected Behavior:**
It should only select the "Don't Save" button and upon hitting enter, it should not prompt you for a filename to save to.

**Comment by psifertex** [comment]
Related internal commit: https://github.com/Vector35/binaryninja/commit/48b510b36ae3626cb325330772fcf433192c54e8

**Comment by psifertex** [comment]
This is actually expected behavior -- using "enter" on this dialog is actually defined in QT as always accepting save. Use `space` to instead select the other element.

Demonstration using quick QT hello world:

https://gist.github.com/psifertex/b52e8c5df590f9ec271319ac2bef78ca
