### ISSUE TITLE
switch case dereferences jump table rather than using the switch variable itself

### ISSUE THREAD

**Issue by imethod** [Vector35/binaryninja-api#4575]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.44271

**Bug Description:**
thumb2 tbb switch case error 
The correct disassembly would be switch(r3)  And he added an extra layer of pointer addressing
![image](https://github.com/Vector35/binaryninja-api/assets/109936536/dfacf9a2-7c40-487a-bea5-3b9d3fa58fe9)
![image](https://github.com/Vector35/binaryninja-api/assets/109936536/18c01bc3-3c81-47a6-a4f6-be947830c422)

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Go to 528f1
3. make fun
4. case condition error 

**Expected Behavior:**
switch case index no index mem valuse

**Screenshots:**

ida 
![image](https://github.com/Vector35/binaryninja-api/assets/109936536/20ab5cbb-2b95-494c-bb3f-00774c2e457e)
ninja
![image](https://github.com/Vector35/binaryninja-api/assets/109936536/732e049d-666d-48c6-b702-48908b9c6757)

**Additional Information:**
Please add any other context about the problem here.
[fix.zip](https://github.com/Vector35/binaryninja-api/files/12425211/fix.zip)
fix.zip rename fix.so

**Comment by lwerdna** [comment]
Note: Submitter says in https://github.com/Vector35/binaryninja-api/issues/4825 that this bug wasn't in 3.4.

**Comment by bpotchik** [comment]
Related https://github.com/Vector35/binaryninja-api/issues/3971

**Comment by bpotchik** [comment]
Fixed in `3.6.4800-dev`.
