### ISSUE TITLE
PseudoC mis-matched / unbalanced parenthesis

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#4589]
**Version and Platform (required):**
- Binary Ninja Version: Latest dev 4494
- OS: N/A

**Bug Description:**
Parenthesis are sometimes mis-matched in pseudo-c

**Steps To Reproduce:**
1. Open attached executable
2. Switch to Pseudo C
3. Navigate to 0x119e

**Expected Behavior:**
Parenthesis should be matched. 

**Screenshots:**
![mismatched](https://github.com/Vector35/binaryninja-api/assets/140215/0f9c5b3f-470c-4290-a17a-98a67c5d0775)
[mismatched.out.zip](https://github.com/Vector35/binaryninja-api/files/12467649/mismatched.out.zip)

**Comment by CouleeApps** [comment]
This is fixed in 3.5.4497-dev. The quotes were being turned into close parentheses.
