### ISSUE TITLE
Choosing an option from the symbol list menu causes scroll

### ISSUE THREAD

**Issue by negasora** [Vector35/binaryninja-api#4594]
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4503-dev

**Steps To Reproduce:**
1. Open a binary
2. Scroll down in the symbol list
3. Choose any option in the hamburger menu (even ones that don't change anything)
4. Symbol list scrolls up a bit

**Comment by psifertex** [comment]
This appears to be resolved with the migration to the new symbols widget.
