### ISSUE TITLE
Sending an empty input in the Python console should repeat the last command

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#4598]
Often times we wish to execute the last command again. Right now, we need to press up to navigate to the last command then press Enter. If we support repeating the last command directly, it would be more effective. One interesting aspect of this issue is pressing up to navigate to the last command sometimes lags a bit, like half a second or so, making the entire process a bit anonying

**Comment by psifertex** [comment]
This shouldn't be the default if it is added. Possible solutions:
 - make a non-default setting for the behavior
 - reduce the delay for up-enter so it's not as much of a blocker

**Comment by xusheng6** [comment]
> This shouldn't be the default if it is added. Possible solutions:
> 
>     * make a non-default setting for the behavior
> 
>     * reduce the delay for up-enter so it's not as much of a blocker

Yeah a non-default settings is a good idea. The delay, though, iirc, is a bug or something (at least not an intended behavior). I will create an issue for it if I see fit

**Comment by fuzyll** [comment]
I agree that this shouldn't be default behavior. I feel like this would be pretty surprising for anyone that is familiar with other interpreters.

I'd rather we try and address whatever the delay is. I'm not seeing any locally, but none of my user profiles have a large amount of console history.

Might need some clearer repro steps before we can address the issue (assuming it's not already addressed).

**Comment by xusheng6** [comment]
I tested and found the lag is only observable when I run a debug build in CLion. Dev builds are snappy, and even if I just run the debug build directly, it shows up very quickly. There might be some issues with CLion. I am closing this because the underlying issue seems non-existent.
