### ISSUE TITLE
extremely slow load times 

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#4600]
Reported in slack that sometimes when passing a large number of binaries (say, 11) to BN, the launch time before the window even shows up can be extremely slow (up to a minute or several minutes)

It does not reproduce deterministically and could be related to the files chosen. Was identified on MacOS so need to check with ObjectiveC and fat MachO files to see if a consistent set of files that reproduce are identified.

**Comment by plafosse** [comment]
We have a potential fix for this internally but its a little spicy so we wanted to wait until after stable

**Comment by fuzyll** [comment]
This should have been completed early last month after the release when @CouleeApps' commit was merged. If anyone has other repro steps for this on latest `dev`, please feel free to reopen. Always possible we missed an edge-case or another cause.
