### ISSUE TITLE
Inherited member access shows up as "__offset(0x0)"

### ISSUE THREAD

**Issue by wildex999** [Vector35/binaryninja-api#4616]
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4271 & 3.5.4514-dev
- OS: Windows 10
- CPU Architecture: x64

**Bug Description:**
While working on an AArch64 project, I found that the variables would start to show `_offset(...)` at random places for some struct member accesses. Some places it would also show a write to two int32_t members as a single int64_t write instead. 
I was able to determine that this only happened with members tagged as `__inherited`, and removing that tag would make it show up as expected in the High Level IL/Pseudo C View of the function. 
The first problem seems to be fixed in 3.5.4514, but the second one remains.

I have managed to re-produce this problem with a minimal C++ x64 project, and have attached the compressed bndb.

**Steps To Reproduce:**
1. Open the attached bndb
2. Go to the main function and observe the construction of the "Heap" class.
3. Note how the value writes to `rax_2->childList`'s count and offset are combined, and also show the `__offset`(Address 0x14000122f)
4. Remove the `__inherited` tags from the `Heap` and `OffsetList` structs and observe everything now looks as expected.

**Expected Behavior:**

It's expected that the behavior with inherited members should be the same with non-inherited members.
In this case it's expected to individually show the value being assigned to `ChildList.ListImpl::count = 0`, and `childList.offset = 0xffffffff`.

**Screenshots:**
Problem with `__inherited `in structs:
![Screenshot_1](https://github.com/Vector35/binaryninja-api/assets/3941053/c3e879ef-6493-41b2-90c1-50b60d9dfd43)

After removing `__inherited `tag:
![Screenshot_2](https://github.com/Vector35/binaryninja-api/assets/3941053/355b514d-76c9-4355-841c-977ea5188fdc)

**Additional Information:**
- Part of the problem seems to have been fixed in latest dev, but other part remains. Attached BNDB shows both problems on old version for context.
- Restarting, Re-analyzing or changing things in the Struct doesn't seem to fix the problem.
- Pressing 'S' while hovering over the `__offset(...)` causes it to remove my `__inherited `member.

BNDB:
[BinaryNinja_Inherited_Bug.zip](https://github.com/Vector35/binaryninja-api/files/12537067/BinaryNinja_Inherited_Bug.zip)

**Comment by D0ntPanic** [comment]
Fixed in 3.6.4747
