### ISSUE TITLE
Malformed ELF file stopped the analyze process.

### ISSUE THREAD

**Issue by WZ-Tong** [Vector35/binaryninja-api#4619]
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4516-dev Personal
- OS: Windows 11
- OS Version: 22H2 22621.2215
- CPU Architecture: X64

**Bug Description:**
It's a malformed elf file that binary ninja cannot parse.

**Expected Behavior:**
At least provide an active ELF view.

**Additional Information:**
Open it in ida 7.5 and 7.7, it alerts the data size is wrong (max 0), but still cannot process it.

**Attachment**
[EndWithExtensionSo.txt](https://github.com/Vector35/binaryninja-api/files/12564590/EndWithExtensionSo.txt)

**Comment by xusheng6** [comment]
The "read out of bounds" exception happens here: https://github.com/Vector35/view-elf/blob/5e81e3c07277a157a88d686d3ba85a8c0284048d/elfview.cpp#L1455

**Comment by WZ-Tong** [comment]
Since the `section header table` is not used when loading, maybe there will be a fallback when failed to parse all sections, or specific section (dynamic, init_array, etc.) is not matching the table (simply ignore the table data, use dynamic to recover) ?

**Comment by xusheng6** [comment]
> Since the `section header table` is not used when loading, maybe there will be a fallback when failed to parse all sections, or specific section (dynamic, init_array, etc.) is not matching the table (simply ignore the table data, use dynamic to recover) ?

We are working on a new release and we will get back to this once we are done with the release

**Comment by xusheng6** [comment]
Fixed in dev 3.6.4530
