### ISSUE TITLE
BinaryView leak on Rebase while in LinearView

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#4621]
1. Open a binary with debugger disabled
2. Ensure you have LinearView visible 
3. Rebase
4. Close
5. Observe leak with `get_memory_usage_info()`

**Comment by xusheng6** [comment]
We are leaking exactly one ref for the old view

**Comment by xusheng6** [comment]
This is fixed by [8b9f16c2156ab6146e2b5fd45320987d3255ec21](https://github.com/Vector35/binaryninja/commit/8b9f16c2156ab6146e2b5fd45320987d3255ec21)
