### ISSUE TITLE
`triage.perferSummaryView` no longer works

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#4622]
**Version and Platform (required):**
- Binary Ninja Version: 3.5

**Bug Description:**
`triage.perferSummaryView` should allow users to see the triage summary first instead of being navigated to main/entry_point. This is likely due to a navigation even coming in after the TriageView is selected as the "Best" view, causing it to navigate away. Most likely what needs to occur is if `triage.perferSummaryView` is enabled the navigation code should take this into account when deciding if it should switch views. 

Things I tested:
 * disable uncheck `ui.files.restore.viewState`
 * uncheck `ui.files.navigation.preferMain`
 * with `ui.files.restore.viewState` checked switch to TriageView then close and reopen

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open settings check `triage.perferSummaryView`
2. Uncheck `ui.files.restore.viewState`
3. Open any file
5. See that you're not in TriageView

**Expected Behavior:**
When you have `triage.perferSummaryView` and **no viewState to apply** it should show TriageView

**Comment by bpotchik** [comment]
What happened is there is a Default Layout set, and it is getting applied.

You can use fix this by using one of the following:
* Use command palette to "Delete Layout..." and type "__default__", or
* Clear QSettings

We will be adding a "Delete Default Layout" in the next build after stable.
