### ISSUE TITLE
Entry/Exit Indicators Display for Every Graph Type

### ISSUE THREAD

**Issue by bpotchik** [Vector35/binaryninja-api#4624]
It might be nice if these indicators only show up for certain types of graphs.

For example, the BNIL instruction graph and Workflow topologies end up looking noisy by default. These are composite graphs, not control flow graphs.

![Screen Shot 2023-09-14 at 7 50 48 AM](https://github.com/Vector35/binaryninja-api/assets/29309548/a79481b2-e3f8-42a2-b123-ff24aa80acff)
![Screen Shot 2023-09-14 at 7 43 09 AM](https://github.com/Vector35/binaryninja-api/assets/29309548/b5c5d819-ea6d-4402-ad89-1258208d6965)

**Comment by fuzyll** [comment]
This should now be fixed in builds >= 3.6.4607 (indicators only show on disassembly views, not all flow graph widgets).

I also moved a settings access out of the node painting routine for a small-but-possibly-tangible-if-your-graph-is-large-enough performance benefit.
