### ISSUE TITLE
GetRegisterInfo null invalid argument error when testing old sample file

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#4627]
Testing https://github.com/Vector35/binaryninja-api/issues/303#issuecomment-392278035 in the latest 3.5 produces a number of errors like:
```
[Default] GetRegisterInfo(-2147483647 == "(null)") invalid argument
[Default] GetRegisterInfo(0 == "(null)") invalid argument
```

**Comment by fuzyll** [comment]
I am unable to reproduce this on the latest 3.6 dev builds. I believe one of Andrew's recent PPC changes might've fixed this issue, but I am not certain. Feel free to reopen if you see this with another binary or if there are repro steps I missed.
