### ISSUE TITLE
Detect from a Python SidebarWidget when the SidebarWidget has been destroyed on the C++ side

### ISSUE THREAD

**Issue by kristopax** [Vector35/binaryninja-api#4629]
**What is the feature you'd like to have?**
I would like to have the ability from within a Python SidebarWidget to get notified when the SidebarWidget on the C++ side is about to be destroyed.

**Is your feature request related to a problem?**
When I have split my view to display both multiple view (e.g. Linear View and Graph View) for the current function, if I make suggestions using the Sidekick Suggestions Sidebar for the Linear View and close the Linear View frame while the sidebar operation is still in progress, when the operation completes, I get the following error:

```
[Default] Exception ignored on calling ctypes callback function: <function _ThreadActionContext.__init__.<locals>.<lambda> at 0x2ea7a8280>
[Default] Traceback (most recent call last):
[Default]   File "/private/var/folders/pj/vws938yx21xfcndxsdc673h80000gn/T/AppTranslocation/A96C51CC-0E16-49B8-8A2D-5A8F08BF1A0C/d/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/scriptingprovider.py", line 64, in <lambda>
[Default]     self.callback = ctypes.CFUNCTYPE(None, ctypes.c_void_p)(lambda ctxt: self.execute())
[Default]   File "/private/var/folders/pj/vws938yx21xfcndxsdc673h80000gn/T/AppTranslocation/A96C51CC-0E16-49B8-8A2D-5A8F08BF1A0C/d/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/scriptingprovider.py", line 72, in execute
[Default]     self.func()
[Default]   File "/Users/bk/Documents/binja_spaces/sidekick_beta_staging/plugins/Vector35_Sidekick/sidebars/suggestions_sidebar.py", line 193, in <lambda>
[Default]     self.assistant.on_num_pending_updated = lambda n: (execute_on_main_thread(lambda n=n: self.onPendingCountUpdated(n)), None)[-1]  # noqa: E501
[Default]   File "/Users/bk/Documents/binja_spaces/sidekick_beta_staging/plugins/Vector35_Sidekick/sidebars/suggestions_sidebar.py", line 398, in onPendingCountUpdated
[Default]     self.updateNotification("pending request", newMessage)
[Default]   File "/Users/bk/Documents/binja_spaces/sidekick_beta_staging/plugins/Vector35_Sidekick/sidebars/suggestions_sidebar.py", line 319, in updateNotification
[Default]     self.displayNotification()
[Default]   File "/Users/bk/Documents/binja_spaces/sidekick_beta_staging/plugins/Vector35_Sidekick/sidebars/suggestions_sidebar.py", line 323, in displayNotification
[Default]     self.notificationLabel.setText(self.notifications[-1].message)
[Default] RuntimeError: Internal C++ object (PySide6.QtWidgets.QLabel) already deleted.
```

**Are any alternative solutions acceptable?**
The following suggested solution was tried, but did not work:

`self.destroyed.connect(lambda: whatever())`

**Additional Information:**
The best solution seems to be to define an explicit message (i.e, virtual function on the C++ side) to signal when the sidebar is going away.  Otherwise Python objects don't know when this is happening

**Comment by plafosse** [comment]
Need to add a `closing()` API analog to the other widgets for the SidebarWidget

**Comment by plafosse** [comment]
I fixed this a while ago and never updated this ticket I guess:

https://github.com/Vector35/binaryninja-api/commit/1d1ed09a3c0b2aec01da9271ab30a59be04f5c44
