### ISSUE TITLE
Crash when using goto address in Graph view with no function selected.

### ISSUE THREAD

**Issue by xmonk** [Vector35/binaryninja-api#463]
When no function is selected in graph view, using `g` go to address with a valid address crashes binary ninja. This may be related to issue #462 Crash occurs both in OS X and Linux.

**Comment by psifertex** [comment]
Sorry for missing this one, can you clarify what you mean by no function selected or a screenshot maybe?

**Comment by plafosse** [comment]
I don't see a crash now but, but the view does fail to navigate if no function is selected and you try to navigate with `g`

**Comment by bpotchik** [comment]
I believe this has been fixed for a while.
