### ISSUE TITLE
Closing a split triage summary window triggers a crash in demo on Windows

### ISSUE THREAD

**Issue by romanholidaypancakes** [Vector35/binaryninja-api#4630]
**Version and Platform (required):**
windows
![image](https://github.com/Vector35/binaryninja-api/assets/51652878/3045071b-2a5d-4f6b-903a-d70ba2e83fc2)

**Bug Description:**
Closing a split triage summary window triggers a crash

**Steps To Reproduce:**
1. open the binary file
2. navigate to `view - triage summary`
3. split to a new panel
4. close the new panel
5. crash

**Comment by xusheng6** [comment]
This only reproduces on Windows, and not on macOS or Linux. Very likely the same as https://github.com/Vector35/binaryninja/issues/525

**Comment by xusheng6** [comment]
Fixed by https://github.com/Vector35/binaryninja/commit/464547c0f737e817ddb2fd93013c7cb34ab6ddda. Should be available in dev 3.6.4538
