### ISSUE TITLE
Open existing bndb with options -> Save causes weird filename suggestion

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#4633]
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4526
- OS: macOS
- OS Version: 12.6
- CPU Architecture: M1

**Bug Description:**
I opened a BNDB with options, and then tried to save. The suggested file name was `mything.bndb.bndb`, which looks silly.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open with Options
2. Select any existing BNDB
3. Finish opening
4. Press save

**Expected Behavior:**
I expected one of the following: 
1. The bndb saves over the original with the new options
2. The save dialog prompts me to make a second bndb with a name like `mything.bndb` (and then it can handle the mess of replacing the file)

**Comment by bpotchik** [comment]
Fixed in `4.6.4548-dev`.
