### ISSUE TITLE
Component class is not hashable

### ISSUE THREAD

**Issue by kristopax** [Vector35/binaryninja-api#4636]
**What is the feature you'd like to have?**
I would like for the Python Component class to be hashable via __hash__ method implementation.

**Is your feature request related to a problem?**
On Sidekick, we are currently having to manually define an implementation instead of just using one provided by the class.

**Are any alternative solutions acceptable?**
This is what we are currently doing on Sidekick to achieve the desired feature:

`Component.__hash__ = lambda self: cast(Component, self).guid.__hash__()
`

**Comment by plafosse** [comment]
Fixed on dev. I didn't cause a build to be generated should be fixed in >= 3.6.4775
