### ISSUE TITLE
Crash in outlining with workflows disabled

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#4639]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4546-dev (does not repro on stable)
- OS: macOS
- OS Version: 12.6
- CPU Architecture: M1

**Bug Description:**
When loading specific functions with workflows disabled, the outlining resolver crashes with an uncaught c++ exception thrown. Somewhere in OutlineResolver::ResolveTypeConstraints is throwing an absl::btree_map::out_of_range

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open this one specific bndb I have that reproes it (private, ask for access)
2. Crash happens a few seconds into reanalysis

**Expected Behavior:**
I expected analysis to not crash.

**Comment by bpotchik** [comment]
Fixed in `3.6.4547-dev`.
