### ISSUE TITLE
Crash on context menu after selecting a variable in linear view then navigating

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#4647]
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4526 (stable)
- OS: Windows
- OS Version: 11
- CPU Architecture: x64

**Bug Description:**
In certain cases, trying to right click the types view crashes after a specific set of actions in linear view.

**Steps To Reproduce:**
1. Open this binary: [animals.exe.zip](https://github.com/Vector35/binaryninja-api/files/12704972/animals.exe.zip)
2. Navigate to 00401f80
3. Double click the the `Fly` token in the variable in the signature
4. Under Xrefs -> Data References, double click the vtable reference
5. Right click in Types View
6. Program crashes

**Expected Behavior:**
I expected the program not to crash.

**Additional Information:**
Looks like `m_highlight.localVarValid` is not being cleared on navigation away from the function, and then `getCurrentFunction()` returns nullptr and crashes.

**Comment by CouleeApps** [comment]
Will be fixed in 3.6.4554-dev

**Comment by wildex999** [comment]
Tested on 3.6.4554-dev any my case no longer crashes :)
