### ISSUE TITLE
Cannot save database after re-opening a database

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#4648]
Steps to reproduce: 

1. Open an existing database
2. Close the tab (do not close BN)
3. Re-open the database
4. Try to save the database

I get the following error message `Error while saving database snapshot: database is locked`.

This has nothing to do with the debugger

**Comment by xusheng6** [comment]
We now have a leak on the FileMetadata object which is causing the current issue. IIRC this is a pretty new regression, since things were fine in the stable release

**Comment by xusheng6** [comment]
Introduced in dev 3.6.4528

**Comment by bpotchik** [comment]
Fixed in `3.6.4560-dev`.
