### ISSUE TITLE
Binary ninja fails to detect switch table

### ISSUE THREAD

**Issue by gsingh93** [Vector35/binaryninja-api#465]
There is a switch table in the binary `diapers` from ASIS CTF Finals 2016 at address 0x8048845. However binja only finds one target from that block. IDA finds all targets. The binary is attached.

[diapers.zip](https://github.com/Vector35/binaryninja-api/files/466185/diapers.zip)

**Comment by psifertex** [comment]
Thanks, that's a good test case. The jump table plugin also fails to process the jump table it looks like.

**Comment by Grazfather** [comment]
[Here[(https://github.com/ctfs/write-ups-2016/blob/master/asis-ctf-2016/pwn/car-market-177/Car_Market.txz)'s a 64 bit bin with the same issue:

**Comment by psifertex** [comment]
Actually, the plugin /does/ find the jump table. I was using it wrong -- to get the most out of the jump table detection plugin, make sure to right-click on the instruction that contains the base of the jump table. (The one just before the jmp itself)

We still want to fix it the right way, but in the meantime there's at least a reasonable work-around. 

Same approach works for the binary @Grazfather posted. Just right click on `0x400c95` and choose `Process Jump Table` after installing the plugin (https://github.com/Vector35/binaryninja-api/blob/master/python/examples/jump-table.py)

**Comment by plafosse** [comment]
Both of these issues are fixed in dev!
