### ISSUE TITLE
In Symbol view with filter delay, typing and pressing enter does not respect filter

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#4656]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4550
- OS: macOS
- OS Version: 14.0
- CPU Architecture: M1

**Bug Description:**
Typing in a filter now has a delay before results appear, but I am impatient and want to press enter immediately to just I'm Feeling Lucky myself into whatever the top result is. Unfortunately, the enter keypress triggers before the filter updates, so instead I'm sent to whatever sub_400000 function is on the top of the list before the filter applies. I want the enter keypress to still trigger the navigate, but wait for the filter to apply first and THEN pick whatever is on top.

**Steps To Reproduce:**
1. Open a binary with symbol names
2. Search for a symbol name and really fast, hit enter
3. Realize you did not get a symbol whose name matches your query
4. Feel like your workflow is not optimized :(

**Expected Behavior:**
I expected to go to a matching symbol. Also I expected the search box to not clear after pressing Enter.

**Comment by psifertex** [comment]
Resolved with the new symbols widget.
