### ISSUE TITLE
Ability to disable name propagation or add property to all things that can be named through name propagation

### ISSUE THREAD

**Issue by kristopax** [Vector35/binaryninja-api#4659]
**What is the feature you'd like to have?**
I would like the ability to disable name propagation (via setting) or a property added to things with names that indicates if its name is auto-named.

**Is your feature request related to a problem?**
Sidekick relies on knowing if a variable is auto-named in order to suggest better names for variables. Currently, Sidekick relies on matching a naming pattern for auto-named variables. However, in a recent Binary Ninja update, name propagation for variables breaks that pattern so that it cannot be reliably determined if a variable has been auto-named. This also applies to structure and field names.

Having a setting available to disable name propagation is probably the best (maybe even easiest) solution for Sidekick.

**Comment by xusheng6** [comment]
Added a setting `analysis.autoNameVariables` in dev 3.6.4580
