### ISSUE TITLE
Address-based comments

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#466]
comments right now are tied to functions which is fine for instructions that are in a function (and important for binaries that might have multiple architectures or functions overlapping), but not fine for either instructions not associated with a function (when they exist), or for data which should also allow comments.

Implement a generic comment API off of the `binaryview` that allows setting comments on the default architecture which is the most common use case (but the set_comment on the function class will remain for instances where a file has multiple architectures that potentially overlap)

**Comment by rollsafe** [comment]
This was added to dev and is exposed by the python api as `bv.set_comment_at`, `bv.get_comment_at`, and `bv.comments`. Keep in mind these aren't the same as function-level comments, which are still the preferred way of annotating code.
