### ISSUE TITLE
Renaming a type to an existing name silently discards the original type

### ISSUE THREAD

**Issue by wildex999** [Vector35/binaryninja-api#4661]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4561-dev Personal
- OS: Windows
- OS Version: 10
- CPU Architecture: AArch64

**Bug Description:**
Types can eat other Types if you accidentally rename instead of change type, causing you to break all types which references the renamed type. If you don't have a backup you're now forced to spend hours fixing all the references which now points to the wrong type.

**Steps To Reproduce:**
1. Create two Struct Types, "StructA" and "StructB, base(StructA)"
2. Make a function reference "StructB" as argument.
3. Click the argument type for "StructB" in the function, and accidentally press "N" instead of "Y"
4. Replace "StructB" with "StructA" and move on with work not expecting anything to be wrong.
5. Find out 5 hours later that "StructB" no longer exists, and all references to "StructA" and "StructB" have combined, and you have to fix all the references which should be to "StructB".

**Expected Behavior:**
If you try to rename a struct to an existing one, it should NOT be allowed, at all. At least not without multiple warnings that you will lose the old struct.
Maybe also have an option to stop renaming types from a function argument.

**Comment by plafosse** [comment]
This should be a pretty easy thing to fix. This should be done in the UI, by checking for conflicts and prompting with an "Are you sure you want to do this"

**Comment by xusheng6** [comment]
Related to https://github.com/Vector35/binaryninja-api/issues/3273

**Comment by xusheng6** [comment]
Fixed in dev 4.1.5181
