### ISSUE TITLE
Unsaved changes dialog text is unusually bold

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/binaryninja-api#4662]
**Why is it like this?**

<img width="532" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/41548458/31a7db81-fb84-4d96-af2f-ac0aa6064f62">

Binary Ninja 3.5.4526 (Stable)

**Comment by psifertex** [comment]
Latest dev uses QT 6.5.3 which uses system-native dialogs for that popup. That said, they're still arguably bold but it's nothing we're doing specifically. Literally just the QT QMessageBox:Question default styling apparently. And the new dialog has some other issues with color we probably need to address as we're doing our UI overhaul this release..

<img width="268" alt="Screenshot 2023-09-30 at 22 57 04" src="https://github.com/Vector35/binaryninja-api/assets/140215/9f5dc4de-1344-4a85-89f8-1b6cb6594149">
