### ISSUE TITLE
total_bytes in components view is wrong

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#4664]
Latest dev: `4574`:

total bytes column is very wrong:

<img width="689" alt="Screenshot 2023-10-04 at 09 45 45" src="https://github.com/Vector35/binaryninja-api/assets/140215/508d91b6-c431-4257-bdef-09d0ced1dbf2">

**Comment by bpotchik** [comment]
Fixed in `3.6.4662-dev`.
