### ISSUE TITLE
Demangler Plugins

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#467]
Provide a generic API for users to add their own name demanglers to be run during analysis.  This can currently be done after the fact, but it would be nice if it could be integrated.

We should provide two api's, Demangle() and DemangleToType()
The DemangleToType() api will return a BNType object containing a type tree for the given type, Demangle() will simply return a string.

**Comment by lucasduffey** [comment]
Example workaround:

```
import subprocess
for func in bv.functions:
    if func.name.startswith("__T") or func.name.startswith("_T"):
        func.name = subprocess.check_output(["/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-demangle", "-compact", func.name])
```

**Comment by CouleeApps** [comment]
As of 4.2.6222 this is now available via the `Demangler` api. Note that this is a strict plugin layer feature for now, and issues such as #4551 #5920 etc are not resolved
