### ISSUE TITLE
Switch-case converted to if-else in HLIL

### ISSUE THREAD

**Issue by imethod** [Vector35/binaryninja-api#4670]
**Version and Platform (required):**
3.6.4580-dev

**Bug Description:**
![image](https://github.com/Vector35/binaryninja-api/assets/109936536/16fc4e16-16a3-403c-9d14-5355b5579ef7)
![image](https://github.com/Vector35/binaryninja-api/assets/109936536/413dac63-5be0-437c-8acf-a77e4c53e6fb)
![image](https://github.com/Vector35/binaryninja-api/assets/109936536/4bfdb38a-6f63-4645-a57c-18e3e9f03cc7)
![image](https://github.com/Vector35/binaryninja-api/assets/109936536/4fb4f02d-3475-4ba7-8409-05192f793549)

In the picture Not defined as switch 
Looks like this jump pattern ninja didn't handle it
**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Go to 0x387c create func
2. Go to 38f8

**Additional Information:**
[demo.zip](https://github.com/Vector35/binaryninja-api/files/12837188/demo.zip)
demozip rename demo.so

**Comment by xusheng6** [comment]
![Screenshot 2023-10-10 at 12 42 48 PM](https://github.com/Vector35/binaryninja-api/assets/94503187/8f35b24a-5d87-4f64-b3e1-5b33e89559a4)

The switch-case is properly detected at MLIL. However, for some reason, at HLIL level, the core decides to convert the switch-case to an if-else statement. The semantics of the code is correct, though it is not very readable.

**Comment by xusheng6** [comment]
This appears to have been fixed some time before 4.1.5552-dev (8c469a9c), though I do not know when exactly was it fixed:
 
![Screenshot 2024-06-20 at 12 48 52 PM](https://github.com/Vector35/binaryninja-api/assets/94503187/91327b02-26bf-4dcd-9efc-364c94fc9e62)
