### ISSUE TITLE
BinaryNinja.load() returns bv with a parent_view of None if the view is a subclass of BinaryView

### ISSUE THREAD

**Issue by mbilzor** [Vector35/binaryninja-api#4680]
**Version and Platform (required):**
- Binary Ninja Version: e.g. 3.6.4585-dev
- OS: MacOS
- OS Version: 13.4.1
- CPU Architecture: M1

**Bug Description:**
When using Python BinaryNinja.load() to open a .bndb, the returned bv is fine, but the bv.parent_view is None. This occurs only when the following are true:
- running headless Python (works fine in the GUI and GUI console) with BinaryNinja.load()
- the class of the binary being opened is a registered subclass of BinaryView, defined in a plugin

**Steps To Reproduce:**
1. Create a subclass of BinaryView (nes.py or nds.py plugins should suffice)
2. Verify that a binary image of that type loads in the GUI and bv.parent_view returns a valid parent view
3. Verify in headless Python script that the bv returned by binaryninja.load() has a parent_view of None:
with binaryninja.load(source=bndb_filename) as bv:
	print(f'parent_view: {bv.parent_view}')

**Expected Behavior:**
There should be a bv with a valid parent_view returned, regardless of whether a database is opened in the GUI or opened headless using BinaryNinja.load().

**Screenshots:**
N/A

**Additional Information:**
This problem only seemed to crop up after other options (besides BinaryNinja.load()) were deprecated for opening an existing database in headless Python.

**Comment by bpotchik** [comment]
Fixed in `3.6.4803-dev`.
