### ISSUE TITLE
Rainbow "braces" effect should not be applied to string delimiters

### ISSUE THREAD

**Issue by galenbwill** [Vector35/binaryninja-api#4681]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4584-dev
- OS: macOS
- OS Version: 12.6.7
- CPU Architecture: M1

**Bug Description:**
Rainbow "braces" effect should not be applied to `"` delimiters on strings.

**Steps To Reproduce:**
Open any binary, find a sequence of strings defined one after another, observe different colors on the quote delimiters on various strings.

**Expected Behavior:**
All string delimiter quotes should be colored the same as strings.

**Screenshots:**
![image](https://github.com/Vector35/binaryninja-api/assets/12259536/aebfde7c-651e-41c0-810f-ff6f76e68c94)

**Additional Information:**
Suspicion is that the tokens for string delimiters are brace tokens, and so get automatically rainbow'ed.

**Comment by CouleeApps** [comment]
This was fixed in >=4.1.5400-dev by fixing the "value" property of the quote bracetokens and expanding the bracetoken matcher to handle quotes.
