### ISSUE TITLE
Need official documentation for how to handle large/complicated binaries

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#4684]
**Is this a general concept that needs to be documented or a specific API?**
General, should be in the user docs.

**What concept or API needs more documentation?**
One of the issues that comes up a lot is, "I have a binary that is large/complicated and analysis doesn't finish because of time/memory constraints, what do I do?" We need to have official documentation on the various ways in which people deal with this that we can point people to.

This happens to people *a lot*. Here are four examples from the last year that I found within 5 minutes of searching:

* #3885 
* #4425 
* #4442 
* #4683

If any of these are the result of a pathological performance issue in our analysis, we should keep them open and address the problem. But, if they're just "I tried to load a complicated binary that's 200 MB in size into Binary Ninja and it OOM'd my box that has 32 GB of RAM with default settings", it's not a "real" issue. The "real" issue is that users don't know what to do when they encounter that scenario and they're stuck.

**Is this documentation related to a specific API?**
No.

**Are there any known examples of people using this API/concept?**
Plenty, but they keep getting lost in the vast, yawning void that is the free version of Slack.

**Comment by fuzyll** [comment]
Thank you for the report. This should be fixed in builds >= 3.6.4613-dev.

**Comment by KyleMiles** [comment]
I started working on this, but it got punted again in interest of proof-reading. WIP patch : `gently lively liked hog `.

**Comment by fuzyll** [comment]
I've added a basic troubleshooting section now in builds >= 4.1.5706-dev. We'll continue to expand on this going forward.
