### ISSUE TITLE
Unnecessary resize-ability in "Update Channel Preferences" window

### ISSUE THREAD

**Issue by blue-devil** [Vector35/binaryninja-api#4685]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4590-dev Personal and v3.5.4526 Personal
- OS: macOS
- OS Version: Sonoma v14.0
- CPU Architecture: x86_64

**Bug Description:**
Please see the screenshot that I have recorded.

* `Update Channel Preferences` qwindow can be resized downwards or upwards; but it is unnecessary.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Go to `Binary Ninja > Preferences`
2. Click on `Settings`
3. On the `search bar` write down `channel`
4. Click on `Select...` button under `Update Channel Preferences`
5. A new qwindow will pop. Now you can resize that button to every direction

**Expected Behavior:**
* I expect `Update Channel Preferences` window not to resize in every direction. I think `Update Channel Preferences` window should be fixed in size. Like Binary Ninja `about` window.

**Screenshots:**

![ss1](https://github.com/Vector35/binaryninja-api/assets/10853207/82603cfa-f3db-438d-a991-04fa4e4ec973)

![ss2](https://github.com/Vector35/binaryninja-api/assets/10853207/41627caf-fc46-4ee4-864b-e2269037956f)
 
**Additional Information**
This issue is a similar issue like closed issue: #4175

**Comment by fuzyll** [comment]
Fixed in builds >= 3.6.4597-dev

**Comment by blue-devil** [comment]
Thank you; I have checked on macOS and Windows 11 releases on Binary Ninja and the issue has been fixed.
