### ISSUE TITLE
Improve `blx lr` handling on ARM/Thumb

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#4688]
Sometimes, a `blx lr` should be treated as a jump, as seen in the binary from #2977.

Other times, it should be treated as a call, as seen in the binary from #4686.

Previously, we lifted this as a call everywhere. [Here](https://github.com/Vector35/arch-armv7/commit/662d1009d707ae7b9010ae1e57cf6829d87b12ff), we specialized it to be a jump in some cases. Unfortunately, this appears to either be incompletely specified at best, or impossible to determine at worst.

If we can determine a way to specify this more completely, or solve #979 and can give users a way to switch between both behaviors, that would be great.

**Comment by bpotchik** [comment]
Fixed in `3.6.4594-dev`.

We now support analysis of 'blx lr' given the context of the target held in lr. Analysis should generate a function return, or a regular call based on the available context.
