### ISSUE TITLE
Update screenshots for 4.0

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#4690]
We are planning on launching 4.0 with a new theme. This also necessitates:

- [x] website screenshots updated
- [x] user docs screenshots updated
- [x] theme repo updated (not needed prior to launch)

**Comment by fuzyll** [comment]
Final version of theme was put on `dev` yesterday (build 4.0.4871-dev).

**Comment by fuzyll** [comment]
Website stuff should be ready to go now, which completes this issue.
