### ISSUE TITLE
url handlers on linux and windows do not open in existing windows

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#4695]
On Windows and Linux, the URL handlers do not open an existing process if one exists. This makes it impossible to use the feature that exists on MacOS to navigate an already existing view using the `expr` parameter along with the same file path. 

The default behavior should be to launch any command line parameters as a new tab in an existing process unless a flag is passed on the command line to force a new process be launched.

**Comment by galenbwill** [comment]
I have this working on a test branch. Still needs more thorough testing, but it's working on all three platforms.

**Comment by galenbwill** [comment]
Fixed in 4.0.4836
