### ISSUE TITLE
SCC: Variadic Macros

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#47]
_From @plafosse on July 21, 2015 17:49_

_Copied from original issue: Vector35/scc#3_

**Comment by plafosse** [comment]
A possible workaround for the lack of this feature is to run a preprocessor on your source code prior to compiling with SCC some have had success using clang -E -nostdinc

**Comment by plafosse** [comment]
This has been obviated by switching to clang for type parsing.
