### ISSUE TITLE
repr of BasicBlock does not show start and end address in hex

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#4708]
```
>>> current_basic_block
<BasicBlock: x86_64@5368754260-5368754267>
```

**Comment by lwerdna** [comment]
This is a simple fix in `api/python/basicblock.py`:

```python
	def __repr__(self):
		arch = self.arch
		if arch:
			return f"<{self.__class__.__name__}: {arch.name}@{self.start:x}-{self.end:x}>"
		else:
			return f"<{self.__class__.__name__}: {self.start:x}-{self.end:x}>"
```

Following my best guess at current convention, there is no leading "0x" and the letter characters are lowercase.

Many unit tests change as a result, having stored the decimal representation:

![image](https://github.com/Vector35/binaryninja-api/assets/474191/1af9f6fe-0137-4a08-a86b-15b7e82418e9)

The question is: Is everyone in agreement that we should change to hex representation?

**Comment by xusheng6** [comment]
> This is a simple fix in `api/python/basicblock.py`:
> 
> 
> 
> ```python
> 
> 	def __repr__(self):
> 
> 		arch = self.arch
> 
> 		if arch:
> 
> 			return f"<{self.__class__.__name__}: {arch.name}@{self.start:x}-{self.end:x}>"
> 
> 		else:
> 
> 			return f"<{self.__class__.__name__}: {self.start:x}-{self.end:x}>"
> 
> ```
> 
> 
> 
> Following my best guess at current convention, there is no leading "0x" and the letter characters are lowercase.
> 
> 
> 
> Many unit tests change as a result, having stored the decimal representation:
> 
> 
> 
> ![image](https://github.com/Vector35/binaryninja-api/assets/474191/1af9f6fe-0137-4a08-a86b-15b7e82418e9)
> 
> 
> 
> The question is: Is everyone in agreement that we should change to hex representation?

We want to keep the address in decimal if it is an IL basic block because we use decimal for IL index

**Comment by plafosse** [comment]
As there are subclasses for each BasicBlock type this is simple to fix

**Comment by xusheng6** [comment]
Related to https://github.com/Vector35/binaryninja-api/issues/4771
