### ISSUE TITLE
Reusable Analysis APIs

### ISSUE THREAD

**Issue by withzombies** [Vector35/binaryninja-api#471]
LLVM has reusable analyses through the getAnalysisUsage api: http://llvm.org/docs/WritingAnLLVMPass.html#specifying-interactions-between-passes

It allows plugins to invoke and query existing analysis passes such as AliasAnalysis, LoopInfo, MemDependence, etc. Binary Ninja should support a generic and standardized analysis framework like LLVM's passmanager.

This ideally would likely result in a new type of plugin class being created.

**Comment by plafosse** [comment]
Closing in favor of: #1606
