### ISSUE TITLE
Decimal values in the comment cannot be selected

### ISSUE THREAD

**Issue by tur11ng** [Vector35/binaryninja-api#4715]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4601-dev Personal (cf7aac28)
- OS: Ubuntu Linux
- OS Version: 22.04]
- CPU Architecture:  x64

While the hexadecimals can be selected the decimals cannot. The hexadecimals are also highlighted too. I know this is very minor but maybe it isn't the intended behavior (at least it doesn't seem so to me).

[Screencast from 2023-10-27 21-12-44.webm](https://github.com/Vector35/binaryninja-api/assets/61602820/c9126389-f9f6-4a35-8fb3-29b496abfc4f)

EDIT : Updated the video to show the mouse.

**Comment by xusheng6** [comment]
I am pretty sure the code enforces the current behavior, though I am not sure that whether this is a conscious decision, or it happens to behave like this.

**Comment by plafosse** [comment]
You can click drag across the comment to select sub sections of the comment.
