### ISSUE TITLE
Modifying an enum makes BN unresponsive for 5-10 minutes

### ISSUE THREAD

**Issue by alexrp** [Vector35/binaryninja-api#4719]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4603-dev Personal ( 2e38be6)
- OS: Windows
- OS Version: 10.0.23575.1001
- CPU Architecture: x64

**Bug Description:**
Modifying a particular enum makes BN unresponsive for 5-10 minutes. This doesn't happen for other enums.

This particular enum has hundreds of members that I need to add as I analyze corresponding classes, so this is quite disruptive.

**Steps To Reproduce:**
1. Grab [this](https://drive.google.com/file/d/1OmIalqv9Mp7NtY2zj97njAJHZtUtXY5Y/view?usp=sharing) BNDB.
2. Navigate to the `S1ControllerType` enum.
3. Edit the enum by adding or removing a member.

**Expected Behavior:**
The modification should complete in a more reasonable amount of time.

**Comment by CouleeApps** [comment]
The main issue with this is that that type is referenced by a lot of types that are referenced by a lot of other types, and thus updating it requires updating all of those other types, which requires updating all the types that depend on them, etc. This is known to be really slow right now, and while there are plans to improve it soon, I'm not sure there's any workaround at the moment.

**Comment by alexrp** [comment]
It still seems extremely disproportionate, though. E.g. `S1GameObject` is referenced in a *ton* of places by comparison (~36k xrefs vs ~600), including from all the same types that `S1ControllerType` is, yet adding a field to it takes about ~2s for BN to become responsive again, and BN is perfectly usable while the following reanalysis takes place. I guess I'm just wondering why modifying the `S1ControllerType` enum, OTOH, completely locks up BN for 5-10 minutes.

**Comment by CouleeApps** [comment]
In this case, I'm not sure what specifically about S1ControllerType makes it so much slower. My best guess off-hand is that it's just referenced more in places that have lots of references to themselves. Eg, many of the vtable structures have a similar impact (eg I tried updating `S1ControllerBase::__vftable` and the same thing happened).

**Comment by CouleeApps** [comment]
Addressed in 4.1.4967-dev

**Comment by alexrp** [comment]
Can confirm that updates to `S1ControllerType` are now ~instantaneous. 🎉

PS: Not super important, but I noticed the commit message mentioned #392. Wrong issue number? :eyes:

**Comment by psifertex** [comment]
Not sure but probably an internal repo issue.

**Comment by CouleeApps** [comment]
Yeah that's an internal issue number (we had a duplicate with private details)
