### ISSUE TITLE
Linear Feature Map rendering is broken

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#4722]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4599
- OS: macOS
- OS Version: 14
- CPU Architecture: M1

**Bug Description:**
Trying to use the feature map in Linear mode causes rendering issues

**Steps To Reproduce:**
1. Open a binary (might have to be > 1MB)
2. Notice feature map is not linear, despite having Linear Feature Map setting enabled (probably a different bug)
3. Right click feature map and enable Linear Feature Map
4. Realize the repaint didn't clear the old feature map
5. Try resizing the window and watch it glitch out

**Expected Behavior:**
I expected it to not look broken

**Screenshots:**
<img width="1142" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/711973/7d2d3e58-8ace-42fd-96a9-1860fed7aa23">
<img width="1130" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/711973/ee209168-e221-4894-a089-c0708caddf89">
<img width="1132" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/711973/da61b384-99e2-4202-a4a4-cc3e9a3ed8de">
<img width="1134" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/711973/4a38909a-f422-49c2-bb65-ab59223f634b">

**Comment by negasora** [comment]
This is because qt does not handle images larger than 32767px in either direction properly. The feature map should work on a widget-sized image and calculate coordinates accordingly instead of operating on a massive image then scaling down.

**Comment by negasora** [comment]
fixed in `4.0.4882-dev`

**Comment by CouleeApps** [comment]
Looks way better! Thanks for the fix

<img width="948" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/711973/9bdc177b-6b00-4123-a5a3-4362a3ff2b94">
