### ISSUE TITLE
inconsistent handling of URLs in interaction APIs

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#4726]
Trying to use URLs in text of get_tex_link_input shows text that _looks_ clickable is not. We should fix the URL handler so it passes to the native browser as done in other interfaces or at least normalize the behavior across all interaction APIs.

Example:

```
>>> from binaryninja import get_text_line_input, show_message_box
>>> get_text_line_input("Test <a href=\"https://google.com/\">link</a>.", "Title")
# Dialog looks clickable but isn't.
```

Conversely, show_message_box just removes linking entirely. 

```
>>> show_message_box('test', 'test <a href="https://google.com/">link</a>')
# neither link style nor clickable
```

**Comment by galenbwill** [comment]
Update (as of 4.0.4863-dev (908ede53)): `show_message_box` now shows the link, and it is clickable.

There is no change in `get_text_line_input`: the links still show styled as a link, even shows the URL mouse pointer when hovered, but does not click.

**Comment by galenbwill** [comment]
I dug into the Qt source a bit on this, and the short answer is that it's not possible to fix the clickability of links rendered in a call to `QInputDialog::getText` without patching the Qt source, as it requires calling `setOpenExternalLinks` on the private `QLabel` created in the `QInputDialog` instance (whose lifetime anyway is only the call to `getText`).

If we really want this, we could implement our own `QInputDialog` class (or maybe subclass?).

Closing as won't fix for now. Someone can reopen if we decide we really need this.
