### ISSUE TITLE
Import header file dialog accepts rich text

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#4729]
I copied a path from a macOS terminal pasted it into the "Compiler Flags" part of the import header file dialog, and I get a funny result, that the color information is preserved and the text is hard to see. We might wish to limit the input to plain text. 

![Screenshot 2023-11-06 at 4 19 15 PM](https://github.com/Vector35/binaryninja-api/assets/94503187/00414fe5-966b-4e9d-a8b8-753104aac1e6)

**Comment by fuzyll** [comment]
Thank you for the report. This should be fixed in builds >= 3.6.4613-dev.
