### ISSUE TITLE
Crash using PDB plugin with large PE

### ISSUE THREAD

**Issue by kukfa** [Vector35/binaryninja-api#473]
Binja crashes without any traces on both Windows 10 and Ubuntu 16.04.1 when using Josh Watson's [PDB loader plugin](https://gist.github.com/joshwatson/47cada73f4fca06fa2f5035b770001c1). Tested and confirmed in both stable & dev channels. I can send the PE & PDB if desired (PE is ~6mb, PDB is ~9mb).

**Comment by psifertex** [comment]
Please send via slack, thanks.

**Comment by plafosse** [comment]
We currently have a built in PDB parser, and the mentioned plugin is deprecated.
