### ISSUE TITLE
Select relevant segment/section in memory map widget sometimes selects one extra section/segment

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#4730]
![Screenshot 2023-11-06 at 7 49 14 PM](https://github.com/Vector35/binaryninja-api/assets/94503187/22656156-7dd1-4412-8a3e-3e9be3cf63bd)

As we can see in the screenshot, selecting the segment 0x2fdc0-0x334b0 also selects the `.extern` section which has no overlap with the segment. 

It is an off-by-one error when we calculate and compare the end

**Comment by fuzyll** [comment]
Thank you for the report. This should be fixed in builds >= 3.6.4613-dev.
