### ISSUE TITLE
Objective-C structure analysis failed on iOS app binary

### ISSUE THREAD

**Issue by fitz-bb** [Vector35/binaryninja-api#4732]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4617-dev
- OS: macOS
- OS Version: Ventura 13.3
- CPU Architecture: M2

**Bug Description:**
Objective-C method names are not shown
Objective-C -> Analyze Structures fails

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
Load attached binary
Click on Objective-C -> Analyze structures

Error output in log:
[Plugin.Objective-C] Objective-C analysis will not be applied due to previous errors.
[Plugin.Objective-C] Structure analysis failed; binary may be malformed.

**Expected Behavior:**
Methods are shown, no error in log

**Screenshots:**
<img width="681" alt="Screenshot 2023-11-07 at 11 35 33 AM" src="https://github.com/Vector35/binaryninja-api/assets/126191933/780a8684-8c49-43df-b788-fa46daedd500">

**Additional Information:**
Example file: https://github.com/fitz-bb/binary-ninja-support/raw/main/ObjcFail.zip

**Comment by 0cyn** [comment]
We've resolved this issue in a series of upcoming changes and it should be landing soon.

**Comment by 0cyn** [comment]
Resolved in **dev builds >= 4.1.5465**
