### ISSUE TITLE
Override Call Type and Set Stack Adjustment unavailable at the disassembly level

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#4739]
The two actions can only be triggered from an IL level. The UI code to determine whether the current instruction is a call seems to have some bugs

Similar to #4687

**Comment by negasora** [comment]
This issue doesn't repro on `3.6.4634-dev`

**Comment by plafosse** [comment]
@xusheng6 If you can please provide a binary and an address to reproduce this issue.

**Comment by fuzyll** [comment]
This *does* repro for me, but only partially, and it's pretty confusing.

Steps:

1. Navigate to `sub_000078ad8`
2. Right-click on the `sub_78b04` in disassembly, LLIL, or MLIL
3. Observe that "Override Call Type" and "Set Stack Adjustment" are not options
4. Right-click on `sub_78b04` in HLIL
5. Observe that "Override Call Type" and "Set Stack Adjustment" are now options
6. Go back to disassembly, LLIL, or MLIL
7. Right-click on the _address_ of the call (`00078af4`)
8. Observe that "Override Call Type" and "Set Stack Adjustment" are now options

File: [htop-arm.bndb.zip](https://github.com/Vector35/binaryninja-api/files/13368988/htop-arm.bndb.zip)

**Comment by xusheng6** [comment]
Try this file and address 0x121c, the "override call type" is only available at HLIL

[helloworld.zip](https://github.com/Vector35/binaryninja-api/files/13816131/helloworld.zip)

**Comment by negasora** [comment]
Fixed in `3.6.4816-dev`
