### ISSUE TITLE
Closing tabs causes the entire UI to hang

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/binaryninja-api#4740]
Closing tabs causes the entire UI to hang. Personally, I find this undesirable. I originally thought this was due to having large binaries open, but this happens regardless of binary size it seems.

- Binary Ninja 3.5.4526, ec37d737
- macOS 13.5 (arm64)

**Comment by plafosse** [comment]
Any clue on if the tab was analyzing or what kind of binary you had open?

**Comment by jonpalmisc** [comment]
This was always on small binaries that had already finished analyzing. It also doesn't seem to matter how long analysis has been completed for.

**Comment by bpotchik** [comment]
A hang was fixed in `3.6.4711-dev`.
