### ISSUE TITLE
Enum Display Types do not update member names when the type is updated

### ISSUE THREAD

**Issue by 0cyn** [Vector35/binaryninja-api#4743]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4591

**Bug Description:**
Enum DisplayTypes for IL constants do not update member names or other type information whenever the type is modified and function reanalyzed

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open a Mach-O
2. Find a 0 in IL and select it
3. Press M, set it to vm_prot_t
4. rename the first member of vm_prot_t from the types browser
5. reanalyze the function
6. observe old name still hanging around

**Comment by plafosse** [comment]
Duplicate of [#4163](https://github.com/Vector35/binaryninja-api/issues/4163)
