### ISSUE TITLE
Crash during Phase 2 analysis 

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#4756]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4642-dev (db162f4a).

Shared internally:  Silver Shark Sips Soda

**Comment by lwerdna** [comment]
Here's a reduced (but maybe not minified) repro: [crash.zip](https://github.com/Vector35/binaryninja-api/files/13397362/crash.zip)

Go to location `1000003e7f: rdi_2 = rsi_3 + var_70`

Click the `rsi_3` and set the type to `uint32_t *` and it will crash.

The index expression is `var_70` and, trying to resolve that, finds it self defined, resulting in infinite descent.

**Comment by plafosse** [comment]
The commit that caused this crash has now been reverted.
