### ISSUE TITLE
plugins - support plugin directories

### ISSUE THREAD

**Issue by lucasduffey** [Vector35/binaryninja-api#476]
It would be nice if you would support directories, so a user could `git pull` into  `~/.binaryninja/plugin` and not have to create a python wrapper file or symlink the scripts.

If the plugin has an `__init__.py` file in it's directory maybe it could kick everything off?

**Comment by joshwatson** [comment]
What about pyz archives?

**Comment by lucasduffey** [comment]
does that already work? it adds another step for users though, and slightly slows down dev AFAIK

**Comment by joshwatson** [comment]
Yeah I was thinking more for finished plugins rather than during development. I have no idea if it already works though

**Comment by lucasduffey** [comment]
relevant: https://github.com/Vector35/binaryninja-plugins

**Comment by psifertex** [comment]
To be clear -- the binary ninja code to do this isn't in yet, re-opening until we've got the code in dev to support this.

**Comment by psifertex** [comment]
(but should be soon)
