### ISSUE TITLE
Improvements to the merge variables workflow

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/binaryninja-api#4761]
Very often when reversing, I'll come across patterns like this:

<img width="397" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/41548458/d89e022c-0c66-462c-8adc-b77911573fd2">

There are three `rawString` variables created here which can really just be one. When hitting "merge variable", I am prompted with this dialog:

<img width="400" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/41548458/c6c4231d-e3a9-492d-ab0d-68ebaaf7faaa">

---

None of the things I would want to merge with are even visible in the first scroll. In fact, they are greyed out all the way near the bottom of the list.

There's a few things wrong here, in my opinion:

- There is no way to search the list of variables to merge with.
- The variable I actually want to merge with is almost always listed as a "potentially unsound merge".
  - This means I have to go hunting for it at the bottom of the list, wasting more time in the dialog.

It would be nice if the above were fixed, but in the meantime, I see two lower-effort(?) solutions:

1. If a variable is present on the right hand side of an assignment, and I open the merge dialog with the left hand side selected, show the right hand side at the top.
2. Offer a fast "merge assignment" action to merge the right hand side of an assignment with the left hand side without even opening the dialog.

The latter is basically what I'm trying to do 99% of the time I open the dialog.

**Comment by xusheng6** [comment]
Very nice suggestions!

**Comment by xusheng6** [comment]
The suggestion for search is already mentioned in https://github.com/Vector35/binaryninja-api/issues/3513. Should we close that one in favor of this?

**Comment by plafosse** [comment]
These features will all be present in 3.6.4772.

* Merge Variables Dialog now has a search
* Merge Variables now has suggested merges that are at the top of the list
* A new 'Merge Variables Here' option is available in the menu and hotkey '+' if you're in HLIL/Pseudo-C and you've selected the index of a variable-to-variable assignment.
