### ISSUE TITLE
Wrong synthetic function __builtin_strcpy

### ISSUE THREAD

**Issue by reversing-dev** [Vector35/binaryninja-api#4768]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4654-dev Personal, fc10ae0f
- OS: windows
- OS Version: 11
- CPU Architecture: x86_64

**Bug Description:**
While lifting from `rep movs` to string initialization, `__builtin_strcpy` used instead of `__builtin_strncpy`
![image](https://github.com/Vector35/binaryninja-api/assets/42991292/c1a30f2b-1f5f-485a-af2f-81785c4a311e)
`strcpy` should only have 2 parameters, but here there are 3 (like `strncpy`). Personally, I would prefer `strncpy`.

File: 
[main.zip](https://github.com/Vector35/binaryninja-api/files/13444091/main.zip)

**Comment by xusheng6** [comment]
yeah I have noticed this as well

**Comment by bpotchik** [comment]
Fixed in `3.6.4659-dev`.
