### ISSUE TITLE
define_user_symbol in Rust API broken on Linux

### ISSUE THREAD

**Issue by greaka** [Vector35/binaryninja-api#4774]
**Version and Platform (required):**
- Binary Ninja Version: Version 3.6.4658-dev Personal (2023-11-24 20:35:59)
- OS: Arch Linux
- OS Version: 6.6.1-arch1-1
- CPU Architecture: x64

**Bug Description:**
`binaryview.define_user_symbol()` creates garbled output on Linux. Windows works fine. Not tested on Mac.

**Steps To Reproduce:**
1. install rust
2. compile the code snippet provided in additional information
3. load the plugin in binja
4. open a x86 project
5. run the test function
6. jump to the function
7. check the name in linear view

**Expected Behavior:**
I expect to see my defined name in binja.

![image](https://github.com/Vector35/binaryninja-api/assets/2805834/02f694b3-a44b-4a70-95bf-f53c3f33d7c5)
Test code run on Windows

**Actual Behavior:**
I see garbled text.

![image](https://github.com/Vector35/binaryninja-api/assets/2805834/060d000b-51ff-4b1a-9930-079b677cebec)
Test code run on Linux

**Additional Information:**

Loading the broken bndb on windows shows the same garbled text.

<details>
<summary>Test Code</summary>

```rs
use binaryninja::{
    binaryview::{BinaryView, BinaryViewExt},
    command::{register, Command},
    logger,
    string::BnString,
    symbol::Symbol,
};
use log::{info, LevelFilter};


struct TestCommand;

impl Command for TestCommand {
    fn action(&self, view: &BinaryView) {
        if let Some(func) = view.functions().iter().next() {
            info!("setting fn {:#x}", func.symbol().address());
            let bn_full_name = BnString::new("bn_full_name");
            let bn_short_name = BnString::new("bn_short_name");
            let symbol = Symbol::builder(
                func.symbol().sym_type(),
                func.symbol().raw_name(),
                func.symbol().address(),
            )
                .full_name(bn_full_name)
                .short_name(bn_short_name)
                .create();

            view.define_user_symbol(&symbol);
        }
    }

    fn valid(&self, _view: &BinaryView) -> bool {
        true
    }
}

#[no_mangle]
#[allow(non_snake_case)]
pub extern "C" fn CorePluginInit() -> bool {
    logger::init(LevelFilter::Info).expect("failed to initialize logging");

    register("Diff\\Test", "Test", TestCommand);

    true
}
```

</details>

**Comment by psifertex** [comment]
I assume this issue is only in the Rust API, did you happen to test it in python as well? I'll take a look next week if not to confirm.

**Comment by greaka** [comment]
Assuming this code is equivalent, only the rust api is affected

![image](https://github.com/Vector35/binaryninja-api/assets/2805834/dc5dfe32-19c9-4359-b540-827d6ab3d8b3)

**Comment by KyleMiles** [comment]
While I was in there, I changed the APIs to use `&str`s instead, per #4625...so you may need to update your code.
