### ISSUE TITLE
DebugInfo should have support for Components

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#4777]
Now that the components UI is being enabled by default we should enahnce DebugInfo to be able to support components as such information may be available in debug info files. Specifically, once those API changes are done, we should update the PDB Plugins and DWARF Plugins to leverage the updated API to create the appropriate components.

**Comment by KyleMiles** [comment]
This is completed as of 3.6.4779-dev. We should open new issues to track PDB Import and DWARF Import support for components, if desired.
