### ISSUE TITLE
Copy as big-endian or little-endian

### ISSUE THREAD

**Issue by pgoodman** [Vector35/binaryninja-api#478]
In the raw hex view, it is possible to copy the raw bytes. It would be nice to be able to copy as raw bytes, wit the option of being able to have the copy treat the bytes as big endian or little endian, so that one of the copies performs a byte swap.

**Comment by plafosse** [comment]
By default it already copies as big endian :) Kinda similar to this I added a transform feature "Reverse", which simply reverse the selected bytes (this only exists in a non-public branch). 

Adding to this feature request: "Paste-from" little endian.

**Comment by plafosse** [comment]
thats a pretty good idea too. Want to add another issue?

**Comment by plafosse** [comment]
A plugin should be able to do this so we're probably never going to get around to this, although I think it is a good suggestion.
