### ISSUE TITLE
Selecting any type in the new types browser causes memory leak on binary view 

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#4780]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4667-dev (2dce02db)
- OS: macOS
- OS Version: 14.1.1 (23B81)
- CPU Architecture: M1

**Bug Description:**
There is a memory leak on the binary view object if I select any type in the new types browser

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open any binary
2. Switch to the types sidebar
3. Select any type in it
5. Close the binary
6. Run `get_memory_usage_info` in the Python console and observer the leak

**Expected Behavior:**
No memory leak on the binary view object

**Additional Information:**
I noticed this after I fix https://github.com/Vector35/binaryninja-api/issues/4779

**Comment by negasora** [comment]
Seems like it leaks without selecting a type too. Opening the type browser is enough to trigger it

**Comment by negasora** [comment]
Fixed in `3.6.4817-dev`
