### ISSUE TITLE
Show folders first option in symbols

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4791]
See the title

**Comment by ccarpenter04** [comment]
This is the most intuitive way to order things in my view as well.

**Comment by bpotchik** [comment]
The default sort order is address so folders are sorted by address as well. The folder address comes from the lowest addressed item within the folder. We can look into adding this as an option though.

**Comment by bpotchik** [comment]
Added in `3.6.4694-dev.` The option is disabled by default.
