### ISSUE TITLE
Can not move selection to already created folder in symbols view

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4792]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4690-dev Personal, 135d31cc
- OS: Windows
- OS Version: 11
- CPU Architecture: x86_64

**Bug Description:**
I need to create a new folder in order to make BN know about it. It does not recognise folders already created in older version (at least this is my guess).

<img width="452" src="https://github.com/Vector35/binaryninja-api/assets/109607896/2591ed81-fc77-4f06-9e3e-1ed956c5bca4">

I can share the BNDB in slack.

**Comment by bpotchik** [comment]
Fixed in `3.6.4691-dev`.
