### ISSUE TITLE
Invalid setting when enabling Show Folders First in Symbols UI

### ISSUE THREAD

**Issue by alexrp** [Vector35/binaryninja-api#4794]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4694-dev Personal ( d220dd4)
- OS: Windows
- OS Version: 10.0.23585.1001
- CPU Architecture: x64

**Bug Description:**
`[Settings] Invalid Setting! ui.view.symbols.showFoldersFirst`

**Steps To Reproduce:**
Enable "Show Folders First" in the Symbols UI.

**Expected Behavior:**
No error.

**Comment by bpotchik** [comment]
Fixed on next build!
