### ISSUE TITLE
API tooltip showing hex dump instead of API declaration

### ISSUE THREAD

**Issue by reversing-dev** [Vector35/binaryninja-api#4795]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4692-dev Personal, 86ff8af0
- OS: windows
- OS Version: 11
- CPU Architecture: x86_64

**Bug Description:**
Imported APIs without a thunk while hovering mouse shows hex dump in tooltip instead of API declaration (like parameter name and type).
Example: VirtualFree
![image](https://github.com/Vector35/binaryninja-api/assets/42991292/b388befa-6370-4c87-8677-7235601e28f6)

It should be much helpful to show the declaration.

**Comment by plafosse** [comment]
Marking as duplicate of  #1175
