### ISSUE TITLE
SCC: Macro Stringification

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#48]
_From @plafosse on July 21, 2015 17:49_

_Copied from original issue: Vector35/scc#2_

**Comment by plafosse** [comment]
A possible workaround for the lack of this feature is to run a preprocessor on your source code prior to compiling with SCC some have had success using `clang -E -nostdinc`

**Comment by verylazyguy** [comment]
actually `clang -E -P -nostdinc` to get rid of the "line commands"

**Comment by plafosse** [comment]
This has been obviated by switching to clang for type parsing.
