### ISSUE TITLE
Incorrect `wsprintfW` prototype

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4805]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4707-dev Personal, 3cd0ac3b
- OS: macos
- OS Version: 14.1
- CPU Architecture: arm64

**Bug Description:**
`wsprintfW` function prototype is wrong.

Current: `int32_t (__stdcall* const wsprintfW)(PWSTR param0, PWSTR param1)`
Correct one: `int32_t (__stdcall* const wsprintfW)(PWSTR param0, PWSTR param1, ...)`

`wsprintfA` is also affected.

**Comment by op2786** [comment]
`DbgPrintEx` is also affected in kernel platform.

**Comment by plafosse** [comment]
Wow this was actually a bug in ALL the windows type libraries thanks for pointing that out! Fixed now in 3.6.4719
