### ISSUE TITLE
Focus on filter when typing in select enum dialog

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4807]
I believe that it could be useful if BN automatically focuses in filter field in the select enum dialog when we start to type something. I generally either know the enumeration I'm looking for or I can guess its name. So most of the time whenever I open select enum dialog I start to typing. I'm not sure about current behaviour, looks like when I type `e` it tries to find out a enum member that starts with `e`.

I also noticed that filter field does not have a placeholder text like "Search enumerations"

**Comment by plafosse** [comment]
Fixed in 4.0.4848
