### ISSUE TITLE
Windows kernel driver `IRP_MJ` and `IRP_MN` enumerations missing

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4808]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4709-dev Personal, 715fcd79
- OS: macos
- OS Version: 14.1
- CPU Architecture: arm64

**Bug Description:**
BN does not know about what does `IRP_MJ_DEVICE_CONTROL` or `IRP_MN_QUERY_REMOVE_DEVICE` is.

**Comment by op2786** [comment]
`DO_*` defs are also missing, which is used in device object flags.

https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/ns-wdm-_device_object#do_buffered_io-or-do_direct_io

**Comment by emesare** [comment]
The root issue is the same as #3923 with constants not being added. But frankly these specific ones would likely best be solved upstream, https://github.com/microsoft/wdkmetadata/issues/27 shows an example of turning disparate constants into a real enum, once that is done, they should be picked up.

**Comment by plafosse** [comment]
I fixed these locally without the wdkmetadata > 3.6.4716.

**Comment by op2786** [comment]
That new update also made BN use the typedef instead of structure itself (`PDRIVER_OBJECT` instead of `struct _DRIVER_OBJECT*`) which is a subtle but useful improvement in my opinion because that's how developers uses them in their code mostly. Thank you @plafosse.
