### ISSUE TITLE
Keystroke Refactor

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#481]
Refactor keystroke system more like Helm/Atom/Sublime. This includes both text based search and hierarchal search with a leader key.

**Comment by lucasduffey** [comment]
also: Ctrl+x currently patches with a nop, but for some programs it's used for xrefs.

I've accidentally hit it several times, and it's very easy to miss the fact that you just patched code by accident.

**Comment by plafosse** [comment]
Closing this in favor of a more detail in #92
