### ISSUE TITLE
Inconsistent Edit Behavior When Creating Folders in Symbols View

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4810]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4709-dev Personal
- OS: macos
- OS Version: 14.1
- CPU Architecture: arm64

**Bug Description:**
As shown in the GIF, when we create a folder while filtering, BN does not allow us to rename that folder directly as it does in non-filtered situation. 

![Recording 2023-12-08 at 15 14 00](https://github.com/Vector35/binaryninja-api/assets/109607896/9c1eb785-8106-4348-91cc-3f55238eeb11)

**Comment by bpotchik** [comment]
Fixed in `4.0.4849-dev`.
