### ISSUE TITLE
Multiple BN window corrupts Binary Ninja menu

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4818]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4712-dev Personal, 599e2ad7
- OS: macos
- OS Version: 14.1
- CPU Architecture: arm64

**Bug Description:**
When we have multiple BN instance, Binary Ninja menu have some duplicated entries.

**Steps To Reproduce:**
* Open multiple BN instance
* Click Binary Ninja menu
* See there are multiple entries

**Screenshots:**
<img width="214" src="https://github.com/Vector35/binaryninja-api/assets/109607896/1ce0c4e9-737b-4496-81e1-2b69be8dcfe3">

**Comment by psifertex** [comment]
This is a QT bug and a duplicate issue of https://github.com/Vector35/binaryninja-api/issues/2630
