### ISSUE TITLE
Feature Map

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#482]
Colorized overview bar, perhaps like sublime/atom. View should also show section/segment delineations.

**Comment by lucasduffey** [comment]
similar things for visual reference:
* IDA’s nav bar: https://www.hex-rays.com/products/ida/tech/navbar.shtml
* atom's minimap scrollbar https://atom.io/packages/minimap

**Comment by plafosse** [comment]
Features desired for MVP implementation
[] Select to navigate.
[] Analysis Cursors
[] Code vs Data vs Data Variables
[] Mapped vs Unmapped Memory
[] Library vs non-library code
[] Configurable orientation
[] Current Offset
[] Current viewport

**Comment by bpotchik** [comment]
Added in 1.1.1473-dev.
