### ISSUE TITLE
Binary Ninja should resolve functions imported by ordinal

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4823]
Looks like currently it is not supported.

<img width="669" src="https://github.com/Vector35/binaryninja-api/assets/109607896/e81ee27a-7277-4eca-9abf-f3a493f938fb">

**Comment by psifertex** [comment]
It's absolutely supported in general. We might be missing a type library for that import however or that type library might have some issue. Will double check later and rename this issue if so.

**Comment by plafosse** [comment]
This was fixed a few weeks ago and is fixed on dev 3.6.4740
