### ISSUE TITLE
Restore view state for file does not restores sidebar

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4827]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4718-dev, ca11e60e
- OS: macos
- OS Version: 14.1
- CPU Architecture: arm64

**Bug Description:**
`ui.files.restore.viewState` does not restores the sidebar I've left open in the last session.

**Steps To Reproduce:**
1. Open any database
2. Open Types sidebar
3. Close & reopen the database
4. See sidebar is not restored to Types.

**Expected Behavior:**
I expect it to restore the sidebar I've left open.

**Comment by xusheng6** [comment]
I am not sure we intend to restore the sidebar as well. I will bring it up with the team. @plafosse what do you think about this?

**Comment by fuzyll** [comment]
@op2786 are you still seeing this on the latest 4.0 stable? I _believe_ this predated some of the sidebar changes and I am pretty sure I tested this during our release testing and made sure it worked. But, happy to look into it further if you're still seeing the issue.

**Comment by fuzyll** [comment]
Closing this as I believe it was taken care of in the 4.0 release. We do have a few things left over to do, though, which are currently tracked in #5092.
