### ISSUE TITLE
`CHAR` array rendered differently than `char` array in linear view

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4835]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4723-dev,  5252537
- OS: macos
- OS Version: 14.2
- CPU Architecture: arm64

**Bug Description:**
See screenshots below.

`CHAR` typedef: `typedef char CHAR;`

**Expected Behavior:**
I expect BN to render `CHAR` array like it did for `char` array.

**Screenshots:**
`char pszPath[0x104]`:
<img width="1149" src="https://github.com/Vector35/binaryninja-api/assets/109607896/042d8731-13bf-4dfd-9aa1-0bc9305f64bd">

`CHAR pszPath[0x104]`:
<img width="1168" src="https://github.com/Vector35/binaryninja-api/assets/109607896/5c42864c-ca36-4fc3-a978-871ea499474c">

**Comment by negasora** [comment]
Fixed in `3.6.4741-dev`
