### ISSUE TITLE
Crash in `ParseAutoTypeId` caused by json assertion when parsing NTR `System.Com::IUnknown`

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#4841]
**Version and Platform (required):**
- Binary Ninja Version: > 3.4

`ParseAutoTypeId` inappropriately expects TypeId's to be json parsable, when these can be directly supplied by the user through the API. If you try to view a com type in the type browser it will cause binary ninja to crash.

**Comment by CouleeApps** [comment]
Looks like rapidjson's parse method does not only return parseerror, it also throws a parseexception. It makes you wonder why the return value exists at all.
