### ISSUE TITLE
Use relative file path for bv.file.original_filename

### ISSUE THREAD

**Issue by mbilzor** [Vector35/binaryninja-api#4842]
When a .bndb is created, it sets bv.file.original_filename using the 'absolute' full path to that file.

As a result, if the folder containing the original file and the associated .bndb is renamed or moved, opening the .bndb causes the view to be corrupted.

If the value in bv.file.original_filename was initially set using the location relative to the .bndb, moving then together or renaming an enclosing folder would not cause the view to be corrupted on subsequent loads.

**Comment by xusheng6** [comment]
How is the view "corrupted"?

**Comment by mbilzor** [comment]
Reverts to 'raw' view only. You lose results of linear sweep and any elements that had been added through a custom view. You can reset the bv.file.filename value in the shell, but that does not seem to restore the view elements -- you have to re-run linear sweep and any other analysis.

**Comment by negasora** [comment]
I can't repro this - are you using a custom view or other plugin that depends on the original file being in the same place? Are there any warnings or errors in the log?

**Comment by mbilzor** [comment]
Hi Josh,

  That’s right – it’s a custom view that needs to read some data from the original file; that’s where this cropped up. No errors or warnings in the log; it just goes to a Raw view instead of using the custom view. This issue appears when you rename a folder anywhere along the containing path, or move the containing folder, since then the bv.file.original_filename in the database is no longer is correct.

  Another solution to the issue would be to leave bv.file.original_filename as is, but add a new field bv.file.relpath_to_original, which starts from the current .bndb location (i.e., how to get from the .bdnb to the original file using just the relative path, which might be as simple as ‘.’, but could also include ‘../../’, etc.).

Best regards,
Mike

From: Josh F ***@***.***>
Reply-To: Vector35/binaryninja-api ***@***.***>
Date: Tuesday, January 2, 2024 at 12:38 PM
To: Vector35/binaryninja-api ***@***.***>
Cc: "Bilzor, Mike" ***@***.***>, Author ***@***.***>
Subject: [EXT] Re: [Vector35/binaryninja-api] Use relative file path for bv.file.original_filename (Issue #4842)

APL external email warning: Verify sender ***@***.*** before clicking links or attachments




I can't repro this - are you using a custom view or other plugin that depends on the original file being in the same place? Are there any warnings or errors in the log?

**Comment by negasora** [comment]
If you want to read data from the original file, you can `bv.read(...)` with `bv` being the `Raw` binary view - file contents (at the time of database creation) are stored inside the bndb. Changing `original_filename` from absolute to relative would break when moving the bndb without moving the original file among other things.

**Comment by mbilzor** [comment]
Hi Josh,

  Thanks for the note; I appreciate you working on this. I understand the comment about getting data bytes using bv.read() from the raw view, but that doesn’t solve the issue I’m experiencing. The issue is that BN only creates the Raw view, and it destroys the custom view (no longer available in the .bndb), as well as the auto-analysis work that went into it, including a linear sweep that can take hours to complete. You can access the raw bytes, sure, but your custom view gets destroyed in the process, so there’s nothing useful to do with said raw bytes 😊.

  I agree that moving only the .bndb and not the original file would cause an issue with relative addressing, but that it easily solved by checking both. If opening with the absolute path fails, you try opening with the relative path, or vice versa. Relative addressing is more robust because it handles renaming of any folder in the path, and also handles moving or copying a folder containing both the original file and the .bndb to another location (a common use case).

  Would love to see this kept open if at all possible, for those doing work with custom views on embedded images.

Best regards,
Mike

From: Josh F ***@***.***>
Reply-To: Vector35/binaryninja-api ***@***.***>
Date: Tuesday, January 2, 2024 at 2:57 PM
To: Vector35/binaryninja-api ***@***.***>
Cc: "Bilzor, Mike" ***@***.***>, Author ***@***.***>
Subject: [EXT] Re: [Vector35/binaryninja-api] Use relative file path for bv.file.original_filename (Issue #4842)

APL external email warning: Verify sender ***@***.*** before clicking links or attachments




If you want to read data from the original file, you can bv.read(...) with bv being the Raw binary view - file contents (at the time of database creation) are stored inside the bndb. Changing original_filename from absolute to relative would break when moving the bndb without moving the original file among other things.

**Comment by negasora** [comment]
Does your custom binary view constructor not get called at all when reopening the bndb?

**Comment by mbilzor** [comment]
Yes, it does get called whenever the .bndb is opened. However, if the original file is no longer at bv.file.original_filename, only a Raw view is created, and only a Raw view exists thenceforth in the database.

From: Josh F ***@***.***>
Reply-To: Vector35/binaryninja-api ***@***.***>
Date: Tuesday, January 2, 2024 at 3:49 PM
To: Vector35/binaryninja-api ***@***.***>
Cc: "Bilzor, Mike" ***@***.***>, Author ***@***.***>
Subject: [EXT] Re: [Vector35/binaryninja-api] Use relative file path for bv.file.original_filename (Issue #4842)

APL external email warning: Verify sender ***@***.*** before clicking links or attachments




Does your custom binary view constructor not get called at all when reopening the bndb?

**Comment by fuzyll** [comment]
My understanding is that the Raw view should be constructed first, so your custom view should be able to read from that. This would obviate the need for accessing the original file at all and would prevent your custom view from breaking when it can't find it. That's why @negasora is suggesting `bv.read()` as an answer to your problem, rather than changing the mechanics of `original_filename`.

Is there something we're missing that makes this a bad suggestion?

**Comment by mbilzor** [comment]
I’m probably just not understanding the load process in full detail.

I’ll get back to you later if I can put together a more detailed description of the issue.

Thanks,
Mike

From: Alexander Taylor ***@***.***>
Reply-To: Vector35/binaryninja-api ***@***.***>
Date: Tuesday, January 2, 2024 at 4:20 PM
To: Vector35/binaryninja-api ***@***.***>
Cc: "Bilzor, Mike" ***@***.***>, Author ***@***.***>
Subject: [EXT] Re: [Vector35/binaryninja-api] Use relative file path for bv.file.original_filename (Issue #4842)

APL external email warning: Verify sender ***@***.*** before clicking links or attachments




My understanding is that the Raw view should be constructed first, so your custom view should be able to read from that. This would obviate the need for accessing the original file at all and would prevent your custom view from breaking when it can't find it. That's why @negasora<https://github.com/negasora> is suggesting bv.read() as an answer to your problem, rather than changing the mechanics of original_filename.

Is there something we're missing that makes this a bad suggestion?
