### ISSUE TITLE
Minor potential typo in settings

### ISSUE THREAD

**Issue by lethalbit** [Vector35/binaryninja-api#4848]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4733-dev Personal (2bddb4e8)
- OS: Arch Linux
- OS Version: N/A
- CPU Architecture: amd64

**Bug Description:**
There is a minor typo under the `file.navigation` setting, category, for `ui.files.navigation.preferMain` under an `en_US.UTF-8` locale the option title reads "Navigate to Programmer's Main"

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Go to `Edit -> Preferences`
2. In the search filter enter `ui.files.navigation.preferMain`
3. Observe the potential typo

**Expected Behavior:**
It should probably be "Navigate to Programs Main".

**Screenshots:**
![image](https://github.com/Vector35/binaryninja-api/assets/201479/0c790167-78c4-4f5d-8fde-345ab0e3fd95)

**Comment by psifertex** [comment]
So that's actually intentional -- "program main" might actually refer to the entry point of most binaries. In this case we really do mean "Programmer's Main" as it's the "main" as written by the actual programmer.

**Comment by lethalbit** [comment]
Yeah okay I thought that might be the case but I wasn't entirely sure, sorry about that!

**Comment by psifertex** [comment]
No worries! Easy to close issues are my favorite. 😉
