### ISSUE TITLE
Memory map no longer uses mono font

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/binaryninja-api#4851]
<img width="480" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/41548458/b9e21ae3-8df7-4893-95d6-b035bbb408f7">

Binary Ninja 3.6.4738-dev, 8ff0a04d, macOS 14.2 (arm64)

**Comment by negasora** [comment]
Fixed in `3.6.4739-dev`
