### ISSUE TITLE
Unclear Deprecation Warning "__init__ is deprecated as of 3.4.3997"

### ISSUE THREAD

**Issue by utkonos** [Vector35/binaryninja-api#4853]
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4526
- OS: macOS
- OS Version: 14.2.1
- CPU Architecture: x64

**Bug Description:**
On instantiation, StructuredDataView raises a warning. But the message is unclear as to what should be changed. The two options listed in the message do not seem related to the executed code.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open Python console
2. Select the address of the first section header
3. Run this python `binaryninja.StructuredDataView(bv, 'Section_Header', here)`
4. See warning:

```none
>>> binaryninja.StructuredDataView(bv, 'Section_Header', here)
<console>:1: DeprecatedWarning: __init__ is deprecated as of 3.4.3997. Use TypedDataAccessor or DataVariable.value instead.
<StructuredDataView type:Section_Header size:0x28 address:0x400200>
```

**Expected Behavior:**
No warnings or errors.

**Screenshots:**
<img width="501" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/2775739/6afb44f6-c35b-4790-a28d-73fa3d7b513c">

**Comment by utkonos** [comment]
There is a second one that is similar.

```none
>>> image_base = bv.start
>>> dos_header = binaryninja.StructuredDataView(bv, 'DOS_Header', image_base)
<console>:1: DeprecatedWarning: __init__ is deprecated as of 3.4.3997. Use TypedDataAccessor or DataVariable.value instead.
>>> dos_header.e_lfanew.value
/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/binaryview.py:9253: DeprecatedWarning: __init__ is deprecated as of 3.4.3997.
  return StructuredDataValue(ty, self._address + offset, value, self._endian)
```

<img width="522" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/2775739/583d93e2-b2df-4ae7-b91b-5d70de13b44f">

**Comment by xusheng6** [comment]
You do not need to use the `StructuredDataView` yourself. You can simply get the desired output by:

```
>>> bv.get_data_var_at(0x140000000).value['e_lfanew']
240
```

**Comment by xusheng6** [comment]
That deprecation warning actually tells you the class `StructuredDataView` is deprecated and should no longer be used. Sorry that it is not very obvious. 

I am closing this for now. Please fee free add more information to this, if any

**Comment by utkonos** [comment]
Thanks for the quick response. Can a deprecation note be added to the docs?

https://api.binary.ninja/binaryninja.binaryview-module.html#binaryninja.binaryview.StructuredDataView
