### ISSUE TITLE
hex data patch not function?

### ISSUE THREAD

**Issue by bb33bb** [Vector35/binaryninja-api#4857]
**Version and Platform (required):**
- Binary Ninja Version: [e.g. 3.2.4000-dev] (if version is stable, please also test the latest development build via the "Update Channel" option)
- OS:manjaro
- OS Version: 
- cat /etc/lsb-release
          DISTRIB_ID="ManjaroLinux"
          DISTRIB_RELEASE="23.1.2"
          DISTRIB_CODENAME="Vulcan"
          DISTRIB_DESCRIPTION="Manjaro Linux"

- CPU Architecture: x64

https://github.com/Vector35/binaryninja-api/assets/5463104/4952fd1d-4540-4a63-9333-4cb55e1b5f99

**Bug Description:**
just see the video
I dont know it is my software problme or its the official tiny bug

**Comment by negasora** [comment]
Is that address not backed by a file? If so, the issue is described by: https://github.com/Vector35/binaryninja-api/issues/920

Can you write to memory that is backed by a file if so?

**Comment by bb33bb** [comment]
I am really dont know this , I am going to close this issue if not apliable here.
Thanks for your help
