### ISSUE TITLE
Memory map no longer shows all the digits by default

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#4862]
I added code to ensure the widget always resizes the columns so that the digits are all visible. However, it is broken after we upgrade to Qt 6.6.1

**Comment by xusheng6** [comment]
This affects macOS, and does not affect Windows. I did not test on Linux

**Comment by xusheng6** [comment]
It now looks like this, exactly like what it was before my changes:

![Screenshot 2024-02-08 at 10 33 50 AM](https://github.com/Vector35/binaryninja-api/assets/94503187/aa719820-21d6-4b78-900c-702e93783f66)

**Comment by plafosse** [comment]
Fixed in 4.0. 4846
