### ISSUE TITLE
BinaryView::GetAutoStart() not exposed in C++/Python API

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#4863]
Just noticed that we have a `BinaryView::GetAutoStart()` function which returns the minimum value of the starts of the auto segments. This is important for cases where the user adds a segment before the first auto segment. This should be exposed so the debugger can also use it

**Comment by bpotchik** [comment]
The internal `GetAutoStart` API has been removed and replaced by `GetImageBase`.

Fixed in `4.2.5758`.
