### ISSUE TITLE
Setting view does not hide/disable settings when ignored scope is selected

### ISSUE THREAD

**Issue by negasora** [Vector35/binaryninja-api#4873]
**Version and Platform (required):**
- Binary Ninja Version: `3.6.4753-dev`

**Bug Description:**
Some settings (like `ui.font.app.name`) aren't hidden/disabled when unrelated settings scopes are selected

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open a binary
2. Go to settings view
3. Select the `Resource` scope
4. Notice that `ui.font.app.name` is still present and can be changed

**Expected Behavior:**
Settings that ignore certain scopes do not show up or are disabled when those scopes are selected

**Comment by bpotchik** [comment]
You can add `@resource` to the filter to filter settings. The scope selection is not intended to also filter the settings

**Comment by fuzyll** [comment]
What @negasora is asking for here is, I think, actually two things:

The first is more of a feature request in that it would be nice if options (like `ui.font.app.size` that can't be changed in e.g. resource settings) were more obviously 'disabled' in that scope by being grayed out or filtered out entirely.

The second is that certain settings (like `ui.font.app.name`) which can't be set in those scopes can still be changed while in that scope. They do, _correctly_, state that they're being changed in "User" and not "Resource". But, it's still somewhat surprising that they can be changed at all.

For example, in this screenshot, I am in the resource settings, and cannot change the antialiasing style (correctly, although it does look like I can change it). But, I did just change the font, which will apply to more than just this file (again, correctly, although it's strange that I can change it from here at all).

<img width="674" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/607452/7eac64c8-f9ad-4dfe-86d0-09b62fdb531a">

I don't think this should be a high priority issue, but I do think it would be worth addressing in some way.

**Comment by bpotchik** [comment]
It's very intentional to be able to see the entire set of settings applied for a particular file at the same time, even when a scope is selected. Also, I really do not want to remove the ability to edit inherited settings from a higher level when a particular scope is selected. This is actually useful in numerous situations.

**Comment by fuzyll** [comment]
Are you able to expand on your rationale for both cases?

The Settings tab seems to be modeled closely after Visual Studio Code's, which filters out settings that aren't available to be changed (and the section, too, if it no longer contains anything). This is most visible with the entire Security section when you switch from the User scope to the Workspace scope.

What works for Visual Studio Code won't necessarily work for Binary Ninja. But, I'd like to understand what makes our user experience so different that we have the opposite design in this specific case.

**Comment by fuzyll** [comment]
We talked about this internally today and, I believe, came to a consensus?

The scope buttons in the Settings tab should only show settings that are available in their respective schema. This means that the settings available, when clicking "Resource", should match what Open with Options shows.

**Comment by bpotchik** [comment]
My mistake, the font related settings were not passing the scope to the core. Fixing this disallows the user font settings from being modified while the resource scope is selected. Fixed in 4759.

**Comment by bpotchik** [comment]
Scope based schema filtering is added in 4760.

**Comment by fuzyll** [comment]
Thanks @bpotchik, works great!
