### ISSUE TITLE
Total Bytes column content not visible in Symbols View

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4875]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4756-dev, a10935ab
- OS: macos
- OS Version: 14.2
- CPU Architecture: arm64

**Bug Description:**
Why does total bytes does not shown in the screenshot below even if there is enough space?

<img width="437" src="https://github.com/Vector35/binaryninja-api/assets/109607896/d5014e4b-22ea-4b2e-92f2-a26048debd32">

**Comment by psifertex** [comment]
Does it show up if you scroll to the right? Still super annoying, but I suspect it's just wider than the window and the numbers are right-aligned.

**Comment by bpotchik** [comment]
Fixed in `3.6.4762-dev`.
