### ISSUE TITLE
"ui.view.symbols.seamlessNavigation" causes spurious navigation events

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#4882]
3.6 dev

If you have the `ui.view.symbols.seamlessNavigation` setting it will occasionally cause spurious navigation events while navigating using the crossReference pane.  

Repro steps:
1. Click on an code reference to a IAT or PLT entry
2. Double click the code reference in the cross references pane
3. Notice that it navigates to the function start instead of the cross reference

**Comment by bpotchik** [comment]
Fixed in `3.6.4774-dev`.
