### ISSUE TITLE
Recognize `_security_init_cookie` in windows kernel drivers

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4887]
Currently BN can not recognize `_security_init_cookie` in windows drivers. It would be nice if BN recognize it.

**Comment by fuzyll** [comment]
Related to #3290.

**Comment by plafosse** [comment]
We do support recognition of `_security_init_cookie ` in drivers, however the removal these checks is tracked by #3290 as Alex noted/
