### ISSUE TITLE
System types automatically expands when types sidebar opened first time

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4888]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4764-dev, 1e8f4a9b
- OS: macos
- OS Version: 14.2
- CPU Architecture: arm64

**Steps To Reproduce:**
1. Open any binary
2. Open types sidebar
3. See System Types is expanded

**Expected Behavior:**
I expect it to be collapsed, I believe it effects the performance of the opening time of types sidebar.

**Comment by ccarpenter04** [comment]
At the very least it's an annoying behavior.

**Comment by CouleeApps** [comment]
This _was_ intended behavior, but it sounds like it has annoyed a number of people. Proposed new behavior: Remember if user/system types is expanded and then only expand them if they were expanded the previous time. This will likely be done via QSettings and therefore not specific to each file.

(In case you're curious why it was intended: internal tests showed some people getting confused when opening fresh binaries. The User Types list was empty and they couldn't figure out where the types were.)

**Comment by CouleeApps** [comment]
This was addressed recently: now System Types will remember if you had expanded/collapsed it previously and will only auto-expand if you had expanded it.
