### ISSUE TITLE
linear sweep

### ISSUE THREAD

**Issue by lucasduffey** [Vector35/binaryninja-api#489]
open raw binary - run a linear sweep and automagicly dissemble like ida.

**Comment by psifertex** [comment]
Umm, it does? Just open the file and hit `p` wherever you want to disassemble. What more were you looking for?

**Comment by lucasduffey** [comment]
ida automatically identifies functions and dissembles it from a binary blob. 

"c" will define stuff as code, "p" defines as function. binja doesn't yet support marking stuff as code with "c". I think this is kind of related.

Example: if you unpack a binary blob from a malware sample, you have to manually find the functions and then hit "p" in binja. In ida it attempts to find the functions and automatically dissembles them.

**Comment by lucasduffey** [comment]
" when we've got the confidence system built in we will include linear sweep. Same thing with the jump table plugin.".

Seems like linear sweap is the feature im talking about.

**Comment by ltfish** [comment]
+1 on this.

> Umm, it does? Just open the file and hit  p  wherever you want to disassemble. What more were you looking for?

This really sounds like a troll to me...

**Comment by ltfish** [comment]
+1 on this.

Removed my previous comment since I didn't see the following sentence: "when we've got the confidence system built in we will include linear sweep. Same thing with the jump table plugin"

**Comment by lucasduffey** [comment]
temporary workaround plugin: https://github.com/Manouchehri/binaryninja-radare2

**Comment by psifertex** [comment]
Other helpful plugins that do linear sweep:
https://github.com/lstotch/linsweep
http://fuzyll.com/2017/better-living-through-function-detection/

**Comment by bpotchik** [comment]
Linear Sweep (BETA) feature now in Binary Ninja Build 890.
