### ISSUE TITLE
Types using inheritance don't properly import from Type Librarires

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4890]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4764-dev, 1e8f4a9b
- OS: macos
- OS Version: 14.2
- CPU Architecture: arm64

I have a binary that uses `IDebugClient5` which according to current type definition inherites from `IUnknown_1`.  (According to MSDN it should inherit from `IDebugClient4` but that is another story)

This is what I got in decompiler output when code tries to use `DebugClient5->QueryInterface` function. Which is actually defined in `IUnknown_1`.

<img width="776" src="https://github.com/Vector35/binaryninja-api/assets/109607896/c4196c82-2e55-4133-970a-4d3d3d196e86">

So there is something wrong with these definitions. When I check out the type looks like `IDebugClient5` does not inherites from `IUnknown_1` correctly. Show inherited members option is enabled in screenshot below:

<img width="460" alt="Screenshot 2024-01-12 at 15 58 53" src="https://github.com/Vector35/binaryninja-api/assets/109607896/160b29e0-4aa6-4d07-82d8-d15aba7419d0">

I guess `IDebugClient5` should have `QueryInterface`, `AddRef` and `Release` member inherited from `IUnknown_1` but it does not so the decompiler output is not show correct function call.

I guess this could also affect the other structures too.

Could be related to #4139.

**Comment by plafosse** [comment]
I haven't been able to verify if this is indeed a problem but in the win32metadata source that is not the case: 
<img width="880" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/10556585/4b5a9940-d1ad-46ad-9cfc-3877c84e602e">

**Comment by plafosse** [comment]
This should be fixed in 3.6.4794
