### ISSUE TITLE
Enhancements to the merge variable dialog

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#4896]
[ ] Search in the variable list (https://github.com/Vector35/binaryninja-api/issues/3513)
[ ] Fix resizing issue for the current selected variable (https://github.com/Vector35/binaryninja-api/issues/4886)

Related to https://github.com/Vector35/binaryninja-api/issues/3640

**Comment by xusheng6** [comment]
Also related to https://github.com/Vector35/binaryninja-api/issues/4761

**Comment by plafosse** [comment]
These features will all be present in 3.6.4772.

* Merge Variables Dialog now has a search
* Merge Variables now has suggested merges that are at the top of the list
* A new 'Merge Variables Here' option is available in the menu and hotkey '+' if you're in HLIL/Pseudo-C and you've selected the index of a variable-to-variable assignment.
