### ISSUE TITLE
Add init_array/fini_array entries into the list of entry points

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#4897]
Otherwise, reversers can easily miss user code. 

This is blocked on https://github.com/Vector35/binaryninja-api/issues/1180

P.S.: I think we should somehow treat the vanilla entry point (i.e., the one we currently report) in a different way, because there are still many cases that people want the vanilla entry point, rather than a list of user code starts. Maybe we need two APIs, `entry_point` and `user_code_starts`, where the second one is a list and it always contain the first one

**Comment by williballenthin** [comment]
TLS callbacks are another class of "entry points" that could be listed, too. [IDA has done this for a long time](https://hex-rays.com/blog/tls-callbacks/) (for example). However, in my experience, TLS callbacks are not widely used to invoke malicious nor interesting code.

**Comment by xusheng6** [comment]
> TLS callbacks are another class of "entry points" that could be listed, too. [IDA has done this for a long time](https://hex-rays.com/blog/tls-callbacks/) (for example). However, in my experience, TLS callbacks are not widely used to invoke malicious nor interesting code.

Interestingly, in CTF challenges, I think TLS function is more popular than init_array. Maybe malware authors use init_array more?

Binary Ninja actually finds and names the TLS functions like TLS_XXXX. We should do something similar to the init_array functions as well.

Btw, does capa do anything for TLS/init_array functions? It would be nice if it can detect, say, there is a non-trivial function in it, and attentions are needed for it.

**Comment by xusheng6** [comment]
Another user suggested that we could give these functions different names so they become easier to spot, e.g., init_func_1.

A relevant file that has a lot of such fini functions: 
[warp_jump.zip](https://github.com/Vector35/binaryninja-api/files/14478397/warp_jump.zip)

**Comment by plafosse** [comment]
This issue is solved but https://github.com/Vector35/binaryninja-api/issues/1180 still needs to be done.
