### ISSUE TITLE
Add an instruction_pointer property to Architecture

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#490]
The `Architecture` has a few properties for things like stack pointer and link register, so that Binary Ninja knows what register to use for things such as pops and pushes. However, there does not seem to be a property for identifying the instruction pointer, and some architectures allow for direct write access to that register.

Since there is no way to specify this to Binary Ninja, behavior such as this occurs on said architectures: 
![image](https://cloud.githubusercontent.com/assets/5834130/18717547/42bdcf70-7fee-11e6-9249-06c69c205eb4.png)

If it were possible to say `Architecture.instruction_pointer = 'pc'`, then Binary Ninja could know that a write to this register is an implicit branch. This would simplify architecture plugin development, because a developer would no longer have to implement functionality to identify whether a move instruction was actually a branching instruction.

**Comment by plafosse** [comment]
Unfortunately, adding this functionality would vastly increase the complexity of all analysis. For instance now the "set_register" command can actually cause a jump. Additionally reads/writes to/from PC function differently on each architecture, and can vary by context. 

Instructions which can write directly to PC should always special case the instruction to contain a jump/branch/ret instruction depending on context.

Our official statement is, "It is the responsibility of the Architecture author to describe how reads and writes to PC happen".

**Comment by joshwatson** [comment]
If there were a sad reaction I would use it :(
