### ISSUE TITLE
Keybindings menu says Ctrl/Meta for Cmd/Ctrl on macOS

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#4903]
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4256
- OS: macOS
- OS Version: 14
- CPU Architecture: M1

**Bug Description:**
The keybindings menu says things like "Select All" is "Ctrl+A", but I use macOS and it is actually Cmd+A. The view needs to account for our reconfiguring which key is considered which on macOS.

**Steps To Reproduce:**
1. Open keybindings menu
2. Look at any keybinding
3. Despair!

**Expected Behavior:**
I expected keybinding descriptions to match my keyboard

**Screenshots:**
<img width="905" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/711973/b06c4ef5-7131-4425-8993-9ef45fd9795d">

**Additional Information:**
The popup that actually accepts the keybinding uses the proper cmd symbol (⌘)

**Comment by 0cyn** [comment]
Resolved in **dev builds >= 4.1.4924**
