### ISSUE TITLE
show_*_report should probably have a save button

### ISSUE THREAD

**Issue by dfraze** [Vector35/binaryninja-api#491]
I think the show_*_report APIs should allow us to save the output.

**Comment by plafosse** [comment]
Hmm, it would be nice to save as text, MD or HTML. But the MD we just be converted to HTML. So we'll need to keep around the original, while the view is open.

**Comment by dfraze** [comment]
Maybe a callback? We've got the data used to build the report (because we passed it to you...), but no way to know the user clicked the save button.

**Comment by plafosse** [comment]
Added as of v1.1.1435
