### ISSUE TITLE
Manage Plugins page shows the last founded plugin if there is no plugin found

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4910]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4774-dev, 20b49d1e
- OS: macos
- OS Version: 14.2
- CPU Architecture: arm64

**Steps To Reproduce:**
1. Open Manage Plugins
2. Search for my_test
3. See it shows ripr plugin on the right side

**Expected Behavior:**
I expect right side to be empty

**Comment by psifertex** [comment]
This is resolved in builds >= 4781. An empty search resets to an empty plugin.
