### ISSUE TITLE
LogView::updateTimerEvent() makes UI un-usable during analysis

### ISSUE THREAD

**Issue by ndrewh** [Vector35/binaryninja-api#4911]
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4526
- OS: macOS
- OS Version:
- CPU Architecture: x64

**Bug Description:**
UI takes 2-3 seconds to respond to clicks while processing analysis

I sampled the process, and it turns out LogView::updateTimerEvent() is taking up more than half of the main-thread execution time.

**Steps To Reproduce:**
1. Load a large binary
2. While still processing, open the Logs view
3. Try navigating in the code view

**Expected Behavior:**
UI responds instantly

**Attachments**
[sample (somewhat redacted)](https://github.com/Vector35/binaryninja-api/files/13964584/binja-log-reload.txt)

**Comment by psifertex** [comment]
Could you please if this same behavior occurs on the latest dev?  You can install dev and stable side-by-side to make testing easier, simply rename one of the bundles.

**Comment by bpotchik** [comment]
Just curious have you modified the `ui.log.maxSize` setting?

**Comment by ndrewh** [comment]
reproduced on 3.6.4780-dev, ui.log.maxSize is the default (10000). here's a sample
[sample-dev.txt](https://github.com/Vector35/binaryninja-api/files/13998835/sample-dev.txt)

**Comment by ndrewh** [comment]
You can DM me for the binary, but there's nothing weird about it. It's just a 30MB Mach-O extracted from a dyld shared cache. The logs are filled with a variety of warnings (LLIL_UNDEF, indirect branch too many targets, etc.)

**Comment by psifertex** [comment]
Yeah, if you can send the file to binaryninja@vector35.com that would be appreciated.

**Comment by negasora** [comment]
This was fixed in `4.2.6132-dev`
