### ISSUE TITLE
Detect module names for imported functions for Mach-O binaries

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4925]
**What is the feature you'd like to have?**
I would like to know which module exports a imported function. Looks like currently it is not supported.

<img width="661" src="https://github.com/Vector35/binaryninja-api/assets/109607896/d2138b70-c452-4ed2-bfb1-1ea6c3a7064e">

**Comment by xusheng6** [comment]
Duplicate of https://github.com/Vector35/binaryninja-api/issues/2385
