### ISSUE TITLE
BN focuses on structure itself when try to navigate a structure member

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4929]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4783-dev, 6fc13294
- OS: macos
- OS Version: 14.2
- CPU Architecture: arm64

**Bug Description:**
See the title.

**Steps To Reproduce:**
1. Have a database which have a structure for testing
2. In linear view, try to navigate a member of that structure
3. Now try to press `Y` or `N`
4. See you changing the type or name for the structure itself, not the member

**Expected Behavior:**
I'm not sure if this is intended behaviour but I expected BN to focus on the member. 

**Additional Information:**
I noticed this issue when I try to navigate to a incorrect structure member in order to undefine it with `U`.

**Comment by psifertex** [comment]
I believe this is intended behavior but one of my coworkers might correct me and reopen. Navigation only takes you to the location. You must separately focus the specific item if you want to modify it instead of the default for that line of analysis.
