### ISSUE TITLE
Automatically set function prototype if a pointer set to a known function in loaded type libraries

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4930]
Let's say I have a pointer variable and I renamed it to `CreateFileA`. It would be useful if BN check if it have a function named `CreateFileA` in currently loaded type libraries. If there is one, it should set the variable type to that function prototype.

**Comment by xusheng6** [comment]
Duplicate of https://github.com/Vector35/binaryninja-api/issues/3635

Also relevant to https://github.com/Vector35/binaryninja-api/issues/2773
