### ISSUE TITLE
Auto set variable name for automatically detected strings

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4934]
Basically I want BN to rename these variables according to the string. Of course with some kind of ruleset. Let's say first 10 character of the string, without unnecessary `_` and space like characters.

<img width="680" src="https://github.com/Vector35/binaryninja-api/assets/109607896/b8347edd-006b-482c-b078-b9b098330944">

**Comment by psifertex** [comment]
Duplicate of #2967
