### ISSUE TITLE
Manage plugin page stars differs on macos and windows

### ISSUE THREAD

**Issue by blue-devil** [Vector35/binaryninja-api#4936]
**What is the feature you'd like to have?**
Hello. On **manage plugin** page, plugins have GitHub star count.  On windows "star" is yellow but on macos it is empty. macos version also should be like windows one/

**Is your feature request related to a problem?**
No, only GUI enhancement

**Are any alternative solutions acceptable?**
No

**Additional Information:**
It is just trivial but I wanted to add

With pictures it is more easy to tell: 

On windows:
![star-win](https://github.com/Vector35/binaryninja-api/assets/10853207/c6345c6d-9e46-4b3b-b802-c02c4bdb2f90)

On macos:
<img width="864" alt="star-mac" src="https://github.com/Vector35/binaryninja-api/assets/10853207/f53ed79e-ba01-451f-8928-1885e6758188">

**Comment by fuzyll** [comment]
We're asking Qt to render "⭐" (White Medium Star, U+2B50). Our default font, Inter, does not have a glyph for this. On Windows, it appears to fall back to Segoe UI Emoji to draw this. On macOS, it picks a different font.

There are three paths forward:

1. Draw this glyph with the user's emoji font, which will probably result in something closer to what users expect to see.
2. Draw an icon here instead so it's consistent across platforms.
3. We close this entirely after other changes that replace the usage of GitHub stars with better statistics.

**Comment by blue-devil** [comment]
I go for option two. A small png/svg icon will consistent on all platforms.

**Comment by psifertex** [comment]
As the person who committed (pun intended) this font crime, I went with #4. Find a star that exists in the font we ship. Not triggering a full build for it but the next build that goes out will use the ★ character instead which is included in our font and as an added bonus will be more easily theme-able.
