### ISSUE TITLE
Add creation date to project files/folders

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#4938]
We were not able to completely implement every Projects feature we wanted before getting it merged to `dev` yesterday.

This issue tracks adding the creation date to files and folders within a project so you can see and sort them in the project items table.

**Comment by negasora** [comment]
File creation date added in `3.6.4804-dev`

**Comment by negasora** [comment]
Unsure if we want folder creation date, since that's not even tracked on the server right now
