### ISSUE TITLE
log_debug does not display any output

### ISSUE THREAD

**Issue by polsab** [Vector35/binaryninja-api#494]
Plugin dev debugging mode is enabled.

**Comment by joshwatson** [comment]
Which platform are you on? Did you try running binja from the command line with `-d` or `--debug`?

I just tried it on Windows 10 with 1.0.dev-68 Personal and seem to have the same issue, even with `-d` or `--debug`. `log_info` works just fine, but `log_debug` does not display in the log.

**Comment by plafosse** [comment]
If you -e -d it will log debug output to the console

**Comment by joshwatson** [comment]
That behavior is not observed on Windows 10; I tried `-e` as well, but it doesn't work.

**Comment by polsab** [comment]
1.0-dev-577 on OS X. -e -d doesn't work either. Other log_xxx functions work fine.

**Comment by psifertex** [comment]
Just double checked on both MacOS and Windows 10 just now on `1064` and looks like it works. If still able to reproduce, please re-open the ticket. 

Note that on windows, `-e` does not output to stderr which is a separate issue, but `-l log.txt` can be used instead and should work fine.
