### ISSUE TITLE
Binary Ninja project extension association broken on macOS/Windows

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#4941]
We were not able to completely implement every Projects feature we wanted before getting it merged to dev yesterday.

This issue tracks macOS and Windows file associations with Binary Ninja project files (`.bnpr` and `.bnpm`). It appears that, in some cases, this either doesn't get added or breaks. We haven't yet been able to figure out the exact circumstances in which it happens, though.

**Comment by negasora** [comment]
The file associations should be set up for fresh installs, but existing clients updating won't have them

**Comment by CouleeApps** [comment]
For macOS specifically, you can run the following to re-scan for file associations:

    /System/Library/Frameworks/CoreServices.framework/Versions/Current/Frameworks/LaunchServices.framework/Versions/Current/Support/lsregister -f -R -trusted "/Applications/Binary Ninja.app"

This is not currently run automatically on update.

**Comment by psifertex** [comment]
Documentation has been [updated](https://dev-docs.binary.ninja/guide/troubleshooting.html#linux-file-assocations) to cover manually updating the associations for each OS.
