### ISSUE TITLE
Clicking "Analyze" in the project browser should prompt if an analysis database already exists

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#4942]
We were not able to completely implement every Projects feature we wanted before getting it merged to `dev` yesterday.

This issue tracks the fact that, right now, if you right-click and choose "Analyze" on a project file, it will *always* create a new `.bndb`. This is surprising to users when they already have an analysis database for that file available in the project. We should detect this case and give the user the option to either open the existing database *or* create a new one (which is, sometimes, what you want).

**Comment by negasora** [comment]
Added in `4.0.4828-dev`
