### ISSUE TITLE
Opening project browser with lots of files is slow

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#4946]
We were not able to completely implement every Projects feature we wanted before getting it merged to `dev` yesterday.

This issue tracks the fact that opening the project browser with a project that has a very large number of files is slow.

**Comment by negasora** [comment]
Load time is improved in `3.6.4820-dev`, but could still be better

**Comment by negasora** [comment]
This is definitely good enough for now, if people run into issues with load performance, separate issues should be opened
