### ISSUE TITLE
Simplify LLIL_PUSH lifting for easier use/def analysis

### ISSUE THREAD

**Issue by ek0** [Vector35/binaryninja-api#4947]
I noticed `LLIL_PUSH` is lifted as follow during LLIL SSA lifting (transferring the pattern to all subsequent ILs)
```
  54 @ 01ff105a  [rsp#15 - 8].q = rsp#15 @ mem#22 -> mem#23
  55 @ 01ff105a  rsp#16 = rsp#15 - 8
```
When it could be lifted like this, as state in [Intel documentation algorithm](https://www.felixcloutier.com/x86/push#operation):
```
  54 @ 01ff105a  rsp#16 = rsp#15 - 8
  55 @ 01ff105a  [rsp#16].q = rsp#15 @ mem#22 -> mem#23
```
Changing it so would make it trivial to actually optimize constructs such as:
```
  44 @ 01fe30ae  [rsp#11 - 8].q = zx.q(0x7ef79a79) @ mem#17 -> mem#18
  45 @ 01fe30ae  rsp#12 = rsp#11 - 8
  46 @ 01fe30b3  [rsp#12].q = rsi#0 @ mem#18 -> mem#19
```
which would then be lifted as:
```
  45 @ 01fe30ae  rsp#12 = rsp#11 - 8
  44 @ 01fe30ae  [rsp#12].q = zx.q(0x7ef79a79) @ mem#17 -> mem#18
  46 @ 01fe30b3  [rsp#12].q = rsi#0 @ mem#18 -> mem#19
``` 
While not a bug, this improvement would make the lifted code much cleaner, and also make leveraging SSA much easier through tracking the uses. For example it would make dead store identification much easier to identify.

**Comment by plafosse** [comment]
Thank you for your suggestion but this was a very intentional design decision. This prevents us from having to special case SP. Which may not always contain the stack pointer. We do the store identification on MLIL where tracking uses isn't a problem.
