### ISSUE TITLE
Cannot patch bytes where there are relocations

### ISSUE THREAD

**Issue by bb33bb** [Vector35/binaryninja-api#4950]
**Version and Platform (required):**
Version and Platform (required):
Binary Ninja Version:3.6.4789-dev Personal (adb795a6)
OS: manjaro
OS Version: Linux version 6.6.10-1-MANJARO
CPU Architecture: x64

**Bug Description:**
i try to  modify arm64 bytecode , after unlocked and when enter mode of 
**elf raw**
some bytes cannot be modified
I am a little new to this software, is  this designed as it should be?

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
see the viedo

**Expected Behavior:**
I need to modified the code 
u know , some times it is really a little hard to patch arm64 instruction because ninja will automatically "correct" your instruction
so i try to modify the program in hexmod
but also meet the obstacle
is there some advise or better method for me ?
really thanks for your help
**
Screenshots:**
https://github.com/Vector35/binaryninja-api/assets/5463104/58cce146-5306-4ce9-92bb-a6a030afb08c

**Additional Information:**
Please add any other context about the problem here.

**Comment by xusheng6** [comment]
Some bytes cannot be modified because there are relocations on it. If you can share the binary, we can have a closer look at it

**Comment by bb33bb** [comment]
> Some bytes cannot be modified because there are relocations on it. If you can share the binary, we can have a closer look at it

to be honest , some times i need to patch the code.
eventhough there are relocations.
for example
i will delete a block of code
and place nop there
but eventhough
there are restrictions.
I can understand if there are some rules i have to accept when patching arm instructions,
but really a little confused that when mode changed to hex , we can not patch byte code.

**Comment by xusheng6** [comment]
Would you consider joining our slack so that we can communicate better? https://slack.binary.ninja/

**Comment by xusheng6** [comment]
There is a viable workaround for this before we properly fix https://github.com/Vector35/binaryninja-api/issues/920:

1. Use a tool to locate the relocation entry in the file (e.g., with `readelf`)
2. Patch the relocation to another existing one, effectively disabling it
3. Now you can edit it as usual

**Comment by bpotchik** [comment]
With the new MemoryMap we do provide a way to patch bytes at regions that contain relocations now. The mechanism is somewhat raw and we will likely refine the process, however here is an example:
```
>>> relo = bv.relocation_ranges[0]
>>> relo_size = relo[1] - relo[0]
>>> relo_size
4
>>> bv.read(relo[0], relo_size)
b'H\x10\x01\x00'
>>> bv.write(relo[0], b'\xff' * 4)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/binaryview.py", line 4232, in write
    raise RelocationWriteException("Attempting to write to a location which has a relocation")
binaryninja.exceptions.RelocationWriteException: Attempting to write to a location which has a relocation

# Note we do not define any permissions, the region will inherit the permissions from the existing shadowed region.
>>> bv.memory_map.add_memory_region("my_writable_relo", relo[0], b'\xff' * 4)
True
>>> bv.read(relo[0], relo_size)
b'\xff\xff\xff\xff'
>>> bv.write(relo[0], b'\xda' * 4)
4
>>> bv.read(relo[0], relo_size)
b'\xda\xda\xda\xda'
```

**Comment by bb33bb** [comment]
as it is solved , may i close it in the future?

**Comment by bpotchik** [comment]
Yeah we can close this one. There are some items that we need to clean up related to this capability. I've captured those in a new issue: https://github.com/Vector35/binaryninja-api/issues/5916
