### ISSUE TITLE
Project Browser actions are not in main menu / command palette

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#4951]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4789
- OS: macOS
- OS Version: 14.0
- CPU Architecture: M1

**Bug Description:**
Using the new projects browser, the actions which are available in the right click menu are not available in the main menu or in the command palette. 

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Create or open a project
2. Hit Cmd+P
3. Type "Add file"
4. Observe "add file" is not in the command palette

**Expected Behavior:**
I expected all of the actions in context menus to be in the command palette

**Additional Information:**
Need to switch from QAction to using UIAction so they are registered. cc Vector35/binaryninja#542

**Comment by negasora** [comment]
Fixed in `3.6.4813-dev`
