### ISSUE TITLE
GetSaveFileNameInput does not account for projects

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#4952]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4789
- OS: macOS
- OS Version: 14.0
- CPU Architecture: M1

**Bug Description:**
When I try to use BinaryNinja::GetSaveFileNameInput to save a file, I don't get a project browser + save dialog. This is missing functionality, since BinaryNinja::GetOpenFileNameInput _does_ use a browser for the current project, and I would expect both of these functions to behave similarly.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Make some code using the BinaryNinja::GetSaveFileNameInput api
2. Open a project
3. Trigger your code
4. Observe stock filesystem dialog

**Expected Behavior:**
I expected a project-aware save file name dialog

**Comment by negasora** [comment]
Fixed in `3.6.4810-dev`
