### ISSUE TITLE
GetOpenFileNameInput with projects does not allow filter by extension

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#4953]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4789
- OS: macOS
- OS Version: 14.0
- CPU Architecture: M1

**Bug Description:**
When using BinaryNinja::GetOpenFileNameInput to open files in projects, the file extension filter I specified is not honored and I am allowed to select any file I please. This is confusing since now it looks like I can pick any file I want, even though normally they would not be displayed (and indeed because they will not work). This dialog should hide files (but not folders) with an extension other than the one I specified.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Make some code using the BinaryNinja::GetOpenFileNameInput api with an extension filter
2. Open a project
3. Trigger your code
4. Observe all files are allowed to be selected

**Expected Behavior:**
I expected the dialog to hide files (but not folders) with an extension other than the one I specified.

**Comment by negasora** [comment]
Added in `3.6.4796-dev`
