### ISSUE TITLE
Project Browser Name column is really small on first open

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#4954]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4789
- OS: macOS
- OS Version: 14.0
- CPU Architecture: M1

**Bug Description:**
When opening a project, the initial width of the "name" column in the browser is really small and can only fit like 5 letter maximum. I end up having to resize it every time I open a project, which is rather frequent since my workflow involves restarting Binja a lot of times and I have to open the project after every restart.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open a project
2. Observe width of columns

**Expected Behavior:**
I expected one of the following:
1. Binja has a sensible default width of the name column such that I don't need to resize it
2. Binja remembers what width i previously gave to the name column and restores that on open

**Screenshots:**
<img width="1270" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/711973/55864a9e-d481-478d-9c97-13a755314f1b">

**Additional Information:**
When i resize the window, the only column that resizes is the last one, Status. This is almost never the behavior I want (I want the name column to expand when I resize the window).

**Comment by negasora** [comment]
This was fixed in `3.6.4786-dev`
