### ISSUE TITLE
Project Browser says Invalid drop target type when trying to drag files in, sometimes

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#4955]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4789
- OS: macOS
- OS Version: 14.0
- CPU Architecture: M1

**Bug Description:**
When I try to drag a file into my project, sometimes it tries to drop the file not _in the project_ but _onto an existing file_. Notably, this only seems to happen in the columns other than the first one? But it tries to drag the file into the date, and then doesn't like that. I have to be very careful to either drop in the first column (which is tiny #4954) or in between two rows of the other columns.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open project with files
2. Drag file into list but like move it around a bunch
3. Observe ability to drop onto date
4. Try to drop onto date
5. Observe error

**Expected Behavior:**
I expected it to just add the file to my project.

**Screenshots:**
<img width="919" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/711973/7c84e940-40c9-411a-8cee-14ade7fc3733">

**Comment by negasora** [comment]
Fixed in `3.6.4821-dev`
