### ISSUE TITLE
If the first few bytes of a function happen to be ascii, binja will deference as a string

### ISSUE THREAD

**Issue by Grazfather** [Vector35/binaryninja-api#496]
I can't upload the binary since it's part of an on-going contest, but should be trivial to create a sample bin.

<img width="246" alt="" src="https://cloud.githubusercontent.com/assets/497310/18810854/2f3be266-8255-11e6-9a9d-e6c8cf0da084.png">

<img width="431" alt="" src="https://cloud.githubusercontent.com/assets/497310/18810860/503430fe-8255-11e6-8bb2-20977d3477d8.png">

**Comment by Grazfather** [comment]
```00000000: 68 60 46 40                                      h`F@
```

**Comment by plafosse** [comment]
Fixed in dev

**Comment by Grazfather** [comment]
:pray: ty!
