### ISSUE TITLE
Signature matcher produces false positives

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4962]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4790-dev, 10b89271
- OS: macos
- OS Version: 14.3
- CPU Architecture: arm64

**Bug Description:**
The screenshots below are from a test executable (x64, no debug symbols, optimizations disabled) used to evaluate BN's C++ reversing features. In the second screenshot, it seems that many of the vft definitions are false positives. It would be beneficial for BN to address and eliminate these false positives, as renaming these functions manually is quite time-consuming.

**Screenshots:**
`std::exception` is false positive here:
<img width="751" src="https://github.com/Vector35/binaryninja-api/assets/109607896/36a3d80c-d00d-47a4-a650-96c9d8abdc7c">

VFT:
<img width="836" src="https://github.com/Vector35/binaryninja-api/assets/109607896/e9d3d8d6-024a-495f-98b3-6eab0271449b">

**Additional Information:**
Binary and source code:
[class_test.zip](https://github.com/Vector35/binaryninja-api/files/14050878/class_test.zip)

**Comment by plafosse** [comment]
Closing as duplicate https://github.com/Vector35/binaryninja-api/issues/3773
