### ISSUE TITLE
Support for the TE file format.

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#4968]
This issue is to add support for the TE binary file format documented here:
https://uefi.org/specs/PI/1.8/V1_TE_Image.html

**Comment by psifertex** [comment]
See also https://github.com/Vector35/binaryninja-api/issues/249

**Comment by zznop** [comment]
Until we bring this into core, a plugin exists [here](https://github.com/zznop/te-loader)

**Comment by zznop** [comment]
Progress can be tracked in the [4096-te-view branch](https://github.com/Vector35/view-pe/tree/4968-te-view) of the `view-pe` plugin

**Comment by zznop** [comment]
The TE view has been merged and is now on dev channel
