### ISSUE TITLE
Some interfaces consist solely of a vft without a corresponding class

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4970]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4797-dev, 6be9a1f4
- OS: macos
- OS Version: 14.3
- CPU Architecture: arm64

**Bug Description:**
In the example below, the `SetInterrupt` function is called from the `IDebugControl4` interface. However, it seems that BN does not recognize this. 

HLIL:
<img width="650" src="https://github.com/Vector35/binaryninja-api/assets/109607896/e9a38087-fae1-4ed5-8c0a-833725c050cd">

Disassembly:
<img width="466" src="https://github.com/Vector35/binaryninja-api/assets/109607896/aaa0cb0a-47c4-462a-886e-e396773acb07">

When I change the type of the variable to `struct IDebugControl4**`, I obtain this result:

<img width="496" src="https://github.com/Vector35/binaryninja-api/assets/109607896/2d93eb03-bc68-4e40-8e8f-b0329b8464d9">

At least I can see the SetInterrupt function call. However, this is not the correct way to resolve this issue because `eng->DebugControl4` has the type `struct IDebugControl4*`, so BN should interpret it as such.

I can share the binary on slack.

**Comment by op2786** [comment]
I understand the root cause of this issue. In fact, `IDebugControl4` should be a class that has a vtable. However, currently, `IDebugControl4` itself is just a vft and not a class. As a result, the code attempts to reference the vftable of the class first, then proceeds to the function. But due to the absence of a class, it displays the function incorrectly.

**Comment by xusheng6** [comment]
@plafosse can you have a look at this?

**Comment by xusheng6** [comment]
search `springbuck suffusive rustles neoplastic benzine` to find the binary

**Comment by plafosse** [comment]
Fixed in 3.6.4817
