### ISSUE TITLE
Breakpoint not hit when debugging an elf bin that rely on interpreter /lib/ld-linux.so.2

### ISSUE THREAD

**Issue by obrunet** [Vector35/binaryninja-api#4973]
Hello bin ninjas!

I'm new to reverse engineering so the issue can come from my side but it doesn't seem to be the case :)

**Version and Platform (required):**
- Binary Ninja Version: `3.5.4526`
- OS: `Ubuntu Linux`
- OS Version: `22.04`
- CPU Architecture: `x64`

**Bug Description:**
- while playing with the [crackmes.de's bf by crp](https://crackmes.one/crackme/5ab77f5833c5d40ad448c39b) 
- when i place a breakpoint  at the beginning of the code, and run the debugee, the file is executed without any stop: the breakpoint doesn't seem to be taken into account.

**Steps To Reproduce:**
1. download this bin
2. toogle a breakpoint
3. launch the debugger
4. the file is executed without any stop

**Additional Information:**
- This has nothing to do with x86_32 binaries as I'm able to run & debug other 32bit executables. The same behavior is encountered with [IOLI 32 & 34bit versions](https://github.com/BinaryResearch/IOLI64)
-  I'm able to debug this crkme with IDA free, so this might be due to LLDB in binary ninja
- by comparison with binaries that i can debug, the issue might be due to the interpreter being `/lib/ld-linux.so.2` 
- I've found [a similar issue in old versions of gdb](https://stackoverflow.com/questions/58225562/how-to-fix-hang-in-gdb-in-ld-linux-so-2-when-running-a-32-bit-executable-on-a-64) but not sure this is related.

Regards

**Comment by xusheng6** [comment]
> Hello bin ninjas!
> 
> 
> 
> I'm new to reverse engineering so the issue can come from my side but it doesn't seem to be the case :)
> 
> 
> 
> **Version and Platform (required):**
> 
> - Binary Ninja Version: `3.5.4526`
> 
> - OS: `Ubuntu Linux`
> 
> - OS Version: `22.04`
> 
> - CPU Architecture: `x64`
> 
> 
> 
> **Bug Description:**
> 
> - while playing with the [crackmes.de's bf by crp](https://crackmes.one/crackme/5ab77f5833c5d40ad448c39b) 
> 
> - when i place a breakpoint  at the beginning of the code, and run the debugee, the file is executed without any stop: the breakpoint doesn't seem to be taken into account.
> 
> 
> 
> **Steps To Reproduce:**
> 
> 1. download this bin
> 
> 2. toogle a breakpoint
> 
> 3. launch the debugger
> 
> 4. the file is executed without any stop
> 
> 
> 
> **Additional Information:**
> 
> - This has nothing to do with x86_32 binaries as I'm able to run & debug other 32bit executables. The same behavior is encountered with [IOLI 32 & 34bit versions](https://github.com/BinaryResearch/IOLI64)
> 
> -  I'm able to debug this crkme with IDA free, so this might be due to LLDB in binary ninja
> 
> - by comparison with binaries that i can debug, the issue might be due to the interpreter being `/lib/ld-linux.so.2` 
> 
> - I've found [a similar issue in old versions of gdb](https://stackoverflow.com/questions/58225562/how-to-fix-hang-in-gdb-in-ld-linux-so-2-when-running-a-32-bit-executable-on-a-64) but not sure this is related.
> 
> 
> 
> Regards

This sounds like a bug that I have fixed recently. Would you please try debugging it with the latest dev version of Binary Ninja? I wish you good luck with it! And if it still does not work, please let me know and I can properly troubleshoot it

**Comment by psifertex** [comment]
Specifically, you can see how to update here: https://docs.binary.ninja/guide/index.html#development-branch

**Comment by obrunet** [comment]
I works like a charm with the latest dev version :)
Thanks to both of you for your quick response!
