### ISSUE TITLE
GetSaveFileNameInput project dialog needs to not apply filter to folders

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#4991]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4812
- OS: windows
- OS Version: 10
- CPU Architecture: x64

**Bug Description:**
When calling GetSaveFileNameInput in a project, the dialog that appears tries to "helpfully" filter to only show folders containing files of the extension I provided. But I want to save a new file to an empty folder! And since the folder is empty, it has been hidden.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Create folder
2. Call that function
3. Observe lack of folder in dialog
4. Feel remorse and confusion

**Expected Behavior:**
I expected to be able to save to empty folders

**Comment by negasora** [comment]
Fixed in `3.6.4813-dev`
