### ISSUE TITLE
GetSaveFileNameInput projects dialog focuses Create External File and not Save

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#4992]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4812
- OS: Windows
- OS Version: 10
- CPU Architecture: x64

**Bug Description:**
When I tried to save a file via GetSaveFileNameInput, the Create External File button is focused instead of Save, so typing the file name and pressing enter starts trying to create an external file instead of accepting my input.

**Steps To Reproduce:**
1. Call function
2. Type text
3. Press enter
4. Confusion

**Expected Behavior:**
I expected pressing enter to accept my changes and close the dialog

**Comment by negasora** [comment]
Fixed in `3.6.4813-dev`
