### ISSUE TITLE
Incorrect Emoji Rendering in Specific UI Locations

### ISSUE THREAD

**Issue by utkonos** [Vector35/binaryninja-api#4994]
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4526
- OS: macOS
- OS Version: 14.2.1
- CPU Architecture: x64

**Bug Description:**
 Certain types of emoji (looks like length of 6 bytes) are rendered correctly in the tag types, tags, and in disassembly. But in the Python console and in popup windows, they are rendered incorrectly.

**Steps To Reproduce:**
1. Open Python console
2. Run this `bv.create_tag_type('Code Reuse', b'\xe2\x99\xbb\xef\xb8\x8f')`
3. Anywhere in a disassembly view, right click and add tag
4. Observe the incorrect rendering in both the drop down menu and in the tooltip when you hover over the tag.
5. In the Python console, observe the incorrect rendering in the command response from step 2.

**Expected Behavior:**
All locations to have identical, correct rendering.

**Screenshots:**
<img width="274" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/2775739/6083655a-d18b-49e9-b771-9c154fd89f69">
<img width="474" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/2775739/42fef545-f91e-4f89-8317-6d3a9b77c40f">

vs.

<img width="190" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/2775739/4919753e-32a1-433d-b24f-80dcd3047abc">
and elsewhere

**Comment by xusheng6** [comment]
I tested on dev latest dev (4.0.4828-dev (ad432be2)) and it works fine:

![Screenshot 2024-02-06 at 3 38 53 PM](https://github.com/Vector35/binaryninja-api/assets/94503187/23401489-e20c-4580-b3a9-fa0e88b6d2f5)

Could you please switch to dev version and have a try? You can follow [this](https://docs.binary.ninja/guide/index.html#updates) to switch to dev builds

**Comment by xusheng6** [comment]
I am closing this now as this is probably fixed on the latest dev. If it still happens to you on latest dev, please free feel to add new comments to this issue, and re-open the issue
