### ISSUE TITLE
Relocations support

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#5]
Some binaries  (http://pwnable.kr/bin/bof) use relocations to directly update the text segment.

**Comment by lucasduffey** [comment]
this might also affect http://pwnable.kr/bin/login.

In "auth" function the call after _IO_printf isn't labeled. In ida it's labeled as _strcmp.

**Comment by plafosse** [comment]
Changing the title to be more inclusive.

**Comment by plafosse** [comment]
Feature added as of v1.1.1345 There are still some relocations that aren't handled and there isn't a python API for creating new handlers but we'll track those in separate tickets.
