### ISSUE TITLE
plugin reloading

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#50]
When developing a plugin, support reloading the plugin without restarting the entire program

**Comment by lucasduffey** [comment]
workaround: http://stackoverflow.com/questions/437589/how-do-i-unload-reload-a-python-module

**Comment by whitequark** [comment]
Here's a quick guide on making plugin hot reload possible:
1. Provide de-registration functions
2. Add this to the top of the plugin:

  ```python
  try:
    for _on_reload_fn in _on_reload:
      _on_reload_fn()
  except NameError:
    pass
  _on_reload = []
  ```
3. When altering global state, do:

  ```python
  MyBinaryView.register()
  _on_reload.append(lambda: MyBinaryView.unregister())
  ```
4. There is no step 4! This works with anything as long as a corresponding de-registration function is provided.

This relies on the way the `reload` function works in Python--the new module code is evaluated in the same context as the old module code was, and it has access to the globals of the old evaluation. This is specifically called out in the [reload() documentation](https://docs.python.org/2/library/functions.html#reload).

**Comment by psifertex** [comment]
Unfortunately we have no plans to change the ability to unload/reload architecture and binaryviews due to the cross-platform plugin and core design. We are instead closing this in favor of #2167 which is our officially planned feature to better support this workflow. We've also updated the documentation on dev for https://docs.binary.ninja/guide/plugins.html#testing

**Comment by whitequark** [comment]
Sounds reasonable!
