### ISSUE TITLE
fonts not loading on Windows

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#500]
Extra fonts aren't showing up as choices on windows, only the default Source Code Pro. 

Check linux as well.

**Comment by xmonk** [comment]
@psifertex Just noticed some issues with fonts in OS X and Linux that might be related to the above. If you change the default font size, next time you start Binary Ninja, the font is set to Courier 12 and the listing in preferences for the font is set to `@Variant`, resetting to default fixes it for the running instance, but when you restart same issue again.  This is on the commercial version latest dev.

**Comment by psifertex** [comment]
It looks like QSettings is broken on OSX. The font is serialized properly on Linux, but not OS X. 

We've got longer-term plans of implementing our own custom preferences backing which is probably going to be the right fix for OS X not being able to persist font changes. 

I think, however, that this is likely a different bug than the fonts not loading on Windows so I'm going to leave this one open to track the original.

**Comment by psifertex** [comment]
Looks like the QT upgrade fixed this for us. Source Code Pro now properly bundled and shipped with Linux, Windows, and MacOS.
