### ISSUE TITLE
When using Projects, Save As Analysis Database does not prompt for location

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#5000]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4818
- OS: Windows
- OS Version: 10
- CPU Architecture: x64

**Bug Description:**
When trying to use Save As on a project analysis database, I do not get presented a file picker window to choose where to save. Instead it just saved my database into the project as "foo.bndb.bndb" (and if you do it again, you can get "foo.bndb.bndb.bndb").

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open project file
2. Save
3. Save As -> Analysis database
4. Observe lack of Save As prompt

**Expected Behavior:**
I expected a project file picker to appear allowing me to choose where in the project I wanted to save my file.

**Comment by negasora** [comment]
Fixed in `3.6.4820-dev`
