### ISSUE TITLE
Documentation links don't navigate to the right place sometimes

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#5001]
This might be a caching issue or maybe something has changed in browsers recently? But, when you click links that use anchors for our documentation, it will often take you to the wrong place. It looks like what's happening is that it takes you to the _right_ place and then the page re-flows. But, I'm not entirely sure.

**Comment by psifertex** [comment]
Mostly just an upstream bug in sphinx I'm not going to worry about. I believe it's only happening when you link to something at the very end of a page and the page itself is short so the auto-scroll tracking thinks it needs to re-adjust what's in focus.
