### ISSUE TITLE
Projects Browser icons hardcoded to white and not visible on light themes.

### ISSUE THREAD

**Issue by 0cyn** [Vector35/binaryninja-api#5013]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4819-dev
- OS: macOS
- OS Version: 14.1
- CPU Architecture: arm64

**Bug Description:**
Projects icons aren't visible on light themes

**Steps To Reproduce:**
1. Enable a light theme
2. Open Projects browser

**Expected Behavior:**
SidebarActiveIconColor, palatte().text(), others should be guaranteed to be visible against palatte().window()

**Screenshots:**
![image](https://github.com/Vector35/binaryninja-api/assets/55725881/d8c41bab-c129-4ec2-8791-76c96d71d4e5)

**Comment by fuzyll** [comment]
These weren't actually hardcoded to white. They were just being rendered without any palette being applied. This is now fixed as of 4.0.4852-dev (the large overhaul of icons).
