### ISSUE TITLE
Copy Opcode Action

### ISSUE THREAD

**Issue by 0cyn** [Vector35/binaryninja-api#5014]
- Binary Ninja Version: 3.6.4819-dev
- OS: macOS
- OS Version: 14.1
- CPU Architecture: arm64

**What is the feature you'd like to have?**
Any way to copy an instruction opcode out of linearview.

**Additional Information:**
This is useful when writing an arch plugin.

**Comment by fuzyll** [comment]
In the hamburger menu in the top right of the pane, there is a `Show Opcode Bytes` option that shows the opcode bytes right in Linear View. These are selectable/copyable.

Were you aware of this option? And is this worse for your workflow in some way than having an action?

Here's how it looks for a random ARM ELF I had open:

<img width="640" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/607452/6d1316fb-3558-4994-aefb-aa19a9822fb0">

**Comment by 0cyn** [comment]
At the time of filing I was unable to copy the bytes when selected. IIRC there was not even a ⌘C option in the menu. This may have been a focus issue that is no longer present. Cannot repro so I will close.
