### ISSUE TITLE
Project Browser: Double clicking in a column other than the folder's name does not uncollapse folder. 

### ISSUE THREAD

**Issue by 0cyn** [Vector35/binaryninja-api#5016]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4819-dev
- OS: macOS
- OS Version: 14.1
- CPU Architecture: arm64

**Bug Description:**
Double clicking on a folder in the project browser somewhere other than the name of the folder does not uncollapse it. This is unexpected as there are no other click events in other columns for folders, and the name column is comparatively tiny. 

**Steps To Reproduce:**
1. Open Project
2. Create Folder
3. Put thing in folder
4. double click folder somewhere other than name column

**Comment by negasora** [comment]
Fixed in `4.0.4824-dev`
