### ISSUE TITLE
Opening files in a project does not insert them into the recent files list

### ISSUE THREAD

**Issue by 0cyn** [Vector35/binaryninja-api#5017]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4819-dev
- OS: macOS
- OS Version: 14.1
- CPU Architecture: arm64

**Bug Description:**
Files opened in project browser should be inserted into the ui/recentFiles list.

**Steps To Reproduce:**
1. Open file in project
2. Hit new tab button.

**Comment by negasora** [comment]
Added in `4.0.4827-dev`
