### ISSUE TITLE
Key binding to show/hide log

### ISSUE THREAD

**Issue by alexrp** [Vector35/binaryninja-api#5021]
It used to be possible to bind a key to show/hide the log, which I used very frequently. I don't remember if it was actually for the log *specifically* or for showing/hiding the entire global area. Whatever the case, after the recent sidebar changes (which are great btw!) it seems like there's no longer such a key binding. Would be nice to be able to do this again.

**Comment by alexrp** [comment]
And just to be clear, `Focus Log` doesn't quite fulfill this need since it can't hide the log.

**Comment by alexrp** [comment]
Hm, I actually have a similar ask for the types view, now that it's possible to put it on the right sidebar.

So maybe this ask could just generally extend to having a show/hide key bindings for every widget?

**Comment by D0ntPanic** [comment]
Added "Toggle" actions for any sidebar widget to replace the old actions in 4.0.4855.
