### ISSUE TITLE
Crash when calling `bv.get_external_locations()`

### ISSUE THREAD

**Issue by jrmo14** [Vector35/binaryninja-api#5023]
**Version and Platform (required):**
- Binary Ninja Version: 4.0.4828-dev
- OS: MacOS
- OS Version: Sonoma
- CPU Architecture: x64

**Description of bug:**
Binary Ninja crashes

**Steps To Reproduce:**
1. Run `x = bv.get_external_locations()`
2. Access x by printing it 
3. Crash

**Expected Behavior:**
Binary ninja doesn't crash

**Additional Information:**
Was able to monkey patch the function to work as expected by creating the `ExternalLocation` from `new_handle` when appending to the list instead of `handles[i]`.

**Comment by negasora** [comment]
Fixed in `4.0.4831-dev`
