### ISSUE TITLE
Can't "Update to latest version automatically"

### ISSUE THREAD

**Issue by KyleMiles** [Vector35/binaryninja-api#5025]
Regardless of the order or timing when I open this dialogue, click the box, and hit done, it doesn't seem to stick for me. Tried clearing my QSettings too. No plugins installed.

https://github.com/Vector35/binaryninja-api/assets/7171118/c7473f82-d0c3-4fd0-9e4f-295098f06aa5

There used to be "a trick" to it, but we should probably just fix it.

**Comment by plafosse** [comment]
Fixed in 4.0.4905
