### ISSUE TITLE
Unable to open binary ninja after updating

### ISSUE THREAD

**Issue by WZ-Tong** [Vector35/binaryninja-api#5028]
**Version and Platform (required):**
- Binary Ninja Version: latest dev (updated just now, unable to get version)
- OS: Windows
- OS Version: 23H2
- CPU Architecture: x64

**Bug Description:**
After updating to the latest dev and re-open binja, the main window flashed and closed, while the background process keeps running, occupying a lot of resources.
If I manually delete my license file in %APPDATA%/Binja, the register dialog can normally pop up, but the main window keeps flash to close.

**Screenshots:**
![image](https://github.com/Vector35/binaryninja-api/assets/77199564/17b7ef44-7921-4d5c-923c-4ac76902f293)
![image](https://github.com/Vector35/binaryninja-api/assets/77199564/d7efb997-baf6-46c3-9e14-ab565af50572)
![image](https://github.com/Vector35/binaryninja-api/assets/77199564/0f5d0258-f698-4fea-be13-4dd16a364116)

**Comment by fuzyll** [comment]
Hey, sorry about that. You are not the only one experiencing this right now. I believe this might be related to an issue we identified earlier today, but I am unable to confirm.

If you, or anyone else, is experiencing this and need to reinstall, you can get a new installer from https://binary.ninja/recover.

Sorry again for the inconvenience!

**Comment by fuzyll** [comment]
Another user experiencing this issue says:

> Up to 4.0.4832 it is fine, starting 4835 UI is not showing up

**Comment by WZ-Tong** [comment]
The latest dev installer from recovery page is `4.0.4836.0` (from .exe's property), it's still flashing after I delete `binaryninja*` from install dir and re-install it. Trying to install `3.5-stable` and upgrade to `4.0.4832-dev`

**Comment by plafosse** [comment]
Workaround: Delete the contents of this registry key: `HKEY_CURRENT_USER\Software\Vector 35\Binary Ninja\ui\recentFileState`
