### ISSUE TITLE
Symbols do not refresh when filtered

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#5029]
**Version and Platform (required):**
- Binary Ninja Version: 4.0.4836-dev, df4290fd
- OS: macos
- OS Version: 14.3
- CPU Architecture: arm64

**Steps To Reproduce:**
1. Open any binary
2. Filter in the symbols view by entering "test"
3. Rename a function with a name that includes the string "test"
4. Observe that the function does not appear in the filtered list of symbols

**Expected Behavior:**
I expect BN to display the newly renamed function in the filtered view.

**Comment by bpotchik** [comment]
Fixed in `4.0.4840-dev`.
