### ISSUE TITLE
Rebasing breaks Symbols view after sidebar updates

### ISSUE THREAD

**Issue by WZ-Tong** [Vector35/binaryninja-api#5032]
**Version and Platform (required):**
- Binary Ninja Version: 4.0.4832-dev Personal (9f9b3a6f)
- OS: Windows
- OS Version: 23H2
- CPU Architecture: x64

**Steps To Reproduce:**
1. Open a binary file (my case: `Platform: linux-aarch64, Architecture: aarch64`)
2. Jump to any local function
3. Rebase
4. Jump to any local function
5. Find it **unable to jump**
6. Close the `.bndb` database
7. Re-open the `.bndb` database
8. It **works** again

Maybe you forget to re-assign the absolute address in function view after rebasing.

**Comment by plafosse** [comment]
Any chance you can share this binary?

**Comment by plafosse** [comment]
What seems to be happening here is the Symbols view isn't getting notified that the update occurred. This was caused by the recent sidebar refactor.
