### ISSUE TITLE
Crash while analyzing `libbinaryninjacore`

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#5037]
**Version and Platform (required):**
- Binary Ninja Version: 4.0.4844-dev, 94ce4c18
- OS: macos
- OS Version: 14.3
- CPU Architecture: arm64

**Bug Description:**
It appears that BN crashes when attempting to analyze the `libbinaryninjacore.1.dylib` file from the Mac ARM build of BN. I assume this is not intended behaviour in order to block reverse engineering of BN itself 😄 

**Steps To Reproduce:**
1. Open `libbinaryninjacore.1.dylib` in BN
2. Wait for the crash

**Comment by plafosse** [comment]
Did you happen to do something like navigate using the symbols list?

**Comment by bpotchik** [comment]
Fixed in `4.0.4845-dev`.
