### ISSUE TITLE
Keybindings and Settings Hotkeys Do Not Work in Other MainWindows

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#5039]
1. Open a new BN window
2. Open settings (via hotkey or menu)
3. Open a new window 
4. Hotkey and menu are both non-functional for settings

This is not a new bug, has existed since at least 3.4, and the fix for https://github.com/Vector35/binaryninja-api/issues/4818 didn't resolve this particular issue.

**Comment by bpotchik** [comment]
Discovered here from the project window: 
https://github.com/Vector35/binaryninja-api/issues/5002

**Comment by bpotchik** [comment]
Fixed in `4.0.4849-dev`.

**Comment by bpotchik** [comment]
So one source of this behavior is fixed which fixes the initial repro steps shown above.

There is a separate issue and the repro is:

1. Open Binary Ninja
2. File....New Window
3. Close the first window
4. Only the Hotkey is non-functional. The menu action and the command palette actions work without issue.

Simply clicking on the Binary Ninja application menu, then clicking back to the Binary Ninja window allows the hotkey to work once again.

**Comment by plafosse** [comment]
Fixed in 4.0.4874
