### ISSUE TITLE
Crash when analyzing a binary 

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#5048]
Customer reports:

There was a regression introduced in 4.0.4841 that makes BN crash when loading this file (file: arm64 slice; from dyld shared cache of macOS 14.4 Beta (23E5191e)), reading the changelog my hunch it’s either commit 0938583 or 6140477 by  @CouleeApps  based on their description. 4.0.4840 loads this file fine. Tested on macOS 14.4 w/ M3 silicon.

[GeoServices.zip](https://github.com/Vector35/binaryninja-api/files/14239398/GeoServices.zip)

**Comment by CouleeApps** [comment]
Sounds like this crash was fixed by @bpotchik in Vector35/binaryninja@ab0cd9ba9600f099f1482760470615e9038ee086 . Here's the crash log though, just for completeness' sake: [crash(1).log](https://github.com/Vector35/binaryninja-api/files/14242119/crash.1.log)

**Comment by bpotchik** [comment]
Yeah looks like it. Fixed in `4.0.4862-dev`.
