### ISSUE TITLE
Open with Options on bndb in Project from Recent Files list does not work

### ISSUE THREAD

**Issue by 0cyn** [Vector35/binaryninja-api#5050]
**Version and Platform (required):**
- Binary Ninja Version: 4.0.4859
- OS: macOS 14 M1

**Bug Description:**
Open with Options on bndb in Project from Recent Files list does not work

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Have BNDB in project
2. Open it
3. Open New Tab
4. Go to recent files list, select it, Cmd+Enter
5. Observe bndb opening without options dialog

**Expected Behavior:**
It should open with options in the same way it does from Project Browser

**Comment by negasora** [comment]
Fixed in `4.0.4864-dev`
