### ISSUE TITLE
`BinaryView.get_functions_by_name` does not act as expected

### ISSUE THREAD

**Issue by negasora** [Vector35/binaryninja-api#5055]
When not passed a platform, it defaults to using the binaryview's platform and may cause incorrect results when used with a binaryview that has functions with multiple platforms. If not passed a specific platform it should fetch all functions with that name, regardless of platform.

We should also do a pass and make sure other plural getters act the same.

**Comment by emesare** [comment]
Fixed in [#ee9248c](https://github.com/Vector35/binaryninja-api/commit/ee9248c0f7144d9925e600be03f37fa155f51aef)
