### ISSUE TITLE
Old sidekick 3rd party plugin repo still present

### ISSUE THREAD

**Issue by jrozner** [Vector35/binaryninja-api#5057]
I removed the 3rd party plugin repo from the old beta and now whenever I open up the plugin manager it locks up while it waits to try and connect to the host. It's no longer in my settings but it must be cached somewhere.

**Comment by psifertex** [comment]
Thanks, I'm going to close this for now, as #3826 is covering a bunch of changes to the plugin manager infrastructure that will resolve this independently.
