### ISSUE TITLE
Deconflicted DebugInfo types have bad references

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#5060]
**Version and Platform (required):**
- Binary Ninja Version: 4.0.4883-dev
- OS: Windows
- OS Version: 10
- CPU Architecture: x64

**Bug Description:**
When loading a PDB, types whose name conflict with a type in the existing view have `_DebugInfo` appended to their name so they do not conflict. Unfortunately, when this happens, any references other types in the PDB make to that type are not updated to point to the updated name. This leads to `_KPCR_DebugInfo` referencing `_KPRCB` instead of `_KPRCB_DebugInfo` and structure members looking strange.

**Steps To Reproduce:**
1. Open ntoskrnl.exe from a recent windows
2. Find the type `_KPCR_DebugInfo`
3. Observe it references `_KPRCB` and not `_KPRCB_DebugInfo` and has like 0x8eff bytes of extra padding at the end

**Expected Behavior:**
I expected renamed types to be referenced correctly by other types from the pdb.

**Screenshots:**
<img width="819" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/711973/6b4b94e3-ceba-43c6-8613-5c591ab4cae7">

**Additional Information:**
Possibly due to the types already referencing the bv type before rename happens and thus the NTRs are broken already

**Comment by plafosse** [comment]
Fixed in 4.0. 4898 Unfortunately due to time constraints in 4.0 release I'm reverting the changes that were made for type deconfliction to fix this issue. This essentially creates a new issue.
