### ISSUE TITLE
Add parameterized syscall IL instruction

### ISSUE THREAD

**Issue by dfraze** [Vector35/binaryninja-api#507]
On some platforms (ARM OABI, for example) the syscall number is part of the instruction stream, not stored in another register.

The way the IL handles this doesn't currently handle this situation.

**Comment by plafosse** [comment]
You can work around this issue by creating a fake syscall parameter register which you set in your lifter, and is used in the system call convention.

**Comment by plafosse** [comment]
I'm going to close this because it has a very straight forward workaround.
