### ISSUE TITLE
Need to automatically put `.bnta` file extension on type archives when saved

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#5078]
**Version and Platform (required):**
- Binary Ninja Version: 4.0.4981-dev
- OS: Ubuntu Linux
- OS Version: 22.04
- CPU Architecture: x86-64

**Bug Description:**
On Linux at least, it doesn't appear that the `.bnta` suffix is being automatically added to new type archives when they are saved.

This is problematic because the "Attach Type Library" context menu option currently requires the extension in order to select it.

**Steps To Reproduce:**
1. Open a project in Binary Ninja
2. Open an analysis database or file within that project
3. In the types browser, right-click and choose "Create Type Archive" from the context menu
4. Save your type archive to the project
5. Observe that it does not have the file extension added automatically

**Expected Behavior:**
The extension is added automatically.

**Comment by plafosse** [comment]
Fixed in 4.0.4900
