### ISSUE TITLE
Need confirmation when pulling from a type archive will clobber an existing type

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#5079]
**Version and Platform (required):**
- Binary Ninja Version: 4.0.4891-dev
- OS: macOS
- OS Version: 14.3.1
- CPU Architecture: arm64

**Bug Description:**
If you pull a type from a type archive that matches the name of a local type, your local type will be overwritten with no warning or confirmation from the user.

**Steps To Reproduce:**
1. Open an analysis database
2. Attach a type archive
3. Push a type to that type archive
4. Undefine the type locally
5. Define a new type with the same name, but different contents
6. Pull the type from the type archive
7. Observe that your local type was overwritten with no warning

**Expected Behavior:**
We warn in a lot of other circumstances where you might be pushing changes you don't want to overwrite something. This is an edge case we missed.

**Comment by CouleeApps** [comment]
This will be fixed in >= 4.0.4894-dev
