### ISSUE TITLE
Crash when opening file

### ISSUE THREAD

**Issue by negasora** [Vector35/binaryninja-api#5085]
Binary available to V35 by searching for `lord puffin powerful entourage`

**Comment by negasora** [comment]
Will be fixed in `4.0.4899-dev`

**Comment by plafosse** [comment]
Gotta share this with more people: 
<img width="985" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/10556585/182a1e79-6541-4379-8048-089da4a08c97">
