### ISSUE TITLE
Outlined rep movsd instruction that clobbers existing variable causes incorrect data flow

### ISSUE THREAD

**Issue by D0ntPanic** [Vector35/binaryninja-api#5086]
**Version and Platform (required):**
- Binary Ninja Version: 4.0.4896-dev
- OS: macOS
- OS Version: 14.3.1
- CPU Architecture: M3

**Bug Description:**
This binary writes a value to offset 0x20 on the stack, then memsets the entire region, including the variable just written, to zero using a `rep movsd` instruction. It then returns the value at offset 0x20 on the stack. This will return zero, but Binary Ninja loses track of the data flow and says the function returns 0x20.

This bug does not occur if an actual call to `memset` is emitted. In that case, Binary Ninja sees the alias and prevents the data flow system from assuming the variable hasn't been clobbered.

<img width="1170" alt="Screenshot 2024-02-21 at 2 40 06 PM" src="https://github.com/Vector35/binaryninja-api/assets/7007406/6bf6261b-b2b8-43c0-ad81-23a8dbdccf5b">

[repmovsd.zip](https://github.com/Vector35/binaryninja-api/files/14364371/repmovsd.zip)

**Comment by bpotchik** [comment]
Fixed in `4.1.4919-dev`.
