### ISSUE TITLE
Outlined functions appear as call to zero when disassembling in a new raw file

### ISSUE THREAD

**Issue by D0ntPanic** [Vector35/binaryninja-api#5087]
**Version and Platform (required):**
- Binary Ninja Version: 4.0.4896
- OS: macOS
- OS Version: 14.3.1
- CPU Architecture: M3

**Bug Description:**
Creating a new binary file, adding some assembly instructions to it, then creating a function out of those instructions can generate incorrect lifting if an outlined memset is detected.

<img width="1139" alt="Screenshot 2024-02-21 at 3 32 39 PM" src="https://github.com/Vector35/binaryninja-api/assets/7007406/8181ea1d-2a09-4b7a-8f0e-a8f9f57eb069">

The "function call" in this decompilation should be an outlined memset.

**Comment by bpotchik** [comment]
Fixed in `4.1.4920-dev`.
