### ISSUE TITLE
Updates on Windows revert site-packages to default

### ISSUE THREAD

**Issue by nbsdx** [Vector35/binaryninja-api#509]
Updates (at least the most recent update) revert `C:\Program Files\Vector35\BinaryNinja\plugins\Lib\site-packages` to the default state, but leave directories that were added (e.g., `PyQt5`). The folders remain, but the files are deleted.

**Comment by joshwatson** [comment]
A temporary fix to this is to install third party packages in the plugins directory. `import PyQt5` will work if it's there

**Comment by plafosse** [comment]
User files should never be placed in the BinaryNinja install directory. That whole directory can be deleted upon update. Plugins should be placed in the Binary Ninja user directory.
