### ISSUE TITLE
Collapse code regions in linear view

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#510]
Regions in linear view should be collapsable and should have a default preference. By default things like ELF/PE headers, IAT/PLT entries should be collapsed.  Should also implement keystrokes and clickable buttons to expand/collapse these regions.

**Proposed foldable items:**

- [ ] Structures and arrays
- [ ] Sections?
- [x] Code blocks, e.g. `if` statement branches

**Comment by plafosse** [comment]
This also applies to structures and arrays.

**Comment by ccarpenter04** [comment]
I would love to see this implemented

**Comment by yrp604** [comment]
With HLIL and linear view this would be really nice. Right now if you have an indent block that spans more than a screen width in HLIL's linear view, it can be very difficult to find the indentation points where blocks are terminated.

**Comment by psifertex** [comment]
There's a feature branch experimenting with adding indentation lines as well to help with this particular problem, though there's been some debate internally as to the right way to do it.

**Comment by jonpalmisc** [comment]
This would ideally include the ability to fold code blocks, e.g. long `if` statements. (#3311)

**Comment by BlasterXiao** [comment]
I very much support the suggestion mentioned by @psifertex  【Code blocks, e.g. if statement branches and Sections and Structures and arrays】This is very user friendly

**Comment by psifertex** [comment]
My original comment is super old and we actually do those bits. Code is not only indented according to structure but there are also empty lines to help differentiate:

<img width="1065" alt="Screenshot 2024-07-24 at 20 42 53" src="https://github.com/user-attachments/assets/3c8dbc69-c541-43d2-9749-2d47d50f9911">

The only thing left for this issue is the actual folding.

**Comment by BlasterXiao** [comment]
> My original comment is super old and we actually do those bits. Code is not only indented according to structure but there are also empty lines to help differentiate:
> 
> <img alt="Screenshot 2024-07-24 at 20 42 53" width="1065" src="https://private-user-images.githubusercontent.com/140215/351919443-3c8dbc69-c541-43d2-9749-2d47d50f9911.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5OTE1MTQsIm5iZiI6MTcyMTk5MTIxNCwicGF0aCI6Ii8xNDAyMTUvMzUxOTE5NDQzLTNjOGRiYzY5LWM1NDEtNDNkMi05NzQ5LTJkNDdkNTBmOTkxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNlQxMDUzMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Y2FmNmVhZTBmMTEzNGUwMzdkNWFkODJhNWE4OGU1ZDhjMWIyOTFlMTgzOTBiZGNiYjI3M2MxZjFjNjNkMDM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rTtdNgY94xpGLVPp0wq3s6eJ1OP5S5AroPl4Dc4sK8Q">
> The only thing left for this issue is the actual folding.
Yes, it would be very comfortable if you could add actual folding

**Comment by plafosse** [comment]
Code folding added 4.2.6274  Track https://github.com/Vector35/binaryninja-api/issues/6038 if you're interested in when DataVariable folding is implemented.
