### ISSUE TITLE
Crash when searching for Hex "c3" in notepad.exe on Windows

### ISSUE THREAD

**Issue by D0ntPanic** [Vector35/binaryninja-api#5104]
**Version and Platform (required):**
- Binary Ninja Version: 4.0.4903
- OS: Windows
- OS Version: 10
- CPU Architecture: x64

**Bug Description:**
Opening `c:\windows\notepad.exe` and searching for Hex of `c3` in the find sidebar widget crashes.

**Comment by plafosse** [comment]
Duplicate of #4854
