### ISSUE TITLE
some clang errors during type parsing not propagated back to the UI

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#5115]
Most notably `--taget=bogustarget` is one example, but there may be more. We should investigate and identify which errors are not being passed up and fix them.

**Comment by CouleeApps** [comment]
Looks like there are cases where the compiler invocation can fail to parse but no errors are reported. Uncertain why, but clang_svcs.cpp:1731

**Comment by CouleeApps** [comment]
Fixed in builds >= 4.1.4926 by just adding an extra error message when parsing fails but no errors are printed
