### ISSUE TITLE
Tag sidebar search bar shown but not interactable with tag types shown

### ISSUE THREAD

**Issue by negasora** [Vector35/binaryninja-api#5117]
1. Open a binary
2. Open the tag sidebar widget
3. Switch to `Tag Types`
4. Notice that the tag filter is still shown but cannot be interacted with

The widget is actually disabled but there's no visual indication unless the user had typed something in the filter box already

**Comment by 0cyn** [comment]
Resolved in **dev builds >= 4.1.4917**. It should now be far more obvious when a FilterEdit is disabled.
