### ISSUE TITLE
Project tab should be closable if it is the last tab in the window

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#5119]
Currently, if you want to switch projects, you have to `Cmd-Shift-N` to make a new window showing the New Tab and then click the X to close the project window. This is awkward and, more generally, not being able to `Cmd-W` to close the project window is annoying.

We should allow the Project Browser to be closed if it is the last tab left in a window. And, when it is, it should do the _opposite_ of what creating a new project window does: Open a new, non-project window with a New Tab. (If we already have one, it should just switch to the already open one.)

**Comment by psifertex** [comment]
To be clear, this is basically to add feature parity with the way non-project tabs work as well. Reverting back to a single "new tab page" tab and then that tab resulting in the window being closed is the same way tabs work on non-projects and we want the same consistent experience in projects.
