### ISSUE TITLE
Sidebar widgets still shown after icon removed from sidebar

### ISSUE THREAD

**Issue by negasora** [Vector35/binaryninja-api#5120]
Sidebar widgets should only be shown if they have a visible icon in the sidebar

1. Open `/bin/true`
2. Start debugging
3. Open `Debugger Modules`
4. Stop debugging
5. `Restart and Reopen Files`
6. Notice that `Debugger Modules` is still open, and can only be closed via command palette

**Comment by D0ntPanic** [comment]
If a widget is open for any reason there will now always be an icon for it in the sidebar. If a widget has the flag to hide on empty set, the icon will only be hidden after the widget is hidden.

Fixed in 4.1.4940
