### ISSUE TITLE
free version shows the changelog

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#5122]
It's hidden on initial load but pops back up later

**Comment by psifertex** [comment]
To reproduce, open a new tab and close it.

**Comment by xusheng6** [comment]
Also fixed by https://github.com/Vector35/binaryninja/commit/b48902b69b3c297c38430ab4566a4817775424c9. In fact, this has the same root cause as https://github.com/Vector35/binaryninja/issues/659

**Comment by plafosse** [comment]
Fixed in 4.0.4958-stable
