### ISSUE TITLE
Related line highlights don't work in Pseudo-C

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#5125]
**Version and Platform (required):**
- Binary Ninja Version: 4.0.4905-dev
- OS: macOS
- OS Version: 14.3.1
- CPU Architecture: arm64

**Bug Description:**
HLIL has related instruction highlighting in disassembly view:

![image](https://github.com/Vector35/binaryninja-api/assets/607452/4cb5859e-44fe-4e74-ad26-116f8ffce6ad)

Pseudo-C does not:

![image](https://github.com/Vector35/binaryninja-api/assets/607452/7cb232b5-6e69-49d8-9fec-5c7087ff8cdc)

**Steps To Reproduce:**
See above. Just switch between HLIL and Pseudo-C with a split pane that includes Disassembly.

**Expected Behavior:**
HLIL and Pseudo-C should have equivalent functionality.

**Comment by psifertex** [comment]
This was fixed in the 4.2 stable with the language representation refactor.
