### ISSUE TITLE
free edition cannot download external resources

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#5126]
The URL handler and "Open URL" menu items should probably be removed if they can't be easily fixed:

<img width="566" alt="Screenshot 2024-02-27 at 18 59 22" src="https://github.com/Vector35/binaryninja-api/assets/140215/78daf174-af75-4624-854e-86f169fbd12c">

(Spoiler: no, that setting is not disabled)

**Comment by psifertex** [comment]
<img width="578" alt="Screenshot 2024-02-27 at 19 01 46" src="https://github.com/Vector35/binaryninja-api/assets/140215/039c4a90-15e4-4a78-95fb-541b7f8a0334">

**Comment by psifertex** [comment]
All items that use network resources probably should be ifdef'ed out, or else that setting should be removed from the block that ifdefs it out of the free edition.

**Comment by psifertex** [comment]
Re-opening to track getting it into the re-release stable

**Comment by plafosse** [comment]
Fixed in 4.0.4958-stable
