### ISSUE TITLE
How can I reduce bndb size

### ISSUE THREAD

**Issue by baikaishiuc** [Vector35/binaryninja-api#5127]
**What is the feature you'd like to have?**
Please reduce bndb size

**Additional Information:**
![image](https://github.com/Vector35/binaryninja-api/assets/618485/14a18495-de44-42a7-955a-10be018b6e60)

bndb is 1000x size than original library file

**Comment by negasora** [comment]
You can also use `File` > `Save As` to save a new analysis database that will only include the most recent snapshot

**Comment by baikaishiuc** [comment]
> If you use File -> Save Analysis Database with Options you have the ability to prune undo history and snapshots from your bndb. If you've saved a lot of times these are likely to be large parts of the file size, and you can clean them if you weren't planning to go through your edit history.

Cool, file size now is very small.
