### ISSUE TITLE
First flag write type in Python API doesn't work

### ISSUE THREAD

**Issue by D0ntPanic** [Vector35/binaryninja-api#513]
The first type listed in the `flag_write_types` array for an Architecture doesn't work in the Python API. Does not affect the C++ API.

Workaround is to place a dummy, unused flag write type (such as an empty string) as the first in the array.

**Comment by joshwatson** [comment]
This issue is still not fixed, I still have to add a dummy flag write type as the first element of the array in order for flags to lift correctly

**Comment by psifertex** [comment]
Re-opening now. Think we have a fix, need to test.
