### ISSUE TITLE
ARM64 CSET and family need to be lifted differently

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#5134]
Higher levels of analysis struggle to deal with the way we've lifted cset. 
Original code:
<img width="495" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/10556585/01e9f771-e64f-422a-99c6-7e6baa45e48f">
Current decompilation
<img width="518" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/10556585/e3df99fc-804e-4e63-9f9b-7334ddf340ce">
Old code vs new code
<img width="683" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/10556585/0b0679f8-b6af-41c5-ae5b-ced81f376f3d">
Significantly improved decompilation
<img width="552" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/10556585/eb204746-e06f-4291-8742-24c8febfa7d7">

**Comment by galenbwill** [comment]
Got binary?

**Comment by plafosse** [comment]
[Archive.zip](https://github.com/Vector35/binaryninja-api/files/14538750/Archive.zip)

**Comment by plafosse** [comment]
O also FWIW my patch patch isn't correct but its close

**Comment by galenbwill** [comment]
With the latest expression improvements on dev, that change now produces this result:
![image](https://github.com/Vector35/binaryninja-api/assets/12259536/3684238e-acff-46b0-93c2-32732e56dfce)

**Comment by galenbwill** [comment]
Implemented in `4.1.5373-dev`

**Comment by galenbwill** [comment]
Just a note: other related operations (`cinc`, `cinv`, `csinv`, `csetm`, `csel`, `csneg`) did not seem to be as amenable to similar optimizations, but this may be worth revisiting.
