### ISSUE TITLE
Cannot filter Log View to "Default" logger

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#5136]
**Version and Platform (required):**
- Binary Ninja Version: 4.0.4911
- OS: Windows
- OS Version: 11
- CPU Architecture: x64

**Bug Description:**
I tried to set the Log View filter to only show logs with the Default logger (as opposed to Analysis or Core). But Default is not in the list of filter options!

**Steps To Reproduce:**
1. Open binja
2. Open log view
3. Try to set filter
4. ??? Cannot set to Default

**Expected Behavior:**
I expected every source of log messages to have a filter option in the list

**Screenshots:**
<img width="453" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/711973/acd484b1-dd05-4285-9fe2-c0f79838cd12">

**Additional Information:**
Probably just need to add it as an option in the list, since it's the Default there's probably no option registered for it specifically/

**Comment by 0cyn** [comment]
Resolved in **builds >= 4.1.4916**
