### ISSUE TITLE
endless analysis

### ISSUE THREAD

**Issue by skirge** [Vector35/binaryninja-api#5141]
**Version and Platform (required):**
- Binary Ninja Version: [e.g. 3.5 and 4.0]
- OS: [Ubuntu Linux]
- OS Version: [22.04]
- CPU Architecture: [x64]

**Bug Description:**
Analysis is stuck and never finishes.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open file 'access_server' (file sent by e-mail title "endless analysis")
2. observer analysis counter start increasing and analysis never finishes

**Expected Behavior:**
analysis should finish and (hopefully) all functions are analysed

**Additional Information:**
file was sent over e-mail titled "endless analysis" and confirmed by galen@vector35.com

**Comment by psifertex** [comment]
This has been resolved in the latest 4.1 development releases, most likely due to the optimizations introduced in https://binary.ninja/2024/06/19/restructuring-the-decompiler.html
