### ISSUE TITLE
Crash When Displaying FlowGraphs

### ISSUE THREAD

**Issue by samrussell** [Vector35/binaryninja-api#5147]
**Version and Platform (required):**
- Binary Ninja Version: 4911
- OS: Windows
- OS Version: 10
- CPU Architecture: x64

**Bug Description:**
Open binary ninja and type this in the console

```
Workflow().show_topology()
```

It crashes

**Comment by bpotchik** [comment]
This crash is triggered by generating many flowgraphs. Some examples are:

- show_[l|m|h]il_hierarchy() commands
- Workflow().show_topology()
- others?

**Comment by plafosse** [comment]
Fixed in 4.1.4918

**Comment by plafosse** [comment]
We're planning on pushing an updated 4.0 leaving this open until the new 4.0 is pushed.

**Comment by plafosse** [comment]
Fixed in 4.0.4958-stable
