### ISSUE TITLE
Skipping analysis for function at 0x8656b4 : Exceeds 'analysis.limits.maxFunctionUpdateCount'.

### ISSUE THREAD

**Issue by nathansrf** [Vector35/binaryninja-api#5156]
**Version and Platform (required):**
- Binary Ninja Version: 4.0.4911,  15e9149
- OS: macos
- OS Version: 14.2
- CPU Architecture: arm64

**Bug Description:**

Running analysis on the attached library results in:

[Function] Skipping analysis for function at 0x8656b4 : Exceeds 'analysis.limits.maxFunctionUpdateCount'. If possible, please report this issue.

Reporting just in case this is useful for you folks as per the log message :)

**Steps To Reproduce:**

Open libtmessages.48.so in Binja and allow analysis to run.

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

Lib is a .so object attached as .zip to appease GitHub.

[libtmessages.48.so.zip](https://github.com/Vector35/binaryninja-api/files/14495781/libtmessages.48.so.zip)

**Comment by galenbwill** [comment]
Maybe related similar issue: #5141

**Comment by plafosse** [comment]
This seems to be fixed as of at least 4.1
