### ISSUE TITLE
PE files causing hangs in analysis

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#5158]
**Version and Platform (required):**
- Binary Ninja Version: 4.0.4911
- OS: Linux
- CPU Architecture: x86-64

**Bug Description:**
An Enterprise customer has reported that certain PE files are causing hangs in analysis on 4.0 that were not previously present on 3.5.

This ticket is tracking the effort to track down why it's happening.

**Comment by CouleeApps** [comment]
Addressed in 4.1.4967-dev

**Comment by hanssl** [comment]
Here is a publicly available file that reproduces the issue: https://www.pconlife.com/download/otherfile/130619/2b93d69374aca5ac7abb171fb4a55eb0/

**Comment by CouleeApps** [comment]
Yep, can confirm: sample hangs on 4.0.4958-stable and does not hang on 4.1.4986-dev. Analysis of the hang reveals the exact stack trace that the mentioned fix is addressing. Thanks for the example!
