### ISSUE TITLE
Cannot use current_il_instruction in Lifted IL view

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#5159]
**Version and Platform (required):**
- Binary Ninja Version: 4.0.4911
- OS: macOS
- OS Version: 14
- CPU Architecture: arm64

**Bug Description:**
The `current_il_instruction` magic variable does not seem to understand Lifted IL view. It works in Low Level IL but I'm trying to quickly debug some code involving the output directly from a lifter, and this convenient variable is no longer convenient.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open any binary
2. Go to an address
3. Switch to Lifted IL view
4. In console: `current_il_instruction`
5. Value is None

**Expected Behavior:**
I expected the magic IL vars to work on ALL ILs

**Screenshots:**
<img width="514" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/711973/3f7ff2a2-3682-43b8-860a-1d093c2c0cf5">

**Additional Information:**
Also applies to Mapped MLIL (and SSA) and Pseudo-C

**Comment by negasora** [comment]
Fixed in `4.1.5585-dev`
