### ISSUE TITLE
Some Free users are being led to believe Mach-O files are unsupported

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#5162]
**Version and Platform (required):**
- Binary Ninja Version: 4.0.4911 Free
- OS: any
- CPU Architecture: any

**Bug Description:**
Using the free version, opening a universal macOS binary may seem like it is not supported if the user doesn't notice that they've loaded the `arm64` slice, which isn't a supported architecture in free.

**Steps To Reproduce:**
This only reproduces _sometimes_ - may be related to the order of the slices within the binary?

1. Install free version
2. Open fat Mach-O file
3. Choose `arm64` slice
4. See that things look unsupported

**Expected Behavior:**
We should prioritize loading slices that are supported within the user's edition of the product.

**Comment by bpotchik** [comment]
Fixed in `4.1.4945-dev`.

**Comment by SoCuul** [comment]
Is there any plans to include arm64 mach-o support for the free version of binary ninja? With the switch to apple silicon many apps will no longer have x64 builds in the future, or have already dropped support for it.

**Comment by psifertex** [comment]
Not currently but we are constantly re-evaluating.
