### ISSUE TITLE
support for better control of network activity / go offline

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#517]
We need an option that will prevent all online activity (or optionally present a dialog allowing an override but not allowing the action without explicit confirmation)

That includes:

- [ ] Checking for update channels (even if going to the preferences window)
- [ ] Plugin manager activity
- [ ] Expiration checks (from the about dialog)
- [ ] URL Handler (this already has a blocking dialog and maybe needs no changes?)
- [ ] Updates and update-available checks
- [ ] New tab active content

**Comment by bpotchik** [comment]
This is already controlled by the activeContent setting.

**Comment by psifertex** [comment]
Closing in favor of #2079
