### ISSUE TITLE
Comments on Lines with Dataflow Always Pushed to New Line

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#519]
If you make a comment on a line that has dataflow information, it will always push the comment above the line. It will do this regardless of how large the value is that has been calculated. Kinda annoying when you want to be able to read down a series of comments later. Both linear and graph view are affected.

<img width="525" alt="kirby's adventure input polling linear" src="https://cloud.githubusercontent.com/assets/607452/19463189/0b20322e-94c0-11e6-84b7-740755633985.png">

<img width="693" alt="kirby's adventure input polling graph" src="https://cloud.githubusercontent.com/assets/607452/19463158/d2d4f5e4-94bf-11e6-846e-a785f39bcb43.png">

**Comment by jeffli678** [comment]
related to https://github.com/Vector35/binaryninja-api/issues/708

**Comment by plafosse** [comment]
Closing in favor of #708
