### ISSUE TITLE
windows updater progress bar does not function

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#52]
When an update is being applied after a reboot, the windows update utility does not show a progress bar.

**Comment by plafosse** [comment]
Are you sure that its not just too fast? Maybe we can show a full progress bar and wait a second, so people fell more satisfied? :)

**Comment by plafosse** [comment]
Looked into this a bit one of the problems could be that windows doesn't update the progress bar quickly, there is a delay, but if you set it forward then back it will force it to update quickly.
SendMessage(hwndPB, PBM_SETPOS, percent+1, 0);
SendMessage(hwndPB, PBM_SETPOS, percent, 0);

**Comment by D0ntPanic** [comment]
Fixed in build 1341
