### ISSUE TITLE
API to rename Type’s name in python.

### ISSUE THREAD

**Issue by cesaryuan** [Vector35/binaryninja-api#5219]
**What is the feature you'd like to have?**
API to rename Type’s name in python.

**Is your feature request related to a problem?**
 I tried <StructureTypeInstance>.registered_name.name = “test”, but it not work. It said that AttributeError: can't set attribute 'name'.

**Are any alternative solutions acceptable?**
No.

**Additional Information:**
No.

**Comment by CouleeApps** [comment]
This API already exists: it's `BinaryView.rename_type`. See https://api.binary.ninja/binaryninja.binaryview-module.html#binaryninja.binaryview.BinaryView.rename_type
