### ISSUE TITLE
Cannot change how immediates are displayed when viewing in intermediate language

### ISSUE THREAD

**Issue by r0d** [Vector35/binaryninja-api#522]
When viewing in IL and using the "Display As" option, intermediates do not change. When switching back to assembly, the feature works perfectly fine.

**Comment by AdvenamTacet** [comment]
Right. Also, "Display As Binary" crashed me Binja, so it's not just command ignoring.

**Comment by psifertex** [comment]
Which version crashed? Dev or stable? Can you reproduce it reliably?

**Comment by AdvenamTacet** [comment]
Version `1.0.13 Personal` due to `About page`. I can (clicking random `Display As...` for about three~four minutes) -- finally crashed with exit code `139` while `Display As Signed Hexadecimal`.

**Comment by plafosse** [comment]
I think this issue was fixed, as I can't repro.
