### ISSUE TITLE
Link to scc.binary.ninja?

### ISSUE THREAD

**Issue by Manouchehri** [Vector35/binaryninja-api#523]
I might be blind, but I can't see a link to [scc.binary.ninja](https://scc.binary.ninja) anywhere on *.binary.ninja. Even Google'ing for "scc.binary.ninja" returns zero results, I had to ask in the Slack for it.

Should I add a link in `docs/getting-started.md`?

**Comment by psifertex** [comment]
That'd be great, thanks. Yeah, I need to add it to the support section of the website as well.

**Comment by psifertex** [comment]
Done.
