### ISSUE TITLE
Batch undefine function definitions in current selection

### ISSUE THREAD

**Issue by bb33bb** [Vector35/binaryninja-api#5232]
**What is the feature you'd like to have?**
Can a shortcut key be added?

As shown below:
![image](https://github.com/Vector35/binaryninja-api/assets/5463104/9b75f927-a2dd-400e-8e00-603e49a475d9)

When decompiling a binary file without any symbols, sometimes a portion of the data in the data segment is decompiled as code.

In this case, it is necessary to batch-cancel function definitions.

**Is your feature request related to a problem?**
NO

**Are any alternative solutions acceptable?**
select memory then define them as data?

**Comment by bb33bb** [comment]
maybe we need a method to select many pages of data?
Now i have to use this method:

https://github.com/Vector35/binaryninja-api/assets/5463104/caf44437-5117-44ec-9a24-9a3dba2d506a

**Comment by xusheng6** [comment]
Related to https://github.com/Vector35/binaryninja-api/issues/5281
