### ISSUE TITLE
Wrong synthetic function

### ISSUE THREAD

**Issue by reversing-dev** [Vector35/binaryninja-api#5240]
**Version and Platform (required):**
- Binary Ninja Version: 4.1.5071-dev Personal, 41729337
- OS: windows
- OS Version: 11
- CPU Architecture: x86_64

**Bug Description:**
`movsb` is lifted to `memset` instead of `strncpy`

**Screenshots:**
![image](https://github.com/Vector35/binaryninja-api/assets/42991292/08bc922a-5815-4c39-abda-c3f1aed721b2)

File: same as #4758 

It used to  work fine (like in #4758).

**Comment by bpotchik** [comment]
Fixed in `4.1.5075-dev`.
