### ISSUE TITLE
Non-ascii characters overlap in comment

### ISSUE THREAD

**Issue by bb33bb** [Vector35/binaryninja-api#5249]
**Version and Platform (required):**
- Binary Ninja Version:4.1.5075-dev Personal (9c39dc55)
- OS:Manjaro
- OS Version: Linux version 6.6.19-1-MANJARO (builduser@fv-az1021-257) (gcc (GCC) 13.2.1 20230801, GNU ld (GNU Binutils) 2.42.0) #1 SMP PREEMPT_DYNAMIC Fri Mar  1 18:16:16 UTC 2024
- CPU Architecture: x64

**Bug Description:**
when adding comment to binaryNinja, comment will displayed NOT OK

**Screenshots:**

https://github.com/Vector35/binaryninja-api/assets/5463104/27c43963-1b2a-4424-a97f-84246ee9179f

**Comment by negasora** [comment]
I'm unable to repro this with some sample comments - can you share one that repros this issue?

**Comment by bb33bb** [comment]
> I'm unable to repro this with some sample comments - can you share one that repros this issue?

OK, i will try today

**Comment by bb33bb** [comment]
> I'm unable to repro this with some sample comments - can you share one that repros this issue?

I think it was patched , in my computer also can not reproduce.
So i closed this issue.
