### ISSUE TITLE
add a command-line plugin loader

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#525]
To make it easier to run batch jobs without having to manually set the PYTHONPATH, for example. 

Likely requires replacing the current main executable with a shim that would either load a command-line plugin or the UI as appropriate based on the command-line arguments so it's easier for users to automate and doesn't violate the principal of least surprise. 

Possible extension: implement dedicated argument passing just for CLI plugins?

**Comment by pgoodman** [comment]
Yes to dedicated argument passing. If you also need to pass arguments to binary ninja, then you could have something like (at least for unix):

```
binaryninja --arg_to_binja -- plugin_command --args_to_plugin
```

Where `plugin_command` would be an arbitrary executable file or command (in the general case it would probably be a python file, or command installed for a python program using an egg).

**Comment by psifertex** [comment]
After some more thought we've decided not to implement this. Our intended workflow for this type of solution is with a headless script. We've also added a few [other](https://docs.binary.ninja/guide/plugins.html#troubleshooting) options that help make working with headless scripts with or without plugins a bit easier which was another previous reason for this approach.
