### ISSUE TITLE
unable to click the lock/unlock icon when maximized on macos

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#5277]
**Version and Platform (required):**
- Both 4.5 stable and 5109 (latest dev as of today)

When BN is maximized on MacOS, the new and smaller lock/unlock icon is unclickable. The tooltip shows up up to click on it but as you can see the cursor is showing the "resize" behavior which is indeed what happens.

Bug isn't new, was the case even with the larger lock icon in previous BN versions, however it was easier to work around.
<img width="317" alt="Screenshot 2024-04-14 at 11 42 41" src="https://github.com/Vector35/binaryninja-api/assets/140215/3aaf4798-01ef-44fd-9515-938c77076a88">

**Comment by psifertex** [comment]
I did find there's about a 4pixel square I can click on with my current resolution as a temporary work around so if you know the bug is there you can at least do that instead of resizing the window first and then clicking

**Comment by fuzyll** [comment]
I believe I have fixed this now in builds >= 4.2.6246-dev. If this isn't _enough_ space, or if there are situations in which this doesn't seem to work right, please let me know and I'll refine it further.
