### ISSUE TITLE
Function Pointers Not Identified and Disassembled Automatically

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#529]
In the attached CTF service, the last function called by `main` takes a function pointer as the 3rd argument. In the function (`sub_8049630`), it very clearly takes the 3rd argument and, after having stored it on the stack, calls it (the `call ecx` at 0x08049730). I would expect Binary Ninja's analysis to understand this is a function pointer as a result and disassemble the function pointer (0x08048ea0, loaded into `edx` in `main` at 0x08049192). Unfortunately, it does not. (Manually navigating to the function and hitting `p` will result in the rest of the binary being disassembled automatically.)

[tomato.zip](https://github.com/Vector35/binaryninja-api/files/549513/tomato.zip)

This is a specific test case for tickets #527 and #528.

**Comment by plafosse** [comment]
I'm closing this and referencing this ticket in #527 and #528
