### ISSUE TITLE
Allow the user to set the 0x0 (zero) base in the stack widget

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#5297]
### Discussed in https://github.com/Vector35/binaryninja-api/discussions/5289

The user suggested that we should support setting an alternative zero for the stack widget. For example, he sometimes wish to set the saved ebp as 0x0, so that when he seems some code like move [ebp-0x44], 0x1, he can see the variable immediately. 

My personal opinion is his issue might also be solved by https://github.com/Vector35/binaryninja-api/issues/5269, but this is still a valid feature request and the feature is nice to have

<div type='discussions-op-text'>

<sup>Originally posted by **utkonos** April 17, 2024</sup>
<img width="600" alt="Screenshot 2024-04-16 at 15 29 56" src="https://github.com/Vector35/binaryninja-api/assets/2775739/089e6c05-afbd-43f9-80be-ec008d5374b3">

In this function, there is a stack alignment at 1 which results in one or two stack slots. Also, at 2 a frame pointer is established which is subsequently used to refer to stack variables in the frame of the previous function as shown at 3. In the Stack pane, the distances shown are static.

Over in x64dbg-land, there is an elegant feature in the stack view where double clicking on a location in the stack sets that as zero and then marks the slots north and south of that location with the appropriate distance. I was reliably informed that this feature dates back to OllyDbg: https://twitter.com/Hexacorn/status/1764068094811529495 How I missed that I don't know, but it is super useful.

![ScreenFlow](https://github.com/Vector35/binaryninja-api/assets/2775739/72213697-7606-45fd-9731-864dc0886bca)

This should happen when I double click one of the distance values in the first colunm of the Stack pane shown in red in the following screenshot.

<img width="268" alt="Screenshot 2024-04-16 at 15 51 59" src="https://github.com/Vector35/binaryninja-api/assets/2775739/420f5efe-89fb-4a73-816e-a38953ade4d6"></div>

**Comment by CouleeApps** [comment]
This has been implemented as of >= 4.1.5256-dev: you can double-click the offset and it will base the rest of the stack view from where you clicked.
