### ISSUE TITLE
UI Elements Unintentionally Capturing Scroll Events

### ISSUE THREAD

**Issue by ChrisKader** [Vector35/binaryninja-api#5298]
**Version and Platform (required):**
- Binary Ninja Version: 4.1.5135-dev Personal, d14e3281
- OS: macos
- OS Version: 14.5
- CPU Architecture: arm64

**Bug Description:**
When scrolling through the UI (Settings, for example) UI elements that can be modified using the scroll wheel (such as "spinner" boxes) capture scroll events if they happen to land under the cursor (even if by accident).

**Steps To Reproduce:**
Open Settings and scroll using a mouse wheel (or trackpad). Your cursor will need to be in an area that would result in it being over an element that can be modified by scroll events.

**Expected Behavior:**
Continue scrolling past such elements. Only modify the values of the element if the element is intentionally selected.

**Screenshots:**

https://github.com/Vector35/binaryninja-api/assets/633360/8a7225e3-a1fa-4922-b96e-cf73f60fdad9

**Additional Information:**

**Comment by galenbwill** [comment]
Also worth noting that a combobox/drop-down widget will capture scroll events if the scrolling is initiated with the mouse over it, though it won't actually change its value unless selected.

The mouse pointer must be moved from over the widget before normal scrolling of the surrounding pane can be performed.

**Comment by plafosse** [comment]
This works like many other UI paradigms like websites. Closing as 'Won't fix"
