### ISSUE TITLE
aarch64 elf symbols failing to properly demangle

### ISSUE THREAD

**Issue by CunningLogic** [Vector35/binaryninja-api#5299]
**Version and Platform (required):**
- Binary Ninja Version: 4.1.5135-dev Personal (d14e3281)
- OS: Ubuntu Linux
- OS Version: 22.04
- CPU Architecture:x64
- Target: aarch64 linux elf

**Bug Description:**
Please provide a clear and concise description of what happened.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1) Open binary
2) Wait for analysis
3) Wonder why all the symboles are _1, _2, _3 etc (multiples of each)

**Expected Behavior:**
It appears function names are demangled improperly, for example this function in the attached binary: 
_ZN3art15instrumentation15Instrumentation21InitializeMethodsCodeEPNS_9ArtMethodEPKv is demangled as _9 which appears to be a substring of the original mangled name.

I have seen this in multiple binaries, Android as well as for other forms of ARM linux.

**Screenshots:**
If applicable, please add screenshots here to help explain your problem.

**Additional Information:**
Please add any other context about the problem here.

See _ZN3art15instrumentation15Instrumentation21InitializeMethodsCodeEPNS_9ArtMethodEPKv at 0x3d8e70

[libart.so.zip](https://github.com/Vector35/binaryninja-api/files/15031290/libart.so.zip)

**Comment by CunningLogic** [comment]
![Screenshot from 2024-04-18 09-17-38](https://github.com/Vector35/binaryninja-api/assets/616385/52e5ac7b-2308-4f98-8d37-c5b074107353)

![Screenshot from 2024-04-18 17-51-38](https://github.com/Vector35/binaryninja-api/assets/616385/e3579860-89a5-44ba-b4bf-0541407bb784)

**Comment by negasora** [comment]
This is fixed in `4.1.5594-dev`, I think the exact version it was fixed in is `4.1.5239-dev`
