### ISSUE TITLE
Theme and colors for BN tend to switch unexpectedly while ALT+TABing repeatedly

### ISSUE THREAD

**Issue by thel3l** [Vector35/binaryninja-api#530]
`uname -a:`

```
Linux kali 4.3.0-kali1-amd64 #1 SMP Debian 4.3.3-5kali4 (2016-01-13) x86_64 GNU/Linux
```

_Description:_ While working with a loaded binary and repeatedly alt-tabbing, BN messes up the colors and selected themes - the working windows stay dark while the UI turns to the classic theme.

**Comment by plafosse** [comment]
This is a UI issue with QT. We're not going to try to fix this.
