### ISSUE TITLE
analysis fails to complete when load is called from some contexts

### ISSUE THREAD

**Issue by jim-carciofini** [Vector35/binaryninja-api#5302]
**Version and Platform (required):**
- Binary Ninja Version: 4.0.4958 (ddff9339) and dev version 4.1.5144
- OS: macOS 
- OS Version: 13.6.6 (22G630)
- CPU Architecture: M2

**Bug Description:**
When calling load from the GUI event thread or a worker thread, analysis fails to complete.

**Steps To Reproduce:**
See attached code fragment. It will add 4 menu items to the Plugins menu. Two exhibit the bug. Two show load working properly. The attached example binary was used, but I do not believe there is anything particular about this binary that causes the problem. I have seen the same behavior on other bins.

**Expected Behavior:**
After load() and calling bv.update_analysis_and_wait() analysis should be complete and all function info should be available.

**Screenshots:**
None

**Additional Information:**
[load-bug.zip](https://github.com/Vector35/binaryninja-api/files/15044881/load-bug.zip)

**Comment by bpotchik** [comment]
The log prints either of the following depending if you're using a Worker thread or UI thread.

> [:21 Analysis] Worker threads are not permitted to wait for analysis completion.
or
> [:97 Analysis] UI threads are not permitted to wait for analysis completion.

I've updated the documentation for the `update_analysis_and_wait` method to be more clear.

You can use the `add_analysis_completion_event` to schedule an action after the analysis completes.
