### ISSUE TITLE
Create array dialog's default array size can overwrite exising code

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#5305]
The current code logic only takes account into the next data variable or the segment end, and it ignores the next basic block, which could cause the default size to be too large

**Comment by xusheng6** [comment]
This will be fixed by https://github.com/Vector35/binaryninja-api/compare/test_improve_create_array

**Comment by plafosse** [comment]
This should call 'GetNextUnknownDataEnd'
