### ISSUE TITLE
Mach-O thumb entry point issue

### ISSUE THREAD

**Issue by withzombies** [Vector35/binaryninja-api#531]
I think the Mach-O loader gets the entry point wrong for thumb binaries.

I made a small armv7/thumb2 binary and loaded it into binja. It's entry point is at 0BEC8, which gets created as thumb and labeled main(). Additionally, 0BEC9 is created and marked as thumb, disassembled misaligned. Thumb disassembly has a minimum alignment of 2, so 0BEC9 should never be a valid instruction.

I've attached the binary.

[test_thumb.zip](https://github.com/Vector35/binaryninja-api/files/554615/test_thumb.zip)

**Comment by D0ntPanic** [comment]
Fixed in dev
