### ISSUE TITLE
PowerPC Instruction Alignment Change

### ISSUE THREAD

**Issue by Martyx00** [Vector35/binaryninja-api#5310]
**What is the feature you'd like to have?**
I would like to change the instruction alignment form current value `4` to `2` (https://github.com/Vector35/binaryninja-api/blob/6929009578958634304404179659515738797945/arch/powerpc/arch_ppc.cpp#L328). 

**Is your feature request related to a problem?**
If the alignment will be set to `2`, it would be easy to create a `ppc` architecture extension to support VLE encoding which adds 2-byte instructions. Currently, if the alignment is set to `4`, branches fail to resolve.

**Are any alternative solutions acceptable?**
I am extending PPC architecture to support VLE instructions with this (currently heavily in progress) plugin: https://github.com/Martyx00/PowerPC-VLE-Extension
Alternative would be to treat PowerPC with VLE instructions as a separate architecture.

**Additional Information:**
None

**Comment by plafosse** [comment]
The best bet would be to make the PPC-VLE a separate architecture, as changing the alignment could have some negative consequences for things like linearsweep.
