### ISSUE TITLE
Load only PDB types option and more

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#5311]
### Discussed in https://github.com/Vector35/binaryninja-api/discussions/5303

<div type='discussions-op-text'>

<sup>Originally posted by **uniquadev** April 20, 2024</sup>
Currently, when importing debug information with a pdb file, there is no pop-up window that allows you to toggle loading options. In my scenario, I have a pdb file that doesn't match the current binary; however, the types do match. It would be useful to have the ability to toggle some loading options..</div>

**Comment by CouleeApps** [comment]
Setting for this added in >= 4.1.5423-dev as `pdb.features.parseSymbols`
