### ISSUE TITLE
function recognizer missing some MIPS imports from 2.4->3.0

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#5329]
Between stable builds 2.4 and 3.0 this particular MIPS sample no longer has its imports properly recognized so that symbol information can be propogated:
[tdpServer_190726.zip](https://github.com/Vector35/binaryninja-api/files/15113164/tdpServer_190726.zip)

![BN_4 1 5172_dev_tdpServer_190726](https://github.com/Vector35/binaryninja-api/assets/140215/dd3263f7-5a37-4593-8eca-c3d70182ffc5)
![BN_2 4 21846_tdpServer_190726](https://github.com/Vector35/binaryninja-api/assets/140215/9b177e21-7648-4144-bb33-baae4d75a088)

**Comment by negasora** [comment]
Fixed in `4.1.5177-dev`
