### ISSUE TITLE
Types for platform mac-thumb2 failed to load

### ISSUE THREAD

**Issue by withzombies** [Vector35/binaryninja-api#533]
I was playing with the type parser by entering this into the console (with a mac thumb2 bv open):

```
bv.parse_type_string("int (*lol)(int one, void* two, size_t three)")
```

I got this error:

```
Types for platform mac-thumb2 failed to load: /Applications/Binary Ninja.app/Contents/Resources/types/platform/mac-thumb2.c:1: error: include file 'mac-armv7.c' not found
```

**Comment by plafosse** [comment]
Fixed in dev

**Comment by psifertex** [comment]
Works in current stable too for that matter for me. Can you double check that's true for you too @withzombies?

**Comment by withzombies** [comment]
I saw @D0ntPanic commit a fix for it within an hour of me filing the ticket. I guess we both forgot to close it.
