### ISSUE TITLE
Symbols View Should Be AND Operand Search

### ISSUE THREAD

**Issue by SmoothHacker** [Vector35/binaryninja-api#5348]
**Version and Platform (required):**
- Binary Ninja Version: 4.1.5207-dev
- OS: MacOS Sonoma
- OS Version: 14.4.1
- CPU Architecture: M1

**Bug Description:**
The symbols view use to have AND operand search when 2 words separated by a space was specified. Now it is OR operand search.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open any binary with symbols
2. Input 2 different common words that are in symbol names

**Expected Behavior:**
Symbols Search should be AND operand search

**Screenshots:**
<img width="368" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/16490754/0a9e61cd-c64b-4fab-b79e-61397d58837f">

**Comment by xusheng6** [comment]
I am not sure whether this is intended, will need some discussion
