### ISSUE TITLE
Two binaries open in split-screen means two check for update menu items

### ISSUE THREAD

**Issue by bkerley** [Vector35/binaryninja-api#536]
Version 1.0.317 (2016-10-10 21:21:03)

Closing one of the files leaves the two menu options in place. Closing both files takes it back down to one menu item.

![screen shot 2016-11-03 at 15 50 40 hacked](https://cloud.githubusercontent.com/assets/4354/19982810/ecc89ffc-a1dd-11e6-898b-bcb4e3fa7a4f.png)

**Comment by tentpegbob** [comment]
Just a quick update - the more windows you have open the more "check for updates" that appear - and all the windows open try to update when clicking "check for updates"

**Comment by bkerley** [comment]
Haha nice

**Comment by psifertex** [comment]
Looks like a QT Bug: https://bugreports.qt.io/browse/QTBUG-13898

Easiest fix is to move the `Update` menu item back to the Help menu where it is on other platforms until QT fixes their bug. Violates the normal conventions on OS X, but better than having it be broken for multiple windows.

**Comment by D0ntPanic** [comment]
Fixed in build 1457
