### ISSUE TITLE
Unable to change the width of the size column in the types sidebar

### ISSUE THREAD

**Issue by bb33bb** [Vector35/binaryninja-api#5361]
**What is the feature you'd like to have?**
need to chagen the  width of the column
**Is your feature request related to a problem?**
No

![image](https://github.com/Vector35/binaryninja-api/assets/5463104/06d5baa8-5837-40fd-8538-39758d22a35c)

**Comment by xusheng6** [comment]
Similar to: https://github.com/Vector35/binaryninja-api/issues/5247

**Comment by bb33bb** [comment]
> Similar to: https://github.com/Vector35/binaryninja-api/issues/5247

是的^ - ^

**Comment by xusheng6** [comment]
Hi @bb33bb, I am curious why would you wish to change the width of the that column? Right now the layout logic is like this, the right column (type size) is resized to the minimum width to host the content, and the name column stretches the remaining width. I do not see a clear motivation to change it

**Comment by bb33bb** [comment]
> Hi @bb33bb, I am curious why would you wish to change the width of the that column? Right now the layout logic is like this, the right column (type size) is resized to the minimum width to host the content, and the name column stretches the remaining width. I do not see a clear motivation to change it

谢谢！我们可以看到这张图中，地址显示不全。
![image](https://github.com/user-attachments/assets/98d66008-f270-4f0a-b52e-d17c5613cb4f)
但是确实如您所说，这里的issue中，没有明显标识，需要拖动列宽。

**Comment by bb33bb** [comment]
这个问题确实不大。只有右侧的size超过显示宽度也许才有必要拖动。如果没有疑问，我可以关闭这个issue。
三天后如果没有回复，我就主动关闭这个issue了哈。因为问题确实很小很小。

**Comment by bb33bb** [comment]
> Hi @bb33bb, I am curious why would you wish to change the width of the that column? Right now the layout logic is like this, the right column (type size) is resized to the minimum width to host the content, and the name column stretches the remaining width. I do not see a clear motivation to change it

这个问题确实不大。只有右侧的size超过显示宽度也许才有必要拖动。如果没有疑问，我可以关闭这个issue。
三天后如果没有回复，我就主动关闭这个issue了哈。因为问题确实很小很小。
