### ISSUE TITLE
CallingConvention can not be instantiated with just an arch

### ISSUE THREAD

**Issue by bambu** [Vector35/binaryninja-api#539]
Instantiating `CallingConvention` with just arch will crash BinaryNinja because calling `BNCreateCallingConvention`. `self.__class__.name` is `None` as it is not set to anything. The fix could be to allow `__init__` to take in a name for the calling convention or just removing the creation and requiring people to inherit from it. 

https://github.com/Vector35/binaryninja-api/blob/dev/python/__init__.py#L9366

**Comment by plafosse** [comment]
Fixed in dev.
