### ISSUE TITLE
BinaryNinja crashes on startup (PyType_Ready gets NULL pointer)

### ISSUE THREAD

**Issue by edd255** [Vector35/binaryninja-api#5392]
**Version and Platform:**
- Binary Ninja Version: 4.0.4958 Personal and 4.1.5261-dev Personal
- OS: Fedora Linux (Workstation Edition)
- OS Version: 40
- CPU Architecture: x64

**Bug Description:**
BinaryNinja crashes with a segmentation fault on startup. The logs are attached. It seems that the binary tries to dereference the address 0xa8. The function `PyType_Ready` is called with a NULL pointer as an argument.

According to `gdb`, this is the stack trace:
```
[#0] 0x7fffbe3f65a4 → PyType_Ready()
[#1] 0x7fffd1cbb360 → Shiboken::init()()
[#2] 0x7fffd1cd70dd → Shiboken::Module::create(char const*, void*)()
[#3] 0x7fffd3422389 → PyInit_Shiboken()
[#4] 0x7fffbe4313c7 → _imp_create_dynamic()
[#5] 0x7fffbe3910c2 → cfunction_vectorcall_FASTCALL()
[#6] 0x7fffbe376d14 → _PyEval_EvalFrameDefault()
[#7] 0x7fffbe39042b → object_vacall()
[#8] 0x7fffbe3aecba → PyObject_CallMethodObjArgs()
[#9] 0x7fffbe3ae5b2 → PyImport_ImportModuleLevelObject()
```

I have tested this under Wayland and X11. At first, it looked like a `xcb-cursor` error from my side, but after executing `chmod +x libxcb-cursor.so.0` it turned out the issue came from something different.

I have re-downloaded a fresh install.

**Steps To Reproduce:**
Use the versions of the binaries described above and execute `export BIN_DISABLE_USER_SETTINGS=1; gdb ./binaryninja -p -w`.

**Expected Behavior:**
BinaryNinja should start without crashes.

**Additional Information:**
Logs are attached.
[logs.txt](https://github.com/Vector35/binaryninja-api/files/15272750/logs.txt)

**Comment by xusheng6** [comment]
Fedora is not an officially supported distribution so we probably would not be fixing this. Also the setting is called "BN_DISABLE_USER_SETTINGS", you had an extra "i" in it

**Comment by edd255** [comment]
Thanks for pointing out the setting name was wrong. Unfortunately, it did not anything.

**Comment by edd255** [comment]
It seems like that this is related to this issue on [Qt for Python](https://bugreports.qt.io/browse/PYSIDE-2747).
