### ISSUE TITLE
GUI _hang_ when loading large c++ binary

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#540]
GUI appears to hang when loading large c++ binary such as libxul. This is due to the file format parsing being done on the same thread as the ui. Part of binary parsing is creating hundreds of thousands of type objects. Solution is to do binary parsing in its own thread. 

Current work around... be patient :P

**Comment by negasora** [comment]
Looks like this is because of handling relocations on the main thread. Adding a progress indicator would solve this, since that's an important part of finalizing the bv

**Comment by plafosse** [comment]
Closing this in favor of: #2604
