### ISSUE TITLE
Crash during analysis

### ISSUE THREAD

**Issue by trumank** [Vector35/binaryninja-api#5404]
**Version and Platform:**
- Binary Ninja Version: 4.1.5261-dev Personal, 859dedd4
- OS: arch
- OS Version: unknown
- CPU Architecture: x86_64

**Bug Description:**
I have a windows-x86_64 exe that is causing a crash shortly into analysis. I can share the exe privately where directed.

**Comment by xusheng6** [comment]
Please email this to us via binaryninja@vector35.com

**Comment by fuzyll** [comment]
User sent binary to support email, available internally by searching for `whispering cactus dance marathon`.

**Comment by negasora** [comment]
Fixed in `4.1.5272-dev`
