### ISSUE TITLE
Function listed twice

### ISSUE THREAD

**Issue by joelreymont** [Vector35/binaryninja-api#5407]
**Version and Platform (required):**
- Binary Ninja Version: 4.1.5261-dev, 859dedd4
- OS: macos
- OS Version: 14.4
- CPU Architecture: arm64

Internal binary `major dine favor`.

See `DjiAccessAdapter_GetCmdHandle`. 
<img width="849" alt="Screenshot 2024-05-13 at 4 21 43 PM" src="https://github.com/Vector35/binaryninja-api/assets/18791/5535e18a-7af7-4a25-a310-49d348e7cc85">

```
000cf930  int64_t DjiAccessAdapter_GetAircraftSeries(enum E_DjiAircraftSeries* series)

000cf948      *series = AIRCRAFT_SERIES
000cf954      return 0


000cf958  struct CommandManager* DjiAccessAdapter_GetCmdHandle()

000cf964      return CBK_MGR


000cf958  struct CommandManager* DjiAccessAdapter_GetCmdHandle()

000cf964      return CBK_MGR


000cf968  uint64_t DjiAccessAdapter_IsAccessFinished()

000cf974      return zx.q(s_isAccessAdapterFinished)
```

**Comment by plafosse** [comment]
Did you happen to create this function or did auto analysis do this? One of the functions has a platform of linux-aarch64 and the other has a platform of just aarch64.

**Comment by joelreymont** [comment]
I don't really remember. I did create some functions and used aarch64 as the architecture. 

Should I have used linux-aarch64?
