### ISSUE TITLE
get_parameter_at crashes BN on MIPS binaries

### ISSUE THREAD

**Issue by polsab** [Vector35/binaryninja-api#542]
To replicate, enter this on Python console:
current_function.get_parameter_at(bv.arch, here, None, 0)

As far as I can tell, it crashes no matter where "here" is.

Happens on all MIPS binaries I've tried so far but if you need samples let me know.

**Comment by plafosse** [comment]
This bug doesn't seem to exist any longer. Tested on 1.0.893. With: `current_function.get_parameter_at(here, None, 0)`
