### ISSUE TITLE
History widget doesn't reanalyze after an undo action

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#5432]
**Version and Platform (required):**
- Binary Ninja Version: 4.1.5295-dev
- OS: macOS
- OS Version: 14.5
- CPU Architecture: aarch64

**Bug Description:**
Right-clicking on an action in the history widget and undoing to that action properly triggers the undo actions, but does not "refresh" linear view. This can lead to some weird situations where e.g. a variable is still typed with a struct that has been completely removed (pressing `y` on it leads to an error where it can't find the type).

This can be trivially worked around by hitting Cmd-Z and then Cmd-Shift-Z, which goes through the normal undo keybindings.

The problem is likely that reanalysis needs to be triggered after the undo action in order to update linear view.

**Steps To Reproduce:**
See above.

**Expected Behavior:**
See above.

**Comment by negasora** [comment]
Fixed in `4.1.5305-dev`
