### ISSUE TITLE
Detecting pointer to C strings in the data section

### ISSUE THREAD

**Issue by uniquadev** [Vector35/binaryninja-api#5434]
**What is the feature you'd like to have?**
Auto C string detection when pointer to string is found.

Imagine the following pseudo structure
```
static const Func[] libs_funcs = {
 {"print", &print_func},
 {"measure2", &measure_2}
};
```
By searching for `measure2` in the strings view, you will notice that no cross-references to it are present, even if there is a pointer to it in the .rdata section. This results in having to manually create a C string to make the xref appear. Typically, we don't have the address of the structure, and if the xref was present, it would be much easier to look it up.

**Are any alternative solutions acceptable?**
A simple plugin could solve this issue but I belive this must be a core feature.
The  solution would be to consider making a reference or directly make the C string during auto analysis.

**Additional Information:**
![binaryninja_NhS63nnRpC](https://github.com/Vector35/binaryninja-api/assets/58218460/6d4fe8d1-a4a4-40bc-a954-70ab4f3152a2)
![binaryninja_Rr3DFnn6XX](https://github.com/Vector35/binaryninja-api/assets/58218460/19cf5371-3b66-4855-9c0a-d4d8da4f6d80)
Now reference appear
![binaryninja_s4FhsRdNbf](https://github.com/Vector35/binaryninja-api/assets/58218460/e0915f47-165d-41f4-b7b6-bb12bfbe2a1d)
**Expected result through auto analysis**
![image](https://github.com/Vector35/binaryninja-api/assets/58218460/b5c528f6-1f87-46b3-8f36-6063b3d4080d)

**Comment by xusheng6** [comment]
@uniquadev could you please share with us the binary? I myself have surely seen a similar case before, but I do not have a handy binary at the moment.

**Comment by uniquadev** [comment]
> @uniquadev could you please share with us the binary? I myself have surely seen a similar case before, but I do not have a handy binary at the moment.

Roblox Client x64
https://1drv.ms/u/s!Aj5-93tqspwHgeVlhr0R_c0rJjOsDA?e=GfUvPs

Simpler binaries can be found here
https://github.com/luau-lang/luau/releases/tag/0.626

**Comment by xusheng6** [comment]
> > @uniquadev could you please share with us the binary? I myself have surely seen a similar case before, but I do not have a handy binary at the moment.
> 
> Roblox Client x64 https://1drv.ms/u/s!Aj5-93tqspwHgeVlhr0R_c0rJjOsDA?e=GfUvPs
> 
> Simpler binaries can be found here https://github.com/luau-lang/luau/releases/tag/0.626

thx, I will have a look at it!

**Comment by xusheng6** [comment]
This issue gets a lot of thumbs-up after the initial filing -- this might be a blind spot in binja interaction that we should really prioritize

**Comment by xusheng6** [comment]
> > @uniquadev could you please share with us the binary? I myself have surely seen a similar case before, but I do not have a handy binary at the moment.
> 
> Roblox Client x64 https://1drv.ms/u/s!Aj5-93tqspwHgeVlhr0R_c0rJjOsDA?e=GfUvPs
> 
> Simpler binaries can be found here https://github.com/luau-lang/luau/releases/tag/0.626

Can you point me at a particular file and offset that I should look at for the luau binary?

**Comment by xusheng6** [comment]
We are only defining a string data variable for those strings that are referenced by code:

![Screenshot 2024-05-20 at 4 26 49 PM](https://github.com/Vector35/binaryninja-api/assets/94503187/f7df6cbc-789c-4c95-8f59-e440803c43a4)

In the above screenshot, we failed to define these strings because we do not see a code xref to it. This should be changed to also include data xrefs

**Comment by uniquadev** [comment]
> We are only defining a string data variable for those strings that are referenced by code:
> 
> ![Screenshot 2024-05-20 at 4 26 49 PM](https://private-user-images.githubusercontent.com/94503187/331996151-f7df6cbc-789c-4c95-8f59-e440803c43a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxOTQwMjAsIm5iZiI6MTcxNjE5MzcyMCwicGF0aCI6Ii85NDUwMzE4Ny8zMzE5OTYxNTEtZjdkZjZjYmMtNzg5Yy00Yzk1LThmNTktZTQ0MDgwM2M0M2E0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA4Mjg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwMmFhZmE5NTBmZWI4YzEwODlhNDdhZGI3MTE0YTNkNGViYjQzNmRhMTQ4NTRlMmI4YmZlNGI0NWJjY2JmM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7psQXKy-Aicwk_8uci6mWFMCtPMpbuDWEtXRsKtgtro)
> 
> In the above screenshot, we failed to define these strings because we do not see a code xref to it. The `bit32` string is defined because there is code that references it. This should be changed to also include data xrefs

I noticed this behavior too, but I wasn't sure if it was planned

**Comment by xusheng6** [comment]
> > We are only defining a string data variable for those strings that are referenced by code:
> > ![Screenshot 2024-05-20 at 4 26 49 PM](https://private-user-images.githubusercontent.com/94503187/331996151-f7df6cbc-789c-4c95-8f59-e440803c43a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxOTQwMjAsIm5iZiI6MTcxNjE5MzcyMCwicGF0aCI6Ii85NDUwMzE4Ny8zMzE5OTYxNTEtZjdkZjZjYmMtNzg5Yy00Yzk1LThmNTktZTQ0MDgwM2M0M2E0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA4Mjg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwMmFhZmE5NTBmZWI4YzEwODlhNDdhZGI3MTE0YTNkNGViYjQzNmRhMTQ4NTRlMmI4YmZlNGI0NWJjY2JmM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7psQXKy-Aicwk_8uci6mWFMCtPMpbuDWEtXRsKtgtro)
> > In the above screenshot, we failed to define these strings because we do not see a code xref to it. The `bit32` string is defined because there is code that references it. This should be changed to also include data xrefs
> 
> I noticed this behavior too, but I wasn't sure if it was planned

I cannot say it is intended -- but it is implemented as such right now. I have touched the relevant code recently. This behavior defined needs some scrutiny

**Comment by xusheng6** [comment]
The data variable is at 0x7ff6d14d36b0

**Comment by xusheng6** [comment]
I have created a simpler sample to test this case:

[test.zip](https://github.com/Vector35/binaryninja-api/files/15429850/test.zip)

![Screenshot 2024-05-24 at 3 48 13 PM](https://github.com/Vector35/binaryninja-api/assets/94503187/b79fcc19-b7db-43e3-a982-59cd4b6f9821)
