### ISSUE TITLE
Multiple Transforms broken

### ISSUE THREAD

**Issue by LiveOverflow** [Vector35/binaryninja-api#544]
It seems like multiple transforms are broken. For me this seems to be:

```
Copy As -> Unicode
Copy As -> Hash
Transform -> Encrypt
Transform -> Decrypt
Transform -> Hash
```

On slack some reported that only the Edit menu is broken, or only some methods are not working.

Verified on 1.0.17 Demo (Build 4766400), and 1.0.dev-121 (Build 8ae4768a) on MacOS 10.11.6.

Demo video: https://www.youtube.com/watch?v=jxT-VVH2ejM

**Comment by plafosse** [comment]
This seems to be fixed now, I don't know when it got fixed. Please verify and reopen if this is still broken.

**Comment by johdcmlaker2000** [comment]
still broken
