### ISSUE TITLE
HLIL doesn't seem to simplify `(x bitop x)`

### ISSUE THREAD

**Issue by whitequark** [Vector35/binaryninja-api#5448]
**Version and Platform (required):**
- Binary Ninja Version: 4.1.5318-dev Personal (80699793)

**Bug Description:**
HLIL still displays expressions of type `(x | x)` or `(x & x)` or `(x ^ x)`.

**Steps To Reproduce:**
[bug.zip](https://github.com/Vector35/binaryninja-api/files/15426351/bug.zip)

**Expected Behavior:**
`x`, `x`, `0`

**Screenshots:**
![Screenshot_20240524_021045](https://github.com/Vector35/binaryninja-api/assets/54771/ad732303-1033-4c68-8a00-dfff14f6d174)

![Screenshot_20240524_021028](https://github.com/Vector35/binaryninja-api/assets/54771/94f11911-5f75-414b-8fbb-9548b03d7fc8)

**Additional Information:**
I discovered this while implementing an architecture which only has the `OR R0, Rn` form and also is lacking in the C compiler department because `MOV` sets flags but it still generates a lot of:

```
MOV R0, R1
OR  R0, R1
```

It looks like the X86 lifter for `or` handles `or eax, eax` specially, but I think this could and should be handled at a higher level, if only because this is still a problem on X86, just after propagation.

**Comment by negasora** [comment]
Fixed in `4.1.5345-dev`

**Comment by whitequark** [comment]
Wow, that was fast :D :D

Thank you, I will bring you more bugs with reproductions then. Is a bug coupled with a custom architecture (installable as a plugin) as useful as a bug reproducible on the built-in ones? It's kind of a pain to reformat the more complex ones so that they reproduce on x86 too.

**Comment by negasora** [comment]
Yw! Having a repro with a built-in arch is preferred but if it's a blocker to reporting then we'll take what you can give!

**Comment by whitequark** [comment]
Cool, noted. I hit a *lot* of issues with REG_SPLIT, which I don't think I really can repro on x86; is that something you think can be improved relatively easily? I've been struggling to get good HLIL out of it and while it works much better than subregisters it's still rather raw.

**Comment by negasora** [comment]
Maybe, I'd need to see how it's failing. If you want to gather some basic examples and toss them in an issue I can look next week

**Comment by whitequark** [comment]
Thanks! I don't have an assembler for my architecture (it's something we're black-box-REing based on hardware behavior and some random notes on the internet) but I think I can assemble a few self-contained functions by hand.
