### ISSUE TITLE
Dataflow lost in some assignments

### ISSUE THREAD

**Issue by withzombies** [Vector35/binaryninja-api#545]
It seems some assignments clear dataflow information.

<img width="803" alt="screen shot 2016-11-11 at 2 19 49 pm" src="https://cloud.githubusercontent.com/assets/4872355/20227378/16b331a0-a81a-11e6-86e8-0f7b94622d80.png">

The `mov eax, eax` instruction prevents this jump table from being detected automatically. Converting the instruction to a NOP fixes the issue.

I've attached and example executable:
[ct64_interpreter.zip](https://github.com/Vector35/binaryninja-api/files/586597/ct64_interpreter.zip)

**Comment by plafosse** [comment]
Fixed in dev

**Comment by withzombies** [comment]
<img width="721" alt="screen shot 2017-04-26 at 6 54 48 pm" src="https://cloud.githubusercontent.com/assets/4872355/25460515/d9a27ae4-2ab1-11e7-96df-fb2ff460d58b.png">

👍
