### ISSUE TITLE
The explanation for certain settings do not show up in "open with options"

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#5452]
See the below screenshot that the explanation for `intermediate` and `full` analysis are missing. 

![Screenshot 2024-05-24 at 3 17 41 PM](https://github.com/Vector35/binaryninja-api/assets/94503187/14798dad-a456-41a8-8831-4548d76001fd)

If we view the very same setting in the settings view, all of the explanations show up as expected

![Screenshot 2024-05-24 at 3 20 23 PM](https://github.com/Vector35/binaryninja-api/assets/94503187/6e1dfea5-d45e-4a2d-a7c0-273791f0ed23)

**Comment by bpotchik** [comment]
This is an issue with wrapping, and having Qt automatically reflow the widget properly.

**Comment by bpotchik** [comment]
Actually this is a duplicate. Link to other issue: #5100
