### ISSUE TITLE
Several issues with REG_SPLIT lifting

### ISSUE THREAD

**Issue by whitequark** [Vector35/binaryninja-api#5456]
**Version and Platform (required):**
- Binary Ninja Version: 4.1.5348-dev Personal (e7cf29c0)

**Bug Description:**
1. Shifts on REG_SPLIT pairs do not seem to be aggregated. However, this bug is invisible because...
2. Return of a freshly assigned register pair seems to be considered dead during HLIL construction.

**Steps To Reproduce:**
This contains the architecture plugin and the binary: [repro.zip](https://github.com/Vector35/binaryninja-api/files/15442072/repro.zip)

Use Platform `avnera`, entry point 0.

**Expected Behavior:**
`return arg1 << 4` or something similar

**Screenshots:**
Integer argument registers are R5, R4, ... and return is in R1:R0. `LSL` is a pseudoinstruction performing a logical left shift on a register pair.

![Screenshot_20240525_065458](https://github.com/Vector35/binaryninja-api/assets/54771/e8c96e37-8aae-46fe-8ff8-684cbeb75586)
![Screenshot_20240525_065543](https://github.com/Vector35/binaryninja-api/assets/54771/edec6d70-2bac-4daf-a4a8-4fc82c6b78db)
![Screenshot_20240525_065553](https://github.com/Vector35/binaryninja-api/assets/54771/dbbf6781-eefe-4df4-8f8b-904fd3120af7)
![Screenshot_20240525_065602](https://github.com/Vector35/binaryninja-api/assets/54771/8322712d-5fc7-41fe-8c14-8a8955fa6703)

**Additional Information:**
Followup from https://github.com/Vector35/binaryninja-api/issues/5448#issuecomment-2130493481.

**Comment by emesare** [comment]
Fixed in `4.1.5661`

**Comment by whitequark** [comment]
Thanks! I'll check this out ASAP, but that might be a while.
