### ISSUE TITLE
Crash when applying Mach-O relocations

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#5469]
Documented here https://github.com/Vector35/binaryninja-api/issues/5460#issuecomment-2133182831

**Comment by negasora** [comment]
I'm able to reproduce (maybe a different crash?) by:
1. Opening the file in that issue
2. Using `Reopen current file` action

**Comment by negasora** [comment]
This isn't a crash in updating strings, and is reproducible by following the above steps

**Comment by negasora** [comment]
Fixed in `4.1.5370-dev`
