### ISSUE TITLE
Project analyze selected only makes progress when UI events fire

### ISSUE THREAD

**Issue by cyberkaida** [Vector35/binaryninja-api#5474]
**Version and Platform (required):**
- Binary Ninja Version: 4.0.4958 (ddff9339)
- OS: macOS
- OS Version: 14.5 - 23F79
- CPU Architecture: Apple Silicon - M3

**Bug Description:**
Using the project feature I am importing ~400 files. I selected them all and clicked "Analyse selected" from the right click menu. The progress through files seems to be tied directly to UI events. Files only start analysis when UI events fire. Files only start analysis if I move the mouse, click on the window or click the icon in the dock. If no UI event fires it hangs forever.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Create a new project
2. Import a directory of files
3. Select all files, right click and select "Analyse selected"
4. Stay still, do not interact with the window. See the analysis does not progress
5. Move your mouse over the window or click the window, see the analysis continues

**Expected Behavior:**
Analysis should continue in the background

**Screenshots:**

https://github.com/Vector35/binaryninja-api/assets/118712366/031da988-505d-4d63-8ec6-b99d4fe83d6f

**Additional Information:**
I posted in Slack here: https://binaryninja.slack.com/archives/C0CVALTLN/p1717038535452589

**Comment by cyberkaida** [comment]
Also happening on dev `4.1.5371-dev (2f2fb426)`.

**Comment by negasora** [comment]
I haven't been able to repro this, and it seems like a Qt+mac quirk

**Comment by CouleeApps** [comment]
Can repro on macOS but it is exceptionally tough to debug since any attempt to break in the debugger causes it to update...

**Comment by CouleeApps** [comment]
Builds >= 4.1.5536-dev will have an attempt to fix this, and it no longer repros on my box at least. Let me know if you are still seeing it with that version. Will leave this open otherwise until then.

**Comment by cyberkaida** [comment]
Confirmed this is fixed for me in `4.1.5541-dev (0ad6b08b)`! 💜
Thank you so much! This is a big help! 🙇‍♀️

**Comment by CouleeApps** [comment]
Glad to hear this is fixed. Thanks for the report :)
