### ISSUE TITLE
Expressing default calling convention via Python API

### ISSUE THREAD

**Issue by whitequark** [Vector35/binaryninja-api#5486]
**What is the feature you'd like to have?**
I would like to be able to set the default calling convention in a Python architecture plugin.

**Is your feature request related to a problem?**
It looks like without being able to set one, the transformation to HLIL gets confused and clobbers registers that shouldn't be.

**Additional Information:**
Per discussion in Slack: https://binaryninja.slack.com/archives/C0CVALTLN/p1717353782152439?thread_ts=1717172170.298609&cid=C0CVALTLN

> Mason
>
> I should also note that your R0 and R1 registers are clobbered, that is why you get a bare return
>
> Looks like the python API can't express a default calling convention, which causes a cascading set of issues in the initial analysis. So no, not really something you did wrong. The analysis is able to pickup your calling convention but I think at a stage after the translation is already done, causing the clobbering.

**Comment by negasora** [comment]
Added in `4.1.5428-dev`

**Comment by whitequark** [comment]
Thanks!

**Comment by whitequark** [comment]
@negasora How do you use this functionality? I don't see it documented...

**Comment by negasora** [comment]
To use a custom calling convention with a custom arch:
```
arch = MyArch.register()
cc = MyCallingConvention(arch, "my calling convention")
arch.set_default_calling_convention(cc)
```
A more in depth example will be done with #5532

**Comment by whitequark** [comment]
Thanks! I'm going to update my architecture and evaluate the HLIL improvement.

**Comment by whitequark** [comment]
Oh wow, the improvement is *dramatic*! The HLIL is still not perfect but it actually looks generally sensible most of the time, and I suspect I could improve this a lot by playing with the architecture---I might switch back to using subregisters as it seems possible that the issues I was getting were more related to the lack of default calling convention support than to the use of subregisters themselves.

Thanks so much!
