### ISSUE TITLE
Reopening a database that has been analyzed will still reanalyze it

### ISSUE THREAD

**Issue by 9540611855** [Vector35/binaryninja-api#5487]
**Version and Platform (required):**
- Binary Ninja Version: 4.0.5336 Personal, b4281362
- OS: macos
- OS Version: 14.3
- CPU Architecture: arm64

**Bug Description:**
When analyzing an iOS app binary, saving the project has no effect, reopening the binary file will still re-analyze it

**Steps To Reproduce:**
1.Use binary ninja to open the binary file and wait for the analysis to complete
2.save database
3.Close binary ninja
4.Open the database  just saved
5.The binary is reanalyzed

**Expected Behavior:**
A database that has been analyzed should not be analyzed again.

**Screenshots:**
save database
<img width="1379" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/39059404/fe52a145-2b65-414a-b6a3-0018bc214612">
open database
<img width="1452" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/39059404/6a5bc483-acde-4695-afd1-5abeab6bc89c">
setting
<img width="948" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/39059404/3789795c-b37c-4c9a-99c4-cc30c5e4cd64">

**Additional Information:**
Because the screen recording file is too large, I can't upload it to issues. No one responded to my slack post, so I don't know how to send the binary file, bndb, and screen recording file to you.

**Comment by xusheng6** [comment]
@9540611855 could you please provide a binary and the repro steps?

**Comment by 9540611855** [comment]
> @9540611855 could you please provide a binary and the repro steps?

Of course, but how can I give it to you?  Binary File 33.3MB，Screen Recording File 200MB

**Comment by 9540611855** [comment]
> @9540611855 could you please provide a binary and the repro steps?

https://cowtransfer.com/s/3ccfc9459abf41   

Can you please download the link above?

**Comment by xusheng6** [comment]
V35 folks should search for `possum repayment justifier willfully` to find the related files

**Comment by 9540611855** [comment]
> V35 folks should search for `possum repayment justifier willfully` to find the related files

Could you please explain it in detail? I searched the official documents but couldn't find  **`possum repayment justifier willfully`**

**Comment by 0cyn** [comment]
Resolved in **dev builds >= 4.1.5465**
