### ISSUE TITLE
Naming offsets in loads/stores/etc

### ISSUE THREAD

**Issue by withzombies** [Vector35/binaryninja-api#55]
Build: 1.0.272 beta

It seems you can assign names to offsets in loads and stores as if you were attempting to name a stack local. This apparently remaps the offset to be that name globally in the database and isn't specific to the stack frame.

Repro:
Highlight offset, hit 'n', provide name
Browse to another function with the same offset.

<img width="493" alt="screen shot 2015-11-09 at 10 13 15 pm" src="https://cloud.githubusercontent.com/assets/4872355/11053543/ee535a7a-872f-11e5-9555-29dc9f21c1e7.png">

<img width="584" alt="screen shot 2015-11-09 at 10 13 24 pm" src="https://cloud.githubusercontent.com/assets/4872355/11053545/f321bee8-872f-11e5-800f-96b1e4c0d75d.png">

<img width="523" alt="screen shot 2015-11-09 at 10 19 56 pm" src="https://cloud.githubusercontent.com/assets/4872355/11053552/05f57adc-8730-11e5-9503-af76f68d4ea2.png">

**Comment by plafosse** [comment]
I believe this is fixed.
