### ISSUE TITLE
Hang in HighLevelILSimplifier::SimplifyArrayIndexCommon

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#5512]
**Version and Platform (required):**
- Binary Ninja Version: 4.0.5336 Commercial and 4.1.5428-dev Enterprise
- OS: macOS
- OS Version: 13.6.6 and 14.5
- CPU Architecture: aarch64

**Bug Description:**
Analysis phase 2 hangs at exactly 41.96%, reproducible on two different machines and with latest stable and dev.

**Steps To Reproduce:**
1. Open this binary: [ffmpeg-x86_64.zip](https://github.com/user-attachments/files/15604273/ffmpeg-x86_64.zip)
2. Wait
3. Observe that analysis does not proceed past 41.96%

**Expected Behavior:**
Analysis finishes.

**Screenshots:**
<img width="301" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/607452/89204f0b-557f-49c9-b64f-e44a11f3cf8c">

**Comment by fuzyll** [comment]
This also failed on 4.0.4911, but succeeded on 3.5.4526, so it must be a 4.0 regression.

**Comment by fuzyll** [comment]
Bug is in commit 663e7c398d4f9c1b744c42d3f3a55e63d1e0bf0d, which modifies `HighLevelILSimplifier::SimplifyArrayIndexCommon`.

**Comment by CouleeApps** [comment]
Can confirm that reverting commit `663e7c398d4f9c1b744c42d3f3a55e63d1e0bf0d` fixes the hang... now trying to investigate _why_

**Comment by CouleeApps** [comment]
Minimized: load this file as x86_64: [thisfunc.txt](https://github.com/user-attachments/files/15745525/thisfunc.txt)
