### ISSUE TITLE
Simplify bitwise AND with constant

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#5525]
The pattern `(X & constant1) & constant2` Should be re-written as `X & (constant1 & constant2)` so it can be further simplified

Search for 1 & 1 in this binary or go to `00004ca4`, or `00007070`
[viva.zip](https://github.com/user-attachments/files/15740248/viva.zip)

**Comment by negasora** [comment]
The given examples were fixed some time before `4.2.6177-dev`

**Comment by emesare** [comment]
Simplified as apart of the disjoint AND simplification `4.2.5788-dev`.
