### ISSUE TITLE
Simplify `zx(X & N)` to `zx(X) & N`

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#5526]
as zero/sign extend and bitwise-and are transitive we can normalize this representation which will allow further simplifications such as this:

```
- Function: 1000021f0 Instruction: 100002260 MLIL->HLILS:  ['return zx.q(zx.d(var_11) & 1)']
?                                                                       -----            -
+ Function: 1000021f0 Instruction: 100002260 MLIL->HLILS:  ['return zx.q(var_11) & 1']
```

[viva.zip](https://github.com/user-attachments/files/15740339/viva.zip)

**Comment by negasora** [comment]
Fixed in `4.2.5894-dev`
