### ISSUE TITLE
Functions from Exports with Empty (Null) Names Not Created

### ISSUE THREAD

**Issue by 8u1a** [Vector35/binaryninja-api#553]
Binary Ninja will create functions / procedures for symbols in the export table of a PE file.  However, it seems that if the name of the symbol is just the null byte, the function is not created.

More context:
http://researchcenter.paloaltonetworks.com/2016/09/unit42-the-dukes-rd-finds-a-new-anti-analysis-technique/

**Comment by psifertex** [comment]
Thanks for the report -- this is fixed in dev.
