### ISSUE TITLE
Document support for getting/setting default calling convention in Python API

### ISSUE THREAD

**Issue by whitequark** [Vector35/binaryninja-api#5532]
**Is this a general concept that needs to be documented or a specific API?**
Specific API.

**What concept or API needs more documentation?**
This commit: https://github.com/Vector35/binaryninja-api/commit/75787e706c877a34a68c23c0d4f90ec5ff1e830c

**Is this documentation related to a specific API?**
Python

**Are there any known examples of people using this API/concept?**
No; it was just added

**Comment by whitequark** [comment]
Oh... so I got confused by the version I had updated (I misread the number) *and* by the online documentation and didn't realize that there is at least a mention of the `set_default_calling_convention` function in the docs, albeit empty.

I do feel that it is worth filling it out, especially given that without setting a calling convention to be a default one, it seems that HLIL results get significantly worse.

**Comment by psifertex** [comment]
Resolved in https://github.com/Vector35/binaryninja-api/pull/5705
