### ISSUE TITLE
Low discoverability and no documentation for non-closing preview window when the Option key is held 

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#5534]
Normally, if we move our mouse cursor outside of the pop-up preview window, the preview window closes. There is a feature that, if we press and hold the Options button (macOS), the preview windows does not close and we can even interact with it. This is a cool feature that worths knowing about, and unfortunately there it is hard to discover and has no documentation as well

**Comment by psifertex** [comment]
resolved with 924a052f57df9a2049f4b8148658190b52b5ad05
