### ISSUE TITLE
Document binaryninja.core_set_license in user docs.

### ISSUE THREAD

**Issue by 0cyn** [Vector35/binaryninja-api#5541]
https://api.binary.ninja/#binaryninja.core_set_license is documented in our API, but nowhere in our user documentation for Commercial/headless processing. 

This allows setting a license at runtime (which seems like a very useful thing to be able to do when batch processing w/ a portable install on other servers). I personally use this frequently. 

My initial instinct (and where google led me when searching this) was that it would be documented or mentioned on this page:  https://docs.binary.ninja/dev/batch.html

**Comment by psifertex** [comment]
see 25b82434dff420390f7e0090fe29f5fd31966787
