### ISSUE TITLE
empty space should be parented to the previous line

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#5543]
Currently empty space lines have the same address as the parent block which is often the top of the function:

<img width="578" alt="Screenshot 2024-06-10 at 17 17 37" src="https://github.com/Vector35/binaryninja-api/assets/140215/314902de-85ef-4691-9862-7fe3dd147df3">

This would be more intuitive if it showed the previous line in the linear view. Also, slightly less buggy for address based comments that start at the top of a function.

**Comment by xusheng6** [comment]
This causes the following side-effect when the target stops at a function start:

![Screenshot 2024-06-14 at 1 44 17 PM](https://github.com/Vector35/binaryninja-api/assets/94503187/ca36ee6b-d764-4fe6-b990-bd0f3273501a)

**Comment by CouleeApps** [comment]
This has been fixed in >= 4.1.5534-dev
