### ISSUE TITLE
Add support for deprecated sfence.vm instruction in RISC-V disassembly

### ISSUE THREAD

**Issue by buildandcrash** [Vector35/binaryninja-api#5559]
**Version and Platform (required):**

- Binary Ninja Version: 4.1.5474-dev (f6ba0af7)
- OS: Linux host 6.5.0-1023 (Ubuntu)
- OS Version: 22.04
- CPU Architecture: x64

**Bug Description:**
The Binary Ninja disassembler currently does not support the sfence.vm (opcode 0x10400073) instruction from the RISC-V ISA. This instruction has been deprecated in favor of the sfence.vma (opcode 0x12000073) instruction in more recent versions of the RISC-V standard. However, many old binaries still contain the sfence.vm instruction, and the lack of support in Binary Ninja makes it difficult to analyze these binaries effectively.

To address this issue, I have had to manually patch the sfence.vm instruction to sfence.vma to obtain a more accurate disassembly. Given that both instructions share the same size, this workaround is feasible but far from ideal. Proper support for sfence.vm would significantly improve the analysis of legacy RISC-V binaries in Binary Ninja.

**Additional Context:**
Supporting the sfence.vm instruction will help maintain compatibility with older RISC-V binaries and ensure that Binary Ninja can provide accurate disassembly and analysis for a broader range of RISC-V executables.

**Steps To Reproduce:**

Load a RISC-V binary containing the sfence.vm instruction (0x10400073) into Binary Ninja.
Attempt to disassemble the binary.
Observe that the sfence.vm instruction is not recognized and disassembled correctly.

**Expected Behavior:**
Binary Ninja should correctly recognize and disassemble the sfence.vm instruction as part of the RISC-V ISA, despite it being deprecated.

**Proposed Solution:**
Add a case in the RISC-V disassembler to handle the sfence.vm instruction (opcode 0x10400073) and map it to the appropriate mnemonic and operands.

Thank you for your attention to this matter. Your efforts to enhance the capabilities of Binary Ninja are greatly appreciated.

**Comment by emesare** [comment]
Added in `4.1.5478-dev`
