### ISSUE TITLE
main entry point on android

### ISSUE THREAD

**Issue by lucasduffey** [Vector35/binaryninja-api#558]
On Android, bionic uses ```__libc_init``` to find main instead of ```__libc_start_main```.

[libc/bionic/libc_init_static.cpp](https://android.googlesource.com/platform/bionic/+/android-7.0.0_r21/libc/bionic/libc_init_static.cpp#80) 

```
void __libc_init(void* raw_args,
                            void (*onexit)(void) __unused,
                            int (*slingshot)(int, char**, char**),
                            structors_array_t const * const structors) __noreturn;
```

**Comment by lucasduffey** [comment]
On further testing, binja already seems to work for some ELFs, 

I think the binary I had issue with, it was pulling the ```slingshot``` function pointer from .data, and that value didn't propagate.

**Comment by lucasduffey** [comment]
duplicate of https://github.com/Vector35/binaryninja-api/issues/527 ?

**Comment by plafosse** [comment]
No this just a lack of symbol in our platform code. You could add this yourself by just adding the __libc_init function prototype to the linux.c file. Once type propagation happens we are going to do a much more thorough job of adding prototypes.

**Comment by plafosse** [comment]
This was added to the ARM linux platform a while ago.
