### ISSUE TITLE
clickable reports

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#559]
We've discussed this before, but I don't think there's a bug tracking it -- the HTML (or MarkDown) reports (http://api.binary.ninja/python.html?highlight=report#binaryninja.BinaryView.show_html_report) should allow for clickable links that navigate to a specific address in the BV that generated them.

Ultimately it'd be nice if we could have even more functionality in the reports to other parts of the application, but I suspect that `GoToAddress` would cover most use cases. 

Biggest issue to resolve is tying back the report to the BV that created it.

**Comment by polsab** [comment]
Can this be done using custom protocols instead (e.g. "binja://bv=foo&addr=0x4085000")? This way the plugin author is responsible for creating the link and also allows for external applications to link to binja as well.

**Comment by psifertex** [comment]
The problem with that is the url handler doesn't know /which/ instance of foo you want to go to if you've got multiple opened, for example. 

Whereas `show_*_report` is specifically generated from a `bv` so we should be able to associate the two. 

I think a generic url handler would be interesting, but think we need something different to keep report links tied back into the binary which they were generated from.

**Comment by plafosse** [comment]
Added in v1.1.1435
