### ISSUE TITLE
Mark Functions As No Return

### ISSUE THREAD

**Issue by bagre** [Vector35/binaryninja-api#560]
You should be able to mark functions as no return from the UI. Several functions do not return and there is no way to annotate them without changing the types file which is problematic when reversing code that decides not to return in several spots.

**Comment by plafosse** [comment]
To add to this typing a function `__noreturn` seems to have no effect.

**Comment by amtal** [comment]
Neither does calling `binaryninja.core.BNSetFunctionCanReturn(binaryninja.core.BNGetFunctionType(current_function.handle), False)`

**Comment by D0ntPanic** [comment]
Fixed in dev build 864. Adding `__noreturn` from the UI works, and the `can_return` property of the Python API is now writable.
