### ISSUE TITLE
Binary Ninja (demo) does not detect PE32 file

### ISSUE THREAD

**Issue by fluxchief** [Vector35/binaryninja-api#561]
It seems that binary ninja (current demo version) is unable to detect a (pretty old) 32 bit PE as such.
[machines.exe.gz](https://github.com/Vector35/binaryninja-api/files/608863/machines.exe.gz)

**Comment by plafosse** [comment]
Fixed in dev: Bit of an odd binary.  The VirtualSegment size is 0 for all segments, so we have to use the "size on disk" instead.  Thanks for the report.

**Comment by fluxchief** [comment]
Glad to hear this, thank you
