### ISSUE TITLE
Update Pending does not get cleared after updating a plugin

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#5614]
**Version and Platform (required):**
- Binary Ninja Version: 4.1.5513-dev
- OS: macOS 14.5
- CPU Architecture: aarch64

**Bug Description:**
I used the new right-click "Update Plugin" feature implemented in #2330. After doing so, the entry doesn't change state.

**Steps To Reproduce:**
1. Open the Plugin Manager
2. Right-click on an out-of-date plugin
3. Click "Update Plugin"
4. Observe in the log that the plugin has been updated successfully
5. Observe that the Plugin Manager still says "Update Pending" for the plugin (this repros on 4.0 stable)
6. Observe that you can still right-click and choose "Update Plugin" (this is new)
7. Close the Plugin Manager and re-open it
8. Observe that you are still in this state (this repros on 4.0 stable)

**Expected Behavior:**
After the plugin has updated, I would expect this state to be cleared and for it to no longer offer me the ability to update the plugin.

It's possible that we're in this state because, although it's finished installing, the new version of the plugin hasn't been enabled? In that case, I would either expect it to not be able to get into that state at all (disable, uninstall, install new, enable?) *or* I would expect it to be in an "Update Complete" (or, better yet, "Restart Required") state so I understand what I need to do as a user to be using the updated plugin.

Update: It _does_ give me a "Restart" message at the bottom briefly, on both 4.0 stable and the 4.1 build I filed this against, but since it doesn't stick around it's easy to miss if you're doing other things.

**Screenshots/Video Recording:**
![image](https://github.com/Vector35/binaryninja-api/assets/607452/642fa480-13c2-46c3-92f0-b8f17cc73c56)

**Additional Information:**
The original text here was incorrect and it looks like some of this was also present in the 4.0.5336 stable build.

**Comment by ElykDeer** [comment]
Fixed in 4.2.6355-dev, with #6080 to cover the notification bit.
