### ISSUE TITLE
Linker error while building rust plugin on windows.

### ISSUE THREAD

**Issue by Apologism** [Vector35/binaryninja-api#5616]
**Version and Platform (required):**
- Binary Ninja Version: 3.0.5336-Stable
- OS: Windows
- OS Version: 23H2
- CPU Architecture: x64

**Bug Description:**
Linker error while building a rust plugin (non-standalone) while on windows.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. download LLVM-17.0.6 (anything higher will result in thousands of errors upon compilation)
2. download rust version 1.77.0 (as per readme instructions)
3. create a rust dynamic library as per read me instructions.
4. add some boilerplate in lib.rs:
```rust
use binaryninja::{binaryview::BinaryView, command};

#[no_mangle]
#[allow(non_snake_case)]
pub extern "C" fn CorePluginInit() -> bool {
    true
}
```

**Expected Behavior:**
it *should* compile correctly, as I've followed all the instructions in the rust api readme exactly as prescribed.
https://github.com/Vector35/binaryninja-api/tree/dev/rust

**Addtional Info:**
Here is the tail of the linker error:
```
ld: C:\Users\Mike\Documents\Home\Code\Rust\dis\target\debug\deps\libbinaryninja-fd36a10fef7bf150.rlib(binaryninja-fd36a10fef7bf150.binaryninja.aaee6b10380c25b4-cgu.05.rcgu.o): in function `<binaryninja::architecture::CoreArchitecture as binaryninja::architecture::Architecture>::intrinsic_class':
          C:\Users\Mike\.cargo\git\checkouts\binaryninja-api-3c86176688a74ccb\51c0684\rust/src/architecture.rs:1469: undefined reference to `BNGetArchitectureIntrinsicClass'
          ld: C:\Users\Mike\Documents\Home\Code\Rust\dis\target\debug\deps\libbinaryninja-fd36a10fef7bf150.rlib(binaryninja-fd36a10fef7bf150.binaryninja.aaee6b10380c25b4-cgu.06.rcgu.o): in function `binaryninja::metadata::Metadata::get_json_string':
          C:\Users\Mike\.cargo\git\checkouts\binaryninja-api-3c86176688a74ccb\51c0684\rust/src/metadata.rs:172: undefined reference to `BNMetadataGetJsonString'```

**Comment by emesare** [comment]
What I assume happened is you tried to use the latest dev branch which is much much newer than your install.

Your core version `3.0.5336-Stable` does not meet the minimum ABI version for the latest dev, if you want to link against `3.0.5336-Stable` you must use the commit that is compatible, you can find the exact commit that is used to build your version in the installation folder as `api_REVISION.txt`.

If this does not solve your issue please re-open.
