### ISSUE TITLE
Crash on register selection with stack view open

### ISSUE THREAD

**Issue by KyleMiles** [Vector35/binaryninja-api#5620]
**Version and Platform:**
- Binary Ninja Version: 4.1.5524-dev
- OS: OSX
- CPU Architecture: M2

**Bug Description:**
When selecting RAX in certain conditions, Binary Ninja will crash. Not sure if it's a variables view bug or linear.

**Steps To Reproduce:**
1. Go to 100001acc
2. Switch to disassembly
3. Open the stack view
5. Scroll down to the bottom
6. Select RAX on line 0x100001ac8
7. Crash

**Screenshots/Video Recording:**

https://github.com/Vector35/binaryninja-api/assets/7171118/6921bb98-fe39-4f08-a52e-715c53c009c4

**Binary:**
[cat](https://github.com/user-attachments/files/15878139/cat.txt)

**Comment by CouleeApps** [comment]
Can confirm. Looks like that address has no lines in the stack view due to https://github.com/Vector35/binaryninja-api/issues/5602 which then crashes because of an off-by-one in the reset logic (`if (scrollOffset > lines.size()) { scrollOffset = lines.size() - 1; }`)

**Comment by CouleeApps** [comment]
Will be fixed in v4.1.5525-dev
