### ISSUE TITLE
Assembly not working on arch/artix

### ISSUE THREAD

**Issue by k4lizen** [Vector35/binaryninja-api#5632]
**Version and Platform (required):**
- Binary Ninja Version: Binary Ninja 4.0.5336 free
- OS: Artix linux
- CPU Architecture: x64
 
**Bug Description:**
When trying to assemble/edit code in the dissasembly view, I get an "execve() failed" popup.

**Steps To Reproduce:**
1. Open any elf file in binja (I created a fresh one with just a printf to test)
2. Look at linear disassembly
( 2.5 (Un)locking the lockpad at the bottom right doesn't seem to have any effect)
3. Press `E` on some line of code
4. Type anything (e.g. `nop`) and press enter
5. See the popup

**Expected Behavior:**
I expect it to edit the file. Notably, I can edit bytes directly with the hex view.

**Screenshots/Video Recording:**
![image](https://github.com/Vector35/binaryninja-api/assets/124312252/8b242f04-2113-4509-a401-b0159f573fdb)

**Binary:**
I tested with multiple and none work but heres an example.
```c
#include <stdio.h>

int main(){
    printf("hello!\n");
    int x = 10 + 17;
    printf("Added: %d", 2*x);
    return 0;
}
```
`gcc main.c -o main`

**Additional Information:**
It seems someone had this issue seven years ago but it was closed with no sight of a solution due to no official support for arch: https://github.com/Vector35/binaryninja-api/issues/686 (having yasm installed doesn't seem to have any effect for me)
I read this but I'm not sure its relevant: https://github.com/Vector35/binaryninja-api/issues/155
I tried doing `binaryninja -d -e main` but no output seems to be generated when the error is shown, is this a bug?
Also when I run BN through the command line I get
```
QApplication: invalid style override 'gtk' passed, ignoring it.
        Available styles: Windows, Fusion
```
but it 'works' anyway so that seems unrelated.

If any hint as to how to solve this could be provided I would be very greatful.

**Comment by psifertex** [comment]
Can you make sure `yasm is executable on the command-line? That is, it's not corrupted, and it has +x permissions? 

```
$ ls -l binaryninja/pluigins/yasm
```

**Comment by psifertex** [comment]
Given that it works for us internally I'm going to close this one out, this seems likely to be an artifact of how the bundle was extracted or something else specific to your particular machine.

**Comment by k4lizen** [comment]
Oke so by looking at the strace it seems it couldn't find the yasm executable because it was looking for it in `./plugins/yasm`. This was a problem for me because I have links to the binaryninja executable, and those links are in my PATH, so it thinks its in the wrong folder when I run `binaryninja`. I got this fixed on my end by using a `exec <path-to-binja> $@` shellscript. It could also be fixed on your end by resolving the [realpath(3)](https://man7.org/linux/man-pages/man3/realpath.3.html) I think.
