### ISSUE TITLE
Don't suggest to enable permissive linear sweep if it's already been enabled

### ISSUE THREAD

**Issue by seekbytes** [Vector35/binaryninja-api#5649]
While opening a binary, Binary Ninja suggests some improvements for the analysis that may include:
- adding a new section with ReadOnlyCodeSectionSemantics
- Enable the linearSweep.permissive setting

This issue is to track the feature of: not suggesting to enable of permissive linear sweep if it's already been used for the file. It should be an easy change but it's only to keep binary ninja messages truthful about the analysis.

**Comment by ElykDeer** [comment]
Fixed in 4.2.6341-dev.
