### ISSUE TITLE
Support parsing of .gfids section for PE

### ISSUE THREAD

**Issue by seekbytes** [Vector35/binaryninja-api#5651]
Gfids (Control Flow Guard metadata) contains some tables that might be helpful for recovering functions. Supporting them could be helpful for adding more context to the analysis.

Some links:
* http://llvm-cs.pcc.me.uk/tools/lld/COFF/Writer.cpp#1572
* https://learn.microsoft.com/en-us/windows/win32/secbp/pe-metadata

**Comment by xusheng6** [comment]
Related to #5287

**Comment by negasora** [comment]
It looks like we already do this https://github.com/Vector35/binaryninja-api/blob/afb41a37f9f6fa9e3c2d8df35fa9c9ae215299ee/view/pe/peview.cpp#L2392

If this doesn't cover everything, if you could provide a binary that'd be helpful
