### ISSUE TITLE
Add a `size_t count` argument to some `BNCustomArchitecture.free*` fields

### ISSUE THREAD

**Issue by mkrasnitski** [Vector35/binaryninja-api#5655]
Specifically, the [`freeFlagConditionsForSemanticFlagGroup`](https://github.com/Vector35/binaryninja-api/blob/dev/binaryninjacore.h#L1834) and [`freeRegisterList`](https://github.com/Vector35/binaryninja-api/blob/dev/binaryninjacore.h#L1842) fields should take an additional `size_t count` argument so that custom architectures implemented in other languages can correctly free the pointers passed to them through these functions without resorting to hackery (as discussed in #5654).

cc-ing @CouleeApps @KyleMiles

**Comment by emesare** [comment]
After `4.2` stable this will be added with https://github.com/Vector35/binaryninja-api/commit/4f9ae2fb35fac84fbdbb1915d0d9930c2d92b6be and https://github.com/Vector35/binaryninja-api/commit/67759e673a99db04ca8e24e78bb46ddf9e7d7665

**Comment by emesare** [comment]
Added with https://github.com/Vector35/binaryninja-api/commit/b34ddd03f71c8637a80a264a3ea757b8295d482b and https://github.com/Vector35/binaryninja-api/commit/121c16592476754800b00a3b51595f4799944d04.
