### ISSUE TITLE
Open with Options dialog parses integer as decimal instead of hexadecimal by default

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#5682]
When I type "1000" into the image base input, it is treated as 0x3e8, instead of 0x1000. I think we should parse the value as hex by default

![Screenshot 2024-07-03 at 1 30 01 PM](https://github.com/Vector35/binaryninja-api/assets/94503187/fdc7009f-138b-4c5d-9f92-7c176a4674fc)

**Comment by plafosse** [comment]
Ideally here we should have instead of a QLineEdit we have our own BinjaNumericEdit control. This would automatically use `ParseExpression` on the backend and would also support automatic preview of the value to the right of the control.

**Comment by xusheng6** [comment]
Well this is actually not easy to do -- the settings view have many other integer inputs that is better parsed as decimal

**Comment by bpotchik** [comment]
Prepending `0x` gives hex and without it you get a decimal. Regarding ParseExpression, it's not useful in this context as symbol information is not available. Since this is a common control used everywhere, I recommend not changing it's behavior.
