### ISSUE TITLE
Symbols for inlined functions

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#569]
We need special handling for symbol to inlined functions. 

![screen shot 2016-12-02 at 1 57 37 pm](https://cloud.githubusercontent.com/assets/10556585/20846370/604da970-b897-11e6-8436-4914fedf90c6.png)
![screen shot 2016-12-02 at 2 02 01 pm](https://cloud.githubusercontent.com/assets/10556585/20846499/f1033110-b897-11e6-89a8-4b53d74f05dc.png)

The problem is that we if we ever see a function symbol we just assume that we assume its the start of a function and do no special handling of it.  We should detect when a symbol is pointing into a basic block of another function and emit a tail call.

**Comment by krx** [comment]
This is causing some issues with mcsema, mainly with tail calls to an external function. The thunk will just get inlined and never gets lifted as a separate function, since there's no symbol/address being picked up

**Comment by plafosse** [comment]
Fortunately I think this will be fixed by one of my current tasks, which is adding symbol binding types, including local, global and weak.

**Comment by fuzyll** [comment]
We haven't seen this issue in some time and we don't have a binary on hand to reproduce it. If anyone comes up with a binary that exhibits this behavior, please re-open this issue and let us know. It's hard for us to fix this without having a test case we can use to reproduce the issue.
