### ISSUE TITLE
Parse the structure referenced by LC_CODE_SIGNATURE

### ISSUE THREAD

**Issue by seekbytes** [Vector35/binaryninja-api#5691]
Mach-o can contain a signature that is usually referenced by [LC_CODE_SIGNATURE](https://github.com/qyang-nj/llios/blob/main/macho_parser/docs/LC_CODE_SIGNATURE.md). This issue to track support of the structure inside binary ninja.

**Comment by xusheng6** [comment]
Duplicate of https://github.com/Vector35/binaryninja-api/issues/5690
