### ISSUE TITLE
parse_types_from_source_file doesn't fully support the C standard.

### ISSUE THREAD

**Issue by lucasduffey** [Vector35/binaryninja-api#571]
```
>>> Architecture.parse_types_from_source_file(bv.arch, "/home/user/research/android/wpa_supplicant_8/wpa_supplicant/wps_supplicant.h")
(None, '/home/user/research/android/wpa_supplicant_8/wpa_supplicant/wps_supplicant.h:92: error: syntax error\n')
```

```/home/user/research/android/wpa_supplicant_8/wpa_supplicant/wps_supplicant.h```
```
# "syntax error" on the following line 92
static inline int wpas_wps_init(struct wpa_supplicant *wpa_s) 
{
        return 0;
}
```

**Comment by lucasduffey** [comment]
I've also seen it syntax error on:
```
#if 0
```

**Comment by lucasduffey** [comment]
I've also seen parse_types_from_source_file syntax error on:
```
/*
```

**Comment by rmspeers** [comment]
I'm updating this ticket with a few more similar issues with these functions which are making it so I can't load headers, at least without doing a lot of pre-processing on them.

One thing is that any #define'd items from a pre-processor seem to not be recognized (can't debug further as is in core.BNParseTypesFromSourceFile). This I can work around by writing a script that find/replaces these definitions (ideally just by calling a preprocessor).

It also fails on typedef enums. This is what the header I'm trying to load has:
```
typedef enum
{
    OptionA = 0,
    OptionB,
} sec_info_type_t;
```
I tried a ton of options till I was able to get this to work:
```
enum sec_info_type_t
{
    OptionA = 0,
    OptionB,
};
```

**Comment by psifertex** [comment]
Yeah, I've renamed this bug to focus specifically on the pre-processor support since that's a known missing feature that unfortunately we don't have any plans for now to support. 

The concern is that if we just silently ignore them we'll obviously get wrong or unexpected behavior and we don't have any plans at this time to add support with the existing SCC based solution. 

We may at some point use llvm instead which would obviously have much better preprocessor support but likely quite far off.

**Comment by natronkeltner** [comment]
Function prototypes seem to be handled incorrectly as well.

Pointers and other typedefs work:
```
typedef void (*test)(int a, int b);
```
But this causes a syntax error.
```
typedef void test(int a, int b);
```

If you create it through the UI or though `parse_type_string()` + `define_user_type()` it works fine:
```
>>> a = bv.parse_type_string("void test(int a, int b);")
>>> a
(<type: void (int32_t a, int32_t b)>, 'test')
>>> bv.define_user_type(a[1], a[0])
>>> bv.get_type_by_name('test')
<type: void (int32_t a, int32_t b)>
```
in the Types UI:
```
typedef void  test(int32_t a, int32_t b);
```

**Comment by irwincong** [comment]
> Function prototypes seem to be handled incorrectly as well.

Not in all cases, see [this example source](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAKxAEZTUAHAvVAOwGdK0BbRvADaYA8mwDCCAIZtgmEAHIADPICUpDqgCuxZHPkB6AFQBqACKZkAycUzHJxgGaa2yFu2MEpBD5IDWmDjs2Yzw2AkxZYmNGa0keTHCo6XRjAFJFAEFjbJsCbU47R2dXVmDGVFDE4wB3QgQPAE9GW3QtACMhCEMVCFbNDswVADp0rOyAFQQ8QNqBATtXYwE8fyC7YmJJBpC2LAAPUOAilzc2IeNDfVG%2BgeMungaAfScT0ohKlR6boRVUgGYAEKjUZGMwWKw2QocBLGVAOY4ldiBTySbwEPy2dgtdpCNKZbLrYCaeJhIIpXL5QrfTDnS7XHG2B6PZBtZ7FU6PWi9BnRWI8X6A%2Bn9XFMlls17sR4AJm5wtsMU2/P%2BQMyoPMlmstnsWAckk0Am8L0RwWqU2Q9VaAWMbFQnkOtKumWpxlFrM8zl8stuCriApVGVGlRdklCEAAbhV0Co0gB2f3ZUFiSRzF1PI2nDyoYy5Yh4TBhrUIjPlSqYMijAnZUIeKaBZCSaGkGuYti2U14c3GDgAR00msCWiioUYmgIDorxmd9zT7NKjxLYTLXwZ0f%2BplT4uNEEUfonE8Tyfmnls6dK0Qqi6i7c7HAQWgEKR7fchx4nBOHo%2BMYeTmkx8IArOO%2BLZgklJMqekoLokED/rumSpDGpjAqqJjmA4oSFhBwQot4FLEAU9hYeepZRG0DaYCkb7uNIOz7EBGRToY4Gzuw7ykqE%2ByfF6PzAnGE4cLUBCdmxnEIfGBL1tCxiKCAIF5PhG5ilhnLKm%2BxiSbYtCyXhwSupuHJSqpwHZDqeoGtpoEKXp7psL4RljAhSHwYhyEZGqmDoa2hT1nMZHIL4RZnjhcn5MiCC2E%2Bmqwg4b7HtExCoGGeBYCkPrxIk9HOnpylcs6aW/M54k6byioXCVcT2Y5IKoR5GHeYefkBURwU6YEUgCPCcLNniYzxYlyUUeV6VlplPLZSxbDStx8p8gVAZ8cBxVpcY%2BjGIZgrOU5bk1Z5hY%2BQIjWBe4LWWQUcWMAlSUpT1BJpQkZY1HUWjeNI2w8BgeDofWpwcKNcqKW6CAetNQ1zWJE5LXylUufBmSqKQAgKP%2B8ikGwCi0CjqAKGIqRSkCeNdoOuhpFKfwY6QBAKMonykL4ID/ooCMKAALCjaNKJjCgo1wjOUxzahwLASC8PwQhkBQEAi4IZYoFYMiPAQxAeqQ6EGmWXAQG0VMo7wJIEKIAgNNrpD4DYJQFlwHPkIuiP8wwzClJbAC0ezqcYTtOxwBDoGuyAAJx%2B/DtvI6jxtY/IuNk49njGHsAAcABsTsJ8z6ly0cECKx6Kgo3z1NqHTDNM/IrOh1b4fcyAvPazTttSmzYdcxTNdqAWxAcKUIDM0AA%3D%3D%3D)

```python
bv.platform.parse_types_from_source("double (*my_function(int index))(double);")
```

will fail with a `SyntaxError`.  Same deal when trying to parse a prototype that takes a function pointer as an argument.

**Comment by plafosse** [comment]
Many of the issues here have been fixed, and some appear to be invalid. We're not attempting to be completely compliant with a specific standard as we require our own extensions. If there is a particular syntax that you believe should be supported. Please create a separate issue.
