### ISSUE TITLE
Invalid submodule added in commit c76953f

### ISSUE THREAD

**Issue by VisualEhrmanntraut** [Vector35/binaryninja-api#5710]
**Version and Platform (required):**
N/A

**Bug Description:**
Invalid submodule added in commit c76953f (suite/binaries) without URL specified, making the repo unable to be cloned.

```
    Updating git repository `https://github.com/Vector35/binaryninja-api.git`
    Updating git submodule `https://github.com/capstone-engine/capstone.git`
    Updating git submodule `https://github.com/intelxed/mbuild.git`
    Updating git submodule `https://github.com/intelxed/xed.git`
    Updating git submodule `https://github.com/Vector35/yasm.git`
    Updating git submodule `https://github.com/Vector35/asmx86.git`
    Updating git submodule `https://github.com/Vector35/pdb-rs.git`
error: failed to get `binaryninja` as a dependency of package `amd-catalyst-fw-extractor v0.1.0 (/Users/visual/Developer/ProjectSources/ReverseEngineering/AMDCatalystFWExtractor)`

Caused by:
  failed to load source for dependency `binaryninja`

Caused by:
  Unable to update https://github.com/Vector35/binaryninja-api.git?branch=dev

Caused by:
  failed to update submodule `suite/binaries`

Caused by:
  no URL configured for submodule 'suite/binaries'; class=Submodule (17)
```

**Steps To Reproduce:**
Add dev branch as a crate to a Rust cargo project, run cargo update on one that already has it or try to clone this repository's submodules.

**Expected Behavior:**
The submodule not be present or have its URL specified.

**Screenshots/Video Recording:**
N/A

**Binary:**
N/A

**Additional Information:**
The submodule may have been committed by accident.

**Comment by emesare** [comment]
🙈Thanks for catching that so quickly, I was on an old commit and didn't check to see what was already in staging.

**Comment by VisualEhrmanntraut** [comment]
No problem. I actually caught this by luck, this mistake happened at the same time I was updating the dependencies on one of my plug-ins. By the way, you should probably avoid force pushes as that is a git history rewrite essentially. Probably could remove this using git rm or something like that.
