### ISSUE TITLE
Double-click to "Undo to Here"

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#5743]
**What is the feature you'd like to have?**
In the History widget, I want to double-click to "Undo to Here" instead of using right-click, which currently does not work.

**Is your feature request related to a problem?**
I am lazy and would prefer to make two clicks with my pointer finger instead of having to swap fingers.

**Are any alternative solutions acceptable?**
Not really, but it also might be cool if hitting "Enter" would also work? Could enable me to use Up + Enter (or, if #5742 exists, Down + Enter!) in order to "step" through undo history, which might be neat?

**Comment by negasora** [comment]
Added in `4.2.5964-dev`
