### ISSUE TITLE
Compilation Failure

### ISSUE THREAD

**Issue by Decencies** [Vector35/binaryninja-api#5745]
**Version and Platform (required):**
- Binary Ninja Version: v4.0.491-stable#b7c8e9bf (API) 
- OS: Windows
- OS Version: 21H2
- CPU Architecture: x64

**The problem**
When attempting to compile a plugin (from Rust) with MSVC 14.38.33130, the following errors are thrown:

```
error LNK2019: unresolved external symbol BNFreeRelocationList referenced in function _ZN95_$LT$binaryninja..relocation..Relocation$u20$as$u20$binaryninja..rc..CoreOwnedArrayProvider$GT$4free17hf8de5a29268efdb7E
error LNK2019: unresolved external symbol BNGetAnalysisTypeContainer referenced in function _ZN61_$LT$binaryninja..types..Type$u20$as$u20$core..fmt..Debug$GT$3fmt17h638ee282ee98c8dfE
error LNK2019: unresolved external symbol BNFreeTypeContainer referenced in function _ZN61_$LT$binaryninja..types..Type$u20$as$u20$core..fmt..Debug$GT$3fmt17h638ee282ee98c8dfE
error LNK2019: unresolved external symbol BNFreeTypeAndNameList referenced in function _ZN100_$LT$binaryninja..types..QualifiedNameAndType$u20$as$u20$binaryninja..rc..CoreOwnedArrayProvider$GT$4free17h773c5ec21df86477E
```

**Comment by fuzyll** [comment]
Are you using the `master` branch of the API with your 4.0 stable build? If you are, please also try the most recent 4.0 stable build, which is 4.0.5336.

These are the two most likely culprits. If it's still broken, let me know and we can troubleshoot further.
