### ISSUE TITLE
crash binja by putting folder as filename argument for parse_types_from_source_file

### ISSUE THREAD

**Issue by lucasduffey** [Vector35/binaryninja-api#575]
**OS:** Ubuntu 16.04 LTS

# reproduction
```
Architecture.parse_types_from_source_file(bv.arch, "/tmp")
```

**Comment by psifertex** [comment]
I can't reproduce this -- might be from the other fix just put onto dev. Can you confirm?

**Comment by lucasduffey** [comment]
not binja issue

**Comment by psifertex** [comment]
Fixed in dev.

**Comment by psifertex** [comment]
I lied four hours ago. ;-) My first fix broke windows so it never passed the CI. Current version building now should be deployed soon and includes the fix.
