### ISSUE TITLE
Can't edit project until permissions are pulled

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#5752]
**Version and Platform (required):**
- Binary Ninja Version: 4.1.5746
- OS: Ubuntu
- OS Version: 24.04
- CPU Architecture: x64

**Bug Description:**
When using a project on the enterprise server, the option to edit its properties is disabled until opening the Manage Permissions dialog. Weirdly, this only applies to the Actions dropdown and not the right click menu.

**Steps To Reproduce:**
1. Create project on server
2. Restart binja
3. Open remote dialog
4. Select project
5. Click Actions dropdown
6. Observe cannot edit the project even though you just created it
7. Click Manage Permissions
8. Close permissions window
9. Observe now you can edit the project

**Expected Behavior:**
I expected to be able to edit my own project, without having to take additional steps first.

**Additional Information:**
Probably need to never disable that button and pop a warning if they actually don't have permissions for it

**Comment by negasora** [comment]
Fixed in `4.3.6474-dev`
