### ISSUE TITLE
License dialog has Enter hotkey as "log out" instead of "start"

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#5753]
**Version and Platform (required):**
- Binary Ninja Version: 4.1.5746
- OS: Ubuntu
- OS Version: 24.04
- CPU Architecture: x64

**Bug Description:**
When I tried to use enter to press the start button on the license dialog, it instead activated the Log Out button. This is very surprising considering the Start button is highlighted and the Log Out button is not highlighted. Also this doesn't happen on macOS

**Steps To Reproduce:**
1. Log into enterprise server with Remember Me enabled
2. Quit
3. Open binja again
4. Press enter to Start
5. Psych you just logged out
6. Get logged out, nerd

**Expected Behavior:**
I expected pressing Enter to activate the highlighted button??

**Screenshots/Video Recording:**
<img width="245" alt="image" src="https://github.com/user-attachments/assets/a18f7042-4403-4219-9a21-58ef4cf1c751">

**Comment by fuzyll** [comment]
Should be fixed in builds >= 4.2.6105-dev.
