### ISSUE TITLE
Make function signature clickable even when scrolled inside a function

### ISSUE THREAD

**Issue by 0xFDFDFDFD** [Vector35/binaryninja-api#5760]
**Version and Platform (required):**
- Binary Ninja Version: 4.1.5747-dev Personal, 7558ffe9
- OS: manjaro
- CPU Architecture: x86_64

**Bug Description:**
When I am not at the top of a function i cannot click (or edit) the signature of it.

This is especially annoying inside the single function view, as the signature is displayed twice and one of them is not clickable

**Steps To Reproduce:**
Scroll inside a big function and try to click the function signature

**Expected Behavior:**
I can click the function signature even when I am not at the top of the function.

**Screenshots:**
1. Function signature clickable:
![function_signature_clickable](https://github.com/user-attachments/assets/0b735553-4aa5-4e16-9629-9dce9d123629)

2. Function signature not clickable scrolled inside a function:
![function_signature_not_clickable](https://github.com/user-attachments/assets/fe9103b6-3741-4eac-8fe7-9ff87ab697e0)

3. Single function view:
![single_function_view](https://github.com/user-attachments/assets/c9e19ae2-9579-4137-b0a7-461356e2418d)

**Comment by negasora** [comment]
This is tracked as part of #3708, please give that issue a thumbs up so we know to prioritize it
