### ISSUE TITLE
Removing "Universal" from ui.files.detection.openWithOptions causes Workflow-ObjC to not be loaded automatically on Universal binaries.

### ISSUE THREAD

**Issue by 0cyn** [Vector35/binaryninja-api#5762]
**Version and Platform (required):**
- Binary Ninja Version: 4.1.5747
- OS: macOS 14 arm64

**Bug Description:**
Removing "Universal" from `ui.files.detection.openWithOptions` (Auto open with options) causes the Objective-C workflow setting to not be automatically enabled. 

This does not reproduce on single-arch binaries and requires a specific settings configuration to trigger.

**Steps To Reproduce:**
1. Load Binaryninja with stock settings 
2. Set `ui.files.detection.openWithOptions` to `["Mapped"]`
3. (Easier bug demo, not required step) Set `files.universal.architecturePreference` to `["arm64e","arm64","x86_64"]`
4. Open `/System/Applications/Chess.app/Contents/MacOS/Chess`
5. If step 3 was completed, observe lack of workflow's inlining behavior. If it was not, observe lack of function call rewrites anywhere in binary. 

**Expected Behavior:**
The load setting should be properly applied regardless of how the binary was opened. 

**Additional Information:**
Unsure where the cause of this is.

**Comment by bpotchik** [comment]
Currently the load settings are only queried and used when opening with options. This is the intended behavior.

There is an existing ticket which tracks always generating load options for open operations here: #5280

However, you no longer need to used a named workflow now. You can grab/modify/register the default meta workflow.
