### ISSUE TITLE
Simplify `a ^ b != 0` to `a != b` when result is extended

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#5766]
![image](https://github.com/user-attachments/assets/77091f7e-61f0-454e-ad86-edf71476aa3e)

[main.exe.zip](https://github.com/user-attachments/files/16284781/main.exe.zip)

**Comment by xusheng6** [comment]
Related to https://github.com/Vector35/binaryninja-api/issues/5545

**Comment by negasora** [comment]
We already convert `(a ^ b) != 0` -> `a != b`, but the zero-extend surrounding the xor breaks it

**Comment by negasora** [comment]
Fixed in `4.2.5894-dev`
