### ISSUE TITLE
Structure/Type Cross References

### ISSUE THREAD

**Issue by withzombies** [Vector35/binaryninja-api#577]
In IDA, structure members can be cross referenced to their use across the entire database. In HexRays, structure members can be cross referenced to their use in a single function, but it includes the access type (read or write).

Binary Ninja should allow structure members to be cross referenced across the entire database as well as including their access type. Read and write accesses would be nice, but also a version of an execute access would be nice. Possibly as a specialization of the read access (a deref+call?).

**Comment by PistonMiner** [comment]
Along this line, enumerator references would also be helpful.

**Comment by jeffli678** [comment]
The initial support for type xref and var xref are pushed to dev 2.2.2648. And I will likely continue to work on improvements for it.
