### ISSUE TITLE
add support for .gnu_debugdata

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#5779]
Fedora (and apparently android based on a sample file we received) may use https://fedoraproject.org/wiki/Features/MiniDebugInfo to include additional debug information.

See also:
https://sourceware.org/gdb/current/onlinedocs/gdb.html/MiniDebugInfo.html
https://archive.fosdem.org/2020/schedule/event/debugging_mini/attachments/slides/4059/export/events/attachments/debugging_mini/slides/4059/fosdem2020_minidebuginfo_kkleine.pdf

**Comment by psifertex** [comment]
Until this is added as a first-class feature, install the snippet plugin from the plugin manager and add the following code to it:

```python
# work-around until https://github.com/Vector35/binaryninja-api/issues/5779 is resolved
import lzma

# Get the raw view
if bv.view_type == "Raw":
    mv = bv
else:
    mv = bv.parent_view

if ".gnu_debugdata" in mv.sections:
    section = mv.sections[".gnu_debugdata"]
    buf = lzma.decompress(mv.read(section.start, section.length))
    symview = load(buf)
    with bv.bulk_modify_symbols():
        for s in symview.get_symbols():
            print(s)
            bv.define_user_symbol(s)
else:
    log_error("No debugdata found")
```  

Then you can trigger it with an action or bind it to a hotkey

**Comment by negasora** [comment]
Added in `4.2.6082-dev`
