### ISSUE TITLE
Copy offsets from structure type

### ISSUE THREAD

**Issue by bb33bb** [Vector35/binaryninja-api#5788]
**What is the feature you'd like to have?**
when copying the structure defination, we can not copy the offset of elements

**Is your feature request related to a problem?**
No

**Are any alternative solutions acceptable?**
?

**Additional Information:**
here is the picture as follow
![111](https://github.com/user-attachments/assets/8b2b65ea-2698-4822-821f-cbd3e5cbb249)
ing

**Comment by psifertex** [comment]
If you click a single-token you can copy it just fine. What are you trying to copy? The entire column?

<img width="387" alt="Screenshot 2024-07-24 at 10 51 42" src="https://github.com/user-attachments/assets/7210e180-d42c-498f-ab0e-d54a9b57f0fc">
<img width="213" alt="Screenshot 2024-07-24 at 10 51 50" src="https://github.com/user-attachments/assets/9250f171-4ac6-44a8-a1e6-bdcaf8bf1bcb">

**Comment by bb33bb** [comment]
yes ， i try to copy all the text , and use all the text to ask ai . Need the offset to let ai gen usefull code.

**Comment by psifertex** [comment]
I don't think we'll be implementing this as a UI feature -- we intentionally strip those offsets so they are not valid C as displayed.

That said, it's easy to use the API to solve this problem. Install the "snippets" plugin from the pugin manager, and paste this into it and you can copy the structures with offsets:

```python
import binaryninjaui
import PySide6

typeName = interaction.get_text_line_input("Type", "Type to copy:").decode('utf8')

typeVar = bv.get_type_by_name(typeName)

if not typeVar:
    # check libraries
    for lib in bv.type_libraries:
        typeVar = lib.get_named_type(typeName)
        if typeVar:
            break

if typeVar:
    lines = ""
    for line in typeVar.get_lines(bv, typeName):
        lines += f"{hex(line.offset)} {str(line)}\n"
    clip = PySide6.QtGui.QGuiApplication.clipboard()
    clip.setText(lines)

else:
    log_info(f"Could not find a type with the name {typeName}")
```
