### ISSUE TITLE
Remote Debugging Support

### ISSUE THREAD

**Issue by xelman** [Vector35/binaryninja-api#579]
Please consider adding support for remote debugging.  It's one of the more powerful features of your more expensive competitor but could be invaluable, especially to those who want to use this for kernel-level stuff in a virtual environment.

**Comment by lucasduffey** [comment]
https://github.com/snare/binjatron

**Comment by psifertex** [comment]
It's worth pointing out that we don't do well with kernel disassembly right now. There's an existing bug for it, but wanted to make you aware.
