### ISSUE TITLE
Custom HLIL Language Representations

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#5798]
**What is the feature you'd like to have?**
Provide an extensible API for plugins to render HLIL with their choice of structure and format. Also, move Pseudo-C to a plugin based on this API.

**Is your feature request related to a problem?**
Desire for Pseudo-Rust, Pseudo-ObjC, etc

**Are any alternative solutions acceptable?**
No real alternatives that are well-integrated with the rest of the UI

**Additional Information:**
* No actual analysis is involved with this, it is simply a custom printing of the already created HLIL.
* Maybe other ILs later, not relevant to this issue for now

**Comment by D0ntPanic** [comment]
Added in build 4.2.6249
