### ISSUE TITLE
More colors for arrows and lines in graph view

### ISSUE THREAD

**Issue by bkerley** [Vector35/binaryninja-api#580]
![httpd binary ninja 2016-12-12 16-22-40](https://cloud.githubusercontent.com/assets/4354/21117376/529f5196-c087-11e6-944a-772b8836dbe0.png)

I'm not saying you have to go all graph theory to pick colors that don't match adjacent lines, but more than three would be nice.

In the past I've taken the sha512 of some object identifier ({source, destination} tuple maybe?), grab the top three bytes, and arithmetic them into a background-appropriate color range.

**Comment by plafosse** [comment]
The Flowgraph API now supports custom colors and line stroke. We are not planning on implementing this in the base products.
