### ISSUE TITLE
Comments within nested code branches split across multiple lines in linear / pseudo C view.

### ISSUE THREAD

**Issue by 0xPerseus** [Vector35/binaryninja-api#5804]
**Version and Platform (required):**
- Binary Ninja Version: 4.1.5747 Personal (7558ffe9)
- OS: Windows 11
- OS [Version 10.0.22621.3958]
- CPU x64

**Bug Description:**
In the Linear and Pseudo C views, comments within long nested code branches are incorrectly split across multiple lines. This issue causes comments to appear fragmented, as seen in the attached image posted below. The comments are displayed properly in the Graph view (right column), but not in the main Linear / Pseudo C view. This issue does not seem to be present earlier on in the function and will progressively worsen the more nested the logic is.

For example, the comment below should appear as a single contiguous comment, but instead, it is broken into multiple lines.

```
// Decoded String: "HTTP
// Debugger Windows
// Service (32
// bit).exe"
```

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1) Open a code file and create a comment within a long nested code branch
2) View the code within Linear / Pseudo C mode.
3) Observe how the comments are split across multiple lines.

**Expected Behavior:**
The comment should appear as a single line, like this:

```
// Decoded String: "HTTP Debugger Windows Service (32 bit).exe"
```

**Screenshots/Video Recording:**
Screenshot of the issue provided below. 

![binaryninja_EPiPzYfWKY](https://github.com/user-attachments/assets/48a435f9-d114-43b2-b218-45e7a8377813)

**Additional Information:**
These comments are auto-generated using a custom Binary Ninja plugin I've written to aid in the analysis of this piece of malware that leverages the "self.bv.set_comment_at" function for a provided address. Although I'm not confident that this is related to the bug, I figured it was worth mentioning just in case.

**Comment by xusheng6** [comment]
We have a `ui.view.common.commentWidth` that decides when to wrap the comment. It defaults to 80, do you have a custom value for it? 

Also, if you add the comment from within the UI, does it look the same?

I tried to reproduce this, but the comment is wrapped at the proper length. Would it be possible to share with us the binary to allow us to reproduce it?

**Comment by plafosse** [comment]
I can not reproduce this issue. This could be due to a misconfiguration of the comment width setting as Xusheng suggests
