### ISSUE TITLE
Extern function with no type library info seemingly supresses function parameter analysis

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#5809]
In the following screenshot, the binary has a call to an external function `TEEC_InvokeCommand`, which we do not have the type information since we do not have the relevant type library. However, it seems that we should still be able to recover the type info from the callsite, we can clearly see the arguments in x0-x3:

![Screenshot 2024-07-31 at 5 17 00 PM](https://github.com/user-attachments/assets/5756f455-062f-4e11-a2f2-aab9af371a3d)

But the HLIL shows a call to `TEEC_InvokeCommand` without any parameters:

![Screenshot 2024-07-31 at 5 17 34 PM](https://github.com/user-attachments/assets/7ca25894-aef6-48d0-8b6b-73fb5f359400)

Initially I think we are just not running the function parameter analysis because we blindly trusted the info from the extern function type (which is empty), but I checked a PE file with type libraries disabled and it does not seem to be the case -- we still managed to recover the parameter info from the call-site. Not sure if there is anything special about this file:

[libckteec.so.0.1.0.zip](https://github.com/user-attachments/files/16439198/libckteec.so.0.1.0.zip)

**Comment by xusheng6** [comment]
FYI this is where the `TEEC_InvokeCommand` function is implemented:

[libteec.so.1.0.0.zip](https://github.com/user-attachments/files/16439332/libteec.so.1.0.0.zip)

**Comment by river-li** [comment]
Fixed in 4.2.5819
