### ISSUE TITLE
Can't move the "Comment" window around

### ISSUE THREAD

**Issue by peperunas** [Vector35/binaryninja-api#581]
I've noticed I cannot move the "Comment" windows when it's open. It's forced to be centered (horizontally and vertically) compared to the main window.

`binja 1.0-dev-147` is running on Arch Linux.

**Comment by psifertex** [comment]
Part of #803

**Comment by plafosse** [comment]
This was fixed a while go, sorry we dont' have the build number

**Comment by jeffli678** [comment]
I do not think this is fully resolved. On Ubuntu, the comment window can move, but the background BinaryNinja window also moves accordingly, which effectively cancels the move of the comment window. Let me know if a GIF is helpful.
