### ISSUE TITLE
Binary Ninja not found

### ISSUE THREAD

**Issue by sugar-please** [Vector35/binaryninja-api#5811]
**Version and Platform (required):**
- Binary Ninja Version: v4.1.5747-stable
- OS: Ubuntu 22.04
- CPU Architecture: x64

**Bug Description:**
when running scripts/install_api.py:
Found install folder of ~/binaryninja-api/python
Binary Ninja not found: ~/binaryninja-api/python
Please provide the path to Binary Ninja's install directory: 
 [~/binaryninja-api/python] :

**Comment by emesare** [comment]
Run the script from your Binary Ninja installation.

i.e. If you have installed Binary Ninja at `~/binaryninja`:
```sh
cd ~/binaryninja/scripts/
./install_api.py
```

**Comment by psifertex** [comment]
Another reason it's important to run the version from your install path is because there may be changes on the API repo that are at a different version from your local install.

Let us know if this resolves your issue.

**Comment by fuzyll** [comment]
Yes, API access is not available on the Free version. This is listed in the limitations at the bottom of [the download page](https://binary.ninja/free/).
