### ISSUE TITLE
Binary Ninja crashes during undo/redo operation after Sidekick structure recovery

### ISSUE THREAD

**Issue by kristopax** [Vector35/binaryninja-api#5812]
**Version and Platform (required):**
- Binary Ninja Version: 4.1.5747 stable
- OS: macOS
- OS Version:14.4
- CPU Architecture: M1

**Bug Description:**
Binary Ninja crashes during an undo/redo operation after Sidekick structure recovery on the libstfaceunlockppl.so binary on the function 0x46cba0.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Ensure sidekick is installed
2. Open the binary
3. Navigate to function 0x46cba0
4. Select Plugins->Sidekick->Recover Structures
5. Undo action
6. Redo action

**Expected Behavior:**
Binary Ninja should not crash.

**Binary:**
Request the binary from me

**Additional Information:**
Sidekick uses the Binary Ninja Python API to create components and types, so this is not an issue with Sidekick.

**Comment by plafosse** [comment]
Search slack for `libstfaceunlockppl.so` to find the file

**Comment by negasora** [comment]
~I can't repro this with `4.2.5948-dev`~ nvm it took a couple tries

**Comment by negasora** [comment]
Fixed in `4.2.5950-dev`
