### ISSUE TITLE
PythonScriptingProvider.magic_variables fails from plugin

### ISSUE THREAD

**Issue by jtang613** [Vector35/binaryninja-api#5823]
**Version and Platform (required):**
- Binary Ninja Version: 4.2.5821-dev (58f7657d)
- OS: Fedora
- OS Version: 40
- CPU Architecture: x64

**Bug Description:**
The PythonScriptingProvider.magic_variables is not being initialized when accessed from a Python plugin. It does work from a Python script (File -> Run Script) and from the Python console, but not from a plugin.

**Steps To Reproduce:**
From inside a script versus a plugin. It succeeds from a standalone script, but fails from inside a plugin (most of the values in the magic_variables dict are `None`).
```python
for inst in PythonScriptingInstance._registered_instances:
    print(f"inst: {inst}")
    break
print(f"line: {inst.interpreter.locals['current_il_function'][inst.interpreter.locals['current_il_index']]}")
print(f"line: {PythonScriptingProvider.magic_variables['current_il_instruction'].get_value(inst)}")
```

**Expected Behavior:**
I'm expecting it to return the IL text from the currently selected line in Linear view.

**Comment by jtang613** [comment]
User error. The following fixes my issue.
```python
for inst in PythonScriptingInstance._registered_instances:
    print(f"inst: {inst}")
    break
inst.interpreter.update_locals()
inst.interpreter.update_magic_variables()
print(f"line: {PythonScriptingProvider.magic_variables['current_il_instruction'].get_value(inst)}")
```

**Comment by psifertex** [comment]
Sorry for the delay in not responding via slack. We really should include an example in the API docs to make this more obvious.

**Comment by jtang613** [comment]
No worries - I was able to fumble my way through it - builds character ;)

**Comment by psifertex** [comment]
I'm glad you have a good attitude about it! That said, I'd prefer if users saved the character building for the RE itself and our API was the easy part. 😛
