### ISSUE TITLE
x86 rep instructions not generating loops in Low Level IL

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#584]
Given a small snippet of x86 assembly like the following:
```
mov ecx, 3
mov edi, 0xbadf00d
mov esi, 0xcafebabe
repne cmpsb
```

The loop seems to be erroneously optimized out, or just skipped or something in the Low Level IL:
![image](https://cloud.githubusercontent.com/assets/5834130/21407158/3652a05c-c79d-11e6-8ce2-2d686f40f6bf.png)

It's still present in the Lifted IL though:
![image](https://cloud.githubusercontent.com/assets/5834130/21407186/4f2cdb38-c79d-11e6-8db7-ab6b6af40f22.png)

And if a second `repne cmpsb` is added, the loop will appear in the Low Level IL...but only the first one. However, I also noticed that other instructions, such as `mov eax, esi` will not cause the loop to be generated.

**Comment by plafosse** [comment]
All the user mode rep prefixed instructions are now lifted in dev channel as of build 842.
