### ISSUE TITLE
Functions should be reanalyzed after using the assemble dialog

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/binaryninja-api#5841]
When using the assemble dialog, it seems that Binary Ninja does not always re-analyze the function, which produces weird results if assembling across function boundaries, etc.

I think at a minimum, the function that contains the address where the assemble dialog started assembling should be re-analyzed to prevent this.

Can't share a screenshot or binary of when I observed this, but can try to reproduce with another binary if clarification is needed.

**Binary Ninja 4.1 Stable, macOS**

**Comment by xusheng6** [comment]
I cannot reproduce this, I checked the code and I believe that we send a BinaryDataWritten notification for the entire range that gets written to, and all functions containing which overlap with it should get updated. Could you please try to find a different sample for it that you can share with us?

Also, can you observe that after the patching, is it:

1. The analysis does not get updated, or
2. The analysis gets updated, but the function with changes does not change

**Comment by jonpalmisc** [comment]
I forget how I was causing this to happen now, so I'm gonna close this until it happens again.
