### ISSUE TITLE
segfault in libtriage.so when opening x86_16 binary

### ISSUE THREAD

**Issue by aleksav013** [Vector35/binaryninja-api#5842]
**Version and Platform (required):**
4.2.5828-dev is crashing on both Linux and Windows.
4.1.5747 (stable) works fine on both Linux and Windows.

**Bug Description:**
segfault
![image](https://github.com/user-attachments/assets/f859f056-d2b8-4a40-aab4-5ebac3e33a45)
![image](https://github.com/user-attachments/assets/ae01629a-0ee0-4472-a41f-ac2c777b7c55)
Function `BNGetPlatformDefaultCallingConvention` is returning `nullptr` for arch "x86_16" after being called in `libtriage.so`.

**Steps To Reproduce:**
After opening x86_16 binary or manually opening ANY binary with "Platform" set to "x86_16" and opening "Triage Summary" the program crashes.
To be able to manually set "Platform" use "Open with Options" when opening file.

**Binary:**
Any binary as long as "Platform" is set to "x86_16" and "Triage summary" is opened.

**Comment by emesare** [comment]
Fixed with `4.2.5860-dev`, thank you for reporting!
