### ISSUE TITLE
The type for various variadic functions (_printf) are inaccurate in macOS type libraries

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#5844]
>>> bv.type_libraries
[<typelib '/usr/lib/libSystem.B.dylib.mac-aarch64.1292.100.5':aarch64>]
>>> lib = bv.type_libraries[0]
>>> bv.import_library_object('_printf', lib)
<type: immutable:FunctionTypeClass 'int32_t(char const*)'>

It should be `int32_t _printf(char const*, ...)`. This also affects functions like `_scanf`, `vsprintf`, `snprintf`, and potentially other variadic functions as well.

This does not affect Linux type libraries -- they are correct

**Comment by HarDToBelieve** [comment]
Confirmed, not only for MacOS type libraries, but also in all ARM type libraries

**Comment by 0xricksanchez** [comment]
Seems Rel: #5828?

**Comment by psifertex** [comment]
Don't think it's related. Lack of type libraries is totally independent from heuristic analysis being off.

**Comment by plafosse** [comment]
Fixed in 4.2.6443
