### ISSUE TITLE
support for raw byte string search

### ISSUE THREAD

**Issue by mgmoshes** [Vector35/binaryninja-api#585]
Currently in the "Find" menu there are only the "Raw String" and "Escaped String" options. However there's no way to search for a raw byte string like '\xB5\x04'.

**Comment by lucasduffey** [comment]
possible duplicate of https://github.com/Vector35/binaryninja-api/issues/41

**Comment by psifertex** [comment]
Escaped string should allow for searching of binary bytes exactly as you describe. Did it not work?

**Comment by plafosse** [comment]
This feature is supported just search for "\xB5\x04" with Escaped String selected.
