### ISSUE TITLE
Warn loudly when settings.json isn't parseable

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#5850]
Ran into an issue where an error in my settings.json that was hard to troubleshoot because I didn't realize it was failing. Should either log warn or log error.

**Comment by fuzyll** [comment]
I have a test branch with an ugly hack that implements this. But, after some discussion, we have decided we would prefer to add back previously-removed functionality that catches this class of problem and defers logging until the UI is available.

This is a bigger lift than my quick hack, so we'll need someone with more time/understanding to make this change instead.

**Comment by bpotchik** [comment]
Fixed in `4.2.6056-dev`.
