### ISSUE TITLE
LowLevelILFunction.get_reg_value_at

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#586]
It would be nice to have an API call like `Function.get_reg_value_at` and other functions like it that , but that work on a `LowLevelILFunction` handle instead. This presumably would allow for dataflow analysis on user-defined IL functions that aren't actually tied to functions in the binary.

**Comment by joshwatson** [comment]
This was added a while back as `LowLevelILInstruction.get_reg_value`, `LowLevelILInstruction.get_reg_value_after`, and `LowLevelILInstruction.possible_values`

**Comment by psifertex** [comment]
Thanks for finding and closing. We're going to do a big pass soon to clean up a bunch as well. Appreciate the help.

**Comment by joshwatson** [comment]
I like to look through my own issues sometimes and clean them up 😀
