### ISSUE TITLE
"Select None" Not Working

### ISSUE THREAD

**Issue by utkonos** [Vector35/binaryninja-api#5866]
**Version and Platform (required):**
- Binary Ninja Version: 4.1.5902
- OS: macOS
- OS Version: 14.6.1 (23G93)
- CPU Architecture: x64

**Bug Description:**
The "Select None" entry in the "Edit" menu does not clear the selected instruction when in Linear View. Also, if you have a particular token selected in the Graph View and then use "Select None" the selection of a particular instruction is cleared, but the selection of a particular token remains. Look at the screenshots below to see that the behavior in Linear and the behavior in Graph are both working incorrectly in opposite ways.

**Steps To Reproduce:**
1. Set Linear View
2. Select any instruction line
3. In the Edit menu click "Select None"
4. Notice instruction still selected
5. Change to Graph View
6. Select one token (eax for example)
7. In the Edit menu click "Select None"
8. Notice cleared instruction but remaining token is selected.

**Expected Behavior:**
All selected entities in the view will be unselected

**Screenshots/Video Recording:**
Before:
<img width="358" alt="image" src="https://github.com/user-attachments/assets/e1e06679-ac3a-4158-9085-a40810bf5e75">

After Select None:
<img width="362" alt="image" src="https://github.com/user-attachments/assets/5cfe1eaf-c588-4b92-a18c-45d77a915d04">

Before:
<img width="455" alt="image" src="https://github.com/user-attachments/assets/3c420bc5-a0e4-4138-8759-4acf900126ac">

After Select None:
<img width="442" alt="image" src="https://github.com/user-attachments/assets/1301940f-42c4-4382-8870-14e17e20829d">

**Comment by xusheng6** [comment]
Btw, I am just curious -- what actually prompts you to use the ""Select None" action? Normally I would think one can do it by just clicking at a location where there is nothing to achieve the same goal

**Comment by utkonos** [comment]
Clean screenshots of your beautiful UI. Both of those views, when using Select None, leave at least one UI element still selected. And, yes, clicking somewhere else is one workaround, but isn't a workaround for small functions where there isn't anywhere off-screen that one can click.

**Comment by fuzyll** [comment]
A better workaround might be to use Select None from the command palette (Cmd-P), which appears to work correctly in linear view.

**Comment by utkonos** [comment]
@fuzyll 
Command pallete does the same thing. At least on macos. are you testing on macos?

https://github.com/user-attachments/assets/12f474b4-b141-4395-8db7-1e9a7571a8b3

**Comment by fuzyll** [comment]
Oh, I understand now. No, you are correct, it also doesn't work. It removes all of the selections *except* for the current line in linear view. I misread what you were saying earlier.

**Comment by utkonos** [comment]
Yes, and interestingly, Graph and Linear have opposite behaviors. Select None leaves the instruction selected or leaves the token selected depending on which view you're looking at.

**Comment by fuzyll** [comment]
Forgot to update this, but I _believe_ Graph View should be fixed as of builds >= 4.2.6025-dev. Linear View was not quite as easy and I haven't finished fixing that yet.

**Comment by fuzyll** [comment]
Should be fixed in builds >= 4.2.6105-dev. I had made _two_ changes to linear view earlier, which cancelled each other out. Making just one of them was more successful. 🙂
