### ISSUE TITLE
LowLevelILInstruction confused when created with disagreeing expr_index and instr_index

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#587]
Given the following code:
```python
idx = current_function.get_low_level_il_at(bv.arch, here)
il = LowLevelILInstruction(current_function.low_level_il, 0, 7)
print il
print il.operation_name,il.operands
```
The output is something like:
```
<il: r15 = 0>
LLIL_CONST [17408L]
```
because the `expr_index` refers to the `LowLevelILExpr` at index 0, which in this case is an `LLIL_CONST`, but the `__repr__` of the instruction acts as though it is `current_function.low_level_il[7]`.

**Comment by plafosse** [comment]
You're passing in the wrong values, there's no way for us to detect this.
