### ISSUE TITLE
Instruction `rev` is improperly lifted

### ISSUE THREAD

**Issue by kangwoosukeq** [Vector35/binaryninja-api#5870]
**Version and Platform (required):**
- Binary Ninja Version: 4.1.5902 Personal, f2165c5d
- OS: windows
- OS Version: 11
- CPU Architecture: x86_64

**Bug Description:**
The `rev` instruction for arm architecture reverses the byte order like `0x04030201` -> `0x01020304` (https://developer.arm.com/documentation/dui0489/h/arm-and-thumb-instructions/rev--rev16--revsh--and-rbit)

However, according to the screenshots below, it collects all bytes using bitwise or (`|`).
Isn't it incorrect lifting?

**Steps To Reproduce:**
Open the `liblib.so` file, and go to the address `0x1734`.

**Expected Behavior:**

**Screenshots:**
![스크린샷 2024-08-21 212227](https://github.com/user-attachments/assets/2e00330a-474a-4c20-9013-53447096e3ed)
![스크린샷 2024-08-21 212247](https://github.com/user-attachments/assets/6d41ef9f-b774-414e-a29d-95e616be0baa)

**Additional Information:**
[liblib.zip](https://github.com/user-attachments/files/16691383/liblib.zip)

**Comment by emesare** [comment]
The lift looks correct?
https://github.com/Vector35/binaryninja-api/blob/46b26cf9f4a8eee8e94f86532220e61120c2a54d/arch/armv7/il.cpp#L1803C3-L1816C10

_The output is for some reason missing the left shifts._

OOPS looks like the thumb version is wrong not the arm version.

**Comment by emesare** [comment]
Fixed in `4.2.5944-dev`
