### ISSUE TITLE
Key-binding for "Clear Log" not working

### ISSUE THREAD

**Issue by mwales** [Vector35/binaryninja-api#5874]
Binary Ninja Version: Enterprise Client 4.1.5747
OS: ubuntu with mate
OS Version: 22.04
CPU Architecture: x64

Bug Description:
Want to clear log with a key binding. Have tried mapping it to Ctrl+Shift+K and Ctrl+Shift-D (incase OS was grabbing one of them for some reason) and neither worked. Can right click on the log, and clear that way. Right click menu shows the key binding too.

Steps To Reproduce:

    Set "Clear Log" key binding
    Have a log full of errors like mine
    Try to clear the log with key binding
    Nothing happens

Expected Behavior:
Log to be cleared, like I right clicked on it and said to clear

Screenshots/Video Recording:
If applicable, please add screenshots/video recording here to help explain your problem.

**Comment by mwales** [comment]
Accidentally submitted / wont let me edit

    Binary Ninja Version: Enterprise Client 4.1.5747
    OS: ubuntu with mate
    OS Version: 22.04
    CPU Architecture: x64

Bug Description:
Want to clear log with a key binding.  Have tried mapping it to Ctrl+Shift+K and Ctrl+Shift-D (incase OS was grabbing one of them for some reason) and neither worked.  Can right click on the log, and clear that way.  Right click menu shows the key binding too.

Steps To Reproduce:
1. Set "Clear Log" key binding
2. Have a log full of errors like mine
3. Try to clear the log with key binding
4. Nothing happens

Expected Behavior:
Log to be cleared, like I right clicked on it and said to clear

Screenshots/Video Recording:
If applicable, please add screenshots/video recording here to help explain your problem.

**Comment by negasora** [comment]
Fixed in `4.2.5964-dev`
