### ISSUE TITLE
The find dialog can be too wide

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#5878]
![Screenshot 2024-08-24 at 2 37 15 PM](https://github.com/user-attachments/assets/71dfb2f6-0e17-453f-acca-e09ac9742b40)

**Comment by plafosse** [comment]
This is due to having a large string in your history

**Comment by fuzyll** [comment]
Should be fixed in builds >= 4.2.6105-dev.

There is now a size limit on the _initial_ dialog size. You should still be able to resize the dialog to be wider if you need to, though.
