### ISSUE TITLE
"Security check failure or stack buffer overrun" when viewing armv7 IL

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#588]
See attached binary. Navigate to `sub_8590` and switch to IL view; Binary Ninja 1.0.dev-654 Commercial crashes on Windows 10.

[crashing-elf.zip](https://github.com/Vector35/binaryninja-api/files/674398/crashing-elf.zip)

**Comment by joshwatson** [comment]
Also crashes in headless with the following (tested in Bash on Windows):
```python
from binaryninja import *
bv = BinaryViewType['ELF'].open('crosscompile-arm')
bv.update_analysis_and_wait()
crashing_function = bv.get_function_at(bv.platform, 0x8590)
il = crashing_function.low_level_il
i = il[24]
```

**Comment by plafosse** [comment]
Fixed in dev
