### ISSUE TITLE
Many Nt definitions missing from ntdll type library

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#5885]
It currently only exports 71 functions this is obviously not close to being complete

```
>>> nt = bv.platform.get_type_libraries_by_name("ntdll.dll")[0]
>>> nt
<typelib 'ntdll.dll':x86_64>
>>> len(nt.named_objects)
71
```

The root cause of this is that the datasource we're using [win32metadata](https://github.com/microsoft/win32metadata) doesn't have it but instead its in: [wdkmetadata](https://github.com/microsoft/wdkmetadata) So we need to pull it from there which is a bit of a hassle.

**Comment by plafosse** [comment]
Significant improvements to this typelib are in 4.2.5977

**Comment by cxiao** [comment]
Really appreciate this change, lots of good stuff in there, makes a big difference for Windows malware RE 🙏🏼 

```
>>> nt = bv.platform.get_type_libraries_by_name("ntdll.dll")[0]
>>> len(nt.named_objects)
1195
```

📈

**Comment by psifertex** [comment]
Let us know if you run into specific issues still!
