### ISSUE TITLE
[0:0 Default error] Trying to add a local variable at positive storage offset 4. Please report this issue.

### ISSUE THREAD

**Issue by kovar-ursa** [Vector35/binaryninja-api#5886]
**Version and Platform (required):**
- Binary Ninja Version: 4.1.5902 (f2165c5d)
- OS: MacOS Sonoma
- OS Version: 14.1 (23B2073)
- CPU Architecture: M3

**Bug Description:**
Used a demo function:
`def analyze_binary(file_path, max_function_size):
    if not os.path.isfile(file_path):
        print(f"File {file_path} does not exist.")
        return

    # Load the binary
    bv = load(file_path)

    print(f"Number of functions in {file_path} is {len(bv.functions)}.")`
    
Ran it on this file:
`libbar-x86_64:` ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=6633b038ea73d1a6ff9a7d0c0edf733d95fea2cc, with debug_info, not stripped`
**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:

**Expected Behavior:**
Not throw an error.

**Screenshots/Video Recording:**
N/A

**Binary:**
Attached.

**Additional Information:**
Please add any other context about the problem here.
[libbar-x86_64.zip](https://github.com/user-attachments/files/16773531/libbar-x86_64.zip)

**Comment by emesare** [comment]
Closing in favor of https://github.com/Vector35/binaryninja-api/issues/5882
