### ISSUE TITLE
Console hangs if file closed during update_analysis_and_wait

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#590]
If one runs `bv.update_analysis_and_wait()` on a binary, then closes that file before analysis completes, the console deadlocks and can't be used again, from any open file, until the program is relaunched.

**Comment by plafosse** [comment]
I just tried this and it deadlocked, yeah definitely an issue here.

**Comment by bpotchik** [comment]
Fixed in Build 819.
