### ISSUE TITLE
Simplify trivial arithmetic: var ^ const ^ const

### ISSUE THREAD

**Issue by KarlVogel** [Vector35/binaryninja-api#5905]
BN 4.2.6033 fails to optimize:

![image](https://github.com/user-attachments/assets/40af6571-6b33-4468-a03a-4dff310c440c)

https://dogbolt.org/?id=852fcdbb-a582-484d-8af6-3ce306b6b144

```asm
        BITS 64

        xor r9w, 0x1234
        xor r9w, 0x1234
        xor rax,rax
        mov ax, r9w
        ret
```

**Comment by emesare** [comment]
Added in `4.2.6036-dev`, thanks!
