### ISSUE TITLE
Unresolved indirect control flow

### ISSUE THREAD

**Issue by joelreymont** [Vector35/binaryninja-api#5921]
**Version and Platform (required):**
- Binary Ninja Version: 4.2.6042-dev, e875db7b
- OS: macos
- OS Version: 14.6
- CPU Architecture: arm64

Internal binary name `deploy article cage`

```
1400c3ecc                  return sub_1400c4240(arg1, *arg4[1], *arg4[2]) __tailcall
❓1400c3ee1              case 4
1400c3ee1                  jump(*(*arg1 + 0x170))
❓1400c3ef8              case 5
1400c3ef8                  jump(*(*arg1 + 0x178))
```

![Screenshot 2024-09-11 at 4 48 15 PM](https://github.com/user-attachments/assets/f3cf618e-1c67-4f6d-a6f1-3138d1fe1e64)

**Comment by emesare** [comment]
There is no analysis we can do to resolve the jump address. What do you expect us to do here?

**Comment by joelreymont** [comment]
Do what IDA does?

```
      case 4:
        (*(void (__fastcall **)(QStyleHints *))(*(_QWORD *)a1 + 0x170LL))(a1);
        break;
      case 5:
        (*(void (__fastcall **)(QStyleHints *))(*(_QWORD *)a1 + 0x178LL))(a1);
```

If they can do it then you can do it too!

**Comment by emesare** [comment]
Ah I see now, closing in favor of https://github.com/Vector35/binaryninja-api/issues/1060, thank you for the report.
