### ISSUE TITLE
Adding a MemoryRegion to an open file alters save behavior

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#5923]
**Version and Platform (required):**
- Binary Ninja Version: 4.2.6050-dev
- OS: macOS and Linux
- CPU Architecture: aarch64 and x86-64

**Bug Description:**
Adding a MemoryRegion to an open file that has not yet been saved as a database alters save behavior to save file contents instead of a new database.

**Steps To Reproduce:**
1. Open a binary (not `.bndb`)
2. Hit `Ctrl+s` to save
3. Notice it prompts you to save a `.bndb`
4. Close the dialog without saving
5. `bv.memory_map.add_memory_region("aaaaab", 0x40000000, b'\x00')`
6. Hit `Ctrl+s` to save
7. Notice it's asking you to save the file contents instead of a `.bndb`
8. Close the dialog without saving
9. Hit `Ctrl+s` to save
10. Notice that you don't get any dialog at all..?

**Expected Behavior:**
I expected to be prompted to save a database.

**Additional Information:**
This might be intended behavior, but I found it surprising. You can work around it by using "Save As" instead, which asks if you want to save the file contents or the database.

**Comment by negasora** [comment]
The underlying bug is also causing analysis info (xrefs and data vars) to not be created when adding a memory region, since we are only marking the file contents as dirty instead of analysis info

**Comment by negasora** [comment]
Fixed in `4.2.6056-dev`
