### ISSUE TITLE
Not possible to copy search results

### ISSUE THREAD

**Issue by mrexodia** [Vector35/binaryninja-api#5924]
**Version and Platform (required):**
- Binary Ninja Version: 4.2.6052-dev, d4f5daa6
- OS: macos
- OS Version: 14.6
- CPU Architecture: arm64

**Bug Description:**

It is not possible to copy the search results.

**Steps To Reproduce:**

Search for a pattern, Cmd+A to select all results, Cmd+C to copy.

**Expected Behavior:**

It should copy the table.

**Screenshots:**

**Additional Information:**

**Comment by psifertex** [comment]
Good suggestion! Added in builds >= 6054
