### ISSUE TITLE
MPIDR_EL1 not identified by AArch64 architecture plugin

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/binaryninja-api#5930]
The AArch64 architecture does not seem to know about [`MPIDR_EL1`](https://arm.jonpalmisc.com/2023_09_sysreg/AArch64-mpidr_el1).

<img width="779" alt="image" src="https://github.com/user-attachments/assets/17287c90-a848-498b-90cc-ba4364a51922">

Same code in IDA:

<img width="631" alt="image" src="https://github.com/user-attachments/assets/0e538440-2c6e-4767-9aec-1e0ac0b9fcca">

**Comment by negasora** [comment]
Will be fixed in `4.2.6071-dev`
