### ISSUE TITLE
resize the subwindow in ninja

### ISSUE THREAD

**Issue by bb33bb** [Vector35/binaryninja-api#5931]
**Version and Platform (required):**
- Binary Ninja Version:4.2.6067-dev Personal (9b225520)
- OS: manjaro
- OS Version:
- > cat /proc/version
Linux version 6.9.12-3-MANJARO (builduser@fv-az772-99) (gcc (GCC) 14.2.1 20240805, GNU ld (GNU Binutils) 2.43.0) #1 SMP PREEMPT_DYNAMIC Wed Aug  7 16:19:28 UTC 2024
- CPU Architecture: x64

**Bug Description:**
can not resize the width of subwindow

**Steps To Reproduce:**
lets look at the following pictures
![image](https://github.com/user-attachments/assets/7a18f12c-2528-4f67-9fbb-f49a971e4897)

**Comment by bpotchik** [comment]
Unable to repro this locally, even with a long name of over 200 chars. Tried renaming the function in the UI, and via console.

Is this for every binary you open, or just this one? Anything need to be done to get it in a strange state?

**Comment by bb33bb** [comment]
as cases before, i will close it first and give you the details of repro.
