### ISSUE TITLE
Setting a return registger for a function does not set the register as clobbered

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#5937]
Sample binary as: https://github.com/Vector35/binaryninja-api/issues/5129

Function 0x40018b is hand-written, and it returns a buffer in the `r12` register. When we set the return register as r12 in the edit function dialog, it does not get marked as clobbered register automatically. As a result, the analysis of the calling function does not pick it up as the return register.

However, if we also manually mark r12 as the return register, it works:

![Screenshot 2024-09-16 at 3 41 37 PM](https://github.com/user-attachments/assets/8578d69e-5e0d-4ab6-90b7-4cce9ddde3ae)

The issue here is we should be able to mark it automatically

**Comment by xusheng6** [comment]
[ch54.bin.zip](https://github.com/user-attachments/files/17019005/ch54.bin.zip)

**Comment by emesare** [comment]
The behavior of setting user function return registers has been updated to insure clobbering. In the future setting auto function return registers might also want this behavior but it has been left unmodified.

this is fixed in dev `> 4.2.6080`.
