### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Cussrro** [Vector35/binaryninja-api#5946]
Can the GetInstructionInfo, GetInstructionText, and GetInstructionLowLevelIL functions in Architecture be enhanced? During the decompilation process, I need to access the data in the segment so that I can correctly parse and display the opcode.

**Comment by plafosse** [comment]
This is unfortunately one of our oldest issues: https://github.com/Vector35/binaryninja-api/issues/551 This may require a significant rewrite of a lot of APIs.
