### ISSUE TITLE
macOS: Opening application bundle should open the underlying application

### ISSUE THREAD

**Issue by bambu** [Vector35/binaryninja-api#595]
When trying to open a macOS application from the UI one has to use `cmd-shift-g` to get past `/Applications/MyApp.app`. 

Currently clicking open on `MyApp.app` just results with a popup `Error opening requested file`.  It would be helpful if opening the `.app` would open `/Applications/MyApp.app/Contents/MacOS/MyApp`. I believe that IDA currently does this. 

The info on the file to open can be discovered by reading the `CFBundleExecutable` key in the bundle's `Info.plist`. This is really just a nicety more than anything

**Comment by plafosse** [comment]
This can be done now with the Triage plugin, which should be shipped with the product pretty soon.

**Comment by plafosse** [comment]
Closing in favor of #1231
