### ISSUE TITLE
Mapped view fails to load from remote project

### ISSUE THREAD

**Issue by Martyx00** [Vector35/binaryninja-api#5961]
**Version and Platform (required):**
- Binary Ninja Version: Ultimate 4.2.6063-dev with Enterprise Server 
- OS: Ubuntu Linux
- OS Version: 24.04
- CPU Architecture: x64

**Bug Description:**
Raw binary files or BNDB files that were created on top of raw binary files do not add any memory segments when open and thus do not disassemble.

**Steps To Reproduce:**
Put a raw binary file to the Enterprise Server and try to open it with options, set the correct loading address and an architecture. The binary file does not open (tried with TriCore and Thumb2 binaries). 
If the locally processed BNDB file is uploaded to the Enterprise Server, opening it does not load any segments as well. This makes Enterprise Server unusable for raw binary files reversing.

**Expected Behavior:**
Raw binary files opened from Enterprise server should be processed identically to those loaded locally.

**Screenshots/Video Recording:**

![raw_bins_issue](https://github.com/user-attachments/assets/0fc4ecd6-402e-4baf-8b09-9046ecb0cbd7)

**Binary:**
Any raw binary will work for this. Attached example is a Thumb2 binary that should load to offset `0x8000000`.
[RANDOM.zip](https://github.com/user-attachments/files/17184345/RANDOM.zip)

**Additional Information:**
Please add any other context about the problem here.

**Comment by negasora** [comment]
This should have been fixed in 4.2.6095-dev, can you try updating to see if it still happens?

**Comment by fuzyll** [comment]
Just to clarify: We believe this is a known issue that we discovered, tracked, and fixed internally. `dev` builds starting with the one above (4.2.6095-dev) should have this resolved.

Alternatively, you could downgrade to 4.2.6062-dev, which is the version before the breaking change was introduced. This is the build that release testing was performed on and is the current "stable" build for Ultimate. Unfortunately, due a mix-up on our side, we shipped the 4.2.6063-dev build as the default installer for Ultimate, which I presume is why you're on that version (this is now also fixed).

Sorry for the mix-up, but do please confirm for us that one of those two versions (or anything newer) works for you. If not, it's always possible we have more than one issue and we're not reproducing this new one locally.

**Comment by Martyx00** [comment]
I confirm that this one is fixed in the latest dev build.
