### ISSUE TITLE
Mach-O takes a long time for initial open

### ISSUE THREAD

**Issue by negasora** [Vector35/binaryninja-api#5966]
Opening the file causes a UI hang for ~1 minute before analysis starts

Repro steps:
1. Download https://folivora.ai/releases/BetterTouchTool.zip
2. Extract `BetterTouchTool.app/Contents/MacOS/BetterTouchTool`
3. Open it in binja
4. Notice the UI hangs on open

Most of the time is spent in type library code

**Comment by plafosse** [comment]
This should be largely fixed as of 4.3.6564 its at least 500% faster
