### ISSUE TITLE
welcome window rendering glitches on windows.

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#5974]
Need to test the welcome window on windows. Getting reports that the rendering is glitched out. 
![image](https://github.com/user-attachments/assets/8dfe18cf-9da8-4d79-8d5d-1e51e0ca706e)
![image](https://github.com/user-attachments/assets/ed6e9439-3e8a-4f94-81cb-8d13eb3748e0)

**Comment by negasora** [comment]
Fixed in `4.2.6174-dev`
