### ISSUE TITLE
file dialogs should support project files (multiple locations)

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#5977]
I noticed this on enterprise but it applies to many different parts of the UI that load files any time we are using a project. Anywhere we load external files we should be able to browse the project as well. 

 - import debug info from external file
 - import header file
 - import from BNDB...
 - load raw file at address

In fact, we should probably take a look at the Interaction module as well that has a file selector. I bet that also needs to be updated to be able to account for project files.

**Comment by negasora** [comment]
Fixed in `4.2.6173-dev`
