### ISSUE TITLE
zstd compressed debug sections are not parsed

### ISSUE THREAD

**Issue by trumank** [Vector35/binaryninja-api#5984]
**Version and Platform (required):**
- Binary Ninja Version: 4.2.6168-dev Personal, cb0f14d8
- OS: arch
- OS Version: unknown
- CPU Architecture: x86_64

**Bug Description:**
Binary Ninja does not read/parse debug sections compressed with `zstd`.

**Steps To Reproduce:**

```cpp
#include <iostream>
#include <ostream>
#include <string>

struct Test {
  std::string msg;
};

int main() {
  Test t{.msg = "Hello, World!"};
  std::cout << t.msg << std::endl;
  return 0;
}
```

```console
g++ hello.cpp -g -fuse-ld=mold -Wl,--compress-debug-sections=zstd -o hello
```

Open `hello` in Binary Ninja and observe there is no struct named `Test` defined. Change the compression type to `zlib` or remove entirely and it will appear.

[hello.zip](https://github.com/user-attachments/files/17290021/hello.zip)

**Additional Information:**
I ran into this with my own tools using the `object` crate, perhaps related: https://github.com/gimli-rs/object/pull/730

**Comment by negasora** [comment]
Fixed in `4.2.6172-dev`
