### ISSUE TITLE
MLIL_BOOL_TO_INT/HLIL_BOOL_TO_INT should be simplified if the source is a consant

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#5988]
![Screenshot 2024-10-10 at 9 06 25 AM](https://github.com/user-attachments/assets/6dcd7f8e-c9b8-4919-aa6f-546a15849227)

[Archive 2.zip](https://github.com/user-attachments/files/17320334/Archive.2.zip)

**Comment by negasora** [comment]
Done in `4.2.6185-dev`
