### ISSUE TITLE
BinaryViewType['ELF'].open("/") segfault

### ISSUE THREAD

**Issue by lucasduffey** [Vector35/binaryninja-api#599]
# system info
`Ubuntu 16 LTS`, commercial dev. Headless processing. Also crashes if I run it from binja's built-in python shell.

# Repro
```
bv = BinaryViewType['ELF'].open("/")
```

**Comment by psifertex** [comment]
That sounds like one that was fixed on dev a while ago -- are you on stable?

**Comment by lucasduffey** [comment]
I'll have to check when I get back. Maybe when I put the new key it reverted to stable.

**Comment by lucasduffey** [comment]
yep I'm on dev

**Comment by bpotchik** [comment]
Fixed in Build 809.
