### ISSUE TITLE
Better handling for trying to open a SQLite database that is not a BNDB

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#5998]
Had an Enterprise customer recently that stored a SQLite database in a Project and then, later, tried to open it (mistaking it for a binary/`.bndb`). Our error handling for this is kinda bad and misled them into thinking that we had corrupted the file (it was, instead, `bindiff` output and not corrupted at all).

**Comment by negasora** [comment]
Fixed in `4.3.6554-dev`
