### ISSUE TITLE
detect 64-bit python on windows

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#6]
_From @psifertex on September 1, 2015 21:42_

Make sure the install python API menu option detects whether 64bit python is installed and error accordingly

_Copied from original issue: Vector35/binaryninja#48_

**Comment by psifertex** [comment]
Note that a temporary workaround if you're being hit with this bug is to just remove the python plugin from the plugin folder. It can otherwise prevent binaryninja from starting up, and every time it auto-updates, the plugin will need to be removed until the proper fix is in.

**Comment by plafosse** [comment]
Key is in:
HKLM\SOFTWARE\Python\PythonCore\versionnumber\InstallPath  or
HKCU\SOFTWARE\Python\PythonCore\versionnumber\InstallPath
for 32-bit python and:
HKLM\SOFTWARE\Wow6432Node\Python\PythonCore\versionnumber\InstallPath
for 64-bit python

**Comment by rssor** [comment]
No longer needed as interpreter override is an option in `settings.json` as of build 1.1.1220-dev.

As an example, to have the UI use homebrew Python on macOS:

```
    "python" :
    {
        "interpreter": "/usr/local/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib"
    }
```
