### ISSUE TITLE
Windows Touch Issues

### ISSUE THREAD

**Issue by murmus** [Vector35/binaryninja-api#60]
On a high DPI touch screen, double click via touch is nearly impossible.

Additional, hex view is completely broken with default touch controls. Zoom is the only way I can get it to scroll.

**Comment by Manouchehri** [comment]
Scrolling is pretty much impossible with a touch screen, it only partly works in graph view (you can scroll if you avoid touching a basic block).

**Comment by KyleMiles** [comment]
Double Clicking on Windows with a High DPI screen works well... Not sure when it started but checked with 1.1.1646-dev.

Trying to scroll in hex view via touch controls still selects what's on the screen, though.

**Comment by psifertex** [comment]
QT fixes have improved the display/clicking, but we have no plans to implement more specific touch-support into the UI as it requires a whole new paradigm. In the meantime, cloud is more appropriate for touch now that it exists.
