### ISSUE TITLE
auto completion for symbols and types

### ISSUE THREAD

**Issue by junorouse** [Vector35/binaryninja-api#600]
Like this.

![a](http://i.imgur.com/fsC5zX0.png) 

(Edit by Jordan to add)
- [x] go to address
- [ ] change type dialog box

**Comment by psifertex** [comment]
Yeah, we plan to add a lot of auto complete functionality for the 1.2 UI update release,it should be for more than just the goto address. For example, the assembler, compiler, structure editor, etc. renaming this bug to track all of those.

**Comment by plafosse** [comment]
Similar to this request as of 1.1.1478 we've implemented input dialog history. This history is global (same across all binaries), persistent (stored across sessions), and distinct (different types of history are stored separately types, name, counts, etc).

**Comment by plafosse** [comment]
This is currently done for the "Go to address" dialog

**Comment by plafosse** [comment]
A new types dialog with auto completion was added in version: 1.1.1757
