### ISSUE TITLE
Unable to Clear Warning/s

### ISSUE THREAD

**Issue by utkonos** [Vector35/binaryninja-api#6005]
**Version and Platform (required):**
- Binary Ninja Version: 4.1.5902
- OS: macOS
- OS Version: 15.0.1 (24A348)
- CPU Architecture: x64

**Bug Description:**
Most of the time, when a warning icon appears in the lower right corner of binja's view, clicking on that warning icon opens the log and allows the user to scroll up to view the text of the warning. Sometimes, however, no matter how many clicks nor how far up one scrolls, the warning cannot be cleared without restarting binja.

**Steps To Reproduce:**
1. Open a binary that doesn't have a database yet (this is more likely to generate a warning than opening a database).
2. Do not clear the warning/s
3. Work for a while
4. Try to clear warnings and note that some cannot be cleared.

**Expected Behavior:**
Clicking on the warning icon opens logs, allows you to view the warning, then clears the icon.

**Screenshots/Video Recording:**

https://github.com/user-attachments/assets/8c5edf8b-8090-45da-86ff-f65a2b2c43b8

**Comment by psifertex** [comment]
related to #4572

**Comment by utkonos** [comment]
@psifertex Just to be clear: I don't mind the way that BN operates and I agree with @fuzyll concerns in that issue. All I'd like is to have some way to just clear everything so that new errors and warnings are obvious. I have tried `Clear Logs` which I assumed would also clear these icons, but it doesn't.

**Comment by psifertex** [comment]
I agree, not trying to suggest we don't want to fix this, just linking the issues so that when we're working on one we can be aware of the other.

**Comment by plafosse** [comment]
This will be fixed in 4.2.6320
