### ISSUE TITLE
Null Pointer Deference after calling demangle_gnu3 from python api.

### ISSUE THREAD

**Issue by 0x05a** [Vector35/binaryninja-api#6036]
**Version and Platform (required):**
- Binary Ninja Version: [4.2.6260-dev]
- OS: [Ubuntu Linux]
- OS Version: [e.g. 22.04]
- CPU Architecture: [x64]

**Bug Description:**

When de-mangling some function names with `demangle_gnu3`, Binary Ninja crashes with a segmentation fault. I have noticed this when calling `demangle_gnu3` on mangled function names that are either virtual or non-virtual thunks ex: `_ZTv0_n24_N8Platypus9makeSoundEv` or `_ZThn8_N8Platypus9makeSoundEv`. 

Before crashing there is a debug message logged: `[0:0 Default debug] Type reference created to empty name. This is suspicious.` Then there is a segmentation fault.

**Steps To Reproduce:**

Run in a python console or in the binary ninja python console:

```python
from binaryninja import load, demangle_gnu3
bad_str = "_ZTv0_n24_N4Bird9makeSoundEv"
bv = load(bytes.fromhex("5054ebfe"), options={"loader.architecture": "x86_64"})
demangle_gnu3(bv.arch, bad_str)
```

**Expected Behavior:**

I would expect a function type and function name to be returned.

**Screenshots**

Segmentation fault from python console:

![python console seg-fault](https://github.com/user-attachments/assets/de5fee02-0bc6-4e2a-8ce9-fe40dbfe6081)

GDB backtrace:

![binary_ninja_gdb_backtrace](https://github.com/user-attachments/assets/a9aac420-5951-4818-a0a7-e37d3d74b7ec)

Failing instruction:

![gdb_instruction_with_regs](https://github.com/user-attachments/assets/c0133e6e-dcca-40e9-9e4e-d903f7ea166a)

**Additional Context**

The GDB images are from running binary ninja with GDB and then either running a plugin which calls `demangle_gnu3` or by pasting 
`demangle_gnu3(bv.arch,  "_ZTv0_n24_N4Bird9makeSoundEv")` in the binary ninja python console and executing it. I also have only tested this on binaryviews that have the `x86_64` architecture. This is also a very recent bug, this did not exist last week.

**Comment by CouleeApps** [comment]
Good find, looks like it was trying to invoke the template simplifier on types that were nullptr. Will be fixed in next dev release, >=4.2.6268
