### ISSUE TITLE
Weirdly-aligned braces in Pseudo C

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/binaryninja-api#6040]
4.2.6281-dev (3f292d7f)

This looks like some weird GNU style guide alignment... Notice how the braces are not aligned with the indentation guide. This does not occur in Pseudo Rust.

![image](https://github.com/user-attachments/assets/c5c651ea-b6da-4f72-b460-09175dce201b)

**Comment by plafosse** [comment]
Fixed on dev 4.2.6300
