### ISSUE TITLE
App won't quit if about dialog is open

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/binaryninja-api#6041]
1. Open Binary Ninja
2. Open "About" dialog
3. Switch back to main window
4. Cmd+Q
5. Notice main window closes, "About" dialog remains open

The app does not terminate until the "About" dialog is manually closed.

8.2.6281-dev (3f292d7f)
macOS 15.0

**Comment by galenbwill** [comment]
Also happens if the "Restart Binary Ninja" action is used... in which case the new instance does launch, but the old instance remains until the About dialog is closed.

**Comment by galenbwill** [comment]
Fixed in builds >= 4.2.6367
