### ISSUE TITLE
Unable to Display Case as Enum Name in Disassembly View

### ISSUE THREAD

**Issue by utkonos** [Vector35/binaryninja-api#6048]
**Version and Platform (required):**
- Binary Ninja Version: 4.1.5902
- OS: macOS
- OS Version: 15.0.1 (24A348)
- CPU Architecture: x64

**Bug Description:**
Selecting a case and using the right click "Display As" -> Enum Member in the Disassembly View does not change how the case is displayed.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Make sure that an enum exists with the correct content
1. Select the hex display of a case.
2. Right click
3. Select Display As -> Enum Member
4. Notice that nothing happens.
5. Open an IL view and do the same
6. Notice that the enum is now displayed rather than hex (but only in this view, not disasm)

**Expected Behavior:**
The display as works just fine for the exact same case in IL views, the Disassebly View should change the 0x12 to "FOO" like IL views.

**Screenshots/Video Recording:**
<img width="733" alt="image" src="https://github.com/user-attachments/assets/9c5f4995-384a-47c5-9949-1c9ed71a6fdf">

vs

<img width="379" alt="image" src="https://github.com/user-attachments/assets/fc9f3a00-f402-4c03-b3e5-cf1028b71c76">

**Comment by CouleeApps** [comment]
Looks like the case labels were not being rendered with the proper address set to pick up on the integer display type settings. Pretty simple to fix, though note that these labels are technically not the same as the HLIL case blocks, and won't synchronize.

**Comment by CouleeApps** [comment]
Will be fixed in >= 4.2.6312

**Comment by utkonos** [comment]
Boom
<img width="541" alt="image" src="https://github.com/user-attachments/assets/9b9fb40c-a23c-4be9-aa2c-86b03ab32919">
