### ISSUE TITLE
`binaryninja.sharedcache.SharedCache.loaded_images` in the Python API is broken

### ISSUE THREAD

**Issue by WeiN76LQh** [Vector35/binaryninja-api#6049]
**Version and Platform (required):**
- Binary Ninja Version: 4.2.6304-dev (65f49c87)
- OS: macOS
- OS Version: 15.0
- CPU Architecture: M1

**Bug Description:**
The following exception occurs when trying to use the Python API to get the loaded images of the DSC being analysed:

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/sharedcache/sharedcache.py", line 181, in loaded_images
    value = sccore.BNDSCViewGetLoadedImages(self.handle, count)
AttributeError: module 'binaryninja.sharedcache._sharedcachecore' has no attribute 'BNDSCViewGetLoadedImages'
```

**Steps To Reproduce:**
Open a copy of the DSC in binary ninja and run the following code:

```python
import binaryninja.sharedcache
binaryninja.sharedcache.SharedCache(bv).loaded_images
```

**Expected Behavior:**
An exception shouldn't occur.

**Binary:**
This seems to be an API issue and not related to the DSC being analysed but in case it matters it occurred when analysing a copy of the DSC extracted from iOS 18.0.

**Comment by 0cyn** [comment]
Resolved in **dev builds >= 4.2.6359**

This (outdated) api was replaced with `SharedCache.loaded_regions` which will return the list of regions that've been mapped into memory.
