### ISSUE TITLE
Analysis hang

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#605]
Address: 0x804991a seems to cause an infinite analysis loop.

[CGC_Hangman_Game_patched_stripped.zip](https://github.com/Vector35/binaryninja-api/files/725345/CGC_Hangman_Game_patched_stripped.zip)

**Comment by joshwatson** [comment]
The name of this particular binary makes this issue hilarious

**Comment by D0ntPanic** [comment]
Fixed in dev
