### ISSUE TITLE
Analysing the DSC in a project doesn't work

### ISSUE THREAD

**Issue by WeiN76LQh** [Vector35/binaryninja-api#6050]
**Version and Platform (required):**
- Binary Ninja Version: 4.2.6304-dev (65f49c87)
- OS: macOS
- OS Version: 15.0
- CPU Architecture: M1

**Bug Description:**
Analyzing the DSC in a project causes the following error:

```
[Default] Serious VM Error: Couldn't read file at <redacted>/dyld_shared_cache_arm64e.bnpr/data/94/650f86-f414-4a81-9829-cc0bea30ba3d.01
[Default] Error: 2 (No such file or directory)
[SharedCache] Failed to perform initial load of Shared Cache
```

It is trying to load `dyld_shared_cache_arm64e.01`, one of the many files that make up the DSC, but it can't find it within the project directory. The file path is almost correct except the file is stored without the `.01` file extension. The path in the error log should have been `<redacted>/dyld_shared_cache_arm64e.bnpr/data/94/650f86-f414-4a81-9829-cc0bea30ba3d` to have been valid. This results in the DSC being unanalyzable within a project and the DSCViewAlpha does not display any information or allow the loading of images within the DSC.

**Steps To Reproduce:**
1. Use [ipsw](https://github.com/blacktop/ipsw) to extract the DSC from an iOS 18.0 IPSW file.
2. Create a new project in Binary Ninja
3. Import all the extract DSC files into the project
4. Analyze the main DSC file (the one that doesn't have a file extension)

**Expected Behavior:**
Binary Ninja should be able to identify the correct file paths for all the different files that make up the DSC when analyzing the DSC in a project.

**Additional Information:**
The current work around for this issue is to analyze the DSC without a project and save the analysis as a new BNDB. Then import the BNDB into a project. The BNDB file will load and work fine within a project, including the ability to load additional images in the DSC.

**Comment by 0cyn** [comment]
Resolved in **dev builds >= 4.2.6359**

**Comment by WeiN76LQh** [comment]
When using Binary Ninja with the UI the issue is fixed but when using Binary Ninja in headless mode with the Python API I'm still getting an error when loading.

```python
binaryninja.load(dsc_file.path_on_disk, update_analysis=False, options={'analysis.mode': 'controlFlow'})
```

(`dsc_file` is a `binaryninja.ProjectFile`)

Is resulting in:

```
[0:0 Default error] Serious VM Error: Couldn't read file at <redacted>/dyld_shared_cache_arm64e.bnpr/data/0b/74762e-0369-44b9-9399-425f0f5d4510.01
[0:0 Default error] 
[0:0 Default error] Error: 2 (No such file or directory)
```

Don't think its user error but it might be. As far as I can tell I have updated the API to the latest dev version because

```python
dir(binaryninja.sharedcache.SharedCache)
```

Contains `loaded_regions`.

This is with Binary Ninja version 4.2.6360-dev (a11957fd)

**Comment by negasora** [comment]
Just pass dsc_file, not dsc_file.path_on_disk
