### ISSUE TITLE
Python Requests fails

### ISSUE THREAD

**Issue by boondoggler** [Vector35/binaryninja-api#606]
Hi, 

Attempting to run Ret-Dec plugin on Win 10 x64 box (https://github.com/hugsy/binja-retdec)
Binary Ninja fails plugin parsing on startup with following message:

_File "C:\Users\xxxxx\AppData\Roaming\Binary Ninja\plugins\binja-retdec-master\retdec.py", line 9, in <module>
import requests
ImportError: No module named requests
Python plugin 'binja-retdec-master' could not be loaded_

Pre-requisites have been fulfilled by installing Requests and Pygments packages. 

A quick check to see if Requests is installed correctly, shown below:

_C:\Windows>pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
capstone (3.0.4)
enum34 (1.1.6)
keystone (0.9.1)
pip (9.0.1)
pycrypto (2.6)
Pygments (2.1.3)
PySide (1.2.4)
python-qt5 (0.1.10)
requests (2.13.0)
setuptools (28.8.0)
unicorn (0.9)
wheel (0.29.0)

C:\Windows>python
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>>_

Any ideas? I am making a huge presumption this is not the ret-dec plugin that is failing!

**Comment by joshwatson** [comment]
Binja on windows doesn't use system Python. Move the requests module to your plugin directory and it will load

**Comment by boondoggler** [comment]
Thanks Jon all good now
