### ISSUE TITLE
extra objc errors when LLIL is missing

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#6069]
The latest DSC plugin produces extra warnings that should either be changed to Warnings or removed entirely:

```
[Function] Skipping analysis for function at 0xc4b21c : Exceeds 'analysis.limits.maxFunctionSize'
[Plugin.Objective-C] (Workflow) Failed to get LLIL for 0xc4b21c
```

**Comment by 0cyn** [comment]
This is an issue w/ the Objective-C Workflow. Resolved in **dev builds >= 4.2.6378**
