### ISSUE TITLE
Crash in PDB import when loading C# NativeAOT binary

### ISSUE THREAD

**Issue by NotNite** [Vector35/binaryninja-api#6076]
**Version and Platform (required):**

- Binary Ninja Version: 4.2.6344-dev Personal
- OS: Windows 11
- OS Version: 23H2 (22631.4317)
- CPU Architecture: x64

**Bug Description:**

When loading a [C# NativeAOT](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot) executable built for Windows x86 with debug information, Binary Ninja crashes in `pdb_import_plugin.dll` with a `STATUS_STACK_BUFFER_OVERRUN`.

Deleting the `.pdb` on disk fixes the issue, but obviously means you don't get symbols.

**Steps To Reproduce:**

1. Download the [.NET 9 SDK](https://dotnet.microsoft.com/en-us/download/dotnet/9.0).
2. Create a new console project.
3. Set `<TargetFramework>net9.0</TargetFramework>` and `<PublishAot>true</PublishAot>` in the `.csproj`.
4. `dotnet publish -r win-x86 -c Release`
5. Load the resulting executable or DLL into Binary Ninja.

**Expected Behavior:**

Not crash, hopefully loading the PDB in the process, or failing the import if it's unrecoverable.

**Binary:**

[Here](https://files.catbox.moe/ubi61w.zip).

**Additional Information:**

.NET 9 is still in beta for a while. NativeAOT targets for x86 are a .NET 9 exclusive feature.

I don't know if this affects any other x86 binary with debug information.

**Comment by CouleeApps** [comment]
Can confirm crash, will look into it

**Comment by CouleeApps** [comment]
So on macOS this is actually throwing a SIGABRT and aborting on an assertion failure, specifically this line:

https://github.com/Vector35/pdb-rs/blob/4013bf82bce7d979c9374aea1ef34692a7c57228/src/tpi/data.rs#L318

Commenting out the assertion causes the binary to load on my box. I'm not sure where you are getting a `STATUS_STACK_BUFFER_OVERRUN` from though, that seems rather not great. This might be a windows-specific crash.

**Comment by CouleeApps** [comment]
Seems like that assert was the only thing crashing the process, even on windows. The fact that `STATUS_STACK_BUFFER_OVERRUN` is the status code for an assertion failure is rather baffling to me, but so is the majority of Windows' behavior so I guess this is just another case to remember.
