### ISSUE TITLE
Pointer Sweep should include all Sections with Readable semantics and backed by a file 

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#6088]
Binary Ninja 4.2-dev
In the following binary PointerSweep doesn't pick up pointers in the .rdata section and it should.

[PE-bear_dumped.exe.zip](https://github.com/user-attachments/files/17633100/PE-bear_dumped.exe.zip)

**Comment by bpotchik** [comment]
Fixed in `4.2.6360`.
