### ISSUE TITLE
Add an easy way to retrieve `LowLevelILBasicBlock` objects

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#609]
It's fairly easy to get an instruction's basic block using `Function.get_basic_block_at`, but the `LowLevelILFunction` does not have an analogous member function. As it stands, it seems the only way to get a `LowLevelILBasicBock` object for a given `LowLevelILInstruction` is something like this:

```python
# assume il_idx is the instruction index
for bb in func.low_level_il:
    if bb.start <= il_idx < bb.end:
        my_block = bb
        break
```

This could be an annoying bottleneck in any script or plugin that needs to do a lot of basic block lookups. It would be nice if a lookup table was used, so that there could be an API for `LowLevelILFunction` similar to `Function.get_basic_block_at`.

**Comment by rssor** [comment]
Support for grabbing basic block objects from both medium and low level IL instructions was added in build 1.1.1296-dev.
