### ISSUE TITLE
DSC View crashes when opening a DSC if contained images aren't accessible

### ISSUE THREAD

**Issue by galenbwill** [Vector35/binaryninja-api#6092]
**Version and Platform (required):**
- Binary Ninja Version: < 4.2.6359-dev

**Bug Description:**
Opening a DSC file will cause a crash when enumerating images if the images referenced by the DSC aren't accessible in the same directory (or project folder) as the DSC file.

**Additional Information:**
This issue is already fixed on `test_dyldsharedcache` branch, and will be resolved when it is merged to dev.

**Comment by 0cyn** [comment]
Resolved in dev builds >= 4.2.6359
