### ISSUE TITLE
Save/Load does not work with SharedCache

### ISSUE THREAD

**Issue by galenbwill** [Vector35/binaryninja-api#6093]
**Version and Platform (required):**
- Binary Ninja Version: 4.2.6360-dev

**Bug Description:**
When saving or loading a SharedCache to/from a BNBD, an error occurs:
```
[Default error] View type 'DSCViewAlpha' could not be created
```

**Additional Information:**
Should be fixed I think in builds > 4.2.6366, though "not for projects"

**Comment by 0cyn** [comment]
Resolved in **dev builds >= 4.2.6376**
