### ISSUE TITLE
Can not parse macos system binary files. 

### ISSUE THREAD

**Issue by M3noetius** [Vector35/binaryninja-api#6100]
**Version and Platform (required):**
- Binary Ninja Version: 4.2.6337-dev personal edition
- OS: MacOS
- OS Version: Sequioia 15.0.1
- CPU Architecture: M1

**Bug Description:**
__text section of Mach-O file is not getting parsed/decompiled

**Steps To Reproduce:**
1. Copy  /usr/libexec/watchdogd 
2. Open the file with binja 
3. Change the platform to macos-AARCH64
4. Go to the __text section or click on any function from the symbol view 

**Expected Behavior:**
The disassembly should be shown.

**Additional Information:**
The same thing happens with system at least (I have not tried any other) binaries on iOS.
[watchdogd.zip](https://github.com/user-attachments/files/17669459/watchdogd.zip)

**Comment by negasora** [comment]
This is working fine for me with both `4.2.6337-dev` and `4.2.6390-dev` - do you have initial analysis hold set maybe?

**Comment by M3noetius** [comment]
I checked it again. During the initial analysis. When the "Open with options" window opens , at the top, the binary is recognized as a universal binary. From there you have to choose the arme version and not leave it on the default x86_x64.
