### ISSUE TITLE
copy paste function need to improve

### ISSUE THREAD

**Issue by bb33bb** [Vector35/binaryninja-api#6108]
- Binary Ninja Version: 
- OS: manjaro
- OS Version:
```
> cat /proc/version
Linux version 6.10.13-3-MANJARO (builduser@fv-az1246-770) (gcc (GCC) 14.2.1 20240910, GNU ld (GNU Binutils) 2.43.0) #1 SMP PREEMPT_DYNAMIC Tue Oct  8 03:24:49 UTC 2024
```
- CPU Architecture: x64

**Bug Description:**
as in the video, meet seviral times that copy and paste not well functioned
**Steps To Reproduce:**
check the video
…
https://github.com/user-attachments/assets/79d96d7c-078d-4e6c-969a-d9711511bf59

**Comment by plafosse** [comment]
We can not reproduce this issue on supported Linux operating systems.

**Comment by bb33bb** [comment]
> We can not reproduce this issue on supported Linux operating systems.

I close it first and forgive me some time to reproduce it.
After i can stably reproduce it , i will reopen it.
if its ok ,i will close it 3 hours later.
