### ISSUE TITLE
Project folder description change can get lost during other project folder metadata update

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#6113]
**Version and Platform (required):**
- Binary Ninja Version: 4.1.5902
- OS: Any
- OS Version: Any
- CPU Architecture: Any

**Bug Description:**
There is a race condition where a change for a project folder description can get lost if the project folder is also updated around the same time by another user (e.g. renamed).

**Expected Behavior:**
We should never silently lose the new information.

**Comment by negasora** [comment]
Fixed in `4.2.6405-dev`
