### ISSUE TITLE
Project import should have an option to follow symlinks

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#6114]
**What is the feature you'd like to have?**
Project import should have an option to follow symlinks (right now, it ignores them and does not resolve them).

**Is your feature request related to a problem?**
An Enterprise user has a workflow where following symlinks during Project import would be quite helpful.

**Are any alternative solutions acceptable?**
Any solution that gets the symlinked files imported directly without having to pre-process things with an extra script would be helpful in this circumstance.

**Comment by negasora** [comment]
Added in `4.2.6412-dev` via setting `projects.folderImportFollowsSymlinks` (disabled by default)
