### ISSUE TITLE
Automatically applied calling conventions for _objc_retain_x{n} and _objc_release_x{n}

### ISSUE THREAD

**Issue by 0cyn** [Vector35/binaryninja-api#6121]
**What is the feature you'd like to have?**
DSC Support recently added some calling conventions to aarch64 for objc_retain_x{n} and objc_release_x{n}, some optimized ARC functions that take their argument on the register noted in the name. 

We should automatically apply these to non-dsc binaries as well, and can do this via typelibs.

**Comment by plafosse** [comment]
Fixed in 4.2.6443
