### ISSUE TITLE
Rename DefaultWorkflow Well-Known Names

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#6154]
Per some internal discussion from several months ago, we plan to rename "defaultAnalysis" and "metaAnalysis" as below to reduce confusion: 

"defaultAnalysis" -> "coreAnalysis"

**Comment by bpotchik** [comment]
'defaultAnalysis' -> 'baseAnalysis'
 
 Fixed in `4.3.6489-dev`.
