### ISSUE TITLE
DWARF Export Crash on Divide by Zero

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#6156]
**Version and Platform (required):**
- Binary Ninja Version: 4.2.6447-dev

**Bug Description:**
[This line](https://github.com/Vector35/binaryninja-api/blob/dev/rust/examples/dwarf/dwarf_export/src/lib.rs#L290) can wind up being 0 and causing a crash.

**Expected Behavior:**
No crashes.

**Additional Information:**
Reported by user in Slack.

**Comment by fuzyll** [comment]
Vector 35 employees can search for `unaltered subatomic barge equivalent` to find the user-provided test case.

**Comment by plafosse** [comment]
Fixed in 4.2.6451
