### ISSUE TITLE
Symbols sidebar filter does not have placeholder text

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#6163]
**Version and Platform (required):**
- Binary Ninja Version: 4.2.6455-dev,  2c8da1e
- OS: macos
- OS Version: 15.1
- CPU Architecture: arm64

**Bug Description:**
I believe there should be some text indicating "Search symbols."

<img width="437" src="https://github.com/user-attachments/assets/0ff644cb-c173-434b-9ed2-458d8c4c840f">

**Comment by psifertex** [comment]
Resolved in builds >= 4.3.6536
