### ISSUE TITLE
Personal license causes segfault when trying to use rust api

### ISSUE THREAD

**Issue by james-a-johnson** [Vector35/binaryninja-api#6186]
**Version and Platform (required):**
- Binary Ninja Version: 4.2.6455 Personal
- OS: Pop-OS
- OS Version: 22.04
- CPU Architecture: x86-64

**Bug Description:**
I was trying to make a rust executable using the binary ninja api. I wasn't sure if that feature was compatible with the personal license or not. I decided to try and see what would happen.

I went through the getting started steps on the crate documentation and when I ran the executable it segfaulted.

**Steps To Reproduce:**
1. Have just a binary ninja personal license
2. Follow the steps [here](https://rust.binary.ninja/binaryninja/#mainrs)
3. `cargo run`

**Expected Behavior:**
I was either expecting success or a reasonable error message but instead I got a segfault.

It would be nice to have a similar error message to the python exception that gets thrown when trying to use it headless.

**Screenshots/Video Recording:**
![image](https://github.com/user-attachments/assets/107f3df7-53e0-4f90-af30-7632bb4f6461)

**Comment by emesare** [comment]
Yea this is being tracked with https://github.com/Vector35/binaryninja-api/issues/5796
