### ISSUE TITLE
Compile on current Ubuntu with GCC14 - Cherrypick fix from rapidjson

### ISSUE THREAD

**Issue by raymontag** [Vector35/binaryninja-api#6201]
**Version and Platform (required):**
- Binary Ninja Version: [e.g. 4.0.4000-dev] (if version is stable, please also test the latest development build via the "Update Channel" option)
- OS: Ubuntu
- OS Version: 24.10
- CPU Architecture: x64

**Bug Description:**
On a current Ubuntu Linux with GCC 14, it is not possible to compile binaryninja-api due to a compilation error in rapidjson.

A fix is available here: https://github.com/Tencent/rapidjson/pull/719

**Steps To Reproduce:**
I used Jordans script to buils binexport which compiles binaryninja-api as a dependency. 

**Expected Behavior:**
That it builds.

**Comment by negasora** [comment]
Done in 6d93e8319411fca2c0d67e7ab29d135f5348328c which will be part of `4.3.6580-dev`
