### ISSUE TITLE
Analysis infinite loop caused by data variable blacklist

### ISSUE THREAD

**Issue by VisualEhrmanntraut** [Vector35/binaryninja-api#6206]
**Version and Platform (required):**
- Binary Ninja Version: 4.3.6502-dev
- OS: macOS
- OS Version: 15.2 Beta (24C5089c)
- CPU Architecture: M3

**Bug Description:**
There's not much to say, the analyser seems to be stuck analysing some functions for some reason...

**Steps To Reproduce:**
No idea...

**Expected Behavior:**
It should not be getting stuck.

**Screenshots/Video Recording:**

https://github.com/user-attachments/assets/891edd8d-e57a-402b-933c-b52f741c55f5

**Binary:**
Can't provide it, sorry.

**Additional Information:**
Instructions in the recording, 9bdc/9bca: `push rbp`, 5f658: is `lea rdi, [rbx+0x198]`, haven't checked the others.

**Comment by VisualEhrmanntraut** [comment]
Forgot to mention that it started after I updated to 6490, but I don't remember which version I was on previously. I noticed the issue too late.

**Comment by xusheng6** [comment]
> Forgot to mention that it started after I updated to 6490, but I don't remember which version I was on previously. I noticed the issue too late.

@VisualEhrmanntraut thx for the bug report! Are you on our slack? If so, could you please ping me?

**Comment by VisualEhrmanntraut** [comment]
I'm not. Should I make a slack account and join it?

**Comment by xusheng6** [comment]
> I'm not. Should I make a slack account and join it?

Please if that is convenient for you (https://slack.binary.ninja/). I have made a bisecting tool that can find out which exact build introduced the bug. It is not yet ready for public consumption but I can share it with you directly

**Comment by VisualEhrmanntraut** [comment]
Actually, I just realised I can look at my previous issue (the cascading math one). It says 4.3.6468-dev, but I'm not 100% sure if that one was without the issue. I'll join the slack in a second.

**Comment by bpotchik** [comment]
@xusheng6  Looks like DefineDataVariable was modified to allow disabling the creation of DataVariables. While this might be acceptable, the method needs to be updated to return an indication when a DataVariable is not created, to prevent distributing unnecessary update notifications. These update notifications are causing the analysis loops.

**Comment by bpotchik** [comment]
Fixed in `4.3.6504-dev`.

**Comment by xusheng6** [comment]
> @xusheng6 Looks like DefineDataVariable was modified to allow disabling the creation of DataVariables. While this might be acceptable, the method needs to be updated to return an indication when a DataVariable is not created, to prevent distributing unnecessary update notifications. These update notifications are causing the analysis loops.

Nice catch, thx!
