### ISSUE TITLE
Dead libcurl-compat link

### ISSUE THREAD

**Issue by ALSchwalm** [Vector35/binaryninja-api#621]
On the troubleshooting [page here](https://docs.binary.ninja/guide/troubleshooting/index.html), the link for libcurl-compat in the Arch Linux section is dead. That package has been moved to Community [here](https://www.archlinux.org/packages/community/x86_64/libcurl-compat/). If there is a more appropriate place for web admin stuff like that, please let me know.

**Comment by psifertex** [comment]
Thanks, fixed. Updated online, will be fixed in the next dev release for offline docs. 

And nope, this is a fine place for that report, thanks!
