### ISSUE TITLE
Auto-Analysis Can Get Stuck in an Infinite Loop

### ISSUE THREAD

**Issue by redlattice-ph** [Vector35/binaryninja-api#622]
When working with a binary file at times if you define something as code which may or may not be actual code, BN can get stuck in an infinite loop.  In this case it pegged all cores of my CPU at 100% utilization and stayed that way while making no noticeable progress for several hours.  In the end, I closed the file and it continued to peg the CPU until I forced the app closed.  In addition, when it began the analysis, it identified a number of functions which showed up in the function list, which were not actual functions as far as I could tell and when I went to those locations, it just showed the hex view.

**Comment by plafosse** [comment]
We have some examples of this already: #605 Do you have a specific test case for this?

**Comment by redlattice-ph** [comment]
This may be the same as #605, but not sure.  Will let you know if I get the time to work on reproducing this.

**Comment by plafosse** [comment]
Since there is no binary supplied or additional information, I'm going to assume this is the same issue as #605 which is fixed in dev.
