### ISSUE TITLE
Add Default Platform to BinaryViewType['Raw']

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#623]
![screen shot 2017-02-15 at 11 18 44 am](https://cloud.githubusercontent.com/assets/5834130/22983579/898873c4-f370-11e6-8176-561b98d82f76.png)

The Raw `BinaryView` does not have a platform associated with it, which means that the Types UI cannot be used, nor can generic types such as `int` or `char` be assigned. Either a default platform needs to be added, or an exception needs to be made so that the raw view can parse a simple set of types in order define structs in raw binary files.

**Comment by bpotchik** [comment]
Fixed in build 1.1.1028-dev.
