### ISSUE TITLE
The first analysis program allows you to set (pop-up window) analysis base address and other options

### ISSUE THREAD

**Issue by eaglesharkmayonnaise** [Vector35/binaryninja-api#6233]
**What is the feature you'd like to have?**
I'm used to setting the base to 0, but due to (#6110 seems to be fixed now (there are many other related bugs [issues?q=rebase](https://github.com/Vector35/binaryninja-api/issues?q=rebase)), but I'm afraid of affecting the analysis results) I have to wait for the analysis to finish before setting it again, and even if the analysis is completed, setting it to 0 seems to trigger a re-analysis, which will take a lot of time (if the file is large enough)

**Is your feature request related to a problem?**
na

**Are any alternative solutions acceptable?**
na
**Additional Information:**
na

**Comment by xusheng6** [comment]
You can use the "open with options" dialog for this purpose.

I am closing this for now because I believe this has a satisfying solution, please free feel to add to this thread if you have more information about it
