### ISSUE TITLE
Plugin Idea Wish List

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#626]
Please include a comment with an idea for a plugin you have that you don't have time to implement and we can use this issue to track it so when someone is looking for ideas of plugins to implement they can grab something from this list: 

- [ ] Function Recognizer (will eventually be implemented in core, but feel free to implement a prototype) -- ability to identify statically compiled functions either by: (analyzing source code and identifying dependencies/relationships) or by porting function fingerprints from a binary with symbols to a binary without symbols)
- [ ] LLIL emulator -- simulate binary execution by emulating IL instructions
- [ ] Division De-optimizer -- Take optimized division (https://zneak.github.io/fcd/2017/02/19/divisions.html / http://www.hackersdelight.org/magic.htm) and annotate the constants with the actual division being done (Start of an implementation: https://github.com/cah011/binja-div)
- [ ] Auditor Framework -- See @lucasduffey below
- [ ] Capstone -- implement a generic shim leveraging capstone for any otherwise unsupported architecture. 
- [ ] Binary Diffing -- see https://github.com/joxeankoret/diaphora/issues/29#issuecomment-248210862 for information on integrating with Diaphora, or consider porting/re-implementing https://github.com/google/binexport for support with bindiff or https://github.com/McGill-DMaS/Kam1n0-Plugin-IDA-Pro
- [ ] Auto-Unpacker -- emulate basic memory operations to automatically unpack simple packing mechanisms. 
- [ ] Magic Strings -- see: https://github.com/joxeankoret/idamagicstrings
- [ ] Sibyl support -- https://github.com/cea-sec/Sibyl
- [ ] Malware Repository search -- automate the ability to query the various online malware repositories for information about a given file's hash (or potentially hashes referenced in another file) and display the results internally. See: https://github.com/rshipp/awesome-malware-analysis#malware-corpora and https://github.com/rshipp/awesome-malware-analysis#online-scanners-and-sandboxes
- [x] Crypto Finder -- using common constants identify various cryptographic algorithms. Bonus points for avoiding false positives by using the IL to detect equivalent uses (https://github.com/blackthorne/Codetective) -- Initial implementation by https://github.com/Rami114/cryptoscan
- [x] IDA/IDC Sync -- Ability to import / export common elements like symbols, names, functions, comments, etc between IDA and Binary Ninja. Bonus points: implement a tool agnostic format that supports plugins so that sync between radare2, hopper, etc, can be done as well.  (Several plugins: https://github.com/Cryptogenic/idc_importer https://zznop.github.io/bnida/ https://github.com/lunixbochs/revsync) 

(I'm leaving off the decompiler as that's probably requires too many core enhancements)

**Comment by lucasduffey** [comment]
Decompiler

**Comment by polsab** [comment]
- [ ] Binary differ - BinDiff/Diaphora/DarunGrim for binja

**Comment by withzombies** [comment]
- [ ] **Arbitrary data flow labels**. Allow plugins to create arbitrary dataflow labels (e.g. "Sensitive", "Crypto") and register callbacks to handle instances where they mix and sink.

**Comment by psifertex** [comment]
@withzombies Not sure that could be done effectively with a third-party plugin? Sounds more like a core change.

**Comment by withzombies** [comment]
It could, but it'd end up with someone re-implementing data flow on top of the IL as a plugin.

**Comment by psifertex** [comment]
Gotcha. I'll add it to the list with the caveat that it'll also be one of those likely to be implemented in the core later as well. Though it will be a lot easier to do with SSA about to land.

**Comment by psifertex** [comment]
Commenting since I'm on my phone: https://github.com/McGill-DMaS/Kam1n0-Plugin-IDA-Pro might be a good basis for a function comparator.

**Comment by cah011** [comment]
Division De-optimizer - WIP
https://github.com/cah011/binja-div

**Comment by lucasduffey** [comment]
intel hex file support (https://en.wikipedia.org/wiki/Intel_HEX)

**Comment by shiftre** [comment]
An IDA importer would be nice, I guess it's similar to ``IDA/IDC Sync``, either export an ``IDB`` to an ``IDC`` or just import the whole ``IDB``.

**Comment by psifertex** [comment]
IDA Importer exists: https://github.com/Vector35/BinaryNinjaImporter

**Comment by tonylambiris** [comment]
FWIW I hacked up a python script to attempt to install and enable all current plugins.

Copy and paste the following into the script console:
https://gist.github.com/tonylambiris/2168f3853f486efb0eb62bef7bbf0fc0

**Comment by nbanmp** [comment]
I've got a working pattern-agnostic division deoptimizer that operates on MLIL, and to a less tested extent a modulo deoptimizer. I've got to clean up the code and fix a couple easy bugs, but I'll open source it relatively soon.

**Comment by psifertex** [comment]
That's great news -- that was actually on our todo list for HLIL after launch, but it's great to hear you've already got something going on that front.
