### ISSUE TITLE
RegisterInfo.extend wrong type in built-in Architectures

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#627]
The `extend` member of the `RegisterInfo` class should be an `ImplicitRegisterExtend` enum value. However, the value actually passed to `RegisterInfo.__init__` by `Architecture` plugins is a string:

```
>>> Architecture['x86_64'].regs['eax'].extend
'ZeroWidthExtend'
>>> Architecture['armv7'].regs['s7'].extend
'NoExtend'
>>> type(Architecture['armv7'].regs['s7'].extend)
<type 'str'>
```

**Comment by plafosse** [comment]
Fixed in dev
