### ISSUE TITLE
linux kernel modules

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#63]
Don't load properly. Need to recognize system instructions as well as parse the different program header / init / exit functions.

**Comment by pgoodman** [comment]
Also worth understanding the various kind of exception table sections that things like `get_user` and `put_user` use to redirect execution to a fixup function when a fault occurs.

See here:
http://code.woboq.org/linux/linux/arch/x86/include/asm/asm.h.html#47
http://code.woboq.org/linux/linux/arch/x86/include/asm/uaccess.h.html#195

**Comment by obnauticus** [comment]
@lucasduffey  wants me to click the thumb but i won't.

**Comment by plafosse** [comment]
Support added as of v1.1.1345
