### ISSUE TITLE
Going from multiple monitors to just laptop screen hides Binary Ninja off screen on restart (Windows)

### ISSUE THREAD

**Issue by odinallo** [Vector35/binaryninja-api#630]
Closing Binary Ninja on a Windows laptop plugged into multiple monitors will cause the "windows0pos" registry key in "Computer\HKEY_CURRENT_USER\SOFTWARE\Vector 35\Binary Ninja\ui" to be set at the position that the program was  closed in. If the laptop is then removed from the monitors, and if this position is off the screen of the laptop, it will cause Binary Ninja to open off screen next launch, and cannot be brought back on screen. 

Temporary solution is to delete registry key and restart application.

**Comment by bpotchik** [comment]
Fixed in build 1.1.1112-dev.
