### ISSUE TITLE
Removing segments doesn't seem to work correctly

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#631]
```
>>> bv.add_user_segment(0, 0x1000, 0, 0, 0)
>>> bv.segments
[<segment: 0x0-0x1000, --->, <segment: 0x400000-0x40107c, r-x>, <segment: 0x601df8-0x602260, rw->]
>>> bv.remove_user_segment(0, 0x10)
>>> bv.segments
[<segment: 0x0-0x1000, --->, <segment: 0x400000-0x40107c, r-x>, <segment: 0x601df8-0x602260, rw->]
>>> bv.remove_auto_segment(0, 0x10)
>>> bv.segments
[<segment: 0x10-0x2000, --->, <segment: 0x400000-0x40107c, r-x>, <segment: 0x601df8-0x602260, rw->]
```

# Expected Result
`bv.remove_user_segment` should remove a user segment, or a portion of the user segment.
`bv.remove_auto_segment` should not remove a user segment at all.
# Actual Result
`bv.remove_user_segment` does not affect the user segment at all.
`bv.remove_auto_segment` removes a portion of the user segment, but also appears to double the size of the segment as a side-effect.

**Comment by plafosse** [comment]
Fixed in dev build number >= 813
