### ISSUE TITLE
Clickable addresses in warnings log

### ISSUE THREAD

**Issue by computerality** [Vector35/binaryninja-api#632]
It would be nice to be able to click on the instruction address in the warning messages in the log such as the ones that appear in the screenshot:
![screen shot 2017-02-24 at 3 13 56 pm](https://cloud.githubusercontent.com/assets/464609/23319294/f1fcea68-faa3-11e6-8498-1ea7e3668c31.png)

**Comment by psifertex** [comment]
Could be part of #803

**Comment by plafosse** [comment]
Added as of v1.1.1401
