### ISSUE TITLE
Argument and return value discovery for arbitrary ABIs

### ISSUE THREAD

**Issue by pgoodman** [Vector35/binaryninja-api#634]
Binary Ninja should be able to discover function arguments that don't respect any conventional ABI. There are a few steps required in order to discover these, all of which are inter-procedural data flow analyses.

At a high level, what this amounts to is an inter-procedural SSA form that also manages to understand that some registers are preserved by functions, and so can potentially be elided from this form. Some steps that could achieve this, that approximate the data needed to build the def-use and use-def chains are:

1. Live register analysis. One of the goals of this analysis is to figure out  what registers are used in a function before being defined. This will include argument registers and preserved registers. This is a backward data-flow analysis. This information that it will produce is:
    - Live register sets on entry/exit to every basic block.
    - Live register sets before/after to every function call within a basic block.
    - Live registers on exit from a function. This is necessary but not sufficient to discover return values in registers.
2. Stack or execution simulation to distinguish live registers and preserved registers. Registers whose values are preserved by a function will also be live on entry to the function. 
3. Inter-procedural reaching definitions. This is a forward data-flow analysis that finds registers that are live on exit from a function, and where there is a definition of that register that reaches the end of a function. This analysis will help discover candidate registers that may contain return values.

**Comment by plafosse** [comment]
We are considering this part of type propagation #121 Though I will keep this around since it documents nicely one of the pieces of type propagation.

**Comment by plafosse** [comment]
This was done a while ago when MLIL was complete.
