### ISSUE TITLE
BinaryView.find_next_data very slow

### ISSUE THREAD

**Issue by endeav0r** [Vector35/binaryninja-api#635]
`BinaryView.find_next_data()` is very slow. Makes searching for constants a slow process over binaries around ~10mb in size.

I understand this may be a slow process to begin with, but this appears to be abnormally slow.

**Comment by plafosse** [comment]
Yeah, the algorithm reads one byte at a time, I can see how this would be slow for large files. We should probably be chunking our reads.

**Comment by bpotchik** [comment]
Fixed in 1.1.1302-dev.
