### ISSUE TITLE
Offset and virtual address side-by-side in disassembly view

### ISSUE THREAD

**Issue by peperunas** [Vector35/binaryninja-api#638]
It would be great to have both offset and virtual address in the disassembly view!

**Comment by psifertex** [comment]
After further consideration, you can make a custom view with this information or add a snippet that copies the [file offset](https://gist.github.com/psifertex/6fbc7532f536775194edd26290892ef7#file-clipboard-py) for quick access, and you can also switch to the hex editor in raw view to get file offsets, but we don't plan to implement this in the main views.
