### ISSUE TITLE
CFG minimap/thumbnail

### ISSUE THREAD

**Issue by justdionysus** [Vector35/binaryninja-api#639]
With larger CFG layouts, it is useful to reference which loop you're examining without having to zoom out and zoom back in.  I didn't realize how much I used the minimap/thumbnail from IDA until it was missing.

**Comment by psifertex** [comment]
I think we have an existing bug for this, when I'm not on my phone I will double check and close as a dupe if so.

One thing that isn't quite as useful but is better than nothing is the ability to zoom all the way out and back in very quickly with the mouse wheel. On OS X I believe it's control two finger scroll.

**Comment by plafosse** [comment]
For reference there is a hack get this: https://github.com/nbsdx/binja-ui-tweaks Version 1.2 will add this.

**Comment by plafosse** [comment]
Happy Thanksgiving 🦃🦃 Added in v1.1.1425
