### ISSUE TITLE
Allow inverted scrolling

### ISSUE THREAD

**Issue by ColdHeat** [Vector35/binaryninja-api#64]
Unsure if this is intentional or a Qt oddity. 

Scrolling up zooms out and scrolling down zooms in. Might be worth reversing it.

In addition, on OSX, Ctrl is used to zoom with conflicts with the zooming shortcut built into the OS. 
Maybe it's better to change that to Cmd to make that more in line with the OSX keyboard shortcuts?

**Comment by plafosse** [comment]
Could be related to "natural scrolling" on OSX probably should be menu item to toggle direction.

**Comment by psifertex** [comment]
Given that screen zooming has been disabled since 10.7, I'm less worried about it conflicting with the defaults. The direction could definitely be an option though.

**Comment by ColdHeat** [comment]
As an end user I'd expect zooming to mimic the browser but the direction is reversed. The browser and Sublime Text zoom with Cmd instead of Ctrl on OSX. It just seems more natural to me is all.

**Comment by psifertex** [comment]
I can't get Safari or Chrome to zoom with either control or cmd and up/down scrolling on OS X. Am I misunderstanding?

**Comment by ColdHeat** [comment]
Sorry I got it totally confused on shortcuts so here is my breakdown. 

It's actually Cmd + and - which is a different story. Also since the browser comparison doesn't work on OSX I will compare with OSX's zooming which uses the same keybinding but is system wide. 

Windows (Ctrl is the modifier key for shortcuts):
Ctrl + Scroll Wheel Up = Zooms OUT in Binja / Zooms IN in Chrome
Ctrl + Scroll Wheel Down = Zooms IN in Binja / Zooms OUT in Chrome
To me this makes sense modifier key wise but not directionally. 

OSX (Cmd is the modifier key for shortcuts):
Ctrl + Scroll Up = Zooms OUT in Binja / Zooms IN on OSX
Ctrl + Scroll Down = Zooms IN in Binja /  Zooms OUT on OSX
The modifier key doesn't make sense and the direction also doesn't make sense to me

**Comment by psifertex** [comment]
Note that this is blocked by #126 and will be also partially addressed by #92.

**Comment by psifertex** [comment]
Reviewing older issues and it looks like this is actually not the case anymore? A quick test shows that Chrome and BN behave the same and each invert their behavior depending on the natural scroll direction option. Feel free to re-open if that's not the case.
