### ISSUE TITLE
Rotate through flags other than carry in LLIL

### ISSUE THREAD

**Issue by alexforencich** [Vector35/binaryninja-api#640]
LLIL has rotate_left_carry and rotate_right_carry instructions.  However, on the 68k architecture, the equivalent instructions are roxl and roxr, which rotate through the X flag instead of through the C flag.  It might make sense to support this generally with rotate_left_flag / rotate_right_flag instructions which can rotate through any specified flag, either specified as an argument to the instruction or as an architecture parameter (similar to endianness or address size).

**Comment by plafosse** [comment]
This actually exists the rotate_left_carry is a misnomer the last argument of this instruction is the flag to rotate through.
