### ISSUE TITLE
OOM on mcsema-lifted SQLite3 binary

### ISSUE THREAD

**Issue by pgoodman** [Vector35/binaryninja-api#642]
[lifted_sqlite.tar.gz](https://github.com/Vector35/binaryninja-api/files/856324/lifted_sqlite.tar.gz)

**Comment by plafosse** [comment]
I tried this again post-dataflow refactor and the binary still takes a long time to complete analysis and takes 8GB of ram, but it does finish without OOMing. Being that this is only a 17MB binary, we there is definitely some degenerate case happening here.

**Comment by bpotchik** [comment]
We have improved analysis and memory utilization since this ticket has been filed. On my machine analysis of this binary completes in about 600 seconds and memory consumption hovers between 5GB-10GB.
