### ISSUE TITLE
Incorrect disassembly of immediates as data references

### ISSUE THREAD

**Issue by mossberg** [Vector35/binaryninja-api#644]
Hi, for this copy of glibc ld.so, binja incorrectly disassembles some insns with imm operands as data references (when compared against objdump). For example, address 0x19316. 

[ld-linux-x86-64.so.2 2.zip](https://github.com/Vector35/binaryninja-api/files/886713/ld-linux-x86-64.so.2.2.zip)

**Comment by psifertex** [comment]
Yeah, this is a known bug on dev and the reason we haven't merged it to stable yet. Before we merge it in, this will be resolved. This is dependent on #121 and has only appeared because #269 was implemented first before #121 was complete.

**Comment by plafosse** [comment]
Fixed in stable.
