### ISSUE TITLE
Architecture endianness setting ignored

### ISSUE THREAD

**Issue by alexforencich** [Vector35/binaryninja-api#645]
Binary ninja is ignoring the architecture endianness setting.  It makes no difference if 'endianness' in an architecture module is set to Endianness.BigEndian or Endianness.LittleEndian, any data defined with bv.define_user_data_var are always interpreted as little endian in the linear disassembly view.  

Test case:

Motorola 68k plugin: https://github.com/alexforencich/binaryninja-m68k

68k ROM: http://www.kswichit.com/68k/T68K.BIN

Create vector table with tools -> create M68k vector table -> address 0, architecture M68000, full size.  

Expected result: All vector table entries will be read as big endian and will match symbols defined with define_user_symbol .

Actual result: Vector table entries are read in wrong endianness (0x1300 instead of 0x130000, 0x200000 instead of 0x2000, 0x8001000 instead of 0x100008, 0x4290000 instead of 0x00002904, etc.), so only palindromes match (i.e. 0x00000000 or 0xFFFFFFFF).

**Comment by alexforencich** [comment]
Now, it's possible that I did something wrong in my code to set the endianness or the platform incorrectly, but the concensus on slack was that this is a bug in binary ninja and not how I'm using the API to define the vector table and corresponding entry points.

**Comment by alexforencich** [comment]
One thing I just noticed: it seems that bv.endianness does not change after setting the platform.  Not sure if this is related to the cause of this or not:

    >>> bv.platform
    >>> bv.endianness
    <Endianness.LittleEndian: 0>
    >>> bv.platform = Architecture['M68000'].standalone_platform
    >>> bv.endianness
    <Endianness.LittleEndian: 0>
    >>> Architecture['M68000'].endianness
    'BigEndian'

**Comment by plafosse** [comment]
I think there might be a bug, 
architecture.py:131
self.__dict__["endianness"] = Endianness(core.BNGetArchitectureEndianness(self.handle)).name
I think this should read
self.__dict__["endianness"] = Endianness(core.BNGetArchitectureEndianness(self.handle))

**Comment by joshwatson** [comment]
That's definitely a bug, haha

**Comment by alexforencich** [comment]
OK, that's definitely a bug, and arch.endianness now appears to return the correct type, but fixing that does not yet solve the original problem.  

    >>> Architecture['M68000'].endianness
    <Endianness.BigEndian: 1>
    >>> bv.platform
    <platform: M68000>
    >>> bv.endianness
    <Endianness.LittleEndian: 0>

And the endianness of the declared vector table entries is still wrong.

**Comment by alexforencich** [comment]
Hmm, it seems bv.arch is None.  Do both bv.platform and bv.arch need to be explicitly set, or is bv.platform supposed to also set bv.arch?

**Comment by plafosse** [comment]
So this issue was indeed that the default architecture wasn't being set.  I've changed the core so that when the default platform is set it also sets the default architecture. I've tested the issue with the linked plugin and binary and it seems to work now. Thanks for the report. Will be fixed >= build 846
