### ISSUE TITLE
Strings don't appear inline when switching to Low Level IL on ARM

### ISSUE THREAD

**Issue by jdj3** [Vector35/binaryninja-api#649]
Looking at an assembly graph, strings appear inline for both x86 and arm, but if I switch to the LLIL graph, the strings are only there for x86. In this case, the instruction at 0x10448 is loading from a non-writeable section.

[hello.zip](https://github.com/Vector35/binaryninja-api/files/907945/hello.zip)

**Comment by psifertex** [comment]
This has been resolved since some time before the latest stable. Sorry we missed closing it.
