### ISSUE TITLE
Export CFG to PDF/SVG

### ISSUE THREAD

**Issue by pgoodman** [Vector35/binaryninja-api#65]
I would like to export binja CFGs to PDFs or SVGs (or PS/EPS)--any vector format. I think this would be great for embedding into papers, presentations, and even websites (SVG).

**Comment by psifertex** [comment]
Mislabeled commit message, sorry. Re-opening. 

For what it's worth, this is one definitely one of the features we've been planning on. HTML export is also on that list which gives a lot of nice features like hovers, dynamic highlighting, etc.

**Comment by psifertex** [comment]
SVG export is [checked in](/vector35/binaryninja-api/tree/dev/python/examples/export-svg.py). I do plan on adding some additional features later on like data-flow annotation in the hovers, as well as selectability (which is much harder on SVG than HTML because of the lack of `background-color`)
