### ISSUE TITLE
crash: integer overflow opening binary

### ISSUE THREAD

**Issue by fatcrack** [Vector35/binaryninja-api#650]
Unhandled exception at 0x00007FF8E597ED47 (binaryninjacore.dll) in binaryninja.exe: 0xC0000095: Integer overflow.

exception at: 00007FF8E597ED47        | 49 F7 F8                           | idiv r8                                                 |

r8 = FFFFFFFFFFFFFFFF

I can't provide the binary due to legal issues...

registers:

RAX : 8000000000000000
RCX : 7FFFFFFFFFFFFFFF
RDX : FFFFFFFFFFFFFFFF
RBX : 000000AFB90FF670
RDI : 000002479E96BBB0
RBP : 000000AFB90FB1F0
RSI : 000000AFB90FDB60
RSP : 000000AFB90FB0F0
R8  : FFFFFFFFFFFFFFFF
R9  : 000002479EA5C6F0
R10 : 000002479EA6A250
R11 : 0000000000000000
R12 : 0000000000000001
R13 : 0000000000000000
R14 : 0000000000000000
R15 : FFFFFFFFFFFFFFFF
RIP : 00007FF8E597ED47     binaryninjacore.00007FF8E597ED47
RFLAGS : 0000000000010286
CF : 0
PF : 1
AF : 0
ZF : 0
SF : 1
TF : 0     L'Ā'
IF : 1
DF : 0
OF : 0
GS : 002B
FS : 0053
ES : 002B
DS : 002B
CS : 0033
SS : 002B     '+'
LastError : 00000000 (ERROR_SUCCESS)
DR0 : 0000000000000000
DR1 : 0000000000000000
DR2 : 0000000000000000
DR3 : 0000000000000000
DR6 : 0000000000000000
DR7 : 0000000000000000
x87r0 : 00000000000000000000
x87r1 : 00000000000000000000
x87r2 : 00000000000000000000
x87r3 : 00000000000000000000
x87r4 : 00000000000000000000
x87r5 : 00000000000000000000
x87r6 : 00000000000000000000
x87r7 : 00000000000000000000
x87TagWord : 0
x87ControlWord : 27F     L'ɿ'
x87StatusWord : 0
x87TW_0 : 0 (Ungleich Null)
x87TW_1 : 0 (Ungleich Null)
x87TW_2 : 0 (Ungleich Null)
x87TW_3 : 0 (Ungleich Null)
x87TW_4 : 0 (Ungleich Null)
x87TW_5 : 0 (Ungleich Null)
x87TW_6 : 0 (Ungleich Null)
x87TW_7 : 0 (Ungleich Null)
x87SW_B : 0
x87SW_C3 : 0
x87SW_TOP : 0 (ST0=x87r0)
x87SW_C2 : 0
x87SW_C1 : 0
x87SW_O : 0
x87SW_IR : 0
x87SW_SF : 0
x87SW_P : 0
x87SW_U : 0
x87SW_Z : 0
x87SW_D : 0
x87SW_I : 0
x87SW_C0 : 0
x87CW_IC : 0
x87CW_RC : 0 (Runden)
x87CW_PC : 2 (Real8)
x87CW_IEM : 0
x87CW_PM : 1
x87CW_UM : 1
x87CW_OM : 1
x87CW_ZM : 1
x87CW_DM : 1
x87CW_IM : 1
MxCsr : 1FA0
MxCsr_FZ : 0
MxCsr_PM : 1
MxCsr_UM : 1
MxCsr_OM : 1
MxCsr_ZM : 1
MxCsr_IM : 1
MxCsr_DM : 1
MxCsr_DAZ : 0     L'Ā'
MxCsr_PE : 1
MxCsr_UE : 0
MxCsr_OE : 0
MxCsr_ZE : 0
MxCsr_DE : 0
MxCsr_IE : 0
MxCsr_RC : 0 (Runden)
MM0 : 0000000000000000
MM1 : 0000000000000000
MM2 : 0000000000000000
MM3 : 0000000000000000
MM4 : 0000000000000000
MM5 : 0000000000000000
MM6 : 0000000000000000
MM7 : 0000000000000000
XMM0  : FFFFFFFFFFFFFFFF00000000000002D0     L'ː'
XMM1  : 00000037000000270000001700000007
XMM2  : 00000000000000000000000000000000
XMM3  : 00000000000000000000000000000000
XMM4  : 00000000000000000000000000000000
XMM5  : 00000000000000000000000000000000
XMM6  : 00000000000000000000000000000000
XMM7  : 00000000000000000000000000000000
XMM8  : 00000000000000000000000000000000
XMM9  : 00000000000000000000000000000000
XMM10 : 00000000000000000000000000000000
XMM11 : 00000000000000000000000000000000
XMM12 : 00000000000000000000000000000000
XMM13 : 00000000000000000000000000000000
XMM14 : 00000000000000000000000000000000
XMM15 : 00000000000000000000000000000000
YMM0  : 00000000000000000000000000000000FFFFFFFFFFFFFFFF00000000000002D0     L'ː'
YMM1  : 0000000000000000000000000000000000000037000000270000001700000007
YMM2  : 0000000000000000000000000000000000000000000000000000000000000000
YMM3  : 0000000000000000000000000000000000000000000000000000000000000000
YMM4  : 0000000000000000000000000000000000000000000000000000000000000000
YMM5  : 0000000000000000000000000000000000000000000000000000000000000000
YMM6  : 0000000000000000000000000000000000000000000000000000000000000000
YMM7  : 0000000000000000000000000000000000000000000000000000000000000000
YMM8  : 0000000000000000000000000000000000000000000000000000000000000000
YMM9  : 0000000000000000000000000000000000000000000000000000000000000000
YMM10 : 0000000000000000000000000000000000000000000000000000000000000000
YMM11 : 0000000000000000000000000000000000000000000000000000000000000000
YMM12 : 0000000000000000000000000000000000000000000000000000000000000000
YMM13 : 0000000000000000000000000000000000000000000000000000000000000000
YMM14 : 0000000000000000000000000000000000000000000000000000000000000000
YMM15 : 0000000000000000000000000000000000000000000000000000000000000000

code:

00007FF8E597ED20        | 0F 85 28 02 00 00                  | jne binaryninjacore.7FF8E597EF4E                        |
00007FF8E597ED26        | 0F B6 47 08                        | movzx eax,byte ptr ds:[rdi+8]                           |
00007FF8E597ED2A        | C0 E0 03                           | shl al,3                                                |
00007FF8E597ED2D        | 8D 88 FF 00 00 00                  | lea ecx,dword ptr ds:[rax+FF]                           |
00007FF8E597ED33        | B8 01 00 00 00                     | mov eax,1                                               |
00007FF8E597ED38        | 48 D3 E0                           | shl rax,cl                                              |
00007FF8E597ED3B        | 48 8D 48 FF                        | lea rcx,qword ptr ds:[rax-1]                            |
00007FF8E597ED3F        | 48 8B C1                           | mov rax,rcx                                             |
00007FF8E597ED42        | 48 F7 D0                           | not rax                                                 |
00007FF8E597ED45        | 48 99                              | cqo                                                     |
00007FF8E597ED47        | 49 F7 F8                           | idiv r8                                                 |
00007FF8E597ED4A        | 4C 8B C8                           | mov r9,rax                                              |
00007FF8E597ED4D        | 48 8B C1                           | mov rax,rcx                                             |
00007FF8E597ED50        | 48 99                              | cqo                                                     |
00007FF8E597ED52        | 49 F7 F8                           | idiv r8                                                 |
00007FF8E597ED55        | 48 8B 4D 80                        | mov rcx,qword ptr ss:[rbp-80]                           |
00007FF8E597ED59        | 49 3B C9                           | cmp rcx,r9                                              |

**Comment by plafosse** [comment]
Can you provide a stack trace?

**Comment by plafosse** [comment]
Also can you provide more details, what were you doing when this occurred. Were you loading a file? What type of file?

**Comment by fatcrack** [comment]
I was loading a 64bit-PE file (exe). The program starts to analyze and then crashes after some seconds.

version: 1.0.320 (Build ID 76713379)

the only stack trace  I can provide at the moment:

0000001EFDBFD198 00007FF8E597B7E4 00007FF8E597ED47 zurück zu binaryninjacore.00007FF8E597B7E4 von binaryninjacore.00007FF8E597ED47
0000001EFDBFF318 00007FF8E59746CB 00007FF8E597B7E4 zurück zu binaryninjacore.00007FF8E59746CB von binaryninjacore.00007FF8E597B7E4
0000001EFDBFF8D8 00007FF8E5858B61 00007FF8E59746CB zurück zu binaryninjacore.00007FF8E5858B61 von binaryninjacore.00007FF8E59746CB
0000001EFDBFFB08 00007FF8E5852685 00007FF8E5858B61 zurück zu binaryninjacore.00007FF8E5852685 von binaryninjacore.00007FF8E5858B61
0000001EFDBFFC38 00007FF8E58B3BDE 00007FF8E5852685 zurück zu binaryninjacore.00007FF8E58B3BDE von binaryninjacore.00007FF8E5852685
0000001EFDBFFCB8 00007FF8E5831041 00007FF8E58B3BDE zurück zu binaryninjacore.00007FF8E5831041 von binaryninjacore.00007FF8E58B3BDE
0000001EFDBFFD78 00007FF8E5832287 00007FF8E5831041 zurück zu binaryninjacore.00007FF8E5832287 von binaryninjacore.00007FF8E5831041
0000001EFDBFFDB8 00007FF8E580CF29 00007FF8E5832287 zurück zu binaryninjacore.00007FF8E580CF29 von binaryninjacore.00007FF8E5832287
0000001EFDBFFDE8 00007FF9072BCAB0 00007FF8E580CF29 zurück zu ucrtbase.00007FF9072BCAB0 von binaryninjacore.00007FF8E580CF29
0000001EFDBFFE18 00007FF908598364 00007FF9072BCAB0 zurück zu kernel32.00007FF908598364 von ucrtbase.00007FF9072BCAB0
0000001EFDBFFE48 00007FF90A4A70D1 00007FF908598364 zurück zu ntdll.00007FF90A4A70D1 von kernel32.00007FF908598364
0000001EFDBFFE98 0000000000000000 00007FF90A4A70D1 zurück zu 0000000000000000 von ntdll.00007FF90A4A70D1

**Comment by psifertex** [comment]
Can you please try again on the latest dev branch and report whether it still crashes?

**Comment by psifertex** [comment]
Also, was the PE file a .NET object file? I believe we've seen some crashes when loading those before.

**Comment by psifertex** [comment]
We've fixed a few bugs we suspect might have caused this. If you can please double check on the latest dev (Dev or stable BuildID greater than 770) and let me know if it's not fixed and re-open it I'd appreciate it. Thanks.
