### ISSUE TITLE
F2 highlight instruction

### ISSUE THREAD

**Issue by lucasduffey** [Vector35/binaryninja-api#652]
F2 in ida will highlight the instruction red and set a breakpoint. 

While breakpoints may not be added soon, the highlighting would make it easier to flag points of interest.

related: https://github.com/Vector35/binaryninja-api/issues/223 (Convert to Breakpoint API)

**Comment by psifertex** [comment]
#223 is about patching the Binary, not a debugging API. This is really just equivalent to the already existing keystroke refactor (#481) as once we allow arbitrary keystroke plugins it becomes trivial for someone to customize the keystroke to do any easy API call like this so I'm marking this as a dupe and closing.

**Comment by psifertex** [comment]
Tracking is now in #92 instead of 481.
