### ISSUE TITLE
MLIL doesn't respect function prototypes

### ISSUE THREAD

**Issue by withzombies** [Vector35/binaryninja-api#659]
Loading the binary bomb, I get the following two basic blocks:

MLIL
<img width="922" alt="screen shot 2017-04-22 at 10 10 06 am" src="https://cloud.githubusercontent.com/assets/4872355/25305137/e1515736-2743-11e7-8dd1-d29e07b6c1b5.png">

MLIL SSA
<img width="1191" alt="screen shot 2017-04-22 at 10 05 58 am" src="https://cloud.githubusercontent.com/assets/4872355/25305134/d4249dca-2743-11e7-8454-3166a50253ff.png">

Setting the function prototype on `initialize_bomb` should remove much of the function arguments but it does not
<img width="257" alt="screen shot 2017-04-22 at 10 10 27 am" src="https://cloud.githubusercontent.com/assets/4872355/25305146/fb961f28-2743-11e7-8de0-f446b9196b9e.png">

**Comment by plafosse** [comment]
This is due to lack of type propagation #121

**Comment by D0ntPanic** [comment]
Fixed in dev build 864
