### ISSUE TITLE
ELF core dumps

### ISSUE THREAD

**Issue by pgoodman** [Vector35/binaryninja-api#66]
Opening a core dump doesn't find anything.

**Comment by psifertex** [comment]
With the addition of linear sweep and some additional ELF support, core files now open properly and some functions are identified though there may be some specific features we could add in addition to that? Let me know if you have any other ideas, but closing for now without more specific guidance.

**Comment by pgoodman** [comment]
It would be nice if you considered things like relocations, or possibly even all data, to be read-only, that way you could do data flow across function pointers stored in memory.

**Comment by joshwatson** [comment]
You can declare them as const and it will follow the pointers

**Comment by psifertex** [comment]
I made #1302 to track that request -- it's a good idea to make that the default. If you've got any other suggestions, definitely happy to hear them.
