### ISSUE TITLE
ARM64 Unimplemented Instructions

### ISSUE THREAD

**Issue by withzombies** [Vector35/binaryninja-api#661]
In a single function for the Nintendo Switch, the following instructions are unimplemented: `movk`, `shmulh`, `ldaxr`, `stlxr`, `madd`, `ccmp`, `cinc`

`movk` is used quite a bit across the library.

**Comment by plafosse** [comment]
`shmulh` isn't an instruction, typo?

**Comment by withzombies** [comment]
Yeah I don't know. I can't find the example function again.

**Comment by plafosse** [comment]
Duplicate of #210
