### ISSUE TITLE
Use subscript for numbering variables in SSA form

### ISSUE THREAD

**Issue by pgoodman** [Vector35/binaryninja-api#662]
Right now things are like `var_20#8 = eax#0`. I think It would look better if the `#8` was instead of subscript `8`.

**Comment by D0ntPanic** [comment]
This is not possible with the current rendering code (using unicode subscripts actually look worse and cause a different bug). This would only be possible in the 1.2 UI refactor.

**Comment by psifertex** [comment]
Might or might not make the cut for #803

**Comment by psifertex** [comment]
For context, we decided to close this as testing with monospaced fonts showed subscripts didn't work well and additionally it actually makes the names harder to work with for example when copying/pasting. Given that, and the fact that SSA is not really intended to be human-visible as a first class property we have no plans to implement this.
