### ISSUE TITLE
give more diagnostics info when plugin fails to load

### ISSUE THREAD

**Issue by 6tudent** [Vector35/binaryninja-api#664]
binaryninja-radare2 doesn't load on windows but works fine on linux. the Log pane contains just two lines:
```
CorePluginInit()
Python plugin 'binaryninja_radare2' could not be loaded
```
I get the same output if I run the application as `binaryninja.exe -d -l logfile.txt`.
This is in version 1.0.13 personal (build id 76713379) on Windows 10.

**Comment by joshwatson** [comment]
You should talk to the author of that plugin then. Vector35 doesn't support third party scripts

**Comment by psifertex** [comment]
It is surprising we're not giving more feedback on the error though. We had an old bug where that was the case but I thought that was fixed. Might need to make sure it didn't regress on windows.

**Comment by 6tudent** [comment]
The issue with the plugin was that the package r2pipe was not available because Binary Ninja on Windows carries a hosted Python runtime, whereas on Linux it uses the available Python instance.

Installing Python packages in Binary Ninja on Windows is possible, as described in https://blog.kchung.co/binary-ninja-ipython-and-the-python-console/ except that permissions would be for "Users". This is a half-baked solution though because some packages require Python development headers.

Returning to the original problem, Binary Ninja should probably display some diagnostics as to why a plugin failed to load -- preferably without using the `-d` option. Thanks!

**Comment by lucasduffey** [comment]
relevant plugin: https://github.com/Manouchehri/binaryninja-radare2

**Comment by 6tudent** [comment]
changed this ticket's title as suggested -- thanks Lucas!

**Comment by plafosse** [comment]
Fixed in dev
