### ISSUE TITLE
Expose font size preference for UI widget fonts

### ISSUE THREAD

**Issue by richinseattle** [Vector35/binaryninja-api#667]
The font for UI widgets like the tab labels are too large on windows when hidpi scaling is at 200%. `
Users should be able to change this font in addition to the currently available option.

![binja_labels](https://cloud.githubusercontent.com/assets/1887673/25408592/4066fa86-29d4-11e7-8673-27ade219d612.png)

**Comment by psifertex** [comment]
Potential feature for #803

**Comment by plafosse** [comment]
This was fixed in 2.4 stable
