### ISSUE TITLE
keyboard navigation improvement (press enter selecting cross-reference should jump to that location)

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#67]
See subject.

**Comment by rlc4** [comment]
Some suggestions for keyboard shortcuts:

arrow-up - up one line of asm
arrow-down - down one line of asm
cmd/meta-arrow-up - to calling function (assuming only one available)
cmd/meta-arrow-down - follow currently selected jmp / call 
n - name selected symbol / address / function
N - name/rename current function
cmd/meta +/- - Zoom view


Commands already found:
H - view in Hex Editor
; - add comment / note
N - rename symbol (function)  (I suggest limiting this to function naming / renaming, use lower n for a general renaming, or the other way around if people have already started using N as rename of currently selected item)
P - create function at symbol

**Comment by D0ntPanic** [comment]
Fixed in dev
