### ISSUE TITLE
Function.set_user_stack_variable

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#671]
Add a convenience function for `BNCreateUserStackVariable`

Preferably something like:
```python
def set_user_stack_variable(self, variable):
    # variable is a function.Variable object
    core.BNCreateUserStackVariable(self.handle, variable.offset, variable.type.handle, variable.name)
```

Note that on dev, `variable.offset` would need to be `variable.storage`.

**Comment by D0ntPanic** [comment]
This already exists in dev, see `create_user_var` and `create_user_stack_var` in the `Function` object.
