### ISSUE TITLE
Constants shown as offset into ELF headers

### ISSUE THREAD

**Issue by Matir** [Vector35/binaryninja-api#675]
Constants are being shown as if they were addresses relative to the start of the binary.  This is a PIE binary on x86-64 (I suspect that's related).  I've attached the binary and a screenshot of what I'm seeing.

[floater.zip](https://github.com/Vector35/binaryninja-api/files/966460/floater.zip)
![elf_headers](https://cloud.githubusercontent.com/assets/808960/25559722/450e6b2c-2cf5-11e7-9e32-4b5e1db0f464.png)

**Comment by psifertex** [comment]
This is a duplicate bug though I don't have the other number offhand. This is only in dev and is the reason we haven't merged to stable. Type propagation will fix it up.

**Comment by joshwatson** [comment]
You can use [this function](https://api.binary.ninja/binaryninja.function-module.html#binaryninja.function.Function.set_int_display_type) to fix it in the disassembly view for the mean time.
