### ISSUE TITLE
x86 overflow flag support

### ISSUE THREAD

**Issue by withzombies** [Vector35/binaryninja-api#679]
It seems Binja doesn't support the x86 overflow flag. This makes analysis on any checked overflow language such as swift impossible.

<img width="644" alt="screen shot 2017-05-01 at 11 19 50 am" src="https://cloud.githubusercontent.com/assets/4872355/25583519/21671202-2e60-11e7-93ee-4f7bb775b1c8.png">

Example binary:
https://github.com/Vector35/binaryninja-api/files/968122/ffd32615055580ceefda1df0fd92d59add984bd7ffc9fee422c3c9e07bdacf60.gz

**Comment by D0ntPanic** [comment]
Fixed in dev
