### ISSUE TITLE
Return Failure for get*function_start_*

### ISSUE THREAD

**Issue by hjlbs** [Vector35/binaryninja-api#680]
bv.get_next_function_start_after(addr) returns the final address of the binary if no additional functions are found. It would be preferable to return -1, None, or some similar error indication that no further functions exist.

The same is true for bv.get_previous_function_start_before(addr) though it returns the starting address of the binary as opposed to the ending.

**Comment by joshwatson** [comment]
```python
if bv.get_next_function_start_after(addr) == bv.end:
    log_info("No more functions")
```

**Comment by hjlbs** [comment]
yeah I just found that. I came back to delete my issue.
