### ISSUE TITLE
Jumptable resolution fails when bounded through stack variable.

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#681]
https://pwnable.tw/static/chall/digimon.tar.gz

0x3adf
<img width="1285" alt="screen shot 2017-05-05 at 12 51 15 pm" src="https://cloud.githubusercontent.com/assets/10556585/25755617/aded6a44-3191-11e7-9610-76ad97597419.png">

**Comment by D0ntPanic** [comment]
Fixed in dev
