### ISSUE TITLE
MLIL view does not show called API names in PE

### ISSUE THREAD

**Issue by polsab** [Vector35/binaryninja-api#682]
In LLIL view:
![screen shot 2017-05-06 at 6 32 01 am](https://cloud.githubusercontent.com/assets/868708/25766627/236bb19c-3226-11e7-8945-e4edbee10906.png)
In MLIL view
![screen shot 2017-05-06 at 6 31 32 am](https://cloud.githubusercontent.com/assets/868708/25766630/26586828-3226-11e7-8586-53185693fc00.png)

**Comment by D0ntPanic** [comment]
Fixed in dev
