### ISSUE TITLE
Function prototype display does not update when changing function type

### ISSUE THREAD

**Issue by polsab** [Vector35/binaryninja-api#683]
Just a minor UI issue. When changing a function's type, the function prototype display in the upper left does not reflect the change immediately. You have to switch IL views or visit another function for it to update.

**Comment by psifertex** [comment]
This sounds familiar, think it's a dupe but on my phone and search stinks. Will double check later.

**Comment by plafosse** [comment]
Fixed as of dev build 869

**Comment by bmuessig** [comment]
This keeps happening again in 1.1.1689. I remember it working correctly in 1555.

**Comment by bpotchik** [comment]
Fixed in 1.1.1742-dev.
