### ISSUE TITLE
String dereference in jump instructions when the first bytes in the dst block is ASCII

### ISSUE THREAD

**Issue by polsab** [Vector35/binaryninja-api#684]
Similar to https://github.com/Vector35/binaryninja-api/issues/496 but for jump instructions.

![screen shot 2017-05-06 at 7 04 55 am](https://cloud.githubusercontent.com/assets/868708/25767266/60132f90-322a-11e7-9d4d-e9cf6f15291d.png)

Let me know if you need the sample.

**Comment by plafosse** [comment]
I believe this issue was fixed prior to the recent stable push.
