### ISSUE TITLE
show_message_box() buttons keyword does not act as expected

### ISSUE THREAD

**Issue by bambu** [Vector35/binaryninja-api#687]
Prototype for `show_message_box()` is:
```python
show_message_box(title, text, buttons=MessageBoxButtonResult.OKButton, icon=MessageBoxIcon.InformationIcon):
```
This reads that by default only an OK button should display. Calling: `show_message_box('','')` displays a popup with a Cancel/No/Yes. 

Likewise: 
`show_message_box('', '', buttons=MessageBoxButtonResult.CancelButton)` shows "Ok"
`show_message_box('', '', buttons=MessageBoxButtonResult.NoButton)` shows "Ok"
`show_message_box('', '', buttons=MessageBoxButtonResult.YesButton)` shows "No" "Yes"
`show_message_box('', '', buttons=MessageBoxButtonResult.OKButton)` shows "Cancel" "No" "Yes"

**Comment by plafosse** [comment]
The default value is actually incorrect should be `MessageBoxButtonSet.OKButtonSet`.

**Comment by psifertex** [comment]
Sorry about that, the autogenerated documentation and the default value is incorrect. Updating the docs to include the proper references, in the meantime if you need to work around, just use [MessageBoxButtonSet](https://api.binary.ninja/binaryninja.enums.MessageBoxButtonSet.html?highlight=buttonset#binaryninja.enums.MessageBoxButtonSet) instead.

**Comment by psifertex** [comment]
Whoops, didn't see peter's comment. At least I added a link. :-P

**Comment by psifertex** [comment]
fixed on dev
