### ISSUE TITLE
modifications to raw data while in IL views cause a crash

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#688]
Modifications of raw contents (via `cut`, `paste`, `assemble`, `compile`, or any `transform` menus) while in either LLIL, LLIL SSA, MLIL, or MLIL SSA  cause Binary Ninja to crash.

If the change itself doesn't trigger an immediate crash (it's not perfectly reliable), an `undo` will usually trigger it immediately afterward.

**Comment by plafosse** [comment]
I believe this issue is fixed.
