### ISSUE TITLE
Make rendering of MLIL ITE configurable

### ISSUE THREAD

**Issue by richinseattle** [Vector35/binaryninja-api#689]
MLIL renders branches as if .. then .. else clauses, I would like a configuration preference to render them vertically as well as the current horizontal layout. 
```
if (reg.reg != 0) then 10 @0xaddress1 else 12 @0xaddress2
```
would become:
```
if (reg.reg != 0) then 
   10 @0xaddress1 
else 
   12 @0xaddress2
```
This is helpful when trying to view two paths in parallel by narrowing the blocks and making it easier to view side-by-side. As a side effect it also makes call instructions stand out as the commonly seen longer expression in blocks.

**Comment by plafosse** [comment]
This is now done in HLIL.
