### ISSUE TITLE
Refactor Functions List

### ISSUE THREAD

**Issue by struct** [Vector35/binaryninja-api#69]
The symbol view on the left hand side should be sortable by alphabetical order. It would also be nice to get a column view of what type of symbol it is.

**Comment by psifertex** [comment]
This is part of the overhaul of that entire part of the UI that's coming in 1.2. There another issue that describes it as well I think, but appreciate the suggestion.

**Comment by plafosse** [comment]
This will enable viewing import, exports and sorting.

**Comment by plafosse** [comment]
Also FWIW you *can* see imports and exports in the triage view.

**Comment by plafosse** [comment]
Version 1.1.1772 converts the "Functions" list to a "Symbols" list with the ability to toggle the visibility of "Imports", "Exports", "Data Variables" and "Functions". The list can also be sorted by address and by name.  A forth coming feature, the SymbolDetailsView will show lots of verbose information like function sizes, start address, symbol type, and more.
