### ISSUE TITLE
Documentation on install api in Linux and Mac

### ISSUE THREAD

**Issue by securisec** [Vector35/binaryninja-api#690]
Would you happen to have any documentation on how to install the binja python api for mac and linux?

Thanks!

**Comment by withzombies** [comment]
The best approach is to add a `binaryninja.pth` file to your python site packages with the path to your binaryninja install's python folder.

I wrote [this](https://gist.github.com/withzombies/c9ab65b878d05fa20878d6c2bfa935d9) a while ago which does this.

**Comment by securisec** [comment]
thanks @withzombies ! worked like a charm!

**Comment by psifertex** [comment]
The more flexible way is using the .last_run or whatever I called it in the user folder (same place as the license: https://docs.binary.ninja/getting-started/#license). That is better for locations like Linux where the install path isn't fixed. I need to add that to the docs.

**Comment by psifertex** [comment]
This is now resolved via the [install_api.py](https://github.com/Vector35/binaryninja-api/blob/dev/scripts/install_api.py) script included with all builds.
