### ISSUE TITLE
Drag/drop

### ISSUE THREAD

**Issue by ecx86** [Vector35/binaryninja-api#698]
It would be nice to be able to drag/drop files into Binary Ninja like in IDA Pro.

**Comment by plafosse** [comment]
We do support drag and drop. What platform/version are you seeing an issue with?

**Comment by plafosse** [comment]
I'm going to close this issue. I you are unable to get Drag/drop still please provide more details. OS version product version etc.

**Comment by ecx86** [comment]
Nevermind. It seems to be an issue with UAC: the updater went through the UAC prompt and drag/drop would stop working when launched after an update.
