### ISSUE TITLE
Bogus xref in chromium function

### ISSUE THREAD

**Issue by nshp** [Vector35/binaryninja-api#702]
Here's a bndb: http://cyberjes.us/chromium-buggy.bndb

At 0x205ca10, there are two xrefs from 0x4b9d151, both in different functions. One of them does not actually exist. Curiously, the fake xref disappears if I give the function at 0x205ca10 a name.

This is in the dev version.

**Comment by nshp** [comment]
I saw the same issue in a linux kernel image. This time I was watching the function in assembly graph view as analysis ran. At first the code looked right - there were two edges into this basic block and two xrefs listed. At one point the entire graph suddenly changed, removing one of the basic blocks with an edge into this one without removing the corresponding xref.

The kernel ELF is here: http://cyberjes.us/vmlinux
The basic block in question is 0xffffffff81053473. I'm fairly sure the first (early-analysis) view of this function is correct, and the change is incorrect.

**Comment by plafosse** [comment]
Thanks for the report I've verified that this is an issue. Likely an analysis issue and possibly also a UI issue where the xref list isn't being updated when the analysis corrects itself.

**Comment by psifertex** [comment]
The second issue isn't actually a problem. The analysis is marking one of the paths above the basic block as a `no_return` and correctly removing the xref which is what it should be doing.

Additionally, we've made a few other changes to xrefs that we believe have fixed the first situation. If I open the original chromium binary and let analysis complete, I only see one xref from 0x4b9d151 to 0x205ca10. 

Given that I'm going to close this out, but please let me know if you have any newer examples.
