### ISSUE TITLE
IL Pointers don't show as such in assembly view

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#703]
The IL sees pointers but doesn't display them as such in the assembly view:

![screen shot 2017-05-26 at 11 13 54 am](https://cloud.githubusercontent.com/assets/10556585/26531643/e3d5328c-43ba-11e7-8282-b13049701225.png)
![screen shot 2017-05-26 at 11 13 48 am](https://cloud.githubusercontent.com/assets/10556585/26531644/e50029f0-43ba-11e7-819e-31129ce2a5db.png)

**Comment by D0ntPanic** [comment]
Fixed in dev, build 764
