### ISSUE TITLE
InstructionBranch __repr__ method broken

### ISSUE THREAD

**Issue by adamcritchley** [Vector35/binaryninja-api#704]
The branch type is supplied to InstructionBranch as a name, however the repr method tries to use it as an object while accessing the **name** member.

Repr with issue... function.py @ line 1328

```
	def __repr__(self):
		branch_type = self.type
		if self.arch is not None:
			return "<%s: %s@%#x>" % (branch_type.name, self.arch.name, self.target)
		return "<%s: %#x>" % (branch_type, self.target)
```

Proposed fix...
```
	def __repr__(self):
		branch_type = self.type
		if self.arch is not None:
			return "<%s: %s@%#x>" % (branch_type, self.arch.name, self.target)
		return "<%s: %#x>" % (branch_type, self.target)
```

**Comment by joshwatson** [comment]
I think the problem actually stems from the `InstructionBranch` object being initialized incorrectly. `branch_type` should be a `BranchType` enum, which does have a `.name` property. The second string formatting should actually be fixed to use `branch_type.name` as well

What architecture is this on?

**Comment by adamcritchley** [comment]
This is with all architectures. You can see the branch_type being assigned
as a string on line 1131 in architecture.py.  I'm including a snippet
below...

for i in xrange(0, info.branchCount):
branch_type = BranchType(info.branchType[i]).name <---- Problem?
target = info.branchTarget[i]
if info.branchArch[i]:
arch = Architecture(info.branchArch[i])
else:
arch = None
result.add_branch(branch_type, target, arch)

That's a better idea to have it be an enum.  So in that case, that line
probably needs to have the ".name" removed.

**Comment by plafosse** [comment]
This was fixed a while ago: https://github.com/Vector35/binaryninja-api/commit/36525b7ee9a8ee3eb95a8ba5ec490c05874bde8d
