### ISSUE TITLE
Edge-crossings and routings

### ISSUE THREAD

**Issue by endeav0r** [Vector35/binaryninja-api#706]
The graph layout could use some work to ease readability. A heuristic to reduce edge-crossings would be appreciated, as well as balancing the layouts of nodes, and making sure edges don't jut/bounce wildly to the sides.

**Comment by plafosse** [comment]
We agree and have a plan for it as part of 1.2  We're using #58 as a tracker for refactoring the entire edge routing algorithm.

**Comment by endeav0r** [comment]
Just came back to check on this, thanks.
