### ISSUE TITLE
N00b - Help changing python interpreter for binja

### ISSUE THREAD

**Issue by securisec** [Vector35/binaryninja-api#711]
Hi, hoping you guys can give me a hand. I am trying to change the default python that binja uses to one that i primarily use (brew installed). My brew installed python 2.7.13 is in my path, but binja loads python 2.7 from the default Mac install. 

I am trying to accomplish this on a mac. 

Thanks!

**Comment by joshwatson** [comment]
Use `virtualenv` and run Binary Ninja from it by invoking `/Applications/Binary Ninja.app/Contents/MacOS/binaryninja`

**Comment by securisec** [comment]
Thanks @joshwatson ! Although that works well, i am getting too many import issues while trying to use r2pipe. Thats why I am hoping to link it to the brew installed python

**Comment by joshwatson** [comment]
You just need to install the imported modules in the virtualenv as well.

**Comment by securisec** [comment]
Yes, I realize that, and i am using the pip for virtualenv to install r2pipe, and making sure the sitepackages are correct also, but when trying to import r2pipe either via the radare plugin, i am getting all sorts of standard library import errors including urllib2, httplib, mimetools etc

**Comment by securisec** [comment]
Hence I will go back to the original question. Is there a way to change the interpreter that Binja is using? Specially for commercial licenses?

**Comment by securisec** [comment]
and if not, may i make this a feature request?

**Comment by psifertex** [comment]
There is not a way to specify it currently within the UI. We're currently working on a preferences system that would make it much easier to do this. 

Blocking on #126

**Comment by psifertex** [comment]
Note that for headless you can of course use whatever Python you like.

**Comment by securisec** [comment]
Thanks psifertex. I really do enjoy the headless capability of binja. You guys are doing awesome work. Just some things need a little tweaking. The plugins I find are a huge part of binja, but not being able to use them in a stable standard manner is a bit of a pain. All cool in Ubuntu, but not all cool in Mac.
