### ISSUE TITLE
Error when installing pip package from console

### ISSUE THREAD

**Issue by Herz3h** [Vector35/binaryninja-api#712]
Hello,

Trying to install nampa plugin for flirt support.

https://pastebin.com/DQ1DXcsg

Environment: 
Binja: Version 1.0.766-dev Personal (2017-06-15 00:11:10)
Windows 8.1 64 bits

**Comment by psifertex** [comment]
Note that this doesn't completely fix it as you'll likely run into bugs about running on a background thread. Easiest fix is to add `--quiet` to the list of arguments to pip, though [execute on main thread](https://api.binary.ninja/binaryninja.mainthread.execute_on_main_thread.html?highlight=thread#binaryninja-mainthread-execute-on-main-thread) might do it as well, but I haven't tested.

**Comment by psifertex** [comment]
Now that we support using external libraries it's recommended not to solely rely on the internal but rather use a system install which makes this process much easier. https://docs.binary.ninja/getting-started.html#python.interpreter
