### ISSUE TITLE
Check update channel on install

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#714]
If someone updates from personal to commercial, the update channel stored in preferences does not update to reflect the new version. It's a simple fix for the user to go into preferences and change it, but users might not realize that when they see the error message.

I propose that when running the binja installer, it should check for cached preferences and identify if the current update channel matches the edition to be installed. If there is a conflict, it should update the channel to match the newly installed edition.

**Comment by plafosse** [comment]
This will be fixed by the new settings system. #126

**Comment by xusheng6** [comment]
I think this is fixed a while ago
