### ISSUE TITLE
binaryninja.exe: 0xC0000095: Integer overflow. occurred

### ISSUE THREAD

**Issue by RkPx** [Vector35/binaryninja-api#719]
I'm opening a 64 bit PE with binaryninja.exe version 1.0.13 Personal, BuildID 76713379 on Windows 10.

Attaching the debugger I see this:

Unhandled exception at 0x00007FFD7EB28917 (binaryninjacore.dll) in binaryninja.exe: 0xC0000095: Integer overflow. occurred

RAX = 8000000000000000 RBX = 000000052CEFEF40 RCX = 7FFFFFFFFFFFFFFF RDX = FFFFFFFFFFFFFFFF RSI = 000000052CEFD430 RDI = 00000189059CA4D0 R8  = FFFFFFFFFFFFFFFF R9  = 00000189059770B0 R10 = 0000018905972830 R11 = 0000000000000000 R12 = 0000000000000001 R13 = 0000000000000000 R14 = 0000000000000000 R15 = FFFFFFFFFFFFFFFF RIP = 00007FFD7EB28917 RSP = 000000052CEFA9C0 RBP = 000000052CEFAAC0 EFL = 00010284 

It looks like a similar issue to this: https://github.com/Vector35/binaryninja-api/issues/650 , but that issue was closed.

Call stack:

>	binaryninjacore.dll!00007ffd7eb48917()	Unknown
 	binaryninjacore.dll!00007ffd7eb453b4()	Unknown
 	binaryninjacore.dll!00007ffd7eb3e28b()	Unknown
 	binaryninjacore.dll!00007ffd7ea26fa1()	Unknown
 	binaryninjacore.dll!00007ffd7ea20ac5()	Unknown
 	binaryninjacore.dll!00007ffd7ea7e8ce()	Unknown
 	binaryninjacore.dll!00007ffd7ea004e1()	Unknown
 	binaryninjacore.dll!00007ffd7ea00fa7()	Unknown
 	binaryninjacore.dll!00007ffd7e9dc769()	Unknown
 	[External Code]

**Comment by RkPx** [comment]
Fortunately it **does not** happen in  1.0.777-dev Personal (Build ID f59ec886) by switching to the dev channel Preferences > Update Channel : Binary Ninja Personal Development 👍

**Comment by psifertex** [comment]
Yeah, the dataflow in particular has had a lot of fixups.

**Comment by psifertex** [comment]
Or rather it's been totally rewritten and a number of known crashes fixed.
