### ISSUE TITLE
Need improved error messages when "copy-as" fails

### ISSUE THREAD

**Issue by scottcohen** [Vector35/binaryninja-api#720]
It would be a tiny bit more convenient if it were to automatically pad with null bytes, or nop instructions.  The same behavior occurs with 16 and 64 bit arrays as well.

**Comment by plafosse** [comment]
I think failing is actually preferred to padding out.  Adding in null bytes to your selection breaks the concept of least surprise. Rather I'd say that we just need better error messages than "The requested transformation failed.". I'm going to mark this as a UI issue instead.

**Comment by Manouchehri** [comment]
Adding a preference in the UI for enabling padding instead of failing would be ideal if possible.

**Comment by plafosse** [comment]
Brian had a good suggestion, instead of padding out with null bytes instead pad out with non-hex characters so if you select one byte and copy as C array. You'd get the following output

uint32_t x[1] = {0x41XXXXXX}

**Comment by psifertex** [comment]
Better error messages used in builds >= 4469
