### ISSUE TITLE
Bug when using python API

### ISSUE THREAD

**Issue by RhythmParadox** [Vector35/binaryninja-api#722]
On the newest build, W10, attempting to execute this python script here on a small binary gives me an invalid syntax error after the loop

https://gist.github.com/RhythmParadox/d44d4f97a36f51df25838cda88545536

Originally tested with f = open( etc. etc. ), an invalid syntax error is shown after the f.
I've tested (similar) code in my python terminal and it works perfectly fine, so i'm very uncertain of whats happening here.

This code is being directly executed in the python script window via copy+paste, not sure if theres a better way to do it?

Here's an example output from one of the versions: http://i.imgur.com/wSs3gWl.png

**Comment by RhythmParadox** [comment]
Followup: This strange behaviour happens when i attempt to declare variables.
For example, this code:

```Python
out_data = []
for i in xrange(len(xor_data)):
	print "Hello lol"
	dat = xor_data[i]
	if ( i % 2 == 0):
		dat = dat ^ 69
	else:
		dat = dat ^ 92

	out_data.append( dat )
	print dat
```

xor_data is already filled via the command line, however we dont even reach the hello.
Likewise if you move out_data to underneath the loop like so


```Python
for i in xrange(len(xor_data)):
	print "Hello lol"
	dat = xor_data[i]
	if ( i % 2 == 0):
		dat = dat ^ 69
	else:
		dat = dat ^ 92

	out_data.append( dat )
	print dat

out_data = []
```

Now you get an invalid syntax error on out_data

**Comment by joshwatson** [comment]
If you're pasting all of it in, the console only executes the first expression

**Comment by psifertex** [comment]
What do you mean when you say xor_data comes from the command line? Are you running in the console of the GUI or a headless version?

**Comment by RhythmParadox** [comment]
Hey, thanks for the response, but if i remove all references to "out_data" everything runs fine

**Comment by RhythmParadox** [comment]
xor_data was set via the console in the gui, simply xor_data = [ ran, dom, num, bers ]

**Comment by psifertex** [comment]
I didn't see out_data created anywhere in the second snippet which would explain that error. 

So it sounds like you're all set now? If so, please close out the issue. I

Thanks.

**Comment by psifertex** [comment]
That is, the second snippet in the earlier comment. Not where it's removed entirely.

**Comment by RhythmParadox** [comment]
No, the error still persists.

How i wanted to use this script was to have it decode some bytes and spit it out into a file for me. 
This is how it was in practice, same conceptual error

```Python
xor_data = []
for i in xrange( bv.end ):
    dat = ord(bv.read(i, 1))
    if( i % 2 == 0 ):
    #even
        dat = dat ^ 0x13
    else:
        dat = dat ^ 0x37
    
    #print dat
    xor_data.append( dat )
    
f = open("xor_test.bin", "w")
f.write( xor_data, len(xor_data))
f.close()
```

With this script, i get a syntax error on "F" in "f = open(etc)" , so its the same error, i had just simplified it a bit.

**Comment by joshwatson** [comment]
If you pasting that entire block into the console, it's not going to work.

**Comment by RhythmParadox** [comment]
I guess i should've mentioned ive done something very similar ( different xor keys, made ~255 files 1 for each xor key ) last update, and it worked perfectly fine.

But things change i guess. I'll just use execfile. Cheers guys.

**Comment by psifertex** [comment]
Ahh, that's right. Thanks Josh. Pasting blocks with indentation doesn't work. 

Convert it to a script that you import and run functions from it. You can use `reload(moduleName)` to test/change on the fly as long as you don't use the `register` family of functions from the API.
