### ISSUE TITLE
BNGetFileForView crashes with an invalid filename

### ISSUE THREAD

**Issue by robert-yates** [Vector35/binaryninja-api#723]
`auto bd = BinaryData(new FileMetadata(), "blah");`

Program received signal SIGSEGV, Segmentation fault.
0x00007ffffd904ac1 in BNGetFileForView () from /home/dev/binaryninja/libbinaryninjacore.so.1

**Comment by psifertex** [comment]
Pretty sure there's a known bug for this already. 

As the doctor told the patient who kept hurting himself: stop doing that. :-)

Seriously, we'll eventually clean these sorts of issues up, but it's kinda a low priority.
