### ISSUE TITLE
BNAddAutoSegment Behaves Oddly on When Called Repeatedly With Non-Sequential Addresses

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#727]
If you place the [`python/examples/nes.py`](https://github.com/Vector35/binaryninja-api/blob/e5be1fc1b4f36a62226e00fa03a2726779026a3b/python/examples/nes.py) file in your `plugins` folder and open the [Pwn Adventure Z ROM](https://github.com/Vector35/PwnAdventureZ/blob/master/PwnAdventureZ-csaw-withkeys.nes), it should disassemble nicely. At the top of the linear view, Binary Ninja happily reports that the following segments have been created as expected:

```
Segments:
rwx 0x00000000-0x00008000
r-x 0x00008000-0x0000c000
r-x 0x0000c000-0x00010000
```

If you then close Binary Ninja, swap lines 556-557 and 558-559 so they look like this instead (where the *higher* segment is mapped in *first*):

```python
self.add_auto_segment(0xc000, 0x4000, self.rom_offset + self.rom_length - 0x4000, 0x4000,
    SegmentFlag.SegmentReadable | SegmentFlag.SegmentExecutable)
self.add_auto_segment(0x8000, 0x4000, self.rom_offset + (self.__class__.bank * 0x4000), 0x4000,
    SegmentFlag.SegmentReadable | SegmentFlag.SegmentExecutable)
```

...and re-open the Pwn Adventure Z ROM, you should see completely incorrect disassembly and the following segments reported at the top of linear view:

```
Segments:
rwx 0x00000000-0x00008000
r-x 0x00008000-0x0000c000
r-x 0x0000c000-0x00014000
```

I have a modified version of `nes.py` that I would like to provide in a pull request, but I can no longer get it to function properly. I *thought* this was due to my own poor programming. After isolating the behavior the aforementioned 4-line change on a completely clean install on a completely clean VM, I believe it might perhaps be a Binary Ninja core bug in `BNAddAutoSegment` (which `BinaryView.add_auto_segment` wraps) instead.

If you would like anything else from me to help understand this behavior, please don't hesitate to ask.

**Comment by plafosse** [comment]
Thank you for the detailed report. This issue is fixed in build >= 815
