### ISSUE TITLE
On Fedora 25 libcurl requires version informations

### ISSUE THREAD

**Issue by Flukas88** [Vector35/binaryninja-api#731]
> /opt/binaryninja/binaryninja: /lib64/libcurl.so.4: no version information available (required by /opt/binaryninja/libbinaryninjacore.so.1)

The default libcurl is 

> Package libcurl-devel-7.51.0-7.fc25.x86_64

**Comment by joshwatson** [comment]
#155 might help you figure this out

**Comment by psifertex** [comment]
Also, https://docs.binary.ninja/guide/troubleshooting/#linux tracks all the known solutions for different linux variants. If you find a different one for fedora, please let us know. 

However, as Fedora is not a supported platform so I'm going to close this for now. 

Note that long term we do plan to fix all the curl/openssl issues with static compiles which will help with a lot of the non-ubuntu compatibility, but no ETA on that fix.
