### ISSUE TITLE
Documentation: wrong return type for perform_get_instruction_low_level_il

### ISSUE THREAD

**Issue by tharina** [Vector35/binaryninja-api#733]
It seems like the function  [perform_get_instruction_low_level_il](https://api.binary.ninja/binaryninja.architecture-module.html#binaryninja.architecture.Architecture.perform_get_instruction_low_level_il) should return an int containing the length of the instruction, not None as is stated in the documentation.

**Comment by plafosse** [comment]
Thanks, fixed in latest dev api, and will be fixed with the next dev update.
