### ISSUE TITLE
Scan Additional BinaryView Sections and Create Well Known Types

### ISSUE THREAD

**Issue by bpotchik** [Vector35/binaryninja-api#745]
For example, types are not created in data sections with well known formats. (e.g. ELF sections .init_array and .fini_array)

- [x] ELF
- [x] Mach-O
- [x] PE

**Comment by bpotchik** [comment]
ELF: Build 1.1.948 - Updated elfview to create auto functions for .init/.fini/.init_array/.fini_array/.ctors/.dtors.

**Comment by psifertex** [comment]
While the auto_functions are created, need to create pointers in those sections as well. for ELF

**Comment by bpotchik** [comment]
Finally added headers and some load command types for Mach-O files.

Fixed in 2.1.2319-dev.
