### ISSUE TITLE
MLIL eliminating stack variable assignments

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#747]
Disassembly:
![screen shot 2017-07-22 at 10 28 58 pm](https://user-images.githubusercontent.com/5834130/28495994-63a7f9ca-6f2d-11e7-9e4d-5207784910a4.png)
LLIL:
![screen shot 2017-07-22 at 10 29 07 pm](https://user-images.githubusercontent.com/5834130/28495996-64aef6d4-6f2d-11e7-9868-606d9a82f50b.png)
MLIL:
![screen shot 2017-07-22 at 10 29 14 pm](https://user-images.githubusercontent.com/5834130/28495997-66b1ecb6-6f2d-11e7-83eb-3a0d6a6613c5.png)
Mapped MLIL:
![screen shot 2017-07-22 at 10 29 56 pm](https://user-images.githubusercontent.com/5834130/28495998-67e0a302-6f2d-11e7-998f-84acd8033062.png)

**Comment by joshwatson** [comment]
File is some random crackme I found somewhere once. Here's the sample.
[Crackme.zip](https://github.com/Vector35/binaryninja-api/files/1167815/Crackme.zip)

**Comment by joshwatson** [comment]
heh, totally hit "close and comment" my bad

**Comment by psifertex** [comment]
Fixed some time ago, sorry for not closing.
