### ISSUE TITLE
Need option to show spaces between opcode bytes

### ISSUE THREAD

**Issue by bdarmofal** [Vector35/binaryninja-api#751]
Please add option to show spaces between opcode bytes.
Placing it in the Options popup submenu is fine.

Needed in both call graph and linear disassembly views.

Binary Ninja Version: 1.0.776, 6573250f
Platform: Windows 10

**Comment by plafosse** [comment]
We don't plan on adding this feature.

**Comment by psifertex** [comment]
Just chiming in to add that it is possible to do this via a custom view if it's important.
