### ISSUE TITLE
Propagate __noreturn from tail called functions

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#759]
Seems like we aren't currently propagating __noreturn status from tail callee to tail caller.

<img width="905" alt="screen shot 2017-08-07 at 3 50 12 pm" src="https://user-images.githubusercontent.com/10556585/29043277-7c0d5728-7b88-11e7-8a93-ece8ac541438.png">

**Comment by bpotchik** [comment]
Fixed in build 1.1.1183-dev.
