### ISSUE TITLE
vmlinuz are detected as PE

### ISSUE THREAD

**Issue by crowell** [Vector35/binaryninja-api#76]
```
minishwoods /tmp » file vmlinuz-4.2.0-22-generic 
vmlinuz-4.2.0-22-generic: Linux kernel x86 boot executable bzImage, version 4.2.0-22-generic (buildd@lcy01-22) #27-Ubuntu SMP Thu Dec 17 22, RO-rootFS, swap_dev 0x6, Normal VGA
```

and output from binja in console

```
Added x86_64 entry point at 0x4810
PE parsing took 0.000 seconds
Analysis update took 0.282 seconds
```

**Comment by D0ntPanic** [comment]
There really is a PE header there, and has valid startup code in it.  However, it should also detect the kernel image and disassemble that as well (the architecture allows for multiple executable images in the same file, so it should disassemble both).

**Comment by D0ntPanic** [comment]
IDA also detects the kernel as a PE, and gives no other options for disassembly. It looks to be an EFI compatible loader. EFI binaries are defined as PE.

**Comment by plafosse** [comment]
As vmlinuz images are indeed EFI images which are indeed PE images, I'm going to close this image. If you need to get at the underlying elf image you can extract with with https://blog.packagecloud.io/eng/2016/03/08/how-to-extract-and-disassmble-a-linux-kernel-image-vmlinuz/ However Binary Ninja doesn't currently support Linux kernel images yet. See #63
