### ISSUE TITLE
Crash with PDB dialogue when loading wpnpinst.exe on Win10

### ISSUE THREAD

**Issue by olliencc** [Vector35/binaryninja-api#761]
Unhandled exception at 0x00007FFA61EF2208 (ucrtbase.dll) in binaryninja.exe: An invalid parameter was passed to a function that considers invalid parameters fatal.

Whilst it is doing its analysis I seem to reliably be able to get it to crash by navigating and clicking on Load PDB.

Weirdly the crash isn't caught when running as follows:

C:\Program Files\Vector35\BinaryNinja>.\binaryninja --debug --debug-log c:\Data\BinNinja3.log

[BinNinjaLogs.zip](https://github.com/Vector35/binaryninja-api/files/1211421/BinNinjaLogs.zip)

**Comment by plafosse** [comment]
Have you tried this in the latest development build? I just attempted and was unable to reproduce the issue. Also which ucrtbase.dll are you using the windows 10 one sys32, sysWow64, WinSxS? The GUID would be helpful too.

**Comment by plafosse** [comment]
Scratch that I've reproduced the issue in wpnpinst.exe but the issues only seems to be present on Windows.

**Comment by plafosse** [comment]
Issues fixed in dev 863
