### ISSUE TITLE
Patching dialog should show the highlighted instruction

### ISSUE THREAD

**Issue by pgoodman** [Vector35/binaryninja-api#762]
When you right click on an instruction and patch with assembler, the text box should be pre-filled with the instruction that is present at the patch point.

**Comment by psifertex** [comment]
I'm inclined to leave this behavior the way it is -- if you want to edit a single instruction you should use `e` which does maintain the current line. If you want to replace a chunk of code with a block of assembly, I like the current behavior where we default to the previous saved chunk of assembly. 

I guess it depends on whether it's more common to repeat a previous assembly or more common to want to append assembly after an existing instruction (though in that case, just start patching from the following instruction instead!)

**Comment by pgoodman** [comment]
Oh I didn't know about `e`!
