### ISSUE TITLE
Segfault when export_svg is present

### ISSUE THREAD

**Issue by walterschell** [Vector35/binaryninja-api#764]
This only segfaults if the export_svg.py is present.

walter@andromeda:~$ ls ~/.binaryninja/plugins/binaryninja-microcorruption  export_svg.pyc
export_svg.py                msp430

walter@andromeda:~$ ./binaryninja/binaryninja -de ctf/microco
/home/walter/.binaryninja/repositories/plugin_status.json doe when a plugin is enabled)
Traceback (most recent call last):
  File "/home/walter/.binaryninja/plugins/msp430/__init__.py"
    arch.register_calling_convention(DefaultCallingConvention
  File "/home/walter/binaryninja/plugins/../python/binaryninj, in __init__
    raise ValueError("Must specify either handle or architect
ValueError: Must specify either handle or architecture and na
Python plugin 'msp430' could not be loaded
Loaded Python plugin 'export_svg'
Loaded Python plugin 'binaryninja-microcorruption'
Segmentation fault (core dumped)

[dump.zip](https://github.com/Vector35/binaryninja-api/files/1219985/dump.zip)

**Comment by psifertex** [comment]
What version of Binary Ninja? (Using the "file a bug" choice from the help menu prepopulates this for you)

**Comment by walterschell** [comment]
Linux 1.0.853-dev Personal build 414c99f

**Comment by psifertex** [comment]
I've been unable to reproduce this bug, but it's quite likely the binaryninja-microcorruption plugin (which for a brief period of time was incompatible but I believe was fixed). Updating to the latest microcorruption and binaryninja should work fine now.
