### ISSUE TITLE
Python CallingConvention objects can't be registered

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#774]
Since (I believe) Version 1.0.864-dev, registering a user-defined `CallingConvention` class results in an exception being raised in _binaryninjacore.py.

```
  File "/Users/user/Library/Application Support/Binary Ninja/plugins/msp430/__init__.py", line 1089, in <module>
    arch.register_calling_convention(DefaultCallingConvention(arch, 'default'))
  File "/Users/user/Documents/Repos/binaryninja-dev/binaryninja-dev/lib/python2.7/site-packages/binaryninja/callingconvention.py", line 67, in __init__
    self._cb.getIncomingRegisterValue = self._cb.getIncomingRegisterValue.__class__(self._get_incoming_reg_value)
TypeError: invalid result type for callback function
```

**Comment by joshwatson** [comment]
It appears that the issue stems from `CallingConvention::GetIncomingRegisterValueCallback` and `CallingConvention::GetIncomingFlagValueCallback` return a `BNRegisterValue` struct, which is valid for C++ but not for C, so `ctypes` fails.

**Comment by plafosse** [comment]
Fixed in dev build 873
