### ISSUE TITLE
Incorrect disassembly of ELF 64 file

### ISSUE THREAD

**Issue by 0x6d636c61757373** [Vector35/binaryninja-api#776]
Binary Ninja Version: 1.0.776 Personal, 6573250f
Platform: Linux Mint 18

Binary Ninja is not able to correctly disasemble the attached file `lost_in_bin`. Please find also attached the debug log file `lost_in_bin.txt`.

With IDA Pro it is possible to get the correct disassembly without any errors.

The binary is a challenge from ctflearn.com

Thanks!

Attachment: [lost_in_bin.zip](https://github.com/Vector35/binaryninja-api/files/1234565/lost_in_bin.zip)

**Comment by plafosse** [comment]
This is a know issue #593 which is slated to be fixed for version 1.1 to be released by Aug 31, in just a couple of weeks

**Comment by psifertex** [comment]
Also, in the meantime, you can hit `p` on the pointer to `main` (0x4007d7) and get it to disassemble the rest of the binary.
