### ISSUE TITLE
Edit Mode Needs Help

### ISSUE THREAD

**Issue by bdarmofal** [Vector35/binaryninja-api#783]
Binary Ninja's "edit mode" for Intel architecture needs improvement.

When editing a mnemonic, the instruction width of the existing opcode sequence to be patched is not taken into consideration.

For example, simply entering and leaving edit mode on:
16-bit sequence (0x7f0a) which disassembles to "jg 0x804848d" with an 8-bit address offset

will always cause Binary Ninja to replace it with:
48-bit sequence (0x0f8f06000000) which still disassembles to "jg 0x804848d" but has automatically been extended to a 32-bit address offset

We need a mechanism to manually specify the desired instruction encoding and address operand width where there is more than one possibility.

Automatically choosing the maximum (32/64) bit address width is not acceptable when patching existing instructions to different values that do not require the size of the address offset width to be promoted.

**Comment by psifertex** [comment]
I'll leave the bug open in case we ever change our mind, but this is /really/ low priority if we ever decide to fix it at all. There are so many duplicate encodings and using an assembler that's even capable of all of them and matching up the input size just isnt a priority*.

We also have a bug tracking "smart patching" which is meant to be able to better handle replacing larger chunks of code where you don't want to have to worry about instruction sizes. That is a much higher priority than trying for a perfect 1:1 on assembly/disassembly. 

*With the exception that we already plan to switch to intel xed and it's possible this will either be solvable or just work out of the box at that point.

**Comment by bdarmofal** [comment]
Can I at least suggest calculating the address offset first, and then always choosing the most efficient encoding?
The current system overwrites instructions after the patch (as needed) without any warning.

**Comment by plafosse** [comment]
The issue here is that the assembler syntax is separate from the disassembler syntax.  We're not planning on implementing our own assembler anytime soon. For assembling x86 we shell out to yasm, so for the short encoding of the jump instruction you do `jmp short 0x41`

**Comment by bdarmofal** [comment]
I wrote my own plugin that uses keystone-engine.org months ago that
functions as a replacement assembler.
