### ISSUE TITLE
Python API: Type.enumeration_type calls BNCreateEnumerationType with invalid number of arguments

### ISSUE THREAD

**Issue by Maykeye** [Vector35/binaryninja-api#784]
Binary Ninja Version: 1.1.921-dev,  568b05e
Platform: Ubuntu 16.04.2 LTS

BNCreateEnumerationType takes four arguments. Python binding passes [two](https://github.com/Vector35/binaryninja-api/blob/0b30396eb319e89e4f69d9cbac12fc3d4b453f53/python/types.py#L521): `Type(core.BNCreateEnumerationType(e.handle, width))`, so when I try to use it it complains

```
  File "/home/mayk/binaryninja/plugins/../python/binaryninja/types.py", line 521, in enumeration_type
    return Type(core.BNCreateEnumerationType(e.handle, width))
  File "/home/mayk/binaryninja/plugins/../python/binaryninja/_binaryninjacore.py", line 1387, in BNCreateEnumerationType
    result = _BNCreateEnumerationType(*args)
TypeError: this function takes at least 4 arguments (2 given)
```

ETA: the following work-around works

````
def enumeration_type(e, width=None):
    return Type(core.BNCreateEnumerationType(bv.platform.arch.handle, e.handle, width, False))

**Comment by plafosse** [comment]
Thanks for reporting the bug. This is fixed in the latest dev api version, this will make it into the next dev release.
