### ISSUE TITLE
[types] If type name has colons in it, it can't be a used as a member of struct

### ISSUE THREAD

**Issue by Maykeye** [Vector35/binaryninja-api#788]
Binary Ninja Version: 1.1.921-dev,  568b05e
Platform: Ubuntu 16.04.2 LTS

Define structure `struct A::B {}`

Press Y to append a new member. Enter `A::B* next`. Binary Ninja will complain "Input 1: error: type A::B is not defined", though A::B is defined. Renaming `A::B` to `A_B` fixes error message.

**Comment by plafosse** [comment]
Fixed in v1.1.1480
