### ISSUE TITLE
handle mach-o MH_DYLINKER filetype

### ISSUE THREAD

**Issue by withzombies** [Vector35/binaryninja-api#794]
Binary Ninja currently can't open dyld. Please add support for filetype==MH_DYLINKER. It works fine when you patch dyld's filetype to be 0x2 (MH_EXECUTE).

#define MH_DYLINKER     0x7             /* dynamic link editor */

**Comment by withzombies** [comment]
The load commands on this file don't seem to be parsed properly in Binja. otool gets it correct.

[dyld_ios11b10.zip](https://github.com/Vector35/binaryninja-api/files/1289422/dyld_ios11b10.zip)

**Comment by plafosse** [comment]
Fixed in dev

**Comment by psifertex** [comment]
version >925
