### ISSUE TITLE
Type parsing of variadic function pointer results in segfault

### ISSUE THREAD

**Issue by 404d** [Vector35/binaryninja-api#795]
Binary Ninja Version: 1.1.924-dev Personal, 8bed27a2
Platform: OS X 10.12

I'll admit I don't touch C that often, but as far as I can see this should be a legal function pointer:

```
bv.parse_type_string("void (*const test)(uint32_t arg1, ...)")
```

**Comment by D0ntPanic** [comment]
Fixed in build 1120
