### ISSUE TITLE
missing variable references in asm and LLIL

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#797]
Some binaries exhibit missing variable references, as evidenced in IgniteMe (Flareon binary and the competition is ongoing so not uploading the sample, but bug is exhibited at offset 0x4010fd)

**Comment by peperunas** [comment]
Adding some images from other binaries.

![image](https://user-images.githubusercontent.com/6033387/30648664-e0e6fa42-9e1e-11e7-85e3-e0dc818a44a0.png)
![image](https://user-images.githubusercontent.com/6033387/30648759-1937c598-9e1f-11e7-9cd2-c89d7b4dcefb.png)
![image](https://user-images.githubusercontent.com/6033387/30648806-31d964b2-9e1f-11e7-9e75-8f0d456ee9be.png)

**Comment by psifertex** [comment]
Now that flareon has finished, binary is attached. See offset 0x40102e for example. 
[igniteme.zip](https://github.com/Vector35/binaryninja-api/files/1624765/igniteme.zip)

**Comment by plafosse** [comment]
1087 Fixes this issue in assembly, but not llil.

**Comment by peperunas** [comment]
I have a (related?) issue:

![image](https://user-images.githubusercontent.com/6033387/37237628-c32d712a-23ca-11e8-8fab-e77cda6d1af6.png)

`argv` is defined as `char ** argv` in Binary Ninja. As you can see, BN doesn't recognize `argv[0]`.

**Comment by D0ntPanic** [comment]
Fixed in build 1099
