### ISSUE TITLE
PPC: Lifted instructions cannot properly refer to CR0, CR1, etc.

### ISSUE THREAD

**Issue by lwerdna** [Vector35/binaryninja-api#799]
PPC replicates the flags LT, GT, EQ, SO eight times across the condition register CR. Instructions can specify which of the eight copies to affect/test with CR0, CR1, ..., CR7.

There is no mapping between these 32 bits and the flag subsystem (flag conditions like LLFC_E, flag roles like PositiveSignFlagRole, etc.).

Currently the PPC plugin just pretends that there are no copies. No matter what CRx is specified by an instruction, it is lifted to touching IL_FLAG_LT, IL_FLAG_GT, IL_FLAG_EQ, IL_FLAG_SO which have the expected roles and are associated with the expected flag conditions.

**Comment by joshwatson** [comment]
This issue seems relevant to me as well, because I can't currently correlate flags in the MSP430 Architecture to bits in the SR register.

**Comment by rssor** [comment]
This has been implemented for PPC as of build 1.1.1108-dev.
