### ISSUE TITLE
QWidget UI Refactor

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#803]
We've got a number of separate tickets tracking the upcoming UI refactor planned for 1.2 but I'm going to link them all to this one so we have an easier time tracking them. 

Current options for the UI are:

1) Electron  (yes, we'll make sure memory and performance is acceptable before we'd consider this)
2) QT Quick
3) Stick with current QWidgets (unlikely -- QWidget support has been getting worse and worse in subsequent QT releases and are especially bad on OS X HiDPI)
4) Other? Again, probably unlikely but we may end up using something else entirely. 

We'll be doing some prototype tests of each of these before we make any decision.

**Comment by psifertex** [comment]
5.10 has improved performance, sticking with qwidgets. Yay!

**Comment by whitequark** [comment]
\o/ this means that my clever plan for extending BN's UI will keep working.
