### ISSUE TITLE
MLIL return statement sometimes eliminates return value

### ISSUE THREAD

**Issue by resrever** [Vector35/binaryninja-api#807]
Binary Ninja Version: 1.1.930-dev, 8df66a30
Platform: OS X 10.12
[mipsel-libpam.so.0.zip](https://github.com/Vector35/binaryninja-api/files/1316299/mipsel-libpam.so.0.zip)

In the attached MIPS binary, the function pam_authenticate returns an error code, but when going from mapped MLIL to full MLIL, jump($ra) becomes "return" without a value.  Note the function type signature has an int32_t return type, so the MLIL lifting should end with a "return $v0".

**Comment by fluxchief** [comment]
I'm having a similar issue (using a custom architecture plugin) where it ignores the size of the return value and just returns one byte (=regsize):
`int16_t  mul_u16(char arg1 @ r26, char arg2 @ r27, char arg3 @ r30, char arg4 @ r31)`
![LLIL](https://user-images.githubusercontent.com/2988703/31128910-64433aca-a853-11e7-8d72-44c7be3c0889.png)
![MLIL](https://user-images.githubusercontent.com/2988703/31128911-644588de-a853-11e7-988f-171b5a19f943.png)

`int16_t  mul_u32(char arg1, char arg2, char arg3, char arg4, char arg5 @ r26, char arg6 @ r27, char arg7 @ r30, char arg8 @ r31)`
![LLIL](https://user-images.githubusercontent.com/2988703/31128909-643e6fb8-a853-11e7-895a-ca8ff535aec9.png)
![MLIL](https://user-images.githubusercontent.com/2988703/31128912-64647f28-a853-11e7-9668-bed727f796e3.png)

The mapped MLIL looks correct for me as well.

**Comment by psifertex** [comment]
We're not sure if this was the result of a coincidence or another fix along the way, but it looks like this particular example now behaves properly. If you see other functions that have trouble, you can additionally try `analysis.experimental.alternateTypePropagation` which may help with some binaries, but may have other negative side effects. Feel free to re-open if you see other examples.
