### ISSUE TITLE
Inaccurate MLIL SSA variable value calculation

### ISSUE THREAD

**Issue by toolCHAINZ** [Vector35/binaryninja-api#808]
Just started looking at this year's flare-on and noticed something odd with MLIL.

Not sure what the etiquette is for posting binaries for an active CTF, so I'll just say it's the binary for challenge 2 (the first one with a binary).

At `0x401000`, there's a simple function with one basic block returning a constant value:

<img width="438" alt="ignite_asm" src="https://user-images.githubusercontent.com/27028960/30769649-6e7ffbec-9feb-11e7-83a2-379a0809842e.png">

MLIL SSA view makes the following statement about the return value of this function:

<img width="419" alt="ignite_mlil" src="https://user-images.githubusercontent.com/27028960/30769653-7cba4bfe-9feb-11e7-9575-71d5916db2ee.png">

However, working it by hand (and emulating this function in `unicorn`) I get `0x700004` as the return value.

It looks to me (without knowing how binja works, of course) like the `xor` of `ax` and `dx` might be improperly clearing out the entirety of `eax` and `edx`?

**Comment by joshwatson** [comment]
The xor actually isn’t zeroing anything

**Comment by bpotchik** [comment]
Fixed in release 1.1.935-dev.
