### ISSUE TITLE
GetLowLevelILForInstruction returns an out of bounds index

### ISSUE THREAD

**Issue by ctfhacker** [Vector35/binaryninja-api#809]
The following code should error with an index error for `/bin/ls`:
```
for xref in bv.get_code_refs(bv.symbols["memcpy"].address):
 print("[0x{:x}] xref LLIL index: {}".format(xref.address, core.BNGetLowLevelILForInstruction(xref.function.handle, xref.arch.handle, xref.address)))
 print(xref.function.get_low_level_il_at(xref.address))

```

This will error with the following printed line:
```
[0x40da78] xref LLIL index: 4
```

The picture below is the LLIL view of `/bin/ls` showing the index should be `141`
![selection_038](https://user-images.githubusercontent.com/7690115/30787568-5756b494-a151-11e7-8bd2-e188d78b44af.png)

The binary being tested: [ls.zip](https://github.com/Vector35/binaryninja-api/files/1327838/ls.zip)

Builds tested:
```
1.1.935 - dev
1.1.922 - release
```

**Comment by bpotchik** [comment]
Instead of index out of bounds, NoneType would be returned. This is also related to #1034.
Fixed in build 1.1.1188-dev.
