### ISSUE TITLE
Problems saving an empty dict in metadata

### ISSUE THREAD

**Issue by pjgat09** [Vector35/binaryninja-api#810]
I tried saving an empty dict as a dict value in metadata with this example:

    foo = {"bar": {}}
    bv.store_metadata('foo', foo)
    bv.modified = True

I can then check that the value is there with:

    bv.query_metadata('foo')

If I then save the BNDB, restart BN, and load the BNDB I have problems checking the metadata. This check: 

    bv.query_metadata('foo')

throws a KeyError 'bar'. And if I try to save the BNDB, BN crashes.
 
Binary Ninja Version: 1.1.921-dev Personal,  568b05e
Platform: Windows 10

**Comment by plafosse** [comment]
Fixed in v 1.1.943
