### ISSUE TITLE
Copy/Paste in Types UI copies from Hex View

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#814]
Given a types view of:
```
      struct foo
      {
0000      int32_t a;
0004      struct foo b[4];
0024  }
```
And a hex view of 
```
00000000: 55 89 e5 83 ec 08 8b 5d 08 8b 43 08 89 ec 5d c3  U......]..C...].
```
If I select the foo struct in its entirety and copy/paste it, I get `U\x89\xe5\x83\xec\x08\x8b]\x08\x8bC\x08\x89\xec]\xc3`. If I select only a portion of the struct, I get something like `U\x89\xe5\x83`, depending on how many member fields I select, it seems.

**Comment by bpotchik** [comment]
Fixed in build 1.1.1317-dev.

Select and copy actions have been implemented. For now pasting into types view can be done through one of the type creation dialogs.
