### ISSUE TITLE
Seg Fault on Create Function Here

### ISSUE THREAD

**Issue by rwincey** [Vector35/binaryninja-api#817]
Binary Ninja Version: 1.1.944-dev, 7c478f6b
Platform: Ubuntu 16.04.3 LTS

Steps to Repro:

Open secondstage binary

Select Linear Disassembly View

Right click at offset 0x0

Create Function Here

Select x86 arch, windows OS, windows-x86 ABI

[secondstage.tar.gz](https://github.com/Vector35/binaryninja-api/files/1347165/secondstage.tar.gz)

**Comment by bpotchik** [comment]
Fixed in build 1.1.948-dev.
