### ISSUE TITLE
mipsel32: Relative jumps do not decode correctly

### ISSUE THREAD

**Issue by valgrind** [Vector35/binaryninja-api#818]
I wrote a loader for Playstation 1 binaries which works well enough, but the decoding of relative jumps in mipsel32  seems to not happend as it should, making the Analysis stop in the first function.

Loader here: https://github.com/valgrind/binja-psx

Test binary I'm using: http://hitmen.c02.at/files/releases/psx/hit-greentro.zip

Example dissassembly: 
![screenshot_pxe-exe-1](https://user-images.githubusercontent.com/6524877/31057037-5fe36b8a-a6dc-11e7-9a41-3b05a945e414.png)

BN Version 1.1.944-dev

**Comment by joshwatson** [comment]
Any update on this one? Seems like a pretty serious bug for several people, but there hasn’t been much movement or acknowledgement of it

**Comment by valgrind** [comment]
build 1.1.980-dev seems to fix this
