### ISSUE TITLE
Uninstaller doesn't delete C:\Program Files\Vector35 directory

### ISSUE THREAD

**Issue by geary** [Vector35/binaryninja-api#819]
I just bought Binary Ninja, and when I uninstalled the trial version I noticed it left an empty `C:\Program Files\Vector35` directory behind. The uninstaller should delete this directory unless there are other Vector35 products remaining inside the directory.

Obviously this is super low priority, as it does little harm to leave an empty directory. Just noting it for the record in case you ever have a lazy rainy afternoon with nothing better to do.

**Comment by psifertex** [comment]
Thanks! We're closing it out with a lowpriority tag so we can pull it later, but for now we'll just leave that as a little reminder that someone once loved us. ;-)
