### ISSUE TITLE
Polyglot functions are not represented in functions list

### ISSUE THREAD

**Issue by D0ntPanic** [Vector35/binaryninja-api#82]
If two functions start at the same address but have different architectures (in a polyglot payload, for example), they show up twice in the function list as the same name with no way to differentiate between them.  It should annotate the function list entries with the architecture so it is easy to tell which is which.

**Comment by psifertex** [comment]
Related to #62, same fix will likely be a fix for both.

**Comment by CouleeApps** [comment]
Behavior of this has since changed, but is now buggy in a different way. Closing this in favor of #1948
