### ISSUE TITLE
Remove gradient fill in Classic theme

### ISSUE THREAD

**Issue by geary** [Vector35/binaryninja-api#820]
In the Classic theme, the default disassembly view (PE Graph) has a gradient fill in each of the boxes. I find this gradient fill very distracting and unhelpful. Is there a way to remove it?

The Dark theme does not appear to have a gradient fill and it looks a lot better, but I have trouble using dark themes. The Classic theme has the best overall usability for me.

**Comment by plafosse** [comment]
Unfortunately colors are impossible to get right for everyone. We plan to address this in version 1.2  #207 Please follow this ticket if you're interested.
