### ISSUE TITLE
Lack of menu contrast in Classic theme

### ISSUE THREAD

**Issue by geary** [Vector35/binaryninja-api#821]
In the Classic theme on Windows, the menus are gray on gray with very little contrast.

The Dark theme has nice high-contrast menu colors, but my eyes do better with light themes.

Would it be possible to have a more normal high-contrast menu in the Classic theme, similar to standard Windows apps?

**Comment by psifertex** [comment]
Unfortunately we are just about to start the 1.2 UI refactor where we will likely be redoing the entire theme system anyway. The good news is the new system will potentially allow for more flexible user defined themes but the downside is that weMre unlikely to be making any UI changes in the current theme. I’ll keep these two open so we can keep an eye on them while we are working on the new UI, but unlikely to see any changes soon unfortunately.

**Comment by plafosse** [comment]
Closing this as it will be handled by #207
