### ISSUE TITLE
Can't zoom in if keyboard layout is set to German

### ISSUE THREAD

**Issue by h0ng10** [Vector35/binaryninja-api#822]
It is not possible to use ```[CTRL-SHIFT] +```  to Zoom in if the keyboard Layout is set to German. Other keyboard layouts might also be affected. 

Tested on: Ubuntu Linux (Gnome) 16.10
Binary Ninja version: 1.1.922 (Build ID 4d40ebb7)

**Comment by plafosse** [comment]
We will be doing a large keystroke refactor for v1.2 #481 In the meantime you can still use ctrl+mouse wheel.

**Comment by psifertex** [comment]
Tracking is now in #92 instead of 481.
