### ISSUE TITLE
mips32: div $a0, $a1 generates 10 instructions

### ISSUE THREAD

**Issue by endeav0r** [Vector35/binaryninja-api#826]
To reproduce, enter the following assembly into the assembler with "mips32" selected as the architecture:
```
div $a0, $a1
```
Ten instructions will be generated.

It looks like perhaps binary ninja is trying to do things for the user, such as emitting a `break` instruction if the divisor is 0, and some other things, and then moves the result into $a0. It would probably be better to just emit the one instruction `div $a0, $a1`, and if someone wants to do the other stuff, allow them to do that on their own.

**Comment by plafosse** [comment]
This is really weird. Assigning this to @lwerdna

**Comment by lwerdna** [comment]
It's a quirk of LLVM's assembler, which we use behind the scenes. It also found its way into keystone:

```
$ kstool mips 'div $a0, $a1'
div $a0, $a1 = [ 01 00 a0 14 1a 00 85 00 0d 00 07 00 ff ff 01 24 03 00 a1 14 00 80 01 3c 01 00 81 14 00 00 00 00 0d 00 06 00 12 20 00 00 ]
```

The solution? LLVM expects a [0,31] destination register, unaware apparently div ignores it and writes to HI:LO:

```
$ kstool mips 'div $zero, $a0, $a1'
div $zero, $a0, $a1 = [ 1a 00 85 00 ]
```

The string `div $zero, $a0, $a1` into BinaryNinja's assemble dialog will also produce 1a 00 85 00 and be disassembled as `div $a0, $a1`.
