### ISSUE TITLE
PDB: Symbols downloaded from Microsoft via http, not https, by default

### ISSUE THREAD

**Issue by riverar** [Vector35/binaryninja-api#827]
Binary Ninja Version: 1.1.922, 4d40ebb7
Platform: Windows 10

Microsoft public symsrv supports https, let's use it.

**Comment by psifertex** [comment]
That’s already done if you switch to dev.

**Comment by riverar** [comment]
Thanks @psifertex, shame on me for not checking dev first.

**Comment by psifertex** [comment]
No worries, I’d rather have too many reports than too few. :-)
