### ISSUE TITLE
Add BNIL operation enum convenience data structures

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#829]
It would be nice to have some convenience data structures that categorize BNIL operations for easily checking if an instruction is a particular type of instruction. For example, something like:
```python
MLIL_Comparisons = [
    MediumLevelILOperation.MLIL_CMP_E,
    MediumLevelILOperation.MLIL_CMP_NE,
    #...
]

if il.operation in MLIL_Comparisons:
    # handle comparison operations
```

Various categories could be control flow, binary operations, unary operations, comparisons.

**Comment by plafosse** [comment]
Instead of doing this instructions live in a hierarchy. You can see if an instruction is a comparison by doing the following: `isinstance(i, Comparison)`
