### ISSUE TITLE
Crash when using bndbs with functions defined in raw view

### ISSUE THREAD

**Issue by itsZN** [Vector35/binaryninja-api#833]
When using a bndb which has functions defined in raw mode, viewing the function causes binja to have a null pointer deref.

I tested on Commercial Version 1.1.948-dev on linux and windows. I don't know when this bug was introduced.

Steps to reproduce:

* Load any file *in raw mode*
* `ctrl+p` and define a function with *any* arch
* Save the analysis database
* Restart binja and open the database
* View the function *in raw mode*

Here are some recording:
![](https://itszn.com/u/5c76e77aa0ab9fc061e488b6237e1f6fb2242411.gif)
![](https://itszn.com/u/1e9e8d147a229b9328f8aae0b86f9c603ecce2e7.gif)

**Comment by itsZN** [comment]
We noticed that it is not actually the custom architecture, but rather defining a function in raw view, and reopening that function in the bndb.

Here is another recording, but only using x86 this time.
![](https://itszn.com/u/5c76e77aa0ab9fc061e488b6237e1f6fb2242411.gif)

**Comment by plafosse** [comment]
Thank you for the detailed report, made reproducing the issue easy. Fixed in 1.1.993
