### ISSUE TITLE
Mapped MLIL not accessible unexpectedly

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#835]
As far as I understand, `function.get_low_level_il_at(addr).mapped_medium_level_il` should always return a value. For example, a `push(some_value)` in LLIL has two Mapped MLIL instructions that correspond to it:
```
var_4 = some_value
esp = &var_4
```
However, `.mapped_medium_level_il` returns `None` rather than the `MLIL_SET_VAR` operation for the first mapped MLIL instruction. There is no other LLIL instruction that corresponds to this disassembly address, so I don’t know how to get the mapped MLIL for it without iterating through the MLIL itself, which isn't particularly enticing.

**Comment by D0ntPanic** [comment]
Fixed in build 1124
