### ISSUE TITLE
BNDB does not open by double-clicking in explorer if update is waiting to be installed

### ISSUE THREAD

**Issue by twvd** [Vector35/binaryninja-api#837]
Binary Ninja Version: 1.1.949-dev Personal, 29bc023d
Platform: Windows 10

To reproduce: after an update is downloaded, close Binary Ninja. Double-click a BNDB file in explorer. The updater runs, then launches Binary Ninja, but the BNDB file is not being opened.

Expected result: BNDB file that I double-clicked in explorer opens.

Just a minor annoyance.

**Comment by plafosse** [comment]
This is a very common issue. Even google chrome has this issue. I'm going to mark this a low priority and close. If we ever are lacking things to do we will go back through these types of issues.
