### ISSUE TITLE
Degraded Performance on Windows

### ISSUE THREAD

**Issue by bpotchik** [Vector35/binaryninja-api#838]
Pathological case where windows takes too long to to finish analysis of the function at 0x100780b. The function is a false positive produced from linear sweep in the import directory area.

[notepad.bndb.zip](https://github.com/Vector35/binaryninja-api/files/1379927/notepad.bndb.zip)

![screen shot 2017-10-12 at 12 12 17 pm](https://user-images.githubusercontent.com/29309548/31506851-a7321e56-af46-11e7-8663-a6ea344a21ee.png)

**Comment by christiancoleman** [comment]
Brian (in Slack) has asked me to post the following binary to this issue as it's not completing it's analysis and he believes it may be related. It seems to never be able to finish. I'm on a 64-bit Windows host (not in a VM).

[Wow.exe.zip](https://github.com/Vector35/binaryninja-api/files/1402232/Wow.exe.zip)

**Comment by gaasedelen** [comment]
Encountered a similar case when testing with Chakra (x86). Linear sweep identified what looked like a false positive (or partial?) function and it got stuck. I let it run for ~30 minutes (trying to analyze a single function) before I killed it.

[ChakraCore.zip](https://github.com/Vector35/binaryninja-api/files/1402584/ChakraCore.zip)

**Comment by bpotchik** [comment]
![screen shot 2017-12-14 at 6 20 50 pm](https://user-images.githubusercontent.com/29309548/34019168-8a5dbea2-e0fb-11e7-8f50-3b25a46283fd.png) Updated time for notepad.bndb.

**Comment by psifertex** [comment]
Closing this as complete. Clearly no longer a pathological case, though there's always optimizations possible. :-) 

@gaasedelen can you confirm your particular use-case is fixed as well? if not, might be a different cause.

**Comment by bpotchik** [comment]
@gaasedelen Your binary will be fixed by either of #745 or #908.

@christiancoleman Yours will be fixed by #908.
