### ISSUE TITLE
Headless mode does not work when hosted app uses jemalloc

### ISSUE THREAD

**Issue by withzombies** [Vector35/binaryninja-api#842]
You can't run Binary Ninja in headless mode and embed it in another application if that host application uses jemalloc. It aborts trying to free an "invalid" pointer.

**Comment by plafosse** [comment]
We're currently working to obviate jemalloc

**Comment by bpotchik** [comment]
Fixed in build 1.1.1042-dev. We no longer statically link with jemalloc. Feel free to preload with your choice of allocator (jemalloc/tcmalloc). For now there will still be some performance benefit although we expect that gap to narrow soon.
