### ISSUE TITLE
Show all symbols in the "functions" window

### ISSUE THREAD

**Issue by TerryThibault** [Vector35/binaryninja-api#843]
[x86vsMIPS-Dynamic-Symbols.zip](https://github.com/Vector35/binaryninja-api/files/1389150/x86vsMIPS-Dynamic-Symbols.zip)

Attached is a simple program that outputs "Hello, world". It is compiled for x86 and for MIPS. 

We can see that in both binaries, the `puts` function is called. However, only in the x86 binary does `puts` show up in the function table.

**Comment by plafosse** [comment]
`puts` doesn't actually exist in this binary, rather is a symbol to a pointer and `puts` exists in that other binary. This is actually a UI issue where we need to overhaul our function list to be more of a symbol list.

**Comment by rssor** [comment]
This was fixed in build 1.1.1178-dev.

**Comment by rssor** [comment]
Woops, spoke a little too soon here. Other issues where the call to the imported symbol would not be labeled correctly were fixed, but external calls directly out of the got still aren't going to have entries in the function list.

**Comment by sheadovas** [comment]
Hi, can anybody tell me what is the status of adding external symbols into list of functions / separate tab? (something similar to IDA pro Subviews: Import/Export)

**Comment by plafosse** [comment]
Fixed in 1.1.1772
