### ISSUE TITLE
macOS + Custom Python Interpreter

### ISSUE THREAD

**Issue by alexmullins** [Vector35/binaryninja-api#844]
Hey everyone,
First off, I want to say that I'm loving binja so far! 

My environment:

- macOS High Sierra 10.13
- homebrew
- pyenv python 2.7.14

Now to the point. I had problems early on changing the default Python interpreter the GUI uses. Every remedy I saw in previous issues did not work for me. The version always pointed to my system python version 2.7.10 and not my pyenv python. I finally found a solution that works for me!

Step 0: What we need to change
```bash
$ cd /Applications/Binary\ Ninja.app/Contents/MacOS/plugins/
$ otool -L libpythonplugin.dylib
[...]
# Points to the system python
/System/Library/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.10)
```

Step 1: Install python with pyenv also building a .dylib to link against
```bash
$ CFLAGS="-I$(brew --prefix openssl)/include" \
LDFLAGS="-L$(brew --prefix openssl)/lib" \
env PYTHON_CONFIGURE_OPTS="--enable-shared" \
pyenv install 2.7.14

$ pyenv global 2.7.14
```

Step 2: Confirm python points to your new install: 
```bash
$ which python
```

Step 3: Replace the linked python dylib in binja
```bash
$ cd /Applications/Binary\ Ninja.app/Contents/MacOS/plugins/

# backup incase you'd like to revert
$ cp libpythonplugin.dylib libpythonplugin.dylib.bak

# now replace the dylib
$ install_name_tool -change /System/Library/Frameworks/Python.framework/Versions/2.7/Python /Users/{name}/.pyenv/versions/2.7.14/lib/libpython2.7.dylib libpythonplugin.dylib
```

That should set the python version correctly in the GUI. You can check by opening the console:
```python
>>> import sys
>>> print sys.version
2.7.14 (default, Oct 18 2017, 02:41:43) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.38)]
```

Hope this can help someone else!

**Comment by Manouchehri** [comment]
https://github.com/Manouchehri/binja-fixer

**Comment by psifertex** [comment]
Going to go ahead and close this one out and use 905 to track the issue going forward if you don't mind since that is our intended fix for this and similar problems. Thanks for the detailed report and example solution!
