### ISSUE TITLE
Arithmetic shift right sometimes returns 0

### ISSUE THREAD

**Issue by DatBrick** [Vector35/binaryninja-api#845]
Binary Ninja Version: 1.1.954-dev, 4c2088ba
Platform: Windows 10
It appears to happen when the operand size is smaller than the native operand size. E.G:
32 bit operand on x86
![image](https://user-images.githubusercontent.com/6098371/31760525-dd4df512-b4ac-11e7-9947-a3135255141c.png)
32 bit operand on x64
![image](https://user-images.githubusercontent.com/6098371/31760493-c55f5e82-b4ac-11e7-9173-b966f7ffd44a.png)
64 bit operand on x64
![image](https://user-images.githubusercontent.com/6098371/31760509-d0d3c55a-b4ac-11e7-93e4-4236f2cd69d1.png)

**Comment by bpotchik** [comment]
Fixed in release 1.1.961-dev.
