### ISSUE TITLE
Mark data portion as code

### ISSUE THREAD

**Issue by dipusone** [Vector35/binaryninja-api#846]
BinaryNinja fails to recognize some portion of the code from the a function (i.e. main) as code, as result the disassembly of the function is incomplete. Would be helpful the ability to mark a segment as code which in turn could be coalesced with the function which contains (or precede ) the marked segment.
![screenshot_20171019_134617](https://user-images.githubusercontent.com/1831345/31769490-30503eb0-b4d4-11e7-8e1c-8f13ed8e2d8a.png)

The binary file is the following and the function is the main.
[no_flo_f51e2f24345e094cd2080b7b690f69fb.bin.tar.gz](https://github.com/Vector35/binaryninja-api/files/1398197/no_flo_f51e2f24345e094cd2080b7b690f69fb.bin.tar.gz)

**Comment by plafosse** [comment]
Two fixes for this. You can select the first byte of the function and hit `p` or you can run the linear sweep analysis module.

**Comment by xusheng6** [comment]
A bit late to the party -- for this particular binary, the actual error is the function `sub_4006c6` is wrongly considered a no-return. Manually setting it to can-return will fix the problem. Also, this has been fixed in recent versions and binja knows the function can return
