### ISSUE TITLE
Deceptively named negu for MIPS

### ISSUE THREAD

**Issue by endeav0r** [Vector35/binaryninja-api#848]
The `negu` instruction for MIPS, or "Negate unsigned," is deceptively named.

`negu d, s` is not `d = ~s`, as I originally thought, but `d = 0 - s`. It's a pseudo instruction for `subu`.

The following script in python shows the correct semantics:

```python
from unicorn import *
from unicorn.mips_const import *

CODE = '\x00\x05\x20\x23'

ADDRESS = 0x10000

mu = Uc(UC_ARCH_MIPS, UC_MODE_32 + UC_MODE_BIG_ENDIAN)
mu.mem_map(ADDRESS, 4096)
mu.mem_write(ADDRESS, CODE)
mu.reg_write(UC_MIPS_REG_A1, 0xff00ff00)
mu.emu_start(ADDRESS, ADDRESS + 4)
print hex(mu.reg_read(UC_MIPS_REG_A0))
print hex(mu.reg_read(UC_MIPS_REG_PC))
```

One would think `negu $a0, $a1` would be `$a0 = ~$a1`, but...
```
hex(~0xff00ff00 & 0xffffffff) # is 0xff00ff
hex((0 - 0xff00ff00) & 0xffffffff) # is 0xff0100
```

We can see by running the following script through unicorn engine that the semantics of MIPS, according to qemu and spec, is `arg0 = 0 - arg1`.

This instruction is currently translated to `arg0 = neg.d(arg1)` in LLIL.

**Comment by endeav0r** [comment]
As more people weigh-in in slack, this may be an erroneous bug report, and just show my lack of understanding in BINJA IL. If that is so, please close :).

**Comment by plafosse** [comment]
The neg LLIL instruction does what you want.

**Comment by endeav0r** [comment]
My misunderstanding.
