### ISSUE TITLE
Some stack variables can't be renamed

### ISSUE THREAD

**Issue by devaneal** [Vector35/binaryninja-api#852]
In the example below I was able to rename `rbp - 0x90` to `input`, but I can't rename `rbp - 0xd0`. Additionally, the names don't match up with the stack offsets. For instance, one line reads `mov dword [rbp-0x`**a0**` {var_`**a8**`}], 0xf0f082be`.
![screenshot from 2017-10-31 10-55-38](https://user-images.githubusercontent.com/8049135/32230768-43435002-be2a-11e7-95a3-a4eccd2c209e.png)
The binary is [here](https://github.com/TechSecCTF/meeting_notes/blob/master/10-30-17-re_ctf_challs/tablez). I'm using Binary Ninja Version 1.1.922 Personal (Build ID 4d40ebb7).

**Comment by joshwatson** [comment]
Duplicate of #797

**Comment by devaneal** [comment]
You're right. Closing.
