### ISSUE TITLE
ASCII strings not identified properly in binary

### ISSUE THREAD

**Issue by christiancoleman** [Vector35/binaryninja-api#857]
I'm progressing through Practical Malware Analysis and in the first lab they provide a binary that has strings that aren't being identified in Binary Ninja (but are being identified properly in IDA or via 'strings -a'. In Slack, Jordan asked me to post the binary to aid with troubleshooting. I'm assuming the binary is unsafe so be careful!

![mem_loc](https://user-images.githubusercontent.com/6051308/32353258-10785f28-bffb-11e7-96fe-1c29a8ce06a3.png)

[Lab01-01.exe.zip](https://github.com/Vector35/binaryninja-api/files/1439562/Lab01-01.exe.zip)

**Comment by plafosse** [comment]
Fixed in version 1.1.992
