### ISSUE TITLE
MIPS branch into delay slot prevents llil generation

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#858]
If an instruction branches into another instructions delay slot llil generation fails. This is because the data for basic blocks is stored in the basic block object itself. This prevents reading past the end of a basic block even when max instruction size is set correctly.
<img width="360" alt="screen_shot_2017-10-31_at_10 17 03_pm_720" src="https://user-images.githubusercontent.com/10556585/32388291-97f38390-c09d-11e7-8d30-db191b997348.png">

**Comment by rssor** [comment]
Fixed in build 1.1.1169-dev.
