### ISSUE TITLE
Add __android_log_assert to noreturn list

### ISSUE THREAD

**Issue by mothran** [Vector35/binaryninja-api#859]
In almost all cases __android_log_assert is marked with the noreturn attrib, unless __GLIBC__ is not defined.  Reference https://android.googlesource.com/platform/system/core/+/jb-dev/include/android/log.h#116

I currently manually mark it can_return = False but it would be nice if this was in mainline.

**Comment by plafosse** [comment]
I've made a local commit but I need to test this out. Could you possibly post a binary here or privately on Slack?

**Comment by galenbwill** [comment]
@plafosse do you still have that local commit for this, and is it still valid/usable?

**Comment by galenbwill** [comment]
Added in 2.4.3004
