### ISSUE TITLE
HiDPI per monitor is broken.

### ISSUE THREAD

**Issue by gynophage** [Vector35/binaryninja-api#86]
It looks bad. I'd post a video, but github is being angry.

https://files.slack.com/files-pri/T0D00AAJW-F0JSAD9JQ/download/test.exe_____binary_ninja_1_19_2016_3_56_58_pm.mp4

**Comment by plafosse** [comment]
Waiting on QT 5.6 which promises fixes for HIDPI

**Comment by D0ntPanic** [comment]
Fixed in dev
