### ISSUE TITLE
Indirect jumps stop tail call analysis

### ISSUE THREAD

**Issue by DatBrick** [Vector35/binaryninja-api#861]
Binary Ninja Version: 1.1.993-dev, 4174b55d
Platform: Windows 10

Binja fails to recognise an indirect (obfuscated) jump as a tail call, even when the destination is marked as a function.
![image](https://user-images.githubusercontent.com/6098371/32555178-f9dc4d36-c493-11e7-9844-8f114969fbe9.png)
![image](https://user-images.githubusercontent.com/6098371/32555350-5cb35a9e-c494-11e7-9f09-9d5ce3695a37.png)

**Comment by bpotchik** [comment]
Fixed in build 1.1.1190-dev.
