### ISSUE TITLE
Provide UI Indication that Function is Invalid

### ISSUE THREAD

**Issue by mossberg** [Vector35/binaryninja-api#875]
This is a nonsensical binary, but BN hangs when trying to disassemble `main`. The first instruction of main is `vinserti128 ymm0,ymm0,xmm0,0x1`

Version 1.1.922
OS X

[helloworld2.zip](https://github.com/Vector35/binaryninja-api/files/1483991/helloworld2.zip)

**Comment by plafosse** [comment]
This will most likely be fixed by #193

**Comment by psifertex** [comment]
I think this got fixed by some of @bpotchik's other fixes for linear sweep, but can you please confirm?

**Comment by bpotchik** [comment]
This is at least fixed in build 1.1-1236-dev and likely has been fixed for a while.
