### ISSUE TITLE
Incorrect get_possible_reg_values behaviour for const ptr

### ISSUE THREAD

**Issue by DatBrick** [Vector35/binaryninja-api#876]
Binary Ninja Version: 1.1.1002-dev, 512e984a
Platform: Windows 10

When dealing with a `const ptr` get_possible_reg_values returns `<undetermined>`. This doesn't happen if the display type of the pointer is changed to anything else (e.g. unsigned hex).

![image](https://user-images.githubusercontent.com/6098371/32993402-5d399618-cd4f-11e7-9f9c-8134896861d0.png)
![image](https://user-images.githubusercontent.com/6098371/32993398-542829e0-cd4f-11e7-8a25-e23a457dd8f3.png)

![image](https://user-images.githubusercontent.com/6098371/32993410-7aca1086-cd4f-11e7-802a-fe3cbb02260c.png)

**Comment by bpotchik** [comment]
Fixed in build 1.1.1003-dev.
