### ISSUE TITLE
typed incorrect email id for license 

### ISSUE THREAD

**Issue by sana-exp** [Vector35/binaryninja-api#881]
bought your package worth $149. money has got debited but I typed an incorrect e mail id
what should I do?

**Comment by psifertex** [comment]
I assume you found the license in your spam folder? If not, feel free to reopen and we'll get it figured out.

**Comment by sana-exp** [comment]
Hi,
Actually I had typed in gmal instead of gmail so mail might not have even
been sent. Thankfully , Brian on slack helped me fix it.

On Nov 25, 2017 8:27 PM, "Jordan" <notifications@github.com> wrote:

I assume you found the license in your spam folder? If not, feel free to
reopen and we'll get it figured out.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/Vector35/binaryninja-api/issues/881#issuecomment-346945361>,
or mute the thread

**Comment by psifertex** [comment]
Gotcha, glad to hear it.
