### ISSUE TITLE
Unable to Load PDBs from Microsoft Symbol Server

### ISSUE THREAD

**Issue by 0xdeadbeefJERKY** [Vector35/binaryninja-api#882]
Binary Ninja Version: 1.1.1002-dev Personal, 512e984a
Platform: Windows 10

Using [HackSysTeam Vulnerable Driver](https://github.com/hacksysteam/HackSysExtremeVulnerableDriver) as a test binary. After loading the driver and running `Load PDB (BETA)`, I receive the following error in the logs:
```
Checking symbol store: C:/symbols
Attempting to download PDB from https://msdl.microsoft.com/download/symbols
Loading pdb downloaded from https://msdl.microsoft.com/download/symbols
Failed to parse pdb file: Failed to parse pdb: Header size too small
```

**Comment by plafosse** [comment]
Can you submit the binary?

**Comment by joshwatson** [comment]
I think this was an issue where the user was trying to download a PDB for a binary that isn't on the Microsoft Symbol Store, and the 404 error was being interpreted as a PDB. That particular issue was fixed a few builds ago on dev.
