### ISSUE TITLE
Can Binary Ninja handle files with mixed ARM/Thumb instructions?

### ISSUE THREAD

**Issue by ProfFan** [Vector35/binaryninja-api#883]
It seems that I can only choose one in a session. IDA handles ARM/Thumb well though.

Binary Ninja Version: 1.1.989 Personal, fad48e3a
Platform: OS X 10.13

**Comment by joshwatson** [comment]
Binary Ninja can handle any combination of architectures in a single binary. Try running the linear sweep plugin

**Comment by psifertex** [comment]
Also, if you right-click you can create a function of any architecture type. If you have a specific example that isn't properly decoding arm/thumb, feel free to submit it (please check dev first as there are several fixes there).
