### ISSUE TITLE
MacOS - zooming with gestures?

### ISSUE THREAD

**Issue by thel3l** [Vector35/binaryninja-api#886]
Is it possible to get gesture based zooming to allow for use of the trackpad to navigate through a file? For example - pinch in zoom out and vice-versa to zoom in?

This currently only works by holding down Control and scrolling up and down.

OS: MacOS 10.13.1
BN Version: 1.1.1020-dev Personal

**Comment by plafosse** [comment]
Fixed in 1.1.1133

**Comment by thel3l** [comment]
AWESOME <3
