### ISSUE TITLE
Clean up zero byte files in PDB Loader plugin

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#887]
When loading a PDB, the plugin first attempts to download `file.pd_` from the symbol store, and if this request results in a 404 error, then `file.pdb` is attempted. However, this leaves a zero byte `file.pd_` sitting in the module's PDB directory. It's a minor thing, but the plugin should clean up after itself if it creates a file and then bails.

**Comment by plafosse** [comment]
Fixed in 1.1.1118
