### ISSUE TITLE
Jump to Type from Disassembly/Type Searching

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#888]
Couldn't find an existing issue for this, but I wanted to make sure that these features were on the radar for the upcoming UI changes. I'd like to be able to double-click a type in disassembly and jump to the type's definition in the Types window. Additionally, there is no way to search for a type in the Types window like one can do with the function list pane. Both of these would make it way more convenient to work with types.

**Comment by bpotchik** [comment]
Fixed in build 1.1.1317-dev.
