### ISSUE TITLE
AArch64 WZR/XZR Lifting Optimizations

### ISSUE THREAD

**Issue by grant-h** [Vector35/binaryninja-api#891]
While reverse engineering an Android native binary I came across this MLIL:

![image](https://user-images.githubusercontent.com/3030665/34006170-6ba6db22-e0cb-11e7-9c72-87de611f20e9.png)

Which is this LLIL:
![image](https://user-images.githubusercontent.com/3030665/34006232-99a0fb20-e0cb-11e7-93c0-9ab74eab0c00.png)

And this ASM:
![image](https://user-images.githubusercontent.com/3030665/34006257-aa3b8c34-e0cb-11e7-82bb-079ff76c88a5.png)

These `ORR` instructions are 32-bits (WZR vs XZR), which means that they are effectively an assignment statement (zero | something) as the upper 64-bits of the assigned register is zeroed. The LLIL is correct but the MLIL could be improved to recognize these as assignment statements or merely as constant values. This would improve the value set analysis of the destination variables and prevent `<undetermined>` from being returned by `get_parameter_at`.

**Comment by rssor** [comment]
Fixed in build 1080.
