### ISSUE TITLE
flesh out API documentation

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#900]
There are many missing sections of the API documentation.  This is bad, they should be filled out, and more examples should be included. Related to #452 but separate.

**Comment by verylazyguy** [comment]
https://api.binary.ninja/binaryninja.binaryview-module.html#binaryninja.binaryview.BinaryView.parse_expression is not formatted very well

**Comment by psifertex** [comment]
Thanks, fixed that one up in particular though I'm not going to make a special build so it'll land whenever we next do a dev build.

**Comment by verylazyguy** [comment]
looks like all the .. note:: and .. warning:: sections are also formatted wrong, at least in the binaryview module

https://api.binary.ninja/binaryninja.binaryview-module.html#binaryninja.binaryview.BinaryView.perform_get_length

**Comment by psifertex** [comment]
These were fixed a few weeks ago on dev.  We only merge dev docs to the website on stable boundaries, but if you use the help menu you should be able to see the fixed version
