### ISSUE TITLE
Enum creation in Raw BinaryView crashes

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#904]
Version 1.1.1039-dev crashes when creating an enum in a Raw BinaryView. Steps to reproduce:

1. Create a new empty bndb
2. Open the Types view
3. Right Click and select `Insert a new Type`
4. Name it `a`
5. Fill in the type with the following:
```
enum {
a1,
a2};
```
6. Click `Create`

Binary Ninja will crash. This does not happen if the same steps are performed in an ELF bndb.

**Comment by bpotchik** [comment]
Fixed in build 1.1.1042-dev.
