### ISSUE TITLE
user configurable python

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#905]
Allow the user to specify a setting of a specific python. Would allow for work-arounds for problems with linking (#897), solve #844, and even obviate #6 to some degree.

**Comment by rssor** [comment]
Added as an option in `settings.json` as of build 1.1.1220-dev.

As an example, to have the UI use homebrew Python on macOS:

```
    "python" :
    {
        "interpreter": "/usr/local/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib"
    }
```
