### ISSUE TITLE
Analysis Limits

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#908]
For extremely large basic blocks or extremely large functions with lots of basic blocks, we should not run any analysis by default bur rather require user interaction or a specific API call to continue analysis. 

Adding upper limit on analysis time for a specific function may also be a related feature that would help for pathalogical cases.

**Comment by bpotchik** [comment]
Added in build 1.1-1236-dev.
New options and API's exist to set analysis limits. You can set options in settings.json. The following settings have been added:
"max-function-analysis-time" : <default value of 0 (disabled)> time in milliseconds
"max-function-size" : <default values of 65536> specifies size in bytes. (added by rusty couple months ago)

The quick on new APIs:
<BinaryViewObject>.analysis_info()
<BinaryViewObject>.parameters_for_analysis (property and setter)
<FunctionObject>.analysis_skip_reason()

These new capabilities may undergo additional changes and documentation is forthcoming. If you have specific questions or needs catch me in the binary ninja slack.
