### ISSUE TITLE
get_section_by_name python api broken

### ISSUE THREAD

**Issue by camjjack** [Vector35/binaryninja-api#909]
A recent update to the python api broke get_section_by_name. This can be reproduced by the following in the python console (with a valid elf loaded):

        bv.get_section_by_name('.text') #or any section name that exists.

The Error returned is:

    ....inaryview.py", line 3401, in get_section_by_name
        section_list.autoDefined)
    NameError: global name 'section_list' is not defined

autoDefined was added to section_list in a number of places in commit b207c76729df133c7b6fc4bc9f1abb6948ae6438 , however section_list was always undefined in this function and now that a property is referenced it errors.

**Comment by bpotchik** [comment]
Fixed in build 1.1.1043-dev.
