### ISSUE TITLE
document the ctrl+] ctrl+[ shortcuts

### ISSUE THREAD

**Issue by whitequark** [Vector35/binaryninja-api#915]
Personally I've found it very annoying that only Back had a shortcut, and actually was about to fix that, but turns out you already had symmetric shortcuts for Back and Forward, just didn't document them...
![screenshot_20180115_171247](https://user-images.githubusercontent.com/54771/34954167-556738ec-fa17-11e7-9773-3deef07805e6.png)

**Comment by psifertex** [comment]
Fixed in offline docs on dev -- my local build isn't working right now but the next time I push the docs to the online site, the change will go live there too. Thanks for the suggestion.
