### ISSUE TITLE
exceptions in plugin is_valid function during startup deadlock the GUI

### ISSUE THREAD

**Issue by whitequark** [Vector35/binaryninja-api#917]
Looks like what happens is:
  * an error is generated even before the main window is made visible
  * `MainWindow::checkForErrors()` takes the log mutex, discovers that there are errors, runs `viewLog()`, thus making visible the entire widget stack visible
  * `MainWindow::updateStatus()` is eventually called, calling `PluginCommandMenu::update()`
  * `PluginCommandMenu::update()` tries to call is_valid again, generating the same error
  * the error handler tries to take the log mutex and deadlocks
I suggest dropping the log mutex before calling `viewLog` in `checkForErrors`. Did you perhaps write something like...
```
void MainWindow::checkForErrors() {
  std::lock_guard<std::mutex> guard = logMutex.lock();
  if(this->newWarnings > 0) {
    this->logStatusWidget->incrementWarningCount(this->newWarnings);
    this->newWarnings = 0;
    viewLog();
  }
}
```
This nicely illustrates one pitfall of RAII.

**Comment by plafosse** [comment]
We've rearchitected the log so that it no longer pops up, so this is no longer an issue. Thanks for filing and issue, and sorry it took so long to respond :)
