### ISSUE TITLE
Crash at startup, caused by Access Violation Exception

### ISSUE THREAD

**Issue by samsonpianofingers** [Vector35/binaryninja-api#919]
Binja is crashing at startup on my Toshiba Satellite L50D
I investigated with x64dbg
it is crashing due to an Access violation exception at an instruction inside arch_arm64.dll
![image](https://user-images.githubusercontent.com/23288711/35075401-f161ecd4-fc46-11e7-9def-3705429d7f0d.png)
The instruction is
`movups  xmmword ptr ds:[rbx], xmm0`
RBX = 0x1 at point of crash, so it accesses invalid memory
No doubt the bug occurs before the actual crash.
I've included suspected call stack frame, and a debugging image
![image](https://user-images.githubusercontent.com/23288711/35075446-24f79e2c-fc47-11e7-9a5c-ca606bc6fe2b.png)
![image](https://user-images.githubusercontent.com/23288711/35075471-43a2674e-fc47-11e7-9307-76b2b79a4747.png)

I will help as much as I can to fix the issue, as I can't use binary ninja until it is fixed

**Comment by psifertex** [comment]
I've edited your comment -- please don't post binary ninja binaries in a public repository. 

This is most likely caused by a corrupted updated that must have failed. Can you please re-download a fresh install and re-install? You can use https://binary.ninja/recover/ to get fresh download links.

**Comment by samsonpianofingers** [comment]
My deepest apologies @psifertex, it will not happen again

Thank You for your help and moderation
It seems that the reinstall has not fixed the issue
I watch it in process hacker, and the process dies shortly after starting

**Comment by samsonpianofingers** [comment]
I managed to fix it and it is now running
deleted the plugins folder in appdata, obviously something was wrong with my plugins stored there, The actual binary ninja software was fine
Thanks again @psifertex

**Comment by psifertex** [comment]
Glad to hear it, thanks for letting us know.
