### ISSUE TITLE
Custom Hotkeys

### ISSUE THREAD

**Issue by CryptXor** [Vector35/binaryninja-api#92]
Something worthwhile to do would be porting the hotkeys into the context menu. Sometimes, I (personally, but I don't think I am singled out in this instance), tend to use my mouse and context menus to navigate around in preference to keyboard hotkeys.

For example: At the moment, from my explorations at least - unless I am missing it and it is staring me in the face - the only way to return to a previous location or "go back" is via ESC on the keyboard.

**Comment by psifertex** [comment]
Navigation in particular we have a different plan for. At some point we want to have all hotkeys controlled via the advanced config (#126)

**Comment by psifertex** [comment]
Updating for 1.2 and renamed to describe our plans for a custom hotkey system that supports:

[ ] user customizable hotkeys
[ ] hotkeys for navigation
[ ] hotkeys for plugins

**Comment by psifertex** [comment]
Part of #803

**Comment by plafosse** [comment]
This feature will also include a command palette where hotkeys and other commands can be discovered as is mentioned in #481

**Comment by D0ntPanic** [comment]
Added in build 1457. Currently controlled by a json file (see help documentation for examples). A UI for setting hotkeys will be added in the future.
