### ISSUE TITLE
Possible memory leak when batch processing

### ISSUE THREAD

**Issue by janfrancu** [Vector35/binaryninja-api#926]
Running repeated load and analysis of one binary causes slow but steady grow of memory usage and eventually the process is killed by Ubuntu. I have encountered this when analysing about a thousand binaries, however it fails even with repeated analysis of one binary using the following script:

```
import binaryninja as bn

numRepeats = 1000
filename = '24c5ac718f3cef2b43f9d607d1feeb244867b8dae405c5668bda26ccabe161ea'

for i in range(numRepeats):
    print('_____ i = ' + str(i))
    bv = bn.binaryview.BinaryViewType['PE'].open(filename)
    print('Project loaded.')
    bv.update_analysis_and_wait()
    print('Analysis done.')
```

**Comment by D0ntPanic** [comment]
Fixed in build 1111, but you must call `bv.file.close()` after you are done with a binary in any batch processing script.
