### ISSUE TITLE
Wrong `mfence` disassembly in x86-64

### ISSUE THREAD

**Issue by bulzika** [Vector35/binaryninja-api#927]
Hi,
I'm working with 64-bit elf file, x86 architecture. The binary file contains `mfence` instruction (`0F AE F0`). Binary Ninja, however, thinks that only the first two bytes (`0F AE`) are `mfence`, then encounters `F0` byte and stops in the middle of the function.

Binary Ninja Version: 1.1.1038 Personal, 64b2574c
Platform: Windows 10

**Comment by bpotchik** [comment]
Fixed in build 1.1.1065-dev.
