### ISSUE TITLE
Spontaneous MLIL-SSA Variable Generation

### ISSUE THREAD

**Issue by nshp** [Vector35/binaryninja-api#929]
Database: http://cyberjes.us/libxul-new.bndb
Address: 0x9621ef

`rax_5#30` appears out of nowhere in a store expression. Looks like maybe a Phi instruction creating `rax_5#30` from `rax_5#27` and something further back is missing here?

**Comment by rssor** [comment]
Unable to reproduce this -- can you confirm whether or not this is still present?

**Comment by nshp** [comment]
I don't see examples in the same place. I made a few new bndbs today, I'll run some tests over them tomorrow to make sure there aren't other occurrences.

**Comment by nshp** [comment]
I was unable to track this down today. There's an annoying element of nondeterminism here - I found another place where this happened, but then in messing with the python console trying to debug it, binja decided to reanalyze the function I was looking at and fix it. I'll do more looking tomorrow.

**Comment by plafosse** [comment]
Unable to reproduce this issue marking as closed unless others are running into this as well.
