### ISSUE TITLE
Phi nodes missed in dead store elimination

### ISSUE THREAD

**Issue by nshp** [Vector35/binaryninja-api#930]
I've noticed that many (if not all) dead MLIL variables created by phi expressions are never cleaned up. Is this an oversight?

Example: http://cyberjes.us/cat @ 0x36e9

**Comment by plafosse** [comment]
This isn't an oversight just an optimization. SSA variables have a liveness boolean now that allows you to query to see if they are actually dead stores. As we might eventually fix this I'm going to leave this ticket here.

**Comment by plafosse** [comment]
We no longer have plans to fix this.
