### ISSUE TITLE
Improved parameter validation in python API

### ISSUE THREAD

**Issue by lucasduffey** [Vector35/binaryninja-api#935]
**OS:** Ubuntu 16 LTS
**Binja Version:** Dev

# repro
```
~/binaryninja/binaryninja $(which ls)

# pretty sure the first "None" is the issue.
bv.add_user_section(None, 0, 0xFFFFFFFF, SectionSemantics.ReadWriteDataSectionSemantics) 
```

**Comment by lucasduffey** [comment]
going to check if it works on other binaries too

**Comment by lucasduffey** [comment]
going to make sure it's latest version. Looks like my license is having issues.

**Comment by plafosse** [comment]
This issue is present in quite a few APIs we're going to make this ticket represent all of these issues.

**Comment by plafosse** [comment]
This issue has been resolved.
