### ISSUE TITLE
Analysis isn't disassembling some instructions

### ISSUE THREAD

**Issue by justinmiller61** [Vector35/binaryninja-api#937]
Not sure what the root of this is or if it's covered by another ticket, but if you analyze the attached binary in Binary Ninja, the instructions at 0x9731109 appear as garbage, but if you disassemble with objdump, you can clearly see there is a call to mprotect that Ninja is missing.
[aeg-binja.zip](https://github.com/Vector35/binaryninja-api/files/1729964/aeg-binja.zip)

**Comment by bpotchik** [comment]
Please run linear sweep on the binary manually. We are currently in the process of adding options to run linear sweep by default. You can run linear sweep from Tools...Run Analysis Module...Linear Sweep.
