### ISSUE TITLE
Incorrect type inferred for local variable in x64

### ISSUE THREAD

**Issue by quickcoldthought** [Vector35/binaryninja-api#940]
I've shared a binary with Peter called libips-bug.so
In that binary if you create a function at address sub_263C90 0x263C90
There appears to be a bug with var_108's inferred type being int32_t instead of int64_t
see instruction at 0x26802b

```
>>> current_mlil.ssa_form[10237].operation
<MediumLevelILOperation.MLIL_SET_VAR_SSA: 101>
>>> current_mlil.ssa_form[10237].size
8L
>>> current_mlil.ssa_form[10237].src
<il: var_108#18:0.q>
>>> current_mlil.ssa_form[10237].src.operation
<MediumLevelILOperation.MLIL_VAR_SSA_FIELD: 107>
>>> current_mlil.ssa_form[10237].src.size
8L
>>> current_mlil.ssa_form[10237].src.src
<ssa <var int32_t var_108> version 18>
>>> current_mlil.ssa_form[10237].src.src.var.type.width
4L
```

![screen shot 2018-02-22 at 12 59 38 pm](https://user-images.githubusercontent.com/26824362/36558328-50c2250a-17d0-11e8-8235-a0f97a19ea44.png)

on build 1062

**Comment by psifertex** [comment]
So analysis has changed considerably since this issue was filed. Among other issues, that function is now automatically created. In particular, the variable created there is now actually a `void*` which is the correct size for this platform.
