### ISSUE TITLE
Lifting issue: int 0x29 in Windows. (fastfail)

### ISSUE THREAD

**Issue by gynophage** [Vector35/binaryninja-api#941]
int 0x29 isn't lifted as fastfail in Windows applications.

0x18000441d in the attached DLL has such an instruction.

https://msdn.microsoft.com/en-us/library/dn774154.aspx

[pyvex.zip](https://github.com/Vector35/binaryninja-api/files/1735016/pyvex.zip)

**Comment by bpotchik** [comment]
Fixed in build 1.1.1065-dev.
