### ISSUE TITLE
Memory leaks in new parts of the API

### ISSUE THREAD

**Issue by nshp** [Vector35/binaryninja-api#942]
It looks like there are a few memory leaks / asymmetries in code recently added to the API:

- `BNGetArchitectureRegisterStackName` and `BNGetArchitectureIntrinsicName` appear to be called without ever freeing the returned strings
- `BNGetAllArchitectureRegisterStacks` and `BNGetAllArchitectureIntrinsics` don't even have corresponding free functions. This may not matter in the Python API where these are called in `Architecture.__init__`, but in my own code I'm stuck calling `BNFreeRegisterList` to free the intrinsics list, because the types happen to match up.

**Comment by psifertex** [comment]
Small update to mention that `BNGetAllArchitectureIntrinsics` does need to get fixed (leaving open because of that), but the rest are not actually leaks because of the way the wrapper generator works.

**Comment by psifertex** [comment]
Rusty fixed this in the middle of a recent refactor.

**Comment by rssor** [comment]
To expand slightly, `BNGetArchitectureRegisterStackName` (and other API calls that return strings) immediately duplicate the string from the core and then free it -- this happens in `_binaryninjacore.py` transparently, so there is no leak.
