### ISSUE TITLE
Unsigned Divides in LowLevelILFunction python api are signed

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#943]
Looks like a copy paste issue.

**Comment by psifertex** [comment]
Thanks, fixed in 1058.

**Comment by pmackinlay** [comment]
This exact same problem applies to modulo operations as well - I was expecting them to be corrected at the same time, but unfortunately that's not the case.

**Comment by psifertex** [comment]
I just saw a single modulo one that was wrong. Did I miss one? (Just committed that one)

**Comment by psifertex** [comment]
*sigh* Nevermind, my previous search missed it. Got them both.
