### ISSUE TITLE
call xref is type mismatched for function signature in x64

### ISSUE THREAD

**Issue by quickcoldthought** [Vector35/binaryninja-api#948]
In the binary I shared with Peter, libips-bug.so there is a function at 0x19d000 that has a call at address 0x19d00d to sub_170830 .  sub170830 takes three agruments and binja knows this.
It appears this mismatch may occur because 0x19000 doesn't alter the values of it's passed in arg2 and arg3 - no reads or wites to the rsi and rdx registers, it just passes them through to the function it calls. 

This means that if we grab the mlil ssa form IL for the call at 0x19d00d
call_il.params  is a list containing only arg1 from rdi 

For our purposes this breaks tracing the data flow across function calls in binja.

![screen shot 2018-02-21 at 12 56 47 pm](https://user-images.githubusercontent.com/26824362/36499624-79acbdd2-1707-11e8-9e61-fb1951ea5f52.png)

**Comment by amatus** [comment]
Minimal test case:
```
_start:
call foo
ret

foo:
mov eax, dword ptr [rdi]
jmp memcpy
```
Here the type of `foo` is guessed to be `int64_t foo(int32_t *arg1)` but the call passes no arguments.

**Comment by rssor** [comment]
I believe this has been addressed with a number of changes to function type resolution over the last few months -- it no longer repros on this binary (and also per discussion on slack ~2 weeks ago).
