### ISSUE TITLE
Simple x64 binary: There is no dead variable elimination? Memory is versioned for no reason? Return variable is missing?

### ISSUE THREAD

**Issue by nshp** [Vector35/binaryninja-api#952]
In this tiny binary: http://cyberjes.us/retn

* Constants propagated without squashing useless intermediate variables: zero is `rax = 0; return 0` for some reason
* Spurious memory versioning: `call zero` apparently versions memory without touching memory
* Return variable missing: The 0 returned by zero is propagated into the syscall argument, but there is no `rax = zero()`.

**Comment by plafosse** [comment]
All calls version memory, and dead variables are more aggressively eliminated in HLIL #1383 which is currently being developed.
