### ISSUE TITLE
data flow: possible values not constrained by control flow

### ISSUE THREAD

**Issue by pmackinlay** [Vector35/binaryninja-api#953]
Binary Ninja Version: 1.1.1062-dev Personal, 5e57b82d
Platform: Windows 10 (10.0)

In the LLIL graph shown, I expected the possible values for r0 to be constrained at 2 (i.e. == 3), but ```current_function.lifted_il[2].operands[0].possible_values``` returns ```<undetermined>``` instead.

![image](https://user-images.githubusercontent.com/352356/36526939-9b0a05bc-17e2-11e8-8a6d-ca501101c33f.png)

**Comment by bpotchik** [comment]
Fixed in build 1.1.1065-dev.
