### ISSUE TITLE
MLIL_VAR size vs var size mismatch

### ISSUE THREAD

**Issue by amatus** [Vector35/binaryninja-api#955]
Loading the following code into binja
```
_start:
mov  ebp,esi
test   edi,edi
jz     l1
lea    edi,[rsi-0x1]
l1:
ret
```
creates an MLIL operation
```
rdi = zx.q((arg2 - 1).d)
```
where the `arg2` is an MLIL_VAR operation of size 8 but arg2 is a var of type int32_t which has a width of 4. The guessed type comes from the `mov ebp, esi` instruction.
The MLIL_VAR operation size should match the type width of the src var.

**Comment by amatus** [comment]
Here the guessed type from `mov ebp, edi` keeps effecting rdi even after it's been written to as a qword creating an MLIL_VAR size mismatch were the MLIL size is 4 but the var type width is 8:
```
mov ebp, edi
mov rdi, [rsp-8]
call free
ret
```
```
>>> current_mlil[2]
<il: rax = 0x4002c0(rdi)>
>>> current_mlil[2].params[0].operation
<MediumLevelILOperation.MLIL_VAR: 8>
>>> current_mlil[2].params[0].size
4L
>>> current_mlil[2].params[0].src.type.width
8L
```
The size should be 8.

**Comment by amatus** [comment]
Here's one that creates a MLIL_SET_VAR with incorrect size:
```
test edi, edi
jz l1
mov edi, esi
l1:
movsxd rax, edi
ret
```
```
>>> current_mlil[3]
<il: arg1 = zx.q(arg2.esi)>
>>> current_mlil[3].operation
<MediumLevelILOperation.MLIL_SET_VAR: 1>
>>> current_mlil[3].size
8L
>>> current_mlil[3].dest.type.width
4L
```

**Comment by plafosse** [comment]
As of version 2.1 this issue has been resolved.
