### ISSUE TITLE
[Help -> Open SCC Reference] Doesn't open the SCC docs

### ISSUE THREAD

**Issue by rmbreak** [Vector35/binaryninja-api#956]
Binary Ninja Version: 1.1.1038 Personal, 64b2574c
Platform: Windows 10

procmon shows attempt to open `C:\Program Files\Vector35\BinaryNinja\scc-docs\index.html`, but `\scc-docs\` doesn't even exist on my filesystem.

**Comment by hdarwin** [comment]
there is scc-docs on linux version.

**Comment by gynophage** [comment]
+1

**Comment by Arcnor** [comment]
This seems to still be happening?

**Comment by psifertex** [comment]
On windows as well?

**Comment by Arcnor** [comment]
Yes

**Comment by psifertex** [comment]
Thanks for the reminder, the next dev build, version 1299 should contain scc documentation on all platforms.
