### ISSUE TITLE
LowLevelILOperation.LLIL_FLAG_COND operand has 4 elements

### ISSUE THREAD

**Issue by krx** [Vector35/binaryninja-api#958]
Running into this issue when trying to iterate over `lifted_il`

The values in ```LowLevelILOperation.LLIL_FLAG_COND: [("condition", "cond", "semantic_class", "sem_class")]``` try to be unpacked here: https://github.com/Vector35/binaryninja-api/blob/dev/python/lowlevelil.py#L361
resulting in `ValueError: too many values to unpack`

I've temporarily avoided the problem by changing the line to `name, operand_type = operand[:2]`, but that's probably not ideal

**Comment by D0ntPanic** [comment]
Fixed in build 1068
