### ISSUE TITLE
libcurl name resolution timeout triggers some broken longjump

### ISSUE THREAD

**Issue by nshp** [Vector35/binaryninja-api#962]
When binja tries to update and the resolution for master.binary.ninja *times out* -- not when it fails -- libcurl's alarmfunc aborts due to some sort of longjmp issue. I don't have the exact error on hand anymore, but I will try to reproduce again later and update.

A workaround was to add a dummy master.binary.ninja entry in /etc/hosts.

**Comment by bpotchik** [comment]
Fixed in build 1.1.1229-dev. Proxy support has been added as well.
