### ISSUE TITLE
Support adding additional registers and intrinsics with Python architecture hooks

### ISSUE THREAD

**Issue by D0ntPanic** [Vector35/binaryninja-api#963]
You can add additional registers or intrinsics using architecture hooks in C/C++, but this is not yet possible in a Python architecture hook. This is technically possible but is not yet implemented.

For now, if you need to add additional registers or intrinsics in an architecture hook, use the C/C++ API.

**Comment by amtal** [comment]
Intrinsics also aren't traversed by `vars_written` and `vars_read` properties the way `MLIL_CALL`/`MLIL_CALL_SSA` are.

**Comment by plafosse** [comment]
We don't plan on continuing developing python architecture hooks as we have now open sourced all of our architecture modules.
