### ISSUE TITLE
assemble in PPC

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#964]
Inline editing, assembling, and right-click patch NOP are not implemented in PPC.

**Comment by lwerdna** [comment]
The nop and assemble are implemented in 766b3584e028fe007d483157050e863d48d53b8e.

Note that PPC assembler dialogue obeys the LLVM syntax which differs from what you see in disassembly. For example the disassembly `lis r8, 0x1000` requires you to enter `lis 8, 1000` (isolated numbers indicate registers).

**Comment by lwerdna** [comment]
LLVM won't accept a numerical displacement for branch, like `b -0x20` but Ben Rodes found that if you make a little expression out of it, like `b -1*0x20` it's accepted. Make sure the result would be on 4-byte boundary.

**Comment by lwerdna** [comment]
Invert branch and skip-and-return-value are implemented in 3364121630ce7d2d317e2d146c4f71f21bd557d3, closing! Hope it builds!
