### ISSUE TITLE
Jump table not being detected

### ISSUE THREAD

**Issue by krx** [Vector35/binaryninja-api#966]
I'm finding that some jump tables don't get detected, so a block ends in a `jmp` with no outgoing branches

Example binary: https://github.com/trailofbits/mcsema/blob/master/tests/test_suite/amd64/linux/bin/ls_amd64

Some spots where this is happening:
`main : 0x402c9a`

**Comment by bpotchik** [comment]
The jump table at 0x402c9a is fixed in build 1.1.1073-dev.
