### ISSUE TITLE
Can we have renaming/rewriting as IDA has?

### ISSUE THREAD

**Issue by Maykeye** [Vector35/binaryninja-api#971]
In IDA I can rename `rbx` to `rbx.dst` to not forget what is used for in given block ofcode.

Similarly, integer literal `40` can be rewritten as `ENUM_MEMBER + 15*2`. 
ILs are trees already anyway. Might as well rewrite trees/store another trees for display purposes.

Renaming almost can be done now in MLIL as registers are being split into rcx_1, rcx_2 in IL and  can be renamed. However, firstly sometimes registers are split too conservatively. For example. in screenshot of `/usr/bin/yes` register `rcx_4 ` is used for counter(instruction 67) and for flag(instructions 69,71) and I can't tell MLIL to split rcx_4 into new rcx_5 (which is safe to do after loop) which  can be renamed, and secondly it would be nice to also rename regs in LLIL

![a](https://user-images.githubusercontent.com/13607441/36833290-14ee5a4c-1d59-11e8-95ed-dc931c06e40e.jpg)

**Comment by psifertex** [comment]
The issue with that particular example is the partial register access -- unfortunately right now it doesn't trigger a split of the variable. 

As for renaming in assembly -- would you prefer it behave globally the way IDA does, or the way you're asking about in MLIL where it is currently split on uses?

**Comment by Maykeye** [comment]
> As for renaming in assembly -- would you prefer it behave globally the way IDA does, or the way you're asking about in MLIL where it is currently split on uses?

Globally/usage-based/globally-but-borrow-default-names-and-ranges-from-MLIL 
IMO anything is fine as long as the names can be manually erased to base form(rcx_4 into rcx), split into new names(rcx_4 into rcx_4 and rcx_5), redefined manually at any point without system getting in a way.

**Comment by psifertex** [comment]
We support this for MLIL and HLIL and we have no plans to allow it at the assembly level.
