### ISSUE TITLE
Fixed-iteration loops unaccounted for in flag dataflow

### ISSUE THREAD

**Issue by nshp** [Vector35/binaryninja-api#972]
This is probably hard to get right and I don't expect a quick solution.

Assembly:
![assembly](https://ptpb.pw/F72Y)

LLIL:
![llil](https://ptpb.pw/-Fnz)

The `seta` at 0xf7aa is using CF from the `CMPSB` immediately preceding it. While binja catches that, it also reaches all the way back to the `test` at 0xf786, because it thinks the "conditional" loop may not run at all -- i.e. rcx might be 0, the cmpsb may not set/clear CF. In this case, however, rcx is unconditionally set to 5 at 0xf799, meaning binja *could* make the assumption that CF is always written by the loop.

Loops are hard.

**Comment by plafosse** [comment]
Doing this would be very expensive. We're not planning on doing this any time soon.
