### ISSUE TITLE
Add Function.get_medium_level_il_at() API

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#975]
As it stands, there's no `Function.get_medium_level_il_at` method, which causes issues with `PluginCommand` callbacks that are registered for an address. The only way to retrieve the MLIL for the address the plugin is invoked from is to call (assuming only one function) `bv.get_containing_functions(addr)[0].get_low_level_il_at(addr).medium_level_il`, and this can fail if the plugin is invoked from within the MLIL view on an instruction that has been optimized, such as an if expression.

**Comment by plafosse** [comment]
You can now register plugins for MLIL instructions and function which is the supported way handling this scenario.

**Comment by joshwatson** [comment]
I would argue that there are still certain situations in which this API would be useful; specifically, this use case:

```python
for ref in bv.get_code_refs(addr):
    il = ref.function.get_medium_level_il_at(ref.address)
    print(il)
```
