### ISSUE TITLE
PPC "assemble at instruction" support

### ISSUE THREAD

**Issue by bdrodes** [Vector35/binaryninja-api#977]
Assembling an instruction at a given address in PPC ignores the specified target address.

For example, if assembly 'asm' is assembled at address 'addr':
     bv.arch.assemble(asm,addr)
The address is ignored. The assembly is assembled as though it were at address 0. This is problematic when assembling PC relative instructions, like branches. If the address is ignored, the destination of the branch is treated like a relative offset. In many cases, the value is too large to be syntactically correct, resulting in assembly failure. 

A workaround is to identify all such instructions and to generate the PC relative address in the instruction prior to assembly, and (for good measure) not provide the address.

**Comment by lwerdna** [comment]
fixed for a while in PPC, this was one of the inspiration issues of the whole "genetic assembler" effort
