### ISSUE TITLE
API Cursor Object

### ISSUE THREAD

**Issue by gynophage** [Vector35/binaryninja-api#98]
A cursor object, or a way to highlight certain lines in a disassembly, and force the UI to "snap" to a spot would be pretty cool - it would be nice to be able to have binary ninja following along WinDBG/OllyDBG/GDB/OMGWTFBBQ breakpoints/single steps.

**Comment by psifertex** [comment]
This was completed with the addition of `here` property in the console as well as the highlighting API.
