### ISSUE TITLE
MLIL '+' instruction doesn't evaluate a sum of 2 constant values

### ISSUE THREAD

**Issue by realnp** [Vector35/binaryninja-api#980]
![default](https://user-images.githubusercontent.com/24685834/37258418-ca548e6a-2588-11e8-834d-0f1f8e750715.png)
![default](https://user-images.githubusercontent.com/24685834/37258431-f7d57a2a-2588-11e8-8537-872c869e0c65.png)
![default](https://user-images.githubusercontent.com/24685834/37258434-198791e4-2589-11e8-9f38-b277779063f8.png)

Binary Ninja Version: 1.1.1038 Personal, 64b2574c
Platform: OS X 10.13

**Comment by bpotchik** [comment]
Have you tried the latest build on the dev channel?

**Comment by psifertex** [comment]
Just as an example, those exact constants do appear to work just fine on dev unless there's something else going on there: 

<img width="837" alt="screen shot 2018-03-11 at 8 07 44 pm" src="https://user-images.githubusercontent.com/140215/37260305-f5633e24-2567-11e8-8769-d556223ea238.png">

**Comment by realnp** [comment]
Well, updating to the latest dev release fixes it:) Thanks
