### ISSUE TITLE
Linear Sweep misses mov edi,edi function heads

### ISSUE THREAD

**Issue by mothran** [Vector35/binaryninja-api#982]
Binja Version: 1.1.1088-dev

Input binary, Tcpview.exe (https://docs.microsoft.com/en-us/sysinternals/downloads/tcpview)
Sha256: c00d90c50a5e05d270b796645d5f12dee94a31ca94b8ddc90c91af1f9e208850

Example address: 0x41f2cc

When running the linear sweep plugin with a windows x86-32 binary, if a function does not have any references the linear sweep will ignore 'mov edi,edi' and start the function at the next instruction.

**Comment by bpotchik** [comment]
Fixed in build 1.1.1102-dev.
