### ISSUE TITLE
Unexpected Memory Consumption

### ISSUE THREAD

**Issue by bdrodes** [Vector35/binaryninja-api#985]
The code below was developed to pull out IL instructions from ordinary basic blocks. 
```
def get_il_instructions_from_bb(bb):
    instrs =[]
    func = bb.function 
    bv = func.view
    cur_addr = bb.start
    while cur_addr != bb.end:
        assert cur_addr < bb.end
        llil_instr = func.get_low_level_il_at(cur_addr) 
        instr_len = bv.get_instruction_length(cur_addr) 
        cur_addr += instr_len
        if instr_len == 0:
            print "IL ERROR: IL ABORT: failed to recover instruction length at addr: " + hex(cur_addr) + " for function: " + str(bb.function.name)
            break
        if llil_instr is None:
            print "IL ERROR: failed to recover IL instruction at addr: " + hex(cur_addr) + " for function: " + str(bb.function.name)
            continue
        instrs.append(llil_instr)
    return instrs
```

Repeatedly calling the function and appending the results to the list results in massive memory consumption. For example, getting ~100k instructions using the following code on a large program takes more than 10 minutes to complete and consumes 4.7 gigs of memory. 

While other solutions exist for getting IL from basic blocks, the issue here is there appears to be some massive inefficiency related to pulling IL instructions at a given address. 

The following code may be unrelated, however, it illustrates another potential memory consumption issue related to getting IL instructions: 

```instrs1=[]
for cnt in range(0,10000)
    instrs.append(bv.llil_instructions.next())
```

The code only gets the first LLIL instruction repeated (granted in a strange way); however, this code consumes ~3gigs of memory for 10k repeated instructions.

**Comment by plafosse** [comment]
The only way to fix this is to not hold on to a reference to all of the function. We can't really fix this though we may be able to incrementally improve memory performance.
