### ISSUE TITLE
need increased zoom options

### ISSUE THREAD

**Issue by lucasduffey** [Vector35/binaryninja-api#989]
need increased zoom options

If you're demoing binja, it's annoying to have to change the system resolution or font size.

I'm using Ubuntu 16 LTS

**Comment by joshwatson** [comment]
Huh?

![screen shot 2018-03-20 at 1 51 00 pm](https://user-images.githubusercontent.com/5834130/37682092-c6a24ffa-2c45-11e8-8a96-517e8923509d.png)

**Comment by joshwatson** [comment]
That's super easy to do

**Comment by psifertex** [comment]
There is an open bug elsewhere for being able to zoom in past 100% that might solve your problem too though I can't find it now. 

The only blocker is we don't want to implement it without some smart snapping/stickiness so that you can easily get back to default zoom.

**Comment by psifertex** [comment]
And yeah, I just crank font-size when I have a demo.

**Comment by lucasduffey** [comment]
ahh, I was using ctrl+scroll to zoom which has limitations

**Comment by plafosse** [comment]
Fixed in build 1.1.1133
