### ISSUE TITLE
"Favorites" or "Bookmarks"

### ISSUE THREAD

**Issue by gynophage** [Vector35/binaryninja-api#99]
It would be cool if we could "star" functions/instructions/global data structures/whatever, and save those to an analysis database.

**Comment by lucasduffey** [comment]
relevant: https://gist.github.com/joshwatson/8866ff9fd30930c85779c821f277cf58

**Comment by plafosse** [comment]
Related #458

**Comment by plafosse** [comment]
Added in 1.1.1816
