### ISSUE TITLE
Add PluginCommand.register_for_low_level_il and PluginCommand.register_for_medium_level_il

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#992]
`PluginCommand.register_for_address` in the LLIL and MLIL graph views only work on the address provided, which can be an issue if that address maps to multiple IL instructions and the user intended for it to run on an IL instruction that isn't the first one.

I'd like to have the option to directly register a plugin for a particular view, such that it is only available in the specified IL view. This also has the added benefit that a callback for `register_for_low_level_il` would easily work with Lifted IL, Low Level IL, and Low Level IL SSA form. The same for `register_for_medium_level_il`, as it would work with Mapped MLIL, MLIL, and MLIL SSA form.

**Comment by D0ntPanic** [comment]
Added in build 1159 (both for IL functions and individual IL instructions)
