### ISSUE TITLE
Allow renaming/retyping structure elements from disassembly graph

### ISSUE THREAD

**Issue by toolCHAINZ** [Vector35/binaryninja-api#994]
So, I make a structure and have it applied to something in the disassembly graph:

<img width="545" alt="assembly" src="https://user-images.githubusercontent.com/27028960/37827266-1c613e5a-2e6d-11e8-8ffc-66c59b8d9eb1.png">

<img width="327" alt="mlil" src="https://user-images.githubusercontent.com/27028960/37827265-1c482956-2e6d-11e8-8f19-10dfcd9c52cb.png">

There doesn't seem to currently be a way to edit the structure from the disassembly graph. So I can alter MLIL variable names and types, but can't change, say `rax_2->field_4` to `rax_2->bitmask`, or change the type of `rax_3->field_8` from a `uint8` to a `char`. To do that, I have to go back over to the types window and do any renaming/retyping there.

I think being able to do this from the disassembly graph would really help the structure workflow.

**Comment by plafosse** [comment]
Added in v1.1.1453
Now TypeTokens and FieldTokens will respond to the 'n' (change name) or 'y' (change type) keys.
